### ISSUE TITLE
Cherry-pick LuaJIT --version enhancement into 3.5

### ISSUE THREAD

**Issue by blueyed** [awesomeWM/awesome#1000]
https://github.com/awesomeWM/awesome/pull/996#issuecomment-231559355

**Comment by psychon** [comment]
Thanks for the tracking issue :)

**Comment by psychon** [comment]
I cherry-picked both 97048de60e901ee2866f5011d81e791ea4c6a977 and 896eee8b1f76fc1622dbef020a364bae6addbdd2 and then didn't have any conflicts to handle, thanks to also picking the first commit. :-)
