### ISSUE TITLE
menubar does not contain items without Categories

### ISSUE THREAD

**Issue by blueyed** [awesomeWM/awesome#1007]
The following .desktop file (generated by Chromium for a web app) will be skipped by the menubar (Super-p), because it has not category:

```
#!/usr/bin/env xdg-open
[Desktop Entry]
Version=1.0
Terminal=false
Type=Application
Name=Signal Private Messenger
Exec=/usr/bin/chromium --profile-directory=Default --app-id=bikioccmkafdpakkkcpdbppfkghcmihk
Icon=chrome-bikioccmkafdpakkkcpdbppfkghcmihk-Default
StartupWMClass=crx_bikioccmkafdpakkkcpdbppfkghcmihk
```

Related code: https://github.com/awesomeWM/awesome/blob/f5f845bb73ce405a5c297ab0ac3816186daaa8d1/lib/menubar/menu_gen.lua#L109-L119

I wonder if we should just add all `Type=Application` entries, or/and look for other indicators, e.g. `StartupWMClass`?

**Comment by gutierri** [comment]
@blueyed All applications that do not follow a pattern (for example) we could put in "Other". Sounds like a good "name" for different things than the default, I do not know if AwesomeWM makes the management of these names.

What do you think?
