### ISSUE TITLE
Maximized windows dont refresh their geometry when titlebars are toggled

### ISSUE THREAD

**Issue by topisani** [awesomeWM/awesome#1021]
Output of `awesome --version`:
```
awesome v3.5.9 (Mighty Ravendark)
 • Build: Mar 12 2016 01:11:40 for x86_64 by gcc version 5.3.0 (builduser@rw)
 • Compiled against Lua 5.3.2 (running with Lua 5.3)
 • D-Bus support: ✔
```
**How to reproduce the issue:**
 1. In the default config, enable titlebars by changing `titlebars_enabled` to `true`
 2. Bind a key to `awful.titlebar.toggle`
 3. Change to floating layout
 4. Maximize a window
 5. Disable the titlebar using the key you set.

**Actual result:**
The window moves up to fill the space the titlebar occupied, Leaving space at the bottom of the screen. This space will be filled up if you unmaximize the window and maximize it again.

**Expected result:**
The window refreshed its maximized state when the titlebar was turned off, instantly filling up the space and looking like a maximized window should.

**Analysis**
The same bug happens if you toggle the statusbar with a maximized window, even when changing the border widths of a maximized client.

Interestingly, it doesnt happen with the maximized _layout_, only with maximized floating clients.

I have yet to find a function that refreshes the maximized state, and i believe this bug might not only be related to maximized clients, since, in my opinion, if a titlebar is removed, the client should fill up its space. Nomatter what, this is a problem for maximized windows.

**Edit 1**
I am running arch linux, and wanted to try this with the latest git version, so i installed `awesome-git` from the aur, which turned out to be outdated, with this version message:
```
awesome v3.5.2-1879-g78171ea (The Fox)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔
```
However, in this version this issue does not exist. I will try with the actual latest `master` branch

**Edit 2**
Seems that, in spite of the weird version string, it did clone the latest master. So, it appears this issue has been fixed already. I don't know if you want it closed since the fix is not released yet, so I'm keeping it open. Feel free to close it

**Comment by psychon** [comment]
Closing as per Edit 2.

Sorry for the weird version output. This string is automatically generated based on the latest git tag and the master and 3.5 branch diverged some time after awesome 3.5.2. Thus, we end up with a version string saying "awesome 3.5.2 plus 1879 commits, the latest of them having commit id 78181ea".
