### ISSUE TITLE
World of Warcraft (WINE) window loses its focus

### ISSUE THREAD

**Issue by poisonby** [awesomeWM/awesome#1023]
**Output of `awesome --version`:**

    awesome v3.5.9 (Mighty Ravendark)
     • Build: Mar 12 2016 01:11:40 for x86_64 by gcc version 5.3.0 (builduser@rw)
     • Compiled against Lua 5.3.2 (running with Lua 5.3)
     • D-Bus support: ✔

**How to reproduce the issue:**

~~Play the game. It doesn't really matter what you do in the game, it will lose focus regardless. It regains focus (and takes in input) when you click on the window or if you switch to another workspace and back. I've tried with windowed mode, windowed (fullscreen) mode and fullscreen mode, none of which works. I've also tried it with different layouts (tiling and floating), same result.~~

Play the game. It doesn't really matter what you do in the game, it will stop taking input from the keyboard regardless, and the sound will stop working. The game acts as if it's losing focus, but it doesn't appear to do that. It works again when you click on the window or if you switch to another workspace and back, or if you focus another window and then focus the game window again. I've tried with windowed mode, windowed (fullscreen) mode and fullscreen mode, none of which works. I've also tried it with different layouts (tiling and floating), same result.

**My rules for the window:**

     { rule = { name = "World of Warcraft" },
        properties = { floating = true,
        ontop = true,
        focus = yes } },

The rules doesn't matter, ~~it loses focus regardless~~. 

**Actual result:**

- The game does respond to mouse movement. You can hover over characters in the game with the mouse just fine.
- The game doesn't take any input from the keyboard at all, **until you click on on the game window, or if you focus something else and then focus the game window again.**
- No sound is coming from the game when this happens.
- When this happens, **awesome doesn't switch focus!**

In order to check what window awesome switches focus to, I used the code below:

```lua
client.connect_signal("focus", function(c)
    awful.util.spawn_with_shell("notify-send 'Debug' 'Window: " .. c.name .. " is now focused'")
 end)
client.connect_signal("unfocus", function(c)
    awful.util.spawn_with_shell("notify-send 'Debug' 'Window: " .. c.name .. " is no longer focused'")
end)
```

It works fine, and it shows that no other window is focused when this happens to the game.

**Comment by psychon** [comment]
Since I don't have any good ideas (and don't have the game and I'm AFK for the next two weeks), just a quick question: if WoW loses the focus, where does the focus go to? What happens if you close that other window that now has the focus?
And another one: "Loses the focus" means that "keyboard input does not go to WoW, but mouse works as usual", or what exactly do you mean by that?

**Comment by poisonby** [comment]
@psychon I've tried to pinpoint the window that gains focus but I've been unable to. When it happens, and I go to another workspace, I can see that the game window has urgent status. Other than that, I have no idea.

>And another one: "Loses the focus" means that "keyboard input does not go to WoW, but mouse works as usual", or what exactly do you mean by that?

Yes, exactly. When this happens, the game doesn't register any input from the keyboard, but you can still move the mouse around, but it's as if you're hovering "above" the window, because it doesn't actually register the movements. In order for the game itself to register mouse movement, you have to click on it, and by then it will take input from the keyboard again.

It might not even have anything to do with focus, but that's the only thing that makes sense for me.

>Edit: Oh and: What's your awesome versionYou are missing the first line ofawesome --version`.

I've updated my original post with the version. Sorry about that, and thanks for the help!

**Comment by psychon** [comment]
Another random debugging idea: Add this to your awesome config.
```lua
client.connect_signal("focus", function(c)
  print(debug.traceback(os.date() .. " Window " .. c.name .. " is now focused"))
end)
client.connect_signal("unfocus", function(c)
  print(debug.traceback(os.date() .. " Window " .. c.name .. " is no longer focused"))
end)
```
This should produce some output on every focus change together with the current time and an indication on which code caused the focus change.

Where will this output go? I'm not sure. It depends on how you start awesome. For example, if you use gdm, it might be `/var/log/gdm.log`. Someone recently reported that his awesome's output goes to the journal (`journalctl --user`). The command `lsof -c awesome` might help you in finding out where the output goes to (you are interested in the line which has something line `2w` in the fourth column..

**Comment by poisonby** [comment]
@psychon 

I did some more testing now and I was wrong about a couple of things before.

- The game does respond to mouse movement. You can hover over characters in the game with the mouse just fine.
- The game doesn't take any input from the keyboard at all, **until you click on on the game window, or if you focus something else and then focus the game window again.**
- No sound is coming from the game when this happens.
- When this happens, **awesome doesn't switch focus!**

In order to check what window awesome switches focus to, I used the code below:

```
client.connect_signal("focus", function(c)
  awful.util.spawn_with_shell("notify-send 'Debug' 'Window: " .. c.name .. " is now focused'")
 end)
client.connect_signal("unfocus", function(c)
    awful.util.spawn_with_shell("notify-send 'Debug' 'Window: " .. c.name .. " is no longer focused'")
end)
```


It works fine, and it shows that no other window is focused when this happens to the game.

**Comment by psychon** [comment]
Hm, ok... Does WoW or WINE have some kind of debug mode which might tell us what is going on on their side?

**Comment by psychon** [comment]
Does this mean that the problem went away?

**Comment by poisonby** [comment]
>Does this mean that the problem went away?

Yes, I'm not sure if it went away because I started a new rc.lua or if it went away because I upgraded from 3.5. Sorry I never updated the issue until now, I completely forgot about it.
