### ISSUE TITLE
What is actual version ?

### ISSUE THREAD

**Issue by YPetremann** [awesomeWM/awesome#1024]
Output of `awesome --version`:

awesome v3.5.2-1879-g78171ea (The Fox)
 • Compiled against Lua 5.1.5 (running with Lua 5.1)
 • D-Bus support: ✔

**Decription:**

Actual official version is 3.5.9, it get visually updates on a single branch
Git actual version, actively updated is 3.5.2 (The Fox) and that seem (I can be wrong) to get the same functionalities since 3.5.2 to 3.5.9

Additionnaly I'm using a version newer than 3.5.6 (the version provided by my system) and the only way to be in peace is to Block my package

**Comment by Elv13** [comment]
The current official release is 3.5.9
The current git master branch will be 3.6.0 and is currently 3.5.2+1850commits. Our version script use the last tag. 3.6 was branched away from "stable" after the 3.5.2 release. Sorry for the confusion. Next time, I guess once we fork 3.7 with should do it KDE style and tag 3.6.60 to avoid confusion. (or do it Gnome/GNU style use immediately tag 3.7 and use 3.8 as stable, but I hate that numbering scheme)
