### ISSUE TITLE
sticky hover question unanswered -- key to new feature

### ISSUE THREAD

**Issue by 22csnyder** [awesomeWM/awesome#1030]
Apologies in advance if this is not the place to post this. I'm a little unsure (StackOverflow, superuser, mailing list), which gives the most visibility.

I probably would have gone with SO but I found [my question exactly](http://stackoverflow.com/questions/34342984/how-to-keep-sticky-window-from-always-getting-focus-in-awesome-wm) unanswered since December '15.

As a motivating example, consider the mini-skype window (on a windows or mac desktop) that surfaces in the corner when skype is not on top. I've been working on functionality to grant this functionality to arbitrary windows (consider a video in mplayer, youtube-viewer, or the present skype implementation for linux, which lacks this function).

So far I achieve this by toggling window properties: 'floating', 'sticky', and 'ontop'. The expected behavior is to have the window always visible in the bottom right corner across all tags. I also have removed it from the task list in tags besides the original tag.

However I would like this miniwindow to not grab focus on switching tags (cmd+#). How can I fix this?

**Comment by actionless** [comment]
i guess you also need to set `.focusable` to `false`
http://new.awesomewm.org/apidoc/classes/client.html#client.focusable

**Comment by Elv13** [comment]
@22csnyder Is it solved? Can I close?
Btw,  IMO the questions on the reddit subreddit are usually answered the fastest.

**Comment by 22csnyder** [comment]
Thanks for the help. I'm almost certain this is the way to do it, but because I'm hitting a bug I might as well quickly ask. Should this property be toggled on a client by:

function(c) c.focusable=not c.focusable end

?
(Sometimes there's an explicit toggle() function)

**Comment by Elv13** [comment]
I deprecated many of the toggle functions from the next version in favor of the first syntax you showed. It is much more consistent.

**Comment by psychon** [comment]
By the way, I don't think `focusable` is writable in 3.5, but only in git/master, isn't it?

**Comment by 22csnyder** [comment]
That seems to be the bug I was running into. c.focusable prints out as "true" before and after a change. I'm a little surprised no error is raised.

**Comment by Elv13** [comment]
@22csnyder whats your Awesome version? As @psychon said, chaging this value may not be possible in 3.5.*. If there is no setter and an hardcoded getter, 3.5 doesn't raise an error. The value just falls into a black hole.

**Comment by 22csnyder** [comment]
I'm on 3.4.15. What do you recommend? Build the master branch?

**Comment by Elv13** [comment]
3.4.* isn't supported since 2012, please upgrade to the master branch. Backup your config and use the new default one. 3.4 configs are not compatible with git-master. Most of your changes can be re-incorporated later.

**Comment by psychon** [comment]
Cheap hack (that Elv13 will hate me for and that should also work on awesome 3.4):
```lua
do
  local orig_filter = awful.client.focus.filter
  awful.client.focus.filter = function(c)
    if c.sticky == true then
      return nil
    end
    return orig_filter(c)
  end
end
```
The above should make all sticky window unfocusable. Dunno if one really wants that...
