### ISSUE TITLE
Client windows move off by one pixel when clicking the titlebar

### ISSUE THREAD

**Issue by Jajauma** [awesomeWM/awesome#1039]
Output of `awesome --version`:
awesome v3.5.2-1903-ge3c24c8 (The Fox)
 • Compiled against Lua 5.1.4 (running with Lua 5.1)
 • D-Bus support: ✔

**How to reproduce the issue:**

1) Run AwesomeWM with the default config (keep the floating layout).
2) Launch xterm (menu → open terminal)
3) Move the xterm window around the screen using mouse for a while.
4) Start pressing the xterm titlebar with left mouse button and releasing it at once.

**Actual result:**
xterm window moves off by one pixel right and one pixel down each time you click the titlebar.

**Expected result:**
xterm window stays still in its position on the screen while just clicking and releasing the LMB on the titlebar.

**Additional info:**
The first bad commit appears to be cdcfb913f1e631453e5101c04ae8a590a4334e55 according to `git bisect`. (Just kill `tests/examples/awful/placement/compose.lua` if the build croaks.)

**Comment by Elv13** [comment]
Just a side note, the client size also need to be an odd number. I will add an integration test for this once I fix it. This is a rounding error somewhere in the pipeline. The commit isn't the issue. It's when the old move/resize pipeline was replaced by the new one. The current test for this used a 200x200 client and pass.

**Comment by Elv13** [comment]
Patch to break the tests with this bug:

```patch
:100644 100644 d7c8085... 0000000... M  tests/test-resize.lua

diff --git a/tests/test-resize.lua b/tests/test-resize.lua
index d7c8085..a168189 100644
--- a/tests/test-resize.lua
+++ b/tests/test-resize.lua
@@ -403,6 +403,39 @@ table.insert(steps, function()
 
     assert(c.first_tag == cur_tag)
 
+    c:geometry {
+        x      = 99,
+        y      = 99,
+        width  = 99,
+        height = 99,
+    }
+
+    return true
+end)
+
+-- Test that odd number sized clients don't move by accident
+for _=1, 15 do
+    table.insert(steps, function()
+        local c = client.get()[1]
+
+        root.fake_input("button_press",1)
+        amouse.client.move(c)
+        root.fake_input("button_release",1)
+
+
+        return true
+    end)
+end
+
+table.insert(steps, function()
+    local c = client.get()[1]
+    root.fake_input("button_release",1)
+
+    assert(c.x      == 99)
+    assert(c.y      == 99)
+    assert(c.width  == 99)
+    assert(c.height == 99)
+
     return true
 end)
 
```

**Comment by Elv13** [comment]
@Jajauma thanks a lot, you found a very old bug, dating technically from 2008! However, the rounding code changed something like 6 time since then, so at some point, the bug was probably fixed, then re-introduced. There is now a test for this, so it won't happen again.
