### ISSUE TITLE
Switching to a tag with a lot of clients is slow

### ISSUE THREAD

**Issue by blueyed** [awesomeWM/awesome#1040]
I've noticed that switching to a tag with many clients (35) is slowish (almost 1s).
The tag itself is switched immediately, but then it takes a while until the focused client is highlighted in the tasklist and the taglist icon changes.  Only after that the client on that tag is raised.

It is still slow when not using a tasklist or taglist, and with the default config.

awesome master (v3.5.2-1903-ge3c24c8-dirty)

**Comment by Elv13** [comment]
If you can manage to get Awesome+lua5.1 running, take the profiling script from my config and run it when switching tag. The output can be visualized in KCacheGrind. If it's in Lua, something will become clear. It takes some learning to see through the generated output, as it isn't representative of "reality", but in the noise, the problem pattern will be visible.

If it's on the C side, then `valgrind --tool=callgrind` will generate the KCacheGrind file.

**Comment by blueyed** [comment]
Can you provide a link to the profiling script, please?
Sounds like something that should be in the documentation/repo, too.

Apart from that: I am pretty sure that this is easily reproducible by just opening 30+ terminals (most of the clients are urxvt and then 2 firefox windows on that tag).

**Comment by Elv13** [comment]
https://gist.github.com/Elv13/b2f8c826d5d99df25585a7a376a16da8

(note, I found it on the Internet, it isn't by me)

```lua
-- utils.profile.start()
-- debug.sethook(utils.profile.trace, "crl", 1)
...
-- local t = timer {timeout=0.1}
-- t:connect_signal("timeout",function()
--     debug.sethook()
--     utils.profile.stop(_G)
--     t:stop()
-- end)
-- t:start()
```

Also, I can't reproduce, my computer may be too fast. I tried to open 100 clients in a tag and see no lag when selecting tags in Xephyr.

**Comment by psychon** [comment]
I cannot reproduce. I tried the following (save as `tests/test-many-clients.lua` and run `tests/run.sh test-many-clients.lua`) and didn't see any warnings "Main loop iteration took too long" nor did things "feel" slow. Is there something that I might be missing?
```lua
local awful = require("awful")
local test_client = require("_client")

steps = {
    function(count)
        local num_clients = 50
        if count == 1 then
            for i=1, num_clients do
                test_client()
            end
        end
        if #client.get() == num_clients then
            return true
        end
    end,

    function(count)
        if count % 2 == 0 then
            awful.tag.viewnext()
        else
            awful.tag.viewprev()
        end
    end,
}

require("_runner").run_steps(steps)
```

**Comment by blueyed** [comment]
@psychon 
Might be related to the clients?! (I was using rxvt-unicode windows mostly)
Maybe the test is also switching to fast back and forth?!

**Comment by blueyed** [comment]
It might also be related to your recent X protocol improvements, but I get the following:

```
> == Running test-many-clients.lua ==
2016-10-10 22:50:14 W: awesome: a_glib_poll:373: Last main loop iteration took 0.666302 seconds! Increasing limit for this warning to that value.
Error: timeout waiting for signal in step 2/2 (@5).
===> ERROR running test-many-clients.lua! <===
Error: timeout waiting for signal in step 2/2 (@5).
There were 1 errors!
```

The test is using the floating layout however (I had them tiled), and I could imagine that Xephyr behaves better than the real X server maybe?!

**Comment by blueyed** [comment]
However, I could not reproduce it just now.
Let's assume this was fixed in recent commits and/or a video driver update etc.

**Comment by elenapan** [comment]
Just in case anyone has the same issue, I was affected by this and my compositor (compton) was the culprit. It only happened when the tag had visible clients. If I minimized them, there was no delay switching to that tag.

As soon as compton was killed every tag switch was snappy again.

**Comment by blueyed** [comment]
@elenapan 
Thanks for the update - I am using compton usually myself, but might not have used it when trying to reproduce it the last time.
