### ISSUE TITLE
Instructions on building with alternate lua VMs?

### ISSUE THREAD

**Issue by DorianGray** [awesomeWM/awesome#1053]
I wasn't able to find any easy way to do this in any of the documentation sources. When I manually specify LUA_LIBRARY and LUA_INCLUDE_DIR in the Makefile it doesn't seem to work... the build succeeds, but it still actually uses the system lua.

CMAKE_ARGS:="-DLUA_INCLUDE_DIR=/usr/include/luajit-2.1 -DLUA_LIBRARY=/usr/lib/x86_64-linux-gnu/libluajit-5.1.so\;dl"

I also tried .a and with and without the ;dl

I should also mention, many commits ago I had this working on another machine but have since forgotten how...

**Comment by Elv13** [comment]
Hello,

You might want to take a look at
https://github.com/awesomeWM/awesome/blob/master/.travis.yml

**Comment by DorianGray** [comment]
Thanks, but that's where I got the line I pasted in my first post from... what am I missing?

**Comment by psychon** [comment]
Is cmake actually called with those arguments? You can check the contents of `build/CMakeOutput/CMakeCache.txt` (I'm not completely sure I got the file name right, but you are looking for CMakeCache.txt). It should contain lines with e.g. `LUA_INCLUDE_DIR=/usr/...`.

**Comment by psychon** [comment]
I found the reason, I think. Try replacing `$(CMAKE_ARGS)` with `${CMAKE_ARGS}`.
Also, run `cmake VERBOSE=1`. That way you should see which arguments cmake is called with (by the way, if you want, you can call cmake directly instead of using the Makefile; just do something like `mkdir my-build-dir ; cd my-build-dir ; cmake -DLUA_INCLUDE_DIR=foo ..`

**Comment by DorianGray** [comment]
CMAKE_ARGS didn't like 2 arguments in the same line for some reason. I moved it into 2 variables and it seemed to work.

Now I'm stuck with awesome crashing immediately while using luajit...

**Comment by Elv13** [comment]
What's the crash? I use it on one computer and it works. Our Travis CI report it (mostly) work. If it is a lua crash, please post stderr. If it is a core crash, please built Awesome with the debug symbols and use `gdb` `run` and  `bt full` commands.

**Comment by DorianGray** [comment]
I got a little further in testing. The build -seems- good, IE I can run awesome from the command line (awesome -k, etc). When I run it as the window manager though, it crashes and kicks me back to lightdm.

I'll try to spend some more time testing further a little later.

**Comment by DorianGray** [comment]
Aha, got it. it was errorring super early because I was missing lgi in my luajit-backed luarocks install. It works perfectly =)

For future reference... to build you need to add something like
`CMAKE_ARGS:="-DLUA_INCLUDE_DIR=/usr/include/luajit-2.1 -DLUA_LIBRARY=/usr/lib/x86_64-linux-gnu/libluajit-5.1.so"` to the top of your Makefile.

You also need to change the line that reads...
`cd ${builddir} && cmake $(CMAKE_ARGS) "$(@D)" ..`
to
`cd ${builddir} && cmake "${CMAKE_ARGS}" "$(@D)" ..`

to get the args to quote correctly.

**Comment by DorianGray** [comment]
Also, I highly recommend https://github.com/serialoverflow/awmtt to test when things are broken.

**Comment by blueyed** [comment]
@DorianGray 
> You also need to change the line that reads...

I think you should just not put quotes around it in the Makefile definition.

**Comment by DorianGray** [comment]
fair enough, either way =)

**Comment by Elv13** [comment]
Is this solved? Can I close this?

**Comment by DorianGray** [comment]
It would be nice to get this documented. I'm happy to do it once I get a few spare minutes to put together a PR. Searching github issues should be a last resort.

**Comment by psychon** [comment]
Where should this be documented? The FAQ (`docs/90-FAQ.md`)? So far this doesn't have any build-specific section. The readme (`README.md`)? That one is meant to be kept short, I think. Dunno.

For the docs, I think that I would suggest calling cmake directly instead of going through our wrapper Makefile. (I don't even know why we have it.) That would avoid all make-related quoting issues.
