### ISSUE TITLE
No startup_id on Qt5/KF5 apps

### ISSUE THREAD

**Issue by Elv13** [awesomeWM/awesome#1057]
Is anyone else having this issue? I tried to find the root of this. The startup id related methods in framework-intergrade, Qt5 X11Extra or KWindowSystem never seem to be called. Even if the code seem to exist. GTK and URxVt SNID are working properly.

As I am trying to re-implement multi-screen in my config, this will soon become a problem again...

(Awesome git-master)

Quick test:

```
echo 'for _,c in ipairs(client.get()) do require("naughty").notify{text="SNID: "..(c.startup_id or "N/A").. ",    Class: "..c.class} end' | awesome-client
```

**Comment by psychon** [comment]
First 697a88958e9d51c2b393398bbc0e13a5206ceabd for GTK and now this for QT. Where does startup-id work at all?! :-(
Looking at Qt's source code, the xcb-integration expects a `DESKTOP_STARTUP_ID` variable and passes this on to other parts of Qt (I don't know which parts). Thus, this *should* work. I cannot really test right now...

(Qt5 X11Extra? What's that? Do you mean Qt4 X11Extra? What exactly is X11Extra? Is that part of Qt5? Do you have a link / a path to the file for me?)

**Comment by psychon** [comment]
Looks to me like the startup-related code in Qt is limited to telling the launcher "startup is done" in a window-independent way. It does not support identifying the window(s) related to some startup sequence.
http://code.qt.io/cgit/qt/qtbase.git/tree/src/plugins/platforms/xcb/qxcbscreen.cpp?id=b393641888f18e3accf094c91808e2189c2138cc#n355
(The code does: When a window is shown and we still have a startup id, then tell the launcher that startup for this ID is now done and clear the startup id)

I'd close this, but instead I'll assign this issue to you.

(And in case someone asks "doesn't this break SN?": Usually SN is only used to change the mouse cursor while start up is going on; for this Qt's support is enough.)
