### ISSUE TITLE
Screen order in Awesome inconsistent with the one defined by XRandr.

### ISSUE THREAD

**Issue by qalk** [awesomeWM/awesome#1080]
Output of `awesome --version`: awesome v3.4.15 (Never Gonna Give You Up)
 • Build: Jan 23 2014 14:28:37 for x86_64 by gcc version 4.8.2 (buildd@komainu)
 • D-Bus support: ✔

Problem description:
I'm using two graphic cards with two monitors connected to each of them, see the xrandr -q output below. Visually the screens (outputs) are arranged like this (from left to right, see xrandr coordinates):
 * GPU-1.DP-1     (A)
 * GPU-1.DVI-I-1  (B)
 * GPU-0.DVI-I-1  (C)
 * GPU-0.DP-1     (D)

And it works - moving the cursor between the monitors works as expected.

However, the problem occurs when I try to use any of the commands that that do something with "the next screen", for example the default behavior of awful.client.movetoscreen. When I try to use it the client jumps between the screens in the following order:
 * GPU-1.DP-1     (A)
 * GPU-0.DVI-I-1  (C)
 * GPU-0.DP-1     (D)
 * GPU-1.DVI-I-1  (B)

which is very confusing :)

From what I can tell (treat this with a grain of salt, I'm not really familiar with the code base) this is happening, because of how the screens list is generated with Randr. Awesome is using the default order returned by xcb_randr_get_monitors (see objects/screen.c : screen_scan_randr_monitors), which:
 * seems to be the same order as the one returned by "randr -q"
 * is different than the visual order defined by the X coordinates

I couldn't find any way to either:
 - rearrange the output order in Randr or
 - rearrange the screens list in Awesome

Which leaves with an open question: What would be the recommended solution here?

Details:
$ xrandr -q
Screen 0: minimum 8 x 8, current 6880 x 1920, maximum 16384 x 16384
GPU-0.DVI-I-0 disconnected (normal left inverted right x axis y axis)
GPU-0.DVI-I-1 connected primary 2560x1600+3120+0 (normal left inverted right x axis y axis) 641mm x 400mm
   2560x1600      59.9*+
...
GPU-0.DP-0 disconnected (normal left inverted right x axis y axis)
GPU-0.DP-1 connected 1200x1920+5680+0 left (normal left inverted right x axis y axis) 518mm x 324mm
   1920x1200      60.0*+   59.9  
...
GPU-1.DVI-I-0 disconnected (normal left inverted right x axis y axis)
GPU-1.DVI-I-1 connected 1200x1920+1920+0 left (normal left inverted right x axis y axis) 518mm x 324mm
   1920x1200      60.0*+   59.9  
...
GPU-1.DP-0 disconnected (normal left inverted right x axis y axis)
GPU-1.DP-1 connected 1920x1080+0+0 (normal left inverted right x axis y axis) 509mm x 286mm
   1920x1080      60.0*+   59.9     50.0     60.1     60.0     50.0  
...

**Comment by Elv13** [comment]
Hello,

Sorry to say that, but Awesome 3.4 isn't supported since 4 and half years. Please upgrade a release that isn't 7 years old. The current official release is 3.5.9. The current recommended version is git-master (to be 3.6). As the 3.6 release is near, there is no point in upgrading to 3.5 for you. You will have to fix your config twice. The documentation for git-master is [here](http://new.awesomewm.org/apidoc/documentation/03-declarative-layout.md.html).

Note that Awesome git-master has proper dynamic multi-screen support. 3.4 doesn't.
