### ISSUE TITLE
awful.placement.top_left is not aware of the top bar

### ISSUE THREAD

**Issue by aroig** [awesomeWM/awesome#1086]
Output of `awesome --version`:

    $ awesome --version
    awesome v3.5.2-1968-ge86ddaa (The Fox)
     • Compiled against Lua 5.3.3 (running with Lua 5.3)
     • D-Bus support: ✔

**How to reproduce the issue:**

1. Add a rule with an `awful.placement.top_left` callback for a client, like this:

    rules.rules = {
        { rule_any = { class = { "qemu-system-x86_64" } },
          properties = { floating = true },
          callback   = function(c) awful.placement.top_left(c) end },
    }

2. Launch that client

**Actual result:**

The client is placed in the top left corner of the *screen*, actually overlapping the top bar.

**Expected result:**

Place the client at the top left corner of "desktop space", not overlapping the top bar.

**Comment by psychon** [comment]
Try `awful.placement.top_left(c, { honor_workarea = true })`. If this doesn't work, wait for @Elv13 to tell us how this works.

**Comment by aroig** [comment]
Aha! I missed that one! It does work, so I'm closing this, then.

Thanks!
