### ISSUE TITLE
dbus.emit_signal() usage question

### ISSUE THREAD

**Issue by actionless** [awesomeWM/awesome#109]
i tried to use that method to send a signal via dbus to other applications, but signal was not received in any applications there i tried and method was always returning `true`

did anyone used it in the config? i can't figure out what am i doing wrong, here is an example for spotify:

``` lua
  local result = dbus.emit_signal(
    "session",
    '/org/mpris/MediaPlayer2',
    'org.mpris.MediaPlayer2.spotify',
    'Next'
  )
```

from `dbus-monitor` output it looks like that:

correct call:

```
method call sender=:1.735 -> dest=org.mpris.MediaPlayer2.spotify serial=5 path=/org/mpris/MediaPlayer2; interface=(null); member=Next
```

resulting call from the example above:

```
signal sender=:1.724 -> dest=(null destination) serial=16 path=/org/mpris/MediaPlayer2; interface=org.mpris.MediaPlayer2.spotify; member=Next
```

so it seems like my problem what i don't know how to set the destination

**Comment by actionless** [comment]
seems i found a problem. already started working on patch

**Comment by blueyed** [comment]
I don't know how useful it is, but maybe this helps: https://github.com/pavouk/lgi/blob/master/tests/dbus.lua

**Comment by actionless** [comment]
thanks, seems `call_sync` from this example is what am i looking for: https://github.com/pavouk/lgi/blob/051170efd8c176fbea7f16abf690dab176d96864/samples/GDbus/list-system-services.lua

**Comment by Elv13** [comment]
Here is an awesome extension for this

https://github.com/Elv13/wirefu/blob/master/demo/mpris.lua

The problem with gio.dbus is that it randomly crash on some user PC (but not others). Sometime ti work for a week then for no reason crash Awesome. If it would not be for that, I would drop capi.dbus for this, but I can't.

See https://github.com/pavouk/lgi/issues/88

**Comment by actionless** [comment]
>An usable DBus bindings for lua

i will try them, thanks

**Comment by Elv13** [comment]
Sorry for the lack of documentation, I guess you will have to look at the examples for now. It support async method call, properties and signals. The syntax is much better than raw LGI.DGbus. I use lua metatables to dynamically build the service/interface/objectpath and method name components. I tried to make it look as native as possible. Of course, the  '/org/mpris/MediaPlayer2' kind of ruin everything from semantic standpoint, but it is necessary, so I have to include it. Some corner case, like dbus service reset and a few others are not correctly handled yet, patches are welcome, it is still work in progress.

**Comment by actionless** [comment]
from that example i did not understood about eventloop,

so when running from awesome it would work in the same eventloop?

because when i just pasted from the example it hanged awesome (without it wasn't send anything or throw any exception)
```lua
local main_loop = GLib.MainLoop()
main_loop:run()
```

**Comment by Elv13** [comment]
Awesome already start the even loop for you, you only need it if you plan to use the script in stand alone mode. This is quite useful for development.

**Comment by actionless** [comment]
so how can i figure out why call is not visible in `dbus-monitor`? 

```lua
    local player = wirefu.SESSION.org.mpris.MediaPlayer2.spotify(
      "/org/mpris/MediaPlayer2"
    ).org.mpris.MediaPlayer2.Player
    player.PlayPause()
```

`player.PlayPause` returns a table with description of that method and all it's parents

**Comment by Elv13** [comment]
I am Elv1313 on IRC if you want to continue the discussion there, it will be much easier
