### ISSUE TITLE
Reloading config moves all clients to one tag

### ISSUE THREAD

**Issue by madduck** [awesomeWM/awesome#1094]
Possibly related to #1091, using Git master (@87d37e2), I encountered that all clients are moved to the first tag upon reloading the configuration. I seem to recall that with 3.4, this wasn't the case, i.e. clients would preserve their tag across a config reload, and I think this should be the behaviour.

**Comment by psychon** [comment]
GitHub says that your version is wrong (there is no git master 87d37e2).
Also, what did you do about #1091? If you are using [this fix](https://github.com/awesomeWM/awesome/issues/1091#issuecomment-246599040), then you should use [this](https://github.com/awesomeWM/awesome/issues/1091#issuecomment-246933520) instead.
More generally: What does your awesome config look like?

**Comment by madduck** [comment]
I am sorry @psychon, that was silly of me. I am talking about commit 25f2b03 of course. And with that it works. The other commit still had a revert from a previous debug stashed on top. I am very sorry to have taken up your time… :/

**Comment by psychon** [comment]
No problem. Better open one issue too much as one too few.
