### ISSUE TITLE
Blacklist broken ldoc versions

### ISSUE THREAD

**Issue by Elv13** [awesomeWM/awesome#1098]
If `ldoc` is installed, we need to check its version and ignore it if it's one of the broken one. If we don't, then there is build "errors". So far, we forced the version on the CI, but that doesn't help the end users who have it installed.

See https://github.com/stevedonovan/LDoc/issues/248

**Comment by psychon** [comment]
Can someone try the following and turn it into a PR?
```patch
diff --git a/awesomeConfig.cmake b/awesomeConfig.cmake
index 4208d67..075d465 100644
--- a/awesomeConfig.cmake
+++ b/awesomeConfig.cmake
@@ -42,6 +42,14 @@ a_find_program(LDOC_EXECUTABLE ldoc FALSE)
 if(NOT LDOC_EXECUTABLE)
     a_find_program(LDOC_EXECUTABLE ldoc.lua FALSE)
 endif()
+if(LDOC_EXECUTABLE)
+    execute_process(COMMAND sh -c "ldoc --sadly-ldoc-has-no-version-option 2>&1  | grep ' vs 1.4.4'"
+                    OUTPUT_VARIABLE LDOC_VERSION_RESULT)
+    if(NOT LDOC_VERSION_RESULT STREQUAL "")
+        message(WARNING "Ignoring LDoc, because version 1.4.4 is known to be broken")
+        unset(LDOC_EXECUTABLE)
+    endif()
+endif()
 # theme graphics
 a_find_program(CONVERT_EXECUTABLE convert TRUE)
 # pkg-config
```
Good night

**Comment by blueyed** [comment]
Shouldn't this check for 1.4.5? (as per https://github.com/awesomeWM/awesome/issues/1127#issuecomment-250826494)

**Comment by psychon** [comment]
If I understand https://github.com/actionless/awesome/commit/74669f4bc3eaa0a0a15c76a524797340fee5583d correctly, then this is not actually fixed?

**Comment by wangjiezhe** [comment]
I build successfully with the newest git version of ldoc.

**Comment by psychon** [comment]
Yup, newest version seems to work fine. I guess only rejecting version 1.4.5 remains to be done then? (Or: Shown that this is not needed)

**Comment by blueyed** [comment]
Yes, finally fixed (since ~20 days already, see https://github.com/stevedonovan/LDoc/issues/248#issuecomment-258492278).

> I guess only rejecting version 1.4.5 remains to be done then?

Yes.
