### ISSUE TITLE
Default config: Re-set wallpaper on property::geometry of a screen

### ISSUE THREAD

**Issue by psychon** [awesomeWM/awesome#1102]
I just swapped the position of two monitors (Before: 1|3|2; After: 1|2|3). 2 and 3 have different resolutions and so I noticed that the wallpaper isn't updated and still displays "the old state of things".

The default config has to set a wallpaper:
- When a new screen appears
- When a screen changes its geometry

**Comment by blueyed** [comment]
Sounds like the issue I was seeing already - but could not find it now.
