### ISSUE TITLE
"less" ("<") in globalkeys mapping breaks "comma" (",") in clientkeys

### ISSUE THREAD

**Issue by blueyed** [awesomeWM/awesome#111]
When using `<` ("less") in a global keybinding, `,` (comma) in a client keybinding does not work.

    globalkeys = awful.util.table.join(
        ....
        awful.key({ modkey }, "less",  function () naughty.notify({text="less"}) end),

    clientkeys = awful.util.table.join(
        ...
        awful.key({ modkey }, ",", function(c) naughty.notify({text="comma"}) end),

I've tried using `<` and `comma` instead.
I am using a German keyboard layout, and `<` is next to the left shift and comma right next to `m`.

Output from `xev`:

For `<`:

    KeyRelease event, serial 34, synthetic NO, window 0x3a00001,
        root 0x94, subw 0x0, time 393382277, (438,630), root:(439,631),
        state 0x10, keycode 94 (keysym 0x3c, less), same_screen YES,
        XLookupString gives 1 bytes: (3c) "<"
        XFilterEvent returns: False

For `,`:

    KeyRelease event, serial 34, synthetic NO, window 0x3a00001,
        root 0x94, subw 0x0, time 393403254, (103,14), root:(104,15),
        state 0x10, keycode 59 (keysym 0x2c, comma), same_screen YES,
        XLookupString gives 1 bytes: (2c) ","
        XFilterEvent returns: False

When using both in globalkeys it works.

I might be doing something stupid here, but I've been using the mapping with comma since a while already.

**Comment by blueyed** [comment]
From some investigation: it appears like `client_getbyframewin()` does not
return a client in this case:

    diff --git a/event.c b/event.c
    index c0a8bfa..c3c70ba 100644
    --- a/event.c
    +++ b/event.c
    @@ -606,11 +606,14 @@ event_handle_key(xcb_key_press_event_t *ev)
             client_t *c;
             if((c = client_getbyframewin(ev->event)))
             {
    +            printf("event_handle_key: 1\n");
                 luaA_object_push(L, c);
                 event_key_callback(ev, &c->keys, L, -1, 1, &keysym);
             }
             else
                 event_key_callback(ev, &globalconf.keys, L, 0, 0, &keysym);
         }
     }

It looks like the global key mapping / binding overlays the one for the client.

**Comment by psychon** [comment]
I have bad news: Works fine for my with the default config and just your two keybindings added.

**Comment by blueyed** [comment]
@psychon 
Thanks for testing it!

This is fixed by calling `setxkbmap -layout de -variant nodeadkeys` in `~/xsessionrc`.

I am calling it like this, to prevent any system settings from overriding it:

    (
    # Sleep a bit, otherwise this gets overwritten by Ubuntu/Gnome.
    sleep 5

    xcape -t 200 -e 'Caps_Lock=Escape;Control_L=Control_L|O;Shift_L=parenleft;Shift_R=parenright'
    setxkbmap -layout de -variant nodeadkeys
    ) &

I am closing the issue: it's some issue with X / Ubuntu, and not with Awesome (probably).
