### ISSUE TITLE
Issue trying to build awesome: "^M" in files

### ISSUE THREAD

**Issue by aajjbb** [awesomeWM/awesome#1110]
I'm trying to build awesome from git, but there's some issue in the build process.

While running 'make' to build awesome, it create some files with lots of carriage returns "^M" that cannot be compiled. 

The file in case is: _/home/user/awesome/.build-manjaro-x86_64-pc-linux-gnu-6.2.1/common/atoms-intern.h_

Here is the file content: https://gist.github.com/aajjbb/3c7c3cdf8bc4bc8f195b9027a6654d77

GNU Make 4.2.1
cmake version 3.6.2

**Comment by psychon** [comment]
Uhm, ok...
What's your `/bin/sh`? (E.g. try `/bin/sh --version`)
Does this work for you: `(echo foo; echo bar) > /tmp/atoms ; build-utils/atoms-int.sh /tmp/atoms`
Output in my case is:
```
/* This file is autogenerated by build-utils/atoms-int.sh - do not edit */

xcb_atom_t foo;
xcb_atom_t bar;

static atom_item_t ATOM_LIST[] =
{
    { "foo", sizeof("foo") - 1, &foo },
    { "bar", sizeof("bar") - 1, &bar },
};
```
The file `atoms-intern.h` is generated by running `build-utils/atoms-int.sh common/atoms.list`. When you run this by hand, do you also get those extra newlines? Does `atoms.list` perhaps have Windows line endings?

**Comment by ff2000** [comment]
Just a really stupid question:
Do you happen to share your $HOME with a windows machine and therefore use VFAT as filesystem?
There seem to be options to convert the line endings, so probably that's your issue...

On Thu, 22 Sep 2016 16:18:54 -0700, Jeferson Siqueira <notifications@github.com> wrote:
> I'm trying to build awesome from git, but there's some issue in the build process.
> 
> While running 'make' to build awesome, it create some files with lots of carriage returns "^M" that cannot be compiled. 
> 
> The file in case is: _/home/user/awesome/.build-manjaro-x86_64-pc-linux-gnu-6.2.1/common/atoms-intern.h_
> 
> Here is the file content: https://gist.github.com/aajjbb/3c7c3cdf8bc4bc8f195b9027a6654d77
> 
> GNU Make 4.2.1
> cmake version 3.6.2
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/awesomeWM/awesome/issues/1110
> 
--

**Comment by aajjbb** [comment]
Hi, thanks for the reply:

@psychon:

Bash: `GNU bash, version 4.3.46(1)-release (x86_64-unknown-linux-gnu)`

My output for running` (echo foo; echo bar) > /tmp/atoms ; build-utils/atoms-int.sh /tmp/atoms` is exactly the same as yours. 

Yes, I do get those extra "^M" by running `build-utils/atoms-int.sh common/atoms.list` by hand. What could it be ?

@ff2000 No, I use ext4 and my $HOME partition isn't shared with a Windows machine.

**Comment by psychon** [comment]
Sounds like your `common/atoms.list` has windows line endings. Could you check? Can you perhaps also figure out where they are coming from? Getting a not-broken version of that file should fix your build.
(For getting rid of them with vim: Open the file in vim, do `:set fileformat=unix` and `:wq`. Done. There are tons of other ways, I guess.)

**Comment by aajjbb** [comment]
This "^M" issue was fixed by running `dos2unix` in `common/atoms.list`, but a new issue was found:

`make[3]: *** No rule to make target '/usr/local/lib/liblua.a', needed by 'awesome'.  Stop.`

I'll try to fix this one now, but, I'm still curious about where does this "^M" came from, do you guys have any clues ?

**Comment by blueyed** [comment]
> I'm still curious about where does this "^M" came from, do you guys have any clues ?

IIRC there are some Git settings regarding this.
Do you have it in all your files maybe?

**Comment by aajjbb** [comment]
It was a matter of a git `core.autocrlf`, setting it to `false` solved the issue.
