### ISSUE TITLE
Fix the default config so that screens become garbage-collectable

### ISSUE THREAD

**Issue by psychon** [awesomeWM/awesome#1125]
Currently when a screen is removed, the screen, its wibox and all the contained widgets cannot be garbage collected. The following patch hopefully describes the issue by itself.
```patch
diff --git a/awesomerc.lua b/awesomerc.lua
index 287a916..b121d07 100755
--- a/awesomerc.lua
+++ b/awesomerc.lua
@@ -237,6 +237,15 @@ awful.screen.connect_for_each_screen(function(s)
         },
     }
 end)
+
+screen.connect_signal("removed", function(s)
+    -- TODO: Figure out how to do this nicely
+    mypromptbox[s] = nil
+    mylayoutbox[s] = nil
+    mytaglist[s] = nil
+    mytasklist[s] = nil
+    mywibox[s] = nil
+end)
 -- }}}
 
 -- {{{ Mouse bindings
diff --git a/tests/test-screen-changes.lua b/tests/test-screen-changes.lua
index 7afb703..66f8548 100644
--- a/tests/test-screen-changes.lua
+++ b/tests/test-screen-changes.lua
@@ -8,6 +8,7 @@ local max = require("awful.layout.suit.max")
 local real_screen = screen[1]
 local fake_screen = screen.fake_add(50, 50, 500, 500)
 local test_client1, test_client2
+local wibox_for_fake_screen
 
 local steps = {
     -- Step 1: Set up some clients to experiment with and assign them as needed
@@ -53,6 +54,8 @@ local steps = {
         assert(wb.y == 110, wb.y)
         assert(wb.width == 600, wb.width)
 
+        wibox_for_fake_screen = wb
+
         return true
     end,
 
@@ -62,15 +65,8 @@ local steps = {
 
         -- Now that the screen is invalid, the wibox shouldn't refer to it any
         -- more
-        assert(mywibox[fake_screen].screen ~= fake_screen)
-
-        -- TODO: This is a hack to make the test work, how to do this so that it
-        -- also works "in the wild"?
-        mypromptbox[fake_screen] = nil
-        mylayoutbox[fake_screen] = nil
-        mytaglist[fake_screen] = nil
-        mytasklist[fake_screen] = nil
-        mywibox[fake_screen] = nil
+        assert(wibox_for_fake_screen.screen ~= fake_screen)
+        wibox_for_fake_screen = nil
 
         -- Wrap in a weak table to allow garbage collection
         fake_screen = setmetatable({ fake_screen }, { __mode = "v" })
```
The only alternative that I see to the about patch is using a weak table in the default config for these tables. I like the above patch more (it's explicit about what is going on). Still, the above patch is also ugly.

Ideas?
(This also kind of blocks speeding up the multi screen tests, because for that we need to make sure that "old" wiboxes are not repainted and our current approach to that is having them GC'd.)

**Comment by Elv13** [comment]
I don't know, maybe we could make "bigger" changes to `awesomerc.lua` and have a single weak table for "screen objects" instead of 5 and use string keys "my_screen_object[s].wibar". Or just store the objects directly in the screen object (thanks to the miss handler thing). It seems nicer. It can also be something in between like `s.my_object.wibar` or something.

Whats the point of these tables anyway. They are barely used outside of the widget definition section.

**Comment by psychon** [comment]
>  Or just store the objects directly in the screen object (thanks to the miss handler thing).

That will give us a reference leak that we cannot work around (at least on Lua 5.1 and LuaJIT). Their GC cannot collect entries from weak tables where the value strongly references the key. However, I like this idea and will try to instead fix things so that the idea works.
