### ISSUE TITLE
We use trailing whitespaces, but do not allow them

### ISSUE THREAD

**Issue by psychon** [awesomeWM/awesome#1129]
Hi,

I can no longer edit files like `lib/awful/widget/watch.lua`. Whenever I do that, the trailing whitespaces in there disappear. I don't remember where I read it, but I think @Elv13 somewhere wrote that these trailing whitespaces are necessary so that LDoc doesn't think a new paragraph starts (or something like that). So I had to figure out why vim kills these trailing whitespaces.

The reason is here: https://github.com/awesomeWM/awesome/blob/502b4139bad5f91306505b3ca148ae00deafae89/.editorconfig#L14-L15

So, am I right that we do not allow trailing whitespaces, but require them?
What should we do about this?

**Comment by Elv13** [comment]
Actually, it's hackyer than that and only applicable for the "doc tests". CMake drop the newlines and convert lines with 1 space into new lines. I "use" this as a feature, but it's mostly a bug.

**Comment by actionless** [comment]
i wasn't adding those trailing spaces there on purpose, seems like some auto-indentation quirk

**Comment by Elv13** [comment]
Can/Should this be closed? There is no whitespace left

**Comment by psychon** [comment]
If I just open the FAQ in vim and `:wq`, I end up with the following diff, so the problem remains (but now at another file?)
```diff
diff --git a/docs/90-FAQ.md b/docs/90-FAQ.md
index 02a2a4e39..1e86036f4 100644
--- a/docs/90-FAQ.md
+++ b/docs/90-FAQ.md
@@ -168,7 +168,7 @@ You can ensure no application ever starts maximized in the first rule of your
 
     -- Search for this rule,
     keys = clientkeys,
-    
+
     -- add the following two:
     maximized_vertical   = false,
     maximized_horizontal = false,
@@ -217,7 +217,7 @@ terminal output you can use the following to match clients in awesome:
                         |           |--- class
                         |
                         |--- instance
-    
+
     WM_NAME(STRING) = "SMPlayer"
                        |
                        |--- name
```
Grepping for affected files (and ignoring PNGs and files in `.git` or `.build*`), I find:
```
./objects/drawin.c
./manpages/awesome.1.ru.txt
./docs/03-declarative-layout.md
./docs/90-FAQ.md
```
