### ISSUE TITLE
doc: gears.color entrypoint?!

### ISSUE THREAD

**Issue by blueyed** [awesomeWM/awesome#1144]
In e.g. https://github.com/awesomeWM/awesome/blob/26d3c5eb1aa3a9f5930dcae609580649f62289ad/lib/wibox/widget/progressbar.lua#L39 `@tparam gears.color` is used, but gets not resolved.

There is no single `color` type that can be used as reference, and apparently ldoc does not link to modules in this case.

Can/should we add some base type in `gears.color` that can be used (not only) for documentation?

**Comment by psychon** [comment]
Not having much clue about ldoc, I have to ask: What is / counts as a base type? How would such a change look like?
Having links in these types would surely be useful.

**Comment by blueyed** [comment]
@Elv13 
Any idea?

**Comment by Elv13** [comment]
> Any idea

I am not sure this is a big issue.

First, it needs something like:

```lua
--- Convert something to a color.
-- @tparam table|string|pattern arg Something that can be converted to a color
-- @function gears.color
```

The "single type" of `gears.color` is a cairo pattern, but this user isn't aware of that, and should not be. Most (all?) APIs just take the unconverted values and pass them to `gears.color`. There isn't much to "do" (from an API doc PoV) about this, right? Sure, having confusing types all over the place need some cleanup. Maybe a `string|pattern|table` + "(See \`gears.color\`)" in the argument description, but there _is_ no types involved here.

**Comment by blueyed** [comment]
I am more interested in linking the user to a good entrypoint about what `gears.color` is: currently it's just not being linked, but could go to the module for example at least.

**Comment by Elv13** [comment]
A `@see` or "(See `gears.color`)" is about as close as you will get without patching ldoc (unless I missed something). And if we get into that, this probably isn't the top thing to patch. The ".manage" signal type issue is the worst, the properties are also weird (we want `value`, not `wibox.widget.progressbar.value`). It's the same limitation that causes both.
