### ISSUE TITLE
new clients always spawned on first screen

### ISSUE THREAD

**Issue by aroig** [awesomeWM/awesome#1158]
Awesome (current master) on a multiscreen setup always opens new clients on the first screen, independently of where the mouse is, or the client that has focus.

This is a change in behavior since last time I used this multiscreen machine (about 40 days ago). Then it opened the new client at the screen that currently had the mouse.

Is this change intentional or a bug? What is the expected way to recover the old behavior, in which new clients open on the screen with the mouse?

To be clear, I don't care about the mouse. I care about a notion of "focused screen". And defining "focused screen" as "the one having a focused client" is not good enough. See #1038 for what I mean.

Thanks.

**Comment by aroig** [comment]
Ah crap, I've just seen #1091. Sorry for the noise... I'm going to test that now.

**Comment by psychon** [comment]
Sounds like you want e8649d0a296a8a014fbd9e98182c78bfae2b9ed3 and 1c177cabce1557f6eacf517dee0e8ff0f4cb02fe. The "problem" was introduced in 2178744.

**Comment by aroig** [comment]
It works fine, thanks. I'm closing this.
