### ISSUE TITLE
awful.spawn calls callback function twice (patch included) 

### ISSUE THREAD

**Issue by ptrxyz** [awesomeWM/awesome#1159]
Output of `awesome --version`:
```
awesome v3.5.2-2035-g8dc98e8 (The Fox)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔
```
**How to reproduce the issue:**
Simply use `awful.spawn("somecommand", false, somecallback)` somewhere.

**Actual result:**

The callback function gets executed **twice**.

**Expected result:**

Callback gets executed **once**.

**Comment by ptrxyz** [comment]
I did some research on this. It seems that `awful.spawn` sets the callback function as a property of a table that is then passed to `rules.execute`. Then, there is a loop that simply applies all properties to the client object **but then**, in addition, there is a loop that executes all callbacks.

Suggested fix:
Either filter out the callback property in rules.execute or before the properties table gets passed to the rules.execute function. I'd go for the 2nd version, since I don't know where else callbacks are used as properties and I am pretty sure the `completed_with_payload_callback` callback is only used for spawned clients.

I'll try to send a merge request asap.

**Comment by psychon** [comment]
Untested, but how about something like this? This makes `awful.spawn` keep the callback separated instead of merging it with the "normal properties table".
```diff
diff --git a/lib/awful/rules.lua b/lib/awful/rules.lua
index f899685..7f8bdfc 100644
--- a/lib/awful/rules.lua
+++ b/lib/awful/rules.lua
@@ -492,9 +492,8 @@ function rules.execute(c, props, callbacks)
     end
 end
 
-function rules.completed_with_payload_callback(c, props)
-    rules.execute(c, props, type(props.callback) == "function" and
-        {props.callback} or props.callback )
+function rules.completed_with_payload_callback(c, props, callbacks)
+    rules.execute(c, props, callbacks)
 end
 
 client.connect_signal("spawn::completed_with_payload", rules.completed_with_payload_callback)
diff --git a/lib/awful/spawn.lua b/lib/awful/spawn.lua
index a59d52d..c06776e 100644
--- a/lib/awful/spawn.lua
+++ b/lib/awful/spawn.lua
@@ -71,9 +71,11 @@ end
 spawn.snid_buffer = {}
 
 function spawn.on_snid_callback(c)
-    local props = spawn.snid_buffer[c.startup_id]
-    if props then
-        c:emit_signal("spawn::completed_with_payload", props)
+    local entry = spawn.snid_buffer[c.startup_id]
+    if entry then
+        local props = entry[1]
+        local callback = entry[2]
+        c:emit_signal("spawn::completed_with_payload", props, callback)
         spawn.snid_buffer[c.startup_id] = nil
     end
 end
@@ -103,15 +105,11 @@ function spawn.spawn(cmd, sn_rules, callback)
     if cmd and cmd ~= "" then
         local enable_sn = (sn_rules ~= false or callback)
         enable_sn = not not enable_sn -- Force into a boolean.
-        if not sn_rules and callback then
-            sn_rules = {callback=callback}
-        elseif callback then
-            sn_rules.callback = callback
-        end
         local pid, snid = capi.awesome.spawn(cmd, enable_sn)
         -- The snid will be nil in case of failure
         if snid and type(sn_rules) == "table" then
-            spawn.snid_buffer[snid] = sn_rules
+            sn_rules = sn_rules or {}
+            spawn.snid_buffer[snid] = { sn_rules, { callback } }
         end
         return pid, snid
     end
```
CC @Elv13

**Comment by ptrxyz** [comment]
Seems reasonable to me. However I think rules.execute needs to be fixed in addition. I don't know where else this problem could come up, so how about fixing rules.execute to merge props['callback'] and the callbacks parameter to a single table:
```
diff --git a/lib/awful/rules.lua b/lib/awful/rules.lua
index 514e8ca..059a563 100644
--- a/lib/awful/rules.lua
+++ b/lib/awful/rules.lua
@@ -368,6 +368,14 @@ end
 -- @tab props Properties to apply.
 -- @tab[opt] callbacks Callbacks to apply.
 function rules.execute(c, props, callbacks)
+    -- First things first: cleanup parameters
+    -- props['callback'] is moved to the callbacks parameter to avoid double
+    -- execution in certain cases
+    if props['callback'] then
+        table.insert(callbacks, props['callback'])
+        props['callback'] = nil
+    end
+
     -- This has to be done first, as it will impact geometry related props.
     if props.titlebars_enabled then
         c:emit_signal("request::titlebars", "rules", {properties=props})
```

**Comment by psychon** [comment]
Well, I disagree. There is nothing special about `callback` as a property. The same will happen if you give the property a different name. Any function as a property value is applied by calling that function and then assigning the return value as the property. For example, the following makes every second client floating:
```lua
local counter = 0
local function floating_some()
  counter = counter + 1
  return counter % 2 == 0
end
awful.rules.rules = { { rule = {}, properties = { floating = floating_some } }
```
Also, the only "callers" of rules are `spawn` (which this bug is about) and the "normal rules" that are set in the config (and which do not (really)) have this problem. So this problem shouldn't come up anywhere else.

**Comment by ptrxyz** [comment]
From a technical point of view, you are right. `callback` in an empty space can be just considered as any other property (like i.e. `floating` in your example). But in context a user could assume `callbacks` and `prop['callback']` _mean_ the same thing, which then would make double execution pretty counter-intuitive. So if that's the intended behavior, it's fine with me I just wanted to point this out.

So, we came up with enough technical solutions I guess. Fixing the calling functions, the executed one, or both -- anything is fine with me. Simply choose one so this can be closed :)

**Comment by psychon** [comment]
Hm, ok. That's also a good argument. In a nutshell "help catch people's typos".
I defer for @Elv13 (and others, feel free to add your opinion).

**Comment by ptrxyz** [comment]
Sure thing. In the end I didn't find `callback` being a documented feature of the `prop`, so users should not use it anyways :smiley:
