### ISSUE TITLE
Some windows don't tile and can't be resized or moved

### ISSUE THREAD

**Issue by poisonby** [awesomeWM/awesome#1167]
Output of `awesome --version`:

Using git master.
```
awesome v3.5.2-2135-gc9f085f (The Fox)
• Compiled against Lua 5.3.3 (running with Lua 5.3)
• D-Bus support: ✔
```

**How to reproduce the issue:**

Open the programs. As far as I know, the affected windows are currently Thunar, Chromium and Steam. Using an unmodified rc.lua doesn't work either.

**Actual result:**

![Bug1](https://ptpb.pw/ADOumO6uLWRYuz9MJDdUEYOK8W_l)
![Bug2](https://ptpb.pw/AAF5ia3MG3-99nE-Q8QU53oItvZd)
![Bug3](https://ptpb.pw/W8UG.png)

**Expected result:**

They should tile, honor gaps, be able to be resized, etc.

**Comment by psychon** [comment]
Does this also happen with the default config?
Could you get the `xwininfo` and `xprop` output for one of those windows?
Can you easily do a git bisect (assuming that this error showed up recently)? (If your answer is "What's a git bisect?", then that's a "no").

I'll see if my Chromium has similar problems with latest master, but so far it doesn't.

**Comment by poisonby** [comment]
> Does this also happen with the default config?

Yes.

>Could you get the xwininfo and xprop output for one of those windows?

xprop:
https://ptpb.pw/H69v

xwininfo:
https://ptpb.pw/qqml

>Can you easily do a git bisect (assuming that this error showed up recently)? (If your answer is "What's a git bisect?", then that's a "no").

I don't know what a git bisect is, sorry.

**Comment by psychon** [comment]
> xprop:
> https://ptpb.pw/H69v
> 
> _NET_WM_STATE(ATOM) = _NET_WM_STATE_MAXIMIZED_VERT, _NET_WM_STATE_MAXIMIZED_HORZ

Your windows are maximized. Press Mod+m to toggle that state. (At least that's the key binding in the default config).

**Comment by poisonby** [comment]
> Your windows are maximized. Press Mod+m to toggle that state. (At least that's the key binding in the default config).

That was it, thanks! Kind of strange how that happened since I never use the maximize function (I hadn't even bound it), I only use the fullscreen mode.

Silly problem, haha, but I'm glad you were able to solve it. Thanks again!

**Comment by psychon** [comment]
I can't explain how these windows ended up being maximized, but I think Chromium restores its maximized state if it was maximized previously.

**Comment by blueyed** [comment]
I have though it might be related to this fix, but then you are using master already..
https://github.com/awesomeWM/awesome/commit/62622f79358c9037f33b0c592b7a9b4ea29371ab
