### ISSUE TITLE
minimize client for each tag

### ISSUE THREAD

**Issue by seniorivn** [awesomeWM/awesome#1170]
Output of `awesome --version`:
awesome --version
awesome v3.5.9 (Mighty Ravendark)
 • Build: Mar 12 2016 01:11:40 for x86_64 by gcc version 5.3.0 (builduser@rw)
 • Compiled against Lua 5.3.2 (running with Lua 5.3)
 • D-Bus support: ✔
**How to reproduce the issue:**
client.minimize work globaly on all tags

**Expected result:**
I want function that will work exactly the same, but for each tag, so if i have two tags:
- first tag
  - client1(not minimized)
  - client2(minimized)
- second tag
  - client1(minimized)
  - client2(not minimized)

Where client1 and client2 are the same on both tags.
Is there a way to do that out of the box? Or i need to reimplement check of minimized windows in widgets and shortcuts?

Edit by psychon: Tried to fix up the list above. Hopefully this is how it was intended to look like.

**Comment by psychon** [comment]
> Is there a way to do that out of the box? 

Quick answer would be: No

**Comment by seniorivn** [comment]
@psychon 
ok, than i think, it could be implemented as the optional feature: client.minimized could be boolean or table of booleans for every tag.
Do you think it's good solution? Am i the only one who need this? should it be implemented in upstream?

**Comment by Elv13** [comment]
@seniorivn This was evaluated for floating too (there is an open issue already, we should probably merge both conversations), but in the end I don't see this happening. Sure it technically makes sense. However, there is very few users who use multi-tag workflows (I am one of them, so I do see your point here). Even if it is set per tag, then you run into issues with multiple selected tags... So, in the end, getting this to work is possible, but it would make things so complicated (for both floating, minimized and maximized) I am not sure it is such a good idea. This is of course my personal opinion. There might just be a magic solution here, but I don't think so.

One solution would be a special layout that looks for an extra property and just don't place (and "hide") some clients. I have an extension for Awesome 3.4 and one for 3.6 capable of implementing this without messing with geometry, but I don't have any for 3.5. Still, it wont be trivial.

**Comment by seniorivn** [comment]
@Elv13 ok, it make sense, and if there is working solution that you mention, maybe we shouldn't mess with standard behavior.
Could you show this special layout code, for 3.6? I'm going to upgrade my config to upstream, so it would work for me, and even will be another goal to do that.

**Comment by Elv13** [comment]
I warn you, your going into the extra experimental territory, but I have been used this code for almost a year, so it work for me. Apply #644 on top of Awesome git-master or use it as a module (it works both way). It rewrite the whole layout engine to re-use `wibox.layout` (the widget layouts). It adds dynamic layouts, tabbing and some other cool stuff, but again, is experimental, experiences may vary. In your case, you need to edit `base.lua` and add some meat around the `client.tiled(self._tag.screen)` to remove the clients with your magic property. It isn't trivial, but it is certainly possible (~15 well placed lines of code in base.lua and rc.lua tasklist button function).

**Comment by seniorivn** [comment]
@Elv13 thanks, looks like you did very good job, i'm afraid it means i will rewrite my whole config :) it could be more then one weekend, i hope it'll worth it.
when upstream become stable it will be greatest wm ever, only one shortage there is no package/module manager.
