### ISSUE TITLE
Windows with "focusable = false" are still focusable

### ISSUE THREAD

**Issue by velovix** [awesomeWM/awesome#1172]
Output of `awesome --version`:

awesome v3.5.9 (Mighty Ravendark)
 • Build: Mar 12 2016 01:11:40 for x86_64 by gcc version 5.3.0 (builduser@rw)
 • Compiled against Lua 5.3.2 (running with Lua 5.3)
 • D-Bus support: ✔

**How to reproduce the issue:**

Make a rule for an application that sets its "focusable" property to false. For instance, in my `rc.lua`:

```
awful.rules.rules = {
...
	{ rule = { class = "chromium" },
	  properties = { focusable = false } },
...
}
```

**Actual result:**

The application doesn't seem to work any differently. I can still focus the application, type on it, use mouse input, and I can still reach it with Mod+J.

**Expected result:**

I would expect not to be able to focus the window or interact with it using mouse or keyboard.

**Comment by psychon** [comment]
Focusable is a read-only property (in awesome 3.5).
You could try something like this:
```lua
do
    local filter = awful.client.focus.filter
    awful.client.focus.filter = function(c)
        return c.class ~= "chromium" and filter(c)
    end
end
```

**Comment by velovix** [comment]
Thank you! That did what I wanted. Unfortunately, this seems to break `awful.client.focus.history` or some other component, because tags with an unfocusable client in them (using this method) no longer have a window focused by default. I had to add the following to banish my unfocusable window from history.

```
-- Ban chromium from history
do
	local historyGet = awful.client.focus.history.get
	awful.client.focus.history.get = function(screen, idx)
		-- Find chromium
		local history = awful.client.data.focus
		for k, v in ipairs(history) do
			if v.class == "chromium" then
				awful.client.focus.history.delete(v)
			end
		end

		return historyGet(screen, idx)
	end
end
```

**Comment by actionless** [comment]
what about smth like?
```lua
  awful.ewmh.add_activate_filter(function(c, source)
      if (
        source=="autofocus.check_focus" or source =="client.focus.bydirection"
      ) and
        c.class == "chromium"
      then
        return false
      end
  end)
```

**Comment by psychon** [comment]
@actionless That requires awesome built from git/master. With git/master, `focusable` can be written to, so the rule from the first comment in this issue should just work.

**Comment by velovix** [comment]
@psychon That's great to hear, I look forward to the next release!
