### ISSUE TITLE
Allow to specify exit code with awesome.quit

### ISSUE THREAD

**Issue by blueyed** [awesomeWM/awesome#1184]
I would like to use a custom exit code with `awesome.quit()`, so that this could signal my `~/.xinitrc` wrapper script to really exit.

Currently it will stop when `awesome` exits with 0, but that then stops it (and the X server) in case of using `awesome --replace`.

`awesome` exiting non-zero when it got replaced would also help in that case (is there a standard spec for this?), but having this feature for `awesome.quit` makes sense in general to me.

**Comment by actionless** [comment]
i like the idea since the problem described sounds familiar to my workflow

**Comment by psychon** [comment]
How would an API for setting the exit code when awesome is replaced look like? Currently `event_handle_selectionclear` in `event.c` just makes the main loop quit in this case. No Lua is involved. Adding a special signal just so that Lua can quit by itself seems a bit odd to me...

(Also, this issue is now about two different issues, add an optional "exit code" argument to `awesome.quit()` and "do something" about "being replaced". Meh...)

**Comment by actionless** [comment]
for me `awesome.quit(2)` will be enough, we could start from that

@blueyed ?

**Comment by psychon** [comment]
Retitling this issue accordingly. Open a new one for `--replace`, if you want.

**Comment by blueyed** [comment]
Yes, `awesome.quit(2)` is fine!
I just wondered if there is a spec regarding how a WM should exit when being replaced.
If that would be 2 already, we could fix it that way (but nobody seems to now about a spec regarding `--replace`?!).
But nonetheless: having custom exit codes is useful.

**Comment by psychon** [comment]
Not completely related to this issue, but:

- Dwm does not implement `WM_Sn`.
- Fluxbox is a huge mess that I couldn't figure out (well, not really a mess, just huge and not on GitHub, so I cannot easily search for `SelectionClear`).
- i3 does not seem to implement the `WM_Sn` selection (@Airblader am I right? At least I couldn't find anything).
- I couldn't even find source code for metacity.
- Openbox exits with code 0 when it is replaced: https://github.com/danakj/openbox/blob/9e8813e111cbe6c1088f6abbc771a29470f05fc2/openbox/openbox.c#L764

At this point I gave up searching.

**Comment by Airblader** [comment]
> i3 does not seem to implement the WM_Sn selection (@Airblader am I right? At least I couldn't find anything).

You're right. Not yet, anyway. We do have https://github.com/i3/i3/issues/536 for it, but frankly I haven't really ever found myself wanting to make use of that so far.
