### ISSUE TITLE
awful.placement.centered is not a function anymore

### ISSUE THREAD

**Issue by blueyed** [awesomeWM/awesome#1185]
Therefore it cannot be used by itself as a callback in the rules:

```
awesome# return require("gears").debug.dump_return(require("awful").placement.centered)
   string "table: 0x132e770
  is_placement : true (boolean)
  context : centered (string)"
```

awesome v3.5.60-2094-g6b90ed7 (The Fox)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔

/cc @Elv13

**Comment by Elv13** [comment]
First, it is a metatable table, for a regular table, it has a `__call`, so you can still use it as a function.

Use the rule `placement` property, it was added for this. See the default config. Also, you can now compose placements, this is why the table indirection was added.

**Comment by blueyed** [comment]
> First, it is a metatable table, not a regular table, it has a `__call`, so you can still use it as a function.

But apparently it gets not recognized as a function anymore then?!
Would it be possible to still support this simplified use case?

I can see that there is a better way now, by having a separate property, but the other use case is still feasible (if only for backward compatibility - which is not a good reason, of course).

**Comment by Elv13** [comment]
> But apparently it gets not recognized as a function anymore then?!

There is a new "placement" rule property. There is no way in lua for type() to interpret metafunctions as functions without dirty hacks.

As for the change, I think it is for the better. The placement property is much more flexible than using the function in the callpack property

**Comment by blueyed** [comment]
Is this a breaking change from 3.5 also?

I could imagine having both a placement function and a rule property living next to each other: the function would just involve the property's default behavior?!

**Comment by Elv13** [comment]
Using `awful.placement` as callback was never really an offical thing. It was convinient, but not official. There is now an official way of doing this. It handle the use case better and is documented. That the way client are placed changed is documented as a breaking change in the 3.6 changelog (#967).

> I could imagine having both a placement function and a rule property living next to each other

No, this will do random things. Just as having 2 callback in 3.4/3.5 would have. This is the very reason why it was turned into meta function in the first place: so you could compose them in a predictable order.

**Comment by blueyed** [comment]
Ok, closing it then.
