### ISSUE TITLE
Keygrabber yields special characters for keymaps with grp:caps_toggle

### ISSUE THREAD

**Issue by mfrischknecht** [awesomeWM/awesome#1194]
Output of `awesome --version`:

```
> awesome --version
awesome v3.5.9 (Mighty Ravendark)
 • Build: Mar 12 2016 01:11:40 for x86_64 by gcc version 5.3.0 (builduser@rw)
 • Compiled against Lua 5.3.2 (running with Lua 5.3)
 • D-Bus support: ✔
```

**How to reproduce the issue:**

- Use an `xkbmap` that switches its variant based on the capslock key

Example (with this map, CapsLock switches from `en_US` to `en_US-intl`):
```
> setxkbmap -query
rules:      evdev
model:      pc105
layout:     us,us
variant:    ,intl
options:    grp:caps_toggle
```

- In awesome, use a keygrabber to identify pressed keys.
- Switch on CapsLock.
- Press a  key.

**Actual result:**

The `key` argument to the provided callback will contain a special character depending on the key pressed (like &#xb9; for the number `1`, `dead_doubleacute` for the number `2`, &#x152; for the `K` Key, or &#216; for the `L` key).

**Expected result:**

Given that normal editors/text fields will continue to work 'properly' even with CapsLock on, the best thing would be for awesome to send the same keys and just include the CapsLock modifiers (as far as I can see, those seem to be `Lock` and `Mod5`).

I for example use the keygrabber for a custom Alt-Tab overlay that allows me fast access to any client on the screen by typing its index (similar to the [ace-window](https://github.com/abo-abo/ace-window) functionality in Emacs). However, this stops working if I have switched to the international keyboard, wich I use to type umlauts.

Interestingly, keys bound to callbacks with `root.keys()` don't have this problem and keep working even when CapsLock is switched on.

**Comment by psychon** [comment]
First thing I note: To set your keymap, run `setxkbmap de -option terminate:ctrl_alt_bksp -option caps:backspace`.

**Comment by psychon** [comment]
Second thing I note: This seems to be fixed in git/master (likely due to the switch to xkbcommon (which is not backportable to the 3.5 branch)).
To test, I started with the default config, applied the above keymap and typed Mod-R (opens a run prompt in the default config) and 1, Caps-Lock, 1, Caps-Lock, 1. With git/master I get "111". When I do something equivalent with awesome 3.5, I instead get "1¹1".

**Comment by psychon** [comment]
Closing this as it is already fixed. Sorry that I cannot provide a solution for 3.5.9.

**Comment by mfrischknecht** [comment]
Thank you very much for looking into it! I was not aware that master
already contained a fix for this. I'll switch to building directly from git
then.

Uli Schlachter <notifications@github.com> schrieb am Fr., 28. Okt. 2016
09:19:

Closing this as it is already fixed. Sorry that I cannot provide a solution
for 3.5.9.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/awesomeWM/awesome/issues/1194#issuecomment-256853572>,
or mute the thread
