### ISSUE TITLE
Window resize is slow

### ISSUE THREAD

**Issue by Alvarocz** [awesomeWM/awesome#1213]
Output of `awesome --version`:

_REPLACE with full version output_

**How to reproduce the issue:**

_REPLACE with step-by-step instructions on what to do_

**Actual result:**

_REPLACE with what happened_

**Expected result:**

_REPLACE with what should happen_

**Comment by blueyed** [comment]
Duplicate of #1209 ?

**Comment by Elv13** [comment]
@Alvarocz please correctly fill the bug report with enough information to be useful. In this case none was provided at all. So it may indeed be a duplicate of #1209 or FS#something (there was a bug for this filled in the days after 3.5.0 was released). I am closing this.

**Comment by Alvarocz** [comment]
Sorry, i had an old version
