### ISSUE TITLE
Active tab indicator square is not scaled with DPI

### ISSUE THREAD

**Issue by l0b0** [awesomeWM/awesome#1214]
Output of `awesome --version`:

```
awesome v3.5.2-2174-g588cbc1 (The Fox)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • RandR 1.5 support: ✔
 • LGI version: 0.9.1
```

**How to reproduce the issue:**

1. Download [`awesome-git`](https://aur.archlinux.org/packages/awesome-git)
1. Unpack it
1. Apply the following diff to `PKGBUILD`:

        20c20
        <          'lua' 'lua-lgi-git' 'pango' 'startup-notification' 'xcb-util-cursor'
        ---
        >          'lua' 'lua-lgi' 'pango' 'startup-notification' 'xcb-util-cursor'
        22c22
        < makedepends=('asciidoc' 'cmake' 'docbook-xsl' 'doxygen' 'imagemagick' 'ldoc-git' 'xmlto')
        ---
        > makedepends=('asciidoc' 'cmake' 'docbook-xsl' 'doxygen' 'imagemagick' 'xmlto')
        47c47,48
        <     -DLUA_LIBRARY=/usr/lib/liblua.so.5.3
        ---
        >     -DLUA_LIBRARY=/usr/lib/liblua.so.5.3 \
        >     -DGENERATE_DOC=False
1. Compile and install using `makepkg --syncdeps --install`
1. Set up your X resources:

        $ cat /etc/X11/Xresources
        Xft.dpi:        276
1. Restart awesome

**Actual result:**

The tab bar font scales up, but the tab state indicator square is still tiny: ![2016-11-09-202242_810x71_scrot](https://cloud.githubusercontent.com/assets/168301/20153466/b64011d6-a6ba-11e6-92d8-31963a0c5645.png)

**Expected result:**

The tab state indicator square should scale with DPI. Possibly it could be a glyph rather than an image?

**Comment by blueyed** [comment]
Related: https://github.com/awesomeWM/awesome/issues/1210.

**Comment by actionless** [comment]
please check if squares are scaled when using `xresources` theme instead of the default one: https://github.com/awesomeWM/awesome/tree/master/themes/xresources

**Comment by psychon** [comment]
In the default config, these squares are just an image and this doesn't have anything "DPI-y" on it. So yup, no scaling
@actionless The `xresources` theme uses `dpi(4)` as the size of the images that it generates on the fly, so of course these will honor DPI.

**Comment by actionless** [comment]
i think it's a time to port all dpi-related stuff from xresources to default theme
