### ISSUE TITLE
We have some slow tests

### ISSUE THREAD

**Issue by psychon** [awesomeWM/awesome#1237]
I was just reminded by [this](https://github.com/awesomeWM/awesome/pull/1236#issuecomment-263113855) that we have this issue. However, I cannot find an issue about this so far. Here it is.

The problem is that `tests/test-awful-client.lua` and `tests/test-awful-tag.lua` are slow. A while ago (in some comment somewhere; we really should have had this issue a long time ago) we figured out that the problem was that some of the intermediate screens are not being garbage collected.

Today I looked into that problem again and here is what I found:
The problem seems to be wibars in connected with screens. When a screen is removed, its wibar (s.mywibar) is [updated](https://github.com/awesomeWM/awesome/blob/333cd6491f57d8ce9b7d665f2b48d8bc8e51682d/lib/wibox/drawable.lua#L475) and now its `_widget_context` refers to another, still existing screen. When that screen is removed, well, our wibar will now keep it alive.

I'm still not sure what the root of this "chain of wibar-screen-wibar-screen-...." is, but this is how the amount of "garbage wibox" keeps increasing...
Ok, the root of this seems to be `mymainmenu.wibox._drawable._widget_context`. So I guess this isn't really relevant "in the real world"?

**Comment by psychon** [comment]
Looking at `test-awful-client.lua` with a profiler says:
- 90% of time in `gears.timer` (so I guess this means inside of `delayed_call`s).
- 66% in `do_redraw` from `wibox.drawable` (this is both relayout and redraw!)
- 38% inside of `hierarchy_update` (so actual relayouts)
- 41% inside of `wibox.hierarchy:draw` (so actual redraws)

The numbers don't quite add up, but I think it's safe to conclude that something is redrawing a lot...

**Comment by psychon** [comment]
Let's look at some relayout and redraw numbers:
```diff
diff --git a/awesomerc.lua b/awesomerc.lua
index f329240..7105b38 100755
--- a/awesomerc.lua
+++ b/awesomerc.lua
@@ -1,3 +1,11 @@
+laycounter, drawcounter = {}, {}
+actlaycounter, actdrawcounter = {}, {}
+function redraw(drawable, hierarchy, x, y, width, height)
+    drawcounter[drawable] = (drawcounter[drawable] or 0) + 1
+end
+function relayout(drawable, hierarchy)
+    laycounter[drawable] = (laycounter[drawable] or 0) + 1
+end
 -- @DOC_REQUIRE_SECTION@
 -- Standard awesome library
 local gears = require("gears")
diff --git a/lib/wibox/drawable.lua b/lib/wibox/drawable.lua
index 268c328..c9518e1 100644
--- a/lib/wibox/drawable.lua
+++ b/lib/wibox/drawable.lua
@@ -71,6 +71,7 @@ local function do_redraw(self)
     -- Relayout
     if self._need_relayout or self._need_complete_repaint then
         self._need_relayout = false
+        actlaycounter[self] = (actlaycounter[self] or 0) + 1
         if self._widget_hierarchy and self.widget then
             self._widget_hierarchy:update(context,
                 self.widget, width, height, self._dirty_area)
@@ -97,6 +98,7 @@ local function do_redraw(self)
     if self._dirty_area:is_empty() then
         return
     end
+    actdrawcounter[self] = (actdrawcounter[self] or 0) + 1
     for i = 0, self._dirty_area:num_rectangles() - 1 do
         local rect = self._dirty_area:get_rectangle(i)
         cr:rectangle(rect.x, rect.y, rect.width, rect.height)
@@ -427,6 +429,7 @@ function drawable.new(d, widget_context_skeleton, drawable_name)
         local x, y, width, height = matrix.transform_rectangle(m, hierar:get_draw_extents())
         local x1, y1 = math.floor(x), math.floor(y)
         local x2, y2 = math.ceil(x + width), math.ceil(y + height)
+        redraw(ret, hierar, x1, y1, x2 - x1, y2 - y1)
         ret._dirty_area:union_rectangle(cairo.RectangleInt{
             x = x1, y = y1, width = x2 - x1, height = y2 - y1
         })
@@ -440,6 +443,7 @@ function drawable.new(d, widget_context_skeleton, drawable_name)
         -- When not visible, we will be redrawn when we become visible. In the
         -- mean-time, the layout does not matter much.
         if ret._visible then
+            relayout(ret, _)
             ret:draw()
         end
     end
diff --git a/tests/test-awful-client.lua b/tests/test-awful-client.lua
index 578f9c1..8874c9b 100644
--- a/tests/test-awful-client.lua
+++ b/tests/test-awful-client.lua
@@ -2,9 +2,36 @@ local awful = require("awful")
 local test_client = require("_client")
 
 awful.util.deprecate = function() end
+function do_print()
+    print("draw counters: ")
+    for k, v in pairs(drawcounter) do
+        print(k, v)
+    end
+    print("actual draw counters: ")
+    for k, v in pairs(actdrawcounter) do
+        print(k, v)
+    end
+    print("layout counters: ")
+    for k, v in pairs(laycounter) do
+        print(k, v)
+    end
+    print("actual layout counters: ")
+    for k, v in pairs(actlaycounter) do
+        print(k, v)
+    end
+    print("clearing")
+    drawcounter, laycounter = {}, {}
+    print()
+    collectgarbage("collect")
+    collectgarbage("collect")
+    collectgarbage("collect")
+    collectgarbage("collect")
+    return true
+end
 
 local has_spawned = false
 local steps = {
+    do_print,
 
 function(count)
 
@@ -75,6 +102,7 @@ assert(not c.floating)
 return true
 end
 end
+, do_print
 }
 
 local original_count, c1, c2 = 0
@@ -238,6 +266,7 @@ table.insert(multi_screen_steps, function()
 
     return true
 end)
+table.insert(multi_screen_steps, do_print)
 
 require("_multi_screen")(steps, multi_screen_steps)
 
```
The result:
Few of these redraws are caused by widgets emitting signals (relayout/redraw), but still there is a metric ton of relayouts and redraws. I tried eliminating the wallpaper-changing in the test, but this didn't help.
Anyone has an idea how to patch `wibox.drawable.draw` to figure out its most frequent callers?
(Line 370 in the file, `ret.draw = function`)

**Comment by Elv13** [comment]
Take it very a very large "this thing is unpredictable", but https://github.com/Elv13/awesome-configs/blob/awesome3_6/utils/profile.lua + KCacheGrind do produce a mostly readable call graph.

**BUT**

You first need to remove the delayed_call and always call the redraw directly. It will be sloooow.

**Comment by psychon** [comment]
> You first need to remove the delayed_call and always call the redraw directly. It will be sloooow.

So... I will investigate lots of effort just to figure out at the end that the above is a bad idea and makes awesome run slowly (because of lots of useless redraws)? Thanks, I'll pass

**Comment by Elv13** [comment]
Well, you want the caller list. It use obfuscated by the delayed call. If you can who triggers the delayed call, then better just dump that as CSV using debug.traceback and get the stats in LibreOffice calc or `sort` + `uniq` in bash
