### ISSUE TITLE
Travis builds fail

### ISSUE THREAD

**Issue by psychon** [awesomeWM/awesome#1242]
```
$ wget https://github.com/lua/lua/releases/download/5.3.3/lua-5.3.3.tar.gz 
--2016-12-01 15:47:00--  https://github.com/lua/lua/releases/download/5.3.3/lua-5.3.3.tar.gz
Auflösen des Hostnamens »github.com (github.com)« … 192.30.253.112, 192.30.253.113
Verbindungsaufbau zu github.com (github.com)|192.30.253.112|:443 … verbunden.
HTTP-Anforderung gesendet, auf Antwort wird gewartet … 404 Not Found
2016-12-01 15:47:01 FEHLER 404: Not Found.
```
Due to commit cf96296f2795a0932ff227d074e3a81c1aa771d2, I'll leave this one for @blueyed to decide. (The tag is now called `5-3-3` instead of `5.3.3`; the only working URL that I found is  https://github.com/lua/lua/archive/v5-3-3.tar.gz ).

This caused a failed travis build for #1240 (and every coming build).

**Comment by blueyed** [comment]
https://github.com/awesomeWM/awesome/pull/1243

**Comment by psychon** [comment]
Thanks! :-)

**Comment by psychon** [comment]
Again: Thank you. You managed to fix this before I even got home and had time to take a look!
