### ISSUE TITLE
doc: include layouts?

### ISSUE THREAD

**Issue by blueyed** [awesomeWM/awesome#1246]
They were included since 400ba86, but some of them actually have useful information, and it allows to link to them.

We could include them and separate them in the doc sidebar by using a new type (https://github.com/awesomeWM/awesome/blob/4cb11b8754f20ad86a7fb389d9541175f7b13f87/docs/config.ld#L50-L51), or something similar.

What do you think?

**Comment by Elv13** [comment]
Maybe add them as `awful.layout` submodules? This way it wont pollute the index with many little documented entries?

**Comment by Elv13** [comment]
PR coming
