### ISSUE TITLE
The piechart-widget draws its "pie pieces" in a non-deterministic order.

### ISSUE THREAD

**Issue by psychon** [awesomeWM/awesome#1249]
I'll copy from https://github.com/awesomeWM/awesome/issues/834#issuecomment-264442256

> And here are the two images:
> https://github.com/awesomeWM/apidoc/blob/9963bf794e719c6937d3bd342ec78cc66b1cdb3b/images/AUTOGEN_wibox_widget_piechart_label.svg
> https://github.com/awesomeWM/apidoc/blob/21583d2133edab6adf6dfce7fb5105d9e16d6233/images/AUTOGEN_wibox_widget_piechart_label.svg
> 
> As you can see, the order in which the piechart draws things changes non-deterministically. And that's a serious bug. This means that a redraw might not actually work!
> Imagine if only half the widget is redrawn, but the widget now decides to change the order of things. The result will be broken.

So I think the piechart widget at least needs a change to get a deterministic iteration order of `self._private.data`. It would also be nice to expose an API so that the data can be given to the widget in a deterministic order, i.e. "first display 'foo' with 33%, then display 'bar' with 67% and finally 'foobar' with 33%". As far I see, that's not yet possible either.

- [ ] piechart needs deterministic iteration order
- [ ] piechart should provide API for "working with" this deterministic order.

**Comment by psychon** [comment]
Assigning to @Elv13 under the assumption that he would want to work on this. Feel free to un-assign if you don't want this.

**Comment by psychon** [comment]
This issue seems to affect all tests for the piechart widget:
![changes](https://cloud.githubusercontent.com/assets/89482/20834710/fcb69228-b896-11e6-9c00-2f5132799bb6.png)

**Comment by Elv13** [comment]
Already discussed in #897. It's worth fixing, but it isn't really an user facing issues. The widget don't flicker and/or change at runtime unless you add/remove pies
