### ISSUE TITLE
Provide signatures

### ISSUE THREAD

**Issue by sonicou** [awesomeWM/awesome#1254]
Please provide pgp signatures for future releases.
Thank you very much for your work.

**Comment by psychon** [comment]
The [release announcement mails](http://www.mail-archive.com/awesome@naquadah.org/msg07828.html) are PGP-signed and contain the md5 and sha1 hashes of the released filed (newer announcement use sha2 hashes, but I can't find any such mail right now). So I just want to mention that there already is a chain of trust towards the released files, but I agree that it is inconvenient and providing a detached signature is a good idea.

The step-by-step list that is used for doing releases is available (but will soon need to be updated). 
https://github.com/awesomeWM/awesome/blob/master/docs/doing_a_release.md
I guess adding a `gpg --output $FILE.sig --detach-sig $FILE` step is all that is needed to handle this.

**Comment by sonicou** [comment]
Thanks.
For distro maintainers it is important to have signatures for easy and automated verification.
