### ISSUE TITLE
"Do something about the web page"

### ISSUE THREAD

**Issue by psychon** [awesomeWM/awesome#1268]
This is not really an issue in the usual sense.

Since @Elv13 is working hard on making a release possible (thanks!), I wanted to document another blocker that I had in my mind for a while, but didn't write down (sorry!): I cannot (easily) update the (old) web page any more.
After the announcement that the old web page will go away, we set up things so that the web page can be hosted via GitHub-pages and Travis auto-builds the web page. These chances are not compatible with the old way to manage the web page since they break/replace the old infrastructure to manage the web page.

Thus, before a release we should
- [x] replace awesomewm.org being a redirect to naquadah with what new.awesomewm.org does (redirect to github). 
- [x] ask @jd to redirect awesome.naquadah.org to awesomewm.org (but only after awesomewm.org no longer redirects to naquadah, else hilarity ensues).

So, since time is running out anyway and nothing is happening for the web page transition anyway, I propose we just make the switch now and deal with the fallout.

CC @blueyed

**Comment by blueyed** [comment]
@psychon 
Done the first part (in CloudFlare), and changed the CNAME file in the awesomeWM.github.io repo.
https://new.awesomewm.org/apidoc/ etc gets redirected to https://awesomewm.org/apidoc/ now.

**Comment by psychon** [comment]
Thanks!

@jd What do you think about such a redirect now?

**Comment by jd** [comment]
Done! http://awesome.naquadah.org redirect to http://awesomewm.org now.

**Comment by psychon** [comment]
Thanks!
