### ISSUE TITLE
Crash due to lgi bug

### ISSUE THREAD

**Issue by psychon** [awesomeWM/awesome#127]
Hi,

I'll let a wall of text speak for itself:

    E: awesome: signal_fatal:254: signal 11, dumping backtrace
    ./awesome(backtrace_get+0x41) [0x423f12]
    ./awesome() [0x40ccea]
    /lib/x86_64-linux-gnu/libc.so.6(+0x35180) [0x7fa5bec4d180]
    /lib/x86_64-linux-gnu/libc.so.6(cfree+0x14) [0x7fa5bec944a4]
    /lib/x86_64-linux-gnu/libglib-2.0.so.0(g_string_free+0x3b) [0x7fa5c146a83b]
    /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_boxed_free+0x13b) [0x7fa5c171d70b]
    /usr/lib/x86_64-linux-gnu/lua/5.1/lgi/corelgilua51.so(+0xed5e) [0x7fa5baf8cd5e]
    /usr/lib/x86_64-linux-gnu/lua/5.1/lgi/corelgilua51.so(lgi_marshal_2lua+0x3cc) [0x7fa5baf9020c]
    /usr/lib/x86_64-linux-gnu/lua/5.1/lgi/corelgilua51.so(+0x82ca) [0x7fa5baf862ca]
    /usr/lib/x86_64-linux-gnu/lua/5.1/lgi/corelgilua51.so(+0xa1c6) [0x7fa5baf881c6]
    /usr/lib/x86_64-linux-gnu/liblua5.1.so.0(+0xc1f0) [0x7fa5bf5161f0]
    /usr/lib/x86_64-linux-gnu/liblua5.1.so.0(+0x16d42) [0x7fa5bf520d42]
    /usr/lib/x86_64-linux-gnu/liblua5.1.so.0(+0xc64d) [0x7fa5bf51664d]
    /usr/lib/x86_64-linux-gnu/liblua5.1.so.0(+0xb92e) [0x7fa5bf51592e]
    /usr/lib/x86_64-linux-gnu/liblua5.1.so.0(+0xc7bb) [0x7fa5bf5167bb]
    /usr/lib/x86_64-linux-gnu/liblua5.1.so.0(lua_pcall+0x5c) [0x7fa5bf51242c]
    ./awesome() [0x4191ac]
    ./awesome(luaA_parserc+0x61) [0x41bdc0]
    ./awesome(main+0x863) [0x40d6a6]
    /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf5) [0x7fa5bec39b45]
    ./awesome() [0x40ca59]

So I bisected and found:

    $ git bisect good
    0a76e41cb850e67c34085a4e3aa87b11424588d7 is the first bad commit
    commit 0a76e41cb850e67c34085a4e3aa87b11424588d7
    Author: Daniel Hahler <git@thequod.de>
    Date:   Tue Feb 10 00:59:15 2015 +0100
    
        Use lgi.GLib.String():append(tb):hash()
    
    :040000 040000 d7ec53bbf2b9e5104eac6deed572aee6f11093e7     7f3f56c3384068ecc9dd979d3529a0491121866a M	lib

A quick experiment confirms:

    $ lua -e 'require("lgi").GLib.String():append("foo")'
    *** Error in `lua': munmap_chunk(): invalid pointer: 0x00000000007ea2e0 ***
    [1]    11823 abort      lua -e 'require("lgi").GLib.String():append("foo")'

Looking at lgi's `lgi/override/GLib.lua` I can't find anything interesting, so I guess the bug must be in GLib. I have glib 2.42.1 installed and a quick look into glib's git repo didn't find anything that would explain this behavior.

I would suggest to just stop using `GLib.String()` (you only call it for the hash anyway) and use the backtrace string directly as key in the table.

By the way: lua intern's strings anyway (so a pointer uniquely identifies the string), so it kind-of hashes the string already. Going through lgi to obtain another hash cannot really speed things up much, I guess.

Edit:

Now I think that this bug is in lgi:

    [...]
    ==12951== Command: lua -e require("lgi").GLib.String():append("foo")
    ==12951== 
    ==12951== Invalid read of size 8
    ==12951==    at 0x6863830: g_string_free (in /lib/x86_64-linux-gnu/libglib-2.0.so.0.4200.1)
    ==12951==    by 0x63B170A: g_boxed_free (in /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.4200.1)
    ==12951==    by 0x5F65D5D: ??? (in /usr/lib/x86_64-linux-gnu/liblua5.1-lgi.so.0.0.0)
    [...]
    ==12951==  Address 0x5c80510 is 0 bytes inside a block of size 24 free'd
    ==12951==    at 0x4C29E90: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
    ==12951==    by 0x6863822: g_string_free (in /lib/x86_64-linux-gnu/libglib-2.0.so.0.4200.1)
    ==12951==    by 0x63B170A: g_boxed_free (in /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.4200.1)
    ==12951==    by 0x5F65D5D: ??? (in /usr/lib/x86_64-linux-gnu/liblua5.1-lgi.so.0.0.0)
    ==12951==    by 0x5F6920B: lgi_marshal_2lua (in /usr/lib/x86_64-linux-gnu/liblua5.1-lgi.so.0.0.0)
    [...]

I will also open a bug report there, but for now awesome cannot use this function.

**Comment by blueyed** [comment]
See also https://github.com/pavouk/lgi/issues/100 - I am going to revert using glib here.
