### ISSUE TITLE
Restore last position of windows

### ISSUE THREAD

**Issue by llatigid** [awesomeWM/awesome#1273]
Hello Awesome! It's not an issue, it's an idea -- the option, that remembers a window last position and its next re-opening will be exactly at the same place. Could you support the brilliant feature?

**Comment by Elv13** [comment]
@mindeunix has a module (at least in theory) capable of doing this. 

https://github.com/mindeunix/clientdb

Awesome is mostly used as a tiled WM. Therefor this feature makes little sense for the majority of the user base. KDE and some others applications also implement this themselves. Having our own system would just fight against this.

Finally, if you want this and still doesn't want to use @mindeunix module, then this is something that belongs to `rc.lua` or an external module, not the Awesome core. It is one of these "it wont ever work perfectly"* features we avoided adding to Awesome.

I will close this for now. If another member of the team thinks I am wrong, then they will re-open it.

* We already have input grabbing, the systray, startup-notification and the current screen algorithm. Each of them is a nightmare to maintain.

**Comment by Elv13** [comment]
The documentation (for 4.0, but still) has been updated to better guide you if you wish to enable such feature:
https://awesomewm.org/apidoc/libraries/awful.spawn.html
