### ISSUE TITLE
Local failures with tests/run.sh

### ISSUE THREAD

**Issue by blueyed** [awesomeWM/awesome#1292]
I am getting the following failures locally:

```
== Running …/src/awesome/tests/test-awesomerc.lua ==
Error: timeout waiting for signal in step 1/11 (@20).
===> ERROR running …/src/awesome/tests/test-awesomerc.lua! <===
Error: timeout waiting for signal in step 1/11 (@20).

===> ERROR running …/src/awesome/tests/test-awful-layout.lua! <===
Error: timeout waiting for signal in step 1/182 (@20).

===> ERROR running …/src/awesome/tests/test-awful-tag.lua! <===
Error: timeout waiting for signal in step 1/61 (@20).
== Running …/src/awesome/tests/test-awful-widget-button.lua ==
Test finished successfully
== Running …/src/awesome/tests/test-awful-widget-watch.lua ==

== Running …/src/awesome/tests/test-resize.lua ==
Error: running function for step 11/39 (@1): [string "local test_client = require("_client")..."]:188: assertion failed!
stack traceback:
        [C]: in function 'assert'
        [string "local test_client = require("_client")..."]:188: in function <[string "local test_client = require("_client")..."]:186>
        [C]: in function 'xpcall'
        …/src/awesome/tests/_runner.lua:49: in function <…/src/awesome/tests/_runner.lua:43>
        [C]: in function 'xpcall'
        lib/gears/protected_call.lua:30: in function 'protected_call'
        lib/gears/timer.lua:167: in function <lib/gears/timer.lua:165>!
===> ERROR running …/src/awesome/tests/test-resize.lua! <===
Error: running function for step 11/39 (@1): [string "local test_client = require("_client")..."]:188: assertion failed!

== Running …/src/awesome/tests/test-urgent.lua ==
Error: timeout waiting for signal in step 2/4 (@5).
===> ERROR running …/src/awesome/tests/test-urgent.lua! <===
Error: timeout waiting for signal in step 2/4 (@5).
```

The first one should be fixed by https://github.com/awesomeWM/awesome/pull/1289, but I am wondering why this is only an issue for me locally, and not Travis and you?!

**Comment by psychon** [comment]
No time to look much into it, but my guess is that the previous test still had some clients open that didn't exit fast enough (`c:kill()` takes some time). Dunno about the other tests. Do things also fail if you run the tests individually? Dunno, other ideas...?

**Comment by blueyed** [comment]
Yes, IIRC it also happens when running the file alone.
Maybe it is related to my config.. will try with https://github.com/awesomeWM/awesome/commit/fb874122ba1ac06a3af29c39c5abe6415e77bbf8 again later.

**Comment by blueyed** [comment]
With the recent changes, it might still fail:

`tests/run.sh test-awesomerc.lua` now just opened three xterms, but `spawn` returned pids for each call.
With three of them there is no subprocess/shell though?!

  |-xterm,9547
  |   `-sh,9552
  |-xterm,9549
  |-xterm,9553
  |-xterm,9555
  |   `-sh,9559
  |-xterm,9557
  |   `-sh,9561

**Comment by psychon** [comment]
Weird. What do those `xterm`s display? Sounds like some kind of problem on the xterm side then, no? Perhaps some maximum-process-count `ulimit` that is hit?

**Comment by blueyed** [comment]
They are not visible.. only 3 windows were there in this case.

I wanted to poke at them using `xwininfo`, but then the tests were killed (`timeout_stale`).
But it's not hard to reproduce (at least yesterday/earlier), so I just need to investigate a bit more.

**Comment by blueyed** [comment]
Second "meh" today: it's caused by my rxvt-unicode wcwidth-callback-hack (`wcwidth(3)` via `LD_PRELOAD`), where the read on the socket blocks / (deadlocks?) forever (IIRC I was using some flocking with the socket approach, but am currently using the AUR PKGBUILD mainly, which does not have that probably).
I have some local (even more) WIP to use terminal escape codes (OSC) instead of a socket, but that was not used here apparently, too.
