### ISSUE TITLE
Visible clients include (invisible) desktop client

### ISSUE THREAD

**Issue by blueyed** [awesomeWM/awesome#1299]
I've noticed that `awful.client.visible(focused_screen())` includes the `desktop` window for Nemo.

Should clients with `type == 'desktop'` be filtered out here?
https://github.com/awesomeWM/awesome/blob/69915fb6585ec483844635d02992d7c75cc6fc25/lib/awful/screen.lua#L318-L327

**Comment by psychon** [comment]
I don't understand why a desktop client should be treated as invisible? They are visible.

**Comment by blueyed** [comment]
Hmm.. fair point.
My use case is a mapping/function that goes to the first client in the task list, and I've used that function for it.
I should then probably also look at `skip_taskbar` etc.
