### ISSUE TITLE
API: awful.client.visible not fully supported by screen.clients

### ISSUE THREAD

**Issue by blueyed** [awesomeWM/awesome#1300]
[`awful.client.visible`](https://github.com/awesomeWM/awesome/blob/69915fb6585ec483844635d02992d7c75cc6fc25/lib/awful/client.lua#L108-L124) is deprecated in favor of the [`screen.clients`](https://github.com/awesomeWM/awesome/blob/69915fb6585ec483844635d02992d7c75cc6fc25/lib/awful/screen.lua#L305-L327) property, but the latter does not provide an option to get the clients in non-stacking order.

Should there be a new property or some method for this on screens?

The same applies to [`awful.client.tiled`](https://github.com/awesomeWM/awesome/blob/69915fb6585ec483844635d02992d7c75cc6fc25/lib/awful/client.lua#L126-L146).

**Comment by Elv13** [comment]
you could add the stacked clients to `screen.object.get_clients`. It will have to be called "the old way" `s:get_clients(false)`. Please note that `.clients` *is* using the stacking order.
