### ISSUE TITLE
Ugly space between clients

### ISSUE THREAD

**Issue by cyberxndr** [awesomeWM/awesome#1308]
**Output of awesome --version**

```
awesome v4.0 (Harder, Better, Faster, Stronger)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • RandR 1.5 support: ✔
 • LGI version: 0.9.1
```

**How to reproduce the issue:**

* choose "tile" layout (most of layouts are affected)
* open a few clients (5-8 in my case)
* (optional) play with `awful.tag.incmwfact()` a bit

**Actual result:**

![r1](https://cloud.githubusercontent.com/assets/2040537/21495207/3d135ba0-cc27-11e6-92e8-bc6fdc9d1c4d.png)
![r2](https://cloud.githubusercontent.com/assets/2040537/21495208/3d13836e-cc27-11e6-92d2-edf06aa3b54b.png)

**Expected result:** (from awesome v3.5.9)

![e1](https://cloud.githubusercontent.com/assets/2040537/21495215/45be0282-cc27-11e6-8a67-a33e0db39905.png)
![e2](https://cloud.githubusercontent.com/assets/2040537/21495216/45e8510e-cc27-11e6-9c8a-af8b3f048a9d.png)

**Additional info:**

* `theme.useless_gap` is default and set to 0
* note also a 1px overlap between the master and slave clients on the second screenshot

**Comment by psychon** [comment]
No idea right now and I cannot reproduce locally with urxvt (However I'm running a slightly old awesome version from 23rd of december).

> choose "tile" layout (most of layouts are affected)

Just to rule out the obvious: You know about the "size_hints_honor" property and have something like `size_hints_honor = false` set for the terminals from the screenshot?
Does it only happen with terminals?
(And no, I do not understand where the overlap is coming from)

**Comment by cyberxndr** [comment]
Seems like only terminal affected. `size_hints_honor = false` fixes the problem. I don't used it in the previous versions though. Thanks for the hint :)

**Comment by psychon** [comment]
I am pretty sure that the previous version should have the same behaviour, weird...
