### ISSUE TITLE
wibox.widget.keyboardlayout() throws error

### ISSUE THREAD

**Issue by VincentWo** [awesomeWM/awesome#1313]
Output of `awesome --version`:
awesome v4.0-1-gfdc93e68 (Harder, Better, Faster, Stronger)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • RandR 1.5 support: ✔
 • LGI version: 0.9.1

**How to reproduce the issue:**

Use `wibox.widget.keyboardlayout()` anywhere

**Actual result:**

Error: `attempt to call a nil value( field 'keyboardlayout')`

**Expected result:**

No error

wibox was imported with `wibox = require("wibox")`.

The widget is documented [here](https://awesomewm.org/apidoc/classes/wibox.widget.keyboardlayout.html).

Interestingly `awful.widget.keyboardlayout()` works, even though it isn't listed in the documentation. Maybe a documentation bug?

**Comment by psychon** [comment]
> Maybe a documentation bug?

Yup. And quite a weird one, I guess this is a copy&paste error. Thanks for spotting it.
