### ISSUE TITLE
Moved to other screen maximized window un-maximizes on first screen

### ISSUE THREAD

**Issue by taptap** [awesomeWM/awesome#1320]
Output of `awesome --version`:

    awesome v4.0 (Harder, Better, Faster, Stronger)
     • Compiled against Lua 5.2.4 (running with Lua 5.2)
     • D-Bus support: ✔
     • execinfo support: ✔
     • RandR 1.5 support: ✔
     • LGI version: 0.9.1

**How to reproduce the issue:**
1. Have two screens. Layout doesn't matter.
2. `S-Ret S-m S-o` on first screen to:
    * create terminal window (actually any window will do)
    * maximize it, and
    * send to other screen.
3. `S-m` on other screen when focused on terminal window from previous step.

**Actual result:**
Terminal window un-maximizes *on the first screen*.
Focus remains on the second screen.

**Expected result:**
I don't really know, but I personally expect window to un-maximize on the screen it currently belongs to.

**Comment by psychon** [comment]
This is also due to `awful.placement` restoring the old geometry of the client ignoring any move-to-other-screen that happened in between.
CC @Elv13

**Comment by Elv13** [comment]
Is this really a bug? Should it keep the `[x,y]` as a relative pair to the parent?

**Comment by psychon** [comment]
At least it is a regression. For example, this is what `awful.ewmh` used to do on screen changes: https://github.com/awesomeWM/awesome/blob/4628b15235612848c6e71329701973dcdbecac41/lib/awful/ewmh.lua.in#L97-L109 (but it did not handle workarea changes...)

**Comment by blueyed** [comment]
Yes, I consider this a bug, too - and noticed it myself a few times.
