### ISSUE TITLE
Float mode un-maximization doesn't restore window width

### ISSUE THREAD

**Issue by taptap** [awesomeWM/awesome#1321]
Output of `awesome --version`:
```
awesome v4.0 (Harder, Better, Faster, Stronger)
 • Compiled against Lua 5.2.4 (running with Lua 5.2)
 • D-Bus support: ✔
 • execinfo support: ✔
 • RandR 1.5 support: ✔
 • LGI version: 0.9.1
```
**How to reproduce the issue:**
1. Have tag in floating layout.
2. `S-Ret S-m S-m` to create terminal (e.g., any window will do), maximize and un-maximize it.

**Actual result:**
Window's height is restored to what it was before maximization, but width is not.

**Expected result:**
Width is also returned to what it was before.

**Comment by taptap** [comment]
This might be a regression since 3.5.

**Comment by psychon** [comment]
Technical reason for this is that we have `maximized_vertically` and `maximized_horizontally`. Setting `maximized` sets both one after the other and the new code in `awful.placement` apparently stores an "in between" position for later.
CC @Elv13

**Comment by blueyed** [comment]
Should be fixed now with https://github.com/awesomeWM/awesome/pull/1453 being merged.
