### ISSUE TITLE
People trying to create their first widgets are took off by "callback is not a function" errors

### ISSUE THREAD

**Issue by skrzyp** [awesomeWM/awesome#1326]
Output of `awesome --version`:
```
awesome v4.0 (Harder, Better, Faster, Stronger)
 • Compiled against Lua 5.2.4 (running with Lua 5.2)
 • D-Bus support: ✔
 • execinfo support: ✔
 • RandR 1.5 support: ✔
 • LGI version: 0.9.1
```

**How to reproduce the issue:**

1. Put the following code in your `rc.lua`

```lua
mybatterybar = wibox.widget( {
                {
                max_value    = 1,
                value        = 0,
                paddings     = 1,
                border_width = 1,
                forced_width = 100,
                border_color = beautiful.border_color,
                widget       = wibox.widget.progressbar,
               },
               {
                text         = "0",
                widget       = wibox.widget.textbox,
               },
               layout        = wibox.layout.stack
              } )
mybatterybar.set_battery = function()
        local charge = tonumber(awful.util.pread("acpi |cut -d, -f 2 | cut -c 2-3"))
        mybatterybar.wibox.widget.progressbar:set_value(charge)
        mybatterybar.wibox.widget.textbox:set_markup(charge)
    end

mybatterybar.connect_signal("mouse::enter", mybatterybar.set_battery)
```

2. Put the `mybatterybar` into the list of your `wibar` widgets

**Actual result:**

```
error while running function!
stack traceback:
	[C]: in function 'assert'
	/usr/share/awesome/lib/gears/object.lua:51: in function 'connect_signal'
	/home/skrzyp/.config/awesome/rc.lua:141: in main chunk
error: /usr/share/awesome/lib/gears/object.lua:51: callback must be a function, got: nil
```

**Expected result:**

Nice and friendly battery bar with text updatie when mouse enters the bar area

**Proposed solution:**

Document some example widgets to get people started with them as a base for their own setups, especially when they decided to not use any external library.

**Comment by Elv13** [comment]
mybatterybar.connect_signal("mouse::enter", mybatterybar.set_battery)

to

    mybatterybar:connect_signal("mouse::enter", mybatterybar.set_battery)

Soved on IRC, closing this. I will add some timer examples in a future PR and try to clarify the doc about the different syntaxes

**Comment by psychon** [comment]
```lua
local charge = tonumber(awful.util.pread("acpi |cut -d, -f 2 | cut -c 2-3"))
```
Just for people trying this out: `awful.util.pread` is deprecated and was changed to always return an empty string. So, even with the `connect_signal` fixed, the code will still not work.
