### ISSUE TITLE
Make a new website design.

### ISSUE THREAD

**Issue by aajjbb** [awesomeWM/awesome#1327]
Hi, 
This isn't a truly issue, but it's something I've mentioned in IRC times ago. The current design of awesome site doesn't looks 'recent'. I do believe that possible new users who reach the page have a first impression that Awesome hasn't been developed in ages, and it's not good.

Why I'm creating this issue ? I don't have enough design skills to create a better and 2016-ish UI for the page, but I would gladly help with a possible new site code (html/css/js). 

It would be nice to use this issue/thread to discuss possible improvements and maybe to lure someone skilled to help the project.

**Comment by holgerschurig** [comment]
The new luadoc contents looks good, so maybe use just this as the landing page?

**Comment by taptap** [comment]
I like current site. Clean, nice and small. Without unnecessary fancy details.
As for state of development, dates of latest release and latest commit are sufficent in my opinion. Maybe site will benefit if someone makes them a bit more conspicuous.

Also, what current site *really* needs is a "Screenshots" section in the main menu. With a showcase of variety of setups, plugins, themes, whatnot

**Comment by aajjbb** [comment]
As I mentioned before, I do like the current site design, I don't think it's bad, but it looks 'outdated'. My point is that it 'might' not be an attractive to new users. 

Couldn't agree more on the Screenshot section. A show case of setups and plugins (resembling the old wiki) would be nice as well.

**Comment by skrzyp** [comment]
Maybe not the design itself is an issue, but consistency between `luadoc` section and landing page. While most of content is the documentation, the landing page might be simply restyled to match the design of docs.

Isn't that reasonable?

**Comment by aajjbb** [comment]
@skrzyp That sound's very reasonable, I'm still checking how ikiwiki (the tool the current site is built) works. 

What's your opinion about ikiwiki. Should the site stick with it or thinking about a new something is feasible ? I believe that tool was used when awesome had a wiki, now that it's gone, maybe a plain site without that Perl dependencies is enough.

**Comment by skrzyp** [comment]
I don't have any strong opinions about ikiwiki, haven't used it anywhere.
But I think the landing site, as a static webpage, might be made using simple makefiles from plain/markdown files, see:

http://git.2f30.org/divzeroweb/files.html
https://github.com/alpinelinux/alpine-mksite

**Comment by aajjbb** [comment]
I agree that plain Makefiles would be better than the ikiwiki stack (depends on some perl packages)

**Comment by psychon** [comment]
> Couldn't agree more on the Screenshot section. A show case of setups and plugins (resembling the old wiki) would be nice as well.

Pull requests welcome. :-)
I don't think I have much time for this. Also, every time I look at the old wiki to look for content to rescue, I go crazy from all the outdated content which never even worked on v3.5 and the 404s I run into it. Feel free to point out things that should be kept, since this seems to be the hard part for me...

> I agree that plain Makefiles would be better than the ikiwiki stack (depends on some perl packages)

Portable Make? GNU make? BSD make? Without a template language so that one can have lots of fun typing HTML?

What's bad about a dependency on "some" perl packages? Why is reinventing the wheel a better idea?

**Comment by aajjbb** [comment]
> Pull requests welcome. :-)
That's great, I just wanted to hear opinions about what and how to improve the current site.

> What's bad about a dependency on "some" perl packages? Why is reinventing the wheel a better idea?
I don't think it's a good idea, but I had in mind the we would keep the site simple, getting rid of old wiki data (which is bad in my opinion). So as we do have plans to save important data and keep it in the site, a template language works fine.

**Comment by Elv13** [comment]
> getting rid of old wiki data (which is bad in my opinion)

It was necessary. See https://www.reddit.com/r/awesomewm/comments/5k9vob/what_happened_to_the_wiki/ for a longer explanation.

**Comment by aajjbb** [comment]
Any opinions on this ?
![screenshot at 2016-12-31 18-57-50](https://cloud.githubusercontent.com/assets/548932/21579233/2c3a2464-cf8b-11e6-967f-b5d95eef96ad.png)

**Comment by psychon** [comment]
Looks a bit too minimalistic for my taste and "awesome" and "home" are too close to each other (the space between them is smaller than the space between the other items).

**Comment by gutierri** [comment]
This is a good example of clean and minimalist => https://stumpwm.github.io/
