### ISSUE TITLE
Docking windows affects other tags

### ISSUE THREAD

**Issue by pstn** [awesomeWM/awesome#1335]
Output of `awesome --version`:

    awesome devel (Harder, Better, Faster, Stronger)
     • Compiled against Lua 5.2.3 (running with Lua 5.2)
     • D-Bus support: ✔
     • execinfo support: ✔
     • RandR 1.5 support: ✔
     • LGI version: 0.7.2

(Build from current master branch)

**How to reproduce the issue:**

* make window dockable on tag 2
* dock window on tag 2
* switch to tag 1
* open window there

**Actual result:**

* the window ignores the spaces taken up by a docked window on tag 2

**Expected result:**

* The fact that something is docked on tag 2 doesn't affect tag 1 at all

**Note:**
I'm not really sure that my idea of what should happen is correct but the current behaviour seems strange to me.

**Comment by psychon** [comment]
How exactly are docking the window? What does "open window there" mean exactly?
I don't think docking a window is a per-tag thing currently. It would then be docked on any tag on which it is visible, but I'm not completely sure.

**Comment by pstn** [comment]
> How exactly are docking the window? 

I have a rule that makes my jabber roster dockable and I move it to the right edge of the screen.

>What does "open window there" mean exactly?

It means that I open a window that is only tagged with 1, nothing else

> I don't think docking a window is a per-tag thing currently. It would then be docked on any tag on 
which it is visible, but I'm not completely sure.

OK, the issue is that the docked window is not visible on tag 1, but the window that is only visible on tag 1 still doesn't use the space.

**Comment by psychon** [comment]
Ah, ok. That sounds like the screen's workarea is incorrect. I do not have the time to try to reproduce this right now, but something like the following might help (sigh, another trailing whitespace that my vim kills...):
```diff
diff --git a/objects/client.c b/objects/client.c
index eb4de5007..ac3c9cc2b 100644
--- a/objects/client.c
+++ b/objects/client.c
@@ -1797,6 +1797,8 @@ client_set_sticky(lua_State *L, int cidx, bool s)
     {
         c->sticky = s;
         banning_need_update();
+        if(strut_has_value(&c->strut))
+            screen_update_workarea(c->screen);
         luaA_object_emit_signal(L, cidx, "property::sticky", 0);
     }
 }
diff --git a/objects/tag.c b/objects/tag.c
index 45624d7b0..a53999d67 100644
--- a/objects/tag.c
+++ b/objects/tag.c
@@ -277,7 +277,8 @@ tag_view(lua_State *L, int udx, bool view)
     {
         tag->selected = view;
         banning_need_update();
-
+        foreach(screen, globalconf.screens)
+            screen_update_workarea(*screen);
         luaA_object_emit_signal(L, udx, "property::selected", 0);
     }
 }
@@ -318,6 +319,7 @@ tag_client(lua_State *L, client_t *c)
     client_array_append(&t->clients, c);
     ewmh_client_update_desktop(c);
     banning_need_update();
+    screen_update_workarea(c->screen);
 
     tag_client_emit_signal(t, c, "tagged");
 }
@@ -336,6 +338,7 @@ untag_client(client_t *c, tag_t *t)
             client_array_take(&t->clients, i);
             banning_need_update();
             ewmh_client_update_desktop(c);
+            screen_update_workarea(c->screen);
             tag_client_emit_signal(t, c, "untagged");
             luaA_object_unref(L, t);
             return;
@@ -357,7 +360,7 @@ is_client_tagged(client_t *c, tag_t *t)
     return false;
 }
 
-/** Get the index of the tag with focused client or first selected 
+/** Get the index of the tag with focused client or first selected
  * \return Its index
  */
 int
```

**Comment by pstn** [comment]
Thanks, the issue is fixed for me, too.
