### ISSUE TITLE
Awesome 4.0 - mouse buttons not working

### ISSUE THREAD

**Issue by dragonnn** [awesomeWM/awesome#1337]
Output of `awesome --version`:

awesome v4.0 (Harder, Better, Faster, Stronger)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • RandR 1.5 support: ✔
 • LGI version: 0.9.1

**How to reproduce the issue:**

Installed awesome 4.0, adjusted some bugs in my config (changed mouse.screen to mouse.screen.index)

**Actual result:**

I can not focus windows with mouse click on it, can not move windows

**Expected result:**

This code should work:
clientbuttons = awful.util.table.join(
    awful.button({ }, 1, function (c) client.focus = c; c:raise() end),
    awful.button({ modkey }, 1, awful.mouse.client.move),
    awful.button({ modkey }, 3, awful.mouse.client.resize)
)

**Comment by blueyed** [comment]
Do  you see any output/errors on awesome's `stderr`?
Sounds like there might be some error causing this.

Also try the default config, it should work there.

**Comment by dragonnn** [comment]
How can I access stderr? Will try default config

**Comment by dragonnn** [comment]
Witch default config it works :/. I would be really thankful for any help getting it working with my old config. http://pastebin.com/MzXMnN8H i posted it here.

**Comment by blueyed** [comment]
@dragonnn 
It depends on how you start `awesome`.  It might be in `~/.local/share/xorg/Xorg.${DISPLAY#:}.log`.

**Comment by dragonnn** [comment]
I use ligthdm, in ~/.local/share i don't have xorg and in /var/log/Xorg.0.log I don't see anything about awesome.

**Comment by psychon** [comment]
> adjusted some bugs in my config (changed mouse.screen to mouse.screen.index)

There are more things you have to change in your config. :-)

The output might be in `~/.xsession-errors`.

Could you show us your config somewhere so that we can try ourselves to see what the problem is?

**Comment by dragonnn** [comment]
I posted it already, here is .xsession-errors http://pastebin.com/dR0sMkaH

**Comment by psychon** [comment]
Sorry, but I cannot see a link to your config. What am I missing?

**Comment by dragonnn** [comment]
http://pastebin.com/MzXMnN8H do you see it now?

**Comment by Elv13** [comment]
Hello, this config has not been properly ported to 4.0. It has multiscreen issues and deprecated functions. You should start with a fresh config and backport your changes. If you prefer to port, then there is a porting guide in out documentation. Fixing all the errors is *not* enough to port a config to Awesome 4.0 as important logic will be missing.

**Comment by psychon** [comment]
The following change fixes the reported issue. No idea how this worked previously for you. The problem was that you never set the keys and buttons on a client (this bug report is only about the buttons, but I fixed the keys anyway):
```diff
--- rc.lua.loads	2016-12-31 09:47:51.297940593 +0100
+++ rc.lua	2016-12-31 09:48:16.101454404 +0100
@@ -468,6 +468,8 @@ root.keys(globalkeys)
 -- {{{ Signals
 -- Signal function to execute when a new client appears.
 client.connect_signal("manage", function (c, startup)
+	c:keys(clientkeys)
+	c:buttons(clientbuttons)
     if not startup then
         -- Set the windows at the slave,
         -- i.e. put it at the end of others instead of setting it master.
```
Additionally (and just FYI) I had to do the following changes just so that the config loads here without erroring:
```diff
--- rc.lua.orig	2016-12-31 09:43:52.566598532 +0100
+++ rc.lua.loads	2016-12-31 09:47:51.297940593 +0100
@@ -7,15 +7,16 @@ require("awful.autofocus")
 local wibox = require("wibox")
 -- Theme handling library
 local beautiful = require("beautiful")
-beautiful.init("/home/dragonnnew/.config/awesome/themes/default/theme.lua")
+--beautiful.init("/home/dragonnnew/.config/awesome/themes/default/theme.lua")
+beautiful.init("/usr/share/awesome/themes/default/theme.lua")
 -- Notification library
 local naughty = require("naughty")
 
 
-local vicious = require("vicious")
+--local vicious = require("vicious")
 
-local wi	 = require("wi")
-local volume = require("volume")
+--local wi	 = require("wi")
+--local volume = require("volume")
 
  -- menubar.set_icon_theme("theme name")
 -- powiadomienia
@@ -257,17 +258,17 @@ for s = 1, screen.count() do
     -- Widgets that are aligned to the right
     local right_layout = wibox.layout.fixed.horizontal()
     if s == 1 then 
-		right_layout:add(space)
-		right_layout:add(mailWidget) 
-        right_layout:add(space)
+		--right_layout:add(space)
+		--right_layout:add(mailWidget) 
+        --right_layout:add(space)
 		right_layout:add(wibox.widget.systray()) 
-		right_layout:add(space)
-		right_layout:add(volicon)
-		right_layout:add(space)
-		right_layout:add(alsawidget.barm)
-		right_layout:add(space)
+		--right_layout:add(space)
+		--right_layout:add(volicon)
+		--right_layout:add(space)
+		--right_layout:add(alsawidget.barm)
+		--right_layout:add(space)
 		right_layout:add(mytextclock)
-		right_layout:add(space)
+		--right_layout:add(space)
 		right_layout:add(mylayoutbox[s])
 		right_layout:add(shutdowntxt)
     end
@@ -378,17 +379,17 @@ clientkeys = awful.util.table.join(
     awful.key({}, "XF86AudioPlay", function () awful.util.spawn("/home/dragonn/.bin/mpdsofttoogle toogle") end),
     awful.key({}, "XF86AudioRaiseVolume", function() 
 												awful.util.spawn("amixer sset " .. alsawidget.channel .. " " .. alsawidget.step .. "+")
-												vicious.force({ alsawidget.bar })
+												--vicious.force({ alsawidget.bar })
 												alsawidget.notify()
 										end),
     awful.key({}, "XF86AudioLowerVolume", function()
 												awful.util.spawn("amixer sset " .. alsawidget.channel .. " " .. alsawidget.step .. "-")
-												vicious.force({ alsawidget.bar })
+												--vicious.force({ alsawidget.bar })
 												alsawidget.notify()
 										end),
 	awful.key({}, "XF86AudioMute", function()
 												awful.util.spawn("amixer sset " .. alsawidget.channel .. " toggle")
-												vicious.force({ alsawidget.bar })
+												--vicious.force({ alsawidget.bar })
 												alsawidget.notify()
 										end),
     
@@ -566,4 +567,4 @@ do
   for _,i in pairs(cmds) do
     awful.util.spawn(i)
   end
-end
\ No newline at end of file
+end
```

**Comment by dragonnn** [comment]
Thank you ^^, I already fixing my config, but had problem witch the buttons, no idea how it could work before 4.0 Oo.

**Comment by xor512** [comment]
I've got something even more confusing. VERY often BOTH mouse and keyboards stop working. Pressing Mod4-P -> typing whatever there fixes keyboard. With mouse I sometimes have to launch gedit for example to make it work. I love awesome but now I plan to move to xmonad because of this. It's impossible to work like that:

```
~ >>> awesome --version        
awesome v4.3 (Too long)
 • Compiled against Lua 5.3.5 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
```

Config: https://github.com/xor512/dotfiles/blob/master/home/ss/.config/awesome/rc.lua

**Comment by actionless** [comment]
Qt apps sometimes stealing input in a way as described in a message above: https://github.com/awesomeWM/awesome/issues/2445

if you think it's a problem with your rc.lua: i didn't found it reasonable analyzing it, so just try if you can reproduce it with default rc.lua, or provide here only the minimal possible diff with which the issue became reproducible

regarding xresources: i wasn't even opening the config, as i hardly could imagine anything there to affect it

**Comment by xor512** [comment]
I will try to reproduce tomorrow with `/etc/xdg/awesome/rc.lua`

**Comment by xor512** [comment]
Funny thing. I was not able to reproduce the issue with /etc/xdg/awesome/rc.lua. But with my config it was enough to launch 2 urxvt and the issue appeared right away. I wasn't able to focus on the first launched terminal. There is nothing fancy in changes of rc.lua. I'm attaching the diff as well as awesome log

[01-awesome.log](https://github.com/awesomeWM/awesome/files/5779175/01-awesome.log)
[rc.lua.diff.txt](https://github.com/awesomeWM/awesome/files/5779178/rc.lua.diff.txt)

Can it be caused by deadbeef? I must admit that I haven't changes anything except for updating the system.

**Comment by xor512** [comment]
I've removed this hack (can't remember why I needed it):

```lua
commit cfbd3f32448c7a194a80087b3d043ef534228db7
Author: Siergiej Riaguzow <siergiej.riaguzow@gmail.com>
Date:   Thu Jan 7 04:52:30 2021 +0100

    Probably fix focues issues

diff --git a/home/ss/.config/awesome/rc.lua b/home/ss/.config/awesome/rc.lua
index cf5f3e7..2e1f3dc 100644
--- a/home/ss/.config/awesome/rc.lua
+++ b/home/ss/.config/awesome/rc.lua
@@ -69,7 +69,7 @@ editor_cmd = editor
 -- However, you can use another modifier like Mod1, but it may interact with others.
 modkey = "Mod4"
 
-add_new_clients_as_slaves = false
+--add_new_clients_as_slaves = false
 -- Table of layouts to cover with awful.layout.inc, order matters.
 awful.layout.layouts = {
     awful.layout.suit.floating,
@@ -776,7 +776,8 @@ awful.rules.rules = {
                      screen = awful.screen.preferred,
                      placement = awful.placement.no_overlap+awful.placement.no_offscreen
       },
-      callback = add_new_clients_as_slaves and awful.client.setslave or nil
+      --callback = add_new_clients_as_slaves and awful.client.setslave or nil
+      callback = awful.client.setslave or nil
     },
```

And it seems to be better now but still I was able to reproduce it with firefox. Here's the latest log attached:

[awesome.log](https://github.com/awesomeWM/awesome/files/5779496/awesome.log)

This is totally driving me mad. I'm very seriously thinking about switching to xmonad although I know absolutely nothing about Haskell. :-\ Otherwise I'm totally satisifed with awesome.

**Comment by xor512** [comment]
It happened again twice with Firefox when trying to switch tabs. Here's the log. Entries should be in the end. To fix it I had to press Mod4-p -> type abracadabra there -> press Esc. Relevant log entries if any should be in the end.

[awesome.log](https://github.com/awesomeWM/awesome/files/5779925/awesome.log)

**Comment by actionless** [comment]
> seriously thinking about switching to xmonad

if you can't debug your own lua code and gonna continue spam here, please do that to xmonad community :3

**Comment by xor512** [comment]
Yes, I can't since it is very hard to reproduce on demand. Just happened a moment ago with Thunderbird. Fix again same as always Mod4+P->abracadavra->Esc. While I can believe that Thunderbird is a QT app (while I doubt it), I don't think thunderbird is. In Firefox I often cannot switch tabs.

And it is not only about mouse, I was able to just launched two terminals (rxvt-unicde) and wasn't able to type anything in one of them no matter the focus.

I cannot even guarantee that this has anything to do with my changes, they are so minor that this is very unlikely. I think if I would try for a whole day with /etc/xdg/awesome/rc.lua I would reproduce this. Will try as soon as have time.

PS BTW I did what you asked me for, at least you could've told me that you see nothing strange there.

**Comment by psychon** [comment]
@actionless You can "unsubscribe" to issues in GitHub. There's a button on the right for that.

**Comment by actionless** [comment]
according to your logs it seems what due to not using desktop manager the awesome doesn't have correct PATH env var, and due to that clicking on notifications causing stack trace, as app handling those can't be started without having PATH

**Comment by xor512** [comment]
> according to your logs it seems what due to not using desktop manager the awesome doesn't have correct PATH env var, and due to that clicking on notifications causing stack trace, as app handling those can't be started without having PATH

1. By desktop manager you mean gdm and such? Why didn't it ever happened before (I'm using this config (without gdm or similar) for years already
2. Which PATH should I set? Something like this:

```bash
~ >>> cat ~/.xinitrc
#!/bin/bash

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

setxkbmap -option terminate:ctrl_alt_bksp # Allow exiting xorg by ctrl-alt-backspacw
xrdb -load ~/.Xresources
/usr/bin/urxvtd -q -f -o

export PATH=~/config/awesome:PATH
#exec awesome
exec awesome 1>~/awesome.log 2>&1
#sleep 1 && nitrogen restorere & # Wallpaper
```

?

3. Apps are started just find. They are just time to time not reacting to neither mouse nor buttons. "Fix" is Mod4+P->abracadabra->exit. Always works.

**Comment by actionless** [comment]
idk, just look yourself on the logs you provided -- each of them ending with the same error

and also non-awesomewm apps i see complaining about the same:

```
[aticonfig] WARNING: Error calling aticonfig to detect if running on a hybrid system with integrated GPU active: Failed to execute child process “aticonfig” (No such file or directory)
```

**Comment by xor512** [comment]
> idk, just look yourself on the logs you provided -- each of them ending with the same error
> 
> and also non-awesomewm apps i see complaining about the same:
> 
> ```
> [aticonfig] WARNING: Error calling aticonfig to detect if running on a hybrid system with integrated GPU active: Failed to execute child process “aticonfig” (No such file or directory)
> ```

Wait.. I've once tried to install awesome-git from AUR maybe this is about it:

```sh
2021-01-07 05:08:02 W: awesome: /usr/local/share/applications: Error opening directory '/usr/local/share/applications': No such file or directory
```

Also what the hell are:

```sh
console.log: (new Error("Cannot load required OTR library", "resource:///modules/OTRLib.jsm", 75))
(blueman-tray:2413): Gdk-CRITICAL **: 05:05:14.143: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
2021-01-07 05:05:18 E: awesome: Failed to load 'dialog-warning': Failed to open file “	”: No such file or directory
```

Nothing like that anywhere:
```sh
~ >>> alias pml  
pml='pacman -Ql'
~/.config/awesome >>> pml awesome | grep OTRLib.jsm
~/.config/awesome >>> pml awesome | grep dialog-warning
~/.config/awesome >>> find . -name "dialog-warning.*"
~/.config/awesome >>> find . -name OTRLib.jsm
```

Anyway thanks, I will google for that, thank you!

**Comment by actionless** [comment]
if you think what `naughty` lib stack traces are unrelated to your problem, then indeed it could be what some of the apps is stealing input; however if you can't reproduce it with default awesomewm config it's still not clear

i recommend, being able trying to reproduce it with the most normal setup (using gdm/lightdm, default awesome wm config); and next returning your custom changes one by one

for example, if you suspect dedadbeef stealing input -- try if that still happens with default awesome setup and so on

**Comment by actionless** [comment]
> dialog-warning

is usually provided by default icon theme; some of your apps asking `naughty` to show notification with such specific icon, and it's missing

**Comment by xor512** [comment]
I'm starting to think that this has something to do with H/W. This comp is of abouy my age and I've just seen a letter stuck in tty2 (where there is no startx). Also I've recently bought 2 Chinese USB hubs with 8 outputs. I've connected everything back to a hub I know was working - hope it will help.

As for aticonfig I really have only Intel

```sh
[root@cocaine usr]# xrandr --listproviders
Providers: number : 1
Provider 0: id: 0x47 cap: 0xb, Source Output, Sink Output, Sink Offload crtcs: 3 outputs: 5 associated providers: 0 name:Intel
```

Also which exact PATH should I set?

PS I  will spent whole tomorrow day to reproduce the issue first with my config and old hub and if reproduycible with /etc/xdh/awesome/rc.lua.

Thanks for your help!

**Comment by actionless** [comment]
usually PATH being set by your .profile / /etc/profile...smth, it should contain at least smth like `/usr/bin` or `/bin/`

but that error mb not because of missing path, but because you still have that `ati..` systemd service, but don't have the binary itself anymore

however if you're able to reproduce similar input lags even in pure tty, it seems what those warnings in your log are just warnings, and basically don't affect your actual result

**Comment by xor512** [comment]
Strange but I cannot reproduce it anymore at least for the last day. Maybe indeed a H/W issue - I've changed a hub to one I know is working. I just prey to ancient Satan worhipers that it won't happen again (now you can see why it is a real pain in the ass to try to reproduce it.

But I've got another annoying issue. I have a tiling layout for music. There is deadbeed to the left and pavucontrol to the right. Here's how I achieve that:

```lua
    { rule = { class = "Deadbeef" },
      properties = { screen = 1, tag = "tile4" } },
    { rule = { class = "Audacious" },
      properties = { screen = 1, tag = "tile4" } },
    { rule = { class = "Pavucontrol" },
      properties = { screen = 1, tag = "tile4" },
      callback = function(c) awful.client.setslave(c) end },

...

awful.spawn("deadbeef")
awful.spawn("pavucontrol")
```
This way I always have pavucontrol to the right of deadbef.

It works but sometimes I'm exiting i3lock the order gets messed up.

Do you have any clue? Maybe add something like awful.client.setmaster to deadbeef? BTW this `function(c) ... end` is necessary or can I just pass the callback as `callback = awful.function.setslave`?

Thanks!

**Comment by actionless** [comment]
i think for your scenario using `sn_rules` and `callback` properties of spawn call https://awesomewm.org/doc/api/libraries/awful.spawn.html#spawn would be more relevant over general client rules

**Comment by xor512** [comment]
I've tried that:
```lua
awful.spawn("deadbeef", { callback = awful.client.master })
awful.spawn("pavucontrol", { callback = awful.client.setslave })
```
but still deadbeef keeps moving to the right of pavuconrol. Also if I right click on the taskbar to see the list of apps - they are random, depending on which tag I right click. For example on tiling tag I have deadbeef on the right and pavucontrol on the left. Then I for example use i3lock. When exiting from i3lock deadbeef goes to the right. Now if I move to another tag and launch something, then move to the tiling tag - deadbeef goes back the right.

I totally don't understand why this order is so random. Something has screwed. :(

**Comment by actionless** [comment]
no, i meant to use callback to start pavucontrol after deadbeef, instead of using setslave/setmaster functions

**Comment by actionless** [comment]
also you're using spawn args wrong, take a look on the docs again for the func signature

**Comment by xor512** [comment]
I've tried that:

```lua
awful.spawn("deadbeef", true, { callback = awful.spawn("pavucontrol")})
```
and the issue is still the same. Manipulations like this often lead to deadbeef going to the right.:

1. Switch to tile tag (4th) - deadbeef is correctly on the right
2. Lock screen with i3lock
3. Unlock
2. Switch to float tag (1th)
3. Lauch gedit
4. Switch to tile tag (4th)
5. deadbeef is on the right

Also the order of clients shown by Mod4-Esc depends on which tag is currently switched on. For exampe if I have gedit on float tag 1 and deadbeef and pavucotrol on tile tag 4 and I press Mod4-Esc on float tag 1the order is "gedit, deadbeef, pavucontrol", if I switch to float tag 2 to the order if "pavucontrol, gedit, deadbeef".

**Comment by actionless** [comment]
sorry, but your example still doesn't make sense, please use `grep` and see how it's really used across src/tests/examples if you can't understand the apidoc

and also, i want to remind once again, when you trying to reproduce some problem -- first do it on clean rc.lua. mb some other `awful.rules` are additionally messing up the order of those clients

**Comment by xor512** [comment]
Thanks for pointing where to look for examples!

**Comment by xor512** [comment]
OK it seems to finally work with all the possible combinations I could come up with:

```lua
    { rule = { class = "Deadbeef" },
      properties = { screen = 1, tag = "tile4", floating = false },
      callback = awful.client.setmaster },
    { rule = { class = "Pavucontrol", floating = false },
      properties = { screen = 1, tag = "tile4" },
      callback = awful.client.setslave }
<skip>
spawn_once("deadbeef", nil, { tag = "tile4"}, function(c)
    spawn_once("pavucontrol", nil, { tag = "tile4" }, function(c)
        awful.client.setslave(c)
    end) 
end)
```

where spawn_once is just a wrapper around awful.spawn with checking whether the process is still running.

But the order of clients when I press Mod4-Esc seems to be totally random and it depends on which tag I press it. Very confusing.

**Comment by xor512** [comment]
I seem to find a way to easily reproduce it.

1. Switch to tiling tag.
2. Open deadbeef
3. Open pavucontrol
4. Open something that has a rule that it is always floating like gedit or firefox
5. pavucontrol is now behind the deadbeef

Will try with default config. Very confusing...

**Comment by xor512** [comment]
OK, I got it. I wanted all clients to appear at the end of the list and did it in two places:

```lua
-- {{{ Rules
-- Rules to apply to new clients (through the "manage" signal).
awful.rules.rules = {
    -- All clients will match this rule.
    { rule = { },
      properties = { border_width = beautiful.border_width,
                     border_color = beautiful.border_normal,
                     focus = awful.client.focus.filter,
                     raise = true,
                     keys = clientkeys,
                     --- Firefox will start maximized next time if it was maximized
                     --- peviously and this will imply floating mode
                     maximized_vertical   = false,
                     maximized_horizontal = false,
                     --- remove gaps between windows
                     size_hints_honor = false,
                     buttons = clientbuttons,
                     screen = awful.screen.preferred,
                     placement = awful.placement.no_overlap+awful.placement.no_offscreen
      }
      callback = awful.client.setslave or nil -- HERE
    },
```
and

```lua
client.connect_signal("manage", function (c)
    -- Set the windows at the slave,
    -- i.e. put it at the end of others instead of setting it master.
    if not awesome.startup then awful.client.setslave(c) end -- and HERE
```
looks like these statements conflict and only the second one is necessary.

**Comment by xor512** [comment]
> ```diff
> +	c:keys(clientkeys)
> +	c:buttons(clientbuttons)
> ```

Why isn't it yet in /etc/xdg/awesome/rc.lua if it is needed and it is known that it is needed from 2016? Should I apply it to my config?

**Comment by xor512** [comment]
> The following change fixes the reported issue. No idea how this worked previously for you (Edit: Previously == with 3.5). The problem was that you never set the keys and buttons on a client (this bug report is only about the buttons, but I fixed the keys anyway):
> 
> ```diff
> --- rc.lua.loads	2016-12-31 09:47:51.297940593 +0100
> +++ rc.lua	2016-12-31 09:48:16.101454404 +0100
> @@ -468,6 +468,8 @@ root.keys(globalkeys)
>  -- {{{ Signals
>  -- Signal function to execute when a new client appears.
>  client.connect_signal("manage", function (c, startup)
> +	c:keys(clientkeys)
> +	c:buttons(clientbuttons)
>      if not startup then
>          -- Set the windows at the slave,
>          -- i.e. put it at the end of others instead of setting it master.
> ```

Why isn't it yet in /etc/xdg/awesome/rc.lua if it is needed and it is known that it is needed from 2016? Should I apply it to my config?

**Comment by actionless** [comment]
it's too much to read (so i didn't), but if you still have some problems, like inconsistent order of the clients  -- it still most probably because you do these experiments not on the default rc.lua.

when you will show the diff to default rc.lua with only minimal change which is not working (but which is still a valid lua code)  -- next we talking :)

**Comment by xor512** [comment]
You don't have to read it, I've  fixed my problems except of one which is also reproducible on default rc.lua:

Order of clients shown by Mod4-Esc depends on which tag is currently focused, which client is currently focused and almost random. At least I cannot understand anything out of it.

But as I don't use Mod4-Esc I can live with it.

**Comment by xor512** [comment]
Ah! Now I understand it! It shows clients starting from the first one focused or the first one to the right which would be focused if we are on empty tag for example and then sort of goes as a circular list. OK, all problems hopefully solved, apart from not knowing whether this:

```lua
+	c:keys(clientkeys)
+	c:buttons(clientbuttons)
```

is needed or not and whether mouse/keyboard freezes are fixed or where H/W issue...

**Comment by actionless** [comment]
> is needed or not and whether mouse/keyboard freezes are fixed or where H/W issue...

as far as i can see it's done slightly differently in the newest rc.lua: https://github.com/awesomeWM/awesome/blob/master/awesomerc.lua#L208

i'm not sure from which conversation of 2016 you copied that patch -- but a lot of things changed during the 4 years

**Comment by xor512** [comment]
Hmm it's very different from what I've got in /etc/xdg/awesome/rc.lua and I'm in Manjaro.

```sh
~ >>> awesome --version
awesome v4.3 (Too long)
 • Compiled against Lua 5.3.5 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
```

there's nothing about mousebindings in my /etc/xdg/awesome/rc.lua... Would you recommend to take git version from AUR? Or maybe I've got something screwed up again?

**Comment by actionless** [comment]
i myself using git version and it works
