### ISSUE TITLE
Awesome 4.0 - magnifier layout does not handle focus properly

### ISSUE THREAD

**Issue by tlarrieu** [awesomeWM/awesome#1338]
Output of `awesome --version`:

awesome v4.0-18-gb4387d38 (Harder, Better, Faster, Stronger)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • RandR 1.5 support: ✔
 • LGI version: 0.9.1

**How to reproduce the issue:**

- select `awful.layout.suit.magnifier` as the tag layout
- open 2 clients
- try to focus the unfocused one
 
**Actual result:**

The next client will get focused and brought to front, but not “magnified” (windows are not reorganized).
Opening a new client *does* reorganize the layout though, as expected.

**Expected result:**

The windows should be reorganized.

**Comment by Elv13** [comment]
This is an error introduced when the new screen support was merged. Can you test this?

```patch
diff --git a/lib/awful/layout/suit/magnifier.lua b/lib/awful/layout/suit/magnifier.lua
index f30d7eeb7..fb4df4c86 100644
--- a/lib/awful/layout/suit/magnifier.lua
+++ b/lib/awful/layout/suit/magnifier.lua
@@ -54,6 +54,10 @@ function magnifier.mouse_resize_handler(c, corner, x, y)
                           end, corner .. "_corner")
 end
 
+local function get_screen(s)
+    return s and capi.screen[s]
+end
+
 function magnifier.arrange(p)
     -- Fullscreen?
     local area = p.workarea
@@ -64,7 +68,7 @@ function magnifier.arrange(p)
     local fidx
 
     -- Check that the focused window is on the right screen
-    if focus and focus.screen ~= p.screen then focus = nil end
+    if focus and focus.screen ~= get_screen(p.screen) then focus = nil end
 
     -- If no window is focused or focused window is not tiled, take the first tiled one.
     if (not focus or focus.floating) and #cls > 0 then
```

**Comment by tlarrieu** [comment]
I've tested it through Xephyr and that does not seem to fix.

**Comment by Elv13** [comment]
Strange, it does here.

Can you add

     client.connect_signal("button::press", function(c)
         if awful.layout.get(c.screen) == awful.layout.suit.magnifier
             and awful.client.focus.filter(c) then
             gears.timer.delayed_call(function()
                 awful.layout.arrange(c.screen)
             end)
         end   
     end)

To your `rc.lua`? Also, is it a clean `rc.lua` or a ported one? In Xephyr with a client config and the patch posted above, it works fine for me.

**Comment by tlarrieu** [comment]
OK, turns out I'm stupid: I forgot to `make install` after `make -j4`.
The patch works just fine :D (and without adding anything to my `rc.lua`)
