### ISSUE TITLE
An alleged race condition on client focus

### ISSUE THREAD

**Issue by aroig** [awesomeWM/awesome#134]
Hi,

On current master there seems to be a race condition, that sometimes makes focus go wrong on new clients. This was made manifest after #118, but I guess it was there hidden before that.

I have configured awesome to set focus on new clients via a rule `focus = true`. For me, it doesn't work for the first client in a tag, but does work when the tag already has a client. After introducing some printf's in the right places, I observed this sequence of calls after creating a new client:

**EDIT**: It turns out the client always gets focus! What happens in case A below is that the focus signal fails to set the border color for the client. I was just looking at that to tell when a client has focus or not... sorry!

A. Case in which focus does not work (no clients in a tag)

    1. client_focus
    2.   client_focus_update (focused_new = 1)
    3. client_focus
    4.   client_focus_update (focused_new = 0)
    5. client_focus_refresh
    6. client_focus_update (focused_new = 0)

B. Case in which focus does work (with existing clients in a tag)

    1. client_focus
    2.   client_focus_update (focused_new = 1)
    3. client_focus_refresh
    4. client_focus
    5.   client_focus_update (focused_new = 0)

I think what makes the focus work or not is the ordering of those calls, and not the fact that the tag is empty or not. That the second implies the first may be just a matter of timings... However I'm not 100% sure of that.

From the data above, there are two things that seem wrong to me plus a mystery:

1. Why on earth client_focus is called twice for a client?
2. Assuming the hypothesis that the ordering is what breaks the focus, it is wrong that the relative ordering between the second client_focus and client_focus_refresh has an effect on the focus behaviour.
3. Who calls client_focus_update in A.6 ??

I'm sorry for not being able to be more helpful. I don't fully understand the way signals work in awesome (it is a bit of a mess), and don't have the time to look deeper right now... However I can do any test you want!

**Comment by Elv13** [comment]
This may or may not be in the same bag as https://github.com/awesomeWM/awesome/issues/130 . In any case, someone need to investigate the client initialization code to be sure it is reproducible from run to run and behave in a sensible way.

To mitigate your issue, there is a request:: signal API. Take a look at "request::activate" to implement your own handler. I also had some issues with "transient for" popups initialization order being random, but I have "fixed" this by handling that event myself (in Tyrannical).

**Comment by aroig** [comment]
@Elv13 Thanks. I forgot to mention that the issue I reported has nothing to do with custom handlers. I can reproduce it with a default rc.lua.

**Comment by aroig** [comment]
Ok, A correction (sorry). The client DOES get focus. I was only looking at the border color to tell if it has focus or not.... silly me. The bug seems to be that after #118, the border color is not properly set from within a focus signal. 

There are still things I don't understand in the sequence of calls I reported before, though.

**Comment by actionless** [comment]
it looks similar to problem i reported in comments -- https://github.com/awesomeWM/awesome/commit/90fde1393f697ca0d7201e385293a5ac4778d136#commitcomment-9423747

it was fixed in one of the later commits but got broken again almost at the same time as i faced that #130 issue

**Comment by aroig** [comment]
Yes! @psychon comment in there (https://github.com/awesomeWM/awesome/commit/90fde1393f697ca0d7201e385293a5ac4778d136#commitcomment-9424536) is very helpful. In particular it explains why I was seeing two calls to client_focus. Also explains the problem I have! 

After a quick test, it turns out the same race between focus handler and rule application happens here!

This still needs a fix. It is odd that rules sometimes win over the focus handler, and sometimes do not.

**Comment by blueyed** [comment]
#116 might help here.

**Comment by aroig** [comment]
2328b57ff fixed this for me. Thanks!
