### ISSUE TITLE
size_hints_honor issue

### ISSUE THREAD

**Issue by vitek** [awesomeWM/awesome#1340]
Output of `awesome --version`:

awesome v4.0-18-gb4387d3 (Harder, Better, Faster, Stronger)
 • Compiled against Lua 5.2.4 (running with Lua 5.2)
 • D-Bus support: ✔
 • execinfo support: ✔
 • RandR 1.5 support: ✘
 • LGI version: 0.9.0

**How to reproduce the issue:**

With global `size_hints_honor = false` and `awful.layout.suit.tile` layout open two `gnome-terminals` then try to resize them with `Mod-L`.

**Actual result:**

Window content is corrupt. Left terminal's right edge is painted with parts of other teminal content.

**Expected result:**

Both terminals painted as expected.

**Comment by psychon** [comment]
Got a screenshot if this issue? Can you try if it also happens when starting awesome with `--no-argb`?

**Comment by vitek** [comment]
The same behaviour with `--no-argb` here is how it looks like:

![2016-12-31 15-40-18](https://cloud.githubusercontent.com/assets/489439/21577687/26853254-cf75-11e6-80d3-d1773cc021d0.png)

**Comment by vitek** [comment]
Same problem on both ubuntu 14.04 and 16.04 while with awesome 3.4 and 3.5 it's ok.

I'm also experience problems with emacs in tile layout (size_hints_honor=true) sometimes it starts like this:

![emacs1](https://cloud.githubusercontent.com/assets/489439/21748189/4b1776ac-d58f-11e6-86c2-288f40fdcc8c.png)

If I open terminal emacs window is ok now:

![emacs2](https://cloud.githubusercontent.com/assets/489439/21748194/66f829ca-d58f-11e6-8ef3-dc92035e1413.png)

**Comment by psychon** [comment]
So the failed ConfigureWindow request seems to be the problem (possibly?), but so far I have no idea why it would fail...

**Comment by vitek** [comment]
Here is xtrace output for emacs issue:

```
000:<:5ef9: 28: Request(12): ConfigureWindow window=0x0280005e values={x=0 y=17 width=0 height=0}
000:<:5efa: 28: Request(12): ConfigureWindow window=0x01e000ab values={x=0 y=0 width=0 height=0}
000:<:5efb: 44: Request(25): SendEvent propagate=false(0x00) destination=0x01e000ab event-mask=StructureNo
tify ConfigureNotify(22) event=0x01e000ab window=0x01e000ab above-sibling=None(0x00000000) x=1 y=18 width=
0 height=0 border-width=1 override-redirect=false(0x00)
047:<:04c6:  4: Request(43): GetInputFocus 
000:<:5efc:  4: Request(127): NoOperation 
000:>:5efc: Event NoExposure(14) drawable=0x02800015 minor-opcode=0x0000 major-opcode=0x3e
000:>:5ef9:Error 2=Value: major=12, minor=0, bad=0
000:<:5efd:  4: Request(37): UngrabServer 
000:<:5efe: 16: Request(2): ChangeWindowAttributes window=0x0280005e value-list={border-pixel=0xff535d6c}
000:<:5eff: 16: Request(12): ConfigureWindow window=0x0280005e values={border-width=1}
000:<:5f00:  8: Request(8): MapWindow window=0x0280005e
000:<:5f01: 44: Request(25): SendEvent propagate=false(0x00) destination=0x01e000ab event-mask=0 ClientMessage(33) format=0x20 window=0x01e000ab type=0x127("WM_PROTOCOLS") data=0x28,0x01,0x00,0x00,0x62,0xb3,0x21,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00;
000:<:5f02: 12: Request(42): SetInputFocus revert-to=Parent(0x02) focus=0x01e000ab time=0x0021b362
000:<:5f03:  4: Request(36): GrabServer 
000:<:5f04:  4: Request(127): NoOperation 
000:<:5f05:  4: Request(37): UngrabServer 
000:<:5f06: 20: Request(12): ConfigureWindow window=0x02800018 values={sibling=0x02800015 stack-mode=Above(0x00)}
000:<:5f07: 20: Request(12): ConfigureWindow window=0x0280001b values={sibling=0x02800018 stack-mode=Above(0x00)}
000:<:5f08: 20: Request(12): ConfigureWindow window=0x0280001c values={sibling=0x0280001b stack-mode=Above(0x00)}
000:<:5f09: 20: Request(12): ConfigureWindow window=0x0280001d values={sibling=0x0280001c stack-mode=Above(0x00)}
000:<:5f0a: 20: Request(12): ConfigureWindow window=0x0280001f values={sibling=0x0280001d stack-mode=Above(0x00)}
000:<:5f0b: 20: Request(12): ConfigureWindow window=0x0280005e values={sibling=0x0280001f stack-mode=Above(0x00)}
000:>:5efa:Error 2=Value: major=12, minor=0, bad=0
```

**Comment by psychon** [comment]
Thanks!

> 000:<:5ef9: 28: Request(12): ConfigureWindow window=0x0280005e values={x=0 y=17 width=0 height=0}
> 000:<:5efa: 28: Request(12): ConfigureWindow window=0x01e000ab values={x=0 y=0 width=0 height=0}

Huh? Something is assigning size 0x0 to a window (I guess the C side should catch that...).
That does not explain what is going on in the screenshots, however. Perhaps Gtk gets highly confused if it is resized to such a size?

**Comment by psychon** [comment]
Can one of you try building awesome with the following patch applied? The effect should be that attempts from Lua code to use "wrong sizes" are silently ignored (isn't it great how return values are always ignored?).
```diff
diff --git a/objects/client.c b/objects/client.c
index ac3c9cc2b..4bc1d5760 100644
--- a/objects/client.c
+++ b/objects/client.c
@@ -1176,6 +1176,24 @@ client_geometry_refresh(void)
         area_t real_geometry = c->geometry;
         if (!c->fullscreen)
         {
+            if ((real_geometry.width < c->titlebar[CLIENT_TITLEBAR_LEFT].size
+                    + c->titlebar[CLIENT_TITLEBAR_RIGHT].size) ||
+                    (real_geometry.height < c->titlebar[CLIENT_TITLEBAR_TOP].size
+                    + c->titlebar[CLIENT_TITLEBAR_BOTTOM].size))
+                warn("Resizing a window to a negative size!? Have width %d-%d-%d=%d"
+                        " and height %d-%d-%d=%d", real_geometry.width,
+                        c->titlebar[CLIENT_TITLEBAR_LEFT].size,
+                        c->titlebar[CLIENT_TITLEBAR_RIGHT].size,
+                        real_geometry.width -
+                            c->titlebar[CLIENT_TITLEBAR_LEFT].size -
+                            c->titlebar[CLIENT_TITLEBAR_RIGHT].size,
+                        real_geometry.height,
+                        c->titlebar[CLIENT_TITLEBAR_TOP].size,
+                        c->titlebar[CLIENT_TITLEBAR_BOTTOM].size,
+                        real_geometry.height -
+                            c->titlebar[CLIENT_TITLEBAR_TOP].size -
+                            c->titlebar[CLIENT_TITLEBAR_BOTTOM].size);
+
             real_geometry.x = c->titlebar[CLIENT_TITLEBAR_LEFT].size;
             real_geometry.y = c->titlebar[CLIENT_TITLEBAR_TOP].size;
             real_geometry.width -= c->titlebar[CLIENT_TITLEBAR_LEFT].size;
@@ -1678,6 +1696,17 @@ client_resize(client_t *c, area_t geometry, bool honor_hints)
     if(geometry.y + geometry.height < 0)
         geometry.y = 0;
 
+    if (honor_hints) {
+        /* We could get integer underflows in client_remove_titlebar_geometry()
+         * without these checks here.
+         */
+        if(geometry.width < c->titlebar[CLIENT_TITLEBAR_LEFT].size + c->titlebar[CLIENT_TITLEBAR_RIGHT].size)
+            return false;
+        if(geometry.height < c->titlebar[CLIENT_TITLEBAR_TOP].size + c->titlebar[CLIENT_TITLEBAR_BOTTOM].size)
+            return false;
+        geometry = client_apply_size_hints(c, geometry);
+    }
+
     if(geometry.width < c->titlebar[CLIENT_TITLEBAR_LEFT].size + c->titlebar[CLIENT_TITLEBAR_RIGHT].size)
         return false;
     if(geometry.height < c->titlebar[CLIENT_TITLEBAR_TOP].size + c->titlebar[CLIENT_TITLEBAR_BOTTOM].size)
@@ -1686,9 +1715,6 @@ client_resize(client_t *c, area_t geometry, bool honor_hints)
     if(geometry.width == 0 || geometry.height == 0)
         return false;
 
-    if (honor_hints)
-        geometry = client_apply_size_hints(c, geometry);
-
     if(!AREA_EQUAL(c->geometry, geometry))
     {
         client_resize_do(c, geometry);
```

**Comment by vitek** [comment]
With your patch emacs startup issue is gone. size_hints_honor is still there.

There is another problem with emacs. Menu bar is disabled in my config but emacs itself shows it on startup and then hides. Sometimes emacs starts with menubar drawn but actually it's not there. Perhaps emacs window geometry isn't updated after menubar removed. Here is how it looks like after switch to another tag and back:

![emacs-menubar](https://cloud.githubusercontent.com/assets/489439/21749716/53763114-d5b5-11e6-8dd0-c31d416c27e4.png)

**Comment by psychon** [comment]
> There is another problem with emacs

Let's have one issue per issue. ;-)

> Menu bar is disabled in my config but emacs itself shows it on startup and then hides. 

What do you mean? Something with `titlebar_enable`? Or `awful.titlebar.hide`?

**Comment by vitek** [comment]
> Let's have one issue per issue. ;-)

Sure. But I'm not sure is it the same issue or not.

> What do you mean? Something with titlebar_enable? Or awful.titlebar.hide?

No it's how emacs works. It always starts with menubar shown then you can hide it with config. Here is how it looks like before I switch to another workspace:

![emacs-menubar2](https://cloud.githubusercontent.com/assets/489439/21749822/3066b63c-d5b8-11e6-87fc-139b7a9d8299.png)

**Comment by psychon** [comment]
> Sure. But I'm not sure is it the same issue or not.

Oh, I just found something from the initial post: https://github.com/awesomeWM/awesome/issues/1340#issue-198231379

> With global size_hints_honor = false

So the issue that we managed to figure out is actually some other issue... :-(

**Comment by mindeunix** [comment]
I can not reproduce this issue on my system, whether enabled size_hints_honor or not, tile layout or floating.  I don't have gnome-terminals, but with rxvt everything works well. I had same issues some time ago, but after updates these problems have disappeared.

Gentoo Linux with GNU Emacs 25.1.1 and Awesome WM master branch.

**Comment by vitek** [comment]
Gnome-terminal makes sense here xterm for instance works well for me. I'm afraid it's problem with gtk or vte based terminals, similar issues occur with mate-terminal and xfce4-terminal.

On my system running two emacs windows on the same tiled screen with `size_hints_honor=true`  doesn't work as expected. See white area on the right window:

![emacs2](https://cloud.githubusercontent.com/assets/489439/21752716/b1ae70b4-d5ee-11e6-9671-d8ad0c367aef.png)

**Comment by mindeunix** [comment]
Ok, found a way how to reproduce, but in a different way. If you start Emacs without scrollbars, menubar or toolbar then everything works as expected, but ```M-x menu-bar-mode``` command creates invisible menubar, only resizing Emacs window makes it visible. Same problem with ```M-x tool-bar-mode```.

Tested:
GNU Emacs 25.1.50.1 (GTK+ Version 2.24.31)
GNU Emacs 25.1.1 (GTK+ Version 2.24.31)
GNU Emacs 24.5.1 (GTK+ Version 3.22.4)

Works with floating layout. I am not an expert in other windows managers, but tried to reproduce this issue with dwm and emacs worked fine there.

**Comment by mindeunix** [comment]
Xtrace output (Emacs periodically runs ```menu-bar-mode```)


```
008:<:45a2: 16: Request(61): ClearArea exposures=false(0x00) window=0x04600138 x=0 y=266 width=7 height=5
008:<:45a3: 20: Request(59): SetClipRectangles ordering=UnSorted(0x00) gc=0x046003c6 clip-x-origin=0 clip-y-origin=0 rectangles={x=15 y=42 w=1415 h=14};
008:<:45a4: 20: Request(70): PolyFillRectangle drawable=0x04600138 gc=0x046003c6 rectangles={x=183 y=42 w=1 h=14};
008:<:45a5: 16: Request(56): ChangeGC gc=0x046003c6 values={clip-mask=None(0x00000000)}
008:<:45a6: 20: Request(59): SetClipRectangles ordering=UnSorted(0x00) gc=0x0460013f clip-x-origin=0 clip-y-origin=0 rectangles={x=0 y=266 w=1438 h=5};
008:<:45a7: 16: Request(53): CreatePixmap depth=0x18 pid=0x046006d2 drawable=0x04600138 width=8 height=70
008:<:45a8: 24: Request(55): CreateGC cid=0x046006d3 drawable=0x046006d2 values={foreground=0x00175a7d background=0x001a1a1a}
008:<:45a9:304: Request(72): PutImage format=Bitmap(0x00) drawable=0x046006d2 gc=0x046006d3 width=8 height=70 dst-x=0 dst-y=0 left-pad=0x00 depth=0x01
008:<:45aa:  8: Request(60): FreeGC gc=0x046006d3
008:<:45ab: 28: Request(62): CopyArea src-drawable=0x046006d2 dst-drawable=0x04600138 gc=0x0460013f src-x=0 src-y=0 dst-x=7 dst-y=266 width=8 height=70
008:<:45ac:  8: Request(54): FreePixmap drawable=0x046006d2
008:<:45ad: 16: Request(56): ChangeGC gc=0x0460013f values={clip-mask=None(0x00000000)}
008:<:45ae: 20: Request(59): SetClipRectangles ordering=UnSorted(0x00) gc=0x0460013f clip-x-origin=0 clip-y-origin=0 rectangles={x=0 y=266 w=1438 h=5};
008:<:45af: 16: Request(56): ChangeGC gc=0x046003a9 values={foreground=0x001a1a1a}
008:<:45b0: 20: Request(70): PolyFillRectangle drawable=0x04600138 gc=0x046003a9 rectangles={x=1430 y=266 w=8 h=5};
008:<:45b1: 16: Request(56): ChangeGC gc=0x0460013f values={clip-mask=None(0x00000000)}
008:>:45b1: Event NoExposure(14) drawable=0x04600138 minor-opcode=0x0000 major-opcode=0x3e




008:<:45b2: 16: Request(61): ClearArea exposures=false(0x00) window=0x04600138 x=0 y=266 width=7 height=5
008:<:45b3: 20: Request(59): SetClipRectangles ordering=UnSorted(0x00) gc=0x046003c6 clip-x-origin=0 clip-y-origin=0 rectangles={x=15 y=42 w=1415 h=14};
008:<:45b4: 20: Request(70): PolyFillRectangle drawable=0x04600138 gc=0x046003c6 rectangles={x=183 y=42 w=1 h=14};
008:<:45b5: 16: Request(56): ChangeGC gc=0x046003c6 values={clip-mask=None(0x00000000)}
008:<:45b6: 20: Request(59): SetClipRectangles ordering=UnSorted(0x00) gc=0x0460013f clip-x-origin=0 clip-y-origin=0 rectangles={x=0 y=266 w=1438 h=5};
008:<:45b7: 16: Request(53): CreatePixmap depth=0x18 pid=0x046006d4 drawable=0x04600138 width=8 height=70
008:<:45b8: 24: Request(55): CreateGC cid=0x046006d5 drawable=0x046006d4 values={foreground=0x00175a7d background=0x001a1a1a}
008:<:45b9:304: Request(72): PutImage format=Bitmap(0x00) drawable=0x046006d4 gc=0x046006d5 width=8 height=70 dst-x=0 dst-y=0 left-pad=0x00 depth=0x01
008:<:45ba:  8: Request(60): FreeGC gc=0x046006d5
008:<:45bb: 28: Request(62): CopyArea src-drawable=0x046006d4 dst-drawable=0x04600138 gc=0x0460013f src-x=0 src-y=0 dst-x=7 dst-y=266 width=8 height=70
008:<:45bc:  8: Request(54): FreePixmap drawable=0x046006d4
008:<:45bd: 16: Request(56): ChangeGC gc=0x0460013f values={clip-mask=None(0x00000000)}
008:<:45be: 20: Request(59): SetClipRectangles ordering=UnSorted(0x00) gc=0x0460013f clip-x-origin=0 clip-y-origin=0 rectangles={x=0 y=266 w=1438 h=5};
008:<:45bf: 16: Request(56): ChangeGC gc=0x046003a9 values={foreground=0x001a1a1a}
008:<:45c0: 20: Request(70): PolyFillRectangle drawable=0x04600138 gc=0x046003a9 rectangles={x=1430 y=266 w=8 h=5};
008:<:45c1: 16: Request(56): ChangeGC gc=0x0460013f values={clip-mask=None(0x00000000)}
008:>:45c1: Event NoExposure(14) drawable=0x04600138 minor-opcode=0x0000 major-opcode=0x3e
```

**Comment by psychon** [comment]
> trace output (Emacs periodically runs menu-bar-mode) https://p.defau.lt/?_hTN4DZCQUL96c0oVxqhog

I'm afraid nothing happens here. All that we can see is drawing-related things. I did not look to closely at what is actually being drawn. So, whatever this is, it seems to be emacs-internal.

**Comment by mindeunix** [comment]
@psychon xtrace writes so much output that to find something useful is really complicated, I tried to create a new function which toggles menubar every 5 seconds, but it does not help much... I can share the full log if you think this can help somehow.

as workaround I'm using:
```
grep emacs ~/.Xdefaults             
emacs.menuBar:			 off
emacs.toolBar: 			 off
emacs.verticalScrollBars: 	 off
```

but each time Emacs tries to show anything from Gtk (menubar, toolbar, scrollbars) it comes to these strange problems.

**Comment by psychon** [comment]
Yup, I know that there is lots of output. Sorry for that. Perhaps the `--timestamps` helps you? Also, anything with RENDER or clip or GC etc in its name is drawing and can be ignored (perhaps `grep -v`?). Sorry that I do not have any more specific hints

> but M-x menu-bar-mode command creates invisible menubar, only resizing Emacs window makes it visible

Hm, I cannot reproduce this here (other PC; Fedora 25) with Emacs 25.1.1. No Emacs configuration file, just the awesome default config and toggling the menu bar seems to work just fine.

**Comment by psychon** [comment]
Ok, I can reproduce the problem here.

**Comment by vitek** [comment]
Hi,

Finally I've nailed it down. Ignororing client configure requests solves both emacs and gnome-terminal issues. Here it is https://github.com/vitek/awesome/commit/15c04d7a33e02f91c2bb0fc1c4fc43795f5832fa

Not sure it's correct in general but now I hope we can solve it.

**Comment by vitek** [comment]
It seems to me that client requests geometry we adjust it back to the old value somewhere in lua code so client is never notified about geometry change.

Here is another way to fix it https://github.com/vitek/awesome/commit/3ce4983eaf1a4384f1278285034b6f4ef6a6dd20

**Comment by psychon** [comment]
Sigh. Fall out from baaff93a7349a9da67b4b8f291a62820828f14bd. Thanks for tracking it down!
I think I would do something slightly different than your https://github.com/vitek/awesome/commit/3ce4983eaf1a4384f1278285034b6f4ef6a6dd20, but you are on a very good track. Thanks again!
Could you test the following patch and if it works then send a pull request with it (I do not care about authorship here and all of the hard work was done by you anyway) (for the commit message: You can mention the commit that introduced this problem):
```diff
diff --git a/event.c b/event.c
index 3bf513c..a89769e 100644
--- a/event.c
+++ b/event.c
@@ -395,9 +395,10 @@ event_handle_configurerequest(xcb_configure_request_event_t *ev)
                 geometry.y += diff_y;
         }
 
-        if(!client_resize(c, geometry, false))
-            /* ICCCM 4.1.5 / 4.2.3, if nothing was changed, send an event saying so */
-            client_send_configure(c);
+        /* ICCCM 4.1.5 / 4.2.3, if nothing was changed, send an event saying so */
+        c->got_configure_request = true;
+
+        client_resize(c, geometry, false);
     }
     else if (xembed_getbywin(&globalconf.embedded, ev->window))
     {
diff --git a/objects/client.c b/objects/client.c
index 309d021..4bd033a 100644
--- a/objects/client.c
+++ b/objects/client.c
@@ -1210,8 +1210,13 @@ client_geometry_refresh(void)
 
         /* Is there anything to do? */
         if (AREA_EQUAL(geometry, c->x11_frame_geometry)
-                && AREA_EQUAL(real_geometry, c->x11_client_geometry))
+                && AREA_EQUAL(real_geometry, c->x11_client_geometry)) {
+            if (c->got_configure_request)
+                /* ICCCM 4.1.5 / 4.2.3, if nothing was changed, send an event saying so */
+                client_send_configure(c);
+            c->got_configure_request = false;
             continue;
+        }
 
         if (!ignored_enterleave) {
             client_ignore_enterleave_events();
@@ -1230,6 +1235,7 @@ client_geometry_refresh(void)
 
         /* ICCCM 4.2.3 says something else, but Java always needs this... */
         client_send_configure(c);
+        c->got_configure_request = false;
     }
     if (ignored_enterleave)
         client_restore_enterleave_events();
diff --git a/objects/client.h b/objects/client.h
index e2dcfc8..760fb13 100644
--- a/objects/client.h
+++ b/objects/client.h
@@ -64,6 +64,8 @@ struct client_t
     /** Old window geometry currently configured in X11 */
     area_t x11_client_geometry;
     area_t x11_frame_geometry;
+    /** Got a configure request and have to call client_send_configure() if its ignored? */
+    bool got_configure_request;
     /** Startup ID */
     char *startup_id;
     /** True if the client is sticky */
```
As a reply to your

> somewhere in lua code

Well: The layout (tile, or something like that) gets the request and re-arranges thing to the way the way before.
