### ISSUE TITLE
awesome 4.0 debian installs default rc.lua to /usr/local/etc/xdg/awesome/ not /etc/xdg/awesome/

### ISSUE THREAD

**Issue by wright8191** [awesomeWM/awesome#1346]
Output of `awesome --version`:

```
↪ awesome --version
awesome v4.0 (Harder, Better, Faster, Stronger)
 • Compiled against Lua 5.1.5 (running with Lua 5.1)
 • D-Bus support: ✔
 • execinfo support: ✔
 • RandR 1.5 support: ✘
 • LGI version: 0.9.0
```

**How to reproduce the issue:**

build and install awesome v4 debian package (was done on ubuntu 16.04.1)

```
make
make package
sudo dpkg -i build/awesome-4.0.0.0-Linux.deb
```

**Actual result:**

default `rc.lua` is installed to `/usr/local/etc/xdg/awesome/rc.lua` not `/etc/xdg/awesome/rc.lua`

```
↪ dpkg -c build/awesome-4.0.0.0-Linux.deb | grep rc.lua
-rw-r--r-- root/root     22027 2016-12-30 21:44 ./usr/local/etc/xdg/awesome/rc.lua
```

so there is no default `rc.lua` to fallback on

**Expected result:**

`rc.lua` is installed to `/etc/xdg/awesome/rc.lua`

**Comment by legostax** [comment]
I would like to add the following:

**Expected result:**

The folders `icons`, `lib`, and `themes` should be installed to `/usr/share/awesome` (at least, according to the docs)

**Actual result:**

The folders `icons`, `lib`, and `themes` are installed to `/usr/local/share/awesome`

This was found on the same version of awesome, (only difference is no D-Bus support) and on the same version of Ubuntu (16.04.1).  I too compiled from source and created a `.deb`.

**Comment by Elv13** [comment]
Note that the workaround is calling CMake yourself instead of using the Makefile wrapper.

```sh
cd path/to/awesome
mkdir build
cmake .. -DCMAKE_INSTALL_PREFIX=/usr
make -j4
make package
```

This is, of course, not a solution to the deeper issue (our "make package" target should check and fix the prefix), but it should generate a correct .deb.

**Comment by wright8191** [comment]
This workaround does not work for me. It installs rc.lua to `/usr/etc/xdg/awesome/rc.lua` which awesome does not fall back to.

```
↪ dpkg -c awesome-4.0.0.0-Linux.deb| grep rc.lua
-rw-r--r-- root/root     22027 2017-01-03 22:05 ./usr/etc/xdg/awesome/rc.lua
```

(also you have to `mkdir build && cd build` before building)

**Comment by psychon** [comment]
That would be fixed by `-DSYSCONFDIR=/etc` ([via](https://anonscm.debian.org/git/collab-maint/awesome.git/tree/debian/rules#n6)).

I don't think having themes in `/usr/local` is a problem. The built awesome should still find it there since that path gets hardcoded somewhere. I rather see this issue as "the path to where the default config file was installed to does not get hardcoded into the binary".

**Comment by elw00d** [comment]
I've fixed this manually by rebuilding the deb package: https://github.com/elw00d/awesome-deb-docker
You can try this to get the working `deb`, while the bug isn't finally fixed.

**Comment by blueyed** [comment]
@elw00d 
Thanks.
This Dockerfile could also be used as a base image for awesome's CI tests on Travis potentially.
