### ISSUE TITLE
menubar error in awesome 4.0

### ISSUE THREAD

**Issue by flosse** [awesomeWM/awesome#1348]
Output of `awesome --version`:
```
awesome v4.0 (Harder, Better, Faster, Stronger)
 • Compiled against Lua 5.2.3 (running with Lua 5.2)
 • D-Bus support: ✔
 • execinfo support: ✔
 • RandR 1.5 support: ✔
 • LGI version: 0.7.2
```

**How to reproduce the issue:**
Start awesome and press `super` + `p`

**Actual result:**

`share/awesome/lib/menubar/init.lua:199: attempt to index field 'prompt' (a nil value)`

**Expected result:**
I'd like to see the menu ;-)

I'm running NixOS and this problem occoured with an [update from v3.5 to v4.0](https://github.com/NixOS/nixpkgs/pull/21430).

**Comment by psychon** [comment]
Somewhere there is a nother bug report about menubar initialisation, but I cannot find it right now.
Could you apply the following diff and grab its output? So far I have no idea.
```diff
diff --git a/lib/menubar/init.lua b/lib/menubar/init.lua
index 10ad65c2d..46a9675d9 100644
--- a/lib/menubar/init.lua
+++ b/lib/menubar/init.lua
@@ -196,6 +196,8 @@ end
 -- @return table List of items for current page.
 local function get_current_page(all_items, query, scr)
     scr = get_screen(scr)
+    print("get_current_page called for", scr)
+    print(debug.traceback())
     if not instance.prompt.width then
         instance.prompt.width = compute_text_width(instance.prompt.prompt, scr)
     end
@@ -350,6 +352,7 @@ end
 --- Create the menubar wibox and widgets.
 -- @tparam[opt] screen scr Screen.
 local function initialize(scr)
+    print("initialize called for", scr)
     instance.wibox = wibox({})
     instance.widget = menubar.get(scr)
     instance.wibox.ontop = true
```

**Comment by rasendubi** [comment]
I experience the same issue. On the first invocation of `Mod4 + p` I see
```
share/awesome/lib/menubar/utils.lua:289: attempt to index field 'Async' (a nil value)
```

All subsequent invocation yield
```
share/awesome/lib/menubar/init.lua:199: attempt to index field 'prompt' (a nil value)
```

I'll try applying the patch now.

**Comment by psychon** [comment]
@rasendubi What's you LGI version? `lua -e 'print(require("lgi.version"))'`

**Comment by psychon** [comment]
NixOS has an ancient version of LGI: https://github.com/NixOS/nixpkgs/blob/98a9d815e05dd56aba0f9040d96092335cd90444/pkgs/top-level/lua-packages.nix#L385 (It's 0.7.2 and it is from 2013)

Turns out that menubar needs at least version 0.8.0 (from 2014, so also quite old) since commit 4eb80853c2f3fb26347cf50eb9b9792a06e6cfca.

**Comment by rasendubi** [comment]
I'll update LGI now and report back.

**Comment by rasendubi** [comment]
Updated LGI to 0.9.1 and I don't see an error now.

**Comment by rasendubi** [comment]
Opened: https://github.com/NixOS/nixpkgs/pull/21580

**Comment by flosse** [comment]
> Updated LGI to 0.9.1 and I don't see an error now.

Works for me too :)
Thanks a lot!

**Comment by psychon** [comment]
We still have to do something on our side for this, like bumping the code that checks for too-old-lgi. :-)
