### ISSUE TITLE
Why does awful.hotkeys_popup use notification_opacity

### ISSUE THREAD

**Issue by psychon** [awesomeWM/awesome#1352]
This seems at least surprising. I wouldn't consider this a notification. Can it use its own beautiful key instead?
https://github.com/awesomeWM/awesome/blob/3fea2db8c5f8cd5a2f3ed463fe57dcdc673c3afc/lib/awful/hotkeys_popup/widget.lua#L338

**Comment by funeralismatic** [comment]
And its own `border_width`, `border_color` and `bg_color`. At the moment, `hotkeys_popup` looks alien, even with the default theme.

**Comment by psychon** [comment]
CC @actionless

**Comment by actionless** [comment]
i was thinking what it should take notifications style since it's, like a notification, some overlay information

mb the best strategy will be to have its own theme keys for hotkeys window but fallback to notification ones if they are not defined?

**Comment by blueyed** [comment]
> mb the best strategy will be to have its own theme keys for hotkeys window but fallback to notification ones if they are not defined?

Makes sense to me.

**Comment by funeralismatic** [comment]
@actionless something like

```lua
opacity = beautiful.hotkeys_popup_opecity or beautiful.notification_opacity or 1
```

?

**Comment by wimstefan** [comment]
And if you're on it could you please also make the fonts configurable?

**Comment by actionless** [comment]
@funeralismatic yup
@wimstefan yup

**Comment by psychon** [comment]
@actionless By the way, `naughty` doesn't have a `beautiful.notification_opacity` setting.

**Comment by mindeunix** [comment]
@actionless Can you add option to show only focused client keys (if any) ?

**Comment by actionless** [comment]
i've realized what that part of the widget is undocumented 😿 

you can set up rules for application hotkeys blocks following this example https://github.com/awesomeWM/awesome/blob/master/lib/awful/hotkeys_popup/keys/vim.lua#L9-L21

**Comment by mindeunix** [comment]
@actionless sorry for not being descriptive. I mean option to display only defined keybindings for third-party applications (without awesome keys). This should not be difficult to implement.

**Comment by actionless** [comment]
@mindeunix 
what kind of api do you expect for that?
i can do some option like "rule_for_awesome_keys"

**Comment by mindeunix** [comment]
good question, maybe this one:
```lua
local hotkeys_popup = require("awful.hotkeys_popup.widget")
local urxvt_rule_any = {class={"URxvt", "urxvt"}, hide_others=true}
for group_name, group_data in pairs({
        ["URxvt"] = { color="#659FdF", rule_any=urxvt_rule_any },
        ["ZSH"]   = { color="#cF4F40", rule_any=urxvt_rule_any }
}) do
    hotkeys_popup.group_rules[group_name] = group_data
end
```

**Comment by actionless** [comment]
what about this?

```lua
local hotkeys_popup = require("awful.hotkeys_popup.widget")
local urxvt_rule_any = {class={"URxvt", "urxvt"}}
for group_name, group_data in pairs({
        ["URxvt"] = { color="#659FdF", rule_any=urxvt_rule_any, hide_others=true },
        ["ZSH"]   = { color="#cF4F40", rule_any=urxvt_rule_any, hide_others=true }
}) do
    hotkeys_popup.group_rules[group_name] = group_data
end
```

because that behavior is not part of a client-matching rule, but of hotkey group
