### ISSUE TITLE
Installing Awesome 4.0 on Ubuntu 16.04

### ISSUE THREAD

**Issue by legostax** [awesomeWM/awesome#1356]
Output of `awesome --version`: Haven't installed it yet.  Trying to install 4.0.

I'm a noob to Awesome, so what am I doing wrong?  I'm 90% sure I installed all of the deps.  That is, I've installed everything where it says "checking for modules"

I run `make` and this happens:
```
Running cmake…
-- git -> /usr/bin/git
-- asciidoc -> /usr/bin/asciidoc
-- xmlto -> /usr/bin/xmlto
-- gzip -> /bin/gzip
-- ldoc -> /usr/bin/ldoc
-- convert -> /usr/bin/convert
-- Checking for modules 'glib-2.0;gdk-pixbuf-2.0;cairo;x11;xcb-cursor;xcb-randr;xcb-xtest;xcb-xinerama;xcb-shape;xcb-util>=0.3.8;xcb-keysyms>=0.3.4;xcb-icccm>=0.3.8;xcb-xkb;xkbcommon;xkbcommon-x11;cairo-xcb;libstartup-notification-1.0>=0.10;xproto>=7.0.15;libxdg-basedir>=1.0.0;xcb-xrm'
--   
CMake Error at /usr/share/cmake-3.5/Modules/FindPkgConfig.cmake:367 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPkgConfig.cmake:532 (_pkg_check_modules_internal)
  awesomeConfig.cmake:153 (pkg_check_modules)
  CMakeLists.txt:17 (include)


-- Configuring incomplete, errors occurred!
See also "/home/legostax/awesome-4.0/.build-LSUbGn-x86_64-linux-gnu-5.4.0/CMakeFiles/CMakeOutput.log".
See also "/home/legostax/awesome-4.0/.build-LSUbGn-x86_64-linux-gnu-5.4.0/CMakeFiles/CMakeError.log".
Makefile:22: recipe for target 'cmake' failed
make: *** [cmake] Error 1
```

Please forgive me if this is the wrong place to be asking for help.

**Comment by psychon** [comment]
Sigh. I thought we had done something about this, but apparently not. CMake is not providing any helpful error messages here.

Can you run the following command? It should produce a more helpful error message. `pkg-config --modversion glib-2.0 gdk-pixbuf-2.0 cairo x11 xcb-cursor xcb-randr xcb-xtest xcb-xinerama xcb-shape xcb-util xcb-keysyms xcb-icccm xcb-xkb xkbcommon xkbcommon-x11 cairo-xcb libstartup-notification-1.0 xproto libxdg-basedir xcb-xrm`

> Please forgive me if this is the wrong place to be asking for help.

Please ask questions here! :-)

**Comment by legostax** [comment]
That command helped a lot!
My build was successful after installing `libstartup-notification0-dev`.  I already `libstartup-notification0` installed, but not the dev version.  Thus, I overlooked that in my `apt search`es.  Thank you for your help!

Maybe that command should be put in the troubleshooting section in `README.md`?  That is, unless you can make CMake provide more helpful error messages for the dependencies?

**Comment by Elv13** [comment]
This is strange.

From your backtrace:

    awesomeConfig.cmake:153 (pkg_check_modules)

From the 4.0 repository:

https://github.com/awesomeWM/awesome/blob/26c0a3c2c5b923fcdd08d26a87e520a58fe6dbb9/awesomeConfig.cmake#L153

If I change the loop to

```cmake
# Check the deps one by one
foreach(dependency ${AWESOME_DEPENDENCIES})
    pkg_check_modules(TMP_DEP REQUIRED ${dependency})
    message("FOO " ${dependency} "   " ${TMP_DEP_FOUND} )

    if(NOT TMP_DEP_FOUND)
        message(FATAL_ERROR)
    endif()
endforeach()
```

I get:

```
-- Checking for module 'xcb>=1.6'
--   Found xcb, version 1.12
-- Checking for module 'glib-2.0'
--   Found glib-2.0, version 2.50.2
FOO glib-2.0   1
FOO gdk-pixbuf-2.0   1
FOO cairo   1
FOO x11   1
FOO xcb-cursor   1
FOO xcb-randr   1
FOO xcb-xtest   1
FOO xcb-xinerama   1
FOO xcb-shape   1
FOO xcb-util>=0.3.8   1
FOO xcb-keysyms>=0.3.4   1
FOO xcb-icccm>=0.3.8   1
FOO xcb-xkb   1
FOO xkbcommon   1
FOO xkbcommon-x11   1
FOO cairo-xcb   1
FOO libstartup-notification-1.0>=0.10   1
FOO xproto>=7.0.15   1
FOO libxdg-basedir>=1.0.0   1
FOO xcb-xrm   1
-- Checking for modules 'glib-2.0;gdk-pixbuf-2.0;cairo;x11;xcb-cursor;xcb-randr;xcb-xtest;xcb-xinerama;xcb-shape;xcb-util>=0.3.8;xcb-keysyms>=0.3.4;xcb-icccm>=0.3.8;xcb-xkb;xkbcommon;xkbcommon-x11;cairo-xcb;libstartup-notification-1.0>=0.10;xproto>=7.0.15;libxdg-basedir>=1.0.0;xcb-xrm'
--   Found glib-2.0, version 2.50.2
--   Found gdk-pixbuf-2.0, version 2.36.0
--   Found cairo, version 1.14.6
--   Found x11, version 1.6.4
--   Found xcb-cursor, version 0.1.3
--   Found xcb-randr, version 1.12
--   Found xcb-xtest, version 1.12
--   Found xcb-xinerama, version 1.12
--   Found xcb-shape, version 1.12
--   Found xcb-util, version 0.4.0
--   Found xcb-keysyms, version 0.4.0
--   Found xcb-icccm, version 0.4.1
--   Found xcb-xkb, version 1.12
--   Found xkbcommon, version 0.7.0
--   Found xkbcommon-x11, version 0.7.0
--   Found cairo-xcb, version 1.14.6
--   Found libstartup-notification-1.0, version 0.12
--   Found xproto, version 7.0.31
--   Found libxdg-basedir, version 1.2.0
--   Found xcb-xrm, version 1.0
```

And when I uninstall `xrm` I get

    --   No package 'xcb-xrm' found

I guess someone will need to install Ubuntu to see why it didn't happen for you.

**Comment by Elv13** [comment]
Ok, I used a Docker image and reproduced the problem.
