### ISSUE TITLE
Systray flicker with multiple monitors

### ISSUE THREAD

**Issue by timpauvictor** [awesomeWM/awesome#1359]
Output of `awesome --version`: 
`
awesome v3.5.9 (Mighty Ravendark)
 • Build: Mar 12 2016 01:11:40 for x86_64 by gcc version 5.3.0 (builduser@rw)
 • Compiled against Lua 5.3.2 (running with Lua 5.3)
 • D-Bus support: ✔
`

**How to reproduce the issue:**
Happens regardless of hardware whenever I have more than one monitor connected. I should also note that when it flickers it's as if the icon isn't even there, clicking in the spot it should be in doesn't open the menu for application. 

**Expected result:**
No flicker would be nice. 

Video: https://webmshare.com/play/omOjo
Note I have three monitors connected (another one to the left) and they flicker between random monitors. The one on the far left seems to like taking ownership more often than the other two.

**Comment by Elv13** [comment]
Hello,

First of all, note that the systray can only be on one screen at any point in time. Trying to force it into multiple screens is not going to work, see the FAQ.

If it still flicker when only on a single screen, then try to start Awesome with `--no-argb`. If that still doesn't work, then try to upgrade to Awesome 4, it has some changes in that regard.

**Comment by psychon** [comment]
Additionally to what Elv13 already said: Can you fix your config so that the systray is only on one monitor or should we help? If so, could you pastebin your config somewhere?

**Comment by timpauvictor** [comment]
I have no idea how to go about doing that, thanks a lot for offering!
Here's my config at the moment: http://pastebin.com/K0q4Df3f
And my xrandr output: http://pastebin.com/G1QrxsKm

**Comment by Elv13** [comment]
Uncomment 

     --if s == 1 then right_layout:add(wibox.widget.systray()) end

and remove

     right_layout:add(wibox.widget.systray())

**Comment by psychon** [comment]
(and possibly change the `1` into a `2` or whatever fits)

@Elv13 Should I try to come up with ugly hacks so that awesome complains when the systray is shown in multiple places?

**Comment by Elv13** [comment]
> @Elv13 Should I try to come up with ugly hacks so that awesome complains when the systray is shown in multiple places?

Didn't you already did something about it in 4.0? If not, then sure, why not. it will be more useful than the current firework.

**Comment by psychon** [comment]
> Didn't you already did something about it in 4.0?

Nope. I have no idea what to do about it. I do not even know how to stop the flickering. The only idea that I have is the following (untested, ugly and slow!) patch that tries to detect the situation:
```diff
diff --git a/lib/wibox/drawable.lua b/lib/wibox/drawable.lua
index 330edc3..c6a2d03 100644
--- a/lib/wibox/drawable.lua
+++ b/lib/wibox/drawable.lua
@@ -25,6 +25,41 @@ local unpack = unpack or table.unpack -- luacheck: globals unpack (compatibility
 
 local visible_drawables = {}
 
+local pending_redraws = 0
+
+-- Set by wibox.widget.systray
+drawable.systray_instance = nil
+
+-- Check that the systray is in only one visible wibox
+local warned = false
+local function check_systray()
+    local systray = drawable.systray_instance
+    if warned or not systray then
+        return
+    end
+
+    local has_systray = nil
+    local function walk_hierarchy(d, h)
+        local width, height = h:get_size()
+        if h:get_widget() == systray and width ~= 0 and height ~= 0 then
+            if has_systray and not warned then
+                require("gears.debug").print_warning("The systray is currently visible in more than one place. This is not possible in X11 and will lead to flickering. Please fix your configuration so that the systray is only visible in a single place!")
+                warned = true
+            end
+            has_systray = d
+        end
+        for _, child in ipairs(h:get_children()) do
+            walk_hierarchy(d, child)
+        end
+    end
+
+    for d in pairs(visible_drawables) do
+        if d._widget_hierarchy then
+            walk_hierarchy(d, d._widget_hierarchy)
+        end
+    end
+end
+
 -- Get the widget context. This should always return the same table (if
 -- possible), so that our draw and fit caches can work efficiently.
 local function get_widget_context(self)
@@ -370,14 +405,19 @@ function drawable.new(d, widget_context_skeleton, drawable_name)
     -- Only redraw a drawable once, even when we get told to do so multiple times.
     ret._redraw_pending = false
     ret._do_redraw = function()
+        pending_redraws = pending_redraws - 1
         ret._redraw_pending = false
         do_redraw(ret)
+        if pending_redraws == 0 then
+            check_systray()
+        end
     end
 
     -- Connect our signal when we need a redraw
     ret.draw = function()
         if not ret._redraw_pending then
             timer.delayed_call(ret._do_redraw)
+            pending_redraws = pending_redraws + 1
             ret._redraw_pending = true
         end
     end
diff --git a/lib/wibox/widget/systray.lua b/lib/wibox/widget/systray.lua
index e83347c..1f17258 100644
--- a/lib/wibox/widget/systray.lua
+++ b/lib/wibox/widget/systray.lua
@@ -177,6 +177,7 @@ end
 function systray.mt:__call(...)
     if not instance then
         instance = new(...)
+        require("wibox.drawable").systray_instance = instance
     end
     return instance
 end
```
(Hm, the `d` argument is not really used; I wanted to include the two wiboxes in the warning, but that's not really useful...)

**Comment by actionless** [comment]
isn't it the fix?
https://github.com/awesomeWM/awesome/commit/a1b20ef6bb1b648f6559d01c998370c0b8f87827

**Comment by psychon** [comment]
I'll close this as "that fix is good enough". However, people can still cause this problem if they try to display the systray in two different places on the same screen...
