### ISSUE TITLE
Travis integration

### ISSUE THREAD

**Issue by blueyed** [awesomeWM/awesome#136]
I've started with adding integration with Travis in a separate branch.

1. "make check" fails with 3 errors, which are related to `assert` not being special as it should be.  Line 51 is this:

    `assert:register("assertion", "widget_fit", widget_fit, "assertion.widget_fit.positive", "assertion.widget_fit.positive")`

    > 43 successes / 0 failures / 3 errors / 0 pending : 0.06 seconds
    Error → spec/wibox/test_utils.lua @ 51
    ./spec/wibox/layout/align_spec.lua
    spec/wibox/test_utils.lua:51: attempt to index global 'assert' (a function value)
    Error → spec/wibox/test_utils.lua @ 51
    ./spec/wibox/layout/flex_spec.lua
    spec/wibox/test_utils.lua:51: attempt to index global 'assert' (a function value)
    Error → spec/wibox/test_utils.lua @ 51
    ./spec/wibox/layout/fixed_spec.lua
    spec/wibox/test_utils.lua:51: attempt to index global 'assert' (a function value)
    make[3]: *** [CMakeFiles/check] Error 3
    make[2]: *** [CMakeFiles/check.dir/all] Error 2
    make[1]: *** [all] Error 2
    make: *** [cmake-build] Error 2
    The command "make" failed and exited with 2 during .
2. I'd like to run the functional tests on Travis, and tried using Xvfb for
   this (which is installed on Travis:
   http://docs.travis-ci.com/user/gui-and-headless-browsers/).

   There are assertion errors from `lib/gears/debug.lua`:

    > lib/gears/debug.lua:23: Assertion failed: 'Cairo context entered error state: INVALID_FORMAT'
    stack traceback:
      lib/gears/debug.lua:23: in function 'assert'
      lib/wibox/drawable.lua:65: in function 'do_redraw'
      lib/wibox/drawable.lua:245: in function <lib/wibox/drawable.lua:243>
      [C]: in function 'pcall'
      lib/gears/timer.lua:103: in function <lib/gears/timer.lua:101>
    lib/gears/debug.lua:23: Assertion failed: 'Cairo context entered error state: INVALID_FORMAT'

The functional tests can be run headless locally using:

       CI=true t/run.sh

Builds can be seen at https://travis-ci.org/blueyed/awesome/branches / https://travis-ci.org/blueyed/awesome.

NOTES:

  - `shared-mime-info` is required for gdk-pixbuf to recognize images from files.  Errors looked like this: `error: lib/gears/surface.lua:39: Couldn't recognize the image file format for file /usr/local/share/awesome/themes/default/background.png''` (with the very minimal / teared down `ubuntu:precise` Docker image).

**Comment by psychon** [comment]
Done and merged (some PR by you)
