### ISSUE TITLE
Awesome doesn't work very well in Xephyr when -resizable is set

### ISSUE THREAD

**Issue by Elv13** [awesomeWM/awesome#1362]
First, the Awesome screen isn't resized. But more importantly, if you play (resize the Xephyr using the mouse) with it for too long, it goes black and Awesome stops responding (but doesn't crash).

![image](https://cloud.githubusercontent.com/assets/340384/21638814/fb0393e6-d23a-11e6-91fb-297ca5eba364.png)

In this screenshot, Xephyr is at the bottom right. The 2 big black rectangles are terminals (they should *not* be black) and tre other is the wibar. It shows the default config.

**Comment by psychon** [comment]
May I just claim that this is a bug in Xephyr?

**Comment by psychon** [comment]
Well, ok. `-resizeable` works and awesome 3.5.6 restarts when I resize the Xephyr window. Awesome 4 doesn't work that well. Weird...

**Comment by psychon** [comment]
Fun fact: Running `xrandr` makes awesome notice the resize. Looking at it with x11trace: When `xrandr` runs, we get a RandR-OutputChange event and then we can react to it. Before this event, apparently the RandR configuration did not change (wee see that the root window was resized, but when querying the RandR state apparently nothing changed).

I continue to blame Xephyr.

**Comment by psychon** [comment]
Same behaviour with `i3` (and i3 spams "ERROR: ERROR: No such screen").
Same behaviour with `xmonad`.
Same behaviour with `dwm`.
xfwm seems to get it right.
metacity seems to get it right.

**Comment by Elv13** [comment]
@psychon Do you want to close this or take a last look? Do as you wish

**Comment by tomjaguarpaw** [comment]
I see the same problem with xmonad. Running `xrandr` in the Xephyr display make xmonad aware of the resize, but before that it does not seem to be aware.
