### ISSUE TITLE
Coverage for C code

### ISSUE THREAD

**Issue by blueyed** [awesomeWM/awesome#1364]
We should track coverage of the C code also (after #1239).

I have found the following references when briefly looking into it:
https://github.com/codecov/example-c
https://github.com/bilke/cmake-modules/blob/master/CodeCoverage.cmake
https://github.com/RWTH-ELP/CMake-codecov

I have added `-g;-O0;-fprofile-arcs;-ftest-coverage` to `AWESOME_C_FLAGS`, `CMAKE_CXX_FLAGS` and `CMAKE_C_FLAGS`.
`.gcno`/`.gcda` files were then written to `build/CMakeFiles/awesome.dir/**/*.gcno`.

**Comment by Elv13** [comment]
Open question: Should/can it use a different codecov/coveralls account/profile and run in another CI target?

Running the tests already takes too long. C tests wont slow it down as much as Lua ones, but they will make the slowest targets slower.

**Comment by blueyed** [comment]
> Should/can it use a different codecov/coveralls account/profile and run in another CI target?

It might be possible to upload/merge coverage from another build job for the same build..
