### ISSUE TITLE
(question/request) Get menubar table

### ISSUE THREAD

**Issue by copycat-killer** [awesomeWM/awesome#1365]
```shell
$ awesome --version
awesome 4.0 (Harder, Better, Faster, Stronger)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • RandR 1.5 support: ✔
 • LGI version: 0.9.1
```

In the previous 3.5.x branch, `menubar.menu_gen.generate` returns an `awful.menu` compliant table, while in the 4.0 branch it doesn't anymore.

Can you tell me a clean way to get the same result in current branch too?

[This](https://github.com/copycat-killer/awesome-freedesktop/blob/master/menu.lua) is the best I could do, but it's dirty: [this part](https://github.com/copycat-killer/awesome-freedesktop/blob/master/menu.lua#L65-L75) doesn't work because of the asynchronicity of `menu_gen.generate`, which terminates after it.

Since the original Freedesktop module was meant to provide a menu, it'd be nice to have this feature back.

**Comment by Elv13** [comment]
Hello,

I started a multi phase refactor of the menubar (https://github.com/awesomeWM/awesome/pull/1329 for phase 1 and there is a gist with phase 2 WIP code). I will probably take care of it in the last PR of that series.

For now, you can copycat my version https://github.com/Elv13/awesome-configs/blob/master/utils/fd_async.lua (demo menu https://github.com/Elv13/awesome-configs/blob/master/customMenu/appmenu.lua). It has:

 * Full async loading
 * Fetching icons using GTK instead of looking around
 * Use the system icon theme
 * Done "right", has no delay even on slow laptops HDD (the example above use Radical for the menus, but `awful.menu` can also be used if you prefer it)

**Comment by psychon** [comment]
> This is the best I could do, but it's dirty: this part doesn't work because of the asynchronicity of menu_gen.generate, which terminates after it.

So, run that code in the callback instead of before it?

> Since the original Freedesktop module was meant to provide a menu, it'd be nice to have this feature back.

I do not think anything that was provided is lost, is it? The only "problem" might be that awesome no longer freezes while it loads all the menu files, meaning your code has to wait for a callback.

**Comment by copycat-killer** [comment]
> So, run that code in the callback instead of before it?

Already tried both, the result is the same: `generate` always terminates after, because it's heavier.

> I do not think anything that was provided is lost, is it? The only "problem" might be that awesome no longer freezes while it loads all the menu files, meaning your code has to wait for a callback.

Of course nothing is lost, but still the menu is no longer allowed. 

The point is waiting for the callback: how can we synchronize? This is the *real* problem. I can only think about sockets, but in Lua it'd require a clever design.

@Elv13 Your work is always impressive, but radical is simply huge and it's hard to figure out how to switch to `awful.menu` in your `customMenu/appmenu`. Can you lend me a hand, please?

**Comment by copycat-killer** [comment]
With @BlueUsername 's patch, my little repo got back on track, even though now I am forced to return an `awful.menu` instead of an entries table. So I'll be waiting for the refactoring mentioned above.

**Comment by Elv13** [comment]
@copycat-killer  Can this be closed?

**Comment by copycat-killer** [comment]
Git shows the request has been satisfied, so yeah. Thanks.
