### ISSUE TITLE
A way to speed up tail --pid in the test suite

### ISSUE THREAD

**Issue by psychon** [awesomeWM/awesome#1374]
Running `tests/run.sh` on this computer takes about 55 seconds. After the following patch, this is down to 25 seconds:
```diff
diff --git a/tests/run.sh b/tests/run.sh
index ed2a604..fef8782 100755
--- a/tests/run.sh
+++ b/tests/run.sh
@@ -210,7 +210,7 @@ for f in $tests; do
     DISPLAY=$D "$AWESOME_CLIENT" 2>&1 < "$f"
 
     # Tail the log and quit, when awesome quits.
-    tail -n 100000 -f --pid "$awesome_pid" "$awesome_log"
+    tail -n 100000 -s 0.01 -f --pid "$awesome_pid" "$awesome_log"
 
     set +e
     wait $awesome_pid
```
I cannot quite explain the speed-up by 30 seconds, but I'll try to explain parts of it:

`tail --pid 1234` works by checking every `n` seconds if the process with the given PID is still alive. If not, it exits. Assuming "exit of the process" is a uniformly distributed event (it is not), the average delay that `tail` needs to notice that the process exited is `n/2`.
According to the man page, the default is `n=1` and we have 30 tests, so the expected delay due to `tail` is `30/2 = 15 seconds`.
However, this obviously does not explain the 30 seconds speed-up that I saw in a quick experiment.
(Random idea: Most tests are "immediately done" (e.g. `test-leaks.lua`) and for these there is a high probability that almost a whole second is needed before `tail` notices)

Before something like this is merged, I guess we should make some (rough) measurements about what is the maximal argument for the `--sleep-interval` argument which still provides quite a good speed-up (on some random computer). I bet that `0.01` is way too low.

Anyone wants to find the sweet spot for this parameter?

**Comment by blueyed** [comment]
Great find.
I think we should start with `0.05`, but `0.01` is also find: after all it's probably quite cheap for `tail` to check if the process is still there?!

On CI we could also skip the `tail` completely probably, and just cat it afterwards?!

**Comment by psychon** [comment]
I did some measurements with the following command and patch:
```sh
export CI=true LC_ALL=C ; for x in $(seq 1 100) ; do TAIL_ARG=$(printf "-s %.2f " $(($x/100.0))) ; /bin/time -f "${TAIL_ARG} %E" sh -c 'tests/run.sh >/dev/null 2>/dev/null' ; done
```
```diff
diff --git a/tests/run.sh b/tests/run.sh
index ed2a604..b45c394 100755
--- a/tests/run.sh
+++ b/tests/run.sh
@@ -210,7 +210,7 @@ for f in $tests; do
     DISPLAY=$D "$AWESOME_CLIENT" 2>&1 < "$f"
 
     # Tail the log and quit, when awesome quits.
-    tail -n 100000 -f --pid "$awesome_pid" "$awesome_log"
+    tail -n 100000 ${TAIL_ARG} -f --pid "$awesome_pid" "$awesome_log"
 
     set +e
     wait $awesome_pid
```
The results are as follows:
```
-s 0.01  0:26.35
-s 0.02  0:26.56
-s 0.03  0:26.85
-s 0.04  0:26.95
-s 0.05  0:27.14
-s 0.06  0:27.61
-s 0.07  0:27.80
-s 0.08  0:28.26
-s 0.09  0:28.38
-s 0.10  0:28.93
-s 0.11  0:28.82
-s 0.12  0:29.40
-s 0.13  0:29.81
-s 0.14  0:30.13
-s 0.15  0:30.45
-s 0.16  0:30.89
-s 0.17  0:31.15
-s 0.18  0:31.32
-s 0.19  0:31.58
-s 0.20  0:32.11
-s 0.21  0:32.45
-s 0.22  0:32.76
-s 0.23  0:33.19
-s 0.24  0:33.68
-s 0.25  0:34.00
-s 0.26  0:34.72
-s 0.27  0:34.55
-s 0.28  0:34.74
-s 0.29  0:35.17
-s 0.30  0:35.67
-s 0.31  0:36.06
-s 0.32  0:36.40
-s 0.33  0:36.43
-s 0.34  0:37.08
-s 0.35  0:37.49
-s 0.36  0:37.67
-s 0.37  0:37.97
-s 0.38  0:38.86
-s 0.39  0:38.38
-s 0.40  0:38.79
-s 0.41  0:38.95
-s 0.42  0:39.20
-s 0.43  0:39.45
-s 0.44  0:39.90
-s 0.45  0:40.15
-s 0.46  0:40.24
-s 0.47  0:41.01
-s 0.48  0:41.04
-s 0.49  0:41.36
-s 0.50  0:41.39
-s 0.51  0:42.12
-s 0.52  0:42.34
-s 0.53  0:42.60
-s 0.54  0:43.11
-s 0.55  0:43.39
-s 0.56  0:43.77
-s 0.57  0:44.40
-s 0.58  0:44.33
-s 0.59  0:44.58
-s 0.60  0:44.91
-s 0.61  0:45.33
-s 0.62  0:45.35
-s 0.63  0:45.75
-s 0.64  0:46.36
-s 0.65  0:47.20
-s 0.66  0:47.58
-s 0.67  0:47.50
-s 0.68  0:47.41
-s 0.69  0:47.77
-s 0.70  0:48.07
-s 0.71  0:48.39
-s 0.72  0:48.57
-s 0.73  0:48.94
-s 0.74  0:49.22
-s 0.75  0:49.72
-s 0.76  0:50.07
-s 0.77  0:50.12
-s 0.78  0:50.51
-s 0.79  0:50.87
-s 0.80  0:51.33
-s 0.81  0:51.56
-s 0.82  0:52.10
-s 0.83  0:52.19
-s 0.84  0:52.48
-s 0.85  0:52.66
-s 0.86  0:53.04
-s 0.87  0:53.77
-s 0.88  0:53.83
-s 0.89  0:54.06
-s 0.90  0:54.29
-s 0.91  0:54.73
-s 0.92  0:55.13
-s 0.93  0:55.19
-s 0.94  0:55.69
-s 0.95  0:56.18
-s 0.96  0:56.43
-s 0.97  0:56.63
-s 0.98  0:57.00
-s 0.99  0:57.32
-s 1.00  0:57.68
```
```
gnuplot -e 'set timefmt "%M:%S"' -e 'set ydata time' -e 'set terminal png' -e 'set output "/tmp/runtime.png"' -e 'plot "/tmp/data2" using 2:3 with linespoints'
```
![runtime](https://cloud.githubusercontent.com/assets/89482/24452412/6ef5d3d8-1483-11e7-91fd-9e7e6ada8209.png)
Hm. This is not the result that I was hoping for...

**Comment by psychon** [comment]
I also collected some data on Travis, but with less precision. The results look more-or-less as in the above image (but there is much more noise).
https://travis-ci.org/awesomeWM/awesome/builds/216360178
https://travis-ci.org/awesomeWM/awesome/builds/216362967
![measurements2](https://cloud.githubusercontent.com/assets/89482/24458828/5b797b40-149a-11e7-9afa-3a30ff51c20a.png)
So... Let's just go with 0.1 and be done? Even smaller values would save only about two seconds on Travis.
