### ISSUE TITLE
Can't access screen.selected_tag in tag.selected signal callback

### ISSUE THREAD

**Issue by warptozero** [awesomeWM/awesome#1387]
Output of `awesome --version`:
```
awesome v4.0-90-gf69769f7 (Harder, Better, Faster, Stronger)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • RandR 1.5 support: ✔
 • LGI version: 0.9.1
```

**How to reproduce the issue:**

Place the following in rc.lua:

```
awful.screen.connect_for_each_screen(function(s)

    [...]

    s.mastercountbox = wibox.widget.textbox(s.selected_tag.master_count)

    awful.tag.attached_connect_signal(s, "property::selected", function()
        s.mastercountbox.text = s.selected_tag.master_count
    end)

    awful.tag.attached_connect_signal(s, "property::master_count", function()
        s.mastercountbox.text = s.selected_tag.master_count
    end)
```

**Actual result:**

- The textbox shows the master count upon startup.
- When changing the master count it updates correctly.
- Yet when switching tags it gives `attempt to index a nil value (field 'selected_tag')`

Using `s.mastercountbox.text = awful.screen.focused().selected_tag.master_count` yields the same result. As does using column_count instead of master_count.

**Expected result:**

Textbox should update correctly upon switching tags.

**Comment by psychon** [comment]
Tag switch works like this: First, all tags are unselected, then all tags are selected (more or less). Notably it is not done atomically in a single step. This means that during a tag switch, your function is called more than once. There is a short moment where no tag is selected and hence `s.selected_tag` is `nil`, just as the error message says.

I would propose using something like `s.selected_tag and s.selected_tag.master_count or 0` to fix this.

> Using s.mastercountbox.text = awful.screen.focused().selected_tag.master_count yields the same result. As does using column_count instead of master_count.

Yup, same reason.

Does the above make sense to you and fix your issue?

**Comment by warptozero** [comment]
Ah I see, that certainly makes sense. And your proposed solution works.

I decided to use an `if s.selected_tag then` block to wrap the statements. I find this a little clearer and I think this also prevents an extra call to the textbox to update to a 0 (although I wasn't able to see this in practice).

So this solves my issue, the texbox now works as expected. Thanks for the explanation!
