### ISSUE TITLE
Encoding key in Desktop Entry group in awesome.desktop is deprecated

### ISSUE THREAD

**Issue by Veratil** [awesomeWM/awesome#1391]
While building my own rpm for v4.0 in Fedora 24, I noticed in the build output:

```
+ desktop-file-validate /builddir/build/BUILDROOT/awesome-4.0-0.fc24.x86_64/usr/share/xsessions/awesome.desktop
/builddir/build/BUILDROOT/awesome-4.0-0.fc24.x86_64/usr/share/xsessions/awesome.desktop: warning: key "Encoding" in group "Desktop Entry" is deprecated
```

Other bugs I've seen with this just removes the line entirely without problem.

**Comment by psychon** [comment]
Silly question: Who makes these "rules" and declares these keys to be deprecated? Some hint/link?

Besides that: fine with me.

**Comment by Veratil** [comment]
Rules are formed from [freedesktop.org](https://www.freedesktop.org/wiki/). On the standards they manage:

***freedesktop.org is not a formal standards organization, though some see a need for one that covers some of the areas we are working on. For Linux operating system standards, look at the Linux Standard Base project. The X.Org Foundation and the IETF are other groups that do formal standards. The Free Standards Group is one group that publishes "de jure" standards for free software; freedesktop.org is loosely affiliated with the FSG.***

***Unlike a standards organization, freedesktop.org is a "collaboration zone" where ideas and code are tossed around, and de facto specifications are encouraged. The primary entry to these discussions is the xdg mailing list.***

-----

The [desktop file specification](https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html) mentions it's followed by GNOME and KDE mainly (and I'm sure others, too).

You can see `Encoding` is listed in section C, and an explanation is given in section D.

**Comment by blueyed** [comment]
@Veratil 
Makes sense.
Please consider creating a PR for it.
