### ISSUE TITLE
Add widget section in My first awesome

### ISSUE THREAD

**Issue by scadu** [awesomeWM/awesome#1393]
Hi,

I noticed that _Add widgets_ section on [My first awesome](https://awesomewm.org/apidoc/documentation/07-my-first-awesome.md.html#) page is still missing. When we can expect to see this section?

**Comment by blueyed** [comment]
Why should it be there already?

Do you feel like creating a PR for it yourself?

**Comment by scadu** [comment]
I am afraid that currently I'm not able to PR.
However, I saw on IRC that this section is ready. @elv13 could you please confim?

**Comment by Elv13** [comment]
Uh, no? The sections that's ready is about how to extend the prompt. The closest thing to such doc would be https://awesomewm.org/apidoc/documentation/03-declarative-layout.md.html

I am not sure the conversation you are referring to. Here's the issue to list missing doc sections
https://github.com/awesomeWM/awesome/issues/1373

I will close this and update the other one.

**Comment by psychon** [comment]
Just for reference: The old "widget section" is here: https://github.com/awesomeWM/awesome-www-backup-old/blob/gh-pages/wiki/My_first_awesome.html#L219
It uses/recommends vicious, which does not really work for the LDoc API documentation. No idea what to do about that.


Can't we just remove that part? Or should we do something Linux-specific with an async-I/O-thingie? Do something with libgtop? Other ideas?

**Comment by mindeunix** [comment]
Libgtop would be nice, but it is currently very unstable :disappointed:
