### ISSUE TITLE
How do I vertically align an imagebox on the wibox?

### ISSUE THREAD

**Issue by legostax** [awesomeWM/awesome#1398]
Output of `awesome --version`:

_awesome v4.0 (Harder, Better, Faster, Stronger)
 • Compiled against Lua 5.1.5 (running with Lua 5.1)
 • D-Bus support: ✘
 • execinfo support: ✔
 • RandR 1.5 support: ✘
 • LGI version: 0.9.1_

**Question: How do I vertically align an imagebox on the wibox?**

Sorry for the noob question, as this probably isn't hard, but I can't seem to figure this one out...

Currently, I have this:

![offset icon](http://i.imgur.com/qdBKc4n.png)

I want this:

![centered icon](http://i.imgur.com/8KyjIzf.png)

So, how would I go about doing this?

**Comment by legostax** [comment]
I was able to solve this by making a black image that was 20px wide and 10px tall.  Then I used the following code:
```
{
    layout = wibox.layout.fixed.vertical,
    x20x10,
    myshswitch,
}
```
 in place of my headphones imagebox:
```
myshswitch,
```
Though I am still curious.  *Is* there a more elegant way to accomplish this?

**Comment by Elv13** [comment]
Eventually yes https://github.com/awesomeWM/awesome/pull/1120

**Comment by streetturtle** [comment]
This could be achieved with margin layout (container) following way:
```lua
    layout = wibox.container.margin (widget, 0, 0, 3)
```

**Comment by legostax** [comment]
`margin` worked!  Thank you!

I don't know what issues you're having with `.png` images, but I'm able to get it to work with them.

```
myshswitch = wibox.widget.imagebox(profileConfigPath.."headphones2.png", false)
...
s.mywibox:setup {
...
  {
    myshswitch,
    layout = wibox.container.margin(myshswitch,0,0,3)
  },
```

Output:

![2017-02-03-065244_1920x1080_scrot](https://cloud.githubusercontent.com/assets/8785607/22593854/c2bdf214-e9dd-11e6-954b-c0682ab932af.png)

**Comment by streetturtle** [comment]
Great! I'll retry with PDF, maybe I missed something.
