### ISSUE TITLE
Menubar won't open when theme.bg_focus is not a color

### ISSUE THREAD

**Issue by silverhammermba** [awesomeWM/awesome#140]
Set `theme.bg_focus` to an invalid color string and try to open the menubar. I would expect the menubar to open with some placeholder color (e.g. white), since this is the behavior of other wiboxes when given invalid colors. Instead, you get this error
````
W: awesome: luaA_dofunction:78: error while running function
stack traceback:
        [C]: in ?
        [C]: in function 'error'
        /usr/share/awesome/lib/wibox/widget/textbox.lua:61: in function 'set_markup'
        /usr/share/awesome/lib/awful/prompt.lua:225: in function 'run'
        /usr/share/awesome/lib/menubar/init.lua:276: in function 'show'
        /home/max/.config/awesome/rc.lua:256: in function 'press'
        /usr/share/awesome/lib/awful/key.lua:42: in function </usr/share/awesome/lib/awful/key.lua:42>
error: attempt to concatenate a userdata value
````

This error occurs because `Pango.set_markup` does not handle invalid colors well and no attempt is made to check the color before sending it. There are two problems here:

 1. By default, the menubar formats the cursor using text, and it gets the text color from `theme.bg_focus` which is not guaranteed to be a color (it could be some other [pattern](http://awesome.naquadah.org/doc/api/modules/gears.color.html#create_pattern)). Perhaps a new theme color needs to be added e.g. `theme.cursor`.
 2. The regular text color is taken from `theme.fg_focus`, which again does not check the color string. If you set it to an invalid string the menubar will again refuse to open and you'll see `<Invalid Text>` in the taglist and tasklist.

**Comment by actionless** [comment]
isn't it the same behavior as in `awful.widget.tasklist`?

**Comment by silverhammermba** [comment]
I don't think so. The tasklist accepts PNGs for bg_normal and bg_focus, but the menubar won't.

**Comment by actionless** [comment]
strange, beautiful is used only for `label()` (the same as in tasklist) and to compute fallback height from font

so fix should be addressed to prompt:
https://github.com/awesomeWM/awesome/blob/master/lib/awful/prompt.lua.in#L209

for example, to add additional check what it's a color

**Comment by silverhammermba** [comment]
Well it would also be nice to add PNG support to bring it in line with the tasklist. That's how I found the bug in the first place, but then I noticed that any non-color string doesn't work.

**Comment by actionless** [comment]
I am looking on `awful.widget.tasklist` and `awful.widget.common` modules and I can't get how it should work when you have an image in `theme.bg_focus` (not in `theme.bg_image_focus`)

**Comment by silverhammermba** [comment]
Ultimately `bg_focus` is passed to [`gears.color.create_pattern`](http://awesome.naquadah.org/doc/api/modules/gears.color.html#create_pattern), which handles much more than just hex colors. It can do gradients and tiled patterns from PNGs.

**Comment by actionless** [comment]
so may be you need just to set `theme.bg_cursor` explicitly to avoid this problem?

**Comment by silverhammermba** [comment]
What does the cursor color have to do with the background focus color?

Here is the problem as I see it:
 1. Set `bg_normal` and `bg_focus` to a hex color string. The tasklist and menubar have the expected appearance.
 2. Set `bg_normal` to a tiled PNG pattern (`"png:..."`) and `bg_focus` to a hex color string. The tasklist and menubar have the expected appearance.
 3. Set `bg_normal` _and_ `bg_focus` to a tiled PNG pattern. The tasklist has the expected appearance but the menubar will not open.

The same goes when you replace the tiled PNG pattern with any invalid color string: the tasklist and menubar will substitute placeholders, but the menubar won't open if `bg_focus` isn't a hex color string.

**Comment by actionless** [comment]
>3. Set bg_normal and bg_focus to a tiled PNG pattern. The tasklist has the expected appearance but the menubar will not open.

can you now set theme.bg_cursor_focus to save hex color?

**Comment by silverhammermba** [comment]
How does that solve the problem of the menubar not opening when the color string is invalid?

**Comment by silverhammermba** [comment]
As a side note, I find it really odd that I don't see a better error for this. Pango actually returns a very informative message:

    Value of 'background' attribute on <span> tag on line 1 could not be parsed; should be a color specification

And Lua tries to do something with it:

    if not attr then error(parsed) end

But I don't see any notification, and nothing in awesome's stdout or stderr. Why not?

**Comment by actionless** [comment]
>But I don't see any notification, and nothing in awesome's stdout or
stderr. Why not?

i think because it fails on concatenation, before passing it to pango

**Comment by psychon** [comment]
Should this be fixed by #155?

**Comment by silverhammermba** [comment]
It should be. Do you need me to test it or something?

**Comment by psychon** [comment]
Nah. I just look slightly less stupid when I ask and then close this, compared to when I just close this and then someone says "this is not fixed yet, reopen!". :-)
