### ISSUE TITLE
User data for awful.key cannot be shared

### ISSUE THREAD

**Issue by p-himik** [awesomeWM/awesome#1401]
Output of `awesome --version`:
```
awesome v4.0 (Harder, Better, Faster, Stronger)
 • Compiled against Lua 5.2.4 (running with Lua 5.2)
 • D-Bus support: ✔
 • execinfo support: ✔
 • RandR 1.5 support: ✘
 • LGI version: 0.9.0
```

**How to reproduce the issue:**
Somewhere in your config where you define keys, replace a local table with description/group with a variable that contains this table. Use the same variable in some other key.
E.g.
```lua
local aud = { description = "Raise the volume", group = "audio" }
local globalkeys = awful.util.table.join(
    awful.key({}, "XF86AudioRaiseVolume", apw.up, aud),
    awful.key({ modkey }, "Right", apw.up, aud),
)
```
Restart with the new config, open hotkeys popup.

**Actual result:**
![image](https://cloud.githubusercontent.com/assets/4410314/21961119/bd53cece-db33-11e6-84ca-ae2e6b3a5e85.png)

**Expected result:**
There should have been two records for different keys with the same description/group. Or at least there should be a documentation notice on `awful.key` that you can't reuse `data` argument.

**Comment by psychon** [comment]
So, something somewhere is modifying a table that it is not supposed to modify? Or using a table as a key in another table where it shouldn't?

**Comment by actionless** [comment]
It should clone the table from 'data' arg instead of just assigning it

I already have some fix in mind, but will write it after will manage with
the tests as planned

**Comment by psychon** [comment]
Thanks a lot!
