### ISSUE TITLE
"awesome --check" ignores requires in configuration file

### ISSUE THREAD

**Issue by warptozero** [awesomeWM/awesome#1407]
When running `awesome --check` on a configuration file that contains a require with invalid code
```
require("file_with_errors")
```
the output will be
```
✔ Configuration file syntax OK.
```

It's probably beyond the intent of that function, but as it can give a false positive I thought it justified making an issue.

**Comment by blueyed** [comment]
It's only a syntax check, and cannot check for any runtime errors that might happen later.

Given that, it might be possible to look for files in Lua's path, i.e. checking if they can be `require`d (but they should not get executed then probably).

**Comment by warptozero** [comment]
Ah well, nevermind, it's probably not worth the time. Also considering it's fairly easy to test a running instance in virtual x window. I'll close it as it only adds noise to the list.

**Comment by psychon** [comment]
So, should we remove "--check"? It is not really useful and I think can be replaced by somehow calling Lua directly (can it?).

**Comment by blueyed** [comment]
`luac -p` can be used, but I think `--check` is useful in general, and could be extended later.. and it will use the user's config automatically, so let's keep it.
