### ISSUE TITLE
'assert' error in awesome build.

### ISSUE THREAD

**Issue by aajjbb** [awesomeWM/awesome#1410]
**How to reproduce the issue:**
Build awesome in Manjaro

**Actual result:**
lua: /home/aajjbb/Devel/awesome/docs/05-awesomerc.md.lua:241: /home/aajjbb/Devel/awesome/awesomerc.lua: No such file or directory
stack traceback:
        [C]: in function 'assert'
        /home/aajjbb/Devel/awesome/docs/05-awesomerc.md.lua:241: in main chunk
        [C]: in ?
make[2]: *** [CMakeFiles/generate_awesomerc.dir/build.make:61: awesomerc.lua] Error 1
make[1]: *** [CMakeFiles/Makefile2:171: CMakeFiles/generate_awesomerc.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

**Expected result:**
Regular build process.

**Comment by aajjbb** [comment]
I managed to fix it creating a fake `awesomerc.lua` inside awesome folder.

**Comment by blueyed** [comment]
Are you building Git master (which has some fixes in this regard IIRC), or the 4.0 tag / tarball?
You might want to try the AUR package I am maintaining: https://aur.archlinux.org/packages/awesome-luajit-git/

**Comment by aajjbb** [comment]
I'm building git master.

**Comment by blueyed** [comment]
Ah, https://github.com/awesomeWM/awesome/pull/1330 improved the error here.

Have you (re)moved `/home/aajjbb/Devel/awesome/awesomerc.lua`?
It should be there, assuming that `awesome` is the cloned repo?!

**Comment by aajjbb** [comment]
I did cloned the repo, but for whatever reason (I don't remember messing with the file), it was gone.

I'll close as I can't recall how the file went missing.

**Comment by blueyed** [comment]
IIRC it popped somewhere else before, so maybe something in the build removes it?!
