### ISSUE TITLE
Transparent background isn't properly cleared between draws

### ISSUE THREAD

**Issue by silverhammermba** [awesomeWM/awesome#1411]
With awesome v3.5.9, fully transparent background colors aren't cleared between draws, meaning that each draw call seems to just stack on top of the last, until everything is a blurry mess. For example, here is what my run dialog looks like:

![transparency bug](http://i.imgur.com/dI32P5A.png)

To reproduce:
1. Set `theme.bg_normal = "#00000000"` i.e. full transparency.
2. Do some stuff that changes the wiboxes e.g. change layouts, open/close windows

If I set the background color to an opaque color everything looks fine. I believe transparency worked as expected in v3.5.8.

**Comment by Elv13** [comment]
You need a background *or* a compositor for this to work. Set your background to black and it will work fine.

**Comment by silverhammermba** [comment]
Ugh, yeah. I just realizing my compositor wasn't running. Disregard.

**Comment by silverhammermba** [comment]
Okay, turns out the compositor wasn't running because of some change in how the background is set. This is how i use to start it:

1. startx runs `compton -b`
2. then `exec awesome`
3. awesome runs `gears.wallpaper.maximized(beautiful.wallpaper, 1, true)`

This was setting the wallpaper, but the compositor was failing with the error `error 143: BadPicture request 139 minor 8`.

If I instead set the wallpaper with feh then the compositor no longer gets an error.

**Comment by psychon** [comment]
> You need a background or a compositor for this to work. Set your background to black and it will work fine.

Well, no? Isn't awesome supposed to do fake transparency in this case?

**Comment by Elv13** [comment]
> Well, no? Isn't awesome supposed to do fake transparency in this case?

It is reproducible, it as always been that way and still is as of git-HEAD. If you have no compositor **and** no root/wallpaper, then semi transparent content is plain garbage. The workaround is simply not to do that. I never saw that as a "bug", but more as a "just don't do this" kind of limitation.

Start a new Xephyr, do something that messes the buffers (but without setting a wallpaper), the start awesome with an `rc.lua` showing a single semi-transparent wibox => garbage.

**Comment by silverhammermba** [comment]
Yeah, that part isn't weird. The odd behavior is that the wallpaper set by awesome causes the compositor to crash.

**Comment by psychon** [comment]
I would still consider this a bug if awesome "draws things wrong" if there is no background.

@silverhammermba Can you run compton with -S and try to get a backtrace of the problem? (With gdb)
https://github.com/chjj/compton/blob/master/src/compton.c#L4528

**Comment by psychon** [comment]
So, is the following patch all that is needed to fix this? If not, did I misunderstand the issue?
```diff
diff --git a/lib/wibox/drawable.lua b/lib/wibox/drawable.lua
index 330edc31c..09e91136c 100644
--- a/lib/wibox/drawable.lua
+++ b/lib/wibox/drawable.lua
@@ -114,11 +114,13 @@ local function do_redraw(self)
     if not capi.awesome.composite_manager_running then
         -- This is pseudo-transparency: We draw the wallpaper in the background
         local wallpaper = surface.load_silently(capi.root.wallpaper(), false)
+        cr.operator = cairo.Operator.SOURCE
         if wallpaper then
-            cr.operator = cairo.Operator.SOURCE
             cr:set_source_surface(wallpaper, -x, -y)
-            cr:paint()
+        else
+            cr:set_source_rgb(0, 0, 0)
         end
+        cr:paint()
         cr.operator = cairo.Operator.OVER
     else
         -- This is true transparency: We draw a translucent background
```
