### ISSUE TITLE
Customizing hotkey popup

### ISSUE THREAD

**Issue by osleg** [awesomeWM/awesome#1412]
Output of `awesome --version`:
awesome v4.0-66-gaab37dc6 (Harder, Better, Faster, Stronger)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • RandR 1.5 support: ✔
 • LGI version: 0.9.1

**How to reproduce the issue:**
Hit mod+s (default)

**Actual result:**
Showing list of default commands for VIM

**Expected result:**
 Any vim user knows the default commands (or at least most of them) on muscular level, there is no real need for that.
So the questions would be:
1. Is there a way to show custom shortcuts automaticaly?
2. Where can I modify the descriptions for shortcuts, as for example I have "s" bound to surround plugin but mod+s shows it as substitute
3. Why actionless is not on IRC when needed? :D

**Comment by psychon** [comment]
>    Is there a way to show custom shortcuts automaticaly?

Sorry, but I do not understand the question.

>    Where can I modify the descriptions for shortcuts, as for example I have "s" bound to surround plugin but mod+s shows it as substitute

Isn't this just set when defining/creating the key binding? For example https://github.com/awesomeWM/awesome/blob/6a91dce42526d4cf8fb54e83d30f710380fd187f/awesomerc.lua#L249-L250 shows how the information for mod+S is added.

**Comment by mindeunix** [comment]
you can add keys for custom applications (if that's what you want), as an example:

```
local hotkeys_popup = require("awful.hotkeys_popup.widget")
local urxvt_rule_any = {class={"URxvt", "urxvt"}}
for group_name, group_data in pairs({
        ["URxvt"] = { color="#659FdF", rule_any=urxvt_rule_any },
        ["ZSH"]   = { color="#cF4F40", rule_any=urxvt_rule_any }
}) do
    hotkeys_popup.group_rules[group_name] = group_data
end

local urxvt_keys = {
    ["URxvt"] = {
        {
            modifiers = { "Mod1" },
            keys = {
                c = "copy",
                v = "Paste"
            }
        },
        {
            modifiers = {"Mod1", "Shift"},
            keys = {
                v = "Paste escaped"
            }
        }
    },
    ["ZSH"] = {
        {
            modifiers = {},
            keys = {
                Home   = "Beginning of line",
                End    = "End of line",
                Insert = "Overwrite mode",
                Delete = "Delete char",
                Left   = "Backward char",
                Right  = "Forward char",
                Prior  = "Beginning of buffer or history",
                Next   = "End of buffer or history",
            }
        },
        {
            modifiers = { "Mod1" },
            keys = {
                Down  = "Beginning of line",
                Up    = "End of line",
                Left  = "Backward word",
                Right = "Forward word"
            }
        },
        {
            modifiers = { "Control" },
            keys = {
                k = "Kill whole line",
                l = "clear screen"
            }
        }
    }
}

hotkeys_popup.add_hotkeys(urxvt_keys)
```
Now if you focus urxvt and press the ***modkey + s*** you will get:
![zsh](http://i.imgur.com/CPrEt0w.png)

But the issue title is correct, hotkey popup does not have any configurations (there is no simple way to change font, colors, width, height through beautiful).

**Comment by actionless** [comment]
> Why actionless is not on IRC when needed? :D

because i don't have an IRC bouncer / server for it :-)

closing as dup of #1352
