### ISSUE TITLE
Error in menugen/init.lua since update to 4.0

### ISSUE THREAD

**Issue by vevais** [awesomeWM/awesome#1415]
Hello, since Arch Linux updated to awesome 4.0, i am getting this error: http://i.imgur.com/b16zfhB.jpg
Here's my rc.lua if it helps: http://sprunge.us/jTYb?lua

I now downgraded and everything works as expected. What seems to be the problem here?

**Comment by Elv13** [comment]
Hello,

Awesome 3.5 configs are not compatible with 4.0. You have a (modified?) copy of the 3.5 version of the menubar module in your config[1]. You should either port your config to 4.0[2] or start from the new one and backport your changes.

Please re-open of you can reproduce the issue with an Awesome 4.0 compatible config.

[1] Line in the errors don't match the new version
[2] Fixing the errors until it "seems" to work is not enough, you miss important logic changes, see the changelog https://awesomewm.org/apidoc/documentation/89-NEWS.md.html

**Comment by psychon** [comment]
Also, the error message talks about menugen. As far as I know, no such module is shipped with awesome...? (we have menubar, not menugen)
