### ISSUE TITLE
awesome crash when there is a syntax error in rc.lua

### ISSUE THREAD

**Issue by Raphi111** [awesomeWM/awesome#1417]
Output of `awesome --version`:

awesome v4.0-105-gbfb35349 (Harder, Better, Faster, Stronger)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • RandR 1.5 support: ✔
 • LGI version: 0.9.1

**How to reproduce the issue:**

make a random syntax error in rc.lua and restart awesome.

**Actual result:**

awesome crash.

**Expected result:**

Awesome fallsback to a default rc.lua and prints some errors 
********************

I've been looking for errors messages in Xorg's logs but I haven't been able to find any (yet). My tty is configured to restart X as soon as it crash so I can't see any error there either but I can disable it to try to debug it more if needed.

PS: awesome 4.0 starts so much faster than version 3.5 ! It's amazing.

**Comment by aajjbb** [comment]
Do your distribution is a fresh install on pure awesome, or you had some DE installed before ? I'm experiencing similar issue with Manjaro (KDE by default). 

Instead of falling back on default `rc.lua` and show the errors, the system just freezes. If you're in KDE base too, I think it might have something to do with SDDM.

**Comment by psychon** [comment]
I can't test right now, so @aajjbb what do you mean exactly with "crash"? (@Raphi111 already wrote that he cannot provide more information)

**Comment by aajjbb** [comment]
By crash, I mean the system just freezes. And I need to open other tty and restart. 

@Raphi111 do you have a main DE installed as well ? I do only experience it in my Desktop, which has ManjaroKDE. I do not experience it with ManjaroMATE, so I suspect it may have something to do with KDE or SDDM (it's display manager)

**Comment by Raphi111** [comment]
I've been able to test it on another laptop that doesn't auto-restart X.
By crash I mean that when I run X (startx) from a console, the screen goes black for one second, then back to the console. I think I got the error:
`awesome: main:728: couldn't find any rc file`
I spotted other errors before that line but I've got to check if they are related or not.

**Comment by psychon** [comment]
> awesome: main:728: couldn't find any rc file

This is the error message you get after all configs error out. So the question should be: What error did the default config die with (after your user config already errored out)?

Note that you can run awesome in Xephyr by running something like this in a terminal:

Xephyr :5 & sleep 1 ; DISPLAY=:5 awesome

So you could log in to a working config, add some small-ish error to your config and then use the above to see the error messages easily.

**Comment by Raphi111** [comment]
Thanks for suggesting using Xephyr, it has been helpful. I think I found the problem. 
I'm starting awesome by running
`awesome -c .config/awesome/rcnew.lua` 
And I have another config file .config/awesome/rc.lua (this is my awesome 3.5 config) which cannot work anymore because I moved file around.
So awesome tries to run with rcnew.lua, it fails so it tries .config/awesome/rc.lua but it fails again so it exits.
Shouldn't awesome try using /etc/xdg/awesome/rc.lua as a last resort ? That way, let's say my home directory is all messed up with multiple rc.lua files I can still use awesome to fix my config files

**Comment by wright8191** [comment]
I experienced this issue because of #1346 - there was no default rc.lua to fallback on

**Comment by Elv13** [comment]
We could do it the "Qt" (and Windows DLL) way and compile the default `rc.lua` into the binary. This way even if the fallback rc.lua happen to be for the wrong version of Awesome or broken or missing, it would still have something to fallback to.

**Comment by aajjbb** [comment]
It would be a good as I don't have any clue on how and why it does happens in my desktop install.

**Comment by Veratil** [comment]
I've run into a similar issue when working with my theme. When there was an error awesome quits and I get put back to my login screen. Only way to fix it is to switch to a different virtual terminal and remove/fix the changes I just made, swap back and try again. Which is odd because some errors get the normal error notification while others just make awesome stop.

**Comment by blueyed** [comment]
@psychon 
> By crash, I mean the system just freezes. And I need to open other tty and restart.

Looks like what I've seen in #1422 - where I had to kill-9 `awesome`.
Maybe some errors that trigger this issue also try to e.g. put something on the stack when they cannot or something similar?!

**Comment by psychon** [comment]
My plan for this issue is to wait/find someone who can provide all the error messages so that we know why the default config breaks. Anyone has this information?

 My plan for a fix (no matter if we can also make the default config more robust) is to change the C code:
Currently, when we fall back to another config file, the Lua state is kept around (which is e.g. why people sometimes get more tags when this happens). This is easy to do on the C side, but not really good. So I guess I will have to teach the C code to close the Lua state and set up a new one for the next config. That's gonna be complicated, but should fix almost all reasons why the fallback to the default config fails (except for "awesome is looking in the wrong place" for which I also have an idea: the path should be hard-coded into the binary (and also other paths, so that all of the @FOO@-replacements that we have in Lua files can be removed))

**Comment by aajjbb** [comment]
The curious fact is that this issue happens in my ManjaroKDE install in desktop, but doesn't happen in ManjaroMATE (in my notebook). So, I guess it's about awesome conflicting with another software, and not 'entirely' awesome's fault.

**Comment by psychon** [comment]
Gentle ping.

Can anyone provide the error messages that makes the default config fail? You could just "break" your config while awesome is running and then run `Xephyr :5 & sleep 1 ; DISPLAY=:5 awesome` to get to the error more easily.

**Comment by Raphi111** [comment]
Here is the complete error log. I tried to reproduce the bug by running awesome with a broken rcnew.lua config file, and an empty rc.lua file in ~/.config/awesome/ but that didn't work. Instead I had a black screen with no errors at all but I guess it's okay since nobody is going to have a completaly empty rc.lua file anywhere.
So instead it's running with my rcnew.lua file which I broke on purpose, and my old (broken also) rc.lua in my home directory.
I see the default config is complaining about the theme but I don't understand why, as it's not complaining if I remove the broken rc.lua from my home directory.

[log.txt](https://github.com/awesomeWM/awesome/files/729367/log.txt)

**Comment by psychon** [comment]
@Raphi111 Thanks, that helps!

* first the `rcnew`-config fails with `.config/awesome/rcnew.lua:24: syntax error near 'if'`. This is all boring.
* Then `~/.config/awesome/rc.lua` fails with `cannot open /home/cabal/.config/awesome/theme.lua: No such file or directory`. So far: No idea why this happens.
Anyway, `beautiful` handles theme-loading-failures extremely bad.
* Next `/etc/xdg/awesome/rc.lua` fails in `require("awful.hotkeys_popup")`. The theme-loading-failure left `beautiful` in a broken state and the code here tries to query values form `beautiful` during startup, running into the broken state.

@Raphi111 What is line 50 of your config? It is the call to `beautiful.init()`, but what arguments do you use?

**Comment by Raphi111** [comment]
The line 50 in my config file is 
`beautiful.init("~/.config/awesome/theme.lua")`

It's _supposed_ to crash because that file no longer exists. I moved my themes to /usr/share/awesome/themes.
If I understand what you said correctly, awesome loads beautiful when it encounters that line, then as there is an error it fallsback to the default config file, then crash because beautiful is in a broken state ?

Wouldn't it be possible to reset beautiful's state before loading the default config file ?
I know awesome is supposed to crash when it gets to that line refering to a file that is no longer available but I wouldn't have expected that it would prevent the default config file from loading.

Thank you for your help on that issue ! :)

**Comment by psychon** [comment]
> but I wouldn't have expected that it would prevent the default config file from loading.

I would not have expected that either ;-)

**Comment by psychon** [comment]
@Raphi111's issue will be fixed by #1470. Since I doubt that all of you hit this problem by "breaking" `beautiful`, I am still interested in more log output to figure out more cases that cause "permanent damage". If I don't here more, I will assume that #1470 fixes this issue.

**Comment by blueyed** [comment]
#1470 is merged now.
@Raphi111 
I assume it helps with your test case then?

Would be nice to get more details on other similar issues, but in a separate issue then.
Luckily @Raphi111 is the OP of this one.. ;)

**Comment by Raphi111** [comment]
@blueyed Yes! I just tested on two different configs and with the patch awesome is able to start with the default config in both cases.
Thank you :)
