### ISSUE TITLE
gaps in layouts caused by not calling or mis-calling client:apply_size_hints

### ISSUE THREAD

**Issue by dzhu** [awesomeWM/awesome#1418]
This is a response to #1308 (but that's closed, so I figured it might be better to not respond directly there).

I believe I know the underlying reason for that issue. The `tile` layout calls `client:apply_size_hints` assuming that it accounts for the border size, which it does not. When `layout.arrange` calls `client:geometry`, it subtracts off the border size (and useless gap) first, which can cause hinted clients to jump down to a smaller size in the actual layout than was reported when `tile` called `apply_size_hints`, leaving a gap.

Meanwhile, the other layouts don't account for hints at all, so there are even more gaps.

Setting `honor_size_hints = false` sort of fixes the problem by forcing each client to fill the space originally computed by `tile`, but the old behavior lets the clients be their natural sizes and starts each client directly after the end of the previous one, which seems preferable.

Something like the patch linked below (based on bfb3534) might be useful; I've been testing it and it looks like it makes `tile` work properly as it used to. It doesn't deal with a nonzero `useless_gap`, though.

https://gist.github.com/dzhu/1d0889ad1419eb2b971ca5eb6b57d493

**Comment by psychon** [comment]
Thanks for figuring this out and writing such a good bug report!
(Note that 3.5 didn't have this "try to work well with size hints" code at all, so there should also have been some kind of issue before)

**Comment by dzhu** [comment]
Previously, `tile` would just call `client:geometry` directly, which would take care of the hints and return the appropriate size. But the change to delaying the actual sizing to later created a mismatch between what size `tile` thought would result and what actually happened, because now one place subtracts borders and one doesn't.

**Comment by Elv13** [comment]
> Can we change apply_size_hints so that it does the subtraction itself or is that too much of an API break @Elv13.

It's an ABI ([B]ehavior, not [B]inary) break, but then again: it's a bug. So yes, I am fine with changing the existing function. However, `awful.placement.resize_to_mouse` (generalized code taken from `awful/mouse/init.lua`) also uses this. It will require to see if this breaks (fast look: probably) then add the offset there, add an unit test and update the documentation of the CAPI function. This is more work... @dzhu already made a great investigation here. Fixing the existing API would be nicer, but it might be a little too much to ask?

**Comment by dzhu** [comment]
Hi, any updates on this? I've been running with my patch since opening the issue, and it's worked well, as far as I can tell. I can make a PR, if that would help, though it sounds like there might be more to consider first.
