### ISSUE TITLE
Menubar search results are reset when searching for the first time

### ISSUE THREAD

**Issue by p-himik** [awesomeWM/awesome#1421]
Output of `awesome --version`:

```
awesome v4.0 (Harder, Better, Faster, Stronger)
 • Compiled against Lua 5.2.4 (running with Lua 5.2)
 • D-Bus support: ✔
 • execinfo support: ✔
 • RandR 1.5 support: ✘
 • LGI version: 0.9.0
```

**How to reproduce the issue:**

1. (re)start Awesome
2. open menubar
3. start typing

**Actual result:**
It displays some results and then immediately resets back to the initial state.

**Expected result:**
It continues displaying results respecting the search query.

**Comment by actionless** [comment]
just wondering how much time passes between the 2nd and the 3rd steps?


i think the solution here will be to add one more condition (if user started typing) to this check:
https://github.com/awesomeWM/awesome/blob/master/lib/menubar/init.lua#L353-L355

**Comment by p-himik** [comment]
About 300-600ms I think.
