### ISSUE TITLE
No tag selected when using awful.tag.add() instead of awful.tag()

### ISSUE THREAD

**Issue by l0b0** [awesomeWM/awesome#1423]
Output of `awesome --version`:

```
awesome v4.0 (Harder, Better, Faster, Stronger)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • RandR 1.5 support: ✔
 • LGI version: 0.9.1
```

**How to reproduce the issue:**

1. Replace rc.lua with the default configuration
1. Replace the line `awful.tag({ "1", "2", "3", "4", "5", "6", "7", "8", "9" }, s, awful.layout.layouts[1])` with `awful.tag.add("shell",     {screen = s, layout = awful.layout.suit.fair})`
1. Restart awesome

**Actual result:**

No tag is focused.

**Expected result:**

The "shell" tag should be focused.

I'm doing this to be able to set separate layouts for the different tags, and this doesn't seem to be possible with `awful.tag()`. I've tried to force setting the focused tag on startup in different ways, but none of them seem to work. First try:

```
screen.selected_tags = { "shell" }
```

Second try:

    local first_tag = awful.tag.add("shell",     {screen = s, layout = awful.layout.suit.fair})
    […]
    screen.selected_tags = { first_tag }

**Comment by Elv13** [comment]
I don't think it should be changed. The whole point of `awful.tag.add` is to do it manually. You should add `selected = true` in the properties.

Having no selected tag is a valid use case.

**Comment by l0b0** [comment]
Alright, thanks! But you have to admit it's a bit surprising that `awful.tag` by default focuses the first tag.

**Comment by l0b0** [comment]
No problem, and thank you for the clarification. Great work on 4.0!
