### ISSUE TITLE
build: docs get generated twice with "make && make install"

### ISSUE THREAD

**Issue by blueyed** [awesomeWM/awesome#1427]
I think for packages the `make` could be just skipped (when `cmake` was called already).

```
build() {
  mkdir -p build
  cd build

  cmake ../$pkgname \
    -DCMAKE_BUILD_TYPE=RELEASE \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DSYSCONFDIR=/etc \
    -DLUA_INCLUDE_DIR=/usr/include/luajit-2.0 \
    -DLUA_LIBRARY=/usr/lib/libluajit-5.1.so
  # XXX: remove this?!
  # make
}

package() {
  cd build
  make DESTDIR="$pkgdir" install

  install -Dm644 "$srcdir"/$pkgname/awesome.desktop \
    "$pkgdir/usr/share/xsessions/awesome.desktop"

  install -Dm644 "$srcdir"/awesomeksm.desktop \
    "$pkgdir/usr/share/apps/ksmserver/windowmanagers/awesome.desktop"
}
```

Our README mentions `make && make install` though..

**Comment by blueyed** [comment]
We might improve the build speed after by just calling `make install` directly / fixing this issue:
```
  - travis_run_in_fold "make" make
  - |
    if [ "$TRAVIS_TEST_RESULT" = 0 ]; then
      travis_run_in_fold "make.install" sudo env PATH=$PATH make install
      awesome --version
    fi
```

**Comment by psychon** [comment]
I'm not sure that just running `install` directly always works fine. It does not run the `all` target, does it? I would feel more comfortable if we keep this separate.

However, we could have `cd build` or something like that in the right places on Travis. That should avoid rerunning cmake, I think.

**Comment by blueyed** [comment]
See https://github.com/awesomeWM/awesome/pull/1867 for some fix regard.

Closing this issue as unclear / not valid.
