### ISSUE TITLE
spec: focusing and raising a client on another tag

### ISSUE THREAD

**Issue by blueyed** [awesomeWM/awesome#143]
How should the following behave when called from tag 1, and with clients on tag 2?

```
echo 'client.focus = tags[1][2]:clients()[1]' | awesome-client
```

Currently it moves the input focus over to the client on the other tag, but does not switch the tag.

Is this the expected behavior after 6183d8587aa53ad222a4dcfe5dcb9cd939caa569?

What should happen for `client.focus:raise()` where `client.focus` is not visible (e.g. after the above)?

I would like to document the expected behavior in some tests.

**Comment by Elv13** [comment]
This

https://awesome.naquadah.org/doc/api/modules/awful.client.html#jumpto

**Comment by blueyed** [comment]
@Elv13 
This doesn't answer the question..

I know that there is `awful.client.jumpto`, but the question / issue is about defining how parts of it should behave.

**Comment by Elv13** [comment]
`jumpto` should be called by the `request::activate` callback if the client `:isvisible()` is false. That should make sure the tag get selected and the client focussed

**Comment by blueyed** [comment]
That make sense, but `request::activate` is not being called for `client.focus = c`.

**Comment by Elv13** [comment]
You can't blame user mistakes. If the user want to focus an invisible client by hand without using requests or jumpto directly, then so be it. no?

**Comment by psychon** [comment]
I guess the current behavior is expected. We could just consider it an API change between 3.5 and 3.6 that `client.focus` now allows to focus banned clients and expect people to switch to request::activate if that's what they actually want.

**Comment by Elv13** [comment]
@blueyed Should/can this be closed or you think those tests referred above would still be valuable?

**Comment by Elv13** [comment]
Closing due to the lack of activity
