### ISSUE TITLE
Bugfix release

### ISSUE THREAD

**Issue by blueyed** [awesomeWM/awesome#1444]
It came up in same issue already, and we should do a bugfix release soon.

I've noticed that current version looks like `4.0.134.g4a02ad86-1` for me (via awesome-luajit-git, which does `git describe | sed 's/^v//;s/-/./g'`), `4.0.1.*` would be lower.. :/

What about using more semantic versioning from now on, and having 4.1.0 as the next version?

We have a milestone for v4.1 (https://github.com/awesomeWM/awesome/milestone/4), and I would be glad to have #1001 in there, but would rather think that we should have a bugfix release (more or less the current master) first.

**Comment by Veratil** [comment]
[Semantic versioning](http://www.semver.org) -- link for details

**Comment by Elv13** [comment]
4.1 is the next version. There wont be official 4.0.* versions anymore (beside the stable+commits ones)

**Comment by blueyed** [comment]
@Elv13 
But 4.1.0 then?

**Comment by blueyed** [comment]
@Elv13 
> beside the stable+commits ones

?

**Comment by Elv13** [comment]
I think `4.1` is enough. I really don't want to get back to the broken ways of 3.x.y. As documented in another issues, I considered it a failure and would rather see the first number bumped more often than having lengthy development cycles without user facing releases, firefox/chrome style.

Having the third version number is intended for bug fix releases, but that would require keeping bug fix branches and we don't have the manpower/will to maintain them, so the bug fixes are part of master and it also has new features.

**Comment by blueyed** [comment]
We have only bugfixes on master by now?
If not, 4.1 is fine for me.

**Comment by Elv13** [comment]
> We have only bugfixes on master by now?

No ;). We have bug fixes *and* non-breaking features. If we had bugfixes only, then it would go into 4.0.1. But given features *are* mixed with bugfixes, then that creates a release worthy of 4.1.

**Comment by Veratil** [comment]
Like it was done with v4 in the NEWS doc, keeping a running log of what's merged with PRs would be beneficial to realizing what the next version string should be. Noting what each PR is (bugfix [patch level], enhancement [major/minor level]) would help in that determination.

As @Elv13 said, there are some features pulled in recently. One PR from me was a bugfix on the theme API, but also adding the proper variable to be looked up (adding "new" API). I think that by definition is a minor version bump?

**Comment by Elv13** [comment]
4.1 is released since a while, closing this
