### ISSUE TITLE
naughty notifications close on mouse press rather than mouse release

### ISSUE THREAD

**Issue by Veratil** [awesomeWM/awesome#1445]
With notifications closing on a mouse press rather than the mouse release, this can cause unwanted release events to happen on an underlying client.

For instance, if a notification is over a titlebar clicking near the top right will close the notification (the mouse button is still pressed). When the button is released this will cause the close button of a client to fire off, closing the client. Not what is wanted to happen.

Granted this is a rare occurrence given a notifications lifetime, this has happened to me before.

**Comment by blueyed** [comment]
i think it might be here: https://github.com/awesomeWM/awesome/blob/2627f087c5ab4ce3dcb8f9fa7c128cf2b31f85ff/lib/naughty/core.lua#L668-L672.

```diff
diff --git i/lib/naughty/core.lua w/lib/naughty/core.lua
index 764afe20..b3a56a8d 100644
--- i/lib/naughty/core.lua
+++ w/lib/naughty/core.lua
@@ -666,8 +666,8 @@ function naughty.notify(args)
     notification.box:set_widget(completelayout)
 
     -- Setup the mouse events
-    layout:buttons(util.table.join(button({ }, 1, run),
-                                   button({ }, 3, function()
+    layout:buttons(util.table.join(button({ }, 1, nil, run),
+                                   button({ }, 3, nil, function()
                                         die(naughty.notificationClosedReason.dismissedByUser)
                                     end)))
```

**Comment by Veratil** [comment]
That works!
