### ISSUE TITLE
keyboardlayout widget (and other) do not show.

### ISSUE THREAD

**Issue by MaPePeR** [awesomeWM/awesome#1451]
So I'm not sure if that is the correct place to put this. Sorry if it isn't.

Output of `awesome --version`:

```
awesome v4.0 (Harder, Better, Faster, Stronger)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • RandR 1.5 support: ✔
 • LGI version: 0.9.1
```
**How to reproduce the issue:**

Install and start the new awesome version 4.0 with the new rc.lua (from `/etc/xdg/awesome/rc.lua`)

(I made some [minor changes](https://gist.github.com/MaPePeR/1b818283a808f9684502ff4179ffe45c) to the `rc.lua` mostly disabling some layouts, switching scroll wheel direction, some keybindings and trying to use the lain `bat` and `pulseaudio` widgets, which also didn't show up)

**Actual result:**
The keyboardlayout widget and also the lain widgets i wanted to try do not show up. I see most of the other widgets like the textclock, the layout indicator, the systray, the promptbox as well as the launcher, the taglist and the tasklist.

**Expected result:**

The keyboardlayout widget and others should be shown.

Because i also don't see the default keyboardlayout widget i assume its a general problem with my setup. Does the missing `✔` with LGI indicate the Problem already?

**Comment by psychon** [comment]
> Does the missing ✔ with LGI indicate the Problem already?

Nope. There is never a ✔ there.

> The keyboardlayout widget [...] i wanted to try do not show up. 

The keyboardlayout widget only shows something when you have multiple groups. For example, run `setxkbmap us,ca` and then something should show up.

> The [...] lain widgets i wanted to try do not show up. 

Might be https://github.com/copycat-killer/lain/issues/248. How old is your version of lain?

**Comment by MaPePeR** [comment]
> For example, run `setxkbmap us,ca` and then something should show up.

This did the trick, so i guess its a lain-only or "in front of the screen" problem. 

> Might be copycat-killer/lain#248. How old is your version of lain?

I cloned the lain repository yesterday and just did a pull again. So it should be up to date. Did not show any widgets after an awesome restart. 

Thanks for helping.

**Comment by psychon** [comment]
Sorry, but if this is now down to "lain not working", I'll send you to https://github.com/copycat-killer/lain/issues/new where @copycat-killer can then figure the rest out. (Shameless CC so that there is now a slight  chance of a race condition between "reporting an issue" and "@copycat-killer taking a look" ;-) ).
