### ISSUE TITLE
Opening an I/O heavy program with a prompt explodes

### ISSUE THREAD

**Issue by zhrts** [awesomeWM/awesome#1458]
Output of `awesome --version`:
```
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • RandR 1.5 support: ✔
 • LGI version: 0.9.1
```

**How to reproduce the issue:**awesome v4.0 (Harder, Better, Faster, Stronger)
`mod4+r; ncmpcpp; Return`

**Actual result:**

90% of my cpu got eaten

**Expected result:**

ideal: seperate callback for spawning terminal-based and window-based programs
realistic: terminal-based programs don't spawn

**Comment by Elv13** [comment]
Knowing "before the fact" if a command starts a TUI or a X11 client isn't easy. You can add a prompt extension to enable the use of `:t` for spawning a command in a terminal, there is an example here:

https://awesomewm.org/apidoc/libraries/awful.prompt.html

Note that the other examples requires awesome git-master (they will be in the next point release), but not that one.

**Comment by psychon** [comment]
I reproduced this with `ncmpc`. First, `ncmpc` is the one in a busy loop. According to strace, it does a lot of:
```
rt_sigaction(SIGTSTP, {sa_handler=SIG_IGN, sa_mask=[], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7f0474ae0040}, {sa_handler=0x7f04757c2ef0, sa_mask=[], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7f0474ae0040}, 8) = 0
poll([{fd=0, events=POLLIN}], 1, 0)     = 1 ([{fd=0, revents=POLLIN}])
rt_sigaction(SIGTSTP, {sa_handler=0x7f04757c2ef0, sa_mask=[], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7f0474ae0040}, NULL, 8) = 0
poll([{fd=0, events=POLLIN}, {fd=3, events=POLLIN}, {fd=5, events=POLLIN}, {fd=7, events=POLLIN}], 4, -1) = 1 ([{fd=0, revents=POLLIN}])
rt_sigaction(SIGTSTP, {sa_handler=SIG_IGN, sa_mask=[], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7f0474ae0040}, {sa_handler=0x7f04757c2ef0, sa_mask=[], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7f0474ae0040}, 8) = 0
rt_sigaction(SIGTSTP, {sa_handler=0x7f04757c2ef0, sa_mask=[], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7f0474ae0040}, NULL, 8) = 0
poll([{fd=0, events=POLLIN}, {fd=3, events=POLLIN}, {fd=5, events=POLLIN}, {fd=7, events=POLLIN}], 4, -1) = 1 ([{fd=0, revents=POLLIN}])
read(0, "", 1)   
```
So, some useless setting of a signal handler and lots of polling that always reports stdin as readable, but actually reading from it results in EOF.

The same happens when running `ncmpc < /dev/null` in a terminal, so I am tempted to just blame ncmpc...?

**Comment by actionless** [comment]
i thought we had some binding like "alt"+"return" to run it in the terminal

**Comment by Elv13** [comment]
Not by default, but it's supported (by the prompt hook system)

**Comment by zhrts** [comment]
I should have mentioned, I don't mean that there is no way to spawn a console program in a terminal, but that there is an easy way to lag the hell out of a prompt, which could be considered to be a bug.

**Comment by blueyed** [comment]
@zhrts 
See the comment from Uli: https://github.com/awesomeWM/awesome/issues/1458#issuecomment-275034194.
There is not much we can do about it, can we?

Maybe some magic that does not disconnect stdin (or rather provides it), and when something is reading from it, kill the program and notify the user?! - but there be dragons.

**Comment by zhrts** [comment]
I reread what @psychon said about `/dev/null` and I can actually agree that the cpu usage is a ncmp* bug reproducable in ncmpcpp. I'll have my hand at adding an `autospawn` that tries to detect interactive programs, thank you for the explination.

**Comment by blueyed** [comment]
Please consider also reporting it to them.
