### ISSUE TITLE
Client maximize does not honor screen paddings

### ISSUE THREAD

**Issue by Bew78LesellB** [awesomeWM/awesome#1459]
Output of `awesome --version`:
```
awesome v4.0-97-g2c3aebc1 (Harder, Better, Faster, Stronger)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • RandR 1.5 support: ✔
 • LGI version: 0.9.1
```

**How to reproduce the issue:**

1. Set `screen.primary.paddings = 10`
2. Open a client on your primary screen
3. Maximize it

**Actual result:**

The client occupy all workarea

**Expected result:**

The client occupy all workarea minus the paddings

---

Maybe that's intentional, if it is, it's not documented

**Comment by Elv13** [comment]
It is easy to fix in ewmh.lua, simply adding `honor_padding = true` in the `request::geometry` handler for "maximize*" contexts would work. The old code also ignored padding, so this one is not a regression. I think it would make sense to honor the padding. @psychon @blueyed opinions?

**Comment by psychon** [comment]
If you want, feel free to make it do that. I'm wondering how long it will take someone to request the current behaviour again. ;-)

**Comment by actionless** [comment]
IMO maximize should honor screen padding, fullscreen shouldn't

**Comment by Bew78LesellB** [comment]
Maybe it's unrelated, but if `context == "fullscreen"` from the function arguments, the `context_mapper` table will change it to `"maximize"`

=> `honor_default` will never be false..
