### ISSUE TITLE
How to overwrite class

### ISSUE THREAD

**Issue by arkhan** [awesomeWM/awesome#1460]
awesome v4.0 (Harder, Better, Faster, Stronger)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • RandR 1.5 support: ✔
 • LGI version: 0.9.1

This rule now dont work:
``` lua
{ rule = { class = "URxvt", name = "Ranger" },
      callback = function (c)
         awful.client.property.set(c, "overwrite_class", "URxvt:Ranger")
      end
    },
```

Thanks

**Comment by Elv13** [comment]
Hello, I guess it's a Tyrannical question/issue (or I can merge it with the other issue you reported?). Please report it there, I will see what I can do
