### ISSUE TITLE
Reserving screen edge for conky

### ISSUE THREAD

**Issue by kdb424** [awesomeWM/awesome#1461]
I used to use a hack to reserve the bottom edge of the screen with an invisible wibox, but it would seem that awesome 4 is correctly bypassing my hack. I'm glad to see that it's working as intended, though I'm curious to see if there is a better way to handle this situation. I've tried the fixes on the wiki, but to no avail. I'm sure I could come up with something, but I'm wondering what's the most correct way so I don't have to always deal with hacks to get what I'd like.

Thank you for your time.

**Comment by Elv13** [comment]
You can add a padding, see https://awesomewm.org/apidoc/classes/screen.html#screen.padding or try to dock the conky client. Docking so far is half broken (to be fixed in the next point release), so padding is your best shot.

**Comment by kdb424** [comment]
Solved! No clue why I couldn't sort that one before, if it even existed. Thank you so much for your continued work.
