### ISSUE TITLE
hotkeys_popup queries values from beautiful during require() (before theme is loaded)

### ISSUE THREAD

**Issue by psychon** [awesomeWM/awesome#1468]
As noticed here: https://github.com/awesomeWM/awesome/issues/1417#issuecomment-275087215

* Do `require("awful.hotkeys_popup.keys.vim")`.
* This file ends with `hotkeys_popup.add_hotkeys(vim_keys)`.
* This function just does `return get_default_widget().add_hotkeys(...)`.
* `get_default_widget` notices that there is no widget yet and constructs one (`widget.new()`).
* This in turn queries values from `beautiful`: https://github.com/awesomeWM/awesome/blob/e2edabb8b18f55d2197895bcb44c9ee42d51496d/lib/awful/hotkeys_popup/widget.lua#L58

The problem is that there is a 99.999% chance that `beautiful.init` was not yet called and thus no theme loaded here. Thus, in total this means that `hotkeys_pop` should be ignoring the `border_width` and `bg_minimize` values that it is trying to query from `beautiful`.

**Comment by Oblomov** [comment]
I solved this locally by moving the require for beautiful at the very beginning of `rc.lua`, and this is a change that could be made to the default configuration file, even though this only hides a more general problem. A more robust solution would be to allow dynamic theme changing, and all widgets interested in theming could hook on a theme change signal and update all necessary fields automatically.

**Comment by actionless** [comment]
see `_load_widget_settings()` method, it now executed before showing hotkeys popup, not before creating it

**Comment by psychon** [comment]
So... is that a "yes, that's what I meant"? If so, feel free to close this.
