### ISSUE TITLE
nm-applet systray icon redraw

### ISSUE THREAD

**Issue by gregdel** [awesomeWM/awesome#1472]
I have an issue with the nm-applet systray icon, it seems like it's redrawing over itself...
I have no idea where this bug comes from. Any idea ?

```
greg@laptop:~
❯❯ awesome --version
awesome v4.0 (Harder, Better, Faster, Stronger)
 • Compiled against Lua 5.1.5 (running with Lua 5.1)
 • D-Bus support: ✔
 • execinfo support: ✔
 • RandR 1.5 support: ✔
 • LGI version: 0.9.1
```

systray icon:

![systray](https://cloud.githubusercontent.com/assets/1162110/22314472/eda755a6-e361-11e6-8990-e1dca2cfe6a1.png)

**Comment by Veratil** [comment]
As another user of nm-applet, I cannot say this has happened to me. The only difference between versions is I compiled against Lua 5.3.3 and running with 5.3 (and for some reason my awesome doesn't report RandR 1.5 support even though I clearly have it in code).

**Comment by psychon** [comment]
So, let's figure out what the difference between @gregdel and @Veratil is:
- Do you start awesome with `--no-argb`?
- Are you running a compositing manager (e.g. compton)?
- X.org version
- NM version?
- More version stuff (Which up to date version of which distro are you using?)

**Comment by Veratil** [comment]
* Do not start with `--no-argb`
* xcompmgr-1.1.7
* xorg-x11-server-1.18.4
* NetworkManager-1.2.4
* Fedora 24
* `theme.bg_systray  = theme.bg_normal`

**Comment by gregdel** [comment]
* I don't start awesome with ```--no-argb```
* I don't run compton or anything like it
* xorg: 1:7.7+18
* network-manager: 1.4.4-1
* network-manager-gnome: 1.4.2-1
* debian (testing): 9.0
* theme.bg_systray = theme.bg_normal

I tried to switch my icons to the (default) gnome icons, it didn't fix the issue.
I also tried to compile the latest ```master``` version, it didn't fix it either.

**Comment by actionless** [comment]
does it works as expected when you run awesome with `--no-argb`?

**Comment by gregdel** [comment]
Nope, the issue is still here even with this option :(

**Comment by gregdel** [comment]
![systray](https://cloud.githubusercontent.com/assets/1162110/22953192/74e02daa-f310-11e6-84b4-b33727e1eb66.png)
I have the same problem with i3wm !
I think we can say the issue is not awesome related and close it  (if you agree with my poor analysis) :)

Thank you all for your help.
