### ISSUE TITLE
My theme broke and I did not notice

### ISSUE THREAD

**Issue by psychon** [awesomeWM/awesome#1473]
Yesterday I `make package`-upgraded to latest git/master. Now my theme half broke:
```
2017-01-26 09:14:38 E: Failed to load '/usr/share/awesome/themes/default/taglist/squarew.png': Failed to open file '/usr/share/awesome/themes/default/taglist/squarew.png': No such file or directory
```
This was introduced in 316734a6812fc19b64a3617018ed14ea04f40cd5 where we made sure Lua code would still work, but forgot to look at existing themes using the files that are now gone.

Ignoring the "improvable" error message, what do we do about this? Do we ignore this or do we bring the files back for version 4.1?
Assigning to @Elv13 to answer the above question.

P.S.: What would be a good title for this issue?

**Comment by Elv13** [comment]
Apparently a comment was ignored when merging this https://github.com/awesomeWM/awesome/pull/1219#pullrequestreview-16660102

**Comment by psychon** [comment]
Well, it "works" in the "does not make the config fail to load"-sense...

**Comment by Elv13** [comment]
> Well, it "works" in the <s>"does not make the config fail to load"</s> "Doesn't cause a blackhole to swallow the world"-sense...

Fixed ;)

But seriously, to get 4.1 and 4.2 (and whatever comes after that) into stable distributions, "doesn't crash" is not enough. Not that I *like* wasting time on backward compatibility. No more than I like writing tests and documentation. However, as stated countless times, the 4.0 development cycle was a disaster that cost us a lot of users and we have to do better this time. That include not using "breaking the API" as an excuse for regressions. If we go down that path again, this means long (4 **years**) delays to get fixes and features to the userbase.

**Comment by actionless** [comment]
@Elv13 your comment was about xresources theme, not default one :)

my bad, i wasn't realizing what it could happen in that way, i was trying to keep backward compatibility for the themes like this:
https://github.com/actionless/awesome_config/blob/devel/themes/gtk/theme.lua#L273
