### ISSUE TITLE
Unable to move clips around in FlowBlade Movie Editor

### ISSUE THREAD

**Issue by kacperski1** [awesomeWM/awesome#1479]
Output of `awesome --version`:

awesome v4.0 (Harder, Better, Faster, Stronger)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • RandR 1.5 support: ✔
 • LGI version: 0.9.1

**How to reproduce the issue:**

1. Create a new project in [FlowBlade Movie Editor](https://github.com/jliljebl/flowblade),

2. Add some clips to the project (can be anything),

3. Try to move clips around the timeline.

**Actual result:**

Sometimes everything works correctly, but most of the time instead of, well, clips moving around as expected, awesome starts spawning file icons at mouse position instead. 
This bug only happens with awesome window manager and, [according to FlowBlade developers](https://github.com/jliljebl/flowblade/blob/master/flowblade-trunk/docs/KNOWN_ISSUES.md), cannot be fixed in the program itself. 

"The problem causing the bug is that awesome fires 'leave-notify-event' signals even when mouse has not left the timeline area." (quoting the FlowBlade devs)

**Expected result:**

Clips should be moving around the timeline.

**Comment by blueyed** [comment]
Can you try it with Git master, please?

**Comment by psychon** [comment]
Sigh. X11. Remove `awful.button({ }, 1, function (c) client.focus = c; c:raise() end),` from `clientbuttons`  and this will work (but focusing clients by mouse click will stop working).

**Comment by kacperski1** [comment]
> Can you try it with Git master, please?

Tried it with awesome v4.0-165-ga1a5e18b, no change.

> Sigh. X11. Remove awful.button({ }, 1, function (c) client.focus = c; c:raise() end), from clientbuttons and this will work (but focusing clients by mouse click will stop working).

This hacky solution works, would be great to keep the client raise functionality though.

**Comment by psychon** [comment]
Some X11 explanation: Titlebars work by creating an own window and reparenting the window that (for example) Firefox into this window. The titlebar-window is a bit larger and this extra space can be used to draw titlebars.

What we do for clientbuttons: We grab the input event on our titlebar-window. Thus, the input focus shortly switches to the titlebar-window for the click event, which is why the "real window" gets informed that the input focus kind-of-shortly moved elsewhere.

What to do about this: Dunno.

**Comment by blueyed** [comment]
Is / can this be short-circuited / skipped when not using titlebars?

**Comment by psychon** [comment]
I don't know. I think there was some kind of conflict when grabbing things directly on the client window, but I am not sure (only one program can have a given grab, if others try the same grab they get an X11 error). I don't remember what ICCCM has to say about this (I bet we are not allowed any grabs).

**Comment by blueyed** [comment]
(it was just a thought since it sounded like using titlebars would trigger some restrictions, which is apparently not the case then)

**Comment by actionless** [comment]
@kacperski1 

try insvestigate with `xprop` name or class of the window with which you are experiencing this problem,

and replace

```lua
awful.button({ }, 1, function (c) client.focus = c; c:raise() end),
```

to


```lua
awful.button({ }, 1, function (c)
  if c.class == "FlowBladeWindow" then return end
  client.focus = c;
  c:raise()
end),
```

**Comment by psychon** [comment]
Duplicate: #1658

**Comment by dtapuska** [comment]
We removed listening for NotifyVirtual as a mouse leave event in Chrome yesterday. I believe this fixes it. See https://chromium.googlesource.com/chromium/src/+/955f4364ffa5c275f04cb3c2d19f7ac63f7d8320
Can someone try a chromium build with that change?

**Comment by gruenlich** [comment]
This is also affecting Blender, causing some erratic changes in views, zoom levels, and other hard to quantify ways.  Using the workaround suggested by @psychon makes everything work as expected, except, well, clicks raising the window.

**Comment by psychon** [comment]
Could someone test if #1724 really fixes this issue?
