### ISSUE TITLE
save windows positions and restore them

### ISSUE THREAD

**Issue by padosucman** [awesomeWM/awesome#1485]
How to save windows positions and restore them after closing?

**Comment by Elv13** [comment]
For floating clients, @mindeunix has a module called [clientdb](https://github.com/mindeunix/clientdb/). For tiled layouts, Awesome 4 doesn't officially support it. I have a "patched" version that supports it, but it is not ready for general adoption and recommended only for advanced users.

**Comment by padosucman** [comment]
With gratitude, Emmanuel!
