### ISSUE TITLE
Make a client decoration dependent on keyboard layout (question)

### ISSUE THREAD

**Issue by sudo-nice** [awesomeWM/awesome#1491]
Hi!

I prefer not to use wibar, so used to display a client keyboard layout with this piece of code:
```lua
dbus.request_name("session", "ru.gentoo.kbdd")
dbus.add_match("session", "interface='ru.gentoo.kbdd',member='layoutChanged'")
dbus.connect_signal("ru.gentoo.kbdd",
  function(...)
    local data = {...}
    local layout = data[2]
    if layout == 0 then
      awful.client.unmark() -- DEPRECATED
    else
      awful.client.mark()   -- DEPRECATED
    end
  end)

```
...and then catch the signals:
```lua
-- Marked

client.connect_signal("marked",
  function(c)
    c.border_color = beautiful.border_marked
  end)

-- Unmarked


client.connect_signal("unmarked",
  function(c)
    c.border_color = beautiful.border_focus
  end)
```

But since the `awful.client.mark` and `awful.client.unmark` are deprecated, could you please, advice me the better approach? It seemed like I could utilize `wibox.widget.keyboardlayout` somehow, but I can't find the way.

**Comment by sudo-nice** [comment]
Found out, I can use `client.focus.marked = (false|true)`.

**Comment by blueyed** [comment]
@sudo-nice 
Glad you figured it out.
Please consider doing a PR for the doc to improve it, e.g. by adding a sentence/reference.

**Comment by sudo-nice** [comment]
@blueyed 
Please, check https://github.com/awesomeWM/awesome/pull/1518
