### ISSUE TITLE
Can't restore previous tag after ruled switchtotag = true

### ISSUE THREAD

**Issue by sudo-nice** [awesomeWM/awesome#1493]
Output of `awesome --version`:

awesome v4.0 (Harder, Better, Faster, Stronger)
 • Compiled against Lua 5.1.5 (running with Lua 5.1)
 • D-Bus support: ✔
 • execinfo support: ✔
 • RandR 1.5 support: ✔
 • LGI version: 0.9.1

**How to reproduce the issue:**

1. Had the rule:
```lua
{ rule = { class = "Gimp" },
properties = { tag = "9", switchtotag = true } },
```
2. Had the hotkey:
```lua
awful.key({ modkey,           }, "Escape", awful.tag.history.restore,
```
3. Spawn Gimp  (*Gimp is placed on tag 9, as expected*)
4. Press <kbd>Mod4</kbd>+<kbd>Esc</kbd> to switch back to previous tag.

**Actual result:**

I stay on the Gimp tag.

**Expected result:**

I should get back to the previous tag (the tag a was before Gimp spawned).

**Notes:**

I use one monitor.
I have no problem with restoring previous tag when switch them manually, like <kbd>Mod4</kbd>+<kbd>9</kbd>.
I've tried the default rc.lua (to exclude possible interaction with other my stuff there), but without success.

**Comment by psychon** [comment]
This can be fixed by adding `c.screen:emit_signal("tag::history::update")` at the end of `awful.rules.delayed_properties.switchtotag`, but what the heck is that function doing? Why does it mess with the `selected` property directly in some complicated fashion? How about replacing all of that with `awful.tag.viewmore(c:tags(), c.screen)`?

**Comment by sudo-nice** [comment]
@psychon, could you, please elaborate? I've added to my rc.lua just after `awful.rules.rules = { all_my_rules_here }`:
```lua
awful.rules.delayed_properties.switchtotag = {
	c.screen:emit_signal("tag::history::update")
}
```
but got `attempt to index global 'c' (a nil value)` error. Should I place it somewhere else?

**Comment by psychon** [comment]
It needs to be placed here: https://github.com/awesomeWM/awesome/blob/420f672661cc98421b19242db41b83b8ecf51b33/lib/awful/rules.lua#L304

**Comment by sudo-nice** [comment]
Thanks a lot!

**Comment by raphaelfournier** [comment]
I had a similar problem, I can confirm that the proposed solution helps in restoring the desired behaviour. `c.screen:emit_signal("tag::history::update")` should definitely be included in awesome/lib/awful/rules.lua at Line 304.
