### ISSUE TITLE
Window Position Via `-geometry` Not Always Honored

### ISSUE THREAD

**Issue by ewhac** [awesomeWM/awesome#1500]
Output of `awesome --version`:

```
awesome v4.0 (Harder, Better, Faster, Stronger)
 • Compiled against Lua 5.1.5 (running with Lua 5.1)
 • D-Bus support: ✔
 • execinfo support: ✔
 • RandR 1.5 support: ✔
 • LGI version: 0.9.1
```

**How to reproduce the issue:**

With the current screen tag's layout set to floating mode:  If you launch a program with a `-geometry` argument, the window is not always placed where you specify.  If Awesome determines the new window occludes an existing window, Awesome will reposition the window.

On an empty screen tag set to floating layout, run the following command:

    xterm -geometry +100+100

Since there are no other windows, the xterm will be placed with the upper-left corner at (100,100).

Now, run the same command again.  Awesome will position the new xterm adjacent to the existing one, with the top edge flush with the wibar.  The expected result is to place the new window exactly on top of the previous one.

**Comment by Elv13** [comment]
This is a feature, see:

```lua
    { rule = { },
      properties = { border_width = beautiful.border_width,
                     border_color = beautiful.border_normal,
                     focus = awful.client.focus.filter,
                     raise = true,
                     keys = clientkeys,
                     buttons = clientbuttons,
                     screen = awful.screen.preferred,
                     -- THIS ----\/----
                     placement = awful.placement.no_overlap+awful.placement.no_offscreen
     }
    },
```

Remove or change this if you want something else. You could also create a new rule to override the default rule. Clients obey the rules unless specified otherwise ;)
