### ISSUE TITLE
Layout box does not update when swapping tags

### ISSUE THREAD

**Issue by mphe** [awesomeWM/awesome#1503]
Output of `awesome --version`:

awesome v4.0 (Harder, Better, Faster, Stronger)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • RandR 1.5 support: ✔
 • LGI version: 0.9.1

**How to reproduce the issue:**

* Add a layoutbox widget

* Add this snippet to rc.lua (it preserves tags when adding and removing a screen at the same time with the same position and size).

```lua
tag.connect_signal("request::screen", function(t)
    for s in screen do
        if s ~= t.screen and
           s.geometry.x == t.screen.geometry.x and
           s.geometry.y == t.screen.geometry.y and
           s.geometry.width == t.screen.geometry.width and
           s.geometry.height == t.screen.geometry.height then
            local t2 = awful.tag.find_by_name(s, t.name)
            if t2 then
                t:swap(t2)
            else
                t.screen = s
            end
            return
        end
    end
end)
```

Then replace a display with another display of the same size and position. The tags of the previous screen will be swapped with the tags on the new screen.

**Actual result:**

The layoutbox doesn't update until switching tags. It still shows the layout of the selected tag on the new screen, before it was swapped.

**Expected result:**

The layoutbox would update accordingly to the layout of the selected tag.

**Example**

Display A: 0, 0, 1920x1080 (active)
Display B: 0, 0, 1920x1080 (inactive)

Tag 9 is selected and has the corner layout. Every other tag has the tile layout (default).
Layoutbox shows corner layout.

`xrandr --output Display-A --off --output Display-B --auto`

Tag 9 is selected and has the corner layout. Every other tag has the tile layout.
Layoutbox shows tile layout.

**Comment by Elv13** [comment]
The problem is much more simple than that: the layoutbox code currently doesn't handle this at all. There is literally no code to track screen changes, so it doesn't.

**Comment by psychon** [comment]
Ok. That's (almost) easy. @Elv13 Any way to get the old screen in a tag's `property::screen` signal? Otherwise, the code will have to update all layoutboxes when a tag is moved to another screen (which wouldn't be bad either, because nothing *actually* changes so the update would be cheap).

**Comment by Elv13** [comment]
So far, no:

```lua
function tag.setproperty(_tag, prop, value)
    if not _tag.data.awful_tag_properties then
        _tag.data.awful_tag_properties = {}
    end

    if _tag.data.awful_tag_properties[prop] ~= value then
        _tag.data.awful_tag_properties[prop] = value
        _tag:emit_signal("property::" .. prop)
    end
end
```

This could be changed to

```lua
function tag.setproperty(_tag, prop, value)
    if not _tag.data.awful_tag_properties then
        _tag.data.awful_tag_properties = {}
    end

    local old = _tag.data.awful_tag_properties[prop]
    if old ~= value then
        _tag.data.awful_tag_properties[prop] = value
        _tag:emit_signal("property::" .. prop, value, old)
    end
end
```

But this is a "large" change. Someone somewhere is probably using a signal handler with a complex signature (re-used in other code?) and will be affected by this... At the same time, it isn't *really* an API break. So it could be done in 4.1. At the same time, if the tag is selected and changes screen, looping all layoutboxes doesn't seem such a problem. It is a very "rare", onetime event and the number of screens is usually low.
