### ISSUE TITLE
awful.tag.add throws me out of tags on awesome.restart

### ISSUE THREAD

**Issue by sudo-nice** [awesomeWM/awesome#1509]
Output of `awesome --version`:
```
awesome v4.0 (Harder, Better, Faster, Stronger)
 • Compiled against Lua 5.1.5 (running with Lua 5.1)
 • D-Bus support: ✔
 • execinfo support: ✔
 • RandR 1.5 support: ✔
 • LGI version: 0.9.1
```
**How to reproduce the issue:**

1. Edit the default rc.lua and replace the line:
`awful.tag({ "1", "2", "3", "4", "5", "6", "7", "8", "9" }, s, awful.layout.layouts[1])`

with these lines:
```
awful.tag.add("1")
awful.tag.add("2")
awful.tag.add("3")
```
2. Restart awesome with the hotkey `awful.key({ modkey, "Control" }, "r", awesome.restart,`

**Actual result:**

After restart I find myself somewhere out of any tag: I see the wallpaper and the wibar, but non of my clients opened on any tag. If I spawn a client from this current transcendental state, I wouldn't see it, but would note the urgent client appears on all tags:
![scr](http://i.imgur.com/iN22xxJ.png)

**Expected result:**

After restart I should find myself on any actual tag.

**Comment by psychon** [comment]
You have no tag selected. For example, you could replace `awful.tag.add("1")` with `awful.tag.add("1").selected = true` in your config.

The remaining part of the issue sounds like the taglist is not updated...?

**Comment by sudo-nice** [comment]
>You have no tag selected. For example, you could replace awful.tag.add("1") with awful.tag.add("1").selected = true in your config.

You are completely right, that helped, thank you.

>The remaining part of the issue sounds like the taglist is not updated...?

All that was caused by the first part, and there is no problem any more.

**Comment by psychon** [comment]
Ah, sorry. I misunderstood your description.
Yes, I think some code in awful makes a client sticky (visible on all tags) if currently no tag is selected. Otherwise the client would be lost. After re-reading this matches your description of the problem.

**Comment by sudo-nice** [comment]
I see, thank you for the info.

**Comment by Elv13** [comment]
Ref https://github.com/awesomeWM/awesome/issues/1373
