### ISSUE TITLE
The only master should keep its place (suggestion)

### ISSUE THREAD

**Issue by sudo-nice** [awesomeWM/awesome#1512]
Output of `awesome --version`:
```
awesome v4.0 (Harder, Better, Faster, Stronger)
 • Compiled against Lua 5.1.5 (running with Lua 5.1)
 • D-Bus support: ✔
 • execinfo support: ✔
 • RandR 1.5 support: ✔
 • LGI version: 0.9.1
```
**How to reproduce the issue:**

*Let's assume we use the default rc.lua*

1. Add a helper function to rc.lua:
```lua
local function add_tag()
	awful.tag.add("NewTag",{
			screen              = awful.screen.focused(),
			layout              = awful.layout.suit.tile,
			master_fill_policy  = "master_width_factor",
		}):view_only()
end
```
2. Add a global keybinding to rc.lua: `awful.key({ modkey }, "a", add_tag,`
3. Apply changes and hit <kbd>modkey</kbd>+<kbd>a</kbd>
4. Run any non-floating client.

**Actual result:**

The client has spawned horizontally centered.

**Expected result:**

The clients has placed on the left side (where it would be if any other slave client was there on the tag).

**Comment by Elv13** [comment]
That would break the API behavior, so no. But you could implement a new `master_fill_policy` to do this.

However I have to say that I don't like the current layout system and it doesn't scale very well when it comes to adding new features. I have an alternate layout systems that makes this trivial to implement (but master_fill_policy is currently ignored). If you wish to play with more flexible layout, the code is in #644.

**Comment by sudo-nice** [comment]
I see, thank you.
>But you could implement a new master_fill_policy to do this.

I'm not even close advanced to do it, so let's things be as they are. :smile:
