### ISSUE TITLE
wibars in 4.0 cover each other, inconsistent doc

### ISSUE THREAD

**Issue by lukash** [awesomeWM/awesome#1523]
Output of `awesome --version`:
```
awesome devel (Harder, Better, Faster, Stronger)
 • Compiled against Lua 5.1.5 (running with Lua 5.1)
 • D-Bus support: ✔
 • execinfo support: ✔
 • RandR 1.5 support: ✔
 • LGI version: 0.9.0
```

Sup guys 😄 

In 4.0 when you have two wibars that meet in the corner, they cover each other. Something along these lines:
```lua
    local panel1 = awful.wibar{position = "left", screen = s, width = 64}
    panel1:setup{
        layout = wibox.layout.align.vertical,
        wibox.widget.textbox("FOO")
    }

    local panel2 = awful.wibar{position = "top", screen = s, height = 15}
    panel2:setup{
        widget = wibox.widget.textbox("BAR")
    }
```

It used to place `panel2` with an offset so that it wouldn't cover `panel1`. I've tried to make it work by passing some extra stuff to the 'constructor' to no avail.

EDIT: I've just found out it works if you switch the order of defining the panels, ie. the top one first. The outcome is obviously not the same though.

- The doc mentions `args.x` and `args.y`, but they don't seem to work and I don't see them used in code at first look.

- `align` is mentioned in the 'constructor', but it is not in `arg`, might be a good idea to formulate better how to set it.

**Comment by copycat-killer** [comment]
Can you post a mockup or screenshot of the desired result?

Anyway, you can also use just a `wibox` for the second panel instead of a 'wibar`.

This is an [example](https://github.com/copycat-killer/awesome-copycats/blob/master/themes/vertex/theme.lua#L398-L411).

**Comment by lukash** [comment]
A screenshot of the way it's supposed to look like? That should be given... by the implementation I suppose, although I'm not sure up to how far it's intended behaviour. I'm not entirely sure how it should work, I only know how it worked in master from many months ago. If I didn't miss something, it's not documented.

The way it used to work for me was the first wibar took all space from corner to corner and the second wibar didn't go into the corner in which the two wibars meet but stretched only up to the first wibar's border. I find this quite wonky because the outcome depends solely on the order of creating the wibars. Expecially now with the `connect_for_each_screen`, which doesn't have a guaranteed order of calling I think.

I find the issue quite clear and don't wanna spend time mocking it up... If you want to look into it, just run the example I posted. You should see "FOO" and "BAR" right next to each other (the second wibar does not cover the first one). Instead, you'll only see "BAR".

I'd look into it myself (and might, when I have the time), but as I said I'm not actually sure of the correct way this should be done. Perhaps there should now be a better way of specifying this. If someone stepped in with some clarification, that would be very welcome. :)

**Comment by lukash** [comment]
Oh, and thanks for the wibox tip. I might try it, although it's just a workaround and I've worked around the issue for now already. Also I'm afraid it might not decrease the working area and windows might stretch under the wibox...?

**Comment by psychon** [comment]
@Elv13 thoughts? Sounds like before switching to `awful.placement` "something was done differently".

**Comment by Elv13** [comment]
apparently they don't overlap, but I could reproduce a case where the vertical height is mis-calculated

![pick8](https://cloud.githubusercontent.com/assets/340384/22870951/6b6fac06-f17a-11e6-881a-36a767e7f3ad.png)

There should be a "BAR" label at the bottom left, but it's under the green wibar. However, the top isn't an overlap. The red bar is `below` and the green one `ontop`.

**Comment by Elv13** [comment]
@lukash Can you try https://gist.github.com/Elv13/bc896e319c8176cceae1d260ef98d578

I am not sure what I found is the same bug as you have. The code examples you gave works fine here.

**Comment by lukash** [comment]
Pull request would be easier, but I tested the patch meanwhile... :) It does fix the overlap issue for me, so now the wibars no longer cover each other.

However, now the top wibar is always the one that "gets into the corner", no matter the order. It used to work so that the left bar "got into the corner", I supposed it was due to it being created first, but I guess I never tried it the other way.

**Comment by Elv13** [comment]
I already made a PR ;). Right now, the top and bottom wibars have the priority. The creation order is not taken into account. Is there a good reason to have left/right wibars that have priority over top/bottom ones? I played with Qt/GTK toolbars and they seem to behave like that.

**Comment by lukash** [comment]
Sure there is :) I'd say it's obvious, but maybe not to everybody... Consider my screenshot:

![screenshot](https://cloud.githubusercontent.com/assets/135954/22905482/a9cf1bd2-f240-11e6-8315-262f237a4a2a.jpg)

You can see the date in the top left corner (yes, it's a date, please disregard the chinese :D). Now it is actually part of the top bar, since it happens to have the same height, so I can put it there. But I hope you can see it belongs more to the side bar and if I wanted to have something higher in it's place (say the taglist - the two lines of letters - Q W E R A S D F), there is now no way to achive that.

**Comment by Elv13** [comment]
Umm, ok... The reason why I don't want "random" order because when position is changed (ei. you implement wibars drag&drop), then the result is unpredictable. Major toolkits seems to also do that, so I didn't invent anything here.

So, if you want this, loop at the code

```lua
    -- Avoid overlapping wibars
    if position == "left" or position == "right" then
        margins.top    = get_margin(w, "top"   )
        margins.bottom = get_margin(w, "bottom")
    end
```

In `wibar.lua`. If you want to add a new beautiful option[1] to behave differently, feel free to open a pull request for it. I don't have a lot of time right now. I fixed the overlapping issue because it was a clear bug. This however, is more like a "new feature" in the sense the current behavior is done on purpose.

[1] It needs a better name, but something like `wibar_expand_policy == "height"`
