### ISSUE TITLE
awful rules not applied

### ISSUE THREAD

**Issue by t0m5k1** [awesomeWM/awesome#1524]
awesome v4.0 (Harder, Better, Faster, Stronger)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • RandR 1.5 support: ✔
 • LGI version: 0.9.1

After upgrading I replaced:

	{ rule = { class = "Firefox" },
			properties = { tag = tags[1][6] } },
with:
	{ rule = { class = "Firefox" }, properties = { tag = 6 } },

However when I start Firefox it is not being placed on tag 6!
I have tried the following variants of "properties" but they also fail:

properties = { tag = screen[1].tags[6] } },
properties = { screen = 1, tag = "6" } },
properties = { tag = " " } },

**Comment by actionless** [comment]
try `{    tag=screen.primary.tags[6] }`

**Comment by psychon** [comment]
> try { tag=screen.primary.tags[6] }

I would propose instead: `{ tag = function() return screen.primary.tags[6] end }`, but I do not think that this really would make a difference here...

**Comment by t0m5k1** [comment]
thnx psychon I'll give it a try and report back

**Comment by t0m5k1** [comment]
The following one suggested by actionless does nothing:
{ tag=screen.primary.tags[6] }},
using :
{ tag = function() return screen.primary.tags[6] end }}, 
seems to work!

So does this give you a clue as to what is wrong?
I see no one else has reported this, so I think I'll drop in a default rc.lua & just re-try all the variants to confirm if this is a quirk of my config.

**Comment by t0m5k1** [comment]
using the xdg default rc.lua with these:
     { rule = { class = "Firefox" },
       properties = { screen = 1, tag = "8" } },
     { rule = { class = "Chromium" },
       properties = { screen = 1, tag = "8" } },
     { rule = { instance = "crx_hnpfjngllnobngcgfapefoaidbinmjnm" },
       properties = { screen = 1, tag = "5" } },

they work perfectly, think I'll just rebuild my config based of this default config.
Thanks for all the pointers.

**Comment by Elv13** [comment]
Added to the "to better document" list, closing this to reduce the number of open issues
