### ISSUE TITLE
second wibar breaks after removing a screen

### ISSUE THREAD

**Issue by lukash** [awesomeWM/awesome#1530]
Output of `awesome --version`:
```
awesome devel (Harder, Better, Faster, Stronger)
 • Compiled against Lua 5.1.5 (running with Lua 5.1)
 • D-Bus support: ✔
 • execinfo support: ✔
 • RandR 1.5 support: ✔
 • LGI version: 0.9.0
```

With two wibars on each screen, when I remove one screen through `xrandr`, on the remaining screen the wibar that was added as second ends up in some weird half-updated state and never updates again. If I flip the order of initialization of the wibars, it's always the second one.

The same snippet as in #1523 should reproduce, although some dynamic content may be needed to show the issue.

**Comment by Veratil** [comment]
This has been fixed with #1501
