### ISSUE TITLE
awful.spawn.easy_async Doesn't work properly

### ISSUE THREAD

**Issue by geripgeri** [awesomeWM/awesome#1532]
Output of `awesome --version`:
```
awesome v4.0 (Harder, Better, Faster, Stronger)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • RandR 1.5 support: ✔
 • LGI version: 0.9.1
```

**How to reproduce the issue:**
Before version 4.0 the command  `"TZ=Europe/London date +'%R'"` returns with correct data, after 4.0 there is no return, no stdout, stderr, reason, exit_code nothing. This also happens to other complex commands.

For example:

```
awful.spawn.easy_async("TZ=Europe/London date +'%R'", function(stdout, stderr, reason, exit_code)
    naughty.notify { text = stdout .. " , " .. stderr .. " , " .. reason .. " , " .. exit_code }
end)
```

**Actual result:**

```
nothing
```

**Expected result:**

```
20:38
```

**Comment by Elv13** [comment]
You need a shell. Does:

```
awful.spawn.easy_async({'bash', '-c, "TZ=Europe/London date +'%R'"}, function(stdout, stderr, reason, exit_code)
    naughty.notify { text = stdout .. " , " .. stderr .. " , " .. reason .. " , " .. exit_code }
end)
```

helps?

**Comment by geripgeri** [comment]
@Elv13 It's working! Thank you :)

**Comment by Elv13** [comment]
@blueyed Should we (read: you 😄) add an `easy_async_with_shell`?

**Comment by blueyed** [comment]
I think https://github.com/awesomeWM/awesome/pull/1001 is still related in this regard.

**Comment by psychon** [comment]
(Oh and: No one checks the return value of anything! We should try not to add too many more of these)

**Comment by psychon** [comment]
Even `awful.widget.watch` gets this wrong...

**Comment by geripgeri** [comment]
Should I reopen this issue?

**Comment by actionless** [comment]
i think we could either wrap command inside sh/bash -c as it was proposed already or we could check (probably via glib) what file is exists and executable

**Comment by blueyed** [comment]
@geripgeri @Elv13 
`env TZ=Europe/London date +'%R'` should also work.

**Comment by geripgeri** [comment]
@blueyed  Thanks with env it's working, but as I mentioned, I have other "complex" commands with wrong outputs, these also work with  @Elv13's workaround, but all of my commands were working before v4.0.

**Comment by psychon** [comment]
There is no `easy_async` before v4.0, what did you use instead?

**Comment by geripgeri** [comment]
To be completely accurate I'm using [Lain](https://github.com/copycat-killer/lain)

As I see this is the point when it switched from `async.request` to `easy_async`
https://github.com/copycat-killer/lain/commit/0279482eeb5867f49b4efc83d591393f9c3d0adb#diff-4a31ac93a3c6a403a2d5060cb45d0e9aL28

**Comment by psychon** [comment]
Well, I would say that's Lain's doing then. Previously it started the command inside of a shell itself: https://github.com/copycat-killer/lain/commit/0279482eeb5867f49b4efc83d591393f9c3d0adb#diff-2a2b10ddc43a283aee4c27e53df00f78L56 (and did a poor job of trying to quote its input: https://github.com/copycat-killer/lain/commit/0279482eeb5867f49b4efc83d591393f9c3d0adb#diff-2a2b10ddc43a283aee4c27e53df00f78L48 )

**Comment by geripgeri** [comment]
Just to be clear, where is the problem? On Lain's site or at Awesome wv's site? If it's at lain's site I'll report an issue and relate it to this issue.

**Comment by psychon** [comment]
Well, it is lain which changed behaviour. Previously, it would send the command for the `abase` widget (whatever that is) through a shell. Now it switched to another function provided by awesome which does not execute its argument through a shell, but executes it directly.
I'd say that awesome's function works as documented (perhaps we should add an `easy_async_with_shell` command for consistency?).

**Comment by geripgeri** [comment]
I think that's a good idea, I'll report the issue to Lain, thank you guys for the help!
