### ISSUE TITLE
How to get solid background?

### ISSUE THREAD

**Issue by MaxG87** [awesomeWM/awesome#1535]
I'm using the version of AwesomeWM in Ubuntu 16.04 (3.5.6-1build1). I'd like to configure a solid background colour, i.e. a single RGB value that will fill all the screen. This is to save network traffic in an office with a central login server.

The best documentation about how to achieve this I found so far is

    https://awesomewm.org/doc/api/documentation/16-using-cairo.md.html

However, it seems that this documentation is not valid for the aforementioned version. Some runtime errors occur complaining about wrong parameters.

Could anyone explain how to achieve a solid background colour, please?

**Comment by Elv13** [comment]
First of all, please watch out, both the link you gave and the following one are for Awesome 4.0 and may differ from the 3.5 API in many ways.

Solid colors, from Cairo point of view (also applies to Awesome) is a simple "pattern" in the sense that it is "repeat this colored pixel forever". Gradient and "tiled pixmaps" are also pattern. So the `gears.wallpaper.set` function accept patterns as inputs

https://awesomewm.org/apidoc/libraries/gears.wallpaper.html#set

You can find examples of solid color wallpaper in the [integration tests](https://github.com/awesomeWM/awesome/blob/master/tests/test-wallpaper.lua).

The #1373 issue already exist and list this is underdocumented.

**Comment by MaxG87** [comment]
Thank you for the immediate reply.

Since `gears.wallpaper.set` does not accept a screen number, I guess one has to call `gears.wallpaper.prepare_context` beforehand?

Is the documentatio/API for AwesomeWM 3.5.6 still available somewhere?

**Comment by Elv13** [comment]
> Is the documentatio/API for AwesomeWM 3.5.6 still available somewhere?

Hopefully on your system in `/usr/share/doc` unless Debian/Ubuntu decided to remove it.

> Since gears.wallpaper.set does not accept a screen number, I guess one has to call gears.wallpaper.prepare_context beforehand?

I am not the wallpaper expert here, so I will settle for a cheap trick. Using a 1x1 transparent surface (you linked how to do that in your first message), you can use the `centered` function.

**Comment by MaxG87** [comment]
Just for reference I want to post my solution here. Actually it's quite simple but I hope it helps someone else. It's tested for Awesome 3.5.6.

Instead of centering a transparent background over a background colour, I'm tiling a 1x1 pixel pattern over the whole screen. This way I avoid dealing with transparencies which I could not set up here.

    local img = cairo.ImageSurface.create(cairo.Format.ARGB32, 1, 1)
    local cr = cairo.Context(img)
    cr:set_source(gears.color("#dd3333"))
    cr:rectangle(0, 0, 1, 1)
    cr:fill()
    gears.wallpaper.tiled(img, 1)

**Comment by psychon** [comment]
Doesn't just `gears.wallpaper.set("#dd3333")` work already? (`set` calls `gears.color` to handle string arguments and `gears.color` will basically do `require("lgi").cairo.Pattern.create_rgb((13*16+13)/255, (3*16+3)/255, (3*16+3)/255, 1)` for the argument you give)

**Comment by Elv13** [comment]
> Doesn't just gears.wallpaper.set("#dd3333") work already? 

Yes, it does
