### ISSUE TITLE
Calculate geometry of a ruled client even without switchtotag = true

### ISSUE THREAD

**Issue by sudo-nice** [awesomeWM/awesome#1537]
Output of `awesome --version`:
```
awesome v4.0 (Harder, Better, Faster, Stronger)
 • Compiled against Lua 5.1.5 (running with Lua 5.1)
 • D-Bus support: ✔
 • execinfo support: ✔
 • RandR 1.5 support: ✔
 • LGI version: 0.9.1
```
**How to reproduce the issue:**

I have a rule to place the terminal client on a certain tag. If I set `switchtotag = true` with my rule, a get this:

![scr2](http://i.imgur.com/4e1QSf4.png)

But if I have `switchtotag = false`, I get this:

![scr1](http://i.imgur.com/bz4gXrc.png)

Don't you think, it should be always like the upper picture, regardless of `switchtotag` value?

If the answer is "No", could you, please, suggest any solution?
Currently I'm looking at new `extra_properties`, `high_priority_properties`, `delayed_properties`, but don't know how to approach it.

**Comment by psychon** [comment]
> I have a rule to place the terminal client on a certain tag.

Could you show us the full rule? Which terminal are you using? What layout is the target tag using?
Right now I have no idea what is going on, so any further hints would be welcome.

**Comment by sudo-nice** [comment]
Sure, sorry.

The tag:
```
awful.tag.add("3", {
		layout              = awful.layout.suit.tile,
		master_width_factor = 0.50,
	})
```
The rule:
```
{ rule = { instance = "TAG_3" },
properties = { tag = "3", switchtotag = true } },
```
The terminal is urxvt (urxvtc, exactly).

**Comment by sudo-nice** [comment]
My guess, it happens due to the order of calculating the client geometry:

With `switchtotag = true`:
1. Switch to the new tag
2. Calculate geometry of the client
3. Create the clent
4. Handle the client according the current layout

With `switchtotag = false`:
1. Calculating the geometry of the client as it was for the current tag
2. Switch to new tag
3. Create the client (with wrong geometry initially passed to the client)
4. Handle the client according the current layout

Once again, I don't know what exactly happens, this just could be a possible scenario.

**Comment by Elv13** [comment]
Can you post the result of:

    awesome-client 'ret = {};for k,t in ipairs(root.tags()) do table.insert(ret, {t.name, t.master_width_factor, t.column_count}) end; return require("gears.debug").dump_return(ret)'

**Comment by sudo-nice** [comment]
string "table: 0x55612b7267b0
  1 : table: 0x55612bcb1fd0
    1 : 1 (string)
    2 : 0.55 (number)
    3 : 1 (number)
  2 : table: 0x55612bd23b30
    1 : 2 (string)
    2 : 0.5 (number)
    3 : 1 (number)
  3 : table: 0x55612bc855c0
    1 : 3 (string)
    2 : 0.5 (number)
    3 : 1 (number)
  4 : table: 0x55612b844140
    1 : 4 (string)
    2 : 0.5 (number)
    3 : 1 (number)
  5 : table: 0x55612bc6a080
    1 : 5 (string)
    2 : 0.5 (number)
    3 : 1 (number)
  6 : table: 0x55612b8440f0
    1 : 6 (string)
    2 : 0.5 (number)
    3 : 1 (number)
  7 : table: 0x55612bcdc070
    1 : 7 (string)
    2 : 0.5 (number)
    3 : 1 (number)
  8 : table: 0x55612bb903b0
    1 : 8 (string)
    2 : 0.5 (number)
    3 : 1 (number)
  9 : table: 0x55612ba96c70
    1 : 9 (string)
    2 : 0.5 (number)
    3 : 1 (number)"

**Comment by sudo-nice** [comment]
Please, note, there is **only one client** on both my screenshots. It's nvim (vim) with two files opened with it.

**Comment by Elv13** [comment]
Ah, that's an important detail ;). Hard to know given you disabled the wibar and talk about `master_width_factor`. Then the answer is much more obvious. The client geometry is set by the layout `arrange` function when a tag is displayed. This is of course done for quite obvious reasons (performance).

You could force the arrange on hidden tags, but this will break use cases such as client selected on multiple tags. Otherwise, the bug is in neovim not redistributing the space on resize.

**Comment by sudo-nice** [comment]
>Ah, that's an important detail

I should highlight it at the very start, sorry.

>You could force the arrange on hidden tags

Is it possible to force the arrange for a certain hidden tag only? Should I patch sources for that?

BTW, I've compared the output of `xprop` for the client with `switchtotag = true` and `switchtotag = false`, so the only difference is the last one has additional line: `_NET_WM_STATE(ATOM) = ` (yes, it's empty). I'm not sure it means something significant, though.

**Comment by sudo-nice** [comment]
I beleive, I can think out something, on my own, please don't bother with the answer.
Thank you for the help!

**Comment by actionless** [comment]
> Otherwise, the bug is in neovim not redistributing the space on resize.

just as a sidenote, in vim i have the same behavior
