### ISSUE TITLE
How to use new API functions for setting keyboard layout

### ISSUE THREAD

**Issue by slaufmann** [awesomeWM/awesome#1546]
Hi,

as described in #967 it should now be possible to set the keyboard layout using new API functions like `xkb_set_layout_group`.
Could someone explain how this can be done because I just can't figure it out.

**Comment by Elv13** [comment]
Better use `setxkbmap` for 4.0. The line was removed from the final changelog version. You can set groups, but it isn't flexible enough to replace setxkbmap yet

**Comment by slaufmann** [comment]
Thanks, I'm gonna stick with 'setxkbmap' then.
