### ISSUE TITLE
menubar/init.lua:  `count_file` not closed.

### ISSUE THREAD

**Issue by ewhac** [awesomeWM/awesome#1548]
Output of `awesome --version`:

```
awesome v4.0 (Harder, Better, Faster, Stronger)
 • Compiled against Lua 5.1.5 (running with Lua 5.1)
 • D-Bus support: ✔
 • execinfo support: ✔
 • RandR 1.5 support: ✔
 • LGI version: 0.9.1
```

While on a walking tour of the menubar code, I found in init.lua the functions `load_count_table()` and `write_count_table()`, which read and write a statistical history for commands invoked by menubar.  I also noted by inspection that, while the file holding the count table is opened:

    local count_file = io.open (count_file_name, "w")

It is never closed.  This leads to a bunch of stale filehandles which only get cleaned up when Lua's garbage collector decides to get around to it (verified by running `lsof | grep menu_count_file` between invocations of the menubar).

**Comment by actionless** [comment]
btw, it could be a nice idea for luacheck to match the number of `io.open` and `io.close` in one function (or module?)
