### ISSUE TITLE
Hotkeys pop-up does not display super or alt keys

### ISSUE THREAD

**Issue by yaast** [awesomeWM/awesome#1558]
```
awesome v4.0-221-g439d0c80-dirty (Harder, Better, Faster, Stronger)
 • Compiled against Lua 5.1.4 (running with LuaJIT 2.0.4)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.5
 • LGI version: 0.9.1
``` 
**How to reproduce the issue:**

Pressing Hotkey Pop-Up Cheatsheet does not display Super/Win or Alt Keys.
Default Hotkey ` Super + s `

**Actual result:**

Pressing the given hotkey does not display any of the Super or Alt keys. Check Screenshot below
![2017-02-11-185323_1157x726_scrot](https://cloud.githubusercontent.com/assets/24945937/22857644/df342978-f08f-11e6-8f91-d6d8723bd2b3.png)

**Expected result:**

It should display the super and alt keys.

**Comment by actionless** [comment]
try setting this theme variable:
https://awesomewm.org/apidoc/libraries/awful.hotkeys_popup.widget.html#beautiful.hotkeys_modifiers_fg

**Comment by yaast** [comment]
Now only the screen,layout,launcher, client, awesome, and tag labels appear.
setting theme.hotkeys_modifiers_fg = to any color

**Comment by actionless** [comment]
try settings `theme.hotkeys_fg` explicitly as well

**Comment by yaast** [comment]
Setting both those variables yields the same result, only the labels, awesome,client, tag and so on are displayed. Nothing else

**Comment by actionless** [comment]
could you upload the current version of your config so i could reproduce the issue?

**Comment by yaast** [comment]
Sure here you go!
https://u.teknik.io/CWSSU.gz
Sorry, github upload for some reason is not working with my internet sorry.

**Comment by actionless** [comment]
you forgot `#` in the beginning of hex color definition :)

**Comment by yaast** [comment]
Oh, I'm dumb.
