### ISSUE TITLE
RFC: make awesome look like a current GTK+ 3 theme

### ISSUE THREAD

**Issue by actionless** [awesomeWM/awesome#1560]
I finished the prototype.
Here is the library for reading current GTK+3 theme: https://github.com/actionless/awesome_config/blob/devel/utils/gtk.lua
Here is an awesome wm theme based on that lib (not sure if it will work correctly with the default config):
https://github.com/actionless/awesome_config/blob/devel/themes/gtk/theme.lua

And few screenshots:

Adwaita:
![2017-02-12--1486918298_3840x2160_scrot](https://cloud.githubusercontent.com/assets/1655669/22864359/509ca840-f150-11e6-98dc-3d9f40d9f660.png)

Breeze:
![2017-02-12--1486918449_3840x2160_scrot](https://cloud.githubusercontent.com/assets/1655669/22864365/6c387a3e-f150-11e6-9577-301625e65260.png)

Arc-Dark:
![2017-02-12--1486918399_3840x2160_scrot](https://cloud.githubusercontent.com/assets/1655669/22864362/66298232-f150-11e6-87f6-de6da4e7bdef.png)

2 themes generated by oomox:
![2017-02-12--1486918564_3840x2160_scrot](https://cloud.githubusercontent.com/assets/1655669/22864373/8173acde-f150-11e6-8c40-385ce015baf3.png)
![2017-02-12--1486918510_3840x2160_scrot](https://cloud.githubusercontent.com/assets/1655669/22864371/7b4d853c-f150-11e6-922f-5dc0342509ea.png)

**Comment by actionless** [comment]
and also test code which should work in the default config:

```diff
diff --git a/config/keys.lua b/config/keys.lua
index 2686a55..fc81892 100644
--- a/config/keys.lua
+++ b/config/keys.lua
@@ -17,6 +17,7 @@ local floats = require("actionless.helpers").client_floats
 local persistent = require("actionless.persistent")
 local tmux_swap_bydirection = require("utils.tmux").swap_bydirection
 local wlppr = require("actionless.wlppr")
+local gtk = require("utils.gtk")
 
 
 
@@ -95,9 +96,78 @@ local bind_key = function(mod, key, press, description, group)
 end
 
 
+local function test_lgi()
+  local result = gtk.get_theme_variables()
+  log(result)
+  local naughty = require("naughty")
+  naughty.notify{
+    text='normal',
+    bg=result.bg_color,
+    fg=result.fg_color,
+  }
+  naughty.notify{
+    text='text',
+    bg=result.base_color,
+    fg=result.text_color,
+  }
+  naughty.notify{
+    text='selection',
+    bg=result.selected_bg_color,
+    fg=result.selected_fg_color,
+  }
+  naughty.notify{
+    text='tooltip',
+    bg=result.tooltip_bg_color,
+    fg=result.tooltip_fg_color,
+  }
+  naughty.notify{
+    text='osd',
+    bg=result.osd_bg_color,
+    fg=result.osd_fg_color,
+    border_color=result.osd_border_color,
+  }
+  naughty.notify{
+    text='menubar',
+    bg=result.menubar_bg_color,
+    fg=result.menubar_fg_color,
+  }
+  naughty.notify{
+    text='button',
+    bg=result.button_bg_color,
+    fg=result.button_fg_color,
+  }
+  naughty.notify{
+    text='header button',
+    bg=result.header_button_bg_color,
+    fg=result.header_button_fg_color,
+  }
+  naughty.notify{
+    text='roundness: '..result.roundness..', spacing: '..result.spacing,
+    bg=result.wm_bg_color,
+    fg=result.menubar_fg_color,
+  }
+  naughty.notify{
+    text='wm focused',
+    bg=result.wm_title_focused_color,
+    fg=result.wm_icons_focused_color,
+    border_color=result.wm_border_focused_color,
+  }
+  naughty.notify{
+    text='wm unfocused',
+    bg=result.wm_title_unfocused_color,
+    fg=result.wm_icons_unfocused_color,
+    border_color=result.wm_border_unfocused_color,
+  }
+end
+
 -- {{{ Key bindings
 local globalkeys = awful.util.table.join(
 
+  bind_key({ modkey,  "Control"  }, "a",
+    function() test_lgi() end,
+    "test", "test"
+  ),
+
   awful.key({modkey}, "/", function()
     hkng.show_help()
   end, nil, {
```

**Comment by actionless** [comment]
we even can render buttons/checkboxes/etc via style_context

**Comment by actionless** [comment]
@blueyed @Elv13 @psychon any opinion?

**Comment by psychon** [comment]
Sorry, but I neither like the idea (making awesome depend on GTK) nor the implementation (you need to create a window (this could try to interact with the WM and thus deadlock), you query things on the style context of "a random window" (which is kind-of incompatible with GTK's move to more-and-more CSS). Also, what does `lookup_gtk_color_fake_int` even do? It somehow interprets a color as an integer...?!?)

**Comment by actionless** [comment]
> you need to create a window (this could try to interact with the WM and thus deadlock

mb it can be avoided by settings some specific window type?

> which is kind-of incompatible with GTK's move to more-and-more CSS

but what can be done to be more compatible, actually querying css for .button somehow? or probably i misunderstanding this point

> what does lookup_gtk_color_fake_int even do? It somehow interprets a color as an integer...?!?

this one can be ignored, it's a hack to export border radius value to style context, but of course it will work only for such 'hacked' themes, for the rest fallback value will be used
if it will be going upstream i will remove it

**Comment by actionless** [comment]
ping @psychon 

could you please answer to questions in my previous comment? i still think what it does not require that much work to be done to get it work fine and i don't see any problems which it could cause

**Comment by psychon** [comment]
> it can be avoided by setting some specific window type?

Dunno. The only save thing would be `override_redirect`, I guess. I also guess that GTK cannot create such a window. But yeah, it's highly unlikely to run into a deadlock with this, so whatever...

For the rest: I don't know much about GTK theming and so I cannot say much on this. It just feels odd...

@Elv13 What do you think?

**Comment by Elv13** [comment]
> @Elv13 What do you think?

\<reminder\>Elv13 is currently a ghost. Ghosts don't have time.\</reminder\>

I can see why some users might want this kind of theme. It isn't the default theme and doesn't seem to deadlock, so what the hell, why not. It not like some code (cough, placement, cough) that has critical impact on everything. This is a low-ish risk, mid impact feature.

**Comment by psychon** [comment]
Thank you, ghost. :-)

**Comment by actionless** [comment]
@psychon do you want any changes other than `override_redirect` before i will prepare a pull request and "port"/fork default xresources theme to use new gtk values?

**Comment by psychon** [comment]
None that I can come up with right now (and as I said, that `override_redirect` thing might be impossible).

One thing that I am seeing:
```lua
  local font = style_context:get_font("NORMAL")
  result.font_family = font:get_family()
  result.font_size = font:get_size()/1024
```
I wanted to get rid of the hardcoded constant, but actually... `gtk_style_context_get_font` gives you a `PangoFontDescription` and that one has a `:to_string()` method: https://developer.gnome.org/pango/stable/pango-Fonts.html#pango-font-description-to-string. Why do you need the family and the size separately anyway instead of just `theme.font = font:to_string()`?

**Comment by actionless** [comment]
thanks, i wasn't aware of that method

i searched now, seems it can: https://developer.gnome.org/gdk3/stable/gdk3-Windows.html#gdk-window-set-override-redirect

**Comment by psychon** [comment]
> UPD: btw, which constant do you mean, 1024 or "NORMAL"?

The 1024. That one is defined "somewhere in Pango", but I'm not sure right now where.

> NORMAL is bugging me but i did not found where in lgi are flags constants defined, smth like Gtk.Flags.State.NORMAL

https://developer.gnome.org/gtk3/stable/gtk3-Standard-Enumerations.html#GtkStateFlags
The `GtkStateFlags` enum is available under `require("lgi").StateFlags`. Thus, you are looking for: `require("lgi").Gtk.StateFlags.NORMAL`

**Comment by actionless** [comment]
thanks! that's what i wanted

**Comment by actionless** [comment]
i am still struggling with https://developer.gnome.org/gdk3/stable/gdk3-Windows.html#gdk-window-set-override-redirect

i was tried several variations of method name and also tried to access it as property but with no luck

@psychon how do you usually find out the names of gtk methods inside lgi?


also, as a side note, i was thinking: since gtk main loop is not started, does that window is really being created?

**Comment by psychon** [comment]
@actionless There is a difference between GtkWindow and GdkWindow. Just accessing `.override_redirect` on a GdkWindow should work, but you do not have one here. Google found https://stackoverflow.com/questions/10264625/how-do-i-get-the-gdk-window-for-a-gtk-window-in-c, but that just returns `nil` here, so there is no GdkWindow, I guess...?

**Comment by actionless** [comment]
@psychon what do you think about my second question?

**Comment by psychon** [comment]
I don't know if the window really is created. I guess not (and the above with "there is no GdkWindow" seems to confirm that). So perhaps that whole exercise is unnecessary... I do not know.

**Comment by actionless** [comment]
but going back to the reason why do we are discussing that (the deadlocking awesome on handing that window) -- how can i check from side of awesome (or X server) if that window is around?

**Comment by psychon** [comment]
Hm... just assume that it is not there and everything is fine, I guess.

**Comment by x-yuri** [comment]
Sorry for barging in. But aren't you talking about [what I'd like to achieve][1]? I remember I had Awesome and GNOME installed on the other machine, and applications looked better:

![](http://i.imgur.com/MCyTV3V.png)

Not the way they do now:

![](http://i.imgur.com/faZ16zA.png)

But I'd like to avoid installing GNOME.

Can you explain why is that? Are they using different set of widgets? Adwaita theme seems to be present on the computer. Not sure about that though. Or where can I learn more about it? Where can I ask?

[1]: https://bbs.archlinux.org/viewtopic.php?pid=1719477

**Comment by actionless** [comment]
no, your issue is completely not related to this topic (i've updated the headline to avoid the confusion)

judging from your screens you just doesn't have any gtk themes installed, probably gnome-themes packages got removed together with gnome

**Comment by gBopHuk** [comment]
Where can I find a set of these themes if I don't want use a https://github.com/actionless/awesome_config/blob/devel/utils/gtk.lua ?

P.S. Sorry for my English!

**Comment by actionless** [comment]
@gBopHuk 
wait for this PR to be merged then: https://github.com/awesomeWM/awesome/pull/2129
