### ISSUE TITLE
Declarative guide mistake?

### ISSUE THREAD

**Issue by doctaweeks** [awesomeWM/awesome#1562]
It appears there is either a bug in awesome or an error in the declarative guide. Adding a screen conditional as suggested by the guide (s == 1) causes the widget to disappear from every screen. However, using s.index instead (which seems more explicit) works as expected.

awesome v4.0 (Harder, Better, Faster, Stronger)
 • Compiled against Lua 5.1.5 (running with Lua 5.1)
 • D-Bus support: ✔
 • execinfo support: ✔
 • RandR 1.5 support: ✔
 • LGI version: 0.9.0

**Comment by Elv13** [comment]
Indeed. This was valid when added to the guide, but isn't anymore. I added a commit a few days ago that enable unit test to be executed on documentation articles. The other examples can now be ported to the documentation test framework (v4.1 https://awesomewm.org/apidoc/documentation/03-declarative-layout.md.html).

**Comment by Elv13** [comment]
Fixed in 052cda939
