### ISSUE TITLE
Keepass systray icon missing / sometimes appears in the wrong place

### ISSUE THREAD

**Issue by geripgeri** [awesomeWM/awesome#1563]
Output of `awesome --version`:

```awesome v4.0 (Harder, Better, Faster, Stronger)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • RandR 1.5 support: ✔
 • LGI version: 0.9.1
```

**How to reproduce the issue:**
Unfortunately I have no idea, sometimes it just appears

**Actual result:**

![keepassawesome](https://cloud.githubusercontent.com/assets/5065965/22926278/3bfacc2a-f2ac-11e6-82d2-2c4b6d58aebe.png)

Keepass icon appears behind the tag list.

**Expected result:**
Keepass icon have to displayed in systray. (this works as usual in awesome 3.5)

My rc.lua: https://github.com/geripgeri/awesome-config/blob/master/rc.lua

**Comment by kapsh** [comment]
This is broken for me too (config almost default).

**Comment by psychon** [comment]
Just a rough ETA: I have no idea what could be going on, I know that blaming KeePass will not help, I think I am the only one who will/can look into this, I would have to try to reproduce this (If you can somehow make this easier for me, that would be very welcome), I am currently sick and do not have time.
So do not expect any results soon-ish, sorry...

> (this works as usual in awesome 3.5)

If this were easy to reproduce, one could try to `git bisect` this, perhaps... (`tests/run.sh /dev/null` should start up awesome and provide an environment to test this in - possibly)

**Comment by geripgeri** [comment]
As soon as I find out how I can reproduce it I will write it down ;)  Thanks for your help!

**Comment by kapsh** [comment]
Um, sorry, I was wrong - icon suddenly became disabled in settings. It works for me on 4.0.

**Comment by blueyed** [comment]
@geripgeri 
Are you using v4?
Can you try it with Git master?

**Comment by geripgeri** [comment]
@blueyed Yes, I'm using: https://aur.archlinux.org/packages/awesome-git/. I tried to reinstall the package. The issue still exist.

**Comment by maiaftv** [comment]
Same here both with Keepass and KeepassX. Please let me know if I can be of any help.

**Comment by blueyed** [comment]
@maiaftv 
You might want to dig into the code, if you really want to help.. :)

**Comment by maiaftv** [comment]
@blueyed That would be great, my friend. Unfortunately, neither my skills nor my free time are adequate for the task at this moment.

**Comment by psychon** [comment]
For anyone who wants to debug this, here is a good starting point (This adds lots of spam to awesome's stderr; with timestamps that hopefully help to find the relevant parts):
```diff
diff --git a/event.c b/event.c
index 40e33d7..200da08 100644
--- a/event.c
+++ b/event.c
@@ -341,6 +341,9 @@ event_handle_configurerequest(xcb_configure_request_event_t *ev)
         uint16_t deco_bottom = bw + tb_bottom;
         int16_t diff_w = 0, diff_h = 0, diff_border = 0;
 
+    warn("ConfigureReques for client 0x%x (%s), wants to move to %dx%d\n",
+            ev->window, c->name, ev->x, ev->y);
+
         if(ev->value_mask & XCB_CONFIG_WINDOW_X)
         {
             int16_t diff = 0;
@@ -400,6 +403,8 @@ event_handle_configurerequest(xcb_configure_request_event_t *ev)
     }
     else if (xembed_getbywin(&globalconf.embedded, ev->window))
     {
+        warn("ConfigureReques for systray window 0x%x, wants to move to %dx%d\n",
+                ev->window, ev->x, ev->y);
         /* Ignore this so that systray icons cannot resize themselves.
          * We decide their size!
          * However, Xembed says that we act like a WM to the embedded window and
@@ -418,6 +423,8 @@ event_handle_configurerequest(xcb_configure_request_event_t *ev)
 
         if (geom && coords)
         {
+            warn("Overriding (no, you may not move yourself!) (actual position (on root window!) and size is %dx%d, %dx%d)",
+                    coords->dst_x, coords->dst_y, geom->width, geom->height);
             xwindow_configure(ev->window,
                     (area_t) { .x = coords->dst_x,
                                .y = coords->dst_y,
@@ -428,8 +435,11 @@ event_handle_configurerequest(xcb_configure_request_event_t *ev)
         p_delete(&geom);
         p_delete(&coords);
     }
-    else
+    else {
+        warn("ConfigureReques for UNKNOWN window 0x%x, moving to %dx%d as desired (but only if this is not 0: %d)\n",
+                ev->window, ev->x, ev->y, ev->value_mask & (XCB_CONFIG_WINDOW_X | XCB_CONFIG_WINDOW_Y));
         event_handle_configurerequest_configure_window(ev);
+    }
 }
 
 /** The configure notify event handler.
@@ -440,6 +450,9 @@ event_handle_configurenotify(xcb_configure_notify_event_t *ev)
 {
     xcb_screen_t *screen = globalconf.screen;
 
+    warn("Configurenotify for window 0x%x, moved to %dx%d\n",
+            ev->window, ev->x, ev->y);
+
     if(ev->window == screen->root)
         globalconf.screen_need_refresh = true;
 
```
(Some terminology: ConfigureNotify events are sent when a window was moved, but they are only sent when one asks for them; we should be asking for them. ConfigureRequest events are sent when one says "windows contained in this window may not move/resize themselves" (which we do; thus, it should be impossible for systray windows to appear in random positions))
(Another helpful "thing" might be `xwininfo -root -tree` which lists all windows together with their position and some hopefully-helpful class/instance. This might help to identify which window ID belongs to the systray icon of KeePass.)

Oh and: It should be impossible for a systray icon to appear outside of the systray. This likely means that awesome is not actually seeing the systray icon and KeePass somehow placed its window itself. So here is another patch with some more debug info for systray icons coming and going:
```diff
diff --git a/event.c b/event.c
index 40e33d7..ccb7584 100644
--- a/event.c
+++ b/event.c
@@ -464,6 +464,7 @@ event_handle_destroynotify(xcb_destroy_notify_event_t *ev)
         for(int i = 0; i < globalconf.embedded.len; i++)
             if(globalconf.embedded.tab[i].win == ev->window)
             {
+        warn("systray icon 0x%x was destroyed", ev->window);
                 xembed_window_array_take(&globalconf.embedded, i);
                 luaA_systray_invalidate();
             }
@@ -750,6 +751,7 @@ event_handle_maprequest(xcb_map_request_event_t *ev)
 
     if((em = xembed_getbywin(&globalconf.embedded, ev->window)))
     {
+        warn("systray icon 0x%x becoming visible (incorrectly, violating the protocol)", ev->window);
         xcb_map_window(globalconf.connection, ev->window);
         xembed_window_activate(globalconf.connection, ev->window);
         /* The correct way to set this is via the _XEMBED_INFO property. Neither
@@ -946,6 +948,7 @@ event_handle_reparentnotify(xcb_reparent_notify_event_t *ev)
         for(int i = 0; i < globalconf.embedded.len; i++)
             if(globalconf.embedded.tab[i].win == ev->window)
             {
+        warn("systray icon 0x%x removed itself fromt the systray and moved to parent 0x%x instead", ev->window, ev->parent);
                 xembed_window_array_take(&globalconf.embedded, i);
                 xcb_change_save_set(globalconf.connection, XCB_SET_MODE_DELETE, ev->window);
                 luaA_systray_invalidate();
diff --git a/systray.c b/systray.c
index 93182f3..753157a 100644
--- a/systray.c
+++ b/systray.c
@@ -138,9 +138,14 @@ systray_request_handle(xcb_window_t embed_win)
             | XCB_EVENT_MASK_ENTER_WINDOW
     };
 
+    warn("Got 'please add me to systray' for 0x%x", embed_win);
+
     /* check if not already trayed */
     if(xembed_getbywin(&globalconf.embedded, embed_win))
+    {
+        warn("but it's already in the systray");
         return -1;
+    }
 
     p_clear(&em_cookie, 1);
 
```

**Comment by psychon** [comment]
I just learned that KeePass is written in C#, so I guess you are running it through Mono. Anyone wants to write a simple program using [NotifyIcon](https://msdn.microsoft.com/de-de/library/system.windows.forms.notifyicon(v=vs.110).aspx) and use it in the same way as you would use the KeePass icon? Figuring out when/how this happen and having a clear reproducer would help a lot.
Also: Mono version, everyone?

**Comment by psychon** [comment]
Oh and: Could someone please test this patch? (It should fix the way that mono found to escape from the systray incorrectly)
```diff
diff --git a/event.c b/event.c
index 40e33d7..bfd0126 100644
--- a/event.c
+++ b/event.c
@@ -801,6 +801,13 @@ event_handle_unmapnotify(xcb_unmap_notify_event_t *ev)
 
     if((c = client_getbywin(ev->window)))
         client_unmanage(c, true);
+    else
+        for(int i = 0; i < globalconf.embedded.len; i++)
+            if(globalconf.embedded.tab[i].win == ev->window)
+            {
+                xembed_window_array_take(&globalconf.embedded, i);
+                luaA_systray_invalidate();
+            }
 }
 
 /** The randr screen change notify event handler.
```

**Comment by geripgeri** [comment]
@psychon  my mono version is:

```
Mono JIT compiler version 4.8.0 (Stable 4.8.0.495/e4a3cf3 Mon Feb 27 08:30:18 UTC 2017)
```

Unfortunately I can't test that patch now...

**Comment by psychon** [comment]
I just found the following and will now close this as "not our bug". Feel free to still report back on the above patches, but for lack of activity, I do not feel like this will happen.

https://bugzilla.xamarin.com/show_bug.cgi?id=14976
https://bugzilla.xamarin.com/show_bug.cgi?id=8935
https://bugzilla.redhat.com/show_bug.cgi?id=1284609#c14 (This one seems to be especially interesting since it looks quite similar to the screenshot in the original report here)

**Comment by geripgeri** [comment]
Thanks for the update 🙂
