### ISSUE TITLE
Make XML strings (un)escaping functions name more clear

### ISSUE THREAD

**Issue by bew** [awesomeWM/awesome#1585]
The XML strings (un)escaping functions `util.escape`, `util.unescape` (which are being moved to `gears` with #1584), are a little unclear about the way the strings passed to them will be (un)escaped. 

I think we should name them `xml_escape` and `xml_unescape` to avoid mixing them with other (un)escape system (example: url, shell,..), and it's clearer for the user what theses does exactly.

**Comment by Veratil** [comment]
I can modify the names before the PR is pulled.

Do we want `xml_[un]escape`? `xml_[un]escape_chars`? `[un]escape_xml_chars`?

**Comment by blueyed** [comment]
IMHO, yes.

**Comment by Veratil** [comment]
I've updated the commit in #1584 to add the `xml_` prefix.

**Comment by Veratil** [comment]
@blueyed This can be closed. PR has been merged.
