### ISSUE TITLE
Titlebar can be shown without any widget (awesome-4.0)

### ISSUE THREAD

**Issue by unode** [awesomeWM/awesome#1588]
Output of `awesome --version`:

Gentoo Linux
```
awesome v4.0 (Harder, Better, Faster, Stronger)
 • Compiled against Lua 5.1.5 (running with Lua 5.1)
 • D-Bus support: ✔
 • execinfo support: ✔
 • RandR 1.5 support: ✔
 • LGI version: 0.9.0
```

**How to reproduce the issue:**

Using the default `rc.lua` config.

1. Disable the awful.rule targeting clients with `type=[ "normal", "dialog" ]` to disable the default behavior of showing a titlebar.
2. Restart awesome.
3. Start a new terminal.
4. Start awesome-client on this terminal.
5. Run `awful.titlebar.toggle(client.focus)`
6. Run `awful.titlebar.toggle(client.focus)`
7. Run `client.focus:emit_signal("request::titlebars", "rules", {})`

**Actual result:**

On step 5 an empty titlebar is shown. I.e. no widgets.
On step 7 the normal titlebar is visible. All widgets rendered.

**Expected result:**

On step 5 the titlebar should be automatically initialized and all widgets should be visible.

**Comment by psychon** [comment]
What is it that you *actually* want to do? You want titlebars to be toggleable with a key binding and want some hidden by default? If so, how about adding a call to `awful.titlebar.hide(c)` at the end of the section that adds widgets to the titlebar in your config?

Besides that, I have no idea what should be done here. "Titlebar can be shown without any widget" is kind of by design. I can also show a wibox without any widgets.

**Comment by Unode** [comment]
@psychon I currently have:

```lua
awful.key({ machine.keys.modkey,           }, "y",
        _, size = client.focus:titlebar_top(client.focus, 'top')
        if size == 0 then
            -- This ensures it gets initialized and shown
            -- NOTE awful's code already takes care of ensuring a titlebar
            -- isn't initialized more than once so we don't need to care
            client.focus:emit_signal("request::titlebars", "rules", {})
        else
            awful.titlebar.hide(client.focus)
        end
    end,
    {description = "toggle titlebar", group = "client"}),
```

this:

```lua
awful.key({ machine.keys.modkey,           }, "y",
        _, size = client.focus:titlebar_top(client.focus, 'top')
        if size == 0 then
            awful.titlebar.show(client.focus)
        else
            awful.titlebar.hide(client.focus)
        end
    end,
    {description = "toggle titlebar", group = "client"}),
```

should also work but it doesn't, unless something else emitted the `request::titlebars` signal and the titlebar has already been initialized.

**Comment by getzze** [comment]
What @psychon suggested, create the titlebar for all client and automatically hide it. Show titlebar at startup only for specific client types:

```
clientkeys = awful.util.table.join(
    awful.key({ modkey, }, "d", awful.titlebar.toggle, {description = "toggle decoration", group = "client"})
)

-- Create titlebar
client.connect_signal("request::titlebars", function(c)
   -- Code to create your titlebar here
   -- ...

   -- Hide created titlebar
    awful.titlebar.hide(c)
end)

-- Rules to apply to new clients (through the "manage" signal).
awful.rules.rules = {
    -- All clients will match this rule.
    {   rule = { },
        properties = { border_width = beautiful.border_width,
                       border_color = beautiful.border_normal,
                       focus = awful.client.focus.filter,
                       raise = true,
                       keys = clientkeys,
                       buttons = clientbuttons,
                       screen = awful.screen.preferred,
                       titlebars_enabled = true,   -- Emit signal request::titlebars
                       placement = awful.placement.no_overlap+awful.placement.no_offscreen+awful.placement.centered
                     }
    },

    -- Show titlebar on some window types
    {   rule_any   = { type = {"utility", "splash", "toolbar"} },
        properties = { floating = true,
                       show_titlebar = true
                     }
    }
}
```
