### ISSUE TITLE
Slider widget forced_width

### ISSUE THREAD

**Issue by legostax** [awesomeWM/awesome#1589]
Output of `awesome --version`:
```
awesome v4.0 (Harder, Better, Faster, Stronger)
 • Compiled against Lua 5.1.5 (running with Lua 5.1)
 • D-Bus support: ✔
 • execinfo support: ✔
 • RandR 1.5 support: ✘
 • LGI version: 0.9.1
```

I would presume that `vslider.forced_width = 100` would actually set the widget's width to be 100 pixels.  However, this does not seem to be the case.  Is there something I'm missing?  Here's my code:
```
vslider = wibox.widget.slider()
vslider.bar_shape = gears.shape.rounded_rect
vslider.bar_height = 3
vslider.bar_color = beautiful.border_color
vslider.bar_border_width = 0
vslider.handle_color = beautiful.bg_focus
vslider.handle_shape = gears.shape.circle
vslider.handle_width = 20
vslider.handle_border_color = beautiful.border_color
vslider.handle_border_width = 0
vslider.value = 50
vslider.minimum = 1
vslider.maximum = 50
vslider.forced_width = 100
vslider.forced_height = 30
```
I even tried putting it inside of a container:
```
slcont = wibox.container.margin(vslider)
slcont.forced_width = 100
slcont.forced_height = 30
```
The widget is added to a wibox with:
```
sysmenu.widget = wibox.layout.fixed.vertical(slcont,systray,voltxt)
```
Regardless of what I do, it still produces this on a wibox that is 240 pixels wide:

![screenshot](http://i.imgur.com/3SpSTGc.png)

Does this have anything to do with Cairo?

**Comment by Elv13** [comment]
sorry, but I can't reproduce using

```lua
local wb = wibox {
    visible = true,
    x = 300,
    y = 300,
    height = 20,
    width = 300,
    bg = "#0000cc"
}

local vslider = wibox.widget.slider()
vslider.bar_shape = gears.shape.rounded_rect
vslider.bar_height = 3
vslider.bar_color = beautiful.border_color
vslider.bar_border_width = 0
vslider.handle_color = beautiful.bg_focus
vslider.handle_shape = gears.shape.circle
vslider.handle_width = 20
vslider.handle_border_color = beautiful.border_color
vslider.handle_border_width = 0
vslider.value = 50
vslider.minimum = 1
vslider.maximum = 50
vslider.forced_width = 100
vslider.forced_height = 30

wb : setup {
    vslider,
    {
        widget = wibox.widget.checkbox
    },
    {
        bar_shape = gears.shape.rounded_rect,
        bar_height = 3,
        bar_color = "#ff0000",
        bar_border_width = 0,
        handle_color = beautiful.bg_focus,
        handle_shape = gears.shape.circle,
        handle_width = 20,
        handle_border_color = beautiful.border_color,
        handle_border_width = 0,
        value = 50,
        minimum = 1,
        maximum = 50,
        forced_width = 100,
        widget = wibox.widget.slider
    },
    layout = wibox.layout.fixed.horizontal
}

```

![pick8](https://cloud.githubusercontent.com/assets/340384/23175965/2756d3b2-f82f-11e6-98ab-ee6624e9c0a7.png)

**Comment by legostax** [comment]
Thank you for the help!

I determined that it has to do with me adding `vslider` to my wibox with a vertical layout.  Apparently this overrides my settings and stretches it to fit that way?
`wibox.widget = wibox.layout.fixed.vertical(vslider,systray)`

**Comment by Elv13** [comment]
Ah, yes. If you're on git-master, you can wrap it into a `wibox.container.place` and the issue will go away. The fixed layout is only fixed on one axis. On the other it will stretch the widgets, even if `force_foo` is set.

**Comment by legostax** [comment]
Good to know for the future!  Thanks for the help!  I'll just put something next to `vslider` like a mute button or something.

I'll wait until the next release to upgrade.  In the meantime, I'll figure out how to add this information to the docs.

**Comment by Elv13** [comment]
>  I'll figure out how to add this information to the docs.

Ok, thanks, I added this to the list of underdocumented APIs (#1373)
