### ISSUE TITLE
Strange issue with conky started async

### ISSUE THREAD

**Issue by spheenik** [awesomeWM/awesome#1593]
**Version**
I tried 4.0, and today's version from git, same results:
```
➜  ~ awesome --version
awesome v4.0-253-g052cda93 (Harder, Better, Faster, Stronger)
 • Compiled against Lua 5.3.4 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.5
 • LGI version: 0.9.1

➜  ~ uname -a
Linux zoidberg 4.9.11-1-ARCH #1 SMP PREEMPT Sun Feb 19 13:45:52 UTC 2017 x86_64 GNU/Linux
```

**How to reproduce the issue:**

The following code starts a conky process, and pipes it it's configuration into stdin.
It then uses `awful.spawn.read_lines` to call the callback which then outputs what conky had to say as a notification.

Now: When restarting (Mod-Ctrl-R) awesome, the conky process is started, but it does nothing, and just sits there. Now when I use the mouse to move a window around, it mysteriously starts working.

It looks as if the stdout pipe of the process is blocked or something and the window moving unblocks it.

**Code (paste to the bottom of rc.lua and restart)**
```lua
function demo_bug()

    local spawn = require("awful.spawn")
    local lgi = require("lgi")
    local Gio = lgi.Gio

    local config = [=[
        conky.config = {
            out_to_console = true,
            out_to_x = false,
            update_interval = 1.0,
            total_run_times = 0,
        };
        conky.text = [[${time %H:%M:%S}]]
    ]=]

    local pid, _, stdin, stdout, _ = awesome.spawn("conky -c -", false, true, true, false, nil)
    assert(type(pid) == "number", "Failed to start conky: " .. pid)

    awesome.connect_signal("exit", function()
        awesome.kill(pid, awesome.unix_signal.SIGINT)
    end)

    local cfg_stream = Gio.UnixOutputStream.new(stdin, true)
    cfg_stream:write(config)

    local callback = function(line)
        naughty.notify({ text = line })
    end

    spawn.read_lines(Gio.UnixInputStream.new(stdout, true), callback, nil, true)

end

demo_bug()
```
**Actual result:**

The notifications only appear after moving windows around with the mouse!

**Expected result:**

Code should immediately spit notifications once per second.

**Comment by psychon** [comment]
Add `cfg_stream:close()` after `cfg_stream:write(config)`.

Conky reads until the end of the file (well, actually it lets Lua parse `/dev/stdin`, which is quite a bit Linux specific and ugly...). In your original code, end-of-file for Conky's standard input only happens when Lua's garbage collector decides to collect the `cfg_stream` object (which is a random amount of time). With the above, the close should happen immediately and Conky will not be blocked waiting for more data.

**Comment by psychon** [comment]
Also: Better use `write_all` instead of `write`. `write` is allowed to write only part of its data and you are supposed to retry with the rest. https://developer.gnome.org/gio/stable/GOutputStream.html#g-output-stream-write-all

**Comment by spheenik** [comment]
Wtf! I swear by all that's holy that I had tried the `cfg_stream:close()` before reporting, so I am unsure of why it is working now!

I use `write_all` now and close properly and [I even made you happy!](https://github.com/spheenik/awesome/commit/429442b347d8ef22b89ff4d8c7362594b1fe160f)

Thanks!
