### ISSUE TITLE
Windows spawned from hidden clients will be hidden as well

### ISSUE THREAD

**Issue by majutsushi** [awesomeWM/awesome#1594]
Output of `awesome --version`:

```
awesome v4.0 (Harder, Better, Faster, Stronger)
 • Compiled against Lua 5.1.5 (running with Lua 5.1)
 • D-Bus support: ✔
 • execinfo support: ✔
 • RandR 1.5 support: ✔
 • LGI version: 0.9.1
```

**How to reproduce the issue:**

1. Create a terminal
2. Run something like `sleep 5; zenity --info --title=foo --text=bar`
3. Hide the terminal by setting `client.hidden = true`

I have a script that creates and hides a "scratchpad" terminal on a keypress:
https://github.com/majutsushi/etc/blob/master/awesome/scratch/uniqdrop.lua

**Actual result:**

The window gets created, but is hidden and inaccessible

This worked fine in Awesome 3.5, so something relevant seems to have changed in 4.0.

I tried running this to get the new window to show up, but it didn't do anything:
```
echo 'for _,c in ipairs(client.get()) do c.hidden = false end' | awesome-client
```

**Expected result:**

The window gets created as if the originating client wasn't hidden

**Comment by blueyed** [comment]
I cannot reproduce it on Git master:

I've created a terminal with title "foo", and made it hidden:
```
for _,c in ipairs(client.get()) do if c.name and c.name:match("foo") then c.hidden = true end end
```

I've started the `sleep 5; zenity --info --title=foo --text=bar` therein before, but the zenity window was visible, and not hidden.

Can you try if it still happens with Git master for you, please?

**Comment by majutsushi** [comment]
Sorry, when trying your test I actually realized that the `hidden` property was a red herring, because it worked fine for me on the stable version as well.

The important part is actually this bit in the script I mentioned above:
```
            local ctags = c:tags()
            for i, t in pairs(ctags) do
                ctags[i] = nil
            end
            c:tags(ctags)
```

I.e. it removes all of the tags from the client in addition to hiding it. And indeed, if I run this:
```
echo 'for _,c in ipairs(client.get()) do if c.name and c.name:match("foo") then local ctags = c:tags() for i, t in pairs(ctags) do ctags[i] = nil end c:tags(ctags) end end' | awesome-client
```
then I can reliably reproduce it with the stable version. I also tried to run the master version in Xephyr but couldn't get `awesome-client` to send its commands to the awesome running in Xephyr instead of the outer one.

So the issue seems to be that windows that get spawned from a client that has no tags won't get assigned any tags either. I'm not sure what the right behaviour here is, but at least in 3.5 the window seemed to get assigned the first tag on the first screen.

**Comment by actionless** [comment]
but why it's removing all the tags from a client?

**Comment by majutsushi** [comment]
The idea of the script is to create a temporary scratch terminal that
conceptually doesn't belong to any tag, that just gets toggled occasionally to
do some quick work. If it wouldn't remove the terminal from all tags then if
you toggled it on any tag it would still show up as belonging to that tag,
which would result in incorrect behaviour if some function wants to do
something to all clients in a tag, and if you switch away from the tag it
would show up as having clients in it in the taglist even though there may not
actually be any clients there.

**Comment by Elv13** [comment]
Untested

awful/ewmh.lua:

from:

```
function ewmh.tag(c, t, hints) --luacheck: no unused
    -- There is nothing to do
    if not t and #get_valid_tags(c, c.screen) > 0 then return end

    if not t then
        if c.transient_for and not (hints and hints.reason == "screen") then
            c.screen = c.transient_for.screen
            if not c.sticky then
                c:tags(c.transient_for:tags())
            end
        else
            c:to_selected_tags()
        end
    elseif type(t) == "boolean" and t then
        c.sticky = true
    else
        c.screen = t.screen
        c:tags({ t })
    end
end
```

to:

```
function ewmh.tag(c, t, hints) --luacheck: no unused
    -- There is nothing to do
    if not t and #get_valid_tags(c, c.screen) > 0 then return end

    if not t then
        if c.transient_for and not (hints and hints.reason == "screen") then
            c.screen = c.transient_for.screen
            if not c.sticky then
                local t = c.transient_for:tags()
                c:tags(#t > 0 and t or c.transient_for.screen.selected_tags)
            end
        else
            c:to_selected_tags()
        end
    elseif type(t) == "boolean" and t then
        c.sticky = true
    else
        c.screen = t.screen
        c:tags({ t })
    end
end
```

**Comment by majutsushi** [comment]
Indeed, that does fix it for me!
