### ISSUE TITLE
Wrong width and height size for main screen

### ISSUE THREAD

**Issue by HoskeOwl** [awesomeWM/awesome#1595]
Output of `awesome --version`:
[hoske@Dual ~]$ awesome --version
awesome v4.0 (Harder, Better, Faster, Stronger)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • RandR 1.5 support: ✔
 • LGI version: 0.9.1

**How to reproduce the issue:**
Run system with awesome and single screen.
Connect a new screen and configure it (xrandr --output VGA1 --above eDP1 --auto).
Check width and height of workarea for main screen.
(I've added code to function set_wallpaper - local size = s.workarea. Then I've checked size.width and size.height)

**Actual result:**
Wrong resolution of screen - 1366x726
From xrandr:
[hoske@Dual ~]$ xrandr
Screen 0: minimum 8 x 8, current 1366 x 1792, maximum 32767 x 32767
eDP1 connected primary 1366x768+0+1024 (normal left inverted right x axis y axis) 340mm x 190mm
   1366x768      60.02*+

**Expected result:**
WIDTHxHEIGHT have to be 1366x768 for main screen

**Comment by actionless** [comment]
you just need geometry instead of workarea:
https://awesomewm.org/apidoc/classes/screen.html#screen.geometry
https://awesomewm.org/apidoc/classes/screen.html#screen.workarea
