### ISSUE TITLE
build: allow to pass in VERSION / GIT_VERSION

### ISSUE THREAD

**Issue by blueyed** [awesomeWM/awesome#160]
I am looking into adding a awesome-git package to Nix / nixpkgs, and it uses `--depth 1` when fetching the git source, which does not allow for "git describe" to work properly.

I've seen another build definition, which passes in `makeFlags = "VERSION=v${version} GIT_VERSION=v${version}";` (https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/editors/emacs-modes/haskell/git.nix), which might be helpful in this regard.

My current workaround is not using Git to fetch it (which is good anyway), and then write the version to `.version-stamp` manually.

While the current approach is good enough for me in this case, it might be nice to support passing in VERSION maybe for this?

**Comment by psychon** [comment]
This is the relevant part of `awesomeConfig.cmake`:

    # {{{ Version stamp
    if(EXISTS ${SOURCE_DIR}/.git/HEAD AND GIT_EXECUTABLE)
        # get current version
        execute_process(
            COMMAND ${GIT_EXECUTABLE} describe --dirty
            WORKING_DIRECTORY ${SOURCE_DIR}
            OUTPUT_VARIABLE VERSION
            OUTPUT_STRIP_TRAILING_WHITESPACE)
        # file the git-version-stamp.sh script will look into
        set(VERSION_STAMP_FILE ${BUILD_DIR}/.version_stamp)
        file(WRITE ${VERSION_STAMP_FILE} ${VERSION})
        # create a version_stamp target later
        set(BUILD_FROM_GIT TRUE)
    elseif( EXISTS ${SOURCE_DIR}/.version_stamp )
        # get version from version stamp
        file(READ ${SOURCE_DIR}/.version_stamp VERSION)
    endif()
    # }}}

The variable `VERSION` is already set to `devel` at the beginning of the file. So... Dunno. Introduce an `OVERRIDE_VERSION` variable which is only evaluated after this?

    if(OVERRIDE_VERSION)
        set(VERSION ${OVERRIDE_VERSION})
    endif()

I'm not fully convinced.

**Comment by blueyed** [comment]
> Why do we have two places running "git describe" anyway`

Yes, that should get fixed probably anyway.
