### ISSUE TITLE
Window not shown

### ISSUE THREAD

**Issue by tinloaf** [awesomeWM/awesome#161]
Hi,

I'm running awesome 3.4.15 and am currently experiencing a problem where windows of github's atom editor are not shown. Atom is definitely running (verified via ps), and windows are created:

```
tinloaf@janeway ~ % xwininfo -tree -root | grep -i atom
     0x2a0002a "atom": ("atom" "Atom")  200x200+0+0  +0+0
     0x2c00001 "Atom": ("atom" "Atom")  800x600+560+240  +560+240
     0x2a0001e "atom": ("atom" "Atom")  200x200+0+0  +0+0
     0x2a00003 "atom": ("atom" "Atom")  200x200+0+0  +0+0
     0x2a00001 "atom": ("atom" "Atom")  10x10+10+10  +10+10
```

I'm not sure why atom creates 5 windows when started only once, but none of these is visible on any of my tags, not even in minimized state. Here's the detailed info on one of those:

```
tinloaf@janeway ~ % xwininfo -id 0x2c00001             

xwininfo: Window id: 0x2c00001 "Atom"

  Absolute upper-left X:  560
  Absolute upper-left Y:  240
  Relative upper-left X:  560
  Relative upper-left Y:  240
  Width: 800
  Height: 600
  Depth: 24
  Visual: 0x20
  Visual Class: TrueColor
  Border width: 0
  Class: InputOutput
  Colormap: 0x22 (installed)
  Bit Gravity State: ForgetGravity
  Window Gravity State: NorthWestGravity
  Backing Store State: NotUseful
  Save Under State: no
  Map State: IsUnMapped
  Override Redirect State: no
  Corners:  +560+240  -560+240  -560-240  +560-240
  -geometry 800x600+560+240
```

I tried finding out more using awesome-client, but for some reason, awful.client.iterate is not available for me, and I can't find another way of getting a handle to one of these windows.  

Any idea what's wrong here?

**Comment by Elv13** [comment]
Hello,

The 3.4 branch is not supported anymore. Can you try with 3.5.6? Even if it turn out to be a bug in 3.4, we wont make another 3.4 release, so it wont get fixed. As for the `awesome-client` issue, you have to do `require("awful").client.iterate`. There is 3.5.* packages for most distributions. The Debian/Ubuntu ones are in the experimental repository

**Comment by tinloaf** [comment]
Just upgraded to 3.5.6 by unmasking it in my Gentoo. Those layout changes gave me a hard time... ;)

As far as I can tell, my config is sane now again, but the problem persists. :(

**Comment by Elv13** [comment]
Hello,

Thanks for testing. You can create a trace?
```
emerge x11-misc/xtrace
```

It is a little tricky. You have to create a new X server from ctrl+alt+F2, using the `X :1` command then launch x11trace for :9, then from ctrl+alt+F3 `DISPLAY=:9 awesome`. Please use the default config for that and do as little as possible beside reproducing the problem. Those files get big _fast_. This will give us all the [debug] information we need to figure this out. I seen something like this before, but could not pinpoint it.

**Comment by psychon** [comment]
Please always use `xtrace --relative-timestamps`.

Also, for something simpler: It might (!) already be enough to just run `xtrace --relative-timestamps whatever-program-you-need-for-the-atom-editor` instead of also running awesome under xtrace.

**Comment by tinloaf** [comment]
Hi! I already fixed it by upgrading to Atom's bleeding etch, but I will nonetheless downgrade again and try this, because I'm curious! Give me a couple of days..

**Comment by psychon** [comment]
Reporter vanished.

**Comment by tinloaf** [comment]
Oh, yeah, sorry.. I failed to reproduce that. Sorry about not closing this.
