### ISSUE TITLE
Tooltip infobubble shape rendering wrong

### ISSUE THREAD

**Issue by 0x041E** [awesomeWM/awesome#1611]
I'm running awesome from Archlinux aur awesome-luajit-git
```
awesome v4.0-261-g3b0269d5-dirty (Harder, Better, Faster, Stronger)
 • Compiled against Lua 5.1.4 (running with LuaJIT 2.0.4)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.5
 • LGI version: 0.9.1
```

I was trying various widget shapes but when i shaped tooltip i found something really strange.
My tooltip code
```
local batterytooltip = awful.tooltip({
    objects = {batterywidget},
    text = "Testing text in the tooltip\n on the battery bar widget",                                                                                          
    shape = gears.shape.infobubble,
    timeout = 5, 
});

```
And the result:
![tooltip](https://cloud.githubusercontent.com/assets/12925543/23412258/4c4ff27e-fdd5-11e6-89d0-b8b04177bbc4.png)
With only 1 line of text:
![tooltip2](https://cloud.githubusercontent.com/assets/12925543/23412628/6de338d2-fdd6-11e6-967f-9c7f158245b9.png)

So it seems to keep the original shape which is obviously wrong.
The tooltip is drawn when i mouse over this widget in case there's something wrong with it
```
local batteryupdatetimer = timer({ timeout = 15 })
local batterybar =  wibox.widget{
                    max_value = 100,
                    value = tonumber(battery_level()),
                    forced_width = 50,
                    forced_height = 10,
                    border_width = 1,
--                     shape = gears.shape.rounded_bar,
                    widget = wibox.widget.progressbar,
                }
local batterybartext = wibox.widget {
                text = (trimstring(battery_level()) .. "%"),
                align = 'center',
                forced_width = 50,
                forced_height = 10,
                widget = wibox.widget.textbox,
            }
local batterywidget = wibox.widget {
    batterybar,
    batterybartext,
    forced_width = 50,
    forced_height = 10,
    layout = wibox.layout.stack,
}
```

**Comment by Elv13** [comment]
The tooltip currently don't support detecting the usable area of a shape and it isn't trivial to implement. Adding margins manually is the best option for now. I will close this and noted the documentation issue in the centralized list of under-documented features.
