### ISSUE TITLE
Making SMPlayer fullscreen moves client to other screen

### ISSUE THREAD

**Issue by dbedrenko** [awesomeWM/awesome#1617]
Output of `awesome --version`:

```
awesome v4.0-270-gedd9415d (Harder, Better, Faster, Stronger)
 • Compiled against Lua 5.3.4 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.5
 • LGI version: 0.9.1
```

**How to reproduce the issue:**

0. 
- Prepare 2 screens.
- Install SMPlayer (I have v17.2.0 (revision 8426) but I found out about this problem a few months ago when I got an extra monitor so I bet an older version has the problem).
- Use the default rc.lua
- Set the tag layout on both screens to "max".
1. On the first screen run `smplayer -minigui`.
2. Notice that the client has the property icons: floating, vertically maximise, horizontally maximised (I would expect no icons).
3. Move the client to the 2nd screen.
4. Press "f" to make SMPlayer go into fullscreen mode.

**Actual result:**

SMPlayer jumps back to 1st screen and is in fullscreen mode.

**Expected result:**

SMPlayer goes into fullscreen mode on the 2nd screen.

This doesn't happen when running `smplayer` without the `-minigui` argument. VLC doesn't have this issue either, nor does mplayer.

**Comment by dbedrenko** [comment]
Forgot to mention that I think this is related to issue https://github.com/awesomeWM/awesome/issues/1320 . It jumps back to the screen where the client remembers it was moved from before being put into fullscreen mode.

**Comment by blueyed** [comment]
Regarding 2. see https://github.com/awesomeWM/awesome/issues/1559 (and #1599}.

**Comment by dbedrenko** [comment]
This workaround worked great, thanks!

```
    { rule = { name = "smplayer" }, properties = {},
		callback = function(c) 
			c.maximized, c.maximized_vertical, c.maximized_horizontal = false, false, false
		end
	},
```

**Comment by dbedrenko** [comment]
FYI Unfortunately, that workaround quite often fails. There is still something buggy going on. I will wait for the linked issues to be fixed.

**Comment by blueyed** [comment]
You could try https://github.com/awesomeWM/awesome/pull/1748 (just rebased on master), but we're eventually merging it anyway.

**Comment by blueyed** [comment]
https://github.com/awesomeWM/awesome/pull/1748 has been merged, so I closing it in the assumption that it also helps here.

Please re-open otherwise, of couse.
