### ISSUE TITLE
awful.util.spawn causes awesomewm to crash

### ISSUE THREAD

**Issue by foulowl** [awesomeWM/awesome#1623]
Output of `awesome --version`:

awesome v3.4.15 (Never Gonna Give You Up)
 • Build: Feb 17 2013 21:10:46 for x86_64 by gcc version 4.7.2 (buildd@barber)
 • D-Bus support: ✔

(please note that this is the version included in the debian 8 repos)

**How to reproduce the issue:**

1. Copy rc.lua to ~/.config/awesome
2. Append the single line "awful.util.spawn("xclock")"
3. Log into lightdm, choosing awesomewm.

**Actual result:**

awesomewm refuses to start, it takes me back to lightdm. No error message. xsession error file has the following lines:

```
Xsession: X session started for foul_owl at Fri Mar  3 19:06:33 PST 2017
localuser:foul_owl being added to access control list
openConnection: connect: No such file or directory
cannot connect to brltty at :0
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  12 (X_ConfigureWindow)
  Resource id in failed request:  0x0 
  Serial number of failed request:  665 
  Current serial number in output stream:  686 
XIO:  fatal IO error 0 (Success) on X server ":0"^M
      after 17 requests (17 known processed) with 0 events remaining.^M
XIO:  fatal IO error 11 (Resource temporarily unavailable) on X server ":0"^M
      after 56 requests (56 known processed) with 0 events remaining.^M
XIO:  fatal IO error 0 (Success) on X server ":0"^M
      after 17 requests (17 known processed) with 0 events remaining.^M
XIO:  fatal IO error 0 (Success) on X server ":0"^M
      after 17 requests (17 known processed) with 0 events remaining.^M
XIO:  fatal IO error 0 (Success) on X server ":0"^M
      after 17 requests (17 known processed) with 0 events remaining.^M
Error: Can't open display: :0
Error: Can't open display: :0
Error: Can't open display: :0
Error: Can't open display: :0
```

If I remove that awful.util.spawn line, awesomewm loads fine, so that one line is the issue.

**Expected result:**

awesomewm should start up and spawn xclock as expected. Even if it can't spawn xclock, that shouldn't cause the entire wm to crash.

Thanks!!

**Comment by Elv13** [comment]
3.4 was released in 2009. This bug was fixed in ~2011(?). To fix the problem, use an non-ancient version of awesome.

**Comment by psychon** [comment]
Also, you should look at your Xorg.0.log. I guess your X server crashes and just takes everything down with it. (The log does not contain any messages which I would think come from awesome)
