### ISSUE TITLE
Title bars should not appear on _KDE_NET_WM_WINDOW_TYPE_OVERRIDE windows

### ISSUE THREAD

**Issue by Malvineous** [awesomeWM/awesome#1626]
I notice the latest Awesome version places title bars on windows of type "dialog", however I am getting title bars on my Promoe (XMMS2 media player) windows that shouldn't be there.

There are two Promoe windows, one with a title bar and one without (both should not have title bars.)

The correct window, that has no title bar, has `xprop` say this:

    _NET_WM_WINDOW_TYPE(ATOM) = _KDE_NET_WM_WINDOW_TYPE_OVERRIDE,
      _NET_WM_WINDOW_TYPE_NORMAL

However the incorrect window, that has a title bar and should not have one, says this:

    _NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_DIALOG,
      _KDE_NET_WM_WINDOW_TYPE_OVERRIDE, _NET_WM_WINDOW_TYPE_NORMAL

It looks like the rule in the default config that puts title bars on dialog boxes needs to be changed so that it puts title bars on dialog boxes *except* if they have `_NET_WM_WINDOW_TYPE_OVERRIDE` also.

I am not sure how to update this rule however so any advice would be appreciated!  Happy to confirm whether any suggested change works so the default config can be updated.

```
awesome v4.0 (Harder, Better, Faster, Stronger)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • RandR 1.5 support: ✔
 • LGI version: 0.9.1
```

**Comment by psychon** [comment]
Could you also check `xprop` output for the windows? If one of them has `Override Redirect State: yes` then that would explain why it has no titlebar: Because awesome does not 'see' this window at all.

Also, sorry, but there is no `_NET_WM_WINDOW_TYPE_OVERRIDE` as far as I can see: https://specifications.freedesktop.org/wm-spec/wm-spec-latest.html (at least Ctrl-F does not find it)

Oh... also, I just read that you are actually saying `_KDE_....`. That sounds quite a bit non-standard. We cannot do anything about "random" atoms in `_NET_WM_WINDOW_TYPE`, I think.

> I am not sure how to update this rule however so any advice would be appreciated!

The best suggestion that I can offer is to make the rule match on `WM_CLASS` (so `.type` and `.class` properties).

**Comment by Malvineous** [comment]
Whoops sorry about the `_KDE` omission.

I can't see anything about `Override Redirect State` so not sure.  The `_MOTIF_WM_HINTS` are different but that seems to be the only other change.

So am I correct in understanding that there's no way to match against atoms like `_KDE_NET_WM_WINDOW_TYPE_OVERRIDE` from `rc.lua`, and the only workaround is to add type/class based exceptions as they come up?

Here is the full `xprop` output:

**Main window** (no titlebar, correct)
```
_NET_WM_USER_TIME(CARDINAL) = 223642928
_NET_WM_DESKTOP(CARDINAL) = 18
_NET_FRAME_EXTENTS(CARDINAL) = 0, 0, 0, 0
WM_STATE(WM_STATE):
                window state: Normal
                icon window: 0x0
_NET_WM_ICON_NAME(UTF8_STRING) = 
XdndAware(ATOM) = BITMAP
WM_NAME(STRING) = "Promoe"
_NET_WM_NAME(UTF8_STRING) = "Promoe"
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x3, 0x4, 0x0, 0x0, 0x0
_NET_WM_WINDOW_TYPE(ATOM) = _KDE_NET_WM_WINDOW_TYPE_OVERRIDE, _NET_WM_WINDOW_TYPE_NORMAL
_XEMBED_INFO(_XEMBED_INFO) = 0x0, 0x1
WM_CLIENT_LEADER(WINDOW): window id # 0x2200007
WM_HINTS(WM_HINTS):
                Client accepts input or input focus: True
                Initial state is Normal State.
_NET_WM_PID(CARDINAL) = 3364
_NET_WM_SYNC_REQUEST_COUNTER(CARDINAL) = 35651590
WM_CLASS(STRING) = "promoe", "Promoe"
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, WM_TAKE_FOCUS, _NET_WM_PING, _NET_WM_SYNC_REQUEST
WM_NORMAL_HINTS(WM_SIZE_HINTS):
                user specified location: 5364, 2037
                user specified size: 275 by 116
                program specified minimum size: 275 by 116
                program specified maximum size: 275 by 116
                window gravity: NorthWest
```
**Playlist window** (has a titlebar but shouldn't)
```
_NET_WM_USER_TIME(CARDINAL) = 223638928
_NET_WM_DESKTOP(CARDINAL) = 18
_NET_FRAME_EXTENTS(CARDINAL) = 0, 0, 20, 0
WM_STATE(WM_STATE):
                window state: Normal
                icon window: 0x0
WM_TRANSIENT_FOR(WINDOW): window id # 0x2200005
_NET_WM_ICON_NAME(UTF8_STRING) = 
XdndAware(ATOM) = BITMAP
WM_NAME(STRING) = 
_NET_WM_NAME(UTF8_STRING) = "Promoe"
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x2, 0x1, 0x0, 0x0, 0x0
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_DIALOG, _KDE_NET_WM_WINDOW_TYPE_OVERRIDE, _NET_WM_WINDOW_TYPE_NORMAL
_XEMBED_INFO(_XEMBED_INFO) = 0x0, 0x1
WM_CLIENT_LEADER(WINDOW): window id # 0x2200007
WM_HINTS(WM_HINTS):
                Client accepts input or input focus: True
                Initial state is Normal State.
_NET_WM_PID(CARDINAL) = 3364
_NET_WM_SYNC_REQUEST_COUNTER(CARDINAL) = 35651598
WM_CLASS(STRING) = "promoe", "Promoe"
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, WM_TAKE_FOCUS, _NET_WM_PING, _NET_WM_SYNC_REQUEST
WM_NORMAL_HINTS(WM_SIZE_HINTS):
                user specified location: 5040, 580
                user specified size: 599 by 1436
                program specified minimum size: 275 by 116
                window gravity: NorthWest
```

**Comment by psychon** [comment]
Sorry, I meant `xwininfo` instead of `xprop`.

**Comment by Malvineous** [comment]
Here's the window correctly having no title bar:
```
xwininfo: Window id: 0x2200005 "Promoe"

  Root window id: 0xe9 (the root window) (has no name)
  Parent window id: 0xc0005d (has no name)
     0 children.

  Absolute upper-left X:  5364
  Absolute upper-left Y:  2037
  Relative upper-left X:  0
  Relative upper-left Y:  0
  Width: 275
  Height: 116
  Depth: 24
  Visual: 0xc6
  Visual Class: TrueColor
  Border width: 0
  Class: InputOutput
  Colormap: 0x2200004 (not installed)
  Bit Gravity State: NorthWestGravity
  Window Gravity State: NorthWestGravity
  Backing Store State: NotUseful
  Save Under State: no
  Map State: IsViewable
  Override Redirect State: no
  Corners:  +5364+2037  -601+2037  -601-7  +5364-7
  -geometry 275x116+5364-7

  Bit gravity: NorthWestGravity
  Window gravity: NorthWestGravity
  Backing-store hint: NotUseful
  Backing-planes to be preserved: 0xffffffff
  Backing pixel: 0
  Save-unders: No

  Someone wants these events:
      KeyPress
      KeyRelease
      ButtonPress
      ButtonRelease
      EnterWindow
      LeaveWindow
      PointerMotion
      ButtonMotion
      Exposure
      StructureNotify
      SubstructureNotify
      FocusChange
      PropertyChange
  Do not propagate these events:
  Override redirection?: No

  Window manager hints:
      Client accepts input or input focus: Yes
      Initial state is Normal State
      Displayed on desktop 18
      Window type:
           Kde Net Wm Window Type Override
          Normal
      Process id: 1401
      Frame extents: 0, 0, 0, 0

  Normal window size hints:
      User supplied location: 5364, 2037
      User supplied size: 275 by 116
      Program supplied minimum size: 275 by 116
      Program supplied maximum size: 275 by 116
      Program supplied window gravity: NorthWestGravity
  No zoom window size hints defined

  No window shape defined
  No border shape defined
```
And here's the window that has a title bar but shouldn't:
```
xwininfo: Window id: 0x220000d "Promoe"

  Root window id: 0xe9 (the root window) (has no name)
  Parent window id: 0xc0005e (has no name)
     0 children.

  Absolute upper-left X:  5040
  Absolute upper-left Y:  600
  Relative upper-left X:  0
  Relative upper-left Y:  20
  Width: 599
  Height: 1436
  Depth: 24
  Visual: 0xc6
  Visual Class: TrueColor
  Border width: 0
  Class: InputOutput
  Colormap: 0x220000c (not installed)
  Bit Gravity State: NorthWestGravity
  Window Gravity State: NorthWestGravity
  Backing Store State: NotUseful
  Save Under State: no
  Map State: IsViewable
  Override Redirect State: no
  Corners:  +5040+600  -601+600  -601-124  +5040-124
  -geometry 599x1436+5040+580

  Bit gravity: NorthWestGravity
  Window gravity: NorthWestGravity
  Backing-store hint: NotUseful
  Backing-planes to be preserved: 0xffffffff
  Backing pixel: 0
  Save-unders: No

  Someone wants these events:
      KeyPress
      KeyRelease
      ButtonPress
      ButtonRelease
      EnterWindow
      LeaveWindow
      PointerMotion
      ButtonMotion
      Exposure
      StructureNotify
      SubstructureNotify
      FocusChange
      PropertyChange
  Do not propagate these events:
  Override redirection?: No

  Window manager hints:
      Client accepts input or input focus: Yes
      Initial state is Normal State
      Displayed on desktop 18
      Window type:
          Dialog
           Kde Net Wm Window Type Override
          Normal
      Process id: 1401
      Frame extents: 0, 0, 20, 0

  Normal window size hints:
      User supplied location: 5040, 580
      User supplied size: 599 by 1436
      Program supplied minimum size: 275 by 116
      Program supplied window gravity: NorthWestGravity
  No zoom window size hints defined

  No window shape defined
  No border shape defined
```
The only difference I can see is the KDE flag.

**Comment by psychon** [comment]
> The only difference I can see is the KDE flag.

You mean the Dialog flag under "Window type", right? That would also be the only relevant difference that I can see. So... I can see why a window with window type `_NET_WM_WINDOW_TYPE_DIALOG` and a `WM_TRANSIENT_FOR` entry would get a titlebar assigned by the default config. However, I do not know why "that other window" does not get one. As far as I can see, it should have window type normal, i.e. `c.type == "normal"` and should also get a titlebar.

The only suggestion that I can make is to change your `rc.lua` so that windows with `class = "Promoe"` do not get a titlebar.

Oh and sorry that I missed this question: 

> So am I correct in understanding that there's no way to match against atoms like _KDE_NET_WM_WINDOW_TYPE_OVERRIDE from rc.lua, and the only workaround is to add type/class based exceptions as they come up?

The answer is just "yup".

**Comment by Malvineous** [comment]
Sorry yes, I was thinking that the KDE flag should override the Dialog flag.  Well I added `titlebars_enabled=false` to a rule for `class="Promoe"` and it fixed the problem, but it still seems like a workaround to me :-)
