### ISSUE TITLE
tag.setmwfact() no longer has any effect

### ISSUE THREAD

**Issue by Malvineous** [awesomeWM/awesome#1627]
Output of `awesome --version`:

```
awesome v4.0 (Harder, Better, Faster, Stronger)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • RandR 1.5 support: ✔
 • LGI version: 0.9.1
```

**How to reproduce the issue:**

Add this line to `rc.lua`:

    awful.tag.setmwfact(0.2, screen[1].tags[1])

Create windows and see if the master width factor has changed.

**Actual result:**

No change, it doesn't matter what the value is set to, two windows with one master are split 50/50.

**Expected result:**

The master window would be much narrower, as it was in earlier versions of Awesome.

**Comment by Veratil** [comment]
The function is deprecated, but [it's a typo](https://github.com/awesomeWM/awesome/blob/master/lib/awful/tag.lua#L613). `get` is called instead of `set`.

Anyway, it should now be: `screen[1].tag[1].master_width_factor = 0.2`

**Comment by Malvineous** [comment]
I got an error `attempt to index a nil value (field 'tag')` but using `tags[]` instead of `tag[]` did the trick!  Many thanks.
