### ISSUE TITLE
Do we want compatibility with older versions of Luacheck?

### ISSUE THREAD

**Issue by psychon** [awesomeWM/awesome#1630]
```
Checking lib/awful/spawn.lua                      1 error

    lib/awful/spawn.lua:1:1: invalid inline option

Checking lib/naughty/core.lua                     1 error

    lib/naughty/core.lua:9:1: invalid inline option
```

**Comment by Elv13** [comment]
As it's not called during `cmake` or `make`, then I guess we don't. All the value is in the latest version and the very few users who will care enough to install it will do so with luarock (unless it is packaged in some distro, I didn't check beside Gentoo)

**Comment by psychon** [comment]
I got my version from debian (I don't even have luarocks installed). That's how I noticed this. But yeah, I guess "just the latest and greatest" is a reasonable choice for this tool.

**Comment by blueyed** [comment]
Agreed.
