### ISSUE TITLE
Unfocusing a client doesn't work

### ISSUE THREAD

**Issue by Elv13** [awesomeWM/awesome#164]
```lua
/* Client module new index.
 * \param L The Lua VM state.
 * \return The number of pushed elements.
 */
static int
luaA_client_module_newindex(lua_State *L)
{
    const char *buf = luaL_checkstring(L, 2);
    client_t *c;

    if (A_STREQ(buf, "focus"))
    {
        c = luaA_checkudata(L, 3, &client_class);
        client_focus(c);
    }

    return 0;
}
```

This code prevent `capi.client.focus = nil` to work. There doesn't seem to be a non-hacky way to remove the focus. A potential solution is to check nil there and set `globalconf.focus.client` and `globalconf.focus.need_update = true;` manually

**Comment by blueyed** [comment]
Might it be possible to "focus" the root window?
Is the root window accessible in Lua?
