### ISSUE TITLE
awful.client.swap.global_bydirection to an empty screen

### ISSUE THREAD

**Issue by xinhaoyuan** [awesomeWM/awesome#1644]
The code doesn't work when swapping a client to an empty screen (lib/awful/client.lua:229).

```
        elseif get_screen(sel.screen) ~= get_screen(c.screen) and sel == c then
            sel:move_to_screen(screen.focused())
```

get_screen(c.screen) should be screen.focused()

**Comment by Elv13** [comment]
Right, there was already a fix in the pipeline. I should have merged it earlier.
