### ISSUE TITLE
Certain Mod4 key combinations don't work

### ISSUE THREAD

**Issue by fishman** [awesomeWM/awesome#1645]
Output of `awesome --version`:

awesome v4.0-305-g2d91d49b (Harder, Better, Faster, Stronger)

I've tried both awesome 4.0 and the latest git. I've tried removing everything and using only the xdg default config. Mod4-t for always on top doesn't work but Mod1-t works. Mod4-Control-t doesn't either, but if I remove the hotkey x passes through t to the client application when i press mod4-t.

So awesome seems to do something with it, but i'm not sure what. I have the same problem with Mod4-n to minimize

      setxkbmap -query
                      
rules:      evdev
model:      pc105
layout:     us,de
variant:    dvorak,
options:    lv3:rwin_switch,apple:badmap,ctrl:nocaps

**Comment by Veratil** [comment]
Possibly related to #1638

**Comment by fishman** [comment]
looks like it
