### ISSUE TITLE
Tag history is not set when awesome (re)starts

### ISSUE THREAD

**Issue by Ram-Z** [awesomeWM/awesome#1651]
Output of `awesome --version`:
awesome v4.0 (Harder, Better, Faster, Stronger)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • RandR 1.5 support: ✔
 • LGI version: 0.9.1

**How to reproduce the issue:**

 * start or restart awesome
 * press <kbd>Mod+2</kbd>
 * press <kbd>Mod+Esc</kbd>

**Actual result:**

Tag 2 is still the current tag.

**Expected result:**

Tag 1 should be the current tag.

**Comment by Veratil** [comment]
I don't think much has been touched with tags since v4 released, but confirmed on v4.0-277-g48ca137 as well.

**Comment by Elv13** [comment]
Related #1493
