### ISSUE TITLE
Cannot open menubar

### ISSUE THREAD

**Issue by boris-petrov** [awesomeWM/awesome#1652]
Output of `awesome --version`:

%  awesome --version
awesome v4.0-310-g4a42ed0d (Harder, Better, Faster, Stronger)
 • Compiled against Lua 5.3.4 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.5
 • LGI version: 0.9.1

(Not sure why, but I can't seem to find such a commit (g4a42ed0d) - anyway, I've compiled from master from commit https://github.com/awesomeWM/awesome/commit/4a42ed0d445ac78ad62d3998dade894ec86c2f01)

**How to reproduce the issue:**

Press the hotkey for opening the menubar.

**Actual result:**

/usr/share/awesome/lib/menubar/utils.lua:309: attempt to call a nil value (field 'escape')

I guess the commit that broke it was this one:
https://github.com/awesomeWM/awesome/commit/2f105eac860d19c186b05a60417a1944e917e1b3

**Comment by Elv13** [comment]
Thanks. Btw 4a42ed0 and 4a42ed0d are the same commit ;)

**Comment by boris-petrov** [comment]
Thanks for the quick fix! Yes, I am stupid sometimes, sorry. :)
