### ISSUE TITLE
fn key crashes awesome wm.

### ISSUE THREAD

**Issue by mail02ankit** [awesomeWM/awesome#1657]
Output of `awesome --version`:
awesome v4.0 (Harder, Better, Faster, Stronger)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • RandR 1.5 support: ✔
 • LGI version: 0.9.1

**How to reproduce the issue:**

When I press fn key (or any other key which is not working in arch for time being) wm crashes. It takes me to the login screen. It looks like somehow  fn or any other special key press is interpreted  as the quit signal. I am using thinkpad T420, and Asus N56JN. Both shows same problem.

**Comment by psychon** [comment]
How do you start awesome? Do you get any messages on awesome's stderr (`ls -l /proc/$(pidof awesome)/fd/2` *might* be helpful in figuring out where these messages go to. This depends on how you start awesome. Possible results are things like `~/.xsession-errors` and `/var/log/gdm.log`)? Does the same also happen with other WMs or without any WM at all? If not: Could you run `xev` in one of these not-exiting cases and show its output for pressing the Fn key?

Normally, the Fn key is not visible to software at all and instead just "does something" inside of the keyboard.

**Comment by mail02ankit** [comment]
Thanks for reply psychon.

I get following when I use the commands:
$ls -l /proc/$(pidof awesome)/fd/2 
~/.xorg.log
$ cat .xorg.log
function spawn_with_shell is deprecated, see awful.spawn.with_shell.... This line I see most in the file.

When I run $xev and press fn, awesome wm stops before I see any output in the terminal. I have other wm installed on my machine (bspwm), fn work fine there. Fine in the sense that it does not kill the wm.

This is how I start awesome in .xinitrc
exec dbus-launch --sh-syntax --exit-with-session awesome

**Comment by mail02ankit** [comment]
I found the mistake. 
"exec awesome" should be used instead of dbus-... option.

Thanks

**Comment by psychon** [comment]
...I read that as "I found a solution". I do not really understand it, but I'll close this as "fixed".
