### ISSUE TITLE
Asking for Function: automatical closing of notifications

### ISSUE THREAD

**Issue by landscape69** [awesomeWM/awesome#166]
some time notifications will be thrown. it woul be nice to have a timer for this notifications, else it waste the screen and need to manually closing by mouse action.

this is annoying. 

http://pix.toile-libre.org/upload/original/1426428215.png

**Comment by actionless** [comment]
i think it's designed like that for error notifications, normal notifications are being closed automatically

**Comment by blueyed** [comment]
@landscape69 
Yes, I think error messages are meant to have no timeout by default - so you won't miss them.

I am closing the issue for now, but please feel free to re-open and argument against it.
