### ISSUE TITLE
~/.cache/awesome/ does not exist => menubar crash while saving menu_count_file

### ISSUE THREAD

**Issue by bew** [awesomeWM/awesome#1663]
Output of `awesome --version`:
```
awesome v4.1-dirty (Technologic)
 • Compiled against Lua 5.3.4 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.5
 • LGI version: 0.9.1
```

**How to reproduce the issue:**

Open the menubar, type anything and press enter

**Actual result:**

```
2017-03-19 18:08:33 W: awesome: luaA_dofunction:77: error while running function!
stack traceback:
	/usr/local/share/awesome/lib/menubar/init.lua:152: in upvalue 'write_count_table'
	/usr/local/share/awesome/lib/menubar/init.lua:176: in function </usr/local/share/awesome/lib/menubar/init.lua:160>
	(...tail calls...)
	/usr/local/share/awesome/lib/awful/prompt.lua:755: in local 'keygrabber_function'
	/usr/local/share/awesome/lib/awful/keygrabber.lua:24: in function </usr/local/share/awesome/lib/awful/keygrabber.lua:21>
error: /usr/local/share/awesome/lib/menubar/init.lua:152: attempt to index a nil value (local 'count_file')
```

**Expected result:**

No error ( _obviously_ )

**Investigations**

As I'm using a tmpfs for my `~/.cache` directory, it is empty on computer start and the directory `~/.cache/awesome` doesn't exists.

The line at `/usr/local/share/awesome/lib/menubar/init.lua:152` is attempting to index a file opened inside this cache directory, thus crash.

**Comment by Elv13** [comment]
Note for myself. The prompt has:

```lua
        if not f then
            local i = 0
            for d in id:gmatch(".-/") do
                i = i + #d
            end
            gfs.mkdir(id:sub(1, i - 1))
            f = assert(io.open(id, "w"))
        end
```

for this. However copy/pasting the code in the menubar isn't such a good idea. GIO has been ways to ensure a file path exist.

**Comment by mvdan** [comment]
> As I'm using a tmpfs for my ~/.cache directory

Have the same setup, experiencing the exact same errors as of recently since switching to v4.1 (not sure if it was present in 4.0). Any workaround until a bugfix is out?

**Comment by psychon** [comment]
@mvdan `io.popen("mkdir -p ~/.cache/awesome")` as the first line in your `rc.lua`.

**Comment by mvdan** [comment]
@psychon much appreciated!
