### ISSUE TITLE
awful.spawn callback not called

### ISSUE THREAD

**Issue by bang-uin** [awesomeWM/awesome#1667]
Output of `awesome --version`:

awesome v4.0 (Harder, Better, Faster, Stronger)
 • Compiled against Lua 5.1.5 (running with Lua 5.1)
 • D-Bus support: ✔
 • execinfo support: ✔
 • RandR 1.5 support: ✔
 • LGI version: 0.9.0

**How to reproduce the issue:**

Add following code and execute.
`awful.spawn("xterm", true, function(c) naughty.notify({text = "Callback"}) end)`

**Actual result:**

xterm executes but the callback function is not called.

**Expected result:**

Callback function should be called.

https://github.com/awesomeWM/awesome/blob/v4.0/lib/awful/spawn.lua#L251
Adds the callback to snid_buffer which in the end should be executed here
https://github.com/awesomeWM/awesome/blob/v4.0/lib/awful/rules.lua#L510
and (for Lua 5.1) here
https://github.com/awesomeWM/awesome/blob/v4.0/lib/gears/protected_call.lua#L31

Not sure where the problem is as it looks ok to me.

**Comment by Elv13** [comment]
Right, `xterm` doesn't support the necessary protocols for callbacks to work. Please use `urxvt` or any `libvte` based terminals (terminator, gnome-terminal, XFCE terminal, etc) instead of `xterm`. `urxvt` is better in every way compared to `xterm`. It is faster, better maintained and has more options/extensions.

There is nothing we can do about xterm, the problem is on "their" side (where "their" is no one, because it's not under active development since 20 years). Closing this.

**Comment by psychon** [comment]
> Not sure where the problem is as it looks ok to me

To add a bit more information here: xterm has `c.startup_id == nil`, i.e. it does not read the necessary environment variable and turns it into a property on its window. That way, we cannot detect that "this new window" belongs to your call to `spawn`.

**Comment by bang-uin** [comment]
Hmm, i tested different applications they all didn't work.
But i see your point. Relying on startup_id is not reliable.

Maybe one of you could give me a hint.
I try to implement a session save/restore feature.
The idea is to save all clients (screens, tags, layout properties) on client appearance/logout and restore them after login. Just like a simple traditional session manager.
Starting the programs works as expected (as long as they have a valid PID) but to restore their layout positions after spawn i need an stable identifier before calling spawn which gets passed to the client and therefore can be used in the manage callback or in awful rules.
Here is an early testing implementation: https://github.com/bang-uin/awesome-sht/blob/master/util/session.lua
This is my first first Lua code, so please be patient with me :)

Any idea?

Thanks

**Comment by psychon** [comment]
> Any idea?

Nothing that works in general. For Xterm, `spawn` gives you the PID of the started process and you can compare this against `c.pid`. However, this does not work in general since some programs have wrapper shell scripts which cause intermediate processes to be started.

**Comment by bang-uin** [comment]
That's what i'm already doing. 
Chroot facilities like firejail are problematic too as they use an `/proc` overlay and therefore the client lies about its PID.

Ok, so stable pre/post spawn identifiers are not possible. Got it :)
Any chance to get the placement of the clients on their tags?
Setting geometry (or size_hints) does not restore the client on its old position for non-floating clients.
For floating clients it sometimes works and sometimes not. Not really reproducible.

**Comment by psychon** [comment]
> Any chance to get the placement of the clients on their tags?
> Setting geometry (or size_hints) does not restore the client on its old position for non-floating clients.

`size_hints` are read-only. The most important input to the layouts is the order of the clients. This can be influenced with `c1:swap(c2)` (swapping two clients). Besides that, all the various tag attributes like e.g. layout and master_width_factor influence the result.

> For floating clients it sometimes works and sometimes not. Not really reproducible.

I would expect this to never work. You are doing `c.geometry = restoredata.geometry` while you want to be doing `c:geometry(restoredata.geometry)` (geometry is not a property, but a function that needs to be called!).

**Comment by bang-uin** [comment]
> This can be influenced with c1:swap(c2) (swapping two clients). Besides that, all the various tag attributes like e.g. layout and master_width_factor influence the result.

So this means that there is no chance to restore a client to bottom_left (assuming tag layout and so on to be the same as before) without doing s swap as i don't see any API to get the placement?
Even if i would use swap i would need to know where each client was placed on save.

> I would expect this to never work. You are doing c.geometry = restoredata.geometry while you want to be doing c:geometry(restoredata.geometry) (geometry is not a property, but a function that needs to be called!).

Ou snap, my fault. Don't why i treated it as a property in restore but using it as a method in save.
Maybe it was just to late yesterday :D

Btw: shall i open a new discussion for that topic?

**Comment by psychon** [comment]
> Even if i would use swap i would need to know where each client was placed on save.

Something like the following gets you the index for a client:
```lua
function get_position(c)
    return awful.util.table.hasitem(client.get(), c)
end
```
However, applying it is a bit harder. Of course, you can just do `c:swap(client.get()[index]` where `index` is the index that you want to assign, but this will change the index of whatever client previously had this index. Also, it only works after all clients are restored (= all programs are restarted).

> Btw: shall i open a new discussion for that topic?

When would that one be closed? This one is already closed, so I don't mind continuing to use it.

**Comment by bang-uin** [comment]
Sounds good but isn't `awful.util.table.hasitem` deprecated?
I also need to consider floating clients and skip their index on relayout.
Thanks!

> However, applying it is a bit harder. Of course, you can just do c:swap(client.get()[index] where index is the index that you want to assign, but this will change the index of whatever client previously had this index. 

There shouldn't be a problem as long as i start from index 1.

> Also, it only works after all clients are restored (= all programs are restarted).

Well it would take two rounds to get everything up and running (first spawn everything / second relayout), but i don't mind waiting a few seconds to automatically restore everything instead of doing it manually (i have a 3 screen multi head with 5 tags each).

**Comment by bang-uin** [comment]
What about passing environment variables to `g_spawn_async_with_pipes` in https://github.com/awesomeWM/awesome/blob/v4.0/spawn.c#L440 to use as an identifier?

**Comment by bang-uin** [comment]
Something like this would do it.

https://github.com/bang-uin/awesome/commit/9e8ea1bce201be624999e527b9102e7bf73ad74c

Now the passed env variable is available and one can create a stable identifier before spawning a process.

**Comment by Elv13** [comment]
cat /proc/`pidof xterm`/environ | grep -E "DESKTOP_STARTUP_ID=.*\0" -ao

Works, but it still wont work if the spawned binary is deamonized/has an unique instance. There is no easy solution for this problem.

**Comment by psychon** [comment]
I was going to suggest `require("lgi").GLib.setenv("FOO", "bar", true)` to set environment variables before starting a process, but that function is not thread-safe. "Awesome is not using threads", you might say, but we cannot be sure that something in Gio/GLib does not create threads behind our back....

**Comment by bang-uin** [comment]
> Works, but it still wont work if the spawned binary is deamonized/has an unique instance.

@Elv13  Could you give me an example of an daemon which start Clients?

Sure, the env solution does not solve everything but i would say that it can handle almost all clients, except for rare cases.

General question: Would you mind to accept a pull request which adds the env ability to awful.spawn? Would make things easier.

**Comment by psychon** [comment]
> @Elv13 Could you give me an example of an daemon which starts clients?

I'm not Elv13, but: `urxvtd` + `urxvtc` do so. Also, I think `evince` sometimes does something like this. I am quite sure that browsers do so, at least if you give them the command line flag saying "open in existing browser window".

**Comment by Elv13** [comment]
> I was going to suggest require("lgi").GLib.setenv("FOO", "bar", true) to set environment variables 
> before starting a process, but that function is not thread-safe. "Awesome is not using threads", you 
> might say, but we cannot be sure that something in Gio/GLib does not create threads behind our back....

No need, we already set `DESKTOP_STARTUP_ID`. I guess someone *could* implement a fallback for `startup_id` by reading the process `environ`. It would "fix" it for xterm and most KF5 based apps. But, as you said, it would not work for firefox/chrome/other. This would be nice because it would keep an unified code path for this sort of things. A nasty side effect would be when a spawned `pid` start spawing clients on its own. In that case, they will inherit the same variable over and over again, so Awesome would have to blacklist them internally. Any other possible bad side effects?

**Comment by bang-uin** [comment]
I appreciate that you like my idea :)

As i said, even if it doesn't work in all cases, it would catch more then now.

> ... so Awesome would have to blacklist them internally

I simple mapping table (startup id/pid) should be enough to ignore spawned childs, or?

So what's the conclusion? You will implement the possibility to pass env vars to the variuos `awful.spwan` implementations or would you also (as you know Awesome better then me) implement a session restore feature?

**Comment by Elv13** [comment]
> the possibility to pass env vars to the variuos awful.spwan implementations

While this is possible, you don't need it for this feature. We *already* add a variable called `DESKTOP_STARTUP_ID`. The FreeDesktop startup notification protocol states that the client should read this variable and set it as an X property (X11 own "env" variables). The bug here is that some clients don't do it. Either because the are older (xterm) or the maintainer doesn't care about fixing X11 bugs anymore (KF5/Qt5) because Wayland is the *Future*.

> would you also (as you know Awesome better then me) implement a session restore feature?

No. I don't have time for this anytime soon. I just signed a new contract and it hopefully will keep me very busy for a long time. I think the other maintainers are all in the same position. You can implement this feature in `rc.lua`. The only change that's required in Awesome itself will be to make `startup_id` read/write instead of read-only.

**Comment by bang-uin** [comment]
> Awesome itself will be to make startup_id read/write instead of read-only.

If by read/write you mean that i can pass my own startup_id to spawn (which would literally be the same amount of work as passing env) i am good to go.

**Comment by Elv13** [comment]
> i can pass my own startup_id to spawn

No, Awesome already pick one for you. Those IDs have a specific format and better let the code choose them. I was talking about the **client** `startup_id` property. Not the spawn own internal one. The spawn API already returns the startup id as the second(?) return argument. The only part that need to be done is in the "new" signal (or "manage", but that's a little too late), parse the `environ` and get the ID.

**Comment by bang-uin** [comment]
I know that Awesome already generates on and yes it is the second return value but that means that the session implementation highly relies on the `DESKTOP_STARTUP_ID` set by Awesome. To be honest, i would prefer to generate and use my own.

> parse the environ and get the ID

Already doing this. Right now. But i think giving everyone else also the possibility to set environ vars is useful. Implementing this is just the matter of adding a few lines in 2 files. Anyway, if your are open for a pull request i'll create one if not we can stop the discussion and i'll use the `DESKTOP_STARTUP_ID` or my own patchset.

**Comment by Elv13** [comment]
> To be honest, i would prefer to generate and use my own.

But one is a standard and "your own" is not ;). Also, by using `DESKTOP_STARTUP_ID`, you fix existing bugs in other part of the code that rely on it. With "your own", you duplicate an existing system instead of fixing it.

**Comment by bang-uin** [comment]
> you fix existing bugs 

I'm not fixing anything i'm just _reading_ the `DESKTOP_STARTUP_ID`. The bugs do still exist.

As you are not answering my question about the pull request i assume you don't want it. So let us close this.

**Comment by Elv13** [comment]
> As you are not answering my question about the pull request i assume you don't want it. So let us close this.

Unless I am not mistaken, the patch above doesn't address my concerns. What you propose is to fix the issue on the spawn side of the sequence diagram. I disagree with this approach and point out that the issue is, in my opinion, better addressed if the "session check" is performed once the client object is created. As I said, it has the following advantages over your solution;

 * It complement nicely with an existing specification rather than re-inventing anything
 * It re-use existing Awesome code
 * It fixes feature like "spawn with properties" and the callbacks that would otherwise not work because the `startup_id` is missing.

The third point is the bug you reported here before talking about the ENV patch. I *am* answering your questions. Whether or not you agree with my answers is something else.

**Comment by bang-uin** [comment]
> the patch above doesn't address my concerns

I'm not sure about which concerns you are talking. I just proposed an enhancement to be able to set env vars for a spawning process. It could be anything, like a special library path or in my case an identifier. Nothing more.

> What you propose is to fix the issue on the spawn side of the sequence diagram.

Yes, that's true, because not all spawning clients do respect the startup notification. 

> I disagree with this approach and point out that the issue is, in my opinion, better addressed if the "session check" is performed once the client object is created.

The session restore consists of 3 steps. 
Step 1 spawn the clients 
Step 2 collect the spawned clients <---- Needs a stable identifer to identify clients spawned in step 1
Step 3 relayout all clients

Sure, in step 2 i can read the `DESKTOP_STARTUP_ID` from eviron which is recorded by step 1 as a result of the spawn. I just pointed out that i would prefer to use my own pre-allocated identifiers.

 > It fixes feature like "spawn with properties" and the callbacks that would otherwise not work because the startup_id is missing.

Why should the `startup_id` be missing by applying my patch? The patch replicates the parents environment and just adds the passed env vars. Nothing gets lost and no behavior gets changed.

> The third point is the bug you reported here before talking about the ENV patch. 

Didn't get that. What is the problem with reporting that? You told me that it's not a bug and closed the issue. I did not ask to reopen it. Au contraire, i asked if i should open a new discussion ticket about how to achieve the session save/restore. The env patch was just the outcome of one night trial/error/research. I just thought that it could be helpful for others too.

> I am answering your questions. Whether or not you agree with my answers is something else.

Where did i say that i disagree with your answers? I think you getting me totally wrong.

We are talking about the env patch since yesterday and i just wanted to end the discussion by either providing a pull request (if you would accept it) or by dismissing the idea. That's why i asked two times but didn't get any answer on that. So i ended the discussion by using the fallback -> dismiss :)

**Comment by blueyed** [comment]
@bang-uin 
> But i think giving everyone else also the possibility to set environ vars is useful. Implementing this is just the matter of adding a few lines in 2 files. Anyway, if your are open for a pull request i'll create one

Do you have that patch available somewhere online?

I think there was some misunderstanding between @Elv13 and you, and I think a PR to allow setting env vars via snid in awesome makes sense.
I assume it works by handling this in the already existing callback handler, i.e. by passing a list of env vars you want to set, similar to how you provide rules already?

**Comment by bang-uin** [comment]
@blueyed 

> Do you have that patch available somewhere online?

This is the corresponding commit.

https://github.com/bang-uin/awesome/commit/9e8ea1bce201be624999e527b9102e7bf73ad74c

**Comment by blueyed** [comment]
@bang-uin 
Thanks.
Why do you use `parse_command`?
The env gets passed as a string ("FOO=foo BAR=bar") then I assume?

I think it makes sense to include it, and it would be nice if you could provide a PR to discuss this further.
/cc @psychon

**Comment by psychon** [comment]
> /cc @psychon

Idea seems fine to me, but the patch introduces memory leaks (first the command, then the env is parsed; if parsing the env fails then the command is leaked). To simplify the C code, I would to more of this in Lua: `require("lgi").GLib.listenv()` and `.getenv("HOME")` are accessible, so that part can be done in Lua and gets automatically GC'd.

> Why do you use parse_command?

Let me guess: Because that function already exists and handles turning `{ "foo", "bar", "baz" }` into a `char**`.


@bang-uin Do you want to submit a PR for this or should I do this?

**Comment by bang-uin** [comment]
@psychon It was just a quick patch to get the desired functionality. I didn't work on that since the discussion here ended. Feel free to do a PR by yourself as you know the code better.
