### ISSUE TITLE
Vmware, icons fail to render after full-screened

### ISSUE THREAD

**Issue by strayArch** [awesomeWM/awesome#1669]
Output of `awesome --version`:

awesome v4.0 (Harder, Better, Faster, Stronger)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • RandR 1.5 support: ✔
 • LGI version: 0.9.1

**How to reproduce the issue:**

Start awesome: `awesome --no-argb` or `awesome`
Start VMware Workstation 12.5.2 build-4638234: `vmware`
`Ctrl+Alt+Return` to make the client full screen
Switch to another workspace and back

**Actual result:**

![Link to screen shot of failed rendered state](http://stro.nz/public/vmware.png)
If fails to render w/ workaround, then this results.
![Link to screen shot of failed rendered state](http://stro.nz/public/vmware3.png)

**Expected result:**

The following result can be obtained by running `Ctrl+Alt+Return` twice. But, it will fail to render again if workspaces are switched.
![Link to screen shot of expected rendered state](http://stro.nz/public/vmware2.png)

**Comment by psychon** [comment]
This has Qt involved, right? There was/is somewhere an issue where Qt did something wrong. Wasn't that with VMware? I'm not sure and do not have the time right now to look it up.

Besides that: No idea. Did this work in older versions of awesome?

**Comment by Elv13** [comment]
> I'm not sure and do not have the time right now to look it up.

https://www.virtualbox.org/ticket/15863

**Comment by strayArch** [comment]
The dependencies:
fuse2 - for vmware-vmblock-fuse
gksu - for root operations (memory allocations, registering license, etc.)
gtkmm - for the GUI
linux-headers - for module compilation
ncurses5-compat-libsAUR - needed by the --console installer

**Comment by strayArch** [comment]
Issue resolved in updates.
