### ISSUE TITLE
Asking for Moon calendar for Asian 

### ISSUE THREAD

**Issue by landscape69** [awesomeWM/awesome#167]
I need a Moon Calendar, which show up the calendar http://en.wikipedia.org/wiki/Lunisolar_calendar

its possible to realize it in additon to the currentyl existing calendar?

this is f.e.: es js code for such kind od calendar: http://kde-apps.org/content/show.php/Vietnamese+lunar+calendar?content=150816

**Comment by blueyed** [comment]
> currently existing calendar

Which one are you referring to?
AFAIK awesome does not ship any calendar..

**Comment by landscape69** [comment]
my mistake

i use this theme https://github.com/Elv13/awesome-configs


there is a calendar. and want to ask for one
