### ISSUE TITLE
awful.spawn.with_line_callback cuts off everything after the first blank line

### ISSUE THREAD

**Issue by Taywee** [awesomeWM/awesome#1671]
Output of `awesome --version`:

```
awesome v4.0 (Harder, Better, Faster, Stronger)
 • Compiled against Lua 5.1.4 (running with LuaJIT 2.0.4)
 • D-Bus support: ✔
 • execinfo support: ✔
 • RandR 1.5 support: ✔
 • LGI version: 0.9.0
```

**How to reproduce the issue:**

I put this in my config:

```lua
io.open('/tmp/testfile.txt', 'w'):close()
awful.spawn.with_line_callback({'printf', [[%s %s\n%s\n%s\n\n%s\n%s]], '1', '2', '3', '4', '5', '6'}, {
  stdout=function(line)
    local file = io.open('/tmp/testfile.txt', 'a')
    file:write('stdout: ' .. line .. '\n')
    file:close()
  end,
  stderr=function(line)
    local file = io.open('/tmp/testfile.txt', 'a')
    file:write('stderr: ' .. line .. '\n')
    file:close()
  end,
  output_done=function()
    local file = io.open('/tmp/testfile.txt', 'a')
    file:write('output_done\n')
    file:close()
  end,
  exit=function(reason, code)
    local file = io.open('/tmp/testfile.txt', 'a')
    file:write(table.concat{'exit reason=', reason, ', code=', code, '\n'})
    file:close()
  end
})
```

And I restarted awesome.

**Actual result:**

```sh
$ cat /tmp/testfile.txt
exit reason=exit, code=0
stdout: 1 2
stdout: 3
stdout: 4
output_done
```

**Expected result:**

All the lines of the stdout should be present, but everything after the double-newline gets cut off.  If I remove the double-newline, all the output is present as expected.  Any other commands that I use that have a double-newline anywhere in the input have the same result.

**Comment by psychon** [comment]
Could you check awesome's stderr, please? (Hopefully `ls -l /proc/$(pidof awesome)/fd/2` provides a hint on where that goes to). If you see the following warning at the beginning (basically first thing when awesome starts), then you successfully discovered that we cannot distinguish between EOF and just an empty line with your version of LGI. Either upgrade or downgrade LGI (no, I do not remember right know which versions have this problem; I have lgi 0.9.1 here).
```
Cannot reliably detect EOF on an GIOInputStream with this LGI version
```
By the way, I get the following output here:
```
$ cat /tmp/testfile.txt 
exit reason=exit, code=0
stdout: 1 2
stdout: 3
stdout: 4
stdout: 
stdout: 5
stdout: 6
output_done
```
