### ISSUE TITLE
draw_test_cairo_xcb: invalid value for an input cairo_format_t

### ISSUE THREAD

**Issue by lucasvr** [awesomeWM/awesome#1680]
Output of `awesome --version`:
 v4.0 (Harder, Better, Faster, Stronger)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • RandR 1.5 support: ✔
 • LGI version: 0.9.1

**How to reproduce the issue:**

Just fire up "exec awesomewm" on .xinitrc. The following Xorg configuration is in place:

[ 16372.929] (==) FBDEV(0): Depth 8, (==) framebuffer bpp 8
[ 16372.929] (==) FBDEV(0): Default visual is PseudoColor
[ 16372.929] (==) FBDEV(0): Using gamma correction (1.0, 1.0, 1.0)
[ 16372.929] (II) FBDEV(0): hardware: NV1d (video memory: 65536kB)
[ 16372.929] (II) FBDEV(0): checking modes against framebuffer device...
[ 16372.929] (II) FBDEV(0): checking modes against monitor...
[ 16372.929] (--) FBDEV(0): Virtual size is 1280x1024 (pitch 1280)
[ 16372.929] (**) FBDEV(0):  Built-in mode "current": 108.0 MHz, 64.0 kHz, 60.0 Hz
[ 16372.929] (II) FBDEV(0): Modeline "current"x0.0  108.00  1280 1328 1440 1688  1024 1025 1028 1066 +hsync +vsync -csync (64.0 kHz b)
[ 16372.929] (==) FBDEV(0): DPI set to (96, 96)

**Actual result:**

Get an error when draw_test_cairo_xcb() is called:
 
2017-03-29 07:00:31 E: awesome: draw_test_cairo_xcb:306: Could not set up display: got cairo surface with status invalid value for an input cairo_format_t
xinit: connection to X server lost

**Expected result:**

Have a successful awesomewm session

**Comment by psychon** [comment]
> [ 16372.929] (==) FBDEV(0): Depth 8, (==) framebuffer bpp 8

It seems like cairo-xcb does not support displays with just 8 bpp / 256 colors. Do you *really* indent to just have so few colors?

**Comment by lucasvr** [comment]
Xorg's video driver failed to load, so the server fell back to FBDEV with a low number of colors. I have just checked and Cairo's CAIRO_FORMAT_A8 does not stand for 8BPP, as I presumed, but rather it's used as an alpha channel. So this is not a bug with Awesome, but rather a limitation of Cairo.
Thanks for having looked at this. I'm closing the bug now.
