### ISSUE TITLE
Control + Alt + Delete keybinding

### ISSUE THREAD

**Issue by aidanharris** [awesomeWM/awesome#1684]
Output of `awesome --version`:

awesome v4.0 (Harder, Better, Faster, Stronger)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • RandR 1.5 support: ✔
 • LGI version: 0.9.1

**How to reproduce the issue:**

I'd like to use the `Control + Alt + Delete` keybinding to lock my screenlocker. Previously I was using `modkey + L` but realised recently that this conflicts with the keybinding to increase the master width factor. I've tried using both keycodes and keynames as follows but it doesn't seem to work:

```lua
awful.key({ "#37", "#64" }, "#119", function ()
  awful.util.spawn( screenlocker_lock )
  end,
  {description = "lock computer", group = "screenlocker"}
),
```

```lua
awful.key({ "Control_L", "Alt_L" }, "Delete", function ()
  awful.util.spawn( screenlocker_lock )
  end,
  {description = "lock computer", group = "screenlocker"}
),
```

**Actual result:**

The above does not seem to work. Interestingly enough, if I double-tap the delete key it seems to work, completely ignoring the fact that the `Control_L` and `Alt_L` keys are not being held.

**Expected result:**

Work as expected...

**Comment by Elv13** [comment]
First, Alt is "mod1", not "Alt_L". Also, where is `screenlocker_lock`
defined? Because right now it is a variable, not a command. Also, please
use `awful.spawn` instead of `awful.util.spawn`. The later is deprecated.

**Comment by aidanharris** [comment]
@Elv13 You are correct that screenlocker_lock is a variable. I didn't bother adding it to the issue since I didn't think it was relevant what it is defined as. It's just a command to call gnome screenlocker defined here:

https://github.com/aidanharris/awesome-config/blob/master/rc.lua#L116-L118

**Comment by aidanharris** [comment]
Using "Mod1" fixed it as follows:

```lua
awful.key({ "Control", "Mod1" }, "Delete", function ()
  awful.util.spawn( screenlocker_lock )
  end,
  {description = "lock computer", group = "screenlocker"}
),
```

@Elv13 Thanks for the help.

**Comment by psychon** [comment]
I'll add some explanation: The first argument to `awful.key` is a list of modifiers, the second is a key. Modifiers and keys are not the same. For example, both your left (`Shift_L`) and right (`Shift_R`) shift key (likely) activate the shift modifier (`Shift`).
Only actual modifiers can be used in the first argument. Arbitrary keys do not work.

**Comment by Ryuno-Ki** [comment]
@psychon In other words I can't define two different keystrokes using Ctrl-L and Ctrl-R respectively. Am I right?

**Comment by Elv13** [comment]
You can rebind the second CTRL to mod5 or iso level 3, then you can use them, but they wont be CTRL anymore (other apps will see them as whatever you binded them to)
