### ISSUE TITLE
rules added to hotkeys_poppup.group_rules are ignored

### ISSUE THREAD

**Issue by barjo** [awesomeWM/awesome#1694]
Output of `awesome --version`:

awesomeawesome v4.1 (Technologic)
 • Compiled against Lua 5.2.4 (running with Lua 5.2)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.4
 • LGI version: 0.9.0

**How to reproduce the issue:**

In `firefox.lua`

```lua
local hotkeys_popup = require("awful.hotkeys_popup.widget")
local fire_rule = {class={"Firefox"}}
for group_name, group_data in pairs({
  ["Firefox: tabs"] = { color="#009F00", rule_any=fire_rule }
}) do
  hotkeys_popup.group_rules[group_name] = group_data
end
local firefox_keys = { ["Firefox: tabs"] = {{modifiers = {"Mod1"}, keys = { ["1..9"]="go to tab" } }
hotkeys_popup.add_hotkeys(firefox_keys)
```

in `rc.lua`

```lua
require("awful.hotkeys_popup.keys.vim")
require("keys/firefox")
```

**Actual result:**

Firefox group_rules are ignored. 
So when showing the hotkeys, firefox hot-keys will always be present.
Only vim rules are defined in the default widget instance. 

**Expected result:**
The rules should be taken into account, the firefox hotkeys should be shown only while on Firefox.

**Solution?**
A solution would be to add a  `add_group_rule` method  in `hotkeys_popups/widget.lua` that delegates to the default widget instance. 

```lua
    function widget_instance:add_group_rule(group, rules)
      self.group_rules[group] = rules
    end
    return widget_instance
end
-- ...
-- ...
function widget.add_group_rule(...)
    return get_default_widget():add_group_rule(...)
end

return widget
```

**Comment by psychon** [comment]
> Only vim rules are defined in the default widget instance.

I fail to understand this one. Does this mean "The vim rules work fine, my firefox rules does not?"

**Comment by barjo** [comment]
Hi, sorry for the confusion. 

In the default `rc.lua` `require("awful.hotkeys_popup.keys.vim")` add the hotkeys for `vim` with the proper awful rules that ensure the `vim` hotkeys are shown only when using vim. 

I added `require("keys/firefox.lua") that contains hotkeys for firefox, just after that require. The firefox hotkeys are properly shown, but all the time, the awful rule that I added to `hotkeys_popup.group_rules` in the `firefox.lua` are not added to the `hotkeys_popup` widget default instance. 

If I require `firefox.lua` first, then the rules will be added to the default instance, but the vim ones won't be.

**Comment by actionless** [comment]
please share your `keys/firefox.lua`

**Comment by actionless** [comment]
proposed solution looks fine to me, are you going to prepare a PR with the described changes?

**Comment by barjo** [comment]
:+1: I will make a PR during the week.

**Comment by actionless** [comment]
Thank you for contributing in both finding and resolving the issue!

**Comment by barjo** [comment]
No pb! Thanks for keeping awesome awesome ;D
