### ISSUE TITLE
Improvement: consider adding version check to awesome config files

### ISSUE THREAD

**Issue by latach** [awesomeWM/awesome#1702]
I recently had the issue #1695. It was due to an old config file being used by a newer version of awesome.

My suggestion is to add a single *config_document_version* line to the top of the config file.

Awesome will check for the version of the document. If it is not a match, then the config file gets discarded instead of just being used as in #1695.

**Comment by psychon** [comment]
> if it is not a match, then the config file gets discarded instead of just being used 

Just ignoring the config breaks backwards compatibility: People will likely just copy that check to their `~/.config/awesome/rc.lua` and when they upgrade their config is being ignored even though it might "just work" otherwise.

**Comment by Veratil** [comment]
Unfortunately the config breakage was a side-effect of the massive upgrade (2000+ commits) from 3.5 to 4.0. As Awesome goes forward it's sticking much closer to API compatibility than before, so this hopefully shouldn't happen moving forward.

The biggest hiccups from 3.5 to 4.0 are from changing much of the core API functionality. If you look now any 3rd party modules using the old API will be generating deprecation warnings for things deprecated in 4.0. Once 5.0 releases (much later) there will be more API deprecation warnings that are already set to show up (you can do a grep for `deprecated_in=5` to see everything currently).

We're still ironing out the deprecation system to get it where it needs to be, but from 4.0 forward there will be much less of a chance of breaking like the 3.5 to 4.0 update did. This means there's no need to add a versioning line to the config.

Obviously this doesn't mean mistakes could be made; no one's perfect after all. :smile:

**Comment by latach** [comment]
Thank you both. I'll close the issue now.
