### ISSUE TITLE
Can `naughty.replace_text` also update widget size?

### ISSUE THREAD

**Issue by coldfix** [awesomeWM/awesome#1707]
Output of `awesome --version`:

```
awesome v4.0-244-ga4b06bca (Harder, Better, Faster, Stronger)
 • Compiled against Lua 5.3.4 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.5
 • LGI version: 0.9.1
```

**How to reproduce the issue:**

```
n = naughty.notify { text="foo", timeout=0 }
naughty.replace_text(n, "foo", "bar")
```

**Actual result:**

notification stays at original size, only `foo` is displayed.

**Expected result:**

notification is resized to fit the new text.

**Comment by Elv13** [comment]
It will require some work. Currently, the code that compute the popup (wibox) size is part of the `notify` function. It will need to be extracted into its own local function. Then that function needs to be called from `replace_text`. I don't have time right now, but feel free to try and submit a pull request. It isn't very complicated, it's just moving code around. Also make sure you take into account the possible existance of other wibox/popup above and below the one you change.
