### ISSUE TITLE
Inconsistent signal documentation

### ISSUE THREAD

**Issue by psychon** [awesomeWM/awesome#1714]
https://github.com/awesomeWM/awesome/issues/1683#issuecomment-292716866

> I think the documentation could be more consistent here, some examples from different classes:
> - `drawable`: the property change signals are documented in the "Signals" section, no documentation of the properties themselve
> - `client`: documented for each individual property; four properties additionaly in the "Signals" section
> - `wibox`: documented for each individual property; no signals section
> - `wibox.widget.slider` not documented; same for the other `wibox.widget.*` classes

CC @jandob (just so that you know what happened to your comment)

**Comment by Elv13** [comment]
Added to https://github.com/awesomeWM/awesome/issues/1373 (central repository of doc issues)
