### ISSUE TITLE
Completion in prompt produces gibberish

### ISSUE THREAD

**Issue by jhaagmans** [awesomeWM/awesome#1719]
Output of `awesome --version`:
`awesome v4.1 (Technologic)
 • Compiled against Lua 5.3.4 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.5
 • LGI version: 0.9.1`

Whenever I use the promt and press <TAB> to complete the command (e.g. `fire` to `firefox`), all text in the prompt gets replaced with gibberish. I'm unable to copy the gibberish, but it's something like `\[0m\;1,36m\\\\\\\\\\\-\\\\\\\\\\\[0m` with some characters in unreadable encoding in there.

I tried running the following lua code from the lua execute thingy:
`require("naughty").notify({ text = require("awful.completion").shell('fire', 5, 5, 'bash' })`

And a nice notification with `firefox` pops up. So the code for completion does seem to work.

Does anyone have any clue where to look?

**Comment by psychon** [comment]
What happens when you run the following? (I just changed 'bash'  to 'zsh' )

`require("naughty").notify({ text = require("awful.completion").shell('fire', 5, 5, 'zsh' })`

Also, what output do you get for `require("naughty").notify{ text = os.getenv("SHELL") }`?

**Comment by jhaagmans** [comment]
Oooh wait. I use `zsh`, I just assumed that because the prompt seemed to be running in bash (I was able to go to the start of the line with `ctrl-a`), the command would also be sent using a bash shell.

I can reproduce the behaviour by replacing `'bash'` with `'zsh'`. The last command you sent returns `zsh`. I still have no clue how to fix this though...

Thanks for your time!

**Comment by psychon** [comment]
> the prompt seemed to be running in bash 

Heh. :-) If only things were so simple.... Someone had lots of fun reimplementing basically everything.

> I still have no clue how to fix this though...

An ugly (but possibly working) hack would be the following (it might be necessary to do this at the beginning of your config, before any other `require()` calls):
```lua
do
  local com = require("awful.completion")
  local shell = com.shell
  com.shell = function(command, cur_pos, ncomp, shell)
    return shell(command, cur_pos, ncomp, "bash")
  end
end
```

However, *why* does the completion break for you when using zsh? Could you run the following and show the result?
```sh
zsh -c 'local -a res; res=( "${(k)commands[@]}" "${(k)aliases[@]}" "${(k)builtins[@]}" "${(k)functions[@]}" "${(k)reswords[@]}" ${PWD}/*(:t) ); print -ln -- ${(M)res[@]:#firef*}'
```
(I changed "fire" to "firef"; for me this results in just "firefox" as output)

**Comment by blueyed** [comment]
Maybe there is something weird in your zshrc?
Are we using "zsh -i" maybe also when querying the completions?

**Comment by jhaagmans** [comment]
Sorry it took me a week to reply. I've looked at the output of the command @psychon provided (thanks!) and noticed that, apart from the phrase `firefox`, it also produced the full output of the `screenfetch` command which was in my `.zshenv` file. Moving that to `.zshrc` (not sure why it was in `.zshenv`) fixed the issue. Thanks a lot for your help!

**Comment by blueyed** [comment]
Ok, thanks for reporting back.
I've played around today to improve the completions for Zsh (based on https://github.com/Valodim/zsh-capture-completion), and it looks nice already: it will e.g. complete Firefox profile names after `firefox -P ` and all the other nice things that Zsh provides - so stay tuned.. ;)
