### ISSUE TITLE
The auto-completion of mod+r luncher doesn't work with zsh

### ISSUE THREAD

**Issue by YuanPre** [awesomeWM/awesome#1734]
Output of `awesome --version`:

awesome v4.1 (Technologic)
 • Compiled against Lua 5.3.4 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.5
 • LGI version: 0.9.1

**How to reproduce the issue:**

I use`·mod + r` to open a program and want to type the tab key for auto-completion.

**Actual result:**
When my home directory does not have anything, it will not be completed, and output error log in `$HOME/.xsession-errors`.
the error log is :` zsh:1: no matches found: /home/tlmf/*(:t)`
**Expected result:**

It should output complete information

**Other imformation**
I use the Z shell.This problem does not occur when using bash.
But I use zsh + i3wm will not have this problem
The `$HOME/.xsession-errors` is in here

[xsession-errors.txt](https://github.com/awesomeWM/awesome/files/925135/xsession-errors.txt)

**Comment by blueyed** [comment]
This should fix it:
```diff
diff --git i/lib/awful/completion.lua w/lib/awful/completion.lua
index 2777cd43..a550988f 100644
--- i/lib/awful/completion.lua
+++ w/lib/awful/completion.lua
@@ -108,7 +108,7 @@ function completion.shell(command, cur_pos, ncomp, shell)
             "res=( "..
             "\"${(k)commands[@]}\" \"${(k)aliases[@]}\" \"${(k)builtins[@]}\" \"${(k)functio
             "\"${(k)reswords[@]}\" "..
-            "${PWD}/*(:t)"..
+            "${PWD}/*(N:t)"..
             "); "..
             "print -ln -- ${(M)res[@]:#" .. string.format('%q', words[cword_index]) .. "*}'"
         end
```

**Comment by blueyed** [comment]
@YuanPre 
Can you test if #1736 works for you, please?

**Comment by YuanPre** [comment]
@blueyed I dont't use the GitHub version. I used Arch Linux to package the binary version. Which file should I change?

**Comment by YuanPre** [comment]
@blueyed  Thank you !
I changed you said part of `/usr/share/awesome/lib/awful/completion.lua`. Then, it works.
If this change does not raise other bugs, I recommend adding this change to the next stable version.
After all, the $HOME directory is not always a file every time ah.
I live in China, because the time difference is not timely reply to you, I am sorry.
And...Sorry for my English.I only use Google translation to speak English
