### ISSUE TITLE
Notifications flickers and are unreadable when replaced quickly

### ISSUE THREAD

**Issue by bew** [awesomeWM/awesome#1737]
Output of `awesome --version`:
```
awesome v4.1-40-ga87387d9-dirty (Technologic)
 • Compiled against Lua 5.3.4 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.5
 • LGI version: 0.9.1
```

**How to reproduce the issue:**

I'm using compton to have a little fade in/out when clients appear/disappear, and the flickering makes notifications impossible to read, but I still want the fade in/out animation when creating/destroying the notification, but not when replacing it!

Here is a little example of a counter in a notification that increase on each invocation:
```lua
local test_id
local test_counter = 0
local function test()
	test_id = naughty.notify({
		text = "counter is " .. test_counter,
		replaces_id = test_id,
	}).id
	test_counter = test_counter + 1
end

globalkeys = awful.key({"Mod4"}, "e", test)
```
Then press `Mod4+e` 10 seconds then release.

**Actual result:**

- Without compton, there is a little flickering, but the counter in the notification is still readable.
- With compton, the flickering is faster than the animation, and the notification is not readable bofore it's replaced by the next one..

**Expected result:**

No flickering:

- **On first notification appearance**: fade in
- **On replace**: recalculate the size & position, apply (without flickers)
- **On timeout or anything**: fade out

**Fix**

I made a patch for this:
```diff
diff --git a/lib/naughty/core.lua b/lib/naughty/core.lua
index 98afd2e8..61cfcc1d 100644
--- a/lib/naughty/core.lua
+++ b/lib/naughty/core.lua
@@ -140,7 +140,8 @@ naughty.notificationClosedReason = {
     expired = 1,
     dismissedByUser = 2,
     dismissedByCommand = 3,
-    undefined = 4
+    replaced = 4,
+    undefined = 5
 }
 
 
@@ -334,8 +335,9 @@ end
 --
 -- @param notification Notification object to be destroyed
 -- @param reason One of the reasons from notificationClosedReason
+-- @param fake If true, do not make the notification invisible
 -- @return True if the popup was successfully destroyed, nil otherwise
-function naughty.destroy(notification, reason)
+function naughty.destroy(notification, reason, fake)
     if notification and notification.box.visible then
         if suspended then
             for k, v in pairs(naughty.notifications.suspended) do
@@ -350,8 +352,12 @@ function naughty.destroy(notification, reason)
         if notification.timer then
             notification.timer:stop()
         end
-        notification.box.visible = false
-        arrange(scr)
+
+        if not fake then
+            notification.box.visible = false
+            arrange(scr)
+        end
+
         if notification.destroy_cb and reason ~= naughty.notificationClosedReason.silent then
             notification.destroy_cb(reason or naughty.notificationClosedReason.undefined)
         end
@@ -553,7 +559,7 @@ function naughty.notify(args)
         local obj = naughty.getById(args.replaces_id)
         if obj then
             -- destroy this and ...
-            naughty.destroy(obj, naughty.notificationClosedReason.silent)
+            naughty.destroy(obj, naughty.notificationClosedReason.replaced, true)
         end
         -- ... may use its ID
         if args.replaces_id <= counter then
```
I can make a PR if needed! (current branch: [naughty-no-flickering](https://github.com/bew/awesome/tree/naughty-no-flickering))

What do you think ?

**Comment by psychon** [comment]
> What do you think ?

- What is the difference between the `replaced ` reason and the `silent` one?
- Doesn't you patch just cause the old notification to be leaked? (It stays visible, after all, does it not?)
- Naughty needs a rewrite so that `replaces_id` becomes less of a hack
- My stomach hurts

**Comment by bew** [comment]
> What is the difference between the `replaced` reason and the `silent` one?

The semantics, when writing/reading a destroy callback, I find it better to check if the reason is `replaced` than `silent`, because I don't really know when could `silent` be set, but I know when `replaced` is.
> Doesn't you patch just cause the old notification to be leaked? (It stays visible, after all, does it not?)

I don't think so (didn't checked), yes it stays visible, but it's just reused, not forgotten, when the 'new' notification (which is also the old one, as it's being reused) will be destroyed, it'll then be collected by the gc.
> Naughty needs a rewrite so that `replaces_id` becomes less of a hack

Good to know
> My stomach hurts

I hope you're going well, or at least better now!

**Comment by psychon** [comment]
> >  What is the difference between the replaced reason and the silent one?
>
> The semantics, when writing/reading a destroy callback, I find it better to check if the reason is > replaced than silent, because I don't really know when could silent be set, but I know when replaced is.

Normally when sending a notification via DBus, naughty sends an event back for "your notification was closed". `silent` only exists to suppress this notification (which is also why it has value -1).
Your patch is removing the only use of `silent` and instead makes us send an `undefined` close reason (that's the defined meaning of number 4 I guess) and `undefined` becomes some value which is not mentioned in the relevant dbus specification at all.

> I don't think so, yes it stays visible, but it's just reused (didn't checked),

That would be the right thing to do. However, all that naughty currently does with `replaces_id` is to delete that other notification and make the new one take its position. That's also why you get some flickering.

Making it reused properly would avoid this problem. So, to add some more hacks (e.g. shape or background color can no longer changed when using `replaced_id`), how about the following? (Didn't test and no time to do so; also this needs API doc for this new parameter):
```diff
diff --git a/lib/naughty/core.lua b/lib/naughty/core.lua
index abe0696..b511102 100644
--- a/lib/naughty/core.lua
+++ b/lib/naughty/core.lua
@@ -335,7 +335,7 @@ end
 -- @param notification Notification object to be destroyed
 -- @param reason One of the reasons from notificationClosedReason
 -- @return True if the popup was successfully destroyed, nil otherwise
-function naughty.destroy(notification, reason)
+function naughty.destroy(notification, reason, hide)
     if notification and notification.box.visible then
         if suspended then
             for k, v in pairs(naughty.notifications.suspended) do
@@ -350,8 +350,10 @@ function naughty.destroy(notification, reason)
         if notification.timer then
             notification.timer:stop()
         end
-        notification.box.visible = false
-        arrange(scr)
+        if hide then
+            notification.box.visible = false
+            arrange(scr)
+        end
         if notification.destroy_cb and reason ~= naughty.notificationClosedReason.silent then
             notification.destroy_cb(reason or naughty.notificationClosedReason.undefined)
         end
@@ -549,11 +551,13 @@ function naughty.notify(args)
     local notification = { screen = s, destroy_cb = destroy_cb, timeout = timeout }
 
     -- replace notification if needed
+    local old_box
     if args.replaces_id then
         local obj = naughty.getById(args.replaces_id)
         if obj then
             -- destroy this and ...
-            naughty.destroy(obj, naughty.notificationClosedReason.silent)
+            naughty.destroy(obj, naughty.notificationClosedReason.silent, false)
+            old_box = obj.box
         end
         -- ... may use its ID
         if args.replaces_id <= counter then
@@ -684,6 +688,7 @@ function naughty.notify(args)
                                shape_border_width = shape and border_width,
                                shape = shape,
                                type = "notification" })
+    if old_box then notification.box = old_box end
 
     if hover_timeout then notification.box:connect_signal("mouse::enter", hover_destroy) end
 
```

**Comment by bew** [comment]
> Normally when sending a notification via DBus, naughty sends an event back for "your notification was closed". silent only exists to suppress this notification (which is also why it has value -1).
Your patch is removing the only use of silent and instead makes us send an undefined close reason (that's the defined meaning of number 4 I guess) and undefined becomes some value which is not mentioned in the relevant dbus specification at all.

Oh didn't know that the `naughty.notificationClosedReason` table values were linked to dbus specification, then it makes sense to use `silent`! _I thought that table was there only to have a sort of C enum for the closed reasons sent to `destroy_cb`_

> That would be the right thing to do. However, all that naughty currently does with replaces_id is to delete that other notification and make the new one take its position. That's also why you get some flickering.

Okay, I see how this is a 'hack'... Also, to clean that _thing_, it'd be good to split the huge `naughty.notify` function, with abstractions (ex: a notification builder?).

> Making it reused properly would avoid this problem. So, to add some more hacks (e.g. no shape or bg color change), how about the following?

Thanks it's better, but as you said, still a hack on top of everything..

**Comment by psychon** [comment]
Luckily, awesome is measured in "satisfied customers" and not in "number of hacks". ;-)

Since I didn't even check if my patch above works: Do you want to take it, test it and submit it as a pull request? (Oh and you'd have to add `@param[opt=false] hide Should the notification be hidden after deletion?` at the right place in front of `naughty.destroy`).

**Comment by bew** [comment]
> Luckily, awesome is measured in "satisfied customers" and not in "number of hacks". ;-)

Ahah, you know, I think there are currently more hacks than satisfied customers, even though some rewrites are planned 😄 

> Since I didn't even check if my patch above works: Do you want to take it, test it and submit it as a pull request?

Sure! Maybe not in the next hour, but yeah I'll do it

**Comment by bew** [comment]
@psychon finally did it and used it, it's **_life_** changing for me!
