### ISSUE TITLE
Any USB event  ::  QT 5.7.1 "eats up" background mouse events from all other screens.

### ISSUE THREAD

**Issue by Manfred-Knick** [awesomeWM/awesome#1752]
Output of `awesome --version`:
$ equery list -p -o awesome
   [-P-] [  ] x11-wm/awesome-4.0-r1:0
   [--O] [  ] x11-wm/awesome-4.1:0
   [IP-] [  ] x11-wm/awesome-9999:0
Happens with all three versions

::   After some time, 
::   using the "second" mouse click yields no effect at all any more.

**How to reproduce the issue:**
Just work and wait ...
Try to open another application via selection menu by clicking upon the background of the screen.

**Actual result:**
Nothing happens.

**Expected result:**
Selection menu should open up.

Unfortunately I was not able to identify any specific correlation yet.
First, had the impression -> "after screen saver blackened the monitors",
but now I'm pretty sure it happened without also.

::   Unfortunately this always involves shutting down the whole X environment
::   because "Menu -> awesome -> restart" is also rendered unavailable the same way.

Background:

I'm working with Multiple separate X11 screens as described in isseue #598.

Recently, there were quite some updates including
- QT 5.7.1
- KDE PLASMA 5.9.4
- KDE FRAMEWORKS 5.33
- KDE APPLICATIONS 17.04

Some other application "eating up" this needed mouse event?

**Comment by psychon** [comment]
You right click on the wallpaper to get the menu with e.g. "Open Terminal" and after a while nothing happens when you right-click, ok.

> :: Unfortunately this always involves shutting down the whole X environment
> :: because "Menu -> awesome -> restart" is also rendered unavailable the same way.

In the default config you can also open up the same menu by clicking on the "a"-logo in the top-left corner and with Mod4+"w".

> Recently, there were quite some updates including

The Qt bug was with input hotplug events. Does this happen when you e.g. disconnect and reconnect your USB mouse?

**Comment by Manfred-Knick** [comment]
Hi, Uli,

> ... right click ... wallpaper ...
Exactly.

Actually I forgot to mention that I'm using the mouse left-handed / mirrored:
`grep -i map /etc/X11/xorg.conf.d/InputDevice_Mouse.conf`
`        Option          "ButtonMapping"         "3 2 1 4 5"     # left-handed`

But that could not be the problem because I had verified that 
inside the applications, all mouse buttons work as expected.

Thanks for the hints!  ( "xmodmap -pm" was helpful.)

> ... disconnect and reconnect your USB mouse?

**Indeed:**
[ ] usb 2-1.7: USB disconnect, device number 3

[ ] usb 2-1.7: new low-speed USB device number 5 using ehci-pci
[ ] usb 2-1.7: New USB device found, idVendor=046d, idProduct=c050
[ ] usb 2-1.7: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[ ] usb 2-1.7: Product: USB-PS/2 Optical Mouse
[ ] usb 2-1.7: Manufacturer: Logitech
[ ] input: Logitech USB-PS/2 Optical Mouse as /devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.7/2-1.7:1.0/0003:046D:C050.0003/input/input24
[ ] hid-generic 0003:046D:C050.0003: input,hidraw0: USB HID v1.10 Mouse [Logitech USB-PS/2 Optical Mouse] on usb-0000:00:1d.0-1.7/input0

::   Afterwards, _no reaction_ upon "right"-clicking on wallpaper: no menu appears.

**Comment by Manfred-Knick** [comment]
> Recently, there were quite some updates including
Besides the main suspicion about QT 5.7.1,
[IP-] [  ] x11-libs/gtk+-3.22.12:3
[IP-] [  ] media-libs/glew-1.13.0:0/1.13
also came to my mind (less probable).

**Comment by Manfred-Knick** [comment]
Confirmation:  After   mouse disconnect / reconnect,
your hints about  "a"-logo and Mod4+"w" still work.
Thanks a lot again! 
Kind regards!

**Comment by psychon** [comment]
> QT 5.7.1

Hm. #415 / https://bugreports.qt.io/browse/QTBUG-49952 say that Qt 5.6 has the fix. Looking at https://code.qt.io/cgit/qt/qtbase.git/tree/src/plugins/platforms/xcb/qxcbconnection_xi2.cpp?h=v5.7.1&id=a55f36211efe1bb0d6717c8545366120bd6dfd9f#n286, the fix is also present in Qt 5.7.

It might be that the fix in Qt does not work for zaphod mode / multiple separate X11 screen. I suggest exiting / restarting all Qt-using apps and check if that makes mouse clicks work again. If so, then a bug report to Qt is needed. At least the implementation only uses `primaryScreen()`: https://code.qt.io/cgit/qt/qtbase.git/tree/src/plugins/platforms/xcb/qxcbconnection.cpp?h=v5.7.1&id=a55f36211efe1bb0d6717c8545366120bd6dfd9f#n1516

**Comment by Manfred-Knick** [comment]
Stripping it down:
- Start awesome on first screen (via "startx ... --layout four")
- Start the other three screens
- Start e.g. urxvt on all four screens
- (un-) plug _any_ USB device (e.g. USB microphone) : o.k.
- Start just even _one_ KDE Konsole on screen one
- (un-) plug _any_ USB device (e.g. USB microphone) : 
- - - failure to "right"-click for menu on every background but the first
- Close that _one_ KDE Konsole on screen one
- - - "right"-click for menu works on every background again.

**Comment by Manfred-Knick** [comment]
Stripping it down / 2: same as above, but:

- Start one KDE Konsole on each screen (you might even minimize it)
- (un-) plug any USB device (e.g. USB microphone) :
- . . . failure to "right"-click for menu on _every_ background (all four)
- Close those KDE Konsole on all screens
- . . . "right"-click for menu works on every background again.

**Comment by Manfred-Knick** [comment]
My Resumee:

- . . . **QT 5.7.1 "eats up" background events from all other screens.**

**Comment by Manfred-Knick** [comment]
"_QT is screen-agnostic_" :   _Indeed!_

**Comment by psychon** [comment]
Can you report this to the Qt guys and/or reopen https://bugreports.qt.io/browse/QTBUG-49952?

**Comment by Manfred-Knick** [comment]
Stripping it down / 3:

**Proof:**
The effect described above has _nothing to do with awesome WM_ at all.

_Verification with plain pure X11 & twm:_

Create additional menues 2 & 3 in plain default .twmrc:
. . .
Button2 = : root : f.menu "defops2"
Button3 = : root : f.menu "defops3"
. . .
menu "defops2"
{
"Twm2"  f.title
""              f.nop
"Konsole"       f.exec "exec konsole &"
""              f.nop
}
. . .
menu "defops3"
{
"Twm3"  f.title
""              f.nop
"firefox"       f.exec "exec firefox &"
""              f.nop
}

- start twm  (via "startx ... --layout four")
- start xterms on all four screens
- start one KDE Konsole on screens 2 and 3
- plug USB microphone
- _none_ of the three background menues raises at all:
- _all three_ background mouse events swallowed on _all four_ screens

**Comment by psychon** [comment]
> The effect described above has nothing to do with awesome WM at all.

**Comment by Manfred-Knick** [comment]
REFERENCE **upstream**:

... QtQTBUG-60394

... QTBUG-49952 revived: 
... Any USB event :: QT 5.7.1 "eats up" background mouse events 
... from all other screens.

... [ https://bugreports.qt.io/browse/QTBUG-60394 ]


CROSS-REFERENCE Gentoo:

... Bug 616568

... [ https://bugs.gentoo.org/show_bug.cgi?id=616568 ]

**Comment by Manfred-Knick** [comment]
@ Uli : 
Thanks a lot again!
Kind regards

**Comment by Manfred-Knick** [comment]
Looks like XI2 again ("QT_XCB_NO_XI2_MOUSE=1")
https://bugreports.qt.io/browse/QTBUG-60394?focusedCommentId=355045&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-355045
