### ISSUE TITLE
bug on super+r key

### ISSUE THREAD

**Issue by nitrofurano** [awesomeWM/awesome#1754]
Output of awesome --version:
awesome v4.0 (Harder, Better, Faster, Stronger)
 • Compiled against Lua 5.1.5 (running with Lua 5.1)
 • D-Bus support: ✔
 • execinfo support: ✔
 • RandR 1.5 support: ✘
 • LGI version: 0.9.1

How to reproduce the issue:
- press super+r key (or meta+r ?)

Actual result:
- shows "oops, an error happened! /home/guest/.config/awesome/rc.lua:272:attempt to index field '?' (a nil value)")

Expected result:
- would allow running command lines on the AwesomeWM panel bar

**Comment by nitrofurano** [comment]
Output of awesome --version:
awesome v4.0 (Harder, Better, Faster, Stronger)
 • Compiled against Lua 5.1.5 (running with Lua 5.1)
 • D-Bus support: ✔
 • execinfo support: ✔
 • RandR 1.5 support: ✘
 • LGI version: 0.9.1

How to reproduce the issue:
- press super+r key (or meta+r ?)

Actual result:
- shows "oops, an error happened! /home/guest/.config/awesome/rc.lua:272:attempt to index field '?' (a nil vlue)")

Expected result:
- would allow running command lines on the AwesomeWM panel bar

**Comment by blueyed** [comment]
What is in rc.lua:272 ?
Please post the code around that line here.

**Comment by nitrofurano** [comment]
awful.key({ modkey },            "r",     function () mypromptbox[mouse.screen]:run() end),

(a copy of rc.lua i have now at https://pastebin.com/raw/4F99DZ9e )
(btw, after seeing the code, i verified that similar bug appears when i enter meta+x )

**Comment by psychon** [comment]
Your `mypromptbox` table maps from screen number (an integer) to your promptbox:
```
for s = 1, screen.count() do
    -- Create a promptbox for each screen
    mypromptbox[s] = awful.widget.prompt()  
```
Then your code later tries to index via a screen object:
```
awful.key({ modkey },            "r",     function () mypromptbox[mouse.screen]:run() end),
```
Try using `mouse.screen.index` instead so that you get the integer that you want instead.

In other words, you found out why we give the following advice at https://awesomewm.org/apidoc/documentation/17-porting-tips.md.html#v4:

> The best advice is to start from the default rc.lua and backport any changes you might have added to your rc.lua. This avoids most of the possible errors due to missing important changes.

**Comment by nitrofurano** [comment]
based on all information you provided above, i edited rc.lua from 4.0 version with what i changed on the 3.5 version - https://pastebin.com/raw/vTnFW7nN - thanks! :)
