### ISSUE TITLE
Some contextual menus on the internet are un-clickable

### ISSUE THREAD

**Issue by latach** [awesomeWM/awesome#1758]
Output of `awesome --version`:
awesome v4.1 (Technologic)
 • Compiled against Lua 5.1.5 (running with Lua 5.1)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.4
 • LGI version: 0.9.1

I'm running on Ubuntu 17.04.

**How to reproduce the issue:**
Some menus on facebook.com & youtube.com are un-clickable:

![01-29-04-2017-screenshot](https://cloud.githubusercontent.com/assets/21196400/25551199/268f72f8-2c79-11e7-99ba-253a17ef17f6.png)

. They target can be hovered upon with the mouse, this produces the menu, which would be un-clickable with the left mouse button. However it can be right clicked, and opened in a new tab.

I have tried this on Opera & Chrome browsers. It works okay on Chrome, but not Opera.

**Actual result:**

The menu disappears without opening the link.

**Expected result:**

Open link in current tab.

(The snapshot attached is from facebook.com, this menu is the one on profile pages).

**Comment by Veratil** [comment]
This was fixed with commit f290ea8

**Comment by latach** [comment]
Oh okay thank you. I will close it now.
