### ISSUE TITLE
[Multiple separate X11 screens] kde-apps/kate-17.04.0 :: starts on wrong tag of current active X11 screen

### ISSUE THREAD

**Issue by Manfred-Knick** [awesomeWM/awesome#1759]
Please c.f.

. . . Bug 616964 - kde-apps/kate-17.04.0:5 always starts on wrong virtual screen.

. . . [ https://bugs.gentoo.org/show_bug.cgi?id=616964 ]

Probably due to  kde-apps/kate-17.04.0:5  
and not due to awesome,
but don't know for sure yet.

**Comment by psychon** [comment]
What exactly do you mean with "virtual screen"? A screen as in "X11 protocol screen" or a screen as in "RandR OUTPUT"?

Because its impossible to move a window between protocol screens aka "awesome cannot cause a window to appear on the wrong protocol screen". (but `# 6` doesn't sound like you mean protocol screens since no one has that many protocol screens... I hope)

>Since upgrade of QT -> 5.7.1 and KDE-Apps -> 17.04, starting kate from the background menu of a screen, it always pops up on the wrong virtual screen # 6 regardless from which one it was started.

Isn't "a QT and KDE upgrade caused this" a good indicator for "not awesome's fault"?

**Comment by Manfred-Knick** [comment]
Hi, Uli,
the intention of mentioning this here is to help others with hint and reference -
presumably ending up is an 'upstream' KDE / kate bug in the end.

- You have read my "Probably ..." above?
- And my hint to my setup in issue #598 also?
- In Gentoo Bugzilla, _very_ few will know awesome's notation of "tag".

- Start 4 instances of awesome
- On screen 2, tag 3 (or 5 or 8), start kate
- It _always_ unwantedly opens up on tag 6.
- This does not happen with other KDE applications, afaicsy.

**Comment by a17r** [comment]
You say you may remember this happening with kde-apps-16.12.x already, and then you confirm that gvim show the same behaviour - so I don't think this has anything to do with Qt or KDE Applications.

**Comment by Manfred-Knick** [comment]
> You say you may remember this happening with kde-apps-16.12.x already, 

? Where ?

> and then you confirm that gvim show the same behaviour 

? Where ?

> - so I don't _think_ this has anything to do with Qt or KDE Applications.

I reject to speculate in areas where I am not an expert.

**Comment by a17r** [comment]
We can assume you are the same person as: https://bugs.gentoo.org/show_bug.cgi?id=617004

**Comment by Manfred-Knick** [comment]
@ Andreas:
> assume
Yes, indeed.
But I still don't understand why you [= Gentoo Dev] comment upon a **different** _Gentoo_ bug _here_ ?

@Uli:
-> https://bugs.gentoo.org/show_bug.cgi?id=617004
-> https://bugs.gentoo.org/show_bug.cgi?id=617004#c4
-> https://bugs.gentoo.org/show_bug.cgi?id=617004#c7

**Comment by Manfred-Knick** [comment]
@Uli:
Concerning -> https://bugs.gentoo.org/show_bug.cgi?id=617004 :
Cross-Check with plain X11 & pure twm (= 4 screens, but no tags) :
Works as expected, 'unfortunately'.
(KDE) Applications started via Dolphin file entries stay on that screen.

**Comment by Manfred-Knick** [comment]
@Uli:

A) -> https://bugs.gentoo.org/show_bug.cgi?id=617004#c9

B) Additional Observation:

B1)   No running instance of LibreOffice:
Starting an entry "*.ods" from Dolphin running on Screen **2**, tag 4
starts LibreOffice on Screen **0**, current active tag.

B2)   Running instance of LibreOffice on Screen 3, tag 5:
Starting an entry "*.ods" from Dolphin  running on Screen 2, tag 4
delivers to LibreOffice on Screen 3, tag 5 
as expected.

**Comment by Manfred-Knick** [comment]
@Uli:
Additional Observation / Change:
Starting an entry "*.txt" from Dolphin running on Screen 2, tag 4
starts Kate on Screen **0**, _current active tag_
(not "_same_ Screen, but _always_ on tag 6" anymore).

This now is a first hint that both findings _might_ be due to the same cause.
The Cross-Check with X11 & twm above _seems_ to exculpate Dolphin / KDE / QT chain.

**Comment by Manfred-Knick** [comment]
Worth the effort, I built fvwm-crystal (which provides 8 virtual screens per X11 screen).
It suffers the _same_ problems, starting applications on wrong screens.
Unfortunately, I could not identify _any_ correlation at all yet.

**Comment by Manfred-Knick** [comment]
Building FVWM, creating a default theme with 3 x (2 x 2) "Desktops" 
(in fvwm nomenclature: 3 "screens" with 2 x 2 "Virtual Desktops")
on all four X11 screens.

A) Started Dolphin on X11 screen 3,  "screen" 2, "Virtual Desktop" 3:
Subsequently selecting file entries, Kate / Okular arose on this same "Desktop".

B) Starting Dolphin on _any_ other X11 screen but 3;
Subsequently selecting file entries, Kate / Okular _always_ arose on the previously described "Desktop" above.

**Comment by Manfred-Knick** [comment]
Building XFCE, starting on the four X11 screens,
starting Dolphin on any other X11 screen but 3:
Subsequently selecting file entries, Kate / Okular always arose on X11 screen 3.

**Comment by Manfred-Knick** [comment]
Starting twm on the four X11 screens,
starting first Dolphin on X11 screen 3,
starting another  Dolphin on any other X11 screen but 3,
the applications always arise on screen 3.

**Comment by Manfred-Knick** [comment]
@Uli:
Do you agree that this is enough evidence that the WMs are not to blame
and to open an upstream KDE -> Dolphin bug?

**Comment by Manfred-Knick** [comment]
Finally I could identify the **patterns**:

AWESOME:

A) _Dolphin_ spawns the apps (including Kate) from file context
- onto that (wrong) X11 screen where (after starting X env) 
  the _first_ instance of Dolphin had been started
- (regardless if this _first_ instance has been closed in between)
- into the currently active "tag" of that (wrong) X11 screen.

B) Starting _Kate_ from awesome background menu, it opens
- onto the current active X11 screen
- but onto that (wrong) "tag"
- which is the active one on X11 screen 0.
- Above behaviour does not apply to KWrite, GVim, LibreOffice and Okular,
- but seems to be specific to Kate and Awesome only afaics.


TWM:     (no "Virtual Desktops" available)

A) Dito.

B) = N.A.   /  = as expected:
- Starting _Kate_ from awesome background menu, it opens
- onto the current active X11 screen


FVWM:

A) Dito:
- onto the currently active "Virtual screen :: virtual desktop" tuple

B) = as to be expected:
- Starting _Kate_ from FVWM background menu, it opens
- onto the current active X11 screen
- onto the currently active "Virtual screen :: virtual desktop" tuple



FLUXBOX:

A) Dito:
- onto the currently active "Workspace"

B) = as to be expected:
- Starting _Kate_ from FLUXBOX background menu, it opens
- onto the current active X11 screen
- onto the currently active "Workspace"


XFCE: creating 2 x 2 "Workspaces"

A) Dito:
- onto the currently active "Workspace"

B) = as to be expected:
- Starting _Kate_ from XFCE background menu, it opens
- onto the current active X11 screen
- onto the currently active "Workspace"


C) _Thunar_ spawns the apps (including Kate) from file context
- onto that (wrong) X11 screen where (after starting X env) 
  the _last_ instance of Dolphin had been started
- (regardless if this _last_ instance has been closed in between)
- onto the currently active "Workspace"

**Comment by Manfred-Knick** [comment]
To me, this looks like three _different_ bugs:
- (A) one in KDE -> Dolphin                                           ==>   KDE upstream
- (B) one in interplay of AWESOME with KDE -> Kate   ==>   this issue #1759
- (C) one in XFCE -> Thunar                                          ==>  XFCE upstream

**Comment by Manfred-Knick** [comment]
@Uli:
Please, let me know if I can be of any further assistance.

**Comment by psychon** [comment]
Well... I have no idea. Awesome doesn't do anything special with zaphod mode, I think. Apps just inherit the value of `$DISPLAY` from awesome, so if awesome has `DISPLAY=:1.1`, then so should whatever you started. After that... no idea how Kate ends up on `:1.0`.
Perhaps you can play around with a terminal from which you start Kate and check if `$DISPLAY` works as expected? Dunno.

Also, no idea how I can help here (no, I'm not going to install Kate to try this out, sorry).

**Comment by Manfred-Knick** [comment]
After all those testing detours, I'm really happy to be back @ awesome :-)

**Comment by Manfred-Knick** [comment]
First startup:
`startx /usr/bin/awesome -c ~/.config/awesome/rc.lua        -- -layout Four`
By default, awesome will run on the first screen (X11 screen number :0.0) only.
Start next three from within:
`$ cat bin/awesome-on-four `
`DISPLAY=:0.1   dbus-launch   --exit-with-session   awesome &`
`DISPLAY=:0.2   dbus-launch   --exit-with-session   awesome &`
`DISPLAY=:0.3   dbus-launch   --exit-with-session   awesome &`

`$ ps aux | grep dbus-daemon`
`... /usr/bin/dbus-daemon --system`
`...  /usr/bin/dbus-daemon --fork --print-pid 5 --print-address 7 --session`
`... /usr/bin/dbus-daemon --config-file=/usr/share/defaults/at-spi2/accessibility.conf --nofork --print-address 3`
`... /usr/bin/dbus-daemon --fork --print-pid 5 --print-address 7 --session`
`... /usr/bin/dbus-daemon --fork --print-pid 5 --print-address 7 --session`
`... /usr/bin/dbus-daemon --fork --print-pid 5 --print-address 7 --session`

Starting from inside _any_ terminal :

- `kate` , `kate --startanon`, `kate -n` :
- all the same behaviour as from background menu
- `xterm` | `urxvt` | `konsole` : all the same

- `DISPLAY=":0.x" kate` : same behaviour.

- `DISPLAY=":0.x" <any-other-app>` : opens on current active tag of X11 screen `x` as expected.

`X11` and henceforth `DISPLAY = <hostname>:<displaynumber>.<screennumber>` 
do not know any concept of `.<virtual-screen>` themselves,
thus no possibility to enforce starting upon a specified "tag" this way.

**Comment by Manfred-Knick** [comment]
_Summary:_  (my impression - a colloquial guess) :

Kate:
- `Kate` "asks" (only one PID) startx -> screen (always :0.0 in my setup) 
- about currently active `[ Display | "virtual screen" ]` tuple.

Consequence in case of `Awesome` :
- four instances, but only first via `startx,` others via `dbus-launch`;
- `[ Display | "tag" ]` tuple of screen :0.0 being delivered, 
- `"tag"` complementing start upon current active screen.

Difference in case of `TWM`, `FVWM`, `FLUXBOX`, `XFCE` :
- All four X11 screens are managed by exactly one instance associated to `startx`,
- delivering the correct tuple of `[ hostname | displaynumber | screennumber | virtual screen ]`.

Dolphin:
- `Dolphin | Klauncher | dbus` "remember and use" X11 screen of "_first_ (lowest PID) Dolphin"

Thunar:
- `Thunar | ...` "remember and use" X11 screen of "_last_ (largest PID) Thunar"

**Comment by psychon** [comment]
I still don't have much clue about Kate, but a quick look in its `main()` function found about 300 lines of code that deals with "Do I need to open a new window myself or can I find an existing instance that does the job?". Among this is: https://cgit.kde.org/kate.git/tree/kate/main.cpp#n334

> // prefer the Kate instance running on the current virtual desktop

No idea what effect that code actually has, but... dunno... You could try debugging that somehow. Perhaps it is even enough to have `dbus-monitor` running (connected to one of your (many?) dbus daemons) to see in which cases Kate defers to an already-running Kate window or when it does the job itself.

**Comment by Manfred-Knick** [comment]
Upstream:

KDE Bug 379488 -
[Multiple separate X11 screens] [Awesome WM] kate starts on wrong tag of current active X11 screen
[https://bugs.kde.org/show_bug.cgi?id=379488](url)

**Comment by Manfred-Knick** [comment]
Sorry - wrong click

**Comment by Manfred-Knick** [comment]
TEST: workaround: The following bash script delivers as expected:

**Comment by Manfred-Knick** [comment]
[bg_awe_kate.txt](https://github.com/awesomeWM/awesome/files/992009/bg_awe_kate.txt)
