### ISSUE TITLE
qt5 tray icons with a grey background

### ISSUE THREAD

**Issue by LockeAnarchist** [awesomeWM/awesome#176]
Systray seems that is not working with qt5 trays (dropbox for example) and appear with a strange grey background.

![captura_de_tela-15](https://cloud.githubusercontent.com/assets/934124/6771497/57bc7f7e-d0be-11e4-861b-0101fa19d327.png)

I googled about it and found some other people with the same problem and it was, initially, a Qt5 bug. But nowadays the issue seems that was fixed( https://qt.gitorious.org/qt/qtbase/source/34ce66cd89ea1c618d8f63dd2d9b95aed0a81b11:dist/changes-5.4.0#L436 ) and tint2, lxde, xfce can render the transparency correcly now but this behavior persists in awesome.

I'm running awesome v3.5.6

**Comment by psychon** [comment]
Sorry, until Shawn tells me otherwise, I still think that this is a qt bug. (Side not: I wrote one of the latest patches in Qt that addressed this issue and someone changed the code again...)

**Comment by LockeAnarchist** [comment]
Thanks.

Can you show me this patch, please?

**Comment by psychon** [comment]
Uhm... I guess these are the patches:

https://codereview.qt-project.org/#/c/101557/
https://codereview.qt-project.org/#/c/105905/
