### ISSUE TITLE
beautiful font setting in rc.lua not honored everywhere

### ISSUE THREAD

**Issue by x49** [awesomeWM/awesome#1765]
```
% awesome --version
awesome v4.1 (Technologic)
 • Compiled against Lua 5.3.4 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.5
 • LGI version: 0.9.1
```

Packages installed from Arch Linux repositories

**How to reproduce the issue:**

1. Start with default rc.lua.
2. Change font in rc.lua, adding the second line here:
> beautiful.init(awful.util.get_themes_dir() .. "default/theme.lua")
> beautiful.font = "sans 12"

**Actual result:**

Only the font of the textclock reflects the change.
![bad](https://cloud.githubusercontent.com/assets/5230949/25580342/89421924-2e80-11e7-9a82-c25fa3f1eb16.png)

**Expected result:**

All fonts in awesome reflect the changed configuration. Same as if changing
`theme.font          = "sans 12"`
in theme file (e.g. /usr/share/awesome/themes/default/theme.lua). This scales all fonts correctly:

![good](https://cloud.githubusercontent.com/assets/5230949/25580369/bc3338c2-2e80-11e7-9975-cc5fd072185c.png)

**Comment by psychon** [comment]
> beautiful.init(awful.util.get_themes_dir() .. "default/theme.lua")
> beautiful.font = "sans 12"

Please allow me to make this mis-use cause Lua errors. :-(

Instead of adding random "things" to the `beautiful` module, try changing your theme as follows:
```lua
beautiful.get().font = "sans 12"
```

**Comment by psychon** [comment]
Argh. That's not the issue here. Instead, `beautiful` internally caches the active font after loading a theme. Try the following:
```lua
beautiful.init(awful.util.get_themes_dir() .. "default/theme.lua")
local theme = beautiful.get()
theme.font = "sans 12"
beautiful.init(theme)
```

**Comment by x49** [comment]
Thank you! Just shows the dangers of only knowing enough of a programming language to cobble together semi-working things from the API.

**Comment by psychon** [comment]
> Thank you! Just shows the dangers of...

....having badly documented APIs which even 50% of the code in awesome uses wrongly (most of the code indexes `beautiful` directly instead of using `beautiful.get()`).

Anyway, no harm done. Feel free to ask questions as issues.

**Comment by ebflhippie** [comment]
May I ask if this is relevant to changing the font size of the keybindings cheat shear. I would like to make it more readable, but I cannot seem to enlarge it's font.

**Comment by psychon** [comment]
No, it's not relevant. You want to change `hotkeys_font` and `hotkeys_description_font` in your theme, e.g.
```lua
beautiful.get().hotkeys_font = "Monospace Bold 24"
beautiful.get().hotkeys_description_font = "Monospace Bold 20"
```

**Comment by ebflhippie** [comment]
Thank you all the same worked great, and sorry for the bloat
