### ISSUE TITLE
Window selection dropdown should be more responsive to dynamic and unexpected window closure

### ISSUE THREAD

**Issue by seanhly** [awesomeWM/awesome#1777]
Output of `awesome --version`:

awesome v3.5.6 (For Those About To Rock)
 • Build: May  8 2017 13:30:29 for x86_64 by gcc version 5.4.0 (@xxx)
 • Compiled against Lua 5.1.5 (running with Lua 5.1)
 • D-Bus support: ✘

**How to reproduce the error:**

In awesome, Open a GUI program that can be exited with the mouse (e.g. firefox). Now, right click on the window selection panel to get the dropdown menu. While the dropdown is open, the keyboard is disabled in the applications, though the mouse isn't. Exit firefox using the mouse.  Note that firefox remains in the dropdown window selection menu. Try to select its item in the menu, and the following error appears (red box, top right):
/usr/share/awesome/lib/awful/menu.lua:469: invalid object

**Actual result:**

An item remains in the window selection dropdown, even if the window is intermittently exited or stopped involuntarily.  When selecting this item, rather than a *nice* error message like: "This window has been closed," an informative debug error appears.

**Expected result:**

The dropdown updates when a window is no longer there (perhaps make the dropdown check every 0.1s). Or the mouse is disabled outside the dropdown while it is opened (this would not solve unexpected window closure however).

**Comment by Elv13** [comment]
I created a pull request to prevent the error message. However, updating the list would require more complex code. The last thing this module need is more complex more.
