### ISSUE TITLE
Get clients ordered by stack / prefer clients on top with client.swap.bydirection

### ISSUE THREAD

**Issue by blueyed** [awesomeWM/awesome#178]
I'd like `awful.client.swap.bydirection` prefer clients that are at the top of the stack.

It uses `client.get` internally to loop over them, and I could imagine having a new C function, or option, which would return the clients as they are on the stack `globalconf.stack`.

Would it make sense to change the default of `client.get` even, or are not all clients necessarily in `globalconf.stack`?
But then any missing clients could be appended.

**Comment by psychon** [comment]
All clients are in `globalconf.stack`, but you cannot just change the result of `client.get`. This is "the" order that clients are in (e.g. the order that they appear in the tasklist, saved as their order in `globalconf.clients`). This is different than the stacking order (and e.g. should not change when the stacking order changes).

**Comment by blueyed** [comment]
Ok, then there should be some new function for this? (and use it with `awful.client.swap.bydirection`)

**Comment by psychon** [comment]
I guess it could be a new argument to `client.get()`. The first one currently is an optional screen, the second one could be a boolean that chooses between stacking order and "normal" order.
