### ISSUE TITLE
[Multiple separate X11 screens] kde-apps/konsole-17.04.1 :: "close" :: app re-locates to another (hidden) tab

### ISSUE THREAD

**Issue by Manfred-Knick** [awesomeWM/awesome#1784]
Description of Startup Procedure:
https://github.com/awesomeWM/awesome/issues/1759#issuecomment-298611832

- Start Konsole on any X11 screen =/= 0
on any tab different to the number of the currently active tab of screen 0.
- Inside, have it execute some longer-term tasks
(like emerging a bunch of packages in Gentoo, compile gcc, ...).
- Abort it by pressing the "close" cross from it's window decorations (upper rightmost corner):

- _The Konsole window including it's decorations vanishes from the currently active tab_
- _and (re-) appears on another (same X11 screen) (hidden) tab_ 
- _corresponding to the tab number which is active on screen 0._

- Correctly, in addition, the small window asking for confirmation (three choices) appears on top.

REFERENCE:  issue #1759:
"[Multiple separate X11 screens] kde-apps/kate-17.04.0 :: 
  starts on wrong tag of current active X11 screen"
Overview:
https://github.com/awesomeWM/awesome/issues/1759#issuecomment-298620529
Observation of Patterns:
https://github.com/awesomeWM/awesome/issues/1759#issuecomment-298374308

**Comment by Manfred-Knick** [comment]
-> Upstream:

Bug 379914 - 

[Multiple separate X11 screens] [Awesome WM] 
kde-apps/konsole-17.04.1 :: 
"close" :: 
app re-locates to another (hidden) tab

https://bugs.kde.org/show_bug.cgi?id=379914

**Comment by Elv13** [comment]
I cannot reproduce and doubt about some of the debug steps, but whatever.

Please disconnect `request::tag` and implement your own handler that prints the `debug.traceback()`. This will at least tell if it's a new client being inserted or the current client being moved due to an event. Also, that handler allows to "fix" the bug from Awesome.

https://awesomewm.org/apidoc/libraries/awful.ewmh.html#awful.ewmh.tag

    client.disconnect_signal("request::tag", awful.ewmh.tag)
    client.connect_signal("request::tag", function(c, ...)
        print(debug.traceback()); awful.ewmh.tag(c, ...)
    end)

**Comment by Manfred-Knick** [comment]
> This will at least tell if it's a new client being inserted or the current client being moved due to an event.

Well, my differential diagnosis was very simple in this case:
- The moved client still contains all the old content,
- still running the started tasks;
- choosing to "quit" instead of "close the window", the started processes continue inside it,
- as if nothing had happened at all.

> Please, ... and implement ...

Sorry, but I'm neither an awesome / desktop developer nor do I depend upon KDE app either.
Just wanted to save others some time and contribute my 2 cents -
which already has grown into a Monster-Projekt with way too many days of [ install | config | test ]
in order to make really sure that my (customers') important applications don't show that mess.

Nevertheless, I will happily supply additional details of information as requested.

**Comment by Manfred-Knick** [comment]
> Also, I doubt these bug will get attention upstream.

I agree. KDE has become totally agnostic of Multi-Screen Setups since KDE4.

> The X11 code is soft-frozen

As I have elaborated e.g. in 
https://github.com/awesomeWM/awesome/issues/1759#issuecomment-298374308,
this is _not_ an X11 problem by any means.

> and effort is being redirected to Wayland.

Can you point to anything securing hope for a better situation under Wayland
esp. concerning integration of multiple driver-incompatible VGAs?

**Comment by Manfred-Knick** [comment]
_Differential diagnosis:_
Under `FVWM` and `Fluxbox` I was not able to re-produce the re-location described above.

**Comment by Manfred-Knick** [comment]
> I cannot reproduce

@ Elv13 : for your convenience:

[etc-X11-xorg.conf.d.zip](https://github.com/awesomeWM/awesome/files/1013747/etc-X11-xorg.conf.d.zip)
