### ISSUE TITLE
No icons in plasma-5 KDE apps

### ISSUE THREAD

**Issue by lmoellendorf** [awesomeWM/awesome#1787]
Output of `awesome --version`:

awesome v4.1 (Technologic)
 • Compiled against Lua 5.1.5 (running with Lua 5.1)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.5
 • LGI version: 0.9.0

**How to reproduce the issue:**

1) Upgrade KDE app to plasma-5 (Qt 5 and KDE Frameworks 5) version, e.g. okular to version 16.12.3
2) Start the app

**Actual result:**

The app starts fine, but there are no icons

**Expected result:**

Icons should be displayed.

**Further information:**

In Gentoo forum ([Icons missing in KDE apps if started from XFCE](https://forums.gentoo.org/viewtopic-t-1045362-highlight-icons+plasma.html)) the proposed solution is:

> 1) kde-frameworks/frameworkintegration must be installed
> 2) The environment variable XDG_CURRENT_DESKTOP must be set to "XFCE" before starting a KDE app

**Questions:**

1) How can XDG_CURRENT_DESKTOP set when awesome is started (I am using slim login manager)?
2) To what value should  XDG_CURRENT_DESKTOP be set?

**Comment by Elv13** [comment]
https://bugs.kde.org/show_bug.cgi?id=344149

The bug isn't on Awesome side. For now the best way is to set the variable and move on. I don't plan to fix it there as I have enough to do already.
