### ISSUE TITLE
clients (chrome, liferea) start maximized and can't be set unmaximized, instead they stay maximized but now with '+' before the window title

### ISSUE THREAD

**Issue by sandervanburken** [awesomeWM/awesome#1790]
Output of `awesome --version`:

awesome v4.1 (Technologic)
 • Compiled against Lua 5.3.4 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.5
 • LGI version: 0.9.1

**How to reproduce the issue:**

Start a vanilla awesome environment, and launch chrome or liferea.

**Actual result:**

Client is started maximized. When unmaximed, awesome shows a '+' sign before the window title name. Sometimes when toggling maximized/unmaximized the '+' sign goes away.

**Expected result:**

Clients should not start maximized. And when unmaximizing a client, it should fit next to the other clients instead of staying maximized and having a '+' sign in before the window title.

**Note:**
I think this bug is probably related to my specific .config for these applications. So far I was not able to figure out what is causing this issue. So any help is much appreciated.

**Comment by Elv13** [comment]
This was fixed in #1748  (merged yesterday). Please upgrade to git-master. It will be part of 4.2 (soon)

**Comment by sandervanburken** [comment]
@Elv13 
Thank you for this information! I think I'll wait for the 4.2 release on Archlinux.

@psychon 
Thank you for your reply! I haven't changed anything to the default behavior regarding `.maximized`.

**Comment by blueyed** [comment]
@sandervanburken 
You could also try https://aur.archlinux.org/packages/awesome-luajit-git/ or https://aur.archlinux.org/packages/awesome-git/
