### ISSUE TITLE
Taglist style override documentation doesn't match code

### ISSUE THREAD

**Issue by sw9** [awesomeWM/awesome#1795]
Output of `awesome --version`:
awesome v4.1 (Technologic)
 • Compiled against Lua 5.1.5 (running with Lua 5.1)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.4
 • LGI version: 0.9.1

The style argument in awful.taglist is used to override parts of the theme. The documentation says to set the member variables `taglist_squares_sel, taglist_squares_unsel, taglist_squares_sel_empty, taglist_squares_unsel_empty` to override the corresponding parts of the theme, but the code in `taglist.taglist_label` actually looks for `squares_sel, squares_unsel, squares_sel_empty, squares_unsel_empty`

**Comment by psychon** [comment]
(Just to avoid any mis-understandings: Seems easy enough to fix, but I cannot do right now. Hence, adding to `v4.2` so this doesn't get forgotten.)

**Comment by sw9** [comment]
Just to clarify, the solution is to change the documentation to match the code or the other way around? Because I certainly can do a pull request for the latter, but not too sure if there's a repo for the website or how that works.

**Comment by legostax** [comment]
> not too sure if there's a repo for the website or how that works

The docs are generated from the comments above every function in the Lua libs.  So, they can be changed via a pull to this repo.

**Comment by psychon** [comment]
> Just to clarify, the solution is to change the documentation to match the code or the other way around? 

Hm. If you want me to guess: Changing the implementation could break configs and thus is not the best idea. So, changing the docs (here in this repo) is the right thing to do.

The web page contains the docs in the state of the release, so the fix will not be visible there until the next release. (Just wanted to clarify this part of the last comment)
