### ISSUE TITLE
awful.menu has hardcoded menu size, does not use DPI

### ISSUE THREAD

**Issue by kierun** [awesomeWM/awesome#1807]
Output of `awesome --version`:

; `which awesome` -v
awesome v4.1-123-ga6ec8c0 (Technologic)
 • Compiled against Lua 5.3.4 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.4
 • LGI version: 0.9.1

**How to reproduce the issue:**

Run on a 4k display with the default zenburn theme. 

**Actual result:**

Look at the tiny menu!

**Expected result:**

A readable menu?… 

The settings I have are:
```
-- {{{ Menu
-- Variables set for theming the menu:
-- menu_[bg|fg]_[normal|focus]
-- menu_[border_color|border_width]
theme.menu_height = 512
theme.menu_width  = 400
-- }}}
```

Which should make the menus large (maybe too large?) but they seem to have no effect.

**Comment by psychon** [comment]
> Look at the tiny menu!

Are you saying that awesome detects the high DPI and the wibar (bar at the top of the screen) has a larger font, but the menu is still small? Could you provide a screenshot? What output does `awesome-client 'local g = require("beautiful.xresources").get_dpi return g(), g(1)'` produce for you?

> theme.menu_height = 512
> theme.menu_width  = 400

That should definitely work. What does `awesome-client 'return require("beautiful").get().menu_height'` say? (By the way: This is a per-item size, the default is a height of 16 and a width of 100, so your 512 might be a bit large.)

**Comment by kierun** [comment]
> Are you saying that awesome detects the high DPI and the wibar (bar at the top of the screen) has a larger font, but the menu is still small?

Yes, pretty much. The wibar font is fine. The menu font is a little small but the gaps between are tiny making the whole thing squashed.

> Could you provide a screenshot?

Sure, here goes:

![awesome-screenshot](https://cloud.githubusercontent.com/assets/3079575/26626704/0488aaea-45f0-11e7-965a-76ce4fd4a05a.png)

> What output does […]

This is what the command return:

```
; awesome-client 'local g = require ("beautiful.xresources").get_dpi return g(), g(1)'
   double 150                                                                         
   double 150
; awesome-client 'return require ("beautiful").get().menu_height'
   double 15
```

**Comment by psychon** [comment]
Ah, ok. So the "actual font height" is fine, the problem is just that the menu doesn't ignores the DPI for its default size. Whoops, that's quite an oversight.

> ; awesome-client 'return require ("beautiful").get().menu_height'
>    double 15

You say you set this to 512, but it looks like that did not work. Did you edit the right theme file? Could you try adding `beautiful.get().menu_height = 512` to your `rc.lua`, right after the call to `beautiful.init`? Besides that, I do not really know, but the problem must be somewhere between your config and your theme.

**Comment by kierun** [comment]
> Ah, ok. So the "actual font height" is fine, the problem is just that the menu doesn't ignores the DPI for its default size. Whoops, that's quite an oversight.

Yes. 

> You say you set this to 512, but it looks like that did not work. Did you edit the right theme file? 

I *believe* I did although the above command kinda points to no. I have this:

`beautiful.init(awful.util.get_themes_dir() .. "zenburn/theme.lua")`

Which clearly is the distribution zenburn theme and not the one I have installed in `~/.config/awesome/zenburn`… 

oops.

Thank you for your help: the bug was an error between keyboard and floor.

**Comment by psychon** [comment]
> Thank you for your help: the bug was an error between keyboard and floor.

Then let's keep this open and track the following as the bug: 

> the problem is just that the menu doesn't use the DPI for its default size. Whoops, that's quite an oversight.

**Comment by kierun** [comment]
No problems. Lemme know if I can test anything.

**Comment by psychon** [comment]
(Turns out only the zenburn theme was affected; all other themes already DPI-scaled the menu size.)
