### ISSUE TITLE
client.transient_for is not set when restarting awesome

### ISSUE THREAD

**Issue by blueyed** [awesomeWM/awesome#181]
The `transient_for` property does not get setup when restarting awesome.

The X property itself is still set.

**Comment by psychon** [comment]
Could you add some debug-printfs to awesome? In `property.c`, function `property_update_wm_transient_for`, make it print the result of `client_getbywin()`.

My guess is that awesome happens to manage the transient window before its parent. So then it sees a WM_TRANSIENT_FOR pointing to a window that it does not know about and thus ignores that value.

**Comment by blueyed** [comment]
> My guess is that awesome happens to manage the transient window before its parent

That appears to be correct.
The result is `0`.

**Comment by psychon** [comment]
Ok. Quick idea for a fix would be a `rescan_transient_for()` at the end of `scan()` which looks at clients with `c->transient_for == NULL` and checks if they really have no `WM_TRANSIENT_FOR` property. Let's see when someone finds the time for this. :-)
