### ISSUE TITLE
Glitches when there's movement on the screen

### ISSUE THREAD

**Issue by morethanoneanimal** [awesomeWM/awesome#1814]
Output of `awesome --version`:
awesome v4.0 (Harder, Better, Faster, Stronger)
 • Compiled against Lua 5.1.5 (running with Lua 5.1)
 • D-Bus support: ✔
 • execinfo support: ✔
 • RandR 1.5 support: ✘
 • LGI version: 0.9.1

**How to reproduce the issue:**

Open browser (chrome) and scroll. Or open some game.

**Actual result:**

The picture is not always smooth, sometimes there are little glitches looking as if double buffering was not enabled.

**Expected result:**

Smooth, nice picture.

Glitches are small and hard to notice at first, but once you do you can't unsee them. When I switch to unity (Ubuntu 16.04) everything is perfectly smooth, so it's not a  driver issue. I saw the same issue on Lubuntu 16, on LXDE everything ran fine. I wonder if anyone has similar experience and how to debug it.

**Comment by psychon** [comment]
Could you try running with the `--no-argb` command line option?

> so it's not a driver issue. 

Yes it is. What else would it be? A window manager only places windows, it does not render them. (We are not a compositing manager!)

**Comment by morethanoneanimal** [comment]
It worked, thanks!

**Comment by farhadp-code** [comment]
I Have the same issue. How can I fix that?
