### ISSUE TITLE
Horizontal layout midle alignment does not work in awesome 4 (but used to work in 3.5)

### ISSUE THREAD

**Issue by ThePinkPanther** [awesomeWM/awesome#1815]
Output of `awesome --version`:

awesome v4.0 (Harder, Better, Faster, Stronger)
 • Compiled against Lua 5.1.5 (running with Lua 5.1)
 • D-Bus support: ✔
 • execinfo support: ✔
 • RandR 1.5 support: ✘
 • LGI version: 0.9.1

**How to reproduce the issue:**

Checkout my awesome configuration from here:
https://github.com/ThePinkPanther/MinimalAwesome

**Actual result:**

 set_middle aligns on the left instead of center in horizontal layout, but the same configuration used to work in Awesome 3.5

I described in this SO question: https://stackoverflow.com/questions/44349147/awesome-wm-4-middle-align-does-not-work-in-horizontal-layout

**Expected result:**

set_middle should align component in the middle of it's layout

**Comment by psychon** [comment]
Set `expand` to `outside` for your `align` layout: https://awesomewm.org/doc/api/classes/wibox.layout.align.html#wibox.layout.align.expand

**Comment by ThePinkPanther** [comment]
Thanks a lot
