### ISSUE TITLE
Missing doc for awesome.register_xproperty

### ISSUE THREAD

**Issue by timroes** [awesomeWM/awesome#1817]
In the [current version](https://awesomewm.org/doc/api/libraries/awesome.html) of the docs the documentation for `awesome.register_xproperty` is missing. The  doc was removed in commit 26f15a13f3c78babf1d448ac5608e8affcf4f6d8.

To quote @psychon: "so... someone should probably check that commit careful for other things that were removed"

**Comment by psychon** [comment]
I took a look and only `awesome.register_xproperty` and the link to `xproperties` seem to be missing (for `set_xproperty` and `get_xproperty`). Documentation used to be:
```lua
--- Register a new xproperty.
--
-- @param name The name of the X11 property
-- @param type One of "string", "number" or "boolean"
-- @function register_xproperty

--- Change a xproperty.
--
-- @param name The name of the X11 property
-- @param value The new value for the property
-- @function set_xproperty

--- Get the value of a xproperty.
--
-- @param name The name of the X11 property
-- @function get_xproperty
```
