### ISSUE TITLE
awesome + virtualbox seamless mode (top panel didnt work)

### ISSUE THREAD

**Issue by berkuse** [awesomeWM/awesome#1821]
Output of `awesome --version`:

awesome v4.1 (Technologic)
 • Compiled against Lua 5.3.4 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.5
 • LGI version: 0.9.1

**How to reproduce the issue:**

1) Install VirtualBox 5.1.22
2) Launch guest Arch linux with awesome wia virtualbox.
3) Install virtualbox-guest-tools to guest os.
4) Enter to seamless mode (right ctrl+l)

**Actual result:**
awesomewm top panel doesn't show.i can see only launched applications.
**Expected result:**
Wallpaper of guest os must be transparency, and u can work with guest os applications\panels from windows host os.

p.s. in screens i install xfce panel and this panel work without any problems.

![image](https://user-images.githubusercontent.com/22992369/26906280-d15cd3a2-4bf4-11e7-8c79-ac9b8542b169.png)
![image](https://user-images.githubusercontent.com/22992369/26906317-20fe78ca-4bf5-11e7-858b-d5b53c0f51c1.png)

**Comment by Elv13** [comment]
Hello, please try the following things (in order):

 * Start Awesome with `--no-argb`
 * Install `compton` and run it
 * Use the `awesome-luajit-git` from AUR
 * Install `xorg-server-git` from AUR

There is hope one of the step above might fix the problem. In all 3 case, it should improve this kind of rendering bugs. @psychon recently patched X11 and Awesome to fix similar issues. However note that VirtualBox has its own share of problems and if the above steps don't work, then I will blame VirtualBox and you should open a bug report there. But there is 805+ chances it should work by the time to fourth item on that list.

**Comment by Elv13** [comment]
@berkuse Ping? Otherwise I will close this issue in a week
