### ISSUE TITLE
beautiful variable `wibar_height` does not affect the height of wibars

### ISSUE THREAD

**Issue by 2009** [awesomeWM/awesome#1824]
Output of `awesome --version`:

awesome v4.1 (Technologic)
 • Compiled against Lua 5.3.4 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.5
 • LGI version: 0.9.1

**How to reproduce the issue:**

1. Remove any `height` args from the `awful.wibar({ position = "top", screen = s })` call.
2. Set beautiful theme variable `wibar_height`.

**Actual result:**

`wibar_height` does not affect the height of the wibars.

**Expected result:**

The height of wibars to be the same as `wibar_height`.

Looks like this [line](https://github.com/awesomeWM/awesome/blob/master/lib/awful/wibar.lua#L393) in wibar.lua is settting the height dynamically and the [line](https://github.com/awesomeWM/awesome/blob/master/lib/awful/wibar.lua#L412) here is checking for `arg.height` to be `nil` before getting the value from `wibar_height`, which in this case will never happen.

**Comment by Elv13** [comment]
Indeed

**Comment by Elv13** [comment]
Fixed in git-master (to be `v4.2`)

**Comment by 2009** [comment]
Awesome, thanks Elv13.
