### ISSUE TITLE
peek screen recorder compatibility

### ISSUE THREAD

**Issue by piec** [awesomeWM/awesome#1827]
Output of `awesome --version`:
```
% awesome --version
awesome v4.1 (Technologic)
 • Compiled against Lua 5.3.4 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.5
 • LGI version: 0.9.1

% compton --version
git-v0.1_beta2-83-g2343e4b-2015-09-22
```

I'm using Arch Linux.

**How to reproduce the issue:**

Run [peek](https://github.com/phw/peek) and start a capture.
Click in the transparent region of the peek window.

**Actual result:**

Clicks are captured by the peek window.

**Expected result:**

The clicks should go through the transparent region, ie the clicks should go to the window under the peek window.

Related issues:
 * https://github.com/phw/peek/issues/52
 * https://github.com/i3/i3/issues/2742

According to this second issue in the case of i3 you can't click through because i3 [doesn't support the shape extension](https://github.com/i3/i3/issues/2742#issuecomment-294443572), is it the same in awesomewm?

Cheers!

This is how it looks:
![image](https://user-images.githubusercontent.com/781471/26977690-12197f64-4d29-11e7-8100-4cc5da15f66b.png)

**Comment by psychon** [comment]
> is it the same in awesomewm?

Yes.

(Well, awesome does support bounding and clipping shape and even makes this work (think: xeyes), but it does not handle the input shape in the same way (yet)).

**Comment by Elv13** [comment]
@psychon Given you just implemented the input shape (from Awesome) in v4.1, do you think you could find the time to fix this while it's still fresh in your mind, or does it require a lot more code than what you recently added?

**Comment by psychon** [comment]
@Elv13 Implementing this is mostly copy&paste. We already can set the input shape for a client's frame window. We just need to be able to query the input shape for a client's "proper" window (`xwindow_get_shape` can already do the X11 part of this, it just needs to be wired up in `objects/client.c`), add signals for when it changes (the X11 server already sends us the right events, `event_handle_shape_notify` just needs to emit the signal) and teach `awful.client.shape` to also handle the input shape. That's nothing which I need fresh on my mind, I just need the time (and some idea on how to test it... or alternatively I can just assume it works).

[To be honest: I looked at https://www.x.org/releases/X11R7.7/doc/xextproto/shape.html while writing the above, but only to read that there is nothing special needed to get events when the input shape changes]

**Comment by psychon** [comment]
@piec Are you sure that the link you provided is the right one? https://github.com/peek/peek doesn't look like anything that captures the screen content.

**Comment by Elv13** [comment]
Google gave me https://github.com/phw/peek

**Comment by psychon** [comment]
Closing under the assumption that this was fixed by https://github.com/phw/peek/pull/148

**Comment by ibrahima** [comment]
Yup, just tested Peek 1.1.0 and it works great on Awesome 4.1 now.
