### ISSUE TITLE
Cannot install new software on ubuntu

### ISSUE THREAD

**Issue by latach** [awesomeWM/awesome#1828]
**Output of `awesome --version`:**
awesome v4.1 (Technologic)
 • Compiled against Lua 5.1.5 (running with Lua 5.1)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.4
 • LGI version: 0.9.1

I'm running ubuntu 17.04.

**How to reproduce the issue:**
* Either:
1. Open Software Center.
2. Go to the page of any program; click install.
3. A progress bar is shown, it reaches 10% then crashes. The app is not installed.
* Or:
1. Open Software Updater.
2. Check for updates (this step is automatically done).
3. Mark the checkboxes you would like to install.
4. Click install. Software Updater will crash.

**Actual result:**
Software Center and Software Updater crashing when installing or updating programs.

**Expected result:**
Install or update the desired program.

I am running ubuntu 17.04. I have tested it on many other ubuntu distros; they all behave the same.

**Comment by Elv13** [comment]
Hello,

Applications crashes are rarely an AwesomeWM issue. Even if the issue would only happen using some window managers and not other, this would still be an Ubuntu Software Center bug. You probably notify Ubuntu themselves of the problem at https://launchpad.net/ubuntu/+bugs
