### ISSUE TITLE
Icons, Fonts, etc. from copycat-killer themes dont show

### ISSUE THREAD

**Issue by CDitzel** [awesomeWM/awesome#1839]
Do I have to install the fonts, icons etc. that are referenced at the bottom of the readme of the copycat-killer repo or are they installed automatically when cloning and installing the repo? it doesnt become clear from the readme

https://github.com/copycat-killer/awesome-copycats#notes
![img_20170611_173841](https://user-images.githubusercontent.com/22954412/27012357-77186a50-4ece-11e7-937e-3d54a2365fd1.jpg)

I guess what Im trying to ask is, why is says N/A where Icons are supoosed to be and why the calendar has bugs

**Comment by Elv13** [comment]
Better report an issue on his repository, Awesome doesn't handle installing fonts, so the bug isn't on our side.

**Comment by psychon** [comment]
CC @copycat-killer (just for your information)

**Comment by copycat-killer** [comment]
@psychon Thanks, already closed: https://github.com/copycat-killer/awesome-copycats/issues/186
