### ISSUE TITLE
Wrong usage of io.popen?!

### ISSUE THREAD

**Issue by blueyed** [awesomeWM/awesome#184]
I've noticed that there are a few places, where `io.popen` gets used like this:

    local f, err = io.popen(cmd, 'r')
    if f then
        local s = f:read("*all")
        f:close()
        return s
    else
        return err
    end

([source](https://github.com/awesomeWM/awesome/blob/master/lib/awful/util.lua.in#L106))

But `io.popen` always only returns a file handle, as far as I can see, also for `io.popen("DOESNOTEXIST")`.

Am I missing something?  Will the second return value be used in case of more serious errors?

**Comment by Elv13** [comment]
Popen should be banned, glib provide an async version that wont block

**Comment by blueyed** [comment]
@Elv13 
Can you provide a PR for this?  Shouldn't be too many places IIRC.

**Comment by actionless** [comment]
if `spawn.pread` will became async it will be no difference between it and `spawn.easy_async`

btw tonight i've updated `menubar` to use async spawn, will submit PR tomorrow during the day after i will update docstrings accordingly

**Comment by psychon** [comment]
You mean async spawn for `find lots of arguments here`? Can't we use something sane for that instead? Assuming that `g_dir_open()` and friends are available through lgi, that can be used.
https://developer.gnome.org/glib/stable/glib-File-Utilities.html

**Comment by actionless** [comment]
are planning to do anything on that? i still haven't deleted my branch with async refactoring for those menubar helpers

**Comment by psychon** [comment]
What exactly do you mean? Am I planning to make "something for iterating over directories" work? If so, then I have just opened https://github.com/pavouk/lgi/issues/135 which contains some hints on how to do this.

**Comment by actionless** [comment]
https://github.com/actionless/awesome/commit/7db9b39aef85f7a3c8775dadfb1637a6f8d882b4

**Comment by psychon** [comment]
I'd just replace "spawn `find`" with using `lgi.GLib.Dir` to iterate over directories. This will likely have more overhead and be slower, but not noticeably much. That's be even simpler code.

**Comment by psychon** [comment]
Ok, apparently `GDir` is the wrong API to use. The following can be put into a file and run as Lua code to list the contents of `/tmp` and supposedly this is even async:
```lua
local lgi = require("lgi")
local glib = lgi.GLib
local gio = lgi.Gio
local main_loop = glib.MainLoop()

local path = "/tmp"

gio.Async.start(function()
	local f = gio.File.new_for_path("/tmp")
	-- Except for "NONE" there is also NOFOLLOW_SYMLINKS
	local enum, err = f:async_enumerate_children("standard::name", gio.FileQueryInfoFlags.NONE)
	if not enum then error(tostring(err)) end
	local files_per_call = 100 -- Actual value is not that important
	while true do
		local list, err = enum:async_next_files(files_per_call, glib.PRIORITY_DEFAULT)
		if err then error(err) end
		for _, info in ipairs(list) do
			local child = f:get_child(info:get_name())
			print(info:get_name(), child:get_path())
		end
		if #list == 0 then
			main_loop:quit()
			break
		end
	end
end)()


-- Start a main loop, awesome would normally do this for us
main_loop:run()
```
(Leave out the `main_loop` if you want to run this in awesome, also the error handling is improvable)

**Comment by actionless** [comment]
thanks!

how did you get to it? i did not managed to find any api doc for lgi others than those: https://github.com/pavouk/lgi/tree/master/docs

but they're not listing methods and so on like this one for example: http://lazka.github.io/pgi-docs/#Gio-2.0/classes/FileEnumerator.html

**Comment by psychon** [comment]
I looked at https://developer.gnome.org/gio/stable/GFileEnumerator.html.

Also, for all functions called `foo_async()`, lgi automatically produces `async_foo()` that "looks non-async" (as you can see in my example), but does some magic with coroutines behind the scenes to really make it async. Note that these magic functions only work inside `gio.Async.start(function() end)(arguments, here)` (and `gio.Async.call`, but just ignore this one).
The above description is basically https://github.com/pavouk/lgi/blob/master/docs/gio.md.

**Comment by actionless** [comment]
thanks, i've updated my PR

**Comment by psychon** [comment]
After #853, there are just three calls to `io.popen` left.

I don't think `awful.completion` needs to be converted to something else. This code is just "querying" shell completions, that's hopefully fast. However, the problem that this issue actually is about should this be fixed (`popen` always "succeeds" and returns a valid file handle).

This leaves us with `awful.spawn.pread`. Does anyone mind if this function is removed? People who want it can easily write it on their own and I don't think we should encourage people to use blocking "stuff".

**Comment by psychon** [comment]
> But io.popen always only returns a file handle, as far as I can see, also for io.popen("DOESNOTEXIST").
>
> Am I missing something? Will the second return value be used in case of more serious errors?

`man popen` says that the function call fail due to a memory allocation failure of `fork()` or `pipe()` fails. This might be hard to hit, but it is possible.

After #998 there is only one call to `io.popen` left in awesome (it's in awful.completion) and since this function can actually fail (even if that's highly unlikely), I'll close this issue.
