### ISSUE TITLE
Synaptic package manager doesn't open in Debian 

### ISSUE THREAD

**Issue by amirteymuri** [awesomeWM/awesome#1852]
Output of `awesome --version`:

awesome v3.4.15 (Never Gonna Give You Up)
 • Build: Feb 17 2013 21:10:46 for x86_64 by gcc version 4.7.2 (buildd@barber)
 • D-Bus support: ✔

**How to reproduce the issue:**

Mod4 + r, synaptic-pkexec, Hit the Enter key

**Actual result:**

**Expected result:**

To have the Synaptic Package Manager opened

**Comment by psychon** [comment]
What happens when you try to start it in a terminal? Any error messages or other output? Does it perhaps even work from there? If so, what does `which synaptic-pkexec` produce?

**Comment by amirteymuri** [comment]
Ok. I simply ran in terminal sudo synaptic and it works fine!
