### ISSUE TITLE
unexpected behaviour in awful.tag()

### ISSUE THREAD

**Issue by thevtm** [awesomeWM/awesome#1853]
Output of `awesome --version`:

```
awesome v4.1 (Technologic)
 • Compiled against Lua 5.3.4 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.5
 • LGI version: 0.9.1
```

**How to reproduce the issue:**
```
awful.layout.layouts = {
    awful.layout.suit.floating,
    awful.layout.suit.tile
}
```
```
awful.tag({ "1", "2", "3", "4", "5" }, s, awful.layout.layouts)
```

Happens when `tags length` > `layouts length`.

**Actual result:**

Tag 1 layout = floating
Tag 2 layout = tile
Tag 3 .. 5 layout = _weird floating_

Weird floating layout can't be changed and once viewed all tags adopts the _weird floating_ layout.
No error messages. 

**Expected result:**

Tag 1, 3, 5 layout = floating
Tag 2, 4 layout = tile

OR

Tag 1 .. 5 layout = floating

**Comment by psychon** [comment]
> Tag 3 .. 5 layout = weird floating

The following code in `awful.tag.new`...
```lua
layout = (layout and layout[id]) or layout
```
...would end up setting the whole `layouts`-table as the layout, I guess. This is not a valid layout (e.g. no `arrange` function) and so stuff will break when trying to arrange. I guess `awful.tag.object.set_layout` should do some checks to rule out surely-invalid layouts? (and throw an error in that case?)

(also: `awful.tag.add` modifies the table it gets as its argument... not good and can actually break things here)

> Weird floating layout can't be changed and once viewed all tags adopts the weird floating layout.
No error messages.

No popups with an error message or also no errors on stderr? My random guess would be that `awful.layout.arrange` should call the layout with a protected call. Currently any errors in a layout ends up having `arrange_lock` stuck to `true` which means that no more re-layouts will be done and we end up in something like "everything is floating" (but no `mouse_resize_handler`, so mouse resizes likely do not work...).

**Comment by thevtm** [comment]
I'm not getting any popup error messages or stderr messages.

**Comment by psychon** [comment]
> No popups with an error message or also no errors on stderr? 

I want to answer my question on why this does not cause a popup: A delayed call already runs in a protected context (but the error message then ends up on stderr). The problem here was that the variable `arrange_lock` got stuck at `true`, meaning that no further arranges happened.
