### ISSUE TITLE
No way to restrict the icon size of dbus notification

### ISSUE THREAD

**Issue by bew** [awesomeWM/awesome#1862]
Output of `awesome --version`:

```
awesome v4.1-184-gba78882c-dirty (Technologic)
 • Compiled against Lua 5.3.4 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.5
 • LGI version: 0.9.1
```

**How to reproduce the issue:**

Execute the following shell commands:
```sh
$ wget http://via.placeholder.com/800x600 -O big-image.png
$ notify-send hello world -i $PWD/big-image.png
```

**Actual result:**

You should see a notification with a big icon (800x600 px)

**Expected result:**

I would expect to have `dbus_notification_icon_max_(width|height)` in beautiful to control the icon max size (and maybe another one to specify if I want to keep aspect ratio or not).

**Comment by nickdiego** [comment]
+1

**Comment by bew** [comment]
#1951 fixed my main issue, can I close this ? or do you want to keep it open for later reference during the naughty rewrite (initiated by #1990) ?

**Comment by Elv13** [comment]
Sure. Anyway, I currently don't have enough time to merge all patches from the rewrite. I don't have an ETA, but I will work meet/work with @blueyed in a month or so. Hopefully we can make progress on this project (among other long standing pending work stalled in the pipeline such as the new Docker CI and maybe even the unification of the layout engines).

**Comment by terinjokes** [comment]
Setting `beautiful.notification_icon_size` doesn't seem to effect the size at all. Can this be reopened?

**Comment by psychon** [comment]
@terinjokes What's your awesome version? If it is 4.2 or older, then you do not yet have the fix for this issue. Put differently: This was closed in September while the latest release of awesome was in June.

**Comment by terinjokes** [comment]
@psychon Yep. I noticed that after I commented and started looking at the code on the latest tag. I edited the above comment for a workaround.

**Comment by actionless** [comment]
https://awesomewm.org/apidoc/libraries/naughty.html#beautiful.notification_icon_size

**Comment by actionless** [comment]
and also see `https://awesomewm.org/apidoc/libraries/naughty.html#beautiful.notification_max_height` for restricting geometry of notification not regarding the icon


from your version it seems what you're running very old build from git master, you need to rebuild it to have all those nice notification options

**Comment by qwelyt** [comment]
@actionless Waiting for the next release.

**Comment by olekthunder** [comment]
For awesome v4.2 you can set beautiful theme variable:
```lua
-- theme.lua
theme.notification_icon_size = 32
```

And use the following as hotfix:
 ```lua
-- rc.lua
naughty.config.presets.normal.icon_size = theme.notification_icon_size
```

**Comment by michaelcadilhac** [comment]
> https://awesomewm.org/apidoc/libraries/naughty.html#beautiful.notification_icon_size

These links seem dead.

**Comment by actionless** [comment]
@michaelbeaumont those are api docs of different versions: https://awesomewm.org/doc/

@Elv13 is it a documentation problem? i see it indeed disappeared by old link, but still used/mentioned in https://awesomewm.org/apidoc/widgets/naughty.widget.icon.html#resize_strategy

**Comment by Elv13** [comment]
> @Elv13 is it a documentation problem?

The new API doc is very different from the one shipped with v4.3, which, itself, is different from v3.5. In both case the old links stopped working. One could spend a couple hours to make symlinks and restore them, but I don't plan to do it myself.

**Comment by actionless** [comment]
i mean what those two, `beautiful.notification_icon_size` and `beautiful.notification_max_height` disappeared from the list of all beautiful variables

and only one of them, `notification_icon_size` is mentioned in the docs at all: https://awesomewm.org/apidoc/widgets/naughty.widget.icon.html#resize_strategy

so i'm trying to understand, is that a documentation problem, or those 2 intended to be removed?

**Comment by x-yuri** [comment]
For those who rarely change something in `awesome` settings: put `beautiful.notification_icon_size = 64` or something after requiring `beautiful` in `lua.rc`. To experiment with icon sizes:

```sh
awesome-client 'naughty = require("naughty"); beautiful = require("beautiful"); beautiful.notification_icon_size = 64; naughty.notify({title="CLI Notification", text="This is a notification sent from the command line!", icon="/path/to/a/big/image"})'
```

**Comment by actionless** [comment]
i think it should be fixed by https://github.com/awesomeWM/awesome/pull/3805
