### ISSUE TITLE
Regex property matching in awful.rules.match()

### ISSUE THREAD

**Issue by syphoxy** [awesomeWM/awesome#188]
I've noticed that [here](https://github.com/awesomeWM/awesome/blob/master/lib/awful/rules.lua.in#L100) it appears that we do check with a pattern but then we immediately check for string equality.

```
if not c[field]:match(value) and c[field] ~= value then
    return false
end
```

I'm not sure I understand why this was written this way. if there was no reason, would it be reasonable to remove the string equality comparison and make it always use regular expressions?

**Comment by blueyed** [comment]
It is a string inequality check..

What is your use case?

**Comment by syphoxy** [comment]
inequality/equality. I'm aware it's inequality but it's a class of equality.

either way, I'm trying to match on Firefox's Page Info dialogue box. it's name is "Page Info - URL" so I want to be able to do "^Page Info - " it's not really the only case scenario. I've seen quite a few situations where regex solve this problem.

**Comment by blueyed** [comment]
But shouldn't that work then?  Because the match is true, and then the inequality does not get checked anymore?

    > p="^Page Info - "
    > s="Page Info - URL"
    > return s:match(p)
    Page Info 
    > return not s:match(p) and s ~= p
    false

Note that the `-` is special in a Lua pattern for "0 or more repetitions".

So the pattern should be "^Page Info %- " really, and maybe that's what's causing your problem already?

**Comment by syphoxy** [comment]
ah, you're correct. I misinterpreted the logic. also, I didn't realize lua patterns (regex?) had such a wildly different syntax. I'm still finding some difficulties though so I'll get back to you after I test some more. something seems to be a little off.

**Comment by blueyed** [comment]
You might want to post your current rule / approach.
Maybe the issue is that another rule gets applied really?

**Comment by psychon** [comment]
I'll assume that the special meaning of `-` in Lua patterns caused this. Feel free to reopen if needed.
