### ISSUE TITLE
Tests should not require zsh/bash to be installed

### ISSUE THREAD

**Issue by blueyed** [awesomeWM/awesome#1882]
spec/awful/completion_spec.lua

**Comment by psychon** [comment]
How do you want to handle this? Do you want to mock the shell and provide the output that we would expect zsh to provide? Or skip the test if the shell is not installed?

**Comment by blueyed** [comment]
> Or skip the test if the shell is not installed?

This.

There could be additional tests with mocked shells, but the existing ones should be kept.

**Comment by blueyed** [comment]
Is there a good way to skip tests in this case?
Also: should I use `command -v` as a shell command to see if `zsh` (and bash) is installed?

**Comment by psychon** [comment]
> Is there a good way to skip tests in this case?

I only know about `pending()`, but no idea if it would work. So I guess "no"?

> Also: should I use command -v as a shell command to see if zsh (and bash) is installed?

I would propose `lua -e 'print(require("lgi").GLib.find_program_in_path("zsh"))'` since it seems simpler
