### ISSUE TITLE
awful.spawn with tag property only works on one screen

### ISSUE THREAD

**Issue by blueyed** [awesomeWM/awesome#1885]
The following only works from the 2nd (laptop) screen, on the other screen it will open on the current tag (and not tag "5").

Both screens have a tag by that name, and (according to some print-debugging) `tag.find_by_name` seems to find the correct tag?!

```lua
awful.spawn("urxvt", {tag="5"})
```

**Comment by Elv13** [comment]
Have you tried with https://github.com/awesomeWM/awesome/pull/1487 ?

**Comment by Elv13** [comment]
@blueyed #1487 has been merged. One of the race condition that caused this is fixed. Please try again. Otherwise I will close the issue as I assume it is fixed

**Comment by Elv13** [comment]
Assuming this is fixed
