### ISSUE TITLE
tests: cleanup temporary dirs

### ISSUE THREAD

**Issue by blueyed** [awesomeWM/awesome#1888]
https://github.com/awesomeWM/awesome/blob/cbb8fd7ac408d229233a3b5490adf35d58a85d79/spec/awful/completion_spec.lua#L34 and https://github.com/awesomeWM/awesome/blob/cbb8fd7ac408d229233a3b5490adf35d58a85d79/spec/awful/completion_spec.lua#L12 should clean up after them.

What is the way to go here, @psychon?

**Comment by psychon** [comment]
I thought the `teadown` calsl in there already handles the needed cleanup...?

**Comment by blueyed** [comment]
Oh, yeah - missed that.
However, it currently fails since the dir is not empty.

We do not have a helper for deleting dirs recursively already, do we?
Does not seem to be supported by Gio directly - I've found https://github.com/cgwalters/glib-async-rm-rf/blob/master/rm-rf-async.c.
