### ISSUE TITLE
Calendar widget style documentation is incorrect

### ISSUE THREAD

**Issue by p-himik** [awesomeWM/awesome#1899]
Output of `awesome --version`:
```
awesome v4.1-220-g09bffcd (Technologic)
 • Compiled against Lua 5.2.4 (running with Lua 5.2)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.4
 • LGI version: 0.9.0
```

`awful/widget/calendar_popup.lua` documents style parameters as being of form `cell .. '_style'` (e.g. `normal_style`), but the code of `parse_all_options` clearly reads only options of form `'style_' .. cell` (i.e. `style_normal`).

**Comment by psychon** [comment]
CC @getzze

**Comment by psychon** [comment]
Does anyone have the time to handle this and submit a PR in the next days?

**Comment by getzze** [comment]
I'll do it this week, I couldn't before

**Comment by psychon** [comment]
Should be fixed by https://github.com/psychon/awesome/commit/9519d666a37b7ddd69e4af995a69dfecf7b9740b / #1912 once merged (yup, I found some time)
