### ISSUE TITLE
KDE Frameworks 5 notifications do not close on click

### ISSUE THREAD

**Issue by ilpianista** [awesomeWM/awesome#190]
I don't know where to start to fix/workaround this. I've reported it to the [KDE bugtracker](https://bugs.kde.org/show_bug.cgi?id=340238), but it could also be an awesomewm bug because I cannot reproduce it while using e.g. *dunst*.

When a notification popup there is no way to close it; in KDE 4 times a single click on it was enough.
Also, the notification doesn't go away after some time, instead it stays there forever and it "blinks" like if it goes away and then immediately appears again.

Any idea?

[Screencast of the issue](https://bugs.kde.org/attachment.cgi?id=89393)

**Comment by Elv13** [comment]
confirmed

**Comment by psychon** [comment]
This is `naughty` displaying the notification, right? Could you run `dbus-monitor` while doing "this" and attach it? I guess KDE does "something" when the notification gets closed (reopening it?).

**Comment by ilpianista** [comment]
[This](https://gist.github.com/ilpianista/3c71fe465b6cd2629448/raw/output) is dbus-monitor output when KDE NetworkManager connects to a WiFi.

**Comment by psychon** [comment]
What the heck. There are 73 "show this notification" requests in there. At first it created notification 12 and then it replaces that one 72 times with an identical(?) notification. Trying to replace an already-existing notification just opens it again, so when you close it by clicking, the NetworkManager immediately opens a new notification. Sadly, I don't have timestamps and thus cannot say how quickly this happens.

Which awesome version are you using? Never versions support larger parts of the spec.

**Comment by ilpianista** [comment]
*awesome 3.5.6* here. Should I try -git?

**Comment by psychon** [comment]
Would be nice, something after commit 26ffd2c6f2e1d8278536bb0252946bef9a781900 with the default config. I'm interested in what happens and also in some `dbus-monitor` output for this.

With these changes, awesome can tell NetworkManager "your notification was closed" and perhaps it then stops re-opening it all the time. Although I really would like to know why it does this...

**Comment by ilpianista** [comment]
Yeah! It's fixed in current git :+1: 
Great!
