### ISSUE TITLE
Quitting from main menu doesn't work

### ISSUE THREAD

**Issue by Dhekke** [awesomeWM/awesome#1908]
**Output of `awesome --version`:**

    awesome v4.1 (Technologic)
    - Compiled against Lua 5.3.4 (running with Lua 5.3)
    - D-Bus support: ✔
    - execinfo support: ✔
    - xcb-randr version: 1.5
    - LGI version: 0.9.1

**How to reproduce the issue:**

Open the main menu, go to `awesome -> quit`

**Actual result:**

I'm getting an error message saying:

    /usr/share/awesome/lib/aweful/menu.lua:302:
        bad argument #1 to 'cmd' (number expected, got table)

Everything was working fine the last time I used Awesome, but I don't remember what version that was...

**Expected result:**

Quit awesome

**Comment by actionless** [comment]
it is fixed already but it seems what your config is based on an older rc.lua version:

https://github.com/awesomeWM/awesome/commit/70f9999a068d4e7131c0ce0d57062743f153fd08
