### ISSUE TITLE
Command starting with "true" breaks completion tests

### ISSUE THREAD

**Issue by FloGa** [awesomeWM/awesome#1923]
While working on #1876, I noticed the following issue: Many tests rely on the fact that there is only one command that can be completed with "true", namely `true`. If however there is another command in `PATH` that starts with "true", then six tests fail because of that (tested with current master).

Example:

    $ touch ~/bin/truebar && chmod +x ~/bin/truebar
    $ cd ~/Projects/awesome
    $ make clean check-unit
    # (Output cropped, there are five identical messages from other tests)
    # ...
    Failure → spec/awful/completion_spec.lua @ 46
    awful.completion.shell in empty directory handles completion of true (bash)
    spec/awful/completion_spec.lua:47: Expected objects to be the same.
    Passed in:
    (table) {
      [1] = 'true'
      [2] = 5
     *[3] = {
        [1] = 'true' } }
    Expected:
    (table) {
      [1] = 'true'
      [2] = 5
     *[3] = {
        [1] = 'true'
       *[2] = 'truebar' } }
    # ...

I tried to change the related tests to not use `assert.same` but instead some sort of a "contains" check, but to give meaningful pass/fail messages I would have to rebuild parts of luassert, including several import requirements, which would be a huge overkill for this issue.

Any ideas how it could be solved otherwise?

**Comment by blueyed** [comment]
I think we should set PATH completely to something we control.

**Comment by FloGa** [comment]
I considered this possibility, but I couldn't find a good point in the command chain where I could modify the PATH reliably, without breaking functionality. We would have to modify the completion command so that it accepts environment variables to be passed down to `/usr/bin/env`. In the testing area, we would have to copy the Bash executable into a local directory, so it is found with the modified PATH.

Would this be acceptable for you?

**Comment by blueyed** [comment]
Sounds good to me.

The EDIT basically creates a symlink?!

**Comment by FloGa** [comment]
The (pseudo-)command I posted creates a tiny script that calls the actual bash, but a symlink might be an even better idea. I'm just careful with symlinks, because some programs behave differently when called via symlink. I'll test what works best.

**Comment by FloGa** [comment]
Since issue-to-pullrequest seems to be deprecated, I created a new PR for this feature:  #1957
