### ISSUE TITLE
Implement request::minimized

### ISSUE THREAD

**Issue by ghost** [awesomeWM/awesome#193]
i have a client, which serves as a desktop, that i never want to minimize, but may minimize by accident. i would like to be able to set in my config that it should never be allowed to be minimized.

**Comment by psychon** [comment]
How about this: Add a new rule to awful.rules that matches your client and has:
```lua
callback = function(c)
   c:connect_signal("property::minimized", function()
    if not c.minimized then return end
    -- Just for testing, remove this when the code works
    naughty.notify({text = "Preventing minimization of " .. tostring(c.name)})
    c.minimized = false
  end
end
```
I'll close this under the assumption that the above works. This is simple enough that I don't think we should add special magic for this to awesome.

(And yes, this does not actually prevent minimization, but instead immediately undoes it. Is that a problem?)
