### ISSUE TITLE
NPE in keyboardlayout

### ISSUE THREAD

**Issue by boris-petrov** [awesomeWM/awesome#1933]
[This PR](https://github.com/awesomeWM/awesome/pull/1771) breaks things for me. I'm getting:

```
/usr/share/awesome/lib/awful/widget/keyboardlayout.lua:123: attempt to concatenate a nil value (field '?')
```

Reverting the commit fixes the issue.

Output of `awesome --version`:

```
%  awesome --version
awesome v4.2 (Human after all)
 • Compiled against Lua 5.3.4 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.5
 • LGI version: 0.9.1
```

**Comment by psychon** [comment]
Could you e.g. add `require("gears.debug").dump(self._layout)` or `require("naughty").notify{ text = require("gears.debug").dump_return(self._layout)` before line 123 and figure out what layouts are detected for you?
Put differently: What exactly is going on here?

**Comment by mbuelte** [comment]
Hi, I've got the same problem after an upgrade, here is the output of 'require("gears.debug").dump(self._layout)' above line 123:

```
table: 0x585afeaa0c0
  1 : de (string)
```

**Comment by boris-petrov** [comment]
@psychon - sorry for the delay. The output:

```
table: 0x55e959041ec0
  0 : En (string)
  1 : Bg (string)
```

Note, however, that I've changed the original names to `En` and `Bg`, but I don't think this matters.
