### ISSUE TITLE
3.5.6-r2 installed but 4.0 and 4.1 failed

### ISSUE THREAD

**Issue by txl263** [awesomeWM/awesome#1935]
gentoo install log 
https://bpaste.net/raw/5620d7700608
Linux Gentoo 4.9.34-gentoo #1 SMP Fri Jul 21 01:12:26 CST 2017 x86_64 Intel(R) Core(TM) i7-2635QM CPU @ 2.00GHz GenuineIntel GNU/Linux

**Comment by psychon** [comment]
Uhm... where is the failure? The build log says that everything worked fine and then your package manager decided that it considers the built to have failed.

I have no idea what `/proc/driver/prl_vtg` is, but apparently awesome built fine even though something tried to open the file, which was denied.

**Comment by txl263** [comment]
![image](https://user-images.githubusercontent.com/969317/28455650-59104f9a-6e32-11e7-8ae5-1dd80e0820cb.png)

**Comment by psychon** [comment]
After having found https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=773303, I am now even more sure that `prl_vtg` belongs to Parallels. I have no idea how they broke your system, but I am sure that it was them.

You could try figuring out which of the following commands reproduce the breakage and then continue from there to figure out how Parallels hooked in there to cause that file to be opened:
```sh
lua -e 'assert(require("lgi").GLib)'
lua -e 'assert(require("lgi").Gio)'
lua -e 'assert(require("lgi").cairo)'
lua -e 'assert(require("lgi").Pango)'
lua -e 'assert(require("lgi").PangoCairo)'
```

**Comment by psychon** [comment]
On your image, let me repeat myself:

> The build log says that everything worked fine and then your package manager decided that it considers the built to have failed.

The only error message is from your package manager (emerge?). We do not control what emerge does. Nothing in there says that anything that awesome does failed.
