### ISSUE TITLE
Strange NET_WM_WINDOW_TYPE_ of tooltip?

### ISSUE THREAD

**Issue by Bekcpear** [awesomeWM/awesome#1938]
Output of `awesome --version`:

```
awesome v4.2 (Human after all)
 • Compiled against Lua 5.3.4 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.5
 • LGI version: 0.9.1
```

**How to reproduce the issue:**
execute `compton` with following configuration
```
...
...
wintypes:
{
        # fade: Fade the particular type of windows.
        # shadow: Give those windows shadow
        # opacity: Default opacity for the type of windows.
        # focus: Whether to always consider windows of this type focused.
    dock = { fade = true; shadow = true; opacity = 0.85; focus = true; };
    tooltip = { fade = true; shadow = false; opacity = 0.85; focus = true; };
    menu = { fade = true; shadow = false; opacity = 0.85; focus = true; };                                                                                            
    popup_menu = { fade = true; shadow = false; opacity = 0.85; focus = true; };
    dropdown_menu = { fade = true; shadow = false; opacity = 0.85; focus = true; };
    notify = { fade = true; shadow = false; opacity = 0.85; focus = true; };
};
```

**Actual result:**

the tooltip is still completely opaque, unless add config `normal = { fade = true; shadow = false; opacity = 0.85; focus = true; };` into the configuration file. However the "normal" will make all windows(clients) transparent.  

**Expected result:**

make tooltip transparent when setting `tooltip = { fade = true; shadow = false; opacity = 0.85; focus = true; };` in the compton configuration file.

*I guess the tooltip has a wrong NET_WM_WINDOW_TYPE?*

**Comment by psychon** [comment]
Could you test if https://github.com/awesomeWM/awesome/pull/1939 fixes this? It's a trivial patch that you can easily apply to your `/usr/share/awesome/lib/awful/tooltip.lua` with a text editor: https://github.com/awesomeWM/awesome/pull/1939/files

**Comment by Bekcpear** [comment]
Yes, it has been fixed. Efficient work, thanks very much.
