### ISSUE TITLE
Resize window issue when running on multiple GPUs + Xinerama

### ISSUE THREAD

**Issue by frobbit** [awesomeWM/awesome#1945]
Output of `awesome --version`:

awesome v4.0 (Harder, Better, Faster, Stronger)
 • Compiled against Lua 5.1.5 (running with Lua 5.1)
 • D-Bus support: ✔
 • execinfo support: ✔
 • RandR 1.5 support: ✔
 • LGI version: 0.9.1

**How to reproduce the issue:**

Run a system with multiple GPUs + Xinerama. In my case I use Nvidia NVS 450 and NVS 440, which both actually are 2x GPUs each under the hood. The OS is Debian 9, and the Nvidia drivers are the 304.xx legacy drivers. So separate Xscreens which are merged together with Xinerama, spanning several GPUs.

In this setup, when I use modkey + right mouse button to resize a window, it seems to go OK on the screens on the first GPU (GPU0), but for other screens, the right side of the window is sometimes initially stretched to a screen edge before resizing starts (not necessarily the monitor edge, but the edge of the particular Xscreen). This can cause the window to become very wide before resizing can start.

To work around this I have to move windows first to a screen on GPU0, then resize, then move back, but it still feels kind of annoying... Incidentally, modkey + left button for window move works fine with no issues, though.

**Actual result:**

Windows on screen other than those on GPU0 are stretched, possibly very wide, before resizing starts

**Expected result:**

Resize proceeds as usual

**Comment by psychon** [comment]
I'm a bit confused about "stretched to the edge of the screen". Does this happen before you actually move the mouse once? What happens if you just right click without dragging, i.e. does the window stay at this larger size? Does "stretch" mean "its content is upscaled" or do you mean "the window is resized to a larger size"?

**Comment by frobbit** [comment]
Hi,

Yes it happens directly after the click, before I subsequently move the
mouse. So if I do modkey+right click it will stretch to the screen edge
(which can be on the "next" monitor since I'm using TwinView), and the
window will stay at the larger side unless I then move the mouse to resize
it.

By stretched I didn't mean the content is deformed or upscaled, but it is
simply as if the window is instantaneously resized by its right border
being moved to the screen edge. Content inside the window is still correct
apart from that.

E.g. I just tested resizing my email window by modkey right click on lower
right corner. Its right edge moves to the right side of the next monitor,
so it becomes extremely wide.

Another thing I just noticed is that the resizing is then not anchored to
the lower right of the window, but the bottom. I guess the anchoring have
been done against this new larger width?.. In any case, to resize back to
normal I have to release mouse, then move to the new lower right of the
window (which is now at the right edge of the next screen) and then repeat
the modkey + right click.  Doing that then works as expected.

**Comment by frobbit** [comment]
Hi, I took a video illustrating the issue. I apologize for the low quality (I filmed with my phone with one hand while controlling mouse+keyboard with my other)

https://www.youtube.com/watch?v=xJVv69ERDqs

**Comment by psychon** [comment]
Thanks for the video. It looks to me as if the window is first resized to "large, but not completely up to the next monitor" and then the window is moved so that its right edge hits the edge of the screen. (Either that or it is immediately resized to that size and then the left edge is moved, making the window smaller)

This reminds me a bit of #154 (that one also involved Xinerama). There, the issue was "clicking on the taglist of screen 1 or screen 2 is always counted as a click on screen 1". As far as I remember, the conclusion was that the X11 server gets "something wrong" and we are being sent a wrong mouse position (the "correct" position is moved to the other monitor and then sent out to us).

Right now I have no idea how to check if this really is the issue and the X11 server is sending us wrong mouse positions (well, I could provide patches to the C source code which print coordinates, but that won't help you much; running awesome under `xtrace` is too spammy)....

**Comment by frobbit** [comment]
Could I set the modkey+right click key binding to some custom Lua function that wraps awful.mouse.client.resize, and from the wrapper write out the coordinates to console/disk ? Or would the mouse coordinates returned into Lua be different than those seen inside the C code for the resize?

**Comment by psychon** [comment]
If you just want the coordinates at the time the mouse was clicked:
```lua
function(c)
  local m = mouse:coords()
  print(m.x, m.y)
  awful.mouse.client.resize(c)
end
```
For "some more" information, I would propose the following patch:
```diff
diff --git a/lib/awful/mouse/init.lua b/lib/awful/mouse/init.lua
index d47e934..f208261 100644
--- a/lib/awful/mouse/init.lua
+++ b/lib/awful/mouse/init.lua
@@ -178,6 +178,15 @@ function mouse.client.corner(c, corner)
     return corner, ngeo and ngeo.x or nil, ngeo and ngeo.y or nil
 end
 
+function print_mouse_explicit(what, x, y)
+    print(string.format("%s mouse=(%d,%d)", tostring(what), x, y))
+end
+
+function print_mouse(what)
+    local m = capi.mouse:coords()
+    print_mouse_explicit(what, m.x, m.y)
+end
+
 --- Resize a client.
 -- @function awful.mouse.client.resize
 -- @param c The client to resize, or the focused one by default.
@@ -186,6 +195,7 @@ end
 -- @treturn string The corner (or side) name
 function mouse.client.resize(c, corner, args)
     c = c or capi.client.focus
+    print_mouse("client.resize called")
 
     if not c then return end
 
@@ -210,6 +220,7 @@ function mouse.client.resize(c, corner, args)
     -- Move the mouse to the corner
     if corner and aplace[corner] then
         aplace[corner](capi.mouse, {parent=c})
+        print_mouse("moved mouse to corner")
     else
         local _
         _, corner = aplace.closest_corner(capi.mouse, {
diff --git a/lib/awful/mouse/resize.lua b/lib/awful/mouse/resize.lua
index 15bfe8d..5c2a134 100644
--- a/lib/awful/mouse/resize.lua
+++ b/lib/awful/mouse/resize.lua
@@ -153,7 +153,10 @@ local function handler(_, client, context, args) --luacheck: no unused_args
         or "fleur"
 
     -- Execute the placement function and use request::geometry
+    print_mouse("before mousegrabber")
     capi.mousegrabber.run(function (_mouse)
+        print_mouse("inside mousegrabber")
+        print_mouse_explicit("explicit position is", _mouse.x, _mouse.y)
         if not client.valid then return end
 
         -- Resize everytime the mouse moves (default behavior).
@@ -169,6 +172,7 @@ local function handler(_, client, context, args) --luacheck: no unused_args
             geo = cb(client, geo, args) or geo
 
             if geo == false then
+                print("end 1")
                 return false
             end
         end
@@ -177,6 +181,7 @@ local function handler(_, client, context, args) --luacheck: no unused_args
             geo = args.move_callback(client, geo, args)
 
             if geo == false then
+                print("end 2")
                 return false
             end
         end
@@ -193,6 +198,7 @@ local function handler(_, client, context, args) --luacheck: no unused_args
         for _,v in pairs(_mouse.buttons) do
             if v then return true end
         end
+        print("all mouse buttons released")
 
         -- Only resize after the mouse is released, this avoids losing content
         -- in resize sensitive apps such as XTerm or allows external modules
```

**Comment by frobbit** [comment]
Hi, 

I printed mouse coordinates, and also added information on current client/screen etc. That all looks OK and as expected. 

I narrowed down the event to something happening inside the     mouse.resize(c, "mouse.resize", new_args) at the end of function mouse.client.resize(c, corner, args) in lib/awful/mouse/init.lua. If I comment out that line there is no strange resizing (but of course, the resizing functionality itself does not work)..

I then modified the handler(_, client, context, args) in mouse/resize.lua... It seems to be happening for the live resizing.. If I comment out:

        --if args.mode == "live" then
            -- Ask the resizing handler to resize the client
            --client:emit_signal( req, context, geo)
        --end
and then make the "after" code always occur by setting:
--        if args.mode == "after" then
            -- Get the new geometry
            geo = args.placement(client, args)

            -- Ask the resizing handler to resize the client
            client:emit_signal( req, context, geo)
--        end
I get correct resizing behaviour (of course, without the live resizing). The mouse goes to correct corner, and on button release the window is resized as it should.

**Comment by frobbit** [comment]
I've further been able to narrow down to it coming from capi.mouse.coords() at the top of placement.resize_to_mouse(d, args). The first time this is called in the resize loop it has an incorrect X coordinate. The logic in the placement.resize_to_mouse then causes the window to have the large width.

This only happens the first time in the resize loop. On subsequent calls the capi.mouse.coords() in the placement function does return the correct values... So it was the mouse coordinates coming from capi all along (although from my other debug prints I can see that the mouse coordinate are correct before going into the resize loop). 

Could something be happening when the mouse is grabbed, or something similar?

**Comment by psychon** [comment]
> coming from capi.mouse.coords()

This function just asks the X11 server for mouse coordinates and returns the result (if you know some C: `mouse.c`, function `luaA_mouse_coords` which then calls `mouse_query_pointer_root`, which calls  `mouse_query_pointer`, which asks the X11 server for the mouse position).

It might still be something in Lua mis-placing the mouse. When you start resizing, `awful.mouse.client.resize` tries to move the mouse to the corner of the client being resized. Could you check if something here mis-computed some coordinates?
Either this patch should do (the `aplace` call directly before is what should move the mouse to the corner of the client):
```diff
diff --git a/lib/awful/mouse/init.lua b/lib/awful/mouse/init.lua
index d47e934..c05d0bd 100644
--- a/lib/awful/mouse/init.lua
+++ b/lib/awful/mouse/init.lua
@@ -210,6 +210,8 @@ function mouse.client.resize(c, corner, args)
     -- Move the mouse to the corner
     if corner and aplace[corner] then
         aplace[corner](capi.mouse, {parent=c})
+        local coords = capi.mouse.coords()
+        print(coords.x, coords.y)
     else
         local _
         _, corner = aplace.closest_corner(capi.mouse, {
```
or directly touch `awful.placement` and make it print something whenever it moves the mouse (this might be a better idea in case something else that I am missing right now also calls into `awful.placement`):
```diff
index 1de4c8b..c65f15b 100644
--- a/lib/awful/placement.lua
+++ b/lib/awful/placement.lua
@@ -387,6 +387,7 @@ local function geometry_common(obj, args, new_geo, ignore_border_width)
     if obj.coords then
         local coords = fix_new_geometry(new_geo, args)
             and obj.coords(new_geo) or obj.coords()
+        print("moved mouse to ", coords.x, coords.y, "input was:",new_geo.x, new_geo.y)
         return {x=coords.x, y=coords.y, width=0, height=0}
     elseif obj.geometry then
         local geo = obj.geometry
```

> Could something be happening when the mouse is grabbed, or something similar?

Of course, yes. However, I don't see why that would only happen "briefly" and immediately afterwards be undone and we get the correct mouse position again.

**Comment by Elv13** [comment]
The issue would make sense if the code gets the "parent area" wrong. If there is some kind of race and the mouse moving code end up thinking the *screen* is the parent area instead of the client, then it will move the cursor to the edge of the screen instead of the edge of the client.

**Comment by frobbit** [comment]
Hi, I added the prints for the movement, but it does not seem to be moved.

I then added mouse coord printing just before the mousegrabber is run, and at the top of the mousegrabber function:

     local mgeo = capi.mouse:coords()
     print("Pre-mousegrabber run", mgeo.x,mgeo.y)
    -- Execute the placement function and use request::geometry
    capi.mousegrabber.run(function (_mouse)
          local mgeo = capi.mouse:coords()
          print("Mousegrabber run", mgeo.x,mgeo.y)

I see from the printouts:

Pre-mousegrabber run    2685    882
Mousegrabber run        4864    882

i.e. the x-coordinate was correct just before capi.mousegrabber.run but has moved to the spurious "next screen" coordinate immediately upon entering the callback function

**Comment by frobbit** [comment]
I am able to seemingly work around the whole issue by doing:

    count = 0
    -- Execute the placement function and use request::geometry
    capi.mousegrabber.run(function (_mouse)
         count = count + 1
         if count == 1 then
            return true
         end


i.e. add some logic that just disregards the first call into the callback. Of course, this is no fix, but at least now my resizing seems to work completely fine.

**Comment by psychon** [comment]
> I then added mouse coord printing just before the mousegrabber is run, and at the top of the mousegrabber function:

Just to avoid confusion: The `mousegrabber` callback does not run immediately, but only when the next mouse event comes in (either move or some button was pressed/released).

On this issue: Seems like the X11 server is doing something weird? I am just not sure what exactly it might be doing wrong. I also do not see what I can do about this.
My only/best idea would be: Can you try writing some minimal reproducer for this? For example, is the following function used instead of `awful.mouse.client.resize` enough to trigger the problem? (Disclaimer: This is completely untested, I just want to illustrate the idea)
```lua
function (c)
  local geo = c:geometry()
  -- Move mouse to bottom right corner of client (this ignores border width)
  mouse.coords{ x = geo.x + geo.width, y = geo.y + geo.height }
  mousegrabber.run(function(m)
    local m2 = mouse.coords()
    print("mouse at", m.x, m.y, "aka", m2.x, m2.y)
    -- Stop when all mouse buttons are released
    for _,v in pairs(m.buttons) do
      if v then return true end
    end
    return false
  end)
end
```
(No idea if that moving-the-mouse-to-the-corner-of-the-client is necessary)

**Comment by frobbit** [comment]
Hi, yes that reproduces the issue:

mouse at        2942    1068    aka     4864    1068
mouse at        2942    1068    aka     2942    1068

so in the first call of the callback the x coordinate has the spuriously
large value. On the second call it's "back to normal".

It could be the X server doing something. I'm using quite old graphics
cards (NVS 450, NVS 440) which use the Nvidia legacy driver, and running
through Xinerama (XRandr is completely disabled).

**Comment by psychon** [comment]
> mouse at        2942    1068    aka     4864    1068

So the event itself has the right coordinates, but asking for the current coordinates (sigh, an useless roundtrip to the X11 server which I'd like to see gone anyway) yields the wrong coordinates... but only after the first mousegrabber event?
Also, why are we getting this event anyway? It looks like the mouse "did not really" move and we should only get events when it moves?

Next step would be to debug what is up with the X11 server... but I don't know a lot about Xorg's code plus Nvidia's binary blob is involved. Sorry, no. :-(

**Comment by frobbit** [comment]
Could the event be generated as a consequence of grabbing the pointer or
something?

I agree that if the problem is coming from inside XOrg or Nvidias drivers
then it would probably be a hopeless task to diagnose the reason..  I guess
only solution in that case is to report it as a bug to them..

It's probably not relevant, but I tried KDE and there resizing works as
expected. Of course, I don't know what mechanisms they are using for it.

**Comment by psychon** [comment]
> Could the event be generated as a consequence of grabbing the pointer or
something?

Well, try printing the mouse position before the `mousegrabber` is started. If all the mouse positions are the same (before and inside the mouse grabber), then there was no real mouse movement, so the event must be caused by just grabbing the mouse.

> It's probably not relevant, but I tried KDE and there resizing works as expected. Of course, I don't know what mechanisms they are using for it.

Well, just using the cursor positions that we get from the mouse grabber instead of re-asking for them seems to be enough. So I guess KDE does not (needlessly) re-query the mouse position.

**Comment by moxian** [comment]
I've ran into the same issue (initiating resize snapping the mouse way to the bottom/right) when adjusting mouse sensitivity with xinput. I don't have xinerama (and I only have one monitor) so this might provide an easier way to reproduce the issue.

To reproduce:
```
$ xinput  # to get the list of devices, find your mouse id in there, use it instead of 11 below
$ xinput --set-prop 11 'Coordinate Transformation Matrix' 2.0, 0.0, 0.0, 0.0, 2.0, 0.0, 0.0, 0.0, 1.0
```

This makes the mouse sensitivity twice as high (expected), and moves the mouse cursor to "twice" the coordinate of the initial grab (not expected), mouse movement after the initial resizing "tick" work as expected.

I don't understand Awesome (or X11, really) internals well enough to draw any conclusions.

```
$ awesome --version
awesome v4.2 (Human after all)
 • Compiled against Lua 5.1.5 (running with Lua 5.1)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.0
```

**Comment by psychon** [comment]
Sounds like an Xorg bug then

**Comment by psychon** [comment]
https://www.reddit.com/r/awesomewm/comments/bh57fo/default_mouse_resizing_behaving_strangely/
https://gitlab.freedesktop.org/xorg/xserver/issues/633

Looks like this really is a bug in Xorg and it will not be fixed. The official solution seems to be "do not use 'Coordinate Transformation Matrix'".
