### ISSUE TITLE
master_fill_policy doesn't work on fair layouts?

### ISSUE THREAD

**Issue by r3lgar** [awesomeWM/awesome#1949]
So it should be?

```
awesome v4.2-14-g82fd7ea8-dirty (Human after all)
 • Compiled against Lua 5.1.4 (running with LuaJIT 2.0.4)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.5
 • LGI version: 0.9.1
```

**Comment by Elv13** [comment]
No, it does not support it. If you wish to implement such layout, take a look at the #644 branch. Here's the documentation

https://elv13.github.io/libraries/awful.layout.html

The current layout system is rather inflexible. Each layout need to implement each options itself (beside the `gap`, which is now mutualized across everything)

**Comment by r3lgar** [comment]
> take a look at the #644 branch

Yeah, good stuff.

>https://elv13.github.io/libraries/awful.layout.html

Oh, thanks.

>The current layout system is rather inflexible. Each layout need to implement each options itself (beside the `gap`, which is now mutualized across everything).

Sigh. Let's wait for 5.0.

**Comment by Elv13** [comment]
> Sigh. Let's wait for 5.0.

The code is compatible with Awesome 4.2. You can copy/paste the `dynamic` directory to `~/.config/awesome/` and `require` it. It will just work.

**Comment by r3lgar** [comment]
>The code is compatible with Awesome 4.2.

>It will just work.

I need to try, thanks.

>You can copy/paste the dynamic directory to ~/.config/awesome/ and require it.

From where? I didn't find the repo. I'm not so familiar with GitHub.

**Comment by psychon** [comment]
I think the following should work for you:
```
git clone https://github.com/Elv13/awesome-1.git
cd awesome-1
git checkout origin/upstream_dynamic_p7
```
The code should then be in `lib/awful/layout/dynamic/`.

**Comment by r3lgar** [comment]
Ah, this is detached branch so I didn't find it. Thanks.

**Comment by blueyed** [comment]
Closing this then for now.
