### ISSUE TITLE
Prompt doesn't find executables outside the normal $PATH, but TAB completes them

### ISSUE THREAD

**Issue by michaelbeaumont** [awesomeWM/awesome#1956]
`awful.widget.prompt` seems unable to execute commands that don't lie on the default `$PATH`

Output of `awesome --version`:

awesome v4.2-17-g28860953 (Human after all)
 • Compiled against Lua 5.3.4 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.5
 • LGI version: 0.9.1

**How to reproduce the issue:**

1. Have custom directories on `$PATH` (e.g. `~/.local/bin`) that contain executable binaries (e.g. `pulp`)
2. In the prompt box, enter the beginning of the executable (`pul`). TAB successfully completes the command.
3. Hit enter

**Actual result:**

Error `Failed to execute child process "pulp" (No such file or directory)`

**Expected result:**

The command is executed

**Comment by blueyed** [comment]
Sounds like you're changing the `$PATH` only after awesome has been started, e.g. in your bashrc.
You should to this in bash_profile or similar.

**Comment by r3lgar** [comment]
Just source your `~/.bashrc`/`~/.bash_profile` in your `~/.xinitrc` or, if you start session by desktop file (GDM, KDM, SDDM, LightDM), `/etc/profile.d/` (use `$HOME` variables here, not `~`).

**Comment by michaelbeaumont** [comment]
Apparently, `~/.profile` isn't loaded but `~/.bash_profile` is, fixed `~/.bash_profile` to source `~/.profile`. Thanks!
