### ISSUE TITLE
Icon fonts for default UI graphics

### ISSUE THREAD

**Issue by tomoyat1** [awesomeWM/awesome#1959]
Would there be any intrest in changing all of the icons used throughout the default themes from PNGs to icon fonts, in similar fashion to Font Awesome. 

The pros would be
* The icons could be scaled
* The colors could be easily changed, especially when they are used in users' custom themes.

**Comment by psychon** [comment]
How would awesome use those fonts? AFAIK there is no simple "here is a path to a font, use it"-API. If you think of installing the fonts system-wide: Is that really a good idea?

**Comment by tomoyat1** [comment]
Without any modifications to Awesome, it would have to get the fonts from fontconfig. Fonts would have to be either installed system-wide, or installed per-user for each user that uses Awesome.

The code points would be in the Private Use Area of Unicode, so there would be a low chance of them affecting other parts of the system, were the fonts be installed system-wide.

Saying "here's a path to a font file, you should use it too" seems to be possible at the Pango level. (I read something about "modifying the local fonconfig state")
I think a little bit of coding in Beautiful could expose that to theme configs, if we were to avoid installing the font system-wide.

**Comment by psychon** [comment]
> Saying "here's a path to a font file, you should use it too" seems to be possible at the Pango level. (I read something about "modifying the local fonconfig state")

Problem is: fontconfig has no Lua bindings, so we cannot modify its state (Google found https://stackoverflow.com/questions/10722577/loading-a-font-from-a-file-to-pango)

**Comment by tomoyat1** [comment]
Could I try hacking a fonconfig binding together?

**Comment by psychon** [comment]
Dunno. I won't stop you, but I'm not sure if awesome should grow new dependencies.

**Comment by psychon** [comment]
Also, wouldn't this kind of change make replacing the icons harder? Right now, people can just point to another PNG file in their theme...

**Comment by tomoyat1** [comment]
I agree this might be too radical of a change.

**Comment by tomoyat1** [comment]
I am going to close this issue.

https://awesomewm.org/doc/api/libraries/beautiful.theme_assets.html#awesome_icon
I thought that extending this API to include layout icons is a better approach.

**Comment by actionless** [comment]
@tomoyat1 but it's including layout icons:
https://awesomewm.org/doc/api/libraries/beautiful.theme_assets.html#recolor_layout
