### ISSUE TITLE
Play notification sound?

### ISSUE THREAD

**Issue by Plasticoo** [awesomeWM/awesome#1965]
Is there a way of playing a certain sound when a notification activates?

**Comment by psychon** [comment]
You mean notifications from `naughty`?
```lua
function naughty.config.notify_callback(args)
    print("New notification with text '" .. tostring(args.text) .."'")
    return args
end
```
I'll leave it to you to find something that can play a sound (`awful.spawn{ "aplay", "/foo/bar/baz" }` or something like that?)

**Comment by Plasticoo** [comment]
Sorry, I didnt make myself clear!

There are applications that give you notifications, like Discord and others.
But I want to play a sound when those applications give me notifications.

Is that possible?

**Comment by psychon** [comment]
What kind of notification are they giving you? A notification popup through naughty?

**Comment by Plasticoo** [comment]
Well, I am sure it is, because it uses naughty settings, like the display of images. I even deactivated the showing of images for it to not get too big, through `theme.notification_icon_size`.

**Comment by psychon** [comment]
Okay, can you detect the notification based on its text? For example
```lua
function naughty.config.notify_callback(args)
    if string.find(args.text, "Time to go to bed") then
        -- Do something here
    end
    return args
end
```
Alternatively:
```lua
function naughty.config.defaults.callback(_, appname)
    print(appname) -- perhaps this one is useful for you?
end
```

**Comment by Plasticoo** [comment]
It works, very well indeed. Using the first snippet of code. Thank you very much!

**Comment by blueyed** [comment]
@Plasticoo 
btw: take a look at dunst if you like customized notifications, too: https://github.com/dunst-project/dunst

**Comment by Plasticoo** [comment]
@blueyed 
Hey!
Sorry for the late response!
I know about Dunst indeed, but I would prefer the awesomeWM notification system, I don't want... extra things, I guess. But, fortunately, it is already working the way I want! :)

Cheers!

**Comment by kajzersoze** [comment]
There is notification hint `--hint=string:sound-file:filename` like there is --icon for example, so when you issue this command in terminal :
`notify-send "Some title" "Some text" --hint=string:sound-file:/usr/share/sounds/freedesktop/stereo/service-login.oga`

it will produce a sound on most notification daemons, that's what's missing here with naughty.

**Comment by blueyed** [comment]
FWIW: dunst also does not play it.

**Comment by rjshrjndrn** [comment]
@blueyed is it possible to replace naughty with dunst? I found naughty is lagging behind, like 
- can't see history
- Won't open the slack message, which I got notified
- No sound
etc...

Or is there any way to achieve those with naughty also? some plugins may be. Google doesn't seems to know much about that.

**Comment by actionless** [comment]
> Or is there any way to achieve those with naughty also? some plugins may be. Google doesn't seems to know much about that.

you can achieve that only by doing some extra coding on top ([ex](https://github.com/actionless/awesome_config/blob/master/actionless/widgets/naughty_sidebar.lua)), it's not possible out of the box

**Comment by psychon** [comment]
With current Git, AFAIK `package.loaded["naughty.dbus"] = {}` is enough to get rid of naughy's dbus integration. Alternatively, just don't `require("naughty")` anywhere.

**Comment by rjshrjndrn** [comment]
@psychon I tried both.. Not working. !!
Can you gimme a sample snippet ? may  be I'm doing something wrong..

**Comment by rjshrjndrn** [comment]
Got it!!!
Basically I had to disable all naughty and add `package.loaded["naughty.dbus"] = {}`
Thanks a ton @psychon
