### ISSUE TITLE
Shared awesome config with slight differences

### ISSUE THREAD

**Issue by johannesmenzel** [awesomeWM/awesome#1969]
Output of `awesome --version`:

awesome v4.0 (Harder, Better, Faster, Stronger)
 • Compiled against Lua 5.1.5 (running with Lua 5.1)
 • D-Bus support: ✔
 • execinfo support: ✔
 • RandR 1.5 support: ✘
 • LGI version: 0.9.1

**How to reproduce the issue:**

Having the same configuration for multiple computers shared via cloud

**Actual result:**

nothing urgent

**Expected result:**

Shared Awesome configuration with slighly different properties.

Hello,

don't know if I'm right here in the issues section, but I don't know exactly were to find best community support for things.

The current situation is as follows: I have a custom made Awesome configuration (rc.lua/theme/some well known widgets), which I already share with multiple computers synchronizing with seafile and connecting the ~/.config/awesome with a symbolic link to the configuration folder in the cloud.

Actually it works fine, but I need some computer specific setup. Anyway, I want to keep up having shared rc.lua and theme.lua files, so that I can configure Awesome for all computers in the same time.

Maybe you have an advice for me, how I could (dynamically) fit some setup. Maybe you can tell me by one example:

For example the lain net widget has to connect to a network interface. One has "wlp4s0", the other "wlan0", the default settings do not work (I think because it gets "eth0" by default.) I know, I could add both as a string and it would sum them up, but I'm searching for a rather theoretically solution. Maybe some lua-code, which says, "if computer-name XYZ, then interface name "ABC, or send client to tag X screen Y".

Another example would be, that some computers have two displays, and I'd like to have one rc.lua, which may be create tags for one or two screens, depending on the computer in use.

Do you have any ideas?

**Comment by psychon** [comment]
For the number of screens: Just check `screen.count()` to see how many screens are there. This does not have to be specific to some computer.

For the network interface name:
Add a file `~/.config/awesome/network_interface_name.lua` containing `return "wlp4s0"`. In your `rc.lua`, use either `local interface_name = require("network_interface_name")` and then use `interface_name` instead of `"wlp4s0"`, or alternatively directly use `require("network_interface_name")` instead of `"wlp4s0"`.
I don't know lain's syntax right now, but:
Before:
```lua
local my_network_widget = lain.network("wlp4s0")
```
After:
```lua
local my_network_widget = lain.network(require("network_interface_name"))
```

If you have your whole `~/.config/awesome` in seafile, you could also put the file anywhere else (e.g. `~/.interface_name_for_awesome`) and then use `dofile(os.getenv("HOME") .. "/.interface_name_for_awesome)` instead of `require("network_interface_name")`.

**Comment by johannesmenzel** [comment]
Thanks for the fast answer. I already set up the current interface in my theme.lua. The outcome I want to have is, that I want to connect net widget to interface "wlp4s0" sitting on this computer and to "wlan0" sitting on the other.

**Comment by johannesmenzel** [comment]
OK, you mean, I should have ~/.config/awesome/network_interface_name.lua non-synchronized on each computer?

**Comment by nickdiego** [comment]
Hi,

I think you can combine the approach recommended by @psychon with some code to conditionally set the machine-specific parameters (wlan interface, etc..), for example, using "hostname" to detect what machine you are running on..

**Comment by psychon** [comment]
> OK, you mean, I should have ~/.config/awesome/network_interface_name.lua non-synchronized on each computer?

Yup.

**Comment by johannesmenzel** [comment]
Yeah, I was searching for something like this, nickdiego. My problem is, that I'm not familiar with lua by now, I even don't know exactly how to make an if-then-condition or how to address the host name.

Thats why I asked for a sample code for a specific problem, more exactly, the lua-code for: "if the computers name is XYZ, then make ABC your local wifi interface".

But otherwise, I like the solution of psychon as well, maybe having a .config/awesome-local folder with all the stuff.

**Comment by psychon** [comment]
> I even don't know exactly how to make an if-then-condition or how to address the host name.

```lua
local hostname = io.popen("hostname"):read("*a")
if hostname == "XYZ\n" then
    -- something
else
    -- something else
end
```
(Yes, the `\n` after `XYZ` is important)

**Comment by johannesmenzel** [comment]
So I could place following code to the net widget section of my theme.lua:

```
-- Net
local neticon = wibox.widget.imagebox(theme.widget_net)
local hostname = io.popen("hostname"):read("*a")
if hostname == "Travelmate5720\n" then
    local localnet = "wlp4s0"
elseif hostname == "Thinkpadx121e\n" then
    local localnet = "wlan0"
end
local net = lain.widget.net({
    iface    = { localnet },
    timeout  = 0.5,
    settings = function()
        widget:set_markup(markup.font(theme.font,
                          markup("#457DC3", " " .. net_now.received)
                          .. " " ..
                          markup("#FFCC00", " " .. net_now.sent .. " ")))
    end
})
```

**Comment by johannesmenzel** [comment]
I think that worked, at least on the first computer, have to check the other later.

Thinking about the local folder anyway, which should make the configuration more portable.

Thanks a lot!

**Comment by johannesmenzel** [comment]
Ok, one last question:

As you may agree, defining the local net interface should actually be in rc.lua, which doesn't matter for me (only having one theme) but is not that elegant.

The reason why I do that is that I am such a newbee, that I do not know, how to include local variables from rc.lua to theme.lua, so that widgets can use them.

So if I'd define the localnet variable in rc.lua, how can the net widget, initialized in theme.lua get it?

**Comment by psychon** [comment]
Hm... just do the hostname check in the theme and export variables from there so that `rc.lua` can use them from there?

**Comment by johannesmenzel** [comment]
Yeah, although I wanted that the other way round, thats what I was looking for, but I dont know how to export variables in lua. Actually, the state I really want to have is that the theme script includes the complete environment initialized in rc.lua. For example, in my whole newbeeness, I wondered why the calender widget didn't show until I realized, that beautiful isn't included in the default theme.lua. So I wonder if theres a command for my theme.lua, which says: "include all environment (variables, functions) initialized by rc.lua".

Anyway, thanks for all the help, the initial problem is solved, so that we can close that topic.

**Comment by psychon** [comment]
Just remove the `local` in front of the variable name in `rc.lua` and it will also be available in your theme (but of course you have to set things up before doing `beautiful.init`, because that's when the theme is loaded).
