### ISSUE TITLE
Gaps when fair layout is active

### ISSUE THREAD

**Issue by chrissound** [awesomeWM/awesome#197]
Using v3.5.6

![2015-04-05-132700_3046x1050_scrot](https://cloud.githubusercontent.com/assets/1499652/6996715/c892bd2c-db8f-11e4-9b7e-09edbe906d6b.png)

**Comment by actionless** [comment]
what is the value of size_hints_honor in your default rule?

**Comment by chrissound** [comment]
Where is that located?

**Comment by psychon** [comment]
http://awesome.naquadah.org/wiki/FAQ#How_to_remove_gaps_between_windows.3F

**Comment by actionless** [comment]
in your `rc.lua`

**Comment by chrissound** [comment]
Thank you!
