### ISSUE TITLE
Words selection broken in 4.2 with ubuntu 16.04

### ISSUE THREAD

**Issue by elw00d** [awesomeWM/awesome#1972]
Output of `awesome --version`:

```
awesome v4.2 (Human after all)
 • Compiled against Lua 5.2.4 (running with Lua 5.2)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.4
 • LGI version: 0.9.0
```

**How to reproduce the issue:**

Install clean awesome v4.2 on clean Ubuntu 16.04.03

**Actual result:**

Word selection with `Ctrl+Shift+→` / `Ctrl+Shift+←` is broken
`Ctrl+Shift+Tab` in browser works identically as `Ctrl+Tab` (`Shift` doesn't work)

**Expected result:**

Word selection with `Ctrl+Shift+→` / `Ctrl+Shift+←` works like swiss clocks !

**Comment by elw00d** [comment]
Sorry. It was not 100% clean installation. I used in my `.profile`:

```
setxkbmap -layout '' -option 
setxkbmap -layout 'us,ru' -option 'grp:ctrl_shift_toggle'
```

and possibly this caused bug https://bugs.launchpad.net/ubuntu/+source/xorg-server/+bug/1683383

Strange that in 14.04 it worked fine..

**Comment by elw00d** [comment]
Reported this bug to ubuntu community…

https://bugs.launchpad.net/ubuntu/+source/xorg/+bug/1710132

**Comment by psychon** [comment]
I'd say that awesome is not involved with keyboard layout things. Does the same happen e.g. in dwm, fluxbox or something else besides awesome?

**Comment by elw00d** [comment]
Yes, it's not awesomewm bug. Actual ticket in launchpad https://bugs.launchpad.net/ubuntu/+source/xorg-server/+bug/1683383
