### ISSUE TITLE
Broken systray icons with Monaco font set to wibar 

### ISSUE THREAD

**Issue by nickdiego** [awesomeWM/awesome#1976]
Output of `awesome --version`:

awesome v4.2 (Human after all)
 • Compiled against Lua 5.3.4 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.5
 • LGI version: 0.9.1

**How to reproduce the issue:**

- Install and set "Monaco" font as theme font with size of 8 or 9 (probably happens with other fonts but I got it trying to use Monaco as theme font with size 8)
- Have systray widget added to wibar

**Actual result:**

- Systray icons appear broken (with wrong size / wrongly rendered), as you can see in the screenshot below:
![awesome-systray-bug-monaco-font](https://user-images.githubusercontent.com/1189757/29237574-2f788d0a-7eef-11e7-8dcb-b4c334fe0ee1.jpg)

**Expected result:**

- It should render the systray icons with correct size.

**Outuput of 'xwininfo' for wibar**
```
xwininfo: Window id: 0x200015 "Awesome drawin"

  Absolute upper-left X:  0
  Absolute upper-left Y:  0
  Relative upper-left X:  0
  Relative upper-left Y:  0
  Width: 1366
  Height: 21
  Depth: 32
  Visual: 0xd2
  Visual Class: TrueColor
  Border width: 0
  Class: InputOutput
  Colormap: 0x200000 (not installed)
  Bit Gravity State: NorthWestGravity
  Window Gravity State: NorthWestGravity
  Backing Store State: NotUseful
  Save Under State: no
  Map State: IsViewable
  Override Redirect State: yes
  Corners:  +0+0  -0+0  -0-747  +0-747
  -geometry 1366x21+0+0
```

**Comment by nickdiego** [comment]
Hi all, actually I'm not sure this an awesome specific issue, since AFAIK awesome is not responsible for "drawing" the icons itself, it just asks Xorg to do that (??). But I'd appreciate if you could help me on this.
thanks

**Comment by psychon** [comment]
Could you do what you already did with `xwininfo`, but this time with `xwininfo -tree -frame`? That provides the size of the actual tray icons (but I guess they have the right size since else they wouldn't be cut off).
How likely is that networkmanager and Chrome (???) just expect a minimum try icon size?

Could you get `xprop` output for the tray icons?
In case `xprop` refuses to work on the tray icon (it does so right now here), look at the `xwininfo` output. For example here I have right now:
```
  Root window id: 0xe9 (the root window) (has no name)
  Parent window id: 0xe9 (the root window) (has no name)
     1 child:
     0xa00006 "Awesome systray window": ("awesome" "awesome")  20x20+1777+0  +1777+0
        1 child:
        0x60001e "Updates Available": ("update-notifier.py" "Update-notifier.py")  20x20+0+0  +1777+0
           1 child:
           0x60001f (has no name): ()  1x1+-1+-1  +1776+-1
```
I see that the window idea of the child of the "Awesome systray window" is `0x60001e`, so I can use `xprop -id 0x60001e` to get `xprop` output for it.
What I am looking for is something like this:
```
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified minimum size: 20 by 20
		window gravity: NorthWest
```
In my example, the tray icon has size 20x20 (can be seen in `xwininfo` output) and this just happens to be the minimal size that it wants. No idea what it does for smaller sizes.

**Comment by nickdiego** [comment]
Hi @psychon , thanks for your response.
Currently I'm using 'terminus 9' as font and it works as expected (as shown in the pic below),
at least regarding the icons size (telegram and dropbox seems to be 'dirty', not sure if it's
coincidence, but both are Qt-based apps):

![awesome-systray-bug-monaco-font-2](https://user-images.githubusercontent.com/1189757/29242381-6ede3dc6-7f5a-11e7-9ab4-a021e7a0d999.jpg)

So first, I'm send the info you asked for this config, to serve as kinda baseline _(and in the next comment I'll send info for the config is not working as expected)_

**'xwininfo -tree -frame' output:**
```
xwininfo: Window id: 0x200015 "Awesome drawin"

  Root window id: 0x139 (the root window) (has no name)
  Parent window id: 0x139 (the root window) (has no name)
     1 child:
     0x200006 "Awesome systray window": ("awesome" "awesome")  72x18+1003+0  +1003+0
        4 children:
        0x1c0003d "TelegramDesktop": ("telegram-desktop" "TelegramDesktop")  18x18+54+0  +1057+0
        0x6009dc "NetworkManager Applet": ("nm-applet" "Nm-applet")  18x18+36+0  +1039+0
           1 child:
           0x6009dd (has no name): ()  1x1+-1+-1  +1038+-1
        0x120004a "chromium": ("chromium" "Chromium")  18x18+18+0  +1021+0
           1 child:
           0x120004b (has no name): ()  1x1+-1+-1  +1020+-1
        0x400015 (has no name): ()  18x18+0+0  +1003+0
```

**chromium xprop output:**
```
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified minimum size: 16 by 16
		program specified base size: 0 by 0
		window gravity: NorthWest
```

**NetworkManager xprop output:**
```
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified minimum size: 16 by 16
		program specified base size: 0 by 0
		window gravity: NorthWest
```

**TelegramDesktop xprop output:**
```
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		user specified location: 1099, 0
		user specified size: 18 by 18
		program specified minimum size: 22 by 22
		window gravity: Static
```

**Comment by nickdiego** [comment]
@pyschon, here are `xwininfo` and `xprop` outputs for "Monaco 8" font: 
![awesome-systray-bug-monaco-font-3](https://user-images.githubusercontent.com/1189757/29242699-767d38e8-7f5f-11e7-9419-892bdcd977e5.jpg)

**'xwininfo -tree -frame' output:**
```
xwininfo: Window id: 0x200015 "Awesome drawin"

  Root window id: 0x139 (the root window) (has no name)
  Parent window id: 0x139 (the root window) (has no name)
     1 child:
     0x200006 "Awesome systray window": ("awesome" "awesome")  84x21+976+0  +976+0
        4 children:
        0x600b58 "NetworkManager Applet": ("nm-applet" "Nm-applet")  21x21+63+0  +1039+0
           1 child:
           0x600b59 (has no name): ()  1x1+-1+-1  +1038+-1
        0x1c00087 "TelegramDesktop": ("telegram-desktop" "TelegramDesktop")  21x21+42+0  +1018+0
        0x1200e2c "chromium": ("chromium" "Chromium")  21x21+21+0  +997+0
           1 child:
           0x1200e2d (has no name): ()  1x1+-1+-1  +996+-1
        0x400051 (has no name): ()  21x21+0+0  +976+0
```

**chromium xprop output:**
```
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified minimum size: 24 by 24
		program specified base size: 0 by 0
		window gravity: NorthWest
```

**NetworkManager xprop output:**
```
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified minimum size: 24 by 24
		program specified base size: 0 by 0
		window gravity: NorthWest
```

**TelegramDesktop xprop output:**
```
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		user specified location: 1060, 0
		user specified size: 21 by 21
		program specified minimum size: 22 by 22
		window gravity: Static
```

**Comment by nickdiego** [comment]
Analyzing the outputs from xwininfo and xprop it looks like for chromium and networkmanager the `program specified minimum size` are 24x24, while the size expected/set by X is `21x21`. Any insight why it could happen?
_considering that doesn't happen when I use `Terminus 9` as font, where xwininfo gives `18x18` and chromium/nm minimum size is 16x16._

**Comment by nickdiego** [comment]
Just tested forcing the wibar's `height` to 20, for example, and the bug doesn't happen anymore.

**Comment by nickdiego** [comment]
I'll close this since I could work around it.
