### ISSUE TITLE
modkey doesn't allow multiple keys

### ISSUE THREAD

**Issue by iamsrp** [awesomeWM/awesome#1988]
**Versions:**

awesome v4.0 (Harder, Better, Faster, Stronger)
 • Compiled against Lua 5.1.5 (running with Lua 5.1)
 • D-Bus support: ✔
 • execinfo support: ✔
 • RandR 1.5 support: ✘
 • LGI version: 0.9.1

Linux <host> 4.10.0-30-generic #34-Ubuntu SMP Mon Jul 31 19:38:17 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

_Running under VNC:_

Xvnc Free Edition 4.1.1 - built Feb 25 2015 23:02:21

**How to reproduce the issue:**

Change the rc.lui file so that it has this in it:

modkey = "Ctrl+Mod1"

**Actual result:**

Well, it kinda goes bonkers. This really confuses keyboard input to various things.

**Expected result:**

I was hoping that this would mean that I do things like window resizing by holding down Ctrl-Alt and using the right mouse button, etc.

**Comments:**

Having multiple modkeys works for things like FVWM and Gnome, so I was hoping that it might work here too. If this is a "WONTFIX" then that's okay, but it's a show-stopper for me. (I'm old and set in my ways it seems.)

**Comment by psychon** [comment]
Open your `rc.lua` and replace each case of `{ modkey }` with `{ "Ctrl", "Mod1" }`. You cannot do this by just assigning something to `modkey`, sorry, it needs to be two different strings.

**Comment by iamsrp** [comment]
That's a perfectly fine work-around. I'll give it a try. 

Thanks for the quick response!
