### ISSUE TITLE
Sometimes font color dialog doesn't show in LibreOffice

### ISSUE THREAD

**Issue by ryankojima** [awesomeWM/awesome#199]
Hi,
I'm using Awesome with ArchLinux.
When I'm using Libreoffice-Fresh version, I often can't open font color selection popup. Sometimes the popup is shown but most of case doesn't appear. If I switch back to Libreoffice-still package, it works. I tried floating rule setting, but it doesn't help.
If I switch WM to gnome, then it works.

**Comment by Elv13** [comment]
While we should probably find a hack to fix it, it is an upstream bug, it also happen on Mac OS X

xprop from LO 4.3
```
_NET_WM_DESKTOP(CARDINAL) = 15
WM_STATE(WM_STATE):
		window state: Normal
		icon window: 0x0
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_TOOLBAR
WM_TRANSIENT_FOR(WINDOW): window id # 0x440001f
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0xf, 0x4, 0x0, 0x0, 0x0
WM_CLIENT_LEADER(WINDOW): window id # 0x4400001
_NET_WM_PID(CARDINAL) = 13273
WM_CLIENT_MACHINE(STRING) = "elepage-laptop"
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified location: 1321, 72
		program specified minimum size: 178 by 260
		program specified maximum size: 178 by 260
		window gravity: Static
WM_CLASS(STRING) = "libreoffice", "libreoffice-writer"
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, WM_TAKE_FOCUS
WM_HINTS(WM_HINTS):
		Client accepts input or input focus: False
		bitmap id # to use for icon: 0x440039b
		bitmap id # of mask for icon: 0x440039c
		window id # of group leader: 0x440001f
_NET_WM_USER_TIME(CARDINAL) = 0
```

**Comment by aelspire** [comment]
workaround: https://bugs.documentfoundation.org/show_bug.cgi?id=86198#c3

It works for me, but setting the "Visible" flag of the GtkWindow to "False" can mess something if you use gnome

**Comment by ryankojima** [comment]
The solution worked for me too. So we assume it's LibreOffice's bug, not Awesome's?

**Comment by aelspire** [comment]
I had the same problem on KDE so it look like it's LibreOffice's bug

**Comment by psychon** [comment]
The above bug report says that LibreOffice fixed their stuff. Closing under this assumption.
