### ISSUE TITLE
tests/run.sh always has its verbose mode enabled

### ISSUE THREAD

**Issue by psychon** [awesomeWM/awesome#1996]
From `tests/run.sh`:
```sh
verbose=${VERBOSE:-0}
while getopts vWh opt; do
    case $opt in
        v) verbose=1 ;;
        W) fail_on_warning=1 ;;
        h) usage 0 ;;
        *) usage 64 ;;
    esac
done
shift $((OPTIND-1))

if [[ $verbose ]]; then
    set -x
fi
```
So this looks up `$VERBOSE` in the env and uses value 0 if not found. If `-v` is specified, this is set to 1.
However, this does not seem to work:
```
$ bash -c 'if [[ 0 ]] ; then echo a ; fi ; if [[ 1 ]] ; then echo b ; fi'
a                                                                                         
b
```
To quote the relevant part of `man bash` (under "CONDITIONAL EXPRESSIONS"):
```
       string
       -n string
              True if the length of string is non-zero.
```
I'm not really sure what to do about this. Perhaps `[[ $verbose -ne 0 ]]`?

**Comment by blueyed** [comment]
Fixed in https://github.com/awesomeWM/awesome/pull/1997.

Using `(( verbose ))` works.
