### ISSUE TITLE
awesome wm with unclutter

### ISSUE THREAD

**Issue by r8b7xy** [awesomeWM/awesome#202]
I use unclutter to hide the cursor and I've spotted one error so far - when cursor is visible everything works as expected but when unclutter hides my mouse pointer while mouse is over the border of the one client, awesome automatically switches into it. I can't change focus to another client - awesome rapidly switches back.
[check out this  video](https://youtu.be/FkydqP_yLIM)
[my rc.lua](https://github.com/r8b7xy/dotfiles/blob/master/awesome/rc.lua)

**Comment by Elv13** [comment]
Sound like https://github.com/DaveDavenport/rofi/issues/138

**Comment by r8b7xy** [comment]
I've found sloppy config from [blueyed rc](https://github.com/blueyed/awesome/blob/sloppy-focus-skip-not-moved/awesomerc.lua.in) very helpful.
