### ISSUE TITLE
Keyboard layout weirdness with xmodmap in 4.2

### ISSUE THREAD

**Issue by sriedel** [awesomeWM/awesome#2022]
Output of `awesome --version`:
awesome v4.2 (Human after all)
 • Compiled against Lua 5.3.4 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.5
 • LGI version: 0.9.1

**How to reproduce the issue:**
I got updated by my distribution to 4.2, and first encountered the bug described in #1933. After applying the patch by hand and restarting awesome i saw the 'us' layout appear in the widget bar.
After clicking on the 'us' string, the 'us' string disappeared, and now the modifier for my xmodmap mappings is continuously applied, unless I press the modifier key. With the modifier key pressed, I get the unmodified keys. No error notification popped up. I tried adding the gears.debug statement as mentioned in #1933, however I don't know where I should be looking for the log message.

Restarting awesome does not fix this issue, looks like i need to restart X.

I'm using the us-with-euro keyboard layout in X, and my xmodmap rules are:
    
    clear Lock
    keycode 66 = Mode_switch 
    keycode 32 = o O Odiaeresis
    keycode 30 = u U Udiaeresis
    keycode 38 = a A Adiaeresis
    keycode 39 = s S ssharp

ßö tö be explicit, withöüt preßßing the xmödmäp mödifier key (mäpped tö cäpßlöck in the rüleß), my regülär typing nöw löökß like thiß. pressing capslock while typing results in normal output.

I should note that I haven't changed my awesome rc file since updating to 4.0.

**Comment by psychon** [comment]
> I'm using the us-with-euro keyboard layout in X,

What exactly does this mean? E.g. can you give a specific call to `setxkbmap` that sets this keyboard layout? Or do you configure this via the Xorg config?
Does "don't use the keyboard layout widget" count as an answer to this report? ;-)

**Comment by Elv13** [comment]
@sriedel Please provide answers to @psychon or this will be closed soon.
