### ISSUE TITLE
Mod4 hurts my  (and your?) thumb

### ISSUE THREAD

**Issue by nihiluis** [awesomeWM/awesome#2024]
It seems that pressing Mod4 often is bad for your thumb. At least mine hurts sometimes. Don't think it's good to grow old like that.

Has anyone had the same? Did you switch keys, did something else? Not sure what to do about this.

**Comment by blueyed** [comment]
Depends on your keyboard probably a lot.
I have not problems with it (on a Lenovo X250), but do not use the thumb for it (only).

**Comment by nenadalm** [comment]
I was using win key until it broke without issues, now I am using menu key :)

**Comment by actionless** [comment]
living in general slowly hurts you..

but from the bright part — `modkey` in default `rc.lua` is defined as variable in one place, so it can be extremely easily switched from `mod4` to an other key (or you could remap your mod4 to another place of your keyboard layout)

**Comment by psychon** [comment]
Depending on the key combination, I use my little finger for reaching the windows key.
(Closing since this is just a discussion and not an "actual" issue in awesome. This does not mean that I want to kill the discussion, but I do try to trim the list of open issues.)
