### ISSUE TITLE
In dual monitor configuration, maximization of a window in screen2 moves window to screen1 

### ISSUE THREAD

**Issue by liar666** [awesomeWM/awesome#203]
Hi,

I have a dual monitor configuration (laptop LVDS1 in 1366x768 + external VGA1 in 1600x900).

In my  .config/awesome/rc.lua , I've added two entries:
    { rule = { class = "Firefox" },
      properties = { maximized_horizontal = true, maximized_vertical = true } },
    { rule = { class = "Firefox" },
      properties = { tag = tags[screen.count()][6] } },

So Firefox is supposed to run maximized on screen 2 (VGA1). It opens on screen2, but it is not maximized, so I try to maximize its window using my combo "Ctl-Alt-a", which is defined as: 
    awful.key({ modkey, "Control" }, "a",
        function (c)
            c.maximized_horizontal = not c.maximized_horizontal
            c.maximized_vertical   = not c.maximized_vertical
        end)
But this moves the Firefox window to the other screen (laptop LVDS1).

I'm wrong (*) or is it actually a bug?

PS: awesome v3.4.15 (Never Gonna Give You Up)
 • Build: Jan 23 2014 14:28:37 for x86_64 by gcc version 4.8.2 (buildd@komainu)
 • D-Bus support: ✔

(*) writing this text I'm realizing that having 2 separated rules for class "Firefox" might be wrong and might explain the first problem I encounter

**Comment by blueyed** [comment]
Having two rules should be no problem.

Can you try this with the current release and/or Git master, please?
3.4.x is rather old and not supported anymore.

**Comment by liar666** [comment]
Huh... Sorry, I'll try with a more recent version. Unfortunately, the one I have is the version that comes along with Ubuntu, as it is shown here :[
http://awesome.naquadah.org/download/
http://packages.ubuntu.com/search?keywords=awesome

**Comment by Elv13** [comment]
https://packages.debian.org/experimental/x11/awesome

**Comment by liar666** [comment]
I've updated the package.

Unfortunately, it's just a pain in ... to convert my config file to the new format, so it might take time before I come back with updated information....

**Comment by psychon** [comment]
I'll assume that this is fixed with the latest version. We had some window gravity oddities that could cause windows to slightly move (and thus end up on the wrong screen). Closing under the assumption that this is fixed. Feel free to reopen if I am wrong.
