### ISSUE TITLE
awful.placement.centered + awful.placement.no_overlap

### ISSUE THREAD

**Issue by actionless** [awesomeWM/awesome#2030]
Output of `awesome --version`:

```
awesome v4.2-173-ga7d24d10-dirty (Human after all)
 • Compiled against Lua 5.1.4 (running with LuaJIT 2.0.5)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.5
 • LGI version: 0.9.1
```

**How to reproduce the issue:**
1)
```lua
  awful.rules.rules = {
      { rule = { },
        properties = {
          focus = awful.client.focus.filter,
          raise = true,
          keys = awesome_context.clientkeys,
          buttons = awesome_context.clientbuttons,
          placement =
            awful.placement.no_offscreen +
            awful.placement.centered +
            awful.placement.no_overlap,
          size_hints_honor = false,
          screen = awful.screen.preferred,
        },
        callback = function(c)
            awful.client.setslave(c)
        end
      },
}
```

2) choose floating layout

3) open few clients

**Actual result:**

``` lua
            awful.placement.centered +
            awful.placement.no_overlap,
```
and
``` lua
            awful.placement.no_overlap +
            awful.placement.centered,

```
are producing different results and only the last of placements got applied correctly, so either clients are centered but overlapping each other , either they not overlapping but starting to open from top left corner of the screen

**Expected result:**

first client opens in the center, each other opens next to it without overlapping previous ones

**Comment by psychon** [comment]
At least the implementation of `no_overlap` tries to handle this:
https://github.com/awesomeWM/awesome/blob/02f894ce0cb14f05b78ee76dacdf1ecab7ecc09a/lib/awful/placement.lua#L889-L897
No idea what is going wrong here and no time to debug.
(`centered` of course ignores the previous position, how could it do anything about it anyway? So `centered + no_overlap` should be the way to go, but why doesn't it work?)

**Comment by actionless** [comment]
i'm trying to debug it, so far i also noticed what this combination

```lua
            awful.placement.right +
            awful.placement.no_overlap,
```

still makes clients to open from top-left corner

**Comment by nickdiego** [comment]
I'm able to reproduce this issue too, running git version on Arch Linux.

**Comment by blueyed** [comment]
Related to https://github.com/awesomeWM/awesome/issues/1092?

**Comment by actionless** [comment]
thanks for suggestion, i'll try to understand what's the difference between those placements and try to fix `no_overlap`
