### ISSUE TITLE
Pointer does not scale properly with DPI

### ISSUE THREAD

**Issue by l0b0** [awesomeWM/awesome#2031]
Output of `awesome --version`:

```
awesome v4.2 (Human after all)
 • Compiled against Lua 5.3.4 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.5
 • LGI version: 0.9.1
```

**How to reproduce the issue:**

1. Set up a high resolution (4k or more) monitor with a high DPI, for example:

    ```
    $ cat /etc/X11/Xresources 
    Xft.dpi:        276
    ```

**Actual result:**

The mouse pointer is much smaller than expected, often making it hard to locate on a high DPI display. See for example this screenshot of this GitHub form scaled at 100% in current Firefox:

![screenshot from 2017-09-05 10-17-07](https://user-images.githubusercontent.com/168301/30054353-bd756b90-9223-11e7-87f7-4e7cc31c763c.png)

**Expected result:**

I'd expect the pointer dimensions to be about the same as an "M" character. The "properly" in the title reflects this, since it's possible that it does scale, but not as expected.

**Comment by psychon** [comment]
Hm, this just works for me. When I run `tests/run.sh /dev/null` in awesome's source dir, Xephyr starts with a "normal" awesome. With the following patch, everything including the cursor are scaled up.
```diff
diff --git a/tests/run.sh b/tests/run.sh
index e4700ac9d..64806d6f4 100755
--- a/tests/run.sh
+++ b/tests/run.sh
@@ -152,7 +152,7 @@ wait_until_success() {
 
 # Wait for DISPLAY to be available, and setup xrdb,
 # for awesome's xresources backend / queries.
-wait_until_success "setup xrdb" "printf 'Xft.dpi: 96
+wait_until_success "setup xrdb" "printf 'Xft.dpi: 200
     *.background: #002b36
     *.foreground: #93a1a1
     *.color0:     #002b36
```
What output do you get when you run `awesome-client 'return awesome.xrdb_get_value("", "Xft.dpi") or "nil", 42'` in a terminal running inside of awesome?

**Comment by psychon** [comment]
Closing since reporter vanished

**Comment by wimstefan** [comment]
Same happens to me as well ... am I allowed to reopen the issue or do you want me to create a new one?

The output of the above command is 
````
   string "180"
   double 42
````
And if the mouse hovers over an app supporting GTK3 the cursor changes to normal size and also recognizes the cursor-theme configured.

`awesome version`
```
awesome v4.2-320-g7e529eea-dirty (Human after all)
 • Compiled against Lua 5.1.5 (running with Lua 5.1)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
```

**Comment by wimstefan** [comment]
Will do so but not now. I'm leaving on Wednesday and will be more or less offline for 2 weeks. Afterwards I'll create a new issue.
To answer your question: I was just editing ~/.gtkrc-2.0, ~/.config/gtk-3.0/settings.ini and ~/.Xresources manually to configure the `gtk-cursor-theme-{name,size}` settings but they where not recognized at all (even the theme was not recognized). After installing and using lxappearance for that it started to work though.
