### ISSUE TITLE
Incomplete documentation for aweful.key

### ISSUE THREAD

**Issue by lucc** [awesomeWM/awesome#204]
The documentation for `aweful.key.new` is missing a description of the parameters: http://awesome.naquadah.org/doc/api/modules/awful.key.html

I found this problem while trying to bind modkey-v to paste text and was wondering if I can put something other than a function for the `press` parameter.

**Comment by psychon** [comment]
This was fixed in June with commit c2ee98b69c09a6123bc5a6009e08cca9095d078e.
