### ISSUE TITLE
Cannot close window with mod+shift+c with default config

### ISSUE THREAD

**Issue by njdart** [awesomeWM/awesome#205]
I've just done a fresh install, and I cant close windows with `modkey+Shift+c` with a fresh install of awesome and I get no errors appearing. I initially installed vicious and lain (lain-git in arch from the AUR) as I have done before along with my rc.lua.

After notching this I've also installed awesome along with vicious and lain onto a laptop and it works fine with the default config and my rc.lua. So I suspect it's an issue with a package or driver I have, although it was working fine before the reinstall. 

I'm running on a nvidia GTX970 with triple monitors, configured by nvidia-settings. All other key bindings work fine in awesome as far as i can tell

uname and list of packages are here:
http://sprunge.us/ELKj
as well as my xorg.conf generated by nvidia-settings and 10-keyboard.conf just in case that's relevant?

my rc.lua is here
https://github.com/njdart/dot-files/blob/master/rc.lua

Thanks

**Comment by blueyed** [comment]
Try looking at and comparing what `xev` gives you for `modkey-Shift-c` on the two systems.

**Comment by njdart** [comment]
the c key isnt being captured on the non-working system, but is on the working one, when in combination with super+shift

Super+c on it's own (without shift) isnt being captured properly (no c key) but shift+c is

http://sprunge.us/TSNT  - Working
http://sprunge.us/RMRH - Not working

**Comment by njdart** [comment]
Rebooted last night and nothing changed, turned it on today and all works as expected. Odd... no idea what was causing it, but if it happens again I'll try find out more about it

Thanks for the help though
