### ISSUE TITLE
Question: how to detect CapsLock pressure

### ISSUE THREAD

**Issue by empijei** [awesomeWM/awesome#2059]
Hello, after spending some time reading the docs I found nothing to help me with this: I would like to detect CapsLock pressure (Just that, the toggling of the CapsLock status)

I have found [here](https://awesomewm.org/doc/api/libraries/awful.key.html) that caps can be used as a modifier, but I would like to have it as a key, and I also found [here](https://awesomewm.org/doc/api/libraries/awful.keygrabber.html) that I could grab all keys, but the doc didn't list a set of keys the "key" parameter will be filled with so I don't know how to compare a "Lock" pressure ("Lock" does not work).

I tried setting up a key with "Lock" as a modifier and an empty string as a key, but it does not work.

I have already removed "Lock" from the ignored keys.

Awesome version:
```
awesome v4.2 (Human after all)
 • Compiled against Lua 5.3.4 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.5
 • LGI version: 0.9.1
```

Thanks in advance for your help.

**Comment by psychon** [comment]
I think the key is called `Caps_Lock`. At least that's what `/usr/bin/xev` tells me it is. Does that work for you?

**Comment by empijei** [comment]
So, I did some digging and found out that remapping Caps_Lock on another key/combination prevents awesome from recognizing it as Caps_Lock. (Note: Escape works and I can intercept it from awesome, and I have bound it to other keys.)

this is weird as this is xev output when I fire a Caps_Lock (currently bound to double shift)
```
KeyPress event, serial 28, synthetic NO, window 0x2400001,
    root 0x146, subw 0x0, time 484275, (99,129), root:(100,156),
    state 0x0, keycode 50 (keysym 0xffe1, Shift_L), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyPress event, serial 28, synthetic NO, window 0x2400001,
    root 0x146, subw 0x0, time 484538, (99,129), root:(100,156),
    state 0x1, keycode 62 (keysym 0xffe5, Caps_Lock), same_screen YES,
    XKeysymToKeycode returns keycode: 50
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyRelease event, serial 28, synthetic NO, window 0x2400001,
    root 0x146, subw 0x0, time 484641, (99,129), root:(100,156),
    state 0x3, keycode 62 (keysym 0xffe5, Caps_Lock), same_screen YES,
    XKeysymToKeycode returns keycode: 50
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyRelease event, serial 28, synthetic NO, window 0x2400001,
    root 0x146, subw 0x0, time 484759, (99,129), root:(100,156),
    state 0x3, keycode 50 (keysym 0xffe5, Caps_Lock), same_screen YES,
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False
```

If I bind something in awesome with the following key (Please ignore I'm spawning chromium, it is just as a placeholder):
```lua
awful.key({           }, "Caps_Lock",    
function () awful.spawn("chromium ") end,{description = "Chromium", group = "system"}),
```
or this key:
```lua
awful.key({ "Shift"          }, "Caps_Lock",    
function () awful.spawn("chromium ") end,{description = "Chromium", group = "system"}),
```

neither work but I noticed that xev does not pickup the Caps_Lock key anymore as if awesome was soaking it.

PS: I know this probably looks like total B.S. and sounds like  an extremely weird request, but I am out of ideas here and would really like to know where I am getting this wrong. :sos:

**Comment by psychon** [comment]
I tried the following and it definitely works here:
```lua
awful.key({}, "Caps_Lock", function() naughty.notify{ text = "Caps!" } end),
```
>  Caps_Lock (currently bound to double shift)

Uhm, does awesome recognize this? For example, when you (with the default config) press mod+r to open the run prompt, does double shift act as a caps lock for you?

**Comment by empijei** [comment]
If I use the `us` layout and press Caps_Lock awesome picks it up, the problem arises when I try to use a layout with the Caps_Lock on the second level of the keyboard.

* In the promptboxes awesome correctly picks it up, so if I start typing a command in the menu and then I press double shift the rest of my typing will be uppercase.
* Also, xev picks Caps_Lock up if I use the double shift.
* Awesome collects the event (as if I bind it, it will not be forwarded to xev) but does not trigger anything :sob:  .

[here](https://github.com/empijei/dotfiles/blob/master/keyboard_layout_empijei#L65) you can find how I bound Caps_Lock, just in case you are curious.

**Comment by empijei** [comment]
You know what? I really don't want to waste any more of your time, sorry to have bothered, thanks for the hint. You correctly gave me the name of the key "Caps_Lock" from here onward I'll bash my head against my will to have a custom kb layout.
Thanks for your help.

**Comment by psychon** [comment]
Feel free to ask, no problem. :-)

If you want, I can give you a technical reason that ends with "sorry, won't work". I'm not entirely sure if this is actually the issue, but the short version is: There is an old and a new way to get keyboard input in X11 (core protocol vs XKEYBOARD extension, aka xkb). I think in the promptboxes we use the new way, but for grabing keys we use the old way (more or less). This might be one of the symptoms of that.

(Also, I doubt that X11 actually allows to grab "double presses" of a key. The protocol here pretty much only allows to grab the pressing of some "physically present" key.)

Again, sorry.

**Comment by empijei** [comment]
Thank you very much for the answer, at least now I know what I was getting wrong :smile: .
I ended up remapping Caps on Escape :man_shrugging:
