### ISSUE TITLE
build: use a fixed date for calendar examples

### ISSUE THREAD

**Issue by blueyed** [awesomeWM/awesome#2070]
There are differences in the generated calendar images, apparently because they are using the current date:

https://github.com/awesomeWM/apidoc/blob/d932f153bfbc1d3ae79b65c399dd02b369ef4e13/images/AUTOGEN_wibox_widget_calendar_font.svg
https://github.com/awesomeWM/apidoc/blob/762037462d89763934a4448826d1f6114b28b08b/images/AUTOGEN_wibox_widget_calendar_font.svg

They should use a fixed date instead.

@Elv13 said this should have been fixed, but apparently it is not.

Via https://github.com/awesomeWM/apidoc/commit/d932f153bfbc1d3ae79b65c399dd02b369ef4e13#diff-c82e6b5d90c6a03924f68894e30f21ee

**Comment by psychon** [comment]
The difficult part of this would be: What date should be picked? Something far in the past? Something far in the future? Anything that is not obviously fake would "feel" bad to readers, I think.

For the actual patch, I would suggest:
```diff
diff --git a/.travis.yml b/.travis.yml
index 47edc3c1f..d69270e04 100644
--- a/.travis.yml
+++ b/.travis.yml
@@ -12,13 +12,13 @@ env:
   matrix:
     - LUA=5.2 LUANAME=lua5.2 DO_COVERAGE=coveralls
     # Lua 5.3 isn't available in Ubuntu Trusty, so some magic below installs it.
-    - LUA=5.3 LUANAME=lua5.3 LUALIBRARY=/usr/lib/liblua.so DO_COVERAGE=codecov EXPORT_SDE=true
+    - LUA=5.3 LUANAME=lua5.3 LUALIBRARY=/usr/lib/liblua.so DO_COVERAGE=codecov
     # luajit: installed from source.
     - LUA=5.1 LUANAME=luajit-2.0 LUALIBRARY=/usr/lib/libluajit-5.1.so LUAROCKS_ARGS=--lua-suffix=jit-2.0.5 TEST_PREV_COMMITS=1
     # Note: luarocks does not work with Lua 5.0.
     - LUA=5.1 LUANAME=lua5.1 BUILD_IN_DIR=/tmp/awesome-build
     # Lua 5.2 with older lgi and screen size not divisible by 2.
-    - LUA=5.2 LUANAME=lua5.2 LGIVER=0.8.0 TESTS_SCREEN_SIZE=1921x1079 BUILD_APIDOC=true DO_CHECKQA=1 EMPTY_THEME_WHILE_LOADING=1
+    - LUA=5.2 LUANAME=lua5.2 LGIVER=0.8.0 TESTS_SCREEN_SIZE=1921x1079 EXPORT_SDE=true BUILD_APIDOC=true DO_CHECKQA=1 EMPTY_THEME_WHILE_LOADING=1
   global:
     # Secure GH_APIDOC_TOKEN to push to awesomeWM/apidoc.
     - secure: "R/HYDclnws1I1+v9Yjt+RKa4CsFhbBT9tiwE3EfPhEj2KCYX4sFRMxuZvLf5sq0XWdrQaPhQ54fgAZGr3f054JKRXcTB0g9J6nhSHz9kIjPh446gafUhEeDQcZRwM/MeCWiwFIkiZm6smYoDFE9JTWu6quNV+lQ4kcVDOp2ibEc="
```
and then hardcode the chosen date in the logic for `$EXPORT_SDE`.

**Comment by blueyed** [comment]
Use the commit timestamp of the NEWS file?
`git log --pretty=format:%cd -n 1 --date=unix -- docs/89-NEWS.md`

It is used already, and was likely meant to be stable through that, but it is the checkout timestamp currently, which is not stable on Travis.

Will create a PR with that.

**Comment by psychon** [comment]
:+1:
