### ISSUE TITLE
awesome-client: should have a --help/-h option

### ISSUE THREAD

**Issue by blueyed** [awesomeWM/awesome#2080]

**Comment by Veratil** [comment]
Is there any specific description of usage we would like to include? I've added the `-h` and `--help` to the script and added a `print_help` function to echo the usage and description and whatnot. I'm just not sure exactly how to describe it.

So far I just have:
```
$ ./awesome-client -h
Usage: awesome-client [-h|--help] [command [command...]]
Interface with awesome through DBUS.

Use awesome-client to run Lua code through the command-line. Every command will
be run and evaluated separately. Examples of things you can do:

$ awesome-client 'return awesome.version'
   string "v4.2"

## This does not return any output, but displays a notification.
$ awesome-client '
> naughty = require("naughty")
> naughty.notify({
> title="CLI Notification",
> text="This is a notification from the command line!"})
> '

Alternatively, you can run awesome-client as a REPL by running awesome-client
with no arguments. Exit with the EOF signal Ctrl-D.
```

**Comment by psychon** [comment]
My only comment is: There already is a manpage for `awesome-client`. I guess we should keep this and `-h` roughly in sync (`manpages/awesome-client.*`).
Also (okay, not "only" comment), I'd like to avoid stuff like `awesome.version` in examples. Having it show `v4.2` only makes it seem old once we reach version "over 9000". ;-)

**Comment by Veratil** [comment]
> Also (okay, not "only" comment), I'd like to avoid stuff like `awesome.version` in examples. Having it show `v4.2` only makes it seem old once we reach version "over 9000". ;-)

Haha, agreed. I was just trying to pad info for the time being until discussed on what small examples we can show. Or we can give examples in the manpage and have `see 'man awesome-client' for examples`?

Honestly, looking at the manpage it's pretty basic, too. It could use some love.

**Comment by psychon** [comment]
Pointing to the man page for further info is always possible, yeah. For examples, something like `return 1+1, "Hello world"` might be good enough.

> Honestly, looking at the manpage it's pretty basic, too. It could use some love.

Yup, that was also my impression.

**Comment by Veratil** [comment]
Alright, I'll work on a simple `--help` message for awesome-client, and update the manpage with examples of usage.
