### ISSUE TITLE
Unit test failures (4.2)

### ISSUE THREAD

**Issue by reinerh** [awesomeWM/awesome#2086]
Hi,

after enabling unit test runs in the Debian build, there was a [failure on s390x](https://buildd.debian.org/status/fetch.php?pkg=awesome&arch=s390x&ver=4.2-2&stamp=1508945611&raw=0):

```
[100%] Running unit tests
cd /<<PKGBUILDDIR>> && /usr/bin/busted --helper=/<<PKGBUILDDIR>>/spec/preload.lua "--lpath=lib/?.lua;lib/?/init.lua;spec/?.lua"
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++****++++***-++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
272 successes / 1 failure / 7 errors / 0 pending : 0.217003 seconds

Failure -> spec/gears/color_spec.lua @ 226
gears.color create_opaque_pattern opaque surface pattern
spec/gears/color_spec.lua:230: Pattern (userdata) 'lgi.rec 0x12239bd40:cairo.SolidPattern' should be opaque, but isn't.

Error -> spec/gears/color_spec.lua @ 121
gears.color linear pattern table description
lib/gears/color.lua:151: cairo.SolidPattern: no `add_color_stop_rgba'

Error -> spec/gears/color_spec.lua @ 138
gears.color linear pattern string description
lib/gears/color.lua:144: cairo.SolidPattern: no `add_color_stop_rgba'

Error -> spec/gears/color_spec.lua @ 156
gears.color radial pattern table description
lib/gears/color.lua:151: cairo.SolidPattern: no `add_color_stop_rgba'

Error -> spec/gears/color_spec.lua @ 173
gears.color radial pattern string description
lib/gears/color.lua:144: cairo.SolidPattern: no `add_color_stop_rgba'

Error -> spec/gears/color_spec.lua @ 211
gears.color create_opaque_pattern transparent linear pattern with transparent stops
lib/gears/color.lua:144: cairo.SolidPattern: no `add_color_stop_rgba'

Error -> spec/gears/color_spec.lua @ 215
gears.color create_opaque_pattern transparent linear pattern with NONE repeat
lib/gears/color.lua:144: cairo.SolidPattern: no `add_color_stop_rgba'

Error -> spec/gears/color_spec.lua @ 222
gears.color create_opaque_pattern opaque linear pattern
lib/gears/color.lua:144: cairo.SolidPattern: no `add_color_stop_rgba'
CMakeFiles/check-unit.dir/build.make:60: recipe for target 'CMakeFiles/check-unit' failed
```

Is this related to awesome? Or is something deeper (ike lgi or cairo) causing this?

**Comment by psychon** [comment]
Uhm. Does lgi's own test suite pass on s390x?

**Comment by psychon** [comment]
Looks like the debian package for lua-lgi does not run tests.
So, since I am now out of ideas (except for: "I doubt a lot that this is a bug in awesome, but sadly I guess I am responsible for lgi as well): I'll ask for porterbox access so that I can mess with this myself. I know that it is possible since I did that before to debug a linking failure of znc (turned out to be a glibc bug, but I can't find a reference right now)

**Comment by psychon** [comment]
Heh :-)

> if [ `dpkg-architecture -qDEB_BUILD_ARCH` != s390x ]; then \
>   make -C tests all; \
>   GI_TYPELIB_PATH=tests LD_LIBRARY_PATH=tests xvfb-run dh_auto_test; \
> fi

https://buildd.debian.org/status/fetch.php?pkg=lua-lgi&arch=s390x&ver=0.9.1-1.2&stamp=1507912592&raw=0

I'll close this as "it's a bug in lgi and the DD maintaining lua-lgi knows & doesn't care", but I am still interested in debugging this.

**Comment by reinerh** [comment]
I also just found it, unfortunately was this changed without explanation.
https://anonscm.debian.org/cgit/pkg-lua/lua-lgi.git/commit/?id=fd1ecc13352ada14c0fdafd5d6627477d4122036
I'll try to reach the lua-lgi maintainer and ask for more information.

**Comment by psychon** [comment]
@reinerh Could you CC me in mails? I more-or-less became lgi upstream as well (original author doesn't have the time and gave me commit access). Thanks.

**Comment by reinerh** [comment]
Found an old s390x log of the lua-lgi build:
https://buildd.debian.org/status/fetch.php?pkg=lua-lgi&arch=s390x&ver=0.7.1-2&stamp=1370295470&raw=0
There the test was indeed failing, and in the next revision it has been disabled.

**Comment by psychon** [comment]
https://github.com/pavouk/lgi/commit/d695b42c7a4bf225ebe285c0635e21c2f1e6bea3 fixes the build on hurd-i386 (the test case counts to one million and assumes some time has passed; timers on hurd are so low-precision that the test often fails).
https://github.com/pavouk/lgi/commit/a127f82af7b60fd4f76b694317eb77ff4c62bbf7 fixes the build on big endian 64bit architectures where previously the wrong half of a long was read as an int, causing the return value of functions that return an enum to always be 0 (thus `cairo_pattern_get_type` returned the wrong type and lgi made the wrong functions available on the object). This fixes the tests on s390x, ppc64, and likely also on sparc64 (this last one is untested).

I already sent this last patch to https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=879956. Given the recent history of lua-lgi in debian, you might want to prepare an NMU to get this patch into the archive. The other patch is so far unreported in debian. Feel free to handle that.

Given the recent history of lgi upstream, waiting for these patches to appear in an release might take quite some time.

**Comment by reinerh** [comment]
Thanks a lot! I'll prepare an NMU for your two patches.
