### ISSUE TITLE
Rule 'tag' with tag name errors if that tag is not on same screen with client

### ISSUE THREAD

**Issue by necauqua** [awesomeWM/awesome#2087]
Output of `awesome --version`:

awesome v4.2-142-g57b18df5 (Human after all)
 • Compiled against Lua 5.3.4 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.5
 • LGI version: 0.9.2

**How to reproduce the issue:**

On two screens have tags 'a' and 'b' respectively.
Move some client to tag 'b'.
Add rule for client to land on tag 'a' (string rule, so `tag = 'a'`).
Reload awesome.

**Actual result:**

Client will still sit on tag 'b' and this line is notified with `debug::error` signal:
```/usr/share/awesome/lib/awful/rules.lua:299: attempt to index a nil value (local 'value')```

This is because is could not find any tag named 'a' on second screen.

**Expected result:**
Either it should search for 'a' tag on all screens and move the client to it, or if such tag is not found on current screen it should ignore it.
Anyway, it should not produce an error, or that error has to be more specific(like `tag 'a' not found on screen #1`)

**Comment by psychon** [comment]
> Either it should search for 'a' tag on all screens and move the client to it,

This still needs the patch below in case there really is no such tag. Plus, ontop of that:
```diff
diff --git a/lib/awful/rules.lua b/lib/awful/rules.lua
index aefd8fbc..0b0bdfa7 100644
--- a/lib/awful/rules.lua
+++ b/lib/awful/rules.lua
@@ -292,6 +292,7 @@ local force_ignore = {
 function rules.high_priority_properties.tag(c, value, props)
     if value and type(value) == "string" then
         value = atag.find_by_name(c.screen, value)
+             or atag.find_by_name(nil, value)
     end
 
     if value then
```

> or if such tag is not found on current screen it should ignore it.

```diff
diff --git a/lib/awful/rules.lua b/lib/awful/rules.lua
index 10a7bb86..aefd8fbc 100644
--- a/lib/awful/rules.lua
+++ b/lib/awful/rules.lua
@@ -290,11 +290,11 @@ local force_ignore = {
 }
 
 function rules.high_priority_properties.tag(c, value, props)
-    if value then
-        if type(value) == "string" then
-            value = atag.find_by_name(c.screen, value)
-        end
+    if value and type(value) == "string" then
+        value = atag.find_by_name(c.screen, value)
+    end
 
+    if value then
         -- In case the tag has been forced to another screen, move the client
         if c.screen ~= value.screen then
             c.screen = value.screen
```
I'm not sure what's the desirable behaviour here. CC @Elv13 @blueyed

**Comment by blueyed** [comment]
Me neither.
Hoping for @Elv13 to provide some insights.

**Comment by necauqua** [comment]
I just discovered that eg. `awful.spawn(terminal, {tag = 'term'})` does not work at all with two screens.
Somehow the `c.screen` is always set to my second screen(which is not even primary!) and so it can't find the tag.

When i changed the code to `find_by_name(nil, value)` it does move the client to proper tag when my mouse is on screen with that tag and does nothing (not even prining gears debug error!) when it is on second one. It finds the tag, it seems, but does not move the client to it.

**Comment by blueyed** [comment]
@necauqua 
Can you create a new issue, please?
Have you tried https://github.com/awesomeWM/awesome/pull/1487 like suggested to me in #1885?
