### ISSUE TITLE
WM_STATE cannot be set to Iconified on restart

### ISSUE THREAD

**Issue by wakjah** [awesomeWM/awesome#2095]
Output of `awesome --version`:

awesome v4.2 (Human after all)
 • Compiled against Lua 5.2.3 (running with Lua 5.2)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.4
 • LGI version: 0.8.0

**How to reproduce the issue:**

Set a client to minimized in the "manage" callback. 

```
client.connect_signal("manage", function (c, startup)
    c.minimized = true
end)
```

Run a client, e.g., `xclock`

The window should disappear and `xprop -name xclock WM_STATE` should say

> WM_STATE(WM_STATE):
>        window state: Iconic

Now restart awesome. 

**Actual result:**

The window disappears as expected, but  `xprop -name xclock WM_STATE` instead says 

> WM_STATE(WM_STATE):
>        window state: Normal

**Expected result:**

The window disappears and `WM_STATE` is still `Iconic`.

Note that it appears I can work around the issue by changing the callback to 

```
client.connect_signal("manage", function (c, startup)
    c.minimized = false
    c.minimized = true
end)
```

It seems that the first line (in either of the two versions of the callback) results in something like the following being printed

> [  1308.86 ] error 3 (BadWindow) request 2 minor 0 serial 8329 ("BadWindow (invalid window parameter)")

**Comment by psychon** [comment]
I'm curious: *Why* do you check the value of `WM_STATE` of `xeyes`? How did you actually come across this problem?
And follow up question: Why do you use `WM_STATE` instead of `_NET_WM_STATE` for this?

> It seems that the first line (in either of the two versions of the callback) results in something like the following being printed
> 
> [ 1308.86 ] error 3 (BadWindow) request 2 minor 0 serial 8329 ("BadWindow (invalid window parameter)")

That does not happen here / cannot reproduce.

**Comment by wakjah** [comment]
I realise it might seem a little strange :) 

Some background: we have an embedded system that uses awesome as the window manager. Some of the applications are java apps that use the 'iconified' property as an optimization to avoid unnecessary updates. All works pretty well (as long as we set _JAVA_AWT_WM_NONREPARENTING of course). 

It appears that awesome has started crashing for some users (or a secondary issue is causing it to - it is under investigation, reason currently unknown), and the mechanism is breaking due to the above mentioned issue. 

From reading the source, it looks like the JVM is using WM_STATE to determine whether a window is iconified.

The example of `xclock` was just for demonstration / reproduction purposes.

**Comment by psychon** [comment]
>  (as long as we set _JAVA_AWT_WM_NONREPARENTING of course).

Side note: Awesome is a reparenting WM since at least v4.0 (I think since v3.5.0, but I'm not completely sure). And another side note: The above env var makes Java actually behave as required by ICCCM instead of making their own rules (At least partly).

**Comment by psychon** [comment]
@actionless Works for me. What did I do "right"?

I added
```lua
client.connect_signal("manage", function(c)
    print(c, c.minimized)
    if not c.minimized then  c.minimized = true end
end)
```
to the end of the default config, started awesome and started xclock.
Result is a minimised xclock and output:
```
window/client(xclock): 0x55ea64749988	false
```
Then, I restarted awesome via right-click on the root window and then pressing "restart". This resulted in a still-minimised xclock and output:
```
window/client(xclock): 0x55747286ec78	true
```

**Comment by actionless** [comment]
should we fix the default config?

**Comment by actionless** [comment]
also, while awesome is exiting (`exit` signal) client is still minimized:

```
window/client([9] (6) tail  /home/...): 0x413742e0      false
window/client([69] fish  /home/lie): 0x400de218 true
window/client([70] fish  /home/lie): 0x412a9258 true
window/client([71] fish  /home/lie): 0x40d25c90 true
window/client(2018-10-14--15394851...): 0x41399ca0      false
```

but when awesome is starting (client `manage` signal) they not anymore:
```
window/client(rpdrt1): 0x40668160       false
window/client([1] fish  /home/lie): 0x4066d380  false
window/client([2] (4) fish  /home/...): 0x40673db0      false
window/client([5] (4) fish  /home/...): 0x418fa8f8      false
```

**Comment by psychon** [comment]
> should we fix the default config?

Fix in what way? As I said, this works for me with the default config just fine.

**Comment by psychon** [comment]
Uhm... instead of restarting awesome, quit awesome, check xprop output and start a new awesome. That way you'd know if Iconic state / `_NET_WM_STATE_HIDDEN` are set properly. Then, uhm, I guess `client.connect_signal("property::minimized", function(c) print(c, c.minimized, debug.traceback()) end)`.

**Comment by actionless** [comment]
after awesome `exit`s clients still stay minimized

after adding traceback i've got more logging for each client (3 times per each instead of 1 time):

```lua
window/client([70] fish  /home/lie): 0x40c93818 true    stack traceback:
        /home/lie/.config/awesome/config/signals.lua:324: in function </home/lie/.config/awesome/config/signals.lua:323>
window/client([70] fish  /home/lie): 0x40c93818 false   stack traceback:
        /home/lie/.config/awesome/config/signals.lua:324: in function </home/lie/.config/awesome/config/signals.lua:323>
        [C]: in function '__newindex'
        /usr/share/awesome/lib/awful/ewmh.lua:120: in function </usr/share/awesome/lib/awful/ewmh.lua:91>
        [C]: in function 'emit_signal'
        /usr/share/awesome/lib/awful/rules.lua:738: in function 'execute'
        /usr/share/awesome/lib/awful/rules.lua:425: in function </usr/share/awesome/lib/awful/rules.lua:419>
window/client([70] fish  /home/lie): 0x40c93818 false
```

**Comment by actionless** [comment]
in the end of `rules.execute` i see this line:

```lua
    if props.focus and (type(props.focus) ~= "function" or props.focus(c)) then
        c:emit_signal('request::activate', "rules", {raise=true})
    end
```

it looks to me what during applying rule to client now it gets raised explicitly after applying all the rules

**Comment by actionless** [comment]
what function `props.focus()` supposed to do? it seems to return the client with which it was called every time

**Comment by psychon** [comment]
https://github.com/awesomeWM/awesome/blob/45430daf7f22724b89004afa0cd06a5f937ff51d/awesomerc.lua#L483

But, no idea why this then works for me...

**Comment by actionless** [comment]
added some debug print:

```lua
    if props.focus and (type(props.focus) ~= "function" or props.focus(c)) then
        print("::rules", c.name, c == client.focus, c == props.focus(c))
        c:emit_signal('request::activate', "rules", {raise=true})
    end
```

```
::rules [71] fish  /home/lie    false   true
::rules [73] fish  /home/lie    false   true
::rules [74] fish  /home/lie    false   true
```

**Comment by actionless** [comment]
i've just realized what `awful.client.focus.filter` is filtering not "focused" client, but "focusable"
