### ISSUE TITLE
Input menus (e.g. Drop Downs) in QtWebEngine based programs close instantly

### ISSUE THREAD

**Issue by crater2150** [awesomeWM/awesome#2102]
Output of `awesome --version`:

awesome v4.2 (Human after all)                                                                                                                                                             
 • Compiled against Lua 5.2.4 (running with Lua 5.2)                                                                                                                                       
 • D-Bus support: ✔                                                                                                                                                                        
 • execinfo support: ✔                                                                                                                                                                     
 • xcb-randr version: 1.5                                                                                                                                                                  
 • LGI version: 0.9.2

**How to reproduce the issue:**

Open a webpage in a QtWebEngine based browser (e.g. qutebrowser, qupzilla) that contains an HTML `<select>` (drop down menu) and try to open that dropdown.

**Actual result:**

Dropdown list shows very briefly and instantly closes again. Sometimes, the position of the list is outside the window. A similar behaviour is shown with other input elements that open a small window, like calendar inputs.
The dropdown list is registered as a separate client by awesome, with type = "utility".

This behaviour does not appear without a window manager running. It also doesn't happen in i3 or xfwm4 (xfce4 window manager), but the same problem appears in wm2.
[Screen recording of behaviour in qutebrowser with awesome and with no window manager](https://qwertyuiop.de/~crater2150/qute_menus.mp4)

**Comment by psychon** [comment]
> Open a webpage in a QtWebEngine based browser (e.g. qutebrowser, qupzilla)
```
$ apt-cache search qutebrowser
$ apt-cache search qupzilla   
libqupzilla-dev - development files for qupzilla's shared library
libqupzilla1 - shared library and header files for qupzilla
qupzilla - lightweight web browser based on libqtwebkit
```
Okay, so `qupzilla`.

>  that contains an HTML <select> (drop down menu) and try to open that dropdown.

https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_select

Okay, done, works for me just fine, sorry.

> The dropdown list is registered as a separate client by awesome, with type = "utility".

> A similar behaviour is shown with other input elements that open a small window, like calendar inputs.

Uhm, what? Google found http://jsfiddle.net/trixta/cc7Rt/embedded/result,html,js,css/, but that doesn't open any new windows.

Anyway, I cannot reproduce. I am on Debian testing. How different are your versions of things from mine? Any other ideas?

(Also, qupzilla does not open any window when run under xtrace....)

**Comment by crater2150** [comment]
During writing this response and trying to collect more information, I got an idea. The drop downs usually close, when the browser loses focus. But if awesome handles the drop down as a new client, it will get focus instead of the browser, so it is closed instantly. The following rule actually fixes the problem:
```lua
{ rule = {class = "qutebrowser", type = "utility" },
  properties = {
    focus = false,
    placement = function() return false end
  }
},
```
So the problem is probably too specific for a bugfix, unless there are more programs using the "utility" window type in that way? 

---
For reference, my response prior to that fix:

> I am on Debian testing. How different are your versions of things from mine?

I'm using Voidlinux, qupzilla is at version 2.2.1, in Debian it seems to be at 1.8.9. According to Wikipedia, qupzilla migrated to QtWebEngine in 2.0, before that it used QtWebkit.
I don't know any other browsers using Webengine, so I can't say if there are any in Debian testing, sorry :-/ As webengine should be based on Chrome's Blink engine, I will check, 

> Uhm, what? Google found http://jsfiddle.net/trixta/cc7Rt/embedded/result,html,js,css/, but that doesn't open any new windows.

Those seem to be javascript-based date pickers, in html5 there is `<input type="date">`. It is not yet widely supported (mostly by things based on chromiums engine), so probably does not do anything in Webkit. (demo: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date).

I found out, that the drop downs are treated as separate clients with a callback in the match-all-rule, that prints some stuff to standard output. xtrace doesn't output anything for me when running qutebrowser under it.

**Comment by psychon** [comment]
> The drop downs usually close, when the browser loses focus. But if awesome handles the drop down as a new client, it will get focus instead of the browser, so it is closed instantly.

So why does this work anywhere? Don't most WMs focus new windows?!?

**Comment by crater2150** [comment]
I noticed, that I had to actually put `focusable = false` to make the dropdown usable, otherwise it would not instantly close, but as soon as the mouse enters it.

**Comment by crater2150** [comment]
Okay, it seems like the rule did not fix it after all. `focusable = false` causes it to stay open, but clicking on any option in the dropdown closes it without changing the value.
I re-checked with i3, the problem does not appear there and the main browser window definitely loses focus when the mouse is over the dropdown's list. I really have no idea, what else to try.

**Comment by chiraag-nataraj** [comment]
Hmm, @crater2150 are you still seeing this issue? I just tried with qupzilla 2.2.3 (and awesome 4.2) and the demo you sent worked just fine. I'm on Debian sid/experimental.

**Comment by crater2150** [comment]
I still have that issue, tried it with same qupzilla and awesome version, but the qt pacakges are still on v5.8 on my distro (voidlinux), Debian sid has 5.9. I'll try building against webengine 5.9 and see if it still occurs.

**Comment by crater2150** [comment]
Today my distro updated Qt from 5.8 to 5.10, which fixed the issue.
