### ISSUE TITLE
Watch widget gives incorrect output

### ISSUE THREAD

**Issue by RomeuG** [awesomeWM/awesome#2120]
Output of `awesome --version`:

```
awesome v4.2-120-ga6613c08 (Human after all)
 • Compiled against Lua 5.3.4 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.5
 • LGI version: 0.9.2
```

**How to reproduce the issue:**

- In the task list, put this line: `awful.widget.watch('curl -s "https://min-api.cryptocompare.com/data/price?fsym=VTC&tsyms=USD" | jq -r .USD', 30),`
- Reload AwesomeWM
- See the JSON in the AwesomeWM bar

**Actual result:**

A json string appears in the bar `{"USD":3.96}` (the number is irrelevant since its always changing).

**Expected result:**

Only the number should appear, since the command itself only gives the number as output, in the command line.

**Comment by psychon** [comment]
> since the command itself only gives the number as output, in the command line.

That's not true (notice that I escaped the `|` to prevent my shell from interpreting it):
```
$ curl -s "https://min-api.cryptocompare.com/data/price?fsym=VTC&tsyms=USD" \| jq -r .USD 
{"USD":3.9}
```
Try replacing your watch widget with `awful.widget.watch({ "sh", "-c", 'curl -s "https://min-api.cryptocompare.com/data/price?fsym=VTC&tsyms=USD" | jq -r .USD' }, 30),` so that a shell gets to handle the pipe.

**Comment by RomeuG** [comment]
Hey, thanks! It is working.

I am very sorry. As I was writing this, I noticed that the example in the documentation:

`awful.widget.watch('bash -c "sensors | grep temp1"', 15),`

You are actually calling "bash". I did not notice that the first time I read it.
