### ISSUE TITLE
someone help build awesome

### ISSUE THREAD

**Issue by batmanm0b1E** [awesomeWM/awesome#2126]
I extracted the git file like said

Then run make in folder

The switched to build folder like said. Run cmake but i get this

Usage

  cmake [options] <path-to-source>
  cmake [options] <path-to-existing-build>

Specify a source directory to (re-)generate a build system for it in the
current working directory.  Specify an existing build directory to
re-generate its build system.

Run 'cmake --help' for more information.

Somebody help please Thank you

**Comment by Elv13** [comment]
Short answer: use `make` instead, we have a wrapper for this.

Long answer:

```
mkdir build
cd build
cmake .. -DCMAKE_INSTALL_PREFIX=/usr
make -j2 package # (or `make -j2 install` if you are not on a .deb or .rpm based distribution)
```

But why do you need to compile Awesome for source. Does your distribution provides packages that are too old?

**Comment by batmanm0b1E** [comment]
um yeah that's what i said. But its saying here @Elv13  need the git version i think

I'm trying to install hes config stuff but haven a difficult time 
https://github.com/actionless/awesome_config

**Comment by Elv13** [comment]
@actionless Does your config really requires Awesome-git?

**Comment by actionless** [comment]
actually i wrote that readme in 3.5 times or so, i'll update it

**Comment by batmanm0b1E** [comment]
SO i can just install 4.2 awesome in the aur @actionless that my understanding?

**Comment by actionless** [comment]
just `community/awesome 4.2-1` should be fine if you're on arch
