### ISSUE TITLE
Get wrong the geometry of client with new tag

### ISSUE THREAD

**Issue by wxg4net** [awesomeWM/awesome#213]
test demo
```lua
local wibox        = require("wibox")
local awful        = require('awful')
local pairs        = pairs
local tostring     = tostring
local naughty      = require("naughty")
local capi         = {
    tag            = tag,
    client         = client,
    mouse          = mouse,
    screen         = screen
}

local function debuginfo( message )
    mm = message
    if not message then
        mm = "false"
    end
    nid = naughty.notify({ text = tostring(mm), timeout = 10 })
end

local t={}
local scr = capi.mouse.screen;
t[scr] = awful.tag.new({'test'},scr,awful.layout.suit.fair)[1]

local clients = capi.client.get(scr)

for _, c in pairs(clients) do
  awful.client.toggletag(t[scr], c)
end

awful.tag.viewonly(t[scr], t.screen)

local clients = awful.client.visible()

for _, thisclient in pairs(clients) do
  local geom = thisclient.geometry(thisclient)
  debuginfo(geom.x) -- not geometry in t[scr] but old geometry
  debuginfo(geom.y) -- not geometry in t[scr] but old geometry
end
```

**Comment by blueyed** [comment]
What awesome version are you using?
3.5.6, or Git master?
Can you try Git master?

**Comment by wxg4net** [comment]
version: Git master

**Comment by blueyed** [comment]
If I understand it correctly, you are copying clients to a new screen, and that's not reflected in the client's geometry?
The clients are still displayed on the initial tags, correct?
Does it work if you move the clients to a new tag (by using `movetotag` (http://awesome.naquadah.org/doc/api/modules/awful.client.html#movetotag))?

I don't know how `geometry` should behave in your case.
Maybe there could be an optional argument for `client.geometry` to accept a tag argument?

But then I currently might be missing something here anyway.

**Comment by wxg4net** [comment]
"you are copying clients to a new screen" -- no. just copy to one new tag;
"The clients are still displayed on the initial tags, correct?" -- yes
"Does it work if you move the clients to a new tag" -- not test. i want to copy

i found issues on https://github.com/awesomeWM/awesome/commit/74106462ac1f0877d4dd3791c9a983283c034169  by git bisect.

**Comment by wxg4net** [comment]
sry . it worked by capi.awesome.emit_signal("refresh")

**Comment by blueyed** [comment]
I see.
See #153.
