### ISSUE TITLE
Useless gap between certain clients not appearing

### ISSUE THREAD

**Issue by Probotect0r** [awesomeWM/awesome#2132]
**Output of `awesome --version`:**
```
awesome v4.2 (Human after all)
 • Compiled against Lua 5.3.4 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.5
 • LGI version: 0.9.2
```

**How to reproduce the issue:**
1. Change the layout mode to `tile`
2. Open 5 - 6 windows.

**Actual result:**
The gap between certain windows doesn't appear. See images below.

Gap between 4th and 5th window doesn't appear:
![2017-12-03-204605_2559x1439_scrot](https://user-images.githubusercontent.com/6376824/33532837-17f8d880-d86b-11e7-9fc4-b5442199fb30.png)

Gap between 2nd and 3rd window doesn't appear:
![2017-12-03-204921_2559x1439_scrot](https://user-images.githubusercontent.com/6376824/33532922-baf715b0-d86b-11e7-8e7f-244c43c65c79.png)

**Expected result:**
The Gap between the all windows should appear, and be the same in size.

**Notes:**
I have tried running AwesomeWM by itself, as well as with XFCE, and the same happens for both.

**Comment by Elv13** [comment]
The gap between terminals is determined by the size of the font. By default, Awesome honors the terminal request to be a multiple of a certain size.

Are you sure you did set the `useless_gap` manually and disable client size honoring in the rules?

**Comment by Probotect0r** [comment]
I only set the `beautiful.useless_gap` variable to 5. I didn't know about disabling client size honoring. I will look in to that now, thanks.

**Comment by Probotect0r** [comment]
Setting `size_hint_honor = false` in the rules for "all clients" section fixes this. Thank you.

**Comment by Elv13** [comment]
glad it works
