### ISSUE TITLE
Firefox and chrome dont snap

### ISSUE THREAD

**Issue by nihiluis** [awesomeWM/awesome#2135]
Output of `awesome --version`:

awesome v4.2 (Human after all)
 • Compiled against Lua 5.3.4 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.5
 • LGI version: 0.9.2

**How to reproduce the issue:**

check firefox and chromium
i use arch linux

**Actual result:**

firefox doesnt snap to the grid at all. I can click on it and move it without pressing mod4. from 57 upwards.

if i do mod4+right click (which resizes other apps), its registered as a normal right click by firefox.

if I do mod4+m (maximize) firefox does get maximized, but I can still move it. 

chromium doesnt snap either but cant be moved and is always maximize

both chromium and firefox have the + sign before the title, not sure what that means.

this has no effect apparently (adding it in rules):
```
          { rule = { class = "chromium" },
            properties = { maximized = false } },
          { rule = { class = "firefox" },
            properties = { maximized = false } },
```

**Expected result:**

chromium and firefox snap to the grid.

__

any ideas how i can fix this?

**Comment by Elv13** [comment]
Make sure they are not floating, it's `mod4+ctrl+space` in the default config.

**Comment by psychon** [comment]
Any special symbols in the tasklist for these programs? What's the output when running `xprop WM_NORMAL_HINTS` in a terminal and clicking on these programs?

**Comment by psychon** [comment]
> firefox doesnt snap to the grid at all. I can click on it and move it without pressing mod4. from 57 upwards.

This sounds like something that is implemented in firefox...? You could do a rule with `callback = function(c) c:connect_signal("property::geometry", function() print(debug.traceback()) end` to get some traceback on where the move comes from. If the traceback looks quite useless, that might be another pointer that this is firefox moving itself.

**Comment by nihiluis** [comment]
the + one is the only task symbol.

when running xprop:

```
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified minimum size: 300 by 166
		program specified base size: 300 by 166
		window gravity: NorthWest
```

**Comment by nihiluis** [comment]
i didnt add a "Nightly" class. I set maximize to false there, firefox doesnt start maximized anymore like that. kinda odd though
