### ISSUE TITLE
Missing files when installing with apt

### ISSUE THREAD

**Issue by argirisNt** [awesomeWM/awesome#2136]
Output of `awesome --version`:

awesome v4.0 (Harder, Better, Faster, Stronger)
 • Compiled against Lua 5.1.5 (running with Lua 5.1)
 • D-Bus support: ✔
 • execinfo support: ✔
 • RandR 1.5 support: ✔
 • LGI version: 0.9.1

**How to reproduce the issue:**

In Debian stretch, when installing awesome with `apt-get`, the files:
`gears/filesystem.lua`, `gears/math.lua`, `gears/string.lua`, `gears/table.lua` 
are missing from `/usr/share/awesome/lib`.

Moreover, the above are not included in the `gears/init.lua` file, i.e. the lines below are missing:
```
math = require("gears.math");
table = require("gears.table");
string = require("gears.string");
filesystem = require("gears.filesystem");
```
This causes my `rc.lua` file to break.

**Comment by actionless** [comment]
it seems like your config was written for awesome wm version 4.1+
