### ISSUE TITLE
naughty.destroy_all_notifications can freeze awesome in suspend mode

### ISSUE THREAD

**Issue by timroes** [awesomeWM/awesome#2138]
Output of `awesome --version`:

```
awesome v4.2 (Human after all)
 • Compiled against Lua 5.3.4 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.5
 • LGI version: 0.9.2
```

Looking at the sources and changes, this should still occur in master, but haven't verified it.

**How to reproduce the issue:**

Create a minimum config file with the following lines:

```lua
local naughty = require('naughty')
naughty.suspend()
naughty.notify({
	text = 'test'
})
naughty.destroy_all_notifications()
```

and run it (e.g. via Xephyr).

**Actual result:**

The awesome process is now frozen with 100% CPU load. In fact this always happens, when you try to call `naughty.destroy_all_notifications` in suspend mode, after a notification has been "shown" (or wanted to be shown, but wasn't due to suspend mode).

If no notification tried to be shown this doesn't occur, neither if you call `naughty.resume()` before calling `naughty.destroy_all_notifications()`.

**Expected result:**
 
awesome shouldn't freeze with 100% CPU load.

**Comment by psychon** [comment]
Side note: We call `destroy_all_notifications` when a screen is removed, so this is easier to hit than it looks as first.

Possible patch (that is only a starting point for a fix, see inline comment):
```diff
diff --git a/lib/naughty/core.lua b/lib/naughty/core.lua
index 2d58d2e0..2d8398ae 100644
--- a/lib/naughty/core.lua
+++ b/lib/naughty/core.lua
@@ -341,7 +341,8 @@ end
 -- @param[opt=false] keep_visible If true, keep the notification visible
 -- @return True if the popup was successfully destroyed, nil otherwise
 function naughty.destroy(notification, reason, keep_visible)
-    if notification and notification.box.visible then
+    if notification then
+        -- TODO protect against destroying a given notification twice
         if suspended then
             for k, v in pairs(naughty.notifications.suspended) do
                 if v.box == notification.box then
@@ -352,7 +353,7 @@ function naughty.destroy(notification, reason, keep_visible)
         end
         local scr = notification.screen
         table.remove(naughty.notifications[scr][notification.position], notification.idx)
-        if notification.timer then
+        if notification.timer and notification.timer.started then
             notification.timer:stop()
         end
 
```

**Comment by Elv13** [comment]
@psychon Can you create a pull request for this?

**Comment by psychon** [comment]
For my not-working patch above? Nope. :-)

Anyway, I self-assigned and will see when I find some Awesome time again.

**Comment by psychon** [comment]
@Elv13 Do you think this was fixed by your rewrite? At least the reproducer above no longer works / does not break anything.

**Comment by Elv13** [comment]
https://github.com/awesomeWM/awesome/commit/c691a0842b28ee03a81f2dbcd8b38477362b5544 changes how this works a bit.

**Comment by Elv13** [comment]
Assuming this is fixed until proven wrong.

**Comment by lorddex** [comment]
hello, 

I'm on awesome v4.3 (Too long)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2

installed on Ubuntu 20.04 using snap.

I think I've reproduced the error, I was working on a "suspend notifications" widget and all the time I try to destroy all the notifications when they are suspended awesome process freezes with 100% CPU load.

The widget code is the following:
```
local awful = require("awful")
local wibox = require("wibox")
local gears = require("gears")
local beautiful = require("beautiful")
local naughty = require("naughty")

local HOME = os.getenv('HOME')

local widget_font = 'Font Awesome 5 Free-Solid-900 10'

local dnd_widget = wibox.widget.textbox()
dnd_widget.font = widget_font
dnd_widget:set_text(" \u{f0f3} ")

dnd_widget:connect_signal("button::press", function(_,_,_,button)

    if (naughty.is_suspended()) then
        dnd_widget:set_text(" \u{f0f3} ")
        naughty.destroy_all_notifications()
    else
        dnd_widget:set_text(" \u{f1f6} ")
    end
    
    naughty.toggle()

end)

return dnd_widget
``` 

if you add it click on the icon to suspend the notifications, send some notifications and try to enable them again awesome freezes.
I think it's the same bug raised time ago 

P.S.
with the following code (first re-.enable notifications and then remove everything) destroy_all_notifications works as expected
```
local awful = require("awful")
local wibox = require("wibox")
local gears = require("gears")
local beautiful = require("beautiful")
local naughty = require("naughty")

local HOME = os.getenv('HOME')

local widget_font = 'Font Awesome 5 Free-Solid-900 10'

local dnd_widget = wibox.widget.textbox()
dnd_widget.font = widget_font
dnd_widget:set_text(" \u{f0f3} ")

dnd_widget:connect_signal("button::press", function(_,_,_,button)

    naughty.toggle()

    if (naughty.is_suspended()) then
        dnd_widget:set_text(" \u{f1f6} ")
    else
        dnd_widget:set_text(" \u{f0f3} ")
        naughty.destroy_all_notifications()
    end
    
end)

return dnd_widget
```

**Comment by Elv13** [comment]
@lorddex Please upgrade to the latest git version. We don't make releases very often, so this has been fixed in git a couple-ish years ago, but it isn't in an official release yet.
