### ISSUE TITLE
awful.placement.no_overlap moves client to top-left corner if no space is available

### ISSUE THREAD

**Issue by psychon** [awesomeWM/awesome#2139]
I just noticed the issue from the title and I think this was introduced by 02b6f9893d630cb7ff5b6f7b61874976d5cc7eb9 which is the fix to #813. Since my fix would be to just revert that commit... I'm confused. And https://github.com/awesomeWM/awesome/pull/852#issuecomment-214689481 confuses me some more.

The code initialises `new` to the client's current position. So if nothing is found, then the client should stay where it was without this 'new' code.
@blueyed The issue from "back then" seems to be "client opens on wrong screen". However, I think this patch just papers over the problem since it kind of forces the client to be positioned at the top left corner of the workarea (and normally, if some space is found, well, the client ends up in the workarea, too). Assuming someone does not use `no_overlap`-placement, then the original issue would still exist.
So... I don't know. The C code should ensure that the client's original position matches its screen, so (once again) I don't understand where this issue would come from.

Any complaints about reverting the patch in question with my "papers over the actual problem"-argument above?

**Comment by blueyed** [comment]
@psychon 
Yes, go ahead with reverting it - I am trusting you there.. :)

**Comment by psychon** [comment]
> I am trusting you there.. :)

Well, reverting it will re-introduce the original issue and I still have no clue where exactly that comes from, I'm just saying that the fix is not a fix, but a paper-over-the-problem. So trusting me here is the wrong thing to do.
