### ISSUE TITLE
Too slow rendering on radeon

### ISSUE THREAD

**Issue by actionless** [awesomeWM/awesome#214]
Today i tried to run awesome on `Radeon HD 8570 / R7 240` using `radeon` driver. Awesome wm itself (ie wiboxes) and some of the terminals (at least `urxvt` and `st`; `xterm` is not affected) are rendering almost as slow as a slideshow. Any other applications started in awesome wm are running fine.
Also I was trying starting awesome either with `--no-argb` option either without it and there wasn't  any difference.
I did not reproduced the problem in Openbox and i3.

**Comment by Elv13** [comment]
Umm, can you try doing some `strace`, `ltrace` and `valgrind --tool=callgrind` sessions to get a general idea of the problem? Maybe this is related to awesome doing way too many redraw for nothing. There is a patch in the old bug tracker, but it will be very, very hard to merge given all the side effects

**Comment by actionless** [comment]
xtrace:
http://sprunge.us/WQPB
strace:
http://sprunge.us/SBGh
valgrind:
http://sprunge.us/SBGh

with `ltrace` i did not managed to wait until awesome will start -- i was waiting for about 5 minutes and it was stalled, i can try to wait more if you think what it can help.

**Comment by egordorichev** [comment]
I had problem like this. I rebuild mesa with `-r600` flag and now it's ok.

**Comment by actionless** [comment]
@egordorichev you mean this one (https://projects.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/mesa#n30) or smth other?

**Comment by egordorichev** [comment]
I don't know. I'm using gentoo, so I just run:
```
USE='r_600' emerge mesa
```

**Comment by actionless** [comment]
it seems to be reproducing only when running the session manually, when using DM (like `lightdm` in my case) it works fine, so mb for correct driver initialization some env vars should be exported or smth like that

so anyway nothing to do with awesome wm here
