### ISSUE TITLE
Is it possible to set the background to application's window?

### ISSUE THREAD

**Issue by tleydxdy** [awesomeWM/awesome#2144]
awesome v4.2 (Human after all)
 • Compiled against Lua 5.3.4 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.5
 • LGI version: 0.9.2

Can I set a window in awesome to be the background? for example, reparent all the windows to some application's window.

**Comment by psychon** [comment]
> reparent all the windows to some application's window.

No, you cannot.

However, what would be the (visible) difference of that from having a floating client with the size of the screen/workarea? Perhaps also sticky and below everything else?
So something like this in awful.rules:
```
properties = { floating = true, sticky = true, below = true, focusable = false, placement = function(c)
    c:geometry(screen[1].geometry)
end },
```

**Comment by tleydxdy** [comment]
aha, so I can let windows to be always at the bottom! that's awesome! can I make it non-interactive?

**Comment by Elv13** [comment]
Yes, you can set an empty input mask. That defines the zones where interactive inputs are allowed. Put an empty zone and that should do it. We don't have an official property for client (yet?), but we have it for wiboxes in Awesome git-master. See https://github.com/awesomeWM/awesome/blob/master/lib/wibox/init.lua#L155 for the implementation details.

**Comment by tleydxdy** [comment]
one last thing, the window is still in front of the topbar systray etc. so it will block all of that....

**Comment by psychon** [comment]
Hm... Make the wibar `ontop = true`. That means that it will also be above other clients, but right now that's the only solution that I see...

**Comment by tleydxdy** [comment]
`	{ rule_any = { class = {"DDLC"}},
		properties = {
			titlebars_enabled = false,
			is_fixed = true,
			width = 1920,
		    height = 1080,
		    skip_taskbar = true,
		    y = 18,
		    x = 0,
		    floating = true,
		    sticky = true,
		    below = true,
		    focusable = false
		   } },`
here is what I ended up with, so the entire window is moved down the height of the taskbar

**Comment by psychon** [comment]
To avoid hardcoding those numbers, you could try (difference to my original proposal is `geometry` vs `workarea`)
```
    placement = function(c)
        c:geometry(screen[1].workarea)
    end
```
