### ISSUE TITLE
beautiful xresources only defaults

### ISSUE THREAD

**Issue by ransomts** [awesomeWM/awesome#2150]
Output of `awesome --version`:

> awesome v4.2 (Human after all)
 > • Compiled against Lua 5.3.4 (running with Lua 5.3)
 > • D-Bus support: ✔
 > • execinfo support: ✔
 > • xcb-randr version: 1.5
 > • LGI version: 0.9.2

Also fwiw, my kernel is 4.14.10-1-ARCH and I got my builds from the official repo.

**How to reproduce the issue:**

Just adding in the normal use cases for the xresources require.
Running this through terminal:
```
awesome-client -v 'awful=require("awful");
 xresources=require("beautiful.xresources");
 xrdb = xresources.get_current_theme();
 awful.spawn("notify-send _"..xrdb.color1)'
```

**Actual result:**

I just get the #cb1578 from the fallbacks in xresources.lua sent back to me.

**Expected result:**

> *.color1: #38B1C6
> *color1:  #38B1C6

This is the relevent section of my .Xresources, so I would like to see this value instead.

**Temp Solution**
Here is my drop-in for similar functionality, but I would still prefer not to make a clone if the original works. Any ideas where my .xresources might be going wrong?
```lua
function os.capture(cmd, raw)
  local f = assert(io.popen(cmd, 'r'))
  local s = assert(f:read('*a'))
  f:close()
  if raw then return s end
  s = string.gsub(s, '^%s+', '')
  s = string.gsub(s, '%s+$', '')
  return s
end

function getXrdbTable()
   x = os.capture("xrdb -query")
   data = {}
   for line in string.gmatch(os.capture("xrdb -query"), "[^\n]*") do
	  tt = {}
	  for element in string.gmatch(line, "[^:]*") do
		 table.insert(tt, element)
	  end
	  data[tt[1]] = tt[2]:gsub("%s+", "")
   end
   return data
   --for key,value in pairs(data) do print(key,value) end
end

xrdb = getXrdbTable()
```

**Comment by actionless** [comment]
what is the output of?
```sh
awesome-client 'return awesome.xrdb_get_value("", "color1")'
awesome-client 'return awesome.xrdb_get_value("", ".color1")'
```

**Comment by ransomts** [comment]
```
$ awesome-client 'return awesome.xrdb_get_value("", "color1")'
   string "#38B1C6"
$ awesome-client 'return awesome.xrdb_get_value("", ".color1")'
   string "#38B1C6
```
That pulls the correct values, was my lua wrong in my first bash command?

**Comment by actionless** [comment]
i am thinking what xrdb settings could be loaded after beautiful.xresources is being init

how/when are you doing `xrdb -merge ~/.Xresources` (or smoething similar to it)?

**Comment by ransomts** [comment]
I've got this in my .xinitrc
```
userresources=$HOME/.Xresources
if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

exec /usr/bin/awesome >> ~/.cache/awesome/stdout 2>> ~/.cache/awesome/stderr
```

The stderr file is still logging the warning from beautiful for my command, and yours doesn't make any warnings. The rest of my xinitrc is based on the example from `/etc/X11/xinit/xinitrc`

Thanks for helping out btw

**Comment by actionless** [comment]
what excatly the message do you see in your log?

also i am wondering what will be if you will insert `sleep 2` between `xrdb -merge ..` and `exec awesome..` in your xinitrc

**Comment by ransomts** [comment]
Here is the warning, looks to me like it's the `xresources.get_current_theme()` warning just.

> 2018-01-04 12:10:59 W: beautiful: can't get colorscheme from xrdb (using fallback).

Putting in the `sleep 2` didn't seem to change the outputs

**Comment by actionless** [comment]
could you test with this patch?

**Comment by actionless** [comment]
the fix was merged now, could you check now?

**Comment by Elv13** [comment]
Closest due to inactivity
