### ISSUE TITLE
Keygrabber doesn't stop on stop

### ISSUE THREAD

**Issue by treere** [awesomeWM/awesome#2167]
Output of `awesome --version`

awesome v4.2-230-gc9bd787f (Human after all)
 • Compiled against Lua 5.3.4 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.5
 • LGI version: 0.9.2

**How to reproduce the issue:**

Call this function on a client. 

```
function grabtest(c)
  local grabber = awful.keygrabber.run(function(mod, key, event)
		 naughty.notify({title= event,text= key })
			awful.keygrabber.stop(grabber)
  end)
end
```

It is like the example in the api.

**Actual result:**
Doesn't stop the grabber. (It is if grabber is not local)

**Expected result:**
To stop the grabber

**Observations**
If `grabber` is not local it works.

**Comment by psychon** [comment]
Well... change the notification to `text = tostring(grabber)` and you will see that you are passing a `nil` argument to `stop()`. Of course that does not work.
You can fix this by doing:
```lua
local grabber
grabber = awful.keygrabber.run(function(mod, key, event)
    [snip]
end)
```

**Comment by treere** [comment]
It makes sense. That apidoc is wrong. 

Thank you!
