### ISSUE TITLE
naughty.reset_timeout cause a `timer already started` error

### ISSUE THREAD

**Issue by Bekcpear** [awesomeWM/awesome#2175]
Output of `awesome --version`:

awesome v4.2 (Human after all)
 • Compiled against Lua 5.3.4 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.5
 • LGI version: 0.9.2

**How to reproduce the issue:**

execute `naughty.reset_timeout(notification, timeout)` function

**Actual result:**

the timeout was reset, but with a `timer already started` error 

**Expected result:**

with no error log

---

Is there a redundant code at line 443 of [core.lua](https://github.com/awesomeWM/awesome/blob/4e42996d9a7e6a3f2da294f072b5288a6c34e4cd/lib/naughty/core.lua)? the timer has been started at line 425. Or maybe there are some other considerations?

**Comment by 1096283585** [comment]
妈呀，都是中国人，搞毛外语啊，可以加个联系方式吗，方便交流，一起折腾 ^_^

**Comment by 1096283585** [comment]
I'm sorry, it's a bit obtrusive *_*

**Comment by Bekcpear** [comment]
@1096283585 可以来 IRC 频道 #awesome-cn 一起愉快的交流，拥有各路大神都在。 Freenode 网络。

**Comment by 1096283585** [comment]
Can you leave a contact, easy to communicate, and toss together

**Comment by Bekcpear** [comment]
@1096283585 You can find me on Telegram @Bekcpear

**Comment by 1096283585** [comment]
信息已经记录下来了，你的那几个也可以删除了 ^^

**Comment by actionless** [comment]
@blueyed looks reasonable, doesn't it? (i think you were merging naughty-related stuff more often lately)

**Comment by Elv13** [comment]
This was fixed a couple months ago.
