### ISSUE TITLE
awful.util.getdir("config") vs. `awesome -c CONFIG`

### ISSUE THREAD

**Issue by ff2000** [awesomeWM/awesome#218]
I ran into issues when trying to run Elv13 awesome-config. Scripts and resources get concatenated with awful.util.getdir("config"). I wanted to simply run it safely without losing my current config, which turned out to be impossible as scripts were not found, because getdir always returns "${XDG_CONFIG_HOME}/awesome".
I would expect this to return the actual location my rc.lua is stored, when I pass one. E.g. "$HOME/test/awesome/" when I run "awesome -c $HOME/test/awesome/rc.lua".

**Comment by Bew78LesellB** [comment]
For my configuration, i've made a Theme Loader that find my different configuration, then try to load them, and set a global variable with the curre't theme path... 
See https://github.com/Bew78LesellB/ConfigAwesome for more information!

**Comment by ff2000** [comment]
Thx for your answer! But your config doesn't work for me, either - because you load files relative to awful.util.getdir("config"), which returns ~/.config/awesome in any case ;) I really thought in the first place that it worked. It looked like the default theme, but - well - probably you like that. Then I read your rc.lua and I realized: This IS the default theme ;)

You can try what this issue is about:
```
mv ~/.config/awesome ~/.config/awesome_bkp
awesome -c ~/.config/awesome_bkp/rc.lua
```
(The default directory has to be out of place)

In the meantime I found awesome.conffile. Manipulating that in awful.util.getdir shouldn't be that hard. I can create a PR if you think this issue is a real issue at all.

And there is another related issue: LUA_PATH isn't expanded, so init.lua never is considered for require when running an rc.lua different from the default one (~/.config/awesome/rc.lua). I have to manually export LUA_PATH="?/init.lua;;" to make it work again (which isn't a big issue)

**Comment by Bew78LesellB** [comment]
Oh ok, I see know what you mean! 

For information, my config is in wip, and the dev branch is much more advanced than master! 

But if you take the idea of my ThemeLoader, I think you can redefine the awful.utils.getdir function, to return another base directory!... 

Also: you could make kind of script that execute awesome, then a function passed by awesome-client, (to the theme loader for example) with the given config path!
