### ISSUE TITLE
[Q] XDG autostart apps

### ISSUE THREAD

**Issue by ildar** [awesomeWM/awesome#2187]
There's the [spec](https://specifications.freedesktop.org/autostart-spec/autostart-spec-latest.html) of the apps to start during X session startup.
Are there implementations around? or what's the best way to implement? a recipe?
Note: the thing is widely supported by other WM/DMs, e.g. Gnome, KDE, Enlightenment.

**Comment by psychon** [comment]
Google lead me to https://wiki.archlinux.org/index.php/desktop_entries#Autostart which says

> Tools like dapper, dex, or fbautostart can be used to offer XDG autostart in unsupported desktop environments as long as some other autostart mechanism exists. Use the existing mechanism to start the xdg compliant autostart tool.

So I guess you can pick one of those tools and start it through awesome.

> other WM/DMs, e.g. Gnome, KDE, Enlightenment

None of those is a WM, they are all DMs. ;-)

**Comment by ildar** [comment]
Thanks! 👍
