### ISSUE TITLE
awful.widget.prompt and menubar do not support russian (cyrillic) input

### ISSUE THREAD

**Issue by Temp24354** [awesomeWM/awesome#219]
When I trigger these widgets (Meta+R, Meta+P by default) and try to type text, input is always in English, even if I have another keyboard layout chosen (for example, if I use russian keyboard layout). Thus I cannot access russian-named files using awful.widget.prompt/menubar, for example.

**Comment by blueyed** [comment]
#227 should fix this.
Can you try it?

**Comment by Temp24354** [comment]
I have built awesome from https://github.com/petoju/awesome, and here is my report:
Now Cyrillic input works fine in all Awesome windows, but those keybinds, which require additional modkeys (such as Ctrl, Shift) stopped working with both layouts. For example, these ones:
awful.key({ modkey, "Shift"   }, "j", function () awful.client.swap.byidx(  1)    end),
awful.key({ modkey, "Shift"   }, "k", function () awful.client.swap.byidx( -1)    end),
awful.key({ modkey, "Control" }, "j", function () awful.screen.focus_relative( 1) end),
awful.key({ modkey, "Control" }, "k", function () awful.screen.focus_relative(-1) end),
while other programs' keybindings using these modkeys (such as Ctrl+F in text editor or file manager) work fine with both layouts.
I will add a similar report to https://github.com/awesomeWM/awesome/pull/227

**Comment by Temp24354** [comment]
Any ideas?

**Comment by petoju** [comment]
@Temp24354 this should be fixed in newer commits in #227

**Comment by blueyed** [comment]
I am closing this in favor of #227.
