### ISSUE TITLE
How to remove the border around the screen

### ISSUE THREAD

**Issue by 1096283585** [awesomeWM/awesome#2194]
Output of `awesome --version`:

awesome v4.2 (Human after all)
• Compiled against Lua 5.3.4 (running with Lua 5.3)
• D-Bus support: ✔
• execinfo support: ✔
• xcb-randr version: 1.5
• LGI version: 0.9.2

**How to reproduce the issue:**

none

**Actual result:**

how to remove only the border around the screen, but do not remove the border of the window, So, when I click on the edge of the screen do not click to the border, for example when I drag the scroll bar, if there is a border, it is easy to click to the border, so how does set the border width for 0 cases, remove the border around the screen.

**Expected result:**

none

**Comment by Elv13** [comment]
The only way I can think of is either using negative screen padding or using titlebars as border and an lot of extra code. The simpler way might be to use 0px border and gaps instead of border. If the wallpaper is a solid color, it will look the same.

**Comment by actionless** [comment]
idk what should be a proper approach for that, the only i've came up with was to subscribe to most of the signals which are fired when window changes its state in any way, and in signal handler checking window properties (like, if it maximixed or not, how many other windows are visible right now and so on) and based on that seting border width, color and other style parameters

https://github.com/actionless/awesome_config/blob/devel/config/signals.lua#L287-L374

**Comment by 1096283585** [comment]
Well, I write a rule that only sets the border of the terminal to 1, the other is 0, so it can be used as well.
