### ISSUE TITLE
Help: how to increase the font of the top bar (which contains 1 2 3 etc )

### ISSUE THREAD

**Issue by sant527** [awesomeWM/awesome#2196]
How to increase the font size and height of top bar which consists of menu , 1,2,3 .. and data etc

**Comment by psychon** [comment]
- If you haven't already, copy `/etc/xdg/awesome/rc.lua` to `~/.config/awesome` (creating that directory if it does not exist)
- Copy `/usr/share/awesome/themes/default/theme.lua` to `~/.config/awesome/theme.lua`
- Edit `~/.config/awesome/rc.lua`: Change `beautiful.init(gears.filesystem.get_themes_dir() .. "default/theme.lua")` to `beautiful.init("/home/YOUR_USER_NAME/.config/awesome/theme.lua")` (it should be somewhere around line 44, depending on your version of awesome)
- Edit `~/.config/awesome/theme.lua` and change `theme.font`. The default value is `sans 8`. How about `sans 12` instead?

**Comment by sant527** [comment]
I changes the 

`theme.font  = "sans 20"`

But then the menu gets crumbled when i click on it

**Comment by psychon** [comment]
Crumbled? Which menu exactly? If you mean the one that opens when you click on the icon in the top left corner: Change `theme.menu_height = dpi(15)` to e.g. `theme.menu_height = 50`.

**Comment by sant527** [comment]
Yes it worked

**Comment by therealplato** [comment]
I found this looking for a high DPI fix, can't hurt to crosslink https://unix.stackexchange.com/a/461525/37733
```
echo "Xft.dpi: 288" >> ~/.Xresources
xrdb -merge ~/.Xresources
```
and restart your apps.

I picked 288 DPI as it's 3x multiple of common 96 DPI and is a close match to my XPS 13's true DPI.

**Comment by actionless** [comment]
enjoy it, guys: https://wiki.archlinux.org/index.php/HiDPI
