### ISSUE TITLE
Help: Xephyr: Sublime text not opening inside awesome it opens on the host

### ISSUE THREAD

**Issue by sant527** [awesomeWM/awesome#2197]
I have kde running on my laptop. 

I am testing awesome inside Xephry using

` Xephyr :3 -ac -br -noreset -resizeable -screen 1152x720 & DISPLAY=:3.0 awesome &`

Then i do 
ctrl+shift + Space to  grab the mouse and keyboard

Inside I do 
Super + p and type firefox .It opens within awesome
Super + p and type dolphin .It opens within awesome

But 
Super + p and type subl .It opens outside

How to change this.

**Comment by psychon** [comment]
I don't know how to change that, nor do I know how sublime "escapes". Assuming you have sublime running in your normal X11 session, it could talk to itself over dbus. To get around that, replace `DISPLAY=:3.0 awesome &` with `DISPLAY=:3.0 dbus-run-session awesome &` to start awesome in a new DBus session.
If that's not it, then I do not know how Sublime manages to "escape".
