### ISSUE TITLE
Window titles on maximized windows get weird sequence of characters

### ISSUE THREAD

**Issue by gbell12** [awesomeWM/awesome#220]
After my upgrade to 3.5.6, I now get this:

![screenshot from 2015-05-12 17 22 32](https://cloud.githubusercontent.com/assets/3937658/7582008/b3e2633c-f8cc-11e4-9d0b-7fe26792898e.png)

Is "airplane, horizontal double-headed arrow, vertical double-headed arrow" a secret code for something?

**Comment by actionless** [comment]
for the maximized window

**Comment by gbell12** [comment]
For me it's not sometimes, but always.

**Comment by actionless** [comment]
You mean always then client is maximized or anytime? That happens with any client or only with firefox?

**Comment by gbell12** [comment]
I only know one way of maximizing the client (hotkey).  Any window, not just firefox.

**Comment by actionless** [comment]
from which repository revision did you built awesome?

mb it is older than the one where single maximized icon was added? https://github.com/awesomeWM/awesome/commit/4ee144188eceeb2695a010c5f0c05a1e5028c592

**Comment by gbell12** [comment]
Holey moley, what you're telling me is that the airplane, double-arrow, double-arrow is actually a FEATURE, not a Wingding/Unicode font problem.  Alright.  Wow.  Wouldn't have guessed that.

And, the situation has been fixed / improved in the code base.

Great, thanks for the replies.  I'll live with it until the next stable release.
