### ISSUE TITLE
Gaps for window snapping

### ISSUE THREAD

**Issue by ma9e** [awesomeWM/awesome#2205]
Here's my lame attempt at hacking something in:

```
diff --git a/lib/awful/mouse/snap.lua b/lib/awful/mouse/snap.lua
index e212d123..54f4ebab 100644
--- a/lib/awful/mouse/snap.lua
+++ b/lib/awful/mouse/snap.lua
@@ -227,8 +227,8 @@ function module.snap(c, snap, x, y, fixed_x, fixed_y)
     for _, snapper in ipairs(aclient.visible(c.screen)) do
         if snapper ~= c then
             local snapper_geom = snapper:geometry()
-            snapper_geom.width = snapper_geom.width + (2 * snapper.border_width)
-            snapper_geom.height = snapper_geom.height + (2 * snapper.border_width)
+            snapper_geom.width = snapper_geom.width + (2 * snapper.border_width) + (2 * (beautiful.snapper_gap or 0))
+            snapper_geom.height = snapper_geom.height + (2 * snapper.border_width) + (2 * (beautiful.snapper_gap or 0))
             geom = snap_outside(geom, snapper_geom, snap)
         end
     end
```

I noticed that this only works when snapping to the right and bottom edges, though. Any idea why? Also, could there be a way to retain both behaviors?

**Comment by psychon** [comment]
>  Any idea why?

Well, because you did not "mess with" the x/y position of the window, but only its size? Also, your multiplication with 2 does not really make sense for me.

I'm not quite sure what you are trying to achieve exactly, but does the following do what you want?
```diff
diff --git a/lib/awful/mouse/snap.lua b/lib/awful/mouse/snap.lua
index e212d123..47cf04f2 100644
--- a/lib/awful/mouse/snap.lua
+++ b/lib/awful/mouse/snap.lua
@@ -227,8 +227,10 @@ function module.snap(c, snap, x, y, fixed_x, fixed_y)
     for _, snapper in ipairs(aclient.visible(c.screen)) do
         if snapper ~= c then
             local snapper_geom = snapper:geometry()
-            snapper_geom.width = snapper_geom.width + (2 * snapper.border_width)
-            snapper_geom.height = snapper_geom.height + (2 * snapper.border_width)
+            snapper_geom.x = snapper_geom.x - (beautiful.snapper_gap or 0)
+            snapper_geom.y = snapper_geom.y - (beautiful.snapper_gap or 0)
+            snapper_geom.width = snapper_geom.width + (2 * snapper.border_width) + (beautiful.snapper_gap or 0)
+            snapper_geom.height = snapper_geom.height + (2 * snapper.border_width) + (beautiful.snapper_gap or 0)
             geom = snap_outside(geom, snapper_geom, snap)
         end
     end
```

> Also, could there be a way to retain both behaviors?

Sorry, what do you mean?

**Comment by ma9e** [comment]
Ah! You set me on the right path. The idea is inspired by [this post](https://www.reddit.com/r/unixporn/comments/7z7jnx/xmonad_now_i_have_two_bars_filled_with_useless/dun4ov2/). It's like a second invisible border around the content that you can snap to. It's purely for aesthetics (which awesome doesn't seem opposed to, correct me if I'm wrong).

The `snapper_geom.{x,y}` was a good hint, but now the patch only works on the top and left edges. :P The `2 *` is actually necessary.

How's this?

```diff
diff --git a/lib/awful/mouse/snap.lua b/lib/awful/mouse/snap.lua
index e212d123..d476a2e4 100644
--- a/lib/awful/mouse/snap.lua
+++ b/lib/awful/mouse/snap.lua
@@ -230,6 +230,15 @@ function module.snap(c, snap, x, y, fixed_x, fixed_y)
             snapper_geom.width = snapper_geom.width + (2 * snapper.border_width)
             snapper_geom.height = snapper_geom.height + (2 * snapper.border_width)
             geom = snap_outside(geom, snapper_geom, snap)
+
+            if (beautiful.snapper_gap ~= nil) then
+                local snapper_geom = snapper:geometry()
+                snapper_geom.x = snapper_geom.x - beautiful.snapper_gap
+                snapper_geom.y = snapper_geom.y - beautiful.snapper_gap
+                snapper_geom.width = snapper_geom.width + (2 * snapper.border_width) + (2 * beautiful.snapper_gap)
+                snapper_geom.height = snapper_geom.height + (2 * snapper.border_width) + (2 * beautiful.snapper_gap)
+                geom = snap_outside(geom, snapper_geom, snap)
+            end
         end
     end
```

**Comment by psychon** [comment]
> The snapper_geom.{x,y} was a good hint, but now the patch only works on the top and left edges. :P The 2 * is actually necessary.

Oh, right. The first addition of `snapper_gap` makes sure that the bottom right corner of the client stays where it was. The second addition actually adds the gap there.

> How's this?

I guess it does what you want, right?
If your question is "should I open a pull request to add this to awesome (together with the proper documentation for it)", I'll leave that question to others, e.g. @Elv13 and @actionless (because these two seem to be the ones who added other kinds of gaps to awesome).

**Comment by actionless** [comment]
i like the idea, also i would suggest to use `beautiful.useless_gap` as a default value if `snapper_gap` is unset

and also to do somehing similar in placement (mb to add a new placement filter `honor_gaps`)

**Comment by ma9e** [comment]
> i like the idea, also i would suggest to use beautiful.useless_gap as a default value if snapper_gap is unset

The only problem with this, as far as I can tell, is that the (useless) gap between contents is actually twice `beautiful.useless_gap`. It would be nice to actually have a second invisible border around the contents and snap *those* together, so it would look the same visually (without adding more non-obvious `2 *`), but I'm not sure how to do this. This also gets us gaps between clients and screen/workarea edges for free.

> and also to do somehing similar in placement (mb to add a new placement filter honor_gaps)

I looked for a while and I have no idea how to do this, sorry.

**Comment by actionless** [comment]
there is a PR for that but it have some unresolved problems:
https://github.com/awesomeWM/awesome/pull/596

basically, what such behavior shouldn't break the current one, ie to be optional
