### ISSUE TITLE
[Show Help] Text formatting error

### ISSUE THREAD

**Issue by kennethdhau** [awesomeWM/awesome#2210]
Output of `awesome --version`:

awesome v4.2-162-g032f587d (Human after all)
 • Compiled against Lua 5.3.4 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.5
 • LGI version: 0.9.2

**How to reproduce the issue:**

Use keybind to `show help` (Mod4+s)

**Actual result:**

Help textbox appears though text runs off the screen
(Sorry, couldn't find a good way to screenshot it as it disappears the moment I press a button. If someone has any suggestions, I'll try to get an image.)

**Expected result:**

Help textbox appears with text properly bounded by textbox dimensions with "next page" "previous page"

**Note**
Issue first appeared with Awesome 4.0 when switching to the `awesome-git` package of the Arch repository. Sorry for not getting a report out soner.

**Comment by kennethdhau** [comment]
Sorry for dropping a comment so soon, but I switched back to the `awesome` package just to see and the problem no longer appears. I believe it may have to do with which dependencies are installed with the package.

`awesome-git` dependencies: 
- cairo
- dbus
- gdk-pixbuf2
- libxdg-basedir
- libxkbcommon-x11
- lua
- lua-lgi
- pango
- startup-notification
- xcb-util-cursor
- xcb-util-keysyms
- xcb-util-wm
- xcb-util-xrm

`awesome` dependencies:
- cairo
- dbus
- gdk
- pixbuf2
- imlib2
- libxdg
- basedir
- lua
- lua
- lgi
- pango- startup
- notification
- xcb
- util
- cursor
- xcb
- util
- keysyms
- xcb
- util
- wm- xorg
- xmessage
- libxkbcommon
- x11
- libxkbcommon
- xcb
- util
- xrm

**Comment by actionless** [comment]
to make a "delayed" screenshot open a terminal and type there `sleep 5 ; scrot`

**Comment by kennethdhau** [comment]
I think it was a mismatch in library version. I just tried switching back to `awesome-git` and it seems to work again. Thanks for the tip!
