### ISSUE TITLE
Mouse resize keep aspect ratio

### ISSUE THREAD

**Issue by SammysHP** [awesomeWM/awesome#2225]
In some situations it is helpful to keep the aspect ratio when resizing (floating) clients. It would be nice to add another argument to `awful.mouse.client.resize` to preserve the aspect ratio.

I had a quick peek into the relevant code but I did not fully understand in the short time how everything works with the various callbacks. For someone who knows that area it might be a simple task.

**Comment by psychon** [comment]
From a quick look at `awful.mouse.resize`, it seems like this could be implemented via a `move_callback`. That would also require a way to pass that through `awful.mouse.client`.
@Elv13 Ideas?

**Comment by Elv13** [comment]
That use case was already taken into consideration when the code was written. It uses `request::geometry` with the `mouse.resize` context. The handler is `awful.mouse.resize_handler` and can be disconnected/upgraded to handle this use case.

**Comment by psychon** [comment]
So, if I understand you correctly, something like the following would do this, right? (I'm not completely sure that my math below is correct)
```lua
client.disconnect_signal("request::geometry", awful.mouse.resize_handler)
client.connect_signal("request::geometry", function(c, context, hints)
    hints = gears.table.clone(hints)
    local geo = c:geometry()
    local aspect = geo.width / geo.height
    hints.width = math.min(hints.width, aspect * hints.height)
    hints.height = math.min(hints.height, hints.width / aspect)
    hints.width, hints.height = gears.math.round(hints.width), gears.math.round(hints.height)
    return awful.mouse.resize_handler(c, context, hints)
end)
```
However, the above likely suffers from accumulation of rounding errors. Put differently, the aspect ratio can drift while resizing since resizing happens in integer increments.

**Comment by Elv13** [comment]
(updated the code above to fix the issue where there is a dozen way the client can get `request::geometry` and only 1 is relevant)

**Comment by SammysHP** [comment]
But what would be an elegant solution to change the behavior depending on a modifier? Something like

```lua
clientbuttons = awful.util.table.join(
    …
    awful.button({ modkey }, 3, awful.mouse.client.resize)
    awful.button({ modkey, "Control" }, 3, …)
)
```

Sounds like the above implementation would require a new context like `mouse.resize_aspect` which could only be added via a new `awful.mouse.client.resize` function AFAICS.

**Comment by actionless** [comment]
idk, mb you can set a variable in clientbutton callback and in geometry request handler choose the behavior based on that var
