### ISSUE TITLE
Can not minimize only client on a tag, while it's under cursor

### ISSUE THREAD

**Issue by flyboy14** [awesomeWM/awesome#223]
Seems like a bug, but I've never heared of someone having it, except me.
Since update to awesome 3.5.6-1 (still stays in 3.5.6-2) I found out, that it is impossible to minimize client, which is alone on current tag, with a hotkey, while cursor is not on the top of the wibox.
I can still minimize it by clicking on a tasklist:
``` lua
mytasklist.buttons = awful.util.table.join(
     awful.button({ }, 1, function (c)
          if c == client.focus then
               c.minimized = true
```
but my hotkey:
``` lua
awful.key({ alt,           }, "Escape", function (c) c.minimized = true end)
```
doesn't work, until I drag my cursor to wibox.
In awesome 3.5.5-1 everything works fine. 
I use lua 5.3.0-1, but in older version 5.2.4-1 same weird shit happened.
My config:
https://github.com/flyboy14/awesomewm

**Comment by blueyed** [comment]
Sounds like a duplicate of https://github.com/awesomeWM/awesome/issues/92.

**Comment by flyboy14** [comment]
Oh, sorry. It really is...
