### ISSUE TITLE
Keep focus after window move to another screen

### ISSUE THREAD

**Issue by funivan** [awesomeWM/awesome#2235]
```
awesome v4.2 (Human after all)
 • Compiled against Lua 5.3.1 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.4
 • LGI version: 0.9.1

```

I'm using following code to move client to another screen:
`awful.key({ modkey,           }, "o",      function (c) c:move_to_screen()        `

But after move focus get lost. 
Is there any way to keep focus on the moved window? 
I also tried 
```
  c:move_to_screen()
  client.focus = c
  client.focus:raise()
```
But this stuff doesent help. 

P.S. Thanks for awesome desktop manager.

**Comment by psychon** [comment]
Uhm.. cannot reproduce, I guess. I just ran `awesome-client 'client.focus:move_to_screen()'` in a terminal and it kept focus.

How about the following to figure out what happens to the input focus? The idea being that the traceback might point out what causes focus to be lost.
```lua
client.connect_signal("unfocus", function()
  naughty.notify{ text = debug.traceback() }
end)
```

**Comment by funivan** [comment]
![screenshot from 2018-04-04 15-36-25](https://user-images.githubusercontent.com/425208/38307892-f76cb722-381d-11e8-9828-5bdda4b2963a.png)

**Comment by funivan** [comment]
I have own config, maybe that`s why this is happening.

**Comment by psychon** [comment]
Uhm, the client is being unfocused because it is assigned to no selected tag. But why??
(And looking at the C code here, I wonder why this does not happen for me, too; the C code first untags and then tags clients in `c:tags(foo)`, so there is a moment when the client has temporarily no tags at all; at this moment the call chain `luaA_client_tags` -> `untag_client` -> `banning_need_update` -> `client_ban_unfocus` -> `client_unfocus` should always cause an unfocus?)

**Comment by funivan** [comment]
I will try to use default config and check it. And then modify it according to my preferences. Maybe I will find some bug, or typo in my configuration.

**Comment by funivan** [comment]
I use following code to move window and keep focus
```
awful.key(
        { super }, "#51", -- \\
        function(c)
            c:move_to_screen()
            c:tags({ awful.screen.focused().selected_tag })
            client.focus = c;
        end,
        { description = "Move window to the next screen", group = "Window" }
    ),
```
[awesome.tar.gz](https://github.com/awesomeWM/awesome/files/2231040/awesome.tar.gz)

All works fine. 
Here is my full config. Maybe it will help.

**Comment by actionless** [comment]
try:

```lua
awful.key(
        { super }, "#51", -- \\
        function(c)
            local new_sid = c.screen.index + 1
            c:move_to_tag(screen[new_sid].selected_tag)
            client.focus = c;
        end,
        { description = "Move window to the next screen", group = "Window" }
),
```

**Comment by funivan** [comment]
@actionless yes, with default config it works fine. I press `super+o` or `super + \` and the client is moved to another monitor without focus lost. Probably there is a bug in my configuration. 
Thanks for the help.
