### ISSUE TITLE
Some theme variables can't be set for notifications

### ISSUE THREAD

**Issue by ervasive** [awesomeWM/awesome#2237]
Output of `awesome --version`:

```
awesome v4.2-289-g98e59225 (Human after all)
 • Compiled against Lua 5.3.4 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
```
It looks like some values of notifications library can't be overwritten properly by theme variables and by looking into its code, the problem seems to be [in the order of how the variables are being set](https://github.com/awesomeWM/awesome/blob/5e6f5343653a3f69ce353f3a3388a9b6f48e370a/lib/naughty/core.lua#L622-L668):

```lua
local border_width = args.border_width or preset.border_width or 
        beautiful.notification_border_width
```

It never reaches the `beautiful.notification_border_width` part, because of `preset.border_width` is always being set by:

```lua
local preset = gtable.join(naughty.config.defaults or {},
      args.preset or naughty.config.presets.normal or {})
```

So it is possible to set let's say `notification_border_width` through `naughty.config.defaults.border_width` but not through `beautiful.border_width`.

**Comment by actionless** [comment]
i would suggest deprecating notification presets system and reimplementing it in beautiful 
```lua
local border_width = args.border_width or beautiful.notification_PRESETNAME_border_width or beautiful.notification_border_width  or preset.border_width```

if preset is not equal to default preset deprecation warning will be printed

**Comment by Elv13** [comment]
> i would suggest deprecating notification presets system and reimplementing it in beautiful:

In the undefined timeframe when I get time to upstream this, I "solved" that issue using the `request::` API where you can control the exact widget that's created for the notification. You also have real objects with built-in lifecycle to work with. This make having pretty notifications much easier.

https://elv13.github.io/classes/naughty.notification.html
https://github.com/awesomeWM/awesome/issues/1874#issuecomment-322026252

However, of course, it require(d) to upstream a dozen new modules and that's very time consuming. I am still "busy" working on making the new layout system support for your `master_fill_policy` use case better. After that, I will finish the popup PR and then work on the 4.3 release (with or without finishing my keygrabber PR, but that's taking too much time, 4.3 is very late).

**Comment by Elv13** [comment]
This can now be mitigated with code in `rc.lua`. I will close this as resolved. The new way to add rules to notification will arrive soon and will be a better solution. But this bug is technically fixed.
