### ISSUE TITLE
Menubar doesn't open terminal apps correctly

### ISSUE THREAD

**Issue by gsaga** [awesomeWM/awesome#2240]
Output of `awesome --version`:
    awesome v4.2-289-g98e59225-dirty (Human after all)
     • Compiled against Lua 5.1.4 (running with LuaJIT 2.0.5)
     • D-Bus support: ✔
     • execinfo support: ✔
     • xcb-randr version: 1.6
     • LGI version: 0.9.2

**How to reproduce the issue:**
Try to open any app with `Terminal = true` in its desktop file through menubar.(htop,vim,nvim,ranger,mc)

**Actual result:**
App doesn't open

**Expected result:**
App should open in a terminal 

The reason being an erroneous conditional in `menubar.utils.parse_desktop_file`.

[This](https://github.com/awesomeWM/awesome/pull/2239) pull request fixes the problem.

**Comment by Elv13** [comment]
Merged
