### ISSUE TITLE
Documentation missing "property::" signal for wibox.widget.slider

### ISSUE THREAD

**Issue by Aire-One** [awesomeWM/awesome#2243]
**Output of `awesome --version`:**
awesome compiled from git master branch.
```
awesome v4.2-291-gd9cc5653 (Human after all)
 • Compiled against Lua 5.3.4 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
```

**How to reproduce the issue:**
Read the documentation available online at [https://awesomewm.org/apidoc/](https://awesomewm.org/apidoc/).

**Actual result:**
Documentation about `wibox.widget.*` misses "property::" signals.

**Expected result:**
Signals should be mentioned. Either, in the "signals" section or in the "Object properties" section.

# More details on the issue

Ok so, because it's not an issue about Awesome itself and my report is probably unclear, I'll add some more explanations:
I was working with `wibox.widget.slider` and I wanted to get the value of the slider while the user moves it. The documentation at [https://awesomewm.org/apidoc/classes/wibox.widget.slider.html](https://awesomewm.org/apidoc/classes/wibox.widget.slider.html) does not refer any signal relative to that use case.
So I forked Awesome to implement my own and while digging the code, I found out that the method `set_value` already call a signal [at line 239](https://github.com/awesomeWM/awesome/blob/master/lib/wibox/widget/slider.lua#L239).
This signal should be part of the documentation. Either in the "signal" section or in the "Object properties" section like [awful.wibar.border_color](https://awesomewm.org/apidoc/classes/awful.wibar.html#awful.wibar.border_color) does.

I didn't take the time to look at other widgets but I wouldn't be surprised if this issue is present for other properties though.

# A quick idea passing by

BTW, The signal only give the current "slider" instance. Wouldn't it be more easy if the signal sends also the value ? You could use the callback `function (sender, value)` for the `connect_signal` method.

I tried to setup a quick test with the following code :
```lua
local wSlider = wibox.widget {
    widget = wibox.widget.slider,
    bar_height = 3,
    handle_shape = gears.shape.circle,
    handle_border_width = 1,
    minimum = 0,
    maximun = 100,
    value = 50
}

wSlider:connect_signal('property::value', function (s, v) print(s, v, s.value) end)

local w = wibox ({
    ontop = true,
    visible = true,
    opacity = 1,
    x = 50,
    y = 50,
    width = 100,
    height = 100
})

w:setup {
    layout = wibox.layout.fixed.horizontal,
    wSlider
}
```

With the current code from git master, I get the following output (second value is `null`):
```
wibox.widget.slider (wibox.widget.slider (table: 0x5598e2630450))	nil	54
wibox.widget.slider (wibox.widget.slider (table: 0x5598e2630450))	nil	55
wibox.widget.slider (wibox.widget.slider (table: 0x5598e2630450))	nil	56
```
If the `emit_signal` call from the slider passes the value as a parameter, the output could be:
```
wibox.widget.slider (wibox.widget.slider (table: 0x55e2ebc635e0))	54	54
wibox.widget.slider (wibox.widget.slider (table: 0x55e2ebc635e0))	55	55
wibox.widget.slider (wibox.widget.slider (table: 0x55e2ebc635e0))	56	56
```
To get that output, I changed the line 239 in `lib/wibox/widget/slider.lua` by:
```lua
self:emit_signal( "property::value", value)
```

**Comment by psychon** [comment]
@Elv13 Comments? I have to admit that I am not quite sure about how this documentation stuff is supposed to look. `grep` finds some occurrences of `@signal` in the code base, but only few of them.

For the "emit the value as argument" suggestion: I see that this might make sense, but, if I remember correctly, we have some places where the signal gets the old value as argument (client's `property::screen`?). This might lead to confusion later on.

**Comment by Elv13** [comment]
Having a `@signal` documentation for each section would double the size of doc for each modules. This is counterproductive since it provides almost no value. However the current alternative is far from good. Some properties have:

```
--
-- **Signal:**
--
-- * *property::index*
```

style comments in their doc. However 90% of them are missing. The fact that some properties have signals and some others don't should be treated as a bug. Those with automatic getters and setters get them for "free", but all manually implemented accessors need to manually emit the signal and most don't.

The "solution" is probably to just copy paste the signal doc in each properties and make sure they all exist (lots of busted tests...)

**Comment by Aire-One** [comment]
I started working on this based on your feedback. I only write documentation for the slider's value property for testing purpose and see what you think.

You can find my modification at [https://github.com/Aire-One/awesome/commit/030333aca9fde6f9b8df7a825df5d8504ec31098](https://github.com/Aire-One/awesome/commit/030333aca9fde6f9b8df7a825df5d8504ec31098).
And here is how it looks like: 
![screenshot_documentation_signal_slider_property:value](https://user-images.githubusercontent.com/6602958/39095684-bf68f32e-4644-11e8-82df-7bac69873171.png)

I also tried to implement a test with busted. I would like to have some feedback on that. The code can be found here: [https://github.com/Aire-One/awesome/blob/796d80bded8f040a22e4cfbe9f18f15cd2a731a4/spec/wibox/widget/slider_spec.lua](https://github.com/Aire-One/awesome/blob/796d80bded8f040a22e4cfbe9f18f15cd2a731a4/spec/wibox/widget/slider_spec.lua).

NOTE: All my work is done in a branch from my fork of awesome. You can find it here [https://github.com/Aire-One/awesome/tree/fix_widget_slider_doc](https://github.com/Aire-One/awesome/tree/fix_widget_slider_doc)

**Comment by Elv13** [comment]
Thanks! This kind of contribution is greatly appreciated. Looking forward to a PR for your work.

**Comment by Aire-One** [comment]
PR on the road  #2249  :)
