### ISSUE TITLE
Add support for multi-pointer X

### ISSUE THREAD

**Issue by stormj** [awesomeWM/awesome#225]
It would be great if you were able to use multiple cursors in Awesome. Right now, it's possible to have two cursors, but you can click with just one. See [this link](https://wiki.archlinux.org/index.php/Multi-pointer_X)

**Comment by Elv13** [comment]
The Awesome API is based on the fact that there is only one focused client and one pointer. MPX is a cool trick, but it seem rather useless. I don't think it is reasonable to implement MPX given the time it would take.

**Comment by stormj** [comment]
All right, too bad then. Should I close the issue?

**Comment by Elv13** [comment]
I guess this one is effectively a `wontfix`, sorry about that
