### ISSUE TITLE
Has easy_async_with_shell got deprecated?

### ISSUE THREAD

**Issue by quapka** [awesomeWM/awesome#2254]
Output of `awesome --version`:

```
qup@qub:~$ awesome --version
awesome v4.0 (Harder, Better, Faster, Stronger)
 • Compiled against Lua 5.1.5 (running with Lua 5.1)
 • D-Bus support: ✔
 • execinfo support: ✔
 • RandR 1.5 support: ✘
 • LGI version: 0.9.1

```
**How to reproduce the issue:**

Add the following inside `rc.lua`
```
awful.spawn.easy_async_with_shell('echo "hello world" | grep "world"', function(o, e, r, c)
    noop = '' 
end)
```
Restart awesome `Ctrl + Mod4 + r`

**Actual result:**

![screenshot from 2018-04-29 19-21-49](https://user-images.githubusercontent.com/4338671/39409177-9a067d88-4be2-11e8-94cf-e84a0fbd18eb.png)

**Expected result:**

Based on the [docs](https://awesomewm.org/doc/api/libraries/awful.spawn.html#easy_async_with_shell) I'd expect the function to exist in `awful.spawn` namespace. I've tried also `awful.easy_async_with_shell` and `awful.util.easy_async_with_shell`, but none of them work.

**Comment by alfunx** [comment]
`easy_async_with_shell` was [introduced in `v4.2`](https://github.com/awesomeWM/awesome/commit/547c0e4b834edd6d7ed9fa4985413c5702eb9229#diff-5e9f05df3207ebe7ffedc0fc2a164063), you're using `v4.0`.

**Comment by quapka** [comment]
Thanks a lot, my bad. I run Ubuntu 17.04. Good to know about the docs within the package, did not know about that one.
