### ISSUE TITLE
screen keyboard : how to prevent gaining focus with mouse/touchscreen

### ISSUE THREAD

**Issue by deb75** [awesomeWM/awesome#2256]
Output of `awesome --version`:

awesome v4.2 (Human after all)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2

**How to reproduce the issue:**

Install any on screen keyboard, I use cellwriter, but you can try with xvkbd, onboard, ... it is not specific

**Actual result:**

My laptop can be turned into a tablet (touchscreen), so I would love to benefit from an on screen keyboard. Nevertheless, each time I press a key, with the mouse or touchscreen, the keyboard steals the focus from the application in which I want to write, and subsequent key press do not work anymore until I touch the application itself.

**Expected result:**

I know there are many ways to prevent the keyboard from stealing the focus at startup for example.

I would need to prevent the keyboard (or any app) from gaining the focus when I do a mouse click on it or  when I tap on it through the touchscreen.

Can it be achieved ?

**Comment by psychon** [comment]
Oh, right. I forgot about that "part of magic".

Then let's try something else. Instead of marking the client is unfocusable, let's mess with the part that focuses the client when clicking on it (with mouse button 1, i.e. left mouse button).
In your `rc.lua`, find the following:
```lua
clientbuttons = gears.table.join(
    awful.button({ }, 1, function (c) client.focus = c; c:raise() end),
    awful.button({ modkey }, 1, awful.mouse.client.move),
    awful.button({ modkey }, 3, awful.mouse.client.resize))
```
Replace this with
```lua
clientbuttons = gears.table.join(
    awful.button({ }, 1, function (c)
        if c.name ~= "CellWriter" then
            client.focus = c
            c:raise()
        end
    end),
    awful.button({ modkey }, 1, awful.mouse.client.move),
    awful.button({ modkey }, 3, awful.mouse.client.resize))
```

**Comment by deb75** [comment]
It does the job,

Many thanks !

**Comment by Sinaaaa** [comment]
On the latest git from the AUR, just the 
`{ rule = { name = "Onboard" }, properties = { focusable = false } }`
is enough for this to work.

Ty [psychon] for the tremendous answer, It's so nice when duck duck travel leads to something useful.
