### ISSUE TITLE
in max mode there should be only 1 mapped window at any time

### ISSUE THREAD

**Issue by vovkav** [awesomeWM/awesome#226]
in max mode there should be only 1 mapped window at any time on screen, all others should be unmapped.

actually I am on debian jessie right now, haven't checked that on later versions.

but still, in max mode, if there is, for example, mapped chromium window in the background and it has an animated gif in active page, chromium consumes a fair share of CPU time. if it is manually unmapped - it doesn't.

**Comment by blueyed** [comment]
Good point.

Does it behave different in fullscreen mode?

> if it is manually unmapped

How do you do this?

**Comment by psychon** [comment]
X11 has a great concept called "visibility notify event". Since Chromium apparently already stops rendering on UnmapNotify events, can't it also be fixed to stop rendering when it is told not to be visible?
I'd prefer if chromium gets fixed for this.

(Side note: This does not work with a composite manager since then all windows are considered to be visible, so perhaps the chromium people don't want to fix this.)

**Comment by vovkav** [comment]
>Does it behave different in fullscreen mode?
haven't checked

>How do you do this?
with a click on a title of an already active window

**Comment by vovkav** [comment]
>X11 has a great concept called "visibility notify event". Since Chromium apparently already stops rendering on UnmapNotify events, can't it also be fixed to stop rendering when it is told not to be visible?

I don't know if it applies, but... Actually if urxvt terminal window is the active window you can see a small stripe of mapped chromium window at the bottom of the screen as urxvt doesn't take all the screen space. So, I think, technically, even in this situation chromium is right in that it tries to redraw itself and awesome is wrong.

**Comment by psychon** [comment]
Uhm, I just noticed that I didn't reply:

Disable size hints honoring if you don't want urxvt to have such a size. And anyway, seems like Chromium is (partly?) right in assuming that its content is visible. Unmapping windows in such a situation would actually change the visible result, wouldn't it?
