### ISSUE TITLE
Question about dbus and X selection

### ISSUE THREAD

**Issue by deb75** [awesomeWM/awesome#2270]
Hello,

I would like to write a small lua module to perform an action whenever the X selection (primary, secondary or clipboard) is modified.

I know how to do it with `python` : 
```
from gi.repository import Gtk, Gdk
clip = Gtk.Clipboard.get(Gdk.SELECTION_PRIMARY)
def test(*args):
    print(clip.wait_for_text())

clip.connect('owner-change',test)
Gtk.main()
```

I wonder if there is a way to do the same in lua for awesome ? Obviously, `Gdk` uses dbus signal under the hood, so it might be possible using dbus bindings for lua.

**Comment by Elv13** [comment]
Yes, but there is 2 catches. First, using GTK from `rc.lua` isn't safe. GTK can query the WM (Awesome) and wait for the answer. If the WM call GTK and GTK call the WM, it dead lock.

The second catch the the "wait_for_text" part. Waiting in `rc.lua` without well designed coroutines, will block all inputs. That may including setting the clipboard itself. So again, it will dead lock.

What you probably want is https://github.com/awesomeWM/awesome/pull/1578

**Comment by deb75** [comment]
Hi,

Thanks very much for your answeer.

Currently, I tested this : 
```
local capi =
   {
    selection = selection
   }

local selection = capi.selection("PRIMARY")

if selection then
   print(selection)
end
```

which works with awesome v4.2

I guess the following : 
```
selection("CLIPBOARD"):connect_signal("selection_changed", function() print("clipboard changed") end)
```
is not currently in my awesome version. `selection` in my working test is just a string.

So I just lack a signal to connect to. But I can't figure out what is under the hood of
```
clip.connect('owner-change',test)
```

**Comment by Elv13** [comment]
The pull request I linked above is not merged. You need to patch Awesome to use it

(or you can use an external program then use `awesome-client` to notify awesome)

**Comment by deb75** [comment]
Hi,

Following your patch, I figured out that this : 
```
local lgi = require("lgi")

local Gdk = lgi.Gdk
local Gtk = lgi.Gtk
local GLib = lgi.GLib

local clipboard = Gtk.Clipboard.get(Gdk.SELECTION_PRIMARY)
print(clipboard:wait_for_text())
```

is also working, but `clipboard` has not method called `connect`. In the Gobject documentation, I can see that this latest method is inheriited by the Clipboard object from the Signal objects.

Is there any reason why the Clipboard Gobject is not fully exported to lua (as it is to python) ?

**Comment by psychon** [comment]
For `g_object_connect`, please take a look at the LGI documentation: https://github.com/pavouk/lgi/blob/master/docs/guide.md#34-signals
