### ISSUE TITLE
Configure critical notifications

### ISSUE THREAD

**Issue by alfunx** [awesomeWM/awesome#2271]
Output of `awesome --version`:

awesome v4.2-311-g4e17cc6b (Human after all)
 • Compiled against Lua 5.3.4 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2

**How to reproduce the issue:**

After overriding `naughty.config.presets.critical` [in the config](https://github.com/alfunx/.dotfiles/blob/master/.config/awesome/themes/blackout/theme.lua#L256-L263), send critical notification with `naughty.notify` and through dbus, e.g. with `notify-send` (from `libnotify`).

**Actual result:**

![screenshot](https://i.imgur.com/54C8tKB.png)

**Expected result:**

I'd say it would be nice if this were configurable. The current configuration feels like monkey patching, though should work that way, at least according to the [docs](https://awesomewm.org/apidoc/libraries/naughty.html#config.presets). Any ideas on how to fix that?

**Comment by alfunx** [comment]
Oh right I forgot about that, I think you guys mentioned it in one of my pull requests before.

That looks great. I will try and test it, and see if I'll be able to complete some of the issues. Thanks!

**Comment by Elv13** [comment]
I just merged a few commits and taken the opportunity to rebase by branch. It's not perfect and the doc is not 100% up to my standards, but it's good enough for using it

https://elv13.github.io/classes/naughty.widget.box.html
https://elv13.github.io/classes/naughty.notification.html

My notification style:

```
naughty.disconnect_signal("request::display", naughty.default_notification_handler)

naughty.connect_signal("request::display", function(n)
    local w = naughty.widget.box {
        notification    = n,
        shape           = gears.shape.rounded_bar,
        border_width    = 2,
        placement       = awful.placement.top,
        offset          = 20,
        widget_template = {
            {
                {
                    naughty.widget.icon {notification = n},
                    {
                        naughty.widget.title   {notification = n},
                        naughty.widget.message {notification = n},
                        layout = wibox.layout.fixed.vertical
                    },
                    fill_space = true,
                    layout     = wibox.layout.fixed.horizontal
                },
                naughty.widget.actionlist {notification = n},
                spacing_widget = {
                    forced_height = 10,
                    span_ratio    = 0.9,
                    color = "#ff0000",
                    widget        = wibox.widget.separator
                },
                spacing = 10,
                layout  = wibox.layout.fixed.vertical
            },
            left    = 20,
            right   = 20,
            top     = 5,
            widget  = wibox.container.margin
        },
    }
end)
```

The branch name is `doc_tests_and_notif` (in my fork) and contains 10k lines of unfinished things. Among those is the notification system rewrite.

**Comment by Elv13** [comment]
The rules API for notification will be a better solution, but this is technically now fixed. This assume the code to actually hook into the notification API is added manually to `rc.lua`. The rule will make integrating this a lot easier.

**Comment by mathieufrh** [comment]
I can't manage to get it working. I have the exact same problem. The notification from the widgets inside my awesome wm configuration is configured via naughty presets. But when using notify-send, notifications does not look the same as when using awesome-client.
Can someone help please ?

**Comment by Elv13** [comment]
@mathieufrh Have you tried with AwesomeWM git-master version? Did you try to enable the new API?

(enabling the new API can be done with this code. It will auto-disable the legacy popups)

```lua
naughty.connect_signal("request::display", function(n)
      
      naughty.layout.box { notification = n }
end)
```

Note that with the new API, you can theme everything explicitly too and bypass the presets (which I will deprecate soon in favor of an `awful.rules` like API).

**Comment by mathieufrh** [comment]
@Elv13 It's ok. I've tried with the git-master build and it's working fine. I haven't manage to set the critical preset for notifications (using notify-send -u critical ... send notification with the same style as normal norifications). But at least it's consistent now. Encore merci :-)
