### ISSUE TITLE
[tasklist] Text padding theme variables / text transformation closure

### ISSUE THREAD

**Issue by saksmt** [awesomeWM/awesome#2274]
Currently awesome lacks a way to customize paddings at all, with tasklist it brings the biggest amount of pain. Consider following line in theme:
```lua
theme.tasklist_shape = function (cr, w, h)
    gears.shape.powerline(cr, w, h, 40)
end
```
Or any other shape which behaves in a way reducing text area and we get something like this:
![2018-05-28-211652_993x30_scrot](https://user-images.githubusercontent.com/3481977/40625747-f53f646c-62bc-11e8-8ac0-ce2dfb1a370e.png)

It could be fixed either by padding or by some text transformation function which at least could padd text with spaces.

P.S. Maybe I missed something and it is possible, if so - tell me I'm an idiot and throw a link at me.

Output of `awesome --version`:

```
awesome 4.2 (Human after all)
 • Compiled against Lua 5.2.3 (running with Lua 5.2)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.5
 • LGI version: [string "return require('lgi.version')"]:1: module 'lgi.version' not found:
	no field package.preload['lgi.version']
	no file '/usr/share/lua/5.2/lgi/version.lua'
	no file '/usr/share/lua/5.2/lgi/version/init.lua'
	no file '/usr/lib/lua/5.2/lgi/version.lua'
	no file '/usr/lib/lua/5.2/lgi/version/init.lua'
	no file './lgi/version.lua'
	no file '/usr/lib/lua/5.2/lgi/version.so'
	no file '/usr/lib/lua/5.2/loadall.so'
	no file './lgi/version.so'
	no file '/usr/lib/lua/5.2/lgi.so'
	no file '/usr/lib/lua/5.2/loadall.so'
	no file './lgi.so'
```
(Just ignore that lgi is not found, it works perfectly - Nix loves such stuff)

**Comment by saksmt** [comment]
Also aligning is not an option since it, hm, centers stuff which is not desirable behavior and it won't help if text takes up all place

**Comment by Elv13** [comment]
It is done in git-master, see https://awesomewm.org/apidoc/classes/awful.widget.tasklist.html#
