### ISSUE TITLE
What properties can a tag have?

### ISSUE THREAD

**Issue by Darksonn** [awesomeWM/awesome#228]
According to the [documentation](http://awesome.naquadah.org/doc/api/modules/awful.tag.html#add) for `awful.tag.add`, the parameter `props` is a table containing some properties.

What properties can we set using this table?

I suggest information is added to the documentation, explaining what properties are available, what their accepted values are and what they do.

**Comment by Elv13** [comment]
Hello,

You can get some in this documentation https://github.com/Elv13/tyrannical

watch out, some are specific to Tyrannical and external module can add their own, so there is no "fix" set of all attributes. It all depends on the modules you use.

**Comment by Darksonn** [comment]
Okay, I still think the documentation would be incomplete without a list of the tags available by default.

**Comment by psychon** [comment]
Hm. What's the point of having both `tag.add` and `tag.new`? Can't we remove one of them?
`add()` was added in 2f3f84c994a612747411c1a55c239d98c4c62f27, but the commit doesn't really explain why.

I propose to remove `add()`. If some properties should be set, then the public API for that (e.g. `awful.tag.setmwfact`) should be used. As this issue shows, providing a table for the properties is confusing.

**Comment by Elv13** [comment]
They don't do the same thing, and `.add` is the right one to use, `.new` is the one that should be removed (if any). `.add` was added to enable dynamic tagging. `.new` is designed to add multiple tags at once with the same property set. This is really not what you want in an dynamic tagging scenario. `.new` is just a wrapper around `.add` for static use case.

I don't think it is confusing at all, it really is a very powerful way to add tags with some properties. If `awful.tag` doesn't support the property, some extra modules like Tyrannical can catch it and handle it. Removing that is a big -1 from me

**Comment by psychon** [comment]
So... should we instead go with "The property argument is provided for advanced users who need properties set via `awful.tag.setproperty` immediately when the tag is created. Normally this isn't needed."? And yes, this is a bad wording, but as this issue shows the current documentation isn't good enough. I see the options "document all properties" (which I don't really like, the wrappers like `setmwfact` should be used) or "make it clear that this argument isn't really needed".

**Comment by psychon** [comment]
Is this fixed by http://awesomewm.github.io/apidoc/classes/tag.html#Object_properties ?

**Comment by Elv13** [comment]
Yes, it is fixed
