### ISSUE TITLE
awesome-client usability

### ISSUE THREAD

**Issue by TatriX** [awesomeWM/awesome#2295]
`awesome-client` is quite inconvenient and has documentation missing.
It can't  default repl experience.
For example to actually `print` anything more complex that `2+2` I have to do the following:
```
awful = require("awful")
d = require("gears.debug")
return d.dump_return(awful.client.visible())
```

Maybe I'm doing something obviously wrong, but I can't find any information about repl usage.

It would be nice to have some documentation about `awesome-client` usage for debugging purposes.
 Thank you!

**Comment by actionless** [comment]
i think this discussion is related: https://github.com/awesomeWM/awesome/issues/1166

**Comment by blueyed** [comment]
Thanks for the reference, @actionless - let's close this as a duplicate.
