### ISSUE TITLE
Compiler warning on current master

### ISSUE THREAD

**Issue by psychon** [awesomeWM/awesome#2309]
Commit 7e17bcd026a39403f8da81172826faca75df2efb introduced the following warning:
```
[  3%] Building C object CMakeFiles/awesome.dir/objects/client.c.o
/home/psychon/awesome/build/objects/client.c:938:5: Warnung: kein vorheriger Prototyp für »client_set_startup_id« [-Wmissing-prototypes]
     client_set_##prop(lua_State *L, int cidx, char *value) \
     ^
/home/psychon/awesome/build/objects/client.c:956:1: Anmerkung: bei Substitution des Makros »DO_CLIENT_SET_STRING_PROPERTY2«
 DO_CLIENT_SET_STRING_PROPERTY2(startup_id, startup_id)
 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
I tried to get this error in English, but setting `LC_ALL=C` did not help, so... "no previous prototype for `client_set_startup_id`" is what the message say.

(Now that I looked at the commit again: Why `DO_CLIENT_SET_STRING_PROPERTY2(startup_id, startup_id)` instead of `DO_CLIENT_SET_STRING_PROPERTY(startup_id)`?)

(Should we build with `-Werror` in Travis?)

**Comment by blueyed** [comment]
> Should we build with -Werror in Travis?

Yes, for one of the build jobs I'd say.
