### ISSUE TITLE
How to bind hotkey to make a Screenshot

### ISSUE THREAD

**Issue by amiralkizaru** [awesomeWM/awesome#2326]
Output of `awesome --version`:

awesome v4.2 (Human after all)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2

**How to reproduce the issue:**

I want to know how to add a hotkey for screenshot in awesome , there's no screen shot layouts which is unfortunate

**Comment by actionless** [comment]
what is screenshot layout?

**Comment by amiralkizaru** [comment]
@actionless keyboard shortcut to screenshot

**Comment by actionless** [comment]
just use `scrot` or any other screenshot utility and bind spawning (`awful.spawn.spawn`) that command to any key

**Comment by psychon** [comment]
For your command: You need `awful.spawn("scrot")` instead of `awful.spawn(scrot)`.

But it might be better to try this:
```
awful.key({ modkey  , "Shift" }, "p", function ()
    awful.spawn({"scrot", "%Y-%m-%d_$wx$h.png", "-e", "mv $f ~/shots/'")
end, {description = "take screenshot", group = "launcher"})
```
(This command is just the example from the scrot man page)

Do you actually have scrot installed? Does scrot work when you run it in a terminal?

**Comment by amiralkizaru** [comment]
@psychon In my command I had set a variable 
scrot = "scrot" 
and your command didn't work also x)
I'll try this
