### ISSUE TITLE
Unused icon_theme with default theme

### ISSUE THREAD

**Issue by blueyed** [awesomeWM/awesome#233]
In the default theme there's this ([source](https://github.com/awesomeWM/awesome/blob/3618d95b11e4b01c95eae87d1c2f0137eb9059af/themes/default/theme.lua.in#L94-96)):

    -- Define the icon theme for application icons. If not set then the icons 
    -- from /usr/share/icons and /usr/share/icons/hicolor will be used.
    theme.icon_theme = nil

This would be a good place to default to the user's GTK theme (e.g. via querying xsettingsd), but it does not appear to be used (anymore?)?!

**Comment by psychon** [comment]
Should this be used in `menubar.icon_theme`'s `get_default_icon_theme_name()`? Oh, wait, `icon_theme.new()` already uses this.
According to `git log -p -S icon_theme`, this was introduced in 60cf963bce1ee3e94d2d2f3dfcf0d69b7ee01011. In fact, that command only lists 5 commits. Oh and `menubar.utils.get_icon_lookup_path` still uses this variable.

So.... can this be closed?

**Comment by psychon** [comment]
No answer, so I guess "yes"
