### ISSUE TITLE
Keyboard's layout switch -- drops out

### ISSUE THREAD

**Issue by Nikolice** [awesomeWM/awesome#2330]
**Output of `awesome --version`:**
> awesome v4.2 (Human after all)
>  • Compiled against: Lua 5.3.4 (running with: Lua 5.3)
>  • D-Bus support: ✔
>  • execinfo support: ✔
>  • xcb-randr version: 1.5
>  • LGI version: 0.9.2

**How to reproduce the issue:**

1. Install an "Arch Linux" based OS (with an "AwesomeWM" chosen), -- by a "Manjaro-Architect" ISO, from a USB-disk;
2. Boot it up;
3. Through a main GUI-menu, in "Keyboard" settings:
3.1. Select some layouts, for multi-lingual support: 
3.1.1. Russian, 
3.1.2. Belarussian (1 normal + 1 latin), 
3.1.3. UK English;
3.2. Select [ALT+SHIFT] -- for switching;
4. Use the OS, for some time: 
4.1. Switching -- works normal;
4.2. ???
5. See: no reaction -- to [ALT+SHIFT] pressings, from the system.

**Actual result:**
A work-around:
1. Having no support, -- I need to go to the "Keyboard" (menu link: to a layout switcher settings page);
2. There -- I press the button, on which -- the [ALT+SHIFT] is selected;
3. I select another key combination. Not doing this -- has no result;
4. Then, -- select [ALT+SHIFT] again;
5. And -- voi la: [ALT+SHIFT] -- works, again.

But I -- now would like to try another distro: "GoboLinux" (due to their choice -- to use the "AwesomeWM" for default).

**Expected result:**

Maybe the problem is within some variables, amongst the system?
Maybe, this -- is not an "AwesomeWM"s problem, but of "Manjaro" OS; I don't know.

**Comment by Nikolice** [comment]
One file: `ma-launcher.desktop`
```
[Desktop Entry]
Type=Application
Name=ma-launcher
Comment=create Manjaro-Architect launcher
Exec=/usr/bin/ma-launcher
```

**Comment by Elv13** [comment]
Then if your `rc.lua` doesn't have a special "Mod1+Shift" keybindings, you will have to digg and figure out how the layout switching daemon is called and run it. This isn't an AwesomeWM issue.

**Comment by Nikolice** [comment]
Sorry, for mentioning this not, before: I don't know, what installer I was using. It had text interface, and it was coloured... Screen-shots of Calamaro -- are not similar.

**Comment by Nikolice** [comment]
Maybe the reason is not selecting the layout while installing. Can't remember; possibly -- not chosen them.

**Comment by Elv13** [comment]
Anyhow, I will close this since switching keyboard is not an AwesomeWM feature (but displaying the current one is). Again, you will have to figure out how manjaro does it and make sure that process runs.

**Comment by Nikolice** [comment]
The process, which arised to manage the settings -- was some of XFCE4:
`xfce4-keyboard-settings`

**Comment by actionless** [comment]
there is also a simpler alternative `kbdd`, just add to you autostart 2 commands:

1) `   setxkbmap -layout us,ru -variant ,winkeys -option grp:caps_toggle,grp_led:caps,terminate:ctrl_alt_bksp,compose:ralt` (i guess you'll need to adjust the line for yourself a bit, in this example it's binded to caps lock)

2) `kbdd` itself


so awesome will be only showing you the keyboard layout but switching will be handled outside, also kbdd will give you per-window keyboard layouts

**Comment by actionless** [comment]
also if you're using manjaro you can install `awesome-git` or `awesome-luajit-git` from AUR to have current version of vanilla awesome (in case if they doing any weird modifications during the packaging or there is some unfixed bugs in older stable version)
