### ISSUE TITLE
JetBrains CLion (and others): Popups not adhering to application placement

### ISSUE THREAD

**Issue by jarlopez** [awesomeWM/awesome#2331]
This may come down to a configuration issue with `awesomewm`, but as a new user I don't quite know where to look for this. It's presumably an issue with CLion's Swing and `awesomewm`, and perhaps related to [a number of IntelliJ issues](https://github.com/awesomeWM/awesome/issues?utf8=%E2%9C%93&q=intellij)

--------------------------

**Output of `awesome --version`:**

```
awesome v4.0 (Harder, Better, Faster, Stronger)
 • Compiled against Lua 5.1.5 (running with Lua 5.1)
 • D-Bus support: ✔
 • execinfo support: ✔
 • RandR 1.5 support: ✔
 • LGI version: 0.9.1
```

**How to reproduce the issue:**
1. Set layout to `awful.layout.suit.floating`
1. Launch CLion 
1. Click on any of the tabs in the application's top bar

**Actual result:**

The dropdown list opens in a new window (expected), but placed in the *top-left corner* of the screen.

**Expected result:**

The dropdown list should open in a new window and be placed according to CLion's original placement.

**Comment by jarlopez** [comment]
It seems somewhat related to #2233 and connected JetBrains issues (such as https://youtrack.jetbrains.com/issue/JRE-709). The popups are opening up as new WM-managed windows rather popups within the application, presumably meaning all tiled WMs have this issue. 

I know for a fact that the same system running GNOME3 instead of awesomewm does _not_ exhibit this behavior.

**Comment by psychon** [comment]
I'm not quite sure what you mean with "dropdown list". Could you run `xprop` in a terminal, click on one of these dropdown lists, and provide the output of `xprop`? Afterwards, do the same with `xwininfo`.
Or do these dropdowns behave like a menu and close as soon as you click elsewhere?

In the latter case, can you get information from awesome's standard output? You could add the following to your rc.lua and see what it says (but this provides a bit less information than `xprop`):
```lua
client.connect_signal("manage", function(c)
    require("gears.debug").dump{ name = c.name, size_hints = c.size_hints }
end)
```
(If the above does not say anything about these dropdowns, then these dropdowns are not managed windows, meaning they are invisible to the WM)

**Comment by jarlopez** [comment]
Switching the application's  "Boot JDK" from the pre-packaged one to my default one (OpenJDK 8) resolved this issue.

```
$ java -version
openjdk version "1.8.0_171"
OpenJDK Runtime Environment (build 1.8.0_171-8u171-b11-1~deb9u1-b11)
OpenJDK 64-Bit Server VM (build 25.171-b11, mixed mode)
```

**Comment by psychon** [comment]
Hm... Does that mean it's a bug in Java and neither in AwesomeWM nor anything from JetBrains? Should this issue be closed?

**Comment by jarlopez** [comment]
I'm not sure, to be honest. I think the issue can be closed since its solution is discussed in the two issues I referenced.
