### ISSUE TITLE
wrong PID value return from spawn

### ISSUE THREAD

**Issue by albert748** [awesomeWM/awesome#2341]
Output of `awesome --version`:

awesome v4.2 (Human after all)
 • Compiled against Lua 5.3.4 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.5
 • LGI version: 0.9.2

**How to reproduce the issue:**

the call to awful.spawn.spawn or awful.spawn.easy_async

I've only tested these two APIs, the issue may exist on  with_line_callback and easy_async_with_shell

**Actual result:**

the return value integer PID

the PID number is not correct and not exist on system.

**Expected result:**

the actual PID exist on system

**Comment by psychon** [comment]
> the PID number is not correct and not exist on system.

Can you provide some more information on this?

For example, I just did the following:
```
$ awesome-client 'return require("awful.spawn"){"sleep", "120"}'
   double 1000
   string "awesome/sleep/1056-3558-kumara_TIME2521395494"
$ ps aux | grep 1000
psychon   1000  0.0  0.0 113612   784 ?        Ss   16:48   0:00 sleep 120
```
The PID looks quite correct to me (although it did look odd at first...).

**Comment by psychon** [comment]
Sorry, but nope:
```
$ awesome-client 'return require("awful.spawn").spawn("xfce4-appfinder", false)' 
   double 3901
$ ps aux | grep 3901
psychon   3901 10.7  0.2 642568 69320 ?        Ssl  17:35   0:00 xfce4-appfinder
```
What happens when you run `xfc4-appfinder` in a terminal?
Does running `xfce4-appfinder& pid=$! ; echo $pid ; ps aux | grep $pid` work as expected for you?

**Comment by psychon** [comment]
Oh, hey, `xfce4-appfinder` does not actually exit when I close the window. Instead, it keeps running. If I run another instance of `xfce4-appfinder` later, the new process just exits and the already running process handles opening a new window.

Thus, closing since this is `xfce4-appfinder`'s doing.
