### ISSUE TITLE
Editing a lua file no longer update ldoc

### ISSUE THREAD

**Issue by Elv13** [awesomeWM/awesome#2343]
Another little regression

When I do changes in a lua file and run `make`, ldoc is not executed. I have to clear the build directory then run `cmake .. && make` for ldoc to be executed again.

**Comment by psychon** [comment]
Well... `CMakeLists.txt` defines the dependencies for running LDoc as `DEPENDS ${AWE_SRCS} ${AWE_LUA_FILES} ${AWE_MD_FILES} ${BUILD_DIR}/docs/config.ld generate-examples ${BUILD_DIR}/docs/ldoc.css`, where `AWE_LUA_FILES` is generated from `file(GLOB_RECURSE AWE_LUA_FILES ${BUILD_DIR}/lib/*.lua)`. Thus, when the copy of the lua file in `build/` is updated, then LDoc will re-run. If the copy of the lua file in `build/` is not actually updated, that's much more severe than just LDoc not being re-run.

So, I guess nothing says any more that `build/lib/foo.lua` depends on `lib/foo.lua` and is regenerated by re-running CMake. However, I have no idea what previously caused CMake to re-run and I would rather get rid of this requirement...

Also: I cannot reproduce. I just added `--foo` to the beginning of `lib/awful/init.lua` and the following `make` re-ran CMake, updated `build/lib/awful/init.lua` and re-ran LDoc. Commit is current master: 1cb8375261bfccc6f3a80f11560253877c5adb7a.

**Comment by blueyed** [comment]
Assuming this is fixed - there have been other build related changes later anyway.
@Elv13 please re-open if it is still an issue.
