### ISSUE TITLE
naugthy state suspended

### ISSUE THREAD

**Issue by osleg** [awesomeWM/awesome#235]
I was trying to make a notification suspension key bind with an icon in a wibox area.
While naughty.suspend()/resume()/toggle() works great I didn't find a way to check the state of it.
Probably I missed it, but I ended up with adding a tiny function to naughty code which exposes the state.
Made pull request here #222

**Comment by blueyed** [comment]
Closing this in favor of #222.

Sorry for not providing feedback there earlier/before.
