### ISSUE TITLE
awful.client.swap.global_bydirection to an empty screen

### ISSUE THREAD

**Issue by mrschyte** [awesomeWM/awesome#2365]
Output of `awesome --version`:

awesome v4.2 (Human after all)
 • Compiled against Lua 5.3.4 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.5
 • LGI version: 0.9.2

**How to reproduce the issue:**

I've added the following key binding to swap the current window with a window to the left.
I have a multi-monitor setup and if there are no clients on the screen to the left, the window is not moved.

```
    awful.key({ modkey, "Shift"   }, "h", function () awful.client.swap.global_bydirection("left",c)    end,
              {description = "swap with client left", group = "client"}),
```

**Actual result:**

The window is not moved.

**Expected result:**

The window should be moved to the empty screen.

The `get_screen(sel.screen) ~= get_screen(c.screen)` part in the swap.global_bydirection function seems to be false for me when trying to move the window to an empty screen. If I remove that part from the if statement, the function works fine.

The issue seems to be similar to https://github.com/awesomeWM/awesome/issues/1644

```
 215 function client.swap.global_bydirection(dir, sel)
 216     sel = sel or capi.client.focus
 217     local scr = get_screen(sel and sel.screen or screen.focused())
 218 
 219     if sel then
 220         -- move focus
 221         client.focus.global_bydirection(dir, sel)
 222         local c = capi.client.focus
 223 
 224         -- swapping inside a screen
 225         if get_screen(sel.screen) == get_screen(c.screen) and sel ~= c then
 226             c:swap(sel)
 227 
 228         -- swapping to an empty screen
 229         elseif get_screen(sel.screen) ~= get_screen(c.screen) and sel == c then
 230             sel:move_to_screen(screen.focused())
 231 
 232         -- swapping to a nonempty screen
 233         elseif get_screen(sel.screen) ~= get_screen(c.screen) and sel ~= c then
 234             sel:move_to_screen(c.screen)
 235             c:move_to_screen(scr)
 236         end
 237 
 238         screen.focus(sel.screen)
 239         sel:emit_signal("request::activate", "client.swap.global_bydirection",
 240                         {raise=false})
 241     end                                                                                                                         
 242 end
```

**Comment by Elv13** [comment]
/me boarding an airplaine, no time for long details

Try this https://github.com/elv13/collision

**Comment by psychon** [comment]
> The get_screen(sel.screen) ~= get_screen(c.screen) part in the swap.global_bydirection function seems to be false for me when trying to move the window to an empty screen. 

The full statement here is: `if get_screen(sel.screen) ~= get_screen(c.screen) and sel == c then`
that one looks obviously always false: The second part implies that the two screens on the left are also the same. Do you want to send a PR that just removes `get_screen(sel.screen) ~= get_screen(c.screen) and`?
