### ISSUE TITLE
Set window as unfocusable

### ISSUE THREAD

**Issue by osleg** [awesomeWM/awesome#237]
Was trying to find a way to set specific window un-focusable. 
For example, since the video live wallpaper doesn't play nice with compositing managers I'm using mpv as follows ` mpv --no-input-default-bindings --no-osc --fs --on-all-workspaces <filename ` which puts mpv on all workspaces in fullscreen mode and I can use on top of it with transparency enabled.
The problem rises with the window being focusable - when i switch tags or switching between open clients the video getting focus and hiding everythin under it (which is pretty obvious). Though if it would be possible to make it unfocusable it will work "perfectly" for the use I need, plus will allow the gimmick (a bit hackish though) of live video wallpaper for awesome ;)

**Comment by osleg** [comment]
`client.focus.filter (c)` is this the right method to do what I need?

**Comment by osleg** [comment]
So what did I try:
1. Adding a keybinding that calling
```
awful.key({ modkey, "Control"   }, "f",      function (c) c.focusable = false end)
```
Silently fails
2. Adding keybinding that calls
```
awful.key({ modkey, "Control"   }, "f",      function (c) awful.client.focus.filter(c) end)
````
Silently fails
3. Tinkering with rules and properties `type`, `focusable`, `dockable` - everything silently fails.

I'm out of ideas how to make client unfocusable :/

**Comment by blueyed** [comment]
`focusable` gets used by `client.focus.filter` only.
It is meant to be used as a filter, not be called directly.

You should set `focusable = false` for the client, e.g. through the rules.

And then it should get honored.  If that's not the case it's a bug.

I could imagine that `autofocus` is responsible for this (see `lib/awful/autofocus.lua.in`).
What happens if you comment / disable it in your `rc.lua`?

**Comment by osleg** [comment]
This is the rule I tried 
```
    { rule = { class = "mpv" },
          properties = { focusable = false } },

```

The client does not honors the rule, it becomes focused instantly and I can
re-focus it with mod+j later on.
I also tried to use client.focus.filter as I showed above, no success as well.

If I comment out the `require('autofocus')` part the autofocus stops working 
for all clients (as expected I guess) but the given window, mpv in my case
is still able to be focused. With above rule set.

I also found out another "bug", if I run mpv with --x11-name argument and
provide some kind of custom class name to - awesome doesn't honor this name 
but only the original, though xprop shows me 2 class name, the custom and the
original.

```
alex in ~ λ Playing: Downloads/KAAR.mp4
 (+) Video --vid=1 (vp9)
VO: [opengl] 852x480 yuv420p
alex in ~ λ xprop | grep WM_CLASS
WM_CLASS(STRING) = "mpvldb", "mpv"
```

**Comment by blueyed** [comment]
`c.focusable` is a read-only property (in Lua) currently ([code ref](https://github.com/awesomeWM/awesome/blob/master/objects/client.c#L2026-L2040)).

I've looked into making it writable and then taking precendence (see PR #239).
Can you try this?

I'm not sure if this is a good idea, but it seems to work.

`autofocus` might need to be fixed, too - by using `client.focus.filter` - but on the other hand it will only look at the history of focused clients (where a client with `c.focusable` should not get into now so easily anymore).

It's still possible to click a non-focusable client with the mouse to focus it, which I think is a good thing.

**Comment by blueyed** [comment]
@osleg 
Please also create a new issue for the WM_NAME bug, and test if it's still an issue on awesome master.

Which version are you currently using?

**Comment by osleg** [comment]
I'm currently on 3.5.6 stable from arch repo.
Will compile and install the version with #239 now and will report back

**Comment by osleg** [comment]
Tested it now. Compiled your client-set-unfocusable branch.
The focusable = false in properties works as expected, the fact that it might be focused by mouse click is pretty cool and useful, else there won't be a way to kill the window.
Though there is another error popped out, not sure if this is just an error in the branch or it is somehow related to focusable. When trying to change layout I'm getting error 
`/usr/share/awesome/lib/awful/layout/init.lua:88 attempt to perform arithmetic on a table value (local 'i')`

**Comment by osleg** [comment]
Ok, the error from post above is nothing to do with the PR as it seems. It does appear if I install from master branch as well, opening new issue for this

**Comment by blueyed** [comment]
@osleg 
Thanks for your feedback!

I've pushed another commit to the PR's branch to fix some issues with the code.
Please test this again.
