### ISSUE TITLE
How to set taglist tag width

### ISSUE THREAD

**Issue by geripgeri** [awesomeWM/awesome#2370]
Output of `awesome --version`:

awesome v4.0-253-g052cda93 (Harder, Better, Faster, Stronger)
 • Compiled against Lua 5.3.4 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.5
 • LGI version: 0.9.2

**How to reproduce the issue:**

```
s.mytaglist = awful.widget.taglist(s, awful.widget.taglist.filter.all, awful.util.taglist_buttons, {
    spacing = 15,
    shape = function(cr, width, height)
        gears.shape.powerline (cr, width, height, -10)
    end
})
```

**Actual result:**

![taglist-1](https://user-images.githubusercontent.com/5065965/44482633-35c92c00-a649-11e8-916c-705fe8ed1386.png)

The tag is too narrow, with a shape the tag name and icon collapses into the spacing of the next / previous tag.

**Expected result:**

I would like to increase the width of the tags, unfortunately  I can't find a clue in the docs.

**Comment by actionless** [comment]
and what happens if you increase the spacing?

**Comment by geripgeri** [comment]
@actionless  The spacing increases but the tag width is the same.

With `spacing = 25`

![image](https://user-images.githubusercontent.com/5065965/44484226-80e53e00-a64d-11e8-9d25-e2dd1290d811.png)

**Comment by actionless** [comment]
sorry to misinform you in my previous comment, it seems you need to use custom widget_template for your case, see this example, at the very top of the page:

file:///usr/share/doc/awesome/doc/classes/awful.widget.taglist.html

**Comment by psychon** [comment]
Does "append spaces to the name of tags" count? Dunno about how to get some extra space on the left.
Spacing is space between tags, i.e. the empty space that you see. The area for the tag entry itself is just the width of the icon and the text. The powerline arrow however needs some extra space. The reason rewrite of the taglist and tasklist widget to use some templates should make that possible, but that's not yet available in your version.

**Comment by psychon** [comment]
@actionless `widget_template` was added in commit 20c4f71e190b922db15ba5fb2c69019266335730 which is not part of the version that @geripgeri is using

**Comment by actionless** [comment]
so then spaces in tagnames could be an easy workaround :-)

**Comment by actionless** [comment]
@geripgeri or could just do some building to get this new shiny taglist: https://awesomewm.org/apidoc/classes/awful.widget.taglist.html

**Comment by geripgeri** [comment]
I would like to use it with icon only but the situation is even worse :cry: 

![image](https://user-images.githubusercontent.com/5065965/44485106-e9cdb580-a64f-11e8-918d-a136a03dd6b8.png)

@psychon I'm using this package: https://aur.archlinux.org/cgit/aur.git I'll take a look into the versioning.

@actionless Coool, I'll try it out :+1:

**Comment by actionless** [comment]
just install `awesome-git` from AUR and that's it

**Comment by geripgeri** [comment]
Yeah, I've done that but there is no update for the package.

**Comment by actionless** [comment]
mb there is something wrong with awesome-git package itself, for now try awesome-luajit-git (it works for sure, i myself using it)

i can take a look on awesome-git package in few hours

**Comment by geripgeri** [comment]
Okay Thanks

**Comment by geripgeri** [comment]
@actionless, @psychon  I upgraded to the latest version with this aur package: `awesome-luajit-git`. 
And it works like a charm! Thank you for the help!

![image](https://user-images.githubusercontent.com/5065965/44516281-f4766200-a6c4-11e8-9eeb-3171919fed1b.png)

Code:
```s.mytaglist = awful.widget.taglist {
    screen  = s,
    filter  = awful.widget.taglist.filter.all,
    style   = {
        shape = function(cr, width, height)
	   gears.shape.powerline (cr, width, height, -10)
	end
    },
    layout   = {
        spacing_widget = {
            shape = function(cr, width, height)
	       gears.shape.powerline (cr, width, height, -10)
	    end,
        },
        layout  = wibox.layout.fixed.horizontal
    },
    widget_template = {
        {
            {
                {
                    {
                        id     = 'icon_role',
                        widget = wibox.widget.imagebox,
                    },
                    widget  = wibox.container.margin,
                },
                layout = wibox.layout.fixed.horizontal,
            },
            left  = 12,
            right = 12,
            widget = wibox.container.margin
        },
        id     = 'background_role',
        widget = wibox.container.background,
    },
    buttons = awful.util.taglist_buttons
}
```
