### ISSUE TITLE
Awesome + Compton = disaster in Chrome and derivatives

### ISSUE THREAD

**Issue by Kaukov** [awesomeWM/awesome#2374]
Output of `awesome --version`:

```
awesome v4.2 (Human after all)
 • Compiled against Lua 5.3.4 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.5
 • LGI version: 0.9.2
```

**How to reproduce the issue:**

- Have Intel Graphics (I think the issue has nothing to do with a graphics driver)
- Install Compton
- Run Compton
- Open Google Chrome or any application that uses Chrome's engine
- Start scrolling
- The display output will start freezing a lot and will need some key to be pressed

**Actual result:**

A lot of programs are freezing.

**Expected result:**

Programs should act normal, have smooth performance and no tearing.

I've experimented and it doesn't happen in other WMs. It only happens with Awesome

**Comment by psychon** [comment]
Could you try running with the `--no-argb` command line option and check if that makes the issue go away?

**Comment by actionless** [comment]
i'd recommend playing with compton config

**Comment by actionless** [comment]
unredir-if-possible, paint-on-overlay, glx-*

**Comment by Kaukov** [comment]
I fiddled around with the configuration and decided to try the glx backend. Works so smooth. Thanks for reminding me to check every setting!
It's all good now, closing the issue :)
