### ISSUE TITLE
os.setlocale(os.getenv("LANG")) in lua 5.3 with LANG = pl_PL.UTF-8 cause errors

### ISSUE THREAD

**Issue by aelspire** [awesomeWM/awesome#238]
I have arch linux - and now the latest lua version is 5.3, in lua 5.2.5 the same rc.lua have worked fine...

I find that line: os.setlocale(os.getenv("LANG"))
with:
echo $LANG
pl_PL.UTF-8 
Cause a lot of errors: https://bugs.archlinux.org/task/45008?getfile=13052

it seem similar to:
https://github.com/awesomeWM/awesome/issues/75
http://comments.gmane.org/gmane.comp.window-managers.awesome/8950

I also reported this bug on archlinux bugs: https://bugs.archlinux.org/task/45008#comment135576

**Comment by blueyed** [comment]
It should be fixed in lgi, if it is the same as #75. https://github.com/pavouk/lgi/issues/97

However, it is more likely a Lua/Arch issue.
Does the code work if used in a `lua` interpreter?

**Comment by blueyed** [comment]
Here is more info: https://bbs.archlinux.org/viewtopic.php?id=197530

**Comment by blueyed** [comment]
It seems like setting the locale influences how awesome handles its object indices / magic.

**Comment by aelspire** [comment]
Removing line os.setlocale(os.getenv("LANG")) make awesome working again (but it cause that date is written in English), but it is not a problem: the problem is that it have just worked in lua 5.2.4 and not work with lua 5.3. I don't know in which version of lgi problem was fixed but now I've version lua-lgi 0.9.0-1 (before I had version 0.8.0-2) and if it was fixed, it should be fixed in newer version too, or this is new bug but it was marked closed in 1 Feb...

**Comment by psychon** [comment]
No idea what exactly is going on, but can someone confirm that the locale influences the number format? Perhaps something wants "2", but thanks to the new integer type in lua 5.3, it now gets "2.0" or "2,0" (depending on the locale) and the code barfs on the later?
Good luck finding where this might occur. All the error messages that I saw so far point at code like `screen[foo].workarea'. So perhaps someone wants to pick such a place and add `print(foo) print(screen[foo]) print(screen[foo].workarea)` before. Perhaps this is already enough to spot what the locale does?
Another random idea: Does `c.screen` print "1" or "1.0"?
And one more: Change `lua_client_get_screen` to use lua_pushinteger instead of lua_pushnumber.

This comment was inspired by reading http://www.lua.org/manual/5.3/manual.html#8

**Comment by aelspire** [comment]
print(foo) print "1.0" without setting locale and after setting locale it still print "1.0"
print(screen[foo]) and print(screen[foo].workarea) doesn't work after setting locale.
I cannot test if change lua_client_get_screen to use lua_pushinteger instead of lua_pushnumber, because I don't know where I should change it. But in my opinion this clue is right, and this change should be made because it's realy hard to imagine screen with number 1.53242...

Test from console:
$ lua
Lua 5.3.0  Copyright (C) 1994-2015 Lua.org, PUC-Rio
> a = 1
> b = 1.0
> print(a)
1
> print(b)
1.0
> os.setlocale(os.getenv("LANG"))
pl_PL.UTF-8
> print(a)
1
> print(b)
1.0

**Comment by a1lu** [comment]
same problem here. archlinux, kernel 4.0.4-1, awesome: 3.5.6 with lua 5.3.0
without os.setlang everything works.
i generated some output with naughty.notify({text=screen, title=type(screen)})
i got some 1 and some 1.0, but all have the type number.
something like capi.screen[tonumber(screen)] changed nothing

**Comment by Elv13** [comment]
can someone try to replace  `lua_pushnumber` by `lua_pushinteger` in `luaA_client_get_screen` in `objects/screen.c`

**Comment by a1lu** [comment]
screen.c is not in objects, but in the parent directory. But in this file is no luaA_client_get_screen function.
i changed pushnumber to pushinteger in luaA_screen_count
problem still exists

**Comment by Elv13** [comment]
@a1lu confirmed replacing `lua_pushnumber` solve the issue. There isn't that many of them

```
common/luaclass.h:153:        lua_pushnumber(L, (lua_class).instances);                              \
dbus.c:140:                                lua_pushnumber(L, data[i]); \
dbus.c:233:                lua_pushnumber(L, ui); \
event.c:157:    lua_pushnumber(L, ev->event_x);
event.c:158:    lua_pushnumber(L, ev->event_y);
event.c:159:    lua_pushnumber(L, ev->detail);
event.c:421:        lua_pushnumber(L, ev->event_x);
event.c:422:        lua_pushnumber(L, ev->event_y);
event.c:431:            lua_pushnumber(L, x);
event.c:432:            lua_pushnumber(L, y);
event.c:443:        lua_pushnumber(L, ev->event_x);
event.c:444:        lua_pushnumber(L, ev->event_y);
luaa.c:163:    lua_pushnumber(L, (ssize_t) mbstowcs(NULL, NONULL(cmd), 0));
luaa.h:144:    lua_pushnumber(L, geometry.x);
luaa.h:146:    lua_pushnumber(L, geometry.y);
luaa.h:148:    lua_pushnumber(L, geometry.width);
luaa.h:150:    lua_pushnumber(L, geometry.height);
mouse.c:116:            lua_pushnumber(L, screen_get_index(globalconf.focus.client->screen));
mouse.c:118:            lua_pushnumber(L, 1);
mouse.c:123:    lua_pushnumber(L, screen_get_index(screen));
mouse.c:155:    lua_pushnumber(L, x);
mouse.c:157:    lua_pushnumber(L, y);
objects/button.c:77:LUA_OBJECT_EXPORT_PROPERTY(button, button_t, button, lua_pushnumber);
objects/client.c:1743:    lua_pushnumber(L, c->titlebar[index].size);                   \
objects/client.c:1810:    lua_pushnumber(L, geometry.width);
objects/client.c:1811:    lua_pushnumber(L, geometry.height);
objects/client.c:1964:LUA_OBJECT_EXPORT_PROPERTY(client, client_t, leader_window, lua_pushnumber)
objects/client.c:1965:LUA_OBJECT_EXPORT_PROPERTY(client, client_t, group_window, lua_pushnumber)
objects/client.c:1966:LUA_OBJECT_EXPORT_PROPERTY(client, client_t, pid, lua_pushnumber)
objects/client.c:2012:    lua_pushnumber(L, screen_get_index(c->screen));
objects/client.c:2057:        lua_pushnumber(L, c->size_hints.x);
objects/client.c:2059:        lua_pushnumber(L, c->size_hints.y);
objects/client.c:2073:        lua_pushnumber(L, c->size_hints.width);
objects/client.c:2075:        lua_pushnumber(L, c->size_hints.height);
objects/client.c:2082:        lua_pushnumber(L, c->size_hints.min_width);
objects/client.c:2084:        lua_pushnumber(L, c->size_hints.min_height);
objects/client.c:2090:        lua_pushnumber(L, c->size_hints.max_width);
objects/client.c:2092:        lua_pushnumber(L, c->size_hints.max_height);
objects/client.c:2098:        lua_pushnumber(L, c->size_hints.width_inc);
objects/client.c:2100:        lua_pushnumber(L, c->size_hints.height_inc);
objects/client.c:2106:        lua_pushnumber(L, c->size_hints.min_aspect_num);
objects/client.c:2108:        lua_pushnumber(L, c->size_hints.min_aspect_den);
objects/client.c:2110:        lua_pushnumber(L, c->size_hints.max_aspect_num);
objects/client.c:2112:        lua_pushnumber(L, c->size_hints.max_aspect_den);
objects/client.c:2118:        lua_pushnumber(L, c->size_hints.base_width);
objects/client.c:2120:        lua_pushnumber(L, c->size_hints.base_height);
objects/drawin.c:363:    lua_pushnumber(L, drawin->geometry.x);
objects/drawin.c:380:    lua_pushnumber(L, drawin->geometry.y);
objects/drawin.c:400:    lua_pushnumber(L, drawin->geometry.width);
objects/drawin.c:420:    lua_pushnumber(L, drawin->geometry.height);
objects/screen.c:515:    lua_pushnumber(L, globalconf.screens.len);
objects/window.c:136:        lua_pushnumber(L, window->opacity);
objects/window.c:139:        lua_pushnumber(L, 1);
objects/window.c:458:LUA_OBJECT_EXPORT_PROPERTY(window, window_t, window, lua_pushnumber)
objects/window.c:460:LUA_OBJECT_EXPORT_PROPERTY(window, window_t, border_width, lua_pushnumber)
spawn.c:146:            lua_pushnumber(L, sn_startup_sequence_get_workspace(sequence));
spawn.c:371:    lua_pushnumber(L, pid);
strut.c:34:    lua_pushnumber(L, strut.left);
strut.c:36:    lua_pushnumber(L, strut.right);
strut.c:38:    lua_pushnumber(L, strut.top);
strut.c:40:    lua_pushnumber(L, strut.bottom);
xkb.c:147:              lua_pushnumber(L, state_notify_event->group);
```

Most (all but 1 or 2) need to be replaced, a patch is coming

**Comment by blueyed** [comment]
I've seen that @salorium has a lot for this in his master branch (https://github.com/awesomeWM/awesome/compare/awesomeWM:eb7fba2...salorium:81a4acb).

@Elv13 
IIRC you've spoken on IRC to create a PR/patch on some existing work to get this fixed.
Was it with @salorium?  Are you working on a PR in this regard?

@salorium
You should use different topic branches.  That way it would be easier to pick/merge only the relevant changes.

@psychon 
I think we should provide a new release with a fix for this, given how popular running into this appears to be currently.

**Comment by Elv13** [comment]
I will take care of this as soon as I get home @a1lu sent me a patch, but there is issues with it

**Comment by blueyed** [comment]
Cool, thanks!

**Comment by psychon** [comment]
There is a good news and a bad news. Both is "I am now working on a computer running awesome with lua 5.3".

I still don't get why the problem exists, but I can confirm that it is `c.screen` somehow now being good enough for `luaA_screen_module_index`:

    return type(client.focus.screen)
     string "number"
    return client.focus.screen
     double 1
    return screen[client.focus.screen]
     string "userdata: 0x1c44ed8"
    return os.setlocale(os.getenv("LANG"))
     string "de_DE.utf8"
    return type(client.focus.screen)
     string "number"
    return client.focus.screen
     double 1
    return screen[client.focus.screen]
    W: awesome: luaA_dofunction:78: error while running function
    stack traceback:
    	[C]: in metamethod '__index'
    	[string "return screen[client.focus.screen]"]:1: in local 'f'
    	/usr/share/awesome/lib/awful/remote.lua:25: in function </usr/share/awesome/lib/awful/remote.lua:21>
    error: [string "return screen[client.focus.screen]"]:1: bad argument #2 to '__index' (number expected, got string)

Hm... I had an idea:

    return tostring(client.focus.screen)
       string "1.0"
    return tonumber("1")
       double 1
    return tonumber("1,0")
       double 1
    return tonumber("1.0")
       [no output]
    return type(tonumber("1.0"))
       string "nil"

So The Real Problem (tm) is that `luaA_screen_module_index` calls `lua_tostring` on its argument, this implicitly turns the number into a string and thus `luaA_checkscreen` is unhappy later. This also explains why the error message talks about a string.
Perhaps `luaA_screen_module_index` should check if `lua_type` return `LUA_TSTRING` instead of just checking if `lua_tostring` fails? That'd avoid the implicit conversion.
(Oh and on why this depends on the locale: In Germany, 1.0 is 1,0, in the Unites States 1.0 is 1.0. Lua seems to handle the locale when converting string -> integer, but it ignores the locale for number -> string and instead chokes on the comma.)
