### ISSUE TITLE
Wibar ignores x and y positions when another wibar is created

### ISSUE THREAD

**Issue by elenapan** [awesomeWM/awesome#2381]
awesome v4.2-437-gd0afcaa3-dirty (Human after all)
 • Compiled against Lua 5.1.4 (running with LuaJIT 2.0.5)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2

**How to reproduce the issue:**

Starting with the default config, set the wibar's x coordinate to some number, for example, 900
```
s.mywibox = awful.wibar({ position = "top", screen = s })
s.mywibox.x = 900
```
It correctly changes the wibar's position on the screen.
![step1](https://user-images.githubusercontent.com/31134749/45090279-92334d80-b117-11e8-9922-fbe4d47db66f.png)

Create a new wibar at the bottom (but the problem is the same regardless of position)
```
s.mywibox = awful.wibar({ position = "top", screen = s })
s.mywibox.x = 900
s.mywibox2 = awful.wibar({ position = "bottom", screen = s })
```

**Actual result:**

The first wibox's x position is ignored.
![step2](https://user-images.githubusercontent.com/31134749/45090286-96f80180-b117-11e8-879a-8157bc0e878e.png)

**Expected result:**

The first wibox's x position should be 900 and not 0.
![step3](https://user-images.githubusercontent.com/31134749/45090290-9a8b8880-b117-11e8-98aa-23d1c600daca.png)

**Workaround**
Changing the x after creating the second wibar fixes the issue.
It works the same for multiple wibars (the changes to x and y should happen after all wibars are created in order to have the desired result)
```
s.mywibox = awful.wibar({ position = "top", screen = s })
s.mywibox2 = awful.wibar({ position = "bottom", screen = s })
s.mywibox.x = 900
```

**Extra Notes**
- I have not tested if other variables apart from x and y are affected.
- I noticed that I could not pass x as an argument like so:
``s.mywibox = awful.wibar({ x = 900, position = "top", screen = s }) ``
  The value was ignored. I am assuming it is related to https://github.com/awesomeWM/awesome/issues/916

**Comment by psychon** [comment]
If you want to position a bar "somewhere", use `wibox` instead of `awful.wibar`. All that `awful.wibar` does is: it takes `wibox` and adds automatic positioning and resizing (e.g. so that multiple wibars stack instead of overlap or that they are resized as needed when the resolution of the screen changes).

Thus, what you are seeing here is pretty much the expected behaviour.

> s.mywibox = awful.wibar({ x = 900, position = "top", screen = s })

What would be the meaning of "I want a a wibar that is at the top of the screen and at the same time 900 pixels away from that"?
Try this:
```
local sgeo = screen:geomery()
s.mywibox = wibox({ x = 900, screen = s, y = sgeo.y, width = sgeo.width, height = beautiful.get_font_height(nil) * 1.5 })
s.mywibox.visible = true
```

**Comment by elenapan** [comment]
Oh, that makes sense.
I assumed that the position argument would only affect the y coordinate if the value was "top" or "bottom".
Using wibox instead of wibar works as expected, thank you!
(From the code above, I had to change `` screen:geometry() `` to ``s.geometry`` to get rid of errors)
