### ISSUE TITLE
Black splash window on audacity

### ISSUE THREAD

**Issue by eliseyim** [awesomeWM/awesome#2382]
Output of `awesome --version`:

awesome v4.2 (Human after all)
 • Compiled against Lua 5.3.4 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.5
 • LGI version: 0.9.2

**How to reproduce the issue:**

As I am using Arch Linux:
1) `# pacman -S audacity`
2) `$ audacity`

**Actual result:**

Splash window is black
![_2018-09-06_18-37-12](https://user-images.githubusercontent.com/35235955/45168535-2da1ec80-b204-11e8-9f96-dd7d169286c1.png)

**Expected result:**

Splash window is audacity's logo
![h5tsljf](https://user-images.githubusercontent.com/35235955/45168578-49a58e00-b204-11e8-811a-19bfd1e07512.png)

**Comment by actionless** [comment]
https://github.com/awesomeWM/awesome/issues/2292
