### ISSUE TITLE
manipulating keys that applications receive with awesome.

### ISSUE THREAD

**Issue by aranmohyeddin** [awesomeWM/awesome#2387]
I was wondering if I can do this with awesome:
I would like:
ctrl+shift+j/k to do no operation in firefox.
ctrl+shift+c/v to work like ctrl+c/v but I want ctrl+c/v to keep their current function(copy/paste) in firefox
ctrl+w to work like ctrl+backspace (delete one word) in firefox and telegram-desktop.

Can I do any of those with awesome? can you link me to some docs/articles that would help me learn how to do it?

**Comment by actionless** [comment]
if i understood your question correct this function could be helpful for you:
https://awesomewm.org/apidoc/libraries/root.html#fake_input

**Comment by Elv13** [comment]
Closing because it has an answer and there is no follow-up
