### ISSUE TITLE
Error while merging rc.lua on s.mytaglist 

### ISSUE THREAD

**Issue by drdevnull** [awesomeWM/awesome#2394]
Output of `awesome --version`:
awesome v4.2 (Human after all)
 • Compiled against Lua 5.3.1 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.4
 • LGI version: 0.9.1

I'm merging the changes from your latest rc.lua file (from here) with my existing one...

**How to reproduce the issue:**
my rc.lua has:
s.mytaglist = awful.widget.taglist(s, awful.widget.taglist.filter.all, taglist_buttons)

your awesomerc.lua has:
    s.mytaglist = awful.widget.taglist {
        screen  = s,
        filter  = awful.widget.taglist.filter.all,
        buttons = taglist_buttons
    }

When I make the merge, it blows up, with a bunch of error messages along the lines of:

taglist.lua:27 bad argument #2 to '__index' (screen expected got table)

also:
error while running function
stack traceback:
[C]: in metamethod....
...taglist.lua:27: in upvalue 'get_screen'
...taglist.lua:411: in  'awful.widget.taglist.new'
etc. etc...
rc.lua in local func bad argumend #2, '__index' screen expected got table...

**Comment by Elv13** [comment]
You have an older version of Awesome than the one required to use this feature. This is a newer change that doesn't yet exist in your version. This API change was introduced last year, but isn't part of an official release yet. If you wish to use this feature, please upgrade to the git-master version of Awesome.

**Comment by psychon** [comment]
Uhm... what are you doing?
If you want to update your config to latest git/master, you need to be running git/master and not awesome v4.2.
Assuming that you recently updated from some older awesome version to awesome v4.2, try merging your rc.lua with the default config of awesome v4.2: https://github.com/awesomeWM/awesome/blob/v4.2/awesomerc.lua#L208
If you really want to update to the default config of git/master, you need git/master.

**Comment by drdevnull** [comment]
thanks for the message guys! I thought the github:master was also v4.2... 

is git/master stable or in dev?

**Comment by psychon** [comment]
It should be quite stable. I regularly update my desktop to whatever is master at the time.
