### ISSUE TITLE
Is there any way to detect display device connection status?

### ISSUE THREAD

**Issue by cnwangjie** [awesomeWM/awesome#2395]
Hi, I'm looking for a way to set monitors when I connect or disconnect a monitor with my laptop. I am using a Lua script to call xrandr to set multi monitors and bind a keyboard shortcut with it, but I need to press the keyboard every time when I disconnect the monitor currently. Although it looks simple enough, I usually need to leave my seat to take a meeting with my laptop. I hope to set monitors automatically when I connect or disconnect a monitor. Is it possible?

**Comment by psychon** [comment]
There is `awesome.connect_signal("screen::changed", function(output, state) end)` where `output` is, well, the name of the output, and `state` is one of `Connected`, `Disconnected`, or `Unknown`. This exists since v4.0 / commit 5d27aa812cc552a12326e8a83440ff1676960eaa.
Does that do what you want?

**Comment by psychon** [comment]
Whoops, `screen::change` without a `d` at the end:
https://awesomewm.org/doc/api/libraries/awesome.html#screen::change

**Comment by cnwangjie** [comment]
@psychon Thank you, this is exactly what I want.
