### ISSUE TITLE
Error on layout switch with awesome from master branch

### ISSUE THREAD

**Issue by osleg** [awesomeWM/awesome#240]
Compiled awesome from master.
When trying to switch layout i'm getting following error
```
/usr/share/awesome/lib/awful/layout/init.lua:88 attempt to perform arithmetic on a table value (local 'i')
```

**Comment by Elv13** [comment]
Hello osleg,

Can you reproduce this error in `Xephyr` and give us the full backtrace? This would be appreciated. If it doesn't print, you can add `print(debug.traceback())` at `/usr/share/awesome/lib/awful/layout/init.lua:88`. This will print a lot of garbage, but it should also print the backtrace when we need it.

Thanks

**Comment by osleg** [comment]
The issue is because the signature of the function is different
My awesome version
```
alex in ~ λ awesome --version
awesome v3.5.6 (For Those About To Rock)
 • Build: May  5 2015 05:45:29 for x86_64 by gcc version 5.1.0 (builduser@)
 • Compiled against Lua 5.3.0 (running with Lua 5.3)
 • D-Bus support: ✔
```
The signature of the awful/layout/inc
```
function layout.inc(layouts, i, s)
```
The signature of version from master
```
+function layout.inc(i, s, layouts)
```
The change was introduced in commit https://github.com/awesomeWM/awesome/commit/3cbdc2a79ff7230fe717ec71c0f7442043e93fd1

**Comment by Elv13** [comment]
@psychon: I know it was done on purpose, but when 3.6 will be released, this will cause a lot of confusion

Maybe we should amend the code to use `type()` to detect this and print  a deprecation warning and then restore the old behavior?

**Comment by blueyed** [comment]
> Maybe we should amend the code to use type() to detect this and print a deprecation warning and then restore the old behavior?

:+1:
Sounds like a good idea.

**Comment by psychon** [comment]
Sorry. I forgot about this issue. Hopefully https://github.com/awesomeWM/awesome/commit/5cf13dba6bd41fc0fbea66984e894b5d02fe0675 does what you want.

**Comment by psychon** [comment]
Feel free to reopen, but I think this was handled properly.
