### ISSUE TITLE
Launch series of commands asynchronously

### ISSUE THREAD

**Issue by deb75** [awesomeWM/awesome#2400]
Hi,

I have three bash commands to launch, say `cmd1`, `cmd2` and `cmd3`.

`cmd1`, `cmd2` and `cmd3` have to be launched in that order because `cmd3` depends on output from `cmd2` which in turn depends on `cmd1` output. Also, these commands do not die one after the other. `cmd1` should still be alive after `cmd3` is launched.

I tried something like this : 
```
awful.spawn.easy_async("cmd1",
                 function(stdout)
                       local var = --get from reading stdout
                       awful.spawn.easy_async({"cmd2", var},
                                                                 function(stdout)
                                                                      -- again with cmd3
                                                                 end)
                       end)
``` 

But it does not work as expected. First of all, the first callback function seems not called before `cmd1` returns, which it does not.

How could I launch asynchronously a "cascade" of commands, each one depending on the previous ?

Regards

**Comment by psychon** [comment]
What does "depends on output from" mean exactly? Why would `cmd2` exit even though `cmd1` is (possibly) not done generating output?

If you just want to forward output from one command to the next:
```lua
awful.spawn.with_shell("cmd1 | cmd2 | cmd3")
```
Well, and if you want to fetch the output of `cmd3`:
```lua
awful.spawn.easy_async({"sh", "-c", "cmd1 | cmd2 | cmd3"}, function(stdout) end)
```

**Comment by deb75** [comment]
Hi,

Thanks for your answeer.

Actually, it is not possible to pipe commands. "Depends" mean that  `cmd2` needs some variables (e.g. the DISPLAY) which are written in `cmd1` output. So, I really need to read `cmd1` output. Then, I can launch `cmd2`. This means I can only launch `cmd2` after `cmd1` has released its output. That is why I wanted the callback function in `awful.spawn.easy_async(cmd1, function(stdout) end)` to launch `cmd2` as the callback is called when `cmd1` has written its output.

**Comment by psychon** [comment]
How do you know when `cmd1` is done generating its output? Does it e.g. close its standard output? Or is there a newline at the end of the output?
If there is a newline at the end, you could use `awful.spawn.with_line_callback`. This gives you separate callbacks for each of:
- a line of output on stdout
- a line of output on stderr
- no more output can be produced (both stdout and stderr were closed)
- process exit.
So, assuming you only want the first line of output of some command and ignore the rest:
```lua
local first_line = true
awful.spawn.with_line_callback("cmd1", {
    stdout = function(line)
        if not first_line then return end
        first_line = false
        -- Do something with line
    end
})
```
(Note that `easy_async` is implemented based on the `with_line_callback`: It buffers the output and once `output_done` is called, it calls the provided callback function)

**Comment by deb75** [comment]
Thanks for your reply.

Indeed, `awful.spawn.with_line_callback` is what I need here. Thanks for the example, it is helpful.

Regards
