### ISSUE TITLE
Tray icon background is not cleared

### ISSUE THREAD

**Issue by mrschyte** [awesomeWM/awesome#2406]
Output of `awesome --version`:

awesome v4.2 (Human after all)
 • Compiled against Lua 5.3.4 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.5
 • LGI version: 0.9.2

**How to reproduce the issue:**

Start an application which changes it's tray icon. (e.g. volumeicon or nm-applet).

**Actual result:**

The background for the tray icon is not cleared. The new icon is drawn on top of the old icon which results in visual artifacts.

![2018-09-29_21 16 16](https://user-images.githubusercontent.com/8571/46249653-12a25100-c42d-11e8-813e-d1f8b2bb17cf.png)

**Expected result:**

Only the new updated icon should be displayed.

**Comment by psychon** [comment]
Did you recently update your Gtk version? Could you try with an older Gtk version? (I think 3.24 has the problem and 3.22 does not, but I am not entirely sure)

**Comment by mrschyte** [comment]
I've downgraded Gtk3 to v3.22.9 and the issue is gone.

**Comment by psychon** [comment]
@mrschyte https://gitlab.gnome.org/GNOME/gtk/issues/1280
