### ISSUE TITLE
rules doesn't honor "custom" WM_CLASS

### ISSUE THREAD

**Issue by osleg** [awesomeWM/awesome#241]
MPV have a feature where you can tell it which WM_CLASS it should expose
 if I run `mpv` with `--x11-name` argument and provide some kind of custom
class name to - awesome doesn't honor this name but only the original,
though xprop shows me 2 class name, the custom and the original.

```
alex in ~ λ mpv --x11-name Downloads/KAAR.mp4
Playing: Downloads/KAAR.mp4
 (+) Video --vid=1 (vp9)
VO: [opengl] 852x480 yuv420p
alex in ~ λ
alex in ~ λ xprop | grep WM_CLASS
WM_CLASS(STRING) = "mpvldb", "mpv"
```

**Comment by psychon** [comment]
The first entry in WM_CLASS is `c.instance`, the second one is `c.class`, so change your rule to use instance instead of class. Welcome to X11.

http://tronche.com/gui/x/icccm/sec-4.html#s-4.1.2.5

**Comment by osleg** [comment]
Hm... good to know :/
