### ISSUE TITLE
gvim is started on wrong screen (i.e. not current) in 3 monitor setup

### ISSUE THREAD

**Issue by trou** [awesomeWM/awesome#2411]
Output of `awesome --version`:
 ```
awesome v4.2-446-g3931ae37 (Human after all)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
```
**How to reproduce the issue:**

* launch `gvim`
* window appears on leftmost monitor instead of current monitor

Note that it works correctly (gvim is displayed on the current screen), when:
* the current screen is empty
* the current screen has maximized window (and I run gvim with awesome)

For example, the following does not work (vim is started on the wrong screen):
* start `termite` (or `xterm`)
* maximize it (Mod4+m)
* launch `gvim` from the terminal

*However* if I do the following, it works:
* start `termite` (or `xterm`)
* maximize it (Mod4+m)
* run `gvim` using awesome (Mod4+r)

More info:
```
$ xrandr
Screen 0: minimum 8 x 8, current 11520 x 2400, maximum 32767 x 32767
DVI-D-0 connected 3840x2400+0+0 (normal left inverted right x axis y axis) 518mm x 324mm
   1920x1200     59.95*+
   1920x1080     60.00    59.93  
   1680x1050     59.95  
   1600x1200     60.00  
   1440x900      74.98    59.89  
   1280x1024     75.02    72.00    60.02  
   1024x768      75.03    70.07    60.00  
   800x600       75.00    72.19    60.32  
   640x480       75.00    72.81    65.99    59.94  
HDMI-0 disconnected (normal left inverted right x axis y axis)
DP-0 connected primary 3840x2160+3840+0 (normal left inverted right x axis y axis) 527mm x 296mm
   3840x2160     29.98*+  30.30  
   1920x1200     59.88  
   1920x1080     60.00    60.00    59.94    50.00    23.98  
   1680x1050     59.95  
   1600x1200     60.00  
   1280x1024     75.02    60.02  
   1280x800      59.81  
   1280x720      60.00    59.94    50.00  
   1152x864      75.00  
   1024x768      75.03    60.00  
   800x600       75.00    60.32  
   720x576       50.00  
   720x480       59.94  
   640x480       75.00    59.94    59.93  
DP-1 disconnected (normal left inverted right x axis y axis)
DP-2 connected 3840x2400+7680+0 (normal left inverted right x axis y axis) 518mm x 324mm
   1920x1200     59.95*+
   1920x1080     60.00    59.94    50.00    50.00  
   1680x1050     59.95  
   1600x1200     60.00  
   1440x900      74.98    59.89  
   1280x1024     75.02    71.93    60.02  
   1280x720      60.00    59.94    50.00  
   1024x768      75.03    70.07    60.00  
   800x600       75.00    72.19    60.32  
   720x576       50.00  
   720x480       59.94  
   640x480       75.00    72.81    65.36    59.94    59.93  
DP-3 disconnected (normal left inverted right x axis y axis)
DP-4 disconnected (normal left inverted right x axis y axis)
DP-5 disconnected (normal left inverted right x axis y axis)
```

There's no special rules:
```lua
awful.rules.rules = {
    -- All clients will match this rule.
    { rule = { },
      properties = { border_width = beautiful.border_width,
                     border_color = beautiful.border_normal,
                     focus = awful.client.focus.filter,
                     raise = true,
                     keys = clientkeys,
                     buttons = clientbuttons,
                     screen = awful.screen.preferred,
                     placement = awful.placement.no_overlap+awful.placement.no_offscreen
     }
    },

    -- Floating clients.
    { rule_any = {
        instance = {
          "DTA",  -- Firefox addon DownThemAll.
          "copyq",  -- Includes session name in class.
        },
        class = {
          "Arandr",
          "Gpick",
          "Kruler",
          "MessageWin",  -- kalarm.
          "Sxiv",
          "Wpa_gui",
          "pinentry",
          "veromix",
          "xtightvncviewer"},

        name = {
          "Event Tester",  -- xev.
        },
        role = {
          "AlarmWindow",  -- Thunderbird's calendar.
          "pop-up",       -- e.g. Google Chrome's (detached) Developer Tools.
        }
      }, properties = { floating = true }},

    -- Add titlebars to normal clients and dialogs
    { rule_any = {type = { "normal", "dialog" }
      }, properties = { titlebars_enabled = false }
    },

    -- Set Firefox to always map on the tag named "2" on screen 1.
    -- { rule = { class = "Firefox" },
    --   properties = { screen = 1, tag = "2" } },
}
```

**Comment by Elv13** [comment]
I don't have it installed, but here's some debug tips. Add

    client.connect_signal("request::geometry", function(c, ctx) print(c.name, ctx, debug.traceback()) end)

and restart Awesome. Now in the logs (their location depends on your system settings), you can get an idea why it is moved there. Note that it isn't a comprehensive list of all moving and resizing, but it should be enough to detect if the client ask for it. In that case, the "ctx" variable will be "ewmh".

A less useful, but you might be lucky test may also to disable the client ability to move and resize themselves:

    client.connect_signal("request::geometry", awful.ewmh.client_geometry_requests)

**Comment by trou** [comment]
I indeed get `ewmh`:
```
Vim	ewmh	stack traceback:
	/home/trou/.config/awesome/rc.lua:591: in function </home/trou/.config/awesome/rc.lua:591>
```
and by adding the *dis*connect line:
```
client.disconnect_signal("request::geometry", awful.ewmh.client_geometry_requests)
```
it seems the gvim always pops up on the current screen.

Adding a bit more info to the log:
```lua
client.connect_signal("request::geometry", function(c, ctx, hints) print(c.name, ctx, hints.x, hints.y, hints.width, hints.height, debug.traceback()) end)
```
I get this for windows popping on the first screen:
```
Vim	ewmh	0	35	1798	729	stack traceback:
Vim	ewmh	0	0	1798	648	stack traceback:
Vim	ewmh	0	35	3590	2269	stack traceback:
```

and this for gvim popping on the current screen:
```
Vim	ewmh	3840	35	1798	729	stack traceback:
```
so I guess the bug is in vim ?

**Comment by psychon** [comment]
Uhm... what happened to those stack tracebacks? Are they all the same and thus you left them out, or what?

**Comment by psychon** [comment]
Hm, okay, then these signals come indeed from ConfigureRequest events sent by the X11 server, meaning that these are requests by gVim. No idea why gVim would move and resize itself around. Anything in `.gvimrc` or `.vimrc` that could cause this? I.e. what does `gvim -u NONE -U NONE` do?

**Comment by trou** [comment]
I've looked into gVim code and my config, and I definitely do not have any config option that influences de window geometry.
However, I've found out that `vim.gtk2` is not affected by the bug whereas `vim.gtk3` is so maybe it's a bug in GTK. I'll try to dig a bit more and report a bug where needed (vim probably).

Maybe we can close this bug ?

**Comment by psychon** [comment]
Random idea: Are you honoring size hints in your config? Anything that sets `size_hints_honor` to false?

> Maybe we can close this bug ?

Feel free, if you want

**Comment by trou** [comment]
> Random idea: Are you honoring size hints in your config? Anything that sets size_hints_honor to false?
No.

I'll close the bug and re-open it if needed. Thanks for the help !

**Comment by psychon** [comment]
> Can you suggest something?

@ChoppinBlockParty https://github.com/awesomeWM/awesome/issues/2411#issuecomment-426841730

**Comment by ChoppinBlockParty** [comment]
Thank you @psychon, actually I was missing this (seems to be new in awesome 4) properties for the rules.

    awful.rules.rules = {
        -- All clients will match this rule.
        { rule = { },
          properties = { border_width = beautiful.border_width,
                        border_color = beautiful.border_normal,
                        ....
                        screen = awful.screen.preferred,
                        placement = awful.placement.no_overlap+awful.placement.no_offscreen
          }

**Comment by Elv13** [comment]
@trou I added an incomplete pull request to add a better API to fix your issue. Right now the fix proposed here is little more than a hack. So I will re-open this as I consider the "solution" too horrible for the general public. Misbahaving clients should leak their misbehavior into making Awesome official APIs misbehave.

**Comment by joeytwiddle** [comment]
Apparently this problem can be caused by setting `lines` and/or `columns` during startup (e.g. from your `.vimrc`)

If that is the case, you can solve it by moving the settings inside an autocommand.

```
" BAD.  Do not do this.
set lines=999 columns=999

" GOOD.  Do this instead.
autocmd GUIEnter * :set lines=999 columns=999
```

https://askubuntu.com/questions/109696/gvim-always-opens-in-workspace-4
