### ISSUE TITLE
Lag while resizing

### ISSUE THREAD

**Issue by RomeuG** [awesomeWM/awesome#2414]
Output of `awesome --version`:

```awesome v4.2-446-g3931ae37 (Human after all)
 • Compiled against Lua 5.3.5 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
```

**How to reproduce the issue:**

Open a program, and resize the window to make it bigger. I am trying with Thunar and RuneLite (Runescape Client)

**Actual result:**

The window border leaves a trail.
Three examples:
Runelite - https://imgur.com/a/ozQ0uPF
Thunar - https://imgur.com/a/CKxRKJ8
Emacs - https://imgur.com/a/mOASOHf

**Expected result:**

Maybe such a big trail, in Runelites' case, shouldnt be happening?
Thunar trail is a lot smaller. Emacs leave a trail and does some kind of flickering.
Is this because of the window itself or the window manager?

**Comment by Elv13** [comment]
Some WMs use an outline to avoid repainting every resize steps. Some compositing WMs will stretch the frame until the next one is ready. Awesome isn't a compositor so it can't do that. You can use outlines if you wish. That leaves Awesome shape_clip and shape_mask that need to be re-allocated for each resize. But that should be wayyy faster then 60fps as Thunar demonstrates. The terminal acts normally. They only resize in steps the size of a character height and width, so the little flickering is actually a feature done on purpose (by the terminal, not Awesome) and not a bug.

As for RuneScape, if it's still Java then blame Java, not Awesome. I am sorry, but there is nothing to do here beside complaining to Oracle and waiting for an answer until the Sun explodes (pun intended) and the Earth is roasted to a crisp. It will happen before Oracle fix this bug. Don't bother submitting a patch to them either, it will be ignored.

**Comment by RomeuG** [comment]
Thank you. I had no clue if the problem was the WM or the program itself.

**Comment by Elv13** [comment]
No problem
