### ISSUE TITLE
Compiler warning in awesome.c

### ISSUE THREAD

**Issue by actionless** [awesomeWM/awesome#2418]
```
[  3%] Building C object CMakeFiles/awesome.dir/awesome.c.o
/home/user/.cache/pikaur/build/awesome-luajit-git/src/build/awesome.c: In function ‘signal_child’:
/home/user/.cache/pikaur/build/awesome-luajit-git/src/build/awesome.c:465:9: warning: unused variable ‘res’ [-Wun
used-variable]
     int res = write(sigchld_pipe[1], " ", 1);
         ^~~
```

**Comment by psychon** [comment]
Hrm. I guess you are building in release mode (instead of the usual debug mode), so `NDEBUG` is defined and `assert` doesn't do anything. For reference, this is the full function:
```c
static void
signal_child(int signum)
{
    assert(signum == SIGCHLD);
    int res = write(sigchld_pipe[1], " ", 1);
    assert(res == 1);
}
```
Ideas what to do about this? Just remove the `assert`?

**Comment by blueyed** [comment]
I am also seeing this (`-DCMAKE_BUILD_TYPE=RELEASE` via the Arch PKGBUILD).
Some suggestions are mentioned on https://stackoverflow.com/questions/5626429/assert-and-unused-local-variable-warning-in-gcc-dont-mix-well (macro or attributes).
But we could also just check this normally and print an error if it failed.

**Comment by psychon** [comment]
Sounds like we have to add a cast to `void`.

**Comment by blueyed** [comment]
This works for me:
```diff
diff --git c/awesome.c i/awesome.c
index 73ecb2787..e711cf70a 100644
--- c/awesome.c
+++ i/awesome.c
@@ -463,6 +463,7 @@ signal_child(int signum)
 {
     assert(signum == SIGCHLD);
     int res = write(sigchld_pipe[1], " ", 1);
+    (void) res;
     assert(res == 1);
 }
```
