### ISSUE TITLE
awful.spawn stop working

### ISSUE THREAD

**Issue by ChoppinBlockParty** [awesomeWM/awesome#2428]
awesome v4.2-473-g7020a97 (Human after all)
 • Compiled against Lua 5.2.4 (running with Lua 5.2)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
• LGI version: 0.9.0

I have some simple global key bindings to spawn processes:

    awful.key({ modkey,           }, "Return", function () awful.spawn(terminal) end),
    awful.key({ modkey,           }, ",",    function () awful.spawn("setsid emacs") end),

It works, but after some time it does not: it just does nothing when the keys are pressed. I have to `awesome.restart` and that it works again. Using awesome 3.5 I was using `awful.util.spawn`, should I use this one or `awful.spawn`? With a Any ideas?

**Comment by Elv13** [comment]
> Any ideas?

My best guess if that something in your config is leaking open file descriptors and you reach the maximum number of open file. After that the quota system stops allowing new files or spawn to be created. Some old versions of `vicious` had this issue.

**Comment by psychon** [comment]
Anything on standard error? `lsof -c awesome` might give you a hint on where that output goes to (you are looking for fd 1 or 2). In my case, this is `~/.xsession-errors`.
Also, what is awesome's memory usage at this point? Could it be that `fork` failed? If so... uhm, there could be an error that is returned.

What does running `awesome-client 'require("naughty").notify{ text = require("awful.spawn")(terminal) }` show/produce?

**Comment by ChoppinBlockParty** [comment]
Thx. Close, please, I am using dwm now.
