### ISSUE TITLE
Way for tag change to bring client under mouse into focus / mouse.object_under_pointer or signal issue?

### ISSUE THREAD

**Issue by Sorky** [awesomeWM/awesome#2433]
Environment:

    awesome v4.2 (Human after all)
     • Compiled against Lua 5.3.3 (running with Lua 5.3)
     • D-Bus support: ✔
     • execinfo support: ✔
     • xcb-randr version: 1.5
     • LGI version: 0.9.2

Aim:

    When changing tabs, sometimes the mouse is over a client but a different client has the focus
    Change this to have the client under the mouse be in focus

Reproduce...

    Tab 1 has 2 clients tiled left & right - Tab 2 has 1 client fullscreen  
    Mouse over Left client in Tab 1 (has focus)
    Change to Tab 2 (mod-2)
    Cursor to right hand side of display
    Change back to Tab 1 (mod-1)
    Left client has focus but mouse is over Right client
        Preferred behavior would be to have the Right client gain focus

Attempted change: = Mouse issue???

    Try to fix by interrogating the mouse (On change of tabs, catch a signal)

    Signal catch eg: client-focus or screen-tab-history-update
    local n = mouse.object_under_pointer()

        n will be the client that was in focus on the tab you came from (Not what I wanted)
            Preferred would be for n to be the client that is under the mouse AFTER the move

    Presumption is that the new tab & client is actually being displayed?

Dodgy work-around:

    Call mouse.object_under_pointer() after a delay (so it sees the desired client)

        gears.timer( {  timeout = 0.1,
                                autostart = true,
                                single_shot = true,
                                callback =  function()
                                                    local n = mouse.object_under_pointer()
                                                        if n ~= nil and n ~= client.focus then
                                                            client.focus = n end
                                                        end
                          } )

Possible resolution:

    Tell me I'm using the wrong signal and close issue after advising the correct one

Alternative resolutions:

    Add signals that occur at the correct time to get the desired behaviour?

    Fix the mouse return value?

    Other?

**Comment by Elv13** [comment]
(untested)

You need to add a [focus filter](https://awesomewm.org/apidoc/libraries/awful.ewmh.html#add_activate_filter) on the "autofocus.check_focus_tag" context. Block it and instead call `client.focus = mouse.current_client` (which does in the background what your workaround does).

By default awesome focus the client from the history, not the one under the mouse. It works this way because things that depend on the mouse position without the mouse actually moving make people who exclusively use the keyboard for navigation "furious".

**Comment by Sorky** [comment]
Thanks for commenting (long time since we last corresponded - I finally upgraded)

Unfortunately I'm still very confused...

Part 1 <make people who exclusively use the keyboard for navigation "furious">

Totally understand that = Changed the title a little to hopefully better represent the questions I have around my 'hack' 

Part 2 <mouse.current_client>

Doesn't seem to work (drop this in rc.lua and see for yourself) - Issue / Usage?

`function focus_client_under_mouse( s )
	gears_timer( {	timeout = 0.1, 
					autostart = true, 
					single_shot = true, 
					callback =	function()
									local n = mouse.object_under_pointer()

local c = mouse.currentclient
naughty.notify( {	preset = naughty.config.presets.critical,
					title = "focus_client_under_mouse",
					text = string.format( "%s\n%s\n%s", tostring(s), tostring(n), tostring(c) ) } )

									if n ~= client.focus then client.focus = n end
						end														} )
end
screen.connect_signal( "tag::history::update", focus_client_under_mouse )`

Part 3 <focus filter>

Something new to play with ;-)

Tried these with c1 & c2 not returning the object I'm wanting (ie: Hasn't changed tag by then?) 
`function test( c )
	c1 = mouse.current_client
	c2 = mouse.object_under_pointer()
	naughty.notify( { preset = naughty.config.presets.critical, title = "border_adjust", text = string.format( "%s\n%s\n%s", tostring(c), tostring(c1), tostring(c2)  ) } )
end
awful.ewmh.add_activate_filter(function(c) test( c ) end )
--awful.ewmh.add_activate_filter(function(c) if c ~= mouse.current_client then return false end end )`

Note: The 'false' rule ensures NO client gets focus ;-)

Part 4 <part of my original question really>

When should the mouse.whatever give the client I'm after [tag changed, clients all showing and mouse unmoved]

**Comment by actionless** [comment]
your "dodgy workaround" from the first post looks fine, i would only replace timer to timer.delayed_call

**Comment by Sorky** [comment]
Hi actionless - I thought the same thing originally but found that timer.delayed_call still had mouse.object_under_pointer() give the old client and mouse.currentclient gives nil

My whole issue seems to come down to knowing the sequence of events

**Comment by psychon** [comment]
This works for me:

Remove `require("awful.autofocus")` from your config. This is the module that tries to automatically focus something based on the focus history.

Add this somewhere to the config:
```lua
do
    local pending = false
    local glib = require("lgi").GLib
    tag.connect_signal("property::selected", function()
        if not pending then
            pending = true
            glib.idle_add(glib.PRIORITY_DEFAULT_IDLE, function()
                pending = false
                local c = mouse.current_client
                print("focusing", c, mouse.object_under_pointer())
                if c then
                    client.focus = c
                end
                return false
            end)
        end
    end)
end
```
The "magic ingredient" here is `require("lgi").GLib.idle_add`. This adds a callback for when the main loop is otherwise idle. This gets around all the "lazy updating" that awesome does. For example, `gears.timer.delayed_call` uses the `refresh` signal and this signal is emitted before the X11 server was told "make this client invisible, move this one here, etc". Thus, because `mouse.object_under_pointer()` asks the X11 server for this information, this function provides stale information whenever something was changed in the current main loop iteration.

**Comment by Sorky** [comment]
G'Day again Uli - Long time no chat as well ;-)

Now that's what I'm talking about! Dare I say AWESOME

I could have sworn there was some "lazy updating" (signal timing selection drama) going on!

Works for me even keeping 'require("awful.autofocus")' so that when the mouse isn't over something, the historical client will get focus [best of both worlds ;-) ]

**Comment by Elv13** [comment]
> awful.ewmh.add_activate_filter(function(c) test( c ) end )
> --awful.ewmh.add_activate_filter(function(c) if c ~= mouse.current_client then return false end end )`

Hi again. You need to add this filter only for the "autofocus.check_focus_tag" context. `add_activate_filter` takes a context argument. If you don't set the context then it applies to all context, which is not what you want.

**Comment by Sorky** [comment]
Thanks for your input Emmanuel,

I still found that the timing was an issue - I've stuck with Uli's piece that waits for the main loop to be idle - so far it has been reliable without my "dodgy timer"

Not sure if the whole signal timing and mouse related timing issues need further investigation, but I'm satisfied for now to highlight that care needs to be taken with mouse location functions and signals
