### ISSUE TITLE
Awesome maximizes Plasma components

### ISSUE THREAD

**Issue by RomanHargrave** [awesomeWM/awesome#2447]
Output of `awesome --version`:

```
awesome v4.2 (Human after all)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
```

**Reproduce it:**

Use base debian configuration, replace _KWin_ with _awesome_ (why? plasma is a great environment, but KWin doesn't do what I need: separate desktops (tags) on separate displays as well as good tiling)

Use a Plasma menu, such as the "hamburger" menu in the upper-right-hand corner of the Plasma Desktop backdrop.

**Actual result:**

The menu will open and occupy the entire display.

**Expected result:**

The menu will open and occupy only the required space.

**Comment by RomanHargrave** [comment]
I have to wonder if this is because the menus aren't hinting their own size.

For instance, here is xprop output from a 900x1600 (portrait) dispay - 

```
_NET_WM_DESKTOP(CARDINAL) = 9
awful.client.property.floating(CARDINAL) = 1
_NET_FRAME_EXTENTS(CARDINAL) = 0, 0, 0, 0
WM_STATE(WM_STATE):
                window state: Normal
                icon window: 0x0
_NET_WM_USER_TIME(CARDINAL) = 768294817
_KDE_NET_WM_SHADOW(CARDINAL) = 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
_KDE_NET_WM_BACKGROUND_CONTRAST_REGION(_KDE_NET_WM_BACKGROUND_CONTRAST_REGION) = 0x1, 0x0, 0x380, 0x1, 0x0, 0x1, 0x382, 0x614, 0x1, 0x615, 0x380, 0x1, 0x3dfe2535, 0xbc430fb5, 0xbc430fb5, 0x0, 0xbd240cba, 0x3dc480cf, 0xbd240cba, 0x0, 0xbb847cd3, 0xbb847cd3, 0x3e071faf, 0x0, 0x3e23d70b, 0x3e23d70b, 0x3e23d70b, 0x3f800000
_KDE_NET_WM_BLUR_BEHIND_REGION(CARDINAL) = 1, 0, 896, 1, 0, 1, 898, 1556, 1, 1557, 896, 1
_NET_WM_STATE(ATOM) = _NET_WM_STATE_SKIP_TASKBAR, _NET_WM_STATE_ABOVE
_KDE_NET_WM_DESKTOP_FILE(UTF8_STRING) = "org.kde.plasmashell"
XdndAware(ATOM) = BITMAP
WM_NAME(STRING) = 
_NET_WM_NAME(UTF8_STRING) = "Plasma"
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x2, 0x1, 0x0, 0x0, 0x0
_NET_WM_WINDOW_TYPE(ATOM) = _KDE_NET_WM_WINDOW_TYPE_OVERRIDE, _NET_WM_WINDOW_TYPE_NORMAL
_XEMBED_INFO(_XEMBED_INFO) = 0x0, 0x1
WM_CLIENT_LEADER(WINDOW): window id # 0x200000d
WM_HINTS(WM_HINTS):
                Client accepts input or input focus: True
                Initial state is Normal State.
_NET_WM_PID(CARDINAL) = 2571
_NET_WM_SYNC_REQUEST_COUNTER(CARDINAL) = 33555261
WM_CLASS(STRING) = "plasmashell", "plasmashell"
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, WM_TAKE_FOCUS, _NET_WM_PING, _NET_WM_SYNC_REQUEST
WM_NORMAL_HINTS(WM_SIZE_HINTS):
                user specified location: -217, 234
                user specified size: 898 by 1558
                window gravity: Static
```

Note that there is no `program specified size`

This resizing continues to happen despite awesome having been told explicity not to tile, resize, decorate, focus, etc.. the entire `plasmashell` class.

**Comment by psychon** [comment]
Could you add `client.connect_signal("property::geometry", function(c) local g = c:geometry() print(c, g.x, g.y, g.width, g.height, debug.traceback()) end)` to your config and see what output this produces on awesome's stdout? (`lsof -c awesome` might be able to help you in figuring out where this goes to; might be `~/.xsession-errors`)
This should dump the size of a client when it newly appears and also when something in awesome resizes it (or it resizes itself). The traceback *might* be helpful in figuring out which piece of code does the resizing.

Also, what exactly do you mean when you write the following? What did you change in your rc.lua for this?

> This resizing continues to happen despite awesome having been told explicity not to tile, resize, decorate, focus, etc.. the entire plasmashell class.

Also: Uhm, what?!?

> WM_NORMAL_HINTS(WM_SIZE_HINTS):
>                user specified location: -217, 234
>                user specified size: 898 by 1558
>                window gravity: Static

The window wants to appear offscreen? And wants to have a huge size? Do you happen to have a huge monitor so that at least the size makes sense?

**Comment by actionless** [comment]
actually the bigger problems with plasma i had when was trying to re-arrange panel, even after playing with `awful.rules` for quite a while, each popup/submenu/whatever was creating a new client with some new surprising behavior so i've just gave up :-)

sorry for sorta offtopic

**Comment by RomanHargrave** [comment]
> The window wants to appear offscreen? And wants to have a huge size? Do you happen to have a huge monitor so that at least the size makes sense?

Secondary monitor to the left of a 4K monitor. Yeah, it's janky.

**Comment by psychon** [comment]
> Secondary monitor to the left of a 4K monitor. Yeah, it's janky.

I'm quite sure that means that the secondary monitor should be at (0,0) and the 4K monitor should be at some non-zero position. Lots of stuff (even awesome) assumes that windows created at negative coordinates are not visible.

Also:

> a 900x1600 (portrait) display
> [...]
> user specified location: -217, 234
> user specified size: 898 by 1558

Let's assume the 900x1600 display were at (0,0). Then, the window would want to appear from (-217,234) up to (-217+898, 234+1558) = (681, 1792). That would still mean that a quarter of the width and about ten percent of the height would be offscreen?!? Just `awful.placement.no_offscreen` would want to change that and move it around (but would not resize it...)

Just to make sure this does not get lost: https://github.com/awesomeWM/awesome/issues/2447#issuecomment-431766973

> Could you add client.connect_signal("property::geometry", function(c) local g = c:geometry() print(c, g.x, g.y, g.width, g.height, debug.traceback()) end) to your config and see what output this produces on awesome's stdout? (lsof -c awesome might be able to help you in figuring out where this goes to; might be ~/.xsession-errors)
> This should dump the size of a client when it newly appears and also when something in awesome resizes it (or it resizes itself). The traceback might be helpful in figuring out which piece of code does the resizing.

**Comment by RomanHargrave** [comment]
> I'm quite sure that means that the secondary monitor should be at (0,0)

That is correct. I can't explain the negative coordinates.

> Just to make sure this does not get lost

I'll try that when I get home from work today. I need to see about testing the Plasma/Awesome session in Xephyr since it should make things a lot simpler to troubleshoot here.

I had considered adding a callback to fix the positioning, but I don't know that there is a correct way to determine the positioning since Plasma seems to pass all that under-the-table to KWin rather than just use standards.

**Comment by RomanHargrave** [comment]
Changing the placement certainly remedies the issue of things going strange places. I haven't seen the sizing issue, and I _have_ upgraded several times in 12 days...

**Comment by RomanHargrave** [comment]
I'm going to go ahead and close this as the original behavior (strange sizes) seizes to occur after only time having passed and no changes.

This was possibly due to a bug with KDE, but I have no definitive proof of that, it's only a guess.
