### ISSUE TITLE
Stacked notifications

### ISSUE THREAD

**Issue by kajzersoze** [awesomeWM/awesome#2455]
Any plans for this feature ?

To clarify what I mean by this, let's say there are 20 notifications with timeout 0, so they are always shown until they are clicked. Problem with this currently is that if they don't fit the screen the first ones would be gone.

So, for example `notify-send "Test" "1" -t 0` and then again but with "2" instead of "1", 
`notify-send "Test" "2" -t 0` , then "3" etc. 

Depending on the screen size, fonts etc. it could fill the screen say at "15", the one with "1" would still be visible, if then "16" comes "1" would be gone, it then "17" comes "2" would be gone etc.

Ideally, the one with "16" would not be visible and would appear only if one notification already shown would be clicked, and so on....

**Comment by kajzersoze** [comment]
Never mind, I made a queue in rc.lua and solved it via callback

It should be implemented though, all other notification engines have that.

**Comment by Elv13** [comment]
Assigning myself given I have some code for this in my eternally stuck in review PR serie to rewrite naughty.

**Comment by Elv13** [comment]
This is now possible as of 10 minutes ago.

See https://awesomewm.org/apidoc/widgets/naughty.list.notifications.html and use a filter for types, then another `naughty.list.notifications` for a list of all the types.

**Comment by actionless** [comment]
@Elv13 cool, thanks a lot!
i wanted such kind of widget like for a eternity :) (i think after i've got my first modern smartphone where it was implemented like that)
