### ISSUE TITLE
minor typo in awful.spawn documentation

### ISSUE THREAD

**Issue by tototest99** [awesomeWM/awesome#2456]
Hello, 

I was looking at [Module awful.spawn doc](https://awesomewm.org/doc/api/libraries/awful.spawn.html), isn’t it « (…) A command **is** what is used to start process(es). It has no direct relation with (…)»,

**Comment by bew** [comment]
Looks like it, you can open a PR to fix the typo if you want ;)

**Comment by actionless** [comment]
the help text is in `lib/awful/spawn.lua`, `grep` tool is usually very helpful when trying to dig into the structure of some new project

when creating a new PR you can specify `Fixes #2456` to auto-close the ticket when PR will be merged

**Comment by McSinyx** [comment]
> `grep` tool is usually very helpful when trying to dig into the structure of some new project

I just want to add that `ack` is even better with saner default option, e.g. you can `ack key-word directory/`.
