### ISSUE TITLE
why "intuitive" window switching needs hacking /usr/share/awesome/lib/awful/widget/tasklist.lua ?

### ISSUE THREAD

**Issue by xor512** [awesomeWM/awesome#2462]
I'm totally OK with modkey+ljk but, simply out of common sense, they should work in a way that:

1. First I open firefox
2. Then lxterminal
3. Then audacious
I'm focused on audacious.

Pressing modkey+j should switch to lxterminal and pressing it again to firefox again to audacios and so on...

Pressing modkey+k being in audacious should switch to firefox and tnext to lxterminal...

That seems totally understandable, useful and simple.

However it does not work like that. It doesn't matter how many window I open modkey+k moves me to the first opened. I won't even try to describe what actually modkey+j,k does since this seem following some totally random rules.

I would understand if this advice helped (that maybe sensible reason that going to left/right is impossible when new added windows became masters):

```lua
{ rule = { }, properties = { }, callback = awful.client.setslave }
```

But it doesn't. Indeed it stops opening new windows as master in tiling configurations, which may or may not be suitable for somebody but switching between windows using modkey+l,k doesn't make any sense in neither case.

And also it appears that sensible going to left/right is when new added windows became masters (or slaves) is actually possible after hacking /usr/share/awesome/lib/awful/widget/tasklist.lua:

```lua
local function tasklist_update(s, w, buttons, filter, data, style, update_function)
    local clients = {}
    for _, c in ipairs(capi.client.get()) do
        if not (c.skip_taskbar or c.hidden
            or c.type == "splash" or c.type == "dock" or c.type == "desktop")
            and filter(c, s) then
            table.insert(clients, 1, c) -- HERE IS THE FIX
        end
    end

    local function label(c, tb) return tasklist_label(c, style, tb) end

    update_function(w, buttons, label, data, clients)
end
```
No matter the setslave option this works predictably.

Following advice containing this hack in https://stackoverflow.com/questions/14537666/how-to-change-the-way-awesome-wm-add-items-to-the-tasklist, I've changed, as suggested, original 
```lua
table.insert(clients, c)
```
to 
```lua
table.insert(clients, 1, c)
```
and it started working as a charm (with or without setslave). I've also had to copy this file to ~/.config/awesome/awful/widget/ to not change original one. After that if I open 5 different windows and modkey+j goes to 4th and modkey+k to (5+1)%5 = 1. If then I'm at window opened as 3rd modkey+k will switch me to 4th and modkey+j to 2nd.

So modkey+j goes "back", modkey+k "forward". This way I can totally predict what is going on.

So:

1. Why going left/right in window history in (expecially visible in floating tags) has some random logic?
2. Why to make it sensible there is no way to do so in rc.lua?
3. If I just change where to place new clients, in the beginning or in the end shouldn't just modkey-j/k start to work in opposite directions? Well I don't see them doing so. I'm seeing no pattern at all.

Maybe this is a bug? I was really annoyed until I've googled this "solution" and applied it. Before I usually used mouse or app switcher (right click on taskbar) to switch between task. I know that you can actually open app switcher by some key binding not using mouse but what the point then in modkey+j/k? Eventually they will get you to the window you want but there is no way to guees which one of them to use and when you will lend up in the window you want.

Again after a hack with table.iinsert(clients, 1, c) modkey+j/k strarted to completely make sense and behave like going left/right where left is an "older" application" (earlier started) and right is a "younger one" (started later).

If this not a bug please at least explain this in FAQ.

**Comment by psychon** [comment]
So, first, all that your patch does (I think) is reversing the entries of the tasklist. So, instead of adding "the last" entry to the right end, it ends up being on the left end. Since the tasklist order does not influence the behaviour of `mod4+j/k`, this does not change anything in window selection, so:

> 1. Why going left/right in window history in (expecially visible in floating tags) has some random logic?

It doesn't. And since you say that with your patch it starts working like a charm, there cannot be anything random in here.

> 2. Why to make it sensible there is no way to do so in rc.lua?

I would have expected that the accepted answer from your stackoverflow link would basically do the same (the one with `setslave`). Then, one could still change the direction of `Mod4+j` and `Mod4+k` by just swapping the two key definitions in `rc.lua`.
So, I would say that this question is un-answerable since it assumes wrong premises.

> 3. If I just change where to place new clients, in the beginning or in the end shouldn't just modkey-j/k start to work in opposite directions? Well I don't see them doing so. I'm seeing no pattern at all.

Uhm... sorry that you see that. But to answer your question: Yes.

----

So, let me test this. With the default config, I open a terminal and type "first" so that I can find it again later. I do this again with "second", "first", and "fourth". Since "fourth" was opened last, it now has the input focus. When I press "Mod4+j", "third" gets focused. Pressing again focuses "second", then "first", then "fourth", then "third", etc. Similarly, "Mod+k" goes "first" -> "second" -> "third" -> "fourth" -> "first" -> ....

I am sorry, but I cannot reproduce the behaviour that you seem to be seeing.

Now, in the tasklist the order is indeed "fourth", "third", "second", "first", i.e. this is backwards compared to what people might expect. To change this, I added `callback = awful.client.setslave` to the default rule in the config. Now, doing the experiment again, the order of focus changes is changed, meaning that "Mod4+j" goes "+1" ("first", then "second", ...) and "Mod4+k" goes "-1". Which seems to be just the behaviour that you are seeing...?

Here is a patch with my change to the default config: (Well, the default config before the templates were expanded, hence the `@DOC_FLOATING_RULE@` appearing in there, so this patch will not apply to an actual installed default config; still, this should be good enough to get the idea)
```diff
diff --git a/awesomerc.lua b/awesomerc.lua
index 10994c993..f36434417 100644
--- a/awesomerc.lua
+++ b/awesomerc.lua
@@ -486,7 +486,7 @@ awful.rules.rules = {
                      buttons = clientbuttons,
                      screen = awful.screen.preferred,
                      placement = awful.placement.no_overlap+awful.placement.no_offscreen
-     }
+     }, callback = awful.client.setslave
     },
 
     -- @DOC_FLOATING_RULE@
```
So, what am I doing differently from you?

**Comment by xor512** [comment]
OK I think I finally understand, And I still think it is a bug. Not a major one but one of those UI Trivial ones like (there should a configuration option to blah-blah-blah).

It took me way to much time and your help to understant what is happening.

And I will still have to stick with a hack since I don't know how to write my own modkey-h,l handlers so that they use position in taskbar and not position in the stack of clents.

No what it going on is that, If I remove my hack and set setslave then if I wil open Firefox -> Chromium -> LxTerminal, my taskbar will look like this

[Firefox][Chromium][LxTerminal]

Being in LxTerminal I wan't to go "left". 'j' is more to the left than 'k' so I press it. But it puts me to firefox. So to go back to the stack I need to press the more "right" button which sort of makes this "arabian" style (they right from right to left).

Worst setslave is not very cool in tiling tags and the problem still persist - looking at the taskbar only Osama Bin Laden can (could since he's presumably dead) find out what to press to go left and what to go right.

Now if I remove the setslave (while my hack is removed), since this is still stack-based, but now masters appear to the left taskbar look like:

[LxTerminal][Chromium][Firefox]

No to go to the right I press modkey-k since it is to the right, but this is stack-based, and I should've pressed modkey-j to go to the right.

Again "Osama situation".

While I totally understand that stack based switching may be a desired behaviour I would very much be happy if navigation is more easily controllaboe from rc.lue, smth like

```lua
properties {
    window_navigation = stack_based | taskbar_based },
```

Because all that my hack does is reverse the stack which happen to work without setslave (which I don't like), but it works not because it is fixed but by a concidence.

**Comment by actionless** [comment]
you probably need this: 

https://awesomewm.org/apidoc/classes/client.html#awful.client.focus.bydirection

**Comment by xor512** [comment]
Additionally to the lack of option like "navigatiion = tasbar" or "navigation = ignore_setslave" there is one more bug.

Since we are not hebrew, modkey-k should go to the top of the stack since it is located to the right of modkey-j. Respectively modkey-j should go to the bottom.  Currently it is reversed.

I understand that awesome is more like a set of lego-like building blocks and it is totally configuring via rc.lua i almost everything to make work as needed, there shoul at least be an entry in FAQ consideting this two things which should explain how to:

1. Make modkey-k go up the stack
2. Make modkey-j go down the stack
3. Make them independent of position in a stack but from position in taskbar

or simpler:
1. How to configure shortcuts to switch to the window fpcus to the one which is "located" to the left of the client (in the taskbar) and shhortcut to d focus on a window more to the lft

**Comment by xor512** [comment]
> you probably need this:
> 
> https://awesomewm.org/apidoc/classes/client.html#awful.client.focus.bydirection
You mean remove the stupid hack and just write my own modkey-j|k handlers using this bydirection function?

Thanks! I will try that (don't have that much time now) within days and report back.

**Comment by xor512** [comment]
bydirection won't do what I want. I understand that my approach is not "tiling manager style" and more "windows style" but one of the important reason why I use awesome ws is that it provides floating layouts apart from tiling one.

Now, imagine situation:

```
[         ][      ]
[         ][  2  ]
[    1   ][      ]
[         ] ------
[         ][      ]
[         ][  3  ]end
[         ][      ]
```
Being at 1 doing awful.client.bydirection("right") I indeed will en up in 2, but to go from 2 to 3 I need bydirection("down"). And this will have absolutely nothing to do with the tasklist.

What I really want was neither stack (client's table) based navigation, neither window positions regarding each other based navigation but taskbar based navigation.

And the only problem for that to happen "hebrew" notation in fact. I've managed to acvhieve what I want like this:

```lua
# somewher in global scpe of rc.ls
add_new_clients_as_slaves = false

awful.rules.rules = {
  { rule = { },
    proprieties = {...},
    callback = add_new_clients_as_slaves and awful.client.setslave or nil
  },
....

globalkeys = gears.table.join(
...

    awful.key({ modkey,           }, "j",
        function ()
            -- it appears that this is not needed to make navigatiom tagbased (worst, itn doesn;t work)
            --awful.client.focus.byidx(add_new_clients_as_slaves and 1 or -1)
            awful.client.focus.byidx(1)
        end,
        {description = "next window to the right by index", group = "client"}
    ),
    awful.key({ modkey,           }, "k",
        function ()
            -- it appears that this is not needed to make navigatiom tagbased (worst, itn doesn;t work)
            --awful.client.focus.byidx(add_new_clients_as_slaves and -1 or -1)
            awful.client.focus.byidx(-1)
        end,
        {description = "next window to the left by index", group = "client"}
    ),
...
```

BTW I still don't totally get it (this comment: "it appears that this is not needed to make navigatiom tagbased (worst, itn doesn't work)"

So if I understand correct there is a table clients. If setstslave is not called after adding a client you new client is put to the ent of the table. Than it would make sense why modkey-k goes "to the left", because it actually goes in direction to master which is at position 1.

Now with setslave callback new clients are appended at the end of the table, so byidx(1) should put it to the end and modkey-k should go right.

Anyway this is not the case. Looks like all what was needed is to change '1' tro '-1' and '-1' to '1'. Confising as it is it works for me know. Angels sing, and a light suddenly fills the room. (c) https://github.com/git/git/tree/e83c5163316f89bfbde7d9ab23ca2e25604af290

Wish I understood this better.

**Comment by Elv13** [comment]
Try https://github.com/elv13/collision, it has multiple modes to navigate clients. Maybe you will like one of them "enough" (and no, it doesn't integrate with the tasklist)

**Comment by actionless** [comment]
https://awesomewm.org/apidoc/classes/awful.widget.tasklist.html#awful.tasklist

you can pass reversing function as `args.update_function` if you need to reverse (or alter in other way) the content of the tasklist

for example:


```lua
function update_function(w, buttons, label, data, clients)
    local focused_client = client.focus
    if focused_client and focused_client.skip_taskbar then
        focused_client = nil
    end
    local sorted_clients = focused_client and {focused_client, } or {}
    for _, c in ipairs(clients) do
        table.insert(sorted_clients, c)
    end
    return awful.widget.common.list_update(w, buttons, label, data, sorted_clients)
end
```

**Comment by xor512** [comment]
Thanks to all your answer will try the links you've sent me. Once again sorry for coming up with bugs which seem to be not as bugs. It still bothers me that smth must've been screw up and now it isn't. Strange shit happens.

Anyway even this is better than this new Ubuntu WM (Plasma it is or Gnome 3)? This is just a f...g joke. Even Mac Os X is more usable.

**Comment by actionless** [comment]
> Like make the car wheel go left when you spin it to the right.

on a motorbike it's the [opposite](https://en.wikipedia.org/wiki/Countersteering) :smile_cat:

**Comment by xor512** [comment]
I would say that this is a not a standard way to ride a bike but a special case. Anyway I've created https://github.com/awesomeWM/awesome/issues/2471 since it's too much blathering coming out of me here and the bug is actually very easy to fix and IMHO it should be unless there are some reasons for such behavior which I'm not aware of.

And window manager is not a bike (well, it's not a car either)
