### ISSUE TITLE
"opposite" directions of modkey-j/k

### ISSUE THREAD

**Issue by xor512** [awesomeWM/awesome#2471]
I'm creating this issue from overbloated and closed https://github.com/awesomeWM/awesome/issues/2462.

**Output of `awesome --version`:**

 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.5
 • LGI version: 0.9.2

**How to reproduce the issue:**

Just open several terminals by pressing mod-enter (maybe on floating tag, will be easier to spot the problem. Type smth inside them to distinguish them. Press mod-k. 'k' is more to the right then 'j' and common sense (and even vim shortcuts) says that having in taskbar

[terminal1][terminal2][terminal3]

being in terminal1 modkey-k should go **to the right**. It goes to the left and focuses on terminal3. Same goes for modkey-j, instead of focusing to the left client it focuses to the right (and setting **setslave callbacks** from my experiments doesn't change anything is this behavior). The opposite direction is even reflected in comments. Just open  /usr/share/doc/awesome/doc/sample files/rc.lua  (on Arch) or /etc/xdg/awesome/rc.lua (on Ubuntu and on Arch probably also) and see this:

```lua
    awful.key({ modkey,           }, "j",
        function ()
            awful.client.focus.byidx( 1) [BUG] shjould be -1 since it should go back not forward
        end,
        {description = "focus next by index", group = "client"}
    ),
    awful.key({ modkey,           }, "k",
        function ()
            awful.client.focus.byidx(-1) --- [BUG!] should be 1 since it should go forward not back
        end,
        {description = "focus previous by index", group = "client"}
    )
```
Can you see the comments? **"k"** "focus previous", **"j"** "focus next". Next is to the right, previous to the left, unless we are hebrew for example and most of population is not (I have nothing against jews). BTW this doesn't depend on setslave callback. It's just totally counter-intuitive, very easy to fix (just change -1 to 1 and 1 to -1 and will avoid confused users like me who spent hours trying to figure out how to use modkey-j/k to navigate.

**Actual result:**

Pressing modkey-k focuses the client which is located to the left of the currently focused one in taskbar. modkey-j focuses the client which is located to the right of the currently focused one in taskbar

**Expected result:**

When you spin the steering wheel in your car to the right it should go to the right and vice versa. When you press k i vim it moves cursor right. Same modkey-k should focus the next (visually the right one in taskbar) client  and modkey-j the previous one (the left one in taskbar).

**Comment by Elv13** [comment]
This was reported before, don't remember where and it was decided changing the keybindings would cause too much confusion to users who use Awesome, but for some weird reason always use the default rc.lua. Changing the order of the tasklist is a possibility.

Awesome v4.3 adds the `source` concept to be able to fix this on your side. No change to tasklist.lua required.
https://awesomewm.org/apidoc/classes/awful.widget.tasklist.html

**Comment by xor512** [comment]
If it was already discussed and decided what to do with that there is no point in keeping this open, so I'm closing this issue. However can you just give an example of how to use it, to know what to change once awesome v4.3 becomes stable and ends up in different distributions? It's not very clear from documentation since there is just one source: awful.tasklist.source.all_clients. You mean that more sources will be added?

Thanks!

**Comment by Elv13** [comment]
The source is a normal function that takes a screen and an additional table of arguments as parameter and return a table of clients. In this case probably  `function() return gears.table.reverse(awful.tasklist.source.all_clients()) end`

**Comment by alfunx** [comment]
If your mental model of the clients is a list, where clients are listed from top to bottom, the default keybindings make sense. In that case you'd use `mod+j` to go down the list (next client) and `mod+k` to go up the list (previous client).

Try to use your variant with the `tile` layout and it will feel weird (at least if you focus the windows with your eyes, instead of the tasklist).

**Comment by xor512** [comment]
If I'd change the model to be "top to bottom"

[client_invoked_1] <- here mod-k will take me (up = right)
[client_invoked_2] <- here I am
[client_invoked_3]

It does make sense, but why should I imagine a list top to bottom? It's much more intuitive to imagine a list being a stack (especially with default "no setslave callback" behaviour)  like this:

[client_ivoked_3] <- mod-k should get me here (up = right)
[client_ivoked_2] <- here I'm
[client_ivoked_1]

I do use tile layouts (that why IMHO awesome is awesome, it allows both floating and tile) and even there with default "no setslave callback" my intuition tells me a list is like a stack and it matches the taskbar order. I understand that the internal representation might be a top-to-bottom list but that's all still counter-intuitive.

Anyways, if the decision was made already I have no other way to adjust rc.lua and stop complaining.

**Comment by alfunx** [comment]
That was just one possible mental model, you don't have to adapt that of course. Internally stacks (and lists) are 1-dimensional, they could go from left to right as well.

> I have no other way to adjust rc.lua and stop complaining.

That, I don't get. What's wrong with using a customized config if you just want to swap those keys? That shouldn't be too painful to maintain...

**Comment by xor512** [comment]
I'm sorry. I just went to sleep and then I understood you. Actually with a stack if I will ignore the taskbar what you say makes sens. 

3 <- and it is
2 <- now. I'm here so going up to the stack should get me to 3 with mod-k
1

BUT. The taskbars are like this: [3][2][1]. So it goes left.

If with "set slave callback" the only way I can imagine how it works is that the the stack is reversed now:

1 <- and it does
2 <- here I'm, mod-k should take me up, to 1
3

BUT, the taskbar is like this [1][2][3]. And again mod-k goes left.

Maybe the taskbar should've been reversed, or the stack should've been reversed, I don't know. Seems more complicated know that I understand.

> That, I don't get. What's wrong with using a customized config if you just want to swap those keys? That shouldn't be too painful to maintain...

No problem, the key point was understanding which appeared to be rather hard (since in Windows/Gnome2/XFCE/LXDE/Mate) is just not sort of this mental model.
