### ISSUE TITLE
Terminal *background* transparency not working

### ISSUE THREAD

**Issue by Maldus512** [awesomeWM/awesome#2473]
Output of awesome --version:
awesome v4.2 (Human after all)
• Compiled against Lua 5.3.4 (running with Lua 5.3)
• D-Bus support: ✔
• execinfo support: ✔
• xcb-randr version: 1.5
• LGI version: 0.9.2

How to reproduce the issue:

- Run a terminal emulator that natively supports transparent background (konsole, terminator, ...).
- Set transparent background
- Run `compton` or `xcompmgr`

Actual result:
The terminal background is not transparent.

Expected result:
The terminal background should be transparent.

Note that I have successfully made the terminal window transparent using Awesome rules in rc.lua:

```lua
        rule_any = { 
            class = { "terminator", "Terminator" },
        },
        properties = {floating = true, opacity=0.8},
```

However this makes the whole window transparent, background and foreground alike. With the background transparency option only the background has lower opacity, while the foreground (text) is perfectly visible. Ideally I would like to make the terminal 100% transparent while still reading from it, but Awesome transparency rules affect everything in the client window.

**Comment by psychon** [comment]
Are you running awesome with the `--no-argb` command line argument?

**Comment by Maldus512** [comment]
Yes, `exec awesome --no-argb` is the last line of my .xinitrc

**Comment by psychon** [comment]
Then get rid of `--no-argb` and transparency will start working.

**Comment by Maldus512** [comment]
Confirmed, thank you for the assistance

**Comment by psychon** [comment]
Perhaps some more information: For transparency support, awesome has to create its windows with a depth of 32. This caused lots of issues for people (mostly bugs in video drivers), so `--no-argb` was added to make awesome switch back to creating windows with depth 24 (so, without an alpha channel). That is all that this option does.
(The actual technical difference: By default, awesome looks for a visual with depth 32 for its windows; if none is found or `--no-argb` is specified, it instead uses the same visual that is used for the root window. In practice, this means a depth 24 visual (=without an alpha channel))

**Comment by actionless** [comment]
btw recently on one of my laptops (with intel driver) the situation changed and --no-argb have often some weird rendering issues while default argb looks fine
