### ISSUE TITLE
utils.lookup_icon(icon) aways fails on next searches if first search failed

### ISSUE THREAD

**Issue by Sorky** [awesomeWM/awesome#2474]
4.2 and reviewed the current master

Test code:
>icon in wrong spot
    local menubar	= { utils = require( "menubar.utils" ) }
    print("menubar.utils.lookup_icon: App.svg:",menubar.utils.lookup_icon("App.svg"))
    print("menubar.utils.lookup_icon: App:    ",menubar.utils.lookup_icon("App"))

>put icon in /usr/share/icons
>run again and it fails [should find it]

Reason:
    lookup_icon_cache[icon] = ... creates an entry with false which causes subsequent searches to skip

Not necisarily ideal fix:
   utils.lookup_icon_uncached should could return nil instead of false
   BUT that would make all missing icons always re-search

**Comment by Sorky** [comment]
PS 1: In utils.lookup_icon, I believe "and lookup_icon_cache[icon] ~= false" is pointless

PS 2: In utils.lookup_icon, I believe "default_icon" should change to nil and remove the local _or_ add make it a property

PS 3: another error but unexpected/unallowed for case - If icon was found and gets deleted/moved/renamed then lookup_icon_cache[icon] returns name that doesn't exist

**Comment by Sorky** [comment]
BTW...

 I reviewed related issues and like the idea of moving some of this functionality to awful.utils - still worth updating now or do the move and update?

Dare I sat that moving brings into play "utils.terminal" 

And utils.rtrim could probably go to gears.string?

**Comment by actionless** [comment]
in case of moving documented functions, old one should point to a new implementation and print deprecation warning (gears.debug.deprecate)

**Comment by psychon** [comment]
So... this bug report is about "you have a cache, don't do that", or what?

The cache was added in commit efbddb587587a13d8ffebe51807ec4c9450efa41 (without giving a reason for this). Still, I would expect that having a cache here is a good idea and not having a cache is a bad idea. We already had enough problems with slow icon lookups.

Some day, a magic fairy will show up and give us a spec-compliant implementation that also makes use of `icon-theme.cache` files. Until then, I guess we will have to live with the code that we have.

**Comment by actionless** [comment]
closing since the behavior described in the first message is expected one

**Comment by Sorky** [comment]
magic fairy ideas...

1) Add a force parameter so that it skips the first if that would normally return the false, thus allowing a re-creation of the table element it it now exists

2) Add a delete cache function

PS 2 from above is still a suggestion...

In utils.lookup_icon, I believe "default_icon" should change to nil and remove the local or make it a property

**Comment by actionless** [comment]
i like the second approach more
