### ISSUE TITLE
Java JMenuBar gets incorrect focus

### ISSUE THREAD

**Issue by petoju** [awesomeWM/awesome#248]
With latest git build of awesome, my Java applications are bugged.

It looks like focus in open JMenuBar is shifted.

Steps to reproduce:
1. Find application with JMenuBar (or compile an example).
2. Center it in your screen, so that shifted focus will be visible
3. Try maximizing it or resizing it from top-left corner. Focus in menu will be shifted. Focus is restored, when you move the window

**Comment by petoju** [comment]
This can be solved by 
```shell
wmname Metacity
```

However, metacity is reparenting and that breaks awesome.
It seems like bug here: http://stackoverflow.com/questions/10572934/java-swing-mouse-pointer-shifted-on-context-menu-when-jframe-is-maximized

Bug was not visible in awesome 3.4, so maybe there is an another issue.

**Comment by psychon** [comment]
I don't really understand this description, but commit 18f6ab107f1b57dda947386c8c074a604ce08244 might possibly help.

**Comment by petoju** [comment]
@psychon that commit does not seem to change anything. Example program is in https://github.com/petoju/awesome-issue-248

**Comment by psychon** [comment]
Sorry, no Java installed locally and experimenting with X11 forwarding just made my X11 session freeze while Java slowly started to do something that in the end resulted in the menu opening. Cursor grabs are annoying. :-(

**Comment by psychon** [comment]
https://github.com/awesomeWM/awesome/pull/658#issuecomment-177168508

The problem is Java ignoring standards and me being annoyed enough by Java ignoring standards that I don't want to apply a band aid to hide their bugs. They should fix their crap!

**Comment by psychon** [comment]
Could you test the following patch? Does it "fix" this issue?
```patch
--- client.c.orig	2016-02-01 09:48:10.234366663 +0100
+++ client.c	2016-02-01 09:49:50.035548600 +0100
@@ -819,6 +819,7 @@ client_resize_do(client_t *c, area_t geo
     lua_State *L = globalconf_get_lua_State();
     bool send_notice = force_notice;
     bool hide_titlebars = c->fullscreen;
+    bool java_is_broken = true;
 
     screen_t *new_screen = c->screen;
     if(!screen_coord_in_screen(new_screen, geometry.x, geometry.y))
@@ -826,6 +827,10 @@ client_resize_do(client_t *c, area_t geo
 
     if(c->geometry.width == geometry.width
        && c->geometry.height == geometry.height)
+        /* We are moving without changing the size, see ICCCM 4.2.3 */
+        send_notice = true;
+    if(java_is_broken)
+        /* Java strong. Java Hulk. Java make own rules! */
         send_notice = true;
 
     /* Also store geometry including border */
@@ -858,7 +863,6 @@ client_resize_do(client_t *c, area_t geo
             (uint32_t[]) { real_geometry.x, real_geometry.y, real_geometry.width, real_geometry.height });
 
     if(send_notice)
-        /* We are moving without changing the size, see ICCCM 4.2.3 */
         client_send_configure(c);
 
     client_restore_enterleave_events();
```

**Comment by petoju** [comment]
@psychon yes, thanks, that also works with Java and so it fixes the issue.
