### ISSUE TITLE
awful.prompt: specify env variables and aliases

### ISSUE THREAD

**Issue by aviau** [awesomeWM/awesome#2486]
Hello!

I have alisases for a number of programs when I use my main shell (bash).

I also have a couple of programs in ~/bin.

It would be nice if awful.prompt could be configured in such a way that I can use these aliases and programs without specifying the full path.

This is a bit related to #1609, so I'll leave the reference here.

Cheers,

**Comment by Elv13** [comment]
This is the job of your login manager to set a proper environment for Awesome to run in. While convoluted solutions could be implemented to load the internal shell "better", it isn't how Unix/Linux is supposed to work. If you open Awesome after sourcing your environment, then it will "just work".

It usually means changing how the `.desktop` start Awesome or configuring GDB/LightDM/WhateverDM/.xinitrc to source ~/.bashrc and/or ~/.zshrc and/or ~/.profile.

Close if you agree with the proposed solution. See `man execvp` for the relevant Posix documentation.

**Comment by aviau** [comment]
Wouldn't it be cleaner if these configs were only available in selected circumstances such as when I run commands myself, manually?

**Comment by Elv13** [comment]
The current API allows such case to be implemented. It also allows syntax highlight on tokens. The current API may not be the most modern completion API available on planet earth and it shows its age, but it can do that. See:

https://awesomewm.org/apidoc/libraries/awful.prompt.html
https://awesomewm.org/apidoc/libraries/awful.completion.html
