### ISSUE TITLE
Mod4+Shift+c (close client) doesn't seem to work anymore

### ISSUE THREAD

**Issue by x-yuri** [awesomeWM/awesome#2487]
Output of `awesome --version`:

```
awesome v4.2 (Human after all)
 • Compiled against Lua 5.3.5 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
```

**How to reproduce the issue:**

1. Start any application, e.g. nautilus.
2. Mod4+Shift+c

**Actual result:**

Nothing happened.

**Expected result:**

Window closed.

**Comment by alfunx** [comment]
Did you modify your config? Can you check if [these lines exist in your config](https://github.com/awesomeWM/awesome/blob/v4.2/awesomerc.lua#L359-L360) at `/etc/xdg/awesome/rc.lua` or `~/.config/awesome/rc.lua`:

```lua
    awful.key({ modkey, "Shift" }, "c", function (c) c:kill() end,
              {description = "close", group = "client"}),
```

Also [make sure `modkey` is set to `Mod4`](https://github.com/awesomeWM/awesome/blob/v4.2/awesomerc.lua#L55-L60):

```lua
    modkey = "Mod4"
```

Finally also check if you're overriding that keybinding somewhere in your configuration.

**Comment by psychon** [comment]
> How to reproduce the issue:
> 
> * Start any application, e.g. nautilus.
> * Mod4+Shift+c
> Actual result:
> Nothing happened.

Well, okay. I started awesome. I started any application (gvim). I pressed Super_L+Shift+C. Gvim closed. As such, I am closing this as invalid.

Since you write "doesn't seem to work anymore": Since when? What changed that made it not work anymore? Did you also test this with the default config?

**Comment by x-yuri** [comment]
@psychon @alfunx 

Okay, I've found the culprit. It doesn't work after adding Dvorak layout:

```
$ setxkbmap us,us ,dvp
```

Not when Dvorak layout is active, but when it's just present. I might be missing here something, but that is most likely out of scope of `awesome`. Or **could it be** that `awesome` doesn't handle keyboard events correctly?

**Comment by psychon** [comment]
Yeah, that's awesome's fault. See #1389.
