### ISSUE TITLE
textclock.lua: incorrect timezone handling

### ISSUE THREAD

**Issue by gajjanag** [awesomeWM/awesome#249]
See the following: https://unix.stackexchange.com/questions/149099/how-to-make-awesomewm-textclock-reflect-timezone-change
for a description of the issue. Essentially, timezone updates are not reflected in the widget until a restart.
The above link also contains a fix for this.

**Comment by psychon** [comment]
Instead of some non-portable new lua library, I'd prefer using GLib's timezone handling.

Does replacing this line in `textclock.lua`

    w:set_markup(os.date(format))

with the following help?

    w:set_markup(require("lgi").GLib.DateTime.new_now_local():format(format))

**Comment by gajjanag** [comment]
I get an error: "/usr/share/lua/5.3/lgi/namespace.lua: Typelib file for namespace 'Glib'(any version) not found". I am running Arch Linux with glib2 version 2.44-1, lua-lgi 0.9.0-1.

**Comment by psychon** [comment]
It's `GLib`, not `Glib`. I tried copy&paste into a lua prompt and it works as expected.

**Comment by gajjanag** [comment]
My bad. I confirmed that it works successfully; timezones are now correctly handled. Thanks!

**Comment by blueyed** [comment]
Fixed in f2e7499.

Thanks!
