### ISSUE TITLE
X crashing on awesome error

### ISSUE THREAD

**Issue by kajzersoze** [awesomeWM/awesome#2490]
Using latest git master.
I just tried with v4.2 and it happens there too.
So, interesting, might be some system update, don't know what else....

Everything was working fine, I'm not sure when it started to behave this way, maybe two weeks or something, but what happens now is that when there is a error in the rc.lua (or some other config file) instead of going back to the default configuration and the notification about the error, X crashes and I have to reboot.

Everything else works fine, I mean when there is no some error in the config files.
I really can't notice any problem in the system.
But if I don't close the bracket for example in rc.lua , X server goes down.
And it's not my config, I rechecked it several times.

I just tried awesome-copycats from scratch, that one always worked for me.
Same thing happened.

Any idea what's going on ?

**Comment by psychon** [comment]
How did you figure out that X.org is crashing? Do you have an error message for that? A backtrace?

Also, do you have error messages from awesome? It should say something about trying to use the other config file, or so. Assuming you have Xephyr and don't want to go through the X.org crash: Somehow break your `rc.lua` and then run this in a terminal: `Xephyr :1 & sleep 3 ; DISPLAY=:1 awesome`

**Comment by kajzersoze** [comment]
I can't go back to it from terminal, plus every app that was up and running is terminated.

Thanks to your `Xephyr` command I get this error message now (there was nothing without `Xephyr`), I guess it has something to do with my patch to naughty which I'm using, more about that here #2397 
Still using the same patch from the last post there.

btw this time I used default rc.lua, so it's just that in .config/awesome
At line 345 I just added `(` , to cause an error.

So, I guess this issue would be gone if I'm not using that patch, but I'm not sure why this is happening in this scenario, because I use naughty extensively and I don't have any errors, must be something specific when config error occurs which this patch doesn't like.

Anyway, I would still like to use this patch so I would appreciate some help in resolving this.

```
Xephyr :1 & sleep 3 ; DISPLAY=:1 awesome
[1] 3141
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Warning:          Unsupported high keycode 372 for name <I372> ignored
>                   X11 cannot support keycodes above 255.
>                   This warning only shows for the first high keycode.
Errors from xkbcomp are not fatal to the X server
/home/themainman/.config/awesome/rc.lua:345: ambiguous syntax (function call x new statement) near '('
error while running function!
stack traceback:
	[C]: in function 'format'
	/usr/share/awesome/lib/naughty/core.lua:473: in function 'setMarkup'
	/usr/share/awesome/lib/naughty/core.lua:483: in function 'set_text'
	/usr/share/awesome/lib/naughty/core.lua:735: in function 'notify'
	/etc/xdg/awesome/rc.lua:25: in main chunk
error: /usr/share/awesome/lib/naughty/core.lua:473: bad argument #3 to 'format' (string expected, got nil)
error while running function!
stack traceback:
	[C]: in function 'format'
	/usr/share/awesome/lib/naughty/core.lua:473: in function 'setMarkup'
	/usr/share/awesome/lib/naughty/core.lua:483: in function 'set_text'
	/usr/share/awesome/lib/naughty/core.lua:735: in function 'notify'
	/etc/xdg/awesome/rc.lua:25: in main chunk
error: /usr/share/awesome/lib/naughty/core.lua:473: bad argument #3 to 'format' (string expected, got nil)
2018-12-06 13:55:25 E: awesome: main:866: couldn't find any rc file
The XKEYBOARD keymap compiler (xkbcomp) reports:                                
> Warning:          Unsupported high keycode 372 for name <I372> ignored
>                   X11 cannot support keycodes above 255.
>                   This warning only shows for the first high keycode.
Errors from xkbcomp are not fatal to the X server



```
