### ISSUE TITLE
How to write the theme path best?

### ISSUE THREAD

**Issue by re-mx** [awesomeWM/awesome#2492]
Hello:

I am writing a configuration file and it may be used by people who don't have `xdg-user-dirs` installed (But this configuration will be in `$HOME/.config/`, and the theme is placed in `~/.config/awesome/themes/`).

How can I write the path inside `beautiful.init()`?

Thank you!

**Comment by actionless** [comment]
https://github.com/awesomeWM/awesome/blob/45430daf7f22724b89004afa0cd06a5f937ff51d/awesomerc.lua#L51

**Comment by re-mx** [comment]
@actionless 
Thank you.

I saw `get_configuration_dir()` and `get_dir("config")`, which is better/faster?

**Comment by actionless** [comment]
they not the same, read https://awesomewm.org/doc/api/libraries/gears.filesystem.html#get_dir

**Comment by actionless** [comment]
ah, my bad in stable awesome version they're same, however in git master `get_dir` is deprecated in favor of https://awesomewm.org/apidoc/libraries/gears.filesystem.html#get_xdg_config_home which is not the same as `get_configuration_dir()`

**Comment by re-mx** [comment]
@actionless 
Thanks.
So what should I use? I want to know your conclusion.

Now it seems that `get_configuration_dir()` is better? After all, some of my users refused to install packages like `xdg-user-dir`. I am afraid that using `get_xdg_config_home` will cause problems.

**Comment by Sorky** [comment]
I've seen this done a lot [and use it myself also]...
 `debug.getinfo( 1, "S" ).source:match( "/.*/" )`

It returns the path of the file it is in...
in rc.lia it most likely returns '/home/<user>/.config/awesome/'
in theme.lua it most likely returns  '/home/<user>/.config/awesome/themes/<name>/'

So you could use `beautiful.init( debug.getinfo( 1, "S" ).source:match( "/.*/" ) .. "themes/default/theme.lua")` but be aware that you are restricting the themes to being under the rc.lua path
