### ISSUE TITLE
Memory leak when opening many windows

### ISSUE THREAD

**Issue by orausch** [awesomeWM/awesome#2493]
Output of `awesome --version`:

```
awesome v4.2 (Human after all)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
```

**How to reproduce the issue:**

1.) use the default config (i.e. install awesome from debian testing and do not load a custom config)
2.) run `ps -eo comm,rss | grep awesome`
3.) switch to a different workspace and hold down super+enter for a few seconds to open a bunch of terminals (around 50-100).
4.) hold down Ctrl+d for a few seconds to close all the terminals
5.) run `ps -eo comm,rss | grep awesome` again.

**Actual result:**

```
$ ps -eo comm,rss | grep awesome
awesome         49980
$ ps -eo comm,rss | grep awesome
awesome         128560
```
Note that memory use does not seem to go down even after waiting for a few minutes, or calling `collectgarbage()` through the lua prompt. Restarting awesome does reset the memory use.

Also note that the memory usage scales with the amount of windows you open, i.e. the more you open, the more memory is leaked.

For me the debian default config opens `mate-terminal`, but I've been able to reproduce this with `xterm` aswell.
**Expected result:**
Memory use stays approximately the same.

**Comment by psychon** [comment]
Well... basically reproducable. `valgrind --tool=massif` just says that all of the memory is "in Lua". Massif's memory usage graph looks like this (I did a `collectgarbage("collect")` via the run prompt at the end):
```
    MB
85.11^                                                         #              
     |                                                       @@#              
     |                                                    @@@@@#              
     |                                                 :@@@@@@@#              
     |                                              @@::@@@@@@@#:             
     |                                           ::@@@::@@@@@@@#:             
     |                                         :@::@@@::@@@@@@@#::            
     |                       @              ::@:@::@@@::@@@@@@@#::            
     |                   :@@:@            ::::@:@::@@@::@@@@@@@#::         @: 
     |                 :@:@ :@        ::::::::@:@::@@@::@@@@@@@#::      :::@: 
     |               :::@:@ :@      ::::: ::::@:@::@@@::@@@@@@@#:::: @:::::@: 
     |             @@:::@:@ :@:::@@:::::: ::::@:@::@@@::@@@@@@@#:::::@:::::@: 
     |           @@@@:::@:@ :@:::@ :::::: ::::@:@::@@@::@@@@@@@#:::::@:::::@: 
     |           @ @@:::@:@ :@:::@ :::::: ::::@:@::@@@::@@@@@@@#:::::@:::::@: 
     |         ::@ @@:::@:@ :@:::@ :::::: ::::@:@::@@@::@@@@@@@#:::::@:::::@: 
     |      : :::@ @@:::@:@ :@:::@ :::::: ::::@:@::@@@::@@@@@@@#:::::@:::::@::
     |  :: ::::::@ @@:::@:@ :@:::@ :::::: ::::@:@::@@@::@@@@@@@#:::::@:::::@::
     | :: :::::::@ @@:::@:@ :@:::@ :::::: ::::@:@::@@@::@@@@@@@#:::::@:::::@::
     | :: :::::::@ @@:::@:@ :@:::@ :::::: ::::@:@::@@@::@@@@@@@#:::::@:::::@::
     | :: :::::::@ @@:::@:@ :@:::@ :::::: ::::@:@::@@@::@@@@@@@#:::::@:::::@::
   0 +----------------------------------------------------------------------->Gi
     0                                                                   35.96
```
According to massif, peak memory usage is 86% usable heap, of which 77% are allocated in Lua-land. 
- 37% via `luaH_resize` (20% through `luaD_call`, 16% `luaH_newkey` (adding a key to a table?)).
- 36% is via `luaC_newobj` (18% `luaH_new`, 9% `luaS_newuserdata` (called by `lua_newuserdata`), plus other stuff).

Second biggest allocated after `luaH_resize` is `luaA_object_connect_signal_from_stack` with 3%, aka "basically nothing" (which is still 2 MiB).

This... doesn't tell me anything usable either.

**Comment by orausch** [comment]
Just skimming through past issues, maybe the cause for this is the same as #1068? From that thread:
 
> Memory increase on every tag switching, client spawning, and even client closing

**Comment by orausch** [comment]
I'm not able to reproduce anymore on:
```
awesome v4.3 (Too long)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
```

**Comment by psychon** [comment]
Weird. I don't know if we changed anything, but glad that the problem disappeared.

Thanks for re-checking and closing this issue on your own.
