### ISSUE TITLE
Urxvt & awesome with--no-argb problem

### ISSUE THREAD

**Issue by kajzersoze** [awesomeWM/awesome#2498]
I have no problems if I run Awesome normally, but if I run it with --no-argb I can't start urvxtc anymore. Screen just flashes and that's it.

My .Xresources (minus colors to make this shorter) 

```
URxvt*scrollBar:         false
URxvt*scrollBar_right:   false

URxvt*depth: 32
URxvt.background:rgba:0600/0600/0600/dddd
URxvt.transparent: true
URxvt.shading: 20

URxvt.font: xft:ShureTechMono Nerd Font:regular:pixelsize=15

Xft.autohint: 0
Xft.antialias: 1
Xft.hinting: 1
Xft.hintstyle: hintslight

URxvt.perl-ext-common: default,matcher
URxvt.url-launcher: /usr/bin/xdg-open
URxvt.matcher.button: 1
URxvt.cursorBlink: 1
URxvt.cursorUnderline: 0
URxvt.urgentOnBell:  true
URxvt.internalBorder: 0
URxvt.externalBorder: 0

XTerm.termName: xterm-256color
```

I start daemon like this :
`urxvtd --quiet --opendisplay --fork`

and client with `urxvtc`

I tried with changing `URxvt*depth: 32` to `24` and commenting out 
```
URxvt.background:rgba:0600/0600/0600/dddd
URxvt.transparent: true
URxvt.shading: 20
```
but still it wouldn't run.
Anything else I can do to make it run ?

**Comment by kajzersoze** [comment]
Never mind, it's a daemon->client thing for some reason.
Client crashes daemon, have no idea why would `--no-argb` interfere with that.

Same config but running a single instance (`urxvt`) and it's working fine.

**Comment by actionless** [comment]
sorry for offtopic, i switched to `xst` because it can do about the same but doesn't have / have less font rendering problems than both xterm and urxvt

**Comment by kajzersoze** [comment]
It's not offtopic, any suggestion is appreciated, `xterm` was just the thing to install to get me going with something fast, I was using urxvt for years and didn't know what else to use :)

Anyway, I found nice little gem, called `st` (suckless terminal) , all I can say is WOW so far !
I heard about it but never used it, this one suits me perfectly.

Looks like I will be using awesome with `--no-argb`, so shame about urxvt not working with it, liked the daemon feature, which others don't have, but it is what it is.

So, I will stay with `st` and that's it.

Not really sure if I should close this or not, I guess I will leave it open for a month maybe, because if someone knows how to solve this problem I would go back to it.
If not I'll close it then.

**Comment by kajzersoze** [comment]
Doesn't matter anymore, I switched to another terminal.
