### ISSUE TITLE
How to define the local variables of theme better?

### ISSUE THREAD

**Issue by re-mx** [awesomeWM/awesome#2499]
Hello, and sorry for my poor English.

I saw two ways to define local variables of the theme:

1.
```lua
local xresources = require("beautiful.xresources")
local dpi = xresources.apply_dpi

local gfs = require("gears.filesystem")
local themes_path = gfs.get_themes_dir()
```

2.
```lua
local dpi = require("beautiful.xresources").apply_dpi
local themes_path = require("gears.filesystem").get_themes_dir()
```

Because I basically know nothing about Lua programming, so I'd like to ask, which of the two ways is better?

I personally don't pay attention to safety, but focus on speed.

Thank you very much!

**Comment by actionless** [comment]
no difference

even if you `require` the same module multiple times lua is caching it under the hood

**Comment by re-mx** [comment]
@actionless Thank you.

In other words, the second way (directly defined once) will not cause some problems?

**Comment by psychon** [comment]
> In other words, the second way (directly defined once) will not cause some problems?

Correct
