### ISSUE TITLE
(Possibly) rewrite how widget shapes are implemented

### ISSUE THREAD

**Issue by psychon** [awesomeWM/awesome#2516]
I just saw a question on StackOverflow about wanting a different stroke mode than "center", namely "inside" and "outside". I guess such a magic would also be interesting for widget shapes, which currently (sometimes?) do some weird things to work around some issues which would be fixed with such a stroke mode.

https://stackoverflow.com/questions/53934276/stroke-alignment-in-cairo/53943201

**Comment by psychon** [comment]
Okay, so we had some problems which shapes lately and some attempts at solving them. This comment is on how about shapes are supposed to work / look like. This is not yet about implementations problems caused by anti-aliasing (thus: the below will not avoid those and some of the images have artifacts).

There are several possible ways to define a shape with a border (really, shapes without borders are so much simpler and the current implementation is fine for those). In the following, I show all of the ones that I can come up with...

All the following examples will be based on this code, only the `draw` function will be different:
```lua
local cairo = require("lgi").cairo
local shape = require("gears.shape")

local unpack = unpack or table.unpack
local fill_color = { 0, 0, 0 }
local border_color = { 1, 1, 1 }

local function draw(cr, width, height, shap, bw)
    error("implement this")
end

local function my_pie(cr, width, height)
    return shape.pie(cr, width, height, 0.5, 5, math.min(width, height) / 2)
end

local shapes = { shape.rounded_rect, shape.infobubble, shape.powerline, my_pie }
local borders = { 0, 10, 15 }

local spacing = 10
local base_size = 100
local width = (base_size + spacing) * #borders
local height = (base_size + spacing) * #shapes
local img = cairo.ImageSurface(cairo.Format.RGB24, width, height)

local cr = cairo.Context(img)
cr:set_source_rgb(0, 1, 0)
cr:paint()

cr:translate(spacing / 2, spacing / 2)

-- draw a grid
for x=0, #borders - 1 do
    cr:move_to(x * (base_size + spacing), 0)
    cr:rel_line_to(0, height - spacing)
    cr:move_to(x * (base_size + spacing) + base_size, 0)
    cr:rel_line_to(0, height - spacing)
end
for y=0, #shapes - 1 do
    cr:move_to(0, y * (base_size + spacing))
    cr:rel_line_to(width - spacing, 0)
    cr:move_to(0, y * (base_size + spacing) + base_size)
    cr:rel_line_to(width - spacing, 0)
end
cr:set_line_width(2)
cr:set_source_rgba(0, 0, 0, 0.3)
cr:stroke()

cr:set_source_rgb(1, 1, 1)
for _, shap in ipairs(shapes) do
    cr:save()
    for _, bw in ipairs(borders) do
        cr:save()
        cr:rectangle(0, 0, base_size, base_size)
        cr:clip()

        draw(cr, base_size, base_size, shap, bw)

        cr:restore()
        cr:translate(base_size + spacing, 0)
    end
    cr:restore()
    cr:translate(0, base_size + spacing)
end

img:write_to_png("/tmp/output.png")
```

# 50-50 borders with clipping

```lua
local function draw(cr, width, height, shap, bw)
    shap(cr, width, height)
    cr.line_width = bw
    cr:set_source_rgb(unpack(fill_color))
    cr:fill_preserve()
    cr:set_source_rgb(unpack(border_color))
    cr:stroke()
end
```

By default, cairo strokes lines by following the path with a pen. This means that 50% of the stroke ends up left of the path and 50% ends up right of the path. If we just use this directly, then the border will be un-even, because half of it will sometimes end up outside of the widget (and thus is clipped away):
![output](https://user-images.githubusercontent.com/89482/51665144-5ceea580-1fbb-11e9-87bc-d7fabe982eed.png)

# 50-50 borders, shape shrunk by half the border size

```lua
local function draw(cr, width, height, shap, bw)
    -- The following two lines are new
    cr:translate(bw / 2, bw / 2)
    width, height = width - bw, height - bw

    shap(cr, width, height)
    cr.line_width = bw
    cr:set_source_rgb(unpack(fill_color))
    cr:fill_preserve()
    cr:set_source_rgb(unpack(border_color))
    cr:stroke()
end
```
This is a slight variant of the previous point: We move the shape half the border width away from (0,0) and make it smaller by the border size.
![output](https://user-images.githubusercontent.com/89482/51665241-99220600-1fbb-11e9-9db4-2642f7cf062c.png)

# Border outside of the line

```lua
local function draw(cr, width, height, shap, bw)
    shap(cr, width, height)

    -- First, fill the shape
    cr:set_source_rgb(unpack(fill_color))
    cr:fill_preserve()

    -- We create a temporary surface; default content is fully transparent
    cr:push_group_with_content(cairo.Content.ALPHA)

    -- Now draw the shape with twice the line width. This draws both the inside
    -- and the outside.
    cr.line_width = bw * 2
    cr:stroke_preserve()

    -- Now remove the inside again
    cr:set_operator(cairo.Operator.SOURCE)
    cr:set_source_rgba(0, 0, 0, 0)
    cr:fill()

    local mask = cr:pop_group()
    -- Draw inside the mask we now have
    cr:set_source_rgb(unpack(border_color))
    cr:mask(mask)

    -- Free some memory
    cr:set_source_rgb(0, 0, 0)
    local status, s = mask:get_surface()
    if status == "SUCCESS" then
        s:finish()
    end
end
```
Instead of having the line on both sides of the line, we can do the line on the outside. This is stupid, but I am just including it for completeness.
![output](https://user-images.githubusercontent.com/89482/51665366-e30aec00-1fbb-11e9-9a37-850e23fa6ca8.png)

# Border outside of the line, shape shrunk by full border size

```lua
local function draw(cr, width, height, shap, bw)
    -- The following two lines are new
    cr:translate(bw, bw)
    width, height = width - 2 * bw, height - 2 * bw

    shap(cr, width, height)

    -- First, fill the shape
    cr:set_source_rgb(unpack(fill_color))
    cr:fill_preserve()

    -- We create a temporary surface; default content is fully transparent
    cr:push_group_with_content(cairo.Content.ALPHA)

    -- Now draw the shape with twice the line width. This draws both the inside
    -- and the outside.
    cr.line_width = bw * 2
    cr:stroke_preserve()

    -- Now remove the inside again
    cr:set_operator(cairo.Operator.SOURCE)
    cr:set_source_rgba(0, 0, 0, 0)
    cr:fill()

    local mask = cr:pop_group()
    -- Draw inside the mask we now have
    cr:set_source_rgb(unpack(border_color))
    cr:mask(mask)

    -- Free some memory
    cr:set_source_rgb(0, 0, 0)
    local status, s = mask:get_surface()
    if status == "SUCCESS" then
        s:finish()
    end
end
```
Same as above, but we shrink the size a bit to have the border inside of the shape.
![output](https://user-images.githubusercontent.com/89482/51665462-1baac580-1fbc-11e9-856c-6096b558fd34.png)

# Border inside the line

```lua
local function draw(cr, width, height, shap, bw)
    shap(cr, width, height)

    -- First, fill the shape
    cr:set_source_rgb(0, 0, 0)
    cr:fill_preserve()

    -- We create a temporary surface; default content is fully transparent
    cr:push_group_with_content(cairo.Content.ALPHA)

    -- Clip to the shape, so that we can only draw inside of it
    cr:clip_preserve()

    -- Now draw the shape with twice the line width. This draws both the inside
    -- and the outside, but the outside is clipped away.
    cr.line_width = bw * 2
    cr:stroke()

    local mask = cr:pop_group()
    -- Draw inside the mask we now have
    cr:set_source_rgb(unpack(border_color))
    cr:mask(mask)

    -- Free some memory
    cr:set_source_rgb(0, 0, 0)
    local status, s = mask:get_surface()
    if status == "SUCCESS" then
        s:finish()
    end
end
```
We can also just have the line on the outside of the shape.
![output](https://user-images.githubusercontent.com/89482/51665565-557bcc00-1fbc-11e9-97f9-468b74b3c4f5.png)

-----
So, the question now is, how should shapes look like?
(Next, I will try including the "weird shape" from Elv13 and edit this comment.)

**Comment by psychon** [comment]
Uhm... our current code (in the background widget, dunno where else something like this is implemented) should be the 50-50 with shrinking variant. However, here the tip of the powerline shape is clipped / would reach outside of the available space. Is this something that really happens already? Or is the current code doing something different here?

Also, things to keep in mind:
- How well does this have to work with transparency? (i.e., with the 50-50 variant and a 50%-transparent border color, half the border is over the "fill", while half of the border is over the "true background". What's the expected outcome here?)
- Lots and lots of antialiasing things to worry about.
- Is performance a concern? (My fix for antialiasing and transparency would involve temporary surfaces that are later used as masks...)

**Comment by psychon** [comment]
After thinking about it a bit: The "outside shrink" variant makes the most sense to me. The shape is drawn and then a border is added around it. The shape is also visible as-is, not like in the 50-50 variant, where the actual shape is "hidden" somewhere.
The only problem now is that this variant makes the mitter issue really prominent.
(Miter: There is a "sharp (angled) corner" where lines make an abrupt bent, like in the tip of an arrow; this miter can reach outside by more than the border width (in theory it can be infinitely long, but cairo implements a miter limit, switching to a bevel if the miter would be too long); this problem can be seen in the images in missing arrow tips (because they were clipped away).)

**Comment by Elv13** [comment]
Yes, after sleeping over this I also came to that conclusion. It's not "perfect", but overall much better. Apparently even my worst case scenario shape looks as good as it will get (compared to all the issues it has like 50/50 border touching overlapping over the content and the funky shape of different size demo I did in the other issue). Thanks for the in-detail report. Sorry for being asleep when you requested the code for that shape.

**Comment by actionless** [comment]
Today I Learned: miter

thanks a lot for your huge research!

considering other sidecases (like half-transparent border) "Border outside of the line, shape shrunk by full border size" looks/sounds most reasonable to me

**Comment by actionless** [comment]
or could we just make it a shape argument, `outside, center, inside` ?

**Comment by Elv13** [comment]
> or could we just make it a shape argument, with choices: outside, center, inside ? (and do correct shrinking based on choice)

Is there any case where any other behavior than the "ouside"+"shrink" is better? Because otherwise the shapes are using in *a lot* of placed and I don't feel like adding dozens of new properties.

**Comment by actionless** [comment]
center could make sense in some sidecases: https://github.com/awesomeWM/awesome/issues/2516#issuecomment-457194593

**Comment by psychon** [comment]
https://gist.github.com/psychon/366fa34858bcb88725a9273012a25f0b
![foo](https://user-images.githubusercontent.com/89482/51687160-44e64880-1ff2-11e9-893e-0b1eb007c97c.png)
This seems to even work with transparency (although my example for this is ugly)!

**Comment by psychon** [comment]
And here is @actionless example from https://github.com/awesomeWM/awesome/issues/2465#issuecomment-436026124:
![foo](https://user-images.githubusercontent.com/89482/51687784-8cb99f80-1ff3-11e9-8a29-d515b505a170.png)
(I also tried it with some different DPI values, but the result still looked good and I am fairly sure that there cannot be anti-aliasing artifacts here due to the way the the border is first drawn bigger than actually needed, thus surely covering anything that could turn into artifacts (unless you set the border width to `0.3`).)

**Comment by actionless** [comment]
yup, mb i've a bit over-thought the stuff and should be enough just to stay on outside border with shrinking

**Comment by actionless** [comment]
@psychon also i see your patch is not doing gmath.round(), as it was in my PR

it causing border to look "muddy" if let's say you have 1px border and some 1.5 scaling
