### ISSUE TITLE
touchscreen

### ISSUE THREAD

**Issue by zaoqi** [awesomeWM/awesome#2519]
the newest version of Ubuntu 18.04
**How to reproduce the issue:**
chroot into ubuntu
Xephyr ...
/etc/init.d/dbus start
Start onbboard in awesome
**Actual result:**
The focus moved to onboard and it can not work.
**Expected result:**
It should work like xfce,lxde,...

**Comment by actionless** [comment]
i think it's duplicate of this:

https://github.com/awesomeWM/awesome/issues/2256

**Comment by zaoqi** [comment]
But it can not work.
I have added
... name = "Onboard" ...

**Comment by zaoqi** [comment]
And how to implement  `long press => right click` ... ?

**Comment by actionless** [comment]
you can with mouse grabber and root.fake_input , however it's easier to use smth like `touchegg` or another gesture-manager

**Comment by actionless** [comment]
(and i double-checked - it works for both `onboard` and `cellwriter`)
