### ISSUE TITLE
Mouse gets crazy over root window and jumps around randomly

### ISSUE THREAD

**Issue by nlw0** [awesomeWM/awesome#253]
I am using Awesome with Arch Linux on a new machine. Things appear to work fine on Gnome but with Awesome I have this weird problem that my mouse behaves normally over application windows, but if I leave it over the root window it starts moving around randomly, jumping here and there a few times every second. The fact that happens only over the root window makes me think the window manager might have something to do with it. Any ideas?

The mouse is actually not completely normal otherwise. Sometimes the movement gets a chopped, like motion events are being dropper, perhaps.

**Comment by blueyed** [comment]
Does it happen with the default config, too?
Which version are you using? Can you try it with Git master, too?

**Comment by nlw0** [comment]
OK, I made a test and found out it actually happens only when I use my favorite background, which is `xsetroot -bitmap /usr/include/X11/bitmaps/root_weave`. Yeah, I know... Any ideas why that might happen, and if awesome might have anything to do with it? I also noticed it seems to be setting my pointer sometime after it runs rc.lua, so I can't use `xsetroot -cursor_name X_cursor`, very frustrating. :(

**Comment by psychon** [comment]
Awesome never warps the pointer by itself, only as a result to calls like `mouse.coords` and the lua code (at least the code that comes with awesome) doesn't call that function randomly either. So... does this also happen without any window manager at all / with something like twm?

For the mouse cursor: We are using some "standard library" for cursors, so setting your cursor theme might work. The mouse cursor is only changed (calls to `root.cursor`) in `awful.startup_notification` (changes to the "waiting cursor" while a startup notification is active, then back to "left_ptr"). The other call is in awful/mouse/init.lua which unconditionally sets the cursor to "left_ptr" once during startup. Dunno why it does that, but this happens during `require("awful")`, so quite near the beginning of your rc.lua.

Perhaps just doing `root.cursor("X_cursor")` at the end of your rc.lua helps?
