### ISSUE TITLE
Virtualbox 6: vms not visible in floating mode

### ISSUE THREAD

**Issue by cars10** [awesomeWM/awesome#2532]
Output of `awesome --version`:

awesome v4.2 (Human after all)
 • Compiled against Lua 5.3.5 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2

**How to reproduce the issue:**

* Install virtualbox 6
* Run any vm (i can reproduce the issue with a w7, w10 and ubuntu vm)
* Set the vm to floating

**Actual result:**

VM is no longer visible. But you can see it working in the virtualbox main window preview, and you can "make it visible" by unfloating it when you have focus.

The issue only started appearing after upgrading to virtualbox 6. With version 5 everything worked perfectly with the same system and the same vm's.

**Expected result:**

VM window should float correctly.

**Comment by psychon** [comment]
Uhm. Sorry, but I would guess that this is a bug in VirtualBox, not awesomeWM. Any reason why you think otherwise?

**Comment by cars10** [comment]
I wondered if it might be related to some rules in awesome because i could not find anything on google about this issue with other window managers.

But you are probably right :) Thanks anyway.

**Comment by psychon** [comment]
Well, "works fine with version 5, but breaks with version 6" is a good hint to me that this is not the WM's doing (unless you somehow manage to have rules that only match version 6, but (a) I bet you would know about them and (b) I have no clue how a rule should make a window disappear).

What exactly do you mean with "no longer visible", by the way? Like, could you try enabling window titlebars and see what happens? Does just the "content" disappear (titlebars stay visible) or is VirtualBox perhaps moving its window offscreen (titlebar disappears, too)? You might also try running something like this in a terminal to get a list of all the windows and their positions: `awesome-client 'local result = {} for _, c in pairs(client.get()) do table.insert(result, { name = c.name, geometry = c.geometry }) end return require("gears.debug").dump_return(result)'` (actually, you can just do `xwininfo -root -tree` to get that list, no need to use `awesome-client` for this job)

**Comment by cars10** [comment]
Well thanks for the hint. You are right, the window is actually offscreen. 

I managed to resposition it like this:
* disable floating for the window
* drag the "resize handler" in the bottom right of the window (i think they added this in virtualbox 6)
* **while dragging** enable floating mode
* the window is now visible and on your screen.

Sadly the window moves offscreen again whenever the vm changes its resolution. I guess that sounds indeed like a virtualbox issue?

**Comment by psychon** [comment]
That sounds a lot like VirtualBox moving itself offscreen. Sigh, we should just start ignoring such requests... 
What's the exact position/size that VirtualBox ends up with when it is offscreen? Any idea where those numbers come from? (This might give a hint on what the problem is)

If you report a bug to VirtualBox, please leave a link here.

**Comment by cars10** [comment]
Hm, it is always too far to the right. My screens are 7200px wide (together):

```bash
$ xrandr
Screen 0: minimum 8 x 8, current 7200 x 2160, maximum 32767 x 32767
(...)
```

Starting an ubuntu vm and running your code snippet results in this (at 8262 px on the x axis):

```bash
  1 : table: 0x562e8b660330
    name : Ubuntu 1604 server -> 1804 (1804) [Running] - Oracle VM VirtualBox (string)
    geometry : table: 0x562e8cce06a0
      height : 578 (number)
      width : 640 (number)
      y : 1096 (number)
      x : 8262 (number)
```

Starting different vm's results in different values, sometimes 7xxx, sometimes 9xxx. My only guess is that the problem is related to hidpi stuff but i have no evidence for that.
