### ISSUE TITLE
awesome.kill: protect against empty string for pid

### ISSUE THREAD

**Issue by blueyed** [awesomeWM/awesome#2534]
`luaA_kill` uses `lua_tonumber` for the pid argument, which turns an empty string into 0.

Given the impact of the function itself, and that `0` has a special meaning this should be protected against.

I assume using `lua_tonumber` should be kept in general, but `nil` and an empty string should be checked for before already then.

Code: https://github.com/awesomeWM/awesome/blob/1c3788c92f9cfe2344de0fdce519b80a250fb9e7/luaa.c#L255-L272

**Comment by blueyed** [comment]
The problem here is apparently that `lua_tonumber` returns 0 if it fails to convert the argument:

> Converts the Lua value at the given acceptable index to the C type lua_Number (see lua_Number). The Lua value must be a number or a string convertible to a number (see §2.2.1); otherwise, lua_tonumber returns 0.

`tonumber("")` returns nil, not 0.

**Comment by psychon** [comment]
`luaL_checknumber`?

**Comment by blueyed** [comment]
Yeah, started working on a PR just now.
