### ISSUE TITLE
Monodevelop GUI editor (Stetic) problems - can't drag and drop widgets

### ISSUE THREAD

**Issue by SandiDusic** [awesomeWM/awesome#254]
The issue is as follows: I can not enter the GUI editor in monodevelop by left-clicking on the "Designer" tab in the strip at the bottom (pictured here). 
![screenshot from 2015-06-04 22-30-39](https://cloud.githubusercontent.com/assets/1926491/7993882/95d20736-0b09-11e5-93fe-b558a9fba5c8.png)
It opens when only when I left click it. Furthermore, I can't drag and drop any widgets to the main window. I have tried adding a container, but it does not help. Everything else but the designer works perfectly.

I'm using Arch. I have tried launching monodevelop with three different gtk2 themes, including the default, but to no avail. I installed at least five different versions of monodevelop: some from the Arch Rollback Machine, the one from the official repositories and a fresh one off of git, and still no luck. There were very few posts about this issue on the internet. They all seemed to share a common theme: the user was using Arch with a lesser known WM, like awesome. 

Out of desperation, I installed openbox and tried running monodevelop in it. Lo and behold, monodevelop worked like a charm. The problem seems to be awesome related. If this can't be fixed, is there any way to run just monodevelop in, say, openbox, inside of awesome? Probably not, but I'm sure as hell not switching away from awesome. 

EDIT: I found a workaround. I made a script that starts a Xephyr session and within it openbox and monodevelop. I configured openbox to remove window decorations from monodevelop and to always keep it maximized. I made a .desktop entry that runs this script so that it's easily accessible from the application menu. Now it looks and acts almost as a normal application.

**Comment by kc8rwr** [comment]
I'm dealing with the same problem using monodevelop in stumpwm.  I'll probably end up with a similar solution to yours.  I'm sure I can figure it out but it might be painful. You wouldn't be interested in posting your script here would you to help out myself and anyone else that lands here from Google would you?? Please

**Comment by SandiDusic** [comment]
Hey! Sadly, this bug doesn't seem to get any traction. Probably should have posted it in the monodevelop repository. Getting the Xephyr thing set up is kinda difficult, but you can probably do it. It's not just a matter of copying my script, though. You have to configure the wm you'll be running inside the Xephyr session. Also, I use fish, not bash. It's been a while since I've done all this, so I can't give you exact instructions. Even when you get it working, it's not absolutely perfect. For me, font sizes are a bit off and it does not play well with awesome as normal apps should.

Some things that may help you on your quest:
- [Xephyr article on ArchWiki](https://wiki.archlinux.org/index.php/Xephyr), which, along with the man page, should be enough to get it doing what you want.
- `Xephyr -keybd ephyr,,,xkblayout=hr,xkbvariant=qwerty -ac -br -noreset -resizeable :1 &`, the command I use to start Xephyr. The `-resizeable` thing makes the Xephyr window take up all the space your wm gives it, which is what you want, especially for tiling wms. `-keybd` is something you will have to deal with if you aren't using the us keyboard layout, which is the default. It's syntax seems pretty confusing after all this time, I have no idea where I got it from. Try the man page.
- You may have to set the `GTK2_RC_FILES` variable in your shell if your current gtk theme isn't compatible with monodevelop (mine made some buttons impossible to read).
- Make the whole thing a script and pass it's args to monodevelop. Doing all this by hand every time is obviously a bad idea.
- Make a .desktop file for the script. Then you can use it as an actual editor, to open files from your file manager, and you can open it from an application menu if you use one.
- You will have to edit your openbox rc.xml (it's in ~/.config/openbox). How exactly, depends. I think the only thing I did was add this to the `<applications>` section (you can find an exhaustive comment there explaining all you need to know about how exactly this entry should look, although I do remember looking up some docs online):
``` xml
<application class="MonoDevelop">
  <decor>no</decor>
  <maximized>true</maximized>
</application>
```

If you're stuck on anything feel free to ask me again! And, if you don't mind, could you tell me whether you use Arch? I wonder if this is Arch specific.

**Comment by Elv13** [comment]
Has recently been fixed
