### ISSUE TITLE
Trap/segfaults with most graphical applications running under awesome

### ISSUE THREAD

**Issue by Jigoku** [awesomeWM/awesome#2549]
I'm on Slackware -current (x86_64). Just over a week ago, after updating some system packages, i've been having this problem where most gtk applications will crash due to trap/segfault. This has only been happening with awesomewm. I've been using awesome as my desktop for the past 3 years or so, so hoping if someone can figure out what is actually happening here, and if there is a solution, because it's been unusable since 20th December for me:

Someone else just confirmed they also have this problem on Slackware -current; as per this thread i started over at LQ: 
https://www.linuxquestions.org/questions/showthread.php?p=5944770

```
$ awesome --version
awesome v4.2 (Human after all)
 • Compiled against Lua 5.1.5 (running with Lua 5.1)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
```

**How to reproduce the issue:**

Launch awesome as your window manager, run a gtk application such as firefox or thunar. They will all randomly crash after a few moments, or sometimes immediately from user input. (eg; pressing ctrl, whilst Thunar is open, causes a trap signal).

**Actual result:**

Launching firefox results in this via `dmesg`;
```
[  396.757846] traps: firefox[6440] trap int3 ip:7f8ae5815535 sp:7fff979fcbe0 error:0 in libglib-2.0.so.0.5800.2[7f8ae57de000+7b000]
[  396.785455] Chrome_~dThread[6729]: segfault at 0 ip 00007f17d9b5b4d5 sp 00007f17d80eeb00 error 6 in libxul.so[7f17d9700000+528e000]
[  396.785473] Code: 04 25 00 00 00 00 3a 02 00 00 e8 86 4f ba ff 48 89 df e8 a2 ca ff ff eb 86 48 8b 05 0d f4 27 05 48 8d 0d 86 0d 24 03 48 89 08 <c7> 04 25 00 00 00 00 fe 09 00 00 e8 5b 4f ba ff 90 55 53 48 83 ec
[  396.785795] Chrome_~dThread[6499]: segfault at 0 ip 00007f4f6f5734d5 sp 00007f4f6db06b00 error 6 in libxul.so[7f4f6f118000+528e000]
[  396.785802] Code: 04 25 00 00 00 00 3a 02 00 00 e8 86 4f ba ff 48 89 df e8 a2 ca ff ff eb 86 48 8b 05 0d f4 27 05 48 8d 0d 86 0d 24 03 48 89 08 <c7> 04 25 00 00 00 00 fe 09 00 00 e8 5b 4f ba ff 90 55 53 48 83 ec

```

A similar problem with Thunar;
```
$ thunar

(thunar:20733): Gdk-ERROR **: 21:47:46.836: The program 'thunar' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadMatch (invalid parameter attributes)'.
  (Details: serial 5397 error_code 8 request_code 2 (core protocol) minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
Trace/breakpoint trap
```
**Expected result:**

Applications should run as normal. 

**Additional notes:**

I have tried using the master branch of the code, but no improvements. I am tempted to believe this is related to the glib2 package being updated; as per Slackware's [changelog](http://ftp.osuosl.org/pub/slackware/slackware64-current/ChangeLog.txt) on `Thu Dec 20 04:19:50 UTC 2018` 

```
a/kernel-firmware-20181218_0f22c85-noarch-1.txz:  Upgraded.
a/kernel-generic-4.19.11-x86_64-1.txz:  Upgraded.
a/kernel-huge-4.19.11-x86_64-1.txz:  Upgraded.
a/kernel-modules-4.19.11-x86_64-1.txz:  Upgraded.
ap/cups-filters-1.21.6-x86_64-1.txz:  Upgraded.
d/bison-3.2.3-x86_64-1.txz:  Upgraded.
d/kernel-headers-4.19.11-x86-1.txz:  Upgraded.
k/kernel-source-4.19.11-noarch-1.txz:  Upgraded.
l/glib2-2.58.2-x86_64-1.txz:  Upgraded.
l/libgsf-1.14.45-x86_64-1.txz:  Upgraded.
x/libinput-1.12.4-x86_64-1.txz:  Upgraded.
isolinux/initrd.img:  Rebuilt.
kernels/*:  Upgraded.
usb-and-pxe-installers/usbboot.img:  Rebuilt.
```

Also if relevant; this is the package build script used to build awesome on Slackware -current can be viewed here;
https://github.com/Ponce/slackbuilds/blob/current/desktop/awesome/awesome.SlackBuild

Is glib2 causing some kind of compatibility problem? I'm not sure what else may be causing these problems within awesome. My only observation is that the `dmesg` messages when applications crash, always mention `libglib-2.0.so.0.5800.2` 

Thanks...

**Comment by Elv13** [comment]
Use `--no-argb` until GTK fix their regression.

See https://github.com/awesomeWM/awesome/issues/2540

**Comment by Jigoku** [comment]
Thanks for the quick reply and mentioning that, cheers.
