### ISSUE TITLE
IntelliJ windows get stuck 

### ISSUE THREAD

**Issue by hari-rangarajan** [awesomeWM/awesome#255]
I tried the delay_raise trick mentioned in the wiki (https://awesome.naquadah.org/wiki/Problems_with_Java) but intellij windows fail to raise after a few switches (or some time). Restarting awesome at that point gets the windows working.

I have intellij windows maximized using tyrannical and awful.rules. As floating mode windows, I would get this problem all the time. Also, my menus work correctly for a while before they also end up with the one-off problem.

I'm on awesome 3.5.6 and JDK8 for Intellij ( I have also tried 7 with no difference).

**Comment by StephaneArguin** [comment]
This bug is a show stopper for me from using AwesomeWM because I do Android development (IntelliJ). Any advice about how to fix this? Thanks. :)

**Comment by hari-rangarajan** [comment]
@psychon 
 I noticed that this problem was discussed before: http://comments.gmane.org/gmane.comp.window-managers.awesome/8515

WM_PROTOCOLS(ATOM): protocols  WM_TAKE_FOCUS, WM_DELETE_WINDOW
WM_CLASS(STRING) = "sun-awt-X11-XFramePeer", "jetbrains-idea"

WM_HINTS(WM_HINTS):
		Client accepts input or input focus: False
		Initial state is Normal State.


Any thoughts on if this is fixable or if there is a work-around? Doing a awesome.restart() restores correct focus behavior but not elegant.

Thanks!

**Comment by psychon** [comment]
I don't really know. The "accepts input focus: False" stuff breaks some assumptions that our API provides (like, doing `client.focus = c` will actually focus `c`). I'd have to debug this, but Java's X11-related code is a mess that I try to stay away from. Also, this sounds like a race condition and those are always hard to figure out... Sorry. (And no, I don't have any idea what is actually happening / causing this problem).

**Comment by hari-rangarajan** [comment]
@psychon 

I dug around. It appears to me that I actually have this problem: https://awesome.naquadah.org/bugs/index.php?do=details&task_id=733

The window can be focussed if I move to any non-maximized layout. In the maximized layout, the window gets the focus but does not "raise" up the stack. The work-around specified in that bug report does not work for me though. Maybe, the right question to ask is with a set of maximized windows, is there trouble with the ordering when focus is given to a maximized window...

Thanks again!

**Comment by Elv13** [comment]
Has been reported to be fixed
