### ISSUE TITLE
awful.rules.match does not check for properties of a rule

### ISSUE THREAD

**Issue by basaran** [awesomeWM/awesome#2559]
Output of `awesome --version`:

awesome v4.2 (Human after all)
 • Compiled against Lua 5.3.5 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2

**How to reproduce the issue:**

    awful.key({                   }, 'F13', function () 
        local matcher = function (c) 
            pooh = {class = "Firefox", properties = {tag = "2"}}
            return awful.rules.match(c, pooh)
        end 
        awful.client.run_or_raise("firefox", matcher) 
    end), -- Firefox

**Actual result:**

Launches a new instance

**Expected result:**

It should have raised Firefox running at tag 2

**Comment by Elv13** [comment]
If you want to try git-master, there is the "better" `awful.spawn.raise_or_spawn`. Firefox is a bit tricky because it doesn't correctly implement the startup notification protocol and reuse PID for many clients, making reliable detection near impossible. Also note that firefox have different class depending on where it comes from or the release channel, mine is "Firefox Developer Edition". So even if you use the newer API, the matcher will still be needed.

Also in git-master there is a bug related to tag-by-name that has been fixed.

**Comment by basaran** [comment]
for the record, I was able to run_or_raise the Firefox class. It just seems the awful.rules.match is ignoring any and all properties defined within the table. 

Thank you for awesomewm, it's awesome none the less.

**Comment by psychon** [comment]
(@Elv13 I marked your comment as off-topic)

> It should have raised Firefox running at tag 2

Why?

The documentation for `awful.rules.match` says:

> Check if a client matches a rule.

Thus, this only checks if the class is "Firefox", as expected. If you want to also apply the expected properties... Perhaps something like this?
```lua
awful.key({                   }, 'F13', function () 
    local matcher = function (c) 
        pooh = {class = "Firefox", properties = {tag = "2"}}
        local matches = awful.rules.match(c, pooh)
        if matches then
            awful.rules.execute(c, pooh.properties)
        end
        return matches
    end 
    awful.client.run_or_raise("firefox", matcher) 
end), -- Firefox
```
In fact, why are you using `awful.rules` for this at all?
```
awful.key({                   }, 'F13', function () 
    local matcher = function (c) 
        if c.class ~= "Firefox" then -- Actually, awful.rules.match does: not c.class and not c.class:match("Firefox") and c.class ~= "Firefox"
            return false
        end
        local t = awful.tag.find_by_name(c.screen, "2")
        if t then
            c:tags{ t }
        end
        return true
    end 
    awful.client.run_or_raise("firefox", matcher) 
end), -- Firefox
```

**Comment by basaran** [comment]
Thank you for the code,  much appreciated. Please allow me to elaborate my use case. I'm running a modified rc.lua provided with the manjaro awesomewm distribution.  
> The documentation for awful.rules.match says:
`awful.rules.match` does  `match (c, rule)`.
and the rule I was trying to use for the match was:
`pooh = {class = "Firefox", properties = {tag = "2"}}`
my intention was to match the firefox instance running at tag 2. I was trying to take advantage of this function:
        -- Toggle tag on focused client.
        awful.key({ modkey, "Control", "Shift" }, "#" .. i + 9,
                  function ()
                      if client.focus then
                          local tag = client.focus.screen.tags[i]
                          if tag then
                              client.focus:toggle_tag(tag)
                          end
                      end
                  end,
                  {description = "toggle focused client on tag #" .. i, group = "tag"})

My goal was to have a tag dedicated to browser where I keep firefox, chromium on tag 2 with the proportioned layout (50/50) and also keep a copy of the same firefox instance on tag 7 along with my development ide (35/65). So, if I was to hit F13, I would go to firefox on tag 2.

I created this as an issue because rules.match wouldn't use the properties of the rule during matching. I tried with minimized, floating as well. Anyhow, I will keep working on this along with the functions you kindly provided and post it here when I create the desired effect. Thank you again for your time and efforts.

**Comment by psychon** [comment]
Ah, okay. I misunderstood your goal then, sorry. I thought you want to move Firefox to tag `"2"` if it matches (which is what the rule you wrote would do). I did not understand that you want to check if Firefox is on a tag with name `"2"`.

Uhm... I don't think `awful.rules` can check for tags (since this e.g. does not really fit with its original goal: If a new client is opened, it will not have any tags yet, so checking these tags for something is pointless).

Here is a new attempt for checking "is this client on a tag with name `"2"`":
```lua
awful.key({                   }, 'F13', function () 
    local matcher = function (c) 
        return c.class == "Firefox" and c.first_tag.name == "2"
    end 
    awful.client.run_or_raise("firefox", matcher) 
end), -- Firefox
```
The above only checks the first tag. Checking for all tags (i.e.: "Is any of the tags the client is on called 2?") is a bit more complicated:
```lua
awful.key({                   }, 'F13', function () 
    local matcher = function (c) 
        if c.class ~= "Firefox" then
            return false
        end
        for _, t in ipairs(c:tags()) do
            if t.name == "2" then
                return true
            end
        end
        return false
    end 
    awful.client.run_or_raise("firefox", matcher) 
end), -- Firefox
```

**Comment by basaran** [comment]
Sorry, I couldn't get back sooner. Thank you again for the snippets. After observing your approach, I came up with the following to ease the management of these windows. It can probably done better, and I also used the deprecated functions. I'm not very fluent with neither lua or the awesomewm api. May be it will benefit others:

```
-- run, raise or warp shortcut
awful.key({ modkey, "Shift" }, 'a', function () 
    -- matcher
	local matcher = function (c) 
		return awful.rules.match(c, {class = 'Code'}) 
	end
	
	-- toggle the editor onto the current tag
	local warper = function(c)  
		local tags = root.tags()
		awful.client.toggletag(tags[awful.tag.getidx()], c) 
	end
	
	-- run, raise or warp
	awful.client.run_or_raise("code", matcher, warper) 
end),

-- remove the cloned window
awful.key({ modkey}, "-" , function () 
  local tags = root.tags()
  if client.focus then
  	local tag = tags[awful.tag.getidx()]
		if tag then 
			client.focus:toggle_tag(tag)
		end 
	end 
end),
```

Thank you again for the awesomewm. Really great window management framework.
