### ISSUE TITLE
c.valid isn't working

### ISSUE THREAD

**Issue by benedeusz** [awesomeWM/awesome#256]
Hello, I'm trying to make a disappearing client border and to avoid errors while changing properties on dead client I found c.valid property useful, but it doesn't work for me.  Without if statement blink works. Is something wrong with my code or is it bug?

https://gist.github.com/benedeusz/91c6ae275a286dea9076

**Comment by psychon** [comment]
What kind of errors exactly? If you get a lua error about an "invalid object", then `c.valid` should help. If you get some X11 errors, then `c.valid` cannot help and there is a race instead.

**Comment by benedeusz** [comment]
If I kill window before timer timeout I get an "invalid object" Lua error. Seems like c.valid is always null/false

**Comment by psychon** [comment]
Sorry, works for me.

I tried the following code and it tells me "skipped blink on invalid object":

	client.connect_signal("focus", function(c)
	  print("focus", c)
	  c.border_color = beautiful.border_focus
	  local blink_timer = timer { timeout = 2 }
	  blink_timer:connect_signal("timeout", function()
	    blink_timer:stop()
	    blink_timer = nil
	    if c.valid then 
	      c.border_color = beautiful.border_normal
	      print("blink", c)
	    else
	      print("skipped blink on invalid object")
	    end
	  end)
	  blink_timer:start()
	end)

**Comment by benedeusz** [comment]
Yes, I tried the same code and I still get an "invalid object" error and c.valid never returns true for me. 
My log:
https://gist.github.com/benedeusz/6f528897b0526899a877

**Comment by blueyed** [comment]
Are you using Awesome from Git?

It has been added recently only:

    commit a4d4204
    Merge: a791e69 f5610fa
    Author: Daniel Hahler <X>
    Date:   Sun Feb 15 13:13:46 2015 +0100
    
        Merge pull request #128 from psychon/client-valid
        
        objects: Add .valid property (Fixes #110)

**Comment by benedeusz** [comment]
Aw sorry. I was using 3.5.6. On master version it works perfectly. Thank you.

**Comment by blueyed** [comment]
Ok, closing it then.

Where have you found out about `client.valid`?  It's not from the online documentation, is it?

**Comment by benedeusz** [comment]
I found it on git obviously. Now I know why I couldn't find anything about it in docs.
https://github.com/awesomeWM/awesome/issues/110

**Comment by blueyed** [comment]
OK then.. thanks for reporting back!

And welcome to Git master then, I suppose? :)

**Comment by benedeusz** [comment]
Definitely. I love Awesome and appreciate what you guys are doing here. Thanks one more time.
