### ISSUE TITLE
wibox.widget.systray triggers parent widget mouse::leave when mouse is inside a systray icon

### ISSUE THREAD

**Issue by sezaru** [awesomeWM/awesome#2560]
Output of `awesome --version`:

awesome v4.2 (Human after all)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2

**How to reproduce the issue:**

I'm using a modified version of https://github.com/elenapan/dotfiles awesome config.

This config have a sidebar which is shown only when I move the mouse to the right border of the monitor and will hide itself when the mouse is not inside the sidebar area (via mouse::leave signal).

I'm trying to add a systray to that sidebar, so I added this code to the `sidebar.lua` file:
```
local systray = wibox.widget.systray()
systray:set_base_size(30)

local traybox = wibox.widget{
   pad(0),
   {
      {
         pad(3),
         systray,
         pad(3),
         layout = wibox.layout.align.horizontal,
      },
      shape         = gears.shape.rounded_bar,
      bar_shape     = gears.shape.rounded_bar,
      bg     = '#ff0000',
      widget = wibox.container.background,
   },
   pad(0),
   expand = "none",
   layout = wibox.layout.align.horizontal,
}
```

And added the traybox widget to the sidebar widgets hierarchy. This is the result for now:
![screenshot from 2019-01-07 22-01-32](https://user-images.githubusercontent.com/279828/50800571-e9b11800-12c7-11e9-8525-df4d7c1dec48.png)

(Yes, I know, the background of the nm-applet is broken, but as far as I know this is because of my gtk+ version).

**Actual result:**

Now I just need to move the mouse the a systray icon (in this case the nm-applet one) and the sidebar will trigger the `mouse::leave` event and hide the entire sidebar.

**Expected result:**

Since the systray widget is a parent of my sidebar, when I move the mouse inside it, it should not trigger the sidebar `mouse::leave` event and, as consequence, not hide the entire sidebar.

**Comment by Elv13** [comment]
Umm, that will be a bit tricky to handle. The systray icons *are* X11 windows and they are *not* part of the bar. So from the bar point it view, it lost focus, so this behavior is understandable. However for your use case it sucks. The easy workaround would be to check if the mouse is still within the bar geometry and not hide it. The proper fix would be to mess with some fragile protocols and risk regressions.

https://awesomewm.org/apidoc/libraries/gears.geometry.html#gears.geometry.rectangle.area_intersect_area

(untested)

    local cursor = {x = mouse.coords().x, y = mouse.coords().y, width = 1, height = 1}
    local wgeo = mywibarname:geometry()
    if not gears.geometry.rectangle.area_intersect_area(wgeo, cursor) then 
        mywibarname.visible = false
    end

**Comment by sezaru** [comment]
Thanks! that worked like a charm!

**Comment by Elv13** [comment]
Reopening since it's still technically a bug

**Comment by psychon** [comment]
@sezaru Are you in the position to test patches?
```diff
diff --git a/event.c b/event.c
index e264d8862..ba93517bc 100644
--- a/event.c
+++ b/event.c
@@ -582,13 +582,14 @@ event_handle_leavenotify(xcb_leave_notify_event_t *ev)
 
     globalconf.timestamp = ev->time;
 
-    if(ev->mode != XCB_NOTIFY_MODE_NORMAL)
+    if(ev->mode != XCB_NOTIFY_MODE_NORMAL || ev->detail == XCB_NOTIFY_DETAIL_INFERIOR)
         return;
 
     /* Ignore leave with detail inferior (we were left for a window contained in
      * our window, so technically the pointer is still inside of this window).
+     * FIXME
      */
-    if(ev->detail != XCB_NOTIFY_DETAIL_INFERIOR && (c = client_getbyframewin(ev->event)))
+    if(c = client_getbyframewin(ev->event))
     {
         luaA_object_push(L, c);
         luaA_object_emit_signal(L, -1, "mouse::leave", 0);
@@ -612,7 +613,7 @@ event_handle_enternotify(xcb_enter_notify_event_t *ev)
 
     globalconf.timestamp = ev->time;
 
-    if(ev->mode != XCB_NOTIFY_MODE_NORMAL)
+    if(ev->mode != XCB_NOTIFY_MODE_NORMAL || ev->detail == XCB_NOTIFY_DETAIL_ANCESTOR)
         return;
 
     if((drawin = drawin_getbywin(ev->event)))
@@ -628,9 +629,9 @@ event_handle_enternotify(xcb_enter_notify_event_t *ev)
         luaA_object_push(L, c);
         /* Ignore enter with detail inferior: The pointer was previously inside
          * of a child window, so technically this isn't a 'real' enter.
+         * FIXME
          */
-        if (ev->detail != XCB_NOTIFY_DETAIL_INFERIOR)
-            luaA_object_emit_signal(L, -1, "mouse::enter", 0);
+        luaA_object_emit_signal(L, -1, "mouse::enter", 0);
 
         drawable_t *d = client_get_drawable(c, ev->event_x, ev->event_y);
         if (d)
```
From https://www.x.org/releases/X11R7.5/doc/x11proto/proto.html:
> Normal events are generated as follows:
> When the pointer moves from window A to window B and A is an inferior of B:
> • LeaveNotify with detail Ancestor is generated on A.
> • LeaveNotify with detail Virtual is generated on each window between A and B exclusive (in that order).
> • EnterNotify with detail Inferior is generated on B.
> When the pointer moves from window A to window B and B is an inferior of A:
> • LeaveNotify with detail Inferior is generated on A.
> • EnterNotify with detail Virtual is generated on each window between A and B exclusive (in that order).
> • EnterNotify with detail Ancestor is generated on B.

So... I would guess the existing code here for EnterNotifies in awesomeWM here is wrong, since it checks for detail Inferior instead of Ancestor. What this patch here should do is to just plainly ignore any LeaveNotify and EnterNotify events that are caused by the mouse pointer just moving in or out of some direct child window.

**Comment by sezaru** [comment]
I just tested it, it worked like a charm!
