### ISSUE TITLE
beautiful.theme_path returns nil (unless in the theme itself)

### ISSUE THREAD

**Issue by Sorky** [awesomeWM/awesome#2573]
Need to reopen https://github.com/awesomeWM/awesome/issues/1508 or edit documentation?

https://awesomewm.org/apidoc/libraries/beautiful.html#theme_path says nothing about it's availability

From beautiful/init.lua...
`beautiful.theme_path = dir and (dir:get_path().."/") or nil`exists it is only accessible in the them.lua and only if the theme.lua has local beautiful = require( "beautiful" ) first

The following...
```
function beautiful.mt:__index(k)
    return theme[k]
end
```
effectively masks access to 'beautiful.theme_path' anytime later

Several ideas (please feel free to add more and please forgive any errors)..

1) Documentation update...
- usage restriction
- need for require( "beautiful" ) in the theme

2) Make it part of the theme as well...
- Add something like `theme[themes_path] = beautiful.theme_path` after `theme = protected_call(dofile, config)`

3) Use a function instead...
- Add `local theme_path = nil` followed by `function get_theme_path() return theme_path end` before `function beautiful.init(config)`
- And remove `beautiful.` from `beautiful.theme_path = dir and (dir:get_path().."/") or nil`

4) Recommend/implement/document an alternative method as the first path of the theme...
- Add `theme.themes_path = debug.getinfo( 1, "S" ).source:match( "/.*/" )` in all samples and show/explain in the theme documentation 

5) Remove the __index and add the theme to beautiful...
- After `if theme.font then set_font(theme.font) end` add `for k, v in pairs(theme) do theme[k] = v end`

**Comment by Sorky** [comment]
@Elv13 ?

**Comment by psychon** [comment]
> effectively masks access to 'beautiful.theme_path' anytime later

Nope. The `__newindex` metamethod catches the assignment and redirects it to the `theme` table. Thus, this is saved in a table that is immediately replaced with another table in the next line.

**Comment by Sorky** [comment]
Sweet - Thanks
