### ISSUE TITLE
awful.client.property.floating *xproperty*

### ISSUE THREAD

**Issue by mobalt** [awesomeWM/awesome#2587]
Output of `awesome --version`:
awesome v4.2 (Human after all)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2

**How to reproduce the issue:**
I am trying to programmatically make a client become *floating* via a shell script. Via `xprop` I noticed this xproperty is set by awesomewm `awful.client.property.floating(CARDINAL) = 1` when floating, and becomes `0` when not floating. So I tried setting it via this command `xprop -id 35651589 -f awful.client.property.floating 8c -set awful.client.property.floating 1` but the window does not become floating. If at this point I restart awesome, then it does become floating. I think awesome is only checking this xproperty on restart, not in real-time.

**Comment by Elv13** [comment]
This property isn't part of the public API.

Please use variants of (untested)

`makefloating.sh`:

```
#!/bin/bash

awesome-client << EOF
local c = nil

for _, c2  in ipairs(client.get()) do
    if c2.window == "$1" then
        c = c2
        break
    end
end

if not c then return end

c.floating = true

EOF
```

    makefloating.sh 35651589
