### ISSUE TITLE
naughty has no support for interacting with application, which sends notification

### ISSUE THREAD

**Issue by jaysonwillson** [awesomeWM/awesome#259]
Some applications may send interactive notifications. For example, Blueman (bluetooth manager) will send a notification and ask if I want to connect to some device, or Networkmanager will send a notification and ask, if I would like to see such notification (screen, using xfce4-notifyd for notification management: https://i.imgur.com/fUOl6KQ.jpg). However, if I use naughty, there will be no possibility to interact with notification sender application (screen: https://i.imgur.com/cwqNdLa.jpg). Could you please add support for interaction with notifications? That would increase usability a lot.

**Comment by psychon** [comment]
Should already be implemented with the following commit:

commit e664a74710a4637b7abd97c410b532268d051a8c
Author: Da Risk <da_risk@geekorum.com>
Date:   Wed Dec 31 14:28:46 2014 +0100

    Add support for notification actions
    
    The desktop notification specification says that a notification can have
    different actions. These actions allow the user to interact with the client
    application and should be displayed by the notification server.
    * Add function to emit a DBus signal
    * Notifications : emit NotificationClosed signal when closing notification
    * Notifications: use constant for notification closed reasons
    * notifications: Implement notifications actions
    
    This is just a basic implementation to display the actions send with the
    notifications. The actions should be displayed differently
    * Notifications: add support for default action

**Comment by jaysonwillson** [comment]
Is this commit in the main tree? In Awesome built from git that's what I see, for example, if nm-applet connects to/disconnects from network (http://i.imgur.com/mTr1HZK.png). However, if I press on this text (disable ...) I will see the same message if I connect/disconnect again. If I disable naughty (remove require naughty from rc.lua) and use xfce4-notifyd instead, that's what I see (http://i.imgur.com/2alGglc.png). That is notification created by xfce4-notifyd, and if I press on it's button, these notifications will be displayed no more. 
Another example. If I run Pidgin and (for example) somebody from my contact-list comes online, notification is being displayed. With xfce4-notifyd I will have a button which will open chat with that person. That's what I see with Naughty: http://i.imgur.com/3QWy7mc.png. There is a string "show", but it is not interactive.

**Comment by psychon** [comment]
Could you run `dbus-monitor` and get the dbus messages for one those messages? Perhaps also with xfce4-notifyd? And also (in each case) including some example for pressing the buttons.

**Comment by jaysonwillson** [comment]
Yes, sure.
Both logfiles were created this way: dbus-monitor > file, do an action which would cause notification, mouseclick on the button (or on the text string in case of Naughty), stop dbus-monitor
In case of Xfce4-notifyd after I pressed on button, I got Pidgin window opened.

Naughty: https://gist.github.com/jaysonwillson/22b794096d69d140b2a4
Xfce4-notifyd: https://gist.github.com/jaysonwillson/25697885586351f76c60

**Comment by blueyed** [comment]
Without looking at the code the commit message sounds like it might not be handled yet:

> This is just a basic implementation to display the actions send with the
notifications. The actions should be displayed differently

**Comment by jaysonwillson** [comment]
Probably, the actual result of that commit is that now under notification body there is a special string for action.

**Comment by psychon** [comment]
@blueyed That's meant to "make this look better".

These two traces are pretty much identical, here's a diff of the notification-related part:

```patch
diff --git a/gistfile1.txt b/gistfile1.txt.1
index 05d4b75..26e17da 100644
--- a/gistfile1.txt
+++ b/gistfile1.txt.1
@@ -1,4 +1,4 @@
-method call sender=:1.43 -> dest=:1.12 serial=21 path=/org/freedesktop/Notifications; interface=org.freedesktop.Notifications; member=Notify
+method call sender=:1.58 -> dest=:1.52 serial=21 path=/org/freedesktop/Notifications; interface=org.freedesktop.Notifications; member=Notify
    string "Pidgin"
    uint32 0
    string ""
@@ -31,11 +31,14 @@ method call sender=:1.43 -> dest=:1.12 serial=21 path=/org/freedesktop/Notificat
       )
    ]
    int32 -1
-method return sender=:1.12 -> dest=:1.43 reply_serial=21
-   uint32 2
-signal sender=:1.12 -> dest=(null destination) serial=7 path=/org/freedesktop/Notifications; interface=org.freedesktop.Notifications; member=ActionInvoked
-   int32 2
+method return sender=:1.52 -> dest=:1.58 reply_serial=21
+   uint32 3
+signal sender=:1.52 -> dest=(null destination) serial=18 path=/org/freedesktop/Notifications; interface=org.freedesktop.Notifications; member=ActionInvoked
+   uint32 3
    string "show"
-signal sender=:1.12 -> dest=(null destination) serial=8 path=/org/freedesktop/Notifications; interface=org.freedesktop.Notifications; member=NotificationClosed
-   int32 2
-   int32 2
+signal sender=:1.52 -> dest=(null destination) serial=19 path=/org/freedesktop/Notifications; interface=org.freedesktop.Notifications; member=NotificationClosed
+   uint32 3
+   uint32 2
```

The differences that surely don't matter: Different addresses on the bus (:1.43 vs :1.58 etc), different serial numbers, different id for the notification (2 vs 3). The only "real" difference that I can spot in there is the argument type for the `ActionInvoked` signal: int32 vs uint32. The spec says it should be uint32 and naughty is wrong.

@jaysonwillson Could you edit naughty/dbus.lua. In the functions `sendActionInvoked` and `sendNotificationClosed`, change `"i", notificationId"` into `"u", notificationId"` (this occurs twice) and `"i", reason)` into `"u", reason)`? These should be lines 55, 64 and 65 in that file. This "i" is int32, but we want "u" aka uint32.

**Comment by jaysonwillson** [comment]
I have done what You have asked me to do, then I have restarted awesome. Connected-disconnected (to summon notification) network while running dbus-monitor.
https://gist.github.com/jaysonwillson/5d018fb664fa98d45545

**Comment by psychon** [comment]
Hm, it's still int32 instead of uint32. Weird...

**Comment by jaysonwillson** [comment]
One moment, seems like I've done something wrong. Forget what I said

**Comment by jaysonwillson** [comment]
By accident, I had two awesome: in /usr and in /usr/local, so the changed which I have done had no effect. Now I have removed both of them and made a fresh git-installation. 
So, now there is uint32 instead of int32 in dbus-monitor, and if I summon nm-applet's notification and press on this string: "never show this message again", it really obeys and doesn't show it any more.
However, when I try interacting with pidgin this way, it segfaults xD. But I don't think it's Naughty's fault.
