### ISSUE TITLE
fake_input: "key_release" via "pressed" callback without delay through globalkeys generates no key

### ISSUE THREAD

**Issue by blueyed** [awesomeWM/awesome#260]
I am trying to use `root.fake_input` from a keybinding, but calling `"key_release"` just after `"key_press"` will not generate the key event / press.

    awful.key({ "Shift", modkey }, "Insert",  function()
      root.fake_input("key_press", "a")
      -- os.execute("sleep 0.5")
      root.fake_input("key_release", "a")
    end),

Uncommenting the `os.execute` to add a delay works (a smaller delay like `0.1` is enough).

Using it through awesome-client works unconditionally:

    echo 'root.fake_input("key_press", "a"); root.fake_input("key_release", "a")' | awesome-client

A maybe relevant issue: https://bugs.freedesktop.org/show_bug.cgi?id=73769 ("xcb_fake_test_input ignoring XCB_KEY_RELEASE")

**Comment by blueyed** [comment]
It works when I use the `release` callback instead of the `pressed` callback (adding a `nil` argument before the `function` (for `pressed`).

Is that expected?  If so, why is that?

**Comment by psychon** [comment]
Dunno, but possible. During the press callback shift, mod and insert are pressed, so perhaps whatever you are testing with doesn't want to have shift, mod, insert and a pressed.

Btw: Your `sleep 0.5` shouldn't change anything. These fake_event calls are only sent to the X11 server at the end of the current main loop iteration. So the only difference here might be that you already released the keys by the time that the "action takes place".
(You could try moving that sleep 0.5 around to test this theory)

**Comment by blueyed** [comment]
> During the press callback shift, mod and insert are pressed, so perhaps whatever you are testing with doesn't want to have shift, mod, insert and a pressed

Makes sense.

btw: it's not possible to access the `kobj` from the callback, is it? (https://github.com/awesomeWM/awesome/blob/master/lib/awful/key.lua.in#L42-L47)
Could this be provided somehow?  Maybe optionally, if a new argument to `key.new` would be true?

**Comment by blueyed** [comment]
Closing this issue.

@psychon 
Please provide feedback on my question above.  I think it might be useful sometimes to have the key object available.  I've tried to add it to the scope where the callback gets called, but that did not work.

**Comment by psychon** [comment]
Nope, you can't access it and I don't see what it would be useful for. Do you want to modify the key object during the callback? If you really wanted it, you'd either have to store it in a global variable or give it as an argument to the callback.
