### ISSUE TITLE
arcchart doesn't display the value correctly when the value is too small and rounded_edge is set to true

### ISSUE THREAD

**Issue by dekeract10** [awesomeWM/awesome#2604]
Output of `awesome --version`:
awesome v4.2 (Human after all)
 • Compiled against Lua 5.3.5 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2

I noticed a bug concerning wibox.container.arcchart. When the rounded edge is set to true, and the value is too small

**How to reproduce the issue:**
Add this to theme.lua and load it in the wibox,

```lua
local github =  wibox.widget {
   rounded_edge = true,
   forced_width = 20,
   thickness = 5.5,
   bg = "#FFFFFF",
   colors = {"#FFCC00"},
   value = 5, --this is to low to be
   min_value = 0,
   max_value = 100,
   widget = wibox.container.arcchart,
}
```

**Actual result:**
![image](https://user-images.githubusercontent.com/46914170/51512741-d8a7f100-1e07-11e9-823a-37b368911fe4.png)

**Expected result:**
Something like this, but with rounded corners
![image](https://user-images.githubusercontent.com/46914170/51512774-faa17380-1e07-11e9-89dd-ef0782a63d43.png)

The workaround I found is to change the value to the minimum one that is displayable if it goes below it. I also found that forced_width, and thickness influence this behaviour.

Thank you for your patience.

**Comment by psychon** [comment]
I'm not quite sure what is going on, but this code causes it:
https://github.com/awesomeWM/awesome/blob/aeab2a70e908389e6ac9b130928c7b92582d40f9/lib/gears/shape.lua#L465-L477
```
before:
arc_length=	1.4922565104552	start_angle=	-0.31415926535898	end_angle=	0
after:
arc_length=	-4.0077434895448	start_angle=	0.26478810306207	end_angle=	-0.57894736842105
```
This code seems to try to make the arc a little shorter to add space for the "rounded heads" that are added later. However, the value here is so small that `start_angle` becomes larger than `end_angle` and thus we end up with an almost full circle. I guess in this case this just should not draw an actual arc at all, only the "heads"...?
(This can also be almost seen in the screenshot: There is a single almost white pixel about where the arc should be, i.e. the arc is now exactly on the parts where it should not be.)

**Comment by Elv13** [comment]
There is also a refactoring bug that was introduced in the revision that got merged. The first version of that pull request was less buggy, but the one that got merged was in the name of "more readable code". I should have fixed that a long time ago and never did. At the time I didn't notice, but I have been aware of this bug for a while.

**Comment by Elv13** [comment]
The other bug related to rounded edges. That's the regression form the earlier version I had in my config before upstreaming it:

![screenshot_20190126_105444](https://user-images.githubusercontent.com/340384/51789631-cd7ef900-2158-11e9-9a13-e1edee0891e8.png)

Another bug is that when the limits are provided as property, the rounded edges were always painted even for a "full circle". One code path acted correctly and the other didn't:

![screenshot_20190126_105851](https://user-images.githubusercontent.com/340384/51789673-64e44c00-2159-11e9-8f0d-f3de2eadb184.png)
