### ISSUE TITLE
Some system tray icons disappeared after restarting AwesomeWM

### ISSUE THREAD

**Issue by Bekcpear** [awesomeWM/awesome#2606]
Output of `awesome --version`:

```
awesome v4.2 (Human after all)
 • Compiled against Lua 5.3.5 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
```

**How to reproduce the issue:**
System tray:  ![11](https://p.ume.ink/i/0d/98a9ee5ea25df54dc5e1ab6f7c2a4bb516b5a8.png)

Press Mod+Ctrl+R to restart AwesomeWM

**Actual result:**

System tray:  ![11](https://p.ume.ink/i/fc/5a4b804d087a611bd29c037447426e4853ce1e.png)

only fcitx icon is only.

**Expected result:**

System tray:  ![11](https://p.ume.ink/i/0d/98a9ee5ea25df54dc5e1ab6f7c2a4bb516b5a8.png)

**Comment by psychon** [comment]
What are the icons that go missing? Are they all e.g. implemented through Gtk?

**Comment by Bekcpear** [comment]
The nextcloud tray icon, the QuiteRSS tray icon and Telegram tray icon. I don't know what they are implemented by.

**Comment by psychon** [comment]
Nextcloud uses Qt5 (per https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/nextcloud-client)
QuiteRSS seems to use Qt (They install Qt 5.9 in their `.travis.yml`).
Telegram uses Qt 5 (per https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/telegram-desktop)

Sounds like I will have to find a systray-using-Qt-example and then I'll have to look into Qt's source code.

**Comment by psychon** [comment]
Sigh. Doesn't seem to be due to Qt.
```c++
#include <QApplication>
#include <QDebug>
#include <QIcon>
#include <QSystemTrayIcon>

int main(int argc, char **argv)
{
    QApplication app(argc, argv);
    QSystemTrayIcon *trayIcon = new QSystemTrayIcon();
    qDebug() << trayIcon->isSystemTrayAvailable();
    trayIcon->setIcon(QIcon("heart.png"));
    trayIcon->show();
    return app.exec();
}
```
```
CONFIG += debug
QT += gui widgets
SOURCES += tray.cpp
```
With `heart.png` somewhere off the internet. System icon stays present when restarting awesome.

My qt version is 5.11.3+dfsg-2 (Debian testing)

**Comment by Elv13** [comment]
First things first, the obvious ones:

 * are the process still running (check using `ps`)
 * if those apps have running clients (windows), are they still in the taskbar
 * if you do `fluxbox --replace` or any other WM that support in-place replacement, does the problem happen?

**Comment by Bekcpear** [comment]
Yes, the processes are still running:
```
 ~ >>> ps aux | grep nextcloud                                                                                                                               19:55:17
u         5088  0.0  0.9 983712 120708 tty1    SLl  15:18   0:07 /home/u/s/local/bin/nextcloud
u        19270  0.0  0.0  10684  2220 pts/3    S+   19:55   0:00 grep nextcloud
 ~ >>> ps aux | grep quiterss                                                                                                                                19:55:28
u         5090  0.0  1.7 2828488 210692 tty1   Sl   15:18   0:06 quiterss
u        19282  0.0  0.0  10684  2432 pts/3    S+   19:55   0:00 grep quiterss
```

The window of Telegram IM works fine, but the tray icon is missing.

Ummm, it doesn't seem to be Awesome problem. I checked it under the fluxbox WM and the problem happens again.

Please help me to confirm if it is the problem of AwesomeWM. If is not, I will close this issue.

**Comment by Elv13** [comment]
If you can reproduce the problem by starting fluxbox, then doing `fluxbox --replace`, then it has nothing to do with Awesome.

**Comment by Bekcpear** [comment]
Okay, sorry for bother. I will do myself to solve this problem.

**Comment by doronbehar** [comment]
@Bekcpear  I'm having this issue as well, exactly as you described - with only Qt5 based system tray icons. Did you reach the conclusion it's a problem with Qt and not Awesome? I noticed this issue started to exist after a certain Qt5 upgrade so Maybe it is a Qt regression.. If you did report it somewhere, could you please share a link to your report?

Thanks.

**Comment by doronbehar** [comment]
For reference, I think this Qt bug report refers to our problem: https://bugreports.qt.io/browse/QTBUG-63065

**Comment by Elv13** [comment]
That bug is about `org.kde.StatusNotifierItem` which we don't implement. It is unrelated.

**Comment by doronbehar** [comment]
If anyone's interested, I've added [another report there](https://bugreports.qt.io/browse/QTBUG-75400).

**Comment by psychon** [comment]
Just for completeness: As written above, I cannot reproduce. I just checked again with `examples/widgets/desktop/systray/` from Qt. The result is that the icon stays visible when restarting AwesomeWM.
Tested with v5.13.0-beta2-301-ge6d9617c79 (something ancient) and... couldn't test with anything newer due to Qt failing to build and me running out of time. I guess my comment from January still stands.

**Comment by doronbehar** [comment]
Hmm.. Why are you using this specific beta version? I'm on Arch with 5.12.3 .

**Comment by psychon** [comment]
I'm not using it. I just have the source code of an old Qt version laying around. And I couldn't build a newer version due to OpenSSL API changes breaking the Qt build. At this point I was too annoyed and lazy to install Qt devel packages from Debian and test with that, but I guess I did that in January:

https://github.com/awesomeWM/awesome/issues/2606#issuecomment-457169636 

> My qt version is 5.11.3+dfsg-2 (Debian testing)
