### ISSUE TITLE
Cannot move floating clients

### ISSUE THREAD

**Issue by parmort** [awesomeWM/awesome#2616]
Output of `awesome --version`:

```
awesome v4.2 (Human after all)
 • Compiled against Lua 5.3.5 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
```

**How to reproduce the issue:**

Bind a key to the following function:
```lua
function() client.x = client.x + 5 end
```

Or altogether:

```lua
awful.key({ modkey }, "o", function() client.x = client.x + 5 end),
```

**Actual result:**

Awesome threw the error:

```
attempt to perform arithmetic on a nil value (field 'x')
```

**Expected result:**

The focused floating client should move to the right by 5 pixels

**Comment by Elv13** [comment]
Hello,

Your keybinding looks to be in the global section. They don't have a `c` argument. `c` is the client object while `client` is the class. A class has no geometry so `nil` is to be expected. If you do

    awful.key({ modkey }, "o", function(c) c.x = c.x + 5 end),

and place the client in the `clientkeys` section, then it will work.
