### ISSUE TITLE
Multiple borders (like 2bwm)?

### ISSUE THREAD

**Issue by furrycatherder** [awesomeWM/awesome#2637]
Is this currently possible?
Could we have support for arbitrarily nested borders? (Gradients?)

**Comment by Elv13** [comment]
Yes, but the API is a bit ugly. You can create titlebars on each side and put whatever widgets you want in them.

If you press "load more" here https://github.com/awesomeWM/awesome/issues/1395, you will see some configs with such borders

**Comment by psychon** [comment]
Here is some two years old hack that I wrote back then to show to Elv13 that this is already possible in Lua via titlebars:
https://gist.github.com/psychon/ed4436cd5ad36da57c6dd81c69ac8e1c
It produces something like this:
![foo](https://user-images.githubusercontent.com/89482/52327647-1fdbd780-29ed-11e9-87f5-7e004dfb5a97.png)
However, this is not something one wants to hack together `rc.lua`.

So, yes, this is already possible, no, you do not want to do it.

(Side note: No idea what kind of multiple borders 2bwm does)

**Comment by furrycatherder** [comment]
Okay, forget the part about gradients. I think what I really want is multiple discrete borders that can connect to different events like focused, marked, tagged, etc., and they can vary their color/size inside the callback function.

Could there be e.g. gears.accent and things like titlebar:setup and wibar:setup would accept an accents field? So this could be applied also to things like menus, bars, etc?

**Comment by actionless** [comment]
elv already suggested you to visit Screenshot topic and look for examples

and actually his own last post there is using such technique :-) https://github.com/awesomeWM/awesome/issues/1395#issuecomment-457876086  (first border is gray, second border is black)

or, somewhere in the middle there is my example (https://github.com/awesomeWM/awesome/issues/1395#issuecomment-272626479, https://github.com/actionless/awesome_config/blob/devel/actionless/titlebar.lua)), but elv's code is using default rc.lua as a base so it will be easier for you to adapt for your usecase

**Comment by alfunx** [comment]
I recently experimented with that as well, though not really in depth (plain aesthetics, no additional features as provided by 2bwm, though that is fairly easy to implement):

![screenshot](https://i.imgur.com/Usa262I.png)

Basically what Elv suggested, 4 titlebars, one on each side. In the screenshot above, the real borders are black. (Relevant parts in my config: https://github.com/alfunx/.dotfiles/blob/master/.config/awesome/themes/blackout/theme.lua#L914)

**Comment by SkyyySi** [comment]
Just wondering, what was the solution? Can anyone provide me an example?
