### ISSUE TITLE
Add more code to config.ld so all the ":" vs "module." issues go away.

### ISSUE THREAD

**Issue by Elv13** [awesomeWM/awesome#2640]
In the category of "known for eternity but nobody acted ever upon it", there is ~150 place in the doc where `ldoc` mistook "real" module level function from methods. Mitigation often include adding a `@class` and `@function`. Even there it still have issue. `ldoc` allows to provide a custom `custom_display_name_handler`. We already do, but we could extend it to be smarter about this issue.

Upstream is dead, so just like LGI, we are on our own.

**Comment by psychon** [comment]
Hey, LGI is not all that dead! I try to keep the lights on there!
