### ISSUE TITLE
awesome-copycats - how to on debian 9?

### ISSUE THREAD

**Issue by s1ranger** [awesomeWM/awesome#2645]
Hello! Help me, please!
I meet with Linux through Debian 9. I installed base Debian 9 without GUI, with Xorg and Awesome WM.
What I need to install for work "awesome-copycats" theme? When I start a theme, I have error 
https://drive.google.com/open?id=16q4oigGgn-WA5ZFykNtaajHd3c7BqWdm

Output of `awesome --version`:
awesome v4.0 (Harder, Better, Faster, Stronger)
 • Compiled against Lua 5.1.5 (running with Lua 5.1)
 • D-Bus support: ✔
 • execinfo support: ✔
 • RandR 1.5 support: ✔
 • LGI version: 0.9.1

uname - a
Linux Alex 4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64 GNU/Linux

lua -v
Lua 5.1.5

lua -e 'print(package.cpath)'
./?.so;/usr/local/lib/lua/5.1/?.so;/usr/lib/x86_64-linux-gnu/lua/5.1/?.so;/usr/lib/lua/5.1/?.so;/usr/local/lib/lua/5.1/loadall.so

**Comment by Elv13** [comment]
You need to install a newer version of Awesome -or- use an older version of awesome-copycats -or- upgrade to Debian Buster (enters features_freeze/alpha tomorrow).

The current version of Awesome is v4.3

**Comment by s1ranger** [comment]
> The current version of Awesome is v4.3

 Many thanks indeed for your help! I upgraded Awesome to 4.3 and it`s work great!
