### ISSUE TITLE
Duplicate tags on multiple displays

### ISSUE THREAD

**Issue by Ladone** [awesomeWM/awesome#2666]
Output of `awesome --version`:

awesome v4.2 (Human after all)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.5
 • LGI version: 0.9.2

**How to reproduce the issue:**

```
awful.screen.connect_for_each_screen(function(s)
    -- Wallpaper
    set_wallpaper(s)

    -- Each screen has its own tag table.
    -- {{ Tags
    tags = {
      names = {"main", "web", "dev", "tools", "chat", "etc"},
      layout = {
        awful.layout.layouts[2],
        awful.layout.layouts[4],
        awful.layout.layouts[4],
        awful.layout.layouts[4],
        awful.layout.layouts[4],
        awful.layout.layouts[1],
        --awful.layout.layouts[1],
        --awful.layout.layouts[1],
        --awful.layout.layouts[1],
      }
    }

    -- Each screen has its own tag table.
    for s = 1, screen.count() do
      -- Each screen has its own tag table.
      tags[s] = awful.tag(tags.names, s, tags.layout)
    end--]]
```

**Actual result:**
http://i.imgur.com/GY5vDvd.png

**Expected result:**

http://i.imgur.com/kk8ZaK3.png

**Comment by Veratil** [comment]
You are adding the tags twice (with two screens). It'd be three times with three screens.

Check out the [default config](https://github.com/awesomeWM/awesome/blob/master/awesomerc.lua#L186) for how to add the tags. :)

**Comment by Ladone** [comment]
Delete loop, and work. :) Thanks.
