### ISSUE TITLE
Using workarea in layouts

### ISSUE THREAD

**Issue by jcrd** [awesomeWM/awesome#2676]
Output of `awesome --version`:
```
awesome v4.3-81-gddf422dd0-dirty (Too long)
 • Compiled against Lua 5.1.4 (running with LuaJIT 2.0.5)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
```

**How to reproduce the issue:**

Add a tag using the following layout to the default `rc.lua`:
```
local testlayout = {}

testlayout.tile = {}
testlayout.tile.name = "testlayout"

function testlayout.tile.arrange(p)
    local g = {
        x = p.workarea.x,
        y = p.workarea.y,
        width = p.workarea.width,
        height = p.workarea.height,
    }
    for _, c in ipairs(p.clients) do
        p.geometries[c] = g
    end
end

return testlayout
```
Then open a few instances of `termite` with that tag and cycle focus through them.

**Actual result:**

Testing in a 1600x900 Xephyr display yields these geometries:
```
1594x864
1596x866
1598x868
```
Each client's width and height differ by 2.

**Expected result:**

Client geometries equal to the workarea.

Defining the `g` variable inside the loop works as expected...
```
function testlayout.tile.arrange(p)
    for _, c in ipairs(p.clients) do
        local g = {
            x = p.workarea.x,
            y = p.workarea.y,
            width = p.workarea.width,
            height = p.workarea.height,
        }
        p.geometries[c] = g
    end
end
```

**Comment by alfunx** [comment]
The problem is that you have a single geometry object `g` for all clients. The geometry is adjusted (for gaps and border width) before the clients are set to the given geometry. If you have 3 clients, that geometry object `g` is adjusted 3 times, so you end up with 3 clients having different sizes.

https://github.com/awesomeWM/awesome/blob/master/lib/awful/layout/init.lua#L228-L242

**Comment by jcrd** [comment]
Thanks for the explanation. It seems so obvious in retrospect.
