### ISSUE TITLE
drawable:find_widgets() returning an empty table

### ISSUE THREAD

**Issue by unai-ndz** [awesomeWM/awesome#2686]
I actually don't know if this is a bug or I'm doing something wrong.

Output of `awesome --version`:

Tested on:

```
awesome v4.3 (Too long)
 • Compiled against Lua 5.3.5 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
```

and

```
awesome v4.3-89-g3cc364ce (Too long)
 • Compiled against Lua 5.3.5 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
```

**How to reproduce the issue:**

Starting from the default configuration add this keybind:
```
        awful.key({ modkey, "Control", }, "a", function ()
            notification = naughty.notify({
                title = "NOTIF",
                text = tostring(table.maxn(wibox.drawable:find_widgets(mouse.coords().x, mouse.coords().y))),
                timeout = 4,
                replaces_id = last_notification_id
            })

            for key, value in pairs(wibox.drawable:find_widgets(mouse.coords().x, mouse.coords().y)) do
                notification = naughty.notify({
                    title = "NOTIF",
                    text = tostring(key) .. " - ".. tostring(value),
                    timeout = 4,
                    replaces_id = last_notification_id
                })
            end
            end),
```
Press the keybind moving the mouse all over the wibar/clients.

**Actual result:**

The first notification prints 0.0 and the ones in the loop don't show at all because :find_widgets returns an empty table. (afaik)

**Expected result:**

:find_widgets returns the table filled.

The actual code i want to use:

```
local progbar = wibox.widget{
    max_value     = 1,
    forced_height  = 3,
    forced_width  = 100,
    widget        = wibox.widget.progressbar
}

progbar:connect_signal("button::press", function(lx, ly, button, mods, find_widgets_result)
    if button == "1" then
        seek_song_pos = find_widgets_result.widget_height / find_widgets_result.ly;
        awful.spawn("mpc seek " .. tostring(seek_song_pos) .. "%")
    end
end)
```

**Comment by psychon** [comment]
```lua
wibox.drawable:find_widgets([stuff])
```
Uhm. What do you think this is doing?

`:find_widgets` needs to be called on an actual instance of a drawable / wibox. The argument is a relative position inside the wibox (while the mouse cursor is an absolute position on the root window and not relative to the top-left corner of a wibox).

> The actual code i want to use:

Okay, then what's up with the code above?

Anyway:

- The widget is passed in as the first argument to the signal, so all your arguments are off by one
- Button is a number, not a string
- There is no `find_widgets_result.ly`, but I guess you mean just `ly`
- Your math to calculate a percentage is the wrong way around

This works for me with the default config:
```lua
mytextclock:connect_signal("button::press", function(_, lx, ly, button, mods, find_widgets_result)
    if button == 1 then
        seek_song_pos = 100 * ly / find_widgets_result.widget_height;
        naughty.notify{ text = tostring(seek_song_pos) .. "%" }
    end
end)
```

**Comment by unai-ndz** [comment]
> Okay, then what's up with the code above?

Just me trying to understand this.

Well, thanks for your time, i was strugling with this.
