### ISSUE TITLE
Additional layoutlist styling option

### ISSUE THREAD

**Issue by tograne** [awesomeWM/awesome#2688]
Output of `awesome --version`:

awesome devel (Too long)
 • Compiled against Lua 5.3.5 (running with Lua 5.3)
 • D-Bus support: ✘
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2

I'm on freebsd and the output of "pkg info awesome" tells me that I'm running 4.3,1 rather than devel

I would like to know if it's possible to set up the layoutlist widget so that all not-used layouts are dimmed or transparent in some way while the selected layout isn't dimmed, I found that it is possible to do this to text in the widget using beautiful.layoutlist_fg_normal and beautiful.layoutlist_fg_selected, but I'd like to hide text and do it to the icons

I've attached a screenshot of my current awesome desktop with a customized layoutbox widget that I hacked together during the 3.x days and have kept working, it's in the top right just to the left of the clock. With the introduction of the layoutlist widget and the fact that it does exactly what I want but better and cleaner, I want to switch over to it and have it behave the same way as my old custom widget setup

![2019-02-20-223646_2560x1440_scrot](https://user-images.githubusercontent.com/47842022/53144150-0614c580-3593-11e9-9afa-359f5d40e39d.png)

**Comment by psychon** [comment]
> awesome devel (Too long)
>
> I'm on freebsd and the output of "pkg info awesome" tells me that I'm running 4.3,1 rather than devel

This is off-topic, but: Could FreeBSD please use https://github.com/awesomeWM/awesome/releases/download/v4.3/awesome-4.3.tar.xz or https://github.com/awesomeWM/awesome/releases/download/v4.3/awesome-4.3.tar.bz2 instead of the automatically-generated https://github.com/awesomeWM/awesome/archive/v4.3.tar.gz from GitHub?  Alternatively, they could at least pass in `-DOVERRIDE_VERSION=4.3` in the build to hide the difference between the two... :-/

**Comment by actionless** [comment]
i think @Elv13 layoutlist-popup should do that

**Comment by Elv13** [comment]
Sorry, I didn't notice this issue before.

This can be done using the `widget_template` property and the `update_callback` that goes with it. All widgets have an `opacity` property.

**Comment by psychon** [comment]
It took me way too long to figure this out. The layoutlist does not use the layout object as "object", but some object that it only creates in `reload_cache`. Thanks to this, all the caching that `awful.widget.common` does, does not work (because the object in the cache is already gone and was replaced with an identical one).
Anyway, here is a starting point for @tograne (or actually, this already does everything he wants to do, assuming he also removes the icons?)
```diff
diff --git a/awesomerc.lua b/awesomerc.lua
index fa584b8a8..4a8ead15b 100644
--- a/awesomerc.lua
+++ b/awesomerc.lua
@@ -214,6 +214,48 @@ awful.screen.connect_for_each_screen(function(s)
     -- Create the wibox
     s.mywibox = awful.wibar({ position = "top", screen = s })
 
+    local dpi = require("beautiful").xresources.apply_dpi
+
+    -- Sigh. The layoutlist does not update widgets, it just recreates them.
+    local function set_transp(widget, lay)
+        local is_active = awful.layout.get(s) == lay.layout
+        widget.opacity = is_active and 1 or 0.5
+    end
+
+    s.mylayoutlist = awful.widget.layoutlist{
+        screen = s,
+
+        widget_template = {
+            id = 'background_role',
+            widget = wibox.container.background,
+            {
+                widget = wibox.layout.fixed.horizontal,
+                fill_space = true,
+                {
+                    id = 'icon_margin_role',
+                    widget = wibox.container.margin,
+                    {
+                        id = 'icon_role',
+                        widget = wibox.widget.imagebox,
+                        left = dpi(4),
+                    },
+                },
+                {
+                    id = 'text_margin_role',
+                    widget = wibox.container.margin,
+                    left = dpi(4),
+                    right = dpi(4),
+                    {
+                        id = 'text_role',
+                        widget = wibox.widget.textbox,
+                    },
+                }
+            },
+            update_callback = set_transp,
+            create_callback = set_transp,
+        }
+    }
+
     -- @DOC_SETUP_WIDGETS@
     -- Add widgets to the wibox
     s.mywibox:setup {
@@ -227,6 +269,7 @@ awful.screen.connect_for_each_screen(function(s)
         s.mytasklist, -- Middle widget
         { -- Right widgets
             layout = wibox.layout.fixed.horizontal,
+            s.mylayoutlist,
             mykeyboardlayout,
             wibox.widget.systray(),
             mytextclock,
```
