### ISSUE TITLE
How to make the window transparent/opacity when you press the keys?

### ISSUE THREAD

**Issue by D1mon** [awesomeWM/awesome#2694]
Output of `awesome --version`:
awesome v4.3 (Too long)
 • Compiled against Lua 5.3.5 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2

wrote the pseudocode of what i want to get:
```
awful.key({ modkey }, "a", function() window.opacity += 0.1 end, ...
awful.key({ modkey }, "s", function() window.opacity -= 0.1 end, ...
```
the window in focus changed transparency

**Comment by psychon** [comment]
Lua does not have a `+=` operator. Still, your pseudocode is almost there:
```lua
function(c) c.opacity = c.opacity + 0.1 end
end
```
(I also used the client argument that clientkeys get; you might use `client.focus` instead if you want)

**Comment by D1mon** [comment]
I wrote that this is not a code on a lua, but pseudocode.
I tried what you wrote did not work. can you write the code completely?

**Comment by actionless** [comment]
show your usage example in which it didn't worked

**Comment by alfunx** [comment]
You should move those bindings to the `clientkeys` table in your `rc.lua` if you want to use that function, as he mentioned. Otherwise go for

```lua
function()
    local c = client.focus
    if c then c.opacity = c.opacity + 0.1 end
end
```

**Comment by D1mon** [comment]
```
clientkeys = my_table.join(
awful.key({ modkey }, "a",
    function()           
        local c = client.focus                                            
        if c then c.opacity = c.opacity - 0.1 end
    end,                    
    {description = "decrease window opacity(transparency)"}),
)
```

@alfunx Thank you so much. Everything worked out.

**Comment by alfunx** [comment]
Since you moved it to the `clientkeys` table, the function @psychon provided should work (and is much cleaner).

**Comment by D1mon** [comment]
@alfunx also works.

**Comment by D1mon** [comment]
when minimizing and restoring the program window (yakuake - F12), the transparency settings are reset. How can I fix this?

**Comment by alfunx** [comment]
Sounds like that window is not actually minimized but closed. Can you show us the binding for `F12`?

**Comment by D1mon** [comment]
`F12 -> Open/Restart Yakuake`
but all the tabs and documents remain and are not closed. most likely it is a translation error or incorrect interpretation of the function. Because the program is not really restarted. It should sound like this: "Show and Hide Yakuake"
in the most awesomewm there is not any binding, just run /usr/bin/yakuake

**Comment by elenapan** [comment]
Try this keybind:
```
awful.key({ superkey }, "a",
    function(c)
        c.opacity = c.opacity + 0.1
        -- Save Yakuake opacity
        if c.class == "Yakuake" then
            last_yakuake_opacity = c.opacity
        end
    end
end,
{description = "decrease client opacity", group = "client"}),
```

And add this to your rules:
```
-- Restore Yakuake opacity
{ rule_any = { class = { "Yakuake" } }, nil,
    callback = function (c)
        c.opacity = last_yakuake_opacity
    end
},
```
Check with `xprop` if the class is actually called "Yakuake" and change it if needed.

**Comment by D1mon** [comment]
@elenapan works. thank
