### ISSUE TITLE
How i can Autostrat apps

### ISSUE THREAD

**Issue by Ladone** [awesomeWM/awesome#2695]
Tell me please detailed autostart application when system is loading? Thanks!

**Comment by alfunx** [comment]
There are a few options:

+ [Use `awful.spawn.once` in your `rc.lua`](https://awesomewm.org/apidoc/libraries/awful.spawn.html#once)
  + [Or `awful.spawn.single_instance` depending on your use case](https://awesomewm.org/apidoc/libraries/awful.spawn.html#single_instance)
+ Start the applications in `.xinitrc` (or `.xprofile` if you use a display manager)
+ Start the application using a systemd service

For more, consider [the Arch Wiki](https://wiki.archlinux.org/index.php/Autostarting)

**Comment by blueyed** [comment]
I consider this to be answered, thanks!

**Comment by Ladone** [comment]
It's not work for me:

awful.spawn.once("Dropbox")
attempt to call a nil value (field 'once')

**Comment by alfunx** [comment]
Forgot to mention, `awful.spawn.once` requires `v4.3`.

**Comment by Ladone** [comment]
@alfunx are there alternatives?

**Comment by psychon** [comment]
`awful.spawn("dropbox")`?

**Comment by Ladone** [comment]
@psychon This method not check duplicate applications if application take care about it.
