### ISSUE TITLE
Doc generation has regressed

### ISSUE THREAD

**Issue by Elv13** [awesomeWM/awesome#2700]
### v4.3

![screenshot_20190224_130149](https://user-images.githubusercontent.com/340384/53303099-6d04d980-3834-11e9-8cf1-72029a53b73f.png)

### master

![screenshot_20190224_130134](https://user-images.githubusercontent.com/340384/53303100-72622400-3834-11e9-924b-5bda48bd1146.png)

Some markdown content is no longer interpreted. Note that `ldoc` has multiple backends and it might have fallen back to the incomplete built-in fallback. I did not investigate.

**Comment by psychon** [comment]
Cannot reproduce locally with current master (commit d119a9a20a53af9d3197f7bd1458dbf1463212ec). Yay, this will be fun to debug.

**Comment by blueyed** [comment]
Links for reference:
stable (OK): https://awesomewm.org/doc/api/libraries/awful.spawn.html
master (broken): https://awesomewm.org/apidoc/libraries/awful.spawn.html

**Comment by blueyed** [comment]
Is it only about the trailing "==="?

**Comment by Elv13** [comment]
> Is it only about the trailing "==="?

Most probably not, but we use very few markdown extensions that are rendered differently by the different backends. This one is the only available syntax for sections within the header, `#` isn't allowed.

**Comment by blueyed** [comment]
Regressed/changed in aa16d77d1.

apidoc change: https://github.com/awesomeWM/apidoc/commit/219d56bf94adc57e0a2cd778970a1ae6c437f751#diff-151ca69003f7e7d77eddc4c6216ce4dbR187.

**Comment by blueyed** [comment]
Ah.. there this was added: https://github.com/awesomeWM/awesome/commit/aa16d77d157cd2e9651c3435a5dd6515934d20fb#diff-5e9f05df3207ebe7ffedc0fc2a164063R11 (I've assumed that something like `=== FAQ ===` was rendered wrong).

Cannot reproduce it locally myself, so likely due to some package being available there, but not on Travis?!

**Comment by blueyed** [comment]
Looks like a diff with how the stable docs are built via how they are built from master after all.

**Comment by blueyed** [comment]
Findings:

1. having the `discount` rock (0.4-1) installed turns the `<h1>` into a `<h2>` for me.
2. I can reproduce it when using `lua-discount` (1.2.10.1-1).  This is installed for the "awesome" repo (apidoc), but not awesome-www, so this seems to explain it.  lua-discount was updated 4 years ago, discount appears to be more recent, so we should switch to it instead I think.

**Comment by blueyed** [comment]
For awesome-www: install discount: https://github.com/awesomeWM/awesome-www/pull/138

**Comment by blueyed** [comment]
For awesome (apidoc): use discount instead of lua-discount: https://github.com/awesomeWM/awesome/pull/2707
