### ISSUE TITLE
keygrabber: Setup multiple keygrabbers

### ISSUE THREAD

**Issue by alfunx** [awesomeWM/awesome#2712]
If you set up multiple keygrabbers, only the first one seems to be used. The first keygrabber has `Mod4+a` as `root_keybinding`, the second one has `Mod4+b`. The first one works as expected. However if you press `Mod4+b` for the second one (while the first keygrabber is **not** running), the first keygrabber is started and the notifications for the first one are shown. I'm not sure if I'm using it correctly though, and didn't yet look at the code of `awful.keygrabber`.

Append to the default `rc.lua`:

```lua
local a = awful.keygrabber {
    stop_key = "Escape",
    start_callback = function() naughty.notification { message = "start 1" } end,
    stop_callback  = function() naughty.notification { message = "stop 1"  } end,
    root_keybindings = {
        { { "Mod4" }, "a", function() end },
    },
    keybindings = {
        { {        }, "x", function()
            naughty.notification { message = "in grabber 1" }
        end },
    },
}

local b = awful.keygrabber {
    stop_key = "Escape",
    start_callback = function() naughty.notification { message = "start 2" } end,
    stop_callback  = function() naughty.notification { message = "stop 2"  } end,
    root_keybindings = {
        { { "Mod4" }, "b", function() end },
    },
    keybindings = {
        { {        }, "x", function()
            naughty.notification { message = "in grabber 2" }
        end },
    },
}
```

By the way, if `function() end` is omitted in the `root_keybindings` is omitted, the keygrabber is not triggered (the example for modal keybindings in the docs suggests this should work).

**Comment by Elv13** [comment]
That's currently a non-feature. A keygrabber grabs the input. That includes grabbing the input away from another keygrabber.

That being said, adding support for "keygrabber groups" isn't out of the question. I don't plan to do it myself, but if you jump into the code, I am sure you can come up with a patch for this rather easily. The current default behavior has to be preserved, but this could be a new option. There's definitely valid use cases for this. That should simply be added by looping all keygrabbers in a group in `keygrabber.lua: local function runner(self, modifiers, key, event)` and adding the `group` (string) propety + black magic to internally keep the list of grabers "alive" (table `{__mode = 'v'}`) in each group.

**Comment by alfunx** [comment]
> A keygrabber grabs the input. That includes grabbing the input away from another keygrabber.

Sorry, realized that I was probably not precise enough. The second keygrabber is *never* available. If you try to start the second keygrabber with `Mod4+b` (while the first one is **not** running) the notifications for the first one are displayed.

Or in other words: Does `awesome.keygrabber()` create "keygrabber objects", or is there only a single keygrabber available?

**Comment by Elv13** [comment]
> Or in other words: Does awesome.keygrabber() create "keygrabber objects", or is there only a single ("global") keygrabber available?

`awsome.keygrabber` is a singleton. `awful.keygrabber` attempt to "emulate" objects on top of this. If only one `awful.keygrabber` can exist and the second never, ever, works, it is a bug. If a second keygrabber isn't available while another one is active, it is not a bug.

**Comment by alfunx** [comment]
Oops, supposed to be `awful.keygrabber` (not `awesome.keygrabber`).

>  If only one `awful.keygrabber` can exist and the second never, ever, works, it is a bug.

That's the case.

**Comment by ndgnuh** [comment]
Sorry for digging this up. I have just moved my config to git version because of this issue.

Just a note for if someone happens to meet the same problem. If you are using the git version `keygrabber`, setting the keys by `awful.keyboard.append_global_keybinding` must be used, else the global keys won't work.

Here's a MWE to reproduce (please run in Xephyr since I didn't include a way to restart in case keybinding fails). 
```lua
local awful = require("awful")
local naughty = require("naughty")
local beautiful = require("beautiful")
local gears = require("gears")

local function dump(msg)
  return function()
    naughty.notification {title = "Debug", message = msg}
  end
end

beautiful.init(gears.filesystem.get_themes_dir() .. "default/theme.lua")

awful.screen.connect_for_each_screen(function(s)
  gears.wallpaper.set("#FFF")
  awful.tag({1})
  dump("Just to know that this worked")()
end)

local modkey = "Mod1"

local globalkeys = gears.table.join(
                     awful.key({modkey}, "a", dump("Global key")),
                     awful.key({modkey}, "r", awesome.restart))

-- this one produce the error
root.keys(globalkeys)
-- this one doesn't
-- awful.keyboard.append_global_keybinding(globalkeys)

awful.keygrabber {
  keybindings = {{{modkey}, "s", dump("Grabber 1")}},
  stop_key = {"Escape", modkey, "Alt_L"},
  stop_event = "release",
  export_keybindings = true
}

awful.keygrabber {
  keybindings = {{{modkey}, "d", dump("Grabber 2")}},
  stop_key = {"Escape", modkey, "Alt_L"},
  stop_event = "release",
  export_keybindings = true
}
```

Output of `awesome --version`
```bash
awesome v4.3-900-g4319b161-dirty (Too long)
 • Compiled against Lua 5.1.4 (running with LuaJIT 2.1.0-beta3)
 • API level: 4
 • D-Bus support: yes
 • xcb-errors support: no
 • execinfo support: yes
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
 • Transparency enabled: yes
 • Custom search paths: no
```
