### ISSUE TITLE
Theme Popup

### ISSUE THREAD

**Issue by Ladone** [awesomeWM/awesome#2718]
Output of `awesome --version`:

awesome v4.3 (Too long)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2

How I can theme popup blocks? Thanks!

**Comment by Elv13** [comment]
Please be more specific

**Comment by Ladone** [comment]
I want to customize popup when i get message from Skype, Discord or other programs.

**Comment by actionless** [comment]
see theme variables for `naughty`, awesomewm notification system:
https://awesomewm.org/doc/api/libraries/naughty.html
