### ISSUE TITLE
How to hide some systray icons?

### ISSUE THREAD

**Issue by funivan** [awesomeWM/awesome#2742]
Can I hide some system tray icons by conditions? 

```
awesome v4.3 (Too long)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
```

**Comment by psychon** [comment]
Nope.

What systray icon is the problem? Can whatever creates those icons be told not to do so? Usually, that's possible.

**Comment by funivan** [comment]
I'm using enpass password manager and I can't hide icon. Already communicate with the team. 
Can I change the icon in the system tray?

**Comment by psychon** [comment]
The C code only gives the number of systray icons to Lua code (so that enough space can be allocated). Nothing more than that. There is no way to interact with individual icons in any way right now. It's not even possible to change the order of icons. Sorry.

**Comment by achuhlomin** [comment]
@funivan perhaps it's not a perfect solution but you can play with an icon. Just find it in your system and replace=)
`locate enpass-status`

**Comment by efaulhaber** [comment]
Can we make this a feature request? I'd like to hide the Zoom logo, and there seems to be no setting in Zoom to do so.

**Comment by actionless** [comment]
@efaulhaber https://github.com/awesomeWM/awesome/issues/2742#issuecomment-480497617

**Comment by efaulhaber** [comment]
Which C code would have to be changed? Is it not Awesome's code?

**Comment by actionless** [comment]
@efaulhaber other wms implement it by creating special sorta micro-compositor (think of picom) just for the tray

as far as i know, no one here wants doing that great amount of work, but if you're feeling what you interested in that and willing to write test-covered code for that - i think it have high chances to be merged (especially if it would have some option to disable that code branch)

**Comment by actionless** [comment]
btw, mb you'll get better chances having it a feature of picom, to composite not only windows, but also tray items

**Comment by efaulhaber** [comment]
Alright, thanks for the answers. When you say third-party tray app, are you talking about something like stalonetray?

**Comment by actionless** [comment]
i can't recommend one because i never tried those myself - but youl'l go through other issues with the same labels you could see some advices from the people
