### ISSUE TITLE
[awesome-client] error() handling

### ISSUE THREAD

**Issue by SoniEx2** [awesomeWM/awesome#2747]
Output of `awesome --version`:

```
$ awesome --version
awesome v4.3 (Too long)
 • Compiled against Lua 5.3.5 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
```

**How to reproduce the issue:**

`awesome-client "error()"`

**Actual result:**

```
Oops, an error happened!
/usr/share/awesome/lib/awful/remote.lua:28: attempt to concatenate a nil value (field '?')
```

**Expected result:**

```
   string "Error during execution: (error object is a nil value)"
```

**Comment by psychon** [comment]
>    string "Error during execution: (error object is a nil value)"

Sorry, but... what? Why do you want `error object is a nil value`? And why do you want this specific error?

For example, with `/usr/bin/lua`, I get:
```
$ lua
Lua 5.2.4  Copyright (C) 1994-2015 Lua.org, PUC-Rio
> error()
> 
```
So, I'd say that your call to `error` is wrong. What do you say?

**Comment by SoniEx2** [comment]
```
$ lua
Lua 5.3.4  Copyright (C) 1994-2017 Lua.org, PUC-Rio
> error()
(error object is a nil value)
stack traceback:
	[C]: in function 'error'
	stdin:1: in main chunk
	[C]: in ?
> 
```

Anything would be better than the red persistent notification thing.

**Comment by SoniEx2** [comment]
okay I'm lying this isn't really Lua:

```
$ lua
Lua 5.3.4  Copyright (C) 1994-2017 Lua.org, PUC-Rio
> t = {[table]=table}
> t:[table].insert("foo")
> t[1]
foo
> 
```

but vanilla Lua 5.3 has this exact same behaviour and it's even documented in the reference manual: http://www.lua.org/manual/5.3/manual.html#7

> In case of unprotected errors in the script, the interpreter reports the error to the standard error stream. If the error object is not a string but has a metamethod `__tostring`, the interpreter calls this metamethod to produce the final message. Otherwise, the interpreter converts the error object to a string and adds a stack traceback to it.

Previously, in Lua 5.2, it said:

> In case of unprotected errors in the script, the interpreter reports the error to the standard error stream. If the error object is a string, the interpreter adds a stack traceback to it. Otherwise, if the error object has a metamethod `__tostring`, the interpreter calls this metamethod to produce the final message. Finally, if the error object is **nil**, the interpreter does not report the error.

Note the subtle difference on handling of nil.
