### ISSUE TITLE
 "beautiful.xresources.get_dpi()" attempt to index a nil value (gloabl "beautiful")

### ISSUE THREAD

**Issue by wxg4net** [awesomeWM/awesome#276]
ver: awesome-git 

<pre>
Error while creating menu entry: /usr/share/awesome/lib/wibox/widget/textbox.lua:135: attempt to index a nil value (field 'xresources')
Error while creating menu entry: /usr/share/awesome/lib/wibox/widget/textbox.lua:135: attempt to index a nil value (field 'xresources')
W: awesome: luaA_dofunction:77: error while running function
stack traceback:
	/usr/share/awesome/lib/wibox/widget/textbox.lua:135: in function </usr/share/awesome/lib/wibox/widget/textbox.lua:125>
	(...tail calls...)
	/usr/share/awesome/lib/naughty.lua:372: in function 'naughty.notify'
	/etc/xdg/awesome/rc.lua:31: in function </etc/xdg/awesome/rc.lua:26>
	[C]: in metamethod '__index'
	/usr/share/awesome/lib/wibox/widget/textbox.lua:135: in function </usr/share/awesome/lib/wibox/widget/textbox.lua:125>
	(...tail calls...)
	/usr/share/awesome/lib/awful/widget/keyboardlayout.lua:56: in function 'awful.widget.keyboardlayout.new'
	/usr/share/awesome/lib/awful/widget/keyboardlayout.lua:95: in field 'keyboardlayout'
	/etc/xdg/awesome/rc.lua:115: in main chunk
error: /usr/share/awesome/lib/wibox/widget/textbox.lua:135: attempt to index a nil value (field 'xresources')
error while running function
stack traceback:
	/usr/share/awesome/lib/wibox/widget/textbox.lua:135: in function </usr/share/awesome/lib/wibox/widget/textbox.lua:125>
	(...tail calls...)
	/usr/share/awesome/lib/awful/widget/keyboardlayout.lua:56: in function 'awful.widget.keyboardlayout.new'
	/usr/share/awesome/lib/awful/widget/keyboardlayout.lua:95: in field 'keyboardlayout'
	/etc/xdg/awesome/rc.lua:115: in main chunk
error: /usr/share/awesome/lib/wibox/widget/textbox.lua:135: attempt to index a nil value (field 'xresources')
E: awesome: main:557: couldn't find any rc file
W: awful: function is deprecated, see gears.timer
stack traceback:
	/usr/share/awesome/lib/awful/util.lua:38: in function 'awful.util.deprecate'
	/usr/share/awesome/lib/awful/init.lua:14: in function 'timer'
	/usr/share/lua/5.3/vicious/init.lua:120: in upvalue 'regregister'
	/usr/share/lua/5.3/vicious/init.lua:167: in function 'vicious.register'
	/home/wxg/.config/awesome/rc.lua:203: in main chunk
W: awesome: a_glib_poll:240: Last main loop iteration took 0.137574 seconds! Increasing limit for this warning to that value.

</pre>

**Comment by actionless** [comment]
can you please paste the full stack trace?

**Comment by wxg4net** [comment]
updated

**Comment by actionless** [comment]
looks like this one: https://github.com/awesomeWM/awesome/issues/244
