### ISSUE TITLE
Question: How to get an "empty" client space

### ISSUE THREAD

**Issue by lukasbash** [awesomeWM/awesome#2760]
Output of `awesome --version`:

awesome v4.3 (Too long)
 • Compiled against Lua 5.3.5 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2

A very short question:
How can I get an empty client space, following the current tiling scheme?
Given I have the layout `awful.layout.suit.fair` and I want to have a gap like this:

```
-------------------------
|           |           |
-------------------------
|           |   empty   |
-------------------------
```

How can I achieve this?

**Comment by Elv13** [comment]
Unless you write your own layout or use an external layout module, you can't. The default layout engine is stateless and half the API it uses for building the layout is in C and can't easily be monkey-patched.

My `dynamite` module can do this using the `dynamite.widget.placeholder` (or even a normal `wibox.widget`). See the documentation:

https://elv13.github.io/libraries/dynamite.html

The most recent version is in the `doc_tests_and_notif` branch of my fork. It's rather usable, but only a drop-in replacement for ~95% of the default engine behavior.
