### ISSUE TITLE
float=true rule for Kupfer sends client to background

### ISSUE THREAD

**Issue by LindyBalboa** [awesomeWM/awesome#2765]
So I have found a curious edge case. I tried setting the rules for [Kupfer](https://github.com/kupferlauncher/kupfer) explicitly and it resulted in it getting sent to the bottom layer (as seen through a transparent terminal) after the second+ call to Kupfer. The first call shows up normally. Restarting Awesomewm results in the first call showing up as it should, but subsequent calls show up on the bottom. Clearly the temporary solution is not to explicitly set `ontop` but I feel this might be exposing a deeper bug.

Output of `awesome --version`:
```
awesome v4.3 (Too long)
 • Compiled against Lua 5.3.5 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
```

**How to reproduce the issue:**
Add the following rule to rc.lua
```
    { rule = {class = "Kupfer.py"},
		properties = {
			floating = true, -- This enabled causes Kupfer to be sent to back
			ontop = true
			}
	},
```

**Actual result:**
![image](https://user-images.githubusercontent.com/20605205/57568582-cb7c3580-73e9-11e9-9363-5f5fead9189e.png)

**Expected result:**
![image](https://user-images.githubusercontent.com/20605205/57568598-e8b10400-73e9-11e9-90f8-edfefe3a330a.png)

rc.lua:
https://pastebin.com/raw/yTHUmDeL

.xinitrc:
https://pastebin.com/raw/rm5N4YQ0

xprop of offending window:
https://pastebin.com/raw/gzPTVeF3

**Comment by psychon** [comment]
> How to reproduce the issue:
> Add the following rule to rc.lua
> 
>     { rule = {class = "Kupfer.py"},
> 		properties = {
> 			floating = true, -- This enabled causes Kupfer to be sent to back
> 			ontop = true
> 			}
> 	},


Well... and then? I added that to the config and started kupfer. Then, kupfer disappeared. When clicking on its tray icon, it appears again. And it does appear above xterm. Each time.

What am I doing wrong/right?

**Comment by LindyBalboa** [comment]
Turns out it was a bug elsewhere in my config where I was using the `client:raise()` function. It just so happened that the first time I noticed it was when using Kupfer because of it's floating nature. Next time I will try to remember to copy the suspect code only into a default config.
