### ISSUE TITLE
Client not being seen by awesome

### ISSUE THREAD

**Issue by Sembiance** [awesomeWM/awesome#2768]
Output of `awesome --version`:
```
awesome v4.3-154-ged0c3ceb-dirty (Too long)
 • Compiled against Lua 5.1.5 (running with Lua 5.1)
 • D-Bus support: ✔
 • xcb-errors support: ✘
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.0
```

**How to reproduce the issue:**

Install the `reicast` emulator program: https://github.com/reicast/reicast-emulator
Launch it, it creates a window.

**Actual result:**

AwesomeWM doesn't seem to "see" the window.
I have a catch all rule:
```
awful.rules.rules = {
  { rule = { }, callback = function(c)
		naughty.notify({ preset = naughty.config.presets.critical,
		  title = "client",
		  text = string.format("%s", c.class) })
	  end }
}
```

**Expected result:**

It never notifies me that the window opened. Similar attempts to target the window via the `class` property also fails. It's like AwesomeWM doesn't see it get created.

The window's `xprop`:

```
WM_NAME(UTF8_STRING) = "reicast git/n - 16.10 (0.00) - 62.09 - V: 31.05 (63.00, PAL480i50.00) R: 0.49+0.00 VTX: 0.00 , MIPS: 0.00"
_NET_WM_DESKTOP(CARDINAL) = 13
_NET_FRAME_EXTENTS(CARDINAL) = 1, 1, 1, 1
WM_STATE(WM_STATE):
        window state: Normal
        icon window: 0x0
awful.client.property.single_instance_id(UTF8_STRING) =
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW
WM_CLASS(STRING) = "reicast"
```

The window's `xwininfo`:
```
wininfo: Window id: 0x2e00002 "reicast git/n - 10.01 (0.00) - 99.89 - V: 49.94 (1.00, PAL480i50.00) R: 49.94+0.00 VTX: 0.00 , MIPS: 0.00"
 
  Absolute upper-left X:  1
  Absolute upper-left Y:  1
  Relative upper-left X:  0
  Relative upper-left Y:  0
  Width: 1198
  Height: 946
  Depth: 24
  Visual: 0x24
  Visual Class: TrueColor
  Border width: 0
  Class: InputOutput
  Colormap: 0x2e00001 (not installed)
  Bit Gravity State: ForgetGravity
  Window Gravity State: NorthWestGravity
  Backing Store State: NotUseful
  Save Under State: no
  Map State: IsViewable
  Override Redirect State: no
  Corners:  +1+1  -3761+1  -3761-973  +1-973
  -geometry 1198x946+0+0
```

It originally didn't have a `WM_CLASS`, so I modified the programs source code to add one, so I could target it. Didn't help. I also have since modified it to have a `WM_HINTS` property as well, that also made no difference.

**Comment by psychon** [comment]
Not much time right now, but
```
_NET_FRAME_EXTENTS(CARDINAL) = 1, 1, 1, 1
awful.client.property.single_instance_id(UTF8_STRING) =
```
both these properties should be set by awesomeWM, so it definitely sees the window.
Also, the `WM_CLASS` value is invalid.
```
WM_CLASS(STRING) = "reicast"
```
I *guess* that your rule causes a Lua error because `c.class` is `nil` and that is why you do not see a popup. Could you try the following rule?
```lua
awful.rules.rules = {
  { rule = { }, callback = function(c)
		naughty.notify({ preset = naughty.config.presets.critical,
		  title = "client",
		  text = "A new client appeared" })
	  end }
}
```

**Comment by Sembiance** [comment]
Thank you!  You are correct and setting the WM_CLASS correctly fixed the problem. Sorry for the bother.

AwesomeWM is AWESOME!

**Comment by Sembiance** [comment]
Oh, by the way, not sure why my config.lua isn't capturing runtime errors. I have this up near the top:
```
do
	local in_error = false
	awesome.connect_signal("debug::error", function (err)
		-- Make sure we don't go into an endless error loop
		if in_error then return end
		in_error = true

		naughty.notify({ preset = naughty.config.presets.critical, title = "Oops, an error happened!", text = err })
		in_error = false
	end)
end
```

Yet no runtime lua errors ever appear.

**Comment by psychon** [comment]
> why my config.lua isn't capturing runtime errors.

Hm... `awful.rules` uses `gears.protected_call` to run callbacks. That way, errors in the callbacks do not break all of `awful.rules`. But this also means that errors are only printed to stderr (via `gears.debug.print_error`).
Should we wire up `gears.debug.print_*` to naughty in the default config? @Elv13 @blueyed @actionless

**Comment by actionless** [comment]
mb to debug:error signal, not to naughty directly?
