### ISSUE TITLE
Trying to swap tags from one screen to another

### ISSUE THREAD

**Issue by frioux** [awesomeWM/awesome#2771]
Output of `awesome --version`:

awesome v4.2 (Human after all)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.5
 • LGI version: 0.9.2

**How to reproduce the issue:**

Use https://github.com/frioux/sharetags (bug could be here, but I don't think it is).

Add some logging:

```lua
screen.connect_signal("tag::history::update", function(s)
   for i, t in ipairs(s.selected_tags) do
      print("screen " .. s.index .. " has tag " .. t.name)
   end
end)

tag.connect_signal("request::screen", function(t)
   print("tag " .. t.name .. " request::select")
end)

tag.connect_signal("tagged", function(t, c)
   print("client " .. c.name .. "(" .. c.window .. ") tagged with " .. t.name)
end)

tag.connect_signal("untagged", function(t, c)
   print("client " .. c.name .. "(" .. c.window .. ") untagged from " .. t.name)
end)

client.connect_signal("request::activate", function(c, ctx, hints)
   print("client " .. c.name .. "(" .. c.window .. ") requested " .. ctx)
end)

client.connect_signal("request::tag", function(c, t, hints)
   local reason = "<unset>"
   if hints ~= nil then
      reason = hints.reson
   end
   if reason == nil then
      reason = "<nil>"
   end
   print("client " .. c.name .. "(" .. c.window .. ") requested tag (reason " .. reason .. ")" )
end)
```

Run this via awesome-client:

```lua
sharetags = require("sharetags")

local function screen_tag_state(s)
   for i, t in ipairs(s.selected_tags) do
      local activated = "NOT"
      if t.activated then
         activated = "IS"
      end
      print("AC: screen " .. s.index .. " has tag " .. t.name)
   end
end

print("AC: client swapping 1 and 2")

screen_tag_state(screen[1])
screen_tag_state(screen[2])

sharetags.swap_screen(screen[1], screen[2])

print("AC: client swapping 1 and 2 again")

screen_tag_state(screen[1])
screen_tag_state(screen[2])

sharetags.swap_screen(screen[1], screen[2])

print("AC: should be back where we started")

screen_tag_state(screen[1])
screen_tag_state(screen[2])
```

Because this is so complicated, here are the logs produced when I run this:

```
AC: client swapping 1 and 2
AC: screen 1 has tag 1
AC: screen 2 has tag 2
moving tag 2 to screen 1
screen 1 has tag 2
moving tag 1 to screen 2
screen 1 has tag 2
screen 1 has tag 1
screen 1 has tag 2
AC: client swapping 1 and 2 again
AC: screen 1 has tag 1
AC: screen 1 has tag 2
moving tag 1 to screen 2
screen 1 has tag 1
moving tag 2 to screen 2
screen 1 has tag 1
screen 1 has tag 1
screen 1 has tag 2
AC: should be back where we started
AC: screen 1 has tag 1
AC: screen 1 has tag 2
client Class tag - awesome API documentation - Mozilla Firefox(37748739) untagged from 2
client Class tag - awesome API documentation - Mozilla Firefox(37748739) tagged with 4
client Class tag - awesome API documentation - Mozilla Firefox(37748739) tagged with 5
client Class tag - awesome API documentation - Mozilla Firefox(37748739) tagged with 6
client Class tag - awesome API documentation - Mozilla Firefox(37748739) tagged with 7
client Class tag - awesome API documentation - Mozilla Firefox(37748739) tagged with 8
client Class tag - awesome API documentation - Mozilla Firefox(37748739) tagged with 9
client Class tag - awesome API documentation - Mozilla Firefox(37748739) requested tag (reason <nil>)
client messaging:zsh:/home/frew/go/src/go.zr.org(20971527) untagged from 1
client messaging:zsh:/home/frew/go/src/go.zr.org(20971527) tagged with 4
client messaging:zsh:/home/frew/go/src/go.zr.org(20971527) tagged with 5
client messaging:zsh:/home/frew/go/src/go.zr.org(20971527) tagged with 6
client messaging:zsh:/home/frew/go/src/go.zr.org(20971527) tagged with 7
client messaging:zsh:/home/frew/go/src/go.zr.org(20971527) tagged with 8
client messaging:zsh:/home/frew/go/src/go.zr.org(20971527) tagged with 9
client messaging:zsh:/home/frew/go/src/go.zr.org(20971527) requested tag (reason <nil>)
```

**Actual result:**

The clients end up on *all off-screen tags*.

I think that basically because awesome is trying to keep clients from being displayed on two screens my clients are getting spilled to off screen tags.  If I could get some advice on how to dig deeper into this I would greatly appreciate it.

**Expected result:**

I expect tags and their clients from screen 1 to end up back on screen 1 and tags and their clients from screen to end up back on screen 2.

**Comment by Elv13** [comment]
Just a sidenote. Once upon a time, my Tyrannical module had this "xmonad style" trick to have a tag on multiple screens. I removed that because of similar issues. However, one of the trick to make this more stable is to create placeholder tags and use `t:swap(t2)` by watching for the `property::selected`. You also need to watch `tagged` to make sure clients added to the placeholder are moved to the "real" tag.

One of the historical drawback was that the tag state would not be correct. However, if you upgrade to Awesome v4.3, you can provide a custom widget template to work around this in addition to the taglist filter.

Keep in mind that it doesn't mean there is no bugs in the way `awful` tries to keep the tagging sane. A client can only be in a single screen. If there is a window of opportunity where, even for a fraction of a second, this isn't the case, then the housekeeping code will be triggered and try (and, in this case, fail) to restore a proper state. Allowing clients to be tagged on multiple screens has way, way more nasty side effects and corner cases than disallowing it.

**Comment by frioux** [comment]
I'll try out having a scratch tag for this purpose and report back here.  My guess is that it can mostly work since this is what I used to manually, instinctively do.  If there are still bugs after I try that we can dig in deeper and try to fix those.  Is there more information I should be recording?

**Comment by frioux** [comment]
Ok, so I added a scratch tag for each screen. I could probably figure out a way to only have one scratch tag but this makes the actual coding really straightforward.  This is the swap_screen function I will test out next time I have a second monitor (Tue at the soonest:)

```lua
function sharetags.swap_screen(s1, s2)
    if #s1.selected_tags > 1 or #s2.selected_tags > 1 then
        print("can't swap multiple tags yet")
    end

    local t1 = s1.selected_tag
    local t2 = s2.selected_tag

    -- hide both tags in scratch space
    t1:swap(s1.scratch)
    t2:swap(s2.scratch)

    -- bring tags back but to alternate screens
    t2:swap(s1.scratch)
    t1:swap(s2.scratch)
end
```

I'll experiment with that and add signal handlers to fix oddities after I see how the above ends up working.

**Comment by frioux** [comment]
@Elv13 thanks for your help!  This incredibly worked almost perfectly on the first try.  The only change above I made (and I intend for this to be fixed at some point) is that I only allow swapping tags if there is a tag in each screen, otherwise (duh) you can't swap with a nil tag.  So far this is surprisingly robust, but I'm leaving my logging in place to help debug issues later.  Thanks!
