### ISSUE TITLE
There seems to be some sort of placeholder in place of a Deluge's systray icon

### ISSUE THREAD

**Issue by x-yuri** [awesomeWM/awesome#2776]
Output of `awesome --version`:

```
awesome v4.3 (Too long)
 • Compiled against Lua 5.3.5 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
```

**How to reproduce the issue:**

Install Deluge and run it. (I'm now running `deluge-1.3.15`.) Then take a look at the systray.

**Actual result:**

![](https://i.imgur.com/icIubQM.png)

Deluge's icon is the one with an exclamation mark inside a triangle. After Dropbox's one.

**Expected result:**

An icon similar to the one on the taskbar should appear:

![](https://i.imgur.com/Jk2hMpv.png)

Back in the day, it worked. I'm not sure how much time passed since it's this way. Maybe a year or more. I've looked through the issues, but still not sure if my case was reported. The following information might prove useful:

```
$ xwininfo -tree
xwininfo: Please select the window about which you
          would like information by clicking the
          mouse in that window.

xwininfo: Window id: 0xa00015 "Awesome drawin"

  Root window id: 0x16a (the root window) (has no name)
  Parent window id: 0x16a (the root window) (has no name)
     1 child:
     0xa00006 "Awesome systray window": ("awesome" "awesome")  100x20+1702+0  +1702+0
        5 children:
        0x1000013 "Toggl Desktop": ("TogglDesktop" "Toggl Desktop")  20x20+80+0  +1782+0
        0x3800003 "deluge": ("deluge" "Deluge")  20x20+60+0  +1762+0
           1 child:
           0x3800004 (has no name): ()  1x1+-1+-1  +1761+-1
        0x2400004 (has no name): ()  20x20+40+0  +1742+0
        0x600007 "slack": ("slack" "Slack")  20x20+20+0  +1722+0
           1 child:
           0x600008 (has no name): ()  1x1+-1+-1  +1721+-1
        0xe00007 "skypeforlinux": ("skypeforlinux" "Skypeforlinux")  20x20+0+0  +1702+0
           1 child:
           0xe00008 (has no name): ()  1x1+-1+-1  +1701+-1

$ xprop -id 0x1000013
_NET_WM_ICON_NAME(UTF8_STRING) = 
XdndAware(ATOM) = BITMAP
WM_NAME(STRING) = 
_NET_WM_NAME(UTF8_STRING) = "Toggl Desktop"
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x2, 0x1, 0x0, 0x0, 0x0
_NET_WM_WINDOW_TYPE(ATOM) = _KDE_NET_WM_WINDOW_TYPE_OVERRIDE, _NET_WM_WINDOW_TYPE_NORMAL
_XEMBED_INFO(_XEMBED_INFO) = 0x0, 0x1
WM_CLIENT_LEADER(WINDOW): window id # 0x1000015
WM_HINTS(WM_HINTS):
		Client accepts input or input focus: True
		window id # of group leader: 0x1000015
WM_CLIENT_MACHINE(STRING) = "yuri"
_NET_WM_PID(CARDINAL) = 2288
_NET_WM_SYNC_REQUEST_COUNTER(CARDINAL) = 16777236
WM_CLASS(STRING) = "TogglDesktop", "Toggl Desktop"
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, WM_TAKE_FOCUS, _NET_WM_PING, _NET_WM_SYNC_REQUEST
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		user specified location: 0, 0
		user specified size: 22 by 22
		program specified minimum size: 22 by 22
		window gravity: Static

$ xprop -id 0x3800003
GDK_TIMESTAMP_PROP(GDK_TIMESTAMP_PROP) = 0x61
_NET_WM_SYNC_REQUEST_COUNTER(CARDINAL) = 58720283
_XEMBED_INFO(_XEMBED_INFO) = 0x1, 0x1
_NET_WM_USER_TIME(CARDINAL) = 22382306
_NET_WM_USER_TIME_WINDOW(WINDOW): window id # 0x3800004
WM_CLIENT_LEADER(WINDOW): window id # 0x3800001
_NET_WM_PID(CARDINAL) = 24337
WM_LOCALE_NAME(STRING) = "en_US.UTF-8"
WM_CLIENT_MACHINE(STRING) = "yuri"
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified minimum size: 22 by 22
		window gravity: NorthWest
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, WM_TAKE_FOCUS, _NET_WM_PING, _NET_WM_SYNC_REQUEST
WM_CLASS(STRING) = "deluge", "Deluge"
WM_ICON_NAME(STRING) = "deluge"
_NET_WM_ICON_NAME(UTF8_STRING) = "deluge"
WM_NAME(STRING) = "deluge"
_NET_WM_NAME(UTF8_STRING) = "deluge"

$ xprop -id 0x2400004
XdndAware(ATOM) = BITMAP
WM_NAME(STRING) = 
_NET_WM_NAME(UTF8_STRING) = 
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x2, 0x1, 0x0, 0x0, 0x0
_NET_WM_WINDOW_TYPE(ATOM) = _KDE_NET_WM_WINDOW_TYPE_OVERRIDE, _NET_WM_WINDOW_TYPE_NORMAL
_XEMBED_INFO(_XEMBED_INFO) = 0x0, 0x1
WM_CLIENT_LEADER(WINDOW): window id # 0x2400005
WM_HINTS(WM_HINTS):
		Client accepts input or input focus: True
		Initial state is Normal State.
_NET_WM_PID(CARDINAL) = 2445
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, WM_TAKE_FOCUS, _NET_WM_PING
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		user specified location: 0, 0
		user specified size: 22 by 22
		program specified minimum size: 22 by 22
		window gravity: Static

$ xprop -id 0x600007
XdndAware(ATOM) = BITMAP
GDK_TIMESTAMP_PROP(GDK_TIMESTAMP_PROP) = 0x61
_XEMBED_INFO(_XEMBED_INFO) = 0x1, 0x1
_NET_WM_SYNC_REQUEST_COUNTER(CARDINAL) = 6291465, 6291466
_NET_WM_USER_TIME(CARDINAL) = 16324451
_NET_WM_USER_TIME_WINDOW(WINDOW): window id # 0x600008
WM_CLIENT_LEADER(WINDOW): window id # 0x600001
_NET_WM_PID(CARDINAL) = 2434
WM_LOCALE_NAME(STRING) = "en_US.UTF-8"
WM_CLIENT_MACHINE(STRING) = "yuri"
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified minimum size: 16 by 16
		program specified base size: 0 by 0
		window gravity: NorthWest
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, WM_TAKE_FOCUS, _NET_WM_PING, _NET_WM_SYNC_REQUEST
WM_CLASS(STRING) = "slack", "Slack"
WM_ICON_NAME(STRING) = "slack"
_NET_WM_ICON_NAME(UTF8_STRING) = "slack"
WM_NAME(STRING) = "slack"
_NET_WM_NAME(UTF8_STRING) = "slack"

$ xprop -id 0xe00007
XdndAware(ATOM) = BITMAP
GDK_TIMESTAMP_PROP(GDK_TIMESTAMP_PROP) = 0x61
_XEMBED_INFO(_XEMBED_INFO) = 0x1, 0x1
_NET_WM_SYNC_REQUEST_COUNTER(CARDINAL) = 14680073, 14680074
_NET_WM_USER_TIME(CARDINAL) = 126238908
_NET_WM_USER_TIME_WINDOW(WINDOW): window id # 0xe00008
WM_CLIENT_LEADER(WINDOW): window id # 0xe00001
_NET_WM_PID(CARDINAL) = 2446
WM_LOCALE_NAME(STRING) = "en_US.UTF-8"
WM_CLIENT_MACHINE(STRING) = "yuri"
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified minimum size: 16 by 16
		program specified base size: 0 by 0
		window gravity: NorthWest
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, WM_TAKE_FOCUS, _NET_WM_PING, _NET_WM_SYNC_REQUEST
WM_CLASS(STRING) = "skypeforlinux", "Skypeforlinux"
WM_ICON_NAME(STRING) = "skypeforlinux"
_NET_WM_ICON_NAME(UTF8_STRING) = "skypeforlinux"
WM_NAME(STRING) = "skypeforlinux"
_NET_WM_NAME(UTF8_STRING) = "skypeforlinux"
```

Is there anything else I could check? Could this possibly be because of Deluge not having a 20x20 icon?.. But why it's displayed on the taskbar then?..

**Comment by psychon** [comment]
All that I can tell you:

- The WM does not draw systray icons. The icons draw themselves.
- The icon looks to me like some kind of "icon not found"-placeholder.
- The code for deluge's systray icon is in `deluge/ui/gtkui/systemtray.py`.
- The code uses `deluge.ui.gtkui.common.get_logo(32)` to find the icon.
- This then calls `deluge.common.get_pixmap("deluge.svg")` to find the icon.
- Which finally calls `pkg_resources.resource_filename("deluge", "data/pixmaps/deluge.svg")` to find the final file. I do not know `pkg_resources`, but apparently it fails to find this file.
- The tasklist icon which seems to work for you is found via `gtk.icon_theme_get_default().load_icon("deluge", 64, 0)`. So this uses a different approach to find the icon.

You should talk to the people behind deluge to figure out what went wrong with the installation of `deluge.svg`. Sorry, but we cannot help you further.

**Comment by x-yuri** [comment]
Thanks a lot. Although let me correct and expand on this based on what I've found. [`deluge.common.get_logo()`][1] is used under Windows and MacOS. On Linux they use `gtk.status_icon_new_from_icon_name("deluge-panel")` which is supposedly similar to `gtk.icon_theme_get_default().load_icon("deluge", 64, 0)`. That is, in both cases they ask for an icon from the icon theme, it's just that the names differ.

And the thing is, when they were adding the [`deluge-panel` icon][2], they forgot to add it to `setup.py` (no icon in the resulting package). But later they [fixed][3] it. That is all in the `develop` branch. (They're working on `deluge-2.0` now.) And then they [backported][4] the `deluge-panel` icon to the stable branch (`1.3-stable`), but not the fix :)

[1]: https://git.deluge-torrent.org/deluge/tree/deluge/ui/gtkui/systemtray.py?h=1.3-stable&id=e050905b291f4d9b417270e38f2aa04366057919#n133
[2]: https://git.deluge-torrent.org/deluge/commit/?h=develop&id=fe42fb2c31d87b013eb0fdd897946e0e08b37018
[3]: https://git.deluge-torrent.org/deluge/commit/?h=develop&id=b665a4a6f7a84e1d4901d566128e7d06b7541825
[4]: https://git.deluge-torrent.org/deluge/commit/?h=1.3-stable&id=993abbc6a66837f32dec00d29ee80dea5dbcdf20

And actually, there's even a [topic][5] on Arch Linux forum.

Regarding icon themes, they are sets of named icons. You can install, [switch][6] between them by changing GTK settings. The default is supposedly [`Adwaita`][7]. But there's also a [fallback theme][8] called `hicolor` (`/usr/share/icons/hicolor`), where applications (e.g. Deluge) usually install their icons.

[5]: https://bbs.archlinux.org/viewtopic.php?id=244434
[6]: https://unix.stackexchange.com/questions/150853/how-to-set-gtk-icon-theme-in-i3
[7]: https://developer.gnome.org/gtk3/stable/GtkSettings.html#GtkSettings--gtk-icon-theme-name
[8]: https://specifications.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html

So, either change `/usr/lib/python2.7/site-packages/deluge/ui/gtkui/systemtray.py` (`deluge-panel` -> `deluge`), or add `deluge-panel` icon to `/usr/share/icons/hicolor`. Or wait for the new version or backport.

**Comment by psychon** [comment]
Ah. Thanks for leaving such a detailed comment here. I thank you in the name of whoever ends up here via Google. :-)
