### ISSUE TITLE
Access to the api with tor

### ISSUE THREAD

**Issue by szorfein** [awesomeWM/awesome#2777]
Hi, since 1 month ago, the access to [awesome](https://awesomewm.org) is blocked by the use of tor.  

**Actual result:**

![capcha](https://pbs.twimg.com/media/DkkxXbuXgAI4IHR.jpg)  

for now, I have to use solutions like [kproxy](https://www.kproxy.com/), this is a little annoying.

**Expected result:**

Normal access

I do not know if this issue can be resolved but maybe this [link](https://gitlab.com/iblech/tor-appeal/blob/master/README.md) can help.

**Comment by psychon** [comment]
Not really a solution, but: You could access the apidoc locally. Either just have the normal build process build it, or you could download the web site as a zip file and browse that locally: https://github.com/awesomeWM/awesomeWM.github.io/archive/master.zip (for git/master, the docs are in https://github.com/awesomeWM/apidoc/archive/gh-pages.zip).

**Comment by szorfein** [comment]
thank you, I will do this for the moment

**Comment by blueyed** [comment]
Thanks for the report.
IIRC we're using this for the SSL certificate / handling.

**Comment by blueyed** [comment]
> I do not know if this issue can be resolved but maybe this [link](https://gitlab.com/iblech/tor-appeal/blob/master/README.md) can help.

That helped - whitelisted it now, and confirmed that it works.
Thanks again for the report.
