### ISSUE TITLE
Notification isn't replaced

### ISSUE THREAD

**Issue by SethBarberee** [awesomeWM/awesome#2789]
Output of `awesome --version`:
```
awesome v4.3-274-g140f11b10 (Too long)
 • Compiled against Lua 5.3.5 (running with Lua 5.3)
 • D-Bus support: ✔
 • xcb-errors support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
```

**How to reproduce the issue:**
* Use the new notification API (merged in #2726 )
```
naughty.connect_signal("request::display", function(n)
      naughty.layout.box { notification = n }
end)
```

* Open Spotify
* Start a song (notification is displayed)
* Before the notification is destroyed, play a new song

**Actual result:**

Notification has the previous song info

**Expected result:**

Notification should be replaced. This happens with the older system.

**Comment by vn-ki** [comment]
I can confirm this.

With `naughty.notify`:
Same notification with old data.

With `naughty.notification`:
New notification. Does not get replaced.

I'm interested in contributing, so if you can give me some pointers I can try to hunt down the issue.

**Comment by Elv13** [comment]
Can someone try https://github.com/awesomeWM/awesome/pull/2816 to see if it solves this problem?

**Comment by SethBarberee** [comment]
@Elv13 It solved my issue. Closing since resolved by merged PR.
