### ISSUE TITLE
Gnome shell starts on background

### ISSUE THREAD

**Issue by jackTaw88** [awesomeWM/awesome#2791]
Hi,

I installed awesome wm on my Ubuntu 18.04 (which uses as default gnome shell).

I restart the machine and I logged with awesome wm.

When I check the CPU with "top" command, after a while, I saw a process "gnome-shell" which use sometimes even my CPU.

I did not have any gnome app (or gnome app) on startup of user.

Is this a bug or something?

Thank you

**Comment by Veratil** [comment]
If you're using GDM is the login manager, then `gnome-shell` is started from that. It's running on my machine as well.

**Comment by jackTaw88** [comment]
And it uses cpu :(

I recognize that I  had open "top" command with gnome-terminal :) Are gnome based apps starts gnome-shell?

**Comment by Veratil** [comment]
According to [this reddit post](https://www.reddit.com/r/gnome/comments/79qb49/is_it_safe_to_kill_the_gnomeshell_process_owned/) GDM is a stripped down version of `gnome-shell`. If you kill it then the login manager will die with it.

To quote the GNOME Developer reply from the link:
> GDM is a stripped down GNOME-Shell instance, killing it will take it down entirely. It is worth noting that even though GNOME-Shell is loaded twice since all of libraries are the same they don't take extra memory so while there is overhead its not insane.
> 
> If it still bothers you your only option is to use a different dm like lightdm but you lose the lock feature doing so.

**Comment by Elv13** [comment]
Not much to do from our side. I am closing this since it is an Ubuntu "mis-feature" and not an AwesomeWM bug.
