### ISSUE TITLE
Imagebox clip shape goes wrong with scale

### ISSUE THREAD

**Issue by worron** [awesomeWM/awesome#2792]
Output of `awesome --version`:

awesome v4.3-274-g140f11b1-dirty (Too long)
 • Compiled against Lua 5.3.5 (running with Lua 5.3)
 • D-Bus support: ✔
 • xcb-errors support: ✘
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2

**How to reproduce the issue:**
```lua
local gears = require("gears")

local ib = wibox.widget.imagebox(beautiful.awesome_icon)
ib:set_clip_shape(gears.shape.rounded_rect, 25)

local wb = wibox({ widget = ib, width = 128, height = 128 })
wb:save_to_svg(gears.filesystem.get_configuration_dir() .. "/output.svg")
```
**Actual result:**
![output-orig](https://user-images.githubusercontent.com/10406966/59353637-1a402680-8d2c-11e9-9f51-f22632efb482.png)
**Expected result:**
![output-mod](https://user-images.githubusercontent.com/10406966/59353706-3ba11280-8d2c-11e9-95ab-5a3b3734f4f2.png)
**Possible fix:**
```diff
diff --git a/lib/wibox/widget/imagebox.lua b/lib/wibox/widget/imagebox.lua
index 76ee97a2..861deed4 100644
--- a/lib/wibox/widget/imagebox.lua
+++ b/lib/wibox/widget/imagebox.lua
@@ -21,6 +21,11 @@ function imagebox:draw(_, cr, width, height)
     if not self._private.image then return end
     if width == 0 or height == 0 then return end
 
+    -- Set the clip
+    if self._private.clip_shape then
+        cr:clip(self._private.clip_shape(cr, width, height, unpack(self._private.clip_args)))
+    end
+
     if not self._private.resize_forbidden then
         -- Let's scale the image so that it fits into (width, height)
         local w = self._private.image:get_width()
@@ -32,11 +37,6 @@ function imagebox:draw(_, cr, width, height)
         cr:scale(aspect, aspect)
     end
 
-    -- Set the clip
-    if self._private.clip_shape then
-        cr:clip(self._private.clip_shape(cr, width, height, unpack(self._private.clip_args)))
-    end
-
     cr:set_source_surface(self._private.image, 0, 0)
     cr:paint()
 end
```
I can add patch to #2779 if this fix has no downsides.

**Comment by psychon** [comment]
The fix looks exactly like what I would have written by myself.

> I can add patch to #2779 if this fix has no downsides.

It would be great if you could open a separate PR for just that fix.
