### ISSUE TITLE
Broken links for core components in apidocs homepage

### ISSUE THREAD

**Issue by gregflynn** [awesomeWM/awesome#2797]
Repro Steps:
1. https://awesomewm.org/apidoc/
1. scroll to `Core components` section (main page, not sidebaa)
1. Click `awful.titlebar` (or any of them really
1. 404 :(

it looks like the main page is rendering the link with an underscore, but the sidebar renders with a space/%20 and _does_ resolve correctly

`https://awesomewm.org/apidoc/popups_and_bars/awful.titlebar.html`
`https://awesomewm.org/apidoc/popups%20and%20bars/awful.titlebar.html`

As i write this it looks like that main page breaks any link with a space, assuming it's an underscore. This is a super minor issue since the doc links in the sidebar work fine

**Comment by alfunx** [comment]
Related to https://github.com/awesomeWM/awesome/pull/2785#issuecomment-500386391
