### ISSUE TITLE
Errors when wibox.widget.systray is inside wibox.container.margin

### ISSUE THREAD

**Issue by sigprof** [awesomeWM/awesome#2799]
Output of `awesome --version`:

```
awesome v4.3 (Too long)
 • Compiled against Lua 5.3.4 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
````

I added some `wibox.container.margin` containers around `wibox.widget.systray` on my wibar:

```
                {
                    widget = wibox.container.margin,
                    right = dpi(1),
                    color = '#000000',
                    draw_empty = false,
                    {
                        widget = wibox.container.margin,
                        left = dpi(4),
                        right = dpi(4),
                        draw_empty = false,
                        wibox.widget.systray(),
                    },
                },
```

The widget looks as expected (when there are no systray icons, the margins and the separator line created by the outer `margin` widget are not displayed). However, there are repeated errors on stderr:

```
2019-06-18 11:28:00 E: awesome: Error during a protected call: /usr/share/awesome/lib/wibox/widget/systray.lua:72: bad argument #4 to 'systray' (value in [1.0, 
65535.0] expected, got -inf)                                                                                                                                    stack traceback:
        [C]: in field 'systray'
        /usr/share/awesome/lib/wibox/widget/systray.lua:72: in function 'wibox.widget.systray.draw'
        [C]: in function 'xpcall'
        /usr/share/awesome/lib/gears/protected_call.lua:36: in function </usr/share/awesome/lib/gears/protected_call.lua:35>
        (...tail calls...)
        /usr/share/awesome/lib/wibox/hierarchy.lua:323: in local 'call'
        /usr/share/awesome/lib/wibox/hierarchy.lua:338: in function 'wibox.hierarchy.draw'
        /usr/share/awesome/lib/wibox/hierarchy.lua:345: in function 'wibox.hierarchy.draw'
        /usr/share/awesome/lib/wibox/hierarchy.lua:345: in function 'wibox.hierarchy.draw'
        /usr/share/awesome/lib/wibox/hierarchy.lua:345: in function 'wibox.hierarchy.draw'
        /usr/share/awesome/lib/wibox/hierarchy.lua:345: in function 'wibox.hierarchy.draw'
        /usr/share/awesome/lib/wibox/hierarchy.lua:345: in function 'wibox.hierarchy.draw'
        /usr/share/awesome/lib/wibox/drawable.lua:160: in upvalue 'do_redraw'
        /usr/share/awesome/lib/wibox/drawable.lua:390: in function </usr/share/awesome/lib/wibox/drawable.lua:388>
        [C]: in function 'xpcall'
        /usr/share/awesome/lib/gears/protected_call.lua:36: in function </usr/share/awesome/lib/gears/protected_call.lua:35>
        (...tail calls...)
        /usr/share/awesome/lib/gears/timer.lua:231: in function </usr/share/awesome/lib/gears/timer.lua:229>
```

Apparently the problem is that `systray:draw` is invoked with `width = -8`, because `wibox.container.margin` sets its own size to (0, 0) when `draw_empty = false`, but still subtracts margins from its size when calculating the child widget size.

Adding another useless layer of `wibox.container.margin` hides the problem:

```
                {
                    widget = wibox.container.margin,
                    right = dpi(1),
                    color = '#000000',
                    draw_empty = false,
                    {
                        widget = wibox.container.margin,
                        left = dpi(4),
                        right = dpi(4),
                        draw_empty = false,
                        {
                            widget = wibox.container.margin,
                            wibox.widget.systray(),
                        },
                    },
                },
```

**Comment by psychon** [comment]
Hm. I cannot reproduce. I replaced `wibox.widget.systray(),` in the default config with your code. Then I replaced each `dpi(x)` with just `x`. The result is:

![foo](https://user-images.githubusercontent.com/89482/59700593-e82f3880-91f3-11e9-92f9-bc71a8e4ae9c.png)

I also added and removed systray icons a couple of times, but no error ever appeared.

> Apparently the problem is that systray:draw is invoked with width = -8, because wibox.container.margin sets its own size to (0, 0) when draw_empty = false, but still subtracts margins from its size when calculating the child widget size.

One quick counter-argument: The error message is:

> bad argument #4 to 'systray' (value in [1.0, 65535.0] expected, got -inf)  

This is a call to `awesome.systray` with argument no. 4 being negative infinity. Argument no. 4 is the base size of the icons.

Do you have something that restricts the available space somehow?

**Comment by sigprof** [comment]
Sorry, I did not have the time to prepare a good bug report. The problem appears when you have 0 tray icons and trigger a redraw somehow (probably by a window list change).

`-inf` comes from a division by the icon count, which is 0 (and the if branch with that division is wrongly taken because the width is negative).

**Comment by sigprof** [comment]
It turned out that another margin container which I have added around the whole wibar is required to reproduce the bug. With this change to the default `awesomerc.lua` I can reproduce the bug with both v4.3 and the current git version (v4.3-278-g99e81c09) by clicking on the launcher button, or by moving the mouse over that button and then moving it outside:

```diff
diff --git a/awesomerc.lua b/awesomerc.lua
index d3390c57..1648cec5 100644
--- a/awesomerc.lua
+++ b/awesomerc.lua
@@ -212,6 +212,10 @@ awful.screen.connect_for_each_screen(function(s)
     -- @DOC_SETUP_WIDGETS@
     -- Add widgets to the wibox
     s.mywibox:setup {
+      widget = wibox.container.margin,
+      top = 1,
+      color = '#ffffff',
+      {
         layout = wibox.layout.align.horizontal,
         { -- Left widgets
             layout = wibox.layout.fixed.horizontal,
@@ -223,10 +227,17 @@ awful.screen.connect_for_each_screen(function(s)
         { -- Right widgets
             layout = wibox.layout.fixed.horizontal,
             mykeyboardlayout,
-            wibox.widget.systray(),
+            {
+                widget = wibox.container.margin,
+                left = 4,
+                right = 4,
+                draw_empty = false,
+                wibox.widget.systray(),
+            },
             mytextclock,
             s.mylayoutbox,
         },
+      },
     }
 end)
 -- }}}
```

Apparently the non-zero **top** margin is required to reproduce the bug. (In my real configuration I have the wibar at bottom and use that margin as a separator line.)

I added some debug output to the systray code:

```diff
diff --git a/lib/wibox/widget/systray.lua b/lib/wibox/widget/systray.lua
index 59b715d3..a1aca122 100644
--- a/lib/wibox/widget/systray.lua
+++ b/lib/wibox/widget/systray.lua
@@ -8,6 +8,7 @@ local wbase = require("wibox.widget.base")
 local drawable = require("wibox.drawable")
 local beautiful = require("beautiful")
 local gtable = require("gears.table")
+local gdebug = require("gears.debug")
 local capi = {
     awesome = awesome,
     screen = screen
@@ -69,6 +70,8 @@ function systray:draw(context, cr, width, height)
     else
         base = in_dir / num_entries
     end
+    gdebug.print_warning(string.format("systray:draw: width=%s height=%s x=%s y=%s num_entries=%s in_dir=%s ortho=%s base=%s",
+        width, height, x, y, num_entries, in_dir, ortho, base))
     capi.awesome.systray(context.wibox.drawin, math.ceil(x), math.ceil(y),
                          base, is_rotated, bg, reverse, spacing)
 end
```

I got this output before the error backtrace:

```
2019-06-19 10:19:38 W: awesome: systray:draw: width=-8 height=17 x=1185.0 y=1.0 num_entries=0 in_dir=-8 ortho=17 base=-inf
```

As you can see, `systray:draw` is really called with a negative `width` value with this wibar config, and the `ortho * num_entries <= in_dir` condition does not give the expected result in this case, which results in a division by zero in the subsequent code.

Obviously, the error in `systray:draw` can be avoided by doing something like

```lua
   width = math.max(width, 0)
   height = math.max(height, 0)
```

But looks like the real bug here is that `wibox.container.margin` can sometimes set a negative width or height for its child widget.

**Comment by psychon** [comment]
First thing I notice: The function `empty_clip` in `wibox.hierarchy` is broken and no one ever noticed (the extra CPU usage that this causes). `cr:clip_extents()` does not describe the clip extents as x,y,width,height, but as x1,y1,x2,y2 (so it gives the upper-left and lower-right corner of the rectangle).
However, that does not yet explain where the negative arguments come from, so I'll keep staring some more.
