### ISSUE TITLE
Mousegrabber mouse.coords()['buttons'] is not documented

### ISSUE THREAD

**Issue by kindlycat** [awesomeWM/awesome#280]
Hello,
I write a slider widget and have a problem with mousegrabber. I can't detect when mouse button released, only when released and moved. On every event "press" or "release", mousegrabber returns that mouse button had an event, but not return name of event or something like this. Is it possible to add this feature or add function that check if mouse button currently pressed?

**Comment by Elv13** [comment]
Can you please add some details about why you closed this? Like the solution or something, that would be helpful if users find this issue later on

Thanks

**Comment by kindlycat** [comment]
Sure, mouse.coords()['buttons'] contains state of all buttons, but it's not in documentation.
