### ISSUE TITLE
Add an option for uncached ImageBox

### ISSUE THREAD

**Issue by vn-ki** [awesomeWM/awesome#2808]
Output of `awesome --version`:
```
awesome v4.3 (Too long)
 • Compiled against Lua 5.3.5 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
```

**How to reproduce the issue:**

- Load an image to imagebox
- Image changes locally
- Do `imagebox:set_image` to set the new image

**Actual result:**

Image does not change due to caching

**Expected result:**

Add option so that new image can be loaded circumventing the cache.

If this can be accepted, I would like to present the PR.

**Comment by Elv13** [comment]
It already exists. You need to do `imagebox.image = gears.surface.load_uncached(image)`.

https://awesomewm.org/doc/api/libraries/gears.surface.html#load_uncached

**Comment by vn-ki** [comment]
Nice. Thanks.

**Comment by vn-ki** [comment]
For some reason only a small part of the image is visible when I do this. @Elv13 
WIth the above method
![image](https://user-images.githubusercontent.com/31964688/60499125-7831af80-9cd5-11e9-914f-ddbfd54541de.png)

![image](https://user-images.githubusercontent.com/31964688/60499155-85e73500-9cd5-11e9-86c6-f228d62eaaf1.png)

**Comment by vn-ki** [comment]
Also, the images are not being reloaded.

**Comment by worron** [comment]
>`imagebox.image = gears.surface.load_uncached(image)`

This doesn't work anymore since imagebox structure changed. It support two different image objects now and separate storage for image sizes.

I think we really need 'uncached' option for `set_image` to resolve this issue, no tricks allowed.

**Comment by psychon** [comment]
> This doesn't work anymore since imagebox structure changed. It support two different image objects now and separate storage for image sizes.

Huh? What is the problem? Works for me:
```diff
local function text_to_image(text, path)
    awful.spawn({"convert", "-size", "100x15", "xc:White", "-gravity", "center", "-font", "DejaVu-Sans", "-annotate", "0", text, path})
end
imgbox = wibox.widget.imagebox()
gears.timer.start_new(1, function()
    local path = "/tmp/date.png"
    imgbox.image = gears.surface.load_uncached(path)
    text_to_image(os.date(), path)
    return true
end)
```

**Comment by psychon** [comment]
```
album_art.image = gears.surface.load_uncached(album_art.image)
```
@vn-ki Uhm. `album_art.image` is a handle to an already-loaded surface (more technically: It is a cairo image surface instance). Try replacing this line with:
```
album_art.image = gears.surface.load_uncached("/tmp/mprisimg.png")
```

**Comment by worron** [comment]
I'm sorry, somehow I was thinking about master branch. This trick works for `v4.3`, but will be broken in future. Still think adding 'uncached' option is  idea worth to consider.

**Comment by Elv13** [comment]
> I'm sorry, somehow I was thinking about master branch. This trick works for v4.3, but will be broken in future. Still think adding 'uncached' option is idea worth to consider.

It will have to be somehow fixed, API breakage cannot go into a release.

**Comment by worron** [comment]
Sorry again, my sentence was misleading,  this solution will not be broken. But the trick with `surface.load_uncached` does not respect new vector scaling imagebox feature. This method forces use surface even for vector images where rsvg handle would be preferable. Not a big deal, but feel there is a place for improvement here.

Imagebox has the separate cache for rsvg handles. And this cache can't be avoided now. But would be nice to have such possibility. I wonder what the best way to do so. Is optional argument for `set_image` allowed?
