### ISSUE TITLE
`awful.placement.no_overlap` does not handle placement on unselected tags

### ISSUE THREAD

**Issue by sigprof** [awesomeWM/awesome#2809]
Output of `awesome --version`:

```
awesome v4.3-285-gf4592967 (Too long)
 • Compiled against Lua 5.3.4 (running with Lua 5.3)
 • D-Bus support: ✔
 • xcb-errors support: ✘
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
```

(current git; also can be reproduced in the v4.3 release)

**How to reproduce the issue:**

1. Run Awesome with the default config.
2. Select tag 2, optionally open some windows on it.
3. Select tag 1, optionally open some windows on it (to see some parts of the wrong behavior, different areas should be occupied by windows on tags 1 and 2).
4. Execute the Lua code 2 or more times:
```lua
require("awful").spawn("urxvt", { tag = "2" })
```
5. Switch to tag 2 and look at window positions there.

An alternative way to reproduce the issue is to assign `tag` using rules, but that requires editing the config file.

**Actual result:**

All new `urxvt` windows are at the same position, and this position was chosen to avoid overlapping windows on tag 1, ignoring windows which were on tag 2.

**Expected result:**

When placing a window on unselected tags, `awful.placement.no_overlap` should use the set of windows on those tags instead of currently visible windows, so that the result of placing a window on the specific tag does not change if that tag was unselected.

-----

The real world use case where this problem appears is described in [the reddit post](https://www.reddit.com/r/awesomewm/comments/c7dxic/how_to_keep_programs_from_switching_workspaces/). The basic idea is to capture the selected tag when `awful.spawn` is called, and place the app window on that tag using the SNID rules even if the user switched to a different tag while the app was starting (the `exec` command in i3 behaves like this).

**Comment by psychon** [comment]
From a quick look at the code: `no_overlap` uses `awful.client.visible(s)` to get the list of clients to "avoid". Then it just avoids placement over any of those clients. There is nothing tag-specific going on here, hence the behaviour you are seeing.
