### ISSUE TITLE
Documentation build problem

### ISSUE THREAD

**Issue by actionless** [awesomeWM/awesome#2812]
Compare 
https://awesomewm.org/apidoc/theme%20related%20libraries/beautiful.html
and
file:///usr/share/doc/awesome/doc/theme%20related%20libraries/beautiful.html

The first have apidoc only for the first function.

**Comment by Elv13** [comment]
Yep, the page footer is above the table, definitely not the way it should be. Either the ldoc submodule code exploded again (which is a known issue, but usually easy-ish to work around) or the markdown parser really didn't like the embedded HTML table and exploded.

**Comment by psychon** [comment]
Looking at the HTML source, there is this beauty:
```html
 <tr> <td><code>wm_border_unfocused_color</code></td> <td><code>wm_border_unfocused</code></td> <td><code>wm_border</code></td> <td><code>menubar_bg_color</code></td> <!--<td><code>theme_bg_color</code></td>&ndash;> <td>HeaderBar bg</td> </tr>
```
There is a stray `<!--` in there with causes the rest of the source to be skipped as comments. The following then ends this mega-long comment near the footer:
```html
</div> <!-- id="content" -->
```
I guess the "footer above the table" then is a result of the browser trying to make the best out of the broken HTML structure.

The broken HTML comes from line 81 of `lib/beautiful/init.lua`:
```lua
-- <tr> <td>`wm_border_unfocused_color`</td> <td>`wm_border_unfocused`</td> <td>`wm_border`</td> <td>`menubar_bg_color`</td> <!--<td>`theme_bg_color`</td>--> <td>HeaderBar bg</td> </tr>
```
As you see, this contains `<!--<td>'theme_bg_color'</td>-->`, but ldoc turns this into `<!--<td><code>theme_bg_color</code></td>&ndash;>` in the HTML above.
