### ISSUE TITLE
local rc.lua ignored

### ISSUE THREAD

**Issue by Berkmann18** [awesomeWM/awesome#2824]
Output of `awesome --version`:
```shell
awesome v4.3 (Too long)
 • Compiled against Lua 5.3.5 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
```

**How to reproduce the issue:**

0. Have ArchLinux (or any Arch-like distro, not sure that's relevant)
1. log in through the tty (no DM needed)
2. `startx` or `xinit`
3. Observe the default config (wallpaper, keybindings, ...) being used as opposed to the tweaked https://github.com/lcpz/awesome-copycats one (which worked before upgrading the kernel from 5.1.0-arch1-1-ARCH to 5.2.0-arch2-1-ARCH and other packages).
4. Optionally try reloading awesome (using the default key bindings or with `pkill X`) and see that it doesn't go back to normal (with no errors being shown).

**Actual result:**

The config file in `~/.config/awesome` is **completely** ignored despite `awesome -k -c ~/.config/awesome/rc.lua` returning `✔ Configuration file syntax OK.`.

**Expected result:**

The WM to show up as expected with the same keybindings as before that issue occurred (which for some reason happened at the same time as `opera` losing data).

**Comment by Veratil** [comment]
The configuration check only returns if the syntax is okay. Running it can still result in errors which prevent loading properly (and then using the default fallback). Is there an error notification popping up? Did you check logs?

**Comment by Berkmann18** [comment]
@Veratil In that case, the error handler that awesome has would pick that up no?
And the `rc.lua` was the same as before that issue happened so it might not be an error on that side.
I looked for `~/.x*errors` files as suggested in some forum posts I've read but I couldn't find any.
I looked at the`/var/log/Xorg.0.log` file but didn't see anything abnormal.

**Comment by Veratil** [comment]
Try saving off your copycats config and pulling in the default rc.lua with some minor changes (like tag names and layouts for instance) and see if that works. If it does then it's most likely the copycats config which has some error, but I cannot help with why it's not popping up an error at that point.

**Comment by psychon** [comment]
> I looked for ~/.x*errors files as suggested in some forum posts I've read but I couldn't find any.

If you use `startx` to start awesome, then you would not have such files. Instead, AwesomeWM's stdout and stderr should go to the tty where you started it and should be visible there (together with other output from Xorg). You could try something like `startx > /tmp/stdout.txt 2> /tmp/stderr.txt` to get the output into files.

> I looked at my /var/log/Xorg.0.log file but didn't see anything abnormal.

That file only contains output from Xorg (the X11 server). Nothing else.

Also: Since you write that the file is completely ignored: If you have `strace`, then `strace -e file awesome -k 2>&1 | grep rc.lua` should tell you which config files AwesomeWM is using.
Does `env | grep XDG` say anything helpful? I'm not quite sure, but `$XDG_CONFIG_PATH` might be the relevant variable for finding, well, configs.

**Comment by Berkmann18** [comment]
@Veratil I've done that and reloaded awesome but it still uses the default config.

@psychon 
> If you use startx to start awesome, then you would not have such files.

Good to know. 

> You could try something like startx > /tmp/stdout.txt 2> /tmp/stderr.txt to get the output into files.

I'll try that.

> `strace -e file awesome -k 2>&1 | grep rc.lua` should tell you which config files AwesomeWM is using.

Here's what I get:
```shell
openat(AT_FDCWD, "$HOME/.config/awesome/rc.lua", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/etc/xdg/awesome/rc.lua", O_RDONLY) = 3
openat(AT_FDCWD, "/etc/xdg/awesome/rc.lua", O_RDONLY) = 3
```

> Does env | grep XDG say anything helpful?

```shell
XDG_CONFIG_HOME=$HOME/.config
XDG_SEAT=seat0
XDG_SESSION_TYPE=tty
XDG_SESSION_CLASS=user
XDG_VTNR=1
XDG_SESSION_ID=1
XDG_RUNTIME_DIR=/run/user/1000
```
Seems like `XDG_CONFIG_HOME`'s value is the culprit here which makes me think I've followed the wrong instruction in a Arch documentation for autostarts.
