### ISSUE TITLE
gears.wallpaper.prepare_context - delayed call

### ISSUE THREAD

**Issue by DorianGray** [awesomeWM/awesome#2835]
latest master of awesome and lgi

After adding some lgi async code with gears.protected_call in a totally unrelated part of the code, the gears.wallpaper.prepare_context function in the delayed call section suddenly sees the pending_wallpaper variable as nil.

I determined that the function is only being called once, but apparently the delayed call is being called before the pending_wallpaper variable is set later in the function? My wallpaper is being drawn correctly and on all screens... can someone explain the purpose of the delayed call here?

**Comment by Elv13** [comment]
> can someone explain the purpose of the delayed call here?

Setting a wallpaper on a large root surface (let say 5 screens) is very slow (> 1 seconds). The last thing you want is to do it 5 time in the same event loop iteration (and freeze for > 5 seconds).

**Comment by psychon** [comment]
> I determined that the function is only being called once, but apparently the delayed call is being called before the pending_wallpaper variable is set later in the function? 

I did another quick look at this function. So, if `pending_wallpaper` is `nil`, then `gears.wallaper.prepare_context()` only calls `cairo` between the calls to `gears.timer.delayed_call` and setting `pending_wallpaper`. Are you somehow messing with LGI's cairo bindings (=monkey patching functions in there)?

Could you dump a call to `print(debug.traceback())` in the delayed call in `gears.wallpaper` to get us at least the Lua part of the traceback that got us here? That should point out how you managed to start a `GMainLoop` before `gears.wallpaper.prepare_context` returned.

**Comment by DorianGray** [comment]
Yes, I'll look into it and dig deeper into awesome's code. I want to learn how this occurred myself, but it sounds like since @Elv13 wants to deprecate this method of setting a wallpaper anyways it might not be that important to fix now anyways.
