### ISSUE TITLE
Bottom text of tooltips is cut off

### ISSUE THREAD

**Issue by last5bits** [awesomeWM/awesome#2840]
Output of `awesome --version`:

```
awesome v4.3-317-gb475c23fd (Too long)
 • Compiled against Lua 5.3.5 (running with Lua 5.3)
 • D-Bus support: ✔
 • xcb-errors support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
```

**How to reproduce the issue:**

Create a widget with a tooltip.

**Actual result:**

![image](https://user-images.githubusercontent.com/290707/62013726-a1265280-b164-11e9-846a-aa100e377b8e.png)

**Expected result:**

The bottom tooltip text should not be cut off.

**Comment by psychon** [comment]
Sorry, but.....

> How to reproduce the issue:
> 
> Create a widget with a tooltip.

...this might not be the best description. I cannot reproduce the problem.

I appended the following to the default config:
```lua
local text = io.popen("cal"):read("*a") -- io.popen() is bad! do not use!
local text = text:gsub('\n$', '') -- Remove trailing newline
print(text)
awful.tooltip{ objects = { mytextclock } }:set_text(text)
```
Result is:
![tooltip](https://user-images.githubusercontent.com/89482/62062042-8fa67e80-b228-11e9-9d57-5ad01ab1613c.png)

(Yes, I am German; yes, there are funny characters in there, but that is not important here)

**Comment by last5bits** [comment]
@psychon Thanks for the quick reply. I did some more digging and discovered that the problem gets exposed once the theme font is increased; e.g., from `theme.font = "sans 8"` to `theme.font = "sans 10"`.

Please let me know if you can reproduce it.

**Comment by sigprof** [comment]
Did you recently update the `pango` library to 1.44.x? Another bug related to missing text (#2844) was just reported, and it turned out that the problem appeared after updating `pango` from 1.43.0 to 1.44.

**Comment by last5bits** [comment]
@sigprof Yup, that's it. Downgrading pango solved the issue, thank you!

Closing this one as a duplicate of #2844.
