### ISSUE TITLE
authentication failed while installing packages

### ISSUE THREAD

**Issue by najamsk** [awesomeWM/awesome#2841]
Output of `awesome --version`:
awesome v4.3 (Too long)
 • Compiled against Lua 5.3.5 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2

**How to reproduce the issue:**

launch pacman gui installer. by going to main menu and launch add or remove software. then tryi installing something and gives you a dialogue saying authentication failed. same thing works with i3gaps.  I first installed manjaro awesomewm edition wipe it clean for this error. then now install manjaro i3gaps edition and using terminal installed awesomewm. in i3gaps i can install softwares using graphical package manager but in awesome i cant.  

**Actual result:**

dialogue saying authentication failed.

**Expected result:**

asking for password and then install package.

**Comment by psychon** [comment]
I'm sorry and I know that this does not help you in any way, but I do not think that this is an issue in AwesomeWM.

Sadly, I do not have any good suggestions on where to ask instead. I do not know what permission system the pacman gui uses. According to https://wiki.archlinux.org/index.php/Pacman/Tips_and_tricks#Graphical, there are lots of GUIs for pacman and none is called pacman gui, so I also cannot check out how it works.

Sorry.

**Comment by Elv13** [comment]
> where to ask instead

Probably in the AUR package comments? If this works in i3 and doesn't work in AwesomeWM, then the difference must be how the session details are packaged? Neither i3 nor AwesomeWM handle polkit or other permission frameworks directly.

**Comment by najamsk** [comment]
yes culprit was polkit. pamac gtk based manager is using it. and its required to run when your session starts. i3 was using it in its confir. few awesomewm rice also include that. so i copied few lines from there and it started working. vanila awesomewm doesnt call polkit so this manager that comes preinstalled with manjaro throws error.

**Comment by DanielSuazo** [comment]
> so i copied few lines from there and it started working. vanilla awesomewm doesn't call polkit so this manager that comes preinstalled with manjaro throws error.

Sorry if its a dumb question but i have the same issue and i have no idea what to do to make polkit run. Would you mind giving a little more detail on how to did it?

**Comment by actionless** [comment]
you need to add polkit daemon to autostart
