### ISSUE TITLE
No bitmap fonts in awesome since pango 1.44

### ISSUE THREAD

**Issue by lynix** [awesomeWM/awesome#2842]
pango 1.44.0 [dropped](https://github.com/GNOME/pango/blob/master/NEWS) support for bitmap (and type1) fonts. This breaks our beloved _Terminus_ (and the-like) styled wibars.

Any plans for changing the awesome font rendering stack, or shall we switch over to using TTF or OTF?

**Comment by psychon** [comment]
> Any plans for changing the awesome font rendering stack

Changing to what?

**Comment by lynix** [comment]
> > Any plans for changing the awesome font rendering stack
> 
> Changing to what?

Well, an equivalent of pango that does not break bitmap fonts ;)

I must admin that I'm not familiar with font rendering libraries but I assume there must be alternatives.

**Comment by psychon** [comment]
I do not know much about this stuff myself.

Pango uses (well, used) freetype and fontconfig (and freebidi and libthai and harfbuzz? and ....).
GTK uses Pango. Qt fontconfig and freetype and harfbuzz and most likely lots of other stuff.

Seems like Qt implemented their own version of what Pango does. There does not seem to be much of an alternative to use. I do not have any interest to reinvent Pango and... dunno, using Qt is not really possible (and I do not want to do that).

Random Google results: https://gitlab.gnome.org/GNOME/pango/issues/386 https://blogs.gnome.org/mclasen/2019/05/25/pango-future-directions/

**Comment by lynix** [comment]
Just had my own round of Google research. It seems one can work around this limitation by converting bitmap fonts to bitmap-only OpenType (.otb).

I'll try to do so with _Terminus_. If this works out and doesn't come with too much loss of sharpness, I'd consider the issue resolved.

**Comment by lynix** [comment]
Done, works like a charm. I used a fontforge-based [conversion script](https://aur.archlinux.org/cgit/aur.git/tree/otbconvert.pe?h=dina-font-otb) from one of the emerging -otb packages in Arch Linux' AUR to convert .bdf to .otb and put the resulting files in _~/.local/share/fonts_.

Shall we close this one, then?
