### ISSUE TITLE
Using an input method in awful.prompt

### ISSUE THREAD

**Issue by Rio6** [awesomeWM/awesome#2845]
Right now I'm trying to make a translator prompt using `awful.prompt`, then I found out I can't use an input method to input chinese characters. (I use [gcin](https://wiki.archlinux.org/index.php/Gcin))

Output of `awesome --version`:

awesome v4.3 (Too long)
 • Compiled against Lua 5.3.5 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2

**How to reproduce the issue:**

Try to type using an input method in an `awful.prompt`

**Actual result:**

The input method doesn't get used, the prompt just shows whatever key I pressed instead of having the IM turn it into chinese charaters.

**Expected result:**

The input method gets the key I type and turns them into chinese charaters.

I think it's because the prompt just grabs whatever key gets pressed and draw them out. But it would be nice to have something like [SDL's textinput api](https://wiki.libsdl.org/Tutorials/TextInput).
I can probably use zenity to do the job but it would be nice to have it as a widget.
Or is there a widget already that has a text input area?

Thanks

**Comment by psychon** [comment]
Short answer: Sorry, but not going to happen any time soon. Text input is surprisingly difficult. :-(
Currently, the key bindings do not even handle the active keyboard layout correctly.

**Comment by Rio6** [comment]
Alright then, maybe I can write a small gtk application that match my theme. Or just use zenity

**Comment by myagko** [comment]
Maybe its too late, but i made my own (text input widget)[https://github.com/myagko/dotfiles/blob/main/home/.config/awesome/ui/widgets/text_input_utf8.lua] with utf8 support, which is very similar to `awful.prompt`, here is an (example)[https://github.com/myagko/dotfiles/blob/940a2903bda00aaae476720af0ec5b9194ab5c85/home/.config/awesome/ui/launcher.lua#L198] of usage. All you need is to install (luautf8)[https://github.com/starwing/luautf8?tab=readme-ov-file] package via luarocks.
