### ISSUE TITLE
cursor name "hand" doesn't work 

### ISSUE THREAD

**Issue by paranoid73** [awesomeWM/awesome#2856]
Hello ,
```
awesome v4.3-364-gb2ebf899 (Too long)
 • Compiled against Lua 5.3.5 (running with Lua 5.3)
 • D-Bus support: ✔
 • xcb-errors support: ✘
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
```

I created a wibox 
`wibox({ border_width = 10, border_color = beautiful.color.main, x = 400,  y = 250, ontop = true, visible = false, type = "dock", height = 200 , width = 500 , shape      = custom_shape,bg = beautiful.color.bg_second  })`
I would like to change the shape of the cursor, when I fly over the widget but
when i use "clock" or any cursor name  it works without problem but not witth "hand" name.
```
btn_2:connect_signal("mouse::enter", function()
  btn_2.bg  = beautiful.color.main
  local w = mouse.current_wibox
  old_cursor, old_wibox = w.cursor, w
  w.cursor = "hand"
end)
```
![2019 08 20-17 10 34 screenshot](https://user-images.githubusercontent.com/34898251/63368471-80b97480-c36d-11e9-97f6-78321ccd193d.png)

**Comment by Veratil** [comment]
Can you try `hand1` or `hand2` ?

**Comment by paranoid73** [comment]
> Can you try `hand1` or `hand2` ?

it works , thank you

**Comment by Veratil** [comment]
@paranoid73 This may help for other common names https://wiki.archlinux.org/index.php/Cursor_themes#Create_links_to_missing_cursors

**Comment by psychon** [comment]
Just a small addendum:
```
$ grep -i hand /usr/include/X11/cursorfont.h 
#define XC_hand1 58
#define XC_hand2 60
```
