### ISSUE TITLE
Missing gears.table.iterate_value in awful.widget.layoutlist example

### ISSUE THREAD

**Issue by krzygorz** [awesomeWM/awesome#2869]
Output of `awesome --version`:

awesome v4.3 (Too long)
 • Compiled against Lua 5.3.5 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2

**How to reproduce the issue:**

I pasted the center popup example from https://awesomewm.org/doc/api/classes/awful.widget.layoutlist.html into a file and `require`d it in my config. When i press mod4+space awesome throws an error.

**Actual result:**

    ~/.config/awesome/layoutlist.lua: 54: attempt to call a nil value (field 'iterate_value')

**Expected result:**

The popups appears, no errors are thrown.

**Additional notes:**

I found a [post](https://www.reddit.com/r/unixporn/comments/akbu6k/awesomewm_wait_why_did_i_do_this_again/) by @Elv13 in /r/unixporn which includes a [config](https://gist.github.com/Elv13/b679fe3cb100cd63a7082cc808d316b8) with a definition of `gears.table.iterate_value`. If this function is not supposed to be part of the awesome library, maybe the code should be included in the example?

**Comment by gunar** [comment]
Sorry, anyone has an idea why I can't find `gears.table.cycle_value` on `awesome 4.3`?

**Comment by psychon** [comment]
That function was added in commit 9e3c418a03 which is after 4.3. So the answer to your question is "because it was only added after the release of v4.3, not before".
