### ISSUE TITLE
Wallpaper not properly painted after first restart (with changed screen offset)

### ISSUE THREAD

**Issue by blueyed** [awesomeWM/awesome#288]
When going to my docking station (with an external monitor) I need to manually
start awesome once more, to fix the wallpaper on the smaller / internal screen:
its offset and scaling is OK, but it does not cover the lower part, which is black.

After restarting once more, it gets painted properly.

It looks like an offset/height calculation issue: the internal screen gets an offset of 432 (when docked).

I am using `theme.wallpaper` from the xresources theme (which is a
`cairo.ImageSurface`), and set it using:

    for s = 1, screen.count() do
        gears.wallpaper.maximized(beautiful.wallpaper, s, true)
    end

(A normal image path will have the same effect.)

The xrandr setup, which triggers this:

    % xrandr --output HDMI2 --gamma 1.0:1.3:1.6 --mode 1920x1200 --panning 0x0 --pos 1366x0 --rate 60.0 --reflect normal --rotate normal --transform 1,0,0,0,1,0,0,0,1 --output LVDS1 --gamma 1.0:1.3:1.6 --mode 1366x768 --panning 0x0 --pos 0x432 --primary --rate 60.0 --reflect normal --rotate normal --transform 1,0,0,0,1,0,0,0,1
    (via [autorandr](https://github.com/phillipberndt/autorandr)).

    % xrandr -q
    Screen 0: minimum 8 x 8, current 3286 x 1200, maximum 32767 x 32767
    LVDS1 connected primary 1366x768+0+432 (normal left inverted right x axis y axis) 277mm x 156mm
    HDMI2 connected 1920x1200+1366+0 (normal left inverted right x axis y axis) 519mm x 324mm

Coming from:

    % xrandr --output HDMI2 --off
    % xrandr --output LVDS1 --gamma 1.0:0.909:0.833 --mode 1366x768 --panning 0x0 --pos 0x0 --primary --rate 60.0 --reflect normal --rotate normal --transform 1,0,0,0,1,0,0,0,1

That does not happen when using `feh` to set the wallpapers:

    awful.util.spawn('feh --randomize --bg-fill /path/to/wallpapers/')

The restart happens through `event_handle_configurenotify`, and I am seeing no
calls to `event_handle_randr_screen_change_notify`.

But it can be reproduced without the automatic restarting.

It's strange that it's fixed after another restart, so some persistent X setting/property might influence this.

I have not tested it with the default config yet, to check if it's related to my config.

**Comment by psychon** [comment]
Can you try if the following patch detects the situation?

The theory here is that awesome restarts while xrandr is still changing things and so it gets the screen size before it changes, but also before it registers itself for notification of screen size changes (and thus it does not restart again).

```diff
diff --git a/awesome.c b/awesome.c
index 4ab7258..37ece6a 100644
--- a/awesome.c
+++ b/awesome.c
@@ -548,6 +548,20 @@ main(int argc, char **argv)
                                  XCB_CW_EVENT_MASK,
                                  ROOT_WINDOW_EVENT_MASK);
 
+    {
+        xcb_get_geometry_reply_t *r = xcb_get_geometry_reply(globalconf.connection,
+                xcb_get_geometry(globalconf.connection, globalconf.screen->root), NULL);
+        if (!r
+                || r->width != globalconf.screen->width_in_pixels
+                || r->height != globalconf.screen->height_in_pixels) {
+            warn("Root window size does not match the expected one. Expecting %dx%d, but got %dx%d\n",
+                    globalconf.screen->width_in_pixels, globalconf.screen->height_in_pixels,
+                    r != NULL ? r->width : -1,
+                    r != NULL ? r->height : -1);
+        }
+        free(r);
+    }
+
     /* we will receive events, stop grabbing server */
     xcb_ungrab_server(globalconf.connection);
     xcb_flush(globalconf.connection);
```

**Comment by blueyed** [comment]
@psychon 
Nope, the patch does not give a warning.

**Comment by psychon** [comment]
Does this still happen? Could you try throwing some random `print()`s into `gears.wallpaper` and see if you can find something that is wrong? Finally, could you add `xcb_aux_sync(c);` to `root_set_wallpaper()` right after the `disconnect:` label (somewhere before `xcb_disconnect(c)`, does not matter where it is compares to the `xcb_flush(c)`)?

**Comment by blueyed** [comment]
Yes, still happens.
I need to investigate.

(Maybe related: I am using slock (IIRC) as a screensaver, and noticed that it will only cover the first/main screen after resuming from suspend, and not the external screen altogether.)

**Comment by blueyed** [comment]
`prepare_wallpaper` gets called seemingly correct:
```
print("DWP: prepare_wallpaper", s, geom.x, geom.y, geom.width, geom.height) =>
DWP: prepare_wallpaper	1	0	432	1366	768
DWP: prepare_wallpaper	2	1366	0	1920	1200
```

It seems to be something outside of `gears.wallpaper` anyway, because a restart fixes it, no?

> add xcb_aux_sync(c); to root_set_wallpaper()

Did not help.

When I change the Y position/offset of the affected screen using e.g. `arand` to be at 0, the top of the wallpaper gets displayed and then the tasklist starts at 432 (not measured, but looks like it).
That seems to come from the internal offset it uses to be on the top of the screen.
Given this, the whole screen is filled with the background, although it starts again at 432+tasklist offset.

Will check the default config now.

**Comment by blueyed** [comment]
I do not need to restart awesome to fix it, but setting the wallpaper through awesome-client also works around it:

```
function set_wallpaper()
if beautiful.wallpaper then
    for s = 1, screen.count() do
        -- gears.wallpaper.maximized('/home/daniel/Downloads/wallpapers/uOqEOCd.jpg', s, true)
        gears.wallpaper.maximized(beautiful.wallpaper, s, true)
    end
end
end

…

echo 'set_wallpaper()' | awesome-client
```

Using `timer.delayed_call` does not help, even with an additional inner one.

**Comment by psychon** [comment]
Another random idea is to put `surface(root.wallpaper()):write_to_png("/tmp/wallpaper.png")` into random positions, perhaps with some counter variable to get different file names at different places.

My ideas so far are:
- Awesome is starting while the RandR configuration is still being changed and thus sees some intermediate state. That's what the patch from July and my `print()`-suggestion was looking for.
- Awesome doesn't actually wait for the X11 server to be done setting the wallpaper before continuing. That's what the `xcb_aux_sync()` was for.
- Something (gears.wallpaper? cairo?) does something wrong. That's what this `:write_to_png()` idea should catch. (Quite a general idea, I know. At least this would also get us the "intermediate steps" after setting up the wallpaper of each screen.)

Hm... Another idea: The current code draws to the old wallpaper without knowing or checking about its size (perhaps it's smaller than the screen, for whatever reason?). So another patch:
```diff
diff --git a/lib/gears/wallpaper.lua b/lib/gears/wallpaper.lua
index 8610b23..6b65c1c 100644
--- a/lib/gears/wallpaper.lua
+++ b/lib/gears/wallpaper.lua
@@ -42,14 +42,22 @@ local function prepare_wallpaper(s)
         img:set_device_offset(-geom.x, -geom.y)
     end
 
-    local cr = cairo.Context(img)
+    local real = img:create_similar(cairo.Content.COLOR, root_geom.width, root_geom.height)
+
+    local cr = cairo.Context(real)
+
+    cr:save()
+    cr.operator = cairo.Operator.SOURCE
+    cr:set_source_surface(img, 0, 0)
+    cr:paint()
+    cr:restore()
 
     -- Only draw to the selected area
     cr:translate(geom.x, geom.y)
     cr:rectangle(0, 0, geom.width, geom.height)
     cr:clip()
 
-    return geom, img, cr
+    return geom, real, cr
 end
 
 --- Set the current wallpaper.
```

**Comment by blueyed** [comment]
@psychon 
Your patch fixes it!
