### ISSUE TITLE
How to add transparency support for terminals

### ISSUE THREAD

**Issue by xeon826** [awesomeWM/awesome#2884]
awesome v4.2 (Human after all)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.5
 • LGI version: 0.9.2

**How to reproduce the issue:**
Use default setup for awesomewm
Add 
`URxvt.transparent: true
URxvt.shading:20`
or something similar in .Xdefaults

**Actual result:**
Background is plain black.

**Expected result:**

Background should be moderately transparent.

Looking [here](https://github.com/awesomeWM/awesome/issues/2473) I found somewhat of an answer but how do I make this the default setting?

**Comment by Elv13** [comment]
Hi,

You need to install (and use) a compositing manager such as `compton`. AwesomeWM is a window manager. not a desktop compositor.

**Comment by psychon** [comment]
> How to reproduce the issue:
> Use default setup for awesomewm
> Add
> URxvt.transparent: true URxvt.shading:20
> or something similar in .Xdefaults
> 
> Actual result:
> Background is plain black.

For me, `urxvt -tr -sh 20` works fine (at least it works in the expected way: this is not real transparency, but "urxvt draws the wallpaper as its background faded to black"). If this does not work, it might depend on how you are setting your wallpaper (for me, I set the wallpaper through awesome). Does `xprop -root _XROOTPMAP_ID` find something or does it say "no such atom"? In the later case, you might try another wallpaper setter.

**Comment by xeon826** [comment]
> > How to reproduce the issue:
> > Use default setup for awesomewm
> > Add
> > URxvt.transparent: true URxvt.shading:20
> > or something similar in .Xdefaults
> > Actual result:
> > Background is plain black.
> 
> For me, `urxvt -tr -sh 20` works fine (at least it works in the expected way: this is not real transparency, but "urxvt draws the wallpaper as its background faded to black"). If this does not work, it might depend on how you are setting your wallpaper (for me, I set the wallpaper through awesome). Does `xprop -root _XROOTPMAP_ID` find something or does it say "no such atom"? In the later case, you might try another wallpaper setter.

I get "_XROOTPMAP_ID(PIXMAP): pixmap id # 0x400000" but I found the answer is actually very simple, I just need to add xcompmgr to my start up applications then something like `urxvt*depth: 32
urxvt*background: rgba:0000/0000/0200/c800` to my .Xdefaults

**Comment by xeon826** [comment]
But now I'm kind've just trying to figure out how to decrease the opacity of "rgba:0000/0000/0200/c800" as I'm not too familiar with this method of formatting.

**Comment by psychon** [comment]
That's a "color" definition: 0 red, 0 green, 0200 blue and c800 alpha. In html, this would be something like that `#000002c8`. To have less opacity, you have to change the `c800` part, for example to `8000`.

**Comment by xeon826** [comment]
> That's a "color" definition: 0 red, 0 green, 0200 blue and c800 alpha. In html, this would be something like that `#000002c8`. To have less opacity, you have to change the `c800` part, for example to `8000`.

So I put the value of the 4th to 9999 and see the opacity increase (by that I mean it increases in visibility which is what I want) and then I put a c at the beginning so it's `c999` it increases further but beyond this, I can't find how to increase the visibility.

**Comment by xeon826** [comment]
So I end up just using [95]#000000
