### ISSUE TITLE
Question about wibox.widget.graph

### ISSUE THREAD

**Issue by deb75** [awesomeWM/awesome#2899]
Output of `awesome --version`:

awesome v4.3 (Too long)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2

Hello,

I would like to use `wibox.widget.graph` to display several functions, like plotting two lines on the same 2D graph for two functions y=f(x) and y = g(x). However, the few screenshots of `wibox.widget.graph` let me think it can only draw bar graphs, instead of just a line, and so that it cannot plot several functions.

Is there a way to perform what I want with `wibox.widget.graph` or another widget ?

Regards

**Comment by psychon** [comment]
I'm not sure how visible just a line would be.

Did you see the `stack` feature of `wibox.widget.graph`? But I guess this also does not do what you want.

Another option would be writing your own widget. It is not as complicated as one might think.

Where do the functions come from? Are these lines like memory usage or what do you have in mind?

**Comment by Elv13** [comment]
Well, there's https://github.com/blindFS/blingbling , but it is very, very old and way, way behind on all the API changes made in the last ~10 years. Some of the code can be salvaged, but it will take some solid effort to revive the core and implement all the API changes from AwesomeWM v3.4 (2009) to today.

**Comment by psychon** [comment]
> If it is not complicated to write one's widget,

Here is some code that you can hopefully start from. I think that if you know some Lua, you should be able to manage.

This code creates a widget that draws some random lines. A timer is used to add new data to the widget. For your use case, you most likely also want to remove old data from the widget.
```lua
local my_widget = wibox.widget.base.make_widget()
my_widget._private.min_value = 0
my_widget._private.max_value = 1
my_widget._private.colors = { "#f00", "#0f0" }
my_widget._private.data = {}
function my_widget:add_data(data)
    local len = #data
    if self._private.len and self._private.len ~= len then
        error()
    end
    self._private.len = len
    table.insert(self._private.data, data)
    self:emit_signal("widget::redraw_needed")
end
function my_widget:fit(_, width, height)
    -- We just want all available space
    return width, height
end
function my_widget:draw(_, cr, width, height)
    local data = self._private.data
    local colors = self._private.colors

    -- Ensure we have at least two points of data
    if #data == 0 then
        return
    end
    if #data == 1 then
        data = { data[1], data[1] }
    end

    -- Scale things so that we have less coordinate values to shuffle
    local xscale = width / (#data - 1)
    local yscale = height / (self._private.max_value - self._private.min_value)

    -- Now, actually draw things
    for line = 1, self._private.len do
        local color = colors[(line - 1) % #colors + 1]
        cr:set_source(gears.color(color))
        for i = 1, #data do
            cr:line_to((i - 1) * xscale, data[i][line] * yscale)
        end
        cr:stroke()
    end
end

gears.timer.start_new(1, function()
    my_widget:add_data({ math.random(), math.random(), math.random() })
    return true
end)
```
Does this help you?

**Comment by deb75** [comment]
Great :-)

I will look into it

Regards

**Comment by deb75** [comment]
Hi,

@psychon : I tried to run the code you posted with `cat test.lua | awesome-client` , where `test.lua` is just the code you send, but nothing appeared so far and no error occured in the logs.

Do I miss something ?

**Comment by psychon** [comment]
That code just creates the widget but does not add it to anything so that it gets displayed.

Here is a patch for the default config:
```diff
diff --git a/awesomerc.lua b/awesomerc.lua
index 948407220..6668ca0e7 100644
--- a/awesomerc.lua
+++ b/awesomerc.lua
@@ -49,6 +49,56 @@ editor_cmd = terminal .. " -e " .. editor
 -- However, you can use another modifier like Mod1, but it may interact with others.
 modkey = "Mod4"
 
+local my_widget = wibox.widget.base.make_widget()
+my_widget._private.min_value = 0
+my_widget._private.max_value = 1
+my_widget._private.colors = { "#f00", "#0f0" }
+my_widget._private.data = {}
+function my_widget:add_data(data)
+    local len = #data
+    if self._private.len and self._private.len ~= len then
+        error()
+    end
+    self._private.len = len
+    table.insert(self._private.data, data)
+    self:emit_signal("widget::redraw_needed")
+end
+function my_widget:fit(_, width, height)
+    -- We just want all available space
+    return width, height
+end
+function my_widget:draw(_, cr, width, height)
+    local data = self._private.data
+    local colors = self._private.colors
+
+    -- Ensure we have at least two points of data
+    if #data == 0 then
+        return
+    end
+    if #data == 1 then
+        data = { data[1], data[1] }
+    end
+
+    -- Scale things so that we have less coordinate values to shuffle
+    local xscale = width / (#data - 1)
+    local yscale = height / (self._private.max_value - self._private.min_value)
+
+    -- Now, actually draw things
+    for line = 1, self._private.len do
+        local color = colors[(line - 1) % #colors + 1]
+        cr:set_source(gears.color(color))
+        for i = 1, #data do
+            cr:line_to((i - 1) * xscale, data[i][line] * yscale)
+        end
+        cr:stroke()
+    end
+end
+
+gears.timer.start_new(1, function()
+    my_widget:add_data({ math.random(), math.random(), math.random() })
+    return true
+end)
+
 -- @DOC_LAYOUT@
 -- Table of layouts to cover with awful.layout.inc, order matters.
 awful.layout.layouts = {
@@ -198,6 +248,7 @@ screen.connect_signal("request::desktop_decoration", function(s)
             mylauncher,
             s.mytaglist,
             s.mypromptbox,
+            my_widget,
         },
         s.mytasklist, -- Middle widget
         { -- Right widgets
```
(And for the next question that you will be most likely asking: Well, what size do you want this widget to be? You can either put it into a `wibox.container.constraint` to get that size or add something like `function my_widget:fit(context, width, height) return 50, 20 end` to the code to force a specific size.)
