### ISSUE TITLE
[Regression from 3.5.6] Gap in tiling layout with d361eea

### ISSUE THREAD

**Issue by juw** [awesomeWM/awesome#290]
Hi,

with the current git-master, there is a vertical gap between the windows in the tiling layouts (e.g with awful.layout.suit.tile there is a 3px wide gap between the windows main window and the other windows). I have set "theme.useless_gap = 0", since I am using the default theme, so this should not be the cause. This gap does not appear with awesome 3.5.6.

Cheers,
Julian

**Comment by Elv13** [comment]
Are you sure its not just a size_honoring client? Have you tried disabling size honoring?

**Comment by psychon** [comment]
Do you know some last good version? When started this happening?
Which programs are you testing with? Could you test without terminals or text-editors (e.g. xcalc).
Does this also happen with the default config?
Perhaps a screenshot?

**Comment by juw** [comment]
Am Mon, 06 Jul 2015 10:54:44 -0700
schrieb Uli Schlachter <notifications@github.com>:

> Do you know some last good version? When started this happening?
> Which programs are you testing with? Could you test without terminals
> or text-editors (e.g. xcalc). Does this also happen with the default
> config? Perhaps a screenshot?

Sorry, I should have been more thorough, it happens with urxvt with the
default config. I checked with Iceweasel, there the problem does not
occur.

**Comment by juw** [comment]
Am Mon, 06 Jul 2015 10:19:47 -0700
schrieb Emmanuel Lepage Vallée <notifications@github.com>:

> Are you sure its not just a size_honoring client? Have you tried
> disabling size honoring?

Since it happens with urxvt, maybe it is a size honoring client, I do
not know. How can one disable size honoring?

Cheers.

**Comment by psychon** [comment]
https://awesome.naquadah.org/wiki/FAQ#How_to_remove_gaps_between_windows.3F

**Comment by juw** [comment]
Am Mon, 06 Jul 2015 12:06:23 -0700
schrieb Uli Schlachter <notifications@github.com>:

> https://awesome.naquadah.org/wiki/FAQ#How_to_remove_gaps_between_windows.3F

That I should have found myself. It does the trick and removes the gap
again.

I can bisect the behaviour change, if it is of interest, but that will
take some time.

Thank you for your quick help,
Julian

**Comment by blueyed** [comment]
The behaviour should not have changed between 3.5.6 and master (AFAIK), so bisecting it would be interesting.
But it looks more like a config change on your side.

**Comment by juw** [comment]
I reinvestigated: What happend ist, that before, the gap was between the right border of the screen and the window closest to that screen border. Now it just shifted, so that it is between the windows.
