### ISSUE TITLE
Is there a way to minimize all windows in the current tag a-la Win-M in Windows?

### ISSUE THREAD

**Issue by xor512** [awesomeWM/awesome#2906]
Output of `awesome --version`:

awesome v4.3 (Too long)
 • Compiled against Lua 5.3.5 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2

**How to reproduce the issue:**

Have a wallpaper. Open several terminals, browser and whatever else on a floating, tiling or any other tag. Now want to see wallpaper with  one shortcut.

**Actual result:**

Lua code has to be added to rc.lua

**Expected result:**

Lua code might have been already written for that. The closest thing I googled is https://github.com/awesomeWM/awesome/issues/92 which confused me more than helped although I do have some knowledge on Lua. Can anyone help?

PS I want to see wallpaper only on currently opened tag but i can modify the solution it will minimize everything everywhere.

Thank you!

Edit by psychon: Removed inappropriate description of the wallpaper.

**Comment by psychon** [comment]
Something like this (untested)?
```
function minimise_all_clients_on_current_tag()
    for _, c in ipairs(mouse.screen.selected_tag:clients()) do
        c.minimized = true
    end
end
```

**Comment by xor512** [comment]
This worked like a charm! Smth like;

`clientkeys = gears.table.join(
    awful.key({ modkey, "Control"   }, "m",      
        function ()
            for _, c in ipairs(mouse.screen.selected_tag:clients()) do
                 c.minimized = true
            end
        end,
              {description = "close all windows in current tag", group = "client"}),

Thanks!`

**Comment by xor512** [comment]
@psychon Everything works but unfortunately I started to want more and got stuck. :( What I wanted is:

1. Shortcut to close every window in currently opened tag
2. Shortcut to minimize every window in currently opened tag
3. Shortcut to bring back every window in currently opened tag

1 and 2 where easy but 3 is a real pain. Even if i mininize one window with modjey+N and then try to bring back it appears in a different place. Here is what I am trying to do;

    `clientkeys = gears.table.join(
    awful.key({ modkey, "Control"   }, "m",      
        function ()
            for _, cl in ipairs(mouse.screen.selected_tag:clients()) do
                 local c = cl
                 if c then
                   c.minimized = true
                 end
            end
        end,
              {description = "minimize all windows in current tag", group = "client"}),
    awful.key({ modkey, "Control"   }, "n",      
        function ()
            for _, cl in ipairs(mouse.screen.selected_tag:clients()) do
                 local c = cl
                 --if c then
                 --   c.unminimize = true
                 --end
                 c:emit_signal(
                     "request::activate", "key.unminimize", {raise = true}
                 )
            end
        end,
              {description = "maximize all windows in current tag", group = "client"}),
    awful.key({ modkey, "Control"   }, "c",      
        function ()
            for _, cl in ipairs(mouse.screen.selected_tag:clients()) do
                 local c = cl
                 if c then
                   c:kill()
                 end
            end
        end,
              {description = "close all windows in current tag", group = "client"}),`
    
Problem is here:

    `            --if c then
                 --   c.unminimize = true
                 --end
                 c:emit_signal(
                     "request::activate", "key.unminimize", {raise = true}
                 )`

None of this works. it restores only one window in a place it wants.

can you please help once agan? I would be very appreciated1a

**Comment by psychon** [comment]
It should be `c.minimized = false` to un-minimize a client.

**Comment by AndrePasache** [comment]
In order to restore all minimized windows you should add that instruction to globalkeys table.
Inside this funtion: `globalkeys=gears.table.join()`
I recommend to place it below the restore minimized funtion
```
awful.key({modkey, "Shift"   }, "a",
      funtion()
          for _, c in ipairs(mouse.screen.selected_tag:clients()) do
              local c = awful.client.restore()
              if c then
                  c:emit_signal(
                  "request::activate",  "key.unminimize, {raise = true}
                  )
              end
          end
      end,
          {description = "restore all minimized windows in current tag", group = "client"}),
```

**Comment by hzaphry** [comment]
Thank you guys so much for inspiring me to solve this one. 
I had it configured like I used to and feels more natural to me, and maybe x windows users.

It looks first if there's any windows that's not minimized in the tag. If yes it minimizes all. if not it restores all minimized.

```
awful.key({modkey}, 'd',
function ()
  for _, cl in ipairs(mouse.screen.selected_tag:clients()) do
    local c = cl
    if c then
      if _G.client.focus then
        c.minimized = true
        else
          c.minimized = false
      end
    end
  end
end,
{description = "min/max all windows", group = "client"}
),
```

**Comment by treymerkley** [comment]
@hzaphry how would I exclude select windows? I'd like to leave up my XFCE status bar and my conky.

**Comment by Aire-One** [comment]
@treymerkley, my recommendation is to replace the `ipairs(mouse.screen.selected_tag:clients())` call by `awful.client.iterate(...)`. https://awesomewm.org/apidoc/core_components/client.html#awful.client.iterate

This function needs a filter callback, that you can use to select the clients you want to minimize. As shown in the doc example, you can use `ruled.client.match()` to select particular clients (use the `not` keyword to exclude then from the result).
