### ISSUE TITLE
Restore an easy way to force width/height/visible

### ISSUE THREAD

**Issue by Elv13** [awesomeWM/awesome#291]
Replacing `:fit()` is a hack. There should be a better way. Ideally one that restore Awesome 3.4 properties

**Comment by psychon** [comment]
Better way would be a constraint layout, I guess.
A .visible property (or :set_visible()?) could be implemented with the widget system if we make sure layouts don't directly call widgets, but use wrapper functions (e.g. by new widget layout system branch should do this).

Having working properties on widgets that transparently forwards to `:set_foo(bar)` and `:get_bar()' requires some non-trivial metatable magic. Do we want to implement some generic object stuff in `gears.object`? Or perhaps export some callback functions for `_index` and `_newindex` that could be used, but I'm not sure how exactly those should look like to work generally ("if field exists, use it directly, else just assume that a suitable setter / getter exists" would work, but produces weird error messages on typos. Checking for the existence of the setter / getter before calling it conflicts with other metatable magic).

**Comment by Elv13** [comment]
It's all there https://github.com/Elv13/radical/blob/master/object.lua

**Comment by psychon** [comment]
Done in #586
