### ISSUE TITLE
Compiling awesome change `docs/common/rules_index.ldoc`

### ISSUE THREAD

**Issue by Aire-One** [awesomeWM/awesome#2911]
Output of `awesome --version`:

```
awesome v4.3-496-g344964a4 (Too long)
 • Compiled against Lua 5.3.5 (running with Lua 5.3)
 • D-Bus support: yes
 • xcb-errors support: no
 • execinfo support: yes
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
```

**How to reproduce the issue:**

I basically did a git pull / make 

```sh
$ cd <aweome-dir>
$ git fetch
$ git pull
$ make distclean
$ make -j5 all
```

**Actual result:**

Running `git status` after `make` gives a 
```
modified: docs/common/rules_index.ldoc
```
git diff is:
```diff
diff --git a/docs/common/rules_index.ldoc b/docs/common/rules_index.ldoc
index 8f5e2f53..eeecdbda 100644
--- a/docs/common/rules_index.ldoc
+++ b/docs/common/rules_index.ldoc
@@ -69,4 +69,6 @@
 --   <tr><td><a href='../core_components/client.html#startup_id'>startup\_id</a></td><td>The FreeDesktop StartId</td></tr>
 --   <tr><td><a href='../core_components/client.html#valid'>valid</a></td><td>If the client that this object refers to is still managed by awesome</td></tr>
 --   <tr><td><a href='../core_components/client.html#first_tag'>first\_tag</a></td><td>The first tag of the client</td></tr>
+--   <tr><td><a href='../core_components/client.html#buttons'>buttons</a></td><td>Get or set mouse buttons bindings for a client</td></tr>
+--   <tr><td><a href='../core_components/client.html#keys'>keys</a></td><td>Get or set keys bindings for a client</td></tr>
 -- </table>
```

**Expected result:**

The compilation process should not have modified a source file.

---
This is not the first time I have this file modified when I compile awesome. I can't remember when it started tho...

To be sure it comes from the compilation I ran:
```sh
$ make distclean
$ git reset --hard
$ git status
# Nothing here
$ make -j5 all
$ git status
# The file is modified
```

**Comment by psychon** [comment]
Bisects to f7474388790df81671c338758801d64fa2929da1 and 296ad189225ffda25908b8c17bbbee3a9efd4fd9. Each of them causes one of the two lines to be added.
Should we add `$ git diff-index --quiet HEAD` to `.travis.yml`? That should make the build fail for changes to the source dir that are not in `.gitignore`. (Although it seems we need to do `git status` first to update the index to suppress some false-positives, otherwise it complains about files that were changed, but there content was replaced with what they already contained (although there should still be a way to prevent that)).

CC @Elv13

**Comment by Aire-One** [comment]
I don't know about travis nor #2739. But #2894 should fix this with a810c157b68d44871ddd57ff74f7039409884eee.

**Comment by Aire-One** [comment]
Thanks for your work @Elv13 but I have to admit I'm a little lost regarding `docs/common/rules_index.ldoc` and similar files from the `docs` directory...

Files from the `docs/common` directory are templates used to replace `@DOC_something_COMMON@` tags in ldocs comments (where `something` is the filename).

What I don't get is how/why `docs/common/rules_index.ldoc` get some additional code at compilation time?

Also, some bonus questions passing-by:
- Why isn't the generated part (if the file is partially generated) only added in a `build/docs/...` file?
- (if it's generated) Why is this file in the repo at all? Shouldn't it just be a generated file popping in the `build` directory at compilation?

(BTW, I just checked and the generated part is not present in my final `file:///home/aireone/documents/prog/awesome/build/doc/libraries/awful.rules.html`)

**Comment by Aire-One** [comment]
Since #2894 is now merged, the issue is no more.
