### ISSUE TITLE
[Question] Adjusting Titlebar Buttons Padding

### ISSUE THREAD

**Issue by xcbdz** [awesomeWM/awesome#2912]
This isn't a bug, just a question:  
I want move my minimize, maximize and close buttons closer to each other. I think it's not currently supported based on documentation or maybe I just overlooked it. You can achieve this in gtk3 by changing the padding in the gtk.css file. Any idea to achieve this? Thanks in advance!

**Expected result:**
![20191018_125513](https://user-images.githubusercontent.com/56459896/67067475-1411f900-f1a9-11e9-8e7c-79671a8a8996.jpg)

**Comment by psychon** [comment]
> This isn't a bug, just a question

That's totally fine.

> I want move my minimize, maximize and close buttons closer to each other.

Right now, the buttons are directly next to each other. The padding that you see comes from some transparent padding around the actual source image. You cannot see this in the GitHub UI, but it is visible e.g. in Gimp:

https://github.com/awesomeWM/awesome/blob/master/themes/default/titlebar/close_normal.png

![foo](https://user-images.githubusercontent.com/89482/67105564-42073580-f1c9-11e9-8b39-b37059382d07.png)

So, to change the padding, you have to replace the images by different versions and then change your theme to refer to the new files.
The default theme references the icons here:
https://github.com/awesomeWM/awesome/blob/344964a44a701c564d3441b818c88e5925f3f210/themes/default/theme.lua#L73-L98

It is possible to do this purely in Lua code without changing the source files (load the images, cut of some pixels on all sides, replace the values in the theme). However, I do not have the time to program this right now.

Does this help you?

**Comment by xcbdz** [comment]
Problem solved! Thank you for your help!
