### ISSUE TITLE
Improvement on generated images for the screen API documentation

### ISSUE THREAD

**Issue by Aire-One** [awesomeWM/awesome#2919]
I wasn't in the mood of creating a PR for this. So here is an issue so we can discuss of what I did :)

You can find my changes at https://github.com/Aire-One/awesome/tree/doc_screen_images.

I were looking at the documentation to find what I can do to make it more easy to read and I found these two "issues" on the generated images for the screen API which are fairly easy to fix.

I'd like your feedback :)

ping @Elv13 :)

# Rulers order

![old-rulers-order](https://user-images.githubusercontent.com/6602958/68998096-181b5e80-08ae-11ea-90dd-a3b9d8d2d085.png)

It just don't seems natural the `geometry` rulers is in the middle. The bubble sort algorithm order rulers correctly but when they have the same size. If rulers have the same size, they keep the order they were inserted into the rulers list. So rulers insertion order impact the result of the bubble sort algorithm.

By inverting the order, we can make the `geometry` ruler be always the most outer one. The generated image looks more natural.

![rulers-order](https://user-images.githubusercontent.com/6602958/68998383-c8d72d00-08b1-11ea-9490-452e0679e992.png)

# Wibar

Generated screen images always have a little margin at the top of the `workarea` rect. This space is caused by the wibar which is at the top of the screen in the default `aweseomerc.lua` and in the code to generate images:

```lua
-- This will shift the workarea by 24px at the top.
awful.wibar {
    position = "top",
    height   = 24,
}
```

It's not a big deal once you know it. However, I think there should be an indication of this mechanism. I added a `draw_wibar` parameter to the template generator to draw it in the generated image:

![show-wibar](https://user-images.githubusercontent.com/6602958/68998249-64679e00-08b0-11ea-89cf-56b84df286cf.png)

I think this still need additional work to be drawn differently than area with the stripe pattern, tho..

**Comment by Elv13** [comment]
Thanks for this. Please make a PR when its ready.

This was my vision for this (see the header comment in https://github.com/awesomeWM/awesome/pull/2855). I was the one too lazy to do it :P. Now its done! Just make sure to also take into account clients with their own `:struts()`. They are the "bars"/"docked" clients. AwesomeWM doesn't support 3rd party bars and docked client very well, but it *tries*.

I am super happy someone else steps in to finish this! It was very deep in my TODO list to the point where I wonder if it would have ever got done. I am sure plenty of new users will really appreciate all those improved images. It makes it so much easier to understand when you *see* what an API does without having to try it first.

**Comment by Aire-One** [comment]
> This was my vision for this (see the header comment in #2855).

I read it back then but totally forget about the "what coming next" part :open_mouth: 

> Just make sure to also take into account clients with their own :struts(). They are the "bars"/"docked" clients. AwesomeWM doesn't support 3rd party bars and docked client very well, but it tries.

I'm not sure to understand what you mean here... I have never used dockable client with awesome and I really don't know how they interact together, nor where in the documentation they are mentioned.

So I feel a little lost on this part...

**Comment by Aire-One** [comment]
Since #2922 is merge is issue has no reason to stay.
