### ISSUE TITLE
Progressbar turns red

### ISSUE THREAD

**Issue by ilovecookieee** [awesomeWM/awesome#2932]
Output of `awesome --version`:

awesome v4.3-576-g4cac2463a 

**How to reproduce the issue:**
After updating AwesomeWM(git-master), all progress bars became red. `background_color` and `color` doesn't change anything. I also tried restarting my laptop.

Relevant code:  
```
progressbar = wibox.widget {
  {
    id            = 'music_bar',
    max_value     = 100,
    forced_height = dpi(3),
    forced_width  = dpi(100),
    color         = '#ffffff',
    background_color  = '#ffffff20',
    shape         = gears.shape.rounded_bar,
    widget        = wibox.widget.progressbar
  },
  layout = wibox.layout.stack
}
```

**Actual result:**

![20191201_152151](https://user-images.githubusercontent.com/40349590/69911008-eda1d780-144f-11ea-96c4-de1d6f6bc59c.png)

**Expected result:**

Should not be red lol

Edit: Fixed it by downgrading to an old build: `awesome v4.3-530-g76f8c117`

**Comment by Elv13** [comment]
whoops, sorry
