### ISSUE TITLE
Unable to access widget that has been added through method

### ISSUE THREAD

**Issue by XeGrox** [awesomeWM/awesome#2945]
Output of `awesome --version`:
```
awesome v4.3-528-g9bc6d4aa (Too long)
 • Compiled against Lua 5.3.5 (running with Lua 5.3)
 • D-Bus support: yes
 • xcb-errors support: no
 • execinfo support: yes
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
```

**How to reproduce the issue:**

```
local widget = {
  id = "wdg",
  widget = wibox.container.background,
}
s.parent:add(widget)
s.parent.wdg.bg = "#000000"
```

**Actual result:**

The widget background does not change as `s.parent.wdg` is not accessible

**Expected result:**

The widget background should be set to black

**Comment by psychon** [comment]
Uhm. What makes you think that your sample code is supposed to work? (And slightly related to that: is there any documentation for the `id` stuff? I fail to find anything)

Anyway, `id` properties are only used by `wibox.widget.base.make_widget_declarative` plus anything based on this function (`wibox.container(foo)` is just an alias for it, same for `wibox.layout(foo)`, same for `wibox.widget(foo)`, someone really made sure this function can be called; it is also called from `wibox.widget.base.make_widget_from_value()` which is used for anything that mentions "widget template")

**Comment by Elv13** [comment]
Related to https://github.com/awesomeWM/awesome/issues/2181

(and the doc is here https://awesomewm.org/apidoc/documentation/03-declarative-layout.md.html)

**Comment by psychon** [comment]
> (and the doc is here https://awesomewm.org/apidoc/documentation/03-declarative-layout.md.html)

You mean the "Accessing widgets" section? That specifically says

> Widgets defined using `setup` can be accessed using these methods:

and there is no call to `setup` in the code sample above. So, I'd still say that this works as documented.

**Comment by Elv13** [comment]
>  So, I'd still say that this works as documented.

Yes, but #2181 and friends are there to fix that. ID "should" be reliable, not just magic when :setup() is used. It is in my TODO list and there was some groundwork commits merged in "API Standardization part 1" to fix it. I will have to do the hierarchy stuff.
