### ISSUE TITLE
awesome keyboard/shourt-cuts didnt work

### ISSUE THREAD

**Issue by lvntky** [awesomeWM/awesome#2953]
awesome v4.3 (Too long)
 • Compiled against Lua 5.3.5 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
i changed the my keymap to tr. It worked on xfce but i cant use awesome

**Comment by Elv13** [comment]
Any reason for closing this. Did you find an answer? Usually changing the keymaps works, but there is sometime issues with some keybindings.

**Comment by lvntky** [comment]
No. I figure out by changing the awesome copy-cat that i formerly used.
