### ISSUE TITLE
Can't set the type of naughty.layout.box

### ISSUE THREAD

**Issue by xcbdz** [awesomeWM/awesome#2956]
Output of `awesome --version`:

awesome v4.3-628-gb8c83fdf9 (Too long)
 • Compiled against Lua 5.3.5 (running with Lua 5.3)
 • D-Bus support: yes
 • xcb-errors support: no
 • execinfo support: yes
 • xcb-randr version: 1.6
 • LGI version: 0.9.2

**How to reproduce the issue:**
```lua
naughty.connect_signal("request::display", function(n)
  naughty.layout.box {
    notification = n,
    shape = gears.shape.rectangle,
    type = "notification",
    widget_template = { .. }
  }
end)
```

**Actual result:**

output of xprop after clicking the notification popup:  
```
_NET_WM_STRUT_PARTIAL(CARDINAL) = 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0  
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_NORMAL  
WM_NAME(STRING) = "Awesome drawin"  
WM_CLASS(STRING) = "awesome", "awesome"  
```

**Expected result:**

The `type = 'notification'` did nothing, expected to change the type of popup to `_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_NOTIFICATION `.

I maybe doing something wrong. Any help would be appreciated!

**Comment by psychon** [comment]
Random guess: This ugly hack does not work when other code iterates over a table or passes it to C (which then also iterates over the table):
https://github.com/awesomeWM/awesome/blob/b8c83fdf9c471c7bced75790dde0a23ba3e2b146/lib/naughty/layout/box.lua#L245

I tried tracing the code... so `naughty.layout.box` uses `awful.popup` with the above "hacked" argument. This then does `.widget = nil` and creates a wibox from the passed in arguments here:
https://github.com/awesomeWM/awesome/blob/b8c83fdf9c471c7bced75790dde0a23ba3e2b146/lib/awful/popup.lua#L447
This then passes the arguments to the C code here:
https://github.com/awesomeWM/awesome/blob/b8c83fdf9c471c7bced75790dde0a23ba3e2b146/lib/wibox/init.lua#L281
The C code then iterates over the table to apply properties that were passed in:
https://github.com/awesomeWM/awesome/blob/b8c83fdf9c471c7bced75790dde0a23ba3e2b146/common/luaclass.c#L520-L523

Untested patch that gets rid of the metatable hack (and which can likely be made nicer with some magic from `gears.table`):
```diff
diff --git a/lib/naughty/layout/box.lua b/lib/naughty/layout/box.lua
index 5e80dd5ca..a157e0037 100644
--- a/lib/naughty/layout/box.lua
+++ b/lib/naughty/layout/box.lua
@@ -242,7 +242,11 @@ local function new(args)
         border_color = args and args.border_color or beautiful.notification_border_color,
     }
 
-    new_args = args and setmetatable(new_args, {__index = args}) or new_args
+    for k, v in pairs(args) do
+        if type(new_args[k]) == nil then -- FIXME: Why is the user not allowed to override things here? If they want ontop=false, let them?!
+            new_args[k] = v
+        end
+    end
 
     -- Generate the box before the popup is created to avoid the size changing
     new_args.widget = generate_widget(new_args, new_args.notification)
```

**Comment by xcbdz** [comment]
Thank you for responding. After using the patch above, the notification popups stopped working/showing up. There's also no error messages.

**Comment by Elv13** [comment]
This one is simpler:

```patch
diff --git a/lib/naughty/layout/box.lua b/lib/naughty/layout/box.lua
index 234d67e50..0c23803a1 100644
--- a/lib/naughty/layout/box.lua
+++ b/lib/naughty/layout/box.lua
@@ -260,7 +260,8 @@ local function new(args)
         screen       = args and args.notification and args.notification.screen
     }
 
-    new_args = args and setmetatable(new_args, {__index = args}) or new_args
+    -- The C code needs `pairs` to work, so a full copy is required.
+    gtable.crush(new_args, args, true)
 
     -- Generate the box before the popup is created to avoid the size changing
     new_args.widget = generate_widget(new_args, new_args.notification)
@@ -294,6 +295,8 @@ local function new(args)
         abutton({ }, 3, hide)
     ))
 
+    gtable.crush(ret, box, false)
+
     return ret
 end
```

It does a full copy, which I don't like, but this makes it more robust when used in code paths where Lua `pairs` is used.

**Comment by xcbdz** [comment]
The patch works perfectly! Thank you very much for the help.
