### ISSUE TITLE
Google chrome only opens in tab 1

### ISSUE THREAD

**Issue by MerrinX** [awesomeWM/awesome#2957]
Output of `awesome --version`:
Awesome 4.3
_REPLACE with full version output_

**How to reproduce the issue:**
google chrome will only open in tab 1, tried to reset to default rc.lua but still only in tab 1
 here is my rc.lue
http://dpaste.com/355BKWK
_REPLACE with step-by-step instructions on what to do_

**Actual result:**

_REPLACE with what happened_

**Expected result:**f

_REPLACE with what should happen_

**Comment by MerrinX** [comment]
When i delete folder .config/google-chrome-stable
then it will start in whatever tab, but does not follow rules in rc.lua

**Comment by MerrinX** [comment]
Solved, after i deleted that folder it now follow rules from rc.lua

**Comment by Elv13** [comment]
A pull request merged a few hours ago add a permission framework to block such call. In v4.3, it can be done be disconnecting the `awful.ewmh.tag` handler from the `request::tag` signal and implement your own alternative.

Closing as fixed.
