### ISSUE TITLE
Notification pop-ups stopped appearing after adding request::display function

### ISSUE THREAD

**Issue by xcbdz** [awesomeWM/awesome#2961]
Output of `awesome --version`:

```
awesome v4.3-628-gb8c83fdf9 (Too long)
 • Compiled against Lua 5.3.5 (running with Lua 5.3)
 • D-Bus support: yes
 • xcb-errors support: no
 • execinfo support: yes
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
```

**How to reproduce the issue:**

Adding the code below made the pop-ups not to show up, even if the function is empty. I also tested it in the default `rc.lua`.

```lua
naughty.connect_signal("request::display", function(n)
  -- Some code here
end)
```

**Actual result:**

The notification pop-ups stopped working/is not showing up. You have to add a `naughty.layout.box` with a `widget_template` to fix the issue. 

**Expected result:**

Show notification pop-ups even without adding a `naughty.layout.box` inside it.

**Comment by xcbdz** [comment]
I changed my use-case so it's not really an issue to me anymore. It also turns out that you need to add `naughty.layout.box {notification = n}` to use the default naughty.layout.box. I'm sorry for not reading the documentation thoroughly. Anyway, thanks for maintaining this awesome window manager.

**Comment by Elv13** [comment]
Sorry for de delay, I was mostly AFK.

What you see is the intended behavior. There is a legacy system which implements the old behavior (show a popup) if no handler is present. If an handler is present, then the legacy system is disabled. If the handler does nothing, then it is honored and the result is doing nothing. You need to add a `naughty.layout.box` in your handler to get a popup again.
