### ISSUE TITLE
Modkeys use `theme.bg_minimize` color in `show_help`

### ISSUE THREAD

**Issue by arbitrary-dev** [awesomeWM/awesome#2963]
Output of `awesome --version`:

```
awesome v4.2 (Human after all)
 • Compiled against Lua 5.1.4 (running with LuaJIT 2.0.5)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
```

**How to reproduce the issue:**

1. Open `.config/awesome/theme.lua`
2. Set `theme.bg_minimize = theme.bg_normal`
3. Open `hotkeys_popup.show_help` using <kbd>modkey</kbd> + <kbd>s</kbd>

**Actual result:**

Modification keys are of the same color as the background, and so are invisible. Only awkward indentation reminds of their existence.

**Expected result:**

Modification keys use a separate color, e.g. `theme.fg_modkeys`

**Comment by actionless** [comment]
https://awesomewm.org/apidoc/popups_and_bars/awful.hotkeys_popup.widget.html#beautiful.hotkeys_modifiers_fg
