### ISSUE TITLE
xbacklight is set to 100 each time I open and close laptop lid

### ISSUE THREAD

**Issue by xor512** [awesomeWM/awesome#2965]
Output of `awesome --version`:

awesome v4.3 (Too long)
 Compiled against Lua 5.3.5 (running with Lua 5.3)
 D-Bus support:
  execinfo support: 
  xcb-randr version: 1.6
 LGI version: 0.9.2

**How to reproduce the issue:**

I have this line in rc.lua:

`awful.util.spawn_with_shell("xbacklight -set 60")`

**Actual result:**

Seems to be working, but when I close the laptop lid and open it again xbacklight -get gives me 100.

**Expected result:**

I want my backlight setting to stay after closing and opening laptop lid

**Comment by Elv13** [comment]
Hello,

AwesomeWM does not handle the backlight. This is either done using the hardware default settings or using an external power managment deadmon such as laptopmode, Powerdevil or UPower.

Please refer to your distribution documentation to know how to change the settings.

**Comment by xor512** [comment]
If anyone wants to do launch smth on laptop start in can be done with acpid. There is an /etc/acpi/handler.sh file and one can put stuff like:

```lua
            open)
                logger 'LID opened'
                echo 7960743 > /sys/class/backlight/intel_backlight/brightness
                setxkbmap -option "grp:alt_shift_toggle,grp_led:scroll" "pl,ru"
                xset -b
              ;;
```
