### ISSUE TITLE
mod4+shift+c kills everything in a tag

### ISSUE THREAD

**Issue by xor512** [awesomeWM/awesome#2968]
Output of `awesome --version`:
awesome v4.3 (Too long)

 ��� Compiled against Lua 5.3.5 (running with Lua 5.3)
 ��� D-Bus support: ���
 ��� execinfo support: ���
 ��� xcb-randr version: 1.6
 ��� LGI version: 0.9.2

**How to reproduce the issue:**

Open several terminals (for example). Focus on one of them. Press mod4+shift+c

**Actual result:**

Everything in the current tag got killed.

**Expected result:**

Only focused window should be killed.

Or I screw smth up in my rc.lua?

**Comment by SethBarberee** [comment]
Link to your rc.lua?

**Comment by xor512** [comment]
I f... up. Sleepless night. It actually works as expected. Is it possible to delete an issue?

PS I'm very sorry. Really.

**Comment by xor512** [comment]
Actually I've just found out what has happened. Except for pressing mod4+shift+c I was pressing mod4+ctrl+c. Probably added the last shortcut myself. Sorries again.
