### ISSUE TITLE
awful.mouse.wibox.move is broken

### ISSUE THREAD

**Issue by laith-m0** [awesomeWM/awesome#2971]
Output of `awesome --version`:

awesome v4.3-655-g67672bf5 (Too long)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: yes
 • xcb-errors support: no
 • execinfo support: yes
 • xcb-randr version: 1.6
 • LGI version: 0.9.2

**How to reproduce the issue:**
Create a wibox with awful.mouse.wibox.move binded to button, then try to drag it:

```
wibox1=wibox{visible=true,height=100,width=200,x=500,y=500}
wibox1.buttons=gears.table.join(wibox1.buttons,
    awful.button({}, 1, function() awful.mouse.wibox.move() end))
```

**Actual result:**

Nothing happens. When callback changed to `function() awful.mouse.wibox.move(wibox1) end` on drag cursor will change, but the wibox will only be dragged corner snaps.

**Expected result:**

Wibox should be dragged like windows are dragged with modkey pressed.
The problem is `awful.mouse.resize()` that updates geometry by emitting signal "request::geometry" which works for client and does not work for wibox.

As a workaround it can be fixed by changing `client:emit_signal(req, context, geo)` to  `client:geometry(geo)` but consequences are unclear to me.

**Comment by Elv13** [comment]
Thanks for reporting this. A fix is in  #2975
