### ISSUE TITLE
systray doesn't respect margin container

### ISSUE THREAD

**Issue by aalhitennf** [awesomeWM/awesome#2981]
Output of `awesome --version`:

awesome v4.3-687-gb350ffcb9-dirty (Too long)
 • Compiled against Lua 5.1.4 (running with LuaJIT 2.0.5)
 • D-Bus support: yes
 • xcb-errors support: no
 • execinfo support: yes
 • xcb-randr version: 1.6
 • LGI version: 0.9.2

**How to reproduce the issue:**

add systray inside of margin container. same problem occured in "normal" lua version

**Actual result:**
margin containers right side doesn't stretch to fit around systray, ovrelaps to over widget right of it.

image with visible margins: https://i.ibb.co/swKBBTw/margin.png

**Expected result:**

container fits around systray

**Comment by aalhitennf** [comment]
same seems to happen with awful.container.place, so probably with more containers too

**Comment by psychon** [comment]
Could you provide some instructions on how to reproduce this? Here is a patch to the default config and a screenshot of the result.
```diff
diff --git a/awesomerc.lua b/awesomerc.lua
index 948407220..9b0ada3c4 100644
--- a/awesomerc.lua
+++ b/awesomerc.lua
@@ -203,7 +203,11 @@ screen.connect_signal("request::desktop_decoration", function(s)
         { -- Right widgets
             layout = wibox.layout.fixed.horizontal,
             mykeyboardlayout,
-            wibox.widget.systray(),
+            {
+                layout = wibox.container.margin,
+                margins = 5,
+                wibox.widget.systray(),
+            },
             mytextclock,
             s.mylayoutbox,
         },
```
![foo](https://user-images.githubusercontent.com/89482/73607923-c8028d00-45bc-11ea-97fe-b0f215e9fb9f.png)

**Comment by aalhitennf** [comment]
i need to do more testing, can't reproduce this with default config and theme. but i noticed that my problem goes away if i comment out `theme.systray_icon_spacing = dpi(4)` from my own theme.

**Comment by aalhitennf** [comment]
did more testing and found how to reproduce, wasn't loading theme properly earlier. 

Add some height to wibar i.e.
```
s.mywibox = awful.wibar({ height = 32, position = "top", screen = s })
```

Create systray widget and set icon size
```
local systray = wibox.widget.systray()
systray:set_base_size(16)
```
```
{ -- Right widgets
    layout = wibox.layout.fixed.horizontal,
     mykeyboardlayout,
    wibox.container.margin(
        systray,
        5,5,5,5, '#FFFFFF'
     ),
     mytextclock,
     s.mylayoutbox,
},
```

And in theme.conf add systray spacing
`theme.systray_icon_spacing = dpi(10)`

**Comment by psychon** [comment]
> theme.systray_icon_spacing = dpi(10)

This is the key ingredient. `:draw()` does not consider the icon spacing when computing how the available space needs to be split into icons. Instead, it just does "100 px for 4 icons means 25 px per icon".

However, something else must also be wrong since there is not enough space available...

**Comment by psychon** [comment]
#2989 fixes this. With those changes, your instructions above result in:
![foo](https://user-images.githubusercontent.com/89482/74136723-e4bb4800-4bee-11ea-96a6-49b8c5c96d5b.png)
I'm not sure if I should consider these "too small icons" a bug. If I remove the call to `:set_base_size()`, the result is:
![foo2](https://user-images.githubusercontent.com/89482/74136792-03214380-4bef-11ea-888a-92e35e8eefbd.png)
What happens is:
- You have a wibar with height 32
- You have a margin container with 10 px of vertical margin, so 22 px of space remain for the systray widget
- As you asked for, you get icons with size 16 px in those 22 px of space.
