### ISSUE TITLE
mouse.current_widget_geometry reporting wrong widget's geometry

### ISSUE THREAD

**Issue by M4he** [awesomeWM/awesome#2985]
## Summary

When a `wibox.widget.progressbar` is contained within a `wibox.container.margin`\*, the geometry reported by `mouse.current_widget_geometry` misbehaves on the bottommost rows of pixels of the progressbar: when the geometry is retrieved during a mouse click event in this region, it will report the underlying container's (`wibox.container.margin`) geometry instead. This leads to problems when attempting to use this value in order to make an interactive progressbar slider.

\* might also affect other containers or wibox hierarchies but was not tested.

## System Information

Output of `awesome --version`:

```
awesome v4.3 (Too long)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
```

OS:

```
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:    10
Codename:   buster
```

Running `awesome` standalone using LightDM.

## How to reproduce the issue

1. save the code snipped quoted in **"Sample code"** below to a file in your awesome configuration folder (e.g. called `sample.lua`)
2. use `local testcase = require("sample.lua")` to import the code
3. bind `testcase:show()` to any suitable trigger of your choice (e.g. a global hotkey button)
4. reload awesome, trigger the popup via the chosen hotkey or similar
5. repeatedly click on the progress bar to set its position, also try to click at different y coordinates on the bar, especially at the lowermost portions
6. pay attention to the reported geometry values displayed in the textboxes

### Actual result

- depending on the y coordinate of the click (relative to the progressbar's height), the returned `mouse.current_widget_geometry` may not report the progressbar's geometry
    - if the click is on the last rows of pixels of the progressbar, the geometry of the underlying `wibox.container.margin` (the green colored container) is returned instead
    - if the click is on anywhere but the last few lines of pixels of the progressbar, the geometry of the progressbar is returned correctly

### Expected result

- `mouse.current_widget_geometry` reports the correct geometry of the `wibox.widget.progressbar` widget whenever the mouse clicks on it, regardless where the click on the progressbar happens

## Sample code

The following is a stripped-down and slightly adjusted version of [this player widget](https://github.com/worron/redflat/blob/4590286bcc73c6758080561fd5945d3f355d955c/float/player.lua) where the issue was discovered:

```lua
local awful = require("awful")
local wibox = require("wibox")

local progbartest = {}

function progbartest:init()

    local bar_layout = wibox.layout.align.vertical()

    self.bar = wibox.widget.progressbar()
    bar_layout:set_bottom(wibox.container.constraint(self.bar, "exact", nil, 10))
    
    self.tb1 = wibox.widget.textbox("click bar")
    bar_layout:set_middle(self.tb1)
    
    local area = wibox.layout.fixed.horizontal()
    area:add(wibox.container.margin(bar_layout, 100, 100, 5, 5, '#00AA00'))

    self.bar:buttons(awful.util.table.join(
        awful.button(
            {}, 1, function()
                local coords = {
                    bar   = mouse.current_widget_geometry,
                    wibox = mouse.current_wibox:geometry(),
                    mouse = mouse.coords(),
                }
                self.tb1.text="current_wibox.x=" .. tostring(coords.wibox.x) .. ",   current_widget_geo.x=" .. tostring(coords.bar.x) .. ",   current_widget_geo.width=" .. tostring(coords.bar.width)
                local position = (coords.mouse.x - coords.wibox.x - coords.bar.x) / coords.bar.width
                self.bar:set_value(position)
            end
        )
    ))

    self.wibox = wibox({
        ontop        = true,
        bg           = "#333333",
        border_width = 2,
        border_color = "#888888",
    })
    self.wibox:set_widget(wibox.container.margin(area, 10))
    self.wibox:geometry({ width = 900, height = 50 })
end

function progbartest:show()
    if not self.wibox then self:init() end
    awful.placement.under_mouse(self.wibox)
    self.wibox.visible = true
end

return progbartest
```

**Comment by M4he** [comment]
This is how it looks for me with two different y-axis positions of the cursor:

![current_widget_geo_glitch_repro](https://user-images.githubusercontent.com/1408105/73782814-f934b600-4792-11ea-8f92-6055320731a1.png)

**Comment by psychon** [comment]
There is an offset of two pixels between the coordinates of the mouse click event and what `awful.mouse.object.get_current_widgets()` computes based on `mouse.coords()`:
```
Have button signal button::press at x=454, y=40
get current widgets: x: 396--60=456, y: 390-348=42
```
Part of the reason might be that the wibox border is not taken into account by this function. However, that only explains one pixel of difference... Oh, wait. To quote the sample code: `border_width = 2,`.

@M4he Can you test the following patch? If it works, who wants to submit a PR for it? @Elv13 Does this need a test?
```diff
diff --git a/lib/awful/mouse/init.lua b/lib/awful/mouse/init.lua
index b94d63eb3..b44787a4e 100644
--- a/lib/awful/mouse/init.lua
+++ b/lib/awful/mouse/init.lua
@@ -309,8 +309,9 @@ function mouse.object.get_current_widgets()
     local w = mouse.object.get_current_wibox()
     if w then
         local geo, coords = w:geometry(), capi.mouse:coords()
+        local bw = w.border_width
 
-        local list = w:find_widgets(coords.x - geo.x, coords.y - geo.y)
+        local list = w:find_widgets(coords.x - geo.x - bw, coords.y - geo.y - bw)
 
         local ret = {}
```

The output above was generated with:
```diff
diff --git a/lib/awful/mouse/init.lua b/lib/awful/mouse/init.lua
index b94d63eb3..9d98245a2 100644
--- a/lib/awful/mouse/init.lua
+++ b/lib/awful/mouse/init.lua
@@ -318,6 +318,10 @@ function mouse.object.get_current_widgets()
             ret[k] = v.widget
         end
 
+        print(string.format("get current widgets: x: %s-%s=%s, y: %s-%s=%s",
+            coords.x, geo.x, coords.x - coords.x,
+            coords.y, geo.y, coords.y - coords.y))
+
         return ret, list
     end
 end
diff --git a/lib/wibox/drawable.lua b/lib/wibox/drawable.lua
index cf9a129e7..63f78d8f9 100644
--- a/lib/wibox/drawable.lua
+++ b/lib/wibox/drawable.lua
@@ -424,6 +424,7 @@ function drawable.new(d, widget_context_skeleton, drawable_name)
 
     local function button_signal(name)
         d:connect_signal(name, function(_, x, y, button, modifiers)
+            print(string.format("Have button signal %s at x=%s, y=%s", name, x, y))
             local widgets = ret:find_widgets(x, y)
             for _, v in pairs(widgets) do
                 -- Calculate x/y inside of the widget
```

**Comment by M4he** [comment]
@psychon I applied the patch to my local awesome installation and it appears to fix this issue for both the sample code as well as the actual player widget I'm using. Thank you so much!

I opened PR #2990 for this.
