### ISSUE TITLE
awful.util.spawn on empty tag

### ISSUE THREAD

**Issue by thriveth** [awesomeWM/awesome#2986]
Output of `awesome --version`:

```
awesome v4.3 (Too long)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
```

**How to reproduce the issue:**

I have included the following in my rc.lua:

```
    -- Call Emacsclient with keypress
    awful.key({"Control", "Mod1"}, "e", 
        function () awful.util.spawn("emacsclient -a '' -c ~/Dropbox/org/orgfiles.org") end,
	{description = "Open new Emacs frame with overview file", group="launcher"}
    ),
```

If I go to a tag with no windows, press the given keyboard shortcut, nothing happens. Also tested with Rofi. 

**Actual result:**

Nothing seemingly happens

**Expected result:**

An application (tested with rofi and emacsclient) would show up on the given tag.
Works fine on tags where windows are already present. Minimized windows don't help.

**Comment by elenapan** [comment]
Make sure you have put your keybind under `clientkeys` and not `globalkeys`.
If you are using the new version of `rc.lua`, it should be under `append_client_keybindings`.

**Comment by thriveth** [comment]
Yeah, that did it. Or rather, the other way around - I had put them under clientkeys, they sho7uld go under globalkeys. Now they work a charm! Thanks for the help!
