### ISSUE TITLE
Use higher-resolution client icons 

### ISSUE THREAD

**Issue by blueyed** [awesomeWM/awesome#299]
The _NET_WM_ICON property contains multiple icons for a window with multiple geometries (e.g. pidgin provides 16x16, 24x24, 32x32 and 48x48 icons). Currently c.icon only provides access to the smallest icon.
We should make all of these accessible to lua. For the tasklist, it might be a good idea to use the next bigger icon available and scale it down.

Branch which handles the C part of this, but gets us lots and lots of deprecation warnings from lua:
http://git.naquadah.org/?p=awesome.git;a=shortlog;h=refs/heads/client-icons

Migrated from [FS#832](https://awesome.naquadah.org/bugs/index.php?do=details&task_id=832)

@psychon 
Do you have that branch still around?
Can you push it to Github, please?

**Comment by psychon** [comment]
It's on GitHub.

https://github.com/awesomeWM/awesome/tree/client-icons
https://github.com/psychon/awesome/tree/client-icons

Last five comments.

**Comment by timroes** [comment]
+1 I would like to see this a lot. Several programs look very pixelated if you use larger bars.

**Comment by Elv13** [comment]
This feature is available as-of v4.1

**Comment by psychon** [comment]
(More or less: only for the titlebar do we actually have a widget showing the best possible icon; the tasklist still uses the first icon by default, or an icon as decided by `awesome.set_preferred_icon_size(42)`)

**Comment by charbelnicolas** [comment]
I'm getting blurry icons too on a recent build of awesome... Setting the `awesome.set_preferred_icon_size(64)` doesn't really do anything in my wibar with a 50 px height.

**Comment by actionless** [comment]
@charbelnicolas either your awesome wm built from older code version than this one: https://github.com/awesomeWM/awesome/commit/5c57f43643906b8e7e9f04fbbb516b0482b0343d

or you have some mistakes in your local config (for a matter of test, you can temporary rename it, so default awesome config would be used)

**Comment by charbelnicolas** [comment]
I don't know what I was doing exactly yesterday, but it's working fine today, it was my mistake, thank you.
