### ISSUE TITLE
Wibox not setting opacity with declarative syntax

### ISSUE THREAD

**Issue by unai-ndz** [awesomeWM/awesome#2997]
Output of `awesome --version`:

```
awesome v4.3-731-g81d652114 (Too long)
 • Compiled against Lua 5.3.5 (running with Lua 5.3)
 • API level: 4
 • D-Bus support: yes
 • xcb-errors support: yes
 • execinfo support: yes
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
 • Transparency enabled: yes
 • Custom search paths: no
```

**How to reproduce the issue:**
Create a wibox, setting the opacity using the declarative syntax.

```
    local w = wibox {
        x       = 0,
        y       = 0,
        visible = true,
        ontop   = true,
        opacity = 0.8,
        height  = 200,
        width   = 200
    }
    print(w.opacity) --Prints 1.0
   w.opacity = 0.8
   print(w.opacity) --Prints 0.8
```

This worked a few commits ago, probably broke between `v4.3-731-g81d652114` and `v4.3-694-gcc4ebd80f`.

**Actual result:**

The opacity only gets set when using the imperative syntax.

**Expected result:**

The wibox should set the assigned opacity on creation.

**Comment by Aire-One** [comment]
Are you sure?

I just updated to latest master today and everything is still working perfectly fine here.

**Comment by unai-ndz** [comment]
Pretty sure. I just tested it again with a minimal config from the newest `rc.lua`.
This just happens using the wibox directly, e.g. the textbox works fine.
