### ISSUE TITLE
Layout box broken on multiscreen systems

### ISSUE THREAD

**Issue by Perlovka** [awesomeWM/awesome#3004]
awesome v4.3-735-g002ecfd4-dirty (Too long)
• Compiled against Lua 5.1.5 (running with LuaJIT 2.1.0-beta3)
• API level: 4
• D-Bus support: yes
• xcb-errors support: no
• execinfo support: yes
• xcb-randr version: 1.6
• LGI version: 0.9.2
• Transparency enabled: yes
• Custom search paths: no

Hi, 
I have 2 monitors. If I create layout box with a new syntax(current master rc.lua), it does not work on second screen(not clickable, hotkeys won't switch layout on this screen):

```lua
    s.mylayoutbox = awful.widget.layoutbox{                    
        screen = s,                                            
        buttons = {                                            
            awful.button({ }, 1, function () awful.layout.inc( 1) end),
            awful.button({ }, 3, function () awful.layout.inc(-1) end),
            awful.button({ }, 4, function () awful.layout.inc( 1) end),
            awful.button({ }, 5, function () awful.layout.inc(-1) end)
        }
    }
```
Old syntax works as expected:
```lua
    s.mylayoutbox = awful.widget.layoutbox(s)
    s.mylayoutbox:buttons(gears.table.join(
                           awful.button({ }, 1, function () awful.layout.inc( 1) end),
                           awful.button({ }, 3, function () awful.layout.inc(-1) end),
                           awful.button({ }, 4, function () awful.layout.inc( 1) end),
                           awful.button({ }, 5, function () awful.layout.inc(-1) end)))
```

My config is attached to https://github.com/awesomeWM/awesome/issues/3003
Thanks.

**Comment by Elv13** [comment]
Hi, thanks for reporting this. The issue seems quite obvious (sorry for the regression). I made a pull request. Please test it (I honestly didn't). You can edit the code directly in /usr/share/awesome/lib if you want, it's a one-liner.

**Comment by Perlovka** [comment]
Thanks, the fix works )

**Comment by Perlovka** [comment]
There is one more small issue, after https://github.com/awesomeWM/awesome/commit/2c08c2fa396d3522041c2f15365c508f00340810#diff-160dd1f8882e9d7c7ad22141cce0780e
keyboard layout not changes on mouse click.

**Comment by psychon** [comment]
@Perlovka Can you open a new issue for that? Thanks
