### ISSUE TITLE
Notifications with icons only show bottom right part of icon

### ISSUE THREAD

**Issue by SethBarberee** [awesomeWM/awesome#3005]
Output of `awesome --version`:
```
awesome v4.3-753-gdd289e5ab (Too long)
 • Compiled against Lua 5.3.5 (running with Lua 5.3)
 • API level: 4
 • D-Bus support: yes
 • xcb-errors support: yes
 • execinfo support: yes
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
 • Transparency enabled: yes
 • Custom search paths: no
```

**How to reproduce the issue:**

1. Trigger notification with icon (been using spotify but also triggered by sending `notify-send -i <random icon here>`)

**Actual result:**

Bottom right of icon is shown

**Expected result:**

Icon is shown in full.

**Comment by actionless** [comment]
> notify-send -i <random icon here>

1) can you reproduce it in the default config?

2) with any image file or just with some specific one(s)?

**Comment by Elv13** [comment]
Can I get a screenshot? Can you try some other naughty.widget.icon.resize_strategy`?

**Comment by SethBarberee** [comment]
> > notify-send -i
> 
>     1. can you reproduce it in the default config?
Yepper. Using the following from the default config and not touching any other part of naughty.
```
-- {{{ Notifications

ruled.notification.connect_signal('request::rules', function()
    -- All notifications will match this rule.
    ruled.notification.append_rule {
        rule       = { },
        properties = {
            screen           = awful.screen.preferred,
            implicit_timeout = 5,
        }
    }
end)

naughty.connect_signal("request::display", function(n)
    naughty.layout.box { notification = n }
end)

-- }}}
```
>     2. with any image file or just with some specific one(s)?

Went through my icons in `.local/share/icons` with each size and made a table with my results based on if it showed all the image or only the bottom right.

| Size | Correct |
|------- | ---------- |
|16x16| Pass |
|24x24| Pass |
|32x32| Pass |
|48x48| Pass |
|96x96| Fail |
|128x128| Fail|

> Can I get a screenshot? Can you try some other naughty.widget.icon.resize_strategy`?

Same results no matter what I have in `theme.notification_icon_resize_strategy` I can try to get some screenshots in the coming days.
