### ISSUE TITLE
naughty.layout.box does not follow the picom rules if `type = notification`

### ISSUE THREAD

**Issue by iletthedogsout69** [awesomeWM/awesome#3006]
awesome version:
```
awesome v4.3-753-gdd289e5ab (Too long)
 • Compiled against Lua 5.3.5 (running with Lua 5.3)
 • API level: 4
 • D-Bus support: yes
 • xcb-errors support: no
 • execinfo support: yes
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
 • Transparency enabled: yes
 • Custom search paths: no
```

As the title says, `naughty.layout.box` does not follow the picom rules(opacity-rules, shadow-rules, etc) if its type is set to `notification`. It's weird because I already tried changing its type to normal, splash, utility, etc and it works without issues. But after changing it to `type = notification`, the rules I set in picom are being ignored.

Picom rules for `_NET_WM_WINDOW_TYPE_NOTIFICATION`

```
shadow-exclude = [
	"name = 'Notification'" # No effect
];

opacity-rule = [ 
	"50:window_type = 'notification'",	# Not following this rule
];

wintypes: {
	notification = { shadow = false, opacity = 0.5 } # still not working
}
```

My layout box config

```lua
naughty.connect_signal("request::display", function(n)
	naughty.layout.box {
		notification = n,
		widget_template = {}
		shape = gears.shape.rectangle,
		type = "notification", 			# does not follow picom rules
		type = *any other type*   			# works with picom rules
	}
```

**Am I sure that it's an awesomewm's issue and not picom's?**

**Definitely**. I also tried a different notification daemon and the rules I set in picom for `_NET_WM_WINDOW_TYPE_NOTIFICATION` are working. Try the `notification-daemon` program. As of now, I'm using `type = utility` for `naughty.layout.box` to match my needs.

**Expected result**

Picom compositor applies the rules to the notification typed window of awesomewm

**Actual result**

Picom can't apply the rules to `type = notification` naughty.layout.box

**Comment by psychon** [comment]
Could you run `xprop -frame _NET_WM_WINDOW_TYPE` in a terminal, cause a notification, and click on it? That should make `xprop` print the window type.

**Comment by iletthedogsout69** [comment]
It matches the type
if `type = utility`
output: `_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_UTILITY`

if `type = notification`
output: `_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_NOTIFICATION`

**Comment by psychon** [comment]
Okay... then.. sorry, I'm out of ideas. Might or might not be that the new code sets the property only after creating the window. CC @yshui

**Comment by iletthedogsout69** [comment]
It's okay, the bug is so weird and as of now using `utility` as the type of layout.box works for me.

**Comment by yshui** [comment]
It could be that picom is not monitoring the changes of window properties properly.

**Comment by iletthedogsout69** [comment]
So I tested running picom in a manjaro xfce4 vm, the problem persists even in xfce4. The notification rules are being ignored. So it's a picom issue. Should I open an issue in picom repo @yshui ?

Sorry for the problem @psychon . I should've test it in a different environment before posting here. I'm closing this issue.

**Comment by yshui** [comment]
@iletthedogsout69 Yes, please open an issue there.

**Comment by Aire-One** [comment]
For reference, here is the link to the upstream issue : https://github.com/yshui/picom/issues/323
