### ISSUE TITLE
Keyboard layout does not changes on mouse click

### ISSUE THREAD

**Issue by Perlovka** [awesomeWM/awesome#3008]
awesome v4.3-735-g002ecfd4-dirty (Too long)
• Compiled against Lua 5.1.5 (running with LuaJIT 2.1.0-beta3)
• API level: 4
• D-Bus support: yes
• xcb-errors support: no
• execinfo support: yes
• xcb-randr version: 1.6
• LGI version: 0.9.2
• Transparency enabled: yes
• Custom search paths: no

This was introduced in https://github.com/awesomeWM/awesome/commit/2c08c2fa396d3522041c2f15365c508f00340810#diff-160dd1f8882e9d7c7ad22141cce0780e

**Comment by Elv13** [comment]
@Perlovka please test the fix.

**Comment by Perlovka** [comment]
Thanks! Test passed )
