### ISSUE TITLE
Naughty markup stops working

### ISSUE THREAD

**Issue by manilarome** [awesomeWM/awesome#3020]
Output of `awesome --version`:

```
awesome v4.3-773-g4a220d2da (Too long)
 • Compiled against Lua 5.3.5 (running with Lua 5.3)
 • API level: 4
 • D-Bus support: yes
 • xcb-errors support: no
 • execinfo support: yes
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
 • Transparency enabled: yes
 • Custom search paths: no
```

**How to reproduce the issue:**

+ Update to the latest `awesome v4.3-773-g4a220d2da`
+ `notify-send '<b>Title</b>' '<i>Message</i>'`

**Actual result:**

This is `awesome v4.3-773-g4a220d2da`

![20200305_104810](https://user-images.githubusercontent.com/40349590/75943281-89b80080-5ecf-11ea-947a-de27929d6e25.png)

**Expected result:**

This is `awesome v4.3-771-g382635a94` 

![20200305_105023](https://user-images.githubusercontent.com/40349590/75943396-d26fb980-5ecf-11ea-8e8d-af91a8fafdc3.png)

**Comment by Elv13** [comment]
The commit has been reverted in https://github.com/awesomeWM/awesome/pull/3021

Thanks for reporting
