### ISSUE TITLE
Find a way to handle invalid pango markup in notification titles

### ISSUE THREAD

**Issue by Elv13** [awesomeWM/awesome#3022]
Find another solution since https://github.com/awesomeWM/awesome/pull/3019 breaks a lot of notifications.

**Comment by psychon** [comment]
Relevant historic code:
https://github.com/awesomeWM/awesome/blob/5da5d36178250335f748eed43551daad9e5af694/lib/naughty/core.lua#L466-L492

**Comment by Elv13** [comment]
Indeed. This code still exists, but is not used for `naughty.widget.message` and `naughty.widget.tittle`.

**Comment by p-himik** [comment]
The commit talks about undoing some of the escaping. But where does it actually happen?
I'm asking because `notify-send "&lt;"` results in the notification text being `&zzlg;`, which surely isn't supposed to be happening?
