### ISSUE TITLE
Customize snap distance

### ISSUE THREAD

**Issue by madprops** [awesomeWM/awesome#3025]
awesome v4.3 (Too long)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2

Is there a way to customize the distance point when windows can snap? 
I find it hard to exactly place them on the 8(?)px distance, especially with multi monitors.

I tried `awful.mouse.snap.default_distance = 50` but that didn't seem to change anything.

**Comment by Elv13** [comment]
Setting `awful.mouse.snap.default_distance = 50` works for me in the git-master version of AwesomeWM. Please confirm.

**Comment by madprops** [comment]
I think the property is not what I thought it was. I was referring to the distance to activate the red outline that allows snapping, like corner snapping, instead of just making it sticky. 
Now I'm getting these errors in the image, using the git awesome.

awesome v4.3-775-g4b3207dc (Too long)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • API level: 4
 • D-Bus support: yes
 • xcb-errors support: no
 • execinfo support: yes
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
 • Transparency enabled: yes
 • Custom search paths: no

![2020-03-06_01-21](https://user-images.githubusercontent.com/206498/76061425-1b178900-5f49-11ea-97ba-8d80be8309a8.png)
