### ISSUE TITLE
Focus problem

### ISSUE THREAD

**Issue by madprops** [awesomeWM/awesome#3026]
awesome v4.3-775-g4b3207dc (Too long)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • API level: 4
 • D-Bus support: yes
 • xcb-errors support: no
 • execinfo support: yes
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
 • Transparency enabled: yes
 • Custom search paths: no

![2020-03-06_01-21](https://user-images.githubusercontent.com/206498/76061425-1b178900-5f49-11ea-97ba-8d80be8309a8.png)

This happens when I focus an application.

Removing these lines in rc.lua fixes it:
`client.connect_signal("focus", function(c) c.border_color = beautiful.border_focus end)`
`client.connect_signal("unfocus", function(c) c.border_color = beautiful.border_normal end)`

This is my config file: https://github.com/madprops/awesome-setup/blob/master/awesome/rc.lua

**Comment by Elv13** [comment]
Umm, that looks very bad. I will see if it can be fixed later today
