### ISSUE TITLE
Add Makefile target to run functional tests

### ISSUE THREAD

**Issue by blueyed** [awesomeWM/awesome#303]
Now that #272 is merged, I think there should be a target in the Makefile (via CMakeLists.txt) for it.

Could `test` be made to depend on `check` and this new one?

While `check` does not require awesome to be built, the functional tests do so.

But then there's the warning from CMake about using `test` anyway, so another target could be used for this explicitly?

> CMake Warning (dev) at CMakeLists.txt:330 (add_custom_target):
  Policy CMP0037 is not set: Target names should not be reserved and should
  match a validity pattern.  Run "cmake --help-policy CMP0037" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

>  The target name "test" is reserved or not valid for certain CMake features,
  such as generator expressions, and may result in undefined behavior.

**Comment by psychon** [comment]
I'd propose a target `check` which does nothing except for depending on `check-unit` and `check-functional` (or `check-integration`?). With this, `check-unit` could still be part of `make all`, while the functional tests shouldn't.

I guess the `test` target should be dropped since CMake complains...

**Comment by psychon** [comment]
Quick attempt, what do you think?

```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index a521764..07dc15b 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -320,14 +320,22 @@ if(GENERATE_DOC)
 endif()
 # }}}
 
-# {{{ Unit tests
+# {{{ Tests
 find_program(BUSTED_EXECUTABLE busted)
 if(BUSTED_EXECUTABLE)
-    add_custom_target(check ALL
+    add_custom_target(check-unit ALL
         ${BUSTED_EXECUTABLE} "--lpath=${CMAKE_BINARY_DIR}/lib/?.lua;${CMAKE_BINARY_DIR}/lib/?/init.lua;spec/?.lua"
         WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
         VERBATIM)
-    add_custom_target(test DEPENDS check)
+endif()
+add_custom_target(check-integration
+    "${CMAKE_SOURCE_DIR}/tests/run.sh"
+    WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
+    VERBATIM)
+if(BUSTED_EXECUTABLE)
+    add_custom_target(check DEPENDS check-integration check-unit)
+else()
+    add_custom_target(check DEPENDS check-integration)
 endif()
 # }}}
 
```

**Comment by blueyed** [comment]
:+1:

**Comment by blueyed** [comment]
Thanks.

For reference, added in c1ea77d.
