### ISSUE TITLE
Spotify no floating spawn problem

### ISSUE THREAD

**Issue by madprops** [awesomeWM/awesome#3034]
awesome v4.3-775-g4b3207dc (Too long)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • API level: 4
 • D-Bus support: yes
 • xcb-errors support: no
 • execinfo support: yes
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
 • Transparency enabled: yes
 • Custom search paths: no

I have windows floating by default, but I'm trying an autolaunch script that where I need the windows non-floating, so I'm doing:

```
                awful.spawn("spotify", {floating = false})
                awful.spawn("tilix", {floating = false})
                awful.spawn("hexchat", {floating = false})
```

This works for Tilix and Hexchat but not for Spotify which stay floating.
This only happens when the application is started.
If, for instance, if it's already started, and I restart awesome, the no-floating rule applies.
Spotify is installed as a snap.

![2020-03-10_11-29](https://user-images.githubusercontent.com/206498/76341408-9d45db80-62c2-11ea-8e81-f9de8fc49c32.png)

**Comment by Elv13** [comment]
Known issue, the bug is upstream. They start the client with a different class, then the rules are executed, then they change the class again. Please report it to Spotify.

**Comment by madprops** [comment]
This will have to do for now:
```
client.connect_signal("property::class", function(c) 
    if c.class == "Spotify" then
        c.floating = false
    end
end)
```

**Comment by actionless** [comment]
i thought it got fixed in Spotify:
https://github.com/awesomeWM/awesome/issues/977
https://www.reddit.com/r/awesomewm/comments/8hegiw/spotify_rule_is_now_possible/
