### ISSUE TITLE
Cannot compile awesomeWM on Ubuntu 19.10

### ISSUE THREAD

**Issue by chocabloc** [awesomeWM/awesome#3039]
Output of `awesome --version`:

AwesomeWM didn't compile

**How to reproduce the issue:**

Download Awesome source code on Ubuntu 19.10 and try to compile

**Actual result:**

AwesomeWM does not compile. It shows error:
`Could NOT find Lua (missing: LUA_LIBRARIES LUA_INCLUDE_DIR)`
although lua 5.3 is already installed

**Expected result:**

AwesomeWM would compile

**Comment by psychon** [comment]
Install `liblua5.3-dev` and not just `liblua5.3-0` / `lua5.3`.

**Comment by psychon** [comment]
Closing this in favor of https://www.reddit.com/r/awesomewm/comments/fiwq10/cannot_compile_git_master_awesomewm/ which seems like the same question from the same person (sorry if I am guessing wrong here) and which has already more helpful information than what I provided here. Sorry if I am wrong about this and feel free to tell me to reopen this.
