### ISSUE TITLE
Preview images/videos in ranger causes system to freeze

### ISSUE THREAD

**Issue by Godnyx** [awesomeWM/awesome#3046]
Output of `awesome --version`:

awesome v4.3 (Too long)
 • Compiled against Lua 5.3.5 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2

**How to reproduce the issue:**

Try to preview images/videos on Ranger file explorer and the previous won't show up and the system will freeze.

**Actual result:**

System completely freezes and I have to change to another tty and kill awesome to log out and go back to the login manager

**Expected result:**

In every other Window Manager/Desktop Environment I tried. Ranger can normally display image/video previous with w3m and some changes to it's config for video previous. But in Awesome It doesn't work! And not only it can't render image/video previous but it also causes CPU to go 100% and Ram to go about 90% and my system to freeze and I have to go to another tty and kill awesome to unfreeze it and go back to the login manger. I don't know If that helps but I looked with Htop and the process that was causing the system to freeze was called "identify". If you need me to provide any other information I will gladly do. :)

**EDIT:**
I tried ArcoLinux Awesome and everything works as expected. So it's either something with the packages or something about my config. I haven't figured out yet but I'll find it. Thanks a lot everyone for your help!

**Comment by SethBarberee** [comment]
Does this happen on `git-master` for you? I am currently running `git-master` on Arch Linux and not having any issues with Ranger.

**Comment by actionless** [comment]
which `preview_images_method` is set in ranger config?

with `w3m` it also works for me:

![2020-03-22--1584894884_1268x749_scrot](https://user-images.githubusercontent.com/1655669/77255461-e05f6180-6c67-11ea-8f1f-fb073ae03930.png)

**Comment by Godnyx** [comment]
> which `preview_images_method` is set in ranger config?
> 
> with `w3m` it also works for me:
> 
> ![2020-03-22--1584894884_1268x749_scrot](https://user-images.githubusercontent.com/1655669/77255461-e05f6180-6c67-11ea-8f1f-fb073ae03930.png)

Its the same for me but still not works. Can you please provide your Awesome config? maybe I miss a library or something...

**Comment by Godnyx** [comment]
> Does this happen on `git-master` for you? I am currently running `git-master` on Arch Linux and not having any issues with Ranger.

How will I check git-master while having the package already installed from Manjaro repos? As I know you can't have the same package more than 1 times. Sorry if I sound too n00b but I haven't compiled anything manually before so some I don't know how it works.

**Comment by actionless** [comment]
awesome config you can try just with default, ranger config:
```console
$ cat ~/.config/ranger/rc.conf
set preview_images true
```

**Comment by Godnyx** [comment]
> awesome config you can try just with default, ranger config:
> 
> ```
> $ ls ~/.config/ranger/
> rc.conf
> $ cat ~/.config/ranger/rc.conf
> set preview_images true
> ```

That's what I'm doing, this was already there from before and it's not working.

**Comment by actionless** [comment]
and what's the terminal? i've tried with xterm, as other were not displaying w3m preview right

**Comment by Godnyx** [comment]
> and what's the terminal? i've tried with xterm, as other were not displaying w3m preview right

Mine is Roxterm. But like I said it's working with other Window Manager/Desktop enviroment so it's Awesome's problem. Maybe I do something wrong in Awesome's config.

**Comment by actionless** [comment]
with roxterm i can't neither see the previews nor reproduce the freeze

**Comment by Godnyx** [comment]
> with roxterm i can't neither see the previews nor reproduce the freeze

Thanks a lot for your help. Haven't fixed the issue yet but I found what's going on. Check the original post, I've made an update!
