### ISSUE TITLE
Switching windows with wmctrl is broken

### ISSUE THREAD

**Issue by h5vx** [awesomeWM/awesome#3047]
Output of `awesome --version`:
```
awesome v4.3-809-g5d1394b91 (Too long)
 • Compiled against Lua 5.3.5 (running with Lua 5.3)
 • API level: 4
 • D-Bus support: yes
 • xcb-errors support: no
 • execinfo support: yes
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
 • Transparency enabled: yes
 • Custom search paths: no
```

**How to reproduce the issue:**
1. Have some windows open
1. Choose window you want to switch, remember window _title_
1. Switch to some another workspace without that window
1. Run command: wmctrl -a _title_

**Actual result:**
* That window is urgent now
* Workspace is not switched to that window
* That window is not made active

**Expected result:**
* Workspace is switched to that contains that window
* That window is made active

**That works correctly on same system and config with that version**:
```
awesome v4.3 (Too long)
 • Compiled against Lua 5.3.5 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
```

**Comment by h5vx** [comment]
Only reason i use git build is that cool feature that add window icons near title... It would be cool if that feature come out to Arch repo build

**Comment by psychon** [comment]
@Elv13 I took a quick look at `awful.permissions` and... I have no idea what is "the right way" to make this work. I only see https://github.com/awesomeWM/awesome/blob/master/lib/awful/permissions/init.lua#L196-L200 which seems loosely related, but also not really helpful for this concrete request (no idea if I am even looking in the right place).

**Comment by Elv13** [comment]
Like that: https://awesomewm.org/apidoc/core_components/client.html#grant but right now only the skeleton of that is implemented, the end result when the other half will be merged will favor using that from the rules. Anyway, yes, it is probably what regressed wmctrl. I don't have that much time right now, but I will add a wmctrl test suite next time I work on it.

**Comment by daraul** [comment]
I'm not sure if this is related, but `xdotool set_desktop 1` doesn't work either. My awesome version: 

```
awesome v4.3-862-g7a759432d-dirty (Too long)
 • Compiled against Lua 5.3.5 (running with Lua 5.3)
 • API level: 4
 • D-Bus support: yes
 • xcb-errors support: no
 • execinfo support: yes
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
 • Transparency enabled: yes
 • Custom search paths: no
```

**Comment by psychon** [comment]
A random guess what `xdotool set_desktop 1` does leads me to: In git, this emits `request::select` on the tag object with argument `"ewmh"`. However, I would guess that it is currently broken, because the `-1` should be a `-2` here: https://github.com/awesomeWM/awesome/blob/cc67a5b40bcd461a3ed3e955da8409219b11efcf/ewmh.c#L471
If this is really broken, the error would have been introduced in c5202a48708585cc33528065af8d1b1d28b1a6e0.

> I'm not sure if this is related, but 

@daraul My general suggestion would be "if in doubt, open a new issue". Also, please open a new issue about this to make sure it is properly tracked.

**Comment by daraul** [comment]
> open a new issue

Done! See #3204

**Comment by psychon** [comment]
I think #3236 is the duplicate where this was debugged and #3237 is the fix.
