### ISSUE TITLE
Coloring notification text with markup makes it not appear

### ISSUE THREAD

**Issue by elenapan** [awesomeWM/awesome#3049]
The following command should create a notification with a red `message`, but instead the `message` does not appear at all.
```shell
notify-send "the title" "<span foreground='#ff0000'>the red message</span>"
```

`naughty` is also affected.

The commit that breaks this: b6ce95cd

**Comment by actionless** [comment]
can you reproduce it with default rc.lua on latest master?

**Comment by elenapan** [comment]
Yes.

**Comment by actionless** [comment]
ah, i see now why i wasn't able to reproduce it -- when updating awesome /etc/xdg/awesome/rc.lua config didn't updated (and new was installed as .pacnew)

the difference between old and new rc.lua was:


```diff
@@ -518,9 +515,27 @@
         layout = wibox.layout.align.horizontal
     }
 end)
+
+-- {{{ Notifications
+
+ruled.notification.connect_signal('request::rules', function()
+    -- All notifications will match this rule.
+    ruled.notification.append_rule {
+        rule       = { },
+        properties = {
+            screen           = awful.screen.preferred,
+            implicit_timeout = 5,
+        }
+    }
+end)
+
+naughty.connect_signal("request::display", function(n)
+    naughty.layout.box { notification = n }
+end)
+
 -- }}}

 -- Enable sloppy focus, so that focus follows mouse.
 client.connect_signal("mouse::enter", function(c)
     c:activate { context = "mouse_enter", raise = false }
```

**Comment by actionless** [comment]
also i've reproduced a similar/related issue:

with notification text `I searched for that on our
 Help Center. Perhaps these articles will help: \n• <Improve company culture with Slack>
\n• <Voice, video, and screen sharing apps>\n• <Use threads to organize discussions>`

awesome logs an error:
`E: awesome: Error on line 2 char 23: Odd character “c”, expected a “
=” after attribute name “company” of element “Improve”`

**Comment by actionless** [comment]
please try if this patch works for you: https://github.com/awesomeWM/awesome/pull/3074

**Comment by elenapan** [comment]
It works.
