### ISSUE TITLE
Variable to increase gap between notification and the edge of the screen

### ISSUE THREAD

**Issue by Tibo-le-canard** [awesomeWM/awesome#3051]
Hello,

There is no way to increase the gap between a notification and the edge of the screen.

I did read the APIDoc and except `notification_spacing`, which increase the gap between each notification, I did not find anything.

Is it possible to add a new theme variable ?

**Comment by SethBarberee** [comment]
https://github.com/awesomeWM/awesome/blob/f997009ff4c4cb73c1364126e6df7867832705d3/lib/naughty/layout/box.lua#L59-L62

This is probably what you mean as the margins for the top and bottom are set and used here for the popup:
https://github.com/awesomeWM/awesome/blob/f997009ff4c4cb73c1364126e6df7867832705d3/lib/naughty/layout/box.lua#L76

This is speculation on my part since i haven't tried it but I wonder if the right/left margins are set with that too, it would have the desired effect.

**Comment by Aire-One** [comment]
IIRC, the spacing is used to separate multiples notifications. That's similar to gaps between clients.

**Comment by Tibo-le-canard** [comment]
Here are some screenshots with the spacing variable set to 0 and 20.
```
    theme.notification_position = 'top_right'
    theme.notification_spacing = 0
    theme.notification_margin = 0
```
![20200331_092537](https://user-images.githubusercontent.com/10544393/77998774-e6250900-7331-11ea-834f-63603191c065.png)

```
    theme.notification_position = 'top_right'
    theme.notification_spacing = 20
    theme.notification_margin = 0
```
![20200331_092553](https://user-images.githubusercontent.com/10544393/77998778-e6bd9f80-7331-11ea-9af1-9cbed34e73ee.png)

As you can see the notification is still stuck on the edge.

**Comment by Tibo-le-canard** [comment]
@SethBarberee indeed adding left/right in get_spacing() kind of works, but each notification is shifted.
Here is a screenshot :
![20200331_222953](https://user-images.githubusercontent.com/10544393/78072443-70578680-739f-11ea-8ef9-2aea15eaa497.png)

Stupid question, but what if somebody want different spacing for left/right and top/bottom ?

**Comment by SethBarberee** [comment]
Yeah, that is probably the effect of that hack as `awful.placement` thinks they are sideways next to each other. I'll take a deeper look into the code later this week to see if I can draft up a PR/idea.

**Comment by actionless** [comment]
this works for me but i didn't tested it with other notification positions than "top_left":

```diff
diff --git a/lib/naughty/layout/box.lua b/lib/naughty/layout/box.lua
index ecbc365f8..a6b81c345 100644
--- a/lib/naughty/layout/box.lua
+++ b/lib/naughty/layout/box.lua
@@ -61,6 +61,11 @@ local function get_spacing()
     return {top = margin, bottom = margin}
 end

+local function get_offset()
+    local margin = beautiful.notification_spacing or 2
+    return {x = -margin}
+end
+
 -- Leverage `awful.placement` to create the stacks.
 local function update_position(position)
     local pref  = position:match("top_") and "bottom" or "top"
@@ -76,6 +81,9 @@ local function update_position(position)
                 margins             = get_spacing(),
                 honor_workarea      = true,
             }
+            if k == 1 then
+                args.offset              = get_offset()
+            end

             -- The first entry is aligned to the workarea, then the following to the
             -- previous widget.
```

**Comment by actionless** [comment]
i've updated the patch above please test, and if works well for you too, i'll prepare a PR

**Comment by vn-ki** [comment]
But there was a config setting `padding` earlier. That one should be exposed by the new api.

**Comment by actionless** [comment]
@vn-ki 

don't remember such, could you please point to older doc/source code?

**Comment by vn-ki** [comment]
https://awesomewm.org/apidoc/libraries/naughty.html#config

this is the master docs. 

> padding int Space between popups and edge of the workarea. (default apply_dpi(4))

**Comment by actionless** [comment]
ah, so it wasn't in beautiful, but only in the config

in that case patch would be a bit less trivial, as it will require accessing config of this notification from that update_position function

**Comment by Tibo-le-canard** [comment]
@actionless patch works like a charm :) ! Thank you !
Here is a screenshot :
![20200517_110037](https://user-images.githubusercontent.com/10544393/82140139-d4d68400-982d-11ea-9834-2578f906b783.png)

**Comment by actionless** [comment]
Thanks @Tibo-le-canard and @vn-ki 

i've created a PR

**Comment by actionless** [comment]
btw whlie testing this i also found what popup have sorta related bug with spacing from the screen :(
now need to dig into that one :D
