### ISSUE TITLE
Hotkeys popup larger than the screen

### ISSUE THREAD

**Issue by psychon** [awesomeWM/awesome#3054]
Basically: https://stackoverflow.com/questions/60924310/how-do-i-chance-the-size-of-hotkeys-popup-show-help

The default size of the hotkeys popup is hardcoded. Instead, the code should do something based on the screen size / workarea.

Based on someone else just asking about this on IRC, I came up with the following (which could also be simplified somehow, I guess...):
```diff
diff --git a/awesomerc.lua b/awesomerc.lua
index 6e2a3a6a6..64f75affb 100644
--- a/awesomerc.lua
+++ b/awesomerc.lua
@@ -215,9 +215,11 @@ awful.mouse.append_global_mousebindings({
 -- {{{ Key bindings
 -- @DOC_GLOBAL_KEYBINDINGS@
 
+local my_hotkeys_popup = hotkeys_popup.widget.new({ width = 300, height = 300})
+
 -- General Awesome keys
 awful.keyboard.append_global_keybindings({
-    awful.key({ modkey,           }, "s",      hotkeys_popup.show_help,
+    awful.key({ modkey,           }, "s",      function() my_hotkeys_popup:show_help() end,
               {description="show help", group="awesome"}),
     awful.key({ modkey,           }, "w", function () mymainmenu:show() end,
               {description = "show main menu", group = "awesome"}),
```
Edit: With "simplified" I mean something like "how about adding this to the docs"?

**Comment by actionless** [comment]
if the hardcoded size is smaller than workarea -- workarea size will be used:

https://github.com/awesomeWM/awesome/blob/master/lib/awful/hotkeys_popup/widget.lua#L529-L532

**Comment by psychon** [comment]
Hm... then I do not understand the questions/reports about this problem that I saw elsewhere...

Should this be closed?

**Comment by actionless** [comment]
i guess, unless it will be provided more info on how to reproduce the issue
