### ISSUE TITLE
Unable to use `awful.tag` with stateful layout

### ISSUE THREAD

**Issue by jcrd** [awesomeWM/awesome#3056]
Output of `awesome --version`:
```
awesome devel (Too long)
 • Compiled against Lua 5.3.5 (running with Lua 5.3)
 • API level: 4
 • D-Bus support: yes
 • xcb-errors support: no
 • execinfo support: yes
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
 • Transparency enabled: yes
 • Custom search paths: no
```

**How to reproduce the issue:**
Add tags with stateful layout to screen:
```
awful.tag({"1", "2", "3"}, s, stateful_layout_func)
```

**Actual result:**
```
error: /usr/share/awesome/lib/awful/tag.lua:371: attempt to index a function value (local 'layout')
```

**Expected result:**
`awful.tag` should expect a function and behave like `awful.tag.add` with regards to stateful layouts.

**Comment by Aire-One** [comment]
`awful.tag.new` and `awful.tag.add` both ignore what layout actually is (stateful or not). Only difference is `awful.tag.new` checks if it's a table (list) of layouts. And that's precisely the test that cause your crash...

Easiest way to fix it should be to use a table to hold your layout (basically a list of 1 layout):

```lua
awful.tag({"1", "2", "3"}, s, {stateful_layout_func})
```

Second option is to patch awesome. I guess something like this should be enought (not tested):

```diff
diff --git a/lib/awful/tag.lua b/lib/awful/tag.lua
index b04687ee2..d7824172b 100644
--- a/lib/awful/tag.lua
+++ b/lib/awful/tag.lua
@@ -318,7 +318,7 @@ end
 function tag.new(names, screen, layout)
     screen = get_screen(screen or 1)
     -- True if `layout` should be used as the layout of each created tag
-    local have_single_layout = (not layout) or (layout.arrange and layout.name)
+    local have_single_layout = (not layout) or (type(layout) == 'function') or (layout.arrange and layout.name)
     local tags = {}
     for id, name in ipairs(names) do
         local l = layout
```

Side question: I'm genuinely interested in what kind of stateful layout you're working with... Would you mind sharing it?

**Comment by jcrd** [comment]
Your proposed patch looks like it would work.

I'm using a layout I wrote called [dovetail](https://github.com/jcrd/awesome-dovetail).
