### ISSUE TITLE
Corrupted rendering in some applications

### ISSUE THREAD

**Issue by skosch** [awesomeWM/awesome#3059]
```
awesome v4.2 (Human after all)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.5
 • LGI version: 0.9.2
```

**How to reproduce the issue:**
Hardware: Intel integrated on Lenovo Thinkpad, using i915 driver on Ubuntu 18.04, Kernel 5.3.0-45.

This affects particular applications, e.g. Emacs, Evince (gtk3?), vim.gtk2 (but not vim.gtk3!), LibreOffice (gtk3), Onivim2 (Skia), GIMP, or Inkscape (gtk2).

Notably, other applications are not affected, e.g. Firefox, Thunderbird, Chrome, Kitty, video players, etc.

The problem does not occur in Gnome 3 (on X11) or when using Wayland.

**Actual result:**
UI elements are not painted correctly. This can be fixed by doing whatever it takes to repaint (sometimes mouse-over, sometimes resizing, sometimes switching to another desktop/tag and back):

![image](https://user-images.githubusercontent.com/554383/78719553-f4969600-78d8-11ea-8cbc-baabbd73c772.png)

**Approaches that have not worked:**

- Turning on "TearFree" or "sna" in the video driver settings
- Using an additional compositor like compton
- Setting `COGL_ATLAS_DEFAULT_BLIT_MODE=framebuffer`
- Changing `size_hints_honor` from `false` to `true`
- Running awesomewm with `--no-argb`
- Using the default `rc.lua` file instead of my own

I love awesome and cannot go back to another WM. I'm not even sure if this is awesome's fault, but I would be grateful for your ideas what I can try next to debug this.

**Comment by actionless** [comment]
does it happens with `openbox`?

**Comment by skosch** [comment]
It does! Thanks for responding so quickly. What does that mean?

**Comment by actionless** [comment]
what the problem is not related to AwesomeWM

**Comment by Elv13** [comment]
> What does that mean?

Most probably a driver bug. One workaround is usually to start `picom`. If the default settings don't fix it, try alternative backends until it works. Make sure to report the bug to the driver developers. You might want to test with Kernel 5.4 or 5.6 first. 5.3 isn't an LTS kernel.

**Comment by skosch** [comment]
@Elv13 Thank you so much. Switching from `"Driver" "intel"` to `"Driver" "modesetting"` finally fixed the problem for me. Apparently the intel driver is deprecated anyway. I'm not even sure how it got in there. Thanks again for your help and for a fantastic window manager!
