### ISSUE TITLE
unexpected unicodes appearing in textbox

### ISSUE THREAD

**Issue by BigfootN** [awesomeWM/awesome#3061]
Output of `awesome --version`:

awesome v4.3-813-gf997009ff (Too long)
 • Compiled against Lua 5.3.5 (running with Lua 5.3)
 • API level: 4
 • D-Bus support: yes
 • xcb-errors support: no
 • execinfo support: yes
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
 • Transparency enabled: yes
 • Custom search paths: no

**How to reproduce the issue:**

Create a textbox:

```lua

wibox.widget {
        font = "NotoSansMono Nerd Font 10",
        align = "right",
        valign = "center",
        text = "36 Crazyfists",
        forced_height = theme.popup_music_text_height,
        widget = wibox.widget.textbox
}
```

**Actual result:**

![](https://i.imgur.com/zKZlXN8.png)

**Expected result**

There shouldn't be any phone.

Thank you very much in advance for any help.

**Comment by actionless** [comment]
seems like your nerd font got the [ligatures](https://www.fonts.com/content/learning/fontology/level-3/signs-and-symbols/ligatures-1) wrong and used their characters for phone icon

unless in some other text view supporting ligatures (for example Konsole) the same ligature is displayed correctly please feel free to reopen

**Comment by actionless** [comment]
also see https://wiki.archlinux.org/index.php/Font_configuration/Examples#Disable_ligatures_for_monospaced_fonts

**Comment by BigfootN** [comment]
Thank you very much for your quick response, I'll look into it.
