### ISSUE TITLE
Center placement that takes into account wibar(s) height

### ISSUE THREAD

**Issue by madprops** [awesomeWM/awesome#3062]
awesome v4.3-809-g5d1394b9 (Too long)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • API level: 4
 • D-Bus support: yes
 • xcb-errors support: no
 • execinfo support: yes
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
 • Transparency enabled: yes
 • Custom search paths: no

I like to center windows often, when they start and when I invoke a shortcut manually. Thing is I'd like to consider 'center' as being the center of the available area (beyond the wibar).

To do this manually I've been doing:

```
    c.center = function()
        if not c.maximized then
            awful.placement.align(c, {position="centered"})
            c.y = c.y - (c.screen.mywibox.height / 2)
        end
    end
```

Which works but maybe there should be a simpler way. Something like:

`awful.placement.centered_area`

It should be able to handle cases when there are multiple wibars which are either horizontal or vertical, and if they're top/bottom, left/right

**Comment by Elv13** [comment]
Hello,

You need to set `honor_workarea` to true.

**Comment by madprops** [comment]
Oops it already exists, works great, thank you

**Comment by madprops** [comment]
Wondering if it's possible to use `honor_workarea` with window rules
`placement = awful.placement.centered`

**Comment by elenapan** [comment]
You can make a custom function:

```lua
local centered_client_placement = function(c)
    return awful.placement.centered(c, {honor_workarea=true})
end
```

And set placement in your rules like so:
```
placement = centered_client_placement
```

**Comment by psychon** [comment]
I think you can also just do `placement = function(c) return awful.placement.centered(c, {honor_workarea=true}) end`, avoiding the extra variable.

**Comment by actionless** [comment]
btw, is the titlebar geometry honored?
