### ISSUE TITLE
problem to count all client

### ISSUE THREAD

**Issue by paranoid73** [awesomeWM/awesome#3066]
Output of `awesome --version`:
```
awesome v4.3-814-g158cc37a0 (Too long)
 • Compiled against Lua 5.3.5 (running with Lua 5.3)
 • API level: 4
 • D-Bus support: yes
 • xcb-errors support: yes
 • execinfo support: yes
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
 • Transparency enabled: yes
 • Custom search paths: no
```
**How to reproduce the issue:**
```
in my rc.new.lua
print("--------debug-------")
    local clients = {}
    for _, c in ipairs(client.get()) do
        table.insert(clients, c)
        print("--------debug-------")
    end
    print(#clients)
```
**Actual result:**
```
--------debug-------
0
```
**Expected result:**
2 because i opened two clients

**Comment by psychon** [comment]
> in my rc.new.lua

So you just put this somewhere in `rc.lua` in global context? If I understand you correctly, this means that this code is executed when awesomeWM starts. At this point, there are always zero clients present.

The following works for me:
```sh
$ awesome-client 'return #client.get()'
   double 9
```
(If you are restarting awesomeWM and some clients are already present: Well, they are still only handled after the config was parsed, so at the time the config is loaded, there will always be zero clients present. You can use `awesome.connect_signal("startup", function() print("startup done") end)` to execute some code once startup is done and all clients were added.)

**Comment by paranoid73** [comment]
thank you , i understand now why i had the issue .
