### ISSUE TITLE
awful.permissions error when using linear pattern as border color

### ISSUE THREAD

**Issue by ndgnuh** [awesomeWM/awesome#3067]
Output of `awesome --version`:
```
awesome --version
awesome v4.3-814-g158cc37a-dirty (Too long)
 • Compiled against Lua 5.1.4 (running with LuaJIT 2.1.0-beta3)
 • API level: 4
 • D-Bus support: yes
 • xcb-errors support: no
 • execinfo support: yes
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
 • Transparency enabled: yes
 • Custom search paths: no
```

**How to reproduce the issue:**

Use this in the `theme.lua`:
```lua
local stop_color = {
   "#FFFF00",
   "#000000",
}
local stop = {}
local stop_end = 0
local stop_index = 1
while stop_end < 1 do
   stop_end = stop_end + 0.01
   table.insert(stop, {stop_end, stop_color[stop_index]})
   stop_index = stop_index + 1
   if stop_index > #stop_color then stop_index = 1 end
end
local stripe = gcolor.create_pattern_uncached{
   type = 'linear',
   from = {2000, 0},
   to = {0, 2000},
   stops = stop
}
theme.border_focus = stripe -- this runs fine, but the error is thrown everytime the border is set
```

**Actual result:**

Some thing like this (the border doesn't change color, of course):
![image](https://user-images.githubusercontent.com/33273948/79691769-8adc9b80-828b-11ea-86c8-59d1cb2abddc.png)

**Expected result:**

The pattern works fine on the titlebars
![image](https://user-images.githubusercontent.com/33273948/79691784-9f209880-828b-11ea-9136-f15ae0b5496b.png)

**Comment by psychon** [comment]
Sorry, but a client's `border_color` must be a string describing a solid color. It cannot be a `gears.color`-style pattern. This is because in X11, a border color is just a border color. The titlebars are drawn by awesomeWM itself and thus can be drawn "more complicated".

If you want more complicated borders, you need to fake that with titlebars on all sides.

**Comment by ndgnuh** [comment]
Woops, so this is not possible because of X. I'm going to close this issue then.
