### ISSUE TITLE
Unmaximize button doesn't work on GTK applications with CSD

### ISSUE THREAD

**Issue by khalid151** [awesomeWM/awesome#3068]
Output of `awesome --version`:
```
awesome v4.3 (Too long)
 • Compiled against Lua 5.3.5 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
```

**How to reproduce the issue:**
- Run any GTK application with CSD
- Maximize using CSD window controls

**Actual result:**

The window cannot be unmaximized using CSD window controls (but keyboard shortcuts still work).

**Expected result:**

The window should be unmaximized.

**Comment by psychon** [comment]
Does this happen with the default config? I think windows (un)maximising themselves is something that can be blocked by rc.lua. I am not even sure if the default config allows that...

**Comment by khalid151** [comment]
Yes, still having the same issue. However, using window controls of the titlebar of awesome works normally.

**Comment by actionless** [comment]
could you try with AwesomeWM from master branch? i think that issue was already fixed there few months ago

**Comment by khalid151** [comment]
I've tried compiling from source and it's fixed. CSD controls work as expected.

I'd like to mention that I've tried the same with Steam client but it's kind of having the same issue. Maximize then unmaximize work for once and stops working after that, until the window is minimized and unminimized again.

Should I close the issue?

**Comment by actionless** [comment]
if Steam is still not working in the master branch you could/create new one and close this one, or just rename this one

**Comment by khalid151** [comment]
Okay then, I'll be closing this issue.
