### ISSUE TITLE
wibox.container.scroll: Can't receive mouse events in children widgets

### ISSUE THREAD

**Issue by actionless** [awesomeWM/awesome#3076]
Output of `awesome --version`:

```
awesome v4.3-826-ge8201368-dirty (Too long)
 • Compiled against Lua 5.1.4 (running with LuaJIT 2.0.5)
 • API level: 4
 • D-Bus support: yes
 • xcb-errors support: yes
 • execinfo support: yes
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
 • Transparency enabled: yes
 • Custom search paths: no
```

**How to reproduce the issue:**

add any widget with either :buttons() or mouse::enter/leave and put it inside wibox.container.scroll

**Actual result:**
mouse events not received by children widgets

**Expected result:**
mouse events are received by children widgets

**Comment by psychon** [comment]
Seems to me to work as intended:

https://github.com/awesomeWM/awesome/blob/87928befe2dc981bfdbca59c0474c0ff5d39544f/lib/wibox/container/scroll.lua#L6-L7

**Comment by actionless** [comment]
oops, my bad
