### ISSUE TITLE
Placement inconsistency on corner

### ISSUE THREAD

**Issue by madprops** [awesomeWM/awesome#3080]
awesome v4.3-809-g5d1394b9 (Too long)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • API level: 4
 • D-Bus support: yes
 • xcb-errors support: no
 • execinfo support: yes
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
 • Transparency enabled: yes
 • Custom search paths: no

I have this calendar program I set to open when the clock is clicked:

`awful.util.spawn("galendae", false)`

I have set this rule, since I want it to open just above the clock:

```
    { rule = { 
        instance="galendae"
    },
      properties = {
            placement = awful.placement.bottom_right
        }
    }
```

The issue I found is that it won't always start at the exact same position when spawned:

(A) Sometimes it starts like this: 
![2020-04-23_19-46](https://user-images.githubusercontent.com/206498/80166553-7bb36180-859b-11ea-8929-ce79b9973132.png)

(B) And sometimes it starts like this:
![2020-04-23_19-47](https://user-images.githubusercontent.com/206498/80166657-adc4c380-859b-11ea-9d11-eaa72d486b11.png)

Notice the difference between the clock and tray icons and the calendar in both screenshots.
galendae closes when I click the clock again; I tried closing it through the close button and observed the same result. I tried re-opening with a delay to avoid race conditions, same result.

If it starts as A or B seems to be unpredictable/random.

Extra information, I also have this:

```
    { rule = { },
      properties = 
        { 
            border_width = 0,
            border_color = beautiful.border_normal,
            focus = awful.client.focus.filter,
            raise = true,
            keys = clientkeys,
            buttons = clientbuttons,
            screen = awful.screen.preferred,
            placement = centro,
            floating = true,
            titlebars_enabled = true
        }
    },
```

**Comment by actionless** [comment]
why this one got closed?

**Comment by madprops** [comment]
Seems it's custom-config specific
