### ISSUE TITLE
awful.spawn (shortcuts) delayed execution

### ISSUE THREAD

**Issue by elyoas** [awesomeWM/awesome#3086]
Output of `awesome --version`:
awesome v4.3 (Too long)
 • Compiled against Lua 5.3.5 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2

**How to reproduce the issue:**
1. Add the two rules to _globalkeys_:
`awful.key( {modkey}, "1", nil, function () awful.spawn("setxkbmap gb") end),`
`awful.key( {modkey}, "2", nil, function () awful.spawn("setxkbmap ara qwerty_digits") end),`

2. Attempt to change language, press _modkey + 1_

**Actual result:**
The response is delayed. Unless you keep both buttons down for a minimum time of some 0.1 second, the command won't be executed.

**Expected result:**
It should execute instantly (the command should not require a minimum press time of the second key). I'm coming from LXDE, and there I had the same shortcuts which executed in an instant.

Other shortcuts tied to a single key, such as:
`awful.key( {}, "KP_Left", nil, function () awful.spawn("gedit") end),`
Execute instantly.

**Comment by psychon** [comment]
Could you try adding `naughty.notify{ text = "Hi" }` to your keybinding to check if it is really not executed?

**Comment by actionless** [comment]
shouldn't it be `awful.key( {}, "KP_Divide", function () awful.spawn(naughty.notify{ text = "Hi" }) end)` then?

**Comment by elyoas** [comment]
Thank you so much! Yes this solves the issue! The response now is lightning fast I'm so happy!
