### ISSUE TITLE
Give option to not escape notification text

### ISSUE THREAD

**Issue by cdubthecoolcat** [awesomeWM/awesome#3109]
Output of `awesome --version`:
```
awesome v4.3-856-ge7113d71 (Too long)
 • Compiled against Lua 5.3.5 (running with Lua 5.3)
 • API level: 4
 • D-Bus support: yes
 • xcb-errors support: no
 • execinfo support: yes
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
 • Transparency enabled: yes
 • Custom search paths: no
```

**How to reproduce the issue:**

Receive a notification from a certain application with a '"' or '&'. I was able to reproduce this with [`mpd-notification`](https://github.com/eworm-de/mpd-notification) as well as [`telegram-desktop`](https://github.com/telegramdesktop/tdesktop).

**Actual result:**

The notification appears but instead of '&' it displays '\&amp;' and instead of '"' it displays '\&quot;'

**Expected result:**

The notification should display '&' and '"' for these notifications.

Certain programs escape their own notification text. It would be nice to be able to apply some rules for these programs to not escape their notifications.

**Comment by p-himik** [comment]
That's already possible with notification rules. Something like
```lua
{rule = { app_name = "Telegram" }
 properties = { message = function(notif) notif.message:gsub("&lt;", "<") end }}
 ```
(didn't check this particular code but you get the idea)
