### ISSUE TITLE
run: paste clipboard

### ISSUE THREAD

**Issue by danrobi11** [awesomeWM/awesome#3110]
Hello
Im new to awesome. Its really awesome btw ;)
One thing I find really strangle is that we cant paste clipboard at run prompt (mod+r)
I've tried ctrl+v and right-clicking but nothing will do here.
I went on internet tried to find something related havent found anything so im here.
So whats up with that?

**Comment by actionless** [comment]
does Shift+Insert works?

**Comment by danrobi11** [comment]
> does Shift+Insert works?

@actionless Yes it does , thank you!
I cant see Shift+Insert in the 'show help' (super+s) 
Is there any other doc with commands info?

**Comment by actionless** [comment]
https://awesomewm.org/doc/api/libraries/awful.prompt.html
