### ISSUE TITLE
awful.screen.focus_relative() mouse jump bug with 3 monitor setup

### ISSUE THREAD

**Issue by Randomneo** [awesomeWM/awesome#3114]
Output of `awesome --version`:

awesome v4.3 (Too long)
 • Compiled against Lua 5.3.5 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2

**How to reproduce the issue:**

I have 3 monitors. It can be reproduced on default config.
Use modkey + ctrl + k/j, or call awful.screen.focus_relative() by any other method.
Cycle through monitors (full loop).
Try to move mouse

**Actual result:**

Mouse jumps to unpredictable place, I could not find the pattern (If it was on the left it jumps to middle, or from middle to right, or from right to right edge of right screen)

**Expected result:**

Mouse stays still.

**Comment by psychon** [comment]
Random (unhelpful) thought: That must be a bug in the X11 server. There is no way in the X11 protocol to have the mouse cursor be displayed in a different position that it actually is. (This is how I interpret the symptoms of the bug, but there might be something else going on. Anyway, `awful.screen.focus_relative()` in the end only calls `mouse.coords()` which sets the position of the mouse cursor.)

**Comment by Randomneo** [comment]
@psychon thank you for your response. Nice thought I'll dig in this way.

But mouse.cords and focus_relative works great. Problems came after moving mouse.

**Comment by Randomneo** [comment]
After a few hours of playing around I removed my mouse configuration file. It helped. And problem was in `Option "TransformationMatrix" "2 0 0 0 2 0 0 0 1"`.
