### ISSUE TITLE
awful.menu cannot perform bash-within-bash

### ISSUE THREAD

**Issue by Yaanu** [awesomeWM/awesome#3115]
Output of `awesome --version`:

awesome v4.3 (Too long)
• Compiled against Lua 5.3.5 (running with Lua 5.3)
• D-Bus support: ✔
• execinfo support: ✔
• xcb-randr version: 1.6
• LGI version: 0.9.2

**How to reproduce the issue:**

1. In "rc.lua", create/configure an awful.menu setup. For example, the right-click menu popup.
2. Add a command which calls a program and incorporates a bash call within its commands. For example, a command for screenshot tool "maim" which calls the native "date" function to return a name to be used in a screenshot: `{ "maim", "maim /home/User/Pictures/Screenshots/$(date).png" }`
3. Save "rc.lua" and refresh Awesome.
4. Use the "maim" function in the menu.

**Actual result:**

A screenshot is created and saved to ~/Pictures/Screenshots as "$(date).png". The filename is interpreted literally, rather than as part of a terminal command.

**Expected result:**

A screenshot should be created and saved with an actual date/time, such as "Fri Jun 12 22:36:52 EDT 2020".

**Other notes:**
I have no idea what the actual term for "bash within bash" is.

**Comment by psychon** [comment]
`awful.menu` uses `awful.spawn` to spawn commands. This means that it just spawns the command directly, without any shell. Thus, if you want to run a shell, you'll have to explicitly specify it. I think `{ "maim", "bash -c 'maim /home/User/Pictures/Screenshots/$(date).png'" }` should work.

**Comment by Yaanu** [comment]
Sorry I didn't get back to you right away about this; the notification slipped my notice.
But this worked! Running it as a bash command got it to work as I wanted. I had to do a bit more futzing to get it working as I had wanted, but otherwise I'd consider this issue closed.

Thanks!
