### ISSUE TITLE
hotkeys_popup shows up on the other screen

### ISSUE THREAD

**Issue by keryell** [awesomeWM/awesome#3118]
Output of `awesome --version`:

 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • API level: 4
 • D-Bus support: yes
 • xcb-errors support: no
 • execinfo support: yes
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
 • Transparency enabled: yes
 • Custom search paths: no

**How to reproduce the issue:**

Just type Mod4-s
on vanilla awesome master https://github.com/awesomeWM/awesome/commit/e7113d7191e37c5b0faedccff6caf82d8e0bd77c configuration.

**Actual result:**

I have 2 displays connected to my Ubuntu 20.04 laptop and I work mainly on my big 34" display.
When I want to see the current key-binding it actually shows up on the other display on my laptop, far away from my eyes.

**Expected result:**

I would like to have it just in front of me, displayed on screen where my mouse is whet I type Mod4-s

Actually I understand that having the help on another screen is also useful in certain cases, so it would be nice to have this configurable and mapped on Mod4-Ctrl-s or whatever.
I do not have the big picture of `awful.hotkeys_popup`, so I do not know if it is possible or not already (without changing the source of `awful.hotkeys_popup` :-) ).
Perhaps having along `awful.hotkeys_popup.show_help` a `awful.hotkeys_popup.show_help_opt(some_options)` that would return a callable doing the right thing. Another trivial use case for such an optional API would be to change the font size of the help without changing the source of hotkeys_popup.

**Comment by actionless** [comment]
> so it would be nice to have this configurable 

https://awesomewm.org/apidoc/libraries/awful.hotkeys_popup.html

**Comment by keryell** [comment]
> https://awesomewm.org/apidoc/libraries/awful.hotkeys_popup.html

Yes you are right.
But I have tried various combinations, such as
```lua
awful.keyboard.append_global_keybindings({
    awful.key({ modkey, "Control" }, "s",
              function ()
--                 hotkeys_popup.show_help(nil, awful.screen.focused())
                 hotkeys_popup.show_help(awful.mouse.client,
                                         awful.mouse.screen,
                                         { show_awesome_keys = false })
--                 hotkeys_popup.widget.show_help(awful.mouse.client,
--                                                awful.mouse.screen,
--                                                { show_awesome_keys = false })
              end,
              {description="show help on focused screen", group="awesome"})
})
```
by changing also the `show_awesome_keys`, but it goes always on the same laptop display,
wherever the mouse is... :-(

**Comment by keryell** [comment]
I have not found yet some time to instrument code to understand what are the `srceen` defined in the running Lua code...
