### ISSUE TITLE
Notification content doesn't display when the title contains specific characters

### ISSUE THREAD

**Issue by IrreversibleReboot** [awesomeWM/awesome#3126]
Output of `awesome --version`:
```
awesome v4.3 (Too long)
 • Compiled against Lua 5.3.5 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
```

**How to reproduce the issue:**

Execute `notify-send "傀儡 ☽" 'test content'`.

**Actual result:**

![1593727161](https://user-images.githubusercontent.com/9488735/86413032-83406680-bcc0-11ea-9566-a86e8b0306df.jpg)
Only the title of the notification is displayed, not the content.

**Expected result:**

Both the title and the content is displayed.

**Comment by psychon** [comment]
I don't know what is going on, but I can reproduce this. Appending `\n` to the message makes things work. Perhaps the height is too small to display the text? Dunno why that would happen.

**Comment by IrreversibleReboot** [comment]
Doesn't seem to happen if the notification has an icon.
![1594243101](https://user-images.githubusercontent.com/9488735/86971404-677e0a00-c171-11ea-90dd-cc2a59be74a6.jpg)

**Comment by timroes** [comment]
@psychon I would second that doubt. I've seen the same issue for emoji only notifications, where adding a bit more height actually fixed the issue for me. I think somehow the height calculation for non "latin-like" unicode might be too small to actually fit the content into it.

**Comment by DziubanMaciej** [comment]
FYI, the issue is still observed :(

![awesome_issue1](https://user-images.githubusercontent.com/23078999/185991434-aeba3be7-3093-46c2-b429-ebc73beede0b.png)
![awesome_issue2](https://user-images.githubusercontent.com/23078999/185991438-9611d224-8770-4faa-83ba-65e05dabb25d.png)

**Comment by Elv13** [comment]
@DziubanMaciej just tested with the current git-master version of AwesomeWM with the new notification API and this appears to have been fixed.

**Comment by DziubanMaciej** [comment]
Huh, it seems arch linux contains a quite old version of awesome (14 Sep 2021). Thanks, I'll try latest.
