### ISSUE TITLE
gears.table.cycle_value doesn't exist

### ISSUE THREAD

**Issue by TornaxO7** [awesomeWM/awesome#3138]
Output of `awesome --version`:
```
awesome v4.3 (Too long)
 • Compiled against Lua 5.3.5 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
```
**How to reproduce the issue:**
1. open `rc.lua`
2. Add this line at the top of the file if it doesn't exist yet:
```lua
local gears = require("gears")
```
3. Than add this line of code:
```lua
gears.table.cycle_value()
```
**Actual result:**
I'm getting this error:
```
Oops, an error happened!
/home/tornax/.config/awesome/widgets/layout_popup.lua:-
69: attempt to call a nil value (field 'cycle_value')
```

**Expected result:**
I'm using [this code (second example)](https://awesomewm.org/apidoc/widgets/awful.widget.layoutlist.html) to have this nice little feature but it looks like that this doesn't work somehow.

**Comment by actionless** [comment]
you're using stable release but docs from master branch: https://awesomewm.org/doc/
