### ISSUE TITLE
naughty.connect_signal(...) doesn't exist

### ISSUE THREAD

**Issue by TornaxO7** [awesomeWM/awesome#3139]
Output of `awesome --version`:

awesome v4.3 (Too long)
 • Compiled against Lua 5.3.5 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2

**How to reproduce the issue:**

1. Open `rc.lua`
2. Enter these line of code [(code is from the wiki)](https://awesomewm.org/apidoc/libraries/naughty.html#request::display)
```lua
local naughty = require("naughty")
naughty.connect_signal("request::display", function(notification, context, args) end)
```
or this:
```lua
local naughty = require("naughty")
naughty:connect_signal("request::display", function(notification, context, args) end)
```

**Actual result:**
An error pops up:
```
error while running function!
stack traceback:
    /home/tornax/.config/awesome/rc.lua:20: in main chunk
error: /home/tornax/.config/awesome/rc.lua:20: attempt to call a nil value (field 'connect_signal')
```
![Screenshot](https://user-images.githubusercontent.com/50843046/89451540-ab5a3400-d75c-11ea-9317-a61e04cbecac.png)

**Expected result:**

It should just work.

**Comment by actionless** [comment]
https://github.com/awesomeWM/awesome/issues/3138#issuecomment-669400795
