### ISSUE TITLE
Arch, Lua 5.4 & AUR. awesome-git is flagged as out of date btw

### ISSUE THREAD

**Issue by Thomashighbaugh** [awesomeWM/awesome#3140]
**How to reproduce the issue:**
Try to download the package from the AUR and see for yourself, it doesn't work because it tries to use lgi from lua 5.4, which isn't ready for primetime yet. 

**Actual result:**
lgi check throws an error and the process stops, so far mixed success modifying the PKGBUILD and CMake files. 

**Expected result:**
Being able to use my config that depends on the git version's functionality still absent from the mainline repo version. 

Like I get that this is done out of the kindness of your hearts, I deeply appreciate it, but please adjust the lua version to look at lua53's lgi so we can actually use the thing.

**Comment by actionless** [comment]
use search mb: https://github.com/awesomeWM/awesome/issues/3123

**Comment by Thomashighbaugh** [comment]
### I don't think the issue is closed, 
##### here are some screenshots as to why I think that way. 


**First**:
![image](https://user-images.githubusercontent.com/32242061/89725271-8a931800-d9c2-11ea-8620-826811673f52.png)
> At 10 PM PDT roughly
 
**Second**: 
![image](https://user-images.githubusercontent.com/32242061/89725357-903d2d80-d9c3-11ea-93a6-81854cda5a45.png)
> with Luarocks 5.3.2 as suggested by [#3123](https://github.com/awesomeWM/awesome/issues/3123) 

**Third**: 
![image](https://user-images.githubusercontent.com/32242061/89725365-a519c100-d9c3-11ea-920a-fc9e35c2a606.png)
> The AUR package is still flagged. 

Maybe I have misread the commentary on issue [#3123](https://github.com/awesomeWM/awesome/issues/3123) but while I already knew about it and the associated branch that is still awaiting another reviewer for the most recent pull request that addresses the issue, the above conditions are still the case and as such the package still won't build for me.

Also lgi is not at the moment building in 5.4 even if it was before (but failing the test suite according to their repo) unless this was the test suite they meant 
![image](https://user-images.githubusercontent.com/32242061/89725528-42292980-d9c5-11ea-93a9-539c1f8ece56.png)

**Comment by Thomashighbaugh** [comment]
Here's what I did to get aweesome with the AUR feature set to finally work, for anyone later interested and in need of a quick fix like I was 

I added Chaotic-AUR to my /etc/pacman.conf
installed awesome-git with `pacman` 
then removed the lines from my /etc/pacman.conf

**Comment by psychon** [comment]
To quote from https://aur.archlinux.org/:

>  To report packaging bugs contact the package maintainer or leave a comment on the appropriate package page.

Please send your "The AUR package does not build" report to.... uhm... the comment section at https://aur.archlinux.org/packages/awesome-git/ or to trollixx, who is reported as the maintainer. I do not have access to ArchLinux infrastructure and I am not responsible for fixing their packaging.

Sorry.

**Comment by Thomashighbaugh** [comment]
> To quote from https://aur.archlinux.org/:
> 
> > To report packaging bugs contact the package maintainer or leave a comment on the appropriate package page.
> 
> Please send your "The AUR package does not build" report to.... uhm... the comment section at https://aur.archlinux.org/packages/awesome-git/ or to trollixx, who is reported as the maintainer. I do not have access to ArchLinux infrastructure and I am not responsible for fixing their packaging.
> 
> Sorry.

Someone already did both of those suggested items and yet here we are, hence the package being flagged as out-of-date and since actionless was the first to respond and (per my third screenshot) one of the listed maintainers that was why I opted to raise an issue here instead of commenting on the already well documented and evidently ignored AUR page. 

I understand that this is done out of the kindness of your hearts, so again thank you.
