### ISSUE TITLE
Spotify is buggy/laggy. (awesome-git version)

### ISSUE THREAD

**Issue by TornaxO7** [awesomeWM/awesome#3142]
Output of `awesome --version`:
```
awesome v4.3-862-g7a759432d-dirty (Too long)
 • Compiled against Lua 5.3.5 (running with Lua 5.3)
 • API level: 4
 • D-Bus support: yes
 • xcb-errors support: no
 • execinfo support: yes
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
 • Transparency enabled: yes
 • Custom search paths: no
```

**How to reproduce the issue:**

1. Install `spotify`
[ (Probably necessary)
2. Install [spicetify](https://github.com/khanhas/Spicetify)
3. Add a theme to it
4. Remove the theme with `spicetify --restore`
]
5. Install `awesome-git`
6. Use `awesome-git`

**Actual result:**
When I'm using `awesome-git` than spotify reacts pretty weird. If I want to hear the next or previous song that it's loaded after about 10 seconds. In general all events on spotify appears later either closing spotify! Restarting and reinstalling spotify didn't help either. Here a little gif with an example what I mean:
![GIF](https://user-images.githubusercontent.com/50843046/89742170-db287500-da97-11ea-919d-985824f9208c.gif)

**Expected result:**

Spotify should work without any problems as in the stable `awesomewm` release c(^-^)c

**Comment by actionless** [comment]
temporary reset awesome to default config (rename rc.lua to rc.lua.bak) and also spicetify (rename ~/.config/spotify to ~/.config/spotify.bak) and see if the problem still reproducible (not for me)

**Comment by TornaxO7** [comment]
Interesting... it works now if I set everything to default.... I'll try to find the issue. Thanks for the tipps!

**Comment by TornaxO7** [comment]
Ok, after setting back my `rc.lua.bak` to `rc.lua` I'm getting this issue again.... damn... this is gonna be funny to find the issue...

**Comment by TornaxO7** [comment]
Ok I found out that `naughty` is laggy/buggy as well.

**Comment by Elv13** [comment]
Mind to be more specific?

**Comment by TornaxO7** [comment]
Of course I'm sorry:<br>
I can't get any notifications anymore when I'm using my own config file... `naughty` doesn't pop up or let's rather say that `notify-send 'Test' 'Hello there'` does nothing. It just holds my cursor and nothing happens. After about 25 seconds my prompt appears and nothing else happens.
![Screenshot](https://user-images.githubusercontent.com/50843046/89768373-d4cbe480-dafb-11ea-9f1b-42a2dc5fd943.png)

**Comment by actionless** [comment]
please either rename or create a new issue

**Comment by TornaxO7** [comment]
ok, I'll create a new one
