### ISSUE TITLE
misleading `copyright`/`author` fields in the docs

### ISSUE THREAD

**Issue by actionless** [awesomeWM/awesome#3144]
btw regarding misleading `copyright`/`author` fields in the docs -- i think this problem was raised before few times

i suggest either to just remove it or to replace those two fields to a single link to github commit log for the appropriate file

_Originally posted by @actionless in https://github.com/awesomeWM/awesome/issues/3137#issuecomment-671114932_

**Comment by psychon** [comment]
Removing those fields is fine with me. They only serve to remind me of the passing of time. "What? It's been so long since I wrote this?!?"

**Comment by actionless** [comment]
mb we could leave smth like "originally added by"?

**Comment by Elv13** [comment]
this was implemented-ish a while back
