### ISSUE TITLE
Ignored DBUS msg type DBUS_TYPE_OBJECT_PATH

### ISSUE THREAD

**Issue by Veids** [awesomeWM/awesome#3154]
Output of `awesome --version`

```
awesome v4.3-862-g7a759432d-dirty (Too long)
 • Compiled against Lua 5.3.5 (running with Lua 5.3)
 • API level: 4
 • D-Bus support: yes
 • xcb-errors support: no
 • execinfo support: yes
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
 • Transparency enabled: yes
 • Custom search paths: no
```

**How to reproduce the issue:**

1. Subscribe for the org.freedesktop.DBus.ObjectManager InterfacesRemoved signal, like this:
```
dbus.add_match(
  "system", 
  "sender='org.bluez', interface='org.freedesktop.DBus.ObjectManager', member='InterfacesRemoved', path='/'"
)
dbus.connect_signal("org.freedesktop.DBus.ObjectManager", function(...)
...
end)
```
2. Remove a Bluetooth device

**Actual result:**

There's no "object path" field in the response

**Expected result:**

```
object path "/org/bluez/hci0/dev_6C_79_14_76_F5_98"
   array [
      string "org.freedesktop.DBus.Properties"
      string "org.freedesktop.DBus.Introspectable"
      string "org.bluez.Device1"
   ]
```
**Question:**
Simply patching dbus.c with:
```
--- ./dbus.c	2020-08-29 18:31:21.975192612 +0300
+++ dbus.new.c	2020-08-29 18:30:55.215048279 +0300
@@ -248,6 +248,7 @@
           DBUS_MSG_HANDLE_TYPE_NUMBER_OR_INT(uint64_t, DBUS_TYPE_UINT64, lua_pushinteger)
           DBUS_MSG_HANDLE_TYPE_NUMBER_OR_INT(double, DBUS_TYPE_DOUBLE, lua_pushnumber)
 #undef DBUS_MSG_HANDLE_TYPE_NUMBER_OR_INT
+          case DBUS_TYPE_OBJECT_PATH:
           case DBUS_TYPE_STRING:
             {
                 char *s;
```
brings the DBUS_TYPE_OBJECT_PATH string back in the response. So why this field is ignored?

**Comment by Elv13** [comment]
Hello,

Please use the LGI GDbus API. `dbus.c` is deprecated. It has a a mix of fixable and undefinable problems and is in every way inferior to the GDBus API you can get from LGI. The only reason it still exist is because it predates AwesomeWM usage of LGI/glib2 and for some time in the early days, LGI.GDBus was too unstable.

**Comment by Veids** [comment]
Ya, thank you for the information. Hope this will be reported in the docs. Will rewrite the script.

**Comment by actionless** [comment]
@Elv13 mb we could print some deprecation warning?
