### ISSUE TITLE
LibreOffice 7 not tiling, cannot be moved, it only can be closed

### ISSUE THREAD

**Issue by Magnus512** [awesomeWM/awesome#3155]
awesome v4.3 (Too long)
 • Compiled against Lua 5.3.5 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2

**How to reproduce the issue:*
Open LIbreoffice 7
**Actual result:**
The window is in full mode it cannot be moved, not tiling, not change between tiling modes, cannot be selected, I just can close it
**Expected result:**
Be able to tile the window, it works well in bspwm and qtile, but not awesome

----- Xprop output ---
_NET_WM_DESKTOP(CARDINAL) = 3
_NET_FRAME_EXTENTS(CARDINAL) = 1, 1, 1, 1
WM_STATE(WM_STATE):
		window state: Normal
		icon window: 0x0
awful.client.property.single_instance_id(UTF8_STRING) = 
_NET_WM_STATE(ATOM) = _NET_WM_STATE_MAXIMIZED_VERT, _NET_WM_STATE_MAXIMIZED_HORZ
WM_HINTS(WM_HINTS):
		Client accepts input or input focus: True
		Initial state is Normal State.
		bitmap id # to use for icon: 0x4200329
		bitmap id # of mask for icon: 0x420032f
		window id # of group leader: 0x4200001
_GTK_THEME_VARIANT(UTF8_STRING) = 
_GTK_UNIQUE_BUS_NAME(UTF8_STRING) = ":1.37"
_GTK_APPLICATION_OBJECT_PATH(UTF8_STRING) = "/org/libreoffice"
_GTK_WINDOW_OBJECT_PATH(UTF8_STRING) = "/org/libreoffice/window/69206791"
_GTK_MENUBAR_OBJECT_PATH(UTF8_STRING) = "/org/libreoffice/window/69206791/menus/menubar"
_GTK_APPLICATION_ID(UTF8_STRING) = "org.libreoffice"
_NET_WM_ICON(CARDINAL) = 	Icon (32 x 32):

---Icons---

XdndAware(ATOM) = BITMAP
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_NORMAL
_NET_WM_SYNC_REQUEST_COUNTER(CARDINAL) = 69206793, 69206794
_NET_WM_USER_TIME(CARDINAL) = 9005899
_NET_WM_USER_TIME_WINDOW(WINDOW): window id # 0x4200308
WM_CLIENT_LEADER(WINDOW): window id # 0x4200001
_NET_WM_PID(CARDINAL) = 11630
WM_LOCALE_NAME(STRING) = "es_MX.utf8"
WM_CLIENT_MACHINE(STRING) = "raven"
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified location: 0, 0
		program specified minimum size: 1 by 1
		program specified base size: 0 by 0
		window gravity: Static
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, WM_TAKE_FOCUS, _NET_WM_PING, _NET_WM_SYNC_REQUEST
WM_CLASS(STRING) = "libreoffice", "libreoffice-writer"
WM_ICON_NAME(STRING) = "Sin título 1 - LibreOffice Writer"
_NET_WM_ICON_NAME(UTF8_STRING) = "Sin título 1 - LibreOffice Writer"
WM_NAME(STRING) = "Sin título 1 - LibreOffice Writer"
_NET_WM_NAME(UTF8_STRING) = "Sin título 1 - LibreOffice Writer"

**Comment by actionless** [comment]
mb it's floating or maximized and you just didn't noticed that

please attach `xprop` output for that window

**Comment by Magnus512** [comment]
> mb

I don't have anything in floating or maximized

**Comment by Magnus512** [comment]
> mb it's floating or maximized and you just didn't noticed that
> 
> please attach `xprop` output for that window

I have the xprop output

**Comment by psychon** [comment]
```
_NET_WM_STATE(ATOM) = _NET_WM_STATE_MAXIMIZED_VERT, _NET_WM_STATE_MAXIMIZED_HORZ
```
The window is maximized

**Comment by actionless** [comment]
@Magnus512 just press `Super+m` to "fix" that

**Comment by Magnus512** [comment]
> ```
> _NET_WM_STATE(ATOM) = _NET_WM_STATE_MAXIMIZED_VERT, _NET_WM_STATE_MAXIMIZED_HORZ
> ```
> 
> The window is maximized

What can I do to fix this ? It always starts in maximized

**Comment by psychon** [comment]
Sounds like a LibreOffice question. Sorry, I do not know an answer. Google found https://forums.linuxmint.com/viewtopic.php?t=100046, but that seems only vaguely related and is quite old.
