### ISSUE TITLE
installing using instructions from readme.md installs stable branch instead of master

### ISSUE THREAD

**Issue by ThePixelHelix** [awesomeWM/awesome#3161]
Output of `awesome --version`:

awesome v4.3 (Too long)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2

**How to reproduce the issue:**

install awesome on ubuntu following the instructions in the readme.md and using the genreated deb

**Actual result:**

installs the stable-branch

**Expected result:**

installs the git-master branch

**Comment by psychon** [comment]
You mean [these instructions](https://github.com/awesomeWM/awesome/blob/master/docs/01-readme.md#debian-based)?

Uhm. I'm confused and tempted to say "it is impossible for this to install a different version than what you checked out from git".

In case you still have the directory where you ran these command, could you run `./build/awesome --version` in that directory and check what it says? Also, did all the commands work or was there any error?

**Comment by ThePixelHelix** [comment]
nope no errors 
I have no idea why this happened and I am inclined to agree that this just didnt happen and I somehow messed up

heres the result of ./build/awesome --version
awesome v4.3-862-g7a759432 (Too long)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • API level: 4
 • D-Bus support: yes
 • xcb-errors support: no
 • execinfo support: yes
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
 • Transparency enabled: yes
 • Custom search paths: no

**Comment by ThePixelHelix** [comment]
It seems that I did do something wrong along the way but im unsure what

**Comment by psychon** [comment]
Ah, I have an idea.

cmake defaults to installing to `/usr/local`. So, where did "the other awesome" come from? Do you have both `/usr/bin/awesome` and `/usr/local/bin/awesome`?

Hm, no. I just did `cd /tmp; git clone [awesome git repo]; make package; ar x build/awesome-*; tar -xvzf data.tar.gz`. The result is the following list of files:
```
./usr/
./usr/bin/
./usr/bin/awesome
./usr/bin/awesome-client
./usr/local/
./usr/local/etc/
./usr/local/etc/xdg/
./usr/local/etc/xdg/awesome/
./usr/local/etc/xdg/awesome/rc.lua
./usr/local/share/
./usr/local/share/awesome/
[lots of stuff in subdirectories]
./usr/local/share/doc/
./usr/local/share/doc/awesome/
[lots of stuff in subdirectories]
./usr/local/share/man/
[lots of stuff in subdirectories]
./usr/local/share/xsessions/
./usr/local/share/xsessions/awesome.desktop
```
So, yes, there is some `/usr/local` involved, but `/usr/bin/awesome` is not in there...

Sorry, no idea what went wrong in your installation.

**Comment by Aire-One** [comment]
Probably a dumb question but : are you sure you didn't have awesome installed by your package manager or something?

**Comment by psychon** [comment]
@Aire-One I thought the same, but installing the .deb generated by `make package` should replace the existing package with the same name. Yeah, I agree that some other awesome package is interfering here, but I have no idea how this is even possible...

Sadly, I do not really know how to check... Well, `apt-cache policy awesome` would kind-of answer that question. For me it says the following (I patched my local awesome source to have version number 9999`; that version is only available "locally" and not from the repositories).
```
$ apt-cache policy awesome
awesome:
  Installiert:           9999.0.0
  Installationskandidat: 9999.0.0
  Versionstabelle:
 *** 9999.0.0 100
        100 /var/lib/dpkg/status
     4.3-5 990
        990 http://ftp.de.debian.org/debian testing/main amd64 Packages
         50 http://http.debian.net/debian unstable/main amd64 Packages
```
