### ISSUE TITLE
[Question] 1 column tiling

### ISSUE THREAD

**Issue by isentropic** [awesomeWM/awesome#3165]
How to achieve simple vertical 1 column tiling with equal vertical size? I have a second monitor placed in portrait, and I want to just have terminals go in 1xN column layout there. I couldnt decrease number of columns to 1 in fairterm or hfair.

[cross post](https://www.reddit.com/r/awesomewm/comments/io42o2/simplest_vertical_tiling/)

**Comment by actionless** [comment]
you could reduce `nmaster` to 0 on normal `tile` layout or indeed use a custom layout as suggeste don reddit
