### ISSUE TITLE
modeline being ignored

### ISSUE THREAD

**Issue by unai-ndz** [awesomeWM/awesome#3166]
Output of `awesome --version`:

awesome v4.3-862-g7a759432d-dirty (Too long)
 • Compiled against Lua 5.1.4 (running with LuaJIT 2.0.5)
 • API level: 4
 • D-Bus support: yes
 • xcb-errors support: yes
 • execinfo support: yes
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
 • Transparency enabled: yes
 • Custom search paths: no

**How to reproduce the issue:**

Change (or add) the modeline on top of rc.lua like:
```lua
-- awesome_mode: api-level=6:screen=on
```

**Actual result:**

No changes;
`awesome.api_level` returns `4`.
`screen=off` does not seams to have an effect either.

**Expected result:**

`awesome.api_level` returns `6`.

Starting awesome like: `awesome --api-level 6 --force` works as expected.

**Comment by psychon** [comment]
Well... cannot reproduce. I used the following patch:
```diff
diff --git a/awesomerc.lua b/awesomerc.lua
index 411377ded..15ff8690a 100644
--- a/awesomerc.lua
+++ b/awesomerc.lua
@@ -1,8 +1,10 @@
--- awesome_mode: api-level=4:screen=on
+-- awesome_mode: api-level=6:screen=on
 -- If LuaRocks is installed, make sure that packages installed through it are
 -- found (e.g. lgi). If LuaRocks is not installed, do nothing.
 pcall(require, "luarocks.loader")
 
+print(awesome.api_level)
+
 -- @DOC_REQUIRE_SECTION@
 -- Standard awesome library
 local gears = require("gears")
diff --git a/tests/run.sh b/tests/run.sh
index ec4395c6a..eb8dab98f 100755
--- a/tests/run.sh
+++ b/tests/run.sh
@@ -115,7 +115,7 @@ fi
 # shellcheck disable=SC2206
 awesome_options=($AWESOME_OPTIONS $manual_screens --search lib --search "$this_dir")
 
-awesome_options+=(--screen off --force)
+#awesome_options+=(--screen off --force)
 
 # Cleanup on errors / aborting.
 cleanup() {
```
Afterwards, `tests/run.sh /dev/null` told me "6".

What arguments do you give to awesome (what does `ps aux | grep awesome` say)?

> Change (or add) the modeline on top of rc.lua like:

This is dangerous. At first I did "add". That left the original modeline in the second line of the file. The C code parses both and ended up with the following modeline-turned-into-command-line-arguments:
```
modeline: --api-level
modeline: 6
modeline: --screen
modeline: on
modeline: --api-level
modeline: 4
modeline: --screen
modeline: on
```
The end result was that the api level still ended up as 4. Removing the second modeline fixed that.

**Comment by unai-ndz** [comment]
Tried building with your patch, running the tests and I could not reproduce either.

But on the running system does not work.

> What arguments do you give to awesome (what does `ps aux | grep awesome` say)?

No arguments, just `awesome`.

In case is useful I'm using `lightdm` to start the window manager and change the arguments by editing `/usr/share/xsessions/awesome.desktop`.

Then again checking with `ps` does not return any argument so I don't know what could be happening.

> Change (or add) the modeline

Sorry, this was meant as "add it if you don't have it yet". Is a recent addition after all.

**Comment by psychon** [comment]
Could you try running with a `--config path/to/config` argument (e.g. in Xephyr)?

It seems that `luaA_find_config` is used to figure out where to find the config file if no path was explicitly given. However, this function is not used for the option parsing. From a quick reading of the source code, it might be that `fopen(NULL, "r")` ends up being called when no config file path was explicitly given (which I guess is even allowed to segfault...?). This then fails and thus no modelines is searched.

**Comment by psychon** [comment]
I just tried that with my own config. I prepended this to my config:
```
-- awesome_mode: api-level=6:screen=on
print(awesome.api_level)
```
Running `awesome` prints 4, running `awesome -c ~/.config/awesome/rc.lua` prints 6. So I guess my guess above is correct.
