### ISSUE TITLE
screen.tiled_clients does not consider c.maximized

### ISSUE THREAD

**Issue by ArtemSmaznov** [awesomeWM/awesome#3169]
Output of `awesome --version`:
```
awesome v4.3-862-g7a759432d-dirty (Too long)
 • Compiled against Lua 5.3.5 (running with Lua 5.3)
 • API level: 4
 • D-Bus support: yes
 • xcb-errors support: no
 • execinfo support: yes
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
 • Transparency enabled: yes
 • Custom search paths: no
```
**How to reproduce the issue:**

1. Have 2 clients opens on the focused tag
1. Make one client maximized via `c.maximized = true`
1. Make a notification to print `awful.screen.focused().focused.tiled_clients`

**Actual result:**

Output is `2`

**Expected result:**

Output is `1`

**Comments**
Reviewing function `function screen.object.get_tiled_clients` in `screen.lua` it only accounts for `c.floating`, `c.fullscreen`, `c.maximized_vertical` and `c.maximized_horizontal` but not for `c.maximized`. Is there a specific reason for it?

I have noticed it when reviewing my rules for showing the title bar for clients and now I have set my maximize function to not only toggle `c.maximized` but also to set `c.maximized_horizontal` and `c.maximized_vertical` to be set to new `c.maximized` value which is a bit ugly but still functional.

Just trying to figure out if that is an oversight or intentional for some reason.

**Comment by psychon** [comment]
CC @Elv13 since you added the new maximized state and I do not understand how `maximized` is supposed to interact with the two other maximisation properties.

**Comment by actionless** [comment]
IMO it shouldn't consider it, since as soon as client became maximixed it's not participating anymore in tiling layout spliting of the screen area

**Comment by Elv13** [comment]
> I do not understand how maximized is supposed to interact with the two other maximisation properties.

The point of adding it was pretty much to avoid having an interaction. This was to fix the "bug" where an user with a partially maximized client would toggle full maximization (which was implemented as setting both vertical and horizontal to true), undo it and then get a different state than they started with (no maximization instead of partial maximization).

Anyway, real bug. I will fix it when I get time
