### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by F4zii** [awesomeWM/awesome#3177]
**Output of `awesome --version`:**

Not installed

**How to reproduce the issue:**

Follow the install instructions for arch linux based

**Actual result:**

```
[ 88%] Generating doc/images/AUTOGEN_awful_mouse_coords.svg, /home/iddos/.config/awesome/awesome-git/src/awesome-git/tests/examples/awful/mouse/coords.output.txt
[ 88%] Built target generate-examples
make: *** [Makefile:149: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
==> Removing installed dependencies...```
```
**Expected result:**

AwesomeWM being installed.

**Comment by psychon** [comment]
Could you show the full output of the build log? Your snippet is missing the actual error message.

Also, since you are mentioning Arch Linux: Could this be a duplicate of #3168?

**Comment by F4zii** [comment]
Hey, I managed to fix it, thanks for responding anyways, have a good day
