### ISSUE TITLE
Dual monitor fullscreen YouTube: Esc exits both instead of just 1

### ISSUE THREAD

**Issue by Jonta** [awesomeWM/awesome#3181]
Output of `awesome --version`:

awesome v4.3 (Too long)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2

**How to reproduce the issue:**

- Dual-monitor setup with xrandr, one main, the other extending it (not duplicated)
- 2 Firefox windows open, one on each monitor
- Floating layout on both
- YouTube-video open in both. Fullscreened with YouTube's fullscreen function
- Cursor in one monitor
- Hit Esc-key

**Actual result:**

Exits fullscreen in both videos

**Expected result:**

Only exits fullscreen in video that was active (had cursor, could therefore control volume with up/down-keys)

**Comment by Elv13** [comment]
Firefox windows are not "really" different process. They are 2 windows owned by the same "instance deamon". So they actually know about each other input and do what they want with it. Also, with X11, keylogging is a "feature", so unless you add some X11 sandboxing, then Awesome cannot help you.

To mitigate your issue, run different Firefox sessions or run different sessions in resizable Xephyr window (or even VMs). That way they will have much harder time talking to each other.

There's nothing to do from Awesome point of view.
