### ISSUE TITLE
Question: How to simulate multiple monitors for debugging purposes?

### ISSUE THREAD

**Issue by elenapan** [awesomeWM/awesome#3188]
Hey guys,

I would like to debug my configuration as if it was running with multiple monitors, however my only machine right now has a broken HDMI port and thus I am unable to do so.

I have tried the following with `Xephyr` to simulate a multiple-monitor setup:

```shell
Xephyr -screen 640x480 -screen 640x480 +xinerama :1 &
DISPLAY=:1 awesome
```

Which worked, to an extent. Awesome runs as expected on one Xephyr monitor, plus I can drag windows towards the second one. But the second one is completely black, and has no wallpaper or bar.

Here is a screenshot:
![image](https://user-images.githubusercontent.com/31134749/94351492-ada48480-0061-11eb-8e14-f61d7212c43f.png)

Also, running this only prints one line instead of 2 as I would expect:
```lua
for s in screen do
    print("hello from screen "..tostring(s))
end

-- Only prints:
-- "hello from screen screen: 0x560e5a52a7b8"
```

I used the default configuration for this test.

```
awesome v4.3-881-gca29aa191-dirty (Too long)
 • Compiled against Lua 5.3.5 (running with Lua 5.3)
 • API level: 4
 • D-Bus support: yes
 • xcb-errors support: no
 • execinfo support: yes
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
 • Transparency enabled: yes
 • Custom search paths: no
```

Could anyone share their experience and tips in order to make this work, or suggest other ways in order to simulate such a setup?
Thank you in advance.

**Comment by psychon** [comment]
The problem with `Xephyr -screen 640x480 -screen 640x480 +xinerama :1` is that the X11 server only announces the second output with Xinerama, but not with RandR:
```
$ xdpyinfo -ext XINERAMA | tail -n 3
XINERAMA version 1.1 opcode: 138
  head #0: 640x480 @ 0,0
  head #1: 640x480 @ 640,0
$ xrandr 
xrandr: Failed to get size of gamma for output default
Screen 0: minimum 160 x 160, current 1280 x 480, maximum 1600 x 1200
default connected 640x480+0+0 (normal left inverted right x axis y axis) 0mm x 0mm
   1600x1200      0.00  
   1400x1050      0.00  
   1280x960       0.00  
   1280x1024      0.00  
   1152x864       0.00  
   1024x768       0.00  
   832x624        0.00  
   800x600        0.00  
   720x400        0.00  
   480x640        0.00  
   640x480        0.00* 
   640x400        0.00  
   320x240        0.00  
   240x320        0.00  
   160x160        0.00  
```
You can add the second screen via some Lua code:
```
$ awesome-client 'screen.fake_add(640, 0, 640, 480)'
```
Oh, another idea is to use xrandr to add a new monitor:
```
$ xrandr --setmonitor foo 640/169x480/127+640+0 none
xrandr: Failed to get size of gamma for output default
$ xrandr --listmonitors                             
xrandr: Failed to get size of gamma for output default
Monitors: 2
 0: foo 640/169x480/127+640+0 
 1: +default 640/169x480/127+0+0  default
```
However, this does not work. This lists `none` as the output for the new monitor, but the C code seems to ignore all monitors without outputs....?

Also, when I click in the second output, the X11 server seems to send those click on the first output instead, so this is quite broken anyway, even when awesome would see the second output.

**Comment by Elv13** [comment]
I suggest trying `screen:split()`. It has the nice side effect of testing hot-plugging screens. The whole `fake_resize()` and `fake_add()` also allow to test various scenarios Xephyr multi-screen has an hard time dealing with. You can use Xephyr multi-screen and `fake_resize()`/`fake_add()` to "fix" the problem.

**Comment by elenapan** [comment]
Thank you both, that was very helpful!
