### ISSUE TITLE
How to change the cursor theme?

### ISSUE THREAD

**Issue by jacksun1237** [awesomeWM/awesome#3189]
Output of `awesome --version`:

_REPLACE with full version output_

**How to reproduce the issue:**

_REPLACE with step-by-step instructions on what to do_

**Actual result:**

_REPLACE with what happened_

**Expected result:**

_REPLACE with what should happen_

**Comment by actionless** [comment]
https://github.com/awesomeWM/awesome/issues/2860

**Comment by jacksun1237** [comment]
Thanks
