### ISSUE TITLE
Homogeneous Grid layout with Expanding icons

### ISSUE THREAD

**Issue by ArtemSmaznov** [awesomeWM/awesome#3198]
I am not 100% sure this is a bug or if I am simply using the layout wrong.

I am trying to make a grid of icons that is independent of the parent widget dimensions (i.e. will be displaying icons of the same sizes on different screens as that dictates the width of the parent widget).

Grid layout having `expand` and `homogeneous` options makes me believe that the layout should dictate the available space for the child widgets rather than the other way around. But when I try to use it the expanding image boxes just take the space of the whole layouts parent instead of just the width of one column.

I don't what to use forced width and height on the child image boxes as I don't know what are the dimensions of the parent widget as it is dependant on the monitor dimensions and the grid layout options seem to indicate that this should be possible to achieve.

**Output of `awesome --version`:**
```
awesome v4.3-862-g7a759432d-dirty (Too long)
 • Compiled against Lua 5.3.5 (running with Lua 5.3)
 • API level: 4
 • D-Bus support: yes
 • xcb-errors support: no
 • execinfo support: yes
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
 • Transparency enabled: yes
 • Custom search paths: no
 ```

**How to reproduce the issue:**

```
local icon = wibox.widget {
  image = icons.other.distributor_logo,
  expand = true,
  widget = wibox.widget.imagebox
}

local grid = wibox.widget {
  icon,
  icon,
  icon,
  icon,
  forced_num_cols = 3,
  spacing       = 5,
  expand_horizontal = true,
  homogeneous = true,
  layout = wibox.layout.grid
}

return wibox.widget {
  grid,
  bg = beautiful.groups_bg,
  shape = function(cr, width, height)
    gears.shape.partially_rounded_rect(cr, width, height, false, false, false, false, beautiful.groups_radius) 
  end,
  widget = wibox.container.background
}
```

**Actual result:**
First element of each row fills the whole space and the remaining elements are 0 or 1 pixels in size making them not display at all

![2020-10-10_15:01:42](https://user-images.githubusercontent.com/31800376/95657118-aa51d400-0b0a-11eb-8b8d-59c111f5efc2.png)

**Expected result:**

![2020-10-10_15:01:21](https://user-images.githubusercontent.com/31800376/95657126-ad4cc480-0b0a-11eb-8e96-f15bc93c6023.png)

**Comment by psychon** [comment]
Some random experiments say that your `expand_horizontal = true,` does not work. The correct `horizontal_expand = true` does not work either. Whoever wrote this never tested that part of the code.
You can hack around it with `expand_horizontal = true,`.

The correct fix seems to be the following. Please take a moment to appreciate just how broken that code currently is.
```diff
diff --git a/lib/wibox/layout/grid.lua b/lib/wibox/layout/grid.lua
index f04c5437d..44104a7d4 100644
--- a/lib/wibox/layout/grid.lua
+++ b/lib/wibox/layout/grid.lua
@@ -692,7 +692,7 @@ end
 -- getting the common property returns the directional property
 -- defined by the `orientation` property
 for _, prop in ipairs(dir_properties) do
-    for _,dir in ipairs{"horizontal_, vertical_"} do
+    for _,dir in ipairs{"horizontal", "vertical"} do
         local dir_prop = dir .. "_" .. prop
         grid["set_"..dir_prop] = function(self, value)
             if self._private[dir_prop] ~= value then
```

**Comment by ArtemSmaznov** [comment]
Thanks

My understanding is that it was tested to adapt to children that are smaller than the parent but using expanding image as a child was an untested edge case.

I will give the workaround a go as I was breaking my head trying to get anything to work.

**Comment by ArtemSmaznov** [comment]
I've tried adding:
```
grid._private.expand_horizontal = true
```
assuming `grid` refers to my widget but the result is the same. I also tried removing `_` like in your commit but that didn't do anything either. Did I misunderstand your suggestion or is there more work that is needed?

**Comment by psychon** [comment]
Well... Seems like I got the order wrong again. It is `horizontal_expand`.

Just to be clear: This code:
```lua
local icon = wibox.widget {
  image = beautiful.awesome_icon,
  expand = true,
  widget = wibox.widget.imagebox
}

local grid = wibox.widget {
  icon,
  icon,
  icon,
  icon,
  forced_num_cols = 3,
  spacing       = 5,
  horizontal_expand = true,
  homogeneous = true,
  layout = wibox.layout.grid
}

local wi = wibox.widget {
  grid,
  bg = beautiful.groups_bg,
  shape = function(cr, width, height)
    gears.shape.partially_rounded_rect(cr, width, height, false, false, false, false, beautiful.groups_radius)
  end,
  widget = wibox.container.background
}
local w = wibox{ x = 30, y = 30, width = 300, height = 300, visible = true, widget = wi }
```
produces this (ugly) result: 
![foo](https://user-images.githubusercontent.com/89482/95660617-51ddff00-0b29-11eb-81fc-43c5459b10a3.png)
Adding this line to the end of the above code produces the following image:
```lua
grid._private.horizontal_expand = true
```
![foo2](https://user-images.githubusercontent.com/89482/95660659-99648b00-0b29-11eb-9a70-be51c9222b4f.png)
Sorry for getting the name wrong before.

**Comment by ArtemSmaznov** [comment]
Damn that order is so easy to get wrong :D

That one worked better.

I know that this still needs a lot of work but would like to mention another thing in case you didn't see it - still seems like there is vertical expand added like this:
![2020-10-10_18:05:37](https://user-images.githubusercontent.com/31800376/95660963-4a1b5c00-0b23-11eb-8fa3-29a65eb26964.png)

Same result even if I set vertical expand to false explicitly:
```
local grid = wibox.widget {
  icon,
  icon,
  icon,
  icon,
  forced_num_cols = 3,
  spacing       = 5,
  expand_vertical = false,
  vertical_expand = false,
  horizontal_homogeneous = true,
  layout = wibox.layout.grid
}

grid._private.horizontal_expand = true
grid._private.vertical_expand = false
```
