### ISSUE TITLE
Spawn terminal as a slave 

### ISSUE THREAD

**Issue by strogiyotec** [awesomeWM/awesome#3202]
Good day, I am  quite new to tilling window managers , so I hope for your support. The problem is , when I spawn my terminal , it became a new master, let's say I have a firefox opened, when I spawn terminal I expect my main window to split into to equal size windows (I am using tile layout), but instead terminal appear on top of firefox and now my tag has two tabs one with browser and another one with terminal . How can I fix it ? P.S I found this comment in my rc.lua 
```
    -- Set the windows at the slave,
    -- i.e. put it at the end of others instead of setting it master.
    -- if not awesome.startup then awful.client.setslave(c) end
```
So I uncommented condition and expect new windows to become slaves , but it doesn't work 

Output of `awesome --version`:
awesome v4.3 (Too long)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
_REPLACE with full version output_

**How to reproduce the issue:**
Here is my config to spawn terminal
```
-- Standard program
        awful.key({ modkey, "Mod1" }, "t", function()
            awful.spawn(terminal)
        end,
                { description = "open a terminal", group = "client" }),
```

**Expected result:**
New terminal has to become slave instead of master 
_REPLACE with what should happen_

Please let me know if you need an additional info . Regards

**Comment by actionless** [comment]
i can't understand, do you want this behavior a) only for the terminal, b) only for the terminal started from specific hotkey, c) for any new window and you used terminal just as an example

**Comment by strogiyotec** [comment]
@actionless well I want it to work for terminal

**Comment by actionless** [comment]
in that case create a rule for your terminal:

https://awesomewm.org/doc/api/libraries/awful.rules.html

and add `callback = awful.client.setslave`
