### ISSUE TITLE
Rofi will not loaded via awful.spawn or _G.awesome.spawn

### ISSUE THREAD

**Issue by SquirrelSenpai** [awesomeWM/awesome#3203]
Output of `awesome --version`:

awesome v4.3-894-gcc67a5b40-dirty (Too long)
 • Compiled against Lua 5.3.6 (running with Lua 5.3)
 • API level: 4
 • D-Bus support: yes
 • xcb-errors support: no
 • execinfo support: yes
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
 • Transparency enabled: yes
 • Custom search paths: no

**How to reproduce the issue:**

Trigger rofi via 
`function () awful.spawn('rofi -show drun -theme config') end` or 
`function () _G.awesome.spawn('rofi -show drun -theme config') end`

**Actual result:**

The processing wheel appears on screen

**Expected result:**

Rofi menu should appear, as it does when triggered via shell

**Comment by gregflynn** [comment]
have you checked `$HOME/.xsession-errors` for anything strange? Maybe a pathing issue finding rofi?

all my rofi calls use `awful.spawn`: https://github.com/gregflynn/dotsanity/blob/master/modules/awesome/sanity/util/rofi.lua

**Comment by SquirrelSenpai** [comment]
> have you checked `$HOME/.xsession-errors` for anything strange? Maybe a pathing issue finding rofi?
> 
> all my rofi calls use `awful.spawn`: https://github.com/gregflynn/dotsanity/blob/master/modules/awesome/sanity/util/rofi.lua

Could you post `awesome --version` please?  Thanks

PATH has /usr/bin which is what terminal uses.  Does AwesomeWM take information form elsewhere?

**Comment by gregflynn** [comment]
> > have you checked `$HOME/.xsession-errors` for anything strange? Maybe a pathing issue finding rofi?
> > all my rofi calls use `awful.spawn`: https://github.com/gregflynn/dotsanity/blob/master/modules/awesome/sanity/util/rofi.lua
> 
> No issues in .xsession-errors.
> 
> Could you post `awesome --version` please? Thanks
> 
> PATH has /usr/bin which is what terminal uses. Does AwesomeWM not use $PATH?

```
awesome v4.3 (Too long)
 • Compiled against Lua 5.3.5 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
```

probably not a PATH issue then, I would have expected some sort of `not found` error in `$HOME/.xsession-errors`

**Comment by SquirrelSenpai** [comment]
> > > have you checked `$HOME/.xsession-errors` for anything strange? Maybe a pathing issue finding rofi?
> > > all my rofi calls use `awful.spawn`: https://github.com/gregflynn/dotsanity/blob/master/modules/awesome/sanity/util/rofi.lua
> > 
> > 
> > No issues in .xsession-errors.
> > Could you post `awesome --version` please? Thanks
> > PATH has /usr/bin which is what terminal uses. Does AwesomeWM not use $PATH?
> 
> ```
> awesome v4.3 (Too long)
>  • Compiled against Lua 5.3.5 (running with Lua 5.3)
>  • D-Bus support: ✔
>  • execinfo support: ✔
>  • xcb-randr version: 1.6
>  • LGI version: 0.9.2
> ```
> 
> probably not a PATH issue then, I would have expected some sort of `not found` error in `$HOME/.xsession-errors`

Ah...  You are on stable.  Git release is 1.5 years in updates ahead of you, which might explain why you don’t see an error

**Comment by psychon** [comment]
Could you try the one of the following options? First one would be for your config while the second one can be run in a terminal. This shows errors instead of just ignoring them.
```
function () naughty.notify{ text = tostring(awful.spawn('rofi -show drun -theme config'))} end
```
```
$ awesome-client 'return require("awful.spawn")("rofi -show drun -theme config")'
```
Also, I'd be interested what happens when you run these in a terminal:
- `which rofi`
- `tr '\0' '\n' < /proc/$(pidof awesome)/environ | grep PATH`

**Comment by SquirrelSenpai** [comment]
> Could you try the one of the following options? First one would be for your config while the second one can be run in a terminal. This shows errors instead of just ignoring them.
> 
> ```
> function () naughty.notify{ text = tostring(awful.spawn('rofi -show drun -theme config'))} end
> ```
> 
> ```
> $ awesome-client 'return require("awful.spawn")("rofi -show drun -theme config")'
> ```
> 
> Also, I'd be interested what happens when you run these in a terminal:
> 
> * `which rofi`
> * `tr '\0' '\n' < /proc/$(pidof awesome)/environ | grep PATH`

I added 

```
local test =  function () 
	naughty.notify{ text = tostring(awful.spawn('rofi -show drun -theme config'))
	} 
end
```
![image](https://user-images.githubusercontent.com/62501353/97213179-3590c200-17b9-11eb-8cf4-476a8e0031d2.png)

![image](https://user-images.githubusercontent.com/62501353/97212319-22312700-17b8-11eb-9da6-ddef15ca21e9.png)

**Comment by psychon** [comment]
Okay, so rofi manages to start correctly. `double 50919` means that a program with PID 50919 was started. So, all the guesses at what could be wrong so far were, well, wrong. I also guess that means we need to figure out what kind of error messages it produces (if any).

The way that you start it now rofi should inherit awesome's stdout and stderr. That is sent... somewhere and to different places in different Linux distros. Since you say that `~/.xsession-errors` is not the right place, let's try this:
```lua
awful.spawn.easy_async("rofi -show drun -theme config", function(stdout, stderr, reason, exit_code)
    local message = string.format("stdout: %s\nstderr: %s\nreason: %s\ncode: %s\n", stdout, stderr, reason, exit_code)
    naughty.notification { message = message }
end)
```

**Comment by SquirrelSenpai** [comment]
Found the error - Failed to set a locale 
Why would rofi triggered via awesome fail and but trigger via terminal succeed?

**Comment by psychon** [comment]
I would suggest to compare the output of `tr '\0' '\n' < /proc/$(pidof awesome)/environ | grep PATH` with `env` in a terminal. Perhaps you set something like `LC_ALL` or `LANG` in your `.bashrc` and that's not set in AwesomeWM?

**Comment by SquirrelSenpai** [comment]
> I would suggest to compare the output of `tr '\0' '\n' < /proc/$(pidof awesome)/environ | grep PATH` with `env` in a terminal. Perhaps you set something like `LC_ALL` or `LANG` in your `.bashrc` and that's not set in AwesomeWM?

Turns out en_US.utf8 wasn't generated via locale-gen, resulting in the error message, when rofi launched via awesomewm.  Still curious but I will chalk it upto an edge case.
