### ISSUE TITLE
Question : Ho to use wibox.widget.calendar

### ISSUE THREAD

**Issue by deb75** [awesomeWM/awesome#3207]
Hello,

I would like to use `wibox.widget.calendar` but. how do you attach it to another wibox like the example with `awful.widget.calendar_popup.month` ?
```
local mytextclock = wibox.widget.textclock()
local month_calendar = awful.widget.calendar_popup.month()
month_calendar:attach( mytextclock, "tr" )
```

**Comment by actionless** [comment]
you can attach only popup
