### ISSUE TITLE
Edge snapping: ignore floating windows?

### ISSUE THREAD

**Issue by mxmilkiib** [awesomeWM/awesome#3209]
I'm dragging the Firefox Picture-in-Picture window to the edge of the screen, but when it snaps into the corner, it starts to act like a tiled window, pushing the main browser window downward

![image](https://user-images.githubusercontent.com/108225/98492908-238b3680-2231-11eb-8be8-06664c1599fd.png)

Might there be a way to avoid this?

**Comment by psychon** [comment]
If you set `dockable = false` on the client, "all of this" goes away. If you still want the snap-to-edge behaviour... I am actually not sure which parts of the code do what, sorry. @Elv13 any ideas?

**Comment by mxmilkiib** [comment]
I rewrote that issue but still got it wrong; yeah, I'd like to keep the edge snapping with a floating window but cut out the.. reflow popping.. thing.

**Comment by psychon** [comment]
>  but cut out the.. reflow popping.. thing.

Those are struts. They can be set with `c:struts{ left = 42, right = 15, top = 5, bottom = 3 }`. They come from EWMH's `_NET_WM_STRUT_PARTIAL` and they allow task lists that run as extra programs to reserve some space on the edge of the screen. When a dockable and floating client comes near the edge of the screen, `awful.mouse.snap` will set e.g. the `left` struts value to the width of the client (if it should dock to the left side of the screen).

One ugly way (completely untested - this is just to give the idea) to get rid of that would be to do something like the following (the `if` is necessary to avoid endless recursion):
```lua
client.connect_signal("property::struts", function(c)
  local struts = c:struts()
  if struts.left ~= 0 or struts.right ~= 0 or struts.top ~= 0 or struts.bottom ~= 0 then
    c:struts({ left = 0, right = 0, top = 0, bottom = 0 })
  end
end)
```

**Comment by mxmilkiib** [comment]
To get this right; so Awesome thinks the FF PiP window is of the type that acts as bar/dock/whatever when its top or bottom edge is inline with the top or bottom of the screen (where it is snapped into position) respectively, and thus sets a strut that pushes the top of Firefox to being below the bottom line of the PiP window? Checking now, and this doesn't happen with mpv, just the FF PiP window.

Thanks, I've just added that to my rc.lua and the PiP window doesn't push the main FF window down any more when the PiP window gets to a corner :)

**Comment by psychon** [comment]
> To get this right; 

Yup. :-)

> and this doesn't happen with mpv,

The default value for "dockable" is (this is the code from function `awful.client.object.get_dockable(c)`):
```lua
    -- Some sane defaults
    if value == nil then
        if (c.type == "utility" or c.type == "toolbar" or c.type == "dock") then
            value = true
        else
            value = false
        end
    end
```
So, if you want me to guess, your PiP window has type "utility".
