### ISSUE TITLE
Enable the GH wiki?

### ISSUE THREAD

**Issue by mxmilkiib** [awesomeWM/awesome#3210]
So that links to examples and snippets can be recorded by users.

**Comment by Elv13** [comment]
Hello,

You can submit a pull request to https://github.com/awesomeWM/awesome-www . We have a recipe section in there for links and you can make new pages.

Once upon a time, we had a MediaWiki, but it suffered from a mix of SPAM, vandalism and incorrect content. These day, we use awesome-www as a static wiki.

Also, if you think the content is generic enough for the main documentation, then it belongs there.

What do you wish to add?

**Comment by mxmilkiib** [comment]
Thanks but I avoid such knowledge base systems for the same reason that I see "static wiki" as being an oxymoron, i.e. a file+pull based system vs. the quicker mechanism that gave rise to the name "wiki". In my opinion/experience, that bottlenecked stop-start workflow hampers participation.

Editing a GH wiki requires not just a user account but a GH account, which I would say might well mitigate opportunities or desire to spam or vandalise, relative to a MediaWiki install.

I get the point about consolidating quality documentation, though I think there is still space for a wiki in this process, both as a place for content that isn't yet generic/good enough for the main documentation and as a place for "staging" snippets for direct peer betterment / Lua-golfing.

Looking at "recipes" atm, most snippets (that do more basic/atomic actions, like moving a window with focus following, as opposed to larger scripts) are in the "Others" section. I would posit that the the lack of smaller snippets featured on that page might reflect the off-putting nature of the process as it stands, and that helpful things just get siloed in closed issues and relatively small posts to be lost in the long-tail of timelines elsewhere, and that the network effect of putting the fuel right next to the heat to create the 'fire' is lost. Semi-proposal; there is the potential for the use of awesomeWM/awesome-www/wiki? Maybe even just, with disclaimer, as a space to collate links to things?

Exampes; if I ctrl-f "reddit" in my rc.lua, I'm already using;
- https://www.reddit.com/r/awesomewm/comments/gu4uek/how_to_move_client_to_nextprevious_tag
- https://www.reddit.com/r/awesomewm/comments/g2lzs3/how_to_cycle_through_tasklist_or_through_tags
- https://www.reddit.com/r/awesomewm/comments/ic7vqt/center_floating_windows_on_screen

There is also the corollary point; if a snippet gets good enough for documentation, then could it not be good enough for distributing with Awesome as code/config, be it as commented out by default, as part of a skeleton/template config file, or, if it is as simple as moving a window with focus following, etc., as part of the standard set of Awesome binds/actions available to the user?

**Comment by actionless** [comment]
IMO reddit is already good enough as such "staging environment" for prospering ideas/snippets/whatever else

**Comment by mxmilkiib** [comment]
> IMO reddit is already good enough as such "staging environment" for prospering ideas/snippets/whatever else

Then how many snippets/scripts have been collected from Reddit and promoted to being in the main documentation (aka 'recipes')?

If not as the primary discursive place where people back-and-forth about ideas, then it would at least make sense to use a wiki to at least keep track of notable solutions that appear on whatever site.

**Comment by actionless** [comment]
i apreciate your reasoning and motivation, however that way already proofed itself on practice less effective than the current

just as a side-note: if awesomewm community would be comparable in size to, let's say, arch linux community -- i could imagine wiki would be the same up-to-date, and amount of PR to static website would be too much to handle
