### ISSUE TITLE
Trouble building it from source on Ubuntu 20.04

### ISSUE THREAD

**Issue by rohit901** [awesomeWM/awesome#3212]
I'm trying to build this software from source and when I follow the instructions I'm getting this in the console output. 
Could anyone help me with this? I tried googling for the required package but it is not fixing the issue.

```
make package
Creating build directory and running cmake in it. You can also run CMake directly, if you want.

Running cmake…
-- The C compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- git -> /usr/bin/git
-- asciidoctor not found.
-- gzip -> /bin/gzip
-- ldoc -> /usr/bin/ldoc
-- convert -> /usr/bin/convert
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Found Lua: /usr/lib/x86_64-linux-gnu/liblua5.3.so;/usr/lib/x86_64-linux-gnu/libm.so (found version "5.3.3") 
-- Not generating manpages. Missing: 
-- Disabled.
-- Using version from git: v4.3-895-g538586c1
-- Checking for module 'xcb>=1.6'
--   Found xcb, version 1.14
-- Checking for modules 'glib-2.0;glib-2.0>=2.40;gdk-pixbuf-2.0;cairo;x11;xcb-cursor;xcb-randr;xcb-xtest;xcb-xinerama;xcb-shape;xcb-util;xcb-util>=0.3.8;xcb-keysyms;xcb-keysyms>=0.3.4;xcb-icccm;xcb-icccm>=0.3.8;xcb-xfixes;xcb-xkb;xkbcommon;xkbcommon-x11;cairo-xcb;libstartup-notification-1.0;libstartup-notification-1.0>=0.10;xproto;xproto>=7.0.15;libxdg-basedir;libxdg-basedir>=1.0.0;xcb-xrm'
--   No package 'xcb-xfixes' found
CMake Error at /usr/share/cmake-3.16/Modules/FindPkgConfig.cmake:463 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPkgConfig.cmake:643 (_pkg_check_modules_internal)
  awesomeConfig.cmake:156 (pkg_check_modules)
  CMakeLists.txt:33 (include)


-- Configuring incomplete, errors occurred!
See also "/home/rohit/awesome/build/CMakeFiles/CMakeOutput.log".
make: *** [Makefile:27: build/Makefile] Error 1
```

**Comment by actionless** [comment]
if the commands above (https://github.com/awesomeWM/awesome#debian-based) didn't helped

then please install all the listed build-depencies manually:

https://github.com/awesomeWM/awesome#build-dependencies


if some of the deps didn't installed by `apt build-dep`, then they're just not listed in `awesome` ubuntu package, so there is no other way as installing it manually

**Comment by rohit901** [comment]
> if the commands above (https://github.com/awesomeWM/awesome#debian-based) didn't helped
> 
> then please install all the listed build-depencies manually:
> 
> https://github.com/awesomeWM/awesome#build-dependencies
> 
> if some of the deps didn't installed by `apt build-dep`, then they're just not listed in `awesome` ubuntu package, so there is no other way as installing it manually

Thank you for the suggestion. I had libxcb-xfixes0 package installed but yet it was not working. Then I installed libxcb-xfixes0-dev package and tried it again, now it built perfectly.
