### ISSUE TITLE
Can't use a complex/composed custom widget in declarative style

### ISSUE THREAD

**Issue by sclu1034** [awesomeWM/awesome#3213]
Output of `awesome --version`:

```
awesome v4.3-895-g538586c17-dirty (Too long)
 • Compiled against Lua 5.3.6 (running with Lua 5.3)
 • API level: 4
 • D-Bus support: yes
 • xcb-errors support: yes
 • execinfo support: yes
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
 • Transparency enabled: yes
 • Custom search paths: no
```

**How to reproduce the issue:**

1. Create file `my_widget.lua`

```lua
local wibox  = require('wibox')
local gtable = require('gears.table')

local my_widget = {}

function my_widget:set_image(img)
	self:get_children_by_id("img")[1]:set_image(img)
end

local function new(img)
	local ret = wibox.widget.base.make_widget_declarative{
		{
			image = img,
			widget = wibox.widget.imagebox,
		},
		margins = { 1, 1, 1, 1 },
		widget = wibox.container.margin,
	}

	gtable.crush(ret, my_widget, true)

	return ret
end

return setmetatable(my_widget, { __call = function(_, ...) return new(...) end })
```

2. Create a `wibox`:

```lua
local my_widget = require('my_widget')
wibox({
	visible = true,
    x = 0,
	y = 0,
	width = 100,
	height = 100,
	bg = "#000000",
	widget = {
		image = "some/icon.png",
		widget = my_widget,
	},
})
```

_Edit: The snippets above are incomplete, here is a full test case: [Gist](https://gist.github.com/sclu1034/e6859b30b627822d60871e10fc33e129)._

**Actual result:**

An empty `wibox`. The custom widget is not drawn.

**Expected result:**

My icon filling the `wibox`. Or an error message stating that I can't use `my_widget` in this way.

It seems that it is not possible to use reusable, complex/composed widgets in declarative style.
If I change the widget definition in the `wibox` to `my_widget("some/icon.png")`, the icon will appear.
It also appears if I remove the wrapping `wibox.container.margin` from `my_widget`, making this just a thin wrapper around a single `wibox.widget.imagebox`.

Similarly, if `my_widget` is built in imperative style:

- Works: `ret = wibox.widget.imagebox(img)`
- Doesn't work: `ret = wibox.container.margin(wibox.widget.imagebox(img))`

It would at least expect to see an error that this specific use case is not supported, rather than just an empty widget. However, it would be quite useful, especially for libraries I presume, to be able to create reusable widgets (e.g. a button that combines `background`, `margin` & `image`) and users of that library can use it in whatever style they prefer.

**Comment by Elv13** [comment]
Composite widgets are supported. What is currently broken is:

```
self:get_children_by_id("img")[1]:set_image(img)
```

IDs across "instances" of a declarative tree currently don't "see" each other. There is plans to support that. Fixing that is really, really non-trivial. However I should publish a very large new set of feature in the next few days which will provide an alternative to do "what you really want" here. The trick is (and you can do that already) to turn this upside down and have the imagebox listen to "the source of the image" rather then something else finding the imagebox object and setting the image.

**Comment by sclu1034** [comment]
Does that actually apply here?

As far as I can tell, the `set_image` method is local to `my_widget`. It is called on the return value of `base.make_widget_declarative` and it's trying to access only its immediate child, which was defined in the same declarative tree. Additionally, adding a `print` to the method did verify that it is called with the expected value.

Also, the imperative definition for `my_widget` (`ret = wibox.container.margin(wibox.widget.imagebox(img))`) doesn't use that function at all, but doesn't work anyway.

Lastly, a default value in the declarative definition of `my_widget` won't show up either:

```lua
local ret = wibox.widget.base.make_widget_declarative{
	{
		image = img or "some/icon.png",
		widget = wibox.widget.imagebox,
	},
	margins = { 1, 1, 1, 1 },
	widget = wibox.container.margin,
}
```

**Comment by psychon** [comment]
Well, there are two parts of the problem here. The following never prints anything:
```lua
function my_widget:set_image(img)
        print("I was called")
	self:get_children_by_id("img")[1]:set_image(img)
end
```
The assignment to `image` does not call `set_image`, but instead just assigns an entry to the table's `image` key:
```lua
local w = wibox({
[snip - all the stuff from the original post]
print(w.widget.image)
```
```
some/icon.png
```
However, the setter has the problem that @Elv13 described. When doing this:
```lua
my_outer_widget().image = "foo"
```
the setter is called and I get an error about no widget being found: `attempt to index a nil value (field '?')`
This is easy to fix. To use `get_children_by_id`, you need to give the widget an id. This makes things work:
```lua
local function new(img)
	local ret = wibox.widget.base.make_widget_declarative{
		{
			image = img,
			widget = wibox.widget.imagebox,
			id = "img", -- This is new!
		},
		margins = { 1, 1, 1, 1 },
		widget = wibox.container.margin,
	}

	gtable.crush(ret, my_widget, true)

	return ret
end
```
So, the only remaining issue is the missing metatable magic. I am not quite sure what happens here, but I never understood the code. From a quick look `make_widget_declarative` and `drill`, I would expect this to work...

**Comment by sclu1034** [comment]
I did forget to include the `id = "img"` in my write-up. Here are my [test files (gist)](https://gist.github.com/sclu1034/e6859b30b627822d60871e10fc33e129), this time copied as-is.

However, unrelated to that, my output doesn't match yours. Adding your two `print`s in the above files, my output looks like this:

```
my_widget.set_image =   /tmp/icon.png
w.widget.image =        nil
```

**Comment by sclu1034** [comment]
This seems to fix the issue:

```patch
diff --git a/lib/wibox/widget/base.lua b/lib/wibox/widget/base.lua
index 904f5adc..7ca09f3f 100644
--- a/lib/wibox/widget/base.lua
+++ b/lib/wibox/widget/base.lua
@@ -556,7 +556,7 @@ local function drill(ids, content)
         end
     end
     -- Replace all children (if any) with the new ones.
-    if widgets then
+    if widgets and #widgets > 0 then
         l:set_children(widgets)
     end
     return l, id
```

Apparently this is the same issue that is mentioned in #1693, but since `parse_table` always returns a table, even if it's empty, the `nil` check didn't help.

**Comment by Aire-One** [comment]
@sclu1034 can we use `max` instead of `#widgets` here? According to my understanding it's supposed to be the amount of children widgets for the layout.

**Comment by sclu1034** [comment]
Ah, yes. I think it's necessary even, since `widgets` might be a sparse table that starts with `nil`.
