### ISSUE TITLE
How do i change the clock from 24 hour time to 12 hour time

### ISSUE THREAD

**Issue by CardboardTurtle** [awesomeWM/awesome#3220]
I looked in the documentation. it doesn't work. ive looked online. all search results are either about awesome 3.5, or windows 10. how do i change the 24 hour clock into a 12 hour one

info: awesome v4.3 (Too long)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2

**Comment by psychon** [comment]
The textclock uses this function from GLib: https://developer.gnome.org/glib/stable/glib-GDateTime.html#g-date-time-format

The call to `wibox.widget.textclock()` is equivalent to `wibox.widget.textclock(" %a %b %d, %H:%M ")`.

The docs for `g_date_time_format()` say that:
- %H: the hour as a decimal number using a 24-hour clock (range 00 to 23)
- %I: the hour as a decimal number using a 12-hour clock (range 01 to 12)

So I guess you want `wibox.widget.textclock(" %a %b %d, %I:%M ")`

**Comment by ShayAgros** [comment]
@psychon 
The [textclock widget site](https://awesomewm.org/doc/api/classes/wibox.widget.textclock.html) isn't the same as in this repository. A reference to the glib site in the documentation were [merged](https://github.com/awesomeWM/awesome/pull/2926) about a year ago.

How frequently is the site updated from the docs in the repo ?

**Comment by psychon** [comment]
@ShayAgros See https://awesomewm.org/doc/. The link above goes to the docs for the latest stable release. https://awesomewm.org/apidoc/widgets/wibox.widget.textclock.html contains the API docs for git/master.

> How frequently is the site updated from the docs in the repo?

The "stable" docs are updated after every release. Updating that is part of the release procedure. The git/master ones are updated after every commit (automatically via Travis CI).

**Comment by ShayAgros** [comment]
> Edit: I guess this issue should only be closed after the docs were improved.

ok, this is labeled as "good first issue". What is there to do here ?

**Comment by psychon** [comment]
From a quick look: Uhm, nothing. The docs were already improved before this issue was opened, but that did not end up in a release. Sorry for missing that.

Could someone else double-check this, please? Thanks.

**Comment by Aire-One** [comment]
> Could someone else double-check this, please? Thanks.

Yup, the new API documentation has been improved and it's waiting for a new version to be released to the stable documentation. 

I guess it still can be improved, tho... Maybe something with the same spirit the imagebox documentation (https://awesomewm.org/apidoc/widgets/wibox.widget.imagebox.html) was improved with https://github.com/awesomeWM/awesome/pull/2921. I should have updated more widgets with this  PR before it got merged...

**Comment by XeroOl** [comment]
I think it might be a good idea to have this as a comment in the default awesomerc.lua, so that a new user looking to change the clock could just switch which line is commented instead of looking through documentation
