### ISSUE TITLE
Is there a way use different layouts to cycle?

### ISSUE THREAD

**Issue by zdmgmail** [awesomeWM/awesome#3222]
Output of `awesome --version`:

```
awesome v4.3 (Too long)
 • Compiled against Lua 5.3.5 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
```

```
awful.layout.layouts = {
	awful.layout.suit.tile,
	awful.layout.suit.max,
}
awful.key({ modkey,   }, "i", function () awful.layout.inc( 1)                          end, {description = "select next layout",      group = "layout_switch"}),
```

I'm using this cycle layouts, but how can I have another layouts to cycle

if I use 

```
awful.layout.layouts2 = {
	awful.layout.suit.tile.left
	awful.layout.suit.max,
}
awful.key({ modkey,   }, "u", function () awful.layout.inc(1, "DP-1", awful.layout.layouts2)                          end, {description = "select next layout2",      group = "layout_switch"}),
```

mod+u still use the first layouts

if can't use two layouts, I try to use 

`awful.layout.set(awful.layout.suit.tile.left)`

but this will append **awful.layout.suit.tile.left** to the first layouts, not I want to do

**Comment by psychon** [comment]
> not I want to do

Sorry, but... what is it that you want to do?

You want `mod4 + i` to cycle between `tile` and `max` and `mod4 + u` to cycle between `tile.left` and `max`?

If you, I'd think that the following does that:
```lua
awful.layout.layouts2 = {
	awful.layout.suit.tile.left
	awful.layout.suit.max,
}
awful.key({ modkey,   }, "u", function () awful.layout.inc(1, nil, awful.layout.layouts2)      
```

**Comment by zdmgmail** [comment]
> ```lua
> awful.key({ modkey,   }, "u", function () awful.layout.inc(1, nil, awful.layout.layouts2)      
> ```

thanks, solved, I don't know inc  can use `nil`

**Comment by actionless** [comment]
you could also use screen number or screen object (returned by screen.primary() or other related func), just not the screen name

**Comment by psychon** [comment]
> thanks, solved, I don't know inc can use nil

When you do `awful.layout.inc(1)`, it calls the function with the extra arguments set to `nil`. Thus, as a general rule, it should be possible to also call the function with explicit `nil` arguments. (Same for other functions)
