### ISSUE TITLE
Menu border color and notification border width are ignored.

### ISSUE THREAD

**Issue by NightH4nter** [awesomeWM/awesome#3223]
Output of `awesome --version`:

awesome v4.3 (Too long)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2

**How to reproduce the issue:**

1. Use this [theme](https://github.com/funtaps/awesome-solarized) with this [theme.lua](https://gist.github.com/NightH4nter/f192cd473cacfad86064796c49c18f29).
2. Use this [rc.lua](https://gist.github.com/NightH4nter/2a7097906dc032f38644435b3d23e3c2).
3. Try changing menu border color and notification border width.

**Actual result:**
Nothing.

**Expected result:**
Menu border color and notification border color actually change, when changed in configs.

**Comment by psychon** [comment]
Uhm... no idea... What exactly do you mean with "Try changing menu border color and notification border width"? Which file are you changing in which way?

**Comment by NightH4nter** [comment]
In theme.lua. Try changing `theme.notification_border_width` and `theme.menu_border_color` to anything else and see if it works.

**Comment by psychon** [comment]
Since I still have no good idea: What happens when you add `error("This code really runs")` to the end of your `theme.lua`? This should break things, so [you best try this change with Xephyr](https://wiki.archlinux.org/index.php/awesome#Debugging_rc.lua). The idea here is "are you really modifying the `theme.lua` that is loaded?".

**Comment by NightH4nter** [comment]
Here is the thing: I provided you with my own theme.lua, because it is not the original file from theme's author. The file was modified by me, and every other change (well, at least, every change that I made) has taken effect. And, as expected, adding your line and restarting broke things.

**Comment by actionless** [comment]
@NightH4nter please limit the steps to reproduce your issue to the minimal amount as possible, ie in this case, use default rc.lua and one of default themes as a base, and provide the small diff with the particular lines which causing the problem

**Comment by NightH4nter** [comment]
First of all: the default theme you linked doesn't work. 
![image](https://user-images.githubusercontent.com/31319604/102016141-4c827800-3d57-11eb-81b3-1f7d9d7ad115.png)
Good luck investigating that. Hint: probably version is the issue here, I use the one from Debian Buster repos.
Second: here are the diffs you asked for, but generated against the files from AwesomeWM website:

```
~/.config/awesome % diff theme-def.lua theme-def-m.lua
60c60,61
<
---
> theme.notification_border_width = 10 --doesn't work
> theme.notification_border_color = "#2aa198" --just to make borders visible
67c68
<
---
> theme.menu_border_color = "#ffffff" --now works (idk why)
```

```
~/.config/awesome % diff rc-def.lua rc-def-m.lua
52,53c52,53
< beautiful.init(gears.filesystem.get_themes_dir() .. "default/theme.lua")
<
---
> -- beautiful.init(gears.filesystem.get_themes_dir() .. "default/theme.lua")
> beautiful.init(awful.util.getdir("config").."/theme-def-m.lua")
582c582
< -- }}}
\ No newline at end of file
---
> -- }}}
```
..., where -def files are the default ones, and -def-m are the ones I modified.

**Comment by actionless** [comment]
> First of all: the default theme you linked doesn't work

yes, it's for latest git version, you should find the appropriate files for it locally somewhere under /usr/share/awesome/themes (or smth like that depending on your particular package)

but anyway the diff you provided in the last message is already helpful to understand what's going on on your side

seems like a documentation issue:
`naughty` prioritize the settings from its config (https://awesomewm.org/doc/api/libraries/naughty.html#config.defaults)
so smth like this should work:

```lua
naughty.config.defaults.border_width = 20
```

**Comment by NightH4nter** [comment]
Well, I'm probably being completely dumb, but local themes and configs usually only exist to override the defaults, aren't they?

**Comment by Elv13** [comment]
> just to double-check, @Elv13, that's an expected behavior?

In git-master, it works better. The old notification code was surpisingly buggy. It only "worked" for most people because nobody configured and would use Dunst instead. The old `naughty.config` and preset systems are now mostly deprecated, but should still emulate the old behavior when it is sane.

**Comment by NightH4nter** [comment]
@actionless Yes, it works, thanks.
Also found out there was another line that changes menu border color, so I think problem solved.
