### ISSUE TITLE
Is there a way transparent with wallpaper in each layout?

### ISSUE THREAD

**Issue by zdmgmail** [awesomeWM/awesome#3224]
```
awesome v4.3 (Too long)
 • Compiled against Lua 5.3.5 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
```

I often use this layout : `awful.layout.suit.max`  , but don't want client transparent with other client, want each client transparent with wallpaper,  Is there a way to do this?

(I'm using picom or compton to give transparent, but seems not about those)

**Comment by unai-ndz** [comment]
If I understand you correctly you wanna start `picom` with the `--transparent-clipping` flag.

**Comment by zdmgmail** [comment]
> If I understand you correctly starting `picom` with the `--transparent-clipping` flag will archive what you want.

It works, thanks!
