### ISSUE TITLE
Implementing a "Click Away" signal for buttons in a popup

### ISSUE THREAD

**Issue by Ham5andw1ch** [awesomeWM/awesome#3227]
Output of `awesome --version`:

```
awesome v4.3 (Too long)
 • Compiled against Lua 5.3.5 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
```

**How to reproduce the issue/expected result:**

I am currently interfacing with the awesome pop-up API in order to make a context menu (I understand that there is already a library for this, but it did not suit my needs). When attaching signals to the pop-up wibox, I was not able to find a way to map a "click outside" signal in order to trigger the visibility (for reference, I am making a traditional right-click context menu for the tasklist that I want to be able to close by clicking away). 

There is obviously the naive solution which spins up a busy-wait with a while loop and waits for `mouse.is_left_mouse_button_pressed` to become true and checking if the mouse is currently on the pop-up, but I wanted to see if there was a more elegant approach with the callback system.

I also know there is something similar in the master branch that involves appending buttons to the global mapping, but if that is anything like the current `root` implementation of global buttons, that will not fit the bill as clicking on a client will not trigger the button click.

Sorry if this is something more out of the scope of the API and thanks in advance for any help.

**Comment by psychon** [comment]
I think you are looking for `mousegrabber`: https://awesomewm.org/doc/api/libraries/mousegrabber.html

**Comment by Ham5andw1ch** [comment]
That worked. Thank you so much.
