### ISSUE TITLE
Firefox thinks its size is smaller

### ISSUE THREAD

**Issue by seqizz** [awesomeWM/awesome#3230]
Hi there,

Sorry for a weird issue.

![2020-12-18_08-47](https://user-images.githubusercontent.com/307899/102589693-a6948c00-410f-11eb-83ad-bd6241ddb19b.png)

As you see in the image, sometimes Firefox is keeping bottom of its area empty on "max" layout. And it's not like the part of the page is not visible, it just thinks that's the available screen space (check the highlighted link's detail on bottom left).

It's happening when I boot the system docked (a.k.a. with 2 external monitors). Autorandr executes after awesome start since I have this in the config:

```
...
  local function autorandr ()
    awful.spawn({"autorandr", "-c"}, false)
  end
...
  screen.connect_signal("screen::change", function(s, state)
    autorandr(s)
  end)

```

Restarting awesome does not fix the issue. But if I:
- Change the layout to "tile" and open something else
- Force Firefox to float
- Make it fullscreen
- _.. or anything which forces Firefox to resize it's window_
It's correcting the problem permanently.

Output of `awesome --version`:
```
awesome 4.3 (Too long)
 • Compiled against Lua 5.2.4 (running with Lua 5.2)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: [string "return require('lgi.version')"]:1: module 'lgi.version' not found:
	no field package.preload['lgi.version']
	no file '/usr/share/lua/5.2/lgi/version.lua'
	no file '/usr/share/lua/5.2/lgi/version/init.lua'
	no file '/usr/lib/lua/5.2/lgi/version.lua'
	no file '/usr/lib/lua/5.2/lgi/version/init.lua'
	no file './lgi/version.lua'
	no file '/usr/lib/lua/5.2/lgi/version.so'
	no file '/usr/lib/lua/5.2/loadall.so'
	no file './lgi/version.so'
	no file '/usr/lib/lua/5.2/lgi.so'
	no file '/usr/lib/lua/5.2/loadall.so'
	no file './lgi.so'
```

**Comment by Aire-One** [comment]
This looks like the "Firefox remembers its last window geometries" bug.

Here are good explanations on the topic : https://github.com/awesomeWM/awesome/issues/2752#issuecomment-485612575. There are also some other issues on this topic here on github and over reddit.com/r/awesomewm (and probably many other forums)...

**Comment by seqizz** [comment]
Ah that looks suspiciously similar. Thanks @Aire-One
Since that one is still open, I'll close this one.
