### ISSUE TITLE
Libreoffice not respecting any other windows

### ISSUE THREAD

**Issue by antaxiom** [awesomeWM/awesome#3231]
Output of `awesome --version`:

awesome v4.3-897-g66b1780d8-dirty (Too long)
 • Compiled against Lua 5.3.6 (running with Lua 5.3)
 • API level: 4
 • D-Bus support: yes
 • xcb-errors support: no
 • execinfo support: yes
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
 • Transparency enabled: yes
 • Custom search paths: no

**How to reproduce the issue:**

- Open up the Libreoffice launcher or certain other Libreoffice tools (like writer) using either:
     - The command line
     - A runner like dmenu
     - The .desktop file using something like a wrapper for dmenu
- Notice that Libreoffice does not respect any other windows, it takes up the whole screen regardless off there being any other windows on top of it.
- The Libreoffice window is not floating, cannot be made to be floating and tiling other windows does not make it change shape
**Actual result:**

**Expected result:**

You open Libreoffice and the window scales with others as any other window should and be able to resize it or float it as needed

I am not sure if this is specifically awesome wm's fault for not support what's needed to make this window work as intended. If there's any rule I could add that could to fix this or at least mitigate it somewhat please inform me.

**Comment by psychon** [comment]
Could it be that LO is maximized or fullscreen? Could you provide the `xprop` output for its window? (Feel free to skip all the `_NET_WM_ICON` stuff, it takes a lot of space and provides little info.)

**Comment by antaxiom** [comment]
I'll check in a moment, but the way it acts is familiar to a full screen window (especially how other selected windows are on top of it), odd part is I can still fullscreen it.

Here's the xprop, tell me if there's any other info you need
```
WM_CLIENT_LEADER(WINDOW): window id # 0x4200001
_NET_WM_PID(CARDINAL) = 3076970
WM_LOCALE_NAME(STRING) = "en_US.UTF-8"
WM_CLIENT_MACHINE(STRING) = "quark"
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified location: 0, 0
		program specified minimum size: 383 by 853
		program specified base size: 383 by 815
		window gravity: Static
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, WM_TAKE_FOCUS, _NET_WM_PING, _NET_WM_SYNC_REQUEST
WM_CLASS(STRING) = "libreoffice", "libreoffice-startcenter"
WM_ICON_NAME(STRING) = "LibreOffice"
_NET_WM_ICON_NAME(UTF8_STRING) = "LibreOffice"
WM_NAME(STRING) = "LibreOffice"
_NET_WM_NAME(UTF8_STRING) = "LibreOffice"
```

**Comment by psychon** [comment]
Hm, okay, that guess was wrong.... However, that output still looks wrong. There is no `WM_STATE` property, which means that no window manager is managing that window. Could you also take a look via `xwininfo`? Specifically, it should say `Override Redirect State: no`.

**Comment by antaxiom** [comment]
Here's the output, it does say that

```
xwininfo: Window id: 0x4200024 "LibreOffice"

  Absolute upper-left X:  18
  Absolute upper-left Y:  80
  Relative upper-left X:  4
  Relative upper-left Y:  4
  Width: 3412
  Height: 1350
  Depth: 24
  Visual: 0x598
  Visual Class: TrueColor
  Border width: 0
  Class: InputOutput
  Colormap: 0x4200002 (not installed)
  Bit Gravity State: NorthWestGravity
  Window Gravity State: NorthWestGravity
  Backing Store State: NotUseful
  Save Under State: no
  Map State: IsViewable
  Override Redirect State: no
  Corners:  +18+80  -10+80  -10-10  +18-10
  -geometry 3412x1350-10-10```

**Comment by psychon** [comment]
Then I'm out of ideas and seriously confused, sorry...

**Comment by antaxiom** [comment]
It's ok, I hope someone elses picks this issue up.

**Comment by actionless** [comment]
try to maximize/unmaximize, put full screen on and off

some apps have some weird window hints on their first run, and aforementioned "tricks" usually helps to go them away permanently

**Comment by antaxiom** [comment]
Thanks so much!! I tried that and that did the trick, I didn't consider maximize being the problem but you're spot on. Since Libreoffice has a pain in the ass bug reporter I can't be bothered to make an issue with them but adding it to the default config could be good. Thanks loads. My new problem is I can't make a rule for it for it to come out not maximized (or at least I can't figure it out) and I also can't get borders on the window once I unmaximize (unless I make it float and back to tiling)

**Comment by actionless** [comment]
feel free filing a PR with the rule (which would be fixing the case without disturbing normal function of LO)

**Comment by antaxiom** [comment]
As I said earlier I can't figure out how to make the exact rule, I tried with the maximize property and such but I couldn't
