### ISSUE TITLE
Touchegg CHANGE_DESKTOP action support (_NET_CURRENT_DESKTOP)

### ISSUE THREAD

**Issue by F0xedb** [awesomeWM/awesome#3236]
Output of `awesome --version`:

```
awesome v4.3-897-g66b1780d8-dirty (Too long)
 • Compiled against Lua 5.3.6 (running with Lua 5.3)
 • API level: 4
 • D-Bus support: yes
 • xcb-errors support: yes
 • execinfo support: yes
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
 • Transparency enabled: yes
 • Custom search paths: no
```

**How to reproduce the issue:**

1. Install `touchegg` 
2. Add the following gesture in touchegg: `~/.config/touchegg/touchegg.conf`
```xml
<gesture type="SWIPE" fingers="4" direction="RIGHT">
  <action type="CHANGE_DESKTOP">
    <direction>previous</direction>
    <animate>true</animate>
    <animationPosition>left</animationPosition>
    <color>3E9FED</color>
    <borderColor>3E9FED</borderColor>
  </action>
</gesture>
```
3. start touchegg daemon: `systemctl start touchegg`
4. Run touchegg client: `touchegg`
5. Swipe with 4 fingers to the right on a touchpad

**Actual result:**

When doing so you are greater with an arrow pointing to the next tag indicating that touchegg wants to switch to that tag.
However nothing happens afterwards.
[Related to this touchegg issue](https://github.com/JoseExposito/touchegg/issues/418)

**Expected result:**

The tags don't get switched.
As far as I understand it, touchegg sends a `_NET_CURRENT_DESKTOP` client message to the root window with the updated value. However `awesomewm` doesn't update it.

The `_NET_CURRENT_DESKTOP` spec: https://specifications.freedesktop.org/wm-spec/wm-spec-1.3.html#idm45760170877056

**Comment by psychon** [comment]
A `_NET_CURRENT_DESKTOP` client message is handled something like by the C code (pseudo-lua-code):
```lua
local t = tag_that_the_message_is_sent_for();
t:emit_signal("request::select", "ewmh")
```
The rest is up to Lua code. `lib/awful/tag.lua` seems to handle this by calling `t:view_only()`, i.e. it always honors the request. Uhm...

Could you add this to your config and see if it works?
```lua
tag.connect_signal("request::select", function(t, context)
    naughty.notify{ text = "request to select " .. tostring(t.name) .. " with context .. tostring(context) }
    t:view_only() -- perhaps it helps?
end)
```
The relevant code in touchegg seems to be here: https://github.com/JoseExposito/touchegg/blob/1829640094b8dfeed15af45fdc2d5f49c488597e/src/window-system/x11.cpp#L546
It does the equivalent of running the shell command `xprop -root _NET_NUMBER_OF_DESKTOPS  ; xprop -root _NET_CURRENT_DESKTOP` and... uhm... the direction thingies cannot work since that depends on `_NET_DESKTOP_LAYOUT` which I do not know.

Another idea would be to run `xev -root` and then trigger touchegg. That show what `_NET_CURRENT_DESKTOP` message it sends.

**Comment by F0xedb** [comment]
Hello psychon,

I tried your advice and added the following snippet to my config as a quick test.
```lua
tag.connect_signal(
  "request::select",
  function(t, context)
    local msg = "request to select " .. tostring(t.name) .. " with context" .. tostring(context)
    naughty.notify {message = msg}
    print(msg)
    t:view_only()
  end
)
```


It appears to not be triggered at all (might be an issue on my end)
I also checked the xprop commands and `_NET_CURRENT_DESKTOP` seems to update when manually switching between tags, but it doesn't get updated when using touchegg (check using your xprop commands).

I quickly installed a `DE` and tested it there, it seems that touchegg is able to update `_NET_CURRENT_DESKTOP`

I'm not an experience c developer but the interesting part seems to be here:
https://github.com/JoseExposito/touchegg/blob/1829640094b8dfeed15af45fdc2d5f49c488597e/src/window-system/x11.cpp#L191

Which gets called from here: https://github.com/JoseExposito/touchegg/blob/1829640094b8dfeed15af45fdc2d5f49c488597e/src/window-system/x11.cpp#L585

Simplified c code of the last link:
```c
  toDesktop = currentDesktop + 1;
  this->sendEvent(rootWindow, rootWindow, "_NET_CURRENT_DESKTOP",
                  {static_cast<unsigned long>(toDesktop)});
```

Thanks for the quick reply!

**Comment by psychon** [comment]
With `xev -root` you should be able to see if that `sendEvent` even runs. I do not have anything to test this with, but it should say something about "ClientMessage events".

AwesomeWM does not do much validation of these events, so I do not really see why they would be "eaten"...

> I quickly installed a DE and tested it there, it seems that touchegg is able to update _NET_CURRENT_DESKTOP

Well, no. The WM itself updates `_NET_CURRENT_DESKTOP`. That's why it changes when you switch tags in AwesomeWM. There is a difference between the property and the ClientMessage of that name. X11 is complicated.

**Comment by F0xedb** [comment]
When running `xev -root` I get the following output:

```
CreateNotify event, serial 18, synthetic NO, window 0x6ab,
    parent 0x6ab, window 0x16001d6, (0,0), width 1920, height 1080
border_width 0, override YES

MapNotify event, serial 18, synthetic NO, window 0x6ab,
    event 0x6ab, window 0x16001d6, override YES

ClientMessage event, serial 18, synthetic YES, window 0x6ab,
    message_type 0x15a (_NET_CURRENT_DESKTOP), format 32

UnmapNotify event, serial 19, synthetic NO, window 0x6ab,
    event 0x6ab, window 0x16001d6, from_configure NO

DestroyNotify event, serial 19, synthetic NO, window 0x6ab,
    event 0x6ab, window 0x16001d6

PropertyNotify event, serial 19, synthetic NO, window 0x6ab,
    atom 0x159 (_NET_ACTIVE_WINDOW), time 379890, state PropertyNewValue

PropertyNotify event, serial 19, synthetic NO, window 0x6ab,
    atom 0x15a (_NET_CURRENT_DESKTOP), time 379890, state PropertyNewValue

PropertyNotify event, serial 19, synthetic NO, window 0x6ab,
    atom 0x15a (_NET_CURRENT_DESKTOP), time 379890, state PropertyNewValue

PropertyNotify event, serial 19, synthetic NO, window 0x6ab,
    atom 0x15a (_NET_CURRENT_DESKTOP), time 379890, state PropertyNewValue
```

It seems that the client event is found by `xev`

```
ClientMessage event, serial 18, synthetic YES, window 0x6ab,
    message_type 0x15a (_NET_CURRENT_DESKTOP), format 32
```

**Comment by psychon** [comment]
Thanks. Hm... that looks correct to me (but yay for `xev` not printing the whole `ClientMessage` :-( )

I'll try to experiment a bit.

**Comment by psychon** [comment]
ARGH. This code is broken since commit c5202a4870 (one year ago) and no one noticed.

I just found this on stderr:
```
2020-12-30 14:43:53 W: Trying to emit signal 'request::select' on non-object
stack traceback:
2020-12-30 14:43:53 W: awesome: a_glib_poll:454: Something was left on the Lua stack, this is a bug!
-------- Lua stack dump ---------
1: userdata	#48	0x55986c6baca8
------- Lua stack dump end ------
```
Thanks for pointing this out and sorry for being so slow in actually figuring this out. PR incoming.
