### ISSUE TITLE
Cursor teleleports to the edge of the screen on resizing client

### ISSUE THREAD

**Issue by figsoda** [awesomeWM/awesome#3240]
Output of `awesome --version`:
```
awesome 4.3 (Too long)
 • Compiled against Lua 5.2.4 (running with Lua 5.2)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: [string "return require('lgi.version')"]:1: module 'lgi.version' not found:
	no field package.preload['lgi.version']
	no file '/usr/share/lua/5.2/lgi/version.lua'
	no file '/usr/share/lua/5.2/lgi/version/init.lua'
	no file '/usr/lib/lua/5.2/lgi/version.lua'
	no file '/usr/lib/lua/5.2/lgi/version/init.lua'
	no file './lgi/version.lua'
	no file '/usr/lib/lua/5.2/lgi/version.so'
	no file '/usr/lib/lua/5.2/loadall.so'
	no file './lgi/version.so'
	no file '/usr/lib/lua/5.2/lgi.so'
	no file '/usr/lib/lua/5.2/loadall.so'
	no file './lgi.so'
```

**How to reproduce the issue:**

Bind `awful.mouse.client.resize` to a mouse button and try to resize any non-fullscreen window (`client`) with the binding.

**Actual result:**

Cursor teleports to the edge of the screen

**Expected result:**

Cursor teleports to the edge of the window (`client`)

** Additional notes:**

I have my pointer's transformation matrix changed to `1 0 0 0 1 0 0 0 0.3` in my `xorg.conf`

**Comment by psychon** [comment]
Could you experiment a bit with `awesome-client 'mouse.coords{ x=10, y=10 }'`? Can you move the mouse to the corners of the screen or the middle of the screen this way?

I would expect that this also does not work. However, this simply calls `xcb_warp_pointer()` aka "send a WarpPointer request to the X11 server". Everything that happens afterwards is a bug in Xorg (or one of its drivers).

**Comment by figsoda** [comment]
> `awesome-client 'mouse.coords{ x=10, y=10 }'`

The cursor moved to the top left corner.

**Comment by psychon** [comment]
What I meant: Can you experiment a bit with that and see if it works everywhere? E.g. you know the size of your screen. Can you move the cursor to the bottom right corner by setting the right numbers?

I am asking because this is the call that is used to move the cursor to the corner of a client for resizing.

**Comment by figsoda** [comment]
It does seem to be bugged. I just found out that moving to 10, 10 also teleports my cursor slightly. I am pretty sure it has something to do with my transformation matrix setting.

**Comment by psychon** [comment]
Then I fear that there is nothing we can do about this and you need to talk to someone from Xorg.

Seems like there are already reports about this. https://gitlab.freedesktop.org/xorg/xserver/-/issues/600 and https://gitlab.freedesktop.org/xorg/xserver/-/issues/633 sound related.

Upstream's position seems to be "don't do this":

> The short summary here would be: don't use the matrix for relative devices. It rarely makes sense to begin with and there are pitfalls as you discovered.
