### ISSUE TITLE
gears.string startswith/endswith, client.name and nil value

### ISSUE THREAD

**Issue by Grumph** [awesomeWM/awesome#3248]
awesome v4.3-895-g538586c17-dirty (Too long)
 • Compiled against Lua 5.3.6 (running with Lua 5.3)
 • API level: 4
 • D-Bus support: yes
 • xcb-errors support: yes
 • execinfo support: yes
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
 • Transparency enabled: yes
 • Custom search paths: no

**How to reproduce the issue:**

The issue appears when there is a client with no title (like a "save as" dialog).
```
local gstring = require("gears.string")
for  _, c in ipairs(client.get()) do
    if gstring.endswith(c.name, "anything") then
        (...)
    end
end
```

**Actual result:**

```
stack traceback:
        [C]: in function 'string.sub'
        /usr/share/awesome/lib/gears/string.lua:195: in function 'gears.string.endswith'
        (...)
        error: /usr/share/awesome/lib/gears/string.lua:195: bad argument #1 to 'sub' (string expected, got nil)
```

**Expected result:**

No error, just gstring.endswith to return false for the nameless client.

My custom function containing the code above worked for weeks and suddenly, of course when I was in a hurry for a task, it stopped working. 
I did not expect to have to check for client's name validity. One should not have to know the internals of awesome for such a simple code.

Either a client with no name should have a client.name value to an empty string,
or gears.string.*with functions should return false if the input str is nil.

I would go for the gears.string "protection", because nil can never start or end with something, so it should just return false. It's logical, and can't break existing code, so it's the safest fix for this particular case.

**Comment by psychon** [comment]
First reaction: No idea what is going on, but `c.name` really cannot be `nil`. It always returns a string, just as you suggest (this should be an empty string for clients without a name):
https://github.com/awesomeWM/awesome/blob/66b1780d85c5e2e2c7a5b0345b0f9cd84681b3a1/objects/client.c#L3582-L3587

Well... no... meh...
https://github.com/lua/lua/blob/825ac8eca8e384d6ad2538b5670088c31e08a9d7/lapi.c#L531-L534
I guess that piece of code in `client.c` needs a `NONULL` to actually do what I expect it to do.
