### ISSUE TITLE
Cannot resize floating window with touchpad

### ISSUE THREAD

**Issue by heppenowski** [awesomeWM/awesome#3250]
Output of `awesome --version`:

awesome v4.3 (Too long)
 • Compiled against Lua 5.3.5 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2

**How to reproduce the issue:**

Try to resize floating window with 2 finger click on  touchpad.

**Actual result:**

Cursor jumps to one of the closest corner and stay there

**Expected result:**

Ability to resize window with touchpad

**Comment by luis-barrera** [comment]
Do you have `clientsbuttons` defined in your `rc.lua`?

**Comment by nfm886** [comment]
W dniu pon, 1 lut 2021 o 09∶47 użytkownik luis-barrera 
<notifications@github.com> napisał:
> clientsbuttons

Actually no. How can I define it?

**Comment by luis-barrera** [comment]
Can you also resize with `modkey`+`right button mouse`?

**Comment by nfm886** [comment]
Yes. With mouse I can resize without any problems.

**Comment by Vaisakhkm2625** [comment]
Try fusuma, it can handle multi touch gestures.... map it to xtodotool

for resizing window with touchpad in default config, you can press superkey with left hand, press right corner of your touchpad with one finger.
then move another finger on touchpad. volla ... it's resizing

**Comment by Aire-One** [comment]
Hello @heppenowski,

It doesn't sound like an issue coming from Awesome, especially since you report it works with a mouse. To Awesome, the mouse is the same whenever it "comes" from a real mouse device or the touchpad.

The best we can do here is to recommend you to change your `clientbuttons` to something that is easier to perform with your touchpad. Or to use a software as recommended by @Vaisakhkm2625 (I personally never had the occasion to try such softwares).

**Comment by heppenowski** [comment]
Hi,
Simply awesome is not designed to be used with touchpad, probably like most of the tiling window managers.
Thanks for your advice. I don't own laptop anymore, now only PCmasterrace with AwesomeWMmasterrace :D so this issue should be closed, it's old anyway.

**Comment by actionless** [comment]
@LunarEclipse363 using the same workaround too when happen to use AwesomeWM on a laptop

**Comment by Aire-One** [comment]
If it's worth anything, I can do touchpad resizing with my laptop. I need to double tap with my finger kept down on the second tap. It's like tap then tap-and-slide.
