### ISSUE TITLE
mlterm window disappears while dragging to screen edges

### ISSUE THREAD

**Issue by vovan69** [awesomeWM/awesome#3256]
Output of `awesome --version`:
awesome v4.3 (Too long)
 • Compiled against Lua 5.1.5 (running with Lua 5.1)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2

**How to reproduce the issue:**
- Awesome is used with default configuration.
- Open [mlterm](http://mlterm.sourceforge.net/) in the floating layout and drag the window to the left or bottom of the screen.

**Actual result:**
- Red square is drаwn as expected, but and the mlterm window is gone

**Expected result:**
- Red square is drаwn and the mlterm window is resized accordingly.

EDIT: Forget to mention explicitly that dragging mlterm window to the top or right edge works as expected.

**Comment by psychon** [comment]
Cannot reproduce with mlterm from Debian Testing and awesome git/master:
```
$ mlterm --version
mlterm version 3.9.0 
Features: otl ssh implugin imagelib(builtin) utmp
```
I start mlterm, click its titlebar and drag it to the bottom of the screen. It snaps to the edge of the screen as expected (when I release the mouse; before releasing the mouse, the window doesn't change when the red indicator appears, as expected).

**Comment by vovan69** [comment]
Thanks for your reply! I'll compile and test the latest awesome version tomorrow.

**Comment by vovan69** [comment]
The same behavior with the latest awesome compiled form git/master.

**Comment by psychon** [comment]
Any specific mlterm config on your end? Does the problem also happen with awesome's default config (`rc.lua`)? Is there something in your reproducing steps that I could be doing wrong?

**Comment by vovan69** [comment]
Thanks for the tip about mlterm! I've reverted to the bundled/default mlterm config and the problem is gone. I think this issue can be closed. Sorry for the noise!

**Comment by psychon** [comment]
@vovan69 I'm curious what causes this. Do you know how to configure mlterm to cause this issue? An answer of "no" is totally fine with me. :-)

**Comment by vovan69** [comment]
@psychon I've been able to find out that the pseudo transparent background is causing this crash, so I'm contacting the developer of mlterm via the mailing list and hope that this interesting crash can be fixed.

**Comment by psychon** [comment]
Thanks. I can reproduce with `mlterm --transbg=true`. `mlterm` says:
```
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  2 (X_ChangeWindowAttributes)
  Serial number of failed request:  78729
  Current serial number in output stream:  78732
```
According to `xtrace`, the failing request is:
```
000:<:13389: 16: Request(2): ChangeWindowAttributes window=0x00a00004 value-list={background-pixmap=ParentRelative(0x00000001)}
```
This request fails because mlterm's window has depth 24, but AwesomeWM created a frame window with depth 32 (starting awesome with `--no-argb` makes it not do that).

I do not know why it changes its background like that. The window is created with a "proper" pixmap as its background pixmap and I can see it replacing that pixmap at times.

The last X11 events that it received before this are (sadly I did not capture timestamps):
```
000:>:022f: Event (generated) ClientMessage(33) format=0x20 window=0x00a00004 type=0x126("WM_PROTOCOLS") data=0x36,0x01,0x00,0x00,0x68,0x12,0x95,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00;
000:>:022f: Event FocusIn(9) detail=Nonlinear(0x03) event=0x00a00004 mode=Normal(0x00)
000:>:022f: Event FocusIn(9) detail=Pointer(0x05) event=0x00a00005 mode=Normal(0x00)
000:>:043e: Event (generated) ConfigureNotify(22) event=0x00a00004 window=0x00a00004 above-sibling=None(0x00000000) x=0 y=31 width=818 height=460 border-width=1 override-redirect=false(0x00)
000:>:04f5: Event (generated) ConfigureNotify(22) event=0x00a00004 window=0x00a00004 above-sibling=None(0x00000000) x=-2 y=40 width=818 height=460 border-width=1 override-redirect=false(0x00)
000:>:061c: Event (generated) ConfigureNotify(22) event=0x00a00004 window=0x00a00004 above-sibling=None(0x00000000) x=-4 y=44 width=818 height=460 border-width=1 override-redirect=false(0x00)
000:>:070b: Event (generated) ConfigureNotify(22) event=0x00a00004 window=0x00a00004 above-sibling=None(0x00000000) x=-8 y=57 width=818 height=460 border-width=1 override-redirect=false(0x00)
000:>:07fa: Event (generated) ConfigureNotify(22) event=0x00a00004 window=0x00a00004 above-sibling=None(0x00000000) x=-10 y=66 width=818 height=460 border-width=1 override-redirect=false(0x00)
000:>:08e9: Event (generated) ConfigureNotify(22) event=0x00a00004 window=0x00a00004 above-sibling=None(0x00000000) x=-13 y=73 width=818 height=460 border-width=1 override-redirect=false(0x00)
```
So... apparently just being moved around makes mlterm change its background pixmap like that (the size stays the same in all those events).

Now it's up to the mlterm devs to figure out what is going on, I guess.

**Comment by psychon** [comment]
It might be that they already figured out the problem and fixed it five months ago:

https://github.com/arakiken/mlterm/commit/a68dcdb9be434b71da9c755ed8c009423027010b#diff-41b6a72cdaa3f65eb153fbc2132ee572d670702c72f3f17f392c1029dbfcaf0eR277

According to GitHub, that commit is part of mlterm 3.9.1. I was just testing with mlterm 3.9.0-1 (latest version from debian testing).

**Comment by vovan69** [comment]
The problem in still there:
mlterm --version
mlterm version 3.9.1
Features: implugin imagelib(builtin)

**Comment by vovan69** [comment]
Actually pseudo transparent background works fine with `--transbg=true --depth=32`, so the problem is fixed. Thanks again for pointing me to the commit!

**Comment by vovan69** [comment]
In case you're interested, here is the fix https://github.com/arakiken/mlterm/commit/122b22201e74b6bdf88b46a8620dd3cdc2c88985#diff-41b6a72cdaa3f65eb153fbc2132ee572d670702c72f3f17f392c1029dbfcaf0e

**Comment by psychon** [comment]
Ah, thanks, that explains what is going on. I hadn't considered the "out of screen" "stuff".
