### ISSUE TITLE
Autostart in Secondscreen

### ISSUE THREAD

**Issue by comod** [awesomeWM/awesome#3258]
I would like to Autostart my Windows properly. Some of them should open on my Second Monitor. I Made a Rule for that, but it dont work

```
    {
        rule = {
            instance = "chromium"
        },
        properties = {
            screen = screenLeft,
            tag = "1",
        },
--        callback = function(c)
--            print("Triggered")
--        end
    },
```

- It was triggered
- screenLeft is a Number wich was also used for initializing Tags:

```
...
    -- Each screen has its own tag table.
    if (s.index == screenLeft) then
        -- left
        awful.tag({ "1", "2", "3" }, s, awful.layout.layouts.left[1])
    else
...
```

My Output of xrandr is:
```
Screen 0: minimum 320 x 200, current 3640 x 1920, maximum 16384 x 16384
VGA-1 connected 1080x1920+0+0 left (normal left inverted right x axis y axis) 598mm x 336mm
   1920x1080     60.00*+
   1680x1050     59.95  
...
   640x480       75.00    72.81    66.67    59.94  
   720x400       70.08  
HDMI-1 connected primary 2560x1080+1080+0 (normal left inverted right x axis y axis) 798mm x 334mm
   2560x1080     59.98*+  74.99  
   1920x1080     60.00    50.00    59.94  
...
   640x480       75.00    60.00    59.94  
HDMI-2 disconnected (normal left inverted right x axis y axis)
```
(I have 2 Screens)

What do I do wrong?

**Comment by ShayAgros** [comment]
I don't seem to have this problem on my setup.

How do you decide on the index of the left screen ?

First thing, are you sure that the rule is being called at all ? Try to do something simpler with it, e.g. only deciding a tag, change its floating state etc.

If the problem isn't with it, how sure are you about the indices of the screens ?

If you run something like
```
local naughty = require("naughty")
awful.screen.connect_for_each_screen(function(s)
	if s.outputs then
		local screen_name

		for key, value in pairs(s.outputs) do
			screen_name = key
			print(key, ":", value)
		end

		naughty.notify {
			title = 'Identified screen',
			text = s.index .. ":" .. screen_name,
			timeout = 5,
		}
	else
		print("doesn't exist")
	end
end)
```
does the index correspond to what you perceive as the right index ?

Did you try setting
```
        properties = {
            screen = "HDMI-1",
            tag = "1",
        },
```
?

**Comment by comod** [comment]
> First thing, are you sure that the rule is being called at all ? Try to do something simpler with it, e.g. only decide on a tag, change its floating state etc.
Yes, of course i played around with it

```
        properties = {
            screen = screenLeft,
            tag = "2", -- <====
        },
        callback = function(c)
            print("Triggered") -- <===
        end
```
I also tried the name-identifier instead

Your Code Snippet to Identify the Screens shows a similar interesting behaviour i also figured out meanwhile:
**The "Screen" is where my mouse is**
So if my cursor is on the left screen, both notifications appear on the left. If my mouse is on the right screen, all notifications appear on the right. 
Same with the AutoStart.

**Comment by comod** [comment]
Still having this Issue.

For a moment i thought i have solved it, but the follwoing works only with some apps:
```
awful.spawn('kitty', {screen = screenLeft, tag = "l"}) -- yes
awful.spawn('nemo', {screen = screenLeft, tag = "l"}) -- yes
awful.spawn('vlc', {screen = screenLeft, tag = "l"}) -- no
awful.spawn('slack', {screen = screenLeft, tag = "l"}) -- no
awful.spawn('joplin', {screen = screenLeft, tag = "l"}) -- no
awful.spawn('chromium', {screen = screenLeft, tag = "l"}) -- no
awful.spawn('gnome-disks', {screen = screenLeft, tag = "l"}) -- yes
awful.spawn('audacity', {screen = screenLeft, tag = "l"}) -- no
awful.spawn('kitty', {screen = screenLeft, tag = "l"}) -- yes
```

yes means = it opens on left screen as expected; no = unexpected on the right

Is this the only way i can open/attach Programms to a screen? Or is there maybe a more Object-Oriented-Style possible (eg: tag.spawn(...) ) ?

**Comment by ShayAgros** [comment]
Hi,
sorry for not updating. It's trickier than I thought it'd be at first.

I'm able to reproduce the same issue on my setup. It seems that programs like `audacity` create a "loading window" which is launched on the tag you requested but by the actual program loads on the same tag (and screen) you happen to be on at the time you launch it.

When looking at the output of `awful.spawn` I see that the `pid` and `startup_ip` are returned correctly. The output of
```
		local pid, startup_notification = awful.spawn("audacity", {tag = "5"})
		print("pid is", pid)
		print("start up notification:", startup_notification)
```

is
```
pid is   17867                        
start up notification:  awesome/audacity/shay_TIME732304814
```

which makes you think that the rules should work since the `DESKTOP_STARTUP_ID` field in `/proc/17867/environ` is the same as returned from `spawn`.

Unfortunately I'm not familiar enough with xcb or `awesome` implementation of `client`, so I'm not sure where to go from here.
I guess that this problem requires more learning or some help from the maintainers.

I don't know a quick-fix either. The [client](https://awesomewm.org/doc/api/classes/client.html) module contains a `pid` and `startup_id` fields. In theory you can traverse all clients and find the spawned client's `client` module (from there it'd be easier to move it to another tag).
Don't have a better solution for now

**Comment by ShayAgros** [comment]
This seems to be a similar issue to #3260

**Comment by comod** [comment]
This works for me

```
ruled.client.append_rule {
	rule = {instance = "joplin"},
	callback = function(c) c.move_to_screen(c, screenLeft) end
}
```

But everytime this callback is called, the mouse will be stealed to the given screen and then other autostart apps opens then there on the wrong screen as well as a follow-up-issue of the actual solution :-D. But more of this rules fixed that as well
