### ISSUE TITLE
Cant open Gnome-Settings

### ISSUE THREAD

**Issue by comod** [awesomeWM/awesome#3259]
If i go over the Menu: Settings > Settings i see my cursor loading, but then nothing happens. I see no Window opens up. At the very first day it worked, but since day x  i cant never again these settings. What can i do?

**Comment by psychon** [comment]
Where are you going to "Settings -> Settings"? Is that somewhere in awesomewm? What happens when you run `gnome-control-center` in a terminal? (Google says that's the name of the command)

**Comment by comod** [comment]
I can open it with
`sudo gnome-control-center &`
without sudo i get 
`Speicherzugriffsfehler (Speicherabzug geschrieben)` (German)

**Comment by comod** [comment]
OK after close and retry i cant even open it again with sudo

**Comment by psychon** [comment]
`gnome-control-center` segfaulting sounds like a bug. No idea why it crashes like that.

For future reference: `LC_ALL=C gnome-control-center` should produce an English error message.

>  i cant even open it again with sudo

Does it still crash? If so, I think there is nothing we can do about that.

**Comment by comod** [comment]
I had for every user and your variant with LC_ALL only exactly ONE try and then it comes never up. It Crashes on Click on Audio Settings (So here must be something fishy)

journal:
```
Feb 04 21:57:27 comod kernel: gnome-control-c[21963]: segfault at 0 ip 00007f12ff5e85b1 sp 00007ffc09eedfa8 error 4 in libc-2.31.so[7f12ff54f000+178000]
Feb 04 21:57:27 comod kernel: Code: ff 0f 00 00 66 0f ....
```

Last days I configured awesomewm/linux to fit my needs (Sound (pulse/effects), Display (xrandr), Profile) Maybe i screwed up at some point. I symlinked .config/awesome to another central point to get two users working at once (maybe important, but i dont think so).

I tried to purge gnome-control-center and reinstall. After that i cant log in. So i install lightdm (What i want to do anyway :-D ) ... now i can work with awesomewm but Ubuntu seems totally broken and im totally lost.

**Comment by ShayAgros** [comment]
`gnome-control-center` doesn't works for me as well under awesome. It does under Ubuntu's gnome DE.
In my case it opens, but displays a blank window. I'm running on Ubuntu 18.04 with its default session launcher UbuntuDM (not sure if it's the correct term, the program that lightDM and UbuntuDM are a).

Anyway, I'm not sure that it is supposed to work ... It does have the word 'gnome' in it. Maybe it wouldn't work under KDE and Cinammon as well. Is there some specific functionality there you're missing ?

**Comment by comod** [comment]
I think i can live without gnome-*

**Comment by adpande** [comment]
This has solved my issue.

`env XDG_CURRENT_DESKTOP=GNOME gnome-control-center`
