### ISSUE TITLE
`awful.spawn` sn_rules doesn't apply

### ISSUE THREAD

**Issue by TornaxO7** [awesomeWM/awesome#3260]
Output of `awesome --version`:
```
awesome v4.3-895-g538586c17-dirty (Too long)
 • Compiled against Lua 5.3.6 (running with Lua 5.3)
 • API level: 4
 • D-Bus support: yes
 • xcb-errors support: no
 • execinfo support: yes
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
 • Transparency enabled: yes
 • Custom search paths: no
```

**How to reproduce the issue:**
Add the following key mapping:
1. map modkey2 as the windows-key.
2. Add this mapping:
```lua
    awful.key({ modkey2,           }, "Return", 
		function () 
			-- go_to(1)
			awful.spawn("alacritty", {tag="3", focus=true}) 
		end,
            {description = "open a terminal in tag 1", group = "launcher"}),
```
3. create a tag with the name `"3"`:
```lua
awful.tag.add("3",
	{
		layout 			= awful.layout.suit.max,
		gap 			= 10,
		screen 		= 1
	}
)
```
4. Restart `awesomewm`
5. Press `winkey + return`

**Actual result:**

Alacritty is opened in the current tag.

**Expected result:**

According to the docs, I can give a table to the `awful.spawn` function which sets some properties to the program/window:
https://awesomewm.org/doc/api/libraries/awful.spawn.html

Now according to this section: https://awesomewm.org/doc/api/classes/client.html#Extra_properties_available_in_awful_rules_and_awful_spawn
I can set these values but it doesn't move `alacritty`  to the given tag.

**Comment by psychon** [comment]
Looks like alacritty does not support startup notification, but the support for that might be in one of its dependencies:
- https://github.com/alacritty/alacritty/search?q=_NET_STARTUP_ID
- https://github.com/alacritty/alacritty/search?q=DESKTOP_STARTUP_ID

**Comment by TornaxO7** [comment]
I've tested `awful.spawn` on other applications as well:
```lua
			awful.spawn("chromium", {tag="2", focus=true})
```
this doesn't spawn chromium on tag 2 as well.

And if I try this:
```lua
	    awful.key({}, "c", function()
            -- go_to(2)
			awful.spawn("chromium", {tag="2", focus=true, switch_to_tag=true, 
                callback=function() awful.spawn("notify-send welp") end})
			root.keys(globalkeys)
			end,
			{description="open chromium", group="browser"}
		),
```
Even the `notify-send` isn't executed.

**Comment by TornaxO7** [comment]
Ok so I've created a workaround by using the rules and the `autofocus` library. It's working now.
