### ISSUE TITLE
Awesome don't pass keyboard events received with xdotool or root.fake_input() to the window client

### ISSUE THREAD

**Issue by nemya9066** [awesomeWM/awesome#3266]
Output of `awesome --version`:
![version](https://user-images.githubusercontent.com/51141144/107508461-f4ba8e80-6b98-11eb-80eb-d70e663d7f72.png)

**How to reproduce the issue:**
add these keys to your rc.lua
![keys](https://user-images.githubusercontent.com/51141144/107508705-5549cb80-6b99-11eb-82ad-4cda9fb9841e.png)

Open a terminal or any program where you can input some text

**Actual result:**
If you use the Mod+Shift+v hotkey the program in focus will receive the 'a' character however with the Mod+v hotkey awesome receive the 'a' character and as a result execute the Mod+a hotkey showing the notification.

**Expected result:**
Both hotkeys should input 'a' to the window in focus, awesome should pass the keyboard event to the window client in focus without having to add a sleep period.
I tried using root.fake_input() but it behave the same way(need a sleep period) I also tested if awesome can pass mouse events and it did just fine it's only keyboard event which it can't pass.

**Comment by nemya9066** [comment]
I tested sxhkd in bspwm to see if it's an Xorg problem apparently it is.
sxhkd behave the same way as awesome it can only pass keyboard events after a sleep period.
What package in Xorg is responsible for this is it Xlib just how hard would this be to fix?

**Comment by psychon** [comment]
Well... you press Mod4 + v. At this point both Mod4 is active and v is down. Then you use `xdotool` to fake a key press and release of `a`. Thus, now three keys are down: Mod4, v, and a. The other keys are "still down".

I'm sorry, but this is how X11 / Xorg works. I don't think we can do anything about it. You just have to release mod4 quicker. ;-)

(And no, awesome is not involved in this in any way; the same would happen without it. It is the X11 server that decides "oh, there is a grab for that combination", I think)

**Comment by nemya9066** [comment]
Yeah I figured out this is not awesome problem but an X one. I tested dwm since it use Xlib instead of xcb and it behave even worse :)
I will return to this later anyway if anyone is having the same problem I found that sleeping for 0.15 second is the sweet spot.
Closing.
