### ISSUE TITLE
Setting a client shape in properties of a rule doesn't work

### ISSUE THREAD

**Issue by wucke13** [awesomeWM/awesome#3271]
Output of `awesome --version`:

```
awesome 4.3 (Too long)
 • Compiled against Lua 5.2.4 (running with Lua 5.2)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: [string "return require('lgi.version')"]:1: module 'lgi.version' not found:
        no field package.preload['lgi.version']
        no file '/usr/share/lua/5.2/lgi/version.lua'
        no file '/usr/share/lua/5.2/lgi/version/init.lua'
        no file '/usr/lib/lua/5.2/lgi/version.lua'
        no file '/usr/lib/lua/5.2/lgi/version/init.lua'
        no file './lgi/version.lua'
        no file '/usr/lib/lua/5.2/lgi/version.so'
        no file '/usr/lib/lua/5.2/loadall.so'
        no file './lgi/version.so'
        no file '/usr/lib/lua/5.2/lgi.so'
        no file '/usr/lib/lua/5.2/loadall.so'
        no file './lgi.so'
```

**How to reproduce the issue:**

Add a `rule` with the following properties table:

```
 properties = { 
      shape = function(cr, w, h) gears.shape.rounded_rect(cr, w, h, 2) end
    }
```

**Actual result:**

An error rises: `lib/gears/shape.lua:69: attempt to perform arithmetic on local 'width' (a table value)`

**Expected result:**

All matching clients are shaped as `rounded_rects`. I interprete https://awesomewm.org/doc/api/classes/client.html#client.shape in such a way that the function signature which is described in https://awesomewm.org/doc/api/libraries/gears.shape.html# should work for the `shape` property, however, this seems not to be the case.

It's not obvious to me what the correct usage is.

**Comment by psychon** [comment]
Try this:
```lua
shape = function() return function(cr, w, h) gears.shape.rounded_rect(cr, w, h, 2) end end
```
The reason is this:
https://github.com/awesomeWM/awesome/blob/4319b161103a81403ba3516924e86e13ff33c036/lib/ruled/client.lua#L611-L613
When a property is a function, the function is called and its return value is assigned to the property. Thus, the above adds a "do nothing" function that returns the shape you want.

**Comment by wucke13** [comment]
@psychon Thank you for the nice for the explanation! I would have wished for this to be  a little clearer in the docs. For future referencen, this does work too (but is a bit ugly):

```
callback = function (c)
        c.shape = function(cr, w, h) gears.shape.rounded_rect(cr, w, h, 7) end
 end
 ```

**Comment by psychon** [comment]
For the future: v4.4 will simplify things (and break the above): https://github.com/awesomeWM/awesome/commit/eca5c869fad936ace37e0e5d0cdd51473945d426
