### ISSUE TITLE
tests/run.sh: Dependencies and how to run?

### ISSUE THREAD

**Issue by psychon** [awesomeWM/awesome#328]
First:

    sh: 1: xdotool: not found

and hence I changed:

```diff
diff --git a/tests/test-urgent.lua b/tests/test-urgent.lua
index c33f01c..a9b3cf2 100644
--- a/tests/test-urgent.lua
+++ b/tests/test-urgent.lua
@@ -46,7 +46,11 @@ local steps = {
   function(count)
     if count == 1 then
       -- Setup: switch to tag.
-      os.execute('xdotool key super+2')
+      root.fake_input("key_press", 133)
+      root.fake_input("key_press", 11)
+      root.fake_input("key_release", 11)
+      root.fake_input("key_release", 133)
+      --os.execute('xdotool key super+2')
 
     elseif awful.tag.selectedlist()[1] == tags[1][2] then
       assert(#client.get() == 1)
```

However, this depends on the specific key codes for Mod and 2 and is non-portable.
Ideas?

The other issue I have can be seen here: https://gist.github.com/psychon/67f795a87a97f67d8128
Can we somehow make this work for not-installed awesome? For example, something like this can be use to "hack up" a "working" theme:

    sed -e 's:/usr/local/share/awesome/themes/default/theme:./themes/sky/theme:' -i lib/beautiful/init.lua
    sed -e 's:/usr/local/share/awesome/themes/default/theme:./themes/sky/theme:' -i awesomerc.lua
    sed -e 's:awesome_icon.*:awesome_icon = "../icons/awesome16.png":' -i themes/sky/theme.lua
    sed -e 's:/usr/local/share/awesome:..:' -i awesomerc.lua -i themes/sky/theme.lua
    sed -e '/titlebar/s:\.\./::' -i themes/sky/theme.lua

(But I guess this should be replaced by e.g. `sed -e 's:@AWESOME_THEMES_PATH@:./themes/sky/theme:' awesomerc.lua.in > build/awesome.rclua` so that it works independently of the prefix)

Ideas?

**Comment by actionless** [comment]
about the latest part, mb to add a function instead of using build-time template? ie:
```lua
local themes_path = beautiful.get_themes_path()
theme.titlebar_close_button_normal = themes_path .. "/default/titlebar/close_normal.png"
```

**Comment by psychon** [comment]
This makes the functional tests totally work for me (by creating a theme that points to the not-installed versions of our PNG files):

https://gist.github.com/psychon/f9f556889a30359ed83d

For `xdotool` I'd suggest something like `which xdotool || { echo "xdotool not found, but is needed by the tests. Aborting." ; exit 1}`. Dunno if this works nor if this works portably.

**Comment by blueyed** [comment]
> https://gist.github.com/psychon/f9f556889a30359ed83d

Seems good.  But please add an extra check for the `rm -rf ...` (test that `$tmp_files` is a dir and (the variable is) non-empty).

> which xdotool || { echo "xdotool not found, but is needed by the tests. Aborting." ; exit 1}

Needs an extra ";" after `exit 1` (IIRC), but seems to be good.

Maybe `setxkbmap` could be used to make `fake_input` work instead? (by using a known keymap during tests)

**Comment by blueyed** [comment]
@psychon 
Can you provide a PR with your Gist?

I think it's good, including to not require/use `xdotool` - where would the keycodes differ?  Wouldn't that be the case for non-standard keys?

**Comment by psychon** [comment]
Well, we had https://awesome.naquadah.org/bugs/index.php?do=details&task_id=627 and I remember someone with a Mac later complaining about this, since there were different keycodes (or something like this). I don't really think that keycodes are all that standardized.

And yeah, this is somewhere near the lower end of my todo list. Sorry.

**Comment by blueyed** [comment]
> https://awesome.naquadah.org/bugs/index.php?do=details&task_id=627
I wonder / could imagine that https://github.com/awesomeWM/awesome/pull/365 would help for this: it might be possible to use "1" .. "0" instead of keycodes now already, or with this PR.

Apart from that, `root.fake_input` should work with strings already?! (converting them via `XStringToKeysym`)

**Comment by blueyed** [comment]
I've tried the following, but it does not seem to work.  Should/could this be supported by `fake_input`?

      root.fake_input("key_press", "Mod4")
      root.fake_input("key_press", "2")
      root.fake_input("key_release", "2")
      root.fake_input("key_release", "Mod4")

**Comment by blueyed** [comment]
..using "Super_L" works.

**Comment by psychon** [comment]
Fixed with e.g. #391.
