### ISSUE TITLE
Can't modify the size of the hotkeys_popup widget

### ISSUE THREAD

**Issue by MarkusLohmayer** [awesomeWM/awesome#3281]
Output of `awesome --version`: 

awesome v4.3 (Too long)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2

**How to reproduce the issue:**
Use the standard configuration
for the hotkeys widget:
```
require("awful.hotkeys_popup.keys")
local hotkeys_popup = require("awful.hotkeys_popup").widget
-- ...
function()
   return false,
   hotkeys_popup.show_help
 end
```

**Actual result:**

the hotkeys widget is cropping some output
because there are too many hotkeys to show,
due to `require("awful.hotkeys_popup.keys")`.

**Expected result:**

I would like to change the size of the hotkey widget 
such that it (almost) fully utilizes my screen
because I expect that all hotkeys could be shown if it were larger.

So far I tried the following:
```
local hotkeys = require("awful.hotkeys_popup");
local hotkeys_popup = require("awful.hotkeys_popup").widget.new(
{
width = awful.screen.focused().geometry.width,
height = awful.screen.focused().geometry.height,
}
)
```
which gives me the following error when I try to show the widget:
```
/usr/share/awesome/lib/awful/hotkeys_popup/widget.lua:496: attempt to index a nil value (local 'self')
```
The problem persists if I try the same but with fixed integers for width and height.

I would also like to have a slightly bigger font size for this popup.
Having examples or a standard configuration which shows how to achieve this would be very helpful.

**Comment by sclu1034** [comment]
In the default config, the hotkey popup is imported with `local hotkeys_popup = require("awful.hotkeys_popup")`, which makes `hotkeys_popup.show_help` point at the [generic `widget.show_help`](https://github.com/awesomeWM/awesome/blob/5da5d36178250335f748eed43551daad9e5af694/lib/awful/hotkeys_popup/widget.lua#L593-L595), which operates on an internal, global instance of the popup widget.

When you switch to `local hotkeys_popup = require("awful.hotkeys_popup").widget.new()`, you create your own, separate instance of that widget and `hotkeys_popup.show_help` points at the [`widget_instance:show_help` method](https://github.com/awesomeWM/awesome/blob/5da5d36178250335f748eed43551daad9e5af694/lib/awful/hotkeys_popup/widget.lua#L492-L546), which requires the instance to be passed as first parameter (or to be called with the `:` notation, which is syntactic sugar for that).

So you need to convert all your calls of `hotkeys_popup.show_help(...)` to `hotkeys_popup:show_help(...)`.

**Comment by Aire-One** [comment]
Username match, so I guess you're from the discord channel. Thanks for reporting this issue upstream! I hope someone will be able to handle it.

**Comment by MarkusLohmayer** [comment]
Thanks for your help!
This indeed my first encounter with Lua.
Anywhow, the original problem is unfortunately not solved:
My expectation that everything will be shown once the window is larger was not met.
With the larger size, the second column is not even full, yet the text at the bottom of the first column is cut off.
Of course, the problem is not grave but nevertheless the behavior should be considered as a bug.
The issue should probable be renamed now to something like:
hotkeys_popup widget is not properly rendering contents

**Comment by sclu1034** [comment]
Hmm, I can't replicate that with a default config. Can you share some additional details:

- screen resolution
- a screenshot
- additions in hotkey definitions from your config, if any

Also, does the pagination (`PgUp`/`PgDn` to switch pages) work? It should be enabled automatically when the screen is too small to fit all hotkeys.

> I would also like to have a slightly bigger font size for this popup.

This can be achieved by passing additional arguments to the `new` function you already used above or by setting some theme variables:

```lua
local hotkeys_popup = require("awful.hotkeys_popup.widget").new({
	-- your width and height
	font = "Monospace Bold 9", -- font and size for the group label and hotkey name
    description_font = "Monospace 8", -- font and size for the hotkey description
})

-- OR, in your theme definition

theme.hotkeys_font = "Monospace Bold 9"
theme.hotkeys_description_font = "Monospace 8"
```

**Comment by MarkusLohmayer** [comment]
In this picture you can hopefully see that the text was cut off at the bottom:
![image](https://user-images.githubusercontent.com/10695734/110300931-d0b36700-7ff7-11eb-91bb-39f7b609e6b9.png)
I observed that the text is only cut off on one of the two monitors, which have slightly different resolution.
If you or anyone else wants to investigate the issue further, I can of course share my old configuration.

Since not all columns were filled, pagination did not make a difference.
But thanks for mentioning. I did not know about the pagination feature.

Having changed the font size, everything is displayed nicely now!
Thanks again for your help!
For me personally, the issue is fixed now in the sense that changing font and window size increased the usability and the aesthetics of this helpful widget.

**Comment by unai-ndz** [comment]
Looks like #3158, which is fixed in master. Could you try your configuration with the latest version of awesome?

> I observed that the text is only cut off on one of the two monitors, which have slightly different resolution.

This _shouldn't_ be a problem, the code looks aware of the different monitors.

**Comment by MarkusLohmayer** [comment]
Alright, I built the package myself and turns out that #3158 fixes the problem.

**Comment by actionless** [comment]
but those fixes were never merged from back then: https://github.com/awesomeWM/awesome/pull/3185

**Comment by Surferlul** [comment]
I had the problem too, but I upgraded from the version in pacman to the version in the AUR (from the default package in the arch-/artixlinux repositories to the newest one directly compiled from source) and it fixed the problem. Your distros repository might not have the newest version so try to find a newer build or compile it yourself
