### ISSUE TITLE
No group labels in hotkeys popup

### ISSUE THREAD

**Issue by Johnystar** [awesomeWM/awesome#3287]
Output of `awesome --version`:

```
awesome v4.3 (Too long)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
 ```

**How to reproduce the issue:**

I have no idea. Here's my [rc.lua](https://github.com/Johnystar/.dotfiles-management/blob/master/.config/awesome/rc.lua).

**Actual result:**

No group labels
![image](https://user-images.githubusercontent.com/29976879/111038390-e1fdd880-8428-11eb-818c-1d80e180441b.png)

**Expected result:**

Group labels
![image](https://user-images.githubusercontent.com/29976879/111038391-e88c5000-8428-11eb-983c-a1bca0b88d04.png)

**Comment by Elv13** [comment]
@actionless any idea?

**Comment by actionless** [comment]
1) how did you made the other screenshot with labels displayed?

2) do you see anything in awesomewm logs?

**Comment by actionless** [comment]
1.1. if the second screenshot was made with default rc.lua:

try commenting out third-party extensions which you have in your config

**Comment by Johnystar** [comment]
1. took the screenshot on a secondary test device, that I don't really use for anything
1.1. I'll look into it, but I think the labels were still there even shortly after I enabled the addons
2. where can I find those? I tried looking, but couldn't figure it out

**Comment by actionless** [comment]
by default awesome  error logs ending up in your Xsession output (`~/.xsession-errors` or so)

**Comment by Johnystar** [comment]
Well, since I was already planning to do so anyway, I finally installed Arch on my main computer and the issue seems to be completely gone even with the same config. I'm not sure what the problem was, but it seems to be working fine now.

**Comment by actionless** [comment]
let's reopen if you'll have more info

**Comment by DaitiDay** [comment]
I have the same problem, no groups labels in the `hotkeys_popup` . Using the default `rc.lua`  from `/etc/xdg/awesome/rc.lua` .
The output of `awesome --output` 
```
awesome v4.3 (Too long)
 • Compiled against Lua 5.3.6 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
```

**Comment by actionless** [comment]
> awesome v4.3 (Too long)

can you reproduce it with the latest git-master?

**Comment by DaitiDay** [comment]
Sorry for the late response. How can I make the switch? I'm on arch and I installed it via the package manager. Should I just install the AUR package `paru -S awesome-git` ?

**Comment by actionless** [comment]
awesome-git or awesome-luajit-git, i myself using the latter

**Comment by DaitiDay** [comment]
After switching to `awesome-git` the labels are where they're supposed to be. Thank you. Just a quick couple of questions:
1. What's the difference between `awesome-git`  and `awesome`? Why are groups labels broken in the latter?
2. Is there a way I can change the color of each group label?

**Comment by actionless** [comment]
1) sorry it's too stupid question to try answering
2)  there is `.label_colors` property: https://github.com/awesomeWM/awesome/blob/master/lib/awful/hotkeys_popup/widget.lua#L374 however when you asked about it - i've noticed that's unfortunately unlike label_fg and _bg it's undocumented here: https://awesomewm.org/apidoc/popups_and_bars/awful.hotkeys_popup.widget.html - so PR or at least an issue to add the doc would be welcome 👍
