### ISSUE TITLE
graph: fix min_value with scaling

### ISSUE THREAD

**Issue by blueyed** [awesomeWM/awesome#3289]
In https://github.com/awesomeWM/awesome/commit/68999f4a86df5f8d23d7bf06939d45985f052411 support for `min_value` was added (to fix #277).

However, I think the default for it is confusing / not wanted when `scale` is set: it will use `math.huge` by default then, scaling/adjusting it to the lowest value of the graph (https://github.com/awesomeWM/awesome/commit/68999f4a86df5f8d23d7bf06939d45985f052411#diff-a7fbbb267f5d802c8978befe19471ea94047d665e04c210cf2daf710d4860756R139-R141).

But I think it should default to `max_value - widget_height` then, so that the graph will be filled, instead of being empty with only a single set of minimal values.

Notes:

- the doc says "Note that the min_value is not supported when used along with the stack property." (https://github.com/awesomeWM/awesome/commit/68999f4a86df5f8d23d7bf06939d45985f052411#diff-a7fbbb267f5d802c8978befe19471ea94047d665e04c210cf2daf710d4860756R47-R48), but then does something for stacked graphs (https://github.com/awesomeWM/awesome/commit/68999f4a86df5f8d23d7bf06939d45985f052411#diff-a7fbbb267f5d802c8978befe19471ea94047d665e04c210cf2daf710d4860756R108-R110)!? => should get revisited
- with `max_value` it mentions the behavior with regard to "scale". This should be revisited (s/below/above/ ?), and also added for `min_value` then

Output of `awesome --version`: awesome v4.3-900-g4319b1611-dirty (Too long)

**Comment by Elv13** [comment]
This was fixed a while back
