### ISSUE TITLE
Some native Linux games freeze when the mouse is moved

### ISSUE THREAD

**Issue by IrreversibleReboot** [awesomeWM/awesome#3296]
Output of `awesome --version`:

```
awesome v4.3-897-g66b1780d8-dirty (Too long)
 • Compiled against Lua 5.3.6 (running with Lua 5.3)
 • API level: 4
 • D-Bus support: yes
 • xcb-errors support: no
 • execinfo support: yes
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
 • Transparency enabled: yes
 • Custom search paths: no
```

**How to reproduce the issue:**

1. Launch Higurashi or Ziggurat (pretty specific games, sorry)

**Actual result:**

Each time the mouse is moved, the game freezes a little bit, sometimes even the whole system freezes.

**Expected result:**

Moving the mouse doesn't causes the game to freeze.

This doesn't happen in XFCE, openbox, or i3, which is why I thought of reporting it here. This happens with the default config. I think it's also worth noting that this does happen on the the previously mentioned WMs/DE if I have picom running, but on awesomewm it happens regardless of that.

I have the following related messages in my Xorg log, but they seem to just describe the symptoms.
```
[   704.846] (EE) event22 - Logitech Wireless Mouse MX Master 3: client bug: event processing lagging behind by 13ms, your system is too slow
[   704.996] (EE) event22 - Logitech Wireless Mouse MX Master 3: client bug: event processing lagging behind by 13ms, your system is too slow
[   705.163] (EE) event22 - Logitech Wireless Mouse MX Master 3: client bug: event processing lagging behind by 14ms, your system is too slow
[   707.463] (EE) client bug: timer event22 debounce short: scheduled expiry is in the past (-0ms), your system is too slow
[   708.129] (EE) event22 - Logitech Wireless Mouse MX Master 3: client bug: event processing lagging behind by 11ms, your system is too slow
[   708.213] (EE) event22 - Logitech Wireless Mouse MX Master 3: client bug: event processing lagging behind by 12ms, your system is too slow
[   708.213] (EE) event22 - Logitech Wireless Mouse MX Master 3: WARNING: log rate limit exceeded (5 msgs per 60min). Discarding future messages.```

**Comment by actionless** [comment]
do you see any difference if running awesome with `--no-argb` flag?

**Comment by IrreversibleReboot** [comment]
No more freezes if I run it with this flag, thank you!
Good to know there's a workaround.
