### ISSUE TITLE
Dracula themed awesomewm (workflow).

### ISSUE THREAD

**Issue by yogeshdcool** [awesomeWM/awesome#3299]
![Screenshot_2021-03-25-25_1920x1080](https://user-images.githubusercontent.com/81402891/112710457-6b141580-8ee7-11eb-9bbc-130673da271a.png)

**Comment by unai-ndz** [comment]
Please, use the [dedicated issue](#1395) for this.

**Comment by Aire-One** [comment]
Hello @yogeshdcool,

Thanks for sharing your work on awesome wm with us!

However, we already have an issue (#1395) where everyone can submit their screenshots. Please close this issue and post your screenshot in #1395.
