### ISSUE TITLE
Dracula themed awesomewm (screenshot).

### ISSUE THREAD

**Issue by yogeshdcool** [awesomeWM/awesome#3300]
![Screenshot_2021-03-25-58_1920x1080](https://user-images.githubusercontent.com/81402891/112710493-a1ea2b80-8ee7-11eb-9607-24306788ab2d.png)

**Comment by Aire-One** [comment]
Hello @yogeshdcool,

Thanks for sharing your work on awesome wm with us!

However, we already have an issue (#1395) where everyone can submit their screenshots. Please close this issue and post your screenshot in #1395.
