### ISSUE TITLE
PHPStorm Dialogs open up on wrong Screen

### ISSUE THREAD

**Issue by comod** [awesomeWM/awesome#3303]
Jetbrains / IntelliJ / PHPStorm Dialogs open up on wrong place/screen

Output of `awesome --version`:

```
awesome v4.3-900-g4319b161 (Too long)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • API level: 4
 • D-Bus support: yes
 • xcb-errors support: no
 • execinfo support: yes
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
 • Transparency enabled: yes
 • Custom search paths: no
```
**How to reproduce the issue:**

I have a rule for Dialogs to make them float. Some PHPStorm Dialogs dont follow this rule completely.

```
-- Dialogs
ruled.client.append_rule {
	id = 'dialog',
	rule_any = {
		type  = {'dialog'},
	},
	properties = {
		titlebars_enabled = true,
		floating = true,
		above = true,
		skip_decoration = true,
		focus = true,
		raise = true,
		ontop = true,
		border_width = 5,
	},
	callback = function(c)
		gears.debug.print_warning("_____dialog");
		gears.debug.print_warning(c.name);
		gears.debug.print_warning(c.instance);
		c.move_to_screen(c, screenRight)
	end
}
```

To be sure the current window followed this rule i set the border_width 5 px, because some Dialogs are Internal-Popup (i guess).
![image](https://user-images.githubusercontent.com/19387282/112752438-485f2b00-8fd3-11eb-8473-d600ed787cfb.png)
_Non-Dialog_

Often some specific Dialog-Windows open up on the second screen (not there where the parent lives).
One Scenario is even 100% reproducable:
1. Open one PHPStorm Instance
2. Open settings Dialog (opens normal centered)
3. Trigger second Dialog
![image](https://user-images.githubusercontent.com/19387282/112752486-9b38e280-8fd3-11eb-8b65-d436c4f0ba9d.png)
_Dialog on wrong screen_

![image](https://user-images.githubusercontent.com/19387282/112752468-865c4f00-8fd3-11eb-9364-580fbda5e44c.png)
_Dialog on right screen_

As you can see i also added
`c.move_to_screen(c, screenRight)`
Which works(!) fine as app starter rule to move specific apps to the right place at start

Why does this thing not work for the Dialog here?

I figured out that when i move the first Dialog some millimeters (or more :-) ) in my Scenario that i then get the expected Result (that might be helpful, to find the actual issue)

**Comment by Elv13** [comment]
Long story short, Java hardcodes behavior with a whitelist of certain window manager being "reparenting" and it has some broken fallback to handle other WMs. Some of it's behavior also contradicts the spec. As long as it does that, lesser known WMs will behave weirdly. I am pretty sure this is one of those corner case. The way X11 handle multi-screen is also another story in itself. There is 4 or 5 different protocols (Xinerama, TwinView, Xrandr, Xaphod, multi-server, unified framebuffer) and some toolkit don't bother trying to get it right (if there is such a thing).

There is little we can do (or JetBrain) to solve this. I wont try my luck arguing with Oracle so they fix Java.

**Comment by actionless** [comment]
mb try to `export _JAVA_AWT_WM_NONREPARENTING=1`

**Comment by comod** [comment]
@actionless unfortunatelly this has no effect

@Elv13 
What is about my trick i figured out that when i move the parent window before i trigger the second dialog? I mean: If i can fix this manually, then i can fix that automatically too, or not? (for this case with the second dialog at least)

**Comment by Elv13** [comment]
> then i can fix that automatically too, or not?

Yes, `ruled.client` *may* be enough, but not always. However, there is definitively a way to fix that. `ruled.client` is only applied when a client first appears. But some buggy apps explicitly ask themselves to be moved *after* they appear in the right place. You can use the no-so-well-documented permission system from a `request::manage` callback to deny the client ability to move and resize itself (one of `request::geometry` permission).

**Comment by comod** [comment]
Yes, This works for me!

```
local capi =
{
	awesome = awesome,
	client = client,
}

local moveRight = function(c) c.move_to_screen(c, screenRight) end

capi.client.connect_signal("request::geometry", function (c)
	if c.instance == 'jetbrains-phpstorm' then
		moveRight(c)
	end
end
```
