### ISSUE TITLE
Deleting one Cyrillic symbol in run prompt requires two Backspace keystrokes

### ISSUE THREAD

**Issue by NordMike** [awesomeWM/awesome#3308]
Output of `awesome --version`:

awesome v4.3 (Too long)
 • Compiled against Lua 5.1.5 (running with Lua 5.1)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2

**How to reproduce the issue:**

* open run prompt with hot key (M+r)
* switch keyboard layout to Cyrillic (Caps Lock)
* write any Cyrillic symbols
* hit Backspace two times

**Actual result:**

One symbol is deleted.

**Expected result:**

Two symbols are deleted.

**Comment by actionless** [comment]
please try with the latest git master, i think that problem for unicode characters was already fixed there

**Comment by psychon** [comment]
I'm not good at writing cyrillic symbols, sorry. Could you run the following in a shell and share its output?
```
$ echo -n ä | hexdump -C
00000000  c3 a4                                             |..|
00000002
```
As you see here, `ä` needs two bytes: `0xc3` and `0xa4`. The prompt code only deletes one byte when you press backspace. That should produce invalid utf8 and cause an error and trigger the fixup here:
https://github.com/awesomeWM/awesome/blob/fda950d186efdc43a64c4300a27a5e19a55c2bd7/lib/awful/prompt.lua#L892-L906

**Comment by NordMike** [comment]
```
$ echo -n фыва | hexdump -C
00000000  d1 84 d1 8b d0 b2 d0 b0                           |........|
00000008
```

**Comment by psychon** [comment]
Ah, thanks a lot.

I found some duplicates: #1744 and #974

This is broken since 2016: 178204449c477ba437946b94ec29ae019d54caad
Before that, setting "broken" text on a textbox threw a lua error. Afterwards, it just prints a warning/error.

I cannot test this, but I guess something like this is needed to fix things to the "new way of doing things" (patch completely untested):
```diff
diff --git a/lib/awful/prompt.lua b/lib/awful/prompt.lua
index 427199136..3283a1b22 100644
--- a/lib/awful/prompt.lua
+++ b/lib/awful/prompt.lua
@@ -114,7 +114,6 @@ local io = io
 local table = table
 local math = math
 local ipairs = ipairs
-local pcall = pcall
 local capi =
 {
     selection = selection
@@ -543,7 +542,7 @@ function prompt.run(args, textbox, exe_callback, completion_callback,
     -- Update textbox
     local function update()
         textbox:set_font(font)
-        textbox:set_markup(prompt_text_with_cursor{
+        return textbox:set_markup_silently(prompt_text_with_cursor{
                                text = command, text_color = inv_col, cursor_color = cur_col,
                                cursor_pos = cur_pos, cursor_ul = cur_ul, selectall = selectall,
                                prompt = prettyprompt, highlighter =  highlighter })
@@ -889,7 +888,7 @@ function prompt.run(args, textbox, exe_callback, completion_callback,
             selectall = nil
         end
 
-        local success = pcall(update)
+        local success = update()
         while not success do
             -- TODO UGLY HACK TODO
             -- Setting the text failed. Most likely reason is that the user
@@ -902,7 +901,7 @@ function prompt.run(args, textbox, exe_callback, completion_callback,
 
             command = command:sub(1, cur_pos - 2) .. command:sub(cur_pos)
             cur_pos = cur_pos - 1
-            success = pcall(update)
+            success = update()
         end
 
         if changed_callback then
```
Whoever wants to: Feel free to take this patch, test it properly, and turn it into a PR. Bonus points for writing tests.
