### ISSUE TITLE
Screen border

### ISSUE THREAD

**Issue by fedoranvar** [awesomeWM/awesome#3313]
Good day to you!

Is it possible to add border color around (active or all) screen or workspace?

![image](https://user-images.githubusercontent.com/52028706/113537339-e2396000-95f1-11eb-8743-475ceb75b0c9.png)

![image](https://user-images.githubusercontent.com/52028706/113537370-f9784d80-95f1-11eb-8b0f-ea98784f9f97.png)

awesome v4.3 (Too long)
 • Compiled against Lua 5.3.5 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2

**Comment by Elv13** [comment]
Yes, but you will need to clarify what you are looking for first. First of all, is adding it to the wallpaper enough? If so, do it there. It is possible to use the widget system to generate programmatic wallpapers.

If you are looking to make an overlay, you can use `awful.placement` and a `wibox`. Make sure you set `ontop = true`. See how the "aero snap" code works. The code that's used to generate the rectangle when you move a client near a screen edge.

My https://github.com/elv13/collision library also does tricks like this. It uses older APIs and there is easier way to do what it does, but if you are looking into low level ways of doing it, there's nice examples there.

**Comment by fedoranvar** [comment]
@Elv13 
just configuring wallpaper is not enough. So I'll look into library-way.

Thank you!

**Comment by fedoranvar** [comment]
@Elv13 
just configuring wallpaper is not enough. So I'll look into library-way.

Thank you!

**Comment by actionless** [comment]
i am changing the color of one of the widgets on the panel, when that screen getting active

**Comment by actionless** [comment]
mb you could try to change the color of panel borders
