### ISSUE TITLE
Black Sreen

### ISSUE THREAD

**Issue by AlaxJI** [awesomeWM/awesome#3319]
Output of `awesome --version`:

awesome v4.3-966-g7a8fa9d2 (Too long)
 • Compiled against Lua 5.4.2 (running with 0.9.2)
 • API level: 4
 • D-Bus support: yes
 • xcb-errors support: no
 • execinfo support: yes
 • xcb-randr version: 1.6
 • LGI version: /usr/share/lua/5.4/lgi/version.lua
 • Transparency enabled: yes
 • Custom search paths: no

**How to reproduce the issue:**

build from source at fedora 33
in console type `startx awesome`

**Actual result:**

black screen with mouse
hotkey don`t work

**Expected result:**

worked awesome winows manager

**Comment by Elv13** [comment]
Is it a regression?

If not, what happens when you start AwesomeWM in Xephyr? Any message printed in the terminal?

**Comment by AlaxJI** [comment]
If start AwesomeWM in Xephyr:
```sh
/lib64/libc.so.6(__libc_start_main+0xf2) [0x7f3499ce81e2]
awesome(_start+0x2e) [0x40fd2e]
2021-04-06 08:28:16 W: awesome: luaA_panic:860: restarting awesome
2021-04-06 08:28:17 W: awesome: luaA_panic:855: unprotected error in call to Lua API (bad argument #1 to 'math.randomseed' (number has no integer representation))
2021-04-06 08:28:17 W: awesome: luaA_panic:859: dumping backtrace
awesome(backtrace_get+0x41) [0x4248c4]
awesome() [0x418ab2]
/lib64/liblua-5.4.so(+0x17a57) [0x7f79798cda57]
/lib64/liblua-5.4.so(+0x1202d) [0x7f79798c802d]
/lib64/liblua-5.4.so(lua_error+0x28) [0x7f79798c8108]
/lib64/liblua-5.4.so(luaL_error+0xc9) [0x7f79798c81e9]
/lib64/liblua-5.4.so(luaL_argerror+0x9f) [0x7f79798c82af]
/lib64/liblua-5.4.so(luaL_checkinteger+0x79) [0x7f79798c8f39]
/lib64/liblua-5.4.so(+0x1e581) [0x7f79798d4581]
/lib64/liblua-5.4.so(+0x1760b) [0x7f79798cd60b]
/lib64/liblua-5.4.so(+0x1775b) [0x7f79798cd75b]
/lib64/liblua-5.4.so(lua_callk+0x47) [0x7f79798c3187]
awesome(main+0xd52) [0x411151]

```

**Comment by Elv13** [comment]
Lua 5.4 is currently not supported (and I am not sure it ever will be) by some of our dependencies. Please link against another Lua. I suggest Luajit2.1, it is much faster.

See https://github.com/awesomeWM/awesome/issues/3123 and https://github.com/awesomeWM/awesome/pull/3279

**Comment by actionless** [comment]
closed in https://github.com/awesomeWM/awesome/issues/3324
