### ISSUE TITLE
[QUESTION] Attach external program to WM globals/state

### ISSUE THREAD

**Issue by levouh** [awesomeWM/awesome#3320]
Didn't see any other templates, nor a better place to ask this so I figured I'd make an issue.

---

I'm aware that `awesome-client` can be used to interact with the window manager, but is there a way to do something like:

_some_executable_file.lua_
```
#!/usr/bin/lua

-- Import various Awesome tools?
local awful = require('awful')

-- Access to globals like `client`?
for _, c in ipairs(client.get()) do
    print(c.name)
end
...
```

from an external PID? Meaning something that isn't a part of the whole `rc.lua`, etc. stack that _does_ have access to these things?

All I want to do is attach an external process and have it be able to do things like query all clients, etc.

Is this possible?

**Comment by Elv13** [comment]
Possible, yes, but it will still run as part of `rc.lua` under the hood, so there is very little reasons to do it in practice. You can pipe code into `awesome-client` or make a shebang wrapper to execute scripts like you do above. However all it does is turn everything into a script, upload it into Awesome current process and execute it there.

If you want true multi-process, you have to implement DBus services in Awesome and manipulate them from your external process. This gives *some* true parallelism, but some code still get executed in the main AwesomeWM thread.

Now, that doesn't mean just using `awesome-client` isn't enough for your workflow. You can totally do a script to list clients and dump some information that way.

```sh
!/bin/bash

cat << EOL | awesome-client
ret = {}

for _, c in ipairs(client.get()) do
    table.insert(ret, {c.name, c.pid})
end

return require("gears.debug").dump_return(ret)
EOL
```

```
   string "table: 0x55e391245940
  1 : table: 0x55e39113d7f0
    1 : xterm (string)
    2 : 2238332 (number)
  2 : table: 0x55e391072900
    1 : xterm (string)
    2 : 2238318 (number)
  3 : table: 0x55e390eeeec0
    1 : xterm (string)
    2 : 2238304 (number)
  4 : table: 0x55e390eeee30
    1 : xterm (string)
    2 : 2238278 (number)
  5 : table: 0x55e391068c30
    1 : xterm (string)
    2 : 2238276 (number)"
```

**Comment by levouh** [comment]
Sounds good, thanks.
