### ISSUE TITLE
Vertical wibar

### ISSUE THREAD

**Issue by fedoranvar** [awesomeWM/awesome#3321]
Is it possible to make wibar vertical?

![image](https://user-images.githubusercontent.com/52028706/113874409-3483a800-97cf-11eb-8509-6df3fe0ecd51.png)

**Comment by Aire-One** [comment]
The wibar constructor do have a `position` parameter. You can use it with the literal string `"left"`, to do what you want.

Please check https://awesomewm.org/doc/api/classes/awful.wibar.html#awful.wibar

Also, you can have a look at the git documentation to find a vertical wibar example. AFAIK, it works on stable version : https://awesomewm.org/apidoc/popups_and_bars/awful.wibar.html

**Comment by fedoranvar** [comment]
> The wibar constructor do have a `position` parameter. You can use it with the literal string `"left"`, to do what you want.
> 
> Please check https://awesomewm.org/doc/api/classes/awful.wibar.html#awful.wibar
> 
> Also, you can have a look at the git version of the documentation to find a vertical wibar example. AFAIK, it works on stable version : https://awesomewm.org/apidoc/popups_and_bars/awful.wibar.html

Thank you!

I've used your link and was able to rotate bar but right now have problems with rotating tags icons and printing keyboard layout textbox with another textbox as one widget.

Looking for answers in docs, any advice are welcome!

![image](https://user-images.githubusercontent.com/52028706/113923121-9826c900-9801-11eb-8b89-3db2afa2f65e.png)

**Comment by Elv13** [comment]
You can use https://awesomewm.org/apidoc/widget_containers/wibox.container.rotate.html in your widget tree to either rotate the whole content or only rotate individual widgets

**Comment by fedoranvar** [comment]
figured it out!
![image](https://user-images.githubusercontent.com/52028706/113929829-ee980580-9809-11eb-8fa4-8b1d88886296.png)

Thanks!
