### ISSUE TITLE
Weird Dual Monitor Behavior

### ISSUE THREAD

**Issue by GRVYDEV** [awesomeWM/awesome#3323]
Output of `awesome --version`:

```awesome v4.3-858-g49a3859c8 (Too long)
 • Compiled against Lua 5.3.5 (running with Lua 5.3)
 • API level: 4
 • D-Bus support: yes
 • xcb-errors support: no
 • execinfo support: yes
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
 • Transparency enabled: yes
 • Custom search paths: no
```

I am currently using 2 monitors stacked on top of each other. Whenever I open a window on my bottom screen it does not show up. If I fullscreen the window I can see it however if it is not full screen I cannot. I can open windows just fine on my top screen. I cannot for the life of me figure out what is causing this. To be clear xrandr recognizes both monitors and I can see my desktop on both monitors.

**Comment by blueyed** [comment]
Does <kbd>Mod4</kbd> + <kbd>o</kbd> fix it then maybe?  ("Send client to next screen.")

**Comment by Elv13** [comment]
Hi,

What are the specific resolution/layout of your monitors so I can try to reproduce?

**Comment by TorchedSammy** [comment]
gonna say that this happens to me too for my second screen
trying to do mod4 + o sends the client i have focused on the second screen, and even with no clients does nothing
and dragging clients to 2nd doesn't allow me to move it freely

**Comment by TorchedSammy** [comment]
i use a laptop at 1366x768, but scaled to 1080p and tv connected to hdmi at 1080p natively
i'm on fedora, but this didnt happen while on debian (and while scaling my laptop screen)
being on fedora and not scaling still has the same problem

**Comment by TorchedSammy** [comment]
with some random fiddling of my config i found out that i only define the layout for tags on the 1st screen
commenting that here, as that's probably the solution to this problem

**Comment by basaran** [comment]
This should be closed.

**Comment by basaran** [comment]
This should be closed.
