### ISSUE TITLE
Reject builds against Lua 5.4

### ISSUE THREAD

**Issue by psychon** [awesomeWM/awesome#3324]
Awesome should check at startup if it is running against Lua 5.4 and provide a good error message. According to #3319, the current error message is quite bad:
```
2021-04-06 08:41:59 W: awesome: luaA_panic:855: unprotected error in call to Lua API (bad argument #1 to 'math.randomseed' (number has no integer representation))
```
Bonus points for doing this check at build time, but since it is possible that `lua` and `liblua.so` are different Lua versions, it's not completely trivial. One needs to build a small test program and link it against the lua library found by CMake *and* run the program.

**Comment by ShayAgros** [comment]
Can you elaborate on what you mean ?

I can fail the build of the C files using static asserts on the macros in the `lua.h` file.

for example in lua5.3 has these macros in its lua.h header:
```
#define LUA_VERSION_MAJOR	"5"
#define LUA_VERSION_MINOR	"3"
#define LUA_VERSION_NUM		503
#define LUA_VERSION_RELEASE	"3"
``` 
so you can add this line to `awesome.c`:
```
static_assert(LUA_VERSION_MINOR < 4, "Awesome doesn't support lua version newer than 5.3");
```

From inside the interpreter I can fish the version by running `print(_VERSION)` (at least it seems to work for 5.3 and 5.2).

You want to prevent awesome from compiling in lua5.4 ?

**Comment by psychon** [comment]
Is `static_assert` part of C? Somehow that feels "not C99 nor C11" to me.

> for example in lua5.3 has these macros in its lua.h header:

Yeah, problem is: Those are strings. It's `"3"` and not `3`. I doubt that `"3" < 4` works.

But I totally missed `LUA_VERSION_NUM`. That one can actually be compared.

> You want to prevent awesome from compiling in lua5.4 ?

Yes. See #3319. Right now, AwesomeWM apparently compiles, but then fails to start. In that specific case this was with no error message and the symptom was "black screen". Failing too build is way better user experience than "does not work and brooke everything" (and results in hopefully less bug reports and those bug reports that do come in would be a lot more obvious).

**Comment by ShayAgros** [comment]
Yup I see what you mean. The static_assert is part of c11 standard.

In any rate the we could uise something like
```
#if LUA_VERSION_NUM >= 540
/* fail somehow */
#endif
```

I'll play around with it and submit a PR about to fail the compilation.
