### ISSUE TITLE
Some variables on `06-appearance.md` page are mentioned multiple times.

### ISSUE THREAD

**Issue by rijenkii** [awesomeWM/awesome#3328]
[Link to the page](https://awesomewm.org/apidoc/documentation/06-appearance.md.html)

`theme.bg_normal` and `theme.fg_normal` appear 5 times each; `theme.bg_systray`, `theme.border_width`, `theme.font` and `theme.useless_gap` appear 2 times each.

Command used to check duplicates:
```
$ cat theme.lua
local theme = {}

-- Default variables
-- theme.bg_normal = nil
[...]
-- theme.wibar_shape = nil

return theme

-- vim: filetype=lua:expandtab:shiftwidth=4:tabstop=8:softtabstop=4:textwidth=80
$ sort theme.lua | uniq -cd
     37 
      5 -- theme.bg_normal = nil
      2 -- theme.bg_systray = nil
      2 -- theme.border_width = nil
      5 -- theme.fg_normal = nil
      2 -- theme.font = nil
      2 -- theme.useless_gap = nil
```

**Comment by Aire-One** [comment]
Thank you for this issue report.

Looking at the source code from [`docs/06-appearance.md.lua`](https://github.com/awesomeWM/awesome/blob/master/docs/06-appearance.md.lua), which is what's used to create this page in the documentation, it seems we parse all the source files looking for `@beautiful` tags and basically add them to the list of variables to render.

https://github.com/awesomeWM/awesome/blob/fda950d186efdc43a64c4300a27a5e19a55c2bd7/docs/06-appearance.md.lua#L9-L11

I can see there is also some code to categorize these variables (there is only 1 category?). But that's about all.

My guess is that we need to add a filter to remove duplicate variables (maybe also sort them / extends the category filter?).

I'm busy right now, so I'll not have a deeper look before meh... maybe next week? But I think it would be a good issue for newcommers :wink: :wink: :wink:

**Comment by aflorea-2k** [comment]
I'm looking at this issue, and a problem I'm running into is that the "duplicates" in 06-appearance.md point to different links.

For instance, `bg_normal` links to `awful.popup`, `awful.wibar`, `beautiful.html`, `naughty.layout.box.html` and `wibox.html`.

As I'm new to this project, I don't quite know what you'd prefer to keep. I'd guess `beautiful.html`.

**Comment by sclu1034** [comment]
All of them, preferably. They could be consolidated into a single row with an additional column that lists the modules that use that variable.
