### ISSUE TITLE
Dbus monitoring

### ISSUE THREAD

**Issue by hari-rangarajan** [awesomeWM/awesome#333]
With "eavesdrop" setting, the code below in awesome does not intercept any notifications. Will this work? Thanks!

local function notifydbus() 
  print("Dbus notification")
end

dbus.request_name("session", "org.freedesktop.Notifications") 
dbus.add_match("session", "type='method_call', interface='org.freedesktop.Notifications', member='Notify', eavesdrop=true")
dbus.connect_signal("org.freedesktop.Notifications", notifydbus)

**Comment by Elv13** [comment]
This can/should be rewritten using LGI GDbus binding, our old dbus API is limited and mostly unmaintained.
