### ISSUE TITLE
Error running make

### ISSUE THREAD

**Issue by CSForever07** [awesomeWM/awesome#3330]
I am trying to build awesome from source and I encounter an error while running Cmake.

This is what happens when I run Cmake.
:~/awesome$ make
Creating build directory and running cmake in it. You can also run CMake directly, if you want.

Running cmake…
-- lua -> /usr/bin/lua
-- git -> /usr/bin/git
-- asciidoctor not found.
-- gzip -> /usr/bin/gzip
-- ldoc not found.
-- ldoc.lua not found.
-- Not generating API documentation. Missing: ldoc.
-- convert not found.
CMake Error at awesomeConfig.cmake:29 (message):
  convert is required to build awesome
Call Stack (most recent call first):
  awesomeConfig.cmake:63 (a_find_program)
  CMakeLists.txt:33 (include)

-- Configuring incomplete, errors occurred!
See also "/home/garv/awesome/build/CMakeFiles/CMakeOutput.log".
make: *** [Makefile:27: build/Makefile] Error 1

**Comment by Elv13** [comment]
Hello,

You need to install some dependencies to properly (and fully) build Awesome. See https://awesomewm.org/apidoc/documentation/10-building-and-testing.md.html

In this case, you are missing ImageMagick, but probably other things. If you are on Ubuntu, you can use `apt build-dep awesome` to take care of that.

**Comment by CSForever07** [comment]
I have tried doing apt build-dep awesome but it says there is no source package for awesome.

**Comment by sclu1034** [comment]
On Debian-based systems, the full list of dependencies (both required and optional) is:

```shell
apt-get install -y --no-install-recommends \
        build-essential \
        bc \
        git \
        gosu \
        curl \
        cmake \
        automake \
        gettext \
        libtool \
        unzip \
        asciidoctor \
        libnotify-bin \
        libcairo2-dev \
        gir1.2-gtk-3.0 \
        libpango1.0-dev \
        libxcb-xtest0-dev \
        libxcb-icccm4-dev \
        libxcb-randr0-dev \
        libxcb-keysyms1-dev \
        libxcb-xinerama0-dev \
        libdbus-1-dev \
        libxdg-basedir-dev \
        libstartup-notification0-dev \
        imagemagick \
        libxcb1-dev \
        libxcb-shape0-dev \
        libxcb-util0-dev \
        libx11-xcb-dev \
        libxcb-cursor-dev \
        libxcb-xkb-dev \
        libxcb-xfixes0-dev \
        libxkbcommon-dev \
        libxkbcommon-x11-dev \
        xcb-proto \
        xorg \
        dbus \
        librsvg2-dev \
        dbus-x11 \
        xterm \
        xdotool \
        wmctrl \
        xterm \
        xserver-xephyr \
        xvfb \
        zsh \
        x11-apps \
        xutils-dev \
        gir1.2-pango-1.0 \
        libgirepository1.0-dev \
        libgdk-pixbuf2.0-dev \
        liblua5.3-dev \
        lua5.3
```

If you want to skip optional packages (e.g. the ones used to run the test suite), you'll have to compare this with the list in the page linked above.
If you want to build against a different Lua version or LuaJIT, adjust the last two packages accordingly.

**Comment by Aire-One** [comment]
> I have tried doing apt build-dep awesome but it says there is no source package for awesome.

According to https://wiki.debian.org/Packaging/SourcePackage#How_to_Download_a_source_package you have to enable source repositories.

I guess Ubuntu, and other Debian based distro, also needs you to enable additional repository.

**Comment by Aire-One** [comment]
Closing as the project can build normally. The issue here is user related and the reporter don't give updates...

@CSForever07, feel free to reopen when you come back, if you still need our help.
