### ISSUE TITLE
freebsd config

### ISSUE THREAD

**Issue by basaran** [awesomeWM/awesome#3331]
Hello, I'm trying to get your module to work under Freebsd 13 stock install. Doing something wrong here, but I'm not sure what it is:

inside `rc.lua`, I have added the following as per README.

```
local machi = require("layout-machi")
beautiful.layout_machi = machi.get_icon()
local editor = machi.editor.create()
local trying = machi.layout.create({name = "grid2x2", persistent = false, default_cmd = "dw66.", editor = editor})
machi.switcher.start()

....

awful.layout.layouts = {
        trying,
}
```

It loads without any errors, however, when I try to launch the editor through `shortcut` or `awesome-client`, I'm getting:

```
awful.key({ modkey, }, "Return", function () editor.start_interactive(s=awful.screen.focused(), l=awful.layout.get(s)) end,
{description = "trying....", group = "awesome"}),
```

```
# echo 'editor.start_interactive(s=awful.screen.focused(), l=awful.layout.get(s))' | awesome-client
   string "[string "editor.start_interactive(s=awful.screen.focus..."]:1: ')' expected near '='"
```

It would be great if you could share a complete configuration file. Thank you for your work.

awesome devel (Too long)
Compiled against Lua 5.2.4 (running with Lua 5.2)
D-Bus support: ok
execinfo support: ok
xcb-randr version: 1.6
LGI version: 0.9.2

**Comment by Elv13** [comment]
Hello,

I guess there is 2 different errors. The `awesome-client` command is not going to work because it's missing some `require` and is not valid Lua code.

```
 'editor.start_interactive(s=awful.screen.focused(), l=awful.layout.get(s))'
```

It seems to be from that module readme, but this isn't valid code. Remove the `s=` and `l=` and report a bug to them. Lua named parameters don't work like that. For the record, this is how they work:

```lua

local function foo(a, b, c)
    print(a, b, c)
end

local function bar(args)
    print(args.a, args.b, args.c)
end

foo(1, 2, 3) -- note the `()`
bar{ a=1, b=2, c=3 } -- note the `{}`

```

**Comment by basaran** [comment]
Hello Elv13 :)

Thank you for getting back and the information. I must have gone to warp for a second and posted the issue under here. I was like, why is Elv13 replying? I'm sorry about that, none the less it is kind of you to get back. I appreciate it. Have a nice sunday.

P.S Of course, thank you indeed for awesomewm.
