### ISSUE TITLE
No way to unfocus client (API feature request)

### ISSUE THREAD

**Issue by MRAAGH** [awesomeWM/awesome#3334]
The API seems to be missing a call for unfocusing the currently focused client.

### To reproduce:
1. have multiple screens
2. use default configuration
3. have a client on screen 1 and nothing on screen 2
4. press `Mod+Ctrl+J`

### Actual result:
The client on screen 1 stays focused.
There is no visual indication which screen is focused (except the mouse cursor,
but if you use [unclutter](https://github.com/Airblader/unclutter-xfixes) like me, the cursor is invisible).

### Expected result:
I want my clients to unfocus when I switch away.
However, with current API, this doesn't seem to be possible.
Maybe something like `awful.client.focus.unfocus()` could work?
Or maybe `awful.client.focus.client(nil)` instead?

### Version:
```
awesome v4.3 (Too long)
 • Compiled against Lua 5.3.5 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
```

**Comment by Elv13** [comment]
It's

```
client.focus = nil
```

But yeah, I guess a `c:deactivate{reason="something"}` would make sense for modules.

**Comment by MRAAGH** [comment]
Thank you! I was not aware the field is modifiable.

**Comment by MRAAGH** [comment]
To anyone who found this wanting to do the same thing, here you go:

```
    awful.key({ modkey, "Control" }, "j", function ()
        awful.screen.focus_relative(1)
        if client.focus.screen.index ~= awful.screen.focused().index then
            client.focus = nil
        end
    end),
```

Or, if you prefer it without wrapping, this:
```
    awful.key({ modkey, "Control" }, "j", function ()
        awful.screen.focus(awful.screen.focused().index+1)
        if client.focus.screen.index ~= awful.screen.focused().index then
            client.focus = nil
        end
    end),
```

**Comment by actionless** [comment]
i think logic should be different, smth like this:

old_focus = client.focus
awful.screen.focus(......)
if old_focus == client.focus then
      unfocus
end

**Comment by jeffmhubbard** [comment]
> btw mb also you'll need to wrap if-condition inside gears.timer.delayed_call()

Since MRAAGH's method seems to work without issue, can you elaborate on why this might be necessary?

**Comment by actionless** [comment]
that for case if any other signal handler which running later on in the same event loop roll would interfeer with the focus

**Comment by jeffmhubbard** [comment]
Gotcha. I'll keep that in mind when if I run into any trouble with this. Thanks for the explanation.
