### ISSUE TITLE
root.fake_input per client

### ISSUE THREAD

**Issue by basaran** [awesomeWM/awesome#3341]
awesome v4.3 (Too long)
 • Compiled against Lua 5.3.5 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2

**How to reproduce the issue:**

```lua
    { rule = {class = "Google-chrome"}, properties = {screen = 1, tag  = "1:DEV", switchtotag = true, floating=true}, callback = function(c)
        local keys = c:keys()
        c:keys(gears.table.join(keys,
        awful.key({}, "F1", function () 
            root.fake_input('key_press'  , "Home")
            root.fake_input('key_release'  , "Home")
            -- awful.spawn("termite")
        end)))
    end},
```

**Expected result:**

I'm trying to assign per client keys using `rules`. My intention is to make  `F1` mapped to `Home` key.

**Actual result:**

It didn't work :)

At first, I tried to use `xdotool` but that also didn't succeed. Perhaps is it because `xdotool` doesn't know about the focused window at X window server?

Then I found Elv13's suggestion to use root.fake_input on reddit, but for some reason, client (chrome) is not executing the `key_press`. Executing an `awful.spawn` works however, so the callback must fine.

**Comment by basaran** [comment]
with the `xdotool` I was able to get it to work with prepending a minor `sleep`.

```
sleep 0.1 && xdotool key ctrl+t
```

**Comment by actionless** [comment]
did you tried prepending minor sleep for fake_root solution, namely using `gears.timer`?

**Comment by basaran** [comment]
Thank you for getting back, does this look right?

I can see it prints out `t` but somehow the `control` is ignore to open the tab.

```lua
    { rule = {class = "Google-chrome"}, properties = {screen = 1, tag  = "1:DEV", switchtotag = true, floating=true}, callback = function(c)
        local keys = c:keys()
        c:keys(gears.table.join(keys,
        awful.key({}, "F1", function () 
            gears.timer.weak_start_new(0.1, function()
                root.fake_input('key_press'  ,   "Control")
                root.fake_input('key_press'  ,   "t")
                root.fake_input('key_release'  , "t")
                root.fake_input('key_release'  , "Control")
            end)
            -- awful.spawn.with_shell(new_tab)
        end)))
    end},
```

**Comment by actionless** [comment]
because it should be `Control_L` or `Control_R`

**Comment by basaran** [comment]
why, of course it should :) Thank you for helping out, much appreciated
