### ISSUE TITLE
Firefox always opens in the previous tag

### ISSUE THREAD

**Issue by pidario** [awesomeWM/awesome#3345]
Output of `awesome --version`:

awesome v4.3-1019-ga4572b9b5 (Too long)
 • Compiled against Lua 5.3.6 (running with Lua 5.3)
 • API level: 4
 • D-Bus support: yes
 • xcb-errors support: no
 • execinfo support: yes
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
 • Transparency enabled: yes
 • Custom search paths: no

**How to reproduce the issue:**

I basically launch firefox (it happens with chromium as well, but any other applications I commonly use such as featherpad, alacritty, pcmanfm, and so on, open themselves in the current tag). My client configuration is this (I'm not attaching buttons and keys configuration):
```lua
local awful = require('awful')
local beautiful = require('beautiful')
local ruled = require('ruled')
local client_buttons = require('configuration.clients.buttons')
local client_keys = require('configuration.clients.keys')

_G.client.connect_signal(
	'manage',
	function(c)
		if not _G.awesome.startup then
			awful.client.setslave(c)
		end
		if _G.awesome.startup and not c.size_hints.user_position and
			not c.size_hints.program_position then
			awful.placement.no_offscreen(c)
		end
	end
)

_G.client.connect_signal(
	'mouse::enter',
	function(c)
		c:emit_signal(
			'request::activate',
			'mouse_enter',
			{
				raise = true
			}
		)
	end
)

_G.client.connect_signal(
	'focus',
	function(c)
		c.border_color = beautiful.border_focus
	end
)

_G.client.connect_signal(
	'unfocus',
	function(c)
		c.border_color = beautiful.border_normal
	end
)

ruled.client.connect_signal(
	'request::rules',
	function()
		ruled.client.append_rule {
			id         = 'all',
			rule       = { },
			properties = {
				focus = awful.client.focus.filter,
				raise = true,
				buttons = client_buttons,
				keys = client_keys,
			}
		}
		ruled.client.append_rule {
			id         = 'floating-clients',
			rule_any   = {
				type  = { 'dialog', 'utility' },
			},
			properties = {
				floating = true,
				above = true,
				raise = true,
				ontop = true,
				placement = awful.placement.centered
			}
		}
	end
)
```

**Actual result:**

See video attached (Edit: I cannot seem to play the video in this page on firefox but I can in chromium. I don't know much about video codec, I recorded it using this command: `ffmpeg -f x11grab -framerate 25 -video_size 1920x1080 -i :0 output.mp4`. In mpv the file plays smoothly. If any of you interested in this issue can't play it, I'll manage to re-encode it in some other way)

https://user-images.githubusercontent.com/3647292/118957871-2e9dec80-b961-11eb-814b-f6b11a5b0936.mp4

**Expected result:**

I expect firefox (but it should happen for any application) to open in the current tag.

**Comment by actionless** [comment]
have you already tried taking back from firefox `tag` permission?

file:///usr/share/doc/awesome/doc/libraries/awful.permissions.html

**Comment by pidario** [comment]
> have you already tried taking back from firefox `tag` permission?
> 
> file:///usr/share/doc/awesome/doc/libraries/awful.permissions.html

I'm not familiar with this API. After you mentioned it, I tried with the example in the documentation (which ironically enough is about firefox:
```lua
awful.permissions.add_activate_filter(function(c)
    if c.class == "Firefox" then return false end
end, "permissions")
```
But after restarting awesome, nothing changed. I even tried the function `remove_activate_filter`

**Comment by actionless** [comment]
i meant smth like:

```
local old_tag_permission = awful.permissions.tag
awful.permissions.tag = function(c, t, h)
    if c.class ~= 'Firefox' then old_tag_permission(c, t, h)
end
```

**Comment by pidario** [comment]
Sorry if I'm so slow, but I can't figure out how to do it in my current configuration..
My latest attempt is this (and of course it's not working, since I'm clearly doing something wrong):

```lua
ruled.client.connect_signal(
	'request::rules',
	function(c)
		if c.class == 'Firefox' then
			c.disconnect_signal("request::tag", awful.permissions.tag)
		end
	end
)
```

**Comment by actionless** [comment]
i mean, add one more rule to your list of rules in `ruled`, for firefox class

**Comment by actionless** [comment]
here's how rule with callback looks usually: https://github.com/actionless/awesome_config/blob/master/config/rules.lua#L130-L143

**Comment by pidario** [comment]
I'm a PITA, I know.
if you mean like this, it doesn't work

```lua
ruled.client.connect_signal(
	'request::rules',
	function()
                -- other rules
		ruled.client.append_rule {
			rule = {
				class = 'firefox', -- tried both 'Firefox' and 'firefox'
				callback = function(c)
					c.disconnect_signal('request::tag', awful.permissions.tag)
				end
			}
		}
        end
)
```

**Comment by actionless** [comment]
and if you put `print` inside callback, do you see the message?

**Comment by pidario** [comment]
As a matter of fact, I don't. It looks like the rule doesn't match, I also tried to set `floating = true` in **properties** in my catch-all rule, which does work as intended.

**Comment by actionless** [comment]
ah, then it should be `c:disconnect_signal` instead of `c.disconnect_signal`

**Comment by pidario** [comment]
Okay, now the error is gone, but the problem still persists

**Comment by actionless** [comment]
and if you disconnect that signal for all clients?

```
client.disconnect_signal("request::tag"           , permissions.tag)  -- this time with dot, not colon :)
```

**Comment by pidario** [comment]
If used like you posted I get an error referring to the global `permissions` object which is undefined. I believe you mean `awful.permissions`?

**Comment by unai-ndz** [comment]
Yes, he meant `awful.permissions`.

Disconnecting `awful.permissions.tag` kind of works, but firefox will still get drawn in the wrong tag, at least in multimonitor setups.
Disconnecting `awful.permissions.client_geometry_requests` fixes that.

```lua
client.disconnect_signal("request::tag", awful.permissions.tag)
client.disconnect_signal("request::geometry", awful.permissions.client_geometry_requests)
```

Disconnecting `awful.permissions.tag` makes awesome stop automatically assigning tags to clients. They have to be explicitly set, e.g. in `ruled`. A client without a tag will effectively be hidden, thats why your clients disappeared

We can instead reconnect the signal like this, so it works for every client except firefox
```lua
client.disconnect_signal("request::tag", awful.permissions.tag)
client.connect_signal("request::tag", function(c, t, hints)
    if c.class == "Firefox" then return end
    awful.permissions.tag(c, t, hints)
end)
client.disconnect_signal("request::geometry", awful.permissions.client_geometry_requests)
client.connect_signal("request::geometry", function(c, context, hints)
    if c.class == "Firefox" then return end
    awful.permissions.client_geometry_requests(c, context, hints)
end)
```

And then make sure you set a tag for firefox in ruled
```lua
ruled.client.append_rule {
    rule       = { class = 'Firefox' },
    properties = {
        tag = 1,
    },
}
```

The permission system is not yet finished, this will be easier to do when it gets merged.

**Comment by pidario** [comment]
Okay, thanks a lot for all your efforts, @actionless and for your explanation, @unai-ndz. I guess for now I'll just pick a tag and use it for browsing.

**Comment by unai-ndz** [comment]
I found a bug with the above "fix". If you move the client to another monitor the tag change will get ignored and it will behave as if it the sticky property was set to true.

To fix that and maybe some other bugs I missed, we have to ignore only the client's requests.

AFAIK this extra check handles that. I did a quick test, but only with firefox.
```lua
-- TODO: This should be updated when the permission system is finished
client.disconnect_signal("request::tag", awful.permissions.tag)
client.connect_signal("request::tag", function(c, t, hints)
    if t and not hints then
        -- If the client requested the tag change, ignore it.
        if c.class == "Firefox" then return end
    end
    awful.permissions.tag(c, t, hints)
end)
client.disconnect_signal("request::geometry", awful.permissions.client_geometry_requests)
client.connect_signal("request::geometry", function(c, context, hints)
    if context == "ewmh" and hints then
        -- If the client requested the geometry change, ignore it.
        if c.class == "Firefox" then return end
    end
    awful.permissions.client_geometry_requests(c, context, hints)
end)
```
This also has another advantage, we do not need to set an explicit tag anymore, so the above`ruled.client.append_rule` is not needed.

**Comment by pidario** [comment]
It works nicely, thank you. Just two itty-bitty issues:

1. if I have to restart awesome, firefox will be put in the first tag, but it's not something I often have to deal with.
2. for some reason, "Firefox" (with capital F) doesn't work, I have to use "firefox". On the other hand, for chromium it's the opposite: "Chromium" works, "chromium" does not

**Comment by sclu1034** [comment]
> for some reason, "Firefox" (with capital F) doesn't work, I have to use "firefox". On the other hand, for chromium it's the opposite: "Chromium" works, "chromium" does not

This value will always depend entirely on the application. To find this for any application:

- make sure `xprop` is installed (sometimes bundled in a "x11 utilities" package)
- run `xprop WM_CLASS` in a terminal
- click on an application window

The output will then show something like `"firefox", "firefox"`. The first value maps to `c.instance`, the second to `c.class`.

**Comment by unai-ndz** [comment]
1. I should investigate when and what triggers the different arguments, but this should be fixed in the last edit.
2. You can check with the command `xprop WM_CLASS` and clicking the window.

**Comment by pidario** [comment]
Nice, that did the trick. Thanks, both of you, @sclu1034 and @unai-ndz
