### ISSUE TITLE
awesome crash supertuxkart with latest mesa update in arch linux

### ISSUE THREAD

**Issue by nemya9066** [awesomeWM/awesome#3353]
Output of `awesome --version`:

awesome v4.3-1019-ga4572b9b5 (Too long)
 • Compiled against Lua 5.3.6 (running with Lua 5.3)
 • API level: 4
 • D-Bus support: yes
 • xcb-errors support: no
 • execinfo support: yes
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
 • Transparency enabled: yes
 • Custom search paths: no

**How to reproduce the issue:**

I think only people who are on arch system can reproduce the issue by installing the game and updating to the latest mesa package.

**Actual result:**

Here is what happened today I did a system update and the game supertuxkart stopped working I found out that it was the latest update of mesa to v21.1.1-1 (the previous version on my system was 21.0-3-2) that caused the crash. Of course I thought it had to do with the game or mesa but I decided to install bspwm to test if the game worked there and it did.
I downgraded mesa and everything is fine for me I just thought about sharing the error message with with the dev here :
https://justpaste.it/8f7n9

**Expected result:**

Here is the log from the game launching correctly with the previous mesa package:
https://justpaste.it/3w1ow

**Comment by actionless** [comment]
1) does it behave the same when running awesome with `--no-argb` flag?
2)                                                                                                         ..... in `openbox`?

**Comment by nemya9066** [comment]
@actionless  
1. yes.
2. no the game work fine in openbox.

**Comment by Elv13** [comment]
Still, if mesa crashes, then it's mesa bug. While defaulting to `argb` surfaces is the main difference between AwesomeWM and most other WMs (it's done because our titlebars can be transparent), there is hundreds of tiny other ones. Every WM will have a few oddities. Mesa need to not-crash here. Please report the bug to them
