### ISSUE TITLE
Unable to draw background on startup

### ISSUE THREAD

**Issue by YJH16120** [awesomeWM/awesome#3357]
Output of `awesome --version`:
```
awesome v4.3-1037-g149d18e0e (Too long)
 • Compiled against Lua 5.3.6 (running with Lua 5.3)
 • API level: 4
 • D-Bus support: yes
 • xcb-errors support: no
 • execinfo support: yes
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
 • Transparency enabled: yes
 • Custom search paths: no
```
**How to reproduce the issue:**

There are 4 things I did to try and draw a wallpaper on startup (or restarting awesome with mod+ctrl+r)
1. At the very bottom of `rc.lua` I wrote this line: `awful.spawn("nitrogen --random ~/Pictures/Backgrounds/")`
2. `awful.spawn.with_shell(<same as previous>)`
3. `awful.spawn("feh --bg-max ~/Pictures/Backgrounds/Text1.jpg")`, I wanted to try to see if I could draw the same image, because I thought the issue was with picking an image randomly.

At this point none of these worked. I even wrote this bash script, and executed it with
`awful.spawn("bash ./autostart.sh")`
The bash script:
```
wallpapers="$HOME/Pictures/Backgrounds/"

images=()
max=0
for file in `ls $wallpapers`; do
    images[max]=$file
    max=$((max+1))
done

index=$(shuf -i 0-$max -n 1)
image=${images[$index]}

full_path="$wallpapers$image"
feh --bg-max $full_path
```
I also tried it with nitrogen, so replace the final line in the script with `nitrogen --set-zoom-fill $full_path`.

However, when I ran the `autostart.sh` script with `bash autostart.sh` and regardless of if I used `feh` or `nitrogen` to draw my wallpaper it was able to pick a random image in my backgrounds folder and set it as the background.

**Actual result:**

Nothing happens

**Expected result:**

A random wallpaper inside my background folder will be drawn.

**Comment by actionless** [comment]
`grep wallpaper rc.lua`

**Comment by YJH16120** [comment]
> `grep wallpaper rc.lua`

`gears.wallpaper.maximized("/home/yjh/Pictures/Backgrounds/Lockers.jpg", s)`  
I found this off the awesome documentation, but I don't know enough about lua to make it pick a random image.

**Comment by YJH16120** [comment]
@actionless sorry for the ping but I found another issue not just for setting up a wallpaper, but I have this line `awful.spawn.with_shell("xinput set-prop 16 'Device Enabled' 0")` but it didn't work. But when I ran that command in the terminal it works. Is this a bug?

**Comment by actionless** [comment]
how do you know what "it didnt work"? what exactly it writes in stdout/err when failing?

**Comment by YJH16120** [comment]
Because what that does is supposed to disable my touchpad, but my mousepad isn't disabled I had to do it manually.

**Comment by actionless** [comment]
you're not helping to debug it

**Comment by YJH16120** [comment]
Then how do I get some debug output?

**Comment by actionless** [comment]
https://awesomewm.org/apidoc/documentation/90-FAQ.md.html

**Comment by YJH16120** [comment]
> https://awesomewm.org/apidoc/documentation/90-FAQ.md.html

A solution proposed there fixed it. Thanks.

**Comment by actionless** [comment]
i actually wanted you to read the part there it describes how to collect the logs, but direct-linking to topics is not supported there unfortunately

but i'm glad what the faq ended up being even more helpful :)
