### ISSUE TITLE
Telegram Desktop icon is not present in tray

### ISSUE THREAD

**Issue by raven2cz** [awesomeWM/awesome#3358]
Output of `awesome --version`: awesome master git

**How to reproduce the issue:**

Install and use Telegram Desktop app

**Actual result:**

Telegram Desktop tray icon is not present in the tray panel.

**Expected result:**

Analyze API between Telegram Desktop and awesome master tray impl. Check where is the problem. Other VM shows the icon and connection works.

**Comment by sclu1034** [comment]
I just installed the application on my system and the tray icon shows up fine, even without an account.
Have you double-checked the "Show tray icon" setting?
Additionally, have you tried switching window managers, both in the VM where it works and where it is broken?

**Comment by raven2cz** [comment]
Yes. Show tray icon, show taskbar icon are activated in the app. Qtile, xfce4, kde, gnome works. Awesome doesn't show tray icon. I have 5 PCs and all stations have same error. 
Arch system, awesome-git is used.

**Comment by Aire-One** [comment]
* Could this be a duplicate of #3245 or #2606?
* Does it affect Telegram only? (do you have systray for other programs?)
* Can you try to run `awesome.systray()`? (it's an undocumented static function that should return the number of systray icons awesome is aware of) (you should be able to call it from `awesome-client`)

**Comment by raven2cz** [comment]
No, it is not duplicate these issues. Systray works perfectly without any problems. Except remmina icon which is whole black now, but it is different problems older few days by new remmina build....
Back to problem. All icons are shown correctly, there is not problem. For example synology drive is shown correctly too, and it is very special app. 
Only one missing and it is Telegram. It was ok in the older release of awesome. But I'm using git master branch one year, and this problem is still not solved. 
I have visible 6 icons in the tray now, and your function returns :  systray.tostring=6
if the telegram is running, and not running, it's still have 6.
Maybe I understand that awesomewm doesn't handle systray, but I haven't any explanation why this happing just only for actual git master version, and all next VMs work.

**Comment by Aire-One** [comment]
Hold on, I just had flashbacks about #2995!

**Comment by sclu1034** [comment]
@Aire-One If this really was about `StatusNotiferItem`/`AppIndicator`, shouldn't it fail for everyone?
To me this sounds closer to the other issues about Qt's tray icon instability. Especially given that Telegram has been mentioned there as well.

@raven2cz Do you have other Qt-based applications with tray icons running?

**Comment by raven2cz** [comment]
I try to create basic QT systray app. 
See my example
![qt-systray](https://user-images.githubusercontent.com/20504243/121080870-476d2580-c7dc-11eb-94e9-04c175690681.png)
and it works normally, the heart icon is shown for the qt app.

**Comment by basaran** [comment]
I installed the latest telegram-desktop from aur, and things appear to look fine:

![image](https://user-images.githubusercontent.com/30809170/124230422-f8659800-dadc-11eb-9367-217f33b68d72.png)

![image](https://user-images.githubusercontent.com/30809170/124230447-00bdd300-dadd-11eb-8390-ce14a64b682b.png)

**Comment by raven2cz** [comment]
Confirmed, last telegram update solved the problem. I can close the issue.

**Comment by actionless** [comment]
> Confirmed, last telegram update solved the problem. I can close the issue.

somebody now need to go through and close all the dups of this ticket :D

**Comment by raven2cz** [comment]
yes, internet is decentralized network. In any case, it takes almost half year....

**Comment by asdf8dfafjk** [comment]
> I try to create basic QT systray app. See my example ![qt-systray](https://user-images.githubusercontent.com/20504243/121080870-476d2580-c7dc-11eb-94e9-04c175690681.png) and it works normally, the heart icon is shown for the qt app.

@raven2cz Is  this using the new `StatusNotifierItem` API? If so, is it somewhere on GitHub? (I went through your repositories and couldn't find it). I'd like to take a look

**Comment by raven2cz** [comment]
@asdf8dfafjk I just implement standard Qt example for tray icon integration. It is longer time.

There is new one
https://doc.qt.io/qt-6/qtwidgets-desktop-systray-example.html

**Comment by asdf8dfafjk** [comment]
Thanks!
