### ISSUE TITLE
awful.menu signals

### ISSUE THREAD

**Issue by Chaostheorie** [awesomeWM/awesome#3359]
Output of `awesome --version`:

awesome v4.3 (Too long)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2

**How to reproduce the issue:**

- Create awful.menu instance
```lua
-- {{{ Menu
-- Create a launcher widget and a main menu
myawesomemenu = {
    {
        "hotkeys",
        function() hotkeys_popup.show_help(nil, awful.screen.focused()) end
    }, {"manual", terminal .. " -e man awesome"},
    {"edit config", editor_cmd .. " " .. awesome.conffile},
    {"restart", awesome.restart}, {"quit", function() awesome.quit() end}
}

local menu_awesome = {"awesome", myawesomemenu, beautiful.awesome_icon}
local menu_terminal = {"open terminal", terminal}

if has_fdo then
    mymainmenu = freedesktop.menu.build({
        before = {menu_awesome},
        after = {menu_terminal}
    })
else
    mymainmenu = awful.menu({
        items = {
            menu_awesome, {"Debian", debian.menu.Debian_menu.Debian},
            menu_terminal
        }
    })
end
```
- Try to listen to mouse signal for `mouse::enter`
```lua
mymainmenu:connect_signal('mouse::enter', function()
    naughty.notify({
        preset = naughty.config.presets.critical,
        title = "Entered",
        text = "Entered"
    })
end)
```
**Actual result:**

- See nothing

**Expected result:**

- See the notification on mouse enter

**Question**:

Is there any way to listen to the `mouse::enter` (or sth comparable) signal for the `awful.menu` signal?

**Comment by Aire-One** [comment]
I can see your `mymainmenu` is an instance of `freedesktop.menu`. So maybe you should report/do a feature request downstream to the awesome freedesktop module developers instead of awesome.

> Is there any way to listen to the mouse::enter (or sth comparable) signal for the awful.menu signal?

`awful.menu` doesn't expose such signal.

There is however a way to access the underlying wibox used by the menu with the `wibox` property. It's an undocumented property, it means this is not intended for user to use it. Anyway, here is how you want to use this property :

```lua 
mymenu.wibox:connect_signal('mouse::enter', function()
    naughty.notify {
        preset = naughty.config.presets.critical,
        title = 'Entered' ,
        text = 'Entered'
    }
end)
```

Out of curiosity : what do you want to use this for?

**Comment by Chaostheorie** [comment]
Sorry, forgot to close. Thanks again @Aire-One for the help.

**Comment by Aire-One** [comment]
I do know by name the freedesktop module for awesome wm, but I'm not familiar with it at all. If the `freedesktop.menu.build` function returns an `awful.menu` instance, it is very likely this is going to work.

Thanks for the use case explanation, it sound fair to listen to the `"mouse::enter"` for this 😀

> Sorry, forgot to close. Thanks again @Aire-One for the help.

I guess it worked. Nice to hear that! Happy to help ;)
