### ISSUE TITLE
Provide widget name (for debugging)

### ISSUE THREAD

**Issue by blueyed** [awesomeWM/awesome#337]
While debugging / hacking on widget related stuff, I've added something like the following to e.g. `lib/wibox/layout/fixed.lua`:

    ret.widget_name = "layout.flex." .. dir

Is this the way to go, or is there something else already to get the name of a widget/layout/wibox?

**Comment by psychon** [comment]
Currently there is no way to get the name of a widget.

**Comment by blueyed** [comment]
Do you think it makes sense to manually define it then?

And/Or should we add a function to `gears.debug` to get the module name of an object somehow (if that is possible)?

**Comment by psychon** [comment]
I don't think we can come up with something useful for `gears.debug`. For names on widget's, you should follow your approach of adding a `widget_name` member, I guess.

Perhaps we can also use this in `wibox.widget.base.draw_widget` in case an error occurs? I'm not sure if that makes sense...

**Comment by blueyed** [comment]
The following would work in `base.make_widget`, but `debug.getinfo` is documented as not being efficient (http://www.lua.org/pil/23.1.html).

    ret.widget_name = debug.getinfo(2, 'S').source:gsub('.*/lib/', ''):gsub("/", "."):gsub("\\.lua$", "")

I've tried to apply this to `gears.object`, with the idea of using `getinfo` on the object's (`self`) metatable / `__call` method, but the metatable is not available from the objects itself.
Doing so would require to change all callers (e.g. wibox/widget/background.lua) to add it probably?

**Comment by psychon** [comment]
That `debug.getinfo` thing looks scary. I'd rather make this explicit (and perhaps so that the widget can change its name and run-time and e.g. add more information? Dunno how useful that would be)

**Comment by blueyed** [comment]
> I'd rather make this explicit

True.
This would also eliminate the discussion about any performance impact.
