### ISSUE TITLE
wibox.widget.base:set_opacity emits "widget::redraw" instead of "widget::redraw_needed"

### ISSUE THREAD

**Issue by ezz666** [awesomeWM/awesome#3371]
Same in both dev and release version.

`wibox.widget.base:set_opacity` emits the `"widget::redraw"` signal instead of the `"widget::redraw_needed"` signal.
As a result when opacity changes the difference  is not seen unless something else triggers redraw.
 
Here is the [problem](https://github.com/awesomeWM/awesome/blob/master/lib/wibox/widget/base.lua#L263).

**Comment by Aire-One** [comment]
I don't have the time to do it right now... 

I don't think we actually have a `"widget::redraw"` signal at all, so it might be a typo. Maybe we should have a unit test for this?

**Comment by actionless** [comment]
indeed looks like a typo:

```console
$ grep widget::redraw . -R | grep -v redraw_needed
./lib/wibox/widget/base.lua:        self:emit_signal("widget::redraw")
```
