### ISSUE TITLE
Infinite Pacman is currently in use, please wait... loop

### ISSUE THREAD

**Issue by itarnyagin** [awesomeWM/awesome#3372]
awesome v4.3 (Too long)
 • Compiled against Lua 5.3.5 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2

Follow the instructions for installing awesome for arch

sudo pacman -S --needed base-devel git
git clone https://aur.archlinux.org/awesome-git.git
cd awesome-git
makepkg -fsri

Infinite Pacman loop

I wanted it to install

It should install

**Comment by actionless** [comment]
you have borken system, go to arch forums

**Comment by Aire-One** [comment]
> Infinite Pacman loop

What does that mean? We can help you with a basic "it don't work" message. What step is blocked? Do you have some logs or something?

Also, given you use the AUR script, you would probably get better help by reporting the issue there...
