### ISSUE TITLE
Go to program when open

### ISSUE THREAD

**Issue by EuCaue** [awesomeWM/awesome#3376]
Output of `awesome --version`:

_awesome v4.3 (Too long)
 • Compiled against Lua 5.3.5 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2_

**I want to open a specific program to go/focus on it. How do I do on i3 with focus, on for_window.**

My config file https://pastebin.com/raw/gyqhXsT7

**Comment by Elv13** [comment]
you can use `awful.rules` for that.

Also note that to get a client out of a `awful.spawn` call, the application need to support the startup notification protocol. It used to be very common, but less and less do it. These days KDE and Gnome actually use systemd and cgroups. That's not implemented in Awesome at the moment (but given everybody else is doing it, we probably should). That being said, if you don't need to know which specific `awful.spawn` created a specific window, then `awful.rules` is enough.
