### ISSUE TITLE
Unable to open the right click menu in chromium after a screenshot

### ISSUE THREAD

**Issue by mattbdc** [awesomeWM/awesome#3379]
Output of `awesome --version`:

```
➜  ~ awesome --version
awesome v4.3 (Too long)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
➜  ~ 
```

**How to reproduce the issue:**

```
Open chromium or google-chrome
Run flameshot to point where you are selecting an area to capture (i.e. overlay shows), press esc
Return focus to chrome
```

**Actual result:**

```
Right click doesn't work in the chrome window (on tabs for example)
Can be fixed by switching to another tag and back
```

Identical issue with i3, they fixed it
https://github.com/i3/i3/commit/a06e66982bc921d05b68b75f8e12323c284233d0

**Comment by mattbdc** [comment]
Browsing the awesomewm issues I think this could potentially fix several reported problems - spotify etc.., awesomewm randomly hands for keys+mouse etc..

**Comment by basaran** [comment]
I can report the same issue. Switching between different clients restores the right click. I didn't need to switch tags. It would be nice to have this patched.

awesome v4.3 (Too long)
 • Compiled against Lua 5.3.5 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2

**Comment by mattbdc** [comment]
Yes can confirm client switch also resolves it. I just had one client in this tag so didn't notice tag.

**Comment by psychon** [comment]
Completely untested port of that i3 patch to AwesomeWM. No idea if I got it right.
```diff
diff --git a/event.c b/event.c
index 030f86166..8c49ea04a 100644
--- a/event.c
+++ b/event.c
@@ -696,6 +696,12 @@ event_handle_enternotify(xcb_enter_notify_event_t *ev)
 static void
 event_handle_focusin(xcb_focus_in_event_t *ev)
 {
+    if (ev->event == globalconf.screen->root) {
+        // FIXME I doubt this is entirely correct, but I'm too lazy to think too
+        // much about it right now.
+        globalconf.focus.need_update = true;
+    }
+
     if (ev->mode == XCB_NOTIFY_MODE_GRAB
             || ev->mode == XCB_NOTIFY_MODE_UNGRAB)
         /* Ignore focus changes due to keyboard grabs */
```

**Comment by basaran** [comment]
I don't know if it is related to this, but often times chromium also loses focus during normal focusing. I noticed this same problem on windows with ahk as well.

I use this in my chromium rule. It first sends a click to the address bar, and then sends the the fake input to open a new tab. But it's not just the fake_input not going through, any shortcut you would send wouldn't go through unless you click somewhere inside chromium.

```lua
local function new_tab(c)
   local keys = c:keys()
   c:keys(gears.table.join(keys, awful.key({}, "F1", function ()
      local was = mouse.coords()
      mouse.coords({x=c.x + 240, y=c.y+75})
      gears.timer.weak_start_new(0.1, function()
         root.fake_input('button_press'  ,   1)
         root.fake_input('button_release'  ,   1)
      
         gears.timer.weak_start_new(0.1, function()
            root.fake_input('key_press'  ,   "Control_L")
            root.fake_input('key_press'  ,   "t")
            root.fake_input('key_release'  , "t")
            root.fake_input('key_release'  , "Control_L")
            mouse.coords(was)
         end)
      end)
   end)))
  
end --|browsers sometimes don't activate properly when raised.
    --|this is not awesomewm's fault. On windows we have the
    --|same issue, although the window has focus, shortcuts do
    --|not render on it. This emulates a fake click on the
    --|window region to ensure our actions go through.
```

**Comment by mattbdc** [comment]
I notice this happens with Edge too.. So maybe Chromium code base is also at fault. It does not happen with Firefox.

**Comment by actionless** [comment]
i didn't understood from your message the result of testing psychon's suggestion

i think all those issues started to be reported as soon as google started using their internal compositor in chrome (aura it was called if i recall correctly)

**Comment by basaran** [comment]
I failed to compile from git, will test it as soon as I figure out #3325.

**Comment by basaran** [comment]
Good news, I think the patch is working fine:

https://user-images.githubusercontent.com/30809170/125135452-fd2add00-e0d6-11eb-9b29-1d249f9d0fc2.mp4

I will test to see if the other chrome focus issue has disappeared, it happens randomly, so I should be able to tell through the day.

**Comment by basaran** [comment]
That other focus issue is still there, @mattbdc can you see if you can send shortcuts (like ctrl-t) after you minimize chrome via shortcut and raise via shortcut.

**Comment by mattbdc** [comment]
Sorry been quite distracted recently, so just to be clear, Im building custom awesomewm from source with the patch from pyschon applied? Thanks

**Comment by basaran** [comment]
Yes please, just git clone the latest awesomewm, add psychon's patch to the relevant file and compile. You can check #3325 and the awesomewm FAQ for compilation steps.

**Comment by mattbdc** [comment]
I can confirm this now works - coming back to chrome frome scaping flameshot I can now right click. For those building on Ubuntu DLUA_LIBRARY needs a slight change from #3325 suggestion. 

```
  export _LUA_VER=5.3
  mkdir -p build
  cd build
  cmake ../ \
    -DCMAKE_BUILD_TYPE=RELEASE \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DSYSCONFDIR=/etc \
    -DLUA_INCLUDE_DIR=/usr/include/lua${_LUA_VER} \
    -DLUA_LIBRARY=/usr/lib/x86_64-linux-gnu/liblua${_LUA_VER}.so \
    -DLUA_EXECUTABLE=/usr/bin/lua${_LUA_VER}
  make
```

**Comment by basaran** [comment]
great, @psychon can this be merged?

**Comment by psychon** [comment]
Dunno. I don't mind anyone turning the above into a PR. Personally, I still don't fully understand what is going on and why needlessly re-setting the focus helps.

**Comment by basaran** [comment]
@mattbdc do you want to send the PR ?
