### ISSUE TITLE
Only redraw relevant/changed wibox elements

### ISSUE THREAD

**Issue by blueyed** [awesomeWM/awesome#338]
I've noticed that the whole main wibox (with the taglist, tasklist, systray etc) gets redrawn when a single widget changes, although that widget is in its own space, e.g. a cpugraph.

The stack traceback for a taglist entry:

    …/awesome/lib/wibox/widget/textbox.lua:71: in function <…/awesome/lib/wibox/widget/textbox.lua:67>
    [C]: in function 'pcall'
    …/awesome/lib/wibox/layout/base.lua:82: in function 'draw_widget'
    …/awesome/lib/wibox/layout/margin.lua:40: in function <…/awesome/lib/wibox/layout/margin.lua:19>
    [C]: in function 'pcall'
    …/awesome/lib/wibox/layout/base.lua:82: in function 'draw_widget'
    …/awesome/lib/wibox/layout/fixed.lua:49: in function <…/awesome/lib/wibox/layout/fixed.lua:21>
    [C]: in function 'pcall'
    …/awesome/lib/wibox/layout/base.lua:82: in function 'draw_widget'
    …/awesome/lib/wibox/widget/background.lua:46: in function <…/awesome/lib/wibox/widget/background.lua:20>
    ...
    [C]: in function 'pcall'
    …/awesome/lib/wibox/layout/base.lua:82: in function 'draw_widget'
    …/awesome/lib/wibox/layout/fixed.lua:49: in function <…/awesome/lib/wibox/layout/fixed.lua:21>
    [C]: in function 'pcall'
    …/awesome/lib/wibox/layout/base.lua:82: in function 'draw_widget'
    …/awesome/lib/wibox/layout/align.lua:84: in function 'draw'
    …/awesome/lib/wibox/drawable.lua:62: in function 'do_redraw'
    …/awesome/lib/wibox/drawable.lua:248: in function '?'
    …/awesome/lib/gears/timer.lua:114: in function <…/awesome/lib/gears/timer.lua:111>
    [C]: in function 'xpcall'
    …/awesome/lib/gears/timer.lua:111: in function <…/awesome/lib/gears/timer.lua:109>

I think this should be optimized to only redraw the changed widget and leave the others as-is.

This got initiated through this delayed callback, from an updated vicious graph widget:

	…/awesome/lib/gears/timer.lua:131: in function 'delayed_call'
	…/awesome/lib/wibox/drawable.lua:254: in function 'func'
	…/awesome/lib/gears/object.lua:90: in function 'emit_signal'
	…/awesome/lib/wibox/layout/align.lua:223: in function 'func'
	…/awesome/lib/gears/object.lua:90: in function 'emit_signal'
	…/awesome/lib/wibox/layout/fixed.lua:130: in function 'func'
	…/awesome/lib/gears/object.lua:90: in function 'emit_signal'
	…/awesome/lib/awful/widget/graph.lua:198: in function 'add_value'
	/home/user/.config/awesome/vicious/init.lua:78: in function 'update'
	/home/user/.config/awesome/vicious/init.lua:166: in function 'func'
	…/awesome/lib/gears/object.lua:87: in function 'emit_signal'
	…/awesome/lib/gears/timer.lua:41: in function <…/awesome/lib/gears/timer.lua:40>
	[C]: in function 'xpcall'
	…/awesome/lib/gears/timer.lua:40: in function <…/awesome/lib/gears/timer.lua:39>

Is this caused by the "align" layout widget or some other widget in this context, or a problem in general?

**Comment by psychon** [comment]
Same issue in the old tracker:

https://awesome.naquadah.org/bugs/index.php?do=details&task_id=1296

I have some branch with ideas on how to fix this. It breaks the widget API (but only for layouts). We didn't have "major" API breaks in quite a while. :-)

**Comment by blueyed** [comment]
Very nice! (for reference: [the branch / diff](https://github.com/awesomeWM/awesome/compare/master...psychon:new_widget_system).  Can you create a PR for it to further discuss this (rebased on master), please?

I see that it conflicts with the stuff I am currently hacking on (DPI per screen), but that's OK and not too bad.  For one, it's good to move `wibox.layout.base` into `wibox.widget.base`.

Is it possible with the new system to be aware of different (DPI) resolutions per screen?

We've talked on IRC about it and I've hacked on passing `drawable` also to `:fit`, which is required for the textbox to get its position/screen (which can have different DPI values).  (In your new system this information might be useful in `widget:layout` and the before/after callbacks, too.)
This would make it necessary to add it as a cache key, too.  But just caching it also by the given drawable (object) would not invalidate the cache in case a drawable gets moved - so maybe it's geometry should be used/passed instead?!
I can also imagine some property/callback on the widget to indicate if this information (or some other) is relevant for `:fit`/`:draw` - so that it can be ignored for the cache.  But that might be too much and is not really necessary probably.
For the case at hand (DPI per screen), it would be enough to only have the screen or even DPI information available.

But given the new system, it might be already possible to just set the resolution somehow before/with the calls to `:fit` and `:draw` etc, so that the textbox layout would not have to do anything special, but inherit from it?

btw: it's cool that you removed the call to `widget:fit` from `base.check_widget`.

> It breaks the widget API (but only for layouts)

I see that old widgets are supported via the "Backwards compatibility" `widget::updated` signal.  I think a deprecation warning should be emitted for them (once for every widget).

**Comment by psychon** [comment]
Quick idea which I am not going to make friends with: Let's just drop these caches (for now?). As far as I know, they break Elv13's config and widget magic anyway. :-)

For rebasing these branches on master: I don't have that much time in near future, but I guess I should try "distilling" things that can be merged beforehand. For example getting rid of `wibox.layout.base` and I also had a PR for this `weak_connect_signal` AFAIR.

**Comment by blueyed** [comment]
> Let's just drop these caches (for now?)

Sounds not too bad.  They can be added later on, and given the new system should not be required anymore hopefully?!

> "distilling" things that can be merged beforehand

Sounds good!

> weak_connect_signal

It's in master already (61275cc).

**Comment by blueyed** [comment]
> For rebasing these branches on master: I don't have that much time in near future

I've looked at it: it's only 3 minor issues:

 - lib/wibox/layout/base.lua merge/renamed
 - a "trivial" conflict in lib/awful/widget/graph.lua
 - the new `lua.in` files should be renamed to `lua`

I've pushed the result to https://github.com/blueyed/awesome/tree/new_widget_system_rebased (comparison view to your branch: https://github.com/psychon/awesome/compare/master...blueyed:new_widget_system_rebased).
But as I've said, it's rather trivial to rebase it - and I might have messed up something..

**Comment by blueyed** [comment]
Some initial feedback: `make check` is failing:

    [ 33%] Built target awesome
    ●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●/usr/bin/lua5.2: error in __gc metamethod (/usr/local/share/lua/5.2/busted/status.lua:16: bad argument #1 to '?' (lgi.record expected, got userdata))
    /usr/bin/lua5.2: error in __gc metamethod (bad argument #1 to '?' (lgi.record expected, got userdata))
    CMakeFiles/check.dir/build.make:49: recipe for target 'CMakeFiles/check' failed

(using busted 2.0.rc10, --verbose for busted did not help)

    % sed -n 14,20p /usr/local/share/lua/5.2/busted/status.lua
    return function(inital_status)
      local objstat = get_status(inital_status)
      local obj = {
        success = function(self) return (objstat == 'success') end,
        pending = function(self) return (objstat == 'pending') end,
        failure = function(self) return (objstat == 'failure') end,
        error   = function(self) return (objstat == 'error') end,

Disabling the checks lets me run it.
The animation in the default config results in only ~50-60fps (not reaching the target of 60fps easily) for me.  With 20 fps, the CPU is at 30-40% already. (I am using a Lenovo X220t (Intel(R) Core(TM) i5-2520M CPU @ 2.50GHz).

**Comment by psychon** [comment]
The fit-cache is still important, since `:fit` is still (possibly) recursive.

I had another idea:
Somewhere (sorry, I don't find it right now and thus I'll write it here) you suggested to add a `dpi` argument to `fit` and `draw`. I would instead suggest the following: Add a `context` or `info` argument that replaces the current `wibox` argument. This is a table with things like `drawable`, `wibox`, `titlebar` and you could also add `dpi` in there. This table is saved in `wibox.drawable` and re-used between redraws. That way, `==` will say the table did not change and we can continue using the cache. If the DPI changes, we throw away the whole table and create a new one, so that `==` is no longer true.
As suggested in I-dont-remember-where, this table would not only be passed to `draw`, but also to `fit` etc.

This could already be implemented with the current widget system (and should likely be done independently of it, because it would also be a big change).

**Comment by blueyed** [comment]
> If the DPI changes, we throw away the whole table and create a new one

That's when you set a new DPI value?
How would that work to invalidate the cache in case of moving the drawable to another screen?

What I have locally already is passing around the drawable additionally for `:fit`.
This does not break the API, but `:fit` gets a new argument only.
Having a generic context sounds good, but might not be necessary (yet).
Wouldn't it work to add the `context`/`info` table to the `wibox` that gets passed around directly?  (And then pass that one also to `:fit`)

**Comment by psychon** [comment]
Well, the wibox is only a wibox if the widget is in a wibox. I don't know what it is for titlebars, but at one point I was evil and just had it pass around `nil`.

The cache already compares the arguments for equally (if you call fit with 100, 100 twice, the second call will return the result from the cache). So if we just add another argument (the table), it will also be compared for equality. So the cache still contains the old information, but it won't be returned from the cache since the argument isn't equal to what it should be.

So the cache isn't really ever cleared (well, the garbage collector will do so), instead we just make sure that values for other DPIs aren't returned from the cache.

**Comment by psychon** [comment]
Fixed in several parts. Some random pointer would be #435.
