### ISSUE TITLE
global_bydirection not honoring stacked option

### ISSUE THREAD

**Issue by basaran** [awesomeWM/awesome#3380]
Output of `awesome --version`:

awesome v4.3 (Too long)
 • Compiled against Lua 5.3.5 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2

**How to reproduce the issue:**

```lua
function focus.global_bydirection(dir, c, stacked)
    local sel = c or capi.client.focus
    local scr = get_screen(sel and sel.screen or screen.focused())

    -- change focus inside the screen
    focus.bydirection(dir, sel)

    -- if focus not changed, we must change screen
```

**Expected result:**

```lua
function focus.global_bydirection(dir, c, stacked)
    local sel = c or capi.client.focus
    local scr = get_screen(sel and sel.screen or screen.focused())

    -- change focus inside the screen
    focus.bydirection(dir, sel, stacked)

    -- if focus not changed, we must change screen
```

I can send a PR if you like.

**Comment by Elv13** [comment]
> I can send a PR if you like.

A PR would be welcome, thanks.

You can also try my https://github.com/elv13/collision module. It handles a lot more corner cases

**Comment by basaran** [comment]
I am already using your collision :) I ran into this while updating a module I'm building for machi-layout and wanted to keep it dependency free.
