### ISSUE TITLE
get_children_by_id

### ISSUE THREAD

**Issue by basaran** [awesomeWM/awesome#3383]
I'm trying to make sense of accessing the widgets once they are created. I tried `get_children_by_id` , get_children, get_all_children and so on yesterday and the better part of tonight and I don't know what I'm doing at this time.

This is the inspection of a titlebar I created on one of the clients. I obtained it with through a signal and wrote it to a file through signalling:

```lua
awful.titlebar(c, {position="bottom", size="14"})
```

[lua.txt](https://github.com/awesomeWM/awesome/files/6758351/lua.txt)

I use these titlebars to create tabs under each client as such:

![image](https://user-images.githubusercontent.com/30809170/124353466-b28bfb00-dbd4-11eb-8c43-704775866683.png)

![image](https://user-images.githubusercontent.com/30809170/124353519-f8e15a00-dbd4-11eb-9bd0-2c9952a25047.png)

Everything is working fine, except that I'm looking to find a way to alter colors, change markup and so on through signals.

I was partially able to do it when assigning the signals within the iteration where I create the wiboxes and reference them, but that creates duplicate signals as the tab logic gets updated, and next thing you know, I have 20 signals on a client doing the same thing.

I also couldn't disconnect them when the layout change and the client no longer needs tabs.

I think I need to attach a signal to the client, get the titlebar at the bottom, and then get those wiboxes and iterate over them. The last part I'm not sure. Could you share some insight?

**Comment by basaran** [comment]
Hello, I just made a short video of the tabbed layout I'm working on. I addressed most of the edge cases to update tab bars when doing shuffling, shifting and swapping between layout-machi's regions and I was also able to retain the order of tabs when moving in and out by keeping a global state. Bling gave me the idea to use such tabs and it plays nicely with layout-machi's manual tiles.

If I can figure out how to access the textbox properties without overloading signals, I will be able to add unfocused color change (the purple indicator should go gray once out of focus), and titlebar name updates for people who prefer to have names in their tabs. For now, I set it to use class names.

https://user-images.githubusercontent.com/30809170/124367776-463ae700-dc28-11eb-8065-353fb9900edb.mp4

**Comment by actionless** [comment]
usually you just specify widget id inside the template first, so you could use such function to look it up from parent

**Comment by basaran** [comment]
Thank you, I'm going to look into it.

**Comment by basaran** [comment]
Thank you, I think I got it to work by putting the widgets in a table first assuming table values are referenced:

```lua
widget_ix[c.window][cc_ix] = tabs.create(cc, (cc == c), buttons, c_ix)
flexlist:add(widget_ix[c.window][cc_ix])
```
Then I was able to access the widgets through signals and get_children_by_id. Do you see any issues with this approach?

**Comment by actionless** [comment]
you creating your layout programmatically, get_children_by_id is more intended for template-based widget placement
