### ISSUE TITLE
Notification action callback receives nil notification

### ISSUE THREAD

**Issue by p-himik** [awesomeWM/awesome#3384]
Output of `awesome --version`:
```
awesome v4.3-1062-gd1c3394e4 (Too long)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • API level: 4
 • D-Bus support: yes
 • xcb-errors support: no
 • execinfo support: yes
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
 • Transparency enabled: yes
 • Custom search paths: no
```

Some background - I'm trying to create a notification action that, when clicked, would copy the notification's text to the clipboard.
This code was working on some earlier version of Awesome, but I have no clue when exactly it stopped working.
Perhaps, I've been using the notification actions functionality wrong all along.

**How to reproduce the issue:**
Add this code to your config:
```lua
local awful = require('awful')
local ruled = require("ruled")
local naughty = require('naughty')

local function request_rules()
  local copy_action = naughty.action({name = "Copy"})
  local function copy_action_cb(_action, notif)
    print("Copy notification action: ", notif)
  end
  copy_action:connect_signal("invoked", copy_action_cb)
  ruled.notification.append_rule({rule = {},
                                  properties = {append_actions = {copy_action},
                                                never_timeout = true,
                                                screen = awful.screen.preferred}})
end

ruled.notification.connect_signal("request::rules", request_rules)
```
Then:
- Restart Awesome
- Open any notification
- Click on "Copy" that should be within the notification
- Check `~/.xsession-errors`

**Actual result:**
It contains `Copy notification action: 	nil`

**Expected result:**
It should contain something like `Copy notification action: 	table: 0x55eac20468b0`.

**Comment by Elv13** [comment]
Hello,

Sorry for the delay. Great bug report BTW, the reproducer worked great.

Fix is in https://github.com/awesomeWM/awesome/pull/3438
