### ISSUE TITLE
c.fullscreen not working anymore

### ISSUE THREAD

**Issue by raven2cz** [awesomeWM/awesome#3392]
Actual awesome-git (built 07/12/2021):
```
        awful.key({ modkey }, "f", function (c)
                c.fullscreen = not c.fullscreen
                c:raise()
            end,
        {description = "toggle fullscreen", group = "client"}),

```
Stop working. 

I tried to check overriding of bindings, but it is correct. 

In addition, maximization attribute : c.maximized = not c.maximized  works. 

Fullscreen not.

**Comment by sclu1034** [comment]
Have you verified that nothing in your configuration is interfering?
Are there any error logs?

Both that hotkey and manually executing `c.fullscreen = true` work perfectly fine on current `master` and in my day-to-day setup.

<details>
<summary>Sidenote</summary>

The date should be good enough this time, as there was nothing merged recently that might affect this property.

But the issue template asks for the output of `awesome --version` for a reason, especially when running versions outside tagged releases. Knowing the specific git revision can be quite helpful to pin things down.

</details>

**Comment by raven2cz** [comment]
Sorry for your interruption. 

I tested one unstable library, which did not have cross-key mapping, but caused instability for fullscreen windows.

Yes, I will include awver for future.

Thanks for help.
