### ISSUE TITLE
Lots of dead links in the landing page of the api docs

### ISSUE THREAD

**Issue by psychon** [awesomeWM/awesome#3393]
- Go to https://awesomewm.org/apidoc/
- Click any link
- Get a 404

More specifically, none of the links here seems to work:

https://github.com/awesomeWM/awesome/blob/3dddc2ba78022c30fab9420b73a0453e845c273a/docs/config.ld#L38-L51

Edit: Git blame blames https://github.com/awesomeWM/awesome/commit/ac0aeb65c04a816d752c53eb4b51d0d65db831c5 which was written 11 months ago and commited four months ago. CC @Elv13 

Edit: This image is also broken:https://github.com/awesomeWM/awesome/commit/ac0aeb65c04a816d752c53eb4b51d0d65db831c5#diff-3ca94a4aac4f498fe4096af4093399744e1eb30164fbef7b072f420f8e41d9b3R34

**Comment by enderger** [comment]
The issue can be remedied by changing all `../doc` to `../apidoc` in the URIs.

**Comment by sclu1034** [comment]
Only partially, since it would need to be touched manually for releases, where the path is `doc/api/`.
