### ISSUE TITLE
gnome-terminal initialized with garbage on startup

### ISSUE THREAD

**Issue by vitek** [awesomeWM/awesome#3403]
Output of `awesome --version`:

actually its pretty old bug. I was able to reproduce it with 4.3 and latest git versions.
 
It also seems that it does not depend on type of video card. Can reproduce on intel, amd and nvidia cards.

**How to reproduce the issue:**

Open gnome-terminal window in tiled mode few times.

**Actual result:**

Terminal window is initialized with some kind of garbage but I still can see background

**Expected result:**

No garbage on terminal window.

`--no-argb` solves the issue instead of garbage terminal is painted black. But I don't wanna use it since it breaks some other applications.

Small video of how it looks (sorry for quality): https://www.youtube.com/watch?v=jYWpr-q8v2A  

Please help to find an issue I can help with resolving/testing it.

Thank you!

**Comment by Elv13** [comment]
Maybe you can mitigate it using picom or compton? Applications being buggy when given ARGB surfaces without a compositor isn't something we can really fix on our side.

**Comment by vitek** [comment]
I'm already using compton it does not help. Will take a look at picom. Thank you!

**Comment by vitek** [comment]
picom doesnt help with glx backend. Do you have recommendation for picom config?

**Comment by vitek** [comment]
it seems that `fading = true;` helps to hide application initial screen. Thanks!
