### ISSUE TITLE
Clients moving to other screens when no other client is in focus

### ISSUE THREAD

**Issue by brokenax3** [awesomeWM/awesome#3404]
Output of `awesome --version`:
```
awesome v4.3-1066-g832483dd6 (Too long)
 • Compiled against Lua 5.3.6 (running with Lua 5.3)
 • API level: 4
 • D-Bus support: yes
 • xcb-errors support: no
 • execinfo support: yes
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
 • Transparency enabled: yes
 • Custom search paths: no
```

**How to reproduce the issue:**
1. Open an application on screen 2
2. Move mouse cursor to a tag on screen 1 which either does not have an application open or the mouse has yet to focus on an application and click on the tag

**Actual result:**
The application on screen 2 moves to screen 1.

**Expected result:**
The application on screen 2 remains on the same screen and tag.

Here is a video of the scenario

https://user-images.githubusercontent.com/53488602/128455563-3cda21b6-660f-49cc-b0b9-e6a4266cb52b.mp4

I am unsure if this was mentioned before but I was not able to find a solution for this.

**Comment by sclu1034** [comment]
Assuming that your dotfiles on GitHub are up-to-date, this is the problem:

```lua
-- modkey == nil
awful.button({ }, 1, function(t) t:view_only() end),
awful.button({ modkey }, 1, function(t)
                                if client.focus then
                                    client.focus:move_to_tag(t)
                                end
                            end),
```

(https://github.com/brokenax3/didactic-configs/blob/master/config/awesome/widgets/bar.lua#L99-L104)

Since you never define `modkey`, both `awful.button` fire on mouse click without modifiers.

**Comment by brokenax3** [comment]
Thanks for your reply.

 I realised that I only defined modkey on the file containing my other keybindings which was why both those actions fire in an unpredictable way.

This solved a problem that was bugging me for awhile.

**Comment by Aire-One** [comment]
This kind of error makes me think we should have some actions in the scope of #3395 or #3131 to provide some environment with a working linter... 🤔

**Comment by actionless** [comment]
`awesome --check` wouldn't catch such?

**Comment by sclu1034** [comment]
An undefined global simply evaluates to `nil` and does not produce any error or warning. It's just a field in a table, after all.
