### ISSUE TITLE
Unable to set or use keybindings

### ISSUE THREAD

**Issue by YJH16120** [awesomeWM/awesome#3406]
Output of `awesome --version`:

awesome v4.3 (Too long)
 • Compiled against Lua 5.3.5 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2

**How to reproduce the issue:**

1. Add these key bindings anywhere in the `gears.table.join()` function.
```lua
    awful.key({ modkey }, "=", function() awful.spawn(Scripts .. "/backlight.fish +") end,
              { description = "Increase brightness", group = "Custom scripts"}),

    awful.key({ modkey }, "-", function() awful.spawn(Scripts .. "/backlight.fish -") end,
              { description = "Decrease brightness", group = "Custom scripts"}),
```
2. Create a fish file in your `~/.config/fish/functions` and name it `backlight.fish` and fill it with this, install fish, and brightnessctl if it's not installed.
```
function backlight -a operation
    set curr (brightnessctl g)

    if test $operation = "-"
        set new_brightness (math $curr - $curr x 0.1)
    else
        set new_brightness (math $curr + $curr x 0.1)
    end

    brightnessctl set $new_brightness
    echo $new_brightness
end
```
3. Add this line somewhere in rc.lua `Scripts = "fish /home/<your user name>/.config/fish/functions"`,
4. Reload awesome

**Actual result:**

Unable to set new keybindings. Occasionally getting an error at line 519 whenever awesome is restarted, so here is the block of code around line 519
```lua
-- {{{ Rules
-- Rules to apply to new clients (through the "manage" signal).
awful.rules.rules = {
    -- All clients will match this rule.
    { rule = { },
      properties = { border_width = beautiful.border_width,
                     border_color = beautiful.border_normal,
                     focus = awful.client.focus.filter,
                     raise = true,
                     keys = clientkeys,
                     buttons = clientbuttons,
                     screen = awful.screen.preferred,
                     placement = awful.placement.no_overlap+awful.placement.no_offscreen
     }
    },

    -- Floating clients.
    { rule_any = {
        instance = {
          "DTA",  -- Firefox addon DownThemAll.
          "copyq",  -- Includes session name in class.
          "pinentry",
        },
        class = {
          "Arandr",
          "Blueman-manager",
          "Gpick",
          "Kruler",
          "MessageWin",  -- kalarm.
          "Sxiv",
          "Tor Browser", -- Needs a fixed window size to avoid fingerprinting by screen size.
          "Wpa_gui",
          "veromix",
          "xtightvncviewer"},

        -- Note that the name property shown in xprop might be set slightly after creation of the client
        -- and the name shown there might not match defined rules here.
        name = {
          "Event Tester",  -- xev.
        },
        role = {
          "AlarmWindow",  -- Thunderbird's calendar.
          "ConfigManager",  -- Thunderbird's about:config.
          "pop-up",       -- e.g. Google Chrome's (detached) Developer Tools. <- This is line 519
        }
      }, properties = { floating = true }},

    -- Add titlebars to normal clients and dialogs
    -- { rule_any = {type = { "normal", "dialog" }
    --   }, properties = { titlebars_enabled = false }
    -- },

    -- Set Firefox to always map on the tag named "2" on screen 1.
    -- { rule = { class = "Firefox" },
    --   properties = { screen = 1, tag = "2" } },
}
-- }}}
```

**Expected result:**

Being able to set and use my keybindings

**Comment by sclu1034** [comment]
1. What is the exact error message?
2. What does "_occasionally_ getting an error at line 519" mean? Do you also get errors elsewhere, or does it work sometimes? What are you changing in your code to change the errors?
3. When adding those two calls to `awful.key`, did you do so at the end of the `gears.table.join` argument list? If so, did you make sure that the very last entry is not followed by a `,`?
   **Error:**
   ```
   gears.table.join(
     foo,
     bar,
   )
   ```
   **OK:**
   ```
   gears.table.join(
     foo,
     bar
   )
   ```

4. What does the code above `awful.rules.rules = {` look like?

**Comment by YJH16120** [comment]
> What is the exact error message?

![image](https://user-images.githubusercontent.com/44822875/128821613-6b720d6c-9f16-41b4-a253-4dcc83d46f5e.png)

> What does "occasionally getting an error at line 519" mean? Do you also get errors elsewhere, or does it work sometimes? What are you changing in your code to change the errors?

The error popup will say that an error occurred at line 519. It only gets an error there sometimes. The other lines have no issue like this.

> When adding those two calls to awful.key, did you do so at the end of the gears.table.join argument list? If so, did you make sure that the very last entry is not followed by a ,?

Yes, I have other keybindings aside from those two. 

> What does the code above awful.rules.rules = { look like?

https://paste.rs/2fa.lua just search for "<- 519" with ctrl+f. It will bring you to line 519.

**Comment by Aire-One** [comment]
```
/usr/share/awesome/lib/awful/spawn.lua:519: [...]
```

Means line 519 of file `/usr/share/awesome/lib/awful/spawn.lua`. Not 519 of your rc file.

The issue is then, how you used a function from the `awful.spawn` module, where it was expected you provide a `callback` parameter, but you didn't. (I didn't look at the full rc file you linked, it's a guess)

The full stack trace would help to identify the location of the issue in your rc file.
See : https://awesomewm.org/doc/api/documentation/90-FAQ.md.html "Where are logs, error messages or something?" section.

**Comment by YJH16120** [comment]
> ```
> /usr/share/awesome/lib/awful/spawn.lua:519: [...]
> ```
> 
> Means line 519 of file `/usr/share/awesome/lib/awful/spawn.lua`. Not 519 of your rc file.
> 
> The issue is then, how you used a function from the `awful.spawn` module, where it was expected you provide a `callback` parameter, but you didn't. (I didn't look at the full rc file you linked, it's a guess)
> 
> The full stack trace would help to identify the location of the issue in your rc file.
> See : https://awesomewm.org/doc/api/documentation/90-FAQ.md.html "Where are logs, error messages or something?" section.

So I got the full traceback, it's in a paste https://paste.rs/TC6

**Comment by sclu1034** [comment]
Looking at your `rc.lua`, the keybinds have nothing to do with the error.

If you scroll all the way to the bottom, this snippet produces the error message:

```lua
local startup = awful.spawn.easy_async_with_shell
startup("xinput set-prop 15 'Device Enabled' 0")
startup("fcitx")
startup("nitrogen --set-zoom-fill --random /home/yjh/Pictures/Backgrounds/")
```

If you check the [documentation on `awful.spawn.easy_async_with_shell`](https://awesomewm.org/apidoc/libraries/awful.spawn.html#awful.spawn.easy_async_with_shell), you'll notice that it expects two parameters. The command to run and a function that will be called with the results of that command.
You don't provide that second parameter, which triggers the error.

Since you don't seem to need such a callback here, simply change it like this:

```diff
-local startup = awful.spawn.easy_async_with_shell
+local startup = awful.spawn.with_shell
```

**Comment by YJH16120** [comment]
I see, before the reason I went it the `easy_async` one was because `spawn.with_shell` wasn't working. But it seems to be working now, and the error is also gone. However, the keybindings for increasing or decreasing the brightness still doesn't work. So this is what I have in awesome
```lua
    awful.key({ modkey }, "=", function() awful.spawn(Scripts .. "/backlight.fish +") end,
              { description = "Increase brightness", group = "Custom scripts"}),

    awful.key({ modkey }, "-", function() awful.spawn(Scripts .. "/backlight.fish -") end,
              { description = "Decrease brightness", group = "Custom scripts"}),
```
And the `backlight.fish` looks like this
```
function backlight -a operation
    set curr (brightnessctl g)

    if test $operation = "-"
        set new_brightness (math $curr - $curr x 0.1)
    else
        set new_brightness (math $curr + $curr x 0.1)
    end

    brightnessctl set $new_brightness
    echo $new_brightness
end
```

**Comment by Aire-One** [comment]
Nice to hear you managed to fix errors in the rc.lua.

Regarding your fish script, I'm not familiar with fish, but I guess you also need to call the function on your script... For now, the script only defines a function and invoke nothing...

https://fishshell.com/docs/current/tutorial.html#functions

I think it should be read like this :

```
# declare a function 
function say_hello
     echo Hello $argv
  end

# invoke it 
say_hello
```

**Comment by Aire-One** [comment]
Sorry for double post.

After reading https://github.com/Hummer12007/brightnessctl

You can invoke brightnessctl with a "delta value" :

```
Operations:
  s, set VALUE			set brightness of the device.
Valid values:
  specific delta		Example: 50- or +10
```

I think it would be a lot easier to drop the fish script and invoke brightnessctl directly from awesome :

```lua
-- Increase brightness 
awful.spawn("brightnessctl set +1")

-- decrease brightness 
awful.spawn("brightnessctl set 1-")
```

**Comment by YJH16120** [comment]
> Regarding your fish script, I'm not familiar with fish, but I guess you also need to call the function on your script... For now, the script only defines a function and invoke nothing...

The way fish works is that if I place a fish file in `~/.config/fish/functions`, I can call that function at any point whenever I'm using fish. So I can write `backlight +` to increase the brightness, and vice versa.

> I think it would be a lot easier to drop the fish script and invoke brightnessctl directly from awesome

I see, so that means I'd need to have all the logic from my fish function to be migrated inside a function within `rc.lua` correct?

**Comment by Aire-One** [comment]
> > Regarding your fish script, I'm not familiar with fish, but I guess you also need to call the function on your script... For now, the script only defines a function and invoke nothing...
> 
> The way fish works is that if I place a fish file in `~/.config/fish/functions`, I can call that function at any point whenever I'm using fish. So I can write `backlight +` to increase the brightness, and vice versa.

Oh ok, I didn't know fish do that. Thanks for the explanation! 

I, however, don't think it would work with `awful.spawn` as this function will spawn a new process to run the script. It wouldn't know about your fish config... 
Maybe with `awful.spawn_with_shell` (or by calling your command with `fish <your function>` instead of the script path) ? 🤷‍♂️ 

> > I think it would be a lot easier to drop the fish script and invoke brightnessctl directly from awesome
> 
> I see, so that means I'd need to have all the logic from my fish function to be migrated inside a function within `rc.lua` correct?

Correct my if I'm wrong, but your script is basically : "if I'm called with `-`: decrease the brightness, else increase the brightness". 

My suggestion was to directly call `brightnessctl` from your keybindings function with `awful.spawn`. I don't think you need to implement any further business logic. It should be as simple as that. 

> -> So the answer for this is yes. It's working now.

I think you find your way! Happy to hear that ☺

**Comment by YJH16120** [comment]
> I, however, don't think it would work with awful.spawn as this function will spawn a new process to run the script. It wouldn't know about your fish config...

That's a good point. I never thought about that before. I'll experiment with this further.

> Correct my if I'm wrong, but your script is basically : "if I'm called with -: decrease the brightness, else increase the brightness".

Yup, that's exactly what it does.

> My suggestion was to directly call brightnessctl from your keybindings function with awful.spawn. I don't think you need to implement any further business logic. It should be as simple as that.

That's true. But I already have the logic written down lol
