### ISSUE TITLE
Quick question. Regaring root element

### ISSUE THREAD

**Issue by leier69** [awesomeWM/awesome#3407]
Hi!

I was just wondering what root means in awesome?  the doc site https://awesomewm.org/doc/api/libraries/root.html
does not answer my questions.

I see a couple of pro looking setups setting root variables for functions and theme and such. What really is the root element and what does it do?

**Comment by Aire-One** [comment]
This class is an abstraction over the X.org root window. Long story short, see it as the window that contains all your windows, aka your desktop/wallpaper.

https://en.m.wikipedia.org/wiki/Root_window

As of, "what it does?", basically anything you want, wallpaper related: with the default rc.lua it's used to define the right click menu on the wallpaper and global keybindings for example.
It can also use it to send "fake_input" to other clients.
