### ISSUE TITLE
Add status icons to tasklist without adding client name

### ISSUE THREAD

**Issue by dylanpjx** [awesomeWM/awesome#3408]
Awesome V4.3

I'm trying to switch to a tasklist that only shows client icons in the wibar as shown here:
![image](https://user-images.githubusercontent.com/42106466/129044349-8df061f4-ffbe-4cfd-bf85-9ff3eb39589e.png)

Is there a way to continue displaying client status icons ([as shown at the top of this page](https://awesomewm.org/doc/api/classes/awful.widget.tasklist.html)) on a tasklist like mine? From the docs linked, I presume that the status icons are only prepended to the client name.

The code for my tasklist is here:
```lua
    s.mytasklist = awful.widget.tasklist {
      screen   = s,
      filter   = awful.widget.tasklist.filter.currenttags,
      buttons  = tasklist_buttons,
      style    = {
        shape = gears.shape.rounded_rect,
      },
      layout   = {
        spacing = 5,
        layout  = wibox.layout.fixed.horizontal
      },
      -- Notice that there is *NO* wibox.wibox prefix, it is a template,
      -- not a widget instance.
      widget_template = {
          {
            {
              id     = 'clienticon',
              widget = awful.widget.clienticon,
            },
            margins = 1,
            left = 12,
            widget  = wibox.container.margin,
          },
          id = 'background_role',
          forced_width = 48,
          widget = wibox.container.background,
          create_callback = function(self, c, index, objects) --luacheck: no unused args
            self:get_children_by_id('clienticon')[1].client = c
          end,
        },
      }

```

**Comment by sclu1034** [comment]
`awful.tasklist` can't do that. The status indicator is build into the `text_role`.
But you can always build it yourself.

The default code for those status icons just checks a few properties like `c.sticky`, then changes the display text accordingly.
Similarly, you can add an additional `wibox.widget.imagebox` or `wibox.widget.textbox` and change its content in an `update_callback`, based on whatever client properties you want to visualize.

**Comment by dylanpjx** [comment]
Hi, I'm not that proficient in theming the wibar so I have a few questions.

Is it possible to update the status using the `create_callback()` function inside my current tasklist? Something like (Pseudo code):
```lua
wiget_template {
  widget = wibox.widget_textbox(text=status)
  widget = awful.widget.clienticon
  ...
  create_callback = function(self, c, index, objects) --luacheck: no unused args
            self:get_children_by_id('clienticon')[1].client = c
            if (c.sticky) then
              status = '...'
            end
            ...
  end,
}
```

Or do I have to make an entirely separate widget outside of `s.mytasklist` and prepend that to the clienticon widget within?

**Comment by actionless** [comment]
here's a real-life example of doing the same thing but for taglist, for tasklist that would work the same:

https://github.com/actionless/awesome_config/blob/c394cf47c7e122a667295ff205b83d53219ad66c/config/widgets.lua#L259-L293

**Comment by dylanpjx** [comment]
Thank you for the example, it really helps a lot!
