### ISSUE TITLE
Use a fallback icon in the taskbar when none is found for a given application

### ISSUE THREAD

**Issue by qsmodo** [awesomeWM/awesome#3411]
```
awesome v4.3 (Too long)
 • Compiled against Lua 5.1.5 (running with Lua 5.1)
 • D-Bus support: ✘
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
```

**How to reproduce the issue:**

Launch a program that has no icon, e.g. `xmessage X`, `st`, `urxvt`.

**Actual result:**

The tasklist shows the program title only, but not its icon.

**Expected result:**

A user-defined default, fallback icon would be used. Or perhaps (but this would probably take much work) Awesome could set icons based on matches on class/instance names in `rc.lua`.

**Background:**

I have set up `rc.lua` as described in the 2nd code-block of [Class awful.widget.tasklist](https://awesomewm.org/doc/api/classes/awful.widget.tasklist.html) such that now I only see the window icons in the taskbar, not their names. Clearly this poses a problem when the window does not have an icon.

Setting `icon_theme` just won't do because some windows just don't have icons.

**Comment by Aire-One** [comment]
> I have set up rc.lua as described in the 2nd code-block of Class awful.widget.tasklist such that now I only see the window icons in the taskbar, not their names. Clearly this poses a problem when the window does not have an icon.

It means you should have defined your `widget_template` parameter to the `tasklist` widget this way :

```lua
    widget_template = {
        {
            wibox.widget.base.make_widget(),
            forced_height = 5,
            id            = 'background_role',
            widget        = wibox.container.background,
        },
        {
            {
                id     = 'clienticon',
                widget = awful.widget.clienticon,
            },
            margins = 5,
            widget  = wibox.container.margin
        },
        nil,
        create_callback = function(self, c, index, objects) --luacheck: no unused args
            self:get_children_by_id('clienticon')[1].client = c
        end,
        layout = wibox.layout.align.vertical,
    },
```

This widget template uses the `awful.widget.clienticon` as the icon you see on your bar, and is initialized by the `create_callback` that basically give the client as a reference to the clienticon widget. (See: https://awesomewm.org/doc/api/classes/awful.widget.clienticon.html)

Given you play with clients that doesn't define icon, it sounds like normal behavior to me that the tasklist widget can't find an icon to use.

I think there are two possible way to resolve this issue :

* Change the `create_callback` callback to detect client with no icon and use your own default icon ;
* Find a way to use custom icons as clienticon (maybe this discussion from Reddit can help you to get started? https://www.reddit.com/r/awesomewm/comments/n8ehwg/add_icon_on_tasklist_for_client_with_no_icon/)

**Comment by qsmodo** [comment]
Alright, since I have no experience with Lua I think I visibly underestimated its powers. Thanks for your suggestions, I'll look into them and if I can come up with a solution I'll post it here.

**Comment by qsmodo** [comment]
The solution proposed by u/kolo1337 [in that first Reddit link](https://libredd.it/r/awesomewm/comments/n8ehwg/add_icon_on_tasklist_for_client_with_no_icon%D9%84%D8%A5/) solved it. Reproducing it here for convenience:
```
client.connect_signal("manage", function(c)
    local cairo = require("lgi").cairo
    local default_icon = "/path/to/fallback/icon.png"
    if c and c.valid and not c.icon then
        local s = gears.surface(default_icon)
        local img = cairo.ImageSurface.create(cairo.Format.ARGB32, s:get_width(), s:get_height())
        local cr = cairo.Context(img)
        cr:set_source_surface(s, 0, 0)
        cr:paint()
        c.icon = img._native
    end
end)
```
I also got rid of the `sleep` command, it does not seem to be required.
