### ISSUE TITLE
Question! How do undo tag.connect_signal without restart.

### ISSUE THREAD

**Issue by leier69** [awesomeWM/awesome#3414]
Hi!

I'm making it so awesome disable borders and rounded corners when there is only one client in a certain tag. But my question is, If I want to remove this signal or "function i just attached to a signal". HOW?

I've Tried disconnect_signal, but cant figure it out.

```
        tag.connect_signal("untagged", function(t)
            if #t:clients() == 1 then
                t:clients()[1].border_width = 0
                t:clients()[1].shape = gears.shape.rect
            end
        end)
```

If my question is a bit unclear. Im trying to toggle between these two during runtime (without restarting awesome):

```
        tag.connect_signal("untagged", function(t)
            if #t:clients() == 1 then
                t:clients()[1].border_width = 0
                t:clients()[1].shape = gears.shape.rect
            end
        end)
```

** KEYPRESS **

```
        tag.connect_signal("untagged", function(t)
            if #t:clients() == 1 then
                t:clients()[1].border_width = 2
                t:clients()[1].shape = gears.shape.rounded_rect
            end
        end)
```

All help is very appreciated. I'm stuck

**Comment by jcrd** [comment]
To later disconnect the signal function, define it outside of the `connect_signal` call:

```lua
local function untagged(t)
    if #t:clients() == 1 then
        t:clients()[1].border_width = 0
        t:clients()[1].shape = gears.shape.rect
    end
end

tag.connect_signal("untagged", untagged)
```

Then use:
```lua
tag.disconnect_signal("untagged", untagged)
```

**Comment by leier69** [comment]
so its not possible to connect it with a generic function?

        tag.connect_signal("untagged", **function(t)**
            if #t:clients() == 1 then
                t:clients()[1].border_width = 0
                t:clients()[1].shape = gears.shape.rect
            end
        end)

**Comment by Aire-One** [comment]
> so its not possible to connect it with a generic function?
> 
>         tag.connect_signal("untagged", **function(t)**
>             if #t:clients() == 1 then
>                 t:clients()[1].border_width = 0
>                 t:clients()[1].shape = gears.shape.rect
>             end
>         end)


What you use here is called an anonymous function. https://en.m.wikipedia.org/wiki/Anonymous_function

It's a useful design when you don't need to reuse the given function. However, when you need to reference the function multiple times, you have to associate it to an identifier.

Both way are valid, as @jcrd showed with a function definition, or with a variable to hold the anonymous function `local untagged = function(t)... end`.

You need to remember that `connect_signal` and `disconnect_signal` functions both take a function reference as parameter. If the identifier you use when calling disconnect is not part of the registrated identifiers from connect_signal, you'll not disconnect anything. You have to ensure you function identifiers are the same.

**Comment by Aire-One** [comment]
Sorry for double post...

As an alternative, you could simply use a flag to change the behavior of your signal callback :

```lua
        tag.connect_signal("untagged", function(t)
            if #t:clients() == 1 then
                t:clients()[1].border_width = flag and 2 or 0
                t:clients()[1].shape = flag and gears.shape.rounded_rect or gears.shape.rect
            end
        end)
```

And your event to toggle the behaviors would basically be defined as `flag = not flag`.

**Comment by actionless** [comment]
@Aire-One that was first idea, but next i've realized what afterwards you'll have to explain how to store that 'flag' per tag and etc :)

**Comment by leier69** [comment]
Haha Thanks guys! I really appreciate the help! love both Awesomewm and the community, super friendly people!

I'll close the issue.
