### ISSUE TITLE
Extra Mouse Button not Working

### ISSUE THREAD

**Issue by bijanbina** [awesomeWM/awesome#3422]
awesome v4.3 (Too long)
 • Compiled against Lua 5.3.5 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2

**How to reproduce the issue:**

I want to switch tags with 8 and 9 button key on my mouse. but look like awesome doesn't detect any mouse key beyond 5, Is there any way that you know to help me fix this.

- The rc.lua lines that I used for this. with 4(scroll up) and 5(scroll down) key these works.

- In `xev` I can confirm that 8 and 9 button on mouse works.
- Used mouse: Logitech G502

```
root.buttons(gears.table.join(
    awful.button({ }, 3, function () mymainmenu:toggle() end),
    awful.button({ }, 8, awful.tag.viewprev),
    awful.button({ }, 9, awful.tag.viewnext)
))
```

**Comment by mattplm** [comment]
Hello, it works fine for me.

Can you explain what you are expecting ? `root.buttons` is for buttons on the root window aka the background (see https://awesomewm.org/doc/api/libraries/root.html#buttons). 

I'm going to make an assumption and say you are looking to change bindings on the taglist (sorry if this is wrong). If this is the case, you want to look for this in the default conf : https://awesomewm.org/doc/api/classes/awful.widget.taglist.html#awful.taglist

**Comment by sclu1034** [comment]
As mattplm explained, buttons assigned to the root window (also known as desktop or wallpaper) only come into play when the mouse hovers that window.
To have these keys active while using regular clients, you'll have to add these callbacks to buttons assigned to those clients (in the default `rc.lua` that's `clientbuttons`) as well.

**Comment by bijanbina** [comment]
Thanks @sclu1034  and @mattplm Yes I figured it out. Sorry for the bother.
