### ISSUE TITLE
Wrong Properties.GetAll dbus method implementation causing freezes

### ISSUE THREAD

**Issue by wereii** [awesomeWM/awesome#3424]
Output of `awesome --version`:

```sh
awesome v4.3 (Too long)
 • Compiled against Lua 5.3.5 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
```

**How to reproduce the issue:**

Run:
```sh
dbus-send --session --dest=org.freedesktop.Notifications --print-reply /org/freedesktop/Notifications org.freedesktop.DBus.Properties.GetAll string:"org.freedesktop.Notifications"
```

**Actual result:**

Times out with no response (essentially blocking anything that would do a call like above)

**Expected result:**

Valid reply for org.freedesktop.DBus.Properties.GetAll should be returned **OR** `org.freedesktop.DBus.Error.UnknownMethod` reply if method not supported.

**Note:**

See https://github.com/blueman-project/blueman/issues/1508 where in combination with blueman (blueman-applet/-tray?) waiting for the reply it seems to cause freeze of whole awesome.
I am guessing it blocks the "receiving side of desktop events " as the mouse still moves but for few seconds there is no reaction to any clicks or keyboard but my panel indicators like network speed and memory are still being updated.

**Comment by wereii** [comment]
I was pondering and looking around to see if I can find something and fix this. I was obviously looking at Awe's dbus implementation, mainly searching if some kind of dbus handlers aren't silently ignoring unknown Interfaces/Methods (`org.freedesktop.DBus.Properties.*`).

Though I quickly found I don't want to deal with anything dbus related for the rest of my life.
I tried snipping out some parts of the Awesome's dbus implementation into separate dbus client to debug it but I wasn't even able to run it all, segfaults or freezes. Though I have a minimal clue how to Lua and even less how to use Gio dbus stuff (eg. I probably wasn't able to get some kind of gio(?) main loop running thru lgi).

**But!** I noticed after browsing my local installed `awesome/lib/naughty` that it is pretty different to current master and after installing latest master I can confirm that the `dbus-send` snippet does not timeout anymore and even properly returns `org.freedesktop.DBus.Error.UnknownMethod` for completely bogus calls like `org.freedesktop.DBus.Properties.GetAaaaa` which would timeout too.

Which resolved the issue from blueman with freezing etc. and everything is as snappy as new!

```sh
└[~]> awesome --version
awesome v4.3-1086-g13cd20780 (Too long)
 • Compiled against Lua 5.3.6 (running with Lua 5.3)
 • API level: 4
 • D-Bus support: yes
 • xcb-errors support: yes
 • execinfo support: yes
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
 • Transparency enabled: yes
 • Custom search paths: no
```

**Comment by Elv13** [comment]
Yeah, the old implementation wasn't that much robust. It's strange that it happens to you and not to other people.

So this is solved in git-master? We can close this?

**Comment by wereii** [comment]
> and not to other people

There is one more guy with the same setup and same problem over at the blueman issue. I obviously tested if the freeze occurs in default theme where it did.

Though, as far as I tested it seems to be resolved in current master so yeah, will close this. (Though can't wait for next release, master is buggy and some parts of my theme are throwing errors :smile: )

**Comment by Elv13** [comment]
> master is buggy and some parts of my theme are throwing errors

I am unaware of them. Could you open a new issue(s)?
