### ISSUE TITLE
Error happened when open show help

### ISSUE THREAD

**Issue by Kritiqual** [awesomeWM/awesome#3427]
Output of `awesome --version`:

awesome v4.3-1086-g13cd20780

**How to reproduce the issue:**

Hit super+s (default key binding)

**Actual result:**

Show error : "/usr/share/awesome/lib/gears/table.lua:118: bad argument #1 to 'for iterator' (table expected, got nil)"

**Expected result:**

Show help table

**Comment by sclu1034** [comment]
Can you post the full error stack trace from the log?
See section "Where are logs, error messages or something?" in the [FAQ](https://awesomewm.org/doc/api/documentation/90-FAQ.md.html) on how to find the log file.

**Comment by Kritiqual** [comment]
Hi, sorry for late response, but it show nothing

**Comment by Kritiqual** [comment]
In /dev/tty2   (with `ls -l /proc/$(pidof awesome)/fd/2`): Nothing
After run `exec /usr/bin/awesome >> ~/.cache/awesome/stdout 2>> ~/.cache/awesome/stderr`:
  - In ~/.cache/awesome/stdout: Nothing
  - In ~/.cache/awesome/stderr: E: `awesome: acquire_WM_Sn:304: another window manager is already running (select opm owned); use --replace`)

**Comment by Elv13** [comment]
Hi. You can launch `awesome` with `--replace` from a terminal and the output should be there. You could also try to setup Xephyr. The only way the error you have is in the popup is if there is a larger version in the logs.

**Comment by Aire-One** [comment]
I think I have already faced this issue. I never took the time to investigate it, tho...

My quick fix was to use a function callback to call the key pop-up. I think, when the key pop-up function is used as the callback for keybindings, it can receive contextual parameters from keybindings. Or something like that...

**Comment by actionless** [comment]
could it be due to using old rc.lua with new awesome-git?

**Comment by Kritiqual** [comment]
Hi, i fixed this!
I replace my keybinding with the one from default rc.lua in `/etc/xdg/awesome/`
