### ISSUE TITLE
Is there any difference between io.open and synchronous Gio operations?

### ISSUE THREAD

**Issue by actionless** [awesomeWM/awesome#3430]
I've noticed what gears.filesystem is using Gio synchronously

I wonder if it have any benefits over blocking io.open and if it's planned to add async versions there instead?

**Comment by Elv13** [comment]
I looked into it many time, but never quite got a future proof API module. My config has `fd_async` and I also had my out of tree `wirefu` module. At some point I had a non working prototype of `gears.async`, but it isn't even in tech preview mode. It mostly worked like:

```lua
-- Magic module to wrap the function in a lot of magic. This way some APIs can
-- auto detect they are in async mode and swaich code paths.
gears.async(function()
    local content = gears.filesystem.whatever() --auto detect it's in async mode and just works

    gears.timer.delayed_call() -- no callback needed, it will just yield

    while true do
        os.sleep(5) --auto detect it's in async mode and just works

        local res = call_come_dbus_stuff() --auto detect it's in async mode and just works

        local f = io.popen("whatever") -- that could be made safe

        content = f:readall()

        local json = gears.network.download_json("www.example.com/foo.json") -- libcurl and json-glib wrapper
    end
end)
```

The `gears.async` wrapper works like my `gears.reactive` PR (some code actually came from there) and wrap coroutines. My monkey-patching some of the built-ins, you could even make them viable in the async wrapper. A couple years ago, when I was more active, I made some good progress toward eliminating all code running in the global context (all those `request::` blocks). In theory there could have been an async version of `connect_signal` and make synchronous code to asynchronous code section pretty painless.

I also have/had a skeleton of `gears.thread("module")` to add real (share-nothing) multi threading. That module pretty much create a new Lua context and expose a `gears.object` object to both side and they can `emit_signal`, `connect_signal` and use the property mechanism to share data. That module, I still dream of finishing up, but _really_ not before 4.4 is out. This is a pretty boring endeavor to integrate this... My plan is/was to couple it with a `gears.model` module and get rid of some of `awful.widget.common` code in favor something closer to Qt/GTK models. That would allow to implement global menus, HUDs, Rofi equivalent and other larger data structures which currently make AwesomeWM run like molass if you implement them in the main thread (async or not).

**Comment by actionless** [comment]
i see, thanks for insight on this

and getting back to original question, is there any practical difference between sync usage of Gio vs io.open/popen?

i just wondering because we might want to update the documentation, to not recommend just Gio, but async versions of Gio methods

**Comment by Elv13** [comment]
> is there any practical difference between sync usage of Gio vs io.open/popen?

Internally, yes, a lot. For the average person, not so much.

> to not recommend just Gio, but async versions of Gio methods

We would need to come up with a nice wrapper. Using async LGI -> Gio is very, very crashy when you don't do it exactly right. When it's done right, it can be made to not crash. But with `wirefu` and `fd_async`, I had "no fun" discovering what "right" is. LGI does a lot of undocumented magic to map them to Lua. This magic is beyond fragile. It's also not very portable. Some calls depend on the `GVFS` helper process and some don't. Obviously, this is totally undocumented and "we" must figure out when to start that helper process or things randomly stop working.

I don't think we can ever expect the average user to be able to "enjoy" using Gio directly.

**Comment by actionless** [comment]
do you mean smth like wrapping everything inside` gio.Async.start(do_protected_call)(function()`?

**Comment by Elv13** [comment]
I don't think "just" running something in `gio.Async.start` makes it async. Do you use the "real" async version of the Gio functions? But beside, I was referring to 2 things:

1) Keeping a blocking version of that function.
2) With the glib mainloop object, you can block and wait for events directly, so you can turn any async coroutine into a synchronous function. It's a hack, but it should work.

Reading https://www.freedesktop.org/software/gstreamer-sdk/data/docs/2012.5/glib/glib-The-Main-Event-Loop.html , I _think_ you need to get the look context and acquire it, then `g_main_context_iteration` it a few time, but the doc is pretty confusing, so it might do something completely different.

**Comment by actionless** [comment]
i meant to wrap async functions inside that thing to avoid side-effects which you mentioned before, or did i got it wrong?

**Comment by Elv13** [comment]
Ops, I think I posted the answer above in the wrong issue. Sorry for the noise

**Comment by actionless** [comment]
for example, like here: https://github.com/awesomeWM/awesome/blob/7ae6d26363442b246ca26e195bdaf3d8b91b58a8/lib/menubar/utils.lua#L405

**Comment by actionless** [comment]
so, here's an example of some sort of async gears.filesystem:

https://github.com/actionless/awesome_config/blob/a88af687a16eb1490b5f7130786def26c5c7bf45/actionless/util/filesystem.lua

**Comment by Elv13** [comment]
Here's some more https://github.com/Elv13/awesome-configs/blob/master/utils/fd_async.lua

But don't you think we should get a coroutine based API before making any of this public? Nested callbacks tend to turn into spaghetti code pretty fast while coroutine is just "normal code that happens to be magically async". We have very few callbacks in the current API (in favor of signals). Also, it's rather hard to integrate error handling with callbacks, especially when there is an undefined number of parameters to the callback (like dbus signals). My `fd_async` solves that by using signals instead of callbacks, but I never really liked that design either.

**Comment by actionless** [comment]
i'm not offering that interface design to awesome, but wondering if i got it right or does need any extra tricks (like that one from menubar module which i linked before)

**Comment by Elv13** [comment]
Yeah, it sure looks alright!

**Comment by actionless** [comment]
and is there any reason to wrap it inside `gio.Async.start` except for fixing pcall in older lua versions?

**Comment by Elv13** [comment]
I don't think it does anything if you use the callbacks, but I might be wrong.

**Comment by actionless** [comment]
ok, thanks for looking into it!

**Comment by actionless** [comment]
and regarding the docs, should we do anything or just close this?

**Comment by sclu1034** [comment]
> it's rather hard to integrate error handling with callbacks, especially when there is an undefined number of parameters to the callback

The common practice seems to be `callback(error, args...)`, e.g.

```lua
db.get_user(id, function(err, user)
	if err then
		error(string.format("Failed to fetch user %s", err.message))
		return
	end
	-- do something with user
end)
```

> Nested callbacks tend to turn into spaghetti code pretty fast 

Yeah, often referred to as "Callback Hell".

In addition to coroutines, common improvements are [Promises](https://promisesaplus.com/) or tools like [async.js](https://caolan.github.io/async/v3/).

Since Awesome's event loop isn't as sophisticated as node.js+libuv, Promises might not work as good as they do in node.js. But Lua implementations do exist, e.g. [zserge/lua-promises](https://github.com/zserge/lua-promises).
And we could certainly implement callback utilities from `async`, such as `async.waterfall` or `async.map`:

```lua
-- callback hell and manual iteration
db.get_user(1, function(err, user)
	if err then
		error(string.format("Failed to fetch user %s", err.message))
		return
	end

    db.get_events(user.id, function(err, events)
        if err then
            error(string.format("Failed to fetch events %s", err.message))
            return
        end

        local now = os.date()
        local index = 0
        local update_event = function(err)
            if err then
                error(string.format("Failed to update event %d %s", index, err.message))
                return
            end

            index = index + 1
            db.update_event(events[index].id, { time = now }, update_event)
        end
    end)
end)

-- async goodies give us a flat implementation and easy iteration
local now = os.date()
local function update_event(callback, event)
    db.update_event(event.id, { time = now }, callback)
end

async.waterfall({
    function(callback) db.get_user(1, callback) end.
    function(callback, user) db.get_events(user.id, callback) end,
    function(callback, events) async.map(events, update_event, callback) end,
}, function(err, _results)
    if err then
        error(string.format("An error ocurred: %s", err.message))
        return
    end

    -- if `db.update_event` returned something, that's now in `_results`
end)
```

Since I haven't used any coroutine-backed async library yet, I'm not sure how these would compare.

**Comment by Elv13** [comment]
> Since I haven't used any coroutine-backed async library yet, I'm not sure how these would compare.

The code would look like what I posted in my first comment. It isn't that hard to implement. It just takes a lot of time wrapping all of Gio to "really" fit the Lua cocoutine model. Then that extra layer of safety to make sure the users cannot shoot themselves in the foot and SIGSEGV AwesomeWM. If we take @actionless code, all it needs is to yeild after starting the call, then delayed-resume in the callback. This hides the callback from the user and all the see is "flat code". Still, it would take a lot of work to make an API that feels integrated with everything we have and be future proof.

> and regarding the docs, should we do anything or just close this?

I think we could close this. I am not really sure what the doc change would be. The Gio code is too complex for more users. The risk of guiding the users into writing code which can segfault AwesomeWM is too high.

**Comment by actionless** [comment]
just a final quick question then - are there any benefits of using sync Gio operations over their standard lua `io.*` counterparts?

**Comment by Elv13** [comment]
Quoting myself from earlier:

> Internally, yes, a lot. For the average person, not so much.

**Comment by actionless** [comment]
and what are the internal benefits of using it but synchronously?

**Comment by Elv13** [comment]
When you use a lot of LGI things, then it can use streams instead of reading the full file, then padding the content to the next thing. That makes things faster and uses less memory.

**Comment by actionless** [comment]
i see, thanks for clarifying @Elv13
