### ISSUE TITLE
Systray widget disappears when assigned to a monitor with `awful.widget.only_on_screen()`

### ISSUE THREAD

**Issue by Kirottu** [awesomeWM/awesome#3433]
Output of `awesome --version`:

```
awesome v4.3-1114-gee3c42652 (Too long)
 • Compiled against Lua 5.3.6 (running with Lua 5.3)
 • API level: 4
 • D-Bus support: yes
 • xcb-errors support: yes
 • execinfo support: yes
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
 • Transparency enabled: yes
 • Custom search paths: no
```

**How to reproduce the issue:**

Add the widget to the wibar like so:
`awful.widget.only_on_screen(wibox.widget.systray(), <screen num>)`, in my case the screen num was 2.

**Actual result:**

The widget would be nowhere to be seen.

**Expected result:**

The widget would be on the second display.

**Comment by sclu1034** [comment]
The systray widget already includes the `only_on_screen` functionality.
You can change its screen with
```lua
local mysystray = wibox.widget.systray()
mysystray:set_screen(screen[1])
```

**Comment by Kirottu** [comment]
Alright that works. Thanks!
