### ISSUE TITLE
Remove Travis from the PR "app" list and fix coverall.io

### ISSUE THREAD

**Issue by Elv13** [awesomeWM/awesome#3437]
I deleted the Travis App from the project, but it still shows up at the bottom of the PR. I also deleted the web hooks, but that also didn't work. Any idea how to remove it from that list?

![image](https://user-images.githubusercontent.com/340384/133703900-2ac0d7f3-53d1-43e6-8794-a54e2c7b1cdc.png)

Mergify can't merge the PR as long as this isn't fixed.

Also, mergify is gone from that list. It is still in the "Checks" list. I am not sure if this is an intentional upstream change or something we broke. That may not be related to the GitHub Action changes. I am pretty sure (but maybe I am imagining things) it was there at some point, but it's no longer there.

For coverall, I added the secret a few days ago

![image](https://user-images.githubusercontent.com/340384/133704019-e0a98bd9-5e33-4801-89e7-14ab1b7eabf3.png)

But it doesn't work.

**Comment by sclu1034** [comment]
Have you checked "Branches > Branch protection rules"? The Mergify summary suggests that it's defined there as well:
![image](https://user-images.githubusercontent.com/4508454/133780938-db6a9a6a-0656-48af-964f-3c58617f4167.png)

---

I just checked again, and noticed this in the "Secrets" repository settings:

> Secrets are not passed to workflows that are triggered by a pull request from a fork. [Learn more](https://docs.github.com/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets).

The linked docs page doesn't actually elaborate on this at all, though. [This blog post](https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/) mentions the situation briefly and suggests a `pull_request_target` trigger, but I'm not sure if that helps in our case.

The [Coveralls GitHub Action](https://github.com/coverallsapp/github-action) might be a solution, but I'm not sure if our tests generate the `lcov.info` that the action is looking for.

**Comment by Elv13** [comment]
@sclu1034 I merged the `wibar` PR earlier today, but the doc is still old. Any idea why? https://awesomewm.org/apidoc/popups_and_bars/awful.wibar.html

**Comment by sclu1034** [comment]
Presumably this line in the merge-commit run: https://github.com/awesomeWM/awesome/runs/3646217375?check_suite_focus=true#step:15:1017

I'm not sure why it fails with this particular message, though. The URL does include an actual GitHub token, it's just [replaced](https://github.com/awesomeWM/awesome/blob/master/.github/scripts/apidoc.sh#L139) in the output.
And GitHub shouldn't need to ask for a password when a token is given.

**Comment by sclu1034** [comment]
@Elv13 have you tried the other repository secret I mentioned in the GH Actions PR (`APIDOC_TOKEN`)?
As I said there, I did use the default `GITHUB_TOKEN` as a fallback, but it might now have permissions to write to the `apidoc` repo.

**Comment by psychon** [comment]
Random guess: Old PRs will keep these checks since "once upon a time", Travis reported a status for that PR. I just looked at the newest PR (#3443) and it only has actions, coveralls, mergify, CodeClimate, and codecov listed.

So... this issue can be closed?

**Comment by Elv13** [comment]
> So... this issue can be closed?

Not quite yet. I did what @sclu1034 proposed to remove the branch protection and it helped to remove Travis. But i/we still need to implement the documentation API key part of this ticket.

**Comment by Elv13** [comment]
@sclu1034 Hi, @blueyed (thanks!) provided a token for the @awesome-robot account. I made a change to the workflow to use it. The job "passed" (https://github.com/awesomeWM/awesome/runs/3794402254?check_suite_focus=true) but the doc isn't updated. What did I miss / can you take a look?

**Comment by sclu1034** [comment]
The issue might be these checks: `if [ "$PR_NUMBER" != false ]; then`.
Since the action is triggered by a `push` event, the `PR_NUMBER` envvar is empty. But I believe bash doesn't consider empty strings as `false`.

So the repo is updated, but the branch pushed to is `pr-`: https://github.com/awesomeWM/apidoc/tree/pr-
The log confirms that: https://github.com/awesomeWM/awesome/runs/3794402254?check_suite_focus=true#step:15:1142

And for the same reason, the very last line, that attempts to create a comment in a PR, fails, because it builds an invalid API URL. And since the script is not executed with `set -o pipefail`, that error is swallowed by the `| sed` and the script exists with `0`.

**Comment by Elv13** [comment]
Ok, did that, it got "somewhere", but no fireworks yet

```

2021-10-04T21:13:36.7353029Z [36;1m.github/scripts/apidoc.sh[0m
2021-10-04T21:13:36.7354460Z shell: /bin/bash -o errexit -o pipefail -o xtrace {0}
2021-10-04T21:13:36.7354922Z env:
2021-10-04T21:13:36.7355294Z   SOURCE_DATE_EPOCH: 1893456000
2021-10-04T21:13:36.7355758Z   AWESOME_VERSION: master-g3807ed8
2021-10-04T21:13:36.7356209Z   PR_NUMBER: 
2021-10-04T21:13:36.7357523Z   APIDOC_TOKEN: ***
2021-10-04T21:13:36.7357907Z ##[endgroup]
2021-10-04T21:13:36.7386268Z + .github/scripts/apidoc.sh
2021-10-04T21:13:36.7411030Z Post-processing (API) documentation.
2021-10-04T21:13:36.7411547Z PR Number: 
2021-10-04T21:13:36.7411919Z GITHUB_HEAD_REF: 
2021-10-04T21:13:38.3266966Z Cloning into 'build/apidoc'...
2021-10-04T21:13:41.6019138Z From https://github.com/awesomeWM/awesome
2021-10-04T21:13:41.6020894Z  * branch              master     -> FETCH_HEAD
2021-10-04T21:13:41.6111134Z fatal: '-3807ed83' is not a valid branch name.
2021-10-04T21:13:41.6113836Z EXIT CODE: 1
2021-10-04T21:13:41.6121836Z ##[error]Process completed with exit code 128.
```

**Comment by sclu1034** [comment]
Ah, now it runs into `elif [ "$GITHUB_HEAD_REF" != master ]; then`, but `$GITHUB_HEAD_REF` is also empty. Apparently, that one also only exists for `pull_request` targets.

Renaming `$GITHUB_HEAD_REF` to `$GITHUB_REF` and changing the check to `"$GITHUB_HEAD_REF" != "refs/heads/master"` might work.

**Comment by Elv13** [comment]
Yep, I pushed a fix for that. It worked this time!
