### ISSUE TITLE
pcmanfm-qt --desktop or other desktop managers do not behave as they should

### ISSUE THREAD

**Issue by yilkalargaw** [awesomeWM/awesome#3441]
Output of `awesome --version`:

awesome v4.3 (Too long)
 • Compiled against Lua 5.4.2 (running with 0.9.2)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: /usr/share/lua/5.4/lgi/version.lua

**How to reproduce the issue:**

launch "pcmanfm-qt --desktop" with the default configuration
or
launch "pcmanfm --desktop" with the default configuration

**Actual result:**

Instead of running as  a out of focus window in all tags it  appears as a fullscreen window.

**Expected result:**

running as  a out of focus window in all tags

**Comment by actionless** [comment]
you need to set https://awesomewm.org/doc/api/libraries/awful.rules.html for it to be above all windows and on all the tags

**Comment by yilkalargaw** [comment]
I need it to be beneath all windows since I want it to behave just like the desktop in xp or gnome2 era. I can not find a good rule for that.  It has the same window name and window class as the normal file manager  window of pcmanfm. Other window managers like xfwm and openbox can identify and make it behave normally though.

**Comment by yilkalargaw** [comment]
The following rule kind of takes care of the  window positioning issue but when I try to create a folder for example the dialogue box will appear only on the tag so I have to switch to that tag to give it a name.
```lua  
    { rule = { name = "pcmanfm-qt" },
        properties = { sticky = true, border_width = 0, focus=false} },
```
