### ISSUE TITLE
Unable to use regex in rules.rule.

### ISSUE THREAD

**Issue by sprnza** [awesomeWM/awesome#3444]
Hi there!
I'm unable to figure it out by myself, so please help. I'm trying to use a regexp inside rules.rule. It seems like it's being string.match used here,
```
    { rule_any = {
       instance = {
           "DTA",  -- Firefox addon DownThemAll.
           "copyq",  -- Includes session name in class.
       },
       class = {
           "zoom",
.... truncated
           "VirtualBox Manager",
         },
       name = {
           "Event Tester",  -- xev.
.... truncated
           "Volume Control",
           "^Slack | .*",
           "^Dev.*",

       },
       role = {
           "AlarmWindow",  -- Thunderbird's calendar.
           "Msgcompose",
           "pop-up",       -- e.g. Google Chrome's (detached) Developer Tools.
       }
     }, properties = { floating = true }},
```
Neither slack call window `"^Slack |"` nor Firefox Developer Tools `"^Dev"` get floating.
Although in Lua works:
```
sdg-dell ➜  ~ lua
Lua 5.4.3  Copyright (C) 1994-2021 Lua.org, PUC-Rio
> s="Developer Tools — New Issue · awesomeWM/awesome — https://github.com/awesomeWM/awesome/issues/new"
> string.match(s, '^Dev.*')
Developer Tools — New Issue · awesomeWM/awesome — https://github.com/awesomeWM/awesome/issues/new
```
Please help.

**Comment by ezz666** [comment]
You might miss that rules are applying only on application startup. I think it happens before firefox window gets the name you want to match.

**Comment by sprnza** [comment]
Yeah. Thank you. You're right. I've noticed that if I restart awesome with Devtools opened. The rule does get applied.
There is no way to workaround this?

**Comment by sprnza** [comment]
Found workaround [here](https://github.com/awesomeWM/awesome/issues/977). So I basically need to add a callback to the default rule `rule = { }` like this:
```
    callback = function(c)
      if not c.class and not c.name then
        local f
        f = function(_c)
            _c:disconnect_signal("property::name", f)
            if string.match(_c.name, "Dev") or string.match(_c.name, "Slack | ") then
                awful.rules.apply(_c)
            end
        c_:connect_signal("property::name", f)
        end
      end
    end
```

**Comment by sprnza** [comment]
I've found relevant information [here](https://github.com/awesomeWM/awesome/issues/977) but I wasn't able to figure out a working solution yet because the DevTools window does get NAME on windows creation, and it's not Devtools but Firefox, so I'll need to setup callback properly to process `property::name` signal.

**Comment by sprnza** [comment]
Due to I'd like to set "Slack Call" window to float adding callback to it's `property::name` signal is not possible because it's appeared that the title is being updated every second because of the call length being displayed. So I ended up with some logic based on new client creation (it's assumed for both Slack and Firefox only first "main" window is not managed by this and all others are set to float)
```
client.connect_signal("manage", function (c)
  local t = c.first_tag
  if c.class == "Slack" then
    local slack_count = 0
    for _, cl in pairs(t:clients()) do
      if cl.class == "Slack" then
        slack_count = slack_count +1
      end
    end
    if slack_count >= 2 then
      print("Send the new slack client to float")
      c.floating = true
    end
  end
  if c.class == "firefox" then
    local ff_count = 0
    for _, cl in pairs(t:clients()) do
      if cl.class == "firefox" then
        ff_count = ff_count +1
      end
    end
    if ff_count >= 2 then
      print("Send the new FF to float")
      c.floating = true
    end
  end
end)
