### ISSUE TITLE
test-screenshot.lua fails when it is run after another test.

### ISSUE THREAD

**Issue by ezz666** [awesomeWM/awesome#3458]
Found the way to reproduce the problem without running all the tests:
```sh
LUA='/usr/bin/lua5.3' ../tests/run.sh  ../tests/test-screen-changes.lua ../tests/test-screenshot.lua
```
It doesn't really matter which test to run before the screenshot. However running screenshot first works fine.

Edit: The problem arises from the first call of `get_pixel` function [here](https://github.com/awesomeWM/awesome/blob/1f84dbef184eab0538ad326969db24e94db3c1a7/tests/test-screenshot.lua#L110). The image size is 1024x768 and it doesn't depend on the previous test.

Edit2: It may be more convenient to move the discussion about the test to the separate issue.

_Originally posted by @ezz666 in https://github.com/awesomeWM/awesome/issues/3457#issuecomment-939135800_

**Comment by Elv13** [comment]
I tried to reproduce on a couple distros and "it works for me". That being said, it obviously doesn't work for you and probably a whole lot of other people. Can you clarify your distribution, glib, gdk, LGI and Lua versions? I will probably have to spawn a VM to reproduce it.

**Comment by ezz666** [comment]
Sure thing. It's a wired problem. I tried to reproduce it in gdb and both tests went through one after another on the same Xephyr instance without an error.

So lets see:

I run archlinux. It's up to date, I've updated it just before writing this message (still have the issue). I use the stock version of all the libraries you mentioned. I use bare minimum of AUR packages, so it's safe to assume that there are no dependencies from there.  

Here is the list of arch packages with versions:

- glib2 2.70.0-1
- gdk-pixbuf2 2.42.6-2
- lua53-lgi 0.9.2-3
- lua53 5.3.6-1

I'll also attach the part of CMake output. Just to see if it found correct libraries:
```
-- Found Lua: /usr/lib/liblua.so.5.3;/usr/lib/libm.so (found version "5.3.6") 
-- Using version from git: v4.3-1202-g1f84dbef
--   Found xcb, version 1.14
--   Found glib-2.0, version 2.70.0
--   Found gdk-pixbuf-2.0, version 2.42.6
--   Found cairo, version 1.17.4
--   Found x11, version 1.7.2
--   Found xcb-cursor, version 0.1.3
--   Found xcb-randr, version 1.14
--   Found xcb-xtest, version 1.14
--   Found xcb-xinerama, version 1.14
--   Found xcb-shape, version 1.14
--   Found xcb-util, version 0.4.0
--   Found xcb-util, version 0.4.0
--   Found xcb-keysyms, version 0.4.0
--   Found xcb-keysyms, version 0.4.0
--   Found xcb-icccm, version 0.4.1
--   Found xcb-icccm, version 0.4.1
--   Found xcb-xfixes, version 1.14
--   Found xcb-xkb, version 1.14
--   Found xkbcommon, version 1.3.1
--   Found xkbcommon-x11, version 1.3.1
--   Found cairo-xcb, version 1.17.4
--   Found libstartup-notification-1.0, version 0.12
--   Found xproto, version 7.0.33
--   Found xproto, version 7.0.33
--   Found libxdg-basedir, version 1.2.3
--   Found libxdg-basedir, version 1.2.3
--   Found xcb-xrm, version 1.3
-- Looking for backtrace_symbols
-- Looking for backtrace_symbols - found
-- checking for execinfo -- found
-- Looking for round
-- Looking for round - not found
-- Looking for round
-- Looking for round - found
-- checking for round -- in libm
--   Found dbus-1, version 1.12.20
--   Found xcb-errors, version 1.0
```

**Comment by ezz666** [comment]
> @ezz666 please confirm if you have gtk4 installed
I don't have it. To be sure:
```
> lgi = require('lgi')
> lgi.Gdk.version
3.0
> lgi.Gtk.version
3.0
```
Checked the branch but result is the same.

**Comment by actionless** [comment]
then, apparently, i was having locally an unrelated issue to your problem (which i can't reproduce then)

**Comment by ezz666** [comment]
Nope, I've checked it's size before, it turned out to be 1024x768 (it's a root window after all!).

I'm a bit concerned that one of the threads in `awesome` process exited before the test starts. Is it supposed to happen?
