### ISSUE TITLE
In Minecraft can't press more than 2 keys

### ISSUE THREAD

**Issue by Sudeep-Sharma0-0** [awesomeWM/awesome#3479]
awesome v4.3 (Too long)
 • Compiled against Lua 5.3.6 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2

Press more than two keys at once while playing games. I got the issue in Minecraft.

I installed awesome wm in vanilla arch recently. The dm is lightdm. Today I tried to play minecraft but while playing I noticed few bugs. Firstly I couldn't press more than 2 keyboard buttons at once. And the second one is if i am typing something in game like commands or chat and if i press backspace it deletes a whole word instead or a single character.

**Comment by Meister1593** [comment]
Not sure about second issue, but first one is defenitely not Awesome issue
it's very old and annoying bug that were resolved at least a year ago at GLFW side but minecraft still didn't update their libraries
https://bugs.mojang.com/browse/MC-122421 (it contains fix for that)

**Comment by actionless** [comment]
you can try with `openbox` instead of `awesome` - it's have very minimal code - so if smth is working there, but no in awesome - it would easier to guess why so

**Comment by Sudeep-Sharma0-0** [comment]
> Not sure about second issue, but first one is definitely not Awesome issue it's very old and annoying bug that were resolved at least a year ago at GLFW side but minecraft still didn't update their libraries https://bugs.mojang.com/browse/MC-122421 (it contains fix for that)

It didn't happened in i3 so I thought the wm is responsible

**Comment by actionless** [comment]
btw does it happen only in Minecraft?

**Comment by Sudeep-Sharma0-0** [comment]
> btw does it happen only in Minecraft?

yes it happens in minecraft only

**Comment by Meister1593** [comment]
have you tried launching pure config (you can make error on first line of rc.lua to trigger fallback config) and using master awesomewm @Sudeep-Sharma0-0 ?
