### ISSUE TITLE
key binding with ">" destroys hotkeys_popup

### ISSUE THREAD

**Issue by SHU-red** [awesomeWM/awesome#3480]
Output of `awesome --version`:

awesome v4.3 (Too long)
 • Compiled against Lua 5.3.6 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2

**How to reproduce the issue:**

Create Keybinding with "<" or ">" character-key like this
`awful.key({ modkey,           }, "<", function() ...`

**Actual result:**

category in hotkeys_popup which is set for the "<" or ">" keybinding is shown empty

**Expected result:**

No error and category is filled with all keybindings, defined for it

**Comment by mattplm** [comment]
Hey @SHU-red, In the hotkey popup, `<key1>/<key2>` indicates that you have bound key1 and key2 to the same description/group pair.

So you should have this somewhere in your config : 

```lua
awful.key({ modkey,           }, "r",
        <anything here>,
        {description = "BashKickstart", group = "custom"}),

**Comment by SHU-red** [comment]
Sorry!! My bad! You are absolutely right!
