### ISSUE TITLE
[ help/feature request ] toggle wibar on current tag only

### ISSUE THREAD

**Issue by gr523** [awesomeWM/awesome#3494]
Its very useful to toggle status bar for current tag/workspace only
For example pressing Super+Shift+b in tag2 will hide the wibar but it will be visible on other tags as usual
After looking into some configs, I understand that we could configure to toggle per screen but not sure how to go about toggling per tag

Also is there any search functionality in the hotkeys popup for keybindings ?
It would be nice if we could search with /word and matched entries will be highlighted

**Comment by gr523** [comment]
I figured it out but do tell me if it's the ideal workaround or not
```lua
local function checkWibarForTag(t)
    t.screen.mywibox.visible = t.barvisible
end

local function toggleWibarForTag()
    local t = awful.screen.focused().selected_tag
    t.barvisible = not t.barvisible
    checkWibarForTag(t)
end


for i,t in pairs(root.tags()) do
    t.barvisible = true
end

tag.connect_signal("property::selected",checkWibarForTag)
```

**Comment by Aire-One** [comment]
I don't think this is a feature we should ship in our API. It looks very specific to your use case.

I think your implementation is correct.
