### ISSUE TITLE
Is it possible that cursor can follow the  focused window?

### ISSUE THREAD

**Issue by hanqing0521** [awesomeWM/awesome#3496]
awesomeWM is a  wonderful WM. I very love it. However, when I use rofi to focus some window (softeware) the cursor can not move to the focused window. It is little imperfect. Is there any method to realize my demand?

**Comment by mattplm** [comment]
Hey, you can do that to move your cursor to the newly focused window (there may be better ways to do it though I don't know) : 

```lua
client.connect_signal("request::activate", function (c, s)
    local geo = c:geometry()
    mouse.coords {
        x = geo.x + math.ceil(geo.width /2),
        y = geo.y + math.ceil(geo.height/2)
    }
end)
```

**Comment by hanqing0521** [comment]
I also found a [solution](https://www.reddit.com/r/awesomewm/comments/gehk1g/cursor_follows_focus_possible/) through Google, however, I have three screens.
I copied your code in the rc.lua, it does not work.

This code can work, but not elegant enough
```lua
local function move_mouse_onto_focused_client()
    local c = client.focus 
	if c then
        local geometry = c:geometry()
        local x = geometry.x + geometry.width/2
        local y = geometry.y + geometry.height/2
        mouse.coords({x = x, y = y}, true)
    end
end

client.connect_signal("focus", move_mouse_onto_focused_client)
client.connect_signal("swapped", move_mouse_onto_focused_client)

local function go_to(tag_number, move_client)
	-- This will open "tag_number"
	local tags_dp = {1, 3, 6, 8, 10}
	local index = 0
	local tmp_screen
	local tag

	-- Look if tag_number is in the list
	while ((index < 5) and (tag_number ~= tags_dp[index])) do
		index = index + 1
	end

	-- Is the tag in the left screen?
	if (index < 5) then
		tmp_screen = 1
		mouse.coords({x = 960, y = 540}, true)
	else
		tmp_screen = 2
		mouse.coords({x = 2880, y = 540}, true)
	end

	tag = awful.tag.find_by_name(awful.screen[tmp_screen - 1], tostring(tag_number))

	-- Open the tag if possible
	if (tag and move_client == nil) then
		tag:view_only()
	else
		-- move the client to the tag
		client.focus:move_to_tag(tag)
	end

	awful.screen.focus(tmp_screen)
end
```

**Comment by basaran** [comment]
Hi, you can use the module I made:

https://github.com/basaran/awesomewm-micky

**Comment by hanqing0521** [comment]
It sounds good, and I will try your module, thanks.
Some thinking of me maybe you concern
1. We just want the cursor following the window when one uses some applications selector software like rofi, or some urgent window in awesome. 
2. The move cursor feature is important especially when one has two or more two monitors.
3. If the cursor always moves when a window is activated,  some cyclic moving trouble may appear. For example, some windows may have some problems that when one moves the cursor to touch the icons it may activate a window at a wrong position so that the cursor will move from one position to another position all time. Therefore, it is better to give an option to cancel the feature, or just let the cursor move to the focused window in some special condition.

**Comment by basaran** [comment]
AwesomeWM is Lua and she gives you classes and libraries to accomplish what your heart desires. It's not logical to include specific user needs into the standard library (that's why it's called standard).

That being said, I also needed such things you said hence put together the micky plugin. Look at the source code, the boilerplate is already there and with a little bit of Lua magic you can do anything and more.

**Comment by hanqing0521** [comment]
Yes, I read your code, it looks good.
I changed the code from https://github.com/awesomeWM/awesome/issues/3496#issuecomment-965911778 . 
```lua
----- this code for move cursor to focused window
local function move_mouse_onto_focused_client()
   local c = client.focus
        if c then
       local geometry = c:geometry()
       local x = geometry.x + geometry.width/2
       local y = geometry.y + geometry.height/2
       mouse.coords({x = x, y = y}, true)
   end
end

local move_cursor_flag= false
function toggle_move_cursor()
    if not move_cursor_flag then
        client.connect_signal("focus", move_mouse_onto_focused_client)
        client.connect_signal("swapped", move_mouse_onto_focused_client)
        move_cursor_flag = not move_cursor_flag
    else
        client.disconnect_signal("focus", move_mouse_onto_focused_client)
        client.disconnect_signal("swapped", move_mouse_onto_focused_client)
    end
end
function enable_move_cursor()
        client.connect_signal("focus", move_mouse_onto_focused_client)
        client.connect_signal("swapped", move_mouse_onto_focused_client)
        move_cursor_flag=true
end
function disable_move_cursor()
        client.disconnect_signal("focus", move_mouse_onto_focused_client)
        client.disconnect_signal("swapped", move_mouse_onto_focused_client)
        move_cursor_flag=false
end
local function go_to(tag_number, move_client)
        -- This will open "tag_number"
        local tags_dp = {1, 3, 6, 8, 10}
        local index = 0
        local tmp_screen
        local tag

        -- Look if tag_number is in the list
        while ((index < 5) and (tag_number ~= tags_dp[index])) do
                index = index + 1
        end

        -- Is the tag in the left screen?
        if (index < 5) then
                tmp_screen = 1
                mouse.coords({x = 960, y = 540}, true)
        else
                tmp_screen = 2
                mouse.coords({x = 2880, y = 540}, true)
        end

        tag = awful.tag.find_by_name(awful.screen[tmp_screen - 1], tostring(tag_number))

        -- Open the tag if possible
        if (tag and move_client == nil) then
                tag:view_only()
        else
                -- move the client to the tag
                client.focus:move_to_tag(tag)
        end

        awful.screen.focus(tmp_screen)
end
--
--end this code
```
So, in the clientkeys, I add
```lua
clientkeys = my_table.join(
awful.key({ modkey, "Shift" }, "f", function () toggle_move_cursor() end,
              {description = "move cursor", group = "client"}),
)
``` 
for toggling the feature by `modkey+Shift+f`.
I use rofi select window, the key map is changed as
```lua
    awful.key({ modkey, }, "'", function ()
        enable_move_cursor()
        awful.spawn("rofi -theme lb -monitor -1 -show ")
        gears.timer.start_new (4, disable_move_cursor)
        end,
              {description = "rofi show windos", group = "launcher"}),
```
I add three small functions ` toggle_move_cursor , enable_move_cursor, disable_move_cursor `
These codes work well during the several weeks.

In fact, **I very like your codes, it is more beautiful than the code I used , but I use some software with WINE  (like WINE WeChat), I have to close the move cursor feature sometimes.**

**Comment by lpanebr** [comment]
> Hi, you can use the module I made:
> 
> https://github.com/basaran/awesomewm-micky

THANKS. It is perfect!
