### ISSUE TITLE
wibox constructor x and y coordinates do not work on a widescreen monitor

### ISSUE THREAD

**Issue by mx-mw** [awesomeWM/awesome#3497]
Output of `awesome --version`: 
awesome v4.3 (Too long)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2

**How to reproduce the issue:**

1. set the primary screen in nvidia config or whatever to a widescreen (2560x1080) monitor

create a wibox: 
```lua

local container = wibox({
	visible = true, 
    ontop = true, 
    type = "splash", 
    screen = screen.primary, 
	y = dpi(100),
	x = 100,
    width = 100,
    height = 30 
})

container:setup {
	{
		nil,
		some_widget,
		layout = wibox.layout.fixed.horizontal,
		expand = "none"
	},
	layout = wibox.layout.fixed.horizontal
}
```

**Actual result:**

the widget is stuck in the top left corner of the display

**Expected result:**

the widget has an offset from the corner of the display.
(this happens when I use a 1920x1080 monitor)

**Comment by Elv13** [comment]
Solved in the chat
