### ISSUE TITLE
h: No such file or directory    27 | #include "common/atoms-extern.h"

### ISSUE THREAD

**Issue by oneplusoneequalstwo** [awesomeWM/awesome#3502]
```

[ 83%] Built target generate-examples
[ 84%] Built target ldoc
[ 84%] Built target version_stamp
[ 91%] Built target man
[ 91%] Building C object CMakeFiles/test-systray.dir/tests/test-systray.c.o
In file included from /home/eric/awesome/tests/test-systray.c:29:
/home/eric/awesome/build/common/atoms.h:27:10: fatal error: common/atoms-extern.
h: No such file or directory
   27 | #include "common/atoms-extern.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[3]: *** [CMakeFiles/test-systray.dir/build.make:82: CMakeFiles/test-systray.dir/tests/test-systray.c.o] Error 1
make[2]: *** [CMakeFiles/Makefile2:11344: CMakeFiles/test-systray.dir/all] Error 2
make[1]: *** [Makefile:171: all] Error 2
make: *** [Makefile:45: package] Error 2

```
pop!_OS 20.04 (NVIDIA)

I am pretty bad at Linux, but I tried reinstalling atom which of course did nothing.
I am stuck and really want to use Awesome, because it's Awesome.

**Comment by dwsong07** [comment]
I'm having same problem in arch linux.
(AUR: https://aur.archlinux.org/packages/awesome-git/)

```
[ 89%] Built target version_stamp
[ 89%] Building C object CMakeFiles/test-systray.dir/tests/test-systray.c.o
In file included from /home/dwsong07/Downloads/awesome-git/src/awesome-git/tests/test-systray.c:29:
/home/dwsong07/Downloads/awesome-git/src/build/common/atoms.h:27:10: fatal error: common/atoms-extern.h: No such file or directory
   27 | #include "common/atoms-extern.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/test-systray.dir/build.make:76: CMakeFiles/test-systray.dir/tests/test-systray.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:10924: CMakeFiles/test-systray.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...

```

**Comment by Aire-One** [comment]
I guess we have a little dependency hell for the new C test from the latest PR https://github.com/awesomeWM/awesome/pull/3490.

I'll not be able to investigate more right now, tho... Maybe you can revert the merge commit for this PR locally to build awesome. There is nothing important for the end-user in this PR, it is mostly CI improvements.

Hm, I'm actually not sure whether this PR is really to blame (?) the CI seems to pass with it...

**Comment by sclu1034** [comment]
It looks like the `test-systray` target is missing the `generated_sources` dependency.

It'll work fine sometimes, if run in a build environment that existed before that PR was merged (since `atoms-{intern,extern}.h` already exists there) or when `generated_sources` wins the race and runs first. But with a clean build directory and doc/manpage generation off, chances are high that `test-systray` runs early enough.

**Comment by Elv13** [comment]
Whoops. @sclu1034 is right, I made a PR from his suggestion (with proper attribution)

**Comment by GhostofCerverus** [comment]
I got the same error as @dwsong07 (on arch Linux). Not sure if I am understanding the responses. Is there a way to fix this? Sorry if I am being stupid.

**Comment by Elv13** [comment]
Make this change
https://github.com/awesomeWM/awesome/pull/3504/files
