### ISSUE TITLE
[Question] Doc about `awesome-client`

### ISSUE THREAD

**Issue by TornaxO7** [awesomeWM/awesome#3505]
Hello! I'd like to know what functions are available for the module `awesome`, so I did `awesome-client --help` which gave me this:

```
Usage: awesome-client [-h|--help] [command [command...]]
awesome window manager remote execution

awesome-client is a remote command line interface to awesome.
It communicates with awesome via D-Bus, allowing remote execution of Lua code.

Run without a command to enter REPL (read-eval-print-loop) mode.
For examples see `man awesome-client`.
```

But if I do `man awesome-client` then I'm getting
```
No manual entry for awesome-client
```
what do I have to do to read the manual of `awesome-client`?

**Comment by Aire-One** [comment]
Hello, 

It's weird that your distro didn't ship the corresponding man page with the package... Anyway, it's also available only on our website : https://awesomewm.org/doc/manpages/awesome-client.1.html

**Comment by TornaxO7** [comment]
thanks!I'm using Arch Linux if it might help you.

**Comment by Aire-One** [comment]
> I'm using Arch Linux if it might help you.

I'm also using arch. I have a custom pkgbuild, tho... However, looking at https://github.com/archlinux/svntogit-community/blob/packages/awesome/trunk/PKGBUILD, I don't think I do something more in order to have the corresponding man page... 
Sooo :shrug:

**Comment by sclu1034** [comment]
The official Arch package definitely includes the manpage, as that is extracted to the web view here: <https://man.archlinux.org/man/community/awesome/awesome-client.1.en>.

**Comment by TornaxO7** [comment]
I'm using the AUR package
