### ISSUE TITLE
client.icon is blurry for firefox, client:get_icon(1) is not.

### ISSUE THREAD

**Issue by Crylia** [awesomeWM/awesome#3508]
Output of `awesome --version`:

`awesome v4.3-1284-g50b9b104 (Too long)`

**How to reproduce the issue:**

using `client.icon` to get and set the firefox icon to a imagebox makes it blurry
while using `client:get_icon(1)` works fine
1 is the index and the lower the index the higher the icon resolution

**Actual result:**
![grafik](https://user-images.githubusercontent.com/50151522/141766084-5cb54081-35f1-40a3-a066-6f4170a4bc65.png)

Blurry with `client.icon`

**Expected result:**
![grafik](https://user-images.githubusercontent.com/50151522/141766145-0bd55393-a6ce-4394-b12d-469a38e8ad60.png)

Sharp with `client:get_icon(1)`

(image taken while using client:get_icon(1))

**Comment by Crylia** [comment]
Also using `image = c:get_icon(1)` directly inside of an imagebox will output the following error but works as expected.
![grafik](https://user-images.githubusercontent.com/50151522/141767002-98feb9da-3fae-4743-b505-af8f85df2e0d.png)

**Comment by Aire-One** [comment]
Hello,

As we discussed on discord, can you please also add to the first post what you get with the clienticon widget? (https://awesomewm.org/doc/api/classes/awful.widget.clienticon.html)

It should select the correct icon size (I'm not sure client.icon does that), so it should be the preferred way to get the client icon in an image widget. Based on our discussion on discord, it wasn't working properly either.

**Comment by Crylia** [comment]
using
```
{
    widget = awful.widget.clienticon(c)
}
```
Results into this and works just fine
![grafik](https://user-images.githubusercontent.com/50151522/141774647-11316acb-b45a-4997-beb9-b920d1e3c783.png)

**Comment by sclu1034** [comment]
Working as intended/documented.
The documentation for `client.icon` states

> This property holds the client icon closest to the size configured via `awesome.set_preferred_icon_size`.

The documentation for `awesome.set_preferred_icon_size` states

> The default is 0 pixels, ie. the smallest icon.

Therefore, it is expected that trying to display the smallest icon in a bigger imagebox will result in the image being resized.

**Comment by Crylia** [comment]
In that case the issue can be closed.

**Comment by Aire-One** [comment]
Thanks to the @sclu1034 investigations, we can assume that the "client.icon is blurry" question is solved. I think we should have a mention of the fact that `awesome.set_preferred_icon_size` defaults to 0 in the doc.

> Also using `image = c:get_icon(1)` directly inside of an imagebox will output the following error but works as expected. ![grafik](https://user-images.githubusercontent.com/50151522/141767002-98feb9da-3fae-4743-b505-af8f85df2e0d.png)

This however is still an issue we have to investigate.
