### ISSUE TITLE
confusion about client:geometry()

### ISSUE THREAD

**Issue by guotsuan** [awesomeWM/awesome#351]
I'm now confused about  the behaviour of the client:geometry(). I'm wondering if it is a bug or it suppose to be like that.

I am  trying to collect all clients to a temporary tag by awful.client.toggletag (), as shown in the picture.
Then I give each client a hintbox with a letter. By pressing the corresponding letter, I can quickly select the client I want.  It actually works fine with the version of awesome a few month ago.  But recently there is some problem about displaying the hintbox.

To properly place the hintbox in the temp tag, I firstly awful.tag.viewonly(the temp tag). As you can see in the picture. 
In this tag, there are all clients "borrowed" from other tags, and tiled in this one.  To place the hintbox in the righ place (the centre of client),  I need to get the geometry of all the clients by client:geometry(). 

I will assume that the geometry of each client will be different if there are in different tag, since the layout of the different tag may be different.  So when I awful.tag.viewonly(the temp tag), which is full of the clients borrowed from other clients, I assume the client:geometry() should return the geometry of the client in this temp tag, not the geometry of client in its original tag.

To be a little bit clearer:
Assume we have  client (A) in tag 1, client (B) in tag 2. Both tags are in awful.layout.suit.fair.
So both client are maximised in tag1 and tag2. The width of client A and B should be equal, let us say 1440.  If both client A band B are added (not moved) to tag 3 by awful.client.toggletag(tag 3). Then if I awful.tag.viewonly(tag3) and use client:geometry() to get the width of client A and B, I would expect that the width of A and B should be 720 and 720 respectively,since two of them equally share the tag 3.  But now from my code. I still get the width of 1440 and 1440 in this case. 

I'm wondering if I'm dong something wrong or it is a bug?

![screenshot](https://cloud.githubusercontent.com/assets/1430766/8889350/c6eaa87e-32d6-11e5-8e90-7384ef470c85.png)

**Comment by psychon** [comment]
Look at `awful.layout.arrange`. It uses (in master) `timer.delayed_call` to arrange clients. What this means is that instead of re-computing the geometry of clients all the time when little thing starts, the code waits until the end of the current main loop iteration and then only re-computes the client positions once.

You could e.g. start a timer with a timeout of 0 seconds and only when the timer fires place your hintboxes. By the time the timer fires, the layout "did its thing".

**Comment by guotsuan** [comment]
I see. Thank you very much for the explanation . @psychon,

**Comment by blueyed** [comment]
This should probably get added to the docs for `client:geometry()`?!

**Comment by guotsuan** [comment]
Adding the extra timer works. I just found that @wxg4net use awesome.emit_signal("refresh") to force the layout to re-calculate the geometry. I'm wondering if there is no other side effect, this way seems more simple?

**Comment by Elv13** [comment]
An ugly hack to do this is implemented [here](https://github.com/Elv13/collision/blob/master/layout.lua). A more future proof solution is implemented in #644.

Either way, this issue has been addressed long ago.
