### ISSUE TITLE
Error on boot, 3 terminals, nothing else works

### ISSUE THREAD

**Issue by GhostofCerverus** [awesomeWM/awesome#3510]
I am fairly new to Archlinux and Linux in general as well as this being my first time attempting to use awesome. So I am sorry if I am making really obvious mistakes or this is formatted incorrectly. And I don't have screen shot software either so sorry about the photos...

This is my second time trying to install awesome. The first time it would launch with startx and then display this (image below). None of the hotkeys worked or mouse. I just had a smaller terminal >_<

![image](https://user-images.githubusercontent.com/92415328/142074353-68f0d71f-558e-4f4a-ade1-3449265e8f03.jpeg)

I then wiped my laptop and reinstalled archlinux as well as xorg, xorg-server, xorg-xinit, xterm, awesome and the intel graphics driver xf86-video-intel (the first time I forgot to install graphics driver but had installed everything else). Now I am getting this error when I run startx. (Image below) and I am sorry if this isn't todo with awesome and is an xorg problem, I'm not sure so I posted it here. 

![image](https://user-images.githubusercontent.com/92415328/142074909-6ac90e59-0a34-4e6a-b5b3-61f12751529f.jpeg)

If I do sudo startx I get the same screen as the first image.

Any help would be appreciated 
And sorry for my lack of knowledge...

(:

**Comment by sclu1034** [comment]
> exec: awesome: not found

It can't find any executable called `awesome` in `PATH`. You can try an absolute path, e.g. `exec /path/to/awesome` or adjust `PATH`.

---

Side note: You'll probably get more readable output if you save it to a file temporarily:

```sh
startx &>/tmp/startx.log
# after that exists/crashes
less /tmp/startx.log
```

**Comment by GhostofCerverus** [comment]
I have just wiped it and started using a different wm. Sorry for the hassle and thanks for the help. Hopefully one day when I have more time I will be able to try awesome again. (:
