### ISSUE TITLE
Awesome is causing visible stuttering on vsync'ed games (Nvidia Proprietary 495.44)

### ISSUE THREAD

**Issue by charbelnicolas** [awesomeWM/awesome#3511]
Output of `awesome --version`:

awesome v4.3-1307-g0246c44d4

**How to reproduce the issue:**

Install latest awesome from git and try to run a game with vsync and while the GPU (GTX 980) can render 60 fps you will still see stutter. (You can try using Xonotic)

**Actual result:**

Rock solid 60 fps but it still has perceived stutter.

**Expected result:**

No stutter and a smoothly rendered game.

I installed qtile and everything works smoothly. This started happening at least a month ago or so. I Thought at first it was the nvidia drivers until I tried using qtile. Something is definitely going on with awesome wm.

**Comment by charbelnicolas** [comment]
I installed awesome stable version 4.3 and the issue persists, so it must be some dependency that got updated not so long ago that awesome uses... or something...

**Comment by charbelnicolas** [comment]
Gnome is also affected...

**Comment by actionless** [comment]
> Gnome is also affected...

sound what it's not WM-specific then

**Comment by charbelnicolas** [comment]
> > Gnome is also affected...
> 
> sound what it's not WM-specific then

Yep, wherein do you think the problem lies? It's X11 on NVIDIA. Gnome and awesome are affected while bspwm and qtile are not.

I'd like to report the bug upstream to whatever package introduced this issue.

**Comment by actionless** [comment]
can you reproduce with awesome running with `--no-argb` flag?

**Comment by charbelnicolas** [comment]
> can you reproduce with awesome running with `--no-argb` flag?

Yes, that fixed the issue, thank you. What will I be missing without argb? Is cairo at fault here?

**Comment by actionless** [comment]
video driver

**Comment by charbelnicolas** [comment]
Ok, I just found out about https://github.com/awesomeWM/awesome/issues/2764

Thank you, I don't use a compositor anyways.
