### ISSUE TITLE
attempt to call a nil value (field 'get_random_file_from_dir')

### ISSUE THREAD

**Issue by UbioZur** [awesomeWM/awesome#3528]
Output of `awesome --version`:
                                                                                                                                                       
awesome v4.3 (Too long)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2

** Code **
```
local gears = require("gears")
local awful = require("awful")

gears.debug.print_warning(folder)
local image = gears.filesystem.get_random_file_from_dir(folder,{"jpg", "png", "bmp"}, true)
```

** Log Output **
> 2021-12-18 12:28:30 W: awesome: /home/quentin/Pictures/wallpapers/1920x1080
> error while running function!
> stack traceback:
> 	./mod/wallpapers.lua:47: in function 'mod.wallpapers.display_new'
> 	/home/quentin/Projects/awesomede/rc.lua:45: in main chunk
> error: ./mod/wallpapers.lua:47: **attempt to call a nil value (field 'get_random_file_from_dir')**

** Expected **

gears.filesystem.get_random_file_from_dir to be a valid function and not an unknown function.

It can absolutly be a mistake from my side (I am new to Lua), but I cannot find any good result after researching that issue. I don't know also how to check what functions / properties I have access to from the code itself (and not from the doc).

- I know my folder variable is not empty (the debug is printing exactly the folder I want).
- I don't believe I use the function wrong (as per the doc last updated in the future)
https://awesomewm.org/apidoc/utility_libraries/gears.filesystem.html#get_random_file_from_dir
**_`Last updated 2030-01-01 00:00:00`_**
- Double checking from the rare result of search I found, I don't seem to have made a mistake on the call of the function.
https://www.reddit.com/r/awesomewm/comments/h0xorw/dynamic_wallpapers_in_awesome/fuzir95/

Any tips/pointers would be welcome.

**Comment by psychon** [comment]
> awesome v4.3 (Too long)

> error: ./mod/wallpapers.lua:47: attempt to call a nil value (field 'get_random_file_from_dir')

`get_random_file_from_dir` was added after v4.3. It does not appear in https://github.com/awesomeWM/awesome/blob/v4.3/lib/gears/filesystem.lua

v4.3 is from January 28th 2019 while `get_random_file_from_dir` was added in #2605 on February 16th 2019.

Sorry.

**Comment by Aire-One** [comment]
To complete the @psychon comment, you are using the awesome stable release, but your online resources (reddit thread and doc link) are targeting the git-master version. The documentation you want to use for your version of awesome is located at https://awesomewm.org/doc/api/index.html.

As a whole, the wallpaper module is not available on the awesome stable version. Alternatively, you can try to play with the `gears.wallpaper` and `gears.filesystem` modules to implement the behavior you want by yourself. (The Bling lib also have some interesting features in their wallpaper module, maybe you can check that out : https://blingcorp.github.io/bling/#/module/wall)

Regarding the doc last update date, that's a known "bug" we use for some tests to have the exact same result as expected (based on the date/time). Maybe we should remove this date from the doc...

**Comment by UbioZur** [comment]
Thank you guys, makes sense, I will try to find another solution (maybe just copying the function from GitHub to my rc).

For the last doc update, it's no big deal, but unless it's needed, could be good to remove/hide it.

Maybe having a way to add from what version a function would be available on the doc. That way it could be faster to figure it out. But that's just an idea, I don't know if it would be easy to implement/maintain.
