### ISSUE TITLE
Only one of {`property::x`, `property::y`} (and similarly for {`property::width`, `property::height`}) is emitted when resizing a client.

### ISSUE THREAD

**Issue by xinhaoyuan** [awesomeWM/awesome#3535]
See the logic here https://github.com/awesomeWM/awesome/blob/1413f0c4b9da13b17b7fc11e2edd78daf695f3b4/objects/client.c#L2403-L2418. It has been there since v4.1. 

**How to reproduce the issue:**

First, find a client, e.g.
```
local c = client.focus
```

Then set up the initial geometry and callbacks for property::*:

```
c:geometry({x = 100, y = 100, width = 200, height = 200})
c:connect_signal("property::x", function (client) print("property::x", client) end)
c:connect_signal("property::y", function (client) print("property::y", client) end)
c:connect_signal("property::width", function (client) print("property::width", client) end)
c:connect_signal("property::height", function (client) print("property::height", client) end)
```

Then call geometry e.g.

```
c:geometry({x = 0, y = 0, width = 100, height = 100})
```

**Actual result:**

You will find in the log that only `property::x` and `property::width` is called.

**Expected result:**

All four `property::*` callbacks are called.

**Comment by Elv13** [comment]
Thanks for reporting. Do you think you can make a PR? I am pretty busy finishing up the next release right now, this would be appreciated.

**Comment by xinhaoyuan** [comment]
No problem! The fix should be simple. I can spend some time on that.
