### ISSUE TITLE
Open clients in tags of another screen

### ISSUE THREAD

**Issue by nicobross** [awesomeWM/awesome#3536]
**Output of `awesome --version`:**

awesome v4.3-1314-ge7a21947-dirty (Too long)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • API level: 4
 • D-Bus support: yes
 • xcb-errors support: no
 • execinfo support: yes
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
 • Transparency enabled: yes
 • Custom search paths: no

**How to reproduce the issue:**

I want to press Super + S and open some clients in a tag which is in a secondary screen.
I tried different approaches, but any of them have worked. For example, I wrote this line:
`              awful.spawn("mocp", { tag = awful.tag.find_by_name(nil,"music")})`
This instruction only works if the tag is in the focused screen. How can I do to achieve this?

**Actual result:**

Clients open only in the focused screen

**Expected result:**

Clients open in the right tag regardless if the tag is in the focused screen or not

**Comment by comod** [comment]
check this out: https://github.com/awesomeWM/awesome/issues/3258
