### ISSUE TITLE
Glitches when there's movement on the screen

### ISSUE THREAD

**Issue by farhadp-code** [awesomeWM/awesome#3538]
Output of `awesome --version`:
awesome v4.3 (Too long)
 • Compiled against Lua 5.3.6 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2

**How to reproduce the issue:**

Open browser (chrome or firefox) and scroll. Or open some game or a youtube video.

**Actual result:**

the picture is not always smooth. specifically when you move or scroll page rapidly there are glitches horizontally in the screen.

**Expected result:**

smooth and nice picture without any glitches. 
I have xfce desktop also installed in this system and the issue does not happen there.

**Comment by Aire-One** [comment]
Hello,

This issue can be solved by installing a compositor like compton or picom.

Alternatively, as stated in this other issue https://github.com/awesomeWM/awesome/issues/1814, you can try to start awesome with the `--no-argb` flag.

**Comment by farhadp-code** [comment]
> Hello,
> 
> This issue can be solved by installing a compositor like compton or picom.
> 
> Alternatively, as stated in this other issue #1814, you can try to start awesome with the `--no-argb` flag.

I have picom installed. i tried toggling it off. the issue persisted. I tried starting awesome with --no-argb flag as stated in previous and closed issue #1814  but didn't help but I am not sure that I did it right. ran this command 'awesome --no-argb -r'

**Comment by unai-ndz** [comment]
Try tweaking picom's config. Maybe use a different renderer.

**Comment by farhadp-code** [comment]
> Try tweaking picom's config. Maybe use a different renderer.

Hello
Thanks for your comment. I tried changing the renderer but didn't resolve the issue.

**Comment by actionless** [comment]
i dont really see much reason for this issue to hang around here as open

**Comment by farhadp-code** [comment]
> i dont really see much reason for this issue to hang around here as open

then solve it instead of closing it

**Comment by sclu1034** [comment]
This is not an issue with Awesome. Or any window manager for that matter.
A window manager has nothing to do with what windows draw within their bounds (unless that window manager also takes on the role of a compositor, which Awesome does not).

XFCE, being a full desktop environment, might be setting things for you in a way so that this issue doesn't appear. But when you use individual parts to set up your own environment, this issue is up to you to fix.

**Comment by farhadp-code** [comment]
> This is not an issue with Awesome. Or any window manager for that matter. A window manager has nothing to do with what windows draw within their bounds (unless that window manager also takes on the role of a compositor, which Awesome does not).
> 
> XFCE, being a full desktop environment, might be setting things for you in a way so that this issue doesn't appear. But when you use individual parts to set up your own environment, this issue is up to you to fix.

Hello.
I think you are right and this is not an issue with awesome and maybe I have posted it in the wrong place. I just wanted to get help from the community to fix this problem. I am new to using window managers.
