### ISSUE TITLE
cant use mouse anymore after first click or scroll anywhere

### ISSUE THREAD

**Issue by comod** [awesomeWM/awesome#3542]
Output of `awesome --version`:
awesome v4.3-900-g4319b161 (Too long)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • API level: 4
 • D-Bus support: yes
 • xcb-errors support: no
 • execinfo support: yes
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
 • Transparency enabled: yes
 • Custom search paths: no

**How to reproduce the issue:**
click somwhere.

since then i am only able to move the cursor, but i cant do anything with the mouse anymore (no hover effects over the clients, clicks do not focus clients ect), keyboard works fine, though.
sometimes i am able to get the mouse working again after switching to another tag and back.
honestly i tweaked my sytem a lot last days to get more done without the mouse - that was my goal, but i never have done something similar to the configs of awesomewm... i installed vim, got a new splitkeyboard, a footpanel, everything works fine for a while, and then someday this happens. so i probably messed it up somewhere, but i have no idea where! after reload i am able to start over, with the same "trap", though, but it helps to quit awesome and re-login - after that everything behaves normal again.
i reverted every modifications i made in the past, without effect. so its not a code or environment issue, i think.

logs without errors as i can see

how can i solve this weird issue?

**Comment by comod** [comment]
its not completely well described. i try to refine: the problem can happen each tag. the mouse will catched as soon as i click on a client (masters are not causing this error) - hope terminology is correct .-)

**Comment by comod** [comment]
also wrong. masters can cause this behaviour as well. damn

**Comment by comod** [comment]
i reverted everything, without effect. so its not a code issue. but it relates to my new keyboard. i use a r-go with a logitech mouse. after turn off and on the new keyboard everything seems to be ok now. WEIRD!

**Comment by comod** [comment]
i cannot even say why this happens, but this is so annoying

**Comment by comod** [comment]
i am not sure if this has something todo with the keyboard. i logged in into another user and back and everything is ok again.

**Comment by Aire-One** [comment]
Hello,

It will be impossible for us to debug this without reproducible steps (preferably from the default awesomerc.lua) and code example of what you have in your config.

**Comment by comod** [comment]
it has nothing to do with my config. i removed the entire configs and i was able to reproduce the issue with awesomewm-standard. i open 2 terminals - click on one of them and it happened again, only quit and relogin helps. i tried to re compile awesomewm with the latest, but this is not possible because of lua version errors. maybe this helps to figure it out what is wrong. i tried to set the correct lua version as described in the docs, but i wasnt able to manage it, at a certain point i gave up.

**Comment by Elv13** [comment]
Something, somewhere is grabbing the mouse. In X11, that can be any process. There is no security and little way to force the faulty process to release the mouse.

Awesome can do such a thing using the `mousegrabber` module, but it can be anything running on your computer.

As you can understand, if AwesomeWM was generally causing this, we would get a lot more user report about this. If this happens with the default config, I would tend to blame "something else on your computer".

**Comment by comod** [comment]
This has absolutely nothing to do with awesomewm. I have similar issues outside of awesome

**Comment by unknown321** [comment]
In my case it was wine that grabbed cursor. You can get a list of grabs by running `xdotool key "XF86LogGrabInfo"` and checking `/var/log/Xorg.0.log`. Killing wine process solved the issue.

https://unix.stackexchange.com/a/62252/580044
