### ISSUE TITLE
Would it be possible to make the layout button show a menu of available layouts when clicked

### ISSUE THREAD

**Issue by godalming123** [awesomeWM/awesome#3549]
As far as I am aware there is not a forum for the awesome WM so I am asking my question here and what I would like is an example of how you can make a menu showing available layouts with a checkmark or asterisk next to the selected one that shows when you click the selected layout icon in awesome.

**Comment by Grumph** [comment]
I wrote a widget for listing clients some time ago, so it took me about an hour to write this quick and dirty widget: https://bitbucket.org/grumph/home_config/src/master/.config/awesome/widgets/layoutsmenu.lua

For the widget to work, you will need this file too: https://bitbucket.org/grumph/home_config/src/master/.config/awesome/helpers/widget_popup.lua

And then you can use it like this:
```
local layoutsmenu = require "widgets.layoutsmenu"
local layoutsmenu_widget = layoutsmenu(screen)  -- replace your layoutbox with this widget
```

**Comment by godalming123** [comment]
Thanks

**Comment by Elv13** [comment]
It's also possible with the built-in layoutlist widget https://awesomewm.org/apidoc/widgets/awful.widget.layoutlist.html

**Comment by godalming123** [comment]
> It's also possible with the built-in layoutlist widget https://awesomewm.org/apidoc/widgets/awful.widget.layoutlist.html

Could you give me say an example config where this is used since I am new to awesome and lua?
