### ISSUE TITLE
Segmentation fault gnome-control-center in sound section

### ISSUE THREAD

**Issue by wesleimp** [awesomeWM/awesome#3571]
Output of `awesome --version`:
```
awesome v4.3 (Too long)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.
```

**How to reproduce the issue:**

Open gnome-control-center and click in sound section

**Actual result:**

The gnome-control-center exits with the following error:

![image](https://user-images.githubusercontent.com/42675056/154175658-07011ad5-a6a6-4722-8f64-45dc39b72a97.png)

control-center does not open again until run `dconf reset -f /org/gnome/control-center/`

**Expected result:**

Open sound settings

**Aditional context**

gnome-control-center works perfectly with i3

**Comment by actionless** [comment]
try running `awesome --no-argb` instead of `awesome`

**Comment by actionless** [comment]
does it works on openbox?

**Comment by wesleimp** [comment]
@actionless Yes, it does. I've tried a lot of things to solve that, but everything failed. I'm using `PulseAudio Volume Control` when I need to change the input/output, but it sucks because the `PulseAudio Volume Control` does not recognize all the inputs and outputs 😕

**Comment by actionless** [comment]
1) mb you have smth in your ~/.config/autostart/ which is required for it to work?

make sure to rename it to autostart.bak while testing with i3/openbox to make sure it's not affecting your result

2) try dbus-launch: https://wiki.gentoo.org/wiki/Awesome#Starting

**Comment by hishamhm** [comment]
Same thing is happening with Awesome on Ubuntu 22.04. I've installed Awesome via the distro's package and I'm starting it using Ubuntu's default display manager, so I'm not sure how to try dbus-launch with it.

**Comment by actionless** [comment]
@hishamhm welp, you made a good point regarding using a distro package - try contacting the packager, as on Arch Linux it works:
![2022-10-24--1666642598_1920x1080_scrot](https://user-images.githubusercontent.com/1655669/197620511-0582e838-3b7a-42fd-b8ce-7143ee49e838.png)

**Comment by hishamhm** [comment]
@actionless Agreed! An app shouldn't be segfaulting, regardless of the window manager they're running in.
