### ISSUE TITLE
Does building against luajit still work? (as with the PKGBUILD provided by awesome-luajit-git)

### ISSUE THREAD

**Issue by kwand** [awesomeWM/awesome#3573]
As titled. (Omitted versioning as this is a build issue)

**How to reproduce the issue:**

Build `awesome-luajit-git` as provided in the AUR.

**Actual result:**

Build errors occur:
```
2022-02-16 07:00:14 E: awesome: Error during a protected call: ...jit-git/src/awesome-luajit-git/lib/wibox/widget/base.lua:1000: Argument is not a widget!
stack traceback:
	[C]: in function 'assert'
	...jit-git/src/awesome-luajit-git/lib/wibox/widget/base.lua:1000: in function 'check_widget'
	...jit-git/src/awesome-luajit-git/lib/wibox/widget/base.lua:476: in function 'record_dependency'
	...jit-git/src/awesome-luajit-git/lib/wibox/widget/base.lua:519: in function 'fit_widget'
	...it-git/src/awesome-luajit-git/lib/wibox/layout/align.lua:120: in function <...it-git/src/awesome-luajit-git/lib/wibox/layout/align.lua:42>
	[C]: in function 'xpcall'
	...-git/src/awesome-luajit-git/lib/gears/protected_call.lua:36: in function '_creation_cb'
	...me-luajit-git/src/awesome-luajit-git/lib/gears/cache.lua:42: in function 'layout_widget'
	...uajit-git/src/awesome-luajit-git/lib/wibox/hierarchy.lua:132: in function 'hierarchy_update'
	...uajit-git/src/awesome-luajit-git/lib/wibox/hierarchy.lua:140: in function 'hierarchy_update'
	...uajit-git/src/awesome-luajit-git/lib/wibox/hierarchy.lua:140: in function 'hierarchy_update'
	...uajit-git/src/awesome-luajit-git/lib/wibox/hierarchy.lua:229: in function 'update'
	...uajit-git/src/awesome-luajit-git/lib/wibox/hierarchy.lua:214: in function 'new'
	...jit-git/src/awesome-luajit-git/lib/wibox/widget/init.lua:44: in function 'draw_to_cairo_context'
	...jit-git/src/awesome-luajit-git/lib/wibox/widget/init.lua:58: in function 'draw_to_svg_file'
	...t/src/awesome-luajit-git/tests/examples/uml/template.lua:210: in function 'generate_nav_table'
	...some-luajit-git/tests/examples/uml/nav_tables/screen.lua:4: in main chunk
	...t/src/awesome-luajit-git/tests/examples/uml/template.lua:227: in main chunk
	[C]: at 0x55d383a43d40
```

**Expected result:**

We should be able to build without errors.

Apologies if this is something simple, but I couldn't seem to find any having the same issue (and as far as I know, building against `luajit` was working at least a few months ago?)

**Comment by kwand** [comment]
> can you post `awesome -v`?

Why would that be relavent? And quite frankly, I can't even build `awesome-luajit-git`, so I'm at a loss at how I could even run that command when I haven't even built let alone installed awesome.

There's no way I can run that command...

**Comment by sclu1034** [comment]
Building against LuaJIT definitely is supported, but I don't know if that particular PKGBUILD works (CC maintainers @actionless @blueyed). I haven't tried with LuaJIT 2.0 in a while.

I'm building against LuaJIT 2.1, personally.

**Comment by kwand** [comment]
> Building against LuaJIT definitely is supported, but I don't know if that particular PKGBUILD works (CC maintainers @actionless @blueyed). I haven't tried with LuaJIT 2.0 in a while.
> 
> I'm building against LuaJIT 2.1, personally.

Looks like you're right - actually, the standard `luajit` community package provided by Arch is already 2.1.0(.beta3). I don't even have LuaJIT 2.0 installed, so that's probably why it was failing.

Changed these three `build()` lines in that PKGBUILD and got it successfully compile:

![image](https://user-images.githubusercontent.com/16279847/154436865-d1c9b56c-6607-4b97-a53b-772669cba5d8.png)
![image](https://user-images.githubusercontent.com/16279847/154437032-6c11f100-3752-4e73-b1d4-fc76208215f5.png)

(None of the provided paths existed on my machine - and probably shouldn't on any other machine that only pulls in the packages in `depends()`)

@actionless @blueyed, perhaps there needs to be an update to the AUR package?

**Comment by sclu1034** [comment]
Ah, I didn't realize `community/luajit` updated to 2.1. It seems they even track by newest commit now.
I've been running my own `luajit-git` package for that.

But in my experience, the only required change should be
```diff
-    -DLUA_INCLUDE_DIR=/usr/include/luajit-2.0 \
+    -DLUA_INCLUDE_DIR=/usr/include/luajit-2.1 \
```

`/usr/bin/luajit` certainly is linked explicitly: https://github.com/archlinux/svntogit-community/blob/packages/luajit/repos/community-x86_64/PKGBUILD#L36

**Comment by kwand** [comment]
@sclu1034 Ah, you're right. I made the mistake of using `fzf` to look up whether the files existed or not, and it looks like it hides symlinks by default.

Checked with `ls` and indeed links for them do exist. The only change required is the one you suggested.

**Comment by Aire-One** [comment]
I'm closing the issue, since it's not an issue with awesome itself but the package you use.

Please report the issue to the maintainers on the AUR directly.

(note that it's still allowed to discuss the issue in this thread)
