### ISSUE TITLE
Error when opening hotkeys cheatsheet

### ISSUE THREAD

**Issue by DarviL82** [awesomeWM/awesome#3577]
When attemping to launch the hotkey cheatsheet, an error appears:
![image](https://user-images.githubusercontent.com/48654552/155897776-0836a7d0-4cbc-4ed9-a707-04b273d2171c.png)

This is most likely caused by a config. It was working fine just a few minutes ago though.

Output of `awesome --version`:

awesome v4.3 (Too long)
 • Compiled against Lua 5.3.6 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2

**How to reproduce the issue:**

Open the awesome hotkey reference popup.

**Actual result:**

An error appears at the top right. (`/usr/share/lib/awful/hotkeys_popup/widget.lua:451: attempt to perform arithmetic on a nil value (field 'border_width')`)

**Expected result:**

The hotkey popup should show up.

Thanks a lot in advance.

**Comment by actionless** [comment]
try with awesome built from latest git commit, 4.3 happened so long ago what some things might not work anymore :D

**Comment by DarviL82** [comment]
Oh I had no idea I was using a very old version, just looked at it and it's from 4 years ago, phew!
Thanks! I'll try it asap.

**Comment by DarviL82** [comment]
Indeed, the error is gone! Thank you so much :D

**Comment by TheoOliveira** [comment]
In case someone face this, just explicitly set beatiful.border_width = 1
