### ISSUE TITLE
Question: Are there any plans to release a new version anytime soon?

### ISSUE THREAD

**Issue by elyoas** [awesomeWM/awesome#3580]
Apologies if I was breaking any rules..

**Comment by sclu1034** [comment]
> Are there any plans to release a new version
Yes.

> anytime soon?
Probably not. There is no ETA.

**Comment by actionless** [comment]
https://github.com/awesomeWM/awesome/milestone/9

**Comment by elyoas** [comment]
I can't believe that it has almost been a year since I wrote this issue! Right now it is 34 issues open, 51 closed (%60 complete).

https://github.com/awesomeWM/awesome/milestone/9

Why not make a release with its current state for the 15th anniversary?

**Comment by actionless** [comment]
spamming and wasting my time by using @-mention wouldn't make release sooner - you'd better fix one of those issues in the milestone instead yourself, to do smth useful **once**
