### ISSUE TITLE
Application of beautiful varibles inconsistent/broken

### ISSUE THREAD

**Issue by IveGotRoot** [awesomeWM/awesome#3586]
Output of `awesome --version`:
awesome v4.3-1358-g392dbc21a (Too long)
 • Compiled against Lua 5.4.4 (running with 0.9.2)
 • API level: 4
 • D-Bus support: yes
 • xcb-errors support: yes
 • execinfo support: yes
 • xcb-randr version: 1.6
 • LGI version: /usr/share/lua/5.4/lgi/version.lua
 • Transparency enabled: yes
 • Custom search paths: no

**How to reproduce the issue:**
Dotfiles: https://gitlab.com/thomasc_/stow-dotfiles
layoutbox.lua & wibox.widget.textclock() parent container bg=beautiful.bg_normal
and any item referencing custom value beautiful.padding fails to set margin with no output to stdout

**Actual result:**
https://imgur.com/a/YytgjsI

**Expected result:**
right segment of titlebar to have a gray bg

**Comment by IveGotRoot** [comment]
Ima try and mark as closed bc moving my theme init before everyting else fixed it

**Comment by Aire-One** [comment]
Yup, the beautiful module needs some major refactors to be more user-friendly / permissive (that would probably also require a lot of changes to the widget system).

For now, you can consider that you are supposed to call the `beautiful.init()` function at the very beginning of your `rc.lua`. Some widgets would even make your configuration crash if beautiful isn't initialized when you load them...
