### ISSUE TITLE
_NET_WM_ICON overwrite beautiful.icon_theme

### ISSUE THREAD

**Issue by tuwuna** [awesomeWM/awesome#3587]
Output of `awesome --version`: Compiled from source

**How to reproduce the issue:**

Open applications, notice how tasklist icon seems off

**Actual result:**

![unknown](https://user-images.githubusercontent.com/56817415/158024182-fde7acbc-b50b-4e25-89b4-846dd2e661e1.png)

**Expected result:**

![unknown](https://user-images.githubusercontent.com/56817415/158024107-7c39d84a-f214-4f46-acfc-606a570e4eeb.png)

Maybe there is some signal like `property::icon` that a mere user like me can overwrite? 

I don't think a user who specifically set `beautiful.icon_theme` would like to see `_NET_WM_ICON`

**Current workaround**

```lua
client.connect_signal("manage", function(c)
  awful.spawn.easy_async_with_shell("sleep 0.05", function()
    if c.instance ~= nil then
      local icon = menubar.utils.lookup_icon(c.instance)
      local lower_icon = menubar.utils.lookup_icon(c.instance:lower())
      if icon ~= nil then
        local new_icon = gears.surface(icon) 
        c.icon = new_icon._native
      elseif lower_icon ~= nil then 
        local new_icon = gears.surface(lower_icon)
        c.icon = new_icon._native
      elseif c.icon == nil then
        local new_icon = gears.surface(menubar.utils.lookup_icon("application-default-icon"))
        c.icon = new_icon._native
      end
    else
      local new_icon = gears.surface(menubar.utils.lookup_icon("application-default-icon"))
      c.icon = new_icon._native
    end
  end)
end)
```

**Comment by sclu1034** [comment]
The name `icon_theme` does suggest that it is a generic feature, but that theme variable is, in fact, only valid/used within the `menubar` module specifically.
So it's not that it's overwritten or replaced for regular client icons. The handling of `c.icon`/`c.icons` doesn't even know about that variable in the first place, because it was never implemented to do so. They are based on X properties only.

So there is no "workaround". If you want themed client icons, you have to implement it yourself.

**Comment by tuwuna** [comment]
@sclu1034 The only way that doesn't yield `sleep 0.05; set_icon` is modify [../lib/awful/widget/clienticon.lua](https://github.com/awesomeWM/awesome/blob/master/lib/awful/widget/clienticon.lua) itself.

I am not sure how to implement it myself. Perhaps there is some way I can access these private objects?

**Comment by sclu1034** [comment]
What you're doing _is_ a way to implement this. So if that works for you, you don't have to do anything else.

**Comment by tuwuna** [comment]
Guess it can't be helped then, will go with `If it works, it works.`

**Comment by Aire-One** [comment]
There is currently only the menubar module that respects the system theme (I think).

We definitely needs to have a global implementation for system theme in awesome. Sadly, I don't think anyone is working on something like that at the moment.

As @sclu1034 said, if your patch works for you, mayen it's good enough 🤷‍♂️ 
Alternatively there is https://github.com/intrntbrn/icon_customizer that also tries to provide a similar feature.

**Comment by actionless** [comment]
yeah, if you could extract that logic from menubar and reuse it elsewhere, that would be appreciated

there are few already opened issues about that which you could pick up if you interested in implementing this
