### ISSUE TITLE
How to disable "drag to edge"?

### ISSUE THREAD

**Issue by arielnmz** [awesomeWM/awesome#3595]
I don't know how is this feature named or even where it's documented, but everytime I drag a client to the side of the screen I get this ugly red border:

![image](https://user-images.githubusercontent.com/24735547/159141519-04da0f2c-3ebd-470e-adbc-39d943232546.png)

How can I disable this feature or at least change the color/width of the border?

**Comment by carpii** [comment]
I'd like to tweak/disable this too. 

I'm fairly new to awesomewm, but have spent enough time in rc.lua that I suspect it might be hardcoded rather than configurable

**Comment by Aire-One** [comment]
There are configuration variables from the `mouse` module.

@arielnmz, I think you are interested in the `mouse.snap.edge_enabled` variable https://awesomewm.org/apidoc/input_handling/mouse.html#snap.edge_enabled

@carpii, I think you are interested in the related theme variables https://awesomewm.org/apidoc/input_handling/mouse.html#Theme_variables

**Comment by Aire-One** [comment]
Judging by the comment's emoji reactions, I guess my message solved the problem. I'm closing the issue, then.

**Comment by arielnmz** [comment]
Sorry, haven't had the time to confirm but it seems to be what I was looking for. Thanks!!

**Comment by carpii** [comment]
Yup, thanks from me too!

**Comment by Aire-One** [comment]
> Sorry, haven't had the time to confirm but it seems to be what I was looking for. Thanks!!

No problem. Feel free to re-open if you need more support here.
