### ISSUE TITLE
My Awesome Layout with Catppuccin colors.

### ISSUE THREAD

**Issue by viper0825** [awesomeWM/awesome#3597]
![Screenshot from 2022-03-22 15-34-11](https://user-images.githubusercontent.com/8973748/159561752-6b35a824-07c0-42ba-9659-c5837a6946ce.png)

**Comment by Aire-One** [comment]
This looks like a good candidate for the screenshot thread https://github.com/awesomeWM/awesome/issues/1395.

Please keep your screenshots for this thread and post over there. I'm closing this issue.

**Comment by hideuk** [comment]
give me dotfiles plz)))
