### ISSUE TITLE
Err when build from source (missing package)

### ISSUE THREAD

**Issue by skintclover** [awesomeWM/awesome#3600]
Output of `awesome --version`:

Git Version
Manjaro Linux

**How to reproduce the issue:**

Running make in awesome-git

**Actual result:**

-- lua -> /usr/bin/lua5.4
-- git -> /usr/bin/git
-- asciidoctor -> /usr/bin/asciidoctor
-- gzip -> /usr/bin/gzip
-- ldoc -> /usr/bin/ldoc
-- convert -> /usr/bin/convert
-- Found PkgConfig: /home/linuxbrew/.linuxbrew/bin/pkg-config (found version "0.29.2") 
-- Found Lua: /usr/lib/liblua.so.5.4;/usr/lib/libm.so (found version "5.4.4") 
-- Using version from git: v4.3-1360-gc539e0e43
-- Checking for module 'xcb>=1.6'
--   Found xcb, version 1.14
-- Checking for modules 'glib-2.0;glib-2.0>=2.40;gdk-pixbuf-2.0;cairo;x11;xcb-cursor;xcb-randr;xcb-xtest;xcb-xinerama;xcb-shape;xcb-util;xcb-util>=0.3.8;xcb-keysyms;xcb-keysyms>=0.3.4;xcb-icccm;xcb-icccm>=0.3.8;xcb-xfixes;xcb-xkb;xkbcommon;xkbcommon-x11;cairo-xcb;libstartup-notification-1.0;libstartup-notification-1.0>=0.10;xproto;xproto>=7.0.15;libxdg-basedir;libxdg-basedir>=1.0.0;xcb-xrm'
--   No package 'glib-2.0' found
--   No package 'glib-2.0' found
--   No package 'gdk-pixbuf-2.0' found
--   No package 'cairo' found
--   No package 'xcb-cursor' found
--   No package 'xcb-util' found
--   No package 'xcb-util' found
--   No package 'xcb-keysyms' found
--   No package 'xcb-keysyms' found
--   No package 'xcb-icccm' found
--   No package 'xcb-icccm' found
--   No package 'xkbcommon' found
--   No package 'xkbcommon-x11' found
--   No package 'cairo-xcb' found
--   No package 'libstartup-notification-1.0' found
--   No package 'libstartup-notification-1.0' found
--   No package 'libxdg-basedir' found
--   No package 'libxdg-basedir' found
--   No package 'xcb-xrm' found
CMake Error at /home/npham/.local/lib/python3.10/site-packages/cmake/data/share/cmake-3.22/Modules/FindPkgConfig.cmake:603 (message):
  A required package was not found
Call Stack (most recent call first):
  /home/npham/.local/lib/python3.10/site-packages/cmake/data/share/cmake-3.22/Modules/FindPkgConfig.cmake:825 (_pkg_check_modules_internal)
  awesomeConfig.cmake:165 (pkg_check_modules)
  CMakeLists.txt:33 (include)

**Expected result:**
I checked and sure all the packages needed for the built but I still failed
Pls help me!
![image_2022-03-26_102736](https://user-images.githubusercontent.com/90600763/160223058-8cd9d5e2-25fe-449c-b44d-f07179abd8ab.png)

**Comment by sclu1034** [comment]
The fact that no package is found hints at gerenal issues/misconfiguration with `pkg-config`.
What does `pkg-config --path <package_name>` show for the packages that couldn't be found (e.g. `pkg-config --path xcb-keysyms`)?

**Comment by Aire-One** [comment]
` CMake Error at /home/npham/.local/lib/python3.10/site-packages/cmake/data/share/cmake-3.22/Modules/FindPkgConfig.cmake` ` /home/npham/.local/lib/python3.10/site-packages/cmake/data/share/cmake-3.22/Modules/FindPkgConfig.cmake`

I don't know what these paths are, but it seems like you have installed softwares with some kind of sandbox mechanism that isolate them from others. So they can't see each other...

**Comment by actionless** [comment]
make sure you following the correct steps of installation instructions: https://github.com/awesomeWM/awesome#arch-linux-aur

as far as i see you dont have most of needed deps installed

**Comment by actionless** [comment]
and as mentioned in above comments, it seems your `PATH` env var is ducked up by linuxbrew which also might cause some unexpected problems

**Comment by AlphaTechnolog** [comment]
Having the same problem in void linux, at try to compile with git

**Comment by skintclover** [comment]
I have solution is PKG_PATH so im fixed with export PKG_CONFIG_PATH=/usr/lib/pkgconfig  thx for help me :))
