### ISSUE TITLE
resizing arcchart with rounded edges and thickness crashes awesome

### ISSUE THREAD

**Issue by paulhersch** [awesomeWM/awesome#3601]
Output of `awesome --version`:

```
awesome 4.3 (Too long)
 • Compiled against Lua 5.2.4 (running with Lua 5.2)
 • API level: 4
 • D-Bus support: yes
 • xcb-errors support: no
 • execinfo support: yes
 • xcb-randr version: 1.6
 • LGI version: [string "return require('lgi.version')"]:1: module 'lgi.version' not found:
	no field package.preload['lgi.version']
	no file './share/lua/5.2/lgi/version.lua'
	no file './lgi/version.lua'
	no file './lgi/version/init.lua'
	no file './lib/lua/5.2/lgi/version.so'
	no file './lgi/version.so'
	no file './lib/lua/5.2/loadall.so'
	no file './lib/lua/5.2/lgi.so'
	no file './lgi.so'
	no file './lib/lua/5.2/loadall.so'
 • Transparency enabled: yes
 • Custom search paths: yes
```

 (NixOS's awesome-git provided by ft2k overlay, lgi version is `0.9.2-1`)

**How to reproduce the issue:**

create a widget with arcchart container, rounded edges and set a thickness. As the crash could also be some edgecase with how i setup everything i can share my config parts if needed.

**Actual result:**

It seems like the configuration cant be interpreted by awesome and the fallback theme isnt activated

**Expected result:**
i can use the container properly

**stderr output**
```
E: awesome: Error during a protected call: ...ome-999-unstable/share/awesome/lib/wibox/widget/base.lua:636: A widget's width cannot be negative: -2
stack traceback:
	[C]: in function 'assert'
	...ome-999-unstable/share/awesome/lib/wibox/widget/base.lua:636: in function <...ome-999-unstable/share/awesome/lib/wibox/widget/base.lua:635>
	(...tail calls...)
	...-unstable/share/awesome/lib/wibox/container/arcchart.lua:183: in function <...-unstable/share/awesome/lib/wibox/container/arcchart.lua:179>
	[C]: in function 'xpcall'
	...-999-unstable/share/awesome/lib/gears/protected_call.lua:36: in function <...-999-unstable/share/awesome/lib/gears/protected_call.lua:35>
	(...tail calls...)
	...h-awesome-999-unstable/share/awesome/lib/gears/cache.lua:99: in function <...h-awesome-999-unstable/share/awesome/lib/gears/cache.lua:86>
	(...tail calls...)
	...esome-999-unstable/share/awesome/lib/wibox/hierarchy.lua:132: in function 'hierarchy_update'
	...esome-999-unstable/share/awesome/lib/wibox/hierarchy.lua:140: in function 'hierarchy_update'
	...esome-999-unstable/share/awesome/lib/wibox/hierarchy.lua:140: in function 'hierarchy_update'
	...esome-999-unstable/share/awesome/lib/wibox/hierarchy.lua:140: in function 'hierarchy_update'
	...esome-999-unstable/share/awesome/lib/wibox/hierarchy.lua:140: in function 'hierarchy_update'
	...esome-999-unstable/share/awesome/lib/wibox/hierarchy.lua:140: in function 'hierarchy_update'
	...esome-999-unstable/share/awesome/lib/wibox/hierarchy.lua:140: in function 'hierarchy_update'
	...esome-999-unstable/share/awesome/lib/wibox/hierarchy.lua:229: in function 'update'
	...wesome-999-unstable/share/awesome/lib/wibox/drawable.lua:84: in function 'do_redraw'
	...wesome-999-unstable/share/awesome/lib/wibox/drawable.lua:395: in function <...wesome-999-unstable/share/awesome/lib/wibox/drawable.lua:393>
	[C]: in function 'xpcall'
	...-999-unstable/share/awesome/lib/gears/protected_call.lua:36: in function <...-999-unstable/share/awesome/lib/gears/protected_call.lua:35>
	(...tail calls...)
	...h-awesome-999-unstable/share/awesome/lib/gears/timer.lua:269: in function <...h-awesome-999-unstable/share/awesome/lib/gears/timer.lua:267>
```
I think the problem here is that i resize the widget, because i have an opening animation created with rubato. If the problem cant properly reproduced without config snippets i can provide them.

**Comment by Aire-One** [comment]
Hello @paulhersch, 

> I think the problem here is that i resize the widget, because i have an opening animation created with rubato. If the problem cant properly reproduced without config snippets i can provide them.

Yes, that's most probably the root cause of the issue.

According to my understanding here, you have some sort of wibox that appear on the screen with a "growing animation". At the beginning of the animation, the wibox is too small to host all the widgets it contains.

I haven't investigated our code yet. I guess we could silently ignore the widgets that doesn't fit in the container instead of throwing an error.

Another possible fix I can think of would take place in rubato (or you config?). The wibox should have a "main container" with the final size of the wibox at the end of the animation. So the widgets inside the wibox wouldn't be resized by the animation.
(The widgets would still be redrawn at every frame, it's a major issue I think. But that's an issue with the awesome widget system that any animation lib would have anyway, and we can't prevent it.)
