### ISSUE TITLE
How to view all tags in one like super 0 in dwm

### ISSUE THREAD

**Issue by Kelen-LYC** [awesomeWM/awesome#3604]
Hi. The tag.viewtoggle can view clients ofdifferent tags on one tag. How to view all tags on one, just like "super 0" do in dwm?

**Comment by sclu1034** [comment]
Iterate over the list of tags you want to show and set `.selected = true` for each.

**Comment by Kelen-LYC** [comment]
I've done some work and now it will view all tags except the current tag. Now I need to exclude the current tag in the loop.


 globalkeys = mytable.join(globalkeys,
         -- Toggle tag display.
         awful.key({ modkey, "Control" }, "0",
             function ()
                 local screen = awful.screen.focused()
                     for i = 1,9 do
                         local tag = screen.tags[i]
                             if tag then
                                 awful.tag.viewtoggle(tag)
                             end
                         end
                 end,
                 {description = "toggle tag all", group = "tag"})
             )

**Comment by Kelen-LYC** [comment]
> Iterate over the list of tags you want to show and set `.selected = true` for each.

Thanks. Then I need a function to return the current tag when the same key is pressed. I am trying.

**Comment by Kelen-LYC** [comment]
There are some logic problems.  

```history.store``` is a restoration of the last change.  However, ```view all``` does not change the current tag.
 Tag numbers in history may be discontinuous, so we can't add another ```viewnext```.  

It is necessary to identify and record the current tag.
I will deal when I figure it out.  Suggestions are welcome.

**Comment by Kelen-LYC** [comment]
Done.  After knowing global variables in lua, I use `tag_current` to record the tag which need to be restored.
The next work is to implement it with one button.
```lua
    globalkeys = mytable.join(globalkeys,
         -- Toggle tag display.
         awful.key({ modkey,  }, "0",
             function ()
                 local screen = awful.screen.focused()
                 tag_current = awful.screen.focused().selected_tags
                 for i = 1,9 do
                         local tag = screen.tags[i]
                             --for _,v in ipairs(tag_current) do
                             --if tag==v then
                                 tag.selected = true
                             --else tag.selected = true
                             --end
                             --end
                     end
                 end,
                 {description = "toggle tag all", group = "tag"})
             )
     globalkeys = mytable.join(globalkeys,
         -- Toggle tag display.
         awful.key({ modkey, "Control" }, "0",
             function ()
                 local screen = awful.screen.focused()
                     for i = 1,9 do
                         local tag = screen.tags[i]
                             for k,v in ipairs(tag_current) do
                             if tag==v then
                                 tag.selected = true
                             else tag.selected = false
                             end
                             end
                         end
                 end,
                 {description = "restore tag", group = "tag"})
             )
```

**Comment by croyleje** [comment]
Not sure if your still working on this or not but I came across your comments and worked out a toggle from a single key I will leave the function below.  Note this save the current tag your own and then restores you back to that tag.

```
local state = false
function toggle_view_all_tags()
     local screen = awful.screen.focused()
     if (state == false)
         tag_current = awful.screen.focused().selected_tags
         then
             state = true
             for i = 1,9 do
                 local tag = screen.tags[i]
                 tag.selected = true
             end
         else
             state = false
             for i = 1,9 do
                 local tag = screen.tags[i]
                 for k,v in ipairs(tag_current) do
                     if tag==v then
                         tag.selected = true
                     else
                          tag.selected = false
                     end
                 end
         end
     end

end
```
Hope this helps someone.

**Comment by croyleje** [comment]
Ok Ill leave this closed issue allow after this but I still wasn't happy with the way this worked so I rewrote the function to save the state of currently selected tags and then it restores you back to that state.  It also now only selects tags that have clients on them.  It also set the view to the fair layout which I think is the best to view multiple clients but can easily be changed to what you prefer.

```lua
local state = false
function toggle_view_all_tags()
    local screen = awful.screen.focused()
    if (state = false)
        then
            current_tag = awful.screen.focused().selected_tags
            for i = 1,9 do
                local tag = screen.tags[i]
                if #tag:clients() > 0
                    then
                        tag.selected = true
                    end
            end
            awful.layout.set(awful.layout.suit.fair)
            state = true
        else
            state = false
            awful.layout.set(awful.layout.suit.tile)
            for i = 1,9 do
                local tag = screen.tags[i]
                for _, v in ipairs(current_tag) do
                    if tag==v then
                        tag.selected = true
                    else
                        tag.selected = false
                    end
                end
        end
    end
end
```
