### ISSUE TITLE
Are you sure you want to close this OS window?

### ISSUE THREAD

**Issue by port19x** [awesomeWM/awesome#3606]
Output of `awesome --version`:

awesome v4.3 (Too long)
 • Compiled against Lua 5.3.6 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2

**How to reproduce the issue:**

- Open terminal (I use kitty)
- do something (like take a screenshot)
- Try closing the window

**Actual result:**
Gives a confirmation prompt
![whytho](https://user-images.githubusercontent.com/82055622/163264112-f25387c0-a126-43a8-9752-2fe417c3c9c8.png)

**Expected result:**

Just close the dang window
This wasn't how it functioned initially, first saw this prompt after an update I made today, running arch linux.
Please let me know if you need further context or if there is a more appropiate place to post this support question.

**Comment by port19x** [comment]
My not very polished awesome config: https://git.sr.ht/~port19/dotfiles/tree/master/item/dots/.config/awesome/rc.lua

**Comment by sclu1034** [comment]
Awesome doesn't do anything like this OOTB. It's either part of your own config, or part of the application.

**Comment by jeffmhubbard** [comment]
This is kitty terminal v0.25. 0.24 doesn't do this. I'm not sure why this is a default now. [kitty/#734](https://github.com/kovidgoyal/kitty/issues/734)

**Comment by port19x** [comment]
@jeffmhubbard thanks a lot.
I'll raise an issue there, this really shouldn't be a default setting.
It's really annoying and doesn't even just happen when you have an active job running
