### ISSUE TITLE
Windows spawning new ones get unresponsive.

### ISSUE THREAD

**Issue by Meph24** [awesomeWM/awesome#3607]
Output of `awesome --version`:

awesome v4.3 (Too long)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2

**How to reproduce the issue:**

Spawning any other process or window from within another application.

- Opening a web-link from another application, e.g. Steam, Email, Teamspeak, while no browser is currently open, will cause a browser window to be opened.
- Opening any file from another application that opens in another process/window.
  - Open a file in for example Libreoffice with the "Open" option, which spawns a file-manager to select a file.
  - Open a file via markdown link from within Obsidian, which causes the file to be opened in its configured standard application.

**Actual result:**

The spawning process, that is the window a link is clicked or a file is opened from, becomes unresponsive to the point of windows not receiving a call to close them, or receive any input really. Windows also do not render. Windows are movable as floats, tileable, but show every symptom of a window not rendering, meaning windows "show" what has been in the buffer before at that spot, do not update their content. Very confusing visual, especially considering that newly spawned windows typically cause a rearrangement of windows that make these effects noticeable.
Interestingly enough is the spawned window/process closed windows become responsive again and work as they should as far as I can tell.
For LibreOffice interestingly enough the contents render correctly on resize,
menu bars, toolbars and footer also resize correctly with the window, yet in LibreOfficeCalc the table is not scrollable and the window not closable.
If files are opened in an existing session of a program it would spawn, as a weblink would just spawn a new tab in an already existing browser session, everything seems to work as intended.

**Expected result:**

1. The spawned process is opened freely from the source process.
2. The spawning process does not go unresponsive and hence does not become completely unusable.
3. I do not have to close the spawned process to use the spawning process again.

Having this symptom for many applications and combinations is making me believe awesome is the culprit.
That windows spawn others, making the spawning windows unreachable while it's still clearly visible makes me recognize similarities to the behavior from a "select a file with this file manager i open for you"- dialogue. In Microsoft-Windows, if I remember correctly, you could not click the spawning window or move it while the dialogue was still open. While I would kind of understand some merit to this design choice, I definitely don't need similar behavior if I want to watch a link a friend sent me via messenger or something.

**Comment by actionless** [comment]
try if you can reproduce the same issue when using 1) openbox, 2) awesome-git instead of v4.3

**Comment by Meph24** [comment]
Reproducable in OpenBox.
With awesome-git you probably mean installing from repository main/master and not [this](https://github.com/dictcp/awesome-git).
Installation from repo pending.

**Comment by actionless** [comment]
if it's Reproducable in OpenBox - nothing to do with awesomewm
