### ISSUE TITLE
`client:kill()` doesn't work anymore

### ISSUE THREAD

**Issue by TornaxO7** [awesomeWM/awesome#3614]
Output of `awesome --version`:

<details>

```
awesome v4.3-1360-gc539e0e43 (Too long)
 • Compiled against Lua 5.4.4 (running with 0.9.2)
 • API level: 4
 • D-Bus support: yes
 • xcb-errors support: no
 • execinfo support: yes
 • xcb-randr version: 1.6
 • LGI version: /usr/share/lua/5.4/lgi/version.lua
 • Transparency enabled: yes
 • Custom search paths: no
```

</details>

**How to reproduce the issue:**

Add the following to your `rc.lua`:

<details>

```lua
clientkeys = gears.table.join(
	-- close window
    awful.key({"Mod1", "Shift"}, "q",
        function (client)
            client:kill()
        end,
        {description = "close", group = "client"}
    ),
)
```

</details>

Open up a window and try the keybinding.

**Actual result:**

The window doesn't get killed.

**Expected result:**

The window gets killed.

**Comment by TornaxO7** [comment]
Ok eh, I just realized that all of my clientkeys aren't working anymore.

**Comment by TornaxO7** [comment]
To reproduce my client-keys stuff:

`rc.lua`:

```lua
-- ...
clientkeys = require("mappings.clientkeys")
-- ...
```

`mappings/clientkeys.lua`:

<details>

```lua
------- Awesome Library ------
local gears = require("gears")
local awful = require("awful")

local keys = require("settings.keys")
------------------------------

local tmp = gears.table.join(

	-- Fullscreen
    awful.key({keys.modkey}, "f",
        function (client)
            client.fullscreen = not client.fullscreen
            client:raise()
        end,
        {description = "toggle fullscreen", group = "client"}
    ),

	-- maximize
	-- awful.key({keys.modkey, keys.shift}, "f",
	-- 	function(client)
 --         client.maximized = not client.maximized
	--     end
 --    ),

	-- close window
    awful.key({keys.modkey, keys.shift}, "q",
        function (client)
            client:kill()
        end,
        {description = "close", group = "client"}
    ),

	-- toggle floating window
    awful.key({keys.modkey, keys.shift}, "space",
        awful.client.floating.toggle,
        {description = "toggle floating", group = "client"}
    ),

	-- move back to master
    awful.key({keys.modkey, keys.shift}, "Return", function (c) c:swap(awful.client.getmaster()) end,
              {description = "move to master", group = "client"}),

	-- toggle keep on top
    awful.key({keys.modkey}, "t",
        function (c)
            c.ontop = not c.ontop
        end,
            {description = "toggle keep on top", group = "client"}
    ),

	-- minimize
    awful.key({keys.modkey, keys.shift}, ".",
        function (c)
            -- The client currently has the input focus, so it cannot be
            -- minimized, since minimized clients can't have the focus.
            c.minimized = true
        end,
        {description = "minimize", group = "client"}
    )
)

return tmp
```

</details>

`settings/keys.lua`

<details>

```lua
local keys = {}
keys.modkey = "Mod1" 	-- Alt-Key
keys.modkey2 = "Mod4" 	-- Win-Key
keys.shift = "Shift"
keys.control = "Control"

return keys
```

</details>

**Comment by Aire-One** [comment]
Hello,

I'm currently away, so I can't use much time to investigate your issue. At first look,it seems to me there is an issue in the way you declare your keybindings.

`clientkeys = require("mappings.clientkeys")` is incomplete, you'll need to use the proper API call from `awful.kayboard` to register your client keybindings (awful.keyboard.append_client_keybindings). And the preferred way to call this method is inside the global client `"request::default_keybindings"` signal.

**Comment by TornaxO7** [comment]
Ok, I could fix my keybindings now :D 
This is in my config now:

```lua
-- ...

-- bindings
awful.keyboard.append_global_keybindings(require("mappings.keybindings.keybindings"))
awful.keyboard.append_client_keybindings(require("mappings.clientkeys"))
awful.mouse.append_client_mousebindings(require("mappings.client_mouse"))
awful.mouse.append_global_mousebindings(require("mappings.mouse"))

-- ...
```

And that's how it looks like:
`mappings.client_mouse.lua`

<details>

```lua
------- Awesome Library ------
local gears = require("gears")
local awful = require("awful")
local keys = require("settings.keys")

------------------------------

local keybindings = {
    awful.button({ }, 1, function (c)
        c:emit_signal("request::activate", "mouse_click", {raise = true})
    end),

    awful.button({ keys.modkey }, 1, function (c)
        c:emit_signal("request::activate", "mouse_click", {raise = true})
        awful.mouse.client.move(c)
    end),

    awful.button({ keys.modkey }, 3, function (c)
        c:emit_signal("request::activate", "mouse_click", {raise = true})
        awful.mouse.client.resize(c)
    end)
}

return keybindings
```

</details>

Thank you for the information with `awful.keyboard` I didn't knew about it!

**Comment by Aire-One** [comment]
Nice, happy to read you succeed!

> Could you please explain where I can find this request::default_keybindings signal?

Right here https://awesomewm.org/apidoc/core_components/client.html#request::default_keybindings

Maybe you should also take a look at the default rc.lua to see how it's used https://awesomewm.org/apidoc/sample%20files/rc.lua.html

**Comment by TornaxO7** [comment]
Oh I see, could it be that those `request`s are lelatively new? I can't remember them, when I started to use awesomewm.

**Comment by TornaxO7** [comment]
Could you please explain me the difference between this:

```lua
awful.keyboard.append_global_keybindings(require("mappings.keybindings.keybindings"))
awful.keyboard.append_client_keybindings(require("mappings.clientkeys"))
awful.mouse.append_client_mousebindings(require("mappings.client_mouse"))
awful.mouse.append_global_mousebindings(require("mappings.mouse"))
```

and this:

```lua
client.connect_signal("request::default_mousebindings", function()
    awful.mouse.append_client_mousebindings({ 
        -- ...
    })
end)
```
? Should I prefer to use this `request` or is it fine to do it with those four lines?

**Comment by Aire-One** [comment]
(Sorry for the late reply, I somehow missed your lasts posts)

> Oh I see, could it be that those requests are lelatively new?

Depends on your "relatively new" definition. :upside_down_face: They are an awesome-git thing

> I can't remember them, when I started to use awesomewm.

If you started with awesome 4.3 or early release, these request stuff wasn't a thing yet.

> Could you please explain me the difference [...]

Basically:

- With the first one, you explicitly ask awful.{keyboard,mouse} to append these bindings to the default global/client binding context
- With the second one, you set a handler that will be called by Awesome (when it's ready to do so) "ask awful.mouse to do append these bindings to the default (global/)client binding context"

The idea behind the `"request::*"` signals is that it's Awesome that will ask for X or Y thing when it's ready to receive/do them (1). It makes your `rc.lua` more modulariz-abe because if you define correctly these handlers, you can load them in any order, unload them, replace them, have multiple definition for them, ...

(1) Note that many (all?) request handler are actually ready to be called even before the rc.lua file is loaded, so it's really a game of "placing some code in callbacks waiting for their invocation latter". This is because Awesome initialize most of its internals before loading the user rc file, then some modules will do further/on-demand initialization by calling for these `"request"` signals.

> Should I prefer to use this request or is it fine to do it with those four lines?

I would prefer the request variant, but it's ok to use the "old" way of doing. I'm calling that the "old way" because it's how we did before introducing request handlers, and it will continue to work until we decide to break backward compatibility.
