### ISSUE TITLE
[Question] How to access `ruled` module?

### ISSUE THREAD

**Issue by TornaxO7** [awesomeWM/awesome#3615]
The [docs](https://awesomewm.org/apidoc/declarative_rules/ruled.client.html#awful.rules) are saying that I need to use the module `ruled`  but how can I access it? I tried the following:

```lua
awful.ruled.client.append -- and so on....
local ruled = require("ruled")
```
but none of them work.

What am I doing wrong?

**Comment by Elv13** [comment]
Hello,

`ruled` only exist in the git-master version of AwesomeWM. It is called `awful.rules` in v4.3. If you like the git-master documentation better, you can consider installing the git version of AwesomeWM. This is easy-ish in Gentoo/Arch and we provide `make packages` scripts to generate packages on Ubuntu/Debian.

Otherwise, `awful.rules` API is very close to `ruled.client`. The name change was mostly because there are now rules for other types of objects, such as notifications.

**Comment by TornaxO7** [comment]
> If you like the git-master documentation better, you can consider installing the git version of AwesomeWM.

Hm.. that's strange, I'm already using the `git` version of AwesomeWM:

```
local/awesome-git 4.3.1360.gc539e0e43-1
    Highly configurable framework window manager
```
this is a part of my output of `pacman -Qs awesome`.

**Comment by TornaxO7** [comment]
> ruled only exist in the git-master version of AwesomeWM. It is called awful.rules in v4.3.

That's strange, I have this line here:

`rc.lua`
```lua
-- ...
awful.rules.client.append_rules(require("rules"))
-- ...
```

And this is in my `rules.lua`:
```lua
-- general rules
local rules = {

	-----===== Application specifique =====-----

    -- ----------------------------
    -- Default for all clients
    -- ----------------------------
    { rule = { },
        properties = {
            border_width = beautiful.border_width,
            border_color = beautiful.border_normal,
            raise = true,
            keys = clientkeys,
            buttons = client_mouse,
            screen = awful.screen.preferred,
     }
    },
    -- ...
}

return rules
```
But AwesomeWM returns me this error:

```lua
attempt to index a nil value (field `client`)
```

**Comment by Elv13** [comment]
And what kind of error do you get when you do `local ruled_client = require("ruled.client")`? 

(you can use Xephyr to easily get the logs in a terminal rather than have to restart your session)

**Comment by TornaxO7** [comment]
![image](https://user-images.githubusercontent.com/50843046/167478950-3d4a4a14-3e49-4bf8-8663-e4aab3159f94.png)

Those are the first error messages which I get, if I have the following *first* line of code in my `rc.lua`:
```lua
pcall(require, "luarocks.loader")

-- ===============
-- Includings
-- ===============
local gears = require("gears")
local awful = require("awful")
local beautiful = require("beautiful")
local naughty = require("naughty")


-- require("awful.hotkeys_popup.keys")

naughty.connect_signal("request::display_error", function(message, startup)
    naughty.notification {
        urgency = "critical",
        title   = "Oops, an error happened"..(startup and " during startup!" or "!"),
        message = message
    }
end)

-- awful.rules.client.append_rules(require("rules"))
local ruled_client = require("ruled.client")
```

**Comment by TornaxO7** [comment]
Ok, so I think that this issue can be closed since my initial question has been answered :) Thank you guys!
