### ISSUE TITLE
undefined reference to 'luaL_newstate' when I try to run make 

### ISSUE THREAD

**Issue by ColemakDH** [awesomeWM/awesome#3617]
I'm not answering the other stuff like version of awesome because I haven't even installed it yet, but here's a copy n paste of what happens in the terminal when i run make
colemak@pop-os:/awesome$ make
Building…
[  0%] Built target test-gravity
[  0%] Linking C executable lgi-check
/usr/bin/ld: CMakeFiles/lgi-check.dir/build-utils/lgi-check.c.o: in function `main':
lgi-check.c:(.text+0x1f): undefined reference to `luaL_newstate'
/usr/bin/ld: lgi-check.c:(.text+0x2f): undefined reference to `luaL_openlibs'
/usr/bin/ld: lgi-check.c:(.text+0x45): undefined reference to `luaL_loadstring'
/usr/bin/ld: lgi-check.c:(.text+0x70): undefined reference to `lua_pcallk'
/usr/bin/ld: lgi-check.c:(.text+0x8a): undefined reference to `lua_tolstring'
collect2: error: ld returned 1 exit status
make[3]: *** [CMakeFiles/lgi-check.dir/build.make:105: lgi-check] Error 1
make[2]: *** [CMakeFiles/Makefile2:13184: CMakeFiles/lgi-check.dir/all] Error 2
make[1]: *** [Makefile:171: all] Error 2
make: *** [Makefile:15: cmake-build] Error 2
colemak@pop-os:/awesome$ 

*also there is normally a ~ after pop-os: but it makes it put lines through the text*

I'm not sure what the problem is and was wondering if anyone else has had a similar issue before and knew what was up, I'll try to answer any questions asap

**Comment by sclu1034** [comment]
You're missing Lua's shared library (the `.so` file) that implements those functions. On Debian-based distributions, such shared libraries are usually provided in a separate `-dev` package. Use your package manager's search functionality to make sure, but most likely it'll be the same package name you used to install the Lua binary, but with a `-dev` prefix.

**Comment by Elv13** [comment]
That or it's loading headers for a different version of Lua than the one it is attempting to link with.
