### ISSUE TITLE
Slow startup with grey screen when launching

### ISSUE THREAD

**Issue by Jigoku** [awesomeWM/awesome#3628]
I'm having an issue in the past several weeks where Awesome takes a while to startup when launching an X session. I do not believe the version of Awesome has changed since things were last working perfectly.

I have tried rebuilding awesome and dependency related packages, but to no effect.

Running Awesome 4.3 on Slackware (-current), using the slackbuild package); And also, using nvidia's blob driver (have also tried rolling back to old driver there to see if this was the cause, but no effect).

I have also tried disabling any autostart commands / daemons along with a fresh awesome config but the problem still persists.

Output of `awesome --version`:
```                                                                      
awesome v4.3 (Too long)
 • Compiled against Lua 5.1.5 (running with Lua 5.1)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
```

**How to reproduce the issue:**
Run `startx`

**Actual result:**
Awesome takes a long time to start and sits at a blank grey screen for maybe 20 seconds before being functional.

**Expected result:**

Awesome should load up almost immediately.

**Comment by mattplm** [comment]
Hello, 

I've never had this problem, either when running version 4.3 or now running the master branch. 

When launching `picom` before awesome in my `.xinitrc`, I can see a grey background on startup, but this lasts at most a second, not 20. Do you happen to launch software outside your awesome configuration (`.xinitrc`, `.profile`...)?

**Comment by Jigoku** [comment]
>  Do you happen to launch software outside your awesome configuration (.xinitrc, .profile...)?
Seems that was the issue, made a new user account and everything worked fine... went back and removed some cruft from .profile, and that seems to have fixed things...

Many thanks!I totally overlooked that.
