### ISSUE TITLE
AwesomeWM doesn't startup

### ISSUE THREAD

**Issue by Cephetir** [awesomeWM/awesome#3630]
Output of `awesome --version`:

awesome v4.3 (Too long)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2

**How to reproduce the issue:**

Xephyr :2 -screen 1280x720
export DISPLAY=:2
awesome

**Actual result:**

error while running function!
stack traceback:
	/usr/local/share/awesome/lib/awful/_compat.lua:37: in main chunk
	[C]: in function 'require'
	/usr/local/share/awesome/lib/awful/init.lua:9: in main chunk
	[C]: in function 'require'
	/usr/local/etc/xdg/awesome/rc.lua:8: in main chunk
error: /usr/local/share/awesome/lib/awful/_compat.lua:37: attempt to call a nil value (field 'set_newindex_miss_handler')
2022-06-09 17:29:12 E: awesome: main:866: couldn't find any rc file

**Expected result:**

awesomewm startup

**Comment by Crylia** [comment]
"couldn't find any rc file"
You don't have a rc.lua file at .config/awesome
either put one there or use -c to specify a config location

**Comment by actionless** [comment]
```
/usr/local/etc/xdg/awesome/rc.lua:8: in main chunk
error: /usr/local/share/awesome/lib/awful/_compat.lua:37: attempt to call a nil value (field 'set_newindex_miss_handler')
2022-06-09 17:29:12 E: awesome: main:866: couldn't find any rc file
```

your /usr/local/etc/xdg/awesome/rc.lua doesnt match the version of your awesome wm

most probably you got two installations of it at the same time, normal one and in /usr/local

**Comment by Elv13** [comment]
> error: /usr/local/share/awesome/lib/awful/_compat.lua:37: attempt to call a nil value (field 'set_newindex_miss_handler')

This indicates that the `awesome` binary is older than v4.3 because `set_newindex_miss_handler` is missing, which isn't possible with the right executable. That function is hardcoded in the C code, it's not possible to remove it, so the only possibility is that it wasn't there in the first place.

Uninstalling `awesome`, use `whereis awesome` and make sure it's deleted, then installing awesome again is the solution to this.

**Comment by actionless** [comment]
considering what it's october now - i think it's safe to close this as problem is either solved or not actual anymore
