### ISSUE TITLE
Help with startup

### ISSUE THREAD

**Issue by dylanpjx** [awesomeWM/awesome#3631]
**Output of `awesome --version`:**

```
~ → awesome --version
awesome v4.3 (Too long)
 • Compiled against Lua 5.3.6 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
```
### 

I have been following [this tutorial](https://wiki.archlinux.org/title/awesome#Autostart) and running an autostart script in my rc.lua.

The [startup script is here](https://github.com/dylanpjx/dotfiles/blob/master/linux/scripts/autorun.sh) for reference.

**Expected result:**
In the past, the config worked as per normal and everything in the startup script would run flawlessly.

**Actual result:**
Now, nitrogen fails to setup the wallpaper for my second monitor and it would show a black or pixelated screen. Also, all the xset commands run in the autostart script are not executed. I would have to restart AwesomeWM on a fresh boot to get it all working.

**What I have tried:**
I have tried to port those over to .xinitrc/.xprofile. However, since I'm using GDM, .xinitrc does not get sourced (at least not to my knowledge), and leaving xset and nitrogen commands in .xprofile does not work for some reason. I am aware that I can set the wallpaper using Awesome, but I use nitrogen's screen fit to fit a higher resolution wallpaper. 

Could someone point me to a direction in which I could debug/fix this issue? Thank you!

**Comment by actionless** [comment]
run nitrogen from inside awesome?
