### ISSUE TITLE
Typos in Class client doc

### ISSUE THREAD

**Issue by madprops** [awesomeWM/awesome#3632]
https://awesomewm.org/doc/api/classes/client.html

Check the image:

![docbug](https://user-images.githubusercontent.com/206498/173459330-897c4fec-e73b-41f9-8810-583fa82af883.jpg)

"Define it" ?

"iconify" instead of "iconified" ?

Also here:

![iconfd2](https://user-images.githubusercontent.com/206498/173459650-867e7f09-541d-4dee-b684-5e568dd2d26b.jpg)

**Comment by Aire-One** [comment]
Hmm... That `i.e.` is disturbing because ldoc considers it as the end of the sentence and truncates the brief.

**Comment by madprops** [comment]
Opened an issue in LDoc https://github.com/lunarmodules/LDoc/issues/374
