### ISSUE TITLE
Restart awesomeWM from terminal

### ISSUE THREAD

**Issue by jasper1378** [awesomeWM/awesome#3637]
Hello all,

In my awesomeWM config I have a keybind that calls `awesome.restart`. I was wondering if there was anyway I could restart/reload/refresh awesomeWM through a terminal command (so that I could use it in a bash script)?

Thanks for the help!

**Comment by arsham** [comment]
```bash
awesome-client 'require("awesome").restart()'
```

**Comment by jasper1378** [comment]
<pre><code>
string "Error during execution: [string "require("awesome").restart()"]:1: module 'awesome' not found:
	no field package.preload['awesome']
	no file '/usr/share/lua/5.4/awesome.lua'
	no file '/usr/share/lua/5.4/awesome/init.lua'
	no file '/usr/lib/lua/5.4/awesome.lua'
	no file '/usr/lib/lua/5.4/awesome/init.lua'
	no file './awesome.lua'
	no file './awesome/init.lua'
	no file '/home/jasper1378/.config/awesome/awesome.lua'
	no file '/home/jasper1378/.config/awesome/awesome/init.lua'
	no file '/etc/xdg/awesome/awesome.lua'
	no file '/etc/xdg/awesome/awesome/init.lua'
	no file '/usr/share/awesome/lib/awesome.lua'
	no file '/usr/share/awesome/lib/awesome/init.lua'
	no file '/usr/lib/lua/5.4/awesome.so'
	no file '/usr/lib/lua/5.4/loadall.so'
	no file './awesome.so'
	no file '/home/jasper1378/.config/awesome/awesome.so'
	no file '/etc/xdg/awesome/awesome.so'
	no file '/usr/share/awesome/lib/awesome.so'"
</code></pre>

**Comment by Elv13** [comment]
It's just `awesome.restart()`, there is no `require` since this is a built-in

**Comment by sclu1034** [comment]
Additionally, `awesome-client` needs to be run with access to the same D-Bus session as the Awesome process.
An alternative that doesn't have such a restriction is `pkill -HUP awesome`.

**Comment by jasper1378** [comment]
Thank you so much.
