### ISSUE TITLE
Textbox using valign and align opposed to what other widgets/container use.

### ISSUE THREAD

**Issue by Crylia** [awesomeWM/awesome#3640]
Output of `awesome --version`:

```
awesome v4.3-1360-gc539e0e4 (Too long)
 • Compiled against Lua 5.3.6 (running with Lua 5.3)
 • API level: 4
 • D-Bus support: yes
 • xcb-errors support: no
 • execinfo support: yes
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
 • Transparency enabled: yes
 • Custom search paths: no
```

AFAIK every other widget than wibox.widget.textbox uses valign and halign which makes it easy to remember.
wibox.widget.textbox on the other hand uses valign and align which is inconsistent and lead to many missuses in my, and possibly also others, config. For example I always either write valign and halign, or halign and align. Changing wibox.widget.textbox to valign and halign would make it more clear and consistent.

**Comment by actionless** [comment]
i think understanding your problem would be easier if you provide some screenshots illustrating your problem and highlight specific parts of the apidoc which by your opinion are not designed or implemented correctly

**Comment by Elv13** [comment]
i think i get the problem and i agree. we should have consistent names and
in this case we don't. this isn't super labor intensive to fix. change the
name, add a legacy deprecated property, add a test for the property, update
all internal usage so it doesn't trigger the deprecated usage tests.
