### ISSUE TITLE
Is it possible to selectively pick the Lua version awesome uses?

### ISSUE THREAD

**Issue by Jigoku** [awesomeWM/awesome#3652]
Output of `awesome --version`:
```
> $ awesome --version                                                                               
awesome v4.3 (Too long)
 • Compiled against Lua 5.1.5 (running with Lua 5.1)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
```
Hi, how can i chose which version of Lua awesome uses? Whether there is a compile time flag to pick it? Can't seem to find something that does.

On Slackware, Lua is available through the slackbuilds packages as; lua, lua52, and lua53 (i'm guessing for compatibility with other programs)

For example:
```
> $ whereis lua5.3                                                                                  
lua5.3: /usr/bin/lua5.3 /usr/include/lua5.3 /usr/man/man1/lua5.3.1.gz
```
However, awesome only looks for "lua" as far as i can tell, so it sticks to 5.1.5. Mostly asking as for needing feature support such as utf8 module, which i believe is a newer addition to lua 5.3?

**Comment by Elv13** [comment]
Hello, this is [documented here](https://awesomewm.org/apidoc/documentation/10-building-and-testing.md.html). Please note that luajit2.1 is pretty much lua 5.1 with some 5.2 features, so keeping your config 5.1 compatible is a rather useful thing to do. LuaJIT is the fastest engine.

**Comment by sclu1034** [comment]
To elaborate slightly:

Awesome does not pick a Lua version at runtime, especially not based on PATH (i.e. what your shell uses to pick a binary called `lua`). As the version output above indicates, Awesome is _compiled against_ a Lua version. And regardless of where you move that compiled binary, even between machines, it will always expect the same version.

So you need to compile Awesome from source, using the documentation @Elv13 provided.

**Comment by Jigoku** [comment]
Ok that clears that up, many thanks both to of you.
