### ISSUE TITLE
Vivaldi crashes when closing any of Vivaldi's windows with awesomeWM

### ISSUE THREAD

**Issue by Inky1003** [awesomeWM/awesome#3660]
Output of `awesome --version`:

awesome v4.3 (Too long)
 • Compiled against Lua 5.3.6 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2

**How to reproduce the issue:**

1. Open Vivaldi
2. Open any other window from Vivaldi (It could be settings or a new window)
3. Close any of the windows

**Actual result:**

Vivaldi keeps working just fine

**Expected result:**

Vivaldi crashes and closes everything

**Comment by Elv13** [comment]
what happens if you use another window manager like openbox? does it happen
100% of the time?

**Comment by Aire-One** [comment]
I haven't experienced such bug with awesome myself and I'm not a user of Vivaldi.

According to this thread on Reddit https://www.reddit.com/r/awesomewm/comments/vffid7/vivaldi_crashing_when_closing_window_in_awesome_wm/?utm_medium=android_app&utm_source=share, this is a bug from Vivaldi and it's reproductive on different DE/WM.

**Comment by Inky1003** [comment]
Yes, It's only on Vivaldi, Chromium and other browsers don't have this problem, and It's only on awesomeWM. Other ones work fine.

**Comment by Elv13** [comment]
Well, so we have a semi closed source app that's doing something that makes it crash. I think the bug should be reported to them. AwesomeWM is 15 years old at this point and the current XCB core is 13y/o. If there was something seriously wrong with those code paths, I think we would have found out long ago. I say the ball is pretty much on Vivaldi to fix this.

This isn't the first time in some apps misbehave, Java ones being the prime examples, but in that case, they had *explicit* code to behave wrongly on Awesome.
