### ISSUE TITLE
Ability to Sustain Previously Set Screen Brightness After Idle Timeouts

### ISSUE THREAD

**Issue by Lonniebiz** [awesomeWM/awesome#3661]
Each time that I leave my computer for several minutes, the screen powers off. When I move my mouse the screen come back on instantly, but it always comes on at 100% brightness instead of honoring my previously set brightness level.

This happens so often, that I've created hotkeys to quickly reset the brightness to my desired level:
https://unix.stackexchange.com/questions/687453/

I couldn't find [anything about brightness](https://www.google.com/search?as_q=&as_epq=brightness&&as_sitesearch=https%3A%2F%2Fawesomewm.org%2Fdoc%2Fapi%2F) in the documentation, so perhaps Awesome doesn't consider this within its realm of responsibility. Still, I'd appreciate helpful suggestions.

For example, in the Awesome configuration is there an event handler that will allow me to fire a custom function each time I return from a power saving state?

Debian 11
awesome v4.3 (Too long)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2

**Comment by Elv13** [comment]
>  so perhaps Awesome doesn't consider this within its realm of responsibility

Correct, AwesomeWM is a window manager, this is out of scope. Personally, I have scripts that do things like:

```sh
echo 1000 > /sys/class/leds/tpacpi\:\:kbd_backlight/brightness 
echo 300 > /sys/devices/pci0000:00/0000:00:02.0/drm/card0/card0-eDP-1/intel_backlight/brightness
```

My laptop seems to remember the correct value when getting out of sleep. To run them on events, I guess the answer is https://unix.stackexchange.com/questions/152039/how-to-run-a-user-script-after-systemd-wakeup
