### ISSUE TITLE
yay -S awesome-luajit-git fail.

### ISSUE THREAD

**Issue by matianhe3** [awesomeWM/awesome#3662]
==> Starting build()...
make -C lgi
make[1]: Entering directory '/home/m/.cache/yay/luajit-lgi-git/src/lgi/lgi'
pkg-config --exists 'gobject-introspection-1.0 >= 0.10.8' --print-errors
touch .depcheck
cc  -fPIC  -I/usr/include/luajit-2.1  -O2 -I/usr/include/gobject-introspection-1.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/sysprof-4 -pthread  -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -c -o buffer.o buffer.c
cc  -fPIC  -I/usr/include/luajit-2.1  -O2 -I/usr/include/gobject-introspection-1.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/sysprof-4 -pthread  -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -c -o callable.o callable.c
cc  -fPIC  -I/usr/include/luajit-2.1  -O2 -I/usr/include/gobject-introspection-1.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/sysprof-4 -pthread  -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -c -o core.o core.c
cc  -fPIC  -I/usr/include/luajit-2.1  -O2 -I/usr/include/gobject-introspection-1.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/sysprof-4 -pthread  -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -c -o gi.o gi.c
cc  -fPIC  -I/usr/include/luajit-2.1  -O2 -I/usr/include/gobject-introspection-1.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/sysprof-4 -pthread  -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -c -o marshal.o marshal.c
cc  -fPIC  -I/usr/include/luajit-2.1  -O2 -I/usr/include/gobject-introspection-1.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/sysprof-4 -pthread  -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -c -o object.o object.c
object.c: In function ‘object_new’:
object.c:553:7: warning: ‘GParameter’ is deprecated [-Wdeprecated-declarations]
  553 |       GParameter *params;
      |       ^~~~~~~~~~
In file included from /usr/include/glib-2.0/gobject/gobject.h:26,
                 from /usr/include/glib-2.0/gobject/gbinding.h:29,
                 from /usr/include/glib-2.0/glib-object.h:22,
                 from lgi.h:50,
                 from object.c:12:
/usr/include/glib-2.0/gobject/gparam.h:273:8: note: declared here
  273 | struct _GParameter /* auxiliary structure for _setv() variants */
      |        ^~~~~~~~~~~
object.c:565:7: warning: ‘GParameter’ is deprecated [-Wdeprecated-declarations]
  565 |       params = g_newa (GParameter, size);
      |       ^~~~~~
/usr/include/glib-2.0/gobject/gparam.h:273:8: note: declared here
  273 | struct _GParameter /* auxiliary structure for _setv() variants */
      |        ^~~~~~~~~~~
object.c:565:7: warning: ‘GParameter’ is deprecated [-Wdeprecated-declarations]
  565 |       params = g_newa (GParameter, size);
      |       ^~~~~~
/usr/include/glib-2.0/gobject/gparam.h:273:8: note: declared here
  273 | struct _GParameter /* auxiliary structure for _setv() variants */
      |        ^~~~~~~~~~~
object.c:576:7: warning: ‘g_object_newv’ is deprecated: Use 'g_object_new_with_properties' instead [-Wdeprecated-declarations]
  576 |       return lgi_object_2lua (L, g_object_newv (gtype, size, params),
      |       ^~~~~~
/usr/include/glib-2.0/gobject/gobject.h:452:13: note: declared here
  452 | gpointer    g_object_newv                     (GType           object_type,
      |             ^~~~~~~~~~~~~
cc  -fPIC  -I/usr/include/luajit-2.1  -O2 -I/usr/include/gobject-introspection-1.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/sysprof-4 -pthread  -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -c -o record.o record.c
cc -shared -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -o corelgilua51.so buffer.o callable.o core.o gi.o marshal.o object.o record.o -lgirepository-1.0 -lgobject-2.0 -Wl,--export-dynamic -lgmodule-2.0 -pthread -lglib-2.0 -lglib-2.0 -lffi
echo "return '0.9.2'" > version.lua
make[1]: Leaving directory '/home/m/.cache/yay/luajit-lgi-git/src/lgi/lgi'
==> Starting check()...
make -C lgi
make[1]: Entering directory '/home/m/.cache/yay/luajit-lgi-git/src/lgi/lgi'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/m/.cache/yay/luajit-lgi-git/src/lgi/lgi'
make -C tests check
make[1]: Entering directory '/home/m/.cache/yay/luajit-lgi-git/src/lgi/tests'
pkg-config --exists 'gio-2.0 cairo cairo-gobject gobject-introspection-1.0 gmodule-2.0 libffi >= 0.10.8' --print-errors
touch .depcheck
cc  -fPIC  -I/usr/include/luajit-2.1  -O2 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/sysprof-4 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/cairo -I/usr/include/lzo -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/harfbuzz -I/usr/include/pixman-1 -I/usr/include/gobject-introspection-1.0 -pthread  -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -I . -c -o regress.o /usr/share/gobject-introspection-1.0/tests/regress.c
cc -shared -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -o libregress.so regress.o -lgio-2.0 -lcairo-gobject -lcairo -lgirepository-1.0 -lgobject-2.0 -Wl,--export-dynamic -lgmodule-2.0 -pthread -lglib-2.0 -lglib-2.0 -lffi  -llua
LDFLAGS="" CFLAGS=""						\
g-ir-scanner --warn-all --no-libtool --quiet --output=Regress-1.0.gir	\
  --namespace=Regress --nsversion=1.0				\
  --include=cairo-1.0 --include=Gio-2.0				\
  --library-path=/usr/lib --library-path=/usr/X11R6/lib		\
  --library-path=/usr/local/lib					\
  /usr/share/gobject-introspection-1.0/tests/regress.c /usr/share/gobject-introspection-1.0/tests/regress.h			\
 -lregress
g-ir-compiler --output=Regress-1.0.typelib Regress-1.0.gir
cd .. && LD_LIBRARY_PATH=tests:$LD_LIBRARY_PATH \
    GI_TYPELIB_PATH=tests:$GI_TYPELIB_PATH \
    LUA_PATH="./?.lua;;" \
    LUA_CPATH="./?.so;;" \
    /usr/bin/dbus-run-session luajit tests/test.lua
dbus-daemon[50119]: [session uid=1000 pid=50119] Activating service name='org.a11y.Bus' requested by ':1.0' (uid=1000 pid=50120 comm="luajit tests/test.lua")
dbus-daemon[50119]: [session uid=1000 pid=50119] Successfully activated service 'org.a11y.Bus'

(luajit:50120): Lgi-WARNING **: 15:00:42.809: Error raised while calling 'lgi.cbk (number): Regress': attempt to call a number value

(luajit:50120): Lgi-WARNING **: 15:00:42.809: Error raised while calling 'lgi.cbk (string: 0x7f0056901bc8): Regress': attempt to call a string value

(luajit:50120): Lgi-WARNING **: 15:00:42.809: Error raised while calling 'lgi.cbk (table: 0x7f00561e18b8): Regress': attempt to call a table value

(luajit:50120): Lgi-WARNING **: 15:00:42.809: Error raised while calling 'lgi.cbk (table: 0x7f0051da7838): Regress': attempt to call a table value
gireg   : all 114 tests passed.
dbus-daemon[50127]: Activating service name='org.a11y.atspi.Registry' requested by ':1.0' (uid=1000 pid=50120 comm="luajit tests/test.lua")
dbus-daemon[50127]: Successfully activated service 'org.a11y.atspi.Registry'
SpiRegistry daemon is running with well-known name - org.a11y.atspi.Registry
marshal : all 1 tests passed.
make[1]: *** [Makefile:61: check-lua] Error 139
make[1]: Leaving directory '/home/m/.cache/yay/luajit-lgi-git/src/lgi/tests'
make: *** [Makefile:31: check] Error 2
==> ERROR: A failure occurred in check().
    Aborting...
checking dependencies...
warning: dependency cycle detected:
warning: ruby will be removed after its rubygems dependency
warning: dependency cycle detected:
warning: ruby-bundler will be removed after its rubygems dependency
warning: dependency cycle detected:
warning: ruby-bundler will be removed after its ruby dependency
warning: dependency cycle detected:
warning: ruby-reline will be removed after its ruby dependency
warning: dependency cycle detected:
warning: ruby-irb will be removed after its ruby dependency
warning: dependency cycle detected:
warning: ruby-json will be removed after its ruby dependency
warning: dependency cycle detected:
warning: ruby-stringio will be removed after its ruby dependency
warning: dependency cycle detected:
warning: ruby-psych will be removed after its ruby dependency
warning: dependency cycle detected:
warning: ruby-rdoc will be removed after its ruby dependency
warning: dependency cycle detected:
warning: ruby-minitest will be removed after its ruby dependency
warning: dependency cycle detected:
warning: ruby-power_assert will be removed after its ruby dependency
warning: dependency cycle detected:
warning: ruby-rake will be removed after its ruby dependency
warning: dependency cycle detected:
warning: ruby-rexml will be removed after its ruby dependency
warning: dependency cycle detected:
warning: ruby-test-unit will be removed after its ruby dependency

Packages (34) asciidoctor-2.0.17-1  cmake-3.23.2-2  docbook-xml-4.5-9  docbook-xsl-1.79.2-7  gobject-introspection-1.72.0-1  ldoc-1.4.6-5  libxslt-1.1.35-1  libyaml-0.2.5-1
              lua-filesystem-1.8.0-3  lua-penlight-1.12.0-2  python-beaker-1.11.0-8  python-importlib-metadata-4.8.1-3  python-mako-1.1.6-3  python-markdown-3.3.7-1
              python-markupsafe-2.1.1-1  python-zipp-3.8.1-1  rhash-1.4.2-1  ruby-3.0.4-2  ruby-bundledgems-3.0.4-2  ruby-bundler-2.3.17-1  ruby-irb-1.4.1-1  ruby-json-2.6.2-1
              ruby-minitest-5.15.0-1  ruby-power_assert-2.0.1-1  ruby-psych-4.0.4-2  ruby-rake-13.0.6-1  ruby-rdoc-6.4.0-2  ruby-reline-0.3.1-1  ruby-rexml-3.2.5-1
              ruby-stdlib-3.0.4-2  ruby-stringio-3.0.2-1  ruby-test-unit-3.5.3-1  rubygems-3.3.15-1  xmlto-0.0.28-4

Total Removed Size:  136.94 MiB

:: Do you want to remove these packages? [Y/n]
:: Processing package changes...
( 1/34) removing xmlto                                                                                        [#################################################################] 100%
( 2/34) removing ldoc                                                                                         [#################################################################] 100%
( 3/34) removing lua-penlight                                                                                 [#################################################################] 100%
( 4/34) removing lua-filesystem                                                                               [#################################################################] 100%
( 5/34) removing docbook-xsl                                                                                  [#################################################################] 100%
( 6/34) removing docbook-xml                                                                                  [#################################################################] 100%
( 7/34) removing libxslt                                                                                      [#################################################################] 100%
( 8/34) removing cmake                                                                                        [#################################################################] 100%
( 9/34) removing rhash                                                                                        [#################################################################] 100%
(10/34) removing asciidoctor                                                                                  [#################################################################] 100%
(11/34) removing rubygems                                                                                     [#################################################################] 100%
(12/34) removing ruby                                                                                         [#################################################################] 100%
(13/34) removing ruby-bundledgems                                                                             [#################################################################] 100%
(14/34) removing ruby-test-unit                                                                               [#################################################################] 100%
(15/34) removing ruby-rexml                                                                                   [#################################################################] 100%
(16/34) removing ruby-rake                                                                                    [#################################################################] 100%
(17/34) removing ruby-power_assert                                                                            [#################################################################] 100%
(18/34) removing ruby-minitest                                                                                [#################################################################] 100%
(19/34) removing ruby-stdlib                                                                                  [#################################################################] 100%
(20/34) removing ruby-rdoc                                                                                    [#################################################################] 100%
(21/34) removing ruby-psych                                                                                   [#################################################################] 100%
(22/34) removing ruby-stringio                                                                                [#################################################################] 100%
(23/34) removing ruby-json                                                                                    [#################################################################] 100%
(24/34) removing ruby-irb                                                                                     [#################################################################] 100%
(25/34) removing ruby-reline                                                                                  [#################################################################] 100%
(26/34) removing ruby-bundler                                                                                 [#################################################################] 100%
(27/34) removing libyaml                                                                                      [#################################################################] 100%
(28/34) removing gobject-introspection                                                                        [#################################################################] 100%
(29/34) removing python-markdown                                                                              [#################################################################] 100%
(30/34) removing python-importlib-metadata                                                                    [#################################################################] 100%
(31/34) removing python-zipp                                                                                  [#################################################################] 100%
(32/34) removing python-mako                                                                                  [#################################################################] 100%
(33/34) removing python-beaker                                                                                [#################################################################] 100%
(34/34) removing python-markupsafe                                                                            [#################################################################] 100%
ldconfig: File /usr/lib/libxdg-basedir.so.1 is empty, not checked.
ldconfig: File /usr/lib/libxdg-basedir.so.1.2.0 is empty, not checked.
ldconfig: File /usr/lib/libxdg-basedir.so is empty, not checked.
:: Running post-transaction hooks...
(1/4) Arming ConditionNeedsUpdate...
(2/4) Updating the MIME type database...
(3/4) Updating icon theme caches...
(4/4) Updating the desktop file MIME type cache...
 -> error making: luajit-lgi-git

**Comment by Aire-One** [comment]
These logs are produced by the build/test of luajit-lgi (https://aur.archlinux.org/packages/luajit-lgi). LGI is a dependency of awesome, so it seems normal that installing awesome also pulls it.

You should however report this error to the AUR maintainers of the packages since we are not responsible for them.

Btw, I think that awesome git master version needs the LGI git master version. Maybe that's another thing to check with the maintainers on AUR.

(Also it seems you have a bunch of issues with your packages on your system. All these package dependency loops are not related to Awesome and smells like problems you should fix)
