### ISSUE TITLE
Can you reload themes?

### ISSUE THREAD

**Issue by willruggiano** [awesomeWM/awesome#3666]
I ported my neovim theme to awesomewm. In neovim, the theme is dynamic; the color palette changes based on time of day. Is there any way to dynamically reload the theme in awesome? My current solution involves systemd and simply restarting awesome on the hour to apply theme changes, which "works" but of course comes with all of the side effects of restarting awesome, notably: client focus is reset (i.e. I could be working in a terminal on tag 3 and when awesome restarts it resets the active tag to tag 1).

**Comment by paulhersch** [comment]
a) this question would be suited better for a Forum instead of the Github issues
b) you can reload the theme by reinitializing beautiful and then using awesomes "wallpaper_changed" signal to force a theme hot reload

**Comment by willruggiano** [comment]
Thank you!
