### ISSUE TITLE
Question: Callback during awful.mouse.resize. "Move callback"

### ISSUE THREAD

**Issue by leier69** [awesomeWM/awesome#3678]
I'm currently using the following to add my own custom window edge_snapping:
```
awful.mouse.resize.add_leave_callback(function(c, _, args)
    local coords = mouse.coords()
    local sg = c.screen.geometry
    local snap = 25

    if coords.x > sg.x
    and coords.x < sg.x + sg.width
    and coords.y <= snap + sg.y
    and coords.y >= sg.y
    then
        snap(c, "max")
    elseif coords.x <= sg.x + snap
    and coords.x < sg.x + sg.width
    and coords.y >= sg.y
    and coords.y < sg.y + sg.height
    then
        snap(c, "left")
    elseif coords.x >= sg.x + sg.width - snap
    and coords.x < sg.x + sg.width
    and coords.y >= sg.y
    and coords.y < sg.y + sg.height
    then
        snap(c, "right")
    end
end, "mouse.move")
```

This works like a charm, but I just wished I had an easy way of adding my own wiboxes indicating where the window will snap to. Just like awful.mouse.snap.edge_enabled already does. Is this possible? to get a "while moving the window" callback?

Another question I can throw into the mix: Is it possible to modify awful.mouse.snap so you remove bottom snapping and make top snapping maximize? I would also have to edit the big red boxes indicating where the window is gonna snap aswell in that case. I'm guessing its not easily achievable

**Comment by Aire-One** [comment]
Hello @leier69,

> I just wished I had an easy way of adding my own wiboxes indicating where the window will snap to. Just like awful.mouse.snap.edge_enabled already does. Is this possible? to get a "while moving the window" callback?

The `awful.mouse.resize` exposes a `add_move_callback` function, which is what the snap module uses under the hood (https://github.com/awesomeWM/awesome/blob/master/lib/awful/mouse/snap.lua#L258).

See https://awesomewm.org/apidoc/input_handling/mouse.html#awful.mouse.resize.add_move_callback

> Another question I can throw into the mix: Is it possible to modify awful.mouse.snap so you remove bottom snapping and make top snapping maximize? I would also have to edit the big red boxes indicating where the window is gonna snap aswell in that case. I'm guessing its not easily achievable

Hm, I don't remember this is configurable in the snap module. I may be wrong, tho :shrug:

**Comment by leier69** [comment]
@Aire-One Thanks man! I read through /usr/share/awesome/lib/awful/mouse/snap.lua and copied what I needed and basicly created my own version of the module.

It basicly solves my overcomplicated solution, even though it still bugs me that snap.lua is loaded and being disabled by a if statement everytime I try to drag a window. 
```
awful.mouse.snap.edge_enabled = false
awful.mouse.snap.client_enabled = false
awful.mouse.drag_to_tag.enabled = false
```

But there is basicly no simple solution to that, I just have to live with it.

Thanks alot for quick answer man :)
