### ISSUE TITLE
I can't get gaps to work.

### ISSUE THREAD

**Issue by Drogobo** [awesomeWM/awesome#3680]
Output of `awesome --version`:
awesome v4.3 (Too long)
 • Compiled against Lua 5.3.6 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2

**How to reproduce the issue:**
Go to theme.lua
Change the line with the gaps to "theme.useless_gap   = dpi(15)"

**Actual result:**
I get no gaps

**Expected result:**
I get frickin gaps

**Comment by Drogobo** [comment]
Nvm it works now for some reason

**Comment by kevinyyca** [comment]
i have the same problem but it doesn't work
