### ISSUE TITLE
Icons not working

### ISSUE THREAD

**Issue by Drogobo** [awesomeWM/awesome#3681]
Output of `awesome --version`:

awesome v4.3 (Too long)
 • Compiled against Lua 5.3.6 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2

**How to reproduce the issue:**

Go install papirus icons
Go to your theme.lua and change the icon line to
theme.icon_theme = "Papirus-Dark"

**Actual result:**

My icons don't show up anywhere

**Expected result:**

I get the right icons on my systray and all.

**Comment by sclu1034** [comment]
That theme variable is specific to `menubar` (https://awesomewm.org/doc/api/libraries/menubar.html).

Client icons (e.g. in the titlebar or tasklist) are provided by the application itself (check `xprop _NET_WM_ICON` on the client). Some GTK-based applications can handle icon themes, if configured via GTK.
For all the others, you can overwrite the client's icon property in your config, but you'll have to implement the theme handling yourself.

And the systray is quite special. Those icons are actually special X clients (i.e. windows), so they are rendered by the application, not Awesome. Awesome cannot affect their appearance at all.
Tools like https://github.com/bilelmoussaoui/Hardcode-Tray exist to patch applications individually to your preferred icons.

**Comment by Drogobo** [comment]
How do I do this exactly? I want qt5ct to work, but I don't want it to interfere with KDE. Also LXAppearance keeps switching back to breeze.

**Comment by Drogobo** [comment]
Found out I can just use kde as the environment variable for kde apps.

**Comment by Drogobo** [comment]
I still have no idea how to get the icons to show up.

**Comment by actionless** [comment]
depending if your systray app is qt or gtk - change the icon theme of setting of qt/gtk accordingly

**Comment by dm17** [comment]
Many threads state that lxappearance should work with blueman (to change its icon), but it doesn't. Is it true that one must change these icons manually if using awesome too - as stated here: https://www.reddit.com/r/awesomewm/comments/lk04h3/how_to_set_icon_theme_for_client_icons/ ?
