### ISSUE TITLE
Mouse jumps to top-left when resizing windows

### ISSUE THREAD

**Issue by ziimro** [awesomeWM/awesome#3682]
Output of `awesome --version`:
awesome v4.3 (Too long)
 • Compiled against Lua 5.3.6 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2

**How to reproduce the issue:**
just resize windows in tiled or floating mode
[this issue](https://gitlab.freedesktop.org/libinput/libinput/-/issues/594) on gitlab is verry simmilar to mine

**Actual result:**
`libinput debug-events --verbose` output:
```
event3   POINTER_MOTION          +25.648s	  0.00/  1.03 ( +0.00/ +1.00)
 event3   POINTER_MOTION          +25.657s	  0.00/  1.02 ( +0.00/ +1.00)
 event3   POINTER_MOTION          +25.712s	  0.00/ -0.88 ( +0.00/ -1.00)
 event3   POINTER_MOTION          +25.723s	  0.00/ -0.81 ( +0.00/ -1.00)
 event3   POINTER_MOTION          +25.733s	  1.00/  0.00 ( +1.00/ +0.00)
 event3   POINTER_MOTION          +25.738s	  0.00/ -1.00 ( +0.00/ -1.00)
-event5   KEYBOARD_KEY            +26.099s	KEY_LEFTMETA (125) pressed
-event3   POINTER_BUTTON          +27.508s	BTN_RIGHT (273) pressed, seat count: 1
 event3   POINTER_MOTION          +29.966s	 -0.88/  0.00 ( -1.00/ +0.00)
 event3   POINTER_MOTION          +29.988s	 -0.54/  0.00 ( -1.00/ +0.00)
 event3   POINTER_MOTION          +30.048s	 -0.61/  0.00 ( -1.00/ +0.00)
 event3   POINTER_MOTION          +30.082s	 -0.53/  0.00 ( -1.00/ +0.00)
 event3   POINTER_MOTION          +30.104s	 -0.68/  0.00 ( -1.00/ +0.00)
 event3   POINTER_BUTTON          +31.048s	BTN_RIGHT (273) released, seat count: 0
-event5   KEYBOARD_KEY            +31.234s	KEY_LEFTMETA (125) released
-event3   POINTER_MOTION          +33.029s	 -0.53/  0.00 ( -1.00/ +0.00)
 event3   POINTER_MOTION          +33.035s	 -0.88/  0.88 ( -1.00/ +1.00)
 event3   POINTER_MOTION          +33.039s	 -1.00/  0.00 ( -1.00/ +0.00)
 event3   POINTER_MOTION          +33.042s	 -1.00/  0.00 ( -1.00/ +0.00)
 event3   POINTER_MOTION          +33.043s	  0.00/  1.30 ( +0.00/ +1.00)
```

_`420'th issue btw`_

**Comment by ziimro** [comment]
After long research and tinkering i found out the issue. I havent found much documentation about the issue i was facing except [this blender issue on x.org](https://developer.blender.org/T62483) which was simmilar to mine.
I encountered that issue when resizing windows and the game League of Legends interacting with mouse controled menus.
As per issue i linked above, i have disabled the option to use "TransformationMatrix" in xorg, and now it works perfectly fine.

**Comment by actionless** [comment]
could it be related to this one? https://github.com/awesomeWM/awesome/issues/424

**Comment by ziimro** [comment]
> could it be related to this one? https://github.com/awesomeWM/awesome/issues/424

Not really, my issue was since i changed mouse sensitivity with `xinput` the wrong way, the issue was present in other applications, not specific to awesomewm
