### ISSUE TITLE
wibox on multimonitor setup does not work as expected.

### ISSUE THREAD

**Issue by leier69** [awesomeWM/awesome#3683]
```
❯ awesome --version
awesome v4.3-1382-g05a405b38 (Too long)
 • Compiled against Lua 5.4.4 (running with 0.9.2)
 • API level: 4
 • D-Bus support: yes
 • xcb-errors support: no
 • execinfo support: yes
 • xcb-randr version: 1.6
 • LGI version: /usr/share/lua/5.4/lgi/version.lua
 • Transparency enabled: yes
 • Custom search paths: no
 ```

When creating a wibox on secondary display, It seems that it works perfectly fine for primary monitor, but when its created on the third or secondary monitor the constructor does not respect X and Y cordinates.

** For example **

```
for s in screen do
    s.menu = wibox {
        ontop = true,
        screen = s,
        type = 'dock',
        x = 0,
        y = 200,
        height = dpi(600),
        width = dpi(450),
        shape = function(cr, width, height) gears.shape.partially_rounded_rect(cr, width, height, false, true, true, true, 20) end,
        bg = "#0000FF",
        visible = true,
    }
end
```

when running this simple snippet, you would expect it to create two separate wiboxes, both 200px down from the top of the displays as Y works the same in side by side monitor setups. What happens is that the first wibox on primary display acts just like it should, but the second one has default X and Y cords.

I can fix the issue by throwing in the following at the bottom om the loop, but it would be so cool if awesomewm would work amazing with multimonitor setups right out the box.

```
for s in screen do
    s.menu = wibox {
        ontop = true,
        screen = s,
        type = 'dock',
        x = 0,
        y = 200,
        height = dpi(600),
        width = dpi(450),
        shape = function(cr, width, height) gears.shape.partially_rounded_rect(cr, width, height, false, true, true, true, 20) end,
        bg = "#0000FF",
        visible = true,
    }
    s.menu.y = 200 --works
end
```

Plz help @Aire-One  :pray:

**Comment by leier69** [comment]
**Before:**
![image](https://user-images.githubusercontent.com/60528788/187565680-7f01f64e-d0e2-440b-901a-4faa9a481572.png)
**After:**
![image](https://user-images.githubusercontent.com/60528788/187565769-f16a563e-9ad9-412d-bacc-f54bf5e5ccd9.png)

**Comment by Elv13** [comment]
I suggest using *either* `screen` or `x`/`y`, not both. Something like:

```lua
wibox {
    x = s.geometry.x,
    y = s.geometry.y + 200,
}
```

Since `x`/`y` are absolute, not relative to the screen, setting both may create a mutually contradicting position. Also, which of the 2 which "wins" in that situation is officially undefined.

**Comment by leier69** [comment]
Thanks alot. I feel stupid but my issue is solved :laughing:
