### ISSUE TITLE
Multimonitor setups and wibox

### ISSUE THREAD

**Issue by leier69** [awesomeWM/awesome#3684]
awesome version = git.

Is it possible to create two separate instances of the same wibox (one for each screen), and then create two separate instances of a widget (one for each wibox), and having them act separately?

Currently when I create a screen.widget for each screen, the mouseover effect on one happens to the other one aswell. why? and is it possible to have the instances of the wiboxes/widgets be and work completely separate?

@Elv13 @Aire-One

**Comment by Elv13** [comment]
> Currently when I create a screen.widget for each screen, the mouseover effect on one happens to the other one aswell. 

Because you use the same instance of the widget in 2 different places. You need 2 different copy of the widget.

Also, you might want to join the Discord server or the subreddit for this kind of questions, you will get more people answering (and get answers much faster).

**Comment by leier69** [comment]
Figured it out, was just a mistake on my part.
