### ISSUE TITLE
Do we want to participate in Hacktoberfest?

### ISSUE THREAD

**Issue by sclu1034** [awesomeWM/awesome#3697]
[Hacktoberfest 2022](https://hacktoberfest.com/)

Since this project is rather niche, the influx in contributors shouldn't be too high, but probably still more than usual.
So it would depend on whether enough maintainers would be around in October to triage and review PRs (they don't actually have to be merged, approvals or a special label are enough).

The entire thing is opt-in these days, so the `hacktoberfest` topic would need to be added to the repository.

**Comment by Elv13** [comment]
I added the topic, lets see what happen.
