### ISSUE TITLE
Bug: awesome wm does not recognizes the names of the windows to their full names.

### ISSUE THREAD

**Issue by TheSafdarAwan** [awesomeWM/awesome#3698]
Output of `awesome --version`:
  
    awesome v4.3-1382-g05a405b38 (Too long)
     • Compiled against Lua 5.4.4 (running with 0.9.2)
     • API level: 4
     • D-Bus support: yes
     • xcb-errors support: no
     • execinfo support: yes
     • xcb-randr version: 1.6
     • LGI version: /usr/share/lua/5.4/lgi/version.lua
     • Transparency enabled: yes
     • Custom search paths: no

hello awesome community :) 

I have experienced a bug in the awesome wm with regards to the workspace's rules when setting programs to open on a certain window i think awesome wm tries to only read the initials for the program but does not recognizes the whole names EX:

```lua
{
    rule_any = {
        class = { "obsidian" },
    },
        properties = { screen = 1, tag = taglist_names[4] },
},

```
here i try to set the **Obsidain** application to open on the workspace 4 but it picks up the next rule which is
```lua
{
    rule_any = {
        class = { "obs" },
    },
        properties = { screen = 1, tag = taglist_names[8] },
},

```
her i define the **Obs** recorder to open on the 8th workspace but **awesome wm** open both **Obs** and **Obsidian** on workspace 8 it means it picks the last rule and applies to the all names starting with the **bos**.

**Comment by sclu1034** [comment]
That's not a bug. Rules are passed through `string.match`, so those strings are interpreted as Lua patterns (similar to regular expressions).

**Comment by TheSafdarAwan** [comment]
solved  use a different regex like `"^obs*"`
