### ISSUE TITLE
Regression in docs guide pages

### ISSUE THREAD

**Issue by sclu1034** [awesomeWM/awesome#3703]
Not sure when this regressed, but guide pages don't render correctly anymore:

e.g. `documentation/07-my-first-awesome.md.html`:
![image](https://user-images.githubusercontent.com/4508454/191802888-ebabdef6-a45c-4138-9671-7c8eec7ab95c.png)

**Comment by Aire-One** [comment]
Oops... https://github.com/awesomeWM/apidoc/commit/57e996484862b8b5507aa7908dd6c13211d0270c

My bad, I'm on it
