### ISSUE TITLE
timer: is_started attribute / function?

### ISSUE THREAD

**Issue by blueyed** [awesomeWM/awesome#371]
It's often useful to know if a timer was started, if not only for the warning that you get in case you're trying to stop a non-running one.

There is `timer.data.source_id` already, but it does not look like a public API really - at least it's not in the docs.

Or is it meant to be used from outside (to check if it's non-nil / read-only)?

**Comment by psychon** [comment]
Try `t.started`. It's even in the docs. :-P (Or at least supposed to)

**Comment by blueyed** [comment]
Yes, totally missed it!
