### ISSUE TITLE
Burpsuite not getting executed from shell and menubar

### ISSUE THREAD

**Issue by Zukxxxx0** [awesomeWM/awesome#3713]
I am a penetration testing student and using linux more than a year and switched to WM last week. When tries to run burpsuite ("Super + r") there is no terms matching it. I have to go to my gui file manager and open the directory and execute the app. Also, it's not running directly from the shell too. Aliases do not work at all. So that, reporting the issue here

**Comment by Elv13** [comment]
`ln -s` the file somewhere in your `$PATH`. Adding an alias may or may not work depending on how `awesome` is started. Also don't bother trying to add something to `$PATH` in your `~/.bashrc` if you start Awesome using a session manager, it likely wont read `~/.bashrc`, so it wont be there.

**Comment by Zukxxxx0** [comment]
@Elv13  That means start from "startx" command? I start awesome with awesomewm directly from login manager. In case awesome is the only one I have had to my distro

**Comment by Zukxxxx0** [comment]
I found the solution that the ubuntu desktop missed some of the sources and after adding them works fine. Also tested that downloading, installing and running burp in fedora arch and manjaro. Ubuntu is the one misses few dependencies in order to run some applications. Thank you for your time
