### ISSUE TITLE
Compositor glitches

### ISSUE THREAD

**Issue by steelman** [awesomeWM/awesome#3717]
awesome v4.3 (Too long)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2

compton 1
picom 8.2

**How to reproduce the issue:**

Run awesome together with a compositor (tested with: picom and compton on Debian 11)

**Actual result:**

Sometimes after switching between tags, some windows (usually one of them) instead of their own content display content of the previous tag that occupies the same area on the screen. (It's as if the previous tag was below the current and the offending window was a hole one can see through.) Then the window switches between the foreign content and its own every time a other windows on the same tag are updated (e.g. cursor blinks in a terminal window).

Sometimes window frames flicker.

Switching tags back and forth (Mod+Esc) or resizing windows usually fix the problem.

Compositors show no error messages that appear related to this issue.

**Expected result:**

No glitches and flickering.

**Comment by Elv13** [comment]
Try awesome with `--no-argb`. If that fixes anything, then the bug is probably in the driver. If that doesn't fix it, then the bug is probably in the compositor. We chased this kind of issues dozens of time in the past and it never was a code bug. Awesome is more prone to this because we use uncommon bit depth (mainly to allow titlebar transparency)

**Comment by steelman** [comment]
I am afraid it happens with `--no-argb` (`-a` to be dead precise) too.

**Comment by actionless** [comment]
obviously awesome have nothing to do with it

**Comment by steelman** [comment]
Obviously? Indeed, it's quite probable, awesome doesn't cause the glitches, but it definitely has *something* to do with them, because the glitches can be fixed (temporarily, until tags are switched again) by resizing windows. So maybe awesome could do *that* thing when switching tags too.

**Comment by actionless** [comment]
> it definitely has something

you mean it doesn't happen for you with i3 and openbox but only awesomewm?

**Comment by Elv13** [comment]
The way to debug when other WMs do something and AwesomeWM doesn't is using `xtruss`, `xtrace` or `xscope`. It has been a really, _really_ long time since I played with those.
