### ISSUE TITLE
Rewrite "tile" layout

### ISSUE THREAD

**Issue by kosorin** [awesomeWM/awesome#3720]
I'm trying to (completely) rewrite default tile layout. The main reasons for this is poor mouse support and bugs when resizing using a mouse. Often it's not possible to resize and it's easier to just restart Awesome and try to resize again.
- gaps - someone created this issue #3658. There is also video that shows this problem. Basically the error happens when trying to resize last window in any column when `useless_gap` is greater than ~2
- titlebars - there is a lot of warnings when client is too small: `W: awesome: client_geometry_refresh:2144: Resizing a window to size zero!?`. This happens when client has any titlebar and is too small. The layout doesn't calculate client's final size correctly I guess.

To be honest I'm surprised no one's complaining about that yet. No one is using mouse to resize windows? 

Things that are improved/changed/added:
- mouse cursor correctly jump to the client's corner (side). Right now for example when resizing third column the cursor jumps between first and second column and it's inconvenient to resize.
- it's possible to resize all columns, not just master column (`master_width_factor`).
- "center" layout (WIP) - instead of simple columns "1,2,3,4,5,..." (for `suit.tile.right`) and "...,5,4,3,2,1" (for `suit.tile.left`) it's easy to add "center" layout "...,5,3,1,2,4,...". This is useful for ultra wide monitors (21:9 and more).
- resize screen padding - I'm not sure if it's useful feature. Right now it doesn't change `screen.padding` directly, it's just padding for current tag's layout.

I wonder if you would be interested in replacing the default tile layout. What are your thoughts?

The code is here if you want to try it. https://github.com/kosorin/powerful/tree/main/layout/tilted 
Just add the three files to your config (expected path is `your/config/powerful/layout/tilted`) and add `powerful.layout.tilted.right` to `awful.layout.append_default_layouts()`.

**Comment by Aire-One** [comment]
Hello @kosorin,

Yes, PRs are very welcome!

Note, however, that a complete rewrite of a basic layout needs a lot of care. We have a strong backward compatibility rule, any change/bugfix needs to not break the current behavior. 

Maybe it would be easier to submit smaller patches, focused on each improvement individually? (Or maybe not if you have many changes that are interdependent :thinking:)
