### ISSUE TITLE
Mousegrabber without specifying cursor

### ISSUE THREAD

**Issue by Crylia** [awesomeWM/awesome#3721]
Currently you have to use the mousegrabber like following

```lua
mousegrabber.run(
  function() return end,
  "arrow"
)
```

You **have** to specify a cursor which can be highly infurating if you are trying to have a different cursor when entering a widget.

```lua
mousegrabber.run(
  function() return end,
  ""
)
```

Passing just an empty string would then result in no change to the cursor.

**Comment by sclu1034** [comment]
`nil` would make more sense for a "no change" value.
Either way, it just has to be mapped to `XCB_NONE` in C.
