### ISSUE TITLE
Focus windows by key/number

### ISSUE THREAD

**Issue by ivasonn** [awesomeWM/awesome#3726]
hello, does awesomewm have something like easymotiion in vim to change focus between windows?

**Comment by sclu1034** [comment]
Not as a built-in, ready-made solution. The point of AwesomeWM is to be a framework for you to build your own logic/workflows.
So it does offer everything you need to build something like that.

The [keygrabber examples](https://awesomewm.org/apidoc/core_components/awful.keygrabber.html) should get you started.

**Comment by ivasonn** [comment]
Thanks a lot for your answer. I searched for some already written lua plugin for it but didn't find anything. Perhaps someone has already done this.

**Comment by sclu1034** [comment]
You'll want to search/ask for that on the social platforms then. The issue tracker isn't something where people come to share those things.

**Comment by actionless** [comment]
i use this one https://github.com/guotsuan/awesome-revelation
