### ISSUE TITLE
Crashing and exiting X after reloading using Mod-Ctrl-r

### ISSUE THREAD

**Issue by DrWaleedAYousef** [awesomeWM/awesome#3727]
Output of `awesome --version`:

 • Compiled against Lua 5.3.6 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2

I am using archlinux.

**How to reproduce the issue:**

`Mod-Ctrl-r`

**Actual result:**

awesomewm crashes and exits X to the shell. However, this is not consistent. Sometimes it does not happen! **In addition, there is another behaviour that usually happens before crashing: when I try to launch any new application, even shell, it does not display although its process is launched!**

**Expected result:**

just reloading

**Comment by actionless** [comment]
upload the output of `awesome` executable

**Comment by DrWaleedAYousef** [comment]
Sorry, could you explain?

**Comment by sclu1034** [comment]
AwesomeWM prints error information to stderr, especially when it panics. That's what actionless asked for.
If you use a display manager, you might have to check where yours redirects stderr to (usually a log file somewhere).

**Comment by DrWaleedAYousef** [comment]
> AwesomeWM prints error information to stderr, especially when it panics. That's what actionless asked for. If you use a display manager, you might have to check where yours redirects stderr to (usually a log file somewhere).

I only use awesome on archlinux; nothing else. I tried finding the log files of awesome under `~/.config/awesome` but I did not find any!

**Comment by DrWaleedAYousef** [comment]
I updated the issue above to reflect another phenomenon that happens in parallel to this crashing; I added to the issue the following sentence:
**In addition, there is another behaviour that usually happens before crashing: when I try to launch any new application, even shell, it does not display although its process is launched!**

**Comment by xmalbertox** [comment]
> > AwesomeWM prints error information to stderr, especially when it panics. That's what actionless asked for. If you use a display manager, you might have to check where yours redirects stderr to (usually a log file somewhere).
> 
> I only use awesome on archlinux; nothing else. I tried finding the log files of awesome under `~/.config/awesome` but I did not find any!

The location of awesome logs depends on how you start awesome, they are **usually** part of your xorg logs or xsession-error logs.

How do you start awesome? From xinit, for example by running startx, or from some display manager (like lightdm, gdm, etc...)

The *xdg-standard* location of both Xorg and Xsession logs is `$XDG_DATA_HOME/xorg/`, inside there should be a `Xorg.log` file and a `xsessions-erros`.

**Comment by DrWaleedAYousef** [comment]
I use 'startx'. I have just awesome on archlinux. I looked at the log file of xorg; I could not identify any error. Do you mean another log file?

**Comment by sclu1034** [comment]
`startx` does not handle writing to log files. It simply pipes to stdout/stderr, i.e. you'd see the output in the terminal from which you started `startx` if you were to quit AwesomeWM.
If you want output written to a file, you'll have to do that yourself in your `.xinitrc`.

**Comment by DrWaleedAYousef** [comment]
Ok; thanks for clarification. Please, find attached the output right after launching then crashing.

![image](https://user-images.githubusercontent.com/12213197/199101793-c8fe1018-7bec-4c83-b783-365ac9c6262c.jpeg)

**Comment by actionless** [comment]
as far as i see from startx output, the relevant log file is located at:

![2022-11-18--1668736750_394x20_scrot](https://user-images.githubusercontent.com/1655669/202599345-c09f6cb2-a426-42e1-8273-efc80d7ae8e4.png)

**Comment by DrWaleedAYousef** [comment]
> as far as i see from startx output, the relevant log file is located at:
> 
> ![2022-11-18--1668736750_394x20_scrot](https://user-images.githubusercontent.com/1655669/202599345-c09f6cb2-a426-42e1-8273-efc80d7ae8e4.png)

I uploaded it in the [previous post](https://github.com/awesomeWM/awesome/issues/3727#issuecomment-1297630930)

**Comment by actionless** [comment]
looks like some problem with video driver:

```
[ 47103.343] (EE) Screen 1 deleted because of no matching config section.
[ 47103.343] (II) UnloadModule: "nvidia"
[ 47103.343] (II) UnloadSubModule: "wfb"
```

does it works better when using `nouveau` driver instead?

**Comment by DrWaleedAYousef** [comment]
> looks like some problem with video driver:
> 
> 
> 
> ```
> 
> [ 47103.343] (EE) Screen 1 deleted because of no matching config section.
> 
> [ 47103.343] (II) UnloadModule: "nvidia"
> 
> [ 47103.343] (II) UnloadSubModule: "wfb"
> 
> ```
> 
> 
> 
> does it works better when using `nouveau` driver instead?

`nouveau` has some issues and I do not like to use. I just want to clarify two things:
1. This crashing issue exists even when I do not use `nvidia` (that is, when I use only the CPU)
2. This crashing issue is new (months ago). I did not encounter it before that!

**Comment by actionless** [comment]
> This crashing issue exists even when I do not use nvidia (that is, when I use only the CPU)

what's that log in this case?

> This crashing issue is new (months ago). I did not encounter it before that!

awesomewm didn't really changed lately, so i recommend you seeking help on forum of your linux distribution
