### ISSUE TITLE
Why there is no native compositor 

### ISSUE THREAD

**Issue by Dregorio1** [awesomeWM/awesome#3729]
Awesome is old project. I think it should have own compositor. Most of modern WM has one like Hyprland. There is any plan to do that?

**Comment by Elv13** [comment]
>95% of X11 WMs don't have a compositor built-in. If you want a compositor, then install `picom`. There is little value in having it built-in. The patches to add a compositor to awesome actually exist, but we don't intend on merging them beyond the systray ones. Having "a compositor" is pretty different from having a "good compositor" one. That would require contiguous effort to maintain and improve. This effort is better spent elsewhere.
