### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by KirbyHacks** [awesomeWM/awesome#3730]
Hi, i recently download awesomeWM, but, i install a theme, I accidentally unknowingly deleted the contents of /etc/xdg/awesome
so.... I can't recover these files. I reinstall it, unistalling and install it again and i try from the source code. Nothing, I use ParrotSecOS natively, so I can't place a VM. 

Version : awesome v4.3 with D-Bus support and execinfo support

**Comment by Elv13** [comment]
Hi, you can get `rc.lua` [here](https://github.com/awesomeWM/awesome/blob/v4.3/awesomerc.lua) for v4.3. You can get the theme files there too. Place them in `~/.config/awesome`. There is nothing else important in `/etc/xdg/awesome`. Also, from the ParrotSecOS website, it seems to be based on Debian. So you can use `apt purge awesome; apt install awesome` to reset things properly

**Comment by KirbyHacks** [comment]
Thanks dude
