### ISSUE TITLE
Fullscreen cuts off the bottom part of the client content

### ISSUE THREAD

**Issue by Senpai-10** [awesomeWM/awesome#3732]
Output of `awesome --version`:

```
awesome v4.3 (Too long)
 • Compiled against Lua 5.3.6 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
```

**How to reproduce the issue:**

1. Select a client 
2. fullscreen the client (or video in client)

**Actual result:**

The client (or video) is not fully inside my view some of the the client (or video) gets cut off (at the bottom)
also the im having the same issue with discord and my terminal when in fullscreen part of the content is cut off

**Expected result:**

client content is fully in view

My current workaround is maximizing the client before changing to fullscreen the fixes the issue and i can see all the content nothing is cut off

**Images for more clarification:**

* when client is not maximized before changing the video to fullscreen
![the issue](https://i.imgur.com/84TZJe7.png)

* when client is maximized before changing the video to fullscreen
![the workaround](https://i.imgur.com/V6deOkL.png)

**Please tag me if any extra info is needed! :)**

**Comment by actionless** [comment]
please check with latest git version - i think someone already submitted a fix for that, which is not included in 4.3 version

**Comment by Senpai-10** [comment]
> please check with latest git version - i think someone already submitted a fix for that, which is not included in 4.3 version

I think you mean [awesome-git](https://aur.archlinux.org/packages/awesome-git) from the AUR
i installed it and nothing changed :(

awesome --version
after installing awesome-git

```
awesome v4.3-1550-ga43647873 (Too long)
 • Compiled against Lua 5.4.4 (running with 0.9.2)
 • API level: 4
 • D-Bus support: yes
 • xcb-errors support: yes
 • execinfo support: yes
 • xcb-randr version: 1.6
 • LGI version: /usr/share/lua/5.4/lgi/version.lua
 • Transparency enabled: yes
 • Custom search paths: no
```

**Comment by actionless** [comment]
weird, this doesn't happen to me, do you use firefox or other browser? have you tried with default rc.lua config?

**Comment by Senpai-10** [comment]
> do you use firefox or other browser?

    I use firefox, but the same thing happens in brave browser and any other program.

> have you tried with default rc.lua config?

    I tried the default configs and the problem is gone!
    So the problem is from my awesome config,
    do you have any idea what could be causing this?

**Comment by Senpai-10** [comment]
Hello, i have been able to locate where the problem came from! :)

```lua
-- Signal function to execute when a new client appears.
client.connect_signal("manage", function(c)
	-- Set the windows at the slave,
	-- i.e. put it at the end of others instead of setting it master.
	-- if not awesome.startup then awful.client.setslave(c) end

	if awesome.startup and not c.size_hints.user_position and not c.size_hints.program_position then
		-- Prevent clients from being unreachable after screen count changes.
		awful.placement.no_offscreen(c)
	end

        -- THIS IS THE PROBLEM 
        -- vvvvvvvvvvvvvvvvvvv
	if c.floating then                                
		awful.titlebar.show(c)                
	else                                                   
		awful.titlebar.hide(c)                  
	end         
        -- ^^^^^^^^^^^^^^^^^^^
end)
```

This is what's causing the problem.
```lua
if c.floating then
    awful.titlebar.show(c)
else
    awful.titlebar.hide(c)
end
```

# Fix
Changing `if c.floating then` to this fixed the problem :) 

```lua
if c.floating then
    awful.titlebar.toggle(c)
end
```

### note: 

if after applying the fix, all your clients now show titlebar when not in floating 

change this in your client rules!

from

```lua

-- Add titlebars to normal clients and dialogs
	{ rule_any = { type = { "normal", "dialog" } }, properties = { titlebars_enabled = true } },

```
titlebars_enabled is set to `true`

to

```lua

-- Add titlebars to normal clients and dialogs
	{ rule_any = { type = { "normal", "dialog" } }, properties = { titlebars_enabled = false } },
```
titlebars_enabled is set to `false`

@actionless Thanks for helping me :+1:

**Comment by actionless** [comment]
i also was thinking it could be related to this one (https://github.com/awesomeWM/awesome/issues/3156#issuecomment-683533740) in case if it would still happen to you

**Comment by Senpai-10** [comment]
Hi, again 

changing to `awful.titlebar.toggle inside the signal` fix it but it made titlebars show by default 
and if i set `properties = { titlebars_enabled = false }` in `awful.rules.rules`
the same problem come back :(

looks like when disabling titlebars 'or hiding them by a keybinding'
the problem (the bottom of the client gets cut off when in fullscreen) come back

only when when titlebars are visible or the client is maximized full screen behaves normally
