### ISSUE TITLE
application window move from side by side to top and bottom after unlocking

### ISSUE THREAD

**Issue by traplover4200** [awesomeWM/awesome#3736]
Output of `awesome --version`:
awesome v4.3 (Too long)
 • Compiled against Lua 5.4.3 (running with 0.9.2)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: /usr/share/lua/5.4/lgi/version.lua

**How to reproduce the issue:**

lock the screen with betterlockscreen

**Actual result:**
application window move from side by side to top and bottom after unlocking

**Expected result:**
application window to be side by side

**Comment by traplover4200** [comment]
fix
https://www.reddit.com/r/awesomewm/comments/ysvi13/window_move_from_side_by_side_to_top_and_bottom/

**Comment by Aire-One** [comment]
Since it is now resolved and wasn't an issue with Awesome, I'm closing the issue as completed.
