### ISSUE TITLE
[Feature Request] Support .webp files as background

### ISSUE THREAD

**Issue by code-IM-perfect** [awesomeWM/awesome#3738]
Output of `awesome --version`:

awesome v4.3 (Too long)
• Compiled against Lua 5.3.6 (running with Lua 5.3)
• D-Bus support: ✔
• execinfo support: ✔
• xcb-randr version: 1.6
• LGI version: 0.9.2

**How to reproduce the issue:**

Set a webp image as the wallpaper with `gears.wallpaper.fit()`

**Actual result:**

No image and only a black background

**Expected result:**

The webp image should be set as the background

**Comment by Elv13** [comment]
This feature request must be sent to Cairo, which we use to convert files into bitmap surfaces. Whatever AwesomeWM supports is whatever Cairo supports. This is out of scope for us, sorry. Alternatively, you can convert the image to png.

**Comment by sclu1034** [comment]
@Elv13 `upstream` label would make sense, I guess.
