### ISSUE TITLE
[QUESTION + ISSUE] awful.screenshot 

### ISSUE THREAD

**Issue by DarkRyuk12345** [awesomeWM/awesome#3755]
I am using the latest version of awesomewm-git 

I was trying to make a tag preview widget and tried using awful.screenshot, it turns out there is no tag argument for it, but I still tried the screen argument, and use the content_widget argument to get an image box, but it failed. The code I used was: `awful.screenshot({screen = s}).content_widget`, the image was nil. So I tried using `awful.screenshot({interactive = true})`, it didn't even do anything. 

Finally, thinking my implementation was wrong, I tried making a binding with the following code, 

```
   awful.key{
      modifiers = {mod.shift}, 
      key = "t", 
      group = "screenshot", 
      on_press = function()
         awful.screenshot({interactive = true})
         
      end
   }
```
and it again didn't work, at this point, I am confused about whether the library itself is bugged or I am doing it all wrong. So I have the following queries

1. Why is there no tag argument for awful.screenshot? 
2. Is there a way to achieve a tag preview using awesome API? 

That's all, thank you!

**Comment by actionless** [comment]
no, in X server is not possible to take a screenshot of a window which is not currently visible
