### ISSUE TITLE
make problem

### ISSUE THREAD

**Issue by Tahahojjati** [awesomeWM/awesome#3763]
make
sudo make install
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target 'install'.  Stop.

**Comment by Elv13** [comment]
Please provide the complete log. What distribution is this? Did you install the dependencies?

**Comment by Tahahojjati** [comment]
> Please provide the complete log. What distribution is this? Did you install the dependencies?

oh sorry
anyway that error is gone
but when i use make command, terminal shows this:
--   No package 'xcb-cursor' found
--   No package 'xcb-randr' found
--   No package 'xcb-xtest' found
--   No package 'xcb-xinerama' found
--   No package 'xcb-shape' found
--   No package 'xcb-keysyms' found
--   No package 'xcb-keysyms' found
--   No package 'xcb-icccm' found
--   No package 'xcb-icccm' found
--   No package 'xcb-xfixes' found
--   No package 'xcb-xkb' found
--   No package 'xkbcommon' found
--   No package 'xkbcommon-x11' found
--   No package 'libstartup-notification-1.0' found
--   No package 'libstartup-notification-1.0' found
--   No package 'libxdg-basedir' found
--   No package 'libxdg-basedir' found

i don't really know how fix this!

**Comment by Aire-One** [comment]
Hello,

You are missing some dependencies. Depending on your Linux distribution, the packages can differ, so it's not easy for us to provide you a full list of packages to install. 

You can read this https://awesomewm.org/apidoc/documentation/10-building-and-testing.md.html documentation to have the list of dependencies, and see what package provides them for your distribution.

Note that Debian and Arch Linux distro have "easy" way to build and install Awesome from source, as pointed out by this section from the README https://github.com/awesomeWM/awesome#installing-current-git-master-as-a-package-receipts.

Note 2: There is this post on Reddit where they list a bunch of way to install Awesome from source for different distribution https://reddit.com/r/awesomewm/comments/xi6ab5/installing_awesomewm/. I haven't reviewed the post content, but it may help you :shrug:

**Comment by volvo007** [comment]
Try to install all these packages one by one, like `sudo apt install xcb-xinerama`. You may get problem said "unable to find a source package ...", then use google to search the `dev` version of the package. e.g. the `dev` version of `xcb-xinerama` would be `libxcb-xinerama0-dev`.

You may need to update your apt sources and install another installer called `aptitude`. It will remind you the correct name of some packages.
