### ISSUE TITLE
Badly cropped images and icons - new fonts approach 

### ISSUE THREAD

**Issue by raven2cz** [awesomeWM/awesome#3766]
This issue is not new one. I had these problems minimal 3/4 year. But always copy old font which hasn't problem and live with it. But the problem is growing and growing. Actual ALL nerd fonts and separated packages have this problem. It seems that we have to find what is changed in the font and find solution for awesome.

Test case is simple. Just use simple new font, you can take almost anyone from arch, I'm using `Iosevka Nerd Font`.

Layout? Almost anyone is wrong, aligh.horizontal, background...

#### **Examples**

![font problem 1](https://user-images.githubusercontent.com/20504243/213857513-776b4fd3-9f2f-4153-85c1-7274fd66d831.png)

![font problem 2](https://user-images.githubusercontent.com/20504243/213857553-e242e1e2-dc63-4273-a46d-9d3038341842.png)

![font problem 3](https://user-images.githubusercontent.com/20504243/213857854-8b22fa4a-cf81-4ea0-b577-767c9fcc6559.png)

There are attached two fonts examples. One which is old and works, second is new which is placed in nerd fonts and in default TTF fonts folder now.

[fonts.tar.gz](https://github.com/awesomeWM/awesome/files/10472043/fonts.tar.gz)

**Comment by kosorin** [comment]
What is your code? I don't have this problem with JetBrainsMono Nerd Font .

```
{
    widget = wibox.widget.textbox,
    font="JetBrainsMono Nerd Font 80",
    text="󰗼",
},
```

![image](https://user-images.githubusercontent.com/13920314/213864667-bbc30d76-7ea7-4be7-8f26-17019bcec831.png)

**Comment by raven2cz** [comment]
> What is your code? I don't have this problem with JetBrainsMono Nerd Font .
> 
> ```
> {
>     widget = wibox.widget.textbox,
>     font="JetBrainsMono Nerd Font 80",
>     text="󰗼",
> },
> ```
> 
> ![image](https://user-images.githubusercontent.com/13920314/213864667-bbc30d76-7ea7-4be7-8f26-17019bcec831.png)

It is not about the code. I attached fonts to issue. Maybe you have older version of jetbrains. I have here nerd fonts which are older, and it works correctly, it is from some specific version of nerd fonts complete pagkage. BUT from yesterday, it is places in main /TTF fonts too, in arch repos! And it is more dangerous. The problem is 

The problem spreads throughout the system. This will no longer be an awesome problem, but we will have to find a solution and try to fix it if it is possible. Because I doubt that they will somehow solve it globally in fonts. Rather, we will have to find out which part of the font incorrectly returns its width to one character...

Codes are
```lua

    local result = wibox.widget{
        {
            nil,
            button_icon,
            forced_height = dpi(170),
            expand = "none",
            layout = wibox.layout.align.horizontal
        },
        {
            nil,
            button_text,
            expand = "none",
            layout = wibox.layout.align.horizontal
        },
        -- forced_width = 100,
        layout = wibox.layout.fixed.vertical
    }
```
```lua
return {
    {
      {
        wibox.container.margin(wibox.widget { icon, wbox, layout = wibox.layout.align.horizontal }, leftIn, rightIn),
        fg = fgcolor,
        widget = wibox.container.background
      },
      bottom = underLineSize,
      color = colorLine,
      fg = fgcolor,
      layout = wibox.container.margin
    },
    left = wiboxMargin,
    right = wiboxMargin,
    bottom = 2,
    layout = wibox.container.margin
  }
```

```lua
    local text = wibox.widget {
        text = "CONFIG",
        font = beautiful.font_board_bold.."12",
        widget = wibox.widget.textbox
    }
    
    local icon = wibox.widget {
        markup = "<span foreground='"..beautiful.fg_focus.."'>漣</span>",
        font = beautiful.icon_font.."24",
        widget = wibox.widget.textbox
    }
    
    local widget = wibox.widget {
        icon,
        text,
        spacing = dpi(16),
        layout = wibox.layout.fixed.horizontal
    }
```

**Comment by raven2cz** [comment]
Try for example: `Fira Mono Nerd Font` too.

**Comment by kosorin** [comment]
https://github.com/polybar/polybar/issues/991

**Comment by kosorin** [comment]
Btw, I also noticed this issue but never see cut off. Some icons are too wide and I use this workaround: `{icon}<span size='50%'> </span>`.

There is another problem with nerd font. Some icons are in place of characters that are "right-to-left". For example this "mute" icon ("ﱜ", `u+FC5C`) is actually arabic character and  requires special character (`u+200E`) to change to "left-to-right" otherwise pango does crazy stuff.

**Comment by raven2cz** [comment]
I have to find some solution. I hope that solution exists, because it worked, and stop working. The situation was that nerd font had this problem, next some versions "fix" the problem and after next several months the problem returned back. Now it is not just nerd fonts, but fonts in ttf, so, it is not just about nerd fonts now.

**Comment by sclu1034** [comment]
Haven't dug into it, but this looks like pango can't handle two cell wide characters properly, and reports a layout size with them considered as just one cell.
In that case, a workaround could be to add a space character after the symbol.

**Comment by sproott** [comment]
Also maybe related to this: using `Symbols Nerd Font` for icons,  they don't get cropped, but are instead shifted down:

![image](https://user-images.githubusercontent.com/46423131/214258926-c599c73d-f150-4428-895e-5eb99ec0190a.png)

Before, the icons were vertically centered with the rest.

**Comment by sclu1034** [comment]
@sproott Yours looks like the mono-monospace variant somehow disregards the font size (unless you actually did that with a separate textbox and different font size).

**Comment by sproott** [comment]
@sclu1034 It seems that the monospace font has a smaller size by default (probably because the characters need to fit the single-character width). The problem is now that the icons have all the same width and it makes some too big:

![image](https://user-images.githubusercontent.com/46423131/214262416-216a5326-3df6-4335-a19a-9bf72b2158fd.png)

So I could manually go and eyeball the sizes until it looks how it's supposed to. But I see that as a workaround, since everything worked flawlessly before.

I wonder what changed in the `Symbols Nerd Font` that it shifts down like this.

**Comment by sclu1034** [comment]
> I wonder what changed in the `Symbols Nerd Font` that it shifts down like this.

That's something you'll have to ask them.

If it was a change in AwesomeWM, you could `git bisect` it, but if it's triggered by a change in the font, there's not much we can do. Especially because I don't think anyone in the project is much of an expert in font rendering.

Alternatively, if you can create a MCVE with just Pango, you might be able to get some help from the Pango devs at https://discourse.gnome.org/.

**Comment by sproott** [comment]
Looks like there's already [an issue on the NerdFonts repo](https://github.com/ryanoasis/nerd-fonts/issues/1069) about it.

**Comment by Finii** [comment]
@sproott That is in fact a different issue.

But there are other Issues about your problem, and what it turns out is that you use the wrong font.
For GUI usage you probably want a `Nerd Font Propo` or the `Nerd Font Mono`.
Or use the `Symbols Only Nerd Font` (which is secretly of `Nerd Font Propo` flavor).

`Nerd Font` (without suffix) is for terminal emulator use, that can not handle 'wider than monospaced' characters.

I will add the Issue here, which has more information, let me search...

> using Symbols Nerd Font for icons, they don't get cropped, but are instead shifted down

This has been fixed (I believe), that is actually the issue you linked.

**Comment by Finii** [comment]
Maybe helpful

* https://github.com/ryanoasis/nerd-fonts/issues/442#issuecomment-1263358904
* https://github.com/ryanoasis/nerd-fonts/discussions/951
* https://github.com/ryanoasis/nerd-fonts/discussions/969
* https://github.com/ryanoasis/nerd-fonts/discussions/900

**Comment by sclu1034** [comment]
> For GUI usage you probably want a `Nerd Font Propo` or the `Nerd Font Mono`. Or use the `Symbols Only Nerd Font` (which is secretly of `Nerd Font Propo` flavor).
> 
> `Nerd Font` (without suffix) is for terminal emulator use, that can not handle 'wider than monospaced' characters.

@raven2cz This seems to apply to your issue as well. Can you check with the `Propo` or `Mono` variants of the font(s) you tested with?

**Comment by raven2cz** [comment]
@Finii I'm lost now. Where are the `Propo` variants? I don't see it in nerd fonts folders...

**Comment by raven2cz** [comment]
@sclu1034   I'm lost now. Where are the Propo variants? I don't see it in nerd fonts folders...

**Comment by Finii** [comment]
The `Nerd Font Propo` is not in the release yet. You need to self patch, or I can patch a font for you and upload somewhere.

**Comment by Finii** [comment]
I strive to put the `Propo` into `Nerd Fonts v3.0.0` which I hope to get out this month. But who knows.

For that to happen I need to find a solution for 'drop the Windows Compatible fonts'. Well, at least that is my very own condition. That would actually shrink the number of fonts from 4 to 3 for each source font.

**Comment by actionless** [comment]
from the way how font rendering implemented in awesome - it's up to font itself or Pango lib, but doesn't seems like a potential AwesomeWM bug

**Comment by Finii** [comment]
Btw, Nerd Fonts `v3.0.0` is released and has a `Nerd Font Propo` variant for GUI uses like these above.
There each symbol is 'really' as wide as it visually is, no need for padding with blanks, no cutting off.

**Comment by raven2cz** [comment]
I'm VERY happy with your Propo concept. Thank you very much!

**Comment by raven2cz** [comment]
@Finii So, I tested your `Nerd Font Propo`, much better, but only 70%. Several icons are not still correct. I attached screenshots with Propo to see still bugs in icons.

Exit icon is wrong
![nerd-fonts-propo-bug1](https://github.com/awesomeWM/awesome/assets/20504243/fe8cdbff-b45e-479c-b023-afe0cb74d512)

package, cpu, ethernet, calendar icons are wrong, too.
![nerd-fonts-propo-bug2](https://github.com/awesomeWM/awesome/assets/20504243/e2fa3aaf-05b3-43f1-89d9-12b9d474f30a)

Any idea why?

**Comment by raven2cz** [comment]
Solved. It was older icons which looks deprecated now. I copy new icons from 
https://www.nerdfonts.com/cheat-sheet
and it is working correctly now. 
Thx.

**Comment by raven2cz** [comment]
Solved. It was older icons which looks deprecated now. I copy new icons from 
https://www.nerdfonts.com/cheat-sheet
and it is working correctly now. 
Thx.
