### ISSUE TITLE
Option to disable window borders for single client in fair layout

### ISSUE THREAD

**Issue by cnekmp** [awesomeWM/awesome#3770]
Is there an option to disable borders in fair mode if there is single client window on tag?  The idea is to make it the same as max layout does (in second screenshot) if there is only one window in fair layout.

As you can see from screenshot, there is one window, but blue borders are around in `fair` layout.

I've tried several client signal solutions from web, but none of them helped me.

My `rc.lua`:

```
beautiful.init("~/.config/awesome/theme.lua")
beautiful.gap_single_client = false
beautiful.maximized_hide_border = true
beautiful.useless_gap = 1

awful.tag({ "1", "2", "3", "4", "5", "6", "7", "8", "9" }, s, awful.layout.layouts[1])
awful.layout.layouts = {
    awful.layout.suit.fair,
}

local function set_border(c)
    local s = awful.screen.focused()
    if c.maximized
        or (#s.tiled_clients == 1 and not c.floating)
        or (s.selected_tag and s.selected_tag.layout.name == 'max')
    then
        c.border_width = 0
    else
        c.border_width = beautiful.border_width
    end
end

client.connect_signal("request::border", set_border)
client.connect_signal("property::maximized", set_border)
```
![Screenshot](https://user-images.githubusercontent.com/35117097/214670441-5b804158-0c94-483b-bbb3-0a5ad6ac73df.png)
![Screenshot_MAX](https://user-images.githubusercontent.com/35117097/214674125-8ffe4733-fa88-4858-8cb6-57577ed414b9.png)

**Comment by Aire-One** [comment]
Hello, what's your Awesome WM version? The `"request::border"` signal only exists on the git version.

**Comment by cnekmp** [comment]
@Aire-One thanks for the tip. I was using `community/awesome 4.3-3` package on Arch. I've switched to `awesome-git` version and the code I've provided works as it should.

Two questions:
1. Is it possible to achieve same behavior on awesome version 4.3-3?
2. If not, what is the approximate time that community version will be updated with current awesome-git version that supports such option?

```
[farid@unknown ~]$ awesome -v
awesome v4.3-1588-gb54e50ad6 (Too long)
 • Compiled against Lua 5.4.4 (running with 0.9.2)
 • API level: 4
 • D-Bus support: yes
 • xcb-errors support: yes
 • execinfo support: yes
 • xcb-randr version: 1.6
 • LGI version: /usr/share/lua/5.4/lgi/version.lua
 • Transparency enabled: yes
 • Custom search paths: no
```

**Comment by Aire-One** [comment]
> Is it possible to achieve same behavior on awesome version 4.3-3?

Yes. The `"request::border"` is emitted by a number of events listed here https://awesomewm.org/apidoc/core_components/client.html#request::border. You can connect your `set_border` function to all the corresponding signals to achieve the same behavior in awesome version 4.3.

**Comment by cnekmp** [comment]
Thanks for the help. I guess, I'll better wait for the updates in community repo :) Closing issue.

**Comment by sclu1034** [comment]
> 2\. If not, what is the approximate time that community version will be updated with current awesome-git version that supports such option?

There is no ETA for v4.4. You're better off running `awesome-git` for now, especially on a distribution like Arch, where it integrates neatly into the package system.
