### ISSUE TITLE
Can't build awesomewm from source - linuxmint 21.1 (based on ubuntu 22)

### ISSUE THREAD

**Issue by gab-luz** [awesomeWM/awesome#3775]
Output of `awesome --version`:

Not installed yet.

**How to reproduce the issue:**

I'm trying to build awesomewm from source.

git clone https://github.com/awesomeWM/awesome
cd awesome
make

**Actual result:**

Building…
[  0%] Built target lgi-check
[  0%] Checking for LGI...
Building for Lua 5.4.
Error: [string "pcall(require, 'luarocks.loader')..."]:3: module 'lgi.version' not found:
	No LuaRocks module found for lgi.version
	no field package.preload['lgi.version']
	no file '/usr/local/share/lua/5.4/lgi/version.lua'
	no file '/usr/local/share/lua/5.4/lgi/version/init.lua'
	no file '/usr/local/lib/lua/5.4/lgi/version.lua'
	no file '/usr/local/lib/lua/5.4/lgi/version/init.lua'
	no file '/usr/share/lua/5.4/lgi/version.lua'
	no file '/usr/share/lua/5.4/lgi/version/init.lua'
	no file './lgi/version.lua'
	no file './lgi/version/init.lua'
	no file '/home/mestre/.luarocks/share/lua/5.4/lgi/version.lua'
	no file '/home/mestre/.luarocks/share/lua/5.4/lgi/version/init.lua'
	no file '/usr/local/lib/lua/5.4/lgi/version.so'
	no file '/usr/lib/x86_64-linux-gnu/lua/5.4/lgi/version.so'
	no file '/usr/lib/lua/5.4/lgi/version.so'
	no file '/usr/local/lib/lua/5.4/loadall.so'
	no file './lgi/version.so'
	no file '/home/mestre/.luarocks/lib/lua/5.4/lgi/version.so'
	no file '/usr/local/lib/lua/5.4/lgi.so'
	no file '/usr/lib/x86_64-linux-gnu/lua/5.4/lgi.so'
	no file '/usr/lib/lua/5.4/lgi.so'
	no file '/usr/local/lib/lua/5.4/loadall.so'
	no file './lgi.so'
	no file '/home/mestre/.luarocks/lib/lua/5.4/lgi.so'

       WARNING
       =======

 The lgi check failed.
 Awesome needs lgi to run.
 Add AWESOME_IGNORE_LGI=1 to your environment to continue.

make[3]: *** [CMakeFiles/lgi-check-run.dir/build.make:71: CMakeFiles/lgi-check-run] Erro 1
make[2]: *** [CMakeFiles/Makefile2:28921: CMakeFiles/lgi-check-run.dir/all] Erro 2
make[1]: *** [Makefile:156: all] Erro 2
make: *** [Makefile:15: cmake-build] Erro 2

**Expected result:**

A working awesome installation.

**What I've installed so far**
luarocks
luarocks install lgi
gir1.2-gtk-3.0 \
    gir1.2-pango-1.0 \
    git \
    libdbus-1-dev \
    libgirepository1.0-dev \
    libnotify-bin \
    libpango1.0-dev \
    libstartup-notification0-dev \
    libx11-xcb-dev \
    libxcb-cursor-dev \
    libxcb-icccm4-dev \
    libxcb-keysyms1-dev \
    libxcb-randr0-dev \
    libxcb-shape0-dev \
    libxcb-util0-dev \
    libxcb-xfixes0-dev \
    libxcb-xinerama0-dev \
    libxcb-xkb-dev \
    libxcb-xrm-dev \
    libxcb-xtest0-dev \
    libxdg-basedir-dev \
    libxkbcommon-dev \
    libxkbcommon-x11-dev \
    xutils-dev \
    liblua5.3-dev \
    lua5.3

**Comment by Aire-One** [comment]
Hello, 

From the `make` logs, you are building Awesome against Lua 5.4 while your system seems to default to Lua 5.3.

I recommend you to read https://awesomewm.org/apidoc/documentation/10-building-and-testing.md.html to have an overview of the build options. To change the Lua version Awesome is build against, you should run something similar to `CMAKE_ARGS="-DLUA_EXECUTABLE=/usr/bin/lua5.3 -DLUA_LIBRARY=/usr/lib/liblua.so.5.3 -DLUA_INCLUDE_DIR=/usr/include/lua5.3" make`

You'll need to make sure all the dependencies are correctly installed. In particular LGI, it doesn't supports Lua 5.4 from a released package and needs to be build from source (or install from the Luarocks dev rockspec)

**Comment by gab-luz** [comment]
I've managed to install awesome-git through this steps on Ubuntu 22 (Jammy):
```bash
wget -qO - 'https://proget.makedeb.org/debian-feeds/makedeb.pub' | gpg --dearmor | sudo tee /usr/share/keyrings/makedeb-archive-keyring.gpg 1> /dev/null
echo 'deb [signed-by=/usr/share/keyrings/makedeb-archive-keyring.gpg arch=all] https://proget.makedeb.org/ makedeb main' | sudo tee /etc/apt/sources.list.d/makedeb.list
sudo apt update
sudo apt install makedeb
git clone 'https://mpr.makedeb.org/awesome-git'
cd awesome-git/
makedeb -si
```

**Comment by gab-luz** [comment]
I'll close this issue since I've managed to install it the other way. If you want it, do include those steps I took.
