### ISSUE TITLE
awful.keygrabber not working

### ISSUE THREAD

**Issue by crzjp** [awesomeWM/awesome#3779]
Output of `awesome --version`:

```
awesome v4.3 (Too long)
 • Compiled against Lua 5.3.6 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
```

I'm trying to setup a chained keybind for taking screenshots. This is my `~/.config/awesome/bindings/screenshot.lua`

``` lua
local awful = require 'awful'
local gears = require 'gears'

awful.keygrabber {
    root_keybindings = {{ }, 'Print' },
    keybindings = {
        {{ }, 's', function() awful.spawn('shot s') end },
        {{ }, 'a', function() awful.spawn('shot a') end },
    },
    stop_key = { 'Return', 'Escape' },
    export_keybindings = true,
    start_callback = function() naughty.notification { message = 'start' } end,
    stop_callback = function() naughty.notification { message = 'stop' } end
}
```

And this is my `~/.config/awesome/bindings/init.lua`, required by `~/.config/awesome/rc.lua`

``` lua
require 'bindings.screenshot'
```

**Actual result:**

I press the `Print` key and nothing happens

**Expected result:**

I press the `Print` key, receive the "start" notification and wait for one of the following keys:
- `s`, for taking screenshot of entire screen and ends the chain
- `a`, for selecting an area and ends the chain

**Comment by kosorin** [comment]
`root_keybindings = {{ }, 'Print' },` this looks suspicious. `root_keybindings` expects a list of keys, not a single key.

**Comment by kosorin** [comment]
Just add another `{` and `}`:

    root_keybindings = {{{ }, 'Print' }},

**Comment by crzjp** [comment]
> Just add another `{` and `}` with empty function:
> 
> ```
> root_keybindings = {{{ }, 'Print', function()end }},
> ```

Now, the table is:
``` lua
awful.keygrabber {
    root_keybindings = {{{ }, 'Print', function() end }},
    keybindings = {
        {{ }, 's', function() awful.spawn('shot s') end },
        {{ }, 'a', function() awful.spawn('shot a') end },
    },
    stop_key = { 'Return', 'Escape' },
    export_keybindings = true,
    start_callback = function() naughty.notification { message = 'start' } end,
    stop_callback = function() naughty.notification { message = 'stop' } end
}
```

But gives same result, nothing happens. Without success.......

**Comment by RomanoZumbe** [comment]
I have the same problem. To be sure I I compiled the current git version and the problem is still there

**Comment by RomanoZumbe** [comment]
I found the cause of the problem. It was because I used `root.keys` to set the global keys, which overrides the keygrabber. If I reverse the order the keygrabber overrides the global keys. After switching to `awful.keyboard.append_global_keybindings` to set the global keys everything works as intended

**Comment by raven2cz** [comment]
> I found the cause of the problem. It was because I used `root.keys` to set the global keys, which overrides the keygrabber. If I reverse the order the keygrabber overrides the global keys. After switching to `awful.keyboard.append_global_keybindings` to set the global keys everything works as intended

So, is it possible to close issue now?

**Comment by RomanoZumbe** [comment]
> > I found the cause of the problem. It was because I used `root.keys` to set the global keys, which overrides the keygrabber. If I reverse the order the keygrabber overrides the global keys. After switching to `awful.keyboard.append_global_keybindings` to set the global keys everything works as intended
> 
> So, is it possible to close issue now?

I didn't open this issue

**Comment by raven2cz** [comment]
@crzjp Is it OK now? Can you close issue?

**Comment by crzjp** [comment]
Yes I can close, since I lost my awesome wm config (kids, always remember to commit your changes) but its working for the others. Thank you for everyone involved.
