### ISSUE TITLE
Sometimes my second monitor won't work after boot

### ISSUE THREAD

**Issue by oscariquelme01** [awesomeWM/awesome#3780]
Output of `awesome --version`:
```
awesome v4.3 (Too long)
 • Compiled against Lua 5.3.6 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
```

**How to reproduce the issue:**

Boot into awesomeWM

**Actual result:**

One of the monitors is not working

**Expected result:**

Both monitors should have signal

 **Detailed explanation**

Basically, as the title suggest, I boot into my awesomeWM setup running over ubuntu 22.04. The output of xrandr -q is the following
```
Screen 0: minimum 8 x 8, current 1920 x 1080, maximum 32767 x 32767
HDMI-0 disconnected primary (normal left inverted right x axis y axis)
DP-0 connected (normal left inverted right x axis y axis)
   1920x1080     60.00 + 165.00   143.99   119.98   119.93    99.93
   1680x1050    119.99    59.95
   1440x900     119.85    59.89
   1280x1024    119.96    75.02    60.02
   1024x768     119.99    75.03    60.00
   800x600       75.00    60.32
   640x480       75.00    72.81    59.94
DP-1 disconnected (normal left inverted right x axis y axis)
DP-2 disconnected (normal left inverted right x axis y axis)
DP-3 disconnected (normal left inverted right x axis y axis)
DP-4 connected 1920x1080+0+0 (normal left inverted right x axis y axis) 0mm x 0mm
   1920x1080     60.00*+ 165.00   143.99   119.98   119.93    99.93
   1680x1050    119.99    59.95
   1440x900     119.85    59.89
   1280x1024    119.96    75.02    60.02
   1024x768     119.99    75.03    60.00
   800x600       75.00    60.32
   640x480       75.00    72.81    59.94
DP-5 disconnected (normal left inverted right x axis y axis)
```

As you can see, the DP-4 device is connected and being used at 60.00 HZs (you can tell because of the * sign). On the other hand, the DP-0 is being detected, yet is not outputting any signal. You can tell because there is no * sign anywhere. I believe the * sign signals the refresh rate being used. 

Anyway, to solve my issue, I have to press `crtl shift e`, logout of awesome, then both screens are suddenly detected again, log back, and then it works. 
For the sake of completeness, here is some code I exectute at start up:

```lua
  awful.spawn.with_shell("xrandr --output DP-0 --left-of DP-4")
  awful.spawn.with_shell("xrandr --output DP-0 --rotate left")
  awful.spawn.with_shell("feh --no-xinerama --bg-scale ~/.config/bg/gruvBox.png ")
```
I believe it is a race condition between awesome and some other thing. Any help is appreciated!

**Comment by Crylia** [comment]
Maybe its because you have two separate `xrandr` commands? Try doing it as a one liner.

**Comment by unai-ndz** [comment]
What happens if you just reload awesome instead of logging out?

**Comment by oscariquelme01** [comment]
> What happens if you just reload awesome instead of logging out?

Thats usually what I do, it  usually takes an additional reload for awesome to get it right tho if i do it too fast it might take about 3 times before it gets it right. Its not like deal breaking but it is kind of annoying. I think i ll look into @Crylia solution and see if that works, if not I ll look into some async lua module or some other way to set defaults for xrandr and wallpapers

**Comment by unai-ndz** [comment]
It's better to run the xrandr command before awesome starts, this way you avoid the race condition and if you use a display manager it will also display correctly in all monitors.
If you use lightdm as I do [here](https://gist.github.com/ciarand/8592193) is what you should do.

**Comment by oscariquelme01** [comment]
That makes a lot of sense, but when I tried to run a tested script in a folder called /etc/gdm3/afterLogin or something like that (i am in ubuntu 22.04 so I figured i am using gnome display manager), it crashed my computer and I had to boot into a tty as root to remove it. I ll take a look into it tho, i am currently really busy and the solution of refreshing awesome 5 times is good enough.
