### ISSUE TITLE
XFCE4 notifications show in "regular" clients instead of toasts since recent Linux/kernel update

### ISSUE THREAD

**Issue by GameLostException** [awesomeWM/awesome#3781]
Output of `awesome --version`:

awesome v4.3 (Too long)
 • Compiled against Lua 5.3.6 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2

**How to reproduce the issue:**

Pop an XFCE4 notification, e.g. via:
`notify-send "foo" "bar"`

**Actual result:**

Notifications show as a new client with a top titlebar poping in a corner of the screen with "Floating" and "Sticky" attributes enabled/highlighted in its top titlebar. It also takes the focus which is the vey annoying part (kinda becoming a blocker here).
Apart from that, the notification client behaves like a proper notification as per the XFCE4 settings, i.e. it shows on top of all other clients, next to other notification clients, fades and slides out after a few seconds, and disapears when right-clicked.

**Expected result:**

Like until very recently, the notifications would appear as toasts, i.e. a new pop-up client without any (title)bar, showing on top of all clients, and **without effect on the focus of other clients**.

I am conscious that it is not an AwesomeWM nor XFCE4 update/change which has caused the issue (XFCE4 has updated on my machine last december without showing this issue initially, and Awesome has not updated in years), but most probably the Linux environment/kernel. My goal here is to identify and understand what could have changed so AwesomeWM does not handle notifications as it used to. That way I may hack my way back to my expectations, either by tweaking Awesome or having its surroundings behaving like before. 

Additional info about my system:
OS: Arch Linux x86_64 
Kernel: 6.1.12-arch1-1 
DE: Xfce 4.18 
WM: awesome 
I also use picom `vgit-b700a` as compositor for Xorg.

Anything else you'd need to help me troubleshoot it, please ask.

Cheers

**Comment by Aire-One** [comment]
Hello @GameLostException, sorry for the late reply.

I don't think this issue is caused by a kernel update, but maybe some other packages from the XFCE stack.

It could be useful to observe the actual changes these notifications had. You can run `xprops` against the notification window before and after the update to see whether some upstream regressions have changed the window properties (I don't realistically expect you to actually do it) :thinking: 

Your solution is a good workaround. Maybe instead of the client `"manage"` signal, you can use the `rule` library, which is designed to handle such configuration.

(Also, note that Awesome ships its own notification system with the `naughtly` library. I encourage you to look at it.)

**Comment by Aire-One** [comment]
Yeap, going through recent XFCE release/announcement, I ended up on the xfce4-notifyd changelog at https://gitlab.xfce.org/apps/xfce4-notifyd/-/blob/master/NEWS

```
0.8.2 (2023-02-27)
=====
- Remove WM_TAKE_FOCUS from WM_PROTOCOLS for notification windows
```

IMO, this change plays a big role on the issue you are facing here. (Except that your bug report is 3 days older than the release... Oops!)

**Comment by Aire-One** [comment]
https://gitlab.xfce.org/apps/xfce4-notifyd/-/issues/91 have to be the associated bug report from other WMs users.

Looks like it is now fixed. So I guess the next steps would be: wait for your distro to include the patch in the package, do the update, revert your changes in your `rc.lua` and profit. :D

**Comment by GameLostException** [comment]
Hi @Aire-One, thanks for the very detailed replies! 
And don't be sorry, you owe me nothing. I must admit I realise now I should have had a look in that direction (XFCE) before posting.

I also confirm that the latest fix on XFCE makes the situation better (no more focus stealing) but the notifications are still messed up. My next step is to do the same investigation as others have done for i3 WM and see if XFCE could push the right/expected hints to Awesome or if Awesome needs to interpret things differently.

Had a look around in the meantime and indeed the `rule` solution looks perfect for my workaround intent, thanks for pointing it out!

Closing this for now, I may update back if I end up creating a `rule` to "handle" the new XFCE behaviour.
