### ISSUE TITLE
error triying to compile awesome wm 

### ISSUE THREAD

**Issue by alavaelian** [awesomeWM/awesome#3787]
Output of `awesome --version`:

i cannot compile 

**How to reproduce the issue:**

i tried to do make but i got this error 
![Captura de pantalla de 2023-03-14 13-49-18](https://user-images.githubusercontent.com/20959812/225107459-34550783-1504-4c02-b861-a4c6f6bffc92.png)

![Captura de pantalla de 2023-03-14 13-41-52](https://user-images.githubusercontent.com/20959812/225106519-72f98eb3-03ef-4145-b75a-b736160b3194.png)
also i got other error earlier in the make process but it still keep going until the final error above 

![Captura de pantalla de 2023-03-14 13-42-22](https://user-images.githubusercontent.com/20959812/225106706-9b8a911e-9173-40fa-a5b3-a4a516e306c6.png)
and i installad luadocs by downloading and making an alias on bash
![Captura de pantalla de 2023-03-14 13-47-01](https://user-images.githubusercontent.com/20959812/225106952-c021c4b0-8557-4d1f-9d4b-cdd4b4ade355.png)
maybe that have something to do with the error i needed to do this way becose ldoc is not in the path by default when i instaled it with apt

**Comment by raven2cz** [comment]
In your error log there is:  bad argument #1. It seems that you are using wrong version (old) of ldoc with older api. You have to use newer version.

Another technique how to use correct build environment is using of docker. For example this by Elv13.

``` bash
# Install docker.io or podman, somehow
# apt/dnf/zipper/pacman/emerge/something

# Create a build dir
mkdir ~/awesome_builder; cd ~/awesome_builder`

# Get the source
git clone https://github.com/awesomewm/awesome

# Same as the CI, so hopefully same outcome
cat > Dockerfile << EOF
FROM ubuntu:20.04

RUN sed -i '/^#\sdeb-src /s/^#//' "/etc/apt/sources.list"
RUN apt update -y
RUN DEBIAN_FRONTEND=noninteractive apt build-dep awesome -y --no-install-recommends
RUN DEBIAN_FRONTEND=noninteractive apt install libxcb-xfixes0-dev \
    librsvg2-common -y --no-install-recommends

CMD mkdir /awesome/build -p && \
    cd /awesome/build && \
    cmake .. && \
    make -j2
EOF

# Build the container
docker build . -t awesome_builder

# Build awesome
docker run -ti --rm -v $PWD/awesome:/awesome awesome_builder

# Open in Firefox (or Chrome, whatever you use)
firefox awesome/build/doc/index.html
```

You can edit the `~/awesome_builder/awesome` code, this is what the container will use. The everytime you want to refresh the doc, run `docker run -ti --rm -v $HOME/awesome_builder/awesome:/awesome awesome_builder` again.

**Comment by alavaelian** [comment]
wich one is the correct versions

**Comment by Aire-One** [comment]
Hello @alavaelian, sorry for the late reply.

What is your Linux distribution?
What version of Lua are you trying to build Awesome against?
Can you invoke ldoc from the command line with e.g. `ldoc --version`?

Reading the ldoc README (https://github.com/lunarmodules/LDoc), I have trouble understanding weather your alias is correct or if the alias has to point to a script `ldoc.lua`, and the script file content should be the given line.

In any case, note that if you have trouble with ldoc, you can skip the doc generation while building Awesome with the `-DGENERATE_DOC=OFF` cmake argument. See https://awesomewm.org/apidoc/documentation/10-building-and-testing.md.html
