### ISSUE TITLE
awesome freezes after opening a youtube video in full screen

### ISSUE THREAD

**Issue by mmrzk** [awesomeWM/awesome#3788]
Output of `awesome --version`:

awesome v4.3 (Too long)
 • Compiled against Lua 5.3.6 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2

Distro: Arch Linux x86_64
Kernel: 6.2.6-arch1-1 
(it's happening since the first day of usage (e.g. more than a year)

Hardware: 
ZenBook UX425UA_UM425UA 1.0 
CPU: AMD Ryzen 7 5700U with Radeon Graphics (16) @ 1.800GHz 
GPU: AMD ATI 04:00.0 Lucienne 

Previously I was using Debian for years, and I never had such an error, but I also had a different laptop.

**How to reproduce the issue:**

Click twice on a Youtube video in Chrome to make it full screen

**Actual result:**

Note: it happens roughly 10 times out of 100.

1. The video isn't show in full screen mode, meaning, that I still can see awesome bar.
2. I still can pause/resume the video with Spacebar, or exit full screen with Esc button.
3. Mouse doesn't work, and awesome doesn't respond to anything.
4. If I open another tty and check awesome process - it shows CPU usage close to 100%.

**Expected result:**

Everything works as usual, without the freeze

**Comment by mmrzk** [comment]
I checked similar issues and found the `--no-argb` option. I'll run awesome with this option for a while and if the issue reappear I'll create another issue, as for now I'm closing it.

**Comment by actionless** [comment]
sometimes running compositor like `picom` helps in argb mode
