### ISSUE TITLE
How to display icons on the desktop

### ISSUE THREAD

**Issue by elias-Mimetrik** [awesomeWM/awesome#3797]
The only way of displaying icons on the desktop on awesomeWM that I know of is by installing pcmanfm. But it isn't very stable especially that I don't use that file manager.

Recently I ran into an old script:
https://github.com/travisjeffery/awesome-wm/blob/master/freedesktop/desktop.lua

It is for creating desktop icons, but it is too old to work.

Is there a way to do this please?

**Comment by actionless** [comment]
use `nemo-desktop` or other similar app
