### ISSUE TITLE
Bad animation when switching from a bright window to dark window 

### ISSUE THREAD

**Issue by rew1nter** [awesomeWM/awesome#3820]
Output of `awesome --version`:

```
awesome v4.3 (Too long)
 • Compiled against Lua 5.3.6 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2

```

**How to reproduce the issue:**

1. Install endeavour os
2. Install `awesome` from pacman
3. Open a light themed window (chrome?) and some black themed window (maybe a terminal)
4. Switch from the terminal to chrome and you can see a pretty bad animation shown during the transition for a split second

**Actual result:**

Bad animation

**Expected result:**

A smooth transition, with or without any effect

**PS:**

I'm new to tiling. Can this be fixed by tweaking the confs?

**Comment by sclu1034** [comment]
Awesome does not provide animations or transitions. Those are done by compositors.

**Comment by rew1nter** [comment]
I heard about picom and stuff. Could you link me to some good resource to get started with compositor?

**Comment by gabrieldlima** [comment]
> I heard about picom and stuff. Could you link me to some good resource to get started with compositor?

This is a great resource: 

https://dev.to/l04db4l4nc3r/compositors-in-linux-1hhb

After that, i recommend read the man pages of Picom compositor
