### ISSUE TITLE
Graphical artifacts when opening alacritty and switching to tag with alacritty (some other apps affected as well)

### ISSUE THREAD

**Issue by piatrashkakanstantinass** [awesomeWM/awesome#3824]
Output of `awesome --version`:
```
awesome v4.3 (Too long)
 • Compiled against Lua 5.4.4 (running with 0.9.2)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: /usr/share/lua/5.4/lgi/version.lua
```

**How to reproduce the issue:**
Used picom with vsync option. (Same result, with compositor on and off)
Spawn alacritty.

https://github.com/awesomeWM/awesome/assets/115642938/7bf550f8-277c-4be5-a646-9792537b2bdc

The issue does not appear in floating and max layouts, but is present in any tiling layout. Same issue also happens with i3wm, other wms (including dwm) do not have this problem

**Actual result:**

Video included.

**Expected result:**

The window should open without startup artifacts (such as kitty example from the video)

**Comment by actionless** [comment]
does it work when starting awesomewm with `--no-argb` flag?

**Comment by piatrashkakanstantinass** [comment]
> does it work when starting awesomewm with `--no-argb` flag?

no artifacts with `--no-argb`

**Comment by actionless** [comment]
then you need to use external compositor (like picom) together with argb mode

transparency without compositor often glitchy (not wm-specific)

**Comment by piatrashkakanstantinass** [comment]
What I mean is that transparency doesn't work in no-argb mode and I have artifacts (with and without transparency) in argb mode.
