### ISSUE TITLE
error run awesome wm with Termux

### ISSUE THREAD

**Issue by Dendi777** [awesomeWM/awesome#3830]
I can't run awesome constant errors with dbus, then he can't find system_bus_socket like he decided and he found it, then on says he can't connect like he decided too, but now he just throws exception [2023-07-20 07:48:03 W: awesome: a_dbus_connect:618: Could not connect to D-Bus system bus: Failed to connect to socket /data/data/com.termux/files/usr/var/run/dbus/system_bus_socket: Connection refused
2023-07-20 07:48:03 E: awesome: signal_fatal:497: signal 11, dumping backtrace
Cannot get backtrace symbols.] how to solve it?

**Comment by Aire-One** [comment]
Hello @Dendi777 

> /data/data/com.termux

Seems like you use the Android Termux application. I think that's a first for me. You'll mostly be on your own to fix this issue.

Anyway, the error message sounds clear enough to me

> [2023-07-20 07:48:03 W: awesome: a_dbus_connect:618: Could not connect to D-Bus system bus: Failed to connect to socket

You are missing a D-Bus session.

**Comment by Dendi777** [comment]
dbus session is running and works fine, but awesome himself does not want to connect to it, other window managers i3, dwm, bspwm, 2dwm, etc., run perfectly and interact with dbus, if you lack information about my environment folders and dbus versions, I will gladly provide it!
INFO:
Termux Variables:
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP__AM_SOCKET_SERVER_ENABLED=true
TERMUX_APP__APK_PATH=/data/app/com.termux-zCzxqqqjfbw19RQ4p5LE0w==/base.apk
TERMUX_APP__APK_RELEASE=GITHUB
TERMUX_APP__FILES_DIR=/data/user/0/com.termux/files
TERMUX_APP__IS_DEBUGGABLE_BUILD=true
TERMUX_APP__IS_INSTALLED_ON_EXTERNAL_STORAGE=false
TERMUX_APP__PACKAGE_MANAGER=apt
TERMUX_APP__PACKAGE_NAME=com.termux
TERMUX_APP__PACKAGE_VARIANT=apt-android-7
TERMUX_APP__PID=25116
TERMUX_APP__SE_FILE_CONTEXT=u:object_r:app_data_file:s0:c101,c257,c512,c768
TERMUX_APP__SE_INFO=default:targetSdkVersion=28:complete
TERMUX_APP__SE_PROCESS_CONTEXT=u:r:untrusted_app_27:s0:c101,c257,c512,c768
TERMUX_APP__TARGET_SDK=28
TERMUX_APP__UID=10357
TERMUX_APP__USER_ID=0
TERMUX_APP__VERSION_CODE=118
TERMUX_APP__VERSION_NAME=0.118.0+d7bab73
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0+d7bab73
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb http://mirror.mephi.ru/termux/termux-main stable main
# root-repo (sources.list.d/root.list)
deb http://mirror.mephi.ru/termux/termux-root root stable
# x11-repo (sources.list.d/x11.list)
deb http://mirror.mephi.ru/termux/termux-x11 x11 main
# tur-repo (sources.list.d/tur.list)
deb https://tur.kcubeterm.com tur-packages tur tur-on-device tur-continuous
Updatable packages:
All packages up to date
termux-tools version:
1.38.3
Android version:
10
Kernel build information:
Linux localhost 4.9.193-perf-g743cb02 #1 SMP PREEMPT Mon Oct 25 17:15:39 CST 2021 armv7l Android
Device manufacturer:
Xiaomi
Device model:
Redmi 8A
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.x11 versionCode:12

DBUS:
dbus:
  Installed: 1.15.6-1
  Candidate: 1.15.6-1
  Version table:
 *** 1.15.6-1 500
        500 http://mirror.mephi.ru/termux/termux-main stable/main arm Packages
        100 /data/data/com.termux/files/usr/var/lib/dpkg/status

**Comment by Dendi777** [comment]
awesome --version:
awesome v4.3-1588-gb54e50ad-dirty (Too long)
 • Compiled against Lua 5.4.4 (running with 0.9.2)
 • API level: 4
 • D-Bus support: yes
 • xcb-errors support: no
 • execinfo support: no
 • xcb-randr version: 1.6
 • LGI version: /data/data/com.termux/files/usr/share/lua/5.4/lgi/version.lua
 • Transparency enabled: yes
 • Custom search paths: no

error run awesome:
 E: awesome: signal_fatal:497: signal 11, dumping backtrace
Cannot get backtrace symbols.

**Comment by Aire-One** [comment]
for reference https://github.com/termux/termux-packages/issues/17461

**Comment by Aire-One** [comment]
@Dendi777, can you provide the full error logs (See https://awesomewm.org/apidoc/documentation/90-FAQ.md.html section `Where are logs, error messages or something?`)

**Comment by Dendi777** [comment]
2023-07-24 13:48:22 W: awesome: a_dbus_connect:618: Could not connect to D-Bus system bus: Failed to connect to socket /data/data/com.termux/files/usr/var/run/dbus/system_bus_socket: No such file or directory
2023-07-24 13:48:22 E: awesome: signal_fatal:497: signal 11, dumping backtrace
Cannot get backtrace symbols.

here is the result

**Comment by Dendi777** [comment]
I noticed a strange thing that the xrandr output does not give any result, but the xrandr —listmonitors output shows an available display, it's worth considering that it is called differently its name is screen instead of HDMI-0 or VG-1 it's worth considering maybe awesome just can't find it among the given names?

**Comment by Aire-One** [comment]
```
2023-07-24 13:48:22 W: awesome: a_dbus_connect:618: Could not connect to D-Bus system bus: Failed to connect to socket /data/data/com.termux/files/usr/var/run/dbus/system_bus_socket: No such file or directory
```

This message comes from https://github.com/awesomeWM/awesome/blob/master/dbus.c#L618 and basically means Awesome fails to connect to the dbus.

It shouldn't be a panic tho, so Awesome should still be usable afterward.

Note that the dbus error differs from the one on the first message `Failed to connect to socket /data/data/com.termux/files/usr/var/run/dbus/system_bus_socket: Connection refused`. I guess you are trying some stuff to debug this problem. Let's hope you have more luck as you tries. :)

https://github.com/awesomeWM/awesome/blob/0e5fc4575ab0adbae75908cb49937d9cf63437ec/dbus.c#L645-L654

Another note: Awesome connects to 2 dbus, one session and one system. Error messages both comes from the second connection, AKA the system bus. 

```
2023-07-24 13:48:22 E: awesome: signal_fatal:497: signal 11, dumping backtrace
Cannot get backtrace symbols.
```

I'm not sure about this one...

> other window managers i3, dwm, bspwm, 2dwm, etc., run perfectly and interact with dbus,

AFAIK, none of them depends on dbus nor interact with it.

> awesome --version:
> awesome v4.3-1588-gb54e50ad-dirty (Too long)

It seems you are building Awesome from sources. Dbus is an optional dependency and can be disabled at build time by turning off the `WITH_DBUS` cmake option.

```
make distclean
CMAKE_ARGS="-DWITH_DBUS=OFF" make
```

It can be a first solution for you.

**Comment by Dendi777** [comment]
unfortunately, I can't build it manually due to the fact that I don't have 2 packages in the repository:
Creating build directory and running cmake in it. You can also run CMake directly, if you want.

Running cmake…
CMake Deprecation Warning at CMakeLists.txt:21 (cmake_policy):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- lua -> /data/data/com.termux/files/usr/bin/lua
-- git -> /data/data/com.termux/files/usr/bin/git
-- asciidoctor -> /data/data/com.termux/files/usr/bin/asciidoctor
-- gzip -> /data/data/com.termux/files/usr/bin/gzip
-- ldoc not found.
-- ldoc.lua not found.
-- Not generating API documentation. Missing: ldoc.
-- convert not found.
CMake Error at awesomeConfig.cmake:29 (message):
  convert is required to build awesome
Call Stack (most recent call first):
  awesomeConfig.cmake:63 (a_find_program)
  CMakeLists.txt:33 (include)


-- Configuring incomplete, errors occurred!
make: *** [Makefile:27: build/Makefile] Error 1

**Comment by Dendi777** [comment]
after digging around and changing a few files for the build, I went up to this point, but now I'm back in place again because of an incomprehensible error here is the build log:
Creating build directory and running cmake in it. You can also run CMake directly, if you want.

Running cmake…
-- The C compiler identification is Clang 16.0.6
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /data/data/com.termux/files/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
CMake Deprecation Warning at CMakeLists.txt:21 (cmake_policy):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- lua -> /data/data/com.termux/files/usr/bin/lua
-- git -> /data/data/com.termux/files/usr/bin/git
-- asciidoctor -> /data/data/com.termux/files/usr/bin/asciidoctor
-- gzip -> /data/data/com.termux/files/usr/bin/gzip
-- convert not found.
-- Found PkgConfig: /data/data/com.termux/files/usr/bin/pkg-config (found version "0.29.2")
-- Could NOT find Lua (missing: LUA_LIBRARIES) (found version "5.4.6")
-- Using version from git: v4.3-1606-g0e5fc457-dirty
-- Checking for modules 'glib-2.0;glib-2.0>=2.40;gdk-pixbuf-2.0;cairo;x11;xcb-cursor;xcb-randr;xcb-xtest;xcb-xinerama;xcb-shape;xcb-util;xcb-util>=0.3.8;xcb-keysyms;xcb-keysyms>=0.3.4;xcb-icccm;xcb-icccm>=0.3.8;xcb-xfixes;xcb-xkb;xkbcommon;xkbcommon-x11;cairo-xcb;libstartup-notification-1.0;libstartup-notification-1.0>=0.10;libxdg-basedir;libxdg-basedir>=1.0.0;xcb-xrm'
--   Found glib-2.0, version 2.76.3
--   Found glib-2.0, version 2.76.3
--   Found gdk-pixbuf-2.0, version 2.42.10
--   Found cairo, version 1.17.8
--   Found x11, version 1.8.6
--   Found xcb-cursor, version 0.1.4
--   Found xcb-randr, version 1.15
--   Found xcb-xtest, version 1.15
--   Found xcb-xinerama, version 1.15
--   Found xcb-shape, version 1.15
--   Found xcb-util, version 0.4.1
--   Found xcb-util, version 0.4.1
--   Found xcb-keysyms, version 0.4.1
--   Found xcb-keysyms, version 0.4.1
--   Found xcb-icccm, version 0.4.2
--   Found xcb-icccm, version 0.4.2
--   Found xcb-xfixes, version 1.15
--   Found xcb-xkb, version 1.15
--   Found xkbcommon, version 1.5.0
--   Found xkbcommon-x11, version 1.5.0
--   Found cairo-xcb, version 1.17.8
--   Found libstartup-notification-1.0, version 0.12
--   Found libstartup-notification-1.0, version 0.12
--   Found libxdg-basedir, version 1.2.3
--   Found libxdg-basedir, version 1.2.3
--   Found xcb-xrm, version 1.3
-- Looking for backtrace_symbols
-- Looking for backtrace_symbols - not found
-- checking for execinfo -- found
-- Looking for round
-- Looking for round - not found
-- Looking for round
-- Looking for round - found
-- checking for round -- in libm
-- busted not found.
-- luacheck not found.
-- Checking if 'package' target should be generated.
-- rpmbuild -> /data/data/com.termux/files/usr/bin/rpmbuild
-- rpmbuild found, enabling RPM for the 'package' target.
-- dpkg -> /data/data/com.termux/files/usr/bin/dpkg
-- dpkg found, enabling DEB for the 'package' target.
-- Package version will be set to 4.3.0.0~git1606-g0e5fc457-dirty.
-- Configuring done (23.9s)
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
LUA_MATH_LIBRARY (ADVANCED)
    linked by target "test-gravity" in directory /data/data/com.termux/files/home/awesome
    linked by target "awesome" in directory /data/data/com.termux/files/home/awesome
    linked by target "lgi-check" in directory /data/data/com.termux/files/home/awesome
    linked by target "test-systray" in directory /data/data/com.termux/files/home/awesome

-- Generating done (3.8s)
CMake Generate step failed.  Build files cannot be regenerated correctly.
make: *** [Makefile:27: build/Makefile] Error 1

**Comment by actionless** [comment]
> -- Could NOT find Lua (missing: LUA_LIBRARIES) (found version "5.4.6")

mb that's actually the rootcause of the segfault, not that it can't connect to dbus?
