### ISSUE TITLE
/home/user/.config/awesome/rc.lua:688/694: attempt to index a nil value (field 'volume')

### ISSUE THREAD

**Issue by diavolicchio** [awesomeWM/awesome#3833]
Output of `awesome --version`:

awesome v4.3 (Too long)
 • Compiled against Lua 5.3.6 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2

**How to reproduce the issue:**
I'm on an HP laptop and when i hit the f8 and f7 keys for volume up and volume down corrispondently i get an error

**Actual result:**
When i hit them i get this error thrown at me: "/home/user/.config/awesome/rc.lua:688: attempt to index a nil value (field 'volume')" if it try to increase volume
and "/home/user/.config/awesome/rc.lua:694: attempt to index a nil value (field 'volume')" if i try to decrease volume

**Expected result:**

It should decrease and increase volume.

My rc.lua if needed:
https://pastebin.com/qbf29j6u

It's the default Arcolinux distro awesome config, anyone can help?

**Comment by Aire-One** [comment]
Hello @diavolicchio,

> /home/user/.config/awesome/rc.lua:688: attempt to index a nil value (field 'volume')

Looking at your config, line 688 is 

```lua
os.execute(string.format("amixer -q set %s 1%%+", beautiful.volume.channel))
```

You have to make sure `beautiful.volume` exists. AFAICT it should be part of the theme with this config.

The issue with the other button is the same problem.

> It's the default Arcolinux distro awesome config, anyone can help?

I'm not familiar with Arcolinux. You should report the issue to them, so that they can fix it.

**Comment by ducks** [comment]
howdy @diavolicchio,

based on your rc.lua file, you are using the blackburn theme which has the volume widget commented out:
https://github.com/arcolinux/arcolinux-awesome/blob/master/etc/skel/.config/awesome/themes/blackburn/theme.lua#L172

it looks like the arcolinux default is the multicolor theme which does not have that widget commented out.

rc file showing chosen_theme:
https://github.com/arcolinux/arcolinux-awesome/blob/master/etc/skel/.config/awesome/rc.lua#L109

multicolor theme volume widget:
https://github.com/arcolinux/arcolinux-awesome/blob/master/etc/skel/.config/awesome/themes/multicolor/theme.lua#L197
