### ISSUE TITLE
Please don't deprecate `awful.keygrabber.run`

### ISSUE THREAD

**Issue by musjj** [awesomeWM/awesome#3842]
It looks like that `awful.keygrabber.run` is marked as deprecated. But I believe that it has use-cases that cannot be covered by other existing functions.

For example, this API is still useful for parsing vi-like keychords. The documentation suggests using `awful.keygrabber { ... }` for this use-case, but this can only be used to parse alphanumeric sequences. For example, key sequences like `Mod4+z a Control+b c` would not be possible with that API.

Another thing that is currently not possible is "sticky" modes. For example, let's say we want to declare a "mode" like this:

```
Mod4+z
└─ m (sticky mode)
   ├─ Control+a
   └─ n
```

`Mod4+z m` will activate a mode where you can repeatedly press either `Control+a` or `n` to trigger the coressponding action. This is useful for triggering repetitive actions, without having to re-do the entire chord over and over again.

The documentation actually demonstrates this use-case:

```lua
-- The following function can be bound to a key, and be used to resize a
-- client using the keyboard.

function resize(c)
  local grabber
  grabber = awful.keygrabber.run(function(mod, key, event)
    if event == "release" then return end

    if     key == 'Up'    then c:relative_move(0, 0, 0, 5)
    elseif key == 'Down'  then c:relative_move(0, 0, 0, -5)
    elseif key == 'Right' then c:relative_move(0, 0, 5, 0)
    elseif key == 'Left'  then c:relative_move(0, 0, -5, 0)
    else   awful.keygrabber.stop(grabber)
    end
  end)
end
```

As you can see, this is only possible with a lower-level API like `awful.keygrabber.{run,stop}`.

Can we consider un-deprecating this function?

**Comment by TaleWatcher** [comment]
As I understand this is functionally identical

```lua
-- to use, bind resizer:start to a key
local resizer = awful.keygrabber{
    keypressed_callback = function(self, mod, key event)
        local c = client.focus

        if     key == 'Up'    then c:relative_move(0, 0, 0, 5)
        elseif key == 'Down'  then c:relative_move(0, 0, 0, -5)
        elseif key == 'Right' then c:relative_move(0, 0, 5, 0)
        elseif key == 'Left'  then c:relative_move(0, 0, -5, 0)
        else self:stop()
        end
    end,
}
```
So it should be possible to replicate anything done with `keygrabber.run` by using `keypressed_callback` and `keyreleased_callback`

**Comment by sclu1034** [comment]
Apart from the additional `self` parameter, the functions assigned to `keypressed_callback` and `keyreleased_callback` form the same one that's passed to `keygrabber.run` (and you rarely need both event types anyways).
Whatever you use in the latter to keep track of your "sticky" mode can be done in the former, too (probably even better, as you can use things like `self._private` for proper per-instance state).
The `sequence` parameter of `stop_callback` does work for simple cases like the alphanumeric Vi mode in the docs, but it is by no means the only way to do things.

So what is a specific instance of those "features fairly difficult to implement"? E.g. where exactly did you get stuck when trying to port that example of yours?

**Comment by musjj** [comment]
Wow, you're right. I was misled by the first two examples, but it looks like the API is more flexible than I thought. The example in the `root_keybindings` [^1] section of the manual was pretty illuminating. 

So this is:

```lua
local function callback(mod, key, event)
  ...
end

awful.keygrabber.run(callback)
awful.keygrabber.stop(callback)
```

equivalent to this:

```lua
local function callback(self, mod, key, event)
  self:stop()
end

awful.keygrabber {
  autostart = true,
  keypressed_callback = callback,
}
```

[^1]: Note that `root_keybindings` is not implemented yet, you need to put the root keybindings you want inside `keybindings` and set `export_keybindings` to `true`. It's not possible to have separate root and internal keybindings yet.
