### ISSUE TITLE
awful.spawn() sometimes kills focused app

### ISSUE THREAD

**Issue by radialserial** [awesomeWM/awesome#3848]
Output of `awesome --version`:

```
awesome v4.3 (Too long)
 • Compiled against Lua 5.4.4 (running with 0.9.2)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: /usr/share/lua/5.4/lgi/version.lua
```

**How to reproduce the issue:**

- Spawn any program  using `awful.spawn(program_name)` bound to a key using `awful.key()`

**Actual result:**

- **_Sometimes_**, the program that is currently focused will be terminated, and the program to be spawned will open as normal.

**Expected result:**

- The spawned program should open **without** killing a focused application.

**Comment by actionless** [comment]
also try running awesome with --no-argb - mb graphic rendering is crashing in your apps due to driver incompatibility with alpha rgb mode

**Comment by radialserial** [comment]
Update: I've since moved from Fedora 38, which was what I used when I made this post, to EndeavourOS

This problem had been popping up every now and then in Fedora 36, 37, and 38 for me.

So far, I haven't been able to reproduce the issue on Endeavour.

**Comment by actionless** [comment]
ok, it confirms that it was some configuration-specific problem, as i mentioned most likely related graphical drivers

**Comment by radialserial** [comment]
Unfortunately the problem still happens on EndeavourOS, albeit very rarely. I've only had it happen two or three times since I distro-hopped.

**Comment by actionless** [comment]
> also try running awesome with --no-argb - mb graphic rendering is crashing in your apps due to driver incompatibility with alpha rgb mode

?

**Comment by radialserial** [comment]
> > also try running awesome with --no-argb - mb graphic rendering is crashing in your apps due to driver incompatibility with alpha rgb mode
> 
> ?

I assume that's done by editing ` /usr/share/xsessions/awesome.desktop`? I'm trying that now, will see if it works.

**Comment by radialserial** [comment]
Update: Issue still happening even with awesome set to start with `--no-argb` in `/usr/share/xsessions/awesome.desktop`

Something I've neglected to mention is that the issue closes the currently focused window but doesn't kill the process, like something such as xkill might do; For instance, when the issue happens with something like Discord, the client closes but it remains open in the tray.

**Comment by radialserial** [comment]
> I suggest you check the journald or syslog logs to see if the OOM killer wasn't involved in this. I have high doubts this is caused by an AwesomeWM bugs

Regarding this, I'm not entirely sure how to check those for this particular issue.
