### ISSUE TITLE
Switch to `--no-argb` flag by default in the next (major?) release?

### ISSUE THREAD

**Issue by actionless** [awesomeWM/awesome#3852]
argb mode (default now):
 - not often used by other window managers, so due to low level of testing - it often bugs on certain combination of hardware, driver version, X version etc
 
no-argb mode:
 - can't use compositor in this mode

idk, mb for such sort of stuff we could employ user surveys, to figure out which of two configurations is more popular - as it might help to reduce often bug reports caused by aforementioned driver issues

my personal idea for the  solution is to have multiple /usr/share/xsession (with --no-argb flag and without), and so i recommend to populate default awesome session with --no-argb flag, but add second session without it (and name it "AwesomeWM (ARGB mode)"

**Comment by Elv13** [comment]
This would be a breaking change. So I am not inclined in changing this in 2024. Yes, it should probably never have been the default, but it is. When it was made the default, nobody knew the impact of it.

**Comment by actionless** [comment]
@Elv13 i understand that it's a breaking change, that's why i suggesting to do in the **major** release as that formally allows breaking API compatibility
