### ISSUE TITLE
root.fake_input() working inconsistently

### ISSUE THREAD

**Issue by mimuki** [awesomeWM/awesome#3853]
Output of `awesome --version`:
```
awesome v4.3 (Too long)
 • Compiled against Lua 5.3.6 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
```

**How to reproduce the issue:**

1. Add a keybinding that presses a different key when pressed, for example:
```
awful.key({ modkey, }, "Left",
    function ()
        root.fake_input('key_release', 'Left')                                         
        root.fake_input('key_press'  , 'F9'  )
        root.fake_input('key_release', 'F9'  )
    end),
```
             
2. Press that keybind repeatedly

**Actual result:**

if you press the keybind too quickly (on my machine, ~3 times a second) sometimes fake_input() won't press the key

**Expected result:**

doing the same action (pressing your keybind) gives the same result (fake_input pressing a different key) consistently. 

I also made sure to test this on the default config (only replacing the default modkey+left binding) and it still happened.

**Comment by actionless** [comment]
you're not releasing left mouse button at all: file:///usr/share/doc/awesome/doc/core_components/root.html#fake_input

**Comment by intrntbrn** [comment]
If you press the key too quickly, you're most likely causing a race condition and you end up with something like:

```
root.fake_input('key_press'  , 'F9'  )
root.fake_input('key_press'  , 'F9'  )
root.fake_input('key_release', 'F9'  )
root.fake_input('key_release', 'F9'  )
```

Hence it looks like that the key press wasn't registered, but in reality the order was just messed up due do the asynchronism.

**Comment by actionless** [comment]
yeah that could be it - while awesome's lua code there is executed synchronously, underlaying xcb call (xcb_test_fake_input()) is executed asynchronously

**Comment by actionless** [comment]
i recommend you using `xdotool `
