### ISSUE TITLE
Missing documentation for `wibox.widget.textbox`'s `set_text` and `set_markup`

### ISSUE THREAD

**Issue by p-himik** [awesomeWM/awesome#3856]
Maybe other methods as well but I checked only those two.

The source docs for `set_markup` is there: https://github.com/awesomeWM/awesome/blob/aa8c7c6e27a20fa265d3f06c5dc3fe72cc5f021e/lib/wibox/widget/textbox.lua#L176-L196
As well as for `set_text`: https://github.com/awesomeWM/awesome/blob/aa8c7c6e27a20fa265d3f06c5dc3fe72cc5f021e/lib/wibox/widget/textbox.lua#L209-L223

However, the docs page at https://awesomewm.org/apidoc/widgets/wibox.widget.textbox.html doesn't mention those at all.

**Comment by Aire-One** [comment]
Hello @p-himik,

Objects based on `gears.object` (which is pretty much every object in the Awesome API) have some metatable magic ✨. Accessor methods `get_property` and `set_property` are automatically called when reading/writing to the `property` property. 

```lua
print(mytextbox.markup)
-- is implicitly the same as
print(mytextbox:get_markup())

mytextbox.markup = "hello"
-- is implicitly the same as
mytextbox:set_markup("hello")
```

The idea is that the accessors can define some business logic that you don't have to worry about as a user. You only need the high level declarative style syntax "I want the markup to be ABC". Whether the accessor methods are defined, or the property is a standard field shouldn't matter to the end user. 

The code you are pointing to is part of the documentation under the markup property's section: https://awesomewm.org/apidoc/widgets/wibox.widget.textbox.html#markup

**Comment by p-himik** [comment]
I see. And the docs seem to be propagated from the source code of the methods to the docs of the corresponding properties, nice.

But shouldn't those methods still at least be mentioned, so that both page search and web search work? Especially given that other docs still do mention `:set_markup` despite them talking about the declarative approach, e.g. on this page: https://awesomewm.org/apidoc/documentation/03-declarative-layout.md.html

**Comment by actionless** [comment]
then, it's more about removing the mentions of now-internal methods
