### ISSUE TITLE
Browser is stuck maximized

### ISSUE THREAD

**Issue by port19x** [awesomeWM/awesome#3866]
Output of `awesome --version`:

awesome v4.3 (Too long)
 • Compiled against Lua 5.3.6 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2

**How to reproduce the issue:**

Start awesomewm with a browser as one of the autostart programs.
Relevant config line:
```
awful.spawn.with_shell("command -v brave && pgrep -x brave || brave")
```
[(Full config)](https://github.com/port19x/dotfiles/blob/master/awesome/rc.lua)

**Actual result:**

This first window stays stuck as a maximized window.
Closing and opening another one does not resolve the issue.
This leads me to believe there may be either an error in my config, or less likely a subtle error in awesome startup code.

**Expected result:**

Windows obey tiling rules as per selected layout.

**Comment by sclu1034** [comment]
There's a third option, which covers the vast majority of these cases: User error. You opened that same browser in a floating-based desktop environment before, maximized it there and the size hints work as designed.
Browsers are one of the few applications that save their windows' geometry at close and try to request the same setup when started. Awesome is, by default, configured to honor those so-called size hints.

Focus the window, hit your "toggle maximized" hotkey once (or create one). As long as you don't switch window managers again, it'll remember to not request being maximized.

**Comment by port19x** [comment]
I have not installed a different desktop environment before on this install, which is automated via a script.
The unmaximize did not work via the following binding
```
    awful.key({ "Mod4",           }, "m", function (c)
          naughty.notify({text="ok go(1)"})
          c.maximized_horizontal = not c.maximized_horizontal
          naughty.notify({text="ok go(2)"})
          c.maximized_vertical   = not c.maximized_vertical
          naughty.notify({text="ok go(3)"})
    end),
```
naughty.notify for debug purposes just in case, as per [this](https://stackoverflow.com/questions/29670635/awesome-wm-does-not-maximize-windows-anymore) stackoverflow post
Some ancient stack exchange posts recommends a timed trigger, but that sounds wrong [(source)](https://unix.stackexchange.com/questions/105548/how-to-force-applications-to-not-start-maximised-in-awesome-wm)

Is there any further debugging I should do, perhaps a log file I'm not aware off?

**Comment by port19x** [comment]
> Awesome is, by default, configured to honor those so-called size hints

Alternatively, just changing this default would be sufficient in my case

**Comment by Aire-One** [comment]
> > Awesome is, by default, configured to honor those so-called size hints
> 
> Alternatively, just changing this default would be sufficient in my case

Maybe you want to try some variant of the snippet from https://github.com/awesomeWM/awesome/issues/3345#issuecomment-848758491

**Comment by port19x** [comment]
So the issue fixed itself and I have no idea how.
I did not follow the steps outlined by @Aire-One.
If anyone stumbles upon this in the future, good luck
