### ISSUE TITLE
KP_ENTER is ignored in main menu

### ISSUE THREAD

**Issue by unknown321** [awesomeWM/awesome#3867]
Output of `awesome --version`:
```
$ awesome --version
awesome v4.3 (Too long)
 • Compiled against Lua 5.3.6 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
```

**How to reproduce the issue:**

Press Super-W to open main menu. Highlight entry (using arrow keys/mouse) and press `numpad enter` (KP_ENTER).

**Actual result:**

Nothing happens

**Expected result:**

Menu entry starts, like on `regular enter` press.

**Comment by unknown321** [comment]
Patch:

```diff
---- /usr/share/awesome/lib/awful/menu.lua	2023-11-17 21:37:00.270213981 +0300
+++ /usr/share/awesome/lib/awful/menu.lua	2023-11-17 21:37:46.518324482 +0300
@@ -107,7 +107,7 @@
               down = { "Down", "j" },
               back = { "Left", "h" },
               exec = { "Return" },
-              enter = { "Right", "l" },
+              enter = { "Right", "l", "KP_Enter" },
               close = { "Escape" } }
```

Not sure if this is a right place to patch, still works for me.

**Comment by Elv13** [comment]
Can you submit a pull request? You can do this directly on the GitHub web UI by pressing edit or in a terminal
