### ISSUE TITLE
Missing notification body if asian language characters are mixed with latin characters in summary

### ISSUE THREAD

**Issue by unknown321** [awesomeWM/awesome#3868]
Output of `awesome --version`:

```
$ awesome --version
awesome v4.3 (Too long)
 • Compiled against Lua 5.3.6 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
```

**How to reproduce the issue:**

Install libnotify, send notifications:

```
notify-send -t 20000 "Ελληνικά greek" "works!"
notify-send -t 20000 "русский russian" "works!"
notify-send -t 20000 "اَلْعَرَبِيَّة arabic" "works!"
notify-send -t 20000 "मानक हिन्दी hindi" "works!"
notify-send -t 20000 "日本語" "works!"
notify-send -t 20000 "汉语" "works!"
notify-send -t 20000 -u critical "汉语 chinese" "broken"
notify-send -t 20000 -u critical "日本語 japanese" "broken"
```

**Actual result:**

Notifications with summaries in japanese and chinese mixed with latin don't have body:

![2023-11-17-081649_149x360_scrot](https://github.com/awesomeWM/awesome/assets/1469658/80319536-5af0-4c96-ac5d-7c08171ac5bf)

**Expected result:**

All notifications have body.

DBus log for single broken notification [dbus-monitor.log](https://github.com/awesomeWM/awesome/files/13387607/dbus-monitor.log)

**Comment by Elv13** [comment]
Can you try again with the Git version of Awesome? This code has been fully rewritten since v4.3

**Comment by unknown321** [comment]
Fixed in master:

![2023-11-19-043852_122x366_scrot](https://github.com/awesomeWM/awesome/assets/1469658/d3dd40c7-f56c-4226-8b65-a3708bc74943)

```
awesome v4.3-1614-gdfe6a478-dirty (Too long)
 • Compiled against Lua 5.3.6 (running with Lua 5.3)
 • API level: 4
 • D-Bus support: yes
 • xcb-errors support: no
 • execinfo support: yes
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
 • Transparency enabled: yes
 • Custom search paths: no
```

**Comment by unknown321** [comment]
Actually, it was a configuration issue. My rc.lua is pretty old and was missing this snippet:

```lua
naughty.connect_signal("request::display", function(n)
    naughty.layout.box { notification = n }
end)
```
