### ISSUE TITLE
theme/titlebar: missing icon for minimize button

### ISSUE THREAD

**Issue by blueyed** [awesomeWM/awesome#387]
Via https://github.com/awesomeWM/awesome/pull/369#issuecomment-126942662, from @actionless:

> also it seems like we are missing an icon for minimize: http://awesome.naquadah.org/doc/api/modules/awful.titlebar.html#titlebar.widget.minimizebutton

**Comment by actionless** [comment]
after you'll merge that PR i can add it

**Comment by sixshotx** [comment]
The latest titlebar.lua in lib/awful directory might still have the problem.
` local widget = titlebar.widget.button(c, "minimize", function() return c.minimized end, function(c) c.minimized = not c.minimized end)`

parameter "c" is missing in the first function().
