### ISSUE TITLE
Menubar Documentation Typo

### ISSUE THREAD

**Issue by floington500** [awesomeWM/awesome#3873]
Not anything huge, just a small typo in [the API docs for menubar](https://awesomewm.org/doc/api/libraries/menubar.html):

![typo](https://github.com/awesomeWM/awesome/assets/109321368/64279813-afb0-4969-996c-656bbca8b424)

I confirmed that the actual value for these two are `menubar_fg_focus` and `menubar_bg_focus`, so it seems to be implemented correctly.

**Comment by mattplm** [comment]
It is fixed on the more recent docs for the git version: https://awesomewm.org/apidoc/popups_and_bars/menubar.html#Theme_variables
