### ISSUE TITLE
gaps outside have been implemented?

### ISSUE THREAD

**Issue by daricoder** [awesomeWM/awesome#3874]
When I set useless_gap the gaps around the layout are added automatically.
I wonder what would happen if I don't want gaps around the layout or if I could modify them it would be good.

In the video I show how I modify the outer gap and the inner gaps. Is there a way to do it or is it implemented in some way?

https://github.com/awesomeWM/awesome/assets/64455469/98415f74-6edf-4d10-99f2-3022cbb1f6f6

**Comment by mattplm** [comment]
Hello,

Nope, afaik, there is only the concept of `useless_gap` in awesome which is basically the inner gap found in sway/i3 if I understand correctly.

One thing you could do is play with the screen padding like so:

```lua
    -- [...]
    awful.key({ modkey,           }, "=", function ()
                local s = awful.screen.focused()
                s.padding = {
                    left   = s.padding.left + 10,
                    right  = s.padding.right + 10,
                    top    = s.padding.top + 10,
                    bottom = s.padding.bottom + 10,
                }
        end, {description = "Increase screen padding by 10", group = "screen"})
    -- [...]
```
You just need to be careful to add boundaries to your padding, negative padding is not forbidden and top padding needs to take the wibar (or whatever you use) into account.

Another solution would be to bake the concept of outer and inner gap into awful's layout system to replace the useless gap.
I've tried moving stuff around a bit and it seems to be pretty easy to do. [I have a commit here on my fork](https://github.com/awesomeWM/awesome/commit/d1d3ac6f52eb7b9cf07156bcf8dfbec8c35d8848). 

Though it needs some more testing and may break some configurations so I'm not sure this is really interesting. This was just an excuse for me to play with the layout system tbh.
