### ISSUE TITLE
Cannot resize windows with mouse

### ISSUE THREAD

**Issue by kevinyyca** [awesomeWM/awesome#3888]
# System
OS: Linux Mint 21.2
AwesomeWM version: `4.3`

full `awesome --version` output
```
awesome v4.3 (Too long)
 • Compiled against Lua 5.3.6 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
```

# Issue
I Was trying to resize a window in Awesome WM but it won't work:
![awesomeresize](https://github.com/awesomeWM/awesome/assets/121273910/1c92346e-e466-4c37-822d-012f021e3df2)
When i move my mouse to one of edges of a window the mouse doesn't change to a resizing thing.
And i can't resize the window. Sometimes it would work like normal but most of the time it doesn't

When i watch a video of someone using Awesome WM they can resize the window like normal.

**Comment by Praxylmx** [comment]
In AwesomeWM you do not move mouse cursor to edge of window to resize, Instead hold your modkey (either Super or ALT) and then click and hold right mouse button to resize window.

**Comment by kevinyyca** [comment]
> In AwesomeWM you do not move mouse cursor to edge of window to resize, Instead hold your modkey (either Super or ALT) and then click and hold right mouse button to resize window.

It doesn't resize the window it moves it

**Comment by Praxylmx** [comment]
> > In AwesomeWM you do not move mouse cursor to edge of window to resize, Instead hold your modkey (either Super or ALT) and then click and hold right mouse button to resize window.
> 
> It doesn't resize the window it moves it

Assuming you haven't modified this in your config file, Modkey + Left Click moves the window and Modkey + Right Click resizes the window. 

https://github.com/awesomeWM/awesome/assets/49450563/25ac7576-f0b8-43c4-a955-93b34e7c29aa
