### ISSUE TITLE
Multiple panels at top when having a mistake in rc.lua

### ISSUE THREAD

**Issue by kevinyyca** [awesomeWM/awesome#3889]
# system
OS: Linux mint 21.2
awesome version: v4.3 (Too long)
awesome version full
```
awesome v4.3 (Too long)
 • Compiled against Lua 5.3.6 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
```

# Issue
Sometimes when i edit the rc.lua config file and i make a mistake when i restart awesome i get two panels on the
top of my screen

**Comment by ilhamfu** [comment]
it's common, it usually happen when error occur after top bar is created
