### ISSUE TITLE
Multiple windows struck to gether with padding

### ISSUE THREAD

**Issue by kevinyyca** [awesomeWM/awesome#3890]
# System
OS: Linux Mint 21.2
awesome version: 4.3 (Too long)
full awesome version:
```
awesome v4.3 (Too long)
 • Compiled against Lua 5.3.6 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
```

# Issue
This is a part of my awesome config
```lua
awful.screen.connect_for_each_screen(function(s)
    -- Useless gaps
    s.padding = {
      top = 15,
      bottom = 15,
      left = 15,
      right = 15
    }
```

So i now have useless gaps but when i open two windows they are stuck together with no gaps
![image](https://github.com/awesomeWM/awesome/assets/121273910/65e79c0c-05fa-4331-9724-faf65e4ed246)

**Comment by jeffmhubbard** [comment]
That is not "useless gaps"... That is screen padding. You need to set `beautiful.useless_gap = 15`.

https://awesomewm.org/doc/api/libraries/beautiful.html#useless_gap

**Comment by kevinyyca** [comment]
> That is not "useless gaps"... That is screen padding. You need to set `beautiful.useless_gap = 15`.
> 
> https://awesomewm.org/doc/api/libraries/beautiful.html#useless_gap

Oh that works
