### ISSUE TITLE
Notification tray icon issue w/ Indicator Sound Switcher

### ISSUE THREAD

**Issue by mxmilkiib** [awesomeWM/awesome#3894]
There's a problem with the tray icon of an app that would be really handy for multiple soundcards and audio work, https://github.com/yktoo/indicator-sound-switcher

There is an existing issue, which is now closed but "incomplete" because it was assumed the issue was on the WM side.

https://github.com/yktoo/indicator-sound-switcher/issues/91

Might anyone have an idea as to why this is happening?

It would be wonderful to be able to use the app!

awesome v4.3 (Too long)
 • Compiled against Lua 5.3.6 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2

**How to reproduce the issue:**

Run https://github.com/yktoo/indicator-sound-switcher

**Actual result:**

The tray icon is a blank black space.

**Expected result:**

That the Indicator Sound Switcher icon should be displayed.

**Comment by actionless** [comment]
> How to reproduce the issue:
> Run https://github.com/yktoo/indicator-sound-switcher

if it can't be reproduced with just AwesomeWM itself - it's not an AwesomeWM problem

**Comment by mxmilkiib** [comment]
That's not sound logic though. Maybe multiple things are doing the wrong thing.

**Comment by actionless** [comment]
then give the smallest possible code snippet how the problem could be reproduced on default config without any installing any extensions

**Comment by actionless** [comment]
oh, i've just relized it's not an awesomeWM widget (on the screenshot it looks like it):

![image](https://github.com/awesomeWM/awesome/assets/1655669/6dc4d57a-ae8a-489e-b91b-3e396dc9aa82)


then try it in another tray app - https://github.com/kolbusa/stalonetray - if it can't be displayed there but not in AwesomeWM - then it's indeed might be a problem here

**Comment by actionless** [comment]
also it could be potentially a dup of https://github.com/awesomeWM/awesome/issues/2995
