### ISSUE TITLE
awesomeWM workspaces and skippy-xd

### ISSUE THREAD

**Issue by felixfung** [awesomeWM/awesome#3902]
Hi,

skippy-xd has seen some improvements and works well with awesomewm!

https://github.com/felixfung/skippy-xd/
https://youtu.be/R__zua04xe0
https://youtu.be/reUDapFGnmQ

As far as I know, everything works perfectly between awesomewm and skippy-xd. EXCEPT workspaces:
https://github.com/felixfung/skippy-xd/issues/52

So far I have not found too many documentations on workspaces/tags...

Right now I am seeing that _NET_NUMBER_OF_DESKTOPS = XineramaQueryScreens() * (virtual desktops per screen)

(and yes I see that awesomewm uses xcb rather than x11, skippy-xd is compatible with WMs that uses xcb)

For proper implementation of skippy-xd paging on awesomewm, we need a way of querying (or perhaps explicit setting through the skippy-xd config file) *tags* in skippy-xd, including querying for:
1. the number of tags
2. the names of the tags
3. the geometric dimensions of the tags
4. and tag associated with each window.

How should we do that?

Thanks a bunch!

**Comment by actionless** [comment]
but the workspace are not specific thing in awesome wm - in other window managers (think `openbox`) the workspaces are implemented the same

so i don't think it's a good idea to use awesome's api to query that info, but rather query it from x itself

**Comment by felixfung** [comment]
@actionless if that is the case, then we should have
```
_NET_NUMBER_OF_DESKTOPS == XineramaQueryScreens()
```
rather than
```
_NET_NUMBER_OF_DESKTOPS == XineramaQueryScreens() * (virtual desktops per screen)
```

E.g. when there are 9 tags, and 1 screen, _NET_NUMBER_OF_DESKTOPS == 9; but when there are 2 screens, then _NET_NUMBER_OF_DESKTOPS == 18.

From https://specifications.freedesktop.org/wm-spec/1.3/ar01s03.html, 
```
 This property should be set and updated by the Window Manager to indicate the *number of virtual desktops*.
```

**Comment by actionless** [comment]
but that's a property of a root window, so it will be a number of desktops for the screen on which that window at
