### ISSUE TITLE
Multiple definition error while compiling on a 32bit machine.

### ISSUE THREAD

**Issue by verso9** [awesomeWM/awesome#3919]
Output of `awesome --version`:
awesome-4.3 

_REPLACE with full version output_

**How to reproduce the issue:**
Have a clean (no desktop enviroments) debian-12.4-1386 installation.
Install awesome dependencies:
`sudo apt install asciidoctor debhelper-compat imagemagick libcairo2-dev libdbus-1-dev libgdk-pixbuf2.0-dev libglib2.0-dev libpango1.0-dev libstartup-notification0-dev libx11-xcb-dev libxcb-cursor-dev libxcb-icccm4-dev libxcb-keysyms1-dev libxcb-randr0-dev libxcb-shape0-dev libxcb-util0-dev libxcb-xinerama0-dev libxcb-xkb-dev libxcb-xrm-dev libxcb-xtest0-dev libxdg-basedir-dev libxkbcommon-dev libxkbcommon-x11-dev x11proto-core-dev xmlto zsh build-essential dbus-x11 gir1.2-gtk-3.0 libxcb-icccm4-dev libxcb-util0-dev libxcb1-dev x11-apps x11-utils x11-xserver-utils xfonts-base xterm xvfb libxcb-xfixes0-dev`
Run `make`

**Actual result:**
Output
```
 [ 66%] Built target setup_directories

[ 67%] Built target generate_awesomerc

[ 68%] Linking C executable awesome 
```

This is the stage where the compiling process breaks.

I get lots of these errors:
```
/usr/bin/ld: CMakeFiles/awesome.dir/objects/tag.c.o:/home/sander/git/awesome-luajit/src/awesome-4.3/build/objects/tag.h:49: multiple definition of `tag_class'; CMakeFiles/awesome.dir/event.c.o:/home/sander/git/awesome-luajit/src/awesome-4.3/build/objects/tag.h:49: first defined here
/usr/bin/ld: CMakeFiles/awesome.dir/objects/tag.c.o:/home/sander/git/awesome-luajit/src/awesome-4.3/build/luaa.h:314: multiple definition of `global_signals'; CMakeFiles/awesome.dir/awesome.c.o:/home/sander/git/awesome-luajit/src/awesome-4.3/build/luaa.h:314: first defined here
/usr/bin/ld: CMakeFiles/awesome.dir/objects/tag.c.o:/home/sander/git/awesome-luajit/src/awesome-4.3/build/objects/client.h:195: multiple definition of `client_class'; CMakeFiles/awesome.dir/awesome.c.o:/home/sander/git/awesome-luajit/src/awesome-4.3/build/objects/client.h:195: first defined here
/usr/bin/ld: CMakeFiles/awesome.dir/objects/tag.c.o:/home/sander/git/awesome-luajit/src/awesome-4.3/build/objects/window.h:83: multiple definition of `window_class'; CMakeFiles/awesome.dir/awesome.c.o:/home/sander/git/awesome-luajit/src/awesome-4.3/build/objects/window.h:83: first defined here
/usr/bin/ld: CMakeFiles/awesome.dir/objects/tag.c.o:/home/sander/git/awesome-luajit/src/awesome-4.3/build/objects/button.h:42: multiple definition of `button_class'; CMakeFiles/awesome.dir/awesome.c.o:/home/sander/git/awesome-luajit/src/awesome-4.3/build/objects/button.h:42: first defined here
```

**Expected result:**
Have a clean compilation process just like on a 64bit machine

 I know the error is Multiple definition of ...
But I don' know how to solve it.
Did I missed a step?
Are there other steps for 32-bit PC's?
Do you think it will compile, i really wouldn't like to go back to DWM.

**Comment by awilfox** [comment]
This is because you are using GCC 10 or later.  It happens to me on a 64-bit machine as well.  It is fixed by d256d9055095.

Note that this commit does not apply cleanly to the tree without applying c5202a487085 first, but the difference is only in the context, so you could probably manually apply it without.
