### ISSUE TITLE
How to make new notifications update to existing notifications?

### ISSUE THREAD

**Issue by ShadeZerox** [awesomeWM/awesome#3921]
![image](https://github.com/awesomeWM/awesome/assets/155251572/0b4d56dc-3bc6-4e56-96bd-a759cce4b2de)

This small script uses dunstify to send notifications, now if i'd have to use dunst, it would update the new text into the first notification instead of outputting 5 notifications separately. How can I replicate that in naughty?

**Comment by actionless** [comment]
save notification to an object and edit properties of it, see documentation for `naughty`

**Comment by actionless** [comment]
https://github.com/actionless/awesome_config/blob/master/actionless/widgets/music/widget.lua#L204-L212
