### ISSUE TITLE
workaround for pystray python tray icon programs

### ISSUE THREAD

**Issue by Konfekt** [awesomeWM/awesome#3922]
Output of `awesome --version`: 4.3

**How to reproduce the issue:**

Run a program using [pystray](https://github.com/moses-palmer/pystray/) such as [emailproxy](https://github.com/simonrob/email-oauth2-proxy) 

**Actual result:**

Tray icon does not react

**Expected result:**

Tray icon reacts

---

Pystray is a Python library to add a tray icon. According to [its description](https://github.com/moses-palmer/pystray/) it is aimed at Ubuntu and Gnome, but maybe there's a workaround for window managers, such as AwesomeWM as well?

**Comment by actionless** [comment]
> Supported platforms are Linux under Xorg

it's written that it supports native xorg tray

if not then not

**Comment by Konfekt** [comment]
Thank you for your assistance. Since Gnome and Ubuntu also used Xorg, and it does not work under Awesome and other Window managers, I asked rather for a work around.
