### ISSUE TITLE
Shell environment not correct while using `awful.spawn_with_shell`?

### ISSUE THREAD

**Issue by solowdev** [awesomeWM/awesome#3924]
**Output of `awesome --version`:**

awesome v4.3 (Too long)
 • Compiled against Lua 5.4.4 (running with 0.9.2)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: /usr/share/lua/5.4/lgi/version.lua

**How to reproduce the issue:**

- Using `awful.spawn("code")` or `awful.spawn_with_shell("code")` to spawn VSCode
- Having rbenv installed as in documentation (through `.bash_profile`/`.bashrc` or `.zshrc`)
- Having Shopify Ruby LSP extension, Solargraph, or any VSCode extension that would need rbenv (or probably any ruby version manager) installed

_Originally posted by @solowdev in https://github.com/Shopify/ruby-lsp/issues/1216#issuecomment-2146990833_

**Actual result:**

- Getting this error:
 ```
Automatic Ruby environment activation with rbenv failed: 
Command failed: 
rbenv exec ruby -W0 -rjson -e 'STDERR.print({env: ENV.to_h,yjit:!!defined?(RubyVM::YJIT),version:RUBY_VERSION}.to_json)'
/bin/sh: line 1: rbenv: command not found
```

**Expected result:**

- Extensions should be working.
- Environment/Path should be loaded from the current user profile.

**Workaround found:**

- I figured out that launching the `.desktop` file made everything work. So I used `awful.util.spawn("gtk-launch code.desktop")` instead and no issues so far.

This is a minor issue but it can be annoying to deal with.

**Comment by solowdev** [comment]
Thank you for the clarification! 

Now, I get that it's supposed to work this way. However, what I still don't quite understand is that I used to never have this problem before. With the same config, same everything. Shell environment somehow was the good one. Not a major issue though.

If you were me in that situation, how would you tackle this problem in the cleanest manner possible? (if not using `gtk-launch`). I don't expect any answer if you don't have the time/energy for it though :)

Thanks again and have a great week.

**Comment by sclu1034** [comment]
> what I still don't quite understand is that I used to never have this problem before. With the same config, same everything
Nothing has changed on AwesomeWM's side, so something did. But it'd be hard to track down.

> If you were me in that situation, how would you tackle this problem in the cleanest manner possible?

Two options:
- Start AwesomeWM with the required environment variables. Then, everything started through it will inherit those values.
- Create a small shell script that sets up the stuff you need, e.g. `aweful.spawn("run_with_rbenv.sh code")`

**Comment by solowdev** [comment]
Thanks a lot!
