### ISSUE TITLE
Bluetooth pin accept notification doesn't appear with naughty.

### ISSUE THREAD

**Issue by m2neral** [awesomeWM/awesome#3931]
Output of `awesome --version`:

awesome v4.3 (Too long)
 • Compiled against Lua 5.3.6 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2

**How to reproduce the issue:**

Try to pair phone with bluetooth using blueman.

**Actual result:**

Pairing accept notification doesn't appear, or appears way too late.

**Expected result:**

Proper pairing notification. Works with dunst on other WMs (or with successfully starting dunst before awesome).

**Comment by actionless** [comment]
mb any errors in the awesome's stderr?

**Comment by actionless** [comment]
> awesome v4.3 (Too long)

also first check with git version, as no fixes are planned for the past release

**Comment by m2neral** [comment]
It's working normally now and I can't seem to replicate it.
