### ISSUE TITLE
codecov pipeline not responding in PRs

### ISSUE THREAD

**Issue by actionless** [awesomeWM/awesome#3934]
i've noticed that lately in all of the currently opened and approved PRs (https://github.com/awesomeWM/awesome/pulls?q=is%3Apr+is%3Aopen+review%3Aapproved), ex. https://github.com/awesomeWM/awesome/pull/3927 https://github.com/awesomeWM/awesome/pull/3930  https://github.com/awesomeWM/awesome/pull/3909

**Comment by Aire-One** [comment]
Digging in our GitHub Workflow, we install some bash script from codecov (https://github.com/awesomeWM/awesome/blob/master/.github/workflows/main.yml#L243) to manage the coverage upload later (https://github.com/awesomeWM/awesome/blob/master/.github/workflows/main.yml#L324 and https://github.com/awesomeWM/awesome/blob/master/.github/workflows/main.yml#L347)

The bash script headers comment links to https://github.com/codecov/codecov-bash/blob/master/readme.md that is an archived repository with deprecation warnings.

I guess the next step for us is to move to the new uploader, https://about.codecov.io/blog/introducing-codecovs-new-uploader/.

Alternatively, there is now an Action by codecov https://docs.codecov.com/docs/github-2-getting-a-codecov-account-and-uploading-coverage. Maybe it would be easier to simply switch to using it 🤷

**Comment by sclu1034** [comment]
Changing deprecated tools is probably helpful in the long run, but I would suggest not to ignore error messages when they itself give you instructions on how to fix them:

> Please upload with the Codecov repository upload token to resolve

A rate limit is server side, and unless they, for some weird reason, decided that the new tool gets to have a higher rate limit, it's going to run into the same issue.

Someone with access would have to log into codecov, get this repo's token, set that as a secret for actions, and configure the upload step to use it.

**Comment by actionless** [comment]
i never liked the dependency on those proprietary third-party services

i am thinking - could we just replace it to the bash one-liner which would compare coverage % in the report to nominal and return 0 (pipeline passing) or 1 (pipeline failing)?

**Comment by sclu1034** [comment]
At that point, you'd be better off removing the check altogether.
codecov's main feature isn't the check mark. It's all the tools it gives you to analyze the data, both changes in coverage over time, and telling you the exact lines that are missing from coverage.

With your "bash one-liner", you'd know nothing about how the PR affects coverage. You wouldn't know if it changed coverage compared to master, and you wouldn't know which lines are or are not covered.

---

As I said above, the error message very clearly tells you what it wants you to do. Have either of you tried that?

**Comment by Aire-One** [comment]
> Have either of you tried that?

I don't have access to the repository secrets on GitHub, so I cannot add the API key for the Actions (even if I can read it on the codecov admin settings)

I think Actionless also don't have access to these GitHub settings. So we are doomed to wait for someone else...

**Comment by sclu1034** [comment]
> we are doomed to wait for someone else...
And this "someone else" shows up once a year, if ever. So I'd say you're doomed for a lot more than that. Not having access to codecov is probably among the least impactful things that could happen.

You might want to try to get a hold of the people that do still have access, especially for the repo. And I don't mean just one ping on GitHub every blue moon. blueyed has an email address in their profile, Elv seems still active on Reddit outside r/Awesome, etc...

**Comment by Elv13** [comment]
I may or may not have fixed this, but anongit.freedesktop.org is getting DDOSsed, so the CI doesn't get far enough for me to test.

**Comment by Aire-One** [comment]
>anongit.freedesktop.org is getting DDOSsed, so the CI doesn't get far enough for me to test.

@Elv13: Ru-running today the CI for https://github.com/awesomeWM/awesome/actions/runs/10468278447. The git service seems to be back up now :)

**Comment by sclu1034** [comment]
The comment at https://github.com/awesomeWM/awesome/pull/3884#issuecomment-1873058236 is getting edited, which would suggest that Codecov does work in some capacity. #3943 still doesn't get coverage, and the error seems to be

> Missing Head Commit
> Unable to compare commits because the head commit was not found. [Learn more here](https://docs.codecov.com/docs/error-reference#section-missing-head-commit)

(https://app.codecov.io/gh/awesomeWM/awesome/pull/3943)

So I guess a successful workflow run on `master` is needed, in addition to the PR itself.
