### ISSUE TITLE
Error while trying to install awesome 

### ISSUE THREAD

**Issue by Danidro20** [awesomeWM/awesome#3935]
**How to reproduce the issue:**
l was following this guide https://www.reddit.com/r/awesomewm/comments/xi6ab5/installing_awesomewm/, but when l was going to install it by yay or by GitHub clone, I got this error.
GitHub clone:
![20240705_020347](https://github.com/awesomeWM/awesome/assets/70298813/38e510c9-63dd-4052-be1c-76f619fade7c)
Yay:
![20240705_020721](https://github.com/awesomeWM/awesome/assets/70298813/27dde3af-27fc-47ba-aed4-fd6c61e2f7a6)
(Before that, I installed base-devel)

**Comment by actionless** [comment]
that guide for arch linux is very-very wrong

just install it from aur directly:

https://aur.archlinux.org/packages/awesome-git

**Comment by Danidro20** [comment]
The first time I tried to install it, I did it directly using yay and I got the same error

**Comment by sclu1034** [comment]
https://gitlab.archlinux.org/archlinux/packaging/packages/ldoc/-/issues/1
