### ISSUE TITLE
Unblocking root window's swapchain

### ISSUE THREAD

**Issue by tyrypyrking** [awesomeWM/awesome#3939]
Output of `awesome --version`:
awesome v4.3-1655-gad0290bc1-dirty (Too long)
 • Compiled against Lua 5.4.7 (running with 0.9.2)
 • API level: 4
 • D-Bus support: yes
 • xcb-errors support: yes
 • execinfo support: yes
 • xcb-randr version: 1.6
 • LGI version: /usr/share/lua/5.4/lgi/version.lua
 • Transparency enabled: yes
 • Custom search paths: no

**How to reproduce the issue:**

Try to access root window with awesomewm running.

**Actual result:**

ERROR_NATIVE_WINDOW_IN_USE_KHR

**Expected result:**

An option to not have the root window taken over to allow third party to use it as the user desires.

**Comment by actionless** [comment]
what are you trying to achieve?

**Comment by tyrypyrking** [comment]
> what are you trying to achieve?

I'm trying to run a wallpaper engine. Essentially a window that takes over root instead of creating it's own window. It was working fine under xmonad, but awesomewm gives me isssue as it already has this resource taken.

**Comment by actionless** [comment]
i'm using this code for setting animated wallpaper:

```
bash -c "killall gifview ; xwinwrap -ov -fs -- gifview --bg \"#$(xrdb -query | grep "^*background" | cut -d# -f2)\" -w WID -a /path/to/image.gif"
```

check it out: https://github.com/takase1121/xwinwrap (or its sourcecode)

**Comment by tyrypyrking** [comment]
Using root window for background drawing is an incorrect usage, and there's no fault of awesomewm. Solution provided by @actionless displayed to me how to can be done.
