### ISSUE TITLE
Unable to Launch Flatpak/Snap App from the Command

### ISSUE THREAD

**Issue by davidganz** [awesomeWM/awesome#3940]
Hi!

you should consider a Solution to **run easily Flatpaks** or **Snaps** with Command.
If not you are a little outdated...

**Comment by Aire-One** [comment]
My distribution packages everything I need without Flatpak or Snaps, so I have to be outdated...

What exactly do you expect a window manager to do with that?

**Comment by davidganz** [comment]
That I said is right. Bah, I found how to fix it by a Script... But for you should be nicer to have overcome this limitation.
This said I want Congratulate you for the Awesome Work! :)
