### ISSUE TITLE
I keep getting this error ... does anyone have any idea ?

### ISSUE THREAD

**Issue by sfantu** [awesomeWM/awesome#3948]
38, minor 4), error=BadMatch (8)                                             2024-08-28 22:30:52 W: awesome: xerror:1062: X error: request=(null) (major 138, minor 8), error=(null) (141)                                             2024-08-28 22:30:52 W: awesome: xerror:1062: X error: request=(null) (major 138, minor 7), error=(null) (141)                                             2024-08-28 22:30:54 W: awesome: xerror:1062: X error: request=(null) (major 138, minor 4), error=BadMatch (8)                                             2024-08-28 22:30:54 W: awesome: xerror:1062: X error: request=(null) (major 138, minor 8), error=(null) (141)                                             2024-08-28 22:30:54 W: awesome: xerror:1062: X error: request=(null) (major 138, minor 7), error=(null) (141)

**Comment by psychon** [comment]
What does `xdpyinfo -queryExtensions | grep 138` say when you get one of these outputs? (It might be that the `major 138` is not always 138 and sometimes has another number, so this command needs to be run when these warnings are printed; at least without a restart of the X11 server in-between)

All I can say right now is that some of the requests AwesomeWM sends to the X11 server are not handled, but instead cause a "BadMatch" error. And all of them seem to be with a request that has the major opcode 138 and minor opcode 8. The major opcode identifies which protocol extension this request belongs to and the minor opcode is the request number for the request within this extension.

**Comment by sfantu** [comment]
Yeah I'm on termux ... Probably something missing from the x11 implementation.

**Comment by actionless** [comment]
i've grep-ed my AwesomeWM's log and apparently i'm seeing them too (on standard Linux desktop) once in several weeeks or so
