### ISSUE TITLE
Issue with second monitor after recent updates

### ISSUE THREAD

**Issue by Irubataru** [awesomeWM/awesome#3953]
Output of `awesome --version`:

```
awesome v4.3-1666-gd53eb1be6-dirty (Too long)
 • Compiled against Lua 5.4.7 (running with 0.9.2)
 • API level: 4
 • D-Bus support: yes
 • xcb-errors support: no
 • execinfo support: yes
 • xcb-randr version: 1.6
 • LGI version: /usr/share/lua/5.4/lgi/version.lua
 • Transparency enabled: yes
 • Custom search paths: no
```

## Description

After recently updating my system (arch, using the AUR `awesome-git` package, I have tried recompiling it),  I am having issues with my second monitor. Nothing shows up on it except the mouse cursor. If I clone the display it works fine, and if I play around with the resolution of it then it sometimes shows "something", but it's messed up, and when I move a window to the monitor it simply disappears regardless if some of the background and title bar is visible on it.

![image](https://github.com/user-attachments/assets/1b4a65af-8786-43e8-8e2b-aabd25c29472)

Not sure if this is an awesome issue, but I also don't know how to debug it. If I downgrade to the Arch `awesome` package (version 4.3-4) it works, but my config doesn't. It also fails with an empty config. Link to [my config](https://github.com/Irubataru/dotfiles/tree/d60e6a507954903623c98e20eef9f5bc9630b703/roles/awesome/config).

_Edit_: I tried rolling arch back to the last state I thought it worked, and rebuilt awesome, but it still doesn't work. Seems my system is just broken somehow :woman_shrugging:

**Comment by Irubataru** [comment]
My guess is that this doesn't have anything to do with awesome, I have made a [thread on the Archlinux forums](https://bbs.archlinux.org/viewtopic.php?pid=2195865#p2195865).

**Comment by actionless** [comment]
also try running awesome in `--no-argb` mode

**Comment by Irubataru** [comment]
It turned out to be an issue with picom ^^

**Comment by vredesbyyrd** [comment]
This should be [fixed](https://github.com/yshui/picom/pull/1344) in picom now.
