### ISSUE TITLE
Does awesomeWM supports _NET_SHOWING_DESKTOP ?

### ISSUE THREAD

**Issue by kurokawachan** [awesomeWM/awesome#3957]
As above, does awesomeWM supports _NET_SHOWING_DESKTOP ?
I looked the code, didn't find any

https://specifications.freedesktop.org/wm-spec/1.3/ar01s03.html#id-1.4.15

**Comment by actionless** [comment]
AFAIK, no

**Comment by kurokawachan** [comment]
Hello @actionless I believe it is a widely used, why not add it? Is it because it have some design issue?

**Comment by actionless** [comment]
because AwesomeWM doesn't have such feature/concept of "Minimizing/Unminimizing all windows at the same time"

**Comment by Aire-One** [comment]
A popular implementation of the "show the desktop" feature with awesome, is to unselecte all the tags. It's straightforward to add a keybinding that calls ` awful.tag.viewnone()`.

**Comment by sclu1034** [comment]
> because AwesomeWM doesn't have such feature/concept of "Minimizing/Unminimizing all windows at the same time"

It might not be implemented as part of the shipped libraries, but you certainly can loop over a list of clients and minimize each one. And while it wouldn't be an atomic operation on a technical level, it should still feel like "at the same time" to the user.

While the hint isn't implemented currently, I don't see anything that would prevent accepting PRs for this.
