### ISSUE TITLE
Wibar gets screwed when layoutbox widget is first on the left

### ISSUE THREAD

**Issue by lmccartneystar** [awesomeWM/awesome#3968]
Output of `awesome --version`:
```
awesome v4.3 (Too long)
 • Compiled against Lua 5.3.6 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
```

**How to reproduce the issue:**

I'm using the default config from /etc/xdg/awesome/rc.lua
1. Change the order of `s.mylayoutbox`  so that it appears left first in wibar, like this:
```
    -- Add widgets to the wibox
    s.mywibox:setup {
        layout = wibox.layout.align.horizontal,
        { -- Left widgets
            layout = wibox.layout.fixed.horizontal,
            s.mylayoutbox, -- <-- THIS LINE
            mylauncher,
            s.mytaglist,
            s.mypromptbox,
        },
        s.mytasklist, -- Middle widget
        { -- Right widgets
            layout = wibox.layout.fixed.horizontal,
            mykeyboardlayout,
            wibox.widget.systray(),
            mytextclock,
        },
    }
```
2. Save the config file with the change.
3. Open at least 2 windows in tag 1.
4. Then restart awesomewm and (IMPORTANT: before doing anything else) change to next layout twice `mod4+space` `mod4+space`.

This error does not occur if after the restart you change focus to a client or view another tag.
If cannot reproduce try opening new windows in tag 1 and then restart and do step 4.

**Actual result:**
A screwed up wibar:
![screenshot_2024-10-16_17-06-21-458](https://github.com/user-attachments/assets/ebf265a3-8065-402d-8e67-642c028bfb2f)

**Expected result:**
A normal wibar:
![screenshot_2024-10-16_17-09-14-004](https://github.com/user-attachments/assets/f890b8c4-5b18-47ed-a7d0-44dc9b081fc3)

**Comment by actionless** [comment]
can you reproduce it with --no-arg awesome flag?

**Comment by lmccartneystar** [comment]
I've noticed that it only happens if I kill the compositor.
I guess I wasn't running one when I submitted the issue.

I'm closing anyway.
