### ISSUE TITLE
I am wondering: "Will wayland support be looked at again now that wayland has matured a bit?"

### ISSUE THREAD

**Issue by Eddieddg1** [awesomeWM/awesome#3969]
It is literally the only thing keeping me on X11/Xorg. I would love to see wayland support for awesome.

**Comment by sclu1034** [comment]
This has nothing to do with maturity. Porting AwesomeWM would be a tremendous amount of work, and so far, no one has shown up willing to do that work.

**Comment by actionless** [comment]
please learn to use search, instead of creating 100th duplicate of the same question
