### ISSUE TITLE
Pango markup gives error when "<" character is used

### ISSUE THREAD

**Issue by ThePinkPanther** [awesomeWM/awesome#397]
when I try using "<" or ">" character in markup I get 

' ' is not a valid charater following a '<' character; it may not begin an element name

here's my code:

```
button_left:set_markup("<span color='" .. beautiful.fg_normal ..  "'> < </span>")
```

I also tried escaping like this: 
\\<
/<

**Comment by Elv13** [comment]
Hello,

The HTML escape for those two are &lt; and &gt; (&.l.t.; without the dots
in case your email client actually escape them). See the pango
documentation for more information.

**Comment by blueyed** [comment]
You can also use `awful.util.escape` to escape it.

Closing as this is not an issue with awesome.

**Comment by ThePinkPanther** [comment]
Thank you! Is this documented somewhere? I couldn't find any info.

**Comment by blueyed** [comment]
@ThePinkPanther 
Not really, as far as I know.

It should get added to the documentation of `wibox.widget.textbox` probably (http://awesomewm.github.io/apidoc/classes/wibox.widget.textbox.html#wibox.widget.textbox:set_text).
Do you feel like creating a PR for it?  Otherwise I'll add it.
