### ISSUE TITLE
Replace maintainers by friendly and helpful people who care for the future of awesome

### ISSUE THREAD

**Issue by kallaballa** [awesomeWM/awesome#3977]
Since I can't express my dear wish of a port to wayland and offer my help otherwise (contrary to high interest in the issue which has been closed) i chose this way. Also while reading through pertaining issues I noticed that maintainers are not afraid to disgruntle their users. So i guess this is the end. X11 will fade and so will awesomewm. Farewell after 16 years of continuous service.

**Comment by kallaballa** [comment]
lol

**Comment by djsigmann** [comment]
I mean, I hate to be that guy, but if someone really wants to make awesomewm work on wayland, they should probably create a fork, and then, assuming that fork works as it should and the codebase is up to standard, it might be merged into this project in the future.

**Comment by kallaballa** [comment]
That was the plan until i read those issues. done before many times. also I siwtched to sway and it is fun.

**Comment by kallaballa** [comment]
I probably was too harsh but i don't understand how wayland -> won't fix is aligning with the future.

**Comment by actionless** [comment]
it's so funny when useless motherlovers can't do the work themselves and DEMANDing others to do it for them for free
