### ISSUE TITLE
[question] How can I paste text into menubar's prompt window?

### ISSUE THREAD

**Issue by jaysonwillson** [awesomeWM/awesome#399]
Is it possible? I have tried Ctrl+V, Ctrl+Shift+V, Shift+Insert (the most common combinations)

**Comment by blueyed** [comment]
`Shift+Insert` works for me and pastes the primary clipboard (mouse selection) (using awesome master).  It might be some custom mapping I have though.

**Comment by jaysonwillson** [comment]
I realized, that I have two "Insert" keys. One of them is on the keypad 
(and it doesn't paste text whether NumLock is enabled or not), and the 
other one works fine with Shift+Insert. Do you have any ideas, how can I 
make ctrl+v work in this case?

**Comment by blueyed** [comment]
Not upfront. Needs digging into the code.
Maybe you can find something yourself this way already? :)

**Comment by jaysonwillson** [comment]
Found nothing in menubar's code. I will try once more. If any results - I will report

**Comment by Elv13** [comment]
Maybe we could merge https://github.com/awesomeWM/awesome/pull/52 and implement this on top of it?

**Comment by blueyed** [comment]
> Maybe we could merge #52 and implement this on top of it?

Good idea.

**Comment by Elv13** [comment]
#52 is merged. It is now possible to implement this from `rc.lua`. While it would still be nice to do it by default, closing this as it is "solved" as of 10 months ago.

**Comment by blueyed** [comment]
@jaysonwillson 
Have you managed to solve this for you?
Are you up for creating a PR to handle it by default?
