### ISSUE TITLE
mod4 + p error bug 

### ISSUE THREAD

**Issue by dannyZhou** [awesomeWM/awesome#414]
when i press "mod4 + p"  it will be wrong (  using origin config file . )

shows that: 

Oops. an error happened!
--------------
/usr/share/awesome/lib/wibox/init.lua:64: bad argument #-1 to '?' (integer expected, got number) 
------------

env: archlinux 

awesome -v display : 
 • Build: Aug 15 2015 09:26:32 for x86_64 by gcc version 5.1.0
 • Compiled against Lua 5.3.1 (running with Lua 5.3)
 • D-Bus support: ✔

if you need some more information you can call me . 

(I'm sorry , my english is poor !!!!!)

**Comment by dannyZhou** [comment]
aha ! i rollback the code to git:a166f86  and the problem is disappear . 

so , the problem are appear in recently version .

**Comment by blueyed** [comment]
This is likely caused by f8ad2cd1.

**Comment by actionless** [comment]
the question, should wibox accept floats? or every widget, like menubar, should convert it to int before attempting to create a wibox?

**Comment by blueyed** [comment]
I think the last time the answer to this was that the callers should apply the rounding - in this case it gets multiplied by 1.5.
