### ISSUE TITLE
wishlist: a fvwm/fvwm2 config --> awesome config auto-conversion tool

### ISSUE THREAD

**Issue by RichardWilliamPearse** [awesomeWM/awesome#417]
so that all of us with detailed, extensive fvwm(2) config files can switch to awesome, with more or less the same functionality.

I/we are just not going to start from scratch again, working & learning towards the same - already fine-tuned in fvwm - functionality.

**Comment by blueyed** [comment]
I don't know fvwm, but I think this won't be trivial?!

**Comment by Elv13** [comment]
Closing this, it's virtually impossible as both are using very advanced config systems. Beside a full interpreter, nothing will work.
