### ISSUE TITLE
[Default rc.lua] Right-click on tasklist (brining up `awful.menu.clients`) is buggy

### ISSUE THREAD

**Issue by d125q** [awesomeWM/awesome#420]
How to reproduce:

1. Open a few clients;
2. Right-click on the tasklist to bring up `awful.menu.clients`;
3. Click on one of the entries to switch to that client;
4. Try to right-click again on the taskbar to bring up another `awful.menu.clients` -- it won't work.

This happens because of the [`instance`](https://github.com/awesomeWM/awesome/blob/master/awesomerc.lua#L153) var in rc.lua. When an entry in the menu is clicked, `menu:exec()` calls `menu:hide()` internally, however, `instance` remains non-nil, causing it to fail the if-condition the next time there is a right-click.

**Comment by blueyed** [comment]
Right-clicking twice works around this.. ;)

The fix would be this:

                     awful.button({ }, 3, function ()
                                              if instance then
                                                  if instance.wibox.visible then
                                                      instance:hide()
                                                  end
                                                  instance = nil
                                              else
                                                  instance = awful.menu.clients({
                                                      theme = { width = 250 }
                                                  })
                                              end
                                          end),

But then it should use a non-global variable here anyway?!

**Comment by everslick** [comment]
also the name of the var should be less generic. I use this code now:

local client_menu_instance = nil
local function client_menu_toggle()
    if client_menu_instance and client_menu_instance.wibox.visible then
        client_menu_instance:hide()
        client_menu_instance = nil
    else
        client_menu_instance = awful.menu.clients({ theme = { width = 240 } })
    end
end

**Comment by blueyed** [comment]
@everslick 
Can you create a PR for that, please?

**Comment by everslick** [comment]
IMHO ALL variables should be local in rc.lua, would you like to heve a PR for that as well? if not, whats the rational behind all variables being global?

**Comment by d125q** [comment]
Seconded. Also, @everslick, perhaps it would be wiser to use a closure instead of what you're using?

```lua
local function client_menu_toggler(theme)
    local instance = nil
    return function ()
        if instance and instance.wibox.visible then
            instance:hide()
            instance = nil
        else
            instance = awful.menu.clients(theme or { theme = { width = 250 } })
        end
    end
end

-- ...

awful.button({ }, 3, client_menu_toggler())
```

**Comment by everslick** [comment]
have you tried this? does not work for me. the inner function is not called.

**Comment by d125q** [comment]
Sure I have and it works just fine. Make sure you have
```lua
awful.button({ }, 3, client_menu_toggler())
```
instead of
```lua
awful.button({ }, 3, client_menu_toggler) -- notice the lack of a function call
```

**Comment by everslick** [comment]
ah, you are right. clever, but easy to overlook! :-) this keeps instance local to the toggle function, so this is indeed the preferred way. to make it more verbose i renamed the function to client_menu_toggle_fn. @blueyed agree?

**Comment by blueyed** [comment]
@everslick 
Yes!
I assume you'll update the PR?
