### ISSUE TITLE
build guide should be improved

### ISSUE THREAD

**Issue by MaxG87** [awesomeWM/awesome#426]
Hi,
I tried to build awesome today which worked finally. Anyway, some things were a bit annoying:

1. No list of dependencies is given. I had to test-install some packages to find out whether they provided what was missing. After doing //mk-build-deps awesome -i// only the packages //libxkbcommon(-x11)?-dev// were missing on Debian/testing.
2. The documentation says that after calling make one has to change the directory and call cmake. That's not correct since make did this for me. Thats great! But not according to the documentation :-)

So maybe one could improve a bit on that documentation. I agree, that this points are minor.

**Comment by blueyed** [comment]
Good points and thanks for bringing it up!

Do you want to create a PR for it?

**Comment by MaxG87** [comment]
I will in the next few days.

**Comment by MaxG87** [comment]
I'm almost done creating a complete list of dependencies. However, I struggle with specifying appropriate Lua packages.

For example, I have to install liblua5.X-dev. I choose liblua5.2-dev, but that won't be the most recent version forever. Unfortunately there is no meta-package. Shall I just use that version or is there a better way?

**Comment by osleg** [comment]
Probably this might help you
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=awesome-git

**Comment by MaxG87** [comment]
I tried so long to find a virgin Debian machine, that I now can't even install VirtualBox due to a very broken repository in Debian/testing. Currently I can't test my new guide. Shall I commit it anyway or wait some weeks until I the repository was fixed?

**Comment by blueyed** [comment]
Yes,  commit and push it for now.

We can then review it already, and you test and potentially amend it later still, before merging.

**Comment by psychon** [comment]
Ping? Any news?
