### ISSUE TITLE
Superfluous mouse event during move block (KiCad)

### ISSUE THREAD

**Issue by Araeos** [awesomeWM/awesome#427]
This may be specific to KiCAD, but the behaviour below does only apply to awesome wm.

# Description
When dragging components in KiCad, the viewport recenters immediately on placing them (see [video](https://www.dropbox.com/s/53ci9u9nnu933ss/kicad-block-move.avi?dl=0))

_Expected behaviour:_ KiCad does not change the viewport or mouse position during the move action, specifically when placing the object using left mouse click.

_Current behaviour:_ KiCad seems to recenter the screen on click before components are acutally placed, places the components on the (now incorrect) position of the mouse and then moves the mouse to the screen's center.
In addition to this movement, this results in an offset `diff` from the expected placement where `diff` is the initial difference of the mouse pointer to the center of the viewport.

When doing the above block movement while holding any modifier key (only during placement, *not* selection) this issue does not manifest itself.

# Analysis
This behavour is a known [issue on launchpad](https://bugs.launchpad.net/kicad/+bug/1480584), but the underlying cause seems to lie in awesome's handling of input events.
Clicking (without modifiers) seems to invoke a mouse movement or mouse leaving event of some sort, at least in the context of dragging the block.
As I am not familiar with wxWidgets/KiCad/awesome internals this is partially speculation.

# Software used
- awesome wm (v3.5.6), default config (rc.lua)
- KiCad product build (2015-08-24 BZR 6119)
- Platform: Arch Linux

**Comment by psychon** [comment]
Could you try removing the mouse binding for the left click from the default config?

     awful.button({ }, 1, function (c) client.focus = c; c:raise() end),

(Note that after this focusing a client becomes harder, so better plan before. The tasklist and titlebars should still work.)

If this really is the problem, then... I don't know.

**Comment by Araeos** [comment]
Yes removing that line fixes the described behaviour in revisions of kicad before 6130.
Revision 6130 introduces a patch that avoids the recentering when the mouse did not leave the viewport.

Interestingly changing the above line to

     awful.button({ }, 1, function (c) end),

did _not_ fix this issue. Only completely removing helps.
This seems very mysterious to me, since I thought the focus or `raise()` call was the issue.

**Comment by psychon** [comment]
Well, awesome will create a grab for the mouse button when you ask it to do so. And when this grab activates, the X11 server will inform KiCAD that it won't be getting all mouse events by telling it via a special kind of leave. Hm...

**Comment by osleg** [comment]
Probably as a hacki-ish workaround it could be reassigned as 
` awful.button({ Shift }, 1, function (c) client.focus = c; c:raise() end), ` (or any other modifier key)
Though that's totally not cool

**Comment by ngg** [comment]
This same issue causes https://bugreports.qt.io/browse/QTBUG-45818 too.
Do you think it can be fixed in Qt?

**Comment by gatispaeglis** [comment]
We fixed this in Qt in the following way: https://codereview.qt-project.org/#/c/147947/

**Comment by psychon** [comment]
Looking at Fluxbox (`src/Window.cc`, `FluxboxWindow::grabButtons()`), we should apparently grab buttons with `GrabModeSync` (awesome uses async right now). Button presses are then "forwarded normally" (`XAllowEvents` in `FluxboxWindow::buttonPressEvent()`; which means all clicks go through the WM first...). I'll take a look.
