### ISSUE TITLE
awesome website: MOPSLinux link leads to porn

### ISSUE THREAD

**Issue by lynix** [awesomeWM/awesome#428]
Just a slight remark concerning the distros linked on the [download page](http://awesome.naquadah.org/download): the link for **MOPSLinux** leads to a page containing porn links, and almost no informative content.

I don't know whether the site has been defaced or it never contained proper content. You might want to think about removing the link ;)

**Comment by osleg** [comment]
For me MOPSLinux linux took me to mopslinux website

**Comment by actionless** [comment]
@osleg:
see the left column

**Comment by osleg** [comment]
Ohwell, I have uBlock installed, no banners for me :)

**Comment by osleg** [comment]
Also I think it would be more correct to notify MOPS admins about this

**Comment by lynix** [comment]
Is this the real MOPSLinux site at all? I dont see any proper content, no links to subpages, no download or release information, nothing. Just a generic text about Linux in general and some chosen distributions.

I dont even see information about the site owner, otherwise I would have tried to contact them first. Wikipedia says the MOPSLinux is discontinued (if I got the russian translation correct), so maybe the real site is just gone?

**Comment by psychon** [comment]
Technically, this should be reported to https://github.com/awesomeWM/awesome-www. ;-)

Distrowatch re-directs for "MOPSLinux" to some other distro and says that one is discontinued, so I agree with this report. Perhaps some domain grabber was intelligent? I don't know, but I'll remove the link.

I can update the awesome-www git repo from here, but I cannot rebuild the website without the correct SSH key, so this will have to wait until tonight.

**Comment by osleg** [comment]
MOPS linux discontinued 5 years ago, the developers of MOPS forked it to https://agilialinux.net/

**Comment by lynix** [comment]
@psychon: I'm sorry, missed that -www repo :)  Thanks for updating!

**Comment by blueyed** [comment]
It seems to have been removed by now.

Thanks for the report and the removal!
