### ISSUE TITLE
Icons break on monitor reconnect

### ISSUE THREAD

**Issue by dasJ** [awesomeWM/awesome#429]
Sometimes, I have to disconnect a monitor, and reconnect it later. I use the command `xrandr --output HDMI-0 --auto --right-of-DVI-I-2` to make X use it.
But, from then on, the icons of awesome (and nothing else) are broken:
![awesome icons](https://cloud.githubusercontent.com/assets/4971975/9543132/9ebe77bc-4d76-11e5-861c-ecdb5dfc17c2.png)
Notification:
![awesome not](https://cloud.githubusercontent.com/assets/4971975/9543154/c9c6f5b0-4d76-11e5-985d-4afabbac4399.png)

I am using arch linux and this awesome version:
```
awesome v3.5.6 (For Those About To Rock)
 • Build: May  5 2015 05:45:29 for x86_64 by gcc version 5.1.0 (builduser@)
 • Compiled against Lua 5.3.0 (running with Lua 5.3)
 • D-Bus support: ✔
```
I believe it's an awesome problem because awesome is the only affected program. Restarting solves the problem but is annoying because all my windows are in the default tag.

**Comment by psychon** [comment]
Ok. This is indeed weird. Since I don't have any good ideas, let's try some bad one:

    echo 'require("gears.surface")("/usr/share/awesome/icons/awesome64.png"):write_to_png("/tmp/awe-out.png")' | awesome-client

This makes awesome load the given PNG and save it again as `/tmp/awe-out.png` (file is overwritten if it already exists). Does the saved PNG also include this problem? (= Is the problem in loading the images or rendering them?)

**Comment by dasJ** [comment]
The icon looks normal:

![awe-out](https://cloud.githubusercontent.com/assets/4971975/9566754/a5d11766-4f11-11e5-948a-19a223c28a4a.png)

**Comment by psychon** [comment]
Hm. And the same happens with `awesome16` instead of `awesome64` (the default theme actually uses the `16` variant)?

Do graph/progressbar widgets work?
Uhm... What about PNG background colors? `mywibox[1]:set_bg({ type="png", file = "/path/to/some/png/file.png" }`?

**Comment by dasJ** [comment]
Um, I have no idea how to change the icon size. Is there anything in the wiki about that?

**Comment by psychon** [comment]
It's just part of the filename.

The default `rc.lua` does `beautiful.init("some-path-that-I-do-not-remeber/theme.lua")`. That file has `theme.awesome_icon = "/usr/local/share/awesome/icons/awesome16.png"`.

So really I was just thinking "does only the `awesome16.png` file break? Perhaps @dasJ should also test with that file". So: `echo 'require("gears.surface")("/usr/share/awesome/icons/awesome16.png"):write_to_png("/tmp/awe-out.png")' | awesome-client`. I still don't have any idea on what might be happening here.

You could also try this: `echo 'require("gears.surface")(mywibox[1].drawin.drawable.surface):write_to_png("/tmp/awe-out.png")' | awesome-client`
This should make a screenshot of the surface based on what awesome "thinks" it is displaying. However, I would be really confused if this wouldn't also contain this kind of drawing corruption.

**Comment by dasJ** [comment]
First test: 
![awe-out](https://cloud.githubusercontent.com/assets/4971975/10392497/e8cb5488-6e87-11e5-96ae-295693386496.png)

Second test:
![awe-out-2](https://cloud.githubusercontent.com/assets/4971975/10392500/ed901134-6e87-11e5-9c2a-0365ff233dae.png)

It looks like these are parts of my Firefox. When I change music, Spotify shows a notification with the cover. Sometimes, these look like parts of websites I have open.

Also, the bugged notification icon always looks different, so when I hear the same song again, the icon looks completely different

**Comment by dasJ** [comment]
Nevermind, it just showed a part of an old notification within my notification icon....

**Comment by psychon** [comment]
Could you test [this patch](https://gist.github.com/psychon/6742ced6b05c2fca264e) and see if it helps? If so, then there is some cairo / X server bug involved.
(The patch does "help" with some issue that I am seeing)

**Comment by Elv13** [comment]
@dasJ Please test @psychon patch. If this is indeed an Awesome bug, we need to know. Otherwise I will close this soon because  "it may be a broken driver issue"

**Comment by dasJ** [comment]
I'd love to, but the bug is not occuring anymore. As I don't know what caused this, I guess we can close it now. Thank you for your help 🙇

**Comment by psychon** [comment]
I guess that this was a bug in the video driver. With `echo 'require("gears.surface")(mywibox[1].drawin.drawable.surface):write_to_png("/tmp/awe-out.png")' | awesome-client` you download "what is actually visible". If something went wrong while drawing the wibox/wibar, well, the video driver must have done something weird.
