### ISSUE TITLE
Opening previously-maximized Evince via D-Bus (SyncView) yields strange results

### ISSUE THREAD

**Issue by d125q** [awesomeWM/awesome#434]
Steps to reproduce:
1. Make sure Evince's "maximized" property is true;
2. Have a TeX-aware editor (such as GNU Emacs with AUCTeX, but it also works with gedit from what I tried) set up to use Evince for forward-searching via D-Bus (org.gnome.evince.Window.SyncView);
3. Perform the forward-search (C-c C-v from within Emacs, or a context menu entry from within gedit). Everything should be OK at this step. However, close Evince, go back to the editor, and perform the forward-search again. You should now get something like this (the layout is set to "floating"): [Screenshot](http://i.imgur.com/ZCw4sTN.png). Notice how Evince still has its "maximized" property set to true, but is not maximized. Resetting the "maximized" property maximizes the window fine.

Please let me know if additional info is needed.  The bug occurs with no `awful.rules` related to Evince whatsoever.

**Comment by d125q** [comment]
This does not happen only when Evince is opened via D-Bus.  It also happens, for example, when opened by double clicking on a downloaded PDF in Firefox's Download window.

**Comment by psychon** [comment]
I didn't feel like installing Emacs. Sorry for neglecting this for so long.

Anyway, I can not reproduce this problem. What's your evince version?

What I did:
- Start `evince a.pdf` and maximize the window
- Start `evince b.pdf`. A new, not-maximized window opens.
- Close all evince windows.
- Start `evince a.pdf`. A new, not-maximized window opens.

Another thing I tried:
- Start `evince a.pdf` and `evince b.pdf`. Maximize, then close the window with `a.pdf`
- Start `evince a.pdf`. A new, not-maximized window opens.

My evince version is 3.18.1 and my awesome version is some-recent-master-build-of-awesome (`v3.5.2-898-g1222b5b-dirty`).

**Comment by d125q** [comment]
@psychon No problem.  The issue is not *that* annoying anyway.  I have not experienced the issue when opening files from the terminal or via something like Nautilus.  Here is, however, a screencast which does not use Emacs: https://www.dropbox.com/s/1lrjrm3mc0zu3oa/out.ogv?dl=0

I'm using the stable awesome from Arch's community repository.
```
awesome v3.5.6 (For Those About To Rock)
 • Build: May  5 2015 05:45:29 for x86_64 by gcc version 5.1.0 (builduser@)
 • Compiled against Lua 5.3.0 (running with Lua 5.3)
 • D-Bus support: ✔
```

**Comment by psychon** [comment]
Thanks for the video.
I did exactly that, but with a master version of awesome and with Chromium. Still, evince didn't start maximized...
I'll ask google how to make Evince remember window sizes.

**Comment by psychon** [comment]
Google tells me Evince remembers its per-document states either in `~/.gnome2/evince` or `~/.local/share/gvfs-metadata`. For my system, the files in there are from 2010, respectively 2014. So might be that gvfs (luckily, I would hate that :-) ) isn't set up so that "things are remembered" on my system.
http://superuser.com/questions/346345/where-does-evince-store-its-per-document-state-position-etc

**Comment by d125q** [comment]
What is interesting to me is that awesome shows it as maximized, but it is, in fact, not (although it acts as such -- I cannot, for example, move the window with the mouse).

**Comment by ff2000** [comment]
On Sat, 07 Nov 2015 03:18:06 -0800, Dario Gjorgjevski <notifications@github.com> wrote:
> What is interesting to me is that awesome shows it as maximized, but it is, in fact, not (although it acts as such -- I cannot, for example, move the window with the mouse).
Gnome is quite special. The Header Bar is a Client Side Decoration and
manages the window. Probably Uli has a different Gtk version? Are you (Uli)
using evince built against Gtk3 or Gtk2? If Gtk3 which exact version? I
know CSD was forced on users either with 3.6 or 3.8.
If evince thinks it is maximized it of course won't let the user move
the window ;) Probably this really is an issue with Gtk/evince?
It also might be an issue with special gtk settings/user-css.

(Just random thoughts, sry if it leads into the wrong direction...)

**Comment by psychon** [comment]
@d125q Can you click at the window below evince while it is maximized? I think that the evince window really is maximized, but evince only draws the "top-right" part of it, so the rest of the window contains what was visible there before. This means in your case that you can see a "screenshot" of firefox in evince's window.

@ff2000 
```
$ LC_ALL=C evince --version                        
GNOME Document Viewer 3.18.1
$ ldd /usr/bin/evince| grep gtk           
	libgtk-3.so.0 => /usr/lib/x86_64-linux-gnu/libgtk-3.so.0 (0x00007f0c8bcb5000)
$ apt-cache show libgtk-3-0 | grep Version
Version: 3.18.2-1
```

**Comment by d125q** [comment]
@psychon Yes, I can click on the window (Firefox in this case).  The focus will be switched over to it as expected.

**Comment by psychon** [comment]
Oh, ok. So evince really has this small size. Then somehow `awful.ewmh` failed to give it a maximized size properly....

@d125q Could you test if this also happens with the default config?

**Comment by d125q** [comment]
@psychon It does happen with the default config, too; yes.

**Comment by Elv13** [comment]
In case this still happens, there is now an API to catch and block such weirdness (`request::geometry`). Closing this as addressed and it is a) not an awesome issue and b) we have a solution
