### ISSUE TITLE
a menu.clients() menu should emit a signal, or call a function, when it is closed by the keygrabber

### ISSUE THREAD

**Issue by everslick** [awesomeWM/awesome#447]
otherwise there is no way to set instance to nil, when the keygrabber closes the menu in the default rc.lua config.

Test:
right click on tasklist -> clients menu opens
press ESC -> menu closes
right click on tasklist -> nothing
right click on tasklist again -> clients list opens

**Comment by blueyed** [comment]
Seems to be a duplicate of #420.
