### ISSUE TITLE
Floating layout - bug when moving client

### ISSUE THREAD

**Issue by Mathiasb17** [awesomeWM/awesome#456]
When i open a client (a terminal for example) and then move it with Windows Key + left click : the window is badly resized for each mouse movement. I then resize it with Windows Key + right click, and moving the client works fine.

**Comment by psychon** [comment]
Which awesome version? What does "badly resize" mean? Which terminal?

You are saying: "I'm just trying to move the terminal, but it is also resized", right?
What does "I then resize it [...] and moving the client works fine" mean exactly? How are you moving a client by resizing it?

**Comment by ciechomke** [comment]
It also occurs me so I can describe this bug (I use Terminator as a terminal emulator). So when you use desktop floating mode when I spawn terminal and want to move it by mod4 + LMB it resizes (much faster than in normal resize by mod4 + RMB) to a small bar (you can see this in the picture below). 

![00 44 50-2015-10-07_920x887_scrotum](https://cloud.githubusercontent.com/assets/10449580/10324813/e1d202c8-6c8c-11e5-87b7-b7f38e938f90.png)

It does not matter in which way you move mouse - terminal window is always going down. Bug does not appear when you want to resize window first (before moving).  Bug also does not appear in tilling mode when you toggle floating mode only for terminal window.

**Comment by blueyed** [comment]
Which awesome version?

**Comment by ciechomke** [comment]
Awesome version 3.5.6-2 from Archlinux repo.

**Comment by Mathiasb17** [comment]
Hello, sorry for the very late answer. I'm working on the version 3.4.15 from ubuntu repo. here is a short video of the issue if it can help to understand : https://youtu.be/-4mObzDfhgY

**Comment by blueyed** [comment]
@Mathiasb17 
> version 3.4.15

That's not supported any more since a while.

@ciechomke 
Is the issue the same for you as in the video? (I have not looked at it yet)

**Comment by blueyed** [comment]
#499 might be related?!

**Comment by ciechomke** [comment]
@blueyed Yes it is exactly same for me.

**Comment by psychon** [comment]
Sorry, but could some try with latest the latest git master version? I can't find it right now, but I think we fixed some bug like this some time ago.

**Comment by ciechomke** [comment]
Maybe somebody using git version will confirm this? Anyway, can somebody resposinble for arch package update it? I mean awesome package, not awesome-git.

**Comment by blueyed** [comment]
@ciechomke 
> can somebody resposinble for arch package update it?

Should be the latest release, no?
If a patch should get added, we first need to know what's causing it (git-bisect), and preferably have a release with the fix included.

> awesome-git

Can you try it with awesome-git yourself?

FWIW, I can reproduce it also in Git:
1. floating layout
2. open gnome-terminal
3. move it using mod-left-click

It does not happen with urxvt.

**Comment by blueyed** [comment]
FWIW, it would be awesome to have a test for this in `tests/`.

It happens with gnome-terminal and terminator for me, but not urxvt, xterm or lilyterm.

**Comment by blueyed** [comment]
@psychon 
#499 has some information, which might be relevant here.

**Comment by psychon** [comment]
I found the commit that I thought should fix this (but looking at the diff again, I don't really get it): commit 2d3103345e3a266eaf1d5261ef37e36ac5498ec

**Comment by ciechomke** [comment]
>It happens with gnome-terminal and terminator for me, but not urxvt, xterm or lilyterm.
@blueyed I can confirm this, bug does not occur when I use uxrvt.

**Comment by psychon** [comment]
https://awesome.naquadah.org/bugs/index.php?do=details&task_id=1022
https://awesome.naquadah.org/bugs/index.php?do=details&task_id=1137
https://awesome.naquadah.org/bugs/index.php?do=details&task_id=1165
Meh...

**Comment by psychon** [comment]
Ok, I spent enough time looking into this again. gnome-terminal is still violating ICCCM.
Simple patch to `event.c`:
```diff
diff --git a/event.c b/event.c
index eab45e3..6ba2f3b 100644
--- a/event.c
+++ b/event.c
@@ -376,7 +376,7 @@ event_handle_configurerequest(xcb_configure_request_event_t *ev)
                 geometry.y += diff_y;
         }
 
-        if(!client_resize(c, geometry, false))
+        if(!client_resize(c, geometry, c->size_hints_honor))
             /* ICCCM 4.1.5 / 4.2.3, if nothing was changed, send an event saying so */
             client_send_configure(c);
     }
```
With this, awesome applies size hints to the size that a client requests for itself. With this change, gnome-terminal now shrinks by itself when it is opened immediately (= without being moved).

Some debug output suggests that we have a different understanding of the size hints and gnome-terminal even asks for a size that is smaller than its minimal size. If that's not broken, then I do not know what is broken. And no, I do not know why this works elsewhere.

Size hints:
```
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified minimum size: 307 by 63
		program specified resize increment: 7 by 13
		program specified base size: 17 by 21
		window gravity: NorthWest
```
Some debug output (this is the end of it, the resizing took a lot longer to finish):
```
W: awesome: event_handle_configurerequest:379: themselves: 0x20 size 577x112 (original 577x112) for Terminal
W: awesome: client_apply_size_hints:726: before size hints: 573x108
W: awesome: client_apply_size_hints:815: after size hints: 573x102
W: awesome: client_resize_do:830: us: 0x20 size 577x106 for Terminal
W: awesome: event_handle_configurerequest:379: themselves: 0x20 size 577x99 (original 577x99) for Terminal
W: awesome: client_apply_size_hints:726: before size hints: 573x95
W: awesome: client_apply_size_hints:815: after size hints: 573x89
W: awesome: client_resize_do:830: us: 0x20 size 577x93 for Terminal
W: awesome: event_handle_configurerequest:379: themselves: 0x20 size 577x86 (original 577x86) for Terminal
W: awesome: client_apply_size_hints:726: before size hints: 573x82
W: awesome: client_apply_size_hints:815: after size hints: 573x76
W: awesome: client_resize_do:830: us: 0x20 size 577x80 for Terminal
W: awesome: event_handle_configurerequest:379: themselves: 0x20 size 577x73 (original 577x73) for Terminal
W: awesome: client_apply_size_hints:726: before size hints: 573x69
W: awesome: client_apply_size_hints:815: after size hints: 573x63
W: awesome: client_resize_do:830: us: 0x20 size 577x67 for Terminal
W: awesome: event_handle_configurerequest:379: themselves: 0x20 size 577x60 (original 577x60) for Terminal
W: awesome: client_apply_size_hints:726: before size hints: 573x56
W: awesome: client_apply_size_hints:815: after size hints: 573x63
```
The configurerequest is the size that the window asks for itself and it can be seen that it asks for a height of 60 which is below its minimum height of 63. So this is gnome-terminal resizing itself...

**Comment by psychon** [comment]
Oh and since this is apparently not mentioned enough: Use `size_hints_honor = false` so that we ignore gnome-terminal's size hints.

**Comment by nuko8** [comment]
Comparing every `original` size with the corresponding`before size hint` size, there's always a dimensional reduction of 4 pixels in both width and height.

It looks as if either gnome-terminal or awesome forgot to count border widths to calculate the net width and height of a window...

**Comment by psychon** [comment]
@nuko8 The bug also occurs without titlebars and with `border_width = 0`

**Comment by psychon** [comment]
Anyone wants to confirm that PR #510 fixes this?

**Comment by blueyed** [comment]
> Anyone wants to confirm that PR #510 fixes this?

Fixes it for gnome-terminal for me.
