### ISSUE TITLE
GTK3 background black with theme elementary

### ISSUE THREAD

**Issue by salorium** [awesomeWM/awesome#459]
Gthumb with theme elementary : 
![17-09-2015 15 43 25](https://cloud.githubusercontent.com/assets/1009923/9934684/256cdc90-5d53-11e5-8555-738b8457e232.png)
Background => black :-1: 

Gthumb with theme Raleigh : 
![17-09-2015 15 43 46](https://cloud.githubusercontent.com/assets/1009923/9934734/68189bce-5d53-11e5-8c6a-c427a8f9d2f1.png)
No background :+1:

**Comment by psychon** [comment]
And why isn't this GTK's / the theme's fault, but awesome's? I'd say this is what GTK is drawing, so its fault.

**Comment by actionless** [comment]
that's something about alpha channel

try running awesome with `--no-argb` and/or starting `compton`

**Comment by svexican** [comment]
I can confirm this is a GTK theme + composition thing. There are 2 options I can think of:

a) In your GTK3 theme:

```css
.window-frame {
  box-shadow: none;
  border: none;
  padding: 0;
  margin: 0;
}
```

b) Run compton/xcompmgr as mentioned above.

NEXT!

**Comment by unihernandez22** [comment]
![image](https://user-images.githubusercontent.com/62044675/91682451-0139b600-eb28-11ea-89cf-9407d41d2055.png)

I have this error but with a compositor running, so the borders are separated of the window because of the shadow.

> ```css
> .window-frame {
>   box-shadow: none;
>   border: none;
>   padding: 0;
>   margin: 0;
> }
> ```

And that didn't solve it.

**Comment by unihernandez22** [comment]
![31-Aug-2020_01-39-19](https://user-images.githubusercontent.com/62044675/91683455-13692380-eb2b-11ea-9d94-0e7a689daaf6.png)

This is with `border_width = 0`
