### ISSUE TITLE
Widgets update delayed / extends to a wrong side

### ISSUE THREAD

**Issue by osleg** [awesomeWM/awesome#460]
Using mpdwidget from Lain
On song change, if the name of the song longer or shorter than previous the widget is not resizing instantly but rather it takes some random time before resize. It might be couple of seconds or couple of minutes. I didn't find yet a direct correlation on resize times.
```
awesome v3.5.2-750-g5e4318c (The Fox)
 • Build: Sep 14 2015 23:03:06 for x86_64 by gcc version 5.2.0 (alex@v3)
 • Compiled against Lua 5.3.1 (running with Lua 5.3)
 • D-Bus support: ✔
```

**Comment by psychon** [comment]
If you want me to guess: The resize happens on the next redraw (e.g. when the textclock updates or you switch tags etc). Could this be?

Could you also test if this change fixes your problem: https://github.com/psychon/awesome/commit/ca1ce606a925b3d64f1326d08c02e6139c8ec68d
You can just edit `wibox/widget/base.lua` by hand to apply this change and try it out.

**Comment by osleg** [comment]
It's seems that you are right about this.
I've tried to change the base.lua as you proposed, it indeed refreshing the layout much faster now, but it still not as fast as it was before

**Comment by psychon** [comment]
The code in this area stabilized and "lots of things" changed. Does this still happen with current master?

Also, what does "much faster now" mean exactly? 9 seconds instead of 10 of more like 0.1 seconds vs 0.7 seconds?

**Comment by osleg** [comment]
it's something like second or 2 before it getting updated vs update happening only on clock update. While previously, before the "lots of things" it was under a second

**Comment by psychon** [comment]
Hm... Is your awesome config only somewhere? Does it already include lain/mpdwidget or do I need more to set this up for testing?

**Comment by psychon** [comment]
Reporter vanished. Closing.
