### ISSUE TITLE
Unminimize clients in awful.client.jumpto?

### ISSUE THREAD

**Issue by blueyed** [awesomeWM/awesome#472]
Should minimized clients be un-minimized automatically?

**Comment by psychon** [comment]
That would make sense, yeah.

**Comment by osleg** [comment]
Yes please!

**Comment by blueyed** [comment]
It works better than expected with the default config already.. :D

(as per `require("awful").client.jumpto(client.get()[8])`, where that client is minimized)

It was my implementation of the `request::activate` handler which did not handle it.

`client.jumpto` uses `c:emit_signal("request::activate", "client.jumpto", {raise=true})`.

I've looked back at #438, and it addresses this issue, too.  I've fixed #438 to not make clients urgent during restart.

**Comment by blueyed** [comment]
Closing this for now, since #438 has been merged.

**Comment by blueyed** [comment]
I think that was not fixed properly - at least `c:raise()` does not un-minimize them for me.

**Comment by psychon** [comment]
I don't see why `c:raise()` should un-minimize anything. Some X11 requests cause clients to be unminimized/minimized, focusing a window unminimizes it and settings its `.minimized` properties. Nothing else changes the minimized status.
