### ISSUE TITLE
Pause redraw when resizing VirtualBox window

### ISSUE THREAD

**Issue by gto76** [awesomeWM/awesome#473]
Hi.
I mostly run Awesome inside VirtualBox, and when I start resizing the VirtualBox window Awesome starts restarting/redrawing frantically...

It would be nice if it waited until the resize was over (my uninformed guess would be that adding a few milliseconds of delay on startup/redraw would do, but then again, maybe I'm misunderestimating the whole Xwindow/Gnome/systemd horror :).

ps:
Great project!

**Comment by psychon** [comment]
Quick idea: Set an environment variable with the current time during exit and wait on restarts if the last restart was "too close":
```lua
awesome.connect_signal("exit", function(restart)
    if not restart then return end
    local var = "LAST_AWESOME_RESTART"
    local last_restart = os.getenv(var)
    if last_restart and tonumber(last_restart) + 5 >= os.time() then
        io.popen("sleep 1"):read("*a")
    end
    require("lgi").GLib.setenv(var, tostring(os.time())
end)
```
No idea what a more general approach would be. Normally the X server doesn't randomly resize the root window for a while.

@gto76: You could just add the above to your rc.lua. It should wait for one second during shutdown whenever the last restart was at most five seconds away. As always, this is completely untested. :-)

**Comment by gto76** [comment]
Thanks,

It works a bit better with the simple delay, although the windows are still frantically resizing, what is delayed is a redraw of a taskbar.

As for the longer solution, there should be a closing bracket before the last end. And it passes the awesome -k test, but Awesome doesn't start.

Anyways the real problem is that sometimes after the resize Awesome is left in state like this:

![awesome-on-resize](https://cloud.githubusercontent.com/assets/1396046/10080324/5f2bcd50-62ef-11e5-8333-56abf2b139c5.png)

And sometimes when resizing it changes the size of the VirtualBox window byitself to some seemingly random size.

The delay makes this two isues appear less frequently, but they still appear sometimes.

**Comment by cydergoth** [comment]
I've also noticed that sometimes under VBox my background isn't drawn correctly after a re-size, it looks like the clip region is still set to the old size. Possibly connected with this issue?

**Comment by Elv13** [comment]
Awesome no longer restarts and resize, so this should be fixed (untested).
