### ISSUE TITLE
Remember mouse position per screen

### ISSUE THREAD

**Issue by blueyed** [awesomeWM/awesome#478]
The (relative) screen position of the mouse on a screen should be remembered and restored when moving the focus to another screen.

Could be done for the following functions first / only / in the beginning:

    awful.key({ modkey, "Control" }, "j", function () awful.screen.focus_relative( 1) end),
    awful.key({ modkey, "Control" }, "k", function () awful.screen.focus_relative(-1) end),

**Comment by Bew78LesellB** [comment]
Hey,
I'd like to do this enhancement, but I don't know how do you usually store extra data..
I have two options : 
**Add a field to each screen objects**
```lua
-- Save mouse position
currentScreen.mousePos = capi.mouse.coords()

-- then later : Restore mouse position
capi.mouse.coords(currentScreen.mousePos, true)
```
or **using an external table**
```lua
local screenMousePos = {}

-- Save mouse position
screenMousePos[currentScreen] = capi.mouse.coords()

-- then later : Restore mouse position
capi.mouse.coords(screenMousePos[currentScreen], true)
```

which one should I use ?

**Comment by blueyed** [comment]
It should be a new table in awful.screen, e.g. mouse_per_screen. It could be made public.
