### ISSUE TITLE
doc: syntax highlighting for code blocks

### ISSUE THREAD

**Issue by blueyed** [awesomeWM/awesome#481]
@Elv13 had the idea of including a JS library like https://craig.is/making/rainbows or https://highlightjs.org/ to apply syntax highlighting for the Lua `<code>` blocks in the documentation.

highlight.js is served from a CDN, but Lua is not in its list of common used languages, and therefore not included in that version.  See https://highlightjs.org/download/.

**Comment by psychon** [comment]
Linking to a CDN might not be popular since they could (in theory) track you. I think something like that counts as a bug for debian, but I don't remember its severity.

Besides that, syntax highlighting is fine with me.

**Comment by blueyed** [comment]
Then we should probably include a stripped down version with a single theme and limited language support (anything besides Lua?) in the repo.

**Comment by actionless** [comment]
yes, also using cdn will be unusable for offline scenario

**Comment by blueyed** [comment]
Lua code is already being highlighted: http://awesomewm.github.io/apidoc/libraries/awful.keygrabber.html#run

Closing it for now.
