### ISSUE TITLE
regression: VirtualBox intercepts WM hotkeys

### ISSUE THREAD

**Issue by Hi-Angel** [awesomeWM/awesome#496]
For a virtual machine of Virtual Box is running, AwesomeWM doesn't respond until one would press a combination of VB to release keyboard *(i.e. <kdb>Right Ctrl</kbd> by default)*.

The awesome-v3.4.15 didn't allow VB to intercept its keys.

I tried to do a git-bisect to find the problem commit. I reduced the scope to the [commit which worked](https://github.com/awesomeWM/awesome/commit/e653b0a65290f854f8de60f76681b6a4ac0d06cb) and [the one that didn't](https://github.com/awesomeWM/awesome/commit/3a25e7822440e0873dcb9bd2238961da2ba06428) *([the both commits are on the page 8 atm](https://github.com/awesomeWM/awesome/commits/3.5?page=8))*. But then something weird happened, I couldn't reproduce it anymore. Anyway, I hope this help.

**Comment by psychon** [comment]
Sorry, but could it be that something went wrong in your bisect? Neither of those two commits touches any input stuff and the last good commit is just awesome v3.5.0.

I would guess that 102063dbbdfb0bc9f43268d98f7dcb5269547395 introduced this problem (just because it's the "only big change" that I can think of). However, I don't know how VirtualBox grabs its keys nor why their grabbing wouldn't work on a non-reparenting WM.

Hm, looking at that code, the change in `client.c`, function `luaA_client_keys` could also cause this. Could you try reverting the following change (this should be easily revertible on any awesome version since 3.5.0 and shouldn't really have any bad effects if reverted):
```diff
@@ -1651,8 +1685,8 @@ luaA_client_keys(lua_State *L)
     {
         luaA_key_array_set(L, 1, 2, keys);
         luaA_object_emit_signal(L, 1, "property::keys", 0);
-        xcb_ungrab_key(globalconf.connection, XCB_GRAB_ANY, c->window, XCB_BUTTON_MASK_ANY);
-        xwindow_grabkeys(c->window, keys);
+        xcb_ungrab_key(globalconf.connection, XCB_GRAB_ANY, c->frame_window, XCB_BUTTON_MASK_ANY);
+        xwindow_grabkeys(c->frame_window, keys);
     }
 
     return luaA_key_array_get(L, 1, keys);

```

**Comment by Hi-Angel** [comment]
Yay, wow, that worked for me! I.e. when I am replace in the two lines the `c->frame_window` → `c->window`, the VirtualBox no more can intercept WM keys.

I'm wondering, what is the difference between frame_window and window?

**Comment by psychon** [comment]
`window` is the window created by VirtualBox while `frame_window` is a window created by awesome and where it draws the window decoration. Awesome makes `window` a child of `frame_window`.

I guess when the input focus is on the virtual box window, then virtual box grabs all window on its own window and thus no input "goes to the parent window" (note that in X11 input events go up the window hierarchy until something wants them). When awesome directly grabs input on VirtualBox' window, then both get the event? I'm not sure.

No idea if there are any bad effects from reverting that part of the patch and neither do I know why I did it like this.

**Comment by Hi-Angel** [comment]
Well, I encourage additionally to test it someone else. Because as I mentioned at the first post for I was trying to find a problem commit, at some point I met a strange behavior. It was that after I revert my local copy to a previous version of code, which worked — it suddenly stops working. And vice versa: a broken commit at some point start working again. I guess perhaps `make distclean` didn't remove something… I don't know.

So to be sure it would be better if anyone else would test it too.

**Comment by Hi-Angel** [comment]
I've got an idea to solve your doubts: why not make that part of code optional? I.e. add some config that enables or disables the feature.

**Comment by psychon** [comment]
Found some other thing that needs to be done (and I wondered for days why my key binding for `awful.client.floating.toggle` didn't work...) and pushed the result as 532ec0cd9015d3d279f208af37ead1d635e30802.

**Comment by Hi-Angel** [comment]
Awesome! ☺
