### ISSUE TITLE
Window positioning w.r.t. border-width using XMoveWindow / XConfigureWindow

### ISSUE THREAD

**Issue by keigen-shu** [awesomeWM/awesome#499]
I am currently implementing window manipulation functions for a library when I found out that awesome behaves differently than Xfwm and KWin when moving  windows.

Currently, awesome moves windows such that the parent is placed at root coord: (X - border width, Y - border width) while the client is placed at root coord: (X, Y). Both Xfwm and KWin will place the parent window at (X, Y) and the client window somewhere south-east of that. (values obtained from `xwininfo`)

Just to be sure that this isn't some weird X madness, I checked the Xlib and ICCCM manuals: the X and Y positions supplied to these functions is supposed to *define the new location of the top-left pixel of the window's border or the window itself if it has no border* (`XMoveWindow`); be *relative to the parent's origin and indicate the position of the upper-left outer corner of the window* (`XConfigureWindow`) and be the *(root) [x,y] location of the window's upper left-outer corner* (ICCCM section 4.1.5).

**Comment by psychon** [comment]
What window gravity does your window have (output of `xprop WM_NORMAL_HINTS`)?

Does anyone want to write a test program for testing that we handle all the gravities correctly? Apparently we do not...

**Comment by psychon** [comment]
Could you test if PR #505 fixes your issue?

**Comment by keigen-shu** [comment]
> Could you test if PR #505 fixes your issue?

```
awesome v3.5.2-811-gb2aaefd-dirty (The Fox)
 • Build: Oct 11 2015 02:36:01 for x86_64 by gcc version 5.2.0 (root@cinder)
 • Compiled against Lua 5.3.1 (running with Lua 5.3)
```

It still behaves the same as before: placing parent window on the supplied position instead of the client window. I am using NorthWestGravity (`xprop` prints NorthWest). Here is the code I used; it's simply creates, maps and then moves a window: https://gist.github.com/keigen-shu/7663dacb2449fd910e6d

I found this note at the bottom of `xwininfo` manual when searching for the geometry string formatting:
> The -geometry string (which I've been using) displayed must make assumptions about the window's border width and the behavior of the application and the window manager. As a result, the location given is not always correct.

Looking at [http://www.opensource.apple.com/source/X11apps/X11apps-13/xwininfo/xwininfo-X11R7.1-1.0.2/xwininfo.c](xwininfo.c), `Display_Stats_Info()` appears doing calculations using border-width before presenting the value. I'm not familiar enough with the specifics to comment on this at the moment.

Will investigate the situation further tomorrow.

**Comment by keigen-shu** [comment]
Ignore my last comment. *The build with PR #505 has fixed the issue*. Using my gist, the client window is now moved to the position suppled to XMoveWindow, which is the correct (same as Xfwm and Kwin) behaviour. I got to the wrong conclusion yesterday because I launched the wrong version of awesome.

Thanks.  :smile:
