### ISSUE TITLE
two taglist on two screen behavior differently

### ISSUE THREAD

**Issue by guotsuan** [awesomeWM/awesome#500]
I use two screens with awesome WM. I found that the taglist widgets behaviour differently even with default rc.lua shipped with the awesomeWM.

With default rc.lua, on screen A, when I press the number or click on the tag list to viewonly a empty tag, it is normal. You will see the tag is selected because the color of number on taglist widget is inverted. You can create new client and the new client  will be tags with this empty tag.

But on screen B,  when I press the number or click on the tag list to viewonly a empty tag, nothing happy apparently.  The color of number on taglist is unchanged just like it was not selected. However it is actually selected, because once you create a client, you will see the color of number on taglist is inverted.  Then it will behaviour normally as long as there are clients attached to this tag. 

It looks two taglists are handled by different functions. 

I try to dig a little more and found that in awful/widget/taglist.lua 

```lua
   tag.attached_connect_signal(screen, "property::selected", ut)
```
If I understand correctly. every time the tag was selected with emitting signals "property:selected",
awesome will call function ut() which is:
```lua
        local function u(s)
            local i = instances[s]
            if i then
                for _, tlist in pairs(i) do
                    tlist._do_taglist_update()
                end
            end
        end
        local uc = function (c) return u(c.screen) end
        local ut = function (t) return u(tag.getscreen(t)) end
```
I then change ut() to 
```
function (t) gears.debug.dump('being called') return u(tag.getscreen(t)) end
```
I found it is indeed for taglist on screen A (behaviour normally), I can see out the output, ut() was called  every time that I selected the empty tag. But for taglist on Screen B (behaviour differently) the ut() function was never called, even you select non-empty tags. 

From default rc.lua. I thing these two taglist should not be different.
```
for s = 1, screen.count() do
    -- Create a promptbox for each screen
    mypromptbox[s] = awful.widget.prompt()
    -- Create an imagebox widget which will contains an icon indicating which layout we're using.
    -- We need one layoutbox per screen.
    mylayoutbox[s] = awful.widget.layoutbox(s)
    mylayoutbox[s]:buttons(awful.util.table.join(
                           awful.button({ }, 1, function () awful.layout.inc( 1) end),
                           awful.button({ }, 3, function () awful.layout.inc(-1) end),
                           awful.button({ }, 4, function () awful.layout.inc( 1) end),
                           awful.button({ }, 5, function () awful.layout.inc(-1) end)))
    -- Create a taglist widget
    mytaglist[s] = awful.widget.taglist(s, awful.widget.taglist.filter.all, mytaglist.buttons)

    -- Create a tasklist widget
    mytasklist[s] = awful.widget.tasklist(s, awful.widget.tasklist.filter.currenttags, mytasklist.buttons)

    -- Create the wibox
    mywibox[s] = awful.wibox({ position = "top", screen = s })

    -- Widgets that are aligned to the left
    local left_layout = wibox.layout.fixed.horizontal()
    left_layout:add(mylauncher)
    left_layout:add(mytaglist[s])
    left_layout:add(mypromptbox[s])

    -- Widgets that are aligned to the right
    local right_layout = wibox.layout.fixed.horizontal()
    right_layout:add(mykeyboardlayout)

    if s == 1 then right_layout:add(wibox.widget.systray()) end
    right_layout:add(mytextclock)
    right_layout:add(mylayoutbox[s])

    -- Now bring it all together (with the tasklist in the middle)
    local layout = wibox.layout.align.horizontal()
    layout:set_left(left_layout)
    layout:set_middle(mytasklist[s])
    layout:set_right(right_layout)

    mywibox[s]:set_widget(layout)
end
```

I'm wondering if anyone else encounter the same problem? Is it a bug? 
Thank you very much.

------------------------------------------
awesome v3.5.2-804-gee0e9ba (The Fox)
 • Build: Oct  7 2015 21:29:35 for x86_64 by gcc version 5.2.0 (dccf87@gqlinux)
 • Compiled against Lua 5.3.1 (running with Lua 5.3)
 • D-Bus support: ✔

**Comment by guotsuan** [comment]
And I tested also in awsomeWM 3.5.6 with the default rc.lua. There is no such problem. uc() was called when the tag was selected in either of taglist.

**Comment by blueyed** [comment]
Can you check if 40db0b7337359118e53ac3e3f8b8ec65dc3f24e3 broke it?

**Comment by guotsuan** [comment]
I just checked, 40db0b7 still broke it, but 6f2e7bb works correctly. So I guess the changes in 40db0b7 introduce the problem.

**Comment by blueyed** [comment]
Thanks for checking it, let's see what @psychon can say about it.

This part looks suspicious: https://github.com/awesomeWM/awesome/commit/40db0b7337359118e53ac3e3f8b8ec65dc3f24e3#diff-a7e081289e823fb261b0bc34e9cdc749R166.

**Comment by psychon** [comment]
Problem exists between my keyboard and my chair. The calls to `tag.attached_connect_signal` should pass `nil` as the first argument (call this function for all screens) instead of `screen` (only for this screen). After all, this is used for updating all taglists and then the taglist callback checks if the tag is on the right screen.

@guotsuan I can't provide a patch right now, but could you if replacing all `tag.attached_connect_signal(screen,` in `taglist.lua` with `tag.attached_connect_signal(nil,` helps?

**Comment by guotsuan** [comment]
Hi @psychon . Thanks for the suggestions. I just tested the modification you suggested. It works. 
After I change all tag.attached_connect_signal(screen to tag.attached_connect_signal(nil, 
The two taglists works normal now.
