### ISSUE TITLE
Add an optional filter to `awful.menu.clients`

### ISSUE THREAD

**Issue by d125q** [awesomeWM/awesome#504]
What does everyone think about adding a filter function as an optional argument to [`awful.menu.clients`](https://github.com/awesomeWM/awesome/blob/master/lib/awful/menu.lua#L471)?  I would find the ability to have it display, say, only visible clients, quite useful.

**Comment by psychon** [comment]
It could use `awful.client.iterate` internally and let caller provide the arguments. That seems like a good idea.

**Comment by d125q** [comment]
You are indeed correct about `awful.client.iterate` -- but I suppose it would have to be modified to make the filter optional. Well, it would be best if [`util.table.iterate`](https://github.com/awesomeWM/awesome/blob/master/lib/awful/util.lua#L584) was changed.

**Comment by psychon** [comment]
We can just use `for c in client.filter(filter or function() return true end, start, s)`, so if no filter is specified, we just use an always-true filter.

**Comment by d125q** [comment]
Of course; you are correct.  The only thing left to determine now is whether it's wise to begin iterating from the focused client, like `awful.client.iterate` by default does.

**Comment by blueyed** [comment]
@d125q 
Do you feel like creating a PR for this?

**Comment by d125q** [comment]
@blueyed: Yes; I will make one during the next few days.
