### ISSUE TITLE
urxvt moves when its font is changed

### ISSUE THREAD

**Issue by psychon** [awesomeWM/awesome#532]
Left-over from https://github.com/awesomeWM/awesome/issues/236 (but I guess @blueyed found this issue elsewhere long ago, I just don't know where).

Running the following makes urxvt move down-right:

     printf '\033]710;xft:monospace:size=10\033\'

Edit: I meant "multiple times". The first call changes the font and resizes the window and the next time, the window merely moves (at least for me)

**Comment by actionless** [comment]
strange but i can't reproduce it

**Comment by psychon** [comment]
Happens for me with my own config and with the default config.

    $ urxvt -h
    rxvt-unicode (urxvt) v9.21 - released: 2014-12-31
    options: perl,xft,styles,combining,blink,iso14755,unicode3,encodings=eu+vn+jp+jp-ext+kr+zh+zh-ext,fade,transparent,tint,pixbuf,XIM,frills,selectionscrolling,wheel,slipwheel,smart-resize,cursorBlink,pointerBlank,scrollbars=plain+rxvt+NeXT+xterm

(Debian testing, amd64)

**Comment by nuko8** [comment]
That might be relevant to, or better looked into in conjunction with the compile option:
```
--enable-smart-resize (default: off)
Add smart growth/shrink behaviour when resizing. This should keep the window corner which is closest to a corner of the screen in a fixed position.
```
Actually, I can't reproduce the right-down move with urxvt-9.20 that was seemingly compiled without that particular option (I installed it via a package manager and thus I'm not sure what options it was built with, other than the info `urxvt -h` tells me about).

So, if you've already set
```
URxvt*smartresize: false
```
or haven't done nothing with it by yourself, then forget my comment :-)

**Comment by actionless** [comment]
ah, yes, it's resizing, but its top-left corner stays still

isn't that an expected behavior?

**Comment by nuko8** [comment]
Looks it's quite similar to what happened to me with my urxvt.

In my case, the top-left corner remains unchanged while the window height increases.

I feel something uneasy about that because I can't understand why that resize happens while the monospace font in use doesn't change.

**Comment by blueyed** [comment]
It seems related to the border size?!

At least that's what happening for me: first it gets resized altogether, and then moves down/right by one pixel.

When I increase the border_width of the floating client, it moves more according to that.

**Comment by psychon** [comment]
The bug is in urxvt. Awesome uses a non-zero border-width on its windows and the urxvt code doesn't take this into account. Patch:
```diff
diff --git a/src/main.C b/src/main.C
index 4b8b62d..b2dc3a5 100644
--- a/src/main.C
+++ b/src/main.C
@@ -1082,23 +1082,30 @@ rxvt_term::resize_all_windows (unsigned int newwidth, unsigned int newheight, in
        * resize by Marius Gedminas <marius.gedminas@uosis.mif.vu.lt>
        * reposition window on resize depending on placement on screen
        */
-      int x, y, x1, y1;
+      int x, y, x1, y1, unused_x, unused_y;
       int dx, dy;
       unsigned int unused_w1, unused_h1, unused_b1, unused_d1;
-      Window unused_cr;
+      Window unused_cr, wm_parent;
+      Window *children;
+      unsigned int num_children, border_width;
 
       XTranslateCoordinates (dpy, parent, display->root,
                              0, 0, &x, &y, &unused_cr);
       XGetGeometry (dpy, parent, &unused_cr, &x1, &y1,
                     &unused_w1, &unused_h1, &unused_b1, &unused_d1);
+      XQueryTree (dpy, parent, &unused_cr, &wm_parent, &children, &num_children);
+      XFree(children);
+      XGetGeometry (dpy, wm_parent, &unused_cr, &unused_x, &unused_y,
+                    &unused_w1, &unused_h1, &border_width, &unused_d1);
+
       /*
        * if display->root isn't the parent window, a WM will probably have offset
        * our position for handles and decorations.  Counter it
        */
       if (x1 != x || y1 != y)
         {
-          x -= x1;
-          y -= y1;
+          x -= x1 + border_width;
+          y -= y1 + border_width;
         }
 
       x1 = (DisplayWidth  (dpy, display->screen) - old_width ) / 2;
```

**Comment by blueyed** [comment]
Thanks @psychon!

Will you forward it to the rxvt-unicode mailinglist?

**Comment by psychon** [comment]
Done: http://lists.schmorp.de/pipermail/rxvt-unicode/2015q4/002197.html

**Comment by psychon** [comment]
http://lists.schmorp.de/pipermail/rxvt-unicode/2016q2/002280.html
http://cvs.schmorp.de/rxvt-unicode/src/main.C?r1=1.399&r2=1.400&sortby=date

**Comment by blueyed** [comment]
Thanks a lot, @psychon!
