### ISSUE TITLE
errors 

### ISSUE THREAD

**Issue by dannyZhou** [awesomeWM/awesome#539]
awesome - git  master  error 

my linux -> archlinux 

$ uname -a 
Linux danny.com 4.0.7-2-ARCH #1 SMP PREEMPT Tue Jun 30 07:50:21 UTC 2015 x86_64 GNU/Linux

$ lua -v       
Lua 5.3.1  Copyright (C) 1994-2015 Lua.org, PUC-Rio

error while running function
stack traceback:

	/usr/local/share/awesome/lib/awful/placement.lua:24: in main chunk
	[C]: in function 'require'
	/usr/local/share/awesome/lib/awful/init.lua:42: in main chunk
	[C]: in function 'require'
	/home/danny/.config/awesome/rc.lua:3: in main chunk
error: /usr/local/share/awesome/lib/awful/placement.lua:24: attempt to index a nil value (field 'xresources')
error while running function
stack traceback:
	/usr/local/share/awesome/lib/awful/placement.lua:24: in main chunk
	[C]: in function 'require'
	/usr/local/share/awesome/lib/awful/init.lua:42: in main chunk
	[C]: in function 'require'
	/home/danny/.config/awesome/rc.lua:3: in main chunk
error: /usr/local/share/awesome/lib/awful/placement.lua:24: attempt to index a nil value (field 'xresources')
error while running function
stack traceback:
	/usr/local/share/awesome/lib/awful/placement.lua:24: in main chunk
	[C]: in function 'require'
	/usr/local/share/awesome/lib/awful/init.lua:42: in main chunk
	[C]: in function 'require'
	/etc/xdg/awesome/rc.lua:3: in main chunk
error: /usr/local/share/awesome/lib/awful/placement.lua:24: attempt to index a nil value (field 'xresources')
E: awesome: main:689: couldn't find any rc file

**Comment by psychon** [comment]
Delete `/usr/local/share/awesome/lib/beautiful.lua`.
