### ISSUE TITLE
Placement of floating clients ignores their border width

### ISSUE THREAD

**Issue by tycan** [awesomeWM/awesome#540]
Under awesome 3.4, opening floating clients places them next to each other, with no borders overlapping. However on 3.5.6, the border width is ignored, and it overlaps the clients next to it. It seems clients wrap around wiboxes properly: I have a task bar sitting at the top of my screen and clients just spawn below it, with their border taken into account.

Here are 3 terms in 3.4 (with large borders):
![awesome34](https://cloud.githubusercontent.com/assets/9666427/10676248/3f90c816-7905-11e5-9fbf-4a2dd9f63d41.png)

And the same in 3.5.6:
![awesome35](https://cloud.githubusercontent.com/assets/9666427/10676261/56cc6940-7905-11e5-87a5-eaa316429140.png)

Any ideas?
Thank you!

**Comment by blueyed** [comment]
Thank you for the clear report!

Could you try if this is fixed in Git master?

**Comment by tycan** [comment]
Sorry, that was forgetful of me.
Installed the git master, and the problem's still here.

**Comment by psychon** [comment]
Looking through the history of `awful.placement`, I can only spot edbc3fa652e2c50342a1ce8a0e8a8b (doesn't touch the `no_overlap` function) and 7d1a96335248377f356c9b5 (same). So no idea what changed.

**Comment by metaory** [comment]
+1 I have this issue on v3.5.6

**Comment by tycan** [comment]
That -almost- fixes it! I've noticed a problem: calling the placement.no_overlap function on a client that does not need to move will grow the client size by its border width repeatedly (you can test that by binding it to a key).
