### ISSUE TITLE
"Applets" blinking in systray

### ISSUE THREAD

**Issue by liar666** [awesomeWM/awesome#547]
Hi,

In my rc.lua (awesomeWM 3.5.6), I have replaced
    if s == 1 then right_layout:add(wibox.widget.systray()) end
by
    right_layout:add(wibox.widget.systray())
as I'd like to see the systray (particularly my cutom launchers and net/cpu/bat graphs on both my screens.

Unfortunately, doing so, the "applets" icons (for instance: dropbox, nm-applet, update_indicator or pidgin systray icon) blink on both screens. 

I've not been able to determine if they are alternating from one screen to the other or just blinking in parallel on both screen...

However, it is a really annoying behaviour.

And having the launchers/graphs only on one screen (e.g. screen 1) is unusable, as I need to traverse almost 2 whole screens (screen 2+a large part of screen 1) with my mouse every time  my mouse is on the other screen (screen 2) and I want to launch an app...

Is there a solution?

**Comment by psychon** [comment]
Welcome to X11. We can only have a single systray (for the same reason that we cannot display windows on two screens at the same time). Sorry.

The only "bug" here is that our current Lua code does not flag this as an error. And yes, the blinking is the systray alternating between screens.

Also, you could use a keybinding to move the mouse to the other screen.

**Comment by liar666** [comment]
Sorry to ear that Xorg is not adapted to dual-screens :{ Do you think Wayland (or other options) would work?
Thanks for the idea! I'll rather try a key binding to switch the systray from one screen to another or, better, make so that the systray follows the mouse :)
