### ISSUE TITLE
`moveTabRight` should move the last tab to be the first

### ISSUE THREAD

**Issue by BohrShaw** [awesomeWM/awesome#549]
Similarly, `moveTabLeft` moves the first tab to be the last.

These adjustments make the two commands consistent with `nextTab` and `previousTab`.

**Comment by psychon** [comment]
...what are you talking about?

There is no `moveTabRight`, `moveTabLeft`, `nextTab` or `previousTab` in awesome.

**Comment by BohrShaw** [comment]
@psychon I'm so sorry about this misinformation. It's actually about "vimium".

**Comment by psychon** [comment]
So this is not about awesome at all? Closing then (feel free to reopen if I misunderstand something)
