### ISSUE TITLE
Keygrabber fires press/release continuously when a Key is Down

### ISSUE THREAD

**Issue by ShadOoW** [awesomeWM/awesome#550]
Hello,
I'm very new to keygrabber so either i'm not using it properly or this is a bug.

```lua
keygrabber.run(function(mod, key, event)
        naughty.notify({text= event })
end)
```

Will print:
press
release
press
release
press
release...

As long as the Key is DOWN, i'm saying it a bug cause it should fire press only until i release key then it should only print ONE release.
Please correct me if i'm wrong.

**Comment by psychon** [comment]
Welcome to X11. Key repeat is implemented by, well, sending lots of individual key press/release.
(The XKB extension somehow allows to change this (they call it "detectable repeat", I think). This changes the sequence to press,press,press,press,...,release. Apparently we do not use this and I don't know if we should.)

**Comment by ShadOoW** [comment]
I see, thank you so much for pointing me to the right direction.

This is kind of useful, for completeness sake I will give a use case example:
Laptop media keys for next/prev song should also be able to fast forward/rewind if pressed for >~1s like how they behave in macos

About a fix, my understanding is that if i had a unique id (time stamp?) i could do the rest, like [this](http://stackoverflow.com/a/3220822) solution, but i don't think keygrabber support it, adding a unique ID will be awesome.

**Comment by ShadOoW** [comment]
Actually...

For the use case described above, it can be achieved without fix because those keys are not used commonly, so one could save the time of the first click and logically release it only if a certain period of time has passed with no new press event received, but this is kind of hacky and tricky to time correctly (to make it usable) and hard to code xD, and would only work with keys that are never spammed like media keys, so this won't work for all other keys, life shouldn't be this difficult :D

**Comment by psychon** [comment]
PR #558 enabled detectable autorepeat. With that, the release events are skipped and instead a series of presses is generated (without any release in between). Only when the key really is released do we get a release event.

Is that what you want?

**Comment by ShadOoW** [comment]
Great news from your pull request description I can assume it exactly what i needed.
I will try to test this tonight I will comment on the pull request after that.

Thank you, can close this issue.
