### ISSUE TITLE
Give wiboxes a default X window name or class

### ISSUE THREAD

**Issue by motdef** [awesomeWM/awesome#551]
Currently, wibox objects are created without X window properties which makes them difficult to target with programs like xdotool. I'm aware that the client module has a function to change a window's X properties but as far as I can tell it can't target a wibox.

**Comment by psychon** [comment]
Uhm, what name or class should they have? And why do you want to target a wibox with xdotool?

**Comment by motdef** [comment]
"wibox" for either would do, and my main interest was for adding inclusion/exclusion rules for external compositors - sorry, xdotool was a poor example, I was just using it to add a window name

**Comment by psychon** [comment]
I created a pull request with a fix. We now have:

    $ xwininfo -root -tree
    
    xwininfo: Window id: 0x2d7 (the root window) (has no name)
    
      Root window id: 0x2d7 (the root window) (has no name)
      Parent window id: 0x0 (none)
         7 children:
         0x200011 "Awesome drawin": ("awesome" "awesome")  1500x20+0+0  +0+0
         0x200010 "Awesome drawin": ("awesome" "awesome")  1x1+0+0  +0+0
         0x20000d "Awesome drawin": ("awesome" "awesome")  100x30+0+0  +0+0
         0x20000a "Awesome no input window": ("awesome" "awesome")  1x1+-1+-1  +-1+-1
         0x200009 "Awesome systray window": ("awesome" "awesome")  1x1+-1+-1  +-1+-1
         0x200008 "awesome": ("awesome" "awesome")  1x1+-1+-1  +-1+-1
         0x200007 "Awesome WM_Sn selection owner window": ("awesome" "awesome")  1x1+-1+-1  +-1+-1

Shout now if this is not what you wanted (instance "awesome", class "awesome" everywhere and the WM_NAME is different between all windows (well, except for drawins, they all get the same value)).

**Comment by motdef** [comment]
That looks great to me, thank you!

**Comment by psychon** [comment]
#556 was merged
