### ISSUE TITLE
Time for a release?

### ISSUE THREAD

**Issue by svexican** [awesomeWM/awesome#553]
I'm writting a plugin and it requires ``.valid`` and I'd like to mark it as a dependency.
It's been a while (January, I think) since 3.5.6 came out and there's been a lot of work done!

Thank you for AwesomeWM!

**Comment by psychon** [comment]
I could release 3.5.7, but that wouldn't bring you `.valid`, but only the fixes that are in the 3.5 branch. And I've been lazy with cherry-picking fixes from master into the 3.5 branch. Anyone wants to make a list of fixes and "nice things" in master, that the 3.5 branch should get? (Well, I can easily figure out fixes, but "nice things" is harder)

The master branch definitely is not in a state for a release, as e.g. #521 / #520 / #368 show.

**Comment by svexican** [comment]
Would valid be for a 3.6?

I'd love to help beginning the draft of a new release but I'm just starting to get involved... I will try to catch up!

**Comment by psychon** [comment]
List of new features that should go into 3.5.7:

- `.valid` (commit f5610fa9203c609f0761e75c1a66707e4e2b7d39)

I'll go through the necessary bug fixes later (but I already know that our window gravity handling fixes should be backported). I'll edit this comment if someone comes up with more stuff that should get in.

**Comment by psychon** [comment]
I did the various cherry-picks (random fixes and the `.valid` property). However, during this I came across a638310e89fe69b8f2e1364f7359a497469cd1bc. The 3.5 branch did not compile since July. Which means that no one tests this code. Which means that we would have a pretty much untested release.

Can someone test the 3.5 branch? For example, install this and use it for a week and check if anything breaks badly.

**Comment by blueyed** [comment]
> Can someone test the 3.5 branch?

We should probably add it to Travis, by adding the .travis.yml file there.
I'll give it a try: https://github.com/awesomeWM/awesome/pull/554

**Comment by blueyed** [comment]
> install this and use it for a week and check if anything breaks badly.

While my config is meant to be bc because of `git cherry-pick` etc, I won't volunteer for that.
IMHO we should get 3.6 out soonish, but 3.5.7 also makes sense in the meantime.

**Comment by psychon** [comment]
I've been running the 3.5 branch on my work machine since the 18th and haven't found any issues (besides #569).

**Comment by nereusx** [comment]
Release?
Please first fix the makefile so I can install awesome at /usr (not 
/usr/local)
It is my main wm :D

**Comment by psychon** [comment]
The following works since pretty much always:

    make CMAKE_ARGS="-DCMAKE_INSTALL_PREFIX:PATH=/usr"

(I'll skip the "installing to `/usr` directly is a bad idea and you should use a proper package manager"-complaint)

**Comment by nereusx** [comment]
On 15/01/2016 07:13 μμ, Uli Schlachter wrote:
>
> The following works since pretty much always:
>
> |make CMAKE_ARGS="-DCMAKE_INSTALL_PREFIX:PATH=/usr" |
>
> (I'll skip the "installing to |/usr| directly is a bad idea and you 
> should use a proper package manager"-complaint)
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/awesomeWM/awesome/issues/553#issuecomment-172019171>.
>
Thank you very much, I didnt find it in docs
Dont worry about package managers, etc, I use slackware and sources when 
I need to.
