### ISSUE TITLE
VirtualBox crashes AwesomeWM

### ISSUE THREAD

**Issue by mrschyte** [awesomeWM/awesome#555]
I've updated to VirtualBox 5.0.8 and if I start a VM, awesome crashes.

* If I run another window manager (e.g. icewm) I get no crashes.
* If I run awesome in Xephyr I get no crashes.
* I've tried debugging with gdb, but I didn't get any errors.

I suspect that the crash may be related to VirtualBox forcefully changing the window size.
Any tips on how can I debug this?

    awesome v3.5.6 (For Those About To Rock)
     • Build: May  5 2015 05:45:29 for x86_64 by gcc version 5.1.0 (builduser@)
     • Compiled against Lua 5.3.0 (running with Lua 5.3)
     • D-Bus support: ✔

**Comment by psychon** [comment]
Any output on awesome's stderr?
While awesome is running, `ls -l /proc/$(pidof awesome)/fd/{1,2}` hopefully tells you where this output goes to.

How did you try debugging with gdb? Did that perhaps already include some output?
(Also, I'm pedantic: So far we only know that awesome exits. We don't know if it crashes.)

**Comment by mrschyte** [comment]
I've tried redirecting the output using "awesome &> /tmp/awesome.log", but the file was empty.

This is the output from gdb, the process seems to exit without a crash:
http://pastebin.com/Y5Jfic4s

**Comment by mrschyte** [comment]
Here is the output from strace http://pastebin.com/eS1gKKDi

**Comment by psychon** [comment]
[Inferior 1 (process 1483) exited with code 01]

So at least it wasn't a "normal" exit. The only such calls to `exit()` in awesome (this could also be a library, I guess!) are when parsing the config fails or when `fatal()` is called. Well, and `fatal()` is used "too much".

How about this theory: Your X server crashes? Could you check `/var/log/Xorg.*` and/or `~/.local/share/xorg`?

**Comment by psychon** [comment]
Line 988 (about 50% through the file) is

    execve("/bin/zsh", ["/bin/zsh", "-c", "/usr/bin/awesome"], [/* 29 vars */] <unfinished ...> 

So awesome is restarting and I guess this is because VirtualBox changed the screen configuration (a different output size?).

This new awesome... I don't know, it works? The strace output stops during startup. The last thing is awesome trying to connect to the X11 server, so we are still deep in startup:

    connect(5, {sa_family=AF_INET, sin_port=htons(6004), sin_addr=inet_addr("127.0.0.1")}, 16

**Comment by mrschyte** [comment]
You're right, Xorg does crash:

    [   597.263] (**) ModulePath set to "/usr/lib/xorg/modules"
    [   597.263] (WW) Hotplugging is on, devices using drivers 'kbd', 'mouse' or 'vmmouse' will be disabled.
    [   597.263] (WW) Disabling Mouse0
    [   597.263] (WW) Disabling Keyboard0
    [   597.263] (II) [KMS] drm report modesetting isn't supported.
    [   597.263] (EE) 
    [   597.263] (EE) Backtrace:
    [   597.263] (EE) 0: /usr/lib/xorg-server/Xorg (OsLookupColor+0x139) [0x596d09]
    [   597.264] (EE) 1: /usr/lib/libc.so.6 (__restore_rt+0x0) [0x7fbc6d8b767f]
    [   597.264] (EE) 2: ? (?+0x0) [0x0]
    [   597.264] (EE) 
    [   597.264] (EE) Segmentation fault at address 0x0
    [   597.264] (EE) 
    Fatal server error:
    [   597.264] (EE) Caught signal 11 (Segmentation fault). Server aborting
    [   597.264] (EE) 
    [   597.264] (EE)

**Comment by psychon** [comment]
Ok. Sorry, but in that case I don't think I can help much. Closing.

**Comment by psychon** [comment]
Oh. One more thing: I guess you captured the strace output from a terminal that was running in the crashing session?

In that case I can provide another theory: VirtualBox resizes the screen, the window manager disconnects from the X11 server and apparently this combination then causes Xorg to crash.
(The terminal dies because it loses its X11 connection and while exiting it kills strace. This would explain the partial strace output.)

**Comment by mrschyte** [comment]
I was running strace in a detached tmux session, so I think that Xorg crashed first and then it killed awesome and strace as well. 

This seems to be the same issue in Xorg:
https://lists.launchpad.net/desktop-packages/msg143737.html

I've found a workaround for the problem by changing the driver from modeset to radeon in Xorg.conf.
