### ISSUE TITLE
`client.{urgent,focus.history}.delete` -- don't do linear search, use a client -> int mapping instead

### ISSUE THREAD

**Issue by d125q** [awesomeWM/awesome#557]
Consider `client.focus.history.delete`:
```lua
function client.focus.history.delete(c)
    for k, v in ipairs(client.data.focus) do
        if v == c then
            table.remove(client.data.focus, k)
            break
        end
    end
end
```
It performs a linear search over the clients to find the appropriate one to delete.  Why not, instead, have a table mapping clients to their indices in `client.data.focus` (I assume the keys, i.e. the clients, would have to be set as weak references)?

**Comment by psychon** [comment]
So I guess you are worried about "my computer is too slow to quickly iterate over the 100 clients that I have open; make that faster!". Let's assume we now have a table which maps clients to their index in `awful.client.data.focus`.

I call `awful.client.focus.history.delete(c)`. The function quickly finds the index of `c` and can remove it (which, by the way, it does via `table.remove` which must also have a `O(n)` complexity). Now it has to update the client-to-index-mapping which is as expensive as the original operation that you want to speed up.
Bad.

So this suggestion replaces an `O(n)` algorithm with another `O(n)` algorithm, but the existing algorithm is a lot simpler than the new algorithm.

Finally, why do you think this linear search is a problem?

P.S.: Yes, I'm always a big critic of performance improvements which complicate the code and weren't actually measured as being an improvement.
P.P.S.: http://c2.com/cgi/wiki?RulesOfOptimization (Especially the quotes)

**Comment by d125q** [comment]
Although I do not think that the existing algorithm is considerably simpler than the approach I suggested (more or less the same number of lines of code), I have to agree that linear search is completely fine.

It is probably possible to make everything run in constant time by using e.g. a linked list and a hash table, but *that's* going to be a more complex approach than the existing one.
