### ISSUE TITLE
[Question] Closing windows based on coffeescript

### ISSUE THREAD

**Issue by eternaltyro** [awesomeWM/awesome#561]
Atleast two applications that I use have refused to close when I press Ctrl + Q . How do I force close windows without *xkill*-ing them?

Affected apps are FBReader (https://github.com/geometer/FBReader) and Springseed (https://github.com/byhestia/springseed)

**Comment by psychon** [comment]
Could you get the `xprop` output for these windows?
In X11, there are two ways to close a window. One of them is what `xkill` does (telling the X11 server to disconnect the client), the other is what awesome does if `WM_DELETE_WINDOW` is in 'WM_PROTOCOLS` (sending a "please close" mesage).

**Comment by ff2000** [comment]
On Thu, 12 Nov 2015 07:23:56 -0800, eternaltyro <notifications@github.com> wrote:
> Atleast two applications that I use have refused to close when I press Ctrl + Q . How do I force close windows without *xkill*-ing them?
<Ctrl+Q> usually is a shortcut defined inside the application.
<Win+Shift+C> AFAIK is defined in awesomes default config to close a
window.

**Comment by eternaltyro** [comment]
Okay, Win+Shift+C worked. Is this defined in rc.lua?

**Comment by psychon** [comment]
Yes. https://github.com/awesomeWM/awesome/blob/b9db1d032a37e0a2f1501de6ef0e4acb6b645275/awesomerc.lua#L331-L332
