### ISSUE TITLE
XDG Compliant Dynamic Start Menu for Awesome

### ISSUE THREAD

**Issue by Teknocrat** [awesomeWM/awesome#562]
Here is my XDG based start menu, it depends heavily on the already merged menubar.
Performs wonderfully for me, definitely better than the very slow freedesktop lua scripts.

This is kinda a lazy mans pull request, I think it would make a nice awesome contribution and the code is pretty simple. 
Use as you will.

Here is my rc.lua snippit
```
local menugen = require("menugen")
-- {{{ Menu
local append_menu = { "Awesome", { { "Restart", awesome.restart },
				 { "Quit!!", quit, beautiful.awesome_icon } } } 
append_menu[#append_menu+1] = { "Terminal", terminal,
			menubar.utils.lookup_icon(terminal) }

menu_st = menugen.create({ append_menu = append_menu })
mylauncher = awful.widget.button({ image = beautiful.awesome_icon })
mylauncher:buttons(awful.button({}, 1, nil, function () menu_st:toggle() end  ))
-- }}}
```
[menugen.lua.txt](https://github.com/awesomeWM/awesome/files/34569/menugen.lua.txt)

**Comment by psychon** [comment]
Since you say "use as you will" and I have no idea what to do with this, I'll just close this. Sorry, but I'm confused. If someone other than me has a good idea, speak up and reopen.

**Comment by blueyed** [comment]
Would make sense to have it as a proper PR probably.
