### ISSUE TITLE
Cannot run two tasklists at the same time?

### ISSUE THREAD

**Issue by eri-trabiccolo** [awesomeWM/awesome#563]
$ awesome --version
awesome v3.5.2-915-gf7bbcf1 (The Fox)
 • Build: Nov 18 2015 13:26:12 for x86_64 by gcc version 4.9.3 (root@localhost.localdomain)
 • Compiled against Lua 5.1.5 (running with Lua 5.1)
 • D-Bus support: ✔

Hello,
I use to have two taslkists running at the same time on the same screens. Working fine with latest stable, do not with the latest git (see awesome version above).

Looks like the second one "ovverrides" something of the first one.

You might be able to reproduce the issue this way:
In your rc.lua, put this line:
`    local test = awful.widget.tasklist(s, awful.widget.tasklist.filter.focused, mytasklist.buttons)`
after
`    -- Create a tasklist widget
    mytasklist[s] = awful.widget.tasklist(s, awful.widget.tasklist.filter.currenttags, mytasklist.buttons)
`
re-run awesome and you'll see that the tasklist doesn't change if you switch tag. Also the current focused client doesn't get highlighted when focusing on a different client.

Can you reproduce this?

Bests,

Rocco

**Comment by psychon** [comment]
Shamefully trivial to fix. Sorry!
```lua
diff --git a/lib/awful/widget/tasklist.lua b/lib/awful/widget/tasklist.lua
index 294f030..a7e9e9a 100644
--- a/lib/awful/widget/tasklist.lua
+++ b/lib/awful/widget/tasklist.lua
@@ -225,7 +225,7 @@ function tasklist.new(screen, filter, buttons, style, update_function, base_widg
         capi.client.connect_signal("unfocus", u)
     end
     w._do_tasklist_update()
-    local list = instances[s]
+    local list = instances[screen]
     if not list then
         list = setmetatable({}, { __mode = "v" })
         instances[screen] = list
```

**Comment by eri-trabiccolo** [comment]
Thanks Uli ;)
