### ISSUE TITLE
My mouse button #9 isn't recognised by Awesome

### ISSUE THREAD

**Issue by Elv13** [awesomeWM/awesome#582]
Client buttons, wibox buttons and root.buttons work only with the first 8 buttons of my mouse. Xev show that the button#9 work as expected and Firefox map it to "Forward" correctly too. However, trying to use it in Awesome (I tried to use it for Alt+tab forward) doesn't work 

Here is a test case. I can reproduce the problem with both 3.5 and master

```lua
local tab, u,b = {}, require("awful.util"),require("awful.button")

for i=1,12 do
   tab = u.table.join(tab,b({ }, i, function () print(i) end))
end

root.buttons(tab)
```

Is there a limit somewhere (8 bit bitmask?) ? I looked at the code quickly. I will need to debug this further.

**Comment by psychon** [comment]
Welcome to X11. The button state (pressed/released) is only reported for the first 8 buttons in events (it's a `uint8_t`). However, I think that `event.c` treats any button number up to 255 correctly... I'd have to investigate/test, but I don't actually know how (I don't have that many mouse buttons).

**Comment by benoit-pierre** [comment]
You can use xdotool to simulate mouse buttons for testing.

**Comment by psychon** [comment]
I cannot reproduce this using the above test code, Xephyr and xdotool. Buttons 1 to 10 work fine here and xdotool breaks on 11 and 12:
```
$ xdotool click 11
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  132 (XTEST)
  Minor opcode of failed request:  2 (X_XTestFakeInput)
  Value in failed request:  0xb
  Serial number of failed request:  17
  Current serial number in output stream:  1
```

**Comment by psychon** [comment]
@benoit-pierre Oh and of course: Thank you for the idea!

**Comment by psychon** [comment]
@Elv13 Can you check if you can reproduce this with xdotool? Apparently I could not reproduce it 2.5 months ago.

**Comment by Elv13** [comment]
Work in a "real" X.org instance, but still broken in Xephyr or XNest

**Comment by psychon** [comment]
In that case the bug is likely in the X.org server. What else would be a difference between "real" and Xephyr+XNest? Sorry.
