### ISSUE TITLE
beautiful.xressources needs to convert colors `rgb:rr/gg/bb` -> `#rrggbb` and `argb:aa/rr/gg/bb` -> `#aarrggbb`

### ISSUE THREAD

**Issue by psychon** [awesomeWM/awesome#585]
See https://github.com/awesomeWM/awesome/pull/421#issuecomment-162161587 and the following comment.

Does anyone know the format for these things? I don't even know where I got the format that I am using from nor do I know what is allowed.

**Comment by psychon** [comment]
So... rxvt-unicode apparently uses `XParseColor` and supports some non-standard extensions: http://sources.debian.net/src/rxvt-unicode/9.21-1/src/rxvttoolkit.C/#L827
The extensions being: A prefix `[50]` means "50% transparency", `rgba:rrrr/gggg/bbbb/aaaa`.
Looking at the source of `XParseColor`... things get complicated. So, `#rrggbb` works with the individual components having a length from 1 to 4 (so `#rgb` to `#rrrrggggbbbb`).
Then Xcms is queries somehow: http://insar.stanford.edu/~lharcke/programming/Xcms/
Finally, the X11 server is asked (this makes things like `red` work).

**Comment by nuko8** [comment]
> Does anyone know the format for these things? I don't even know where I got the format that I am using from nor do I know what is allowed.

Perhaps, you saw them in the man page, `X(7)`, `COLOR NAMES`.

**Comment by actionless** [comment]
probably, in `beautiful.xresources` we could check if color string starts from `rgb:`

prefix `[50] ` is supported only in urxvt, right? seems it could problems elsewhere if it will be used in xsetting not prefixed with `URxvt`, ie ```
*background: #0e0021
URxvt*background: [95]#0e0021
```
