### ISSUE TITLE
Alternate configuration for setting border/titlebar colour?

### ISSUE THREAD

**Issue by motdef** [awesomeWM/awesome#592]
The default configuration paints each client's border with the "normal" colour when it loses focus, and paints it with the "focused" colour when it gains focus. This results in the focused client's decorations flickering briefly to another colour when switching between tags, or when toggling off the tag of the focused client. This probably isn't terribly noticeable with the default (1px?) border, but if you use title bars the effect can be quite distracting.

Since the issue boils down to clients losing focus before showing/hiding clients, I attempted to solve it by having Awesome perform colour changes only when a client receives focus (so that all unfocused clients are painted with the "normal" colour - in retrospect I suppose this only needs to be done for the last focused client). However, it seems like clients can still receive focus even if they're not visible, so it didn't fix the issue - is there a way to wait until the newly focused client has been mapped before setting colours?

**Comment by psychon** [comment]
I remember seeing this, too. Sounds like we have to make the default config more complicated... Something like the following is awfully complicated, but should work.
```lua
do
  local list =  {}
  local function need_border_update(c)
    table.insert(list, c)
  end
  client.connect_signal("focus", need_border_update)
  client.connect_signal("unfocus", need_border_update)
  client.connect_signal("unmanage", function(c)
    for i = 1, #list do
      if c == list[i] do
        table.remove(list, i)
      end
    end
  end)
  awesome.connect_signal("refresh", function()
   local need = need_border_update
   need_border_update = {}
    for k, c in ipairs(need) do
      if client.focus == c then
        c.border_color = beautiful.border_focus
      else
        c.border_color = beautiful.border_normal
      end
    end
  end)
end
```

**Comment by motdef** [comment]
I think `need` should be initialised as `list` rather than `need_border_update` but otherwise that makes sense. I don't actually use borders myself but I dropped in the awful.titlebar `update_colors()` function and it seemed to work at first, but after opening a few clients on a few different tags and moving around it became very slow.
