### ISSUE TITLE
Timestamp with awesome warnings/errors

### ISSUE THREAD

**Issue by blueyed** [awesomeWM/awesome#602]
Looking at e.g. `~/.xsession-errors` it would be useful if the messages (warnings etc) from awesome would be prefixed by a timestamp.

This would probably mean to change `_warn` and `_fatal` in `common/util.c` and `luaA_warn` in `luaa.h`.
The latter should then be used e.g. in `awful.util.deprecate` etc.

What do you think?

**Comment by psychon** [comment]
Seems fine to me. I'd implement this in both C and Lua instead of exporting some function to Lua for this. Should I give this as try, or do you want to do that?

**Comment by blueyed** [comment]
> Should I give this as try

Yes, please do.
