### ISSUE TITLE
focus is lost after unstick a client

### ISSUE THREAD

**Issue by sudo-nice** [awesomeWM/awesome#603]
Steps to reproduce:
1. Add to config a hotkey: `awful.key({ modkey, }, "s", function (c) c.sticky = not c.sticky end)`.
2. Press the hotkey to make a client sticky.
3. Switch to any other tag with some clients already there (our sticky client is focused).
4. Press the hotkey again to unstick the client.
5. The sticky client disappears but none of the other clients get focus. They can be focused with mouse click or switching to another tag forth and back.

My AwesomeWM version is 3.5.6 (and yes, it's AWESOME in general).

**Comment by psychon** [comment]
I guess this needs a `client.connect_signal("property::sticky", check_focus_delayed)` in `lib/awful/autofocus.lua`. Could you try adding this to `/usr/share/awesome/lib/awful/autofocus.lua`? (You do have `require("awful.autofocus")` in your config, right?)

**Comment by sudo-nice** [comment]
`client.connect_signal("property::sticky", check_focus_delayed)` didn't work for me, my x-server fall soon after that change. But then I tried `client.connect_signal("property::sticky", check_focus)` and it worked.
@psychon thank you very much!
