### ISSUE TITLE
"arrange" is called when focus change

### ISSUE THREAD

**Issue by Elv13** [awesomeWM/awesome#616]
In `awful/layout/init.lua`, there is:

```lua
capi.client.connect_signal("focus", function(c) layout.arrange(c.screen) end)
```

This cause slowdown and full redraw of some clients. For example, then using `urxvtd` (daemon with multiple terminal and internal IPC between terminals), this cause all terminal to be redrawn. On my old computer, this took more time than it took to focus the next one when moving the mouse across the screen, causing visual glitches for a few milliseconds (with urxvt/aterm `tint` option).

I am also playing with a port of the `awful.layout` system to use `wibox.hierarchy`, this cause many pointless calls (but they are delayed, some in the end don't affect performance that much).

Commenting the line cause no immediate issues for me, so is it really needed?

**Comment by psychon** [comment]
Removing that line breaks the magnifier layout.

Why does re-layouting stuff cause redraws? Every window should get the position that it already had before. In the C code, `client_resize()` doesn't do anything at all if the geometry doesn't change (look at the code, only if something changed does it call `client_resize_do()`).
