### ISSUE TITLE
RFC: Use wibox.layout.fixed as base for wibox.layout.flex and more?

### ISSUE THREAD

**Issue by Elv13** [awesomeWM/awesome#617]
I am currently in the progress of writing a new `wibox.layout.ratio`, `wibox.layout.magnifier` and `wibox.layout.stack` layouts to be able to implement the current `awful.layout` using `wibox.layout` combination. Most of those "list" layout are copy pasted from each other. Adding new methods such as `swap`, `insert`, `remove` and `get_children_count` just add more identical logic. Currently, I just put the code in `wibox.widget.base`, but it really doesn't belong there.

So I can either keep using a common lua file to store the duplicated code or just use `wibox.layout.fixed` as base for the others then monkeypatch the `layout`/`draw`/`fit` methods. This would simplify the code a lot. Anybody disagree with that?

**Comment by psychon** [comment]
I am fine with using `fixed` as base and monkeypatching the `layout` method. I guess that this could already be enough for most "children"...? So yeah, fell free.

However, this will break the `tostring(layout)` magic that @blueyed added here: https://github.com/awesomeWM/awesome/blob/bd8e2d2ca83f2eaa121d30cfd89681ad75563753/lib/wibox/widget/base.lua#L461-L468
