### ISSUE TITLE
awful.widget.tasklist is not redraw when wibox.widget.systray changes

### ISSUE THREAD

**Issue by mindeunix** [awesomeWM/awesome#624]
![1](http://i.imgur.com/1d1I2pu.png)
![2](http://i.imgur.com/m80wtPX.png)
![3](http://i.imgur.com/A91mZX7.png)

**Comment by psychon** [comment]
...but... it should be doing so! :-(

Could you check `xwininfo -frame -tree` in the above situation? (Click somewhere on the wibox, but not where the systray is/was). It should tell you about the current state of the systray window (last thing it prints, after "1 child:"). For example, my systray currently is: `0x1200003 (has no name): ()  1x1+1784+0  +3704+0`.
More information is shown by `xwininfo -id 0x1200003` and this also says `Map State: IsUnMapped` and thus we learn that my systray really is not visible currently.

What I want to know: Did we screw up getting rid of the systray icon or is this really the layout update going wrong?

**Comment by mindeunix** [comment]
Opened and then closed PyChrom:
```
xwininfo: Window id: 0x200010 "Awesome drawin"

  Root window id: 0x1bd (the root window) (has no name)
  Parent window id: 0x1bd (the root window) (has no name)
     1 child:
     0x200008 "Awesome systray window": ("awesome" "awesome")  20x20+455+0  +455+0

xwininfo: Window id: 0x200008 "Awesome systray window"

  Absolute upper-left X:  455
  Absolute upper-left Y:  0
  Relative upper-left X:  455
  Relative upper-left Y:  0
  Width: 20
  Height: 20
  Depth: 24
  Visual: 0x21
  Visual Class: TrueColor
  Border width: 0
  Class: InputOutput
  Colormap: 0x20 (installed)
  Bit Gravity State: ForgetGravity
  Window Gravity State: NorthWestGravity
  Backing Store State: NotUseful
  Save Under State: no
  Map State: IsViewable
  Override Redirect State: no
  Corners:  +455+0  -125+0  -125-380  +455-380
  -geometry 20x20+0+0
```
And that means that the systray is still visible?

anyway it's a little strange, because I've noticed this problem happens with my custom prompt widget too, but most likely I missed something because there are no such problem with default config.

**Comment by psychon** [comment]
Yup, the systray is still visible and has a size of 20x20. So apparently the C code does not notice that PyChrom closed its systray icon. Does this also happen with the default config?
I guess I will have to reproduce this, so some hints&instructions would be nice.

**Comment by mindeunix** [comment]
yes, it happens with default config. To reproduce this open **any** application which uses systray and then close it.

awesome v3.5.2-977-g430f4fa (running with LuaJIT 2.0.4)
Lgi 0.9.0-25-gd08dfee

**Comment by mindeunix** [comment]
There is no difference how many applications runs in the systray, when all of them are closed only one item/space remains visible.
