### ISSUE TITLE
is startup-notification optional? / irritating waiting cursor

### ISSUE THREAD

**Issue by funeralismatic** [awesomeWM/awesome#64]
can I build awesome without that? and if so, how? or if it imposible, why?

**Comment by blueyed** [comment]
I am closing this.

@funeralismatic 
Please feel free to re-open and/or create a new pull request for any improvements in this regard.

**Comment by psychon** [comment]
Create an empty file `~/.config/awesome/awful/startup-notification.lua`.

**Comment by blueyed** [comment]
And to emit a "completed" signal from a shell script yourself:

    if [ -n "$DESKTOP_STARTUP_ID" ]; then
      echo "awesome.emit_signal('spawn::completed', {id='$DESKTOP_STARTUP_ID'})" | awesome-client
    fi

(this assumes that `$DESKTOP_STARTUP_ID` is getting set, which is the responsibility of the launchee, e.g. awesome or nemo (file manager)).
