### ISSUE TITLE
awesome 3.5.7 client key bindings stop working after ibus-daemon starts

### ISSUE THREAD

**Issue by zhangkun83** [awesomeWM/awesome#640]
I can consistently reproduce it on Ubuntu 14.04.3, Awesome 3.5.7 built from source, with the vanilla `rc.lua`

Just after booting up, Awesome works fine. As soon as I run `ibus-daemon -d`, all the client key bindings that manipulate a window, such as `Mod4+m`, stop working. The global key bindings such as `Mod4+Right` are not affected.

Killing `ibus-daemon` doesn't restore the key bindings, neither does restarting Awesome with `Mod4 + Control + r`. Only restarting X does.

Awesome 3.5.6 does not have the problem.

**Comment by blueyed** [comment]
Could you git-bisect it?
There are not many commits in-between 3.5.6 and 3.5.7, but it requires you to be able to build and start awesome from the Git checkout.

**Comment by zhangkun83** [comment]
Bisect shows ff799a0f5dba06beed9f13939237899e53ff8fd8 is the culprit.

**Comment by blueyed** [comment]
@zhangkun83 
Awesome. thanks!

@psychon 
Your turn now.. :)

**Comment by psychon** [comment]
@blueyed I'm lazy :-P

Duplicate of #639, closing.
