### ISSUE TITLE
Travis should check/fail if there are issues with building docs

### ISSUE THREAD

**Issue by blueyed** [awesomeWM/awesome#643]
Currently `make ldoc` has these warnings on master, which should cause a build
error on Travis:

    …/objects/client.c:2678: ?: unknown tag: 'args' nil
    …//lib/gears/shape.lua:33: ?: unknown tag: 'note' nil

It's not clear to me how this could be enforced - maybe only by doing some `ldoc | grep -q .` magic?!

**Comment by psychon** [comment]
I like that idea a lot. Perhaps we could add a `--fatal-warnings` flag to `ldoc` upstream and use that in travis (or at least open a feature request there)?

**Comment by blueyed** [comment]
Yes, sounds good.

**Comment by psychon** [comment]
For your `ldoc` | grep -q .` magic, the following does the trick:
```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 47d19f3..75b3142 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -260,7 +260,7 @@ if(GENERATE_DOC)
     file(GLOB_RECURSE AWE_MD_FILES ${AWE_DOC_DIR}/*.md)
 
     add_custom_target(ldoc ALL
-        COMMAND ${LDOC_EXECUTABLE} .
+        COMMAND ${LDOC_EXECUTABLE} . 3>&1 1>&2 2>&3 | awk "{ fail=1 \; print } END { exit fail }"
         WORKING_DIRECTORY ${AWE_DOC_DIR}
         DEPENDS ${AWE_LUA_FILES} ${AWE_MD_FILES})
 endif()
```
Should we commit that? It's quite ugly...
The shell redirection magic swaps stdout and stderr and awk exits with a non-zero exit status whenever it sees at least one line of output (but does after "forwarding" that output).

**Comment by blueyed** [comment]
:+1: 
It's not too ugly.
Maybe add a comment above?

**Comment by psychon** [comment]
Ok, I will then push that straight to master (with a comment added) when I get the time. (ldoc upstreams seems to be a little inactive and so it might take a while before someone reacts to the issue I reported there.)

**Comment by blueyed** [comment]
Please provide a link to the issue when you're are working on this.
Thanks!
