### ISSUE TITLE
Loss of clientkeys functionality after issuing setxkbmap

### ISSUE THREAD

**Issue by Lilolbet** [awesomeWM/awesome#662]
Hi,

when setting a new keyboard layout via setxkbmap all client keys stop functioning on old opened windows/applications. If you spawn a new app/window only it will have clientkeys.

Running setxkbmap again will make the new window also lose its clientkey functionality.

I have replicated this on two machines, tried the default configuration and the problem persists.

**Comment by Elv13** [comment]
This has been fixed in 3.5.8 and the "git master" versions, can you confirm?

**Comment by Lilolbet** [comment]
Can confirm, works after upgrading to 3.5.8
