### ISSUE TITLE
Keyboard issues: stops responsing

### ISSUE THREAD

**Issue by nenadalm** [awesomeWM/awesome#67]
It happens to me time to time (about twice per month I think) that keyboard stops responding as usual. If I hit a key, nothing happens. But if I hold a key, it starts writing after a while (but I need to hold every key from that time to be able to write anything).

Restart of Awesome doesn't help.
Quit Awesome and login again does help.

```
nenadalm@localhost:~$ awesome -v
awesome v3.5.5 (Kansas City Shuffle)
 • Build: Apr 14 2014 18:44:32 for x86_64 by gcc version 4.8.2 (mockbuild@)
 • Compiled against Lua 5.2.2 (running with Lua 5.2)
 • D-Bus support: ✔

nenadalm@localhost:~$ cat /etc/issue
Fedora release 20 (Heisenbug)
Kernel \r on an \m (\l)


```

**Comment by WillianPaiva** [comment]
im having the same problem rightnow !awesome v3.5.6 (For Those About To Rock)
 • Build: Jan 10 2015 23:18:34 for x86_64 by gcc version 4.9.2 (builduser@)
 • Compiled against Lua 5.2.3 (running with Lua 5.2)
 • D-Bus support: ✔

Linux Arch 3.18.2-2-ARCH 

xev gives normal output it just take   long time press to the key being recognized .

**Comment by WillianPaiva** [comment]
ok after looking around looks like the problem is connected to GDM i just would like to know if nenadalm uses GDM also

**Comment by blueyed** [comment]
Does `ibus restart` help in this case?

**Comment by nenadalm** [comment]
@WillianPaiva I did use gdm, but since I don't expect to use more window managers in the nearest future, I disabled it.

It didn't happen from the time I disabled it yet.

**Comment by WillianPaiva** [comment]
I did change gdm for slim and i until the moment no problem an it was a frequent problem

**Comment by WillianPaiva** [comment]
Sory i had did change before testing ibus restart 
But a quick solution was holding shift for 10 seconds than it was back to normal

**Comment by actionless** [comment]
just faced the same issue (and faced it few days before on other machine)

so current is using slim, other is not using any DM

in xev keys output looks as usual

it seems to be what affected only mod4, arrow keys, home, end, insert, delete

page down behaves like 'menu' key
page up behaves like '/'

**Comment by nenadalm** [comment]
@actionless - exactly the same happened to me a few days ago (sinc it was for the first time, I didn't pay attention to that)

**Comment by nenadalm** [comment]
without reloading awesome

**Comment by psychon** [comment]
Could this be the same issue as #415?

**Comment by psychon** [comment]
Since no one complaint, I'll assume that this is the Qt issue from #415 ("Qt is stealing our ~~jobs~~ mouse events).
