### ISSUE TITLE
Stop restarting on RandR configuration changes

### ISSUE THREAD

**Issue by psychon** [awesomeWM/awesome#672]
Same issue in the old tracker:https://awesome.naquadah.org/bugs/index.php?do=details&task_id=687
Some branch where I worked on something, but I'm not even sure on what: https://github.com/awesomeWM/awesome/tree/remove_screen_index

I think everyone agrees that restarting on RandR configuration changes is just a cheap hack since we are too lazy to handle this properly. This issue is about handling this properly. Before working on this, I want to get some input on what everyone thinks "properly" means.

For example, should monitor "coldplug" (monitor already present when awesome starts) and "hotplug" (configuration is changed on the fly) be handled differently?

### The current screen API

- Screens identified with integers from 1 to `screen.count()`
- Properties:
  - `geometry` The geometry on the root window
  - `workarea` The geometry of the screen minus things like e.g. the wibox. This is the space available for displaying clients
  - `index` The number identifying this screen
  - `outputs` Some information about the RandR outputs connected to this screen's CRTC (only if RANDR is in use)
- Signals: Only `property::workarea`

I explain this so detailed, because I think the first point is a problem: Assume you are in a situation with three screens and screen 2 is disconnected. Effectively this means that there are now screens 1 and 2, but 2 has a completely different meaning. This is why I propose to stop identifying screens with numbers and only use userdata instead.

### @psychon's idea after thinking for 0.5 seconds

- Lua can iterate over all screens via `for s in screen.iterate()` (I don't want `for i, s in screen.iterate()` or something like that since this would provide some kind of integer again)
- Properties stay the same (minus `index`)
- All the properties get signals that are emitted when needed
- Screens have signals like `connected`/`disconnected` or `enabled`/`disabled` (I'd try to stay close the RANDR's terminology, but I don't know what that is right now)

So far for simple. I'd guess that I wouldn't many complaints about this. However, now comes my evil idea:

- While parsing the config, we have no screens at all yet.
- Afterwards (and before managing any clients), the screens are introduced in the same way as monitor hotplug is handled

Pro (at least I hope so): No special magic is needed so that Lua code handles monitor hotplug correctly, because all Lua code will have to do this anyway.
Con: Quite an API break (but I guess removing screen indices already does quite a lot of damage)

### Your idea here

So, what is your opinion? Without thinking about any implementation constraints, what kind of API would you prefer?

**Comment by kapsh** [comment]
I like second idea without index. But I have only one question: how it should be possible to distinguish screens? 
Let's say I have 3 monitors and only one is plugged when Awesome starts. The others are small 17" and big 24" so I have different use cases and layouts for them. 
How it should look in rc.lua?
```
screen.connect_signal("connected", function(s)
    if screen.SOME_DISTINCTIVE_ATTR == "big_mon" then 
        blablabla
```
I hope I'm explained my thoughts clearly.

**Comment by psychon** [comment]
@kapsh Screens already now provide information about the outputs, that can be used for identifying them (so in your case: something like: `if s.outtputs.VGA1 then`:
```
$ echo 'return require("gears.debug").dump_return(screen[1].outputs)' | awesome-client 
   string "table: 0xf6aaeb0
  VGA1 : table: 0xf6aaf00
    mm_width : 477 (number)
    mm_height : 268 (number)"
```

**Comment by kapsh** [comment]
Nice, thank you. I got it.

**Comment by Elv13** [comment]
I was wondering. Can we do this step by step with little incremental changes?

1) Stop reloading Awesome by force
2) Add more signals like the one merged a few days ago
3) Move the forced reload to lua (so `awful.screen` call `capi.awesome.restart()` itself)
4) Add a "reload" method to `capi.screen`
5) Use the existing lua code path to move out-of-screen clients back into the workarea (we have that already)
6) Upgrade `awesomerc.lua` to use a signal connection instead of a for-loop for wibox definition.
7) start deprecating, then dropping the screen index API for an object based one.

Compared to your previous branch (from 2 years ago) that tried to do everything at once. This seem like something that could be gradually implemented in master. Am I missing something?

**Comment by psychon** [comment]
Re (2): You mean the signal for output connected/disconnected, right?
Re (4): What would that do? Throw away the current screen configuration and come up with a new one by reading something from the X server? What happens with screen indexes here? (e.g. when the middle out of three monitors is disconnected)

My plan for this was "break everything for no gain" :-)
What I mean is this: I can just move the call to `screen_scan()` to a later place in startup so that the config is loaded with no screens defined, but awesome will still restart on RANDR changes. That way I can mostly ignore the C code for this for now.

So my incremental changes list would be:

1) Add the new API to C (without breaking the current one)
2) Port all the Lua code to the new API, preparing things for "a wild monitor appeared"
3) Change the C code so that screens are defined after the config is loaded
4) Remove old API (what would a deprecation step gain us?)
5) Figure out the RANDR stuff for dynamic screen configuration (this shouldn't cause any Lua changes at this point, this is where the "forced reload" is removed)

The problem with too many RANDR specific signals is that the C code would have to emulate RANDR on Xinerama / no-RANDR&Xinerama configurations during startup. Depending on how RANDR-specific the signals are, that could be annoying.

If you are worried about users having too do big changes at an inconvenience time, well, that's what they get for living on master. ;-) Alternatively, we could add a step 3.5 "Add deprecation warnings" and wait a month or so before (4).

Does this sound like a plan? Any comments on what the new API should look like?

**Comment by Elv13** [comment]
> Re (2): You mean the signal for output connected/disconnected, right?

right

> Re (4): What would that do? Throw away the current screen configuration and come up with a new one by reading something from the X server? What happens with screen indexes here? (e.g. when the middle out of three monitors is disconnected)

No, just reload `capi.screen` information and do nothing else. Keep it simple. That way, the lua side can slowly be ported to dynamic screen even if the API suck. This will make the transition much smoother.

> If you are worried about users having too do big changes at an inconvenience time, well, that's what they get for living on master. ;-) Alternatively, we could add a step 3.5 "Add deprecation warnings" and wait a month or so before (4).

No a problem, I just fear trying to get everything right then merge into master will keep failing forever. By doing incremental API break for dynamic screen support, then you ensure at least some of it get done. If <s>you work hard</s> we are lucky, then it will also be "right".
