### ISSUE TITLE
Unwanted monitor switching

### ISSUE THREAD

**Issue by reteo** [awesomeWM/awesome#674]
I recently updated my distribution of Linux, and I have just installed Awesome 3.5.6.

I've reset the rc.lua file, and made some small changes (removed the menu, expanded the time to be full-text time and date, and set the taglist to hide empty tags).  However, I've noticed a glitch with Firefox and VLC.  Whenever I click somewhere specific (empty tab bar in FF, Start/Stop button in VLC), the window will immediately switch desktops, as if I had pressed (logo key)-O.

**Comment by blueyed** [comment]
Can you check it with Awesome 3.5.8?

**Comment by reteo** [comment]
Updated.  And it works.  I think I'll shut up now.
