### ISSUE TITLE
Support images in documentation

### ISSUE THREAD

**Issue by Elv13** [awesomeWM/awesome#681]
My first attempt apparently only work locally. I was kind of expecting this, but hoped it would work anyway.

http://awesomewm.github.io/apidoc/documentation/03-declarative-layout.md.html

Look like I will have to dive deeper into this

**Comment by funeralismatic** [comment]
```
CMake Error at cmake_install.cmake:147 (file):
  file INSTALL cannot find
  "/var/tmp/portage/x11-wm/awesome-9999/work/awesome-9999_build/docs/images/widgetlayout1.png".
```

**Comment by Elv13** [comment]
strange, I get

```
-- Installing: /tmp/dir/share/doc/awesome/images/widgetlayout1.png
-- Installing: /tmp/dir/share/doc/awesome/images/widgetlayout2.png
```

**Comment by psychon** [comment]
There is no awesome-9999 in Gentoo: https://gitweb.gentoo.org/repo/gentoo.git/tree/x11-wm/awesome. @funeralismatic Where did you get the ebuild from? Also, do you have ldoc installed or are you building without docs? I guess this is the problem, because the copy-images-to-build-dir is inside of a `if(GENERATE_DOC)` while the `install()` command is executed always.

(However, the ebuild for 3.5.8 doesn't use our wrapper Makefile)

**Comment by Elv13** [comment]
Indeed, patch coming

 cmake .. -DCMAKE_INSTALL_PREFIX=/tmp/cab -DGENERATE_DOC=false

sorry about that

**Comment by Elv13** [comment]
Done

**Comment by funeralismatic** [comment]
@psychon 

>Where did you get the ebuild from?

ebuild from [nightmare overlay](https://gitlab.com/r3lgar/nightmare/tree/master/x11-wm/awesome).

>Also, do you have ldoc installed or are you building without docs?

Without docs.

>I guess this is the problem, because the copy-images-to-build-dir is inside of a if(GENERATE_DOC)

All files are copied to build dir, only these two images are ignored.

**Comment by Elv13** [comment]
@funeralismatic Is it fixed now? I pushed a commit yesterday that fixed `-DGENERATE_DOC=false`, at least on my side

**Comment by funeralismatic** [comment]
@Elv13, all ok without docs.

**Comment by Elv13** [comment]
@blueyed Can you update the robot to also copy the image folder? I don't seem to have access to it (and I don't need access, just add a line to copy the image folder at the right relative path).

**Comment by psychon** [comment]
https://gitlab.com/r3lgar/nightmare/blob/master/x11-wm/awesome/awesome-9999.ebuild
> DEPEND="
> [...]
>	doc? (
>		app-doc/doxygen
>		media-gfx/graphviz
>	)
>"

Ha, that ebuild is funyy. :-)

@Elv13 awesome-robot lives in `build-utils/travis-apidoc.sh`. I'm not completely sure, but I *think* it adds all files under `build/apidoc` to Git (`cd build/apidoc` and `git add --all .`)

**Comment by funeralismatic** [comment]
@psychon, that code is derived from gentoo portage tree.

No ldoc in tree, only luadoc.

**Comment by psychon** [comment]
@Elv13 No idea which package I need to get this to work, but for me ldoc doesn't parse the markdown. Could you test the following patch for me? (Yes, I am removing that `install()` call on purpose, because all of `build/doc` is installed and I copy the images there, `docs` was the wrong one) I'm not sure about the changes do the actual docs. Are the images still found?
```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index a1fad87..f94986f 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -34,13 +34,6 @@ set(AWE_DOC_FILES
     ${AWE_DOC_DIR}/02-contributing.md
     ${SOURCE_DIR}/LICENSE)
 
-if (GENERATE_DOC)
-   set(AWE_DOC_IMAGES
-        ${AWE_DOC_DIR}/images/widgetlayout1.png
-        ${AWE_DOC_DIR}/images/widgetlayout2.png
-    )
-endif()
-
 set(AWE_SRCS
     ${BUILD_DIR}/awesome.c
     ${BUILD_DIR}/banning.c
@@ -261,13 +254,14 @@ endif()
 if(GENERATE_DOC)
     if(NOT BUILD_DIR STREQUAL SOURCE_DIR)
         file(MAKE_DIRECTORY ${BUILD_DIR}/lib)
+        file(MAKE_DIRECTORY ${BUILD_DIR}/doc)
     endif()
 
     file(GLOB_RECURSE AWE_LUA_FILES ${BUILD_DIR}/lib/*.lua)
     file(GLOB_RECURSE AWE_MD_FILES ${AWE_DOC_DIR}/*.md)
 
     # Copy the images to the build directory
-    file(COPY ${SOURCE_DIR}/docs/images DESTINATION ${AWE_DOC_DIR})
+    file(COPY ${SOURCE_DIR}/docs/images DESTINATION ${BUILD_DIR}/doc)
 
     # Run ldoc and make it fail if any warnings are generated. The
     # redirection-magic swaps stdout and stderr and awk exits with a non-zero
@@ -352,7 +346,6 @@ install(DIRECTORY ${SOURCE_DIR}/themes DESTINATION ${AWESOME_DATA_PATH}
 install(DIRECTORY ${BUILD_DIR}/themes DESTINATION ${AWESOME_DATA_PATH}
     PATTERN "*.lua")
 install(FILES ${AWE_DOC_FILES}  DESTINATION ${AWESOME_DOC_PATH})
-install(FILES ${AWE_DOC_IMAGES} DESTINATION ${AWESOME_DOC_PATH}/images)
 install(FILES "awesome.desktop" DESTINATION ${AWESOME_XSESSION_PATH})
 if(GENERATE_DOC)
     install(DIRECTORY ${BUILD_DIR}/doc DESTINATION ${AWESOME_DOC_PATH})
diff --git a/docs/03-declarative-layout.md b/docs/03-declarative-layout.md
index 3b75243..be88a21 100644
--- a/docs/03-declarative-layout.md
+++ b/docs/03-declarative-layout.md
@@ -75,7 +75,7 @@ Code:
 
 
 Result:
-![Example2 screenshot](../../docs/images/widgetlayout1.png)
+![Example2 screenshot](../images/widgetlayout1.png)
 
 
 ## Use an `wibox.layout.align` layout
@@ -114,7 +114,7 @@ Code:
     }
 
 Result:
-![Example4 screenshot](../../docs/images/widgetlayout2.png)
+![Example4 screenshot](../images/widgetlayout2.png)
 
 For more information about how to draw widgets, refer to the `Cairo` api:
 
```

**Comment by Elv13** [comment]
You need either `markdown` or `discount` parser in your $PATH.

Yes, images still load on my side
