### ISSUE TITLE
Travis doesn't notice some errors

### ISSUE THREAD

**Issue by psychon** [awesomeWM/awesome#689]
Some quote from https://travis-ci.org/awesomeWM/awesome/jobs/108660087 (a successful travis build):

> == Running /home/travis/build/awesomeWM/awesome/tests/test-leak-client.lua ==
> [...]
> 2016-02-11 22:39:46 W: beautiful: can't get colorscheme from xrdb (using fallback).
> 2016-02-11 22:39:47 W: awesome: luaA_dofunction:77: error while running function
> stack traceback:
>	lib/awful/titlebar.lua:117: in function <lib/awful/titlebar.lua:72>
>	(...tail calls...)
>	[string "-- Some memory leak checks involving clients ..."]:30: in function <[string "-- Some memory leak checks involving clients ..."]:6>
> error: lib/awful/titlebar.lua:117: attempt to index global 'base' (a nil value)
> +grep -q -E ^Error|assertion failed /tmp/tmp.ogV2z6N0Cu/_awesome_test.log
> +echo == Running /home/travis/build/awesomeWM/awesome/tests/test-leaks.lua ==

The above should have made the build fail.

(This issue is not about the problem "titlebars are broken", but about the bug in the tests runner that hides this issue!)

**Comment by blueyed** [comment]
The `grep` should look for `^error:` maybe, too?

**Comment by psychon** [comment]
My plan is to turn the logic around. Instead of looking for errors, I want to do `print("Functional test finished successfully")` at the end of `_runner` and grep for that. The test fails unless that is present. Hopefully that should be all that is necessary.

Or do we have some kind of non-fatal errors that grepping for errors catches, but wouldn't make the test fail otherwise?

**Comment by blueyed** [comment]
Sounds good!
No time for this currently though.
