### ISSUE TITLE
Mplayer window drifting slowly in top left direction.

### ISSUE THREAD

**Issue by jk411** [awesomeWM/awesome#697]
Hi

Every time mplayer video window is set fullscreen/restored it is moved in top left direction.
It happens in floating mode.
With border_width = 0 video window stays in place.
Any other value sets the "step".
So far Ive noticed this behavior only with mplayer video window, xine and the rest of programs seems to be fine.

lib/awful/ewmh.lua:
71:    elseif data[window] and data[window].fullscreen then
72:        window:geometry(data[window].fullscreen)
73:        window.border_width = data[window].fullscreen.border_width
74:    end

Swapping line 72 with line 73 fixes problem but Ive no idea if it's the correct fix.

Awesome 3.5.8
complied from sources on slackware 14.1 x64
Thanks

**Comment by psychon** [comment]
Confirmed on master. This was introduced in https://github.com/awesomeWM/awesome/commit/b2aaefd095c964491f2c93aa01ec7f0fcc9c340f. Before this, the top-left corner of a client stayed where it was when the border width changes. Now we apply window gravity and the top-left corner of the actual content window stays where it was.

So yeah, your proposed fixed is the correct one. From a quick look through `ewmh.lua`, line 77 has the same problem, but nothing else in this file. I'll have to carefully look at all places that set the border width. And I guess it would also make sense to add test cases for this....

Thanks for reporting a bug and providing the fix with it! :-)
