### ISSUE TITLE
Make the systray less weird to use

### ISSUE THREAD

**Issue by psychon** [awesomeWM/awesome#724]
Here's a random idea that I had in my mind lately:

Based on https://github.com/awesomeWM/awesome/pull/710, make the systray "screen aware". One can configure the screen on which the systray should be visible (`:only_visible_on_screen(s)`). Based on `context.screen` the widget does nothing on other screens and is only visible on this specific screen.

That way, we can get rid of the `s == 1 and`-magic in the default config and it becomes easier to move the systray between screens (just call `:only_visible_on_screen(s)`!).

To keep some kind of compatiblity and sane behaviour, I would suggest to add a special value `"primary"` which is also the default screen. When the value is selected, then `screen.primary` is used to display the systray (and the systray updates when the primary screen is changed, e.g. through `xrandr --output VGA1 --primary`).

This would also make things much easier for https://github.com/awesomeWM/awesome/issues/672, because with the `"primary"` value, nothing special has to done when the screen that the systray is on disappears (Some other screen will become the new primary screen).

What do you think about this?

**Comment by Elv13** [comment]
I am fine with this. Unless we support the new spec[1], there is not much to do.

[1] Only KDE and Unity support it, Gnome went their own NIH way, so it's probably not worth implementing yet ( https://www.freedesktop.org/wiki/Specifications/StatusNotifierItem/ )

**Comment by psychon** [comment]
That relies on DBus and "DBus" is a code word for "cannot be sanely used from Lua". ;-)

**Comment by Elv13** [comment]
This is why my async module exist, but the dbus code is still in a local branch. Maybe your pre-compiled LGI alternative would work. Finishing the async module would take time (that I don't have). The parts that are there are there, even with all the TODO and memory leaks, feel free to take a look. There is unit tests ;)

**Comment by blueyed** [comment]
Sounds good!
