### ISSUE TITLE
Enable branch protection?

### ISSUE THREAD

**Issue by psychon** [awesomeWM/awesome#749]
GitHub offers branch protection feature: https://help.github.com/articles/about-protected-branches/
With this enabled, force-pushes and branch deletion are prevented.

Optionally, it's also possible to require Travis to pass before something can be pushed to a branch. This requires the above, but can be controlled separately! https://help.github.com/articles/enabling-required-status-checks/

Do we want this? I think branch protection sounds like a good idea, but I'm less sure about the second. I wonder how this interacts with `[ci skip]`-commits or releases...

**Comment by blueyed** [comment]
> I think branch protection sounds like a good idea

Yes.

 > about the second

In my experience it will get more in the way.

Let's start with the protection for now.

**Comment by psychon** [comment]
Done for 3.5 and master branch.
