### ISSUE TITLE
Export naughty suspension status

### ISSUE THREAD

**Issue by Unode** [awesomeWM/awesome#755]
I'm trying to write a simple widget to pause notifications on demand: `naughty.suspend() / naughty.resume() / naughty.toggle()`.
Currently I can't find a way to know what is the state of naughty.
`naughty.suspended` is used internally but is not accessible externally.

Would it be possible to make `naughty.suspended` accessible or alternatively provide `naughty.status()` to return its value?

**Comment by Elv13** [comment]
In the git version of Awesome, there is `naughty.is_suspended()`, so this is already implemented.

**Comment by Unode** [comment]
Hi @Elv13.

I just had a look at the git version and I'm confused. The change that introduced `naughty.is_suspended()` dates from 15th of May 2015, however the latest release (v3.5.9) is less than 10 days old and doesn't include the change.

When should I expect the change to be part of a release?

Thanks

**Comment by psychon** [comment]
Current master will (hopefully...) some day be version 3.6.0. The 3.5.9 release comes from the 3.5 branch. I guess a cherry-pick could help here...

**Comment by psychon** [comment]
Hrm. That commit can't easily be cherry picked.
