### ISSUE TITLE
Maximized windows

### ISSUE THREAD

**Issue by rshadow** [awesomeWM/awesome#758]
In version 3.5 are broken maximized window:
1. They are in what is a separate layer. And not the tile with the other windows.
2. They do not adapt to the screen size. If you create a maximized window on a screen and move to another smaller, the window simply override everything and be cropped to fit the screen.

This behavior was not in version 3.4. Maximize the window behave like the rest of the window. These properties are simply ignored.

**Comment by psychon** [comment]
What do you mean by (1)? How could a maximized window tile normally with the other windows? What would "maximized" mean if it did that? Why do you want it to be ignored? I'm confused.

For (2): I thought this was already fixed. And I'm surprised that 3.4 did not have that problem. Weird.

**Comment by rshadow** [comment]
1. I say about windows with X state:
```
$ xprop | grep -i max
_NET_WM_STATE(ATOM) = _NET_WM_STATE_MAXIMIZED_VERT, _NET_WM_STATE_MAXIMIZED_HORZ
```

You can set current window maximized like:
```
wmctrl -r :ACTIVE: -b toggle,maximized_vert,maximized_horz
```

**Comment by rshadow** [comment]
2. This is only for maximized windows. I hope if (1) it will be fixed, and (2) too.

**Comment by rshadow** [comment]
I use awesome 3.5.6

**Comment by blueyed** [comment]
Can you try awesome master, please?

(2) should be fixed there, and (1) maybe, too?!

**Comment by rshadow** [comment]
I try master. Bug exists.

**Comment by rshadow** [comment]
I try 3.5.9 from debian. Bug exists.

**Comment by Elv13** [comment]
The code has been rewritten, most of these issues are fixed, for what remains, better open new issues.
