### ISSUE TITLE
use hotkey to switch between process.

### ISSUE THREAD

**Issue by jinleileiking** [awesomeWM/awesome#764]
`.xinitrc:`

```
DISPLAY=:0.1 dbus-launch --exit-with-session awesome &
DISPLAY=:0.0 dbus-launch --exit-with-session awesome

```

I have  2 monitors at 0.1,  2 at 0.0 

mod + J  can switch between client in one process.

How can I switch mouse between the two processes?

**Comment by funeralismatic** [comment]
It should be on the Xorg side, it's not a wm job.

**Comment by Elv13** [comment]
My collision module can do this (and display an arrow to show where it moved). The mouse can be set using `mouse.coords {x= 42, y=42}`. Closing this to reduce the number of open issues.

**Comment by blueyed** [comment]
@Elv13 
Does collision really work across different X DISPLAYs?
Can you point to where it does it, please?

**Comment by Elv13** [comment]
As long as Xinerama is enabled it can, but I missed that it wasn't in this case, so no, I retract what I said. I should have read better, sorry. I could be implemented, but it isn't.
