### ISSUE TITLE
use ruby instead of lua.

### ISSUE THREAD

**Issue by jinleileiking** [awesomeWM/awesome#765]
As a wm, I think the computer resource is big: big mem, big cpu.
 
Lua is very good in  emmbed linux such as uclinux, and so on .

But lua is not very friendly to programmers.

So I think ruby / python is better to do the script think.

c++ ( core ) + ruby (api) is awesome !

I know this suggest will be close. But ... That is what I should say.

**Comment by jinleileiking** [comment]
然而并没有什么卵用.

**Comment by Elv13** [comment]
Good luck with Awesome 2.* then, patches still welcome. Awesome isn't only scripted in Lua, it is written in Lua. Switching language = rewriting 60% of the code, so better start from scratch.

There is not much more to do/say here, so closing this

Previous discussion https://www.mail-archive.com/awesome@naquadah.org/msg08027.html
