### ISSUE TITLE
[RFC] Removed irrelevant methods from the API doc

### ISSUE THREAD

**Issue by Elv13** [awesomeWM/awesome#766]
See

http://awesomewm.github.io/apidoc/classes/wibox.widget.background.html

There is a lot of methods (mostly re-implemented methods from `widget.base`) that provide very little value to the documentation user. Frameworks like Qt usually hide them in "N inherited methods from M" link. I propose doing the same for our API and just adding a link in the doc header.

Any opposition?

Edit: I forgot to mention I just plan to change `---` to `--`, not remove the doc from the code

**Comment by psychon** [comment]
Changing the "---" to "--" sounds like a good idea for the methods which no user should ever call, yeah.

**Comment by Elv13** [comment]
Ok, I will take that into account in my next PRs, thanks for the feedback
