### ISSUE TITLE
maximizing some windows confuses awesome

### ISSUE THREAD

**Issue by sim590** [awesomeWM/awesome#769]
This always happens with `mpv` so that's the example I use. When I have two monitors configured like so:

```
Screen 0: minimum 320 x 200, current 3286 x 1080, maximum 8192 x 8192
LVDS1 connected primary 1366x768+0+0 (normal left inverted right x axis y axis) 309mm x 173mm
   1366x768      60.10*+
   1024x768      60.00
   800x600       60.32    56.25
   640x480       59.94
VGA1 connected 1920x1080+1366+0 (normal left inverted right x axis y axis) 510mm x 290mm
   1920x1080     60.00*+
   1680x1050     59.95
   1280x1024     75.02    60.02
   1152x864      75.00
   1024x768      75.08    60.00
   832x624       74.55
   800x600       75.00    60.32    56.25
   640x480       75.00    60.00
   720x400       70.08
```

and I maximize `mpv` in the right monitor (VGA1) and "unmaximize" it, the `mpv` window is systematically moved to the left monitor (LVDS1), which is kind of annoying.

**Comment by Elv13** [comment]
Hello/Salut,

What's your Awesome version?

**Comment by sim590** [comment]
```
awesome v3.5.9 (Mighty Ravendark)
 • Build: Mar 12 2016 01:11:40 for x86_64 by gcc version 5.3.0 (builduser@rw)
 • Compiled against Lua 5.3.2 (running with Lua 5.3)
 • D-Bus support: ✔
```

**Comment by Elv13** [comment]
Can you try with the git-master version first? (it may require some changes to your config). 3.5.* is ~1200 commits behind master.

In some case, if the monitor "y" is different from 0, this kind of bugs happen. However, both of your screens start at 0, so this is not that one.

**Comment by actionless** [comment]
mb you have an `awful.rule` which is matching your `mpv`?

**Comment by sim590** [comment]
@actionless nope.

**Comment by sim590** [comment]
I've just tested it with the latest master version:
```
awesome v3.5.2-1290-ga407862 (The Fox)
 • Compiled against Lua 5.3.2 (running with Lua 5.3)
 • D-Bus support: ✔
```
and it behaved the same way.

**Comment by sim590** [comment]
I have just tried with the following version (latest):
```
awesome v3.5.2-2262-g13fdaa08 (The Fox)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • RandR 1.5 support: ✔
 • LGI version: 0.9.1
```
and the bug is gone!

**Comment by Elv13** [comment]
great, thanks for the fllow up!
