### ISSUE TITLE
Mouse doesn't work after screen change if texmaker is open

### ISSUE THREAD

**Issue by chamoAt** [awesomeWM/awesome#774]
Hi,

if i use texmaker on my laptop and switch from my laptop screen to my 2 external screens my mouse doesn't work in awesome anymore. But just in awesome. In any other application is the mouse still working.

For example: 
- if i want to switch the tag by using the mouse it doesn't work.
- if i open the menu with mod4+w, i can click on none of the elements
- ...
any mouse operation in awesome doesn't work.

My software setup:
Arch Linux 4.4.5-1-ARCH
awesome v.3.5.9
texmaker 4.5

**Comment by psychon** [comment]
Does closing texmaker make the mouse in awesome work again? Does texmaker use Qt? Which Qt version is it using? Are you using any other Qt apps? Could you try if closing them makes everything work again?

**Comment by chamoAt** [comment]
Problem is gone after installing some updates.
But thanks for you respond @psychon.
