### ISSUE TITLE
Attempt to perform arithmetic on a userdata value

### ISSUE THREAD

**Issue by csolg** [awesomeWM/awesome#784]
Hi, I've updated awesome wm to e8c7e573cbac40dc157839fbae6e4199ffd5aabd. Now the error occurs when I select another screen:
`/usr/local/share/awesome/lib/awful/screen.lua:146: attempt to perform arithmetic on a userdata value`

Thanks.

**Comment by csolg** [comment]
I reverted to 770cfa45530a4b82b5bdb25e5a4c9b982f9d42d7. Now it works.

**Comment by Elv13** [comment]
Can you try https://github.com/Elv13/awesome-1/tree/fix_screen_index

I only have 1 screen, so my testing ability are limited.

There might be many more of these, the recent (and future) changes to the screen API to support adding/removing/resizing screens without reloading Awesome will cause many problems, but it is unavoidable and a good thing.

**Comment by csolg** [comment]
Thank you!
