### ISSUE TITLE
[Question] Client toggle minimize code in default rc.lua

### ISSUE THREAD

**Issue by AKuederle** [awesomeWM/awesome#794]
Hi,

I am currently trying to fully understand the code in the default rc.lua file. However, I can't figure out, what the following lines of code in the buttons attached to the tasklist do.

``` lua
c.minimized = false
if not c:isvisible() then
     awful.tag.viewonly(c:tags()[1])
end
```

I couldn't find a situation, where the client wasn't visible after setting minimized to false.

Kind regards

**Comment by blueyed** [comment]
It might be possible that the client is not visible on the current tag.

It comes originally from this commit: https://github.com/awesomeWM/awesome/commit/76b081622b7848bac37a922ef60dd0794c72d8b8.

I did not know about the "alltags" filter (https://github.com/awesomeWM/awesome/blob/3e5b1b3ba9b9f91f3ec78c1f547adb405c10bb6a/lib/awful/widget/tasklist.lua#L258-L265) myself, but it's a thing.. :)
It will apparently display all clients from all tags on the tasklist.
