### ISSUE TITLE
"Invalid screen number" error with xresources theme

### ISSUE THREAD

**Issue by blueyed** [awesomeWM/awesome#795]
```
2016-04-04 11:28:46 E: Error during a protected call: /usr/share/awesome/themes/xresources/assets.lua:51: invalid screen number: 1
stack traceback:
        /usr/share/awesome/lib/gears/protected_call.lua:17: in function </usr/share/awesome/lib/gears/protected_call.lua:16>
        [C]: in metamethod '__index'
        /usr/share/awesome/themes/xresources/assets.lua:51: in field 'wallpaper'
        /usr/share/awesome/themes/xresources/theme.lua:94: in main chunk
        [C]: in function 'dofile'
        [C]: in function 'xpcall'
        /usr/share/awesome/lib/gears/protected_call.lua:37: in function </usr/share/awesome/lib/gears/protected_call.lua:36>
        (...tail calls...)
        /usr/share/awesome/lib/beautiful/init.lua:120: in function 'beautiful.init'
        /home/user/.config/awesome/rc.lua:178: in main chunk
2016-04-04 11:28:46 E: beautiful: error loading theme file /usr/share/awesome/themes/xresources/theme.lua
```

Code: https://github.com/awesomeWM/awesome/blob/e24cb901cbe95718901c5b0b73b15ac0448f989d/themes/xresources/assets.lua#L51

**Comment by actionless** [comment]
weird, it's still working for me (just built the latest master) and also according to aipdocs it's still the valid usage (http://awesomewm.github.io/apidoc/classes/screen.html#screen.screen). or they should be updated?

**Comment by psychon** [comment]
Try master before 9ea207afaa71ca443fe22437aa5cd35d737743ea ;-)

**Comment by actionless** [comment]
can wallpaper be a function? so it will be called when the screen is already present

or i am getting the root cause of the issue wrong?

**Comment by psychon** [comment]
Right now it cannot be a function (the default config does `gears.wallpaper.maximized(beautiful.wallpaper, s, true)`, `gears.wallpaper` does no `type`-magic), but that might be one way to solve it, yeah.

The root cause is the goal "don't restart on RandR screen changes" and as part of getting there I made awesome load the config with 0 screens defined and only load screens afterwards. Due to this, the `screen[1]` in the xresources theme failed.

**Comment by Elv13** [comment]
This has been fixed, right?

**Comment by psychon** [comment]
The "evil commit" was reverted. That fixed the immediate symptom. Also, the idea of turning the wallpaper into a function was also implemented.
