### ISSUE TITLE
Displaying startup errors fails on master (no screen)

### ISSUE THREAD

**Issue by blueyed** [awesomeWM/awesome#796]
In case of startup errors the following code will fail, because there's no screen available yet ([source](https://github.com/awesomeWM/awesome/blob/e24cb901cbe95718901c5b0b73b15ac0448f989d/awesomerc.lua#L18-L22)):

```lua
if awesome.startup_errors then
    naughty.notify({ preset = naughty.config.presets.critical,
                     title = "Oops, there were errors during startup!",
                     text = awesome.startup_errors })
end
```

```
error while running function!
stack traceback:
        /home/daniel/.config/awesome/rc.lua:3215: in main chunk
error: /home/daniel/.config/awesome/rc.lua:3215: attempt to index a nil value (field '?')
========================
error while running function!
stack traceback:
        /usr/share/awesome/lib/naughty/core.lua:617: in function 'naughty.core.notify'
        /etc/xdg/awesome/rc.lua:22: in main chunk
error: /usr/share/awesome/lib/naughty/core.lua:617: attempt to index a nil value (local 's')
2016-04-04 14:12:41 E: awesome: main:699: couldn't find any rc file
```

I am not sure how to address this, but it would be helpful to `print` it here also (and not rely on `naughty` alone)?!

**Comment by Elv13** [comment]
Can this still happen?

**Comment by psychon** [comment]
We reverted the late screen addition stuff. I still think that it would be a good idea to not have coldplug, but only hotplug of monitors, but people get mad at me when I implement that. :-)
