### ISSUE TITLE
awful.placement.no_overlap does not consider current screen (was: mouse.screen can be wrong)

### ISSUE THREAD

**Issue by blueyed** [awesomeWM/awesome#813]
I've noticed today, that `mouse.screen` (used via `awful.screen.focused()`, but also in `awesome-client`) is often wrong for me: it returns 2 for the index, although the mouse pointer is on screen 1 (screen.primary).

I have not investigated further.

**Comment by blueyed** [comment]
@psychon 
Any idea / hints for me to look at/for?

**Comment by psychon** [comment]
Nope, nothing good really. Some bad ifrsd:
- How easy can you reproduce this?
- What are `mouse.coords()` when `mouse.screen` is wrong? (plus what's the geometry of all the screens)

**Comment by blueyed** [comment]
Seems to be reproducible at work always, but it does not seem to be about `mouse.screen` being wrong.

`screen.primary.index` is 1 (the laptop screen).
The other screen is above.
```
mouse.coords():
  x : 2181 (number),
  y : 2345 (number)
mouse.screen.index = 1
```

Therefore that's OK.

But programs will open at screen 2 (the one above), and not where the mouse is.

`xrandr -q`:
```
Screen 0: minimum 8 x 8, current 2688 x 2592, maximum 32767 x 32767
eDP1 connected 1920x1080+768+1512 (normal left inverted right x axis y axis) 276mm x 156mm
DP2-2 connected 2688x1512+0+0 (normal left inverted right x axis y axis) 521mm x 293mm panning 2688x1512+0+0
```

**Comment by psychon** [comment]
The "place new client's on mouse's screen"-stuff is handled by `lib/awful/tag.lua`, connecting to the "manage" signal. It does `c.screen = ascreen.focused()`. Perhaps you can add some `print(c.screen)` before and after this to see if it worked? Also, `client.connect_signal("property::screen", function(c) print(debug.traceback(c.name .. " now on " .. (c.screen and c.screen.index or "no screen")) end)` might be really spammy, but might also be helpful.

**Comment by blueyed** [comment]
See https://github.com/awesomeWM/awesome/pull/852 for a fix and the explanation.
