### ISSUE TITLE
Add ${CMAKE_DL_LIBS} in CMakeLists.txt

### ISSUE THREAD

**Issue by Samuel88** [awesomeWM/awesome#82]
Under Slackware current without adding manually 

target_link_libraries(${PROJECT_AWE_NAME}
    ${AWESOME_COMMON_REQUIRED_LDFLAGS}
    ${AWESOME_REQUIRED_LDFLAGS}
    ${AWESOME_OPTIONAL_LDFLAGS}
    ${CMAKE_DL_LIBS})

awesome make fail

**Comment by psychon** [comment]
Could you show the output of "make" (at least the part around the error)? I don't see why this should be necessary.

Documentation says:

    $ cmake --help-variable CMAKE_DL_LIBS
    CMAKE_DL_LIBS
    -------------
    
    Name of library containing dlopen and dlcose.
    
    The name of the library that has dlopen and dlclose in it, usually
    -ldl on most UNIX machines.

Awesome doesn't use `dlopen`/`dlclose`/`dlsym`.

**Comment by Samuel88** [comment]
this is the error running make without 

>>> make   
Running cmake…
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check if the system is big endian
-- Searching 16 bit integer
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of unsigned short
-- Check size of unsigned short - done
-- Using unsigned short
-- Check if the system is big endian - little endian
-- git -> /usr/bin/git
-- hostname -> /bin/hostname
-- asciidoc -> /usr/bin/asciidoc
-- xmlto -> /usr/bin/xmlto
-- gzip -> /usr/bin/gzip
-- ldoc not found.
-- ldoc.lua not found.
-- convert -> /usr/bin/convert
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.5") 
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.25") 
-- Found Lua51: /usr/lib64/liblua.a;/usr/lib64/libm.so (found version "5.1.5") 
-- Not generating API documentation. Missing: ldoc
-- checking for module 'xcb>=1.6'
--   found xcb, version 1.11
-- checking for modules 'glib-2.0;gdk-pixbuf-2.0;cairo;x11;xcb-cursor;xcb-randr;xcb-xtest;xcb-xinerama;xcb-shape;xcb-util>=0.3.8;xcb-keysyms>=0.3.4;xcb-icccm>=0.3.8;cairo-xcb;libstartup-notification-1.0>=0.10;xproto>=7.0.15;libxdg-basedir>=1.0.0'
--   found glib-2.0, version 2.42.0
--   found gdk-pixbuf-2.0, version 2.31.1
--   found cairo, version 1.12.16
--   found x11, version 1.6.2
--   found xcb-cursor, version 0.1.1
--   found xcb-randr, version 1.11
--   found xcb-xtest, version 1.11
--   found xcb-xinerama, version 1.11
--   found xcb-shape, version 1.11
--   found xcb-util, version 0.3.9
--   found xcb-keysyms, version 0.3.9
--   found xcb-icccm, version 0.4.1
--   found cairo-xcb, version 1.12.16
--   found libstartup-notification-1.0, version 0.12
--   found xproto, version 7.0.26
--   found libxdg-basedir, version 1.2.0
-- Looking for backtrace_symbols
-- Looking for backtrace_symbols - found
-- checking for execinfo -- found
-- checking for __builtin_clz -- yes
-- checking for module 'dbus-1'
--   found dbus-1, version 1.6.12
-- Configuring lib/menubar/menu_gen.lua
-- Configuring lib/menubar/init.lua
-- Configuring lib/menubar/utils.lua
-- Configuring lib/naughty/init.lua
-- Configuring lib/naughty/core.lua
-- Configuring lib/naughty/dbus.lua
-- Configuring lib/awful/button.lua
-- Configuring lib/awful/menu.lua
-- Configuring lib/awful/tooltip.lua
-- Configuring lib/awful/ewmh.lua
-- Configuring lib/awful/prompt.lua
-- Configuring lib/awful/titlebar.lua
-- Configuring lib/awful/keygrabber.lua
-- Configuring lib/awful/init.lua
-- Configuring lib/awful/autofocus.lua
-- Configuring lib/awful/remote.lua
-- Configuring lib/awful/client/shape.lua
-- Configuring lib/awful/layout/init.lua
-- Configuring lib/awful/layout/suit/max.lua
-- Configuring lib/awful/layout/suit/fair.lua
-- Configuring lib/awful/layout/suit/magnifier.lua
-- Configuring lib/awful/layout/suit/init.lua
-- Configuring lib/awful/layout/suit/floating.lua
-- Configuring lib/awful/layout/suit/tile.lua
-- Configuring lib/awful/layout/suit/spiral.lua
-- Configuring lib/awful/placement.lua
-- Configuring lib/awful/screen.lua
-- Configuring lib/awful/mouse/finder.lua
-- Configuring lib/awful/mouse/init.lua
-- Configuring lib/awful/wibox.lua
-- Configuring lib/awful/rules.lua
-- Configuring lib/awful/util.lua
-- Configuring lib/awful/dbus.lua
-- Configuring lib/awful/widget/button.lua
-- Configuring lib/awful/widget/prompt.lua
-- Configuring lib/awful/widget/init.lua
-- Configuring lib/awful/widget/launcher.lua
-- Configuring lib/awful/widget/taglist.lua
-- Configuring lib/awful/widget/tasklist.lua
-- Configuring lib/awful/widget/common.lua
-- Configuring lib/awful/widget/progressbar.lua
-- Configuring lib/awful/widget/layoutbox.lua
-- Configuring lib/awful/widget/textclock.lua
-- Configuring lib/awful/widget/graph.lua
-- Configuring lib/awful/key.lua
-- Configuring lib/awful/startup_notification.lua
-- Configuring lib/awful/tag.lua
-- Configuring lib/awful/completion.lua
-- Configuring lib/awful/client.lua
-- Configuring lib/beautiful.lua
-- Configuring lib/wibox/init.lua
-- Configuring lib/wibox/drawable.lua
-- Configuring lib/wibox/layout/constraint.lua
-- Configuring lib/wibox/layout/flex.lua
-- Configuring lib/wibox/layout/init.lua
-- Configuring lib/wibox/layout/fixed.lua
-- Configuring lib/wibox/layout/rotate.lua
-- Configuring lib/wibox/layout/mirror.lua
-- Configuring lib/wibox/layout/base.lua
-- Configuring lib/wibox/layout/align.lua
-- Configuring lib/wibox/layout/margin.lua
-- Configuring lib/wibox/widget/textbox.lua
-- Configuring lib/wibox/widget/init.lua
-- Configuring lib/wibox/widget/imagebox.lua
-- Configuring lib/wibox/widget/systray.lua
-- Configuring lib/wibox/widget/base.lua
-- Configuring lib/wibox/widget/background.lua
-- Configuring lib/gears/timer.lua
-- Configuring lib/gears/init.lua
-- Configuring lib/gears/sort.lua
-- Configuring lib/gears/color.lua
-- Configuring lib/gears/debug.lua
-- Configuring lib/gears/object.lua
-- Configuring lib/gears/surface.lua
-- Configuring lib/gears/wallpaper.lua
-- Configuring themes/zenburn//theme.lua
-- Configuring themes/default//theme.lua
-- Configuring themes/sky//theme.lua
-- Configuring config.h
-- Configuring config.ld
-- Configuring awesomerc.lua
-- Configuring awesome-version-internal.h
-- Configuring awesome.doxygen
-- Configuring done
-- Generating done
-- Build files have been written to: /home/samuel/Scaricati/slackware-build/awesome/awesome-git/.build-darkasus-x86_64-slackware-linux-4.8.4
Running make Makefile…
Building…
Scanning dependencies of target generated_sources
[  1%] Generating atoms-intern.h
[  2%] Generating atoms-extern.h
[  2%] Built target generated_sources
Scanning dependencies of target version_stamp
[  2%] Built target version_stamp
Scanning dependencies of target awesome
[  2%] Building C object CMakeFiles/awesome.dir/awesome.c.o
[  3%] Building C object CMakeFiles/awesome.dir/banning.c.o
[  4%] Building C object CMakeFiles/awesome.dir/color.c.o
[  5%] Building C object CMakeFiles/awesome.dir/dbus.c.o
[  6%] Building C object CMakeFiles/awesome.dir/draw.c.o
[  6%] Building C object CMakeFiles/awesome.dir/event.c.o
[  7%] Building C object CMakeFiles/awesome.dir/ewmh.c.o
[  8%] Building C object CMakeFiles/awesome.dir/keygrabber.c.o
[  9%] Building C object CMakeFiles/awesome.dir/keyresolv.c.o
[ 10%] Building C object CMakeFiles/awesome.dir/luaa.c.o
[ 11%] Building C object CMakeFiles/awesome.dir/mouse.c.o
[ 11%] Building C object CMakeFiles/awesome.dir/mousegrabber.c.o
[ 12%] Building C object CMakeFiles/awesome.dir/property.c.o
[ 13%] Building C object CMakeFiles/awesome.dir/root.c.o
[ 14%] Building C object CMakeFiles/awesome.dir/selection.c.o
[ 15%] Building C object CMakeFiles/awesome.dir/spawn.c.o
[ 16%] Building C object CMakeFiles/awesome.dir/stack.c.o
[ 16%] Building C object CMakeFiles/awesome.dir/strut.c.o
[ 17%] Building C object CMakeFiles/awesome.dir/systray.c.o
[ 18%] Building C object CMakeFiles/awesome.dir/xwindow.c.o
[ 19%] Building C object CMakeFiles/awesome.dir/common/atoms.c.o
[ 20%] Building C object CMakeFiles/awesome.dir/common/backtrace.c.o
[ 21%] Building C object CMakeFiles/awesome.dir/common/buffer.c.o
[ 21%] Building C object CMakeFiles/awesome.dir/common/luaclass.c.o
[ 22%] Building C object CMakeFiles/awesome.dir/common/lualib.c.o
[ 23%] Building C object CMakeFiles/awesome.dir/common/luaobject.c.o
[ 24%] Building C object CMakeFiles/awesome.dir/common/util.c.o
[ 25%] Building C object CMakeFiles/awesome.dir/common/version.c.o
[ 25%] Building C object CMakeFiles/awesome.dir/common/xcursor.c.o
[ 26%] Building C object CMakeFiles/awesome.dir/common/xembed.c.o
[ 27%] Building C object CMakeFiles/awesome.dir/common/xutil.c.o
[ 28%] Building C object CMakeFiles/awesome.dir/objects/button.c.o
[ 29%] Building C object CMakeFiles/awesome.dir/objects/client.c.o
[ 30%] Building C object CMakeFiles/awesome.dir/objects/drawable.c.o
[ 30%] Building C object CMakeFiles/awesome.dir/objects/drawin.c.o
[ 31%] Building C object CMakeFiles/awesome.dir/objects/key.c.o
[ 32%] Building C object CMakeFiles/awesome.dir/objects/screen.c.o
[ 33%] Building C object CMakeFiles/awesome.dir/objects/tag.c.o
[ 34%] Building C object CMakeFiles/awesome.dir/objects/window.c.o
Linking C executable awesome
/usr/lib64/gcc/x86_64-slackware-linux/4.8.4/../../../../x86_64-slackware-linux/bin/ld: /usr/lib64/gcc/x86_64-slackware-linux/4.8.4/../../../../lib64/liblua.a(loadlib.o): undefined reference to symbol 'dlclose@@GLIBC_2.2.5'
/lib64/libdl.so.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[3]: *** [awesome] Errore 1
make[2]: *** [CMakeFiles/awesome.dir/all] Errore 2
make[1]: *** [all] Errore 2
make: *** [cmake-build] Errore 2

**Comment by psychon** [comment]
Ah, so you have a statically built liblua.a and that one is using `dlclose()`. I guess slackware is the only distro doing that. I'd rather have this added library only when it is really needed instead of in general. However, right now I can't think of a good approach to do that and the #lua IRC channel didn't really manage to help me much.

Can you somehow figure out if slackware install a pkg-config file for lua? Something that can be spot via `pkg-config --list-all | grep -i lua`?

**Comment by Samuel88** [comment]
The output of this command is
```
samuel@darkasus ~> pkg-config --list-all | grep -i lua
lua                                 Lua - An Extensible Extension Language
```

**Comment by psychon** [comment]
(Sorry for the awfully long delay)

Could you find the pkg-config file (`lua.pc`, you should find it via `pkg-config --debug --exists lua`, somewhere in the output it will tell you where the file is) and append it? Apprently it is broken.

Also, could you write the following into a file called `CMakeLists.txt` and run `cmake . && make && ./prog` in the same directory?

Thanks!

```
cmake_minimum_required(VERSION 3.0)
project(prog)
include(FindLua)
if(NOT LUA_FOUND)
	message(ERROR "Lua not found")
endif()
include_directories(${LUA_INCLUDE_DIR})

file(WRITE  prog.c "#include \"lauxlib.h\"\n")
file(APPEND prog.c "#include \"lualib.h\"\n")
file(APPEND prog.c "#include <stdio.h>\n")
file(APPEND prog.c "int main() {\n")
file(APPEND prog.c "  lua_State *L = luaL_newstate();\n")
file(APPEND prog.c "  luaL_openlibs(L);\n")
file(APPEND prog.c "  lua_pushstring(L, \"Success!\");\n")
file(APPEND prog.c "  printf(\"%d\\n\", luaL_dostring(L, \"print('foo', require('lgi'))\"));\n")
file(APPEND prog.c "  printf(\"%s\\n\", lua_tostring(L, -1));\n")
file(APPEND prog.c "  lua_close(L);\n")
file(APPEND prog.c "  return 0;\n")
file(APPEND prog.c "}\n")
add_executable(prog prog.c)
target_link_libraries(prog ${LUA_LIBRARIES})
add_custom_target(run-prog COMMAND ./prog DEPENDS prog)
```

**Comment by Samuel88** [comment]
my /usr/lib64/pkgconfig/lua.pc is the following
```
# lua.pc -- pkg-config data for Lua

# vars from install Makefile

# grep '^V=' ../Makefile
V= 5.1
# grep '^R=' ../Makefile
R= 5.1.5

# grep '^INSTALL_.*=' ../Makefile | sed 's/INSTALL_TOP/prefix/'
prefix= /usr
INSTALL_BIN= ${prefix}/bin
INSTALL_INC= ${prefix}/include
INSTALL_LIB= ${prefix}/lib64
INSTALL_MAN= ${prefix}/man/man1
INSTALL_LMOD= ${prefix}/share/lua/${V}
INSTALL_CMOD= ${prefix}/lib64/lua/${V}

# canonical vars
exec_prefix=${prefix}
libdir=${exec_prefix}/lib64
includedir=${prefix}/include

Name: Lua
Description: An Extensible Extension Language
Version: ${R}
Requires: 
Libs: -L${libdir} -llua -lm
Cflags: -I${includedir}

# (end of lua.pc)
```

and this is the output of the command
```
samuel@hestia mercoledì 10 febbraio 2016 - 06:25:03 [exit=0]
/home/samuel/Scaricati/slackware-build/awesome/awesome
>>> cat > CMakeLists.txt 
cmake_minimum_required(VERSION 3.0)
project(prog)
include(FindLua)
if(NOT LUA_FOUND)
    message(ERROR "Lua not found")
endif()
include_directories(${LUA_INCLUDE_DIR})

file(WRITE  prog.c "#include \"lauxlib.h\"\n")
file(APPEND prog.c "#include \"lualib.h\"\n")
file(APPEND prog.c "#include <stdio.h>\n")
file(APPEND prog.c "int main() {\n")
file(APPEND prog.c "  lua_State *L = luaL_newstate();\n")
file(APPEND prog.c "  luaL_openlibs(L);\n")
file(APPEND prog.c "  lua_pushstring(L, \"Success!\");\n")
file(APPEND prog.c "  printf(\"%d\\n\", luaL_dostring(L, \"print('foo', require('lgi'))\"));\n")
file(APPEND prog.c "  printf(\"%s\\n\", lua_tostring(L, -1));\n")
file(APPEND prog.c "  lua_close(L);\n")
file(APPEND prog.c "  return 0;\n")
file(APPEND prog.c "}\n")
add_executable(prog prog.c)
target_link_libraries(prog ${LUA_LIBRARIES})
add_custom_target(run-prog COMMAND ./prog DEPENDS prog)

samuel@hestia mercoledì 10 febbraio 2016 - 06:25:14 [exit=0]
/home/samuel/Scaricati/slackware-build/awesome/awesome
>>> cmake .
-- The C compiler identification is GNU 5.3.0
-- The CXX compiler identification is GNU 5.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Lua: /usr/lib64/liblua.so;/usr/lib64/libm.so (found version "5.1.5") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/samuel/Scaricati/slackware-build/awesome/awesome

samuel@hestia mercoledì 10 febbraio 2016 - 06:25:20 [exit=0]
/home/samuel/Scaricati/slackware-build/awesome/awesome
>>> make
Scanning dependencies of target prog
[ 50%] Building C object CMakeFiles/prog.dir/prog.c.o
[100%] Linking C executable prog
[100%] Built target prog

samuel@hestia mercoledì 10 febbraio 2016 - 06:25:25 [exit=0]
/home/samuel/Scaricati/slackware-build/awesome/awesome
>>> ./prog 
foo	table: 0x21be0b0
0
Success!
```

And if I try to compile last awesome commit on Slackware-current, compilation work fine without modify nothing :-)...
Maybe Slackware's lua package was upgraded and the previous error still not appers.

**Comment by psychon** [comment]
> -- Found Lua: /usr/lib64/liblua.so;/usr/lib64/libm.so (found version "5.1.5") 

Your Lua is now a dynamically linked library, not a statically linked one. The pkg-config file is still weird, but whatever. Good to hear that the Slackware package was fixed.
