### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by hari-rangarajan** [awesomeWM/awesome#821]
/home/hari/tmpbuilds/awesome1/awesome/tests/examples/awful/placement/align.lua
  A test failed, bye
Call Stack (most recent call first):
  tests/examples/CMakeLists.txt:243 (run_test)
  tests/examples/CMakeLists.txt:235 (digg)
  tests/examples/CMakeLists.txt:235 (digg)
  tests/examples/CMakeLists.txt:264 (digg)
  awesomeConfig.cmake:306 (include)
  CMakeLists.txt:17 (include)

**Comment by Elv13** [comment]
Can you add more lines please?

**Comment by hari-rangarajan** [comment]
This is the entire log. Please let me know if you need specific details from the logs. BTw, 3.5.9 builds fine on the same machine. The error is with the latest pull.

Running cmake…
-- git -> /usr/bin/git
-- asciidoc -> /usr/bin/asciidoc
-- xmlto -> /usr/bin/xmlto
-- gzip -> /bin/gzip
-- ldoc -> /usr/bin/ldoc
-- convert -> /usr/bin/convert
-- checking for execinfo -- found
-- checking for __builtin_clz -- yes
-- Testing code based on _awful

2016-04-11 16:07:53 W: Cannot reliably detect EOF on an GIOInputStream with this LGI version
Fontconfig error: "~/.fonts.conf", line 1: XML or text declaration not at start of entity
Fontconfig warning: "/etc/fonts/conf.d/50-user.conf", line 14: reading configurations from ~/.fonts.conf is deprecated. please move it to /home/hari/.config/fontconfig/fonts.conf manually

CMake Error at tests/examples/CMakeLists.txt:162 (message):
  
  /home/hari/tmpbuilds/awesome1/awesome/tests/examples/awful/placement/align.lua
  A test failed, bye
Call Stack (most recent call first):
  tests/examples/CMakeLists.txt:243 (run_test)
  tests/examples/CMakeLists.txt:235 (digg)
  tests/examples/CMakeLists.txt:235 (digg)
  tests/examples/CMakeLists.txt:264 (digg)
  awesomeConfig.cmake:306 (include)
  CMakeLists.txt:17 (include)


-- Configuring incomplete, errors occurred!
See also "/home/hari/tmpbuilds/awesome1/awesome/.build-lini-me-x86_64-linux-gnu-5.2.1/CMakeFiles/CMakeOutput.log".
See also "/home/hari/tmpbuilds/awesome1/awesome/.build-lini-me-x86_64-linux-gnu-5.2.1/CMakeFiles/CMakeError.log".
Makefile:22: recipe for target 'cmake' failed
make: *** [cmake] Error 1

**Comment by Elv13** [comment]
>2016-04-11 16:07:53 W: Cannot reliably detect EOF on an GIOInputStream with this LGI version
Fontconfig error: "~/.fonts.conf", line 1: XML or text declaration not at start of entity
Fontconfig warning: "/etc/fonts/conf.d/50-user.conf", line 14: reading configurations from ~/.fonts.conf is deprecated. please move it to /home/hari/.config/fontconfig/fonts.conf manually

Ok, so please execute

    mkdir -p /home/hari/.config/fontconfig/
    mv ~/.fonts.conf /home/hari/.config/fontconfig/fonts.conf

As the message told you to. It is still a problem with our new build system being a little too trigger happy. The obvious solution for this is to disable those tests unless a CMake config option is set.

**Comment by blueyed** [comment]
@Elv13 
Hmm, we should have a positive here also maybe, matching only errors from Awesome?!

**Comment by Elv13** [comment]
@blueyed If LGI cause the warning, it will be hard to "catch". Disabling these tests is probably a more practical workaround. Travis and our workstations provide a more predictable system while `some random user system` have too many potential issues for us to catch and white list. At the same time, it is good to know something is broken, but if there is too many false positive, it is too much trouble.

**Comment by psychon** [comment]
Plan B (or suggestion B): Only make this fail if Lua returns a non-zero exit status. Additionally, if on Travis (some environment variable is set), all messages on stdout/stderr could be made fatal. I think that this could even allow us to get rid of the special case for the "can't reliable detect EOF"-warning.

**Comment by actionless** [comment]
atm build is failing for me the different error:
```
-- Generating done
-- Build files have been written to: /home/lie/build/awesome-git/src/build
[  0%] Built target version_stamp
reading configuration from config.ld
file or directory does not exist: '/home/lie/build/awesome-git/src/docs/aliases/awful_client.lua'
CMakeFiles/ldoc.dir/build.make:159: recipe for target 'CMakeFiles/ldoc' failed
make[2]: *** [CMakeFiles/ldoc] Error 1
CMakeFiles/Makefile2:137: recipe for target 'CMakeFiles/ldoc.dir/all' failed
make[1]: *** [CMakeFiles/ldoc.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by psychon** [comment]
Whoops, I guess that is something that needs to be fixed... somehow.
Perhaps we should add some Travis target which does not use our cmake-`Makefile`-wrapper, but instead builds somewhere in `/tmp`...

**Comment by hexchain** [comment]
Can we make this Plan B real?

**Comment by blueyed** [comment]
https://github.com/awesomeWM/awesome/pull/885 has been merged.

@psychon 
What do you think needs to be fixed for 3.6 in this regard?

**Comment by psychon** [comment]
@blueyed The problem that @actionless had might be some problem in the Arch package if it's fixed by adding `cd ${pkgname}` in there. Sounds like that can be ignored. Also, this was not the problem that this issue originally was about.

What remains is "the tests in tests/examples are considered to have failed on any warning that they generate". Something should be done about this. My Plan B above was to only look at the exit status of Lua by default (so: warnings are just ignored) and only on travis is this more strict and warnings are considered as errors.

**Comment by actionless** [comment]
that wasn't problem in PKGBUILD -- i used that cd as a workaround but later on after some commit to cmake configs it started to build again without editing PKGBUILD

**Comment by Elv13** [comment]
Can this be closed?

**Comment by hexchain** [comment]
I'm sorry, but I don't think this is actually solved. Fontconfig warnings still break the test.

```
...
-- checking for execinfo -- found
-- Looking for round
-- Looking for round - not found
-- Looking for round
-- Looking for round - found
-- checking for round -- in libm
-- Checking for module 'dbus-1'
--   Found dbus-1, version 1.10.10
-- Running tests/examples/awful/mouse/coords.lua...
-- Running tests/examples/awful/placement/align.lua...

Fontconfig warning: "/etc/fonts/conf.d/52-felix-nonlatin.conf", line 16: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/52-felix-nonlatin.conf", line 31: Having multiple values in <test> isn't supported and may not work as expected

CMake Error at tests/examples/CMakeLists.txt:162 (message):
  
  /tmp/yaourt-tmp-hexchain/aur-awesome-git/src/awesome-git/tests/examples/awful/placement/align.lua
  A test failed, bye
Call Stack (most recent call first):
  tests/examples/CMakeLists.txt:238 (run_test)
  awesomeConfig.cmake:310 (include)
  CMakeLists.txt:17 (include)


-- Configuring incomplete, errors occurred!
```

**Comment by psychon** [comment]
What does your `/etc/fonts/conf.d/52-felix-nonlatin.conf` contain? (The idea being: What do I have to write into that file so that fontconfig generates a warning and I can reproduce this and fix it in a way that still makes sure that no warnings appear on travis?)

**Comment by hexchain** [comment]
Easy, just put multiple values in `<test>` block, and save as something like `52-.conf` in `~/.config/fontconfig/conf.d`:
```
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
    <match target="pattern">
        <test qual="any" name="family">
            <string>serif</string>
            <string>another-serif</string>
        </test>

        <edit binding="weak" mode="prepend" name="family">
            <string>DejaVu Serif</string>
        </edit>
    </match>
</fontconfig>
```

**Comment by psychon** [comment]
I can reproduce this problem with the above file, thanks! Now I just need the time to fix this (or someone else does so...).
