### ISSUE TITLE
string concatenation after awful.util.pread not working

### ISSUE THREAD

**Issue by AlphaFoxAlpha** [awesomeWM/awesome#839]
I have a problem doing a string concatenation after using awful.util.pread(). Anything after the pread-variable is cut off.
Here is a quick example:

`testbox = wibox.widget.textbox()`
`local testvar = awful.util.pread('echo "1234"')`
`testbox:set_markup("pre " .. testvar .. " post")`

The output of this widget is only
>  pre 1234

but in my opinion it should display
>   pre 1234 post

**Comment by psychon** [comment]
Line break at the end?
Try `echo -n` instead.

**Comment by AlphaFoxAlpha** [comment]
Thank you very much for your hint. The newline was the problem.
