### ISSUE TITLE
Menubar cannot handle special pattern characters

### ISSUE THREAD

**Issue by roysc** [awesomeWM/awesome#84]
Entering a "magic character" for Lua patterns in the menubar causes it to freeze and issue an error, e.g., after entering only a "%":
```
W: awesome: event_handle_key:586: error running function: /usr/share/awesome/lib/menubar/init.lua:140: malformed pattern (ends with '%')
```
The menubar then can't be closed without reloading Awesome.

**Comment by roysc** [comment]
Problem characters: `% [ ( )`

**Comment by blueyed** [comment]
Thanks for the report!

See my PR for a (possibly rough) fix.
