### ISSUE TITLE
make check fails on test-spawn-snid.lua

### ISSUE THREAD

**Issue by Jajauma** [awesomeWM/awesome#848]
Doing `make check` of the current master (2ccc7c8) fails on my system on a step which tests the startup notifications. The complete build and run logs are in the attach.  

Adding a `print()` statement to the Step 1 of the offending test reveals that [c_snid](https://github.com/awesomeWM/awesome/blob/master/tests/test-spawn-snid.lua#L22) happens to be nil for some reason, hence the failure.

[test-failure.txt](https://github.com/awesomeWM/awesome/files/233635/test-failure.txt)

**Comment by Elv13** [comment]
Hello,

This test is known to be currently broken on some distributions because of the compilation flags they use on our test program. I will change it for a less fragile one. Thanks for reporting this.

**Comment by Jajauma** [comment]
As of 6b6cbf4 I've got yet another test case failing. This time it is test-resize.lua, at the lines [here](https://github.com/awesomeWM/awesome/blob/master/tests/test-resize.lua#L279) and [here](https://github.com/awesomeWM/awesome/blob/master/tests/test-resize.lua#L297). Assertions fail because they try to compare the numbers like 395 and 394,5. Wrapping the divisions with a `math.ceil()` call makes this test pass for me. 
```patch
diff --git a/tests/test-resize.lua b/tests/test-resize.lua
index a9eb716..18613b1 100644
--- a/tests/test-resize.lua
+++ b/tests/test-resize.lua
@@ -276,7 +276,7 @@ table.insert(steps, function()
     local c = client.get()[1]
 
     assert(c:geometry().x      == c.screen.workarea.x                                     )
-    assert(c:geometry().y      == c.screen.workarea.y+c.screen.workarea.height/2          )
+    assert(c:geometry().y      == math.ceil(c.screen.workarea.y+c.screen.workarea.height/2))
     assert(c:geometry().width  == c.screen.workarea.width - 2*c.border_width              )
     assert(c:geometry().height == math.ceil(c.screen.workarea.height/2 - 2*c.border_width))
 
@@ -294,7 +294,7 @@ table.insert(steps, function()
     local c = client.get()[1]
 
     assert(c:geometry().x       == c.screen.workarea.x                                     )
-    assert(c:geometry().y       == c.screen.workarea.y+c.screen.workarea.height/2          )
+    assert(c:geometry().y       == math.ceil(c.screen.workarea.y+c.screen.workarea.height/2))
     assert(c:geometry().width   == math.ceil(c.screen.workarea.width/2 - 2*c.border_width) )
     assert(c:geometry().height  == math.ceil(c.screen.workarea.height/2 - 2*c.border_width))
```
The test-spawn-snid.lua test is sill failing.

**Comment by psychon** [comment]
Hrm, perhaps we should start the X server for the test with a non-divisible-by-two width and height to make such issues more likely to occur?

**Comment by Elv13** [comment]
> Hrm, perhaps we should start the X server for the test with a non-divisible-by-two width and height to make such issues more likely to occur?

Or maybe extend the test framework to be able to run geometry sensitive tests multiple time with different screen size? Xephyr support live screen resizing. As an useful side effect, it will also help test screen resizing (currently uncovered, since support for that was merged a few hours ago)

**Comment by blueyed** [comment]
Good idea, done in https://github.com/awesomeWM/awesome/pull/870 for a single build job only.

**Comment by blueyed** [comment]
#870 still fails, so there seems to be another issue still.

**Comment by Jajauma** [comment]
@blueyed The offender step 14/23 has got another unrounded division [by 2](https://github.com/awesomeWM/awesome/blob/master/tests/test-resize.lua#L242) as well as 15/23 [do](https://github.com/awesomeWM/awesome/blob/master/tests/test-resize.lua#L260). I didn't touch those since they are passing on my system and I can't tell for sure whether they are just odds and ends of https://github.com/awesomeWM/awesome/issues/848#issuecomment-216052517 or we have a separate issue. Should we try to ceil them too?
```patch
diff --git a/tests/test-resize.lua b/tests/test-resize.lua
index 18613b1..d7c8085 100644
--- a/tests/test-resize.lua
+++ b/tests/test-resize.lua
@@ -239,7 +239,7 @@ end)
 table.insert(steps, function()
     local c = client.get()[1]
 
-    assert(c:geometry().x       == c.screen.workarea.x+c.screen.workarea.width/2           )
+    assert(c:geometry().x       == math.ceil(c.screen.workarea.x+c.screen.workarea.width/2))
     assert(c:geometry().y       == c.screen.workarea.y                                     )
     assert(c:geometry().width   == math.ceil(c.screen.workarea.width/2 - 2*c.border_width) )
     assert(c:geometry().height  == math.ceil(c.screen.workarea.height/2 - 2*c.border_width))
@@ -257,7 +257,7 @@ end)
 table.insert(steps, function()
     local c = client.get()[1]
 
-    assert(c:geometry().x       == c.screen.workarea.x+c.screen.workarea.width/2          )
+    assert(c:geometry().x       == math.ceil(c.screen.workarea.x+c.screen.workarea.width/2))
     assert(c:geometry().y       == c.screen.workarea.y                                    )
     assert(c:geometry().width   == math.ceil(c.screen.workarea.width/2 - 2*c.border_width))
     assert(c:geometry().height  == c.screen.workarea.height - 2*c.border_width            )
```

**Comment by blueyed** [comment]
Re-opening.  If I understand it correctly, #875 only mentions "let's fix #848".

@Jajauma 
I'd say that this fix is good.  Do you want to create a PR, or should I commit it for you?

**Comment by psychon** [comment]
@blueyed #875 fixes this issue (tests require urxvt build with SN support). The above comment is about another issue, which somehow ended up entangled with this. I guess that this issue is now about the "uneven geometry"-problem...

**Comment by Jajauma** [comment]
Yeah, I am sorry since this turned out to be extremly troublesome for all of us. This is actually my very first time on GitHub, but I have already learned a lesson not to mix multiple issues into one.
@blueyed I've got a PR fixing the rest of those divisions submitted here https://github.com/awesomeWM/awesome/pull/882, and it looks like that CI thing of ours is happy now!

**Comment by Jajauma** [comment]
I guess this can be safely closed now since https://github.com/awesomeWM/awesome/pull/870 is passing. Thank you very much for your time.
