### ISSUE TITLE
The menubar doesn't show any applications anymore

### ISSUE THREAD

**Issue by Jajauma** [awesomeWM/awesome#863]
The menubar (Mod+p) doesn't work for me anymore on the latest master (a1e340d currently). It doesn't show any applications. It still does show the category entries though.

Here are some screenshots from a1e340d:
![menubar1-a1e340d](https://cloud.githubusercontent.com/assets/11892063/14935425/571b1c52-0ee2-11e6-83e8-b54bcbec1880.png)
![menubar2-a1e340d](https://cloud.githubusercontent.com/assets/11892063/14935426/5e7fb34a-0ee2-11e6-90a1-a0d8b1477259.png)
It couldn't find firefox and others on the second picture when I type `f`, `i`. Compare with the known good revision (namely, 951e030 which I use ATM):
![menubar1-951e030](https://cloud.githubusercontent.com/assets/11892063/14935434/a55d08c6-0ee2-11e6-96ba-c0faf3d8c923.png)
![menubar2-951e030](https://cloud.githubusercontent.com/assets/11892063/14935435/a9727766-0ee2-11e6-9eef-c50c1beb0419.png)
(Disregard the difference in the icon resolution since my copy of 951e030 is patched).

I tried bisecting the range and the git checks stopped somewhere at 4eb8085, which I couldn't test at all because it fails to start. It apparently seems to be related to the menubar functionality, however. All of the git checks up until 4eb8085 were "good".

The [xsession-errors.txt](https://github.com/awesomeWM/awesome/files/243562/xsession-errors.txt)  right after the login.

**Comment by actionless** [comment]
could you try building latest git master of `lgi` and try again?

**Comment by Jajauma** [comment]
1. Trying the latest lgi (https://github.com/pavouk/lgi/commit/2c5e63d0d4158fe083579a08663008b495d019ad) made completely no difference compared to the 0.9.0 release which I normally run AWM with.
2. That `parser()` function seems to not enter any of the `if`'s you expected it to do. When I change the code to
```
local enum, err = f:async_enumerate_children("standard::name", gio.FileQueryInfoFlags.NONE)
print('enum = ', enum, ' err = ', err)
```
and then hit Mod+p under the test instance running on Xephyr it gives me lines like
```
enum = 	lgi.obj 0x297ecf0:Gio.FileEnumerator(GLocalFileEnumerator)	 err = 	nil
enum = 	lgi.obj 0x297eda0:Gio.FileEnumerator(GLocalFileEnumerator)	 err = 	nil
enum = 	lgi.obj 0x297ee50:Gio.FileEnumerator(GLocalFileEnumerator)	 err = 	nil
```
Still no application entries though.

**Comment by Jajauma** [comment]
It looks like I managed to find something: `info:get_file_type()` (https://github.com/awesomeWM/awesome/blob/master/lib/menubar/utils.lua#L270) returns 'UNKNOWN' but no 'REGULAR'. `file_path`s are correct and point to my actual *.desktop files.

**Comment by Jajauma** [comment]
And finally changing the code in utils.lua as follows
```patch
diff --git a/lib/menubar/utils.lua b/lib/menubar/utils.lua
index 20d6180..4c649db 100644
--- a/lib/menubar/utils.lua
+++ b/lib/menubar/utils.lua
@@ -254,7 +254,7 @@ function utils.parse_dir(dir_path, callback)
     local function parser(dir, programs)
         local f = gio.File.new_for_path(dir)
         -- Except for "NONE" there is also NOFOLLOW_SYMLINKS
-        local enum, err = f:async_enumerate_children("standard::name", gio.FileQueryInfoFlags.NONE)
+        local enum, err = f:async_enumerate_children("standard::*", 'NONE')
         if not enum then
             debug.print_error(err)
             return

local enum, err = f:async_enumerate_children("standard::*", 'NONE')
```
seems to fix the issue for me. I have a quite vague idea what the former or the latter actually does, just picked the working line from [one of the lgi samples](https://github.com/pavouk/lgi/blob/master/samples/gtk-demo/demo-iconview-basics.lua#L106).

**Comment by psychon** [comment]
Whoops, my fault, I guess. We use the name and the file type, so should query for both.
Can you try changing the string to `"standard::name,standard::type"`?

(Off-topic: Does `gio.FILE_ATTRIBUTE_STANDARD_NAME .. "," .. gio.FILE_ATTRIBUTE_STANDARD_TYPE` look better than `"standard::name,standard::type"` because it feels a bit less hardcoded?)

Just out of interest: Which glib version do you have installed and what filesystem are you using?
I'm asking for the filesystem because of the following part of `man readdir`:

> d_type This field contains a value indicating the file type, making it possible to avoid the expense of calling lstat(2) if further actions depend on the type of the file.
> ...
>               Currently, only some filesystems (among them: Btrfs, ext2, ext3, and ext4) have full support for returning the file type in d_type.  All applications must properly  handle a return of DT_UNKNOWN.

**Comment by Jajauma** [comment]
I've tried `f:async_enumerate_children("standard::name,standard::type", gio.FileQueryInfoFlags.NONE)` and `f:async_enumerate_children("standard::name,standard::type", 'NONE')` and both work just fine and our lovely menu is back. Seems that querying that `type` thing is crucial for the rest of the code to work.

I run CentOS 7 with glib 2.42 and use XFS which is the vendor default.
