### ISSUE TITLE
License is currently not valid, the content of the License template wasn't changed.

### ISSUE THREAD

**Issue by toogley** [awesomeWM/awesome#867]
[The License shows](https://github.com/awesomeWM/awesome/blob/master/LICENSE#L332) currently:

>   Yoyodyne, Inc., hereby disclaims all copyright interest in the program
>   `Gnomovision' (which makes passes at compilers) written by James Hacker.
> 
>   <signature of Ty Coon>, 1 April 1989
>   Ty Coon, President of Vice

As this is still the unchanged content of the template, i don't think the License is valid.

**Comment by psychon** [comment]
Let's quote the sentence before the part that you cite:

    You should also get your employer (if you work as a programmer) or your
    school, if any, to sign a "copyright disclaimer" for the program, if
    necessary.  Here is a sample; alter the names:
    
      Yoyodyne, Inc., hereby disclaims all copyright interest in the program
      `Gnomovision' (which makes passes at compilers) written by James Hacker.
    
      <signature of Ty Coon>, 1 April 1989
      Ty Coon, President of Vice

To add some emphasis: "*if* you work as a programmer" and "*if* necessary"
Is that clear enough?

Also, let me quote the first 7 lines of `LICENSE`:

   		    GNU GENERAL PUBLIC LICENSE
   		       Version 2, June 1991
   
    Copyright (C) 1989, 1991 Free Software Foundation, Inc.,
    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
    Everyone is permitted to copy and distribute verbatim copies
    of this license document, but changing it is not allowed.

Again some emphasis: "but changing it is not allowed."
We aren't even legally allowed to modify the contents of that file!

Feel free to explain yourself and point out which part I am missing.

P.S.: The kernel's license is invalid! https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/tree/COPYING?id=b3358a116c25267446a45e4164cb2b8e98276da0#n346

**Comment by toogley** [comment]
Oh, sorry. I didn't read that part carefully enough.
