### ISSUE TITLE
layoutbox: fallback to textbox in case the image cannot be loaded

### ISSUE THREAD

**Issue by blueyed** [awesomeWM/awesome#896]
If the layoutbox' imagebox fails to load the image(s) (because the path in `theme.layout_*` is wrong), you end up with a layoutbox of 0x0 px.

I think that there should be a placeholder / indicator in this case - maybe falling back to displaying some text?! (e.g. by replacing the imagebox with a textbox)

What do you think?

**Comment by psychon** [comment]
Sounds good. Broken themes should never happen, but they do happen too often...

**Comment by Elv13** [comment]
Done in my dynamic layout branch, I will submit a proper PR at some point
