### ISSUE TITLE
floatingbutton, maximizedbutton, minimizebutton, ... on  titlebar does not work?

### ISSUE THREAD

**Issue by wxg4net** [awesomeWM/awesome#905]
version: git
rc.lua and theme.lua all are default files.
when i click these buttons,  not work. but tooltip worked.

a1918b83 lib/awful/titlebar.lua.in (Uli Schlachter   2012-10-23 20:32:59 +0200 242) ret:buttons(abutton({ }, 1, nil, function() action(c, selector(c)) end))
=> not work

**Comment by psychon** [comment]
No idea what went wrong in your edit, but the problem described in the original version of this message is fixed by https://github.com/awesomeWM/awesome/pull/901

**Comment by blueyed** [comment]
@wxg4net 
Can you update master and test it again?  #901 is merged now.

**Comment by wxg4net** [comment]
it worked. thx
