### ISSUE TITLE
Wibar ignores some arguments for wibox construction

### ISSUE THREAD

**Issue by actionless** [awesomeWM/awesome#916]
for example, `visible` is hardcoded to `true` so you have to set it after creating a widget

and the rest of args is just skipped:
```
border_width
border_color
ontop 	
cursor 	
opacity 
x 	
y 	
drawable 	
widget 	
window 	
shape_bounding 
shape_clip     
bg 	
bgimage 
fg 	
```

mb in `wibar.new()` we can iterate through args and assign them all to a newly created wibar?

**Comment by psychon** [comment]
Looking at the code I thought "this has to work". Then I thought: Could someone please try changing line 344 of lua/awful/wibar.lua from `function awfulwibar.mt:__call(...)` into `function awfulwibar.mt:__call(_, ...)` and check if this fixes this issue?

**Comment by actionless** [comment]
sorry, my bad, the problem was only with visible, so `if arg.visible == nil then w.visible = true end` should address the problem

**Comment by funeralismatic** [comment]
bgimage not work.

**Comment by Elv13** [comment]
@funeralismatic That one isn't a regression, it just wasn't a feature. Anyway, I fixed that.

**Comment by actionless** [comment]
sorry, closed by mistake
