### ISSUE TITLE
Can't set position for wibox no more

### ISSUE THREAD

**Issue by actionless** [awesomeWM/awesome#917]
I was using `set_position` from `awful.wibox` to set a position of a wibox (menubar to be precise)
After wibar refactoring that method became deprecated (because it's param of wibar instance).
But wibox instance don't have that param and calling awful.wibar.set_position on wibox is making it to behave as a wibar (ie displayed as a panel instead of floating).

I think it can be workarounded at the moment by overriding client type for that wibox, but i am wondering what could be a solution to address the problem (assigning some position like 'top' or 'bottom' to wibox, not only wibar) correctly.

Mb we could move all the position logic from wibar to wibox?

**Comment by psychon** [comment]
Isn't this 'just' `(awful.placement.top + awful.placement.maximize_horizontally)(wb)`? (Hm, perhaps some more magic for the workarea? I'm not sure)

**Comment by actionless** [comment]
how could i pass placement to the wibox?

**Comment by actionless** [comment]
ah, calling placement itself

**Comment by Elv13** [comment]
Sorry about this. I should have been more careful to reproduce the previous behavior instead of simply deprecating this with little regards to backward compatibility. I now published a PR that try to fix this oversaw.
