### ISSUE TITLE
Windows snapping problem.

### ISSUE THREAD

**Issue by jk411** [awesomeWM/awesome#928]
In floating layout window snapping doesn't work properly when dragged window is
attached to top or left side of the static one.
This happens only when border_width != 0.
Windows borders overlap each other.

Tested in ver. 3.5.8, 3.5.9 and master.

**Comment by jk411** [comment]
Snapping functions are the same: snap_inside, snap_outside and module.snap
Snap_inside and snap_outside don't know anything about borders so it looks like window size and position is adjusted before snapping in snap_...
but lines
227: geom.x = geom.x - (2 * c.border_width)
228: geom.y = geom.y - (2 * c.border_width)
and
238: geom.x = geom.x + (2 * c.border_width)
239: geom.y = geom.y + (2 * c.border_width)
work correctly only for the snapping from left and bottom sides.

Snapping in function snap_inside is not fully "symmetric":
164:    if math.abs(g.x) < snap + sg.x and g.x > sg.x then
167:    elseif math.abs((sg.x + sg.width) - (g.x + g.width)) < snap then
windows snap differently when dragged when their part was outside screen
this full line abs in 167 makes a difference.

How about extra line:
        geom = snap_inside(geom, snapper:geometry(), snap)
232: geom = snap_outside(geom, snapper:geometry(), snap)
that would enable snapping windows inside bigger windows.

Small note:
99:    -O1 -std=gnu99 -ggdb3 -fno-strict-aliasing -Wall -Wextra
in CMakeLists.txt. I think that -O1 overrides preceding -O[23].
Checked with export VERBOSE=1.

Thanks

**Comment by psychon** [comment]
I can reproduce this with 3.5.9. I can't test with master right now, so I don't know if this was fixed.

For testing, I did `echo 'client.focus.border_width = 42' | awesome-client` in two terminals and dragged them around.

@jk411 Sorry, I don't understand. Could you provide diffs instead?
And yeah, `lib/awful/mouse/init.lua` looks weird where it does `geom.x = geom.x - (2 * c.border_width)`. It should only subtract the border width here ones. I guess the following for-loop has to fix up the geometry of other clients as well (why, just why, does X11 not include the border in the client's geometry?)

**Comment by jk411** [comment]
[patch.txt](https://github.com/awesomeWM/awesome/files/289939/patch.txt)
This ugly patch is for 3.5.8 version but these functions are the same in 3.5.9+
This redundant -O1 option is of course in awesomeConfig.cmake.
