### ISSUE TITLE
Cannot launch awesome using non default config dir

### ISSUE THREAD

**Issue by yuggmatt** [awesomeWM/awesome#930]
Awesome crashes when trying to launch it using another config dir from ~/.config/awesome.

With a freshly built master branch, from the build dir:

```
$ ./awesome --version
awesome v3.5.2-1720-ge8da309 (The Fox)
 • Compiled against Lua 5.3.1 (running with Lua 5.3)
 • D-Bus support: ✔
```
And:

```
$ DISPLAY=:1.0 ./awesome -c ~/.config/awesome-git/rc.lua
2016-05-30 00:05:48 W: awesome: screen_scan_randr_crtcs:372: Ignoring RandR, only a compatibility layer is present.
error while running function!
stack traceback:
	[C]: in function 'require'
	/home/matteo/.config/awesome-git/rc.lua:2: in main chunk
error: /home/matteo/.config/awesome-git/rc.lua:2: module 'gears' not found:
	no field package.preload['gears']
	no file '/usr/local/share/lua/5.3/gears.lua'
	no file '/usr/local/share/lua/5.3/gears/init.lua'
	no file '/usr/local/lib/lua/5.3/gears.lua'
	no file '/usr/local/lib/lua/5.3/gears/init.lua'
	no file '/usr/share/lua/5.3/gears.lua'
	no file '/usr/share/lua/5.3/gears/init.lua'
	no file './gears.lua'
	no file './gears/init.lua'
	no file '/home/matteo/.config/awesome/gears.lua'
	no file '/home/matteo/.config/awesome/gears/init.lua'
	no file '/etc/xdg/awesome/gears.lua'
	no file '/etc/xdg/awesome/gears/init.lua'
	no file '/usr/local/share/awesome/lib/gears.lua'
	no file '/usr/local/share/awesome/lib/gears/init.lua'
	no file '/usr/local/lib/lua/5.3/gears.so'
	no file '/usr/lib/x86_64-linux-gnu/lua/5.3/gears.so'
	no file '/usr/lib/lua/5.3/gears.so'
	no file '/usr/local/lib/lua/5.3/loadall.so'
	no file './gears.so'
error while running function!
stack traceback:
	[C]: in function 'require'
	/home/matteo/.config/awesome/rc.lua:2: in main chunk
error: /home/matteo/.config/awesome/rc.lua:2: module 'gears' not found:
	no field package.preload['gears']
	no file '/usr/local/share/lua/5.3/gears.lua'
	no file '/usr/local/share/lua/5.3/gears/init.lua'
	no file '/usr/local/lib/lua/5.3/gears.lua'
	no file '/usr/local/lib/lua/5.3/gears/init.lua'
	no file '/usr/share/lua/5.3/gears.lua'
	no file '/usr/share/lua/5.3/gears/init.lua'
	no file './gears.lua'
	no file './gears/init.lua'
	no file '/home/matteo/.config/awesome/gears.lua'
	no file '/home/matteo/.config/awesome/gears/init.lua'
	no file '/etc/xdg/awesome/gears.lua'
	no file '/etc/xdg/awesome/gears/init.lua'
	no file '/usr/local/share/awesome/lib/gears.lua'
	no file '/usr/local/share/awesome/lib/gears/init.lua'
	no file '/usr/local/lib/lua/5.3/gears.so'
	no file '/usr/lib/x86_64-linux-gnu/lua/5.3/gears.so'
	no file '/usr/lib/lua/5.3/gears.so'
	no file '/usr/local/lib/lua/5.3/loadall.so'
	no file './gears.so'
error while running function!
stack traceback:
	[C]: in function 'require'
	/etc/xdg/awesome/rc.lua:2: in main chunk
error: /etc/xdg/awesome/rc.lua:2: module 'gears' not found:
	no field package.preload['gears']
	no file '/usr/local/share/lua/5.3/gears.lua'
	no file '/usr/local/share/lua/5.3/gears/init.lua'
	no file '/usr/local/lib/lua/5.3/gears.lua'
	no file '/usr/local/lib/lua/5.3/gears/init.lua'
	no file '/usr/share/lua/5.3/gears.lua'
	no file '/usr/share/lua/5.3/gears/init.lua'
	no file './gears.lua'
	no file './gears/init.lua'
	no file '/home/matteo/.config/awesome/gears.lua'
	no file '/home/matteo/.config/awesome/gears/init.lua'
	no file '/etc/xdg/awesome/gears.lua'
	no file '/etc/xdg/awesome/gears/init.lua'
	no file '/usr/local/share/awesome/lib/gears.lua'
	no file '/usr/local/share/awesome/lib/gears/init.lua'
	no file '/usr/local/lib/lua/5.3/gears.so'
	no file '/usr/lib/x86_64-linux-gnu/lua/5.3/gears.so'
	no file '/usr/lib/lua/5.3/gears.so'
	no file '/usr/local/lib/lua/5.3/loadall.so'
	no file './gears.so'
2016-05-30 00:05:48 E: awesome: main:704: couldn't find any rc file
```

Here, the lib file is not looked after in ~/.config/awesome-git but in ~/.config-awesome.

**Comment by Elv13** [comment]
Some more details

On IRC I assumed that ln -a gears, awful... in another folder config would work, but apparently, it only work with ~/.config/awesome (assuming it is the issue).

**Comment by psychon** [comment]
If I understand this correctly, you are trying to run awesome without installing it. The problem is that the `-c`-flag does not influence the Lua search path, but only the config file is taken from there. I *think* that setting the following environment variable *could* help, but I am not totally sure: `XDG_CONFIG_DIR=$HOME/.config-awesome/` (this replaces `~/.config` with this value)

Alternatively, I think you could just do the following in your rc.lua:
```
local prefix = os.getenv("HOME") .. `/.config-awesome/`
package.path = package.path .. ";" .. prefix .. "?.lua;" .. prefix .. "?/init.lua"
```
What this really boils down to is the flag that https://github.com/awesomeWM/awesome/pull/485 wants to add.

(And no, we don't exactly make it easy to run awesome without installing it; I'd recommend to just install it, perhaps with prefix set to `$HOME/my-awesome-installation`)

**Comment by yuggmatt** [comment]
Yes, you guessed right: I want to run the master branch of awesome without installing it. I just want to test it, and keep the stable one installed.
None of the solution you proposed worked. The second one allowed to go one step further, but new errors related to missing libs are raised:
```
error: /home/matteo/.config/awesome-git/gears/color.lua:16: module 'lgi' not found:
```
I will do my tests in a VM.

**Comment by psychon** [comment]
The test runner does the following to run awesome without installing it:
```
export LUA_PATH="$(lua -e 'print(package.path)');lib/?.lua;lib/?/init.lua"
```
For your case, this could be changed into
```
AWESOME_SOURCE_DIR="$HOME/whatever"
AWESOME_BUILD_DIR="$AWESOME_SOURCE_DIR/build"
export LUA_PATH="$(lua -e 'print(package.path)');$AWESOME_BUILD_DIR/lib/?.lua;$AWESOME_BUILD_DIR/lib/?/init.lua"
```
(where AWESOME_SOURCE_DIR is the directory with awesome's source, thus that + `build/` should contain the build libraries).

I haven't tested this.

**Comment by psychon** [comment]
@yuggmatt No idea about lgi, I would guess that running `lua -e 'require("lgi")'` also fails and you don't have lgi installed. However... somehow I doubt that.

**Comment by ff2000** [comment]
On Mon, 30 May 2016 01:52:28 -0700, Uli Schlachter <notifications@github.com> wrote:
> @yuggmatt No idea about lgi, I would guess that running `lua -e 'require("lgi")'` also fails and you don't have lgi installed. However... somehow I doubt that.

There might be different versions of lua installed in your system and the system-version of awesome uses the correct one (which the distro builds its lua modules for) and your locally built awesome uses a different lua version.

**Comment by yuggmatt** [comment]
ff2000, yes this is exactly that.

- I built awesome against lua5.3
- debian does not provide lgi for lua 5.3

Switching back to lua 5.2...

**Comment by yuggmatt** [comment]
Symlinking gears, awful... in another config folder, then adding
```
local prefix = os.getenv("HOME") .. `/.config-awesome/`
package.path = package.path .. ";" .. prefix .. "?.lua;" .. prefix .. "?/init.lua"
```
at the top of this new config folder's rc.lua

works when awesome is properly compiled with lua5.2 on debian sid.

So there were two things in this issue:
1. I compiled awesome against lua 5.3, and lgi does not work (yet) with lua5.3
2. Psychon you are right, it all boils down to #485 

I am closing this issue. Having the feature described in #485 would be ideal, yet the workaround consisting in symlinking a few dirs and adding two lines in rc.lua is good enough for testing purpose.
