### ISSUE TITLE
My config broke

### ISSUE THREAD

**Issue by psychon** [awesomeWM/awesome#933]
Symptom is (besides the wibox not being properly drawn):
```
2016-05-31 17:17:26 E: Error during a protected call: ...e/psychon/projects/awesome/build/lib/wibox/hierarchy.lua:310: bad argument #2 to 'paint_with_alpha' (number expected, got table)
stack traceback:
	...chon/projects/awesome/build/lib/gears/protected_call.lua:17: in function <...chon/projects/awesome/build/lib/gears/protected_call.lua:16>
	[C]: in function 'paint_with_alpha'
	...e/psychon/projects/awesome/build/lib/wibox/hierarchy.lua:310: in function 'draw'
	...e/psychon/projects/awesome/build/lib/wibox/hierarchy.lua:301: in function 'draw'
	...e/psychon/projects/awesome/build/lib/wibox/hierarchy.lua:301: in function 'draw'
	...e/psychon/projects/awesome/build/lib/wibox/hierarchy.lua:301: in function 'draw'
	/home/psychon/projects/awesome/build/lib/wibox/drawable.lua:142: in function 'do_redraw'
	/home/psychon/projects/awesome/build/lib/wibox/drawable.lua:338: in function </home/psychon/projects/awesome/build/lib/wibox/drawable.lua:336>
	[C]: in function 'xpcall'
	...chon/projects/awesome/build/lib/gears/protected_call.lua:37: in function <...chon/projects/awesome/build/lib/gears/protected_call.lua:36>
	(...tail calls...)
	/home/psychon/projects/awesome/build/lib/gears/timer.lua:158: in function </home/psychon/projects/awesome/build/lib/gears/timer.lua:156>
```
Adding some debug `print`s and `gears.debug.dump`s shows that instead of the opacity this gets a progressbar widget. Even funnier is that the output of `print(widget, widget:get_opacity())` is `table: 0x2557a20	table: 0x2557a20`, meaning that `:get_opacity()` returns the widget itself.
Another funny thing: Adding a `print` inside of `wibox.widget.base.widget.get_opacity` shows that this function is being called and returns the correct value, meaning that something in the general property support must be broken.

Git bisect says that the first bad commit is (but that's likely because this commit actually causes the new code to be run, not before things weren't broken before):
```
commit 542070205f34b82c3eb57e178589d63d5be32f5b
Author: Emmanuel Lepage Vallee <elv1313@gmail.com>
Date:   Thu May 26 13:57:34 2016 -0400

    widget: Add proper accessors for the 'opacity' property
    
    To avoid collision with the property system and comply with the
    API guidelines.

:040000 040000 4c24f4e8f79c138ac093926fde35fc8a7fc88315 d21d90e00d8d1a71962bd609d9a58584f51b8c65 M	lib
```

Unrelated problem: In lots of commits the unit tests fails, making bisecting unnecessary hard. I think I pointed out that the change fixing the unit tests wasn't in the right commit and now this is quite annoying...

**Comment by psychon** [comment]
Sigh. It is obvious which broke due to this change. It wraps a widget in an empty table with the following `__index` operation (`obvious.lib.widget.from_data_source`):
```
    meta.__index = function (obj, key)
        local ret = obj[1][key]
        if key ~= "layout" and type(ret) == "function" then
            -- Ugly hack: this function wants to be called on the right object
            return function(_, ...)
                -- Ugly hack: this function wants to be called on the right object
                ret(obj[1], ...)
                -- Ugly hack 2: We force obj to be returned again and discard
                -- the function's return value
                return obj
            end
        end
        return ret
    end
```
Hack 2 is what causes this breakage.

**Comment by Elv13** [comment]
> Unrelated problem: In lots of commits the unit tests fails, making bisecting unnecessary hard. I think I pointed out that the change fixing the unit tests wasn't in the right commit and now this is quite annoying...

Sorry, I should have been more careful...

**Comment by blueyed** [comment]
As for breaking the git-bisect, we could run the tests on every commit for a PR.
This could be achieved using `git-bisect run` probably, and could be done only for one of the variants.

**Comment by psychon** [comment]
I guess this will have to be fixed in obvious. My ugly hack from 2009 will have to go.
@hoelzro What awesome versions is obvious supposed to work with? Can this hack be replaced by e.g. a `wibox.widget.background` widget without a background set? (This would allow to change the visible widget via `:set_widget()`)

@blueyed How much would that scare away people who just add new commits to their PR instead of rewriting history? You are the one who taught me about `git commit --fixup` :-) I'm not sure if we really want that.

**Comment by hoelzro** [comment]
@psychon Ugh...I hate that hack and would be extremely happy to see it go.  I wanted to remove it already, but I didn't know how many configs it would break.  I'm sure we can figure out a better way to do things.

Obvious is intended to work with the latest release of Awesome; if people are staying on earlier releases, I will support them provided it's not terribly difficult.

**Comment by psychon** [comment]
@hoelzro Apropos commit ab93397862e9438bb938c2de0be7d1be515fcc19 "Get rid of ugly from_data_source hack": I think I wanted something like `w:set_type("progressbar"):set_max_value(42)` to work when writing this. Glad to see that this hack is gone. This should already solve the problem in this bug report, I just have to update my ancient version of obvious (I think that it is still stuck in 2009 or 2010).

For getting rid of the remaining hack... I don't know how. This `ret[1]` stuff is still from awesome 3.4 (or 3.3?) where just doing this was enough (the code recursively walked tables looking for widget objects). Something like https://gist.github.com/psychon/586a724ce9ee0c954f27e024893c5155 changes things, but I'm not sure if it actually makes stuff better. Same for https://gist.github.com/psychon/03a6ca91e5cdeb4102681c6067591c77, but this surely breaks things for older awesome releases.

Closing this bug report since apparently it was a case of "psychon is using 5 years old code which finally broke".
