### ISSUE TITLE
Run tests against every commit in PRs

### ISSUE THREAD

**Issue by blueyed** [awesomeWM/awesome#935]
Ref: https://github.com/awesomeWM/awesome/issues/933#issuecomment-222802531

**Comment by Elv13** [comment]
Wont that cause the test time to take hours?

**Comment by blueyed** [comment]
Only for one variant maybe.
But then the tests are not the slow part after all, and not all PRs have 68 commits.. :)

**Comment by blueyed** [comment]
Closing this in favor of #936.
