### ISSUE TITLE
Travis: do not run check if check-coverage is run?!

### ISSUE THREAD

**Issue by blueyed** [awesomeWM/awesome#938]
Currently for the DO_COVERAGE target `check` is effectively being run twice:

https://github.com/awesomeWM/awesome/blob/eab71038cb4637fb19958de3d79aa0d2f57b7758/.travis.yml#L102-L108

I think we could skip `make check` in that case?!

**Comment by psychon** [comment]
Heh, why me? :-)
The following patch should be enough for this, shouldn't it?
```diff
diff --git a/.travis.yml b/.travis.yml
index f769b9b..0d5a7a8 100644
--- a/.travis.yml
+++ b/.travis.yml
@@ -99,7 +99,8 @@ script:
         cd "$BUILD_IN_DIR"
         cmake $CMAKE_ARGS "$SOURCE_DIRECTORY"
     fi
-  - make && sudo env PATH=$PATH make install && awesome --version && make check
+  - make && sudo env PATH=$PATH make install && awesome --version
+  - if [ "$DO_COVERAGE" != "true" ]; then make check ; fi
   - |
     if [ "$DO_COVERAGE" = "true" ]; then
         make check-coverage || exit 1;
```

**Comment by blueyed** [comment]
Yes, basically.  See #940.  It should not get done if the building failed already.

> Heh, why me? :-)

Just wanted to know if this was intentionally maybe, e.g. because running it with coverage might accidentally hide some error etc.
