### ISSUE TITLE
Mouse cursor might not be visible for the first time when switching VTs

### ISSUE THREAD

**Issue by blueyed** [awesomeWM/awesome#942]
I am using two X / awesome sessions on VT1 and VT2 typically, and sometimes the mouse is not visible when switching to the other session.

This might be related to monitor configuration having changed: just now it happened when switching from VT2 which has 3 screens to VT1 without any external screen.

The workaround is to switch back and forth, which usually fixes it instantly.

@psychon 
Do you have an idea what to print or where to hook into to debug this?
I assume I could look at some (root) window properties when that happens?!

I could imagine that this is some video driver / X session after all, too.

I've mentioned this in https://github.com/awesomeWM/awesome/issues/804#issuecomment-205496869 on Apr 4th, and it seems to have started back then.

**Comment by psychon** [comment]
Awesome doesn't really set the mouse cursor. Well, the `cursor` property on drawins and `root.cursor()` do set the cursor, but neither of these are touched on VT switch (awesome can't even notice VT switches, I think) and neither allow setting an invalid cursor.

I guess you'll have to report this upstream to the X server.

And no, there are no root window properties to look at. The cursor apparently can't be queried (`xwininfo` doesn't show anything). The only semi-good idea that I have is: When you move the cursor to another window (and that window displays another cursor), does this make the cursor visible? E.g. you could do `echo 'root.cursor("start")' | awesome-client`, check that now your root window and wibox really have different cursor, then cause this bug and then blindly move the mouse around in the hope that this makes a difference (= the cursor suddenly appears).

Still, the bug would be in the X server (we don't change the cursor on mouse enter events).

**Comment by psychon** [comment]
Some thing that you might try: Start a "plain X session" (no window manager, no nothing (well, perhaps just a terminal?)) and check if you can reproduce the issue there.

**Comment by blueyed** [comment]
> echo 'root.cursor("start")' | awesome-client

"start" appears to be invalid?!  I've tried it with "watch", without success.

> 2016-06-06 11:58:18 [string "root.cursor("start")"]:1: W: invalid cursor start

When moving the pointer focus changes and wibox tooltips appear.  It's just that it's not visible.
