### ISSUE TITLE
Remove xproperty support

### ISSUE THREAD

**Issue by psychon** [awesomeWM/awesome#947]
As far as I remember, the idea for the xproperty code was to save some state across restarts. This was wanted because awesome restarted on RANDR changes. Now that awesome no longer does this, the main motivation for the xproperty code is gone and we are left with a big chunk of code. As a simplification of the code base I thus propose to remove this again.

What use does this code still have in your eyes? Why should it be kept? How likely is it that things will work correctly for this use case? (E.g. saving state across restarts will be a rarely tested feature and thus bugs won't be caught.)

**Comment by blueyed** [comment]
I am using a custom property for a safe-kill function:

```lua
-- Kill client, asking for confirmation, if indicated by X property.
-- This is used from Zsh to indicate if a program is running, and
-- works around URxvt not having support for it.
-- It uses a delay of 1-2 seconds after Zsh has indicated that no program is
-- running anymore, preventing to close a window accidentally.
local safe_kill_client = function(c)
    local prop = c:get_xproperty('my_confirm_client_kill')
    -- 1: confirm
    -- otherwise: seconds since epoch when confirmation has been turned off.
    if prop and (prop == 1 or ((prop + 2) > os.time())) then
        local prompt = c.name and 'Quit "' .. c.name:gsub('"', '\\"') .. '"?' or 'Quit?'
        if not confirm_through_rofi(prompt) then
          return
        end
    end
    c:kill()
end
```

This property gets updated from the shell config then.

It is meant to ask for confirmation when killing a urxvt instance with a running program in it.

**Comment by psychon** [comment]
Hm, ok. Should we allow Lua to query and watch-for-updates arbitrary properties? Right now we enforce some awesome-specific prefix.
Also, I guess it could be nice to query "is a window floating" from outside of awesome... This means the code stays.
