### ISSUE TITLE
Switch to codecov

### ISSUE THREAD

**Issue by psychon** [awesomeWM/awesome#952]
Based on https://github.com/awesomeWM/awesome/pull/936#issuecomment-223718847, I assume that @blueyed wants to switch us from coveralls.io to codecov.io (and I have to say there web page looks way more awesome). And apparently they even have working Lua support out of the box!
I'm opening this issue for tracking that and so that we have a place for discussion.

So:
- Anyone against this?
- @blueyed Do you want to do this? Should I look into it?

**Comment by blueyed** [comment]
Thanks for listing to my complains.. :)

I don't want to do this myself though currently.
I think we could maybe have both services at the beginning to see how they compare.

**Comment by psychon** [comment]
I can make things work on codecov like this: https://github.com/awesomeWM/awesome/compare/master...psychon:codecov2
The result can be found here: https://codecov.io/gh/psychon/awesome/branch/codecov2 (is this link public? I don't know)

The problem is that this breaks coveralls integration. For coveralls via are using magic in luacov-coveralls to merge the results from the different runs together (unit tests and "sample tests" use the files in the source dir, integration/functional tests use the built result). For codecov, I just upload the data after each test (this even allows to tell where the coverage came from: unit/functional/sample test; however I didn't find this in the UI yet).
Perhaps we can somehow make both work, but right now I don't know how.

**Comment by blueyed** [comment]
It seems like we could still have one build tracking coverage for codecov, and another for coveralls?!

**Comment by psychon** [comment]
Thanks, that's a really good idea. Done. :-)

**Comment by psychon** [comment]
Also: Found the button in coverall's web interface to disable the comment posting. Now it never leaves a comment.
