### ISSUE TITLE
awful.wibar() becomes transparent when set bgimage

### ISSUE THREAD

**Issue by funeralismatic** [awesomeWM/awesome#954]
```
panel[s] = awful.wibar({
	position = "top",
	screen = s,
	height = 40,
	opacity = 1.0,
	ontop = true,
	bg = beautiful.color.black,
	bgimage = "/home/funeralismatic/.config/awesome/themes/my/img/panel/bg.png"
})
```

File exists.

**Comment by psychon** [comment]
Sigh. @funeralismatic This should cause errors and break painting of the wibar. You don't have anything like this? Nothing on awesome's stderr?

The problem: `wibox.drawable:set_bgimage` just saves its arguments in the drawable. The actual redrawing code then does `cr:set_source(cairo.Pattern.create_for_surface(self.background_image))`. So nothing ever turns the string into a cairo Surface and thus `create_for_surface` should throw an error complaining "the argument is not a surface". Apparently this never worked.

**Comment by psychon** [comment]
Possible patch:
```diff
diff --git a/lib/wibox/drawable.lua b/lib/wibox/drawable.lua
index 1f2c038..579fc0f 100644
--- a/lib/wibox/drawable.lua
+++ b/lib/wibox/drawable.lua
@@ -237,6 +237,9 @@ end
 -- as arguments. Any other arguments passed to this method will be appended.
 -- @param image A background image or a function
 function drawable:set_bgimage(image, ...)
+    if type(image) ~= "function" then
+        image = surface(image)
+    end
 
     self.background_image = image
     self.background_image_args = {...}
```

**Comment by funeralismatic** [comment]
>This should cause errors and break painting of the wibar. You don't have anything like this? Nothing on awesome's stderr?
Nope. If this were so, I wouldn't report this bug.

>Apparently this never worked.
Lol, ok.

**Comment by funeralismatic** [comment]
>Possible patch:

Your patch work fine. Thanks.

**Comment by psychon** [comment]
Sorry that I only come back to this now. The following change should make the bgimage work in the way you want it to work: https://github.com/awesomeWM/awesome/pull/994/commits/7f74c7c859234452aaf31ab48be0af351c47663d
