### ISSUE TITLE
The signal and property names documentation are incorrect 

### ISSUE THREAD

**Issue by Elv13** [awesomeWM/awesome#965]
While this is well known, there is no (?) issue to track this yet.

Some signals (http://new.awesomewm.org/apidoc/classes/client.html#Signals) have a leading `.` in front of them to avoid ldoc adding an unwanted prefix in front of the name (for example, turn the `manage` signal into `client.manage`. This is also true for properties, but we don't add any prefix, so for example, a background property is displayed as `wibox.container.background.widget` instead of `widget`.

There is some possible solutions for this
- Add an hardcoded prefix like `DOC_AUTO_REMOVE` then use sed in a post-processing script to remove all of them (with the dot). This is easy enough, but a really bad hack.
- Fix `ldoc`. However, `ldoc` doesn't seem to be developed anymore, so I am not sure adding new code will be welcome.

Any other ideas?

**Comment by cmertz** [comment]
Hope my unqualified opinion is welcome:

Harmonizing the client signals with the other ones (e.g. client::focus) would incidentally eleminate the first point.

There seems to be interest in a new `ldoc` release at https://github.com/awesomeWM/awesome/issues/965 (if i got the right repo)

**Comment by psychon** [comment]
> Harmonizing the client signals with the other ones (e.g. client::focus) would incidentally eleminate the first point.

Sounds like a big API break just because of a documentation tool. Also, the signal is emitted on clients, having a "client" prefix on its name doesn't add any value. I don't like that idea, sorry.

**Comment by Elv13** [comment]
Moving to 4.1. It wasn't even documented in older releases (there was an incomplete wiki page). It can be fixed later. For now, there is a comment in the page warning about the issue. If you want I can add a comment in each and every affected signals (using a @FOO@ cmake variable to make it easier to remove later).

**Comment by psychon** [comment]
Removing milestone since having a release blocked by this basically means having no release (no fix in sight).
