### ISSUE TITLE
undefined reference to symbol 'round@@GLIBC_2.2.5

### ISSUE THREAD

**Issue by nasedo** [awesomeWM/awesome#969]
When trying to build awesome (GCC 6.1.1) from git I'm getting the following errors:
`/usr/bin/ld: CMakeFiles/awesome.dir/mouse.c.o: undefined reference to symbol 'round@@GLIBC_2.2.5'`

Reverting commits 9991f9cc and 5ebe073c makes the build possible but then when running a red message window often appears:
`(integer expected, got number)`

**Comment by psychon** [comment]
How are you building awesome? Anything special? What system are you on (Which distro, any special packages, ...)? Could you do a fresh build, but with `make V=1` so that all the arguments that are passed to the compiler are shown (and of course provide the resulting output somehow)?

**Comment by nasedo** [comment]
Weird, apparently this happens only if linking to luajit. I'm on Arch Linux and this [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=awesome-luajit-git) describes the build process. It boils down to [this](https://aur.archlinux.org/cgit/aur.git/tree/0001-add-luajit.patch?h=awesome-luajit-git) patch and:
`cmake -DCMAKE_INSTALL_PREFIX=/usr -DSYSCONFDIR=/etc -DLUA_LIBRARIES=/usr/lib/libluajit-5.1.so`
[Here](http://ix.io/Ubi) is `make VERBOSE=1` output.

**Comment by psychon** [comment]
Hm, seems like `FindLua51` does indeed make us link against `libm`. For now I'd say that the `PKGBUILD` from AUR is broken since it makes awesome fail to build. However, we really should check for `libm` ourselves if we use it (and of course this isn't actually easy with CMake... why are we using CMake again?).
