### ISSUE TITLE
Set icon size in system tray

### ISSUE THREAD

**Issue by lunix4** [awesomeWM/awesome#971]
In awesomeWM, look like system tray icon size equal to wibox size. I wonder is there a way to manual set the size of icon in system tray and padding between icons, in order to make them look better, thanks !

**Comment by psychon** [comment]
Depends on what exactly you want to do.

You can add a margin around the systray by replacing `right_layout:add(wibox.widget.systray())` in your `rc.lua` with `right_layout:add(wibox.layout.margin(wibox.widget.systray(), 3, 3, 3, 3))` (Order of arguments is left, right, top, bottom).

If you really want to force a certain size, you can use:
```
local systray = wibox.widget.systray()
systray:set_base_size(10)
(and then replace right_layout:add(wibox.widget.systray()) with right_layout:add(systray()))
```

For padding between icons: Use a git version of awesome (this is not in 3.5, it seems) and set `systray_icon_spacing` in your theme to e.g. 4.

Does this help you?

**Comment by lunix4** [comment]
thanks for your reply, that helped me a lot

**Comment by AdsonCicilioti** [comment]
How align vertically @psychon ??

**Comment by psychon** [comment]
@AdsonCicilioti sorry, there is only a single "me" and I am unaligned.

**Comment by dranzer9944** [comment]
it only apply on one icon only.  i want for all

**Comment by Aire-One** [comment]
Hello, @dranzer9944, please open a new issue with your particular problem.
