### ISSUE TITLE
[question] How to isolate mouse in multi monitor system

### ISSUE THREAD

**Issue by lvsv** [awesomeWM/awesome#973]
Hello,

I have a two monitors configuration (`xrandr --output DP1  --output LVDS1 --mode 1366x768 --pos 0x0 --rotate normal --output VGA1 --mode 1920x1080 --above LVDS1 --rotate normal`), a keybinding to switch between of them, and a strong wish to disable switching between screens by mouse movement. 

it is very annoying, to lose application's focus when mouse moved to another screen. 

How can i do this?

**Comment by psychon** [comment]
The default config has the following part for this:
```lua
-- Enable sloppy focus
client.connect_signal("mouse::enter", function(c)
    if awful.layout.get(c.screen) ~= awful.layout.suit.magnifier
        and awful.client.focus.filter(c) then
        client.focus = c
    end
end)
```
If I understand you correctly, you want the following:
```lua
-- Enable sloppy focus
client.connect_signal("mouse::enter", function(c)
    if awful.layout.get(c.screen) ~= awful.layout.suit.magnifier
        and awful.client.focus.filter(c)
        and (not client.focus or client.focus.screen == c.screen) then
        client.focus = c
    end
end)
```

**Comment by Elv13** [comment]
Awesome does not support locking the mouse into a single screen. There might be external utilities to do that. If you wish to implement it in Awesome.You could add a 1px wibox on each side and hope it will be detected when the mouse cross it (it might not if you move it too fast). then open a mousegrabber if no button are pressed. The mousegrabber as to quit when it detect the mouse is moving in the right direction again. Else, it just cancel the x movement. This is a terrible hack. An external utility is a better idea.
