### ISSUE TITLE
Issues with xrandr on current master ( d3ccd04291da0f6e5b3b10d7c98b2db80f6573ca )

### ISSUE THREAD

**Issue by alxchk** [awesomeWM/awesome#975]
Just updated and get next issue. When screen is addedd/removed there are next errors:
error: /usr/share/awesome/lib/awful/tag.lua:1127: attempt to index field 'screen' (a nil value)

After that awesome becomes unusable until restart.

**Comment by Elv13** [comment]
Have you upgraded your rc.lua to support multiple screens? This change is required since a couple of months. If you use an older config without native multi-screen support, Awesome wont restart anymore, so there will be errors/issues.

Until recently, Awesome would restart itself when the screen configuration changed to keep things simple. Obviously, simple wasn't good enough for many users, so now Awesome has real multi-screens support.

You can take a look at the current rc.lua to see the required changes.

**Comment by alxchk** [comment]
I almost managed to fix my config, but some things are not clear for me. In my setup I have two monitors - LVDS laptop and big Dell. When I plug my laptop to dock, big monitor activates using 
`/usr/bin/xrandr --output HDMI3 --left-of LVDS1 --brightness 1 --primary --auto`
And when I remove it:
`/usr/bin/xrandr --output HDMI3 --off`
In my old setup I had status bar only on primary screen. So I made something like this:

```
awful.screen.connect_for_each_screen(
   function(s)
.....
      if s.index > 1 then
	 return
      end

      bottombox = awful.wibar({
	    position = "bottom",
	    screen = 1,
	    height = 16
      })
 .....
end)
```

The problem with this code, that after changing primary screen wibar will not move by itself. For example my primary screen during awesome initialization was HDMI3. Wibar is there. Then I detach it. LVDS becomes primary screen. No wibar on LVDS. As far as I understand that happens because screens are not reinitialized. Only new screens initialized by those callbacks.

So, my question is - what is the proper way to migrate my old setup to new architecture?

**Comment by alxchk** [comment]
Looks like the problem is more generic. With old behavior primary screen always had index==1.

**Comment by alxchk** [comment]
So, I tried to manually handle "primary_changed". Looks like it doesn't fired when I remove primary screen. I tried also screen::remove event without any success =\

**Comment by Elv13** [comment]
Meh, I have an unit test for moving the wibar... But I use a single screen, so there is little "actual" testing for this (and the code is very recently rewritten). What I can say is that the test pass and it should work. However I will have to find a "real" second screen to try it. Can you please test with the default config?

**Comment by alxchk** [comment]
Default config is not equal to my setup. In default config there is just tray which is moved across the screens. And to do that there are some workarounds, as I see. But, anyway. Even tray (with default config) is not rendered from time to time after primary screen disconnected.

It will be very good to have property XXX.screen = "primary", to handle this automatically. And until then to have nice option - restart awesome on screen reconfiguration :)

**Comment by psychon** [comment]
> It will be very good to have property XXX.screen = "primary", to handle this automatically.

`XXX.screen == screen.primary`

> And until then to have nice option - restart awesome on screen reconfiguration

`for _, sig in ipairs{ "added", "removed", "primary_changed" } do screen.connect_signal(sig, awesome.restart) end`

**Comment by psychon** [comment]
What is this issue actually about? To me this sounds like "awesome changed things and now my config needs to be updated". Am I wrong?

**Comment by alxchk** [comment]
You are right. Your post with restart works for me.
