### ISSUE TITLE
Floating windows end up off-screen if left monitor is turned off

### ISSUE THREAD

**Issue by Keridos** [awesomeWM/awesome#976]
When turning off my left monitor in my dualhead with "xrandr --output HDMI3 --off" all the windows are shifted 1920 pixels (my monitors x resolution) to the right. That unfortunately includes the windows on the right monitor that after that are inaccessible because they are outside of the shown space.

Edit by Elv13: Keridos say he can reproduce the issue with both 3.5 and master

**Comment by psychon** [comment]
For 3.5, the default config does: `if not startup then [...] awful.placement.no_offscreen(c) [...] end`
Removing the `startup`-check here would force windows to be on-screen as wanted.

For master: Uhm.... We will have to provide "something" for screen changes. Should rules be re-processed on screen changes? That's likely not what users want. Some special something to move (floating) clients to their new screen? (They are assigned a new screen when their tags are deleted; clients without any tags are evil anyway (tm))

**Comment by psychon** [comment]
Oh and: @Keridos You should still be able to focus clients via the tasklist. Then you can un-float them, which should move them back into the visible area. :-)

**Comment by Elv13** [comment]
I guess a global `no_offscreen` pass when screen are resized or removed would not hurt that much, but this doesn't seem to be the issue, as @Keridos claim it happens with 3.5. This seem improbable given the "manage"->no_offscreen call.

**Comment by psychon** [comment]
@Elv13 3.5 does the `no_offscreen`-call only for clients that are managed after startup; during startup it is skipped (and the code tries to keep the current window position).
So:
- Window becomes offscreen because an output is disabled
- Awesome restarts, window still has the same position
- During the new startup, `manage` is emitted with the `startup`-argument being `true`, so window still has the same position

**Comment by blueyed** [comment]
With only having skimmed this issue I think I'm affected by this as well with an external monitor when unplugging: especially `arandr` (floating) will end up with Y above the internal screens height, after disabling the other output (which is above).
IIRC a restart fixes this, because then the `no_offscreen` filter kicks in.

**Comment by psychon** [comment]
To have some progress: Should we add the following to the default config? If not, why? (E.g. "because this is some ugly and long code")
```lua
screen.connect_signal("removed", function(s)
    local cls = client.get(s)
    gears.timer.delayed_call(function()
        for _, c in pairs(cls) do
            if c.valid then
                awful.placement.no_offscreen(c)
            end
        end
    end)
end)
```

**Comment by blueyed** [comment]
@psychon 
OK with me.  But does it have to be a delayed call?

**Comment by psychon** [comment]
During the callback the screen is still valid. We want to wait until the screen is gone.

**Comment by blueyed** [comment]
> Alternatively we would have to teach `no_offscreen` something like "please ignore the screen `s`".

I like that.

Also: why is `cls` set before the delayed call already?  Is this on purpose?

**Comment by psychon** [comment]
`cls` is set earlier, because I only want to "fix" clients which were on the screen that is removed. I can only get this list of clients before the screen is actually removed.

**Comment by psychon** [comment]
Actually... I think the issue is not that much that some monitor is turned off. The problem is that some monitor is moved.

Does someone want to test the following code? When a screen is moved, all of its clients are moved to follow it.
```lua
screen.connect_signal("property::geometry", function(s, old_geom)
    local geom = s.geometry
    local xshift = geom.x - old_geom.x
    local yshift = geom.y - old_geom.y
    if xshift == 0 and yshift == 0 then
        return
    end
    for _, c in ipairs(client.get(s)) do
        local cgeom = c:geometry()
        c:geometry{ x = cgeom + xshift, y = cgeom + yshift }
    end
end)
```

**Comment by Keridos** [comment]
I am currently not able to test this, sorry, completely reinstalled my linux systems from gentoo to arch.

**Comment by webknjaz** [comment]
Correction to @psychon's last snippet.
I've got `attempt to perform arithmetic on local 'cgeom' (a table value)` error.
So I assume the fix is:
```diff
 screen.connect_signal("property::geometry", function(s, old_geom)
     local geom = s.geometry
     local xshift = geom.x - old_geom.x
     local yshift = geom.y - old_geom.y
     if xshift == 0 and yshift == 0 then
         return
     end
     for _, c in ipairs(client.get(s)) do
         local cgeom = c:geometry()
-        c:geometry{ x = cgeom + xshift, y = cgeom + yshift }
+        c:geometry{ x = cgeom.x + xshift, y = cgeom.y + yshift }
     end
 end)
```
