### ISSUE TITLE
Travis is not very stable as of late.

### ISSUE THREAD

**Issue by Elv13** [awesomeWM/awesome#982]
Some build passes, some build fails. I didn't investigate much, but I have seen the "build::passed" and "build::failed" change state for no apparent reasons.

```
-- All test passed!

-- Running tests again with coverage

-- Running tests/examples/awful/mouse/coords.lua...

Error: couldn't run config file /home/travis/build/awesomeWM/awesome/.luacov: line 4: $BUILD_DIRECTORY not set

CMake Error at tests/examples/CMakeLists.txt:162 (message):

  /home/travis/build/awesomeWM/awesome/tests/examples/awful/mouse/coords.lua

  A test failed, bye

Call Stack (most recent call first):

  tests/examples/CMakeLists.txt:238 (run_test)

  awesomeConfig.cmake:359 (include)

  CMakeLists.txt:17 (include)

```

I wont have time this week, nor the next. I should have some time the week after that, but if someone want to step in, it is quite obvious which commit broke this (and I have a big part of the partial blame for it).

**Comment by blueyed** [comment]
> it is quite obvious which commit broke this

Do you have a reference / more information regarding this?

**Comment by psychon** [comment]
I don't think I saw `$BUILD_DIRECTORY not set` before, but two builds in https://travis-ci.org/awesomeWM/awesome/builds/142325384 failed due to this (and another one failed because `Error: timeout waiting for signal in step 4/4 (@5).` in `test-screen-changes.lua`; let's see if restarting the builds fixes things there).

I'm not sure where this was introduced either.

**Comment by psychon** [comment]
It just occurred to me: "Not very stable" is wrong. Both builds with coverage information consistently fail, so they *are* stable. The only unstable build is (once again) the LuaJIT build where two functional tests randomly fail.

**Comment by psychon** [comment]
A fix for the part of this that is caused by the new luacov release is in #964, but afterwards coverage for `tests/examples/` seems to be missing. Perhaps I got some path wrong, or something like that?

**Comment by psychon** [comment]
I give up. Someone else can look into this. I just don't understand Travis.

Before https://github.com/psychon/awesome/commit/a39f5ff71e68fd705072f0763adb6900026ea6ec, the travis build output showed that the `$SOURCE_DIRECTORY` environment variable was passed on into `.luacov`: https://travis-ci.org/psychon/awesome/builds/143392915 Relevant output is
```
lib	/home/travis/build/psychon/awesome/.build-testing-gce-4796a659-90c2-49c5-ba40-28880012c0c5-x86_64-linux-gnu-4.8/lib/	source	/home/travis/build/psychon/awesome	magic	42
```

The above commit has some unrelated changes, but doesn't touch `$SOURCE_DIRECTORY`. Yet, the build for that commit showed that the value of the variable was lost: https://travis-ci.org/psychon/awesome/builds/143394520
```
lib	/home/travis/build/psychon/awesome/.build-testing-gce-5345d8ab-207b-4aea-8bea-f69c60718df3-x86_64-linux-gnu-4.8/lib/	source	nil
```

That makes no sense to me...

**Comment by psychon** [comment]
Apropos this issue: My guess is that the luacov support for `tests/examples` never worked properly. Lua always errored out when trying to load our `.luacov` settings. However, apparently `luacov` then continued with its default settings and things mostly worked.
So... the task at hand is to fix the code that was always broken. (And I think if I'd get that ***** environment variable through, everything should work fine (tm). However, some gremlin eats the variable on its way.)

**Comment by psychon** [comment]
Should the following also be tracked in this issue (random failure of some functional test):

https://travis-ci.org/awesomeWM/awesome/jobs/143437510

> test-screen-changes.lua
> [...]
> Error: timeout waiting for signal in step 4/4 (@5).

**Comment by psychon** [comment]
About the `test-screen-changes.lua` instability: The following "patch" (=hack) "fixes" this problem (the problem being: The client's titlebar keeps a reference to the deleted screen, because it isn't updated in-time for its new screen; the hack just forces the titlebar to update):
```diff
diff --git a/tests/test-screen-changes.lua b/tests/test-screen-changes.lua
index 7afb703..503ba68 100644
--- a/tests/test-screen-changes.lua
+++ b/tests/test-screen-changes.lua
@@ -60,6 +60,9 @@ local steps = {
     function()
         fake_screen:fake_remove()
 
+        require("awful.titlebar").hide(test_client1)
+        require("awful.titlebar").hide(test_client2)
+
         -- Now that the screen is invalid, the wibox shouldn't refer to it any
         -- more
         assert(mywibox[fake_screen].screen ~= fake_screen)
@@ -81,6 +84,8 @@ local steps = {
     -- Step 4: Everything should now be on the main screen, the old screen
     -- should be garbage collectable
     function()
+        require("awful.titlebar").show(test_client1)
+        require("awful.titlebar").show(test_client2)
         assert(test_client1.screen == real_screen, test_client1.screen)
         assert(test_client2.screen == real_screen, test_client2.screen)
```

**Comment by blueyed** [comment]
> because it isn't updated in-time for its new screen

Would it help to have some additional step in the test, so that the main loop gets run?
We could probably fix the test runner to trigger this always then, too?!

**Comment by psychon** [comment]
The main loop does run. The test runner uses timers to call the steps and in-between timer invocations, the normal main loop runs.

I think the problem is more like "something should trigger a repaint if a drawable is moved to another screen", or something like that...

**Comment by psychon** [comment]
Adding to 3.6 milestone, because this seems to be a genuine bug: We apparently have to force full redraws when a drawable moves to another screen (both by being moved and because a screen disappears).
